### ISSUE TITLE
Avoid using translatable error messages in test assertions

### ISSUE THREAD

**Issue by Inkdpixels** [lerna/lerna#1002]
While contributing #1000 we found that a recent commit added assertions for NPM error messages. E.g. in `test/ImportCommand.js` the spec `ImportCommand › import › errors without an argument` asserts the throwed error message.

This is sadly not that nice since the error message thrown is in the language of your OS, so in case your OS is set to a different language other than en-US, the contributor gets wrongfully failing assertions.

## Expected Behavior
The tests should not expect the systems language to be english.

## Current Behavior
The tests expect the systems language to be english, and if this is not the case they fail unexpectedly.

```
expect(received).toBe(expected)

    Expected value to be (using ===):
      "Not enough non-option arguments: got 0, need at least 1"
    Received:
      "Nicht genügend Argumente ohne Optionen: 0 vorhanden, mindestens 1 benötigt"
```

## Possible Solution
Do not assert the error message, or introduce an error code to the throwed Error Object instead

## Steps to Reproduce (for bugs)
1. Set your system language to anything other than en-US
2. Execute `npm test` in the lerna repository

## Context
I would like to contribute to lerna, but this makes it hard and less welcoming for newcomers.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | latest/master |
| `npm --version`  | 5.4.0 |
| `yarn --version` | --- |
| `node --version` | 8.3.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
I did not realize yargs automatically localized its output! That is very cool.

Like many mono-lingual Americans, I'm very bad at i18n, and I apologize for that. I definitely agree we should be making the assertions as robust as possible, which includes respecting localized output. I would appreciate any and all help you're willing to contribute toward this goal.

In this _particular_ case, we're probably over-asserting; we shouldn't be testing `yargs`' behavior, just that we've configured `yargs` correctly (it throws an error when the argument validation fails).

**Comment by Inkdpixels** [comment]
@evocateur  Had a thought about how to handle this, I guess if the point is to assert that the error originated from the `yargs` package, can't we just check if the throwed error object contains `yargs` in it's stack trace?

**Comment by evocateur** [comment]
I'm pretty sure yargs throws a specific sub-class of Error (YError?) that should give us a little more distinct properties to check. The stack might be useful, but feels brittle to me.

**Comment by evocateur** [comment]
Ah yes, we can just `expect(err.name).toBe('YError')`:
https://github.com/yargs/yargs/blob/master/lib/yerror.js

**Comment by Inkdpixels** [comment]
Awesome, are you already on it? Otherwise I think @kevroadrunner also was interested on picking this up.

**Comment by evocateur** [comment]
Go for it!

**Comment by cezaraugusto** [comment]
we are already passing `LC_ALL=en-us` to the test scripts to prevent this behavior (added in 2adab3c8b9d72f5a7fb8cc8bc4e8638529dd354a). I think this can be closed.
