### ISSUE TITLE
Please provide example of or link to a model project using fresh tech

### ISSUE THREAD

**Issue by haraldrudell** [lerna/lerna#1006]
There is little documentation for scaffolding a complete ECMAScript monolithic repository, in particular

* ESLint configuration in yaml, single file with root: true
* Separate Babel for build: **babel-preset-node8**
* src Babel for newish browsers
* Webpack configuration files single location for development and production
* babel-loader properly configured in terms of paths
* Jest
* npm as a build tool
* No fossil baggage like gulp,  5.1, Karma

I have looked for such projects, but everyone I have seen is stuck with some of their favorite 70s libraries

Thank you,

**Comment by haraldrudell** [comment]
The educated guess is that:
* **.eslintrc.yaml** goes next to **lerna.json**
* **babel-preset-node8** goes in the **babel** key of a **package.json** next to **lerna.json**
* **webpack.config.*.js** goes into every package that is an executable as part of **npm run build**
  * rules has the **babel-node** as:
    * test: /\\.js$/,
    * exclude: /node_modules/,
    * loader: require.resolve('babel-loader'),
    * options: {babelrc: false, presets: …
* **lerna**, **babel-preset-node8** installed by the **package.json** next to **lerna.json** instead of globally
* Lots of troubles I don't know about

**Comment by evocateur** [comment]
In general, any way in which an npm package can be constructed or arranged is supported by lerna. It's just calling npm, after all.

In practice, a lerna monorepo affords certain optimizations, mostly derived from centralization of test and build scripts. If every package has the same build, then just run it from the root with appropriate config targeting the leaf packages.

Personally, I am not a huge fan of boilerplates, as they have a tendency to be abused and do not promote basic npm skills acquisition. Politically, lerna doesn't have an opinion about what module bundler or test runner etc that one uses. I have a couple private lerna repos, for example, that don't use a module bundler at all (as they are 100% CommonJS).

Some random experiential opinions/observations:
- Use `babel-preset-env`, and put the relevant config in a root `.babelrc` (or `.babelrc.js`, if you're living on the edge with v7)
- yes, eslint from the root implies `.eslintrc.yaml` as a sibling of `lerna.json`.
- yes, `lerna` is a dev dependency of the root `package.json`. Never use globally-installed build tools, that's just deferred, inevitable pain.

An "examples" directory would be interesting, although an extra burden to maintain. They also run the risk of boilerplating, which I'm keen to avoid. The documentation of the pattern itself can always use improvement, and is heartily encouraged to pull-request. :)

**Comment by haraldrudell** [comment]
The desired state is that leaf-package-modules has no configuration other than **package.json**. Therefore:

The things that are recursively searched for up the parent directory tree should go in the directory where **lerna.json** is.

- **.eslintrc.yaml** goes next to **lerna.json**
- The **package.json** next to **lerna.json** has the **babel** configuration and all devDependencies like **babel**, **eslint**, **jest**, **rollup**, **webpack**, **yarn** and **lerna**
- **rollup.config.js** can be imported from a shared package-module or located using a file system reference to the **lerna.json** directory

**env targets: node: current** produces worse code than cherry-picking plugins say from **babel-preset-node8**. For certain targets, this is really important. Likewise **rollup** is much better than **Webpack** if your target allows for its use.

If there are other fossil devDependencies, it’s time to refactor.

**Comment by CapitanRedBeard** [comment]
@evocateur I understand your opposition to boilerplates and their tedency to be abused, however I think base examples with the standard tech that @haraldrudell would be highly helpful (Since this is not a trivial problem). Perhaps a good way to go about this is have a best practices section in the readme that we can keep minimal to avoid it being abused as the bible. 
I'm currently working through getting most of the above tech that is discussed in this thread to behave properly, if I'm able to get it working properly would you be opposed to PR to illustrate the basic use case for the good of the community? 

BTW appreciate your hard work on this module.

**Comment by evocateur** [comment]
@CapitanRedBeard I would appreciate a PR of docs demonstrating "best practice" setup examples!

**Comment by pravdomil** [comment]
this basic Babel setup works for me
```json
{
  "scripts": {
    "watch": "lerna exec --parallel -- babel src -d lib -w --presets @babel/preset-es2015,@babel/preset-stage-1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.40",
    "@babel/preset-es2015": "^7.0.0-beta.40",
    "@babel/preset-stage-1": "^7.0.0-beta.40",
    "@babel/cli": "^7.0.0-beta.40",
    "lerna": "^2.9.0"
  }
}
```

**Comment by dmk255** [comment]
@pravdomil Do you have that package.json in each of your leaf packages? It seems excessive to have lerna in each repo. Can these be shared at the root level instead?

**Comment by pravdomil** [comment]
@dmk255 that package.json is that one in your project root :)

**Comment by dmk255** [comment]
Thanks @pravdomil !

I've created an example repo that encompasses some of the recommendations enumerated here. 

https://github.com/dmk255/lerna-webpack-example

This repo includes:
1. Monorepo code splitting via lerna.
1. Babel building across packages (with react).
1. A package with a webpack config that has dependencies on packages in the monorepo.
1. Code splitting and asynchronous loading.

I've love to get some feedback and see if I'm using good patterns.  @evocateur I'm happy to submit a PR with the contents of this repo (or a documentation link) if you'd like.

**Comment by evocateur** [comment]
@dmk255 Thanks for taking the time to create a live example! Here are some observations:

* The root `lint` script should just call `eslint --cache --ignore-path .gitignore ./packages/*/src`
* No tests?! (`"test": "jest"` would be sufficient in the root, finding all the matching tests under `packages`)
* `lerna.json` already has `"useWorkspaces": true`, you don't need the `--use-workspaces` flag when calling `lerna bootstrap` in the `bootstrap` script
* `prebuild` doesn't need to be a `lerna exec`, just call `git clean -fdx packages`
* The `lerna exec --parallel -- babel src -d lib --config-file ../../.babelrc` call is duplicated twice in the scripts, I would extract that to its own script (`"build:babel"`?) and then you can call it from both places via `npm run build:babel` (with an extra arg for watch: `"watch": "npm run build:babel -- -w"`)
  * (I wouldn't use `yarn` to run nested scripts, it has troubles with concurrency in scripts)

**Comment by dmk255** [comment]
Thanks for the comments @evocateur - I've made some updates to address them. I'm happy to apply any other recommendations you have. It might be easier to take those comments to the PR though https://github.com/dmk255/lerna-webpack-example/pull/1 .

**Comment by MatejMazur** [comment]
Here is another example (it uses Parcel and Rollup):
https://github.com/MatejMazur/starter-monorepo
