### ISSUE TITLE
Install dependent packages issue

### ISSUE THREAD

**Issue by IhostVlad** [lerna/lerna#1010]
## Expected Behavior
Lerna should perform `npm install` for all bootstrapped packages, so that dependent modules will be placed in `node_modules` directory. In other words, the dependent packages should be in the same places they would be installed if the real installation was used instead of the Lerna usage.

## Current Behavior
Lerna iterates over all dependent packages, but modules have been installed into inner directories, instead of top-level `node_modules` folder for current bootstrapped package.

## Possible Solution
Now this issue can be walkarounded by perform manual `npm install` in every packages, and then only invoking `npx lerna bootstrap` for project root.
Maybe it can be automated by `npm install`-ing properly for each lerna-managed package

## Steps to Reproduce (for bugs)
1. Create Lerna project and some module (`MyMod`) inside it. Add to that module (`MyMod`) some dependenciy (`Dep`), which have following dependencies (`DepDep`).
2. After `npx lerna bootstrap`, dependency `DepDep` will be placed in `MyMod/node_modules/Dep/node_modules/DepDep`, but should be located in parent node_modules - `MyMod/node_modules/DepDep`, if it have not conflicting versions

## Context
Develop starter kit like `create-react-app` with `react-scripts`. In that case, if lerna project has some examples to using `react-script`-like package, it can't be bootstrapped, because recursive dependencies does not be installed into proper directory.

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0 |
| `npm --version`  | 5.3.0 |
| `node --version` | 8.3.0 |

OS: Linux 4.4.0-62-generic SMP x86_64 GNU/Linux /  Ubuntu 16.04.1 LTS

**Comment by chrisforrette** [comment]
I also have a need for this. My use case is that I'm using Lerna (2.1.0) to manage a bunch of simple packages for AWS Lambda functions and when I publish them I need to have the top-level dependencies included in the lower-level `node_modules/` before deploying to AWS. From looking through docs, I expected the `--nohoist` to do something like this but it doesn't seem to.

**Comment by evocateur** [comment]
Unless you're hoisting dependencies (`lerna bootstrap --hoist`), lerna _does_ run `npm install` in every package directory (with a little mangling of the package.json to avoid installing local siblings). I'm a bit mystified how you got this result, @IhostVlad. What's your `lerna.json` look like?

**Comment by evocateur** [comment]
@chrisforrette Why not just install the published modules into a separate directory? I really wouldn't recommend creating an artifact from lerna bootstrapped source directories, they're _not_ identical to how npm or yarn lays them out.

**Comment by chrisforrette** [comment]
@evocateur I started down that route as a work-around, but now that I think of it it makes a lot of sense that Lerna would require each dependency listed in each package's `package.json` for publishing—I just didn't need it for my use case. Thank you 🙂

**Comment by IhostVlad** [comment]
Closed due cover by more fresh and verbose issue - https://github.com/lerna/lerna/issues/1147
