### ISSUE TITLE
Problems with git tags

### ISSUE THREAD

**Issue by morpheus-87** [lerna/lerna#1012]
I have a small shell script, that created release packages and uploads them to GitHub - it is run, when there is a tagged commit.

## Expected Behavior

I would expect, that pushing the tags triggers a CI (like travis).

## Current Behavior

At the moment, the CI doesn't get triggered by the tagged commit and the shell script isn't run.

## Steps to Reproduce (for bugs)
1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.1.2",
  "packages": [
    "CanvasLink",
    "ImageCropper",
    "KeyboardNavigation",
    "ManifestButton",
    "MultiPageNavigation",
    "PhysicalRuler",
    "PiwikTracking",
    "ViewFromUrl"
  ],
  "version": "independent"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.1.2 |
| `npm --version`  | 5.4.1 |
| `yarn --version` | 1.0.1 |
| `node --version` | 8.4.0 |

| OS | Version |
| --- | --- |
| Xubuntu | 16.04.3 |

**Comment by evocateur** [comment]
This doesn't sound like a Lerna issue.
