### ISSUE TITLE
Publish a specific location

### ISSUE THREAD

**Issue by vitorcamachoo** [lerna/lerna#1013]
Before using Lerna, I was applying Babel into the project and it generates a distance folder and after Babel I copied the remaining files like package.jsom, etc.. the content of the folder was published with es5 code avoiding to have different paths in development and production mode.

I need to have this mechanism with Lerna but he doesn't provide any way to change the publish behaviour.

## Possible Solution

Maybe a possible solution is to store somewhere the publish location.

**Comment by evocateur** [comment]
Specify a [`main`](https://docs.npmjs.com/files/package.json#main) field in your package.json. This is how npm works, not lerna.
