### ISSUE TITLE
Detailed usage guide

### ISSUE THREAD

**Issue by christophercliff** [lerna/lerna#102]
Does this exist already? Would be helpful to see suggested workflow for setup, development and releases.

**Comment by hzoo** [comment]
We are working on 2.0 and rewriting the readme

**Comment by dalanmiller** [comment]
@hzoo How does `lerna` automatically detect packages within my repo? Does it just search one folder level deep for `package.json` files? 

I currently have a repo with three separate packages contained. Do I need to put their npm package names in the `package.json` `lerna` created at the root of the repository?

**Comment by thejameskyle** [comment]
No it can tell based on what you have in the `packages` folder.

**Comment by hzoo** [comment]
We have a better readme now, but we can add some more detailed guides - might be useful to add some gifs/instructions on a workflow like I showed at https://twitter.com/left_pad/status/733136037489315840

**Comment by hzoo** [comment]
@gigabo Do you want to start a PR for this? I think we can just write the setup/usage for a few scenarios - maybe the one yall are using in react-server (independent mode, fixed mode, publishing, canary, etc)

**Comment by thejameskyle** [comment]
I think our docs mostly cover it at this point for this issue to be closed. Docs are always going to need improvement, don't need to leave an issue open forever about it.
