### ISSUE TITLE
bootstrap --use-workspaces does not trigger lifecycle scripts 

### ISSUE THREAD

**Issue by Quramy** [lerna/lerna#1021]
Hi. I've attempted Lerna v2.2.0 and yarn v1.0.2's workspaces feature and it seems that `--use-workspaces` option obstructs packages' lifecycle scripts. 

## Expected Behavior

`lerna bootstrap --use-workspace` triggers `prepublish` and `prepare` script in each package.

## Current Behavior

Bootstrap command does not run lifecycle scripts.

```text
yarn run v1.0.2
$ "/Users/yosuke/workspaces/javascript/lerna-yarn-workspaces-example/node_modules/.bin/lerna" "bootstrap"
lerna info version 2.2.0
lerna info Bootstrapping 2 packages
lerna info hoist Finished installing in root
lerna success Bootstrapped 2 packages
```

For now, I execute `lerna run prepublish` explicitly...

## Steps to Reproduce (for bugs)

1. clone https://github.com/Quramy/lerna-yarn-workspaces-example
2. exec `yarn run lerna bootstrap`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.2.0",
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "1.0.0"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.2.0 |
| `npm --version`  | 5.4.2 |
| `yarn --version` | 1.0.2 |
| `node --version` | 8.1.3 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.6 |

**Comment by alex-pex** [comment]
Is ```lerna bootstrap``` still useful in most yarn workspace scenarios? I used lerna to install all packages and symlink between them, but now with yarn workspace I don't see what ```lerna bootstrap``` does but yarn doesn't.

I'm still using lerna to run commands on all packages.

**Comment by nhducit** [comment]
Change this line "useWorkspaces": true ==>false,
I have a similar issue, after turn off `useWorkspaces` options, it works.
https://github.com/lerna/lerna/issues/1014

**Comment by evocateur** [comment]
`lerna bootstrap` when `useWorkspaces` is enabled just calls `yarn install` once in the root. If the lifecycle scripts aren't being called, that's an issue with yarn, not lerna.
