### ISSUE TITLE
Bootstrap hangs with --hoist and --nohoist=react-native

### ISSUE THREAD

**Issue by connectdotz** [lerna/lerna#1022]
lerna bootstrap hung when using both hoist and nohoist, which basically triggered multiple concurrent npm installs during `installExternalDependencies`.

suspect it is a concurrency issue, tried `--concurrency 1` and it worked.

## Expected Behavior

bootstrap should not hang. 

## Current Behavior

bootstap hung.

## Possible Solution

while reducing concurrency to 1 worked, it removes all the (current and future) parallel optimization, therefore, might not be ideal. 

Looking at the code, I think a more precise and still minimal impact fix might be to turn `_async2.default.parallelLimit` to `_async2.default.series` at the end of BootstrapCommand.js  installExternalDependencies ([line 509](https://github.com/lerna/lerna/blob/master/src/commands/BootstrapCommand.js#L509)), where it tries to execute all the actions.

## Steps to Reproduce (for bugs)

see the [test project](https://github.com/connectdotz/lerna-concurrency-bug), which has 3 out-of-box react, react-native packages inside.

1. run `npm run bs` to kick off the bootstrap that will hang. (this one runs with concurrency 4)
2. change the concurrency to 1 in lerna.json, and run `npm run bs` again, it should finish successfully.
3. you can try changing the concurrency back to 4, and make the code change in lerna's BootstrapCommand.js `installExternalDependencies` as  suggested above, it should work as well.

(this is a simple fix, just want to make sure I didn't miss anything obvious before submitting the PR).

<details><summary>lerna.json</summary><p>

```json
{
    "lerna": "2.2.0",
    "packages": ["packages/*"],
    "commands": {
        "bootstrap": {
            "hoist": true,
            "nohoist": ["react-native"],
            "concurrency": 4
        }
    },
    "version": "0.0.0"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.2.0 |
| `npm --version`  | 5.4.2 |
| `yarn --version` | n/a |
| `node --version` | v8.4.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.6 |

**Comment by evocateur** [comment]
Is there any particular reason you're not hoisting `react-native`? (I've never used it, so I'm missing context)

**Comment by connectdotz** [comment]
sorry for the late reply. 

react-native doesn't follow symlink, therefore we need react-native to stay in the package thus nohoist.

**Comment by goodmind** [comment]
any solution?

**Comment by connectdotz** [comment]
we are no longer using lerna + npm... switched to yarn and uses its native [nohoist](https://yarnpkg.com/blog/2018/02/15/nohoist/) instead.
