### ISSUE TITLE
[Question] include changelog content in the tag release notes (as lerna does)

### ISSUE THREAD

**Issue by esakal** [lerna/lerna#1023]
I love using Lerna, it simplify the monorepo devop and does all the heavy lifting for you. Thanks for your valuable work :)

I would like to include the change log of the new version in the release notes as done in [lerna releases](https://github.com/lerna/lerna/releases). at the moment our releases are very vague as can be seen in our [monorepo kaltura-ng](https://github.com/kaltura/kaltura-ng/releases).

The motivation behind my question is to make github releases more effective and also to allow  using service like [sibbell.com](https://sibbell.com) which is extremely useful.

I reviewed the [publish command](https://github.com/lerna/lerna/blob/master/src/commands/PublishCommand.js) and lerna codebase yet failed to find how it is done.

also, another question about the manual changes in change log file: What is the right flow (if exists) to fix the changelogs.md files before publishing the packages?

Thanks!

**Comment by evocateur** [comment]
Our releases are pretty low-tech, literally copy+pasted from the output of [lerna-changelog](https://github.com/lerna/lerna-changelog):
```sh
npm i -g lerna-changelog
GITHUB_AUTH=$(cat ~/Dropbox/GITHUB_AUTH.txt) lerna-changelog | pbcopy
```
Which is, of course, the same output I copy+paste into the `CHANGELOG.md`. (Sometimes I edit it for brevity, and often add bloggy bits at the beginning).

----

As for automating changelogs with lerna, `lerna publish` currently supports [conventional-commits](http://conventionalcommits.org/) (via the `--conventional-commits` flag or `"conventionalCommits": true` lerna.json config), which creates/updates `CHANGELOG.md` files on a per-package basis, requiring adherence to the angular commit convention. It has some rough edges, but it covers the 80% case for most people.

Unfortunately, we do not have any other extensibility for "operations during publish" at this time.

**Comment by lostintangent** [comment]
@evocateur Stupid question, but what is the guidance around `lerna publish ---conventional-commits` vs. `lerna-changelog`? I'm loving the conventional commits workflow, but I like the way that `lerna-changelog` allows you to customize the changelog format a bit. Is the desire to continue iterating on `lerna publish ---conventional-commits` to fill in that additional 20% of scenarios? Thanks!

**Comment by evocateur** [comment]
There are no stupid questions! (Only scatter-brained maintainers :D)

My ultimate goal is to use lerna to manage lerna, ideally with conventional commits. I’m stuck on Bitbucket for most of my internal lerna usage, so bringing the `--conventional-commits` experience up to par is the direction I would like to go in, definitely.

**Comment by lostintangent** [comment]
Beautiful! Thanks so much for confirming that. I’m currently migrating some projects over to Lerna, and I’ve been trying to rationalize the various options (due to my unfamiliarity), so it’s super helpful to know that the Commitizen + Lerna combo is the “future proof” workflow for conventionally committing/publishing monorepos.

**Comment by am80l** [comment]
I havn't tried, but is there some maybe way to use the conventional releaser-tools to accomplish this? 

https://github.com/conventional-changelog/releaser-tools

**Comment by evocateur** [comment]
Possibly! I get by with a cheesy manual copy+paste after the root changelog is written, but automation would be nice.

**Comment by hbetts** [comment]
The releaser-tools, as written, don't support mono-repositories. They fetch all commits from the current git project and generate a changelog from those.

However, the underlying libraries used by the releaser-tools do support sub-packages (specifically Lerna projects). So it may be possible to use the releaser-tools on a mono-repository after a slight modification to take a package name or directory path. 

Sorry for the slight tangent there.

I also like this idea, and I would love to have it for our `conventional-changelog` org. I receive quite a few support questions that are answerable by indicating where our changelog files are.

**Comment by Igmat** [comment]
I use [this script](https://github.com/Igmat/metaf/blob/master/scripts/publishGithubRelease.js) in my two lerna based projects: [BaseT](https://github.com/Igmat/baset) and [MetaF](https://github.com/Igmat/metaf).

Obviously it isn't generic enough solution, but GitHub releases looks much better (see [this](https://github.com/Igmat/metaf/releases) and [this](https://github.com/Igmat/baset/releases)) with, so it could be a good starting point for further improvements and adding such capability to lerna itself.

**Comment by Siilwyn** [comment]
This would be great to have!
For now a workaround I'm using is amending manually like:
```
git stash
lerna version --no-push
git stash pop
git add changelog.md
git commit --amend
git push
```

Would be nice to be able to include staged changes.

**Comment by void-kuangyi** [comment]
@evocateur I use conventional commits with lerna, so it generates the changelogs under each package, i wonder whether lerna has the capabilities of merging all the changelogs under each package into one changelog and it can be used as release notes under the `release` tab in github after each publish? 

Also, a second question is what does `--create-release` when run `lerna version --conventional-commits --create-release github`? I can not find more documentation about it and can not run it successfully either.

**Comment by xthilakx** [comment]
@void-kuangyi It maintains changelog in leaf package, if `version` is set to `independent` in lerna.json. By default, it maintains changelog in the root directory of your repo.

**Comment by elibolonur** [comment]
Is there any best practice to apply this? Trying to figure out how to include change logs in release notes for 4 different packages in a monorepo but can not really find a proper way to do it.

**Comment by JamesHenry** [comment]
As noted the resolution to this issue was to use the `--create-release` flag
