### ISSUE TITLE
How to detect which package has a circular dependency?

### ISSUE THREAD

**Issue by FezVrasta** [lerna/lerna#1024]
Sorry if I'm not following the template but I'm not reporting a bug nor requesting a feature.

I'm getting this error now that I enabled the Yarn workspaces but I don't know how to find out which packages are genereting the circular dependency.

```
lerna WARN ECYCLE Encountered a cycle in the dependency graph. This may cause instability!
```

Is there any way to find it out?

**Comment by evocateur** [comment]
If you're using `lerna bootstrap`, add `--loglevel=silly` and it might become apparent? It's hard to say, since the warning itself could use improvement (although how much, I'm not certain, as it is a complex part of the codebase).

Grepping packages for references to other packages should be sufficient to identify circular dependencies, however. A -> B -> A is the sort of thing this warning is (attempting to) highlight.

**Comment by FezVrasta** [comment]
Thanks for the tip! Unfortunately it doesn't provide any useful info :-(

```
❯ lerna bootstrap --loglevel=sillylerna sill input []
lerna sill flags { _: [ 'bootstrap' ], loglevel: 'silly', args: [] }
lerna verb rootPath /Users/federicozivolo/Acme/repos/stacks/ui-framework
lerna info version 2.2.0
lerna sill existsSync /Users/federicozivolo/Acme/repos/stacks/ui-framework/VERSION
lerna sill initialize attempt
lerna WARN ECYCLE Encountered a cycle in the dependency graph. This may cause instability!
lerna sill initialize successlerna sill execute attempt
lerna info Bootstrapping 16 packages
lerna sill installInDir ui-framework
lerna sill installInDir /Users/federicozivolo/Acme/repos/stacks/ui-framework/package.json
lerna sill getExecOpts { cwd: '/Users/federicozivolo/Acme/repos/stacks/ui-framework' }
lerna sill installInDir [ 'yarn', [ 'install', '--mutex', 'network:42424' ] ]
```

(it gets stuck there for several minutes)

I checked my dependencies manually but I couldn't find any circular dependency 😞

**Comment by evocateur** [comment]
Dang, sorry, I coulda sworn there was more verbose logging around those bits. If you're comfortable editing files under `node_modules`, [here](https://github.com/lerna/lerna/blob/54761ba26f8cb6d50d16a4c920d1a9594c19d6e9/src/PackageUtilities.js#L192-L199) is where that logging is from (in the transpiled output, `ECYCLE` is probably the easiest thing to search for). Maybe log `packages` and `batch` (after they are pushed on in that conditional)?

As I said, it's a very complex part of the codebase, I'm not even sure logging more detail is _possible_, given the nature of the comparison.

**Comment by FezVrasta** [comment]
Thanks, logging `packages` it points to a fork of `testcafe-reporter-datadog`, which has a devDependency to a custom eslint config we maintain in our monorepo.

But that dependent package doesn't have any dependency to any of our other lerna packages, so I'm not sure where the ECYCLE error comes from...

Is there anything I can do to help me (and the project) to debug the problem? Unfortunately I can't share the repository because it's a private one.

**Comment by FezVrasta** [comment]
Oh nevermind, found it out. The package was dependent on itself :-|

**Comment by evocateur** [comment]
Oops! I agree that we need better logging there, if possible. I'm not exactly sure what that logging is, but I'm glad you were able to resolve your warning.

**Comment by FezVrasta** [comment]
I created a PR to add some additional logging, I'm not sure how helpful can it be... I guess better than nothing
