### ISSUE TITLE
Lerna stops executing tests on certain package

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#1027]
I have a package without tests, but for consistency I want to provide a test command as a placeholder. The test command just executes an echo to the console. When I execute `lerna run test` it executes the tests on all packages until it reaches the mentioned package and it stops there. I don't know what Lerna 

## Expected Behavior
I want the echo message to be displayed and lerna continuing to the next package

## Current Behavior
All tests are executed until it reaches the package with the echo command on the test

## Possible Solution
I don't have a solution at this momment

## Steps to Reproduce (for bugs)
Here is the script that I have on the package.json of the mentioned package:

```
    "test": "echo --- This module is not supported at this time. You should update it to conform to the new notification spec. ---"

```

<details><summary>
</summary><p>

```json
{
  "lerna": "2.0.0",
  "packages": [
    ".",
    "src/*"
  ],
  "hoist": true,
  "registry": "https://tools.caseonit.com/npm",
  "commands": {
    "publish": {
      "conventionalCommits": true,
      "message": "chore: Publish"
    }
  },
  "version": "independent"
}
```
</p></details>

## Your Environment
Node 7

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0 |
| `npm --version`  | 4.1.2 |
| `node --version` | 7.7.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.6 |

**Comment by jenniesyip** [comment]
You have some syntax errors, try: 
```
"test": "echo \"This module is not supported at this time. You should update it to conform to the new notification spec. ---\" && exit 0"
```

**Comment by evocateur** [comment]
I'm not sure why the `---` stuff is in the echo, but @jenniesyip's solution is the appropriate one, here.

In any case, lerna isn't doing anything more than calling `npm run test` (which is the same as calling `npm test`), so if you can run `npm test` successfully from the package directory in question, lerna should be able to run the tests successfully.

**Comment by danielo515** [comment]
Hello @evocateur 
I don't see why the echo has typos. I can execute it on the console without problems

```bash
echo --- This module is not supported at this time. You should update it to conform to the new notification spec. ---
```
Also, if I go to the package directory and execute `npm test` the test runs and finishes without any problem. In fact, if I execute the following snippet it works

```bash
for d in $(ls packages)
do
(cd d && npm t)
done
```
it executes all the tests without problem. I expected lerna to be able to do the same.

Regards

**Comment by evocateur** [comment]
Ooh, thanks for confirming that. I am a bit stumped now, but at least it sounds like something we might be able to reproduce without trying to “trick” npm.
