### ISSUE TITLE
Hoist doesn't allow specific packages

### ISSUE THREAD

**Issue by natew** [lerna/lerna#1028]
Figured this would be talked about more if it were true, perhaps I'm just missing something.

## Expected Behavior
Lerna.json:

```
{
  "hoist": ["mobx"]
}
```

Should hoist just mobx.

## Current Behavior
Seems to ignore this setting and hoist everything.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.2.0 |
| `npm --version`  | 5.4.2 |
| `yarn --version` | 1.1.0 |
| `node --version` | v8.4.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
Does `lerna bootstrap --hoist mobx` work as expected?

**Comment by natew** [comment]
Did not, it still installs basically everything into top level folder for some reason.

**Comment by evocateur** [comment]
Huh, yeah, that is the behavior one would expect passing `--hoist` as a Boolean. Definitely a bug.
