### ISSUE TITLE
Make running scripts in sub packages less verbose.

### ISSUE THREAD

**Issue by akosyakov** [lerna/lerna#1031]
We keep dev dependencies in the root package to avoid managing versions in sub packages.  It brings to the issue that binaries are not installed in sub packages. In order to solve it, we have to run all commands from the root via lerna. It is fine except the fact that command is long to type, e.g.: `npx lerna run build --scope @theia/core --stream`.

It would be nice if there is a shorter way, e.g. `npx lerna @theia/core build`, which streams by default. If it causes collisions with existing commands, maybe use some special syntax, e.g. `npx lerna :@theia/core:build` ([gradle style](https://stackoverflow.com/questions/26509427/execute-gradle-task-on-sub-projects/26512462)).

**Comment by evocateur** [comment]
I've always felt the `--scope` flag, in addition to being a bit confusingly-named (contra `--scope` in almost any other npm context, which governs the `@scope` one uses to init a package with), should in most cases just be a series of trailing (optional) positional arguments. This is of course a breaking change. e.g.,

```bash
# lerna run <scriptName> [..pkgFilterGlobs] [--options...] -- <unparsed args forwarded to script execution>

lerna run build '@theia/core' --stream
# is equivalent to
lerna run build --stream '@theia/core'
```
The positionals are weeded out from flags, so ordering isn't especially important. I'm not sold on (but not 100% against) making `--stream` enabled by default, but that _can_ be added to `lerna.json` "durable" config that overrides the command defaults. You could omit `--stream` from `lerna run` with the following `lerna.json`:

```json
{
  "lerna": "2.0.0",
  "command": {
    "run": {
      "stream": true
    }
  },
  "version": "1.2.3"
}
```

The double-dash (`--`) would be _required_ in this case when passing _any_ arguments to the wrapped call, unlike today where you can get away with passing unknown positional arguments without halting the parser with the double-dash.

```bash
lerna run build --stream '@theia/core' -- --silent
# forwarded as `npm run build --silent`,
# the build script sees no additional args

lerna run build --stream '@theia/core' -- --silent -- --production
# forwarded as `npm run build --silent -- --production`,
# which means your build script only sees `--production`
```

### Alternatively...

...run your _whole_ build from the root. Jest makes it easy to run all the tests anywhere they might be, of course (same thing for eslint). Transpilers are a bit trickier, of course.

I only specify `devDependencies` in the root, as well. A lot of my internal projects use Rollup to build. The "normal" rollup CLI is most convenient to use at the package level, which is necessitates the verbose "run in a package but from the root" you describe. So I wrote a shared rollup config that spiders the tree and looks for conventional patterns based on standard npm fields and minor package-level rollup config overrides. I really need to get around to open-sourcing it...
