### ISSUE TITLE
How do I install a new npm package?

### ISSUE THREAD

**Issue by RinatMullayanov** [lerna/lerna#1034]
Hi.
I apologize in advance if the question is not executed according to the rules.
**Your project seems very cool, but I don't fully understand how to use it.**
I did not have enough information in your README.md.

I have 6 different repositories - 2 of them are general libraries, 4 are final web applications (SPA) using the 2 libraries mentioned earlier.
I did:
1. `lerna init --exact`
2. `lerna import` each of them
3. `lerna bootstrap`
4. **How do I add new npm packages to my Lerna repo now? 
Can I use `npm install`? If yes, where to execute these commands - at the root of the repository or in a specific package?**

## My Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.2.0|
| `npm --version`  | 5.4.2|
| `node --version` | v6.11.2|

| OS | Version |
| --- | --- |
| Windows 10 Pro | 1703 |

**Comment by nhducit** [comment]
In a specific package.

For example: I want to add `web` folder under `packages` [I use yarn workspaces with lerna](https://github.com/lerna/lerna#bootstrap)

- create `web` folder under `packages`
- run `cd web` <===
- run `npm init -y`
- run `yarn add react`

<img width="472" alt="screen shot 2017-10-01 at 11 49 50 pm" src="https://user-images.githubusercontent.com/4246176/31056877-40429b08-a703-11e7-974e-f3ee8140e2a7.png">

**Comment by RinatMullayanov** [comment]
@nhducit I thought that the whole point using Lerna and all dependences are installed in a root of a repository and are the general.

**Comment by RinatMullayanov** [comment]
@nhducit `lerna bootstrap` uses existing package.json in each packages, but How to add there new dependencies? 

I want to have one **node_modules** folder at the root. 
My 4 applications are built on the same template and use the same packages. Now each of them has its own **node_modules** folder, which is essentially duplicated.

And there are 2 common libraries.
Let's say there is a library A and a library B that depends on A.
And each of the 4 applications uses both library A and B simultaneously.

When I update the library A I need to make 5 almost identical PRs in each of the 5 repositories (library B and 4 applications) with the update `package.json` in each of them.
This is very tiring.

**Comment by nhducit** [comment]
@RinatMullayanov Please read this link for more detail information. 
https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/
```
Lerna is a tool that optimizes the workflow around managing multi-package repositories with git and npm. Internally it uses Yarn or the npm CLI to bootstrap (i.e. install all third party dependencies for each package) a project. In a nutshell, Lerna calls yarn/npm install for each package inside the project and then creates symlinks between the packages that refer each other.

Being a wrapper of a package manager, Lerna can’t manipulate the contents of node_modules efficiently:

Lerna calls yarn install multiple times for each package which creates overhead because each package.json is considered independent and they can’t share dependencies with each other. This causes a lot of duplication for each node_modules folder which quite often use the same third-party packages.
Lerna manually creates links between packages that refer each other after installation has finished. This introduces inconsistency inside node_modules that a package manager may not be aware of, so running yarn install from within a package may break the meta structure that Lerna manages.
Issues such as these convinced us, as package manager developers, that we should support multi-package repositories directly in Yarn. Starting with Yarn 0.28, we’re excited to share that we support such repositories under the Workspaces feature.
```

**Comment by RinatMullayanov** [comment]
@nhducit I don't understand - How can I add new package (modify package.json) in my applications (packages) in packages folder.
For example, I want to install - lodash.
Should I run `npm install lodash` in root? Why do I then need the Lerna? It would work without it.

**Comment by nhducit** [comment]
@RinatMullayanov when using lerna with yarn, if 2 or more of your packages use same dependency with same version. This dependency will be stored in root node_modules folder.
>Should I run npm install lodash in root?
if lerna force you install all dependencies in root folder. what happen if child packages ABC depend on `chalk 1.1.0` but child packages `DEF` depend on `chalk 2.0.0`?

> Why do I then need the Lerna? It would work without it (for external dependencies).
these questions you should ask yourself. I use lerna to share code between platforms e.g. react web and react native

I think you don't understand what is the problem lerna is trying to solve (please read lerna readme and the link i sent). If lerna doens't solve your problem then you don't need to use lerna.

Cheers

**Comment by evocateur** [comment]
@RinatMullayanov To create a new package in a lerna repo, the simplest path is using `npm init` (just like creating a "normal" npm package):

```bash
mkdir -p packages/my-new-package
cd packages/my-new-package
npm init
cd ../..
lerna ls
# my-new-package is now in the list of recognized packages
```

As for the meta-question, "why use lerna?": If you're not publishing npm packages to a registry (public _or_ private), I wouldn't recommend using lerna. There's no shame in relative imports.

**Comment by RinatMullayanov** [comment]
@evocateur I understand how to create a new package in a lerna repo.
I am publishing npm packages to my private registry.
I don't understand how to manage package.json in each own package.
If I have to do this manually using `npm install`, this is somehow strange ...

**Comment by RinatMullayanov** [comment]
@evocateur How to add a new dependency in `package.json` some package. If I using `npm install` npm itself modifies `node_modules` bypassing lerna and not just creates a line in dependence section in `package.json`.

**Comment by RinatMullayanov** [comment]
@evocateur I asked how to add dependencies to external packages (`lodash`,` webpack`).

**Comment by evocateur** [comment]
Right now the easiest way is to install it in the root, copy the dependency into the target package, and run `lerna bootstrap --hoist`. Even doing a direct `npm install` is fine, just bootstrap afterward and it should restore the symlinks.

**Comment by RinatMullayanov** [comment]
@evocateur Ok thanks. 
I think you should make the **README.md** more detailed. 
I would like that there was described the full workflow for working with **Lerna**.
Really only I had a similar question.

**Comment by shawnthye** [comment]
i am using lerna manage my libraries workspace, i have the same problem, so everytime i need to npm install in the specific library and lerna bootstrap.
Cheers

**Comment by marionebl** [comment]
@shawnthye there is `lerna add` now, e.g.:

```
lerna add a --scope=b # add b to packages/a
lerna add c --scope=d --scope=e 
```

**Comment by shanimal** [comment]
@marionebl i think you meant
> ```
> lerna add a --scope=b # adds a to packages/b
> ```

[docs Examples](../../../lerna/lerna/tree/master/commands/add#examples)
