### ISSUE TITLE
Top-level loglevel flag not respected in lerna.json

### ISSUE THREAD

**Issue by jadengore** [lerna/lerna#1035]
When I set `loglevel: "warn"` at top-level `lerna.json`, it is not respected by my Lerna commands.

## Expected Behavior

When `loglevel` is set in `lerna.json` at the top-level, it should respect that all of my commands share that loglevel configuration.

## Current Behavior

Lerna ignores the `loglevel` key at the top-level in `lerna.json`

## Possible Solution

Check implementation of flags in `lerna.json` and make sure that `loglevel` can be configured at the top level.

## Steps to Reproduce (for bugs)

1. Add `loglevel` at top-level to your `lerna.json`
2. Commands are not affected

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.2.0",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "loglevel": true
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.2.0 |
| `npm --version`  | 5.3.0 |
| `yarn --version` | 1.1.0 |
| `node --version` | 8.1.2 |

| OS | Version |
| Ubuntu | 16.10 |

**Comment by jadengore** [comment]
I think the problem is found [here](https://github.com/lerna/lerna/blob/master/src/Command.js#L203-L208). The `loglevel` flag does not happen soon enough, so it isn't respected. My guess is there's custom flag implementations for each command. This one is universal across all, so there needs to be some special considerations.

I added this line to the block I linked, and it properly suppressed the logs:
```js
  run() {
    const { loglevel } = this.options;

    if (loglevel) {
      log.level = loglevel;
    }

    log.info("version", this.lernaVersion);

    if (this.repository.isIndependent()) {
      log.info("versioning", "independent");
    }
```

**Comment by evocateur** [comment]
Indeed, you've nailed it. I would even go so far to say that we should move _all_ the loglevel config into the top of `run()`, as well as the `log.resume()` from the end of the constructor. In essence, no logging should be emitted until `run()` is called.

**Comment by evocateur** [comment]
I went ahead and implemented the fix, verifying it on a local project as well as a unit test. Should be merged shortly.

**Comment by jadengore** [comment]
Thanks @evocateur!
