### ISSUE TITLE
When lerna bootstrap running they failed because some of the dependency package.json is supposed to be empty!

### ISSUE THREAD

**Issue by SerkanSipahi** [lerna/lerna#1036]
Not often but a lot times, lerna stop running bootstrap (installing) due:
```vim
322 error execute npm ERR! code EJSONPARSE
322 error execute
322 error execute npm ERR! Failed to parse json
322 error execute npm ERR! No data, empty input at 1:1
322 error execute npm ERR!
322 error execute npm ERR! ^
322 error execute npm ERR! File: /Users/bitcollage/.npm/browser-stdout/1.3.0/package/package.json
```
But this can't be true. The package.json is not empty. Why is this error occurs? The strange thing its always an another package.json file from a different lib. I have to run `lerna bootstrap` 2, 3 times for a successful run.

### Full log:
322 error execute Error: Command failed: npm install
322 error execute npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
322 error execute npm ERR! Darwin 15.6.0
322 error execute npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
322 error execute npm ERR! node v6.11.0
322 error execute npm ERR! npm  v3.10.10
322 error execute npm ERR! file /Users/bitcollage/.npm/browser-stdout/1.3.0/package/package.json
322 error execute npm ERR! code EJSONPARSE
322 error execute
322 error execute npm ERR! Failed to parse json
322 error execute npm ERR! No data, empty input at 1:1
322 error execute npm ERR!
322 error execute npm ERR! ^
322 error execute npm ERR! File: /Users/bitcollage/.npm/browser-stdout/1.3.0/package/package.json
322 error execute npm ERR! Failed to parse package.json data.
322 error execute npm ERR! package.json must be actual JSON, not just JavaScript.
322 error execute npm ERR!
322 error execute npm ERR! This is not a bug in npm.
322 error execute npm ERR! Tell the package author to fix their package.json file. JSON.parse
322 error execute
322 error execute npm ERR! Please include the following file with any support request:
322 error execute npm ERR!     /Users/bitcollage/Dropbox/Works/Projects/app-decorators/packages/babel-plugin-app-decorators-component-register/npm-debug.log
322 error execute
322 error execute     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
322 error execute     at process._tickCallback (internal/process/next_tick.js:109:7)
322 error execute  callback with error
322 error execute  { Error: Command failed: npm install
322 error execute npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
322 error execute npm ERR! Darwin 15.6.0
322 error execute npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
322 error execute npm ERR! node v6.11.0
322 error execute npm ERR! npm  v3.10.10
322 error execute npm ERR! file /Users/bitcollage/.npm/browser-stdout/1.3.0/package/package.json
322 error execute npm ERR! code EJSONPARSE
322 error execute
322 error execute npm ERR! Failed to parse json
322 error execute npm ERR! No data, empty input at 1:1
322 error execute npm ERR!
322 error execute npm ERR! ^
322 error execute npm ERR! File: /Users/bitcollage/.npm/browser-stdout/1.3.0/package/package.json
322 error execute npm ERR! Failed to parse package.json data.
322 error execute npm ERR! package.json must be actual JSON, not just JavaScript.
322 error execute npm ERR!
322 error execute npm ERR! This is not a bug in npm.
322 error execute npm ERR! Tell the package author to fix their package.json file. JSON.parse
322 error execute
322 error execute npm ERR! Please include the following file with any support request:
322 error execute npm ERR!     /Users/bitcollage/Dropbox/Works/Projects/app-decorators/packages/babel-plugin-app-decorators-component-register/npm-debug.log
322 error execute
322 error execute     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
322 error execute     at process._tickCallback (internal/process/next_tick.js:109:7)
322 error execute   stack: 'Error: Command failed: npm install\nnpm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! \nnpm ERR! Darwin 15.6.0\nnpm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"\nnpm ERR! node v6.11.0\nnpm ERR! npm  v3.10.10\nnpm ERR! file /Users/bitcollage/.npm/browser-stdout/1.3.0/package/package.json\nnpm ERR! code EJSONPARSE\n\nnpm ERR! Failed to parse json\nnpm ERR! No data, empty input at 1:1\nnpm ERR! \nnpm ERR! ^\nnpm ERR! File: /Users/bitcollage/.npm/browser-stdout/1.3.0/package/package.json\nnpm ERR! Failed to parse package.json data.\nnpm ERR! package.json must be actual JSON, not just JavaScript.\nnpm ERR! \nnpm ERR! This is not a bug in npm.\nnpm ERR! Tell the package author to fix their package.json file. JSON.parse\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /Users/bitcollage/Dropbox/Works/Projects/app-decorators/packages/babel-plugin-app-decorators-component-register/npm-debug.log\n\n    at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)\n    at process._tickCallback (internal/process/next_tick.js:109:7)',
322 error execute   code: 1,
322 error execute   killed: false,
322 error execute   stdout: '',
322 error execute   stderr: 'npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! \nnpm ERR! Darwin 15.6.0\nnpm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"\nnpm ERR! node v6.11.0\nnpm ERR! npm  v3.10.10\nnpm ERR! file /Users/bitcollage/.npm/browser-stdout/1.3.0/package/package.json\nnpm ERR! code EJSONPARSE\n\nnpm ERR! Failed to parse json\nnpm ERR! No data, empty input at 1:1\nnpm ERR! \nnpm ERR! ^\nnpm ERR! File: /Users/bitcollage/.npm/browser-stdout/1.3.0/package/package.json\nnpm ERR! Failed to parse package.json data.\nnpm ERR! package.json must be actual JSON, not just JavaScript.\nnpm ERR! \nnpm ERR! This is not a bug in npm.\nnpm ERR! Tell the package author to fix their package.json file. JSON.parse\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /Users/bitcollage/Dropbox/Works/Projects/app-decorators/packages/babel-plugin-app-decorators-component-register/npm-debug.log\n',
322 error execute   failed: true,
322 error execute   signal: null,
322 error execute   cmd: 'npm install',
322 error execute   timedOut: false }

**Comment by evocateur** [comment]
This looks like a problem with the `browser-stdout` package? If you run `npm cache clear` and re-install/bootstrap, does it reproduce?

**Comment by SerkanSipahi** [comment]
it varies with the packages! i will try cache clear.
