### ISSUE TITLE
I have some local packages, lerna update doesn't seem to see the changes to those dependencies

### ISSUE THREAD

**Issue by kirbdee** [lerna/lerna#1039]
## Expected Behavior

Expected `lerna update` to catch any changes to a local package
## Current Behavior

`lerna updated` ignores all local dependencies as part of it's check
## Steps to Reproduce (for bugs)

1. Create npm package
2. Refer to this package from another package locally `npm i -S /path`
3. `lerna updated`

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

It doesn't make sure update/republish based on local depenency changes

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
`lerna updated` is the command you're looking for. Unfortunately there's no error message when you enter a command that doesn't exist.

We tried enabling strict parsing with the CLI recently, but it broke some stuff that couldn't be broken without a major version. We'll probably enable it in the next major version, along with some other refactoring.

**Comment by kirbdee** [comment]
That was a typo on my part, I was using `lerna updated`, I did however find a workaround for my need, all my packages are "private" and just setting the versions(rather then installing by path) as part of the package.json and `lerna bootsrap` automatically then looks at the version numbers as intended

**Comment by evocateur** [comment]
Ah, sorry. Yes, currently lerna requires a semver-matching version for a given "sibling" dependency, not a relative path.

**Comment by kirbdee** [comment]
Right, thanks. I thought lerna was looking at the actual local directories in package.json(if applicable) no worries, thanks for the clarification.

Also maybe an enhancement? or add to docs for this type of case?

**Comment by evocateur** [comment]
A PR adding docs to clarify this requirement would be much appreciated!
