### ISSUE TITLE
Bootstrap performance regression between 2.2.0 and 2.3.0

### ISSUE THREAD

**Issue by tybook** [lerna/lerna#1050]
## Expected Behavior

Lerna v2.3.0 offers at least the same performance as v2.2.0 when bootstrapping.

## Current Behavior

Performance when bootstrapping a monorepo with 55 private packages:
v2.2.0
```
real     1m38.284s
user    4m23.864s
sys      0m33.936s
```
v2.3.0
``` 
real     5m46.422s
user    8m36.540s
sys      1m0.260s
```

## Steps to Reproduce (for bugs)

1. `npm install -g lerna@2.2.0`
2. `lerna clean --yes`
3. `time lerna bootstrap` 
4. `npm install -g lerna@2.3.0`
5. `lerna clean --yes`
6. `time lerna bootstrap`
7. compare the run times

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.2.0",
  "concurrency": 6,
  "hoist": true,
  "packages": [
    "(our private package dirs)"
  ],
  "version": "0.0.0"
}
```
```json
{
  "lerna": "2.3.0",
  "concurrency": 6,
  "hoist": true,
  "packages": [
    "(our private package dirs)"
  ],
  "version": "0.0.0"
}
```
</p></details>

## Context

Bootstraps (at least ones run from a clean starting state) are way slower, slowing down development.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.2.0 and 2.3.0 |
| `npm --version`  | 3.10.8 |
| `yarn --version` | 1.0.2 |
| `node --version` | v6.9.1 |

| OS | Version |
| --- | --- |
| Ubuntu | 16.04.3 LTS |

**Comment by evocateur** [comment]
Whoops, probably shouldn't be passing `npmGlobalStyle` to the initial `installInDir` ([here](https://github.com/lerna/lerna/blob/a132b6e7ed34ca348a9a356d6d8af3ebf82b57f8/src/commands/BootstrapCommand.js#L53)).

So I'll have a partial revert of a132b6e ready soon, thanks for raising this issue!
