### ISSUE TITLE
Add warning for using yarn and --hoist together

### ISSUE THREAD

**Issue by edmorley** [lerna/lerna#1053]
Until #852 is resolved (though it may end up being wontfixed given yarn workspaces makes it redundant), it would be good to add a warning (or even fail loudly) when trying to use yarn and `--hoist`, since it's pretty broken at the moment.

**Comment by evocateur** [comment]
Sounds good to me!

**Comment by marionebl** [comment]
I'd pick this up and go with printing a very human-friendly error message and failing loudly if `BootstrapCommand` detects `--hoist` and `--npm-client=yarn`

**Comment by evocateur** [comment]
Sounds good to me, thanks!
