### ISSUE TITLE
Feature: ignore a package during testing

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#1064]
Hello,

I want to know how can I specify a package to be ignored during testing.
Currently for executing tests on the whole repository I just use `lerna run test`. There is a package that I want to ignore, and I want to specify that on lerna.json, but with the current implementation it's not possible or I don't see how to do it. The problem is that currently you can only configure lerna.json for lerna commands, and test is not one of them

Thanks in advance.

**Comment by marionebl** [comment]
`lerna run test --ignore=ignored-package` might to the trick for you. See the [flag documentation](https://github.com/lerna/lerna#--ignore-glob) for reference

**Comment by evocateur** [comment]
I really don't recommend ignoring packages during tests. Part of the whole _reason_ lerna exists is to run tests of related modules in parallel.

Alternatively, you could always run the tests from the root, configuring the test runner to ignore the package in question.

**Comment by joetidee** [comment]
Why does the `--ignore` flag work, but the ignore directive in `lerna.json` not work ?
