### ISSUE TITLE
lerna publish failures exit with status 0

### ISSUE THREAD

**Issue by aaronjensen** [lerna/lerna#1066]
## Expected Behavior

If a lerna publish fails, I would hope/expect that it would return a non-zero exit status.

## Current Behavior

It returns 0

## Possible Solution

Have it return non-zero

## Steps to Reproduce (for bugs)

1. Attempt to publish a package you don't have access to publish w/ lerna

## Context
We're publishing in CI and it'd be great to know if things fail.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.2.0 |
| `yarn --version` | 1.2.0 |
| `node --version` | 8.4.0 |

**Comment by evocateur** [comment]
What does your `lerna.json` look like?

**Comment by aaronjensen** [comment]
```json
{
  "lerna": "2.2.0",
  "packages": [
    "example",
    "packages/*"
  ],
  "version": "0.1.0",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```

**Comment by aaronjensen** [comment]
For anyone else that needs to error on failure, you can do this for now:

```bash
            ./node_modules/.bin/lerna publish --canary --yes --npm-tag=dev --exact \
              | tee /tmp/publish-results \
              && grep -qv "lerna ERR!" < /tmp/publish-results
```
