### ISSUE TITLE
How do I watch for changes in /packages

### ISSUE THREAD

**Issue by dagda1** [lerna/lerna#1073]
I have the following directory structure:
```
    application
              |
              |__ component-library
                 |
                 |__src
              |
              |__ app
                 |
                 |__src
```

I have used [lerna][1] to link `component-library` in `app`.

At the minute I am linking to the compiled output of the `component-library`.

Is there a way I can watch for changes in the component-library from app?

Is there an example project with this set up?

**Comment by Gurkenschreck** [comment]
I am also interested.
I think I solved this by `npm link`ing the packages together.

**Comment by evocateur** [comment]
I run jest from the root, testing all packages (works great with `--watch`). Similarly, I run `rollup -c -w` from the root, which builds packages as they change. The general idea, as with all lerna-related patterns, is that the watcher is run from the root and affects all packages equally.

We don't have great examples, that's true. Hopefully we can get to them, one day.

**Comment by marlonmleite** [comment]
@evocateur any example using --watch?

**Comment by evocateur** [comment]
This very repo. `npm test -- --watch` or `npx jest --watch`, same diff.

**Comment by marlonmleite** [comment]
Yes, I did, thank you.

@evocateur does your console make the test result ugly? Before separating with Lerna it was very intuitive to interact and see results on the console.

**Comment by evocateur** [comment]
Jest's `--watch` console output is really nice all by itself, there's no need to wrap it inside `lerna exec` or whatever. What output is "ugly" to you?

**Comment by Dombo** [comment]
This may be of use to anyone who stumbles across this while searching for a solution like I did.

https://github.com/Dombo/node-lerna-monorepo

Simple demonstration of watching the lerna graph and building only what's necessary on change events.

**Comment by zposten** [comment]
I'm working on a CLI tool for monorepos which has this functionality

https://github.com/zposten/unorepo#uno-watch

**Comment by lindesvard** [comment]
@zposten will try `uno` (love the name) tonight! Looks promising 🙏

**Comment by shifalijain** [comment]
Unorepo is great, i used it to run watch on multiple packages in my monorepo, works seamlessly.

**Comment by hamzahamidi** [comment]
Apparently this functionality doesn't exist in lerna

**Comment by sdwvit** [comment]
how to watch interdependent packages?

**Comment by yinonov** [comment]
any takes on **_uno_**? what would be ideal from a performance POV? `lerna run watch`? or a root `watch` for all packages.
2 main concerns are:
- log reports of changes
- build dependents as well as affected package (can be achieved by lerna run with a parameter `--include-dependents`)

**Comment by JamesHenry** [comment]
Hi Folks, I'm delighted to be able to close this one as we added the `lerna watch` command in version `6.4.0`. Please update to the latest lerna (`6.5.1` at the time of writing) and enjoy!

Here are the docs: https://lerna.js.org/docs/features/workspace-watching

If you run into any issues with `lerna watch` please open a new issue, providing all the requested information.

Many thanks!
