### ISSUE TITLE
run script before lerna publish

### ISSUE THREAD

**Issue by Arikael** [lerna/lerna#1074]
is it possible to run a npm script before lerna publish?

Currently I want to lint and build my solution before my package is published.
Unfortunately  `prepublishOnly` runs too late leading to broken builds if it the script yields an error.
Broken means: git-tags are published, the configs are updated with the newest version but the package has not been published.

I know I can just create a custom npm script which runs my script and afterwards `lerna publish`.
But if I have a tool like lerna it would nice doing it the "lerna-way" and not something like `npm run myscript` to publish a package.
I may remember to call this script instead of `lerna publish` another dev probably won't.

So, is this possible?
If not. I think it would be a good idea to implement.

Or what is the suggested workflow to achieve what I want?

**Comment by danday74** [comment]
I am facing the same issue - I want a prepublish script in the root package.json that is executed before lerna publishes any module or pushes anything to git. If the prepublish script exists with a non zero exit code I want lerna to abort early.

At the moment I am forced to use a solution similar to @Arikael and I have the same concerns as him.

Many thanks

**Comment by evocateur** [comment]
```json
{
  "name": "my-monorepo",
  "private": true,
  "scripts": {
    "build": "rollup -c",
    "release": "npm test && npm run build && lerna publish",
    "pretest": "eslint packages",
    "test": "jest"
  },
  "dependencies": {
    "et": "cetera"
  }
}
```

`npm run release` should then be documented as "the way" to publish new releases. A plugin system or lifecycle script specific to lerna would be nice, but it's realistically unlikely to happen any time soon, given I am the only active maintainer with a very busy day-job.

**Comment by sarneeh** [comment]
AFAIK Lerna runs a `prepublish.js` script located in `your_package/scripts` directory before publishing your libs on `lerna publish`.
