### ISSUE TITLE
Allow `lerna publish` to skip files that are in the `.gitignore`

### ISSUE THREAD

**Issue by acarl005** [lerna/lerna#1075]
We have a slightly different workflow with Lerna. Within `packages/*`, most of the packages are on GitHub and NPM. However, there is one package in there that is not part of the monorepo. It was placed inside the monorepo in order to get cross-linked, but it is `.gitignore`'d.

The following change will accommodate a more customizable workflows. 

## Expected Behavior
We would like `lerna publish` to work on all the **checked-in** packages, as it currently does. But additionally, we would like it to update the `package.json` in the **git-ignored** package, but not try to `git add` it.

## Current Behavior
`lerna publish` command fails due to the git-ignored package.

## Possible Solution
Invoke `git check-ignore` before attempting `git add`, skipping the file to avoid an exit.
PR #1076

## Steps to Reproduce (for bugs)

```sh
📂 our-monorepo
├──📂.git
├──.gitignore  # /packages/api-service
├──📂 packages
│  ├──📂 a
│  │  └──package.json
│  ├──📂 b
│  │  └──package.json
│  └──📂 api-service
│     ├──📂 .git
│     └──package.json
├──package.json
└──lerna.json
```

```sh
$ lerna publish
# THIS FAILS
```

We put `📂 api-service` inside the monorepo because the cross-linking greatly helps local development and keeping its dependencies up-to date. But it maintains its own, separate git history for ops reasons.

**Comment by matryoshcow** [comment]
Wouldn't tagging your `api-service` package as private solve your issue? `lerna publish` ignores packages that are marked as private AFAIK. This behavior is documented here: https://github.com/lerna/lerna/blob/master/README.md#publish

**Comment by acarl005** [comment]
@matryoshcow Marking it as private only causes it to skip `npm publish`, not the git stuff.
