### ISSUE TITLE
Can devDependencies in the root package.json be used in all repos without installing in each individually?

### ISSUE THREAD

**Issue by wagg-matt** [lerna/lerna#1079]
Have looked through the docs and can't see an obvious way to do this or even if it's possible, if it's in the docs already would you mind pointing me in the direction of it please?

Just starting with creating a monorepo with Lerna and we have multiple repos that use the same packages (react, styled-components etc) and was hoping that these could be installed at root level and all packages within the monorepo can use them. 

The thought being is to control versioning across the monorepo in one place without having to update each individually.

If this is already possible, could you please share how (and make my dreams come true)? If not, would the wider Lerna users find this a feature?

Thanks

**Comment by evocateur** [comment]
Indeed, `devDependencies` in the root package.json can be used in all packages in the monorepo. This is generally used to co-locate test-related deps and config (jest, eslint, etc).

A couple caveats:
1. This only works for non-CLI `devDependencies`. If you need to run a CLI from a child package, that CLI needs to be in that package's `devDependencies`. (transpiling, flowcopy, etc)
2. All `dependencies` for a given child package still need to be listed in that child's package.json. (obvious, perhaps? just clarifying)

[Hoisting](https://github.com/lerna/lerna/blob/master/doc/hoist.md) can optimize the installation of both `dependencies` and `devDependencies` in child packages. I highly recommend it.

**Comment by wagg-matt** [comment]
@evocateur that's great Dan, thanks for coming back to me. 

Has certainly clarified a few things for me. Am building a test project at the moment and will give hoisting a go and see how I get on.

**Comment by hannadrehman** [comment]
@evocateur can we put `dependencies` in root `package.json`. 
lets say that i am building a monorepo for react applications. I would want to have consistent versions of react and other libraries used across all projects.  right now each of my projects have seperate dependencies. but all are same actually.

**Comment by evocateur** [comment]
@hannadrehman If you are publishing the packages, no, the dependencies need to stay in the leaf package manifests. If you're _not_ publishing the packages, I wouldn't bother with Lerna and configure everything in the root, with multiple webpack entries for the various apps.

Using relative `file:` specifiers is even better than bootstrap hoisting, in my experience.

**Comment by hannadrehman** [comment]
@evocateur that makes sense. I had the same thoughts about it.
