### ISSUE TITLE
Stop immediately with non-zero exit code if a cycle is found

### ISSUE THREAD

**Issue by mitchhentges** [lerna/lerna#1085]
In most cases where there's a cyclic dependency within a `lerna` project, it's a erroneous situation. Currently, we need to have our build server watch for a specific "magic string" (the warning that `lerna` emits when it discovers a cycle). Ideally, `lerna` will automatically stop its current task and exit with an error code as soon as a cycle is detected.

For existing-project-migration (and for situations where it's OK to have a cycle, if one exists?), it would be :100: if the resolution for this ticket included the ability to configure if `lerna` should fall back to its old (current) behaviour of just logging and continuing to build, even if a cycle is found.

## Expected Behavior
1. `lerna run bootstrap`
2. Lerna detects a cycle
3. Lerna stops "bootstrapping" and exits with a non-zero exit code

## Current Behavior
1. `lerna run bootstrap`
2. Lerna detects a cycle
3. Lerna warns "Encountered a cycle in the dependency graph" but keeps bootstrapping anyways.

## Possible Solution
In the same location where cycles are detected that produce the warning added by #302, instead stop the task and exit

## Steps to Reproduce (for bugs)
1. Create a `lerna` project
2. Produce a cycle within two or more packages
3. `lerna run bootstrap`

## Context
Our CI servers have to manually watch for the current warning text output when `lerna` discovers a cycle, then kills the process and stops the build. If `lerna` exited immediately with a non-zero code, then CI would work without any magic config.

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0 |
| `npm --version`  | 3.10.10 |
| `node --version` | 6.11.3 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.6 |

**Comment by evocateur** [comment]
I sympathize, as I've never understood why it's "okay" to have cycles in the first place. (I get that they happen in the real world, but I've never felt comfortable leaving them as-is)

I'm open to a new flag that affects this behavior, for sure. I would wait for a major version to exit by default when encountering a cycle, but an opt-in flag seems doable in 2.x. How does `--reject-cycles` sound?
```sh
## 2.x
lerna bootstrap                 # when cycle detected: warns
lerna bootstrap --reject-cycles # when cycle detected: exits non-zero
# lerna.json config: { "rejectCycles": true }

## 3.x+
lerna bootstrap                 # when cycle detected: exits non-zero
lerna bootstrap --allow-cycles  # when cycle detected: warns
# lerna.json config: { "allowCycles": true }
```

You can negate options by prefixing with "no" (e.g., `--no-reject-cycles`), but that reads kinda clunky in this case. Since it would be a breaking change anyway, we could just rename the flag while inverting its purpose.

**Comment by mitchhentges** [comment]
Yeah, going opt-in until the next major release makes a lot of sense.
Thanks for being on board :smile:

**Comment by Gurkenschreck** [comment]
Nice stuff.

> I sympathize, as I've never understood why it's "okay" to have cycles in the first place. 

Who said that it's ok?

**Comment by evocateur** [comment]
Circularity in CommonJS was only possible due to the dynamic nature of `require()`, so I guess the “okay”-ness is more accurately “tolerated.”

It’s definitely a bad idea to intentionally create circular dependencies inside a single monorepo.
