### ISSUE TITLE
All the commands aren't catch()-ing their promises: `UnhandledPromiseRejectionWarning`

### ISSUE THREAD

**Issue by mitchhentges** [lerna/lerna#1086]
Whenever there's an error in one of the commands (e.g. `BootstrapCommand`), there's an extra error at the end of the logs: 
```
(node:18692) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): <error>
```

At the top of each the files in `src/commands/*`, you can see the cause:
```
export function handler(argv) {
  new BootstrapCommand([...argv.args], argv, argv._cwd).run()
    .then(argv._onFinish, argv._onFinish);
    // no .catch()!
}
```

## Expected Behavior
`UnhandledPromiseRejectionWarning` should not be printed if any of the commands throws an error.

## Current Behavior
If a command throws an error, NodeJS complains with an `UnhandledPromiseRejectionWarning`

## Possible Solution
Write in a `.catch()` when initializing any command that returns a promise.
A beautiful :100:/:100: solution (IMHO) would move the logging of the error to the `.catch()` function, rather than logging where the `reject()` handler (or associated callback up-the-chain) is called.

## Steps to Reproduce (for bugs)
1. In `BootstrapCommand.js` change the `initialize()` function so it immediately has a `throw new Error()` at the beginning.
2. `npm run build`
3. If you `lerna bootstrap`, the error will be caught and logged (good), but the _resulting Promise error_ won't be caught.

## Context
To properly support newer versions of NodeJS and not run into undefined (or spooky) behaviour, this should probably be resolved.

**Comment by evocateur** [comment]
`.then(onFulfilled, onRejected)` is effectively the same as `.then(onFulfilled).catch(onRejected)`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

That being said, it's likely there are Promises being dropped on the floor, and there is room for improvement in this area. (The chain isn't 100% async/await, there are a lot of callbacks still)

**Comment by mitchhentges** [comment]
Hmm, it looks like `argv._onFinish` isn't defined (at least in [`BootstrapCommand](https://github.com/lerna/lerna/blob/master/src/commands/BootstrapCommand.js#L14)).

**Comment by evocateur** [comment]
hmm, yeah, now _that_ is quite likely...

(it's mostly used in the test harnesses)

**Comment by sthzg** [comment]
I find this especially problematic in CD environments, where errors in a promise(-chain) should exit the process with an error code. That is what node will do in the future, but right now it prints the deprecation warning but otherwise exits the process with `0`.

**Comment by esprehn** [comment]
> .then(onFulfilled, onRejected) is effectively the same as .then(onFulfilled).catch(onRejected): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

They're not the same. If onFulfilled causes an error the first one will result in an unhandled rejection, while the second will run onRejected.

**Comment by evocateur** [comment]
Ah, indeed, you are right. Thanks for the fact-check.
