### ISSUE TITLE
Possible solution to bootstrap failing to symlink missing files on Windows

### ISSUE THREAD

**Issue by Zalastax** [lerna/lerna#1090]
In https://github.com/lerna/lerna/issues/794 and https://github.com/gatsbyjs/gatsby/pull/2529 bootstrap fails because Windows can't symlink to missing files. It was revealed in https://github.com/lerna/lerna/issues/794 that splitting symlinking into multiple parts is not a viable solution, so we're stuck in the situation that prepublish has to be run after symlink is fully completed but symlinking can depend on prepublish.  
I propose that lerna should check if the file being linked to exists and if it doesn't, create an empty dummy file with the same path. This would ensure that symlinkning on windows works without running prepublish before symlink.  
The only case I see this breaking is if you have a script that checks if the file exists before building and skips building if it does. I don't think that's very common though and in all other ways this seem like a clean solution to me. I'll create the patch myself if you think it's a good idea.

**Comment by evocateur** [comment]
As @jquense noted in [this comment](https://github.com/gatsbyjs/gatsby/pull/2658#issuecomment-340536090):
> Actually I have an idea, we do this for yarn workspaces. let's create a file that requires the built file that way the bin file always exists and can be symlinked.
>
> e.g. gatsby-cli/bin.js which just contains:
>
> ```
> require('lib/index.js')
> ```
>
> you need to change the bin pointer in the package.json as well

This is the appropriate fix in all cases, in my experience. A package's `bin` should never be transpiled output due to permissions and shebangs and whatnot.
