### ISSUE TITLE
Lerna publish dist intended implementation

### ISSUE THREAD

**Issue by wagg-matt** [lerna/lerna#1093]
Hi,

Just publishing my first lerna project and am running into an issue with publishing the first version.

Our lerna monorepo contains three packages that are organised in the following way:

packages/
  atoms/
  molecules/
  organisms/

We were under the impression that this monorepo would create a single dist file containing all the dist files from all of the packages. Is that not the case? I can't find anything in the docs to help with this.

If I need to create a script to do that, it's fine. Would I do that using `exec`?

Any help would be great.

Thanks

**Comment by evocateur** [comment]
Assuming you have three npm packages (`atoms`, `molecules`, and `organisms`), lerna is meant to publish those "in sequence" with versioning identified by previous git tags (if any). lerna is basically a fancy way to run `npm` commands on _n_ npm packages in the same git repository.

If you want a "rollup" package (named `stuff-visibile-from-a-microscope`? 🤔 ), you'll need to add another child of `packages/` that has dependencies on its siblings, and its `main` entry (specified in package.json) should re-export the sibling dependencies as you see fit.

As far as publishing goes, lerna doesn't do anything more than `npm publish` does (but in a slightly different order, to adapt to publishing multiple packages at once).

----
That being said, unless you want to publish your existing packages separately, a single npm package works just as well for creating a single distribution. YMMV
