### ISSUE TITLE
Using workspaces for install/bootstrap but excluding certain packages from `lerna publish`

### ISSUE THREAD

**Issue by skyl** [lerna/lerna#1096]
I have a similar situation as what is described in #216. I have lerna 2.4.0 and I'm using yarn workspaces (yarn 1.2.0). In package.json, I have:

```
  "workspaces": [
    "build/*",
    "packages/*",
    "projects/*"
  ],
```

For `yarn install`, I want all of the package.json's for each of these workspaces taken into consideration and dependencies hoisted/bootstrapped etc (I'm using yarn install instead of lerna bootstrap). This is nice, works great.

I don't have the luxury of working in a total monorepo though. So, I clone other repos in eg `projects` and then add the new dir to `projects/.gitignore`. Yarn install finds these external projects and installs their dependencies. I have `"private": true` in these projects' package.jsons.

## Expected Behavior

I would expect that `lerna publish` would skip over these external, .gitignore'd, private repos and not try to publish them at all.

## Current Behavior

When I run `lerna publish`, these private external repos are taken into account and because they are git ignored, I get weird behavior that I'm not expecting.

```
lerna publish
lerna info version 2.4.0
lerna info current version 0.3.2
lerna info Checking for updated packages...
lerna info Comparing with v0.3.2.
? Select a new version (currently 0.3.2) Patch (0.3.3)

Changes:
 - i-want-to-publish-this: 0.3.2 => 0.3.3
 - dont-publish-this: 4.2.0 => 0.3.3 (private)

? Are you sure you want to publish the above changes? Yes
lerna ERR! execute caught error
lerna ERR! Error: The following paths are ignored by one of your .gitignore files:
lerna ERR! projects/dont-publish-this/package.json
lerna ERR! Use -f if you really want to add them.
lerna ERR! 
lerna ERR!     at Function.module.exports.sync (/.../node_modules/execa/index.js:303:26)
lerna ERR!     at Function.execSync (/.../node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
lerna ERR!     at Function.addFile (/.../node_modules/lerna/lib/GitUtilities.js:68:39)
lerna ERR!     at /.../node_modules/lerna/lib/commands/PublishCommand.js:653:41
lerna ERR!     at Array.forEach (native)
lerna ERR!     at PublishCommand.updateUpdatedPackages (/.../node_modules/lerna/lib/commands/PublishCommand.js:652:22)
lerna ERR!     at PublishCommand.execute (/.../node_modules/lerna/lib/commands/PublishCommand.js:299:12)
(node:46509) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: The following paths are ignored by one of your .gitignore files:
projects/dont-publish-this/package.json
Use -f if you really want to add them.
```

## Possible Solution

Right now my workaround would be to remove the offending workspaces from package.json when I publish and then put them back for install/bootstrap.

## Steps to Reproduce (for bugs)

Create ler

1. Create lerna boilerplate (with one publishable package)
2. clone external repo into packages (set to private in package.json)
3. add the cloned dir to `packages/.gitignore`
4. run `lerna publish`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.4.0",
  "npmClient": "yarn",
  "npmClientArgs": [
    "--ignore-engines",
    "--verbose",
    "--registry http://private-registry"
  ],
  "useWorkspaces": true,
  "version": "0.3.2"
}
```
</p></details>

## Context

Are there any workarounds for always skipping publish for certain packages? Known workflows or gotchas working with external repos as packages that you never want to publish?

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.4.0 |
| `npm --version`  | 4.3.0 |
| `yarn --version` | 1.2.0 |
| `node --version` | 6.10.3 |

| OS | Version |
| --- | --- |
| Yosemite | 10.10.5 |

**Comment by evocateur** [comment]
This is similar to #1076, with the same solution: we should be passing `--update` to the `git add` command, which avoids this git error entirely while respecting things that should be ignored.

**Comment by evocateur** [comment]
Add `"private": true` to the package.json of the packages you don’t want to publish to the registry.

**Comment by sarneeh** [comment]
@evocateur Sorry, I guess I didn't explain the problem properly. I'd like to ignore it completely, this is also not bumping the version in package.json. I know there is independent mode, but in this way I also have to specify the version for the `private` package - which is completely redundant as I won't publish it anyways.

**Comment by evocateur** [comment]
Nope, sorry, lerna doesn’t work that way.

It’s really not that big of a deal to let lerna bump the version. It’s not even a burden in the default fixed versioning mode.

**Comment by sarneeh** [comment]
@evocateur Yeah, I've ended up that way as realised it's not much of a problem. Anyways, thanks for the answers! :)
