### ISSUE TITLE
`lerna add` removes all dependencies before adding new dependency

### ISSUE THREAD

**Issue by ben-z** [lerna/lerna#1099]
When I execute `lerna add <pkg>`, all of the existing dependencies get wiped before the new dependency is added.

## Expected Behavior (Example)

`package.json` for a project  before `lerna add express`:

```json
"dependencies": {
  "body-parser": "^1.18.1"
}
```

`package.json` for a project  after `lerna add express`:

```json
"dependencies": {
  "body-parser": "^1.18.1",
  "express": "^4.16.2"
}
```

## Current Behavior (Example)

`package.json` for a project  before `lerna add express`:

```json
"dependencies": {
  "body-parser": "^1.18.1"
}
```

`package.json` for a project after `lerna add express`:

```json
"dependencies": {
  "express": "^4.16.2"
}
```

Notice how `body-parser` does not exist in the dependencies list anymore.

## Possible Solution

Probably related to #1069, cc @marionebl

## Steps to Reproduce (for bugs)

1. execute `lerna add <pkg>` in a repo with existing dependencies

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.5.0",
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.0 |
| `npm --version`  | 5.3.0 |
| `yarn --version` | 1.2.1 |
| `node --version` | v8.5.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13 |

**Comment by marionebl** [comment]
Just reproduced this, guess it happened when refactoring from `JSONFile` to `write-pkg`. I'll cook up a fix immediately.

**Comment by evocateur** [comment]
Cool, I can hotfix that right now. Thanks for digging in, @marionebl

**Comment by marionebl** [comment]
I opened a PR with relevant new unit tests for `lerna add` @evocateur: https://github.com/lerna/lerna/pull/1100

**Comment by evocateur** [comment]
Awesome, thanks!

**Comment by marionebl** [comment]
Added the relevant fix to the same PR via a second commit.

**Comment by ben-z** [comment]
@evocateur Do hotfixes get a release right away as 2.5.1 or do users have to wait for 2.6.0/3.0.0?

**Comment by evocateur** [comment]
I'm gonna release 2.5.1 as soon as I cover a few missed conditionals, and CI stops pooping the bed...

**Comment by evocateur** [comment]
Fixed in https://github.com/lerna/lerna/releases/tag/v2.5.1, apologies for the delay

**Comment by ben-z** [comment]
Good work @evocateur @marionebl!
