### ISSUE TITLE
Lerna test frozen (probably on a loop)

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#1103]
Hello,

First of all, let me say that when I opened this issue I was totally lost. I had no idea about what the problem was or how to reproduce it. Now I have fixed it and I know why this was happening, but I still think I should report it here. That way if it gets fixed, then hurray, if not maybe someone else can get advantage of this report.

The behavior was quite funny:

- I execute lerna run test through npm script called test `"scripts":{ "test": "lerna run test" }`
- Lerna executes all the tests, and gets frozen at the last package on the repo.
- If I exclude the last package on the repo using `--ignore=` then lerna gets frozen on the package right before the last one (now the last on the repo)

I was very puzzled and thinking that the problem should be on some package test script. Then, when I opened this issue and I pasted my lerna.json file I noticed something funny: `./` was part of the packages array. This along with the fact that the script launching `lerna run test` was also called test made me realize that I was on an infinite test execution loop. 
No log output is shown by lerna when the loop starts again, that was probably one of the reasons this problem was so hard to figure out.

## Expected Behavior
Lerna should execute all the test and finish.

## Current Behavior
Lerna gets frozen at the last package on the repository.

## Possible Solution
- Do not include the root of the repo on the packages section of lerna.json
- Ideally lerna should detect this situation and prevent it, or at least it should be documented.
- Maybe don't name `test` the script that executes `lerna run test`

## Steps to Reproduce (for bugs)
Just put the root of the repo on the packages section and launch test through an script called `test`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0",
  "packages": [
    ".",
    "src/*"
  ],
  "hoist": true,
  "registry": "https://private-registry/npm",
  "commands": {
    "publish": {
      "conventionalCommits": true,
      "message": "chore: Publish"
    }
  },
  "version": "independent"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0 |
| `npm --version`  | 4.1.2 |
| `node --version` | v7.7.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
I'm not aware of any recommendation to add `"."` to the `"packages"` config in lerna.json. I really don't recommend it, as the root package.json should generally be used for managing all the common test/build scripts and dependencies.

There is a similar problem when you have a `postinstall` script in the root that calls `lerna bootstrap --hoist`, which then calls `npm install` in the root first, and then we're off to the races. Detecting various lifecycle-related env vars (and providing our own, to signal that we're running already) is one way we could work around this, but it has its own pitfalls.

**Comment by danielo515** [comment]
Hello @evocateur 
> I'm not aware of any recommendation to add "." to the "packages" config in lerna.json. 

Officially not, but if you want your root package json version to be updated along with the rest of packages, this is one easy way.

> There is a similar problem when you have a postinstall script in the root that calls lerna bootstrap --hoist

That's funny, because I do have a postinstall script which calls lerna bootstrap with hoist configured on `lerna.json` 😄  . But, as far as I know (and contrary to what I thought) postinstall is a life-cycle method that affects only to packages that are being installed. This  means it is not triggered when you run `npm install` on your repo, but after a package is installed

>  is one way we could work around this, but it has its own pitfalls.

Or at least provide a couple of warnings on the readme. That is fast and easy.

**Comment by danielo515** [comment]
Maybe it's all about npm version. I have updated it recently. Wich version are you using?

**Comment by evocateur** [comment]
```json
{
  "name": "install-with-no-arguments",
  "version": "1.0.0",
  "description": "run a postinstall after npm install with no arguments",
  "repository": "npm/avoid-warning",
  "scripts": {
    "postinstall": "echo ran postinstall"
  },
  "license": "ISC",
  "dependencies": {
    "tiny-tarball": "^1.0.0"
  }
}
```

```
$ nvm exec 8 npm install
Running node v8.9.1 (npm v5.5.1)

> install-with-no-arguments@1.0.0 postinstall /private/tmp
> echo ran postinstall

ran postinstall
up to date in 0.09s
```

```
$ nvm exec 6 npm install
Running node v6.12.0 (npm v3.10.10)

> install-with-no-arguments@1.0.0 postinstall /private/tmp
> echo ran postinstall

ran postinstall
```

```
$ nvm exec 4 npm install
Running node v4.8.6 (npm v2.15.11)
npm WARN package.json install-with-no-arguments@1.0.0 No README data

> install-with-no-arguments@1.0.0 postinstall /private/tmp
> echo ran postinstall

ran postinstall
```

`lerna bootstrap --hoist` always runs `npm install` (with no arguments) in the root before any other operations, and thus will always invoke a `postinstall` lifecycle, if it exists.

**Comment by danielo515** [comment]
Hello @evocateur ,

That's the behavior I was expecting, but at some point it stopped working.
I usually run `npm i` instead of `npm install`, could that make a difference ?

In any case, thank you very much for your detailed showcase.

Regards

**Comment by evocateur** [comment]
`npm i` is just an alias to `npm install`
