### ISSUE TITLE
lerna exec stream flag not supported

### ISSUE THREAD

**Issue by alan-agius4** [lerna/lerna#1105]
Is there any reason why `lerna exec` only supports the `parallel` flag and not `stream` as well?

I'd very much need the stream flag to work on exec

**Comment by evocateur** [comment]
I don't recall, honestly, and it's quite likely it just wasn't needed by whomever implemented `--parallel`.

**Comment by alan-agius4** [comment]
After checked I noticed that by default it's streaming :)
