### ISSUE TITLE
Lerna run broken argument passing

### ISSUE THREAD

**Issue by StarpTech** [lerna/lerna#1106]
Execute npm script on root level
```
lerna run bin --scope=bootme-cli -- --config ./examples\.bootme.js
```
has following `argv` in `cli.js`

```
[ 'C:\\Program Files\\nodejs\\node.exe',
  'E:\\Repositorys\\bootme\\packages\\bootme-cli\\cli.js',
  './packages/bootme-cli/examples\\.bootme.js' ]
```

when I run `cli.js` in the directory with `npm run bin -- --config ./examples\.bootme.js` I get

```
[ 'C:\\Program Files\\nodejs\\node.exe',
  'E:\\Repositorys\\bootme\\packages\\bootme-cli\\cli.js',
  '--config',
  './examples\\.bootme.js' ]
```

## Expected Behavior
All arguments should be passed after `--`.

## Current Behavior
Arguments are not passed correctly

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 5.4.2 |
| `node --version` | 8.8.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Windows 10 | 1607 |

**Comment by evocateur** [comment]
Actually, this is because `lerna run` is first calling `npm run`, so you have to pass `--` twice to pass the args to the npm script itself. It's not ideal, but it's kind of necessary to preserve the ability to pass flags to `npm` (or `yarn`) itself.

```
lerna run bin -- --silent -- --config ./path/to/config.js
```
This would run the script without the npm-inserted headers and whatnot, passing `--config ...` to the underlying npm script.

**Comment by StarpTech** [comment]
I tried `lerna run bin -- --scope=bootme-cli -- --config ./examples\.bootme.js` but still doesnt work

**Comment by evocateur** [comment]
`--scope` belongs to lerna, not npm.
```
lerna run bin --scope=bootme-cli -- -- --config ./examples\.bootme.js
```

(`lerna run` will only run the script where it exists, so if `bootme-cli` is the only one with a "bin" script, you don't need the `--scope` arg)

(also, not sure why your're escaping the second `.` in the `--config` arg?)

**Comment by StarpTech** [comment]
It works now, thanks but I don't see the output of my script.

**Comment by StarpTech** [comment]
I expect to see this

```
√ request-1: Retrieve the IIS position
√ temp-1: Create temp file
√ request-2: Make request
```
but got

```
> node cli.js "--config" "./examples/.bootme.js"

lerna success run Ran npm script 'bin' in packages:
lerna success - bootme-cli
```

**Comment by evocateur** [comment]
What stream is the expected result logged to? If it's not `stdout` (console.log, console.info), then you'll probably need to pass `--stream` to `lerna run` (by default it buffers `stdout` and emits it after the scripts complete).

**Comment by StarpTech** [comment]
@evocateur thanks `--stream` works I had to set it to `stdout`

**Comment by tommedema** [comment]
When using yarn as npm client you are incorrectly parsing the `--` flags. This is deprecated and returns a warning.

**Comment by evocateur** [comment]
>When using yarn as npm client you are incorrectly passing the `--` flags. This is deprecated and returns a warning.

@tommedema Open a new issue, please.
