### ISSUE TITLE
Package dependencies not installed during bootstrap (and very slow)

### ISSUE THREAD

**Issue by chrisui** [lerna/lerna#1114]
Hoping to transition over to lerna to manage our repo I setup a very basic repo with two packages (one the legacy repo) and another with only a handful of new dependencies.

However when running `lerna bootstrap` the dependencies of the new package do not get installed.

You can find the minimal repo case with all my configuration here: https://github.com/chrisui/lerna-bug

## Expected Behavior

Dependencies in `packages/test.com` are installed in `packages/test.com/node_modules`. I expect `react` and `react-dom` dependency to be in the package node_modules but then the `next` dependency _could_ be hoisted.

## Current Behavior

None of the dependencies within the `test.com` package are installed anywhere. There are no errors.

Also note that it takes a very long time for `lerna bootstrap` to complete which is odd since it is only two packages with the new one having only 3 dependencies. This is basically a 6x time increase for installing dependencies over just having the single package and using `npm install`.

```
$ time lerna bootstrap --loglevel silly
lerna sill input []
lerna sill flags { _: [ 'bootstrap' ],
lerna sill flags   'reject-cycles': false,
lerna sill flags   rejectCycles: false,
lerna sill flags   loglevel: 'silly',
lerna sill flags   args: [] }
lerna verb rootPath /Users/chris/Projects/lerna-bug
lerna info version 2.5.1
lerna sill existsSync /Users/chris/Projects/lerna-bug/VERSION
lerna sill initialize attempt
lerna sill npmConfig { registry: undefined,
lerna sill npmConfig   npmClient: 'yarn',
lerna sill npmConfig   npmClientArgs: undefined,
lerna sill npmConfig   mutex: 'network:42424' }
lerna sill initialize success
lerna sill execute attempt
lerna info Bootstrapping 2 packages
lerna sill installInDirOriginalPackageJson /Users/chris/Projects/lerna-bug
lerna sill getExecOpts { cwd: '/Users/chris/Projects/lerna-bug' }
lerna sill installInDir [ 'yarn',
lerna sill installInDir   [ 'install', '--mutex', 'network:42424', '--non-interactive' ] ]
lerna info hoist Finished installing in root
lerna success Bootstrapped 2 packages
lerna sill execute success

real    6m21.862s
user    1m26.540s
sys     0m45.632s
```

## Steps to Reproduce (for bugs)
1. Clone https://github.com/chrisui/lerna-bug (note yarn.lock file was generated from bootstrapping)
2. `lerna bootstrap`

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "yarn",
  "useWorkspaces": true,
  "lerna": "2.5.1",
  "packages": ["packages/*"],
  "version": "0.0.0",
  "hoist": true,
  "command": {
    "publish": {
      "allowBranch": "master"
    }
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 3.10.8 |
| `yarn --version` | 1.3.2 |
| `node --version` | v6.9.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.6 |

**Comment by chrisui** [comment]
Pointing my naive finger at `yarn` currently since just trying to use yarn without lerna is causing me trouble with random dependencies being missing not even in a monorepo/workspaces environment.

**Comment by cansin** [comment]
I am hitting the same problem with:

```
lerna --version 2.5.1
npm --version  5.3.0
yarn --version  1.3.2
node --version v8.4.0
macOS Sierra   10.12.6
```

where `lerna.json` has:

```
{
  "lerna": "2.5.1",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```

and top level `package.json` has:

```
{
  "private": true,
  "name": "some-name",
  "devDependencies": {
    "lerna": "2.5.1"
  },
  "workspaces": [
    "packages/*"
  ],
  "engines": {
    "node": ">=8.4.0",
    "yarn": "^1.3.2"
  },
}
```

Running `lerna bootstrap` at root path does create `node_modules` folder at top level, but does not create any `node_modules` folder under any of the `packages/package-name/` folders.

**Comment by cansin** [comment]
Actually, I just realized this might be the expected behavior for yarn workspaces: https://yarnpkg.com/lang/en/docs/workspaces/#toc-how-to-use-it

**Comment by chrisui** [comment]
Have confirmed this is a yarn/workspaces/lerna-yarn-integration issue now with a [npm only branch](https://github.com/chrisui/lerna-bug/tree/npm) of the previous failing repro case (see linked repo).

**Comment by evocateur** [comment]
Okay, this sounds like an upstream issue, then.

**Comment by abhinavsingi** [comment]
Are you installing yarn with giving NODE_ENV as production?
