### ISSUE TITLE
Lerna should refuse to publish packages with unstaged changes

### ISSUE THREAD

**Issue by timm-gs** [lerna/lerna#1120]
I ran into this the last few days when getting started with Lerna, and in #1009 a similar issue is reported.

Basically committing and then tagging a Git commit with the just published version is futile, if that Git commit is not ensured to contain all the files that were published.

I know that that might still be files missing from the "Git version" of that package, e.g. if they're ignored by `.gitignore` but part of the NPM package regardless (in my case for example the compiled JS output of TS files).

In case of unstaged changes in a package to be published I would expect `lerna publish` to err outright, or ask the user whether they'd like to proceed.\

**Comment by evocateur** [comment]
I could have sworn this check was happening, but I am quite likely mistaken. Adding validation [here](https://github.com/lerna/lerna/blob/00b979f45b6c3886380f6dad01473e2e2ff88db0/src/commands/PublishCommand.js#L176) seems reasonable, for the simple case.

High-level logic:
1. Call `git status --porcelain -- [...this.repository.packageParentDirs]`.
    * With pathspec filters like [`DiffCommand`](https://github.com/lerna/lerna/blob/00b979f45b6c3886380f6dad01473e2e2ff88db0/src/commands/DiffCommand.js#L56) to allow dirtiness in places lerna doesn't care about?
2. Assert that call's `stdout` is empty; i.e., no staged changes, unstaged changes, or untracked files under the package directories.
    * A new [`GitUtilities`](https://github.com/lerna/lerna/blob/master/src/GitUtilities.js) method would be clearest and easiest to test.
3. If non-empty, throw a `ValidationError` like the other git checks.

Reference: https://stackoverflow.com/questions/2657935/checking-for-a-dirty-index-or-untracked-files-with-git

**Comment by NMinhNguyen** [comment]
> or ask the user whether they'd like to proceed

I probably have a very convoluted setup, but may I request that if such validation is added, then for there to be an option to opt out?

My use case is that I'd like to have a `packages/my-package/index.js` file that's basically identical to React's own [index.js](https://github.com/facebook/react/blob/3c977dea6b96f6a9bb39f09886848da870748441/packages/react/index.js) file, but before publishing I'd like to replace it with this [index.js](https://github.com/facebook/react/blob/3c977dea6b96f6a9bb39f09886848da870748441/packages/react/npm/index.js) file that resides in a different, `packages/my-package/npm` folder. However, I would not want this to be committed back to the repo, and used when publishing only.

Now, I understand the reasoning in https://github.com/lerna/lerna/issues/901#issuecomment-350423290, but being able to publish from a custom `packages/my-package/build` or `packages/my-package/dist` directory (kinda what React does) would allow me to just copy the `npm` folder into `build` without causing unstaged changes 😃

**Comment by evocateur** [comment]
This has been fixed for quite some time.
