### ISSUE TITLE
Feature request: warn user when yarn workspaces are configured in package.json but disabled in lerna.json

### ISSUE THREAD

**Issue by sveinburne** [lerna/lerna#1124]
I just had a long day-quest to solve a difficult bug which originated from a yarn conflict with lerna. Workspaces where mistakenly configured on `package.json` but disallowed in `lerna.json`. It resulted in yarn checking for a local package in yarn registry from a dev-dep, and failing to find it. The bug is unfortunately hard to reproduce in a minimal working example regarding my many attempts.

So I would be in favor of disallowing such a configuration : 

*package.json*
```json
{
  "workspaces": [
    "packages/*"
  ]
}
```
*lerna.json*
```json
{
  "npmClient": "yarn",
  "useWorkspaces": false,
  "packages": [
    "packages/*"
  ]
}
```

**Comment by evocateur** [comment]
This seems reasonable. I've opened a PR to address this, bumping up the warning to an error (I don't see the point of continuing if it will inevitably cause problems).
