### ISSUE TITLE
[Feature] Modifiable default commit message

### ISSUE THREAD

**Issue by wizzy25** [lerna/lerna#1127]
## Expected Behavior

It would be nice to have a customisable default commit message, specified in the `lerna.json` file
## Current Behavior

Running `lerna publish` without a `--message` flag fails on my `validate-commit-msg` hook, and it makes no sense having to type the same thing over and over for every publish.
## Possible Solution

Possible addition of a `"commit-message"` field to the lerna.json file, which `lerna publish` can default to. This should be overridable by passing the `--message` flag
## Context

Currently, I am hardcoding the message in `package.json` and running `lerna publish` through a custom script, but a natural solution will be more ideal.
## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.4.0 |
| `npm --version`  | 5.5.1 |
| `yarn --version` | 1.3.2 |
| `node --version` | 8.9.0 |

| OS | Version |
| --- | --- |
| macOS El Capitan | 10.11.6 |

**Comment by evocateur** [comment]
It's always been possible to do just that (I use it almost every day). I updated the [docs](https://github.com/lerna/lerna#--message--m-msg) with a lerna.json example.

**Comment by wizzy25** [comment]
@evocateur Thanks for the response. I thought it didn't exist already
