### ISSUE TITLE
There should be a version of --exact that doesn't apply to peerDependencies

### ISSUE THREAD

**Issue by Dru89** [lerna/lerna#1128]
## Expected Behavior
I should be able to update `peerDependencies` with version ranges, even if `dependencies` have exact versions.  This would best support the "plugin" architecture that `peerDependencies` seems to mostly exist for.

Reading the documentation from npm:
> Trying to install another plugin with a conflicting requirement will cause an error. For this reason, make sure your plugin requirement is as broad as possible, and not to lock it down to specific patch versions.

— https://docs.npmjs.com/files/package.json#peerdependencies

## Current Behavior
Currently, version pinning is done with the `--exact` flag, and that extends to `dependencies`, `peerDependencies`, and `devDependencies`:
https://github.com/lerna/lerna/blob/da3e30f644113f1080fb645bb28a066c3f4cb761/src/commands/PublishCommand.js#L579-L582

## Possible Solution
I think `--exact` should continue to do what it already does, so we don't have any breaking changes.  But we could introduce flags like `--[no-]exact-dependencies`, `--[no-]exact-peer-dependencies`, and `--[no-]exact-dev-dependencies` to turn on/off specific dependencies sections.

## Context
We use lerna to build a "framework" for applications, including a base package and a few plugins.  This means that every application depends on a few plugins and then the base package.  But with `--exact`, what will happen is that the `peerDependencies` for updated dependencies are kept in lock-step.

This seems to be against npm's recommendations for `peerDependencies`, and could put us in a position where two plugins can't be used at the same time, because of a strict peer dependency on the base package.

**Comment by evocateur** [comment]
In #1018 we've already agreed that lerna really shouldn't be touching `peerDependencies` _at all_, since changes to the peer range (especially the bottom end) are semver-major, and often very hard to automate safely. The linked issue gets a little in the weeds toward the end, but fundamentally we shouldn't be doing anything to `peerDependencies` right now (or "surprise" changes, as described in #955).

**Comment by Dru89** [comment]
Oh, cool.  I'm okay closing this as a duplicate and just following #1018, then.  Sorry, I tried to search for this but had a harder time finding it.
