### ISSUE TITLE
stalled builds on CI when Lerna is used

### ISSUE THREAD

**Issue by donaldpipowitch** [lerna/lerna#1131]
## Expected Behavior

I run [several Lerna commands](https://github.com/Mercateo/ws/blob/a45d2ed996c6ee9920c882f2b5364839affacba3/examples/package.json#L3) in my CI and I'd expect them to exit successfully.

## Current Behavior

It looks like I occasionally (>=30%) [get stalled builds](https://travis-ci.org/Mercateo/ws/jobs/305141203) (from Node 6 - 9) when I run my tests with Lerna (with and without concurrency set to 1). When I run the same logic [with a custom script](https://github.com/Mercateo/ws/blob/a45d2ed996c6ee9920c882f2b5364839affacba3/scripts/test.js#L26) the tests pass correctly.

## Steps to Reproduce (for bugs)

My example is open source. The stalled builds which use Lerna for running the scripts can be found [here](https://github.com/Mercateo/ws/tree/f78409cd491b3ea1b20409b44f97a01b99724a4d).

My custom script can be found [here](https://github.com/Mercateo/ws/tree/a45d2ed996c6ee9920c882f2b5364839affacba3).

(The test runners live in `scripts/test.js` in both cases.)

Sadly I can only see this on Travis CI. Locally it seems to run fine. (?)

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.5.1"
}
```
</p></details>

## Context

I run several Lerna commands in our Travis CI. I also use yarn Workspaces.

**Comment by evocateur** [comment]
Well, one possibility is that `lerna run` currently always calls `npm run <scriptName>` instead of `yarn run <scriptName>`. Travis might have a wonky version of npm, then?

Streaming the output through two processes might be an issue, too?

Calling a CLI via a relative path that reaches below the CWD of the lerna process might also be gumming things up.

Strikes me that the examples packages should probably have a proper dependency on the `ws` package so the bin symlinks get properly setup and such?

**Comment by donaldpipowitch** [comment]
Great feedback and ideas. I'll check them. Thank you for taking the time to check this.

Yeah, I still want to add `ws` as a proper dependency. I had it some time ago, but it couldn't build correctly so I wanted to introduce workspaces in smaller steps.

_Really_ thank you.

**Comment by donaldpipowitch** [comment]
Sadly I can't spot a real difference. I tried to use `npm run` everywhere with the same result. I haven't tried including the `ws` into the workspaces directly, but I can't imagine how this would affect Lerna 🤔 I'll revert the test script for now.

Feel free to close this issue, if you want.
