### ISSUE TITLE
Lerna is not installing optionalDependencies in workers

### ISSUE THREAD

**Issue by MatthD** [lerna/lerna#1136]
Hi Lerna!

I am facing a problem, my lerna programm is not installing optionalDependencies,
If I go to my worker & run "npm install" it install it correctly .

the module to install could be only installed on darwin/linux : 
https://github.com/istex/popplonode/blob/master/package.json#L6

The worker which not install it's optionalDependencies: 
https://github.com/istex/sisyphe/blob/pdfforall/src/worker/pdf/package.json

What could be the problem ?

**Comment by MatthD** [comment]
it seems it works if the the optionalDpendencies is written on the main package.json (maybe because its a real "npm install") but not in the workers ..

**Comment by MatthD** [comment]
Ok , when I use lerna with the '--hoist' option, it throw an error on an optional dependencies ... :ss

**Comment by MatthD** [comment]
Is there a workarround for this ? regards

**Comment by evocateur** [comment]
Once we stop drastically mangling the package.json during bootstrap, this should be solved.

**Comment by BMalaichik** [comment]
@MatthD do you deal with linked(npm link) packages?

**Comment by evocateur** [comment]
Implemented (correctly) in b73e19df
