### ISSUE TITLE
Lerna key in lerna.json

### ISSUE THREAD

**Issue by klis87** [lerna/lerna#1141]
We do we need `lerna` version in `lerna.json`, current version of lerna is already known by lerna itself - the one we installed:
```js
{
  "lerna": "2.0.0", // why this is necessary?
  "version": "0.0.0"
}
```

**Comment by evocateur** [comment]
It's a (somewhat brittle) way to determine if the local configuration of lerna is compatible with the running executable. since v2.0.0, it's been a semver comparison, so you never really have to edit it.
