### ISSUE TITLE
run: transitive dependencies not sorted correctly when not all packages have the script?

### ISSUE THREAD

**Issue by martijnthe** [lerna/lerna#1143]
## Expected Behavior

I have a mono repo with 3 internal packages:
```
A => depends on B -- has `"myscript"`
B => depends on C -- does NOT have `"myscript"`
C => no dependencies -- has `"myscript"`
```

When I run `yarn lerna run --stream --sort myscript`, I would expect that the `"myscript"` script gets run for `C`, then for `A`.

## Current Behavior

The script is run for `A` before `C`'s script has run.
If I add a `"myscript"` script to `B`, `C` gets run before `A`.

## Steps to Reproduce (for bugs)

Will try to create an example later.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 5.5.1 |
| `yarn --version` | 1.3.2 |
| `node --version` | 8.9.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.6 |

**Comment by evocateur** [comment]
`--stream` is irrelevant to the repro, and `--sort` (`this.toposort`, helpfully...) is the default. The package candidates are filtered for the target script before they are topographically sorted. I don't know how you'd do it the other way around, but it sounds complicated.

**Comment by martijnthe** [comment]
> The package candidates are filtered for the target script before they are topographically sorted. I don't know how you'd do it the other way around, but it sounds complicated.

Filtering first and then sorting sounds like the problem indeed.

Why is sorting first, then filtering more complicated?

**Comment by evocateur** [comment]
The topographic sort returns a two-dimensional array of “batched” packages, not a simple list. It’s more complicated to filter out packages that do not have the script and still maintain the batching.
