### ISSUE TITLE
Feature: package-specific private npm registries for deps and publishing

### ISSUE THREAD

**Issue by reggi** [lerna/lerna#1146]
I have two packages both need to pull dependencies from different registries. 

```
/pacakges
  /package-a - (needs deps from registry one && needs to be published to registry three)
  /package-b - (needs deps from registry two && needs to be published to registry four)
```

NPM has a way to publish to a specific registry in `package.json`

```
{
    "publishConfig":{
        "registry": "http://my-internal-registry.local"
    }
}
```

Is this a feature that has been discussed by the npm, yarn or lerna teams?

I am requesting this:

```
{
    "dependencyConfig":{
        "registry": "http://my-internal-registry.local"
    }
}
```

Would this be a feature of lerna or npm?

**Comment by evocateur** [comment]
My gut reaction is "don't do that, why would you do that?", but I realize this is unhelpful. In terms of lerna support, I'd say those two packages don't belong in the same monorepo if they've got such drastically different registry requirements.

If you're willing to run two `lerna bootstrap` commands, I suppose you could run one scoped to registry A and another scoped to registry B, but that will probably fail if package-a and package-b have a relationship of _any_ kind (which is kinda the whole point of lerna? It's okay not to use lerna).
```
lerna bootstrap --registry foo.com --scope package-a
lerna bootstrap --registry bar.com --scope package-b
```

The normal solution is to place `.npmrc` files with `registry = foo.com` contents next to the afflicted `package.json`. If you're _not_ hoisting/using yarn workspaces, this could work. If you _are_ doing either of those, I'm afraid you're out of luck.

**Comment by reggi** [comment]
Could also shrinkwrap here and it will pull tar from given installed registry.
