### ISSUE TITLE
Lerna does not hoist dependent packages

### ISSUE THREAD

**Issue by IhostVlad** [lerna/lerna#1147]
## Expected Behavior
In general, `lerna bootstrap` should organise monorepo, as like all packages had been installed from npm. Any packages should be placed in that directories, in which they will be placed, if regular `npm install` process had been occured. Of course, coping can be avoided by using symlinks.

Something like `--hoist` flag can be appropriate - https://github.com/lerna/lerna/blob/master/doc/hoist.md . But installation should be performed not in global scope, but it dependent package's scope.

## Current Behavior
Now dependent packages of two and deeper levels do not hoist to upper `node_modules` directory, even in symlink form.

Current behaviour also reflected in `hoist`-flag documentation:
> it is possible to symlink packages from their hoisted top-level location, to individual package node_modules directory [but] lerna does not yet do this automatically

## Possible Solution
Issue can be solved, if perform creating symlinks for nested packages in `node_modules` directory. In other words, folder structure in each module should repeat tree, which will be built, it read `npm install` occured.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.4.0",
  "packages": [
    "packages/*",
    "examples/*",
  ],
  "version": "0.100.500"
}
```
</p></details>

## Context
Imagine that you have monorepo with two global folders: for packages and for examples on them. Some package **`P`** in `packages` folder has requirements from npm - let it be **`D`** package. Then some example **`E`** from `example` folder try to use bootstrapped package **`P`** from current monorepo, but process fall with error - because node.js require tries to find dependencies only in root `node_modules`, and since there is not **`D`** package there - it can't be resolved.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 5.5.1 |
| `node --version` | 8.3.0 |

**Comment by MrCheater** [comment]
+1

**Comment by IhostVlad** [comment]
Should `--host` flag help for that solution? 
https://github.com/lerna/lerna/blob/master/doc/hoist.md

**Comment by evocateur** [comment]
If you've configured all of your dev dependencies in the root anyway, this isn't generally a problem. I don't foresee lerna symlinking transitive dependencies at every level, because that is a fractal nightmare of bugs and edge-cases.
