### ISSUE TITLE
[suggestion] Use prettier to format lerna source

### ISSUE THREAD

**Issue by jezzay** [lerna/lerna#1148]
Just a suggestion to use [prettier](https://github.com/prettier/prettier) to format lerna's source code. 

Using prettier would automate + enforce a consistent style for the source code; allowing contributors to not worry about code formatting when sending PRs.

## Possible Solution
Integrate prettier with eslint, which would maintain the current workflow of `yarn lint`  to lint sources. 

This would mean running `yarn lint --fix` would auto format the *.js sources. 

I'll be happy to send a PR for this if there is interest.

**Comment by evocateur** [comment]
Yeah, I've been meaning to do this, a PR would be great!

**Comment by jezzay** [comment]
@evocateur Looks like you beat me to raising a PR for this :) 

The changes in your PR look good 👍

**Comment by evocateur** [comment]
Thanks!
