### ISSUE TITLE
Bug: invalid subcommands return successful status code

### ISSUE THREAD

**Issue by jasonkarns** [lerna/lerna#1150]
## Expected Behavior
`lerna foo` should exit with status `127` (corresponding to the common "command not found" shell error)

## Current Behavior

`lerna foo` returns a `0` (success) status code, despite `foo` not being a valid subcommand.

## Steps to Reproduce (for bugs)
1. `lerna foo`

(Even more damning, lerna-debug.log isn't even generated for an invalid subcommand.)

## Context
When scripting or even just invoking manually from the CLI, a successful exit status code communicates that the command was invoked successfully. lerna is "lying" in the sense that scripts (like CI, for example) can be running invalid commands without the script being aware that the intended steps are actually failing. (like a fat-fingered `bootstrap` for instance, which is easy to do since lerna doesn't appear to have any tab completion)

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 5.5.1 |
| `yarn --version` | 1.3.2 |
| `node --version` | 6.12.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
Yep, I definitely sympathize. #1140 fixed this, released in v2.7.0.
