### ISSUE TITLE
Lerna --config argument

### ISSUE THREAD

**Issue by reggi** [lerna/lerna#1154]
I have a monorepo where there are several modules, each needs to be bootstrapped with a different version of node. I've created three lerna config files I can switch out the node versions before running `lerna bootstrap` I just need a way to specify which config file to use.

Is this something that is in lerna & undocumented?

Or do i have to `mv` my files to `lerna.json` and overwrite it from there?

**Comment by evocateur** [comment]
These modules that require _literally different versions of `node`_ should not be in the same monorepo.

**Comment by reggi** [comment]
I still would like a `--config` option so I can have multiple monorepos within one repo.

**Comment by evocateur** [comment]
Lerna does not support managing multiple multi-package roots in the same repository. I'm confused just thinking about it.

As I explained in #1398, we can't support a `--config` flag because we _also_ store the global version in `lerna.json`. I don't see a non-breaking (like, _catastrophically_ breaking) way of changing that right now.

**Comment by reggi** [comment]
@evocateur  Why can't `--config` point to any given `.json` file and pull the version from there? I am confused as to what the bottleneck is.

This would allow for supporting multi-package roots in the same repo.

* `lerna-project-a.json` => points to ./packages-a/
* `lerna-project-b.json` => points to ./packages-b/

Then every `lerna` command would accept `--config` using that as it's 

```
lerna publish --config ./lerna-project-a.json
lerna publish --config ./lerna-project-b.json
```

**Comment by evocateur** [comment]
The location of `lerna.json` _also_ determines where the "root" of a lerna project is based from. `./packages-a` and `./packages-b` should just be different package locations for a single lerna project.

And if they _need_ separate node configs to even _work_, they should be in separate repositories. They aren't related, and they aren't sharing symlinks.
