### ISSUE TITLE
Private packages and publishing crashes

### ISSUE THREAD

**Issue by SimenB** [lerna/lerna#1160]
## Expected Behavior

Lerna should be able to perform a publish.

## Current Behavior

Lerna crashes with `No version number specified!`

## Steps to Reproduce (for bugs)

1. Clone https://github.com/facebook/jest (at the time of writing HEAD is https://github.com/facebook/jest/commit/036eb60400749d4a87dabbcd9d12ec74151e6ae6)
2. run `yarn`
3. run `yarn lerna publish` and pick some version
4. Hit enter

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.5.1",
  "version": "21.2.2",
  "npmClient": "yarn",
  "useWorkspaces": true
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

I got 
![image](https://user-images.githubusercontent.com/1404810/33885010-3e767570-df42-11e7-92d1-a2cace802bde.png)

So here: https://gist.github.com/SimenB/caccf53c73b4936820827b2933080d9f

</p></details>

## Context

I'm trying to use private packages in order to centrally manage dependencies.

It works with a project I have at work which uses independent versioning, but fails in Jest

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.3.2 |
| `node --version` | 8.9.3 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.5 |

**Comment by evocateur** [comment]
I believe this was fixed in #1145 + #1204. v2.7.1 has both fixes, and v2.8.0 is the latest.

**Comment by SimenB** [comment]
@cpojer FYI ^

**Comment by cpojer** [comment]
Woohooo! Thank you.
