### ISSUE TITLE
Consume canary publish automatically

### ISSUE THREAD

**Issue by mike-robertson** [lerna/lerna#1161]
I tried to read through the docs but I couldn't find an answer (if there is one that I missed, please close this issue). 

I've got a use case where I want to do a canary publish, but I also want to update all my packages to use those canary releases. It seems like when I do a canary publish right now, it doesn't update my packages `package.json` to consume the canary version I just published. Is this intended behavior? If so, is there a way to get this behavior outside of writing some script to update my packages to consume the canary release?

Thanks!

**Comment by MaxMilton** [comment]
Within your lerna repo the packages should be symlinked together once you `lerna bootstrap` so they're actually version independant — you get the current state of the files. It's in your external projects that you'll want to update the dep versions.

**Comment by evocateur** [comment]
Right now, because the `--canary` versions are _not_ incrementing properly (#277), you can't simply put a range in the dependency field (`^1.0.0-alpha.0`) and expect the resolution to "just work".

You can, however, do `lerna publish --cd-version prerelease` to get the sort of behavior you describe. However, one big caveat: it creates git tags and whatnot, which is not always desirable/possible from CI.

**Comment by christianevans214** [comment]
@evocateur Ahh I see! Should that be affecting publishing that occurs even with exact dependency fields? 

`prerelease` would potentially work for us, the only problem I can see is that we're publishing canary/prereleases in our CI builds, and we have multiple CI builds running in parallel as we trigger app dev deployment on merging into our develop branch. In this scenario, 2 engineers may unknowlingly try to publish the same npm prerelease version at the same time.

**Comment by alan-agius4** [comment]
@evocateur I don't know the whole flow around the `--canary` and why it uses the commit hash but wouldn't it make sense in order to avoid such issue to use `Date.now()` instead? as a version. it's always incremental and could avoid collision issues.

**Comment by christianevans214** [comment]
Sorry for the delayed response here! I guess what it comes down to for me is 
```
      if (this.options.canary) {
        this.logger.info("canary", "Resetting git state");
        // reset since the package.json files are changed
        this.repository.packageConfigs.forEach(pkgGlob => {
          GitUtilities.checkoutChanges(`${pkgGlob}/package.json`, this.execOpts);
        });
      }
```
this block of code in `publishPackagesToNpm`. Would it be possible to have some flag that doesn't revert the `package.json` files so that my circleCI builds would know how to appropriately point to the canary releases?

**Comment by christianevans214** [comment]
Yeah that's fair! I actually followed the comment you left above on using `--cd-version` and came up with a stop-gap that seems to be working for us. In our CI build, we run:
```
lerna publish --yes --skip-git --exact --cd-version=prerelease --preid=alpha.${COMMIT_SHA:0:6}
```
We get the latest git commit injected into our CI build anyways, so we can dynamically generate a preid similar to `--canary`, and all our package.jsons are updated accordingly ¯\\_(ツ)_/¯

**Comment by mike-robertson** [comment]
@christianevans214 I ended up doing something similar, but not quite as good. I'll definitely be modifying my process to be more in line with what you posted. I think the solutions raised here solve the use case without the need for the original ask, so I am closing this.
