### ISSUE TITLE
run command breaks when using chalk-cli

### ISSUE THREAD

**Issue by tobimx** [lerna/lerna#1162]
Hi,
I'am facing a small problem. 

In advance, I have to say that I benefit from the differences of `exec` and `run`.
Where run skips gracefully, exec fails on a missing task.
I defined some projects conventions on this behaviour.

Config:

~~~json
{
  "lerna": "2.5.1",
  "packages": [
    "packages/*"
  ],
  "command": {
    "publish": {
      "allowBranch": "master"
    }
  },
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true
}
~~~

Consider the following script in a package:

~~~json
{
  "scripts": {
    "task": "chalk bold yellow 'pending...'"
  }
}
~~~

`exec` works as expected.

**Using `run`, the task freeze.**

> The run task should work like exec if defined.

**Comment by evocateur** [comment]
`lerna exec` just executes whatever you pass to it, it never consults scripts in a given package directory. `lerna run` only calls the named script in packages that contain it. So the package that is freezing needs to have a dev dependency on `chalk-cli` for that task script to work.
