### ISSUE TITLE
The `--skip-git` and `--skip-npm` flags are not working when specified in `lerna.json`

### ISSUE THREAD

**Issue by fengyuanchen** [lerna/lerna#1165]
## Expected Behavior
The `--skip-git` and `--skip-npm` flags are working when specified in `lerna.json`.

## Current Behavior
The `--skip-git` and `--skip-npm` flags are **not** working when specified in `lerna.json`, but work fine when use directly in command: `lerna publish --skip-git --skip-npm`.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.5.1",
  "version": "independent",
  "commands": {
    "bootstrap": {
      "hoist": true
    },
    "publish": {
      "skip-git": true,
      "skip-npm": true
    }
  },
  "packages": [
    "packages/*"
  ]
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | - |
| `node --version` | 9.3.0 |

**Comment by fengyuanchen** [comment]
Just found the solution: should use `skipGit` and `skipNpm` instead of `skip-git` and `skip-npm` in `lerna.json`.

Do you plan to support both **camelCase** and **kebab-case**?

**Comment by evocateur** [comment]
Not at the moment, as kebab-case is a pain to use in JS (and is automatically camelized by yargs).
