### ISSUE TITLE
Lerna run removes colors from the output

### ISSUE THREAD

**Issue by BjornMelgaard** [lerna/lerna#1168]
## Expected Behavior
on `lerna run --scope=@ll2a/extension lint` I expect colorful output

## Current Behavior
![2017-12-17-20 02 59-screenshot](https://user-images.githubusercontent.com/7573215/34082364-502ee398-e365-11e7-97f5-93da06c2cf6b.png)

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.5.1",
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent"
}
```
</p></details>

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 5.5.1 |
| `yarn --version` | 1.3.2 |
| `node --version` | v8.9.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| NixOS | `Linux machine 4.9.63 #1-NixOS SMP Sat Nov 18 10:22:25 UTC 2017 x86_64 GNU/Linux` |

**Comment by bensampaio** [comment]
is there any workaround for this?

**Comment by rileylnapier** [comment]
I ended up using jest from the root dir instead which was the command I
wanted colors

**Comment by evocateur** [comment]
Thing is, when `lerna run` executes the npm lifecycle, it's a subprocess that isn't technically a TTY and thus almost all CLI color modules (`chalk`, etc) will automatically disable colors.

Pass `--stream` to `lerna run` and it will pipe the output through, which should restore the colors.

**Comment by mAiNiNfEcTiOn** [comment]
@evocateur unfortunately no. The only colors passed to the terminal are the 'labels' defining which process is logging.

**Comment by mAiNiNfEcTiOn** [comment]
So my solution was to run `lerna exec -- npm run <task>`. That runs it as a TTY which retrieves the colors.

**Comment by jonaskello** [comment]
@mAiNiNfEcTiOn Thanks for the workaround, works fine for me with mocha and jest :-).

**Comment by jonaskello** [comment]
The only drawback of the workaround that I can find is that `lerna run` will only run the script for the packages that have it, while for `lerna exec -- yarn run foo`, the foo script needs to be in every package to not fail with an error.

**Comment by evocateur** [comment]
Literally all `--stream` does is pipe the stdout directly into the parent process. It's not doing any stripping of color whatsoever. It is the wrapped CLI itself that is not detecting TTY, and thus disabling color (a reasonable default given color escapes are garbage output in most non-interactive terminal situations).

Solutions:
* Pass explicit options (e.g, `--color`) to the wrapped CLIs so that they _always_ output color escapes
* Run tests from the root, which is half the point of lerna in the first place.

**Comment by jonaskello** [comment]
Yes, `--colors` works with both mocha and jest, thanks for explaining that! 👍 

> Run tests from the root, which is half the point of lerna in the first place.

I'm not sure what this means. Do you mean have one test script in the root package.json that runs tests for all packages rather than putting test scripts in each sub-package's package.json?

**Comment by evocateur** [comment]
Yes, eslint and jest from the root are almost trivially easy to set up, and even faster to run (with appropriate caching, in eslint’s case). Otherwise you’ve got tons of duplication in every leaf package, increasing the burden of maintenance.

All of your devDependencies should be moved to the root package.json, regardless of whether or not you hoist the dependencies (lerna bootstrap --hoist).

**Comment by jonaskello** [comment]
I have all devDependencies in the root package.json and I am using yarn workspaces so I have hoisting. But I still have scripts in each package.json that is run through `lerna run`. Are you suggesting to move all scripts (test, start, build etc.) to the root package.json too, so the sub-packages have nothing in the script section? In which case, how do you run the scripts? Using `lerna exec`? (Sorry for going off-topic a bit, just curious to understand the recommendations).

**Comment by evocateur** [comment]
All the test/build scripts are run from the root, with normal npm/yarn commands, using config that allows them to find the relevant files under the workspace targets (which no longer have any devDependencies). Lerna run/exec becomes largely unnecessary, and indeed the scripts block can be removed entirely.

**Comment by jonaskello** [comment]
Got it, thanks for taking the time to explain :-).

**Comment by paradite** [comment]
Encountered a very strange behaviour with `jest`, passing `--color` to `yarn test` makes jest output color when executed via `lerna`.

However, if I pass `--colors` to `yarn test`, which is documented by jest(https://jestjs.io/docs/en/cli.html#colors), then it outputs color, but also makes the process impossible to terminate (pressing control+C goes back to the terminal, but jest continues to run and output to the terminal).

I wonder if `--color` is being interpreted different by `lerna` or `yarn`?

**Comment by satyamgupta** [comment]
@paradite It works for me somehow, I can terminate the process and output also stops 🤔

**Comment by sibelius** [comment]
we should use lerna exec instead of lerna run to get colors?
