### ISSUE TITLE
Config option for ignoring packages to bootstrap

### ISSUE THREAD

**Issue by thejameskyle** [lerna/lerna#117]
https://github.com/babel/babel/pull/3438#discussion_r57091960

**Comment by rygine** [comment]
A few questions about this issue:

1. Should the `ignore` option work for all commands?
2. Should ignored packages also be removed from the packageGraph?
3. Is logging ignored packages helpful? If so, is it ok to use the logger within a utility?
4. Is supporting globs desirable?
5. Would it he helpful to add an `ignorePackages` config option to `lerna.json` to configure package exclusion per command?

Here's the current diff: https://github.com/kittens/lerna/compare/master...rygine:ignore-packages

Just trying to get an idea of the scope of this.

**Comment by thejameskyle** [comment]
> 1. Should the `ignore` option work for all commands? (this may duplicate the new ignore option for publishing on the publish command)

No we definitely don't want to go down the path of that, although it does raise a concern about the naming.

```js
{
  publishConfig: { ignore: ["path/to/file"] },
  bootstrapConfig: { ignore: ["package-name"] }
}
```

This doesn't read well... Idk what to call it though.

> 2. Should ignored packages also be removed from the packageGraph?

I haven't really thought through the implementation. However, removing it from the `packageGraph` means you just never have access to that information which could cause problems down the road when we try to implement something else so I guess I would prefer that it didn't.

> 3. Is logging ignored packages helpful? If so, is it ok to use the logger within a utility?

If you could log it in as `debug` information that would be useful for the `lerna-debug.log` files that get output on errors. And the logger already gets used in utilities so yeah that's fine.

> 4. Is supporting globs desirable?

I don't think that's necessary.

> 5. Would it he helpful to add an ignorePackages config option to lerna.json to configure package exclusion per command?

I'm not sure what you mean by this, but I don't think we should add ignore to every command right now.

**Comment by hzoo** [comment]
We can move this issue to the PR https://github.com/lerna/lerna/issues/160

**Comment by thejameskyle** [comment]
You mean #168?

**Comment by hzoo** [comment]
Oops.. yeah must of copied the wrong one.
