### ISSUE TITLE
npmClientArgs --verbose isn't logged on lerna bootstrap

### ISSUE THREAD

**Issue by payload** [lerna/lerna#1170]
This line should be `spawn`, because `exec` isn't piping the log to stdout/err, right?

https://github.com/lerna/lerna/blob/d35c7aa0875013248f55b26487eac99d55b59a78/src/NpmUtilities.js#L40

**Comment by scythargon** [comment]
+1 here

**Comment by abelkbil** [comment]
+1

**Comment by benminer** [comment]
+1
