### ISSUE TITLE
Can I use local lerna packages as scripts on the root of the repository ?

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#1174]
Hello,

I have a lerna monorepo with a couple of packages that are command line commands. I can link those packages and they work fine. I was wondering if it is possible to use those packages (without executing npm link on any of them) like they were installed as dev-dependencies from the root of te repository. Let me explain with an example:

I have a monorepo with two packages, `pkg-one`, `pkg-cmd`. The second one (`pkg-cmd`) has a bin section, which allows it to be executed as a cmd script. What I want to do is to have an npm script on my root package.json that just executes `pkg-cmd` as it were installed as a dev-dependency, just like you do with your test suite, for example.

Hope I've been clear.
Regards

**Comment by evocateur** [comment]
If it's not possible now, I definitely want to make it so in the near future, as lerna itself moves to a multi-package setup. I was going to experiment with local `file:` dependencies, see what happens.

**Comment by gziolo** [comment]
That would be awesome. We are trying to do the same for https://github.com/@WordPress/packages. At the moment we need to reference the script using local path like this:
https://github.com/WordPress/packages/blob/fdd1458e3d38c1e067ffdcac3b193bf57cd2c910/package.json#L32

**Comment by gziolo** [comment]
@evocateur, why aren't those packages linked inside the top level `node_modules` folder? I think it could help to solve this issue and other similar unexpected errors when using `--hoist` flag like this error:
https://github.com/WordPress/packages/pull/68#discussion_r165029336

**Comment by evocateur** [comment]
You can, if the targeted package (and all of its dependencies) are regular boring commonjs that can be laid out by npm. I wouldn’t recommend otherwise.

**Comment by gziolo** [comment]
Are there plans to add a flag which would teach Letna to do it as part of the bootstrap command?

**Comment by evocateur** [comment]
Probably not. I’m working on some mad science to completely remove the bootstrap command, which seems more worthwhile, tbh.

**Comment by danielo515** [comment]
@evocateur how do you plan to do that? Currently I'm using some post install scripts and it is not a top priority for me (at least)

**Comment by gziolo** [comment]
@danielo515 I'm about to do the same. Use post-install scripts to npm link all I need to use in the root folder.

**Comment by evocateur** [comment]
With npm5: Make all sibling dependencies in the leaves relative `file:` specifiers, and `npm install packages/*` in the root. That replaces `lerna bootstrap` entirely, automatically hoisting everything into a package-lock.json.

I’m working on making `lerna publish` capable of rewriting the relative links into the linked package’s semver range (without committing that temporary change). Just gotta write some tests/docs and I can cut the first 3.0 alpha.

**Comment by ntwb** [comment]
I'd rather have a solution that doesn't involve `package-lock.json`, I added a note in #1235 on how to stop generating `package-lock.json` files for Lerna that seems to be working currently.

So much so I plan on removing the lockfiles from the @wordpress/packages repo next week.

Via https//github.com/sindresorhus/ama/issues/479#issuecomment-310661514
> _"Lockfiles for apps, but not for packages. Lockfiles are great for apps where you want a controlled reproducible environment, but for packages this doesn’t make much sense. The `package-lock.json` files in dependencies are ignored, so the lockfile only applies when users run `npm install` in the package repo. If you use a lockfile for packages, your local dependency tree will not match the dependency tree of users having your package as a dependency. This can potentially cause problems if one of your package dependencies breaks your package in a patch release. The lockfile will prevent you from seeing the problem locally, but it will affect your users.”_

I went further and wrote about this further on my blog last week [Lockfiles break semantic versioning](
https://netweb.blog/2018/01/26/lockfiles-breaks-semantic-versioning/)

**Comment by danielo515** [comment]
I would prefer to avoid lock files atall cost. If lerna stars to rely on then I'll be forced to lock myself to version 2.

@gziolo I was talking about the bootstrap, not the linking. Currently I'm not doing anything on that regard

**Comment by gziolo** [comment]
> @gziolo I was talking about the bootstrap, not the linking. Currently I'm not doing anything on that regard

No worries. It turns out the only thing we need is:

```sh
#!/usr/bin/env bash

lerna bootstrap --hoist

npm link packages/browserslist-config
npm link packages/jest-preset-default
```

Probably we need a smarter way to automatically create all links :)

**Comment by gziolo** [comment]
Well, I finally decided to create all symlinks myself:

```sh
#!/usr/bin/env bash

mkdir -p node_modules/@wordpress
ln -sf ../../packages/browserslist-config node_modules/@wordpress
ln -sf ../../packages/babel-preset-default node_modules/@wordpress
ln -sf ../../packages/jest-preset-default node_modules/@wordpress
ln -sf ../../packages/scripts node_modules/@wordpress
ln -sf ../@wordpress/scripts/bin/wp-scripts.js node_modules/.bin/wp-scripts
```

See related PR and the reasoning behind this decision: https://github.com/WordPress/packages/pull/77.

**Comment by DavideDaniel** [comment]
The poor rollout of npm5 and the lack of resources behind the client has veered us away from npm5 to yarn. A huge issue has been npm5's `link` which has exacerbated linking issues when working with multiple repos. It maybe that this exacerbated by `bootstrap`, so I can see why you're going down this path, but what about projects that do not use npm5 in favor of yarn?

**Comment by evocateur** [comment]
Use yarn workspaces?

**Comment by DavideDaniel** [comment]
```
How does it compare to Lerna?

Yarn’s workspaces are the low-level primitives that tools like Lerna can (and do!) use. They will never try to support the high-level feature that Lerna offers, but by implementing the core logic of the resolution and linking steps inside Yarn itself we hope to enable new usages and improve performance.
```
https://yarnpkg.com/lang/en/docs/workspaces/#toc-how-does-it-compare-to-lerna

**Comment by jalal246** [comment]
Is there any solution yet to this issue?

As @gziolo suggested I used `npm link scripts/foo` in root but not sure if this this the best way to do it. Also it works locally but failed with `Travis` build  `Missing write access to /home/travis/build/username/prject/node_modules/foo`

**Comment by ezhikov** [comment]
Hi. Will there be any solution to this problem except for explicit linking?

**Comment by danielo515** [comment]
Not as far as I know. Maybe @stale[bot] has an answer ,since he closed the issue ...

**Comment by evocateur** [comment]
I use `lerna` from within the lerna monorepo like, all the time? So I'm not sure what else there is to do to support this. Just `npm i ./path/to/my-awesome-cli`, and now `my-awesome-cli` is available to `npx` and npm lifecycle scripts.

**Comment by danielo515** [comment]
@evocateur but you are doing that on the root of the monorepo or on specific packages?

**Comment by evocateur** [comment]
Yes, from the root.

**Comment by liuwenzhuang** [comment]
test
