### ISSUE TITLE
Lerna Publish should first check if publishing is possible

### ISSUE THREAD

**Issue by ibratoev** [lerna/lerna#1177]
Currently, Lerna publish starts publishing to npm and git without checking for potential git problems like git remote branch being ahead.

This can lead to consistency issues. 

In our scenario, we run a CI build on each push to master that calls: `lerna publish --exact --cd-version minor --yes`. If we merge 2 PRs quickly the CI build is stuck. What happens:
* After we merge 2 PRs quickly -> publish is called for the first build -> npm packages are published successfully with the new version but the git push fails.
* On the next build -> publish is called -> it uses the same version as the previous build because git push failed last time -> npm publishing fails because the same version already exists.

## Expected Behavior
npm packages should not be published if git remote branch is ahead.

## Current Behavior
npm packages are published even though git push is impossible.

## Possible Solution
Check if git push is possible before npm publish. Consider a flag if the build should fail.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.5.1",
  "packages": [
    "packages/*"
  ],
  "version": "1.17.0",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 3.10.10 |
| `yarn --version` | 1.3.2 |
| `node --version` | v6.11.5 |

**Comment by vzaidman** [comment]
I'd also suggest to do `npm whoami` to see if the npm publishing stage is possible.

**Comment by evocateur** [comment]
#1317 fixed the "upstream ahead of local clone" problem, we still don't have preflight npm checks (such as `npm whoami`, etc).
