### ISSUE TITLE
Bootstrap --skip-npm support

### ISSUE THREAD

**Issue by Andarist** [lerna/lerna#1178]
I'd like to be able to run a bootstrap without it executing any prepublish/prepare/etc scripts. Just install deps + link them.

I'm willing to implement this, just would like to establish what needs to be done - name of the option, what it should do etc.

**Comment by evocateur** [comment]
I think matching npm's `--ignore-scripts` flag would be fine. A simple early exit based on `this.options.ignoreScripts` in [`runScriptInPackages()`](https://github.com/lerna/lerna/blob/31b82fc7cf2938b8cea26694bac4aa16decc8265/src/commands/BootstrapCommand.js#L175) should do it.

Thanks for reminding me to remove the `prepublish` execution during bootstrap (for 3.0), it's clearly not necessary there.
