### ISSUE TITLE
[Question] Using lerna with --use-git-version flag

### ISSUE THREAD

**Issue by chinchang** [lerna/lerna#1179]
From the docs (https://github.com/lerna/lerna#--use-git-version):

>This allows packages to be distributed via git repos if eg. packages are private and private npm repo is not an option.

Does this also mean that with `use-git-version` flag lerna should publish the packages on git instead of npm registry? Confused because I found no such code in the publishCommand file.

**Comment by zenflow** [comment]
@chinchang Yes, I believe that's the idea. Check https://github.com/lerna/lerna/pull/1033#issuecomment-335894690 for a bit more info.

**Comment by evocateur** [comment]
I really have no idea, I assume `--use-git-version` folks always use `--skip-npm` when they call `lerna publish`, so the git tags get propagated but the registry is never sent a package tarball. I don't altogether understand the use-case, to be honest.

**Comment by evocateur** [comment]
To be clear, Lerna will never actually do all that complicated git stuff for you. It just modifies the version pins appropriately.
