### ISSUE TITLE
Get rid of dependency to pinkie-promise

### ISSUE THREAD

**Issue by czuendorf** [lerna/lerna#1182]
Lerna has a dependency to pinkie-promise
https://github.com/floatdrop/pinkie-promise
, which seems somehow like troll project.

https://status.npmjs.org/incidents/41zfb8qpvrdj

Please check out the developer profile on GitHub:
https://github.com/floatdrop?tab=overview&from=2017-03-14
A lot of extreme simple projects, which are intended to be used in many projects, to cause a lot of harm in case when module is deleted.

Also check out  the dependency graph of Lerna:
http://npm.anvaka.com/#/view/2d/lerna

And also these articles about todays issue:
https://news.ycombinator.com/item?id=16087024
https://github.com/npm/registry/issues/255

Package Pinkie-Promise is required through

Lerna 
->
https://github.com/sindresorhus/globby
->
https://github.com/sindresorhus/pify
->
https://github.com/floatdrop/pinkie-promise

>
## Expected Behavior

I want to install lerna via npm

## Current Behavior

I could not install lerna via npm for hours, because somebody (the developer?) deleted the package "pinkie-promise" from npm. It is not clear whether the developer intended to have such an impact on so many npm projects by deleting, but I assume he did.

## Possible Solution

Get rid of the dependency to pinkie-promise.

## Steps to Reproduce (for bugs)

1. https://github.com/lerna/lerna/blob/master/package.json#L49
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
http://blog.npmjs.org/post/169432444640/npm-operational-incident-6-jan-2018
