### ISSUE TITLE
Publishing tags with indipendent packages

### ISSUE THREAD

**Issue by equinusocio** [lerna/lerna#1189]
Hi, i'm working on a project that have indipendent scoped packages. When i run
```bash
lerna publish --conventional-commits
```
It generate and push separated git tags for each updated packages. There is a way to skip only the tag generation or generate one tag for release?

I know there is `--skip-git` but this will skip committing, tagging, and pushing git changes...

**Comment by evocateur** [comment]
That's pretty much the tradeoff of using `--independent` versioning: the tags are much more verbose. Using the default "fixed" versioning only uses one tag per release, because it only uses one version per release (e.g., `v2.0.3`).

There's no way around it, sorry.

**Comment by equinusocio** [comment]
What about skipping all git commands and do it manually? What are the git commands that `—skip-git` skip?
