### ISSUE TITLE
Bootstrap fails when using the locally installed version of lerna, yarn, and private registries

### ISSUE THREAD

**Issue by cappslock** [lerna/lerna#1190]
When bootstrapping with Lerna (using Yarn as the npm client and with each package having a private repository) it fails when running with the version of Lerna installed locally and succeeds when running the global Lerna.

## Expected Behavior
Bootstrap succeeds regardless of whether Lerna is run with the local binary or the global binary.

i.e. these two commands both succeed:
```
yarn lerna bootstrap
lerna bootstrap
```

## Current Behavior
Running locally with yarn fails to use auth specified in .npmrc. Running globally works.

## Steps to Reproduce (for bugs)
1. Set up a monorepo with a package with a dependency in a private registry. Use yarn as the npmClient.
2. Set up an .npmrc for the package pointing to the private registry. Include auth.
3. Run `yarn install` in the _package_, not the monorepo (just to generate the yarn.lock file, which will include the private registry)
4. Run yarn lerna clean to remove the installed node_modules
5. Clean your yarn cache `yarn cache clean` (to remove the cache of the private package)
6. In the monorepo root, run `yarn lerna bootstrap`. The install will fail with a 401.
7. Clean cache again. Now run `lerna bootstrap`. The install will succeed.
```

## Your Environment
Lerna 2.5.1
Yarn 1.3.2
Node 8.9.1

OS X, High Sierra or whatever the hell

**Comment by cappslock** [comment]
@evocateur just tested with 2.7.1, no change in observed behavior unfortunately :(

**Comment by evocateur** [comment]
Yeah, I would raise it with yarn folks, I really don't have great insight into their codebase.

**Comment by cappslock** [comment]
Will do. Looks like 1.4 touches on some related things so hopefully that resolves it.

I'm not totally sure Lerna isn't involved somehow, since a direct yarn install works fine, but I'll report back after 1.4 is released.

**Comment by mflodin** [comment]
We also had this issue. We updated to the latest version of yarn (1.5.1) and then it worked. Before we had 1.3.2, so not sure which version it actually got fixed in, but at least now it works.

**Comment by dballance** [comment]
Adding another data point. I do believe this is a `yarn` issue, and not a lerna issue. 

https://github.com/yarnpkg/yarn/issues/4451#issuecomment-410384607

**Comment by evocateur** [comment]
Please re-open if the yarn issue is resolved and the problem persists with `lerna`.
