### ISSUE TITLE
Nested packages not installing all dependencies

### ISSUE THREAD

**Issue by seanlandsman** [lerna/lerna#1191]
## Expected Behavior

I have a project that a number of sub-projects within it, each with its own package.json:
```
package
       |- package-1
       |- package-2
               |-  sub-package-1
                       |- package.json
               |-  sub-package-2
                       |- package.json
```

When I run lerna bootstrap I'd expect each package & sub-package to have their respective node_modules populated with the contents of their respective package.json

## Current Behavior

When I run lerna bootstrap, I get a message that says: Package name "package-2" used in multiple packages

And once done sub-package-1 & sub-package-2 will have package-1 under node_modules, but none of the other dependencies in the respective package.json

I kind of understand why this is happening and I'd imagine if I broke package-2 into separate project this would work, but that's not really an option for me

## Possible Solution

I'm not sure this is actually a bug or not - it's entirely possible that this scenario simply isn't supported

## Steps to Reproduce (for bugs)

<details><summary>lerna.json</summary><p>

I've tried these two configs so far:

```json
{
  "lerna": "2.5.1",
  "packages": [
    "packages/*"
  ],
  "version": "15.0.0"
}
```
```json
{
  "lerna": "2.5.1",
  "packages": [
    "packages/package-1",
    "packages/package-2/sub-package-1",
    "packages/package-2/sub-package-2",
  ],
  "version": "15.0.0"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 4.1.2 |
| `yarn --version` | 1.3.2 |
| `node --version` | v7.7.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS High Sierra | 10.13.2 |

**Comment by evocateur** [comment]
The packages managed by lerna need to be valid npm packages in their own right. That is, you should be able to put the packages in a separate repo and publish them to npm and whatnot. The structure you are proposing does not pass that test.

A nested _tree_ of packages _is_ supported. With this config:
```json
{
  "lerna": "2.5.1",
  "packages": [
    "packages/**"
  ],
  "version": "1.0.0"
}
```
this tree will produce three packages
```
packages/
  app/
    foo-app/
      package.json
    bar-app/
      package.json
  ui/
    baz-ui/
      package.json
```
