### ISSUE TITLE
[conventional-commits] Add a flag to disable conventional-recommended-bump

### ISSUE THREAD

**Issue by apapko** [lerna/lerna#1195]
Context: lerna publish --conventional-commits

As a developer i would like to have an ability to disable _conventional-recommended-bump_ when using --conventional-commits flag during release.
For less-mature projects, it is beneficial to have control over how release versions get incremented. However, lerna _--conventional-commits_ uses _conventional-recommended-bump_ by default to increment release version. It would be great to have an ability to disable it and use interactive version prompt instead ( as it is now when --conventional-commits are not used ).

## Expected Behavior
Allow to run --conventional-commits without recommended-bump ( interactive version prompt instead )
example:
```
lerna publish --conventional-commtis --disable-recommended-bump
```
or perhaps this:
``` 
lerna publish --conventional-commit --version-prompt
```

**Comment by evocateur** [comment]
Why bother with `--conventional-commits` at all if you don't want it to compute the bump?

Incidentally, you can pass `--cd-version <semver-keyword>` (using some unstable-sounding keyword like "preminor" or "prepatch" or "prerelease") to pre-empt the angular fix/feat/breaking calculation. The changelog generation should still work, if that's the only reason you're using `--conventional-commits` in this context.

| Starting Version | `lerna publish` Flags | Result |
| ---------------- | --------------------- | ------ |
| v0.1.0 | `--cd-version preminor --preid beta` |  v0.2.0-beta.0 |
| v0.2.0-alpha.0 | `--cd-version prerelease` | v0.2.0-alpha.1 |

**Comment by diegohaz** [comment]
@evocateur Please, correct me if I'm wrong. The problem I see with your suggestion is that whether you publish all packages as `alpha` or none of them.

In https://github.com/reakit/reakit I wanted to publish only one of my packages as alpha. My solution was to [patch](https://github.com/reakit/reakit/blob/next/patches/%40lerna%2Bversion%2B3.13.1.patch) `@lerna/version` to disable the recommended version bump.

It seems to work fine, but it would be better if lerna supported it.
