### ISSUE TITLE
Add %v as placeholder in commit message

### ISSUE THREAD

**Issue by mojavelinux** [lerna/lerna#1196]
## Expected Behavior

I would like to reference the version number in the commit message without a leading v. I could do so if lerna substituted the placeholder %v with the version.

%s = v1.0.0
%v = 1.0.0

## Current Behavior

The only placeholder in commit messages lerna currently supports is %s. This value is the version with a leading "v". There's no way to reference just the version itself.

## Possible Solution

The solution is to provide a custom commit message that includes the version string. But then you have to hardcode the version.

## Steps to Reproduce (for bugs)

Run lerna publish with a custom commit message:

```sh
$ lerna publish --message="release version %s"
```

See that the commit message appears as:

```
release version v1.0.0
```

## Context

I want to be able to reference the version number without the leading "v" using:

```sh
$ lerna publish --message="release version %v"
```

which would result in:

```
release version 1.0.0
```

## Your Environment

lerna: 2.6.0
npm: 5.5.1
node: 8.9.4

**Comment by evocateur** [comment]
I suppose that's fair. `%v` to indicate _lack_ of preceding "v" is a little confusing to me, but they're all arbitrary strings anyway and documentation will clarify in any event. PRs welcome!

**Comment by mojavelinux** [comment]
Actually, I would argue it makes a lot of sense because it contains just the version. It's very clear in the docs that the tag includes a leading "v", which would make it not part of the version.

PR sent!

**Comment by evocateur** [comment]
That’s a good point, I didn’t think about that.
