### ISSUE TITLE
devDependencies should not encounter cycles in deps graph

### ISSUE THREAD

**Issue by zxqfox** [lerna/lerna#1198]
I have this structure with cross-dependencies:
```
packages/
  a/
    package.json: `{ dependencies: { 'b': '*' } }`
  b/
    package.json: `{ devDependencies: { 'a': '*' } }`
```

## Expected Behavior

No error because `b` relies on `a` only for development purposes.

## Current Behavior

> lerna WARN ECYCLE Encountered a cycle in the dependency graph.This may cause instability! Packages in cycle are: "a", "b"

<details>
<summary>Real life output:</summary>

It's from https://github.com/bem/bem-sdk repo

> lerna WARN ECYCLE Encountered a cycle in the dependency graph.This may cause instability! Packages in cycle are: "@bem/sdk.bemjson-to-decl", "@bem/sdk.bemjson-to-jsx", "@bem/sdk.bundle", "@bem/sdk.cell", "@bem/sdk.decl", "@bem/sdk.deps", "@bem/sdk.entity-name", "@bem/sdk.file", "@bem/sdk.graph", "@bem/sdk.naming.cell.stringify", "@bem/sdk.naming.entity.parse", "@bem/sdk.naming.entity.stringify", "@bem/sdk.naming.entity", "@bem/sdk.naming.file.stringify", "@bem/sdk.walk"
> lerna sill packages [ '@bem/sdk.entity-name' ]

It's pretty annoying ;-(

</details>

## Possible Solution

Detect what kind of link between nodes (packages) we have while calculating cycles in dependency graph.
Make a difference between strict dependency/devDependency cycles and mixed ones (like in this case). Change level from `warn` to `verbose` for this case. 

## Steps to Reproduce (for bugs)

Make a structure like in example and run `lerna bootstrap`.

Or use real life example:
1. git clone https://github.com/bem/bem-sdk.git bem-sdk-test
2. cd bem-sdk-test
3. git checkout 62b46eb89f8200ddf1fc06ca7e743d9f3f77da5a
4. lerna bootstrap

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.7.0",
  "packages": [
    "packages/*"
  ],
  "hoist": true,
  "independent": true,
  "version": "independent"
}
```
</p></details>

## Context

Each time I run `bootstrap` command I see few warns with huge messages about cycles.
If I'll see this each time I can miss real true positive warns about cycles. 

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | v2.7.0 |
| `npm --version`  | v8.4.0 |
| `yarn --version` | — |
| `node --version` | v5.4.1 |

| OS | Version |
| --- | --- |
| macOS X El Capitan | v10.11.6 |

**Comment by evocateur** [comment]
The warning is still valid from lerna's perspective, as there is no (maintainable) way to tell if the circularity is bad (except of course it is, circularity is _always_ bad). The fact that one _can_ employ circular dependencies in Node is not a reason _to_ employ circular dependencies in Node. In my experience they are almost always a failure of module design, and perhaps one-in-a-million _on purpose_.

**Comment by evocateur** [comment]
Note: `devDependencies` vs `dependencies` is a distinction without a difference when it comes to this circularity warning. It's not warning about runtime, it's warning about bootstrap instability.

**Comment by jasonbarone** [comment]
What is the recommended method to handle circular dependencies? There are plenty of use cases where this makes sense, but I'm having trying finding a system that works. My example is similar to OP. My monorepo has tooling packages used for the development of the components in the same monorepo. Is there a way to do that without running into the circular graph, which is full of issues?

**Comment by evocateur** [comment]
I struggle to identify a single use case where circularity is _preferred_. Tools certainly should not have dependencies on the packages they help build/develop. If they do, there is almost always a better module boundary to be drawn.

**Comment by psirenny** [comment]
> I struggle to identify a single use case where circularity is preferred. Tools certainly should not have dependencies on the packages they help build/develop. If they do, there is almost always a better module boundary to be drawn.

I have a tools package that I use to build several other modules such as remark presets, etc. It would be helpful to be able to apply those built modules to the original builder package for things like linting it's readme file, etc. I've run into a bunch of use cases like that. My solution thus far has been to just maintain duplicate code in multiple packages (prone to error) or short circuit lerna and require code by file path manually.

**Comment by evocateur** [comment]
Duplicate code in multiple packages is begging for extraction into a separate package. Whether or not the relationship is defined in `devDependencies` is irrelevant.

**Comment by jasonbarone** [comment]
Yea these are great points. For what it's worth, my use case is a UI dev canvas similar to Storybook.js, where the UI tool is also built using the UI elements created with the UI tool kit itself. The tool and UI components follow the same design system. For now I've opted to dupe the UI elements into the UI dev tool. Not ideal though.

**Comment by Igmat** [comment]
@evocateur, I can't agree with you that circular dependency is always bad.

I'm working on [testing tool](https://github.com/Igmat/baset) and it is used to test itself, which seems to be as fully reasonable solution.

**Comment by evocateur** [comment]
@Igmat That's fine, disagree with me. Lerna won't agree with you.

**Comment by Igmat** [comment]
@evocateur, wow... Kinda unexpected reaction to normal user feedback. Ok, I won't bother you no longer...
