### ISSUE TITLE
Lerna hangs when trying to publish

### ISSUE THREAD

**Issue by ChrisBAshton** [lerna/lerna#1201]
When running `lerna publish` and more than one package has updated, Lerna hangs on the second package and I have to quit the terminal.

Searched for a while but nobody else seemed to have the problem. Then I figured it was a problem with the prompt library so did some Googling.

Turns out it's a known issue with Inquirer.js - https://github.com/SBoudrias/Inquirer.js/issues/547 - and the solution is to upgrade to at least Node v8.1.2 (I was on Node v8.1.0).

Thought I'd open and close the issue so that other people who Google problems with Lerna publishing might find this useful. Apologies if this is a little unorthodox!

**Comment by evocateur** [comment]
Wow, that's a niche bug. Thanks for the notice!
