### ISSUE TITLE
Possibility to publish the same package with multiple names?

### ISSUE THREAD

**Issue by Sharaal** [lerna/lerna#1203]
Maybe there is already a solution, is this the case, a hint would be very nice, because I didn't found something. :)

## Expected Behavior
I currently use lerna and looked for a approach how it's possible to publish a package with multiple names, e.g. a global name like `example` and a scoped name `@example/example`.

## Current Behavior
`name` in the `package.json` can only be a string.

## Possible Solution
`name` in the `package.json` can be an array of strings. Lerna will publish the package for every name automatically:
```
{
  "name": ["example", "@example/example"]
}
```

**Comment by evocateur** [comment]
No, that's not possible in npm (it's not a lerna issue, basically). A package has one name.
