### ISSUE TITLE
[Feature] Does not work with optionalDependencies

### ISSUE THREAD

**Issue by nolanlawson** [lerna/lerna#121]
If one module is an `optionalDependency` of the other (rather than a `dependency`), then Lerna does not link them together.

Our use-case for this in PouchDB is that sometimes we have native dependencies (e.g. `leveldown`) that users struggle to install on certain hardware, so we make it optional so it doesn't completely block them.

I'll try to get to this when I get a chance, but filing the issue to make a note of it.

**Comment by thejameskyle** [comment]
This should just require updating:

- https://github.com/kittens/lerna/blob/3f84f9a19c76043441655120b66f65db46883997/src/commands/PublishCommand.js#L240-L243
- https://github.com/kittens/lerna/blob/9246f288b57122bbf1121d4b6910c2232baf35c5/src/Package.js#L30-L49

**Comment by nolanlawson** [comment]
Nice! Probably just a user error on my part.

**Comment by hzoo** [comment]
It's good now?

**Comment by nolanlawson** [comment]
I'll check when I get a chance, but it sounds like it!

**Comment by thejameskyle** [comment]
No it's definitely not supported. I was saying that in order to support it those places need to be updated.

**Comment by hzoo** [comment]
If that's it, https://github.com/lerna/lerna/pull/191
