### ISSUE TITLE
Bug: Lerna prerelease publish menu provides incorrectly incremented version

### ISSUE THREAD

**Issue by pzrq** [lerna/lerna#1214]
## Expected Behavior

As per [node's implementation](https://www.npmjs.com/package/semver) of [prerelease semver](https://semver.org/#spec-item-9), Lerna should provide a `1.x.y-0`, `1.x.y-1`, ... version option in its publish menu.

## Current Behavior

As seen [here](https://github.com/mongodb-js/hadron-react/pull/10#issuecomment-358536006), lerna actually provided me with a `1.x.y+1-0` option instead of the `1.x.y-1` option I expected.

## Steps to Reproduce (for bugs)

1. (Might be optional) [Add 2FA](https://docs.npmjs.com/getting-started/using-two-factor-authentication) to an npm account
2. NPM_CONFIG_OTP=<YOUR_OTP> lerna publish --npm-tag=beta

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "lerna": "2.6.0",
  "version": "1.13.1-0",
  "packages": [
    "packages/*"
  ]
}
```
</p></details>

## Context

As I was in the middle of using [`NPM_CONFIG_OTP`](https://github.com/lerna/lerna/issues/1137#issuecomment-353547051), had at most 30 seconds and was not sure if it would work at all, I decided to publish anyway.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.6.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 0.16.1 |
| `node --version` | v8.9.4 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.2 |

**Comment by evocateur** [comment]
Yeah, we haven't adapted to OTP yet, sorry.

```bash
$ npx semver --increment prerelease --preid beta 1.13.0
1.13.1-beta.0
```

We literally call node's semver implementation [here](https://github.com/lerna/lerna/blob/6080e6b5b029714acc47a8489d35589e61542704/src/commands/PublishCommand.js#L503-L504), and that's what we get. The section on [prerelease identifiers](https://www.npmjs.com/package/semver#prerelease-identifiers) disagrees with your assertion that `1.x.y-1` was the expected result of a prerelease of `1.x.y`.

Judging by the commit history in hadron-react, perhaps you didn't have an existing `--preid` of "beta" yet, and thus the existing `1.13.0-0` got confused? It's a little hard to tell what was intended by the publish commits (which is really on us, since we don't record the command executed anywhere, like, say, the footer of the commit message...)

**Comment by mAAdhaTTah** [comment]
I think I'm running into a similar situation. I'm using lerna 3.0.0.rc-0, and I'm attempting to publish the first prelease version of what will eventually be 1.0.0 (so 1.0.0-alpha.0). I did the bump itself [in this commit](https://github.com/valtech-nyc/brookjs/commit/28b8668b2495c0ae603600392571db72e75d8e9c), but when I run the command as shown in `package.json` with `yarn pub`, I see the below:

<img width="426" alt="jamesdigioia_jamesdigioia-macbook-pro__users_jamesdigioia_code_javascript_brookjs__node_" src="https://user-images.githubusercontent.com/4371429/43619370-5b8b0110-969b-11e8-98d0-222fd076c82d.png">

Selecting prerelease gives me this:

<img width="500" alt="jamesdigioia_jamesdigioia-macbook-pro__users_jamesdigioia_code_javascript_brookjs__node_" src="https://user-images.githubusercontent.com/4371429/43619382-6a2fb396-969b-11e8-9c0c-690cb7872051.png">

I feel like I'm missing something obvious. Ideas?

**Comment by evocateur** [comment]
By selecting "Prerelease", you need to enter a string like "alpha" or "beta". Admittedly, that particular option is not well-tested.

**Comment by mAAdhaTTah** [comment]
I set `preid` in the command config in `lerna.json`. Also, it doesn't allow me to specify `1.0.0-preid.0`; it looks like it's going to stick it on the end of `0.11.7`.

**Comment by evocateur** [comment]
Okay, so in that case what you really want is the "Premajor" choice, except it doesn't appear to be using the `--preid` option, which is definitely a bug. The perils of a poorly-tested feature...
