### ISSUE TITLE
When publishing updated packages in --independent mode, the top level package.json does not update with newest versions

### ISSUE THREAD

**Issue by BMillman19** [lerna/lerna#1216]
## Expected Behavior

- I have a lerna repo that manages packages A, B, C in --independent mode, each is currently at version 1.0.0. Packages A and B are dependent on C
- The top level package.json lists a devDependency to C
- I make some changes to C and want to publish them
- I run `lerna publish` and bump the version of package C to 2.0.0
- A new commit is created where the package.json of A, B, and the top level package.json is updated to reflect the new version of package C

## Current Behavior

- When running `lerna publish` the package.json of A, B are updated correctly but the top level package.json is not

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

https://github.com/0xProject/0x.js/commit/d58bfb46cf50131d361ad0cbd08ef44454f8930e

The top level package.json of this lerna repo defines a dev dependency to @0xproject/utils which has been updated as a part of this publish. The version is correctly updated in all of the subpackages but not in the top level

<details><summary>lerna.json</summary><p>

```json
{
    "lerna": "2.5.1",
    "packages": ["packages/*"],
    "version": "independent",
    "npmClient": "yarn",
    "useWorkspaces": true
}
```
</p></details>

## Context

Publishing an updated package in --independent mode that the top level package.json also relies on

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 5.5.1 |
| `yarn --version` | 1.3.2 |
| `node --version` | 8.9.1 |

| OS | Version |
| macOS Sierra | 10.12.6 |
| NAME | VERSION |

**Comment by evocateur** [comment]
I really, really don't recommend this pattern, but here you go: add `"."` to your lerna.json `packages` array, which makes the root package addressable by `lerna publish` operations (it is considered "managed" by lerna, but still private, so it will never actually publish it to a registry, just do the git things).

This ability to treat the root package.json as a lerna-managed package will be going away in lerna [v3.0](https://github.com/lerna/lerna/milestone/2)

**Comment by BMillman19** [comment]
@evocateur why do you warn against this pattern? what negative side effects might we see?

**Comment by evocateur** [comment]
The root package is better-suited to encapsulating the project-wide build/test infrastructure, and making it _also_ published violates that separation of concerns. By convention, most people develop in a multi-package repo (aka “monorepo”) from the root, not from individual package directories, and overloading the root package with non-dev concerns is a recipe for confusion.

There is also the potential for race conditions/ordering problems when the root package is evaluated alongside the other managed packages. It’s also just plain confusing when there is a “packages” directory that doesn’t contain all the packages in the repository.
