### ISSUE TITLE
Lerna 2.8.0 release?

### ISSUE THREAD

**Issue by alan-agius4** [lerna/lerna#1221]
Seems like lerna 2.8.0 has been released however Its not mentioned in the change log and nor in the version of the package.json in master.

Maybe you forgot to push a commit?

**Comment by evocateur** [comment]
Nope, it's in the 2.x branch: https://github.com/lerna/lerna/blob/2.x/CHANGELOG.md#v280-2018-01-19 (and the github releases page: https://github.com/lerna/lerna/releases). I can cherry-pick the changelog update, but I don't want the v2.8.0 tag cherry-picked into master. Eventually, I think we're going to need to move the 2.x changelog, or just use the Github Releases page exclusively.
