### ISSUE TITLE
How to configure no-package-lock on lerna.json

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#1235]
## Expected Behavior
I want to be able to configure the no-package-lock option for bootstrap on lerna.json, so I don't want lerna to create package.lock on every package.

## Current Behavior
The command is being ignored

## Possible Solution
I find the documentation about lerna.json very confusing and incomplete. You say that you can put any command on the commands section, but you provide only a weird example (using the useless foo and bar examples). I think that providing all the options that can be used will be much more easier to understand and will not be much work.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0",
  "packages": [
    "src/*"
  ],
  "hoist": true,
  "registry": "https://privateregistry",
  "commands": {
    "publish": {
      "conventionalCommits": true,
      "message": "chore: Publish"
    },
    "bootstrap": {
      "no-package-lock": true
    }
  },
  "version": "independent"
}```
</p></details>

<details><summary>lerna-debug.log</summary><p>
<!-- browsers demand the next line be empty -->

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

I want to be able to configure no-package-lock on lerna.json so I don't have to hardcode it on my package.json scripts

**Comment by ntwb** [comment]
I'm pretty new to Lerna so I'm not sure of the ramifications of this method below or if Lerna is expecting to find a lock file or if Lerna is just calling npm and it is npm creating the lock files, anyway, it would be great to clarify in the docs somewhere on how Lerna utilises lock files.

I'm looking to remove `package-lock.json` files from a Lerna repo, I've just created a test Lerna repo and by adding a `.npmrc` in the root, and also in each packages root not lock files were created:

• `.npmrc`
```
package-lock=false
```

**Comment by evocateur** [comment]
```json
{
  "lerna": "2.9.0",
  "command": {
    "bootstrap": {
      "npmClientArgs": ["--no-package-lock"]
    }
  },
  "version": "1.2.3"
}
```

**Comment by skyrpex** [comment]
What is confusing to me is how is the Lerna repo itself doing this? I don't see this on the `lerna.json` file, yet the modules don't contain the `package-lock.json`:

```
"command": {
    "bootstrap": {
      "npmClientArgs": ["--no-package-lock"]
    }
  },
```

**Comment by evocateur** [comment]
It's because I'm not using `lerna bootstrap`, I'm using relative `file:` specifiers from the root.

**Comment by skyrpex** [comment]
Oh! Thanks for explaining it to me. I didn't know that the bootstrap step wasn't needed when using `file:` specifiers...
