### ISSUE TITLE
Better dependency management and error detection

### ISSUE THREAD

**Issue by mrozbarry** [lerna/lerna#1236]
First, I'm not sure if this PEBKAC, an issue directly with lerna, or more-so an npm/yarn issue.

I'm working on a project that uses lerna, and have been, for the time being, manually writing package.json files for the child packages. This has generally been going well, but occasionally, I mis-type a version of child package B in child package A's dependencies, and when I run `lerna bootstrap`, I just get errors saying the package I wan't doesn't exist on npm/yarn.

## Expected Behavior
Lerna should be able to detect that a package is local and give feedback that the version could be incorrect.

## Current Behavior
Lerna just let's npm/yarn fail. The problem here is I don't really get feedback on how it failed. The problem is definitely more on npm/yarn's side, but since lerna technically has insider knowledge of local packages that have been linked, I think we can circumvent this altogether.

## Possible Solution

To debug the problem, I ended up writing a dependency checker/resolver to step through issues, and maybe there is some code here that can be cannibalized

```
const path = require('path');
const fs = require('fs');

// This could be loaded from lerna.json
const packagesPath = ‘packages’;
const packagesRoot = path.resolve(__dirname, packagesPath);

const dependencyOrderResolver = (a, b) => {
  const isADepOfB = b.dependencies.indexOf(a.name) >= 0;
  const isBDepOfA = a.dependencies.indexOf(b.name) >= 0;
  const isCircularDep = isADepOfB && isBDepOfA;

  // Can’t do circular dependencies
  if (isCircularDep) {
    throw new Error(`Detected circular dependency between ${a.name} and ${b.name}. Consider creating a new package to host shared features.`);
  }

  // If there is a dependency, make sure the dependent package is build first
  if (isADepOfB) {
    return -1;
  } else if (isBDepOfA) {
    return 1;
  }

  // If there is no dependency, make sure the package with less local dependencies is built first
  return Math.sign(a.dependencies.length - b.dependencies.length);
};

const components = fs.readdirSync(packagesRoot)
  .filter(node => !(/^\./.test(node)))
  .filter(node => fs.existsSync(path.resolve(packagesRoot, node, ‘package.json’)))
  .map(directory => {
    const packageJson = require(path.resolve(packagesRoot, directory, 'package.json'));

    // TODO: Maybe refactor with Object.assign() and a single Object.keys() call?
    const allDependencies = Object.assign({},
      packageJson.dependencies || {},
      packageJson.devDependencies || {},
      packageJson.optionalDependencie || {},
      packageJson.peerDependencies || {},
    );
    const dependencies = Object.keys(allDependencies)
      .map(name => ({ name: name, version: allDependencies[name] }));

    return {
      directory: directory,
      path: resolve(packagesPath, directory),
      name: packageJson.name,
      version: packageJson.version,
      dependencies: localPackages,
    };
  })
  
  .reduce((packages, package, _, original) => {
    const packageWithFilteredDeps = Object.assign({}, package, {
      dependencies: package.dependencies.filter(d => original.find(p => p.name === d.name))
    })
    return packages.concat(packageWithFilteredDeps);
  }, [])
  .sort(dependencyOrderResolver)
  .forEach((package, _, allPackages) => {
    // Check version of package.dependencies against the allPackages version
  });
```

## Context
I'm just trying to help users get better error messages so we can just know what to do rather than guess.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.7.1 |
| `npm --version`  | 5.5.1 |
| `yarn --version` |  1.3.2 |
| `node --version` | 8.9.1 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.6 |

**Comment by evocateur** [comment]
So there's one complication here: lerna 2.x technically allows depending on sibling package names that have different semver major, which means they are installed from the registry instead of linked locally.

I don't necessarily agree that it should be supported, it's just terribly confusing, but that's "legacy" for you. The first alpha of 3.x (which I am about to publish) provides an alternative: local `file:` specifiers that link automagically (with npm5), overwritten temporarily during `lerna publish`.
