### ISSUE TITLE
Enable feature to --nohoist with yarn and lerna add

### ISSUE THREAD

**Issue by jaimesangcap** [lerna/lerna#1238]
I'm using lerna integrated with yarn workspace.
When adding package `@bahmutov/add-typescript-to-cypress` using `lerna add @bahmutov/add-typescript-to-cypress --scope=e2e --dev` the package is I think being installed in the node_modules of root directory first. This causes to fail the `postinstall` of the package `@bahmutov/add-typescript-to-cypress` which depends on `process.cwd()` and expects a directory structure relevant to `e2e` (_it checks that cypress/ folder exists_).

Directory structure:
```
* F:\greenfield\taskify
  | ----packages/
  | --------client/
  | ------------node_modules/
  | ------------package.json
  | --------server/
  | ------------node_modules/
  | ------------package.json
  | --------e2e/
  | ------------node_modules/
  | ------------cypress/
  | ------------package.json
  | ----node_modules/
  | ----package.json
  | ----lerna.json
```

## Expected Behavior
The `process.cwd()` of `postinstall` should be relative to `e2e/node_modules`

## Current Behavior
The `process.cwd()` of `postinstall` is relative to `taskify/node_modules`

## Possible Solution
- enable `--nohoist` in conjunction with `lerna add`?
- or resolve the issue in the repo `@bahmutov/add-typescript-to-cypress` to handle resolving the `e2e/cypress` folder?

Disclaimer: it's my first time to use lerna and I'm new to npm/js/nodes world.
If this issue can be done by newbie, I'm very willing to try 😄 

## Steps to Reproduce (for bugs)

1. git clone https://github.com/jaimesangcap/lerna-issue-sample
2. cd to the cloned repo && `$ lerna bootstrap`
3. cd to `packages/e2e` 
4. run `$ ./node_modules/.bin/cypress open`, this open cypress and creates the `packages/e2e/cypress` folder
5. run `$ lerna add @bahmutov/add-typescript-to-cypress --scope=e2e --dev`
6. error related to unable to find the `cypress` folder

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.8.0",
  "packages": ["packages/*"],
  "version": "0.0.0",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
30 error execute callback with error
31 error Error: Command failed: yarn install --mutex network:42424 --non-interactive
31 error error F:\sanay\lerna-issue-sample\node_modules\@bahmutov\add-typescript-to-cypress: Command failed.
31 error Exit code: 1
31 error Command: node src/add-plugin.js
31 error Arguments:
31 error Directory: F:\sanay\lerna-issue-sample\node_modules\@bahmutov\add-typescript-to-cypress
31 error Output:
31 error ⚠️ Cannot find "cypress" folder in F:\sanay\lerna-issue-sample
31 error Please scaffold Cypress folder by opening Cypress once
31 error and then installing this package again
31 error See: https://github.com/bahmutov/add-typescript-to-cypress/issues/3
31 error yarn install v1.3.2
31 error [1/4] Resolving packages...
31 error [2/4] Fetching packages...
31 error info fsevents@1.1.3: The platform "win32" is incompatible with this module.
31 error info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
31 error [3/4] Linking dependencies...
31 error [4/4] Building fresh packages...
31 error info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
31 error
31 error     at Promise.all.then.arr (C:\Users\ELITE052A\AppData\Local\Yarn\config\global\node_modules\lerna\node_modules\execa\index.js:236:11)
31 error     at <anonymous>
```
</p></details>

## Context
I'm trying to install module `@bahmutov/add-typescript-to-cypress` to package `e2e`, but the module has a `postinstall` script that requires `packages/e2e/cypress` folder to exists. The module's  using `process.cwd()` and goes two directory up _(it assumes that its inside `e2e/node_modules/@bahmutov/add-typescript-to-cypress`)_

Link of the issue: https://github.com/bahmutov/add-typescript-to-cypress/issues/5

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.8.0 |
| `npm --version`  | 5.5.1 |
| `yarn --version` | 1.3.2 |
| `node --version` | 8.9.1 |

| OS | Version |
| --- | --- |
| NAME                     | VERSION |
| Windows 10 Home | Build 1709 |
-->

**Comment by evocateur** [comment]
If you're using yarn workspaces, why not use a yarn workspace command to add the dependency?

(yikes, the docs for `yarn workspace` are completely missing!)

Reading the code, I guess `yarn workspace e2e add @bahmutov/add-typescript-to-cypress` should work? I dunno, seems like an issue to raise with the yarn team.
