### ISSUE TITLE
Debugging Jest tests in Visual Studio Code

### ISSUE THREAD

**Issue by millermatt** [lerna/lerna#1239]
I'm just sharing knowledge in this issue.

I was able to get debugging with breakpoints working with the vscode launch configuration below in the monorepo's `<root>/.vscode/launch.json` file. It launches Jest for a single package, `my-package`, managed in the monorepo.

        {
            "name": "Jest my-package",
            "type": "node",
            "request": "launch",
            "address": "localhost",
            "protocol": "inspector",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/lerna",
            "runtimeArgs": [
                "exec",
                "--scope",
                "my-package",
                "--",
                "node"
            ],
            "args": [
                "${workspaceRoot}/node_modules/jest/bin/jest.js",
                "--runInBand", // https://facebook.github.io/jest/docs/en/cli.html#runinband - don't parallelize
                "--no-cache", // https://facebook.github.io/jest/docs/en/cli.html#cache - just avoid caching issues
                "path/to/my-package" // from monorepo root
            ]
        }

**Comment by noherczeg** [comment]
@millermatt This could go to a new type of doc under the `doc` folder. I'd say "guides.md". Would you like to create a PR for it? :)
