### ISSUE TITLE
How to list lerna dependencies using JS instead of command line?

### ISSUE THREAD

**Issue by simonwjackson** [lerna/lerna#1240]
In my app, I need to obtain all of the local dependencies of the current package.

I know how to do this in the command line..
but is there a way to obtain the results using pure JS?
(without shell exec and parsing)

-----------------------------------

**Command line**

```bash
lerna ls  --scope package-A --include-filtered-dependencies --json
```
```bash
lerna info version 2.8.0
lerna info scope elevate-vg-database
[
  {
    "name": "elevate-vg-database",
    "version": "1.0.0",
    "private": false
  },
  {
    "name": "elevate-vg-schema",
    "version": "0.0.12",
    "private": false
  }
]
```
--------------------------------------

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.8.0 |
| `npm --version`  | 5.5.1 |
| `node --version` | 9.2.0 |

| OS | Version |
| --- | --- |
| Windows 10 | 1607 |

**Comment by evocateur** [comment]
Not right now, but once #174 lands there should be a package available with a JS API.
