### ISSUE TITLE
Remove Lerna version number from lerna.json

### ISSUE THREAD

**Issue by tkrotoff** [lerna/lerna#1247]
I don't understand why Lerna version number should be specified inside `lerna.json`, example:
```JSON
{
  "lerna": "2.8.0",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```

If `"lerna": "2.8.0"` is not specified, you get:
```
lerna info version 2.8.0
lerna ERR! ENOLERNA `lerna.json` does not exist, have you run `lerna init`?
error Command failed with exit code 1.
```

I propose to remove the need to specify Lerna version number inside `lerna.json`.

Lerna version number should be already inside `yarn.lock` or `package-lock.json`.
If `lerna.json` format changes, it should be considered a breaking change and Lerna version number should be bumped according to SemVer.

**Comment by alexeyraspopov** [comment]
Seems like it was changed in https://github.com/lerna/lerna/commit/ee8dae1991f661007b0cca5994eb5c812ec93561.

**Comment by tkrotoff** [comment]
@alexeyraspopov thx for the notification
