### ISSUE TITLE
Bootstrap only missing dependencies

### ISSUE THREAD

**Issue by thejameskyle** [lerna/lerna#125]
In Lerna 2 we switch from running `npm install` in every package directory to installing all the packages individually in order to avoid installing local dependencies that don't exist on npm.

```
$ npm install dep-1@^1.0.0 dep-2@^2.0.0 ...
```

While this improves the initial bootstrap, this also slows down subsequence bootstraps because when running npm install with the dependencies specified will force npm to re-install things it already has in the local `node_modules`.

In order to speed this up we can replicate what npm normally does and check if a dependency is already installed before re-installing it making sure that it satisfies the version in `package.json`.

This means modifying [`BootstrapCommand#installExternalPackages`](https://github.com/kittens/lerna/blob/master/src/commands/BootstrapCommand.js#L93-L113) to perform this check and filter out installed packages.

**Comment by hzoo** [comment]
Fixed in https://github.com/lerna/lerna/issues/199
