### ISSUE TITLE
Git push does not ask for credentials

### ISSUE THREAD

**Issue by asn007** [lerna/lerna#1251]
## Expected Behavior
I am not sure if it's a bug or should be a change/improvement, but:
* I use lerna on Windows (so no ssh-agent without hacks for me)
* I run lerna publish
* Lerna asks me for SSH key password if needed and pushes

## Current Behavior
* I run lerna publish
* I receive the following:
```
lerna info git Pushing tags...
(node:54588) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(node:54588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero
exit code.
```

## Context
I am trying to publish packages using Git on windows with password-protected SSH key

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.8.0 |
| `npm --version`  | 5.5.1 |
| `yarn --version` | 1.3.2 |
| `node --version` | 8.9.1 |

| OS | Version |
| --- | --- |
| Windows 10 | 1709 |

**Comment by evocateur** [comment]
Lerna is just calling `git`, it's the user's responsibility to ensure they have the proper authentication and whatnot. OS X has a git credential helper to cache those authentications, I don't know what Windows provides.

**Comment by bertho-zero** [comment]
Lerna should catch the rejection of the promise to display it more beautifully, we should not see a warning from node. Moreover, in future versions of node this will completely stop the script.

On my side I have an UnhandledPromiseRejectionWarning when I publish packages before doing a git pull, when pushing the git tags.

**Comment by evocateur** [comment]
Pretty sure lerna 3.0-alpha.2 handles the rejection now, as everything is run inside a Promise chain now. Some up-front validation of “is my remote in sync” is more appropriate to avoid a non-fast-forward push.

**Comment by CaptEmulation** [comment]
For anyone that ends up here when they can't publish on Windows because of a password protected pubkey.   Try running `start-ssh-agent` which if installed will prompt for password once and then keep an ssh-agent running for further git commands.
