### ISSUE TITLE
I can not find any example with lerna using ngrx/store Add to there is not a complete project with angular2+,

### ISSUE THREAD

**Issue by bolbol201288** [lerna/lerna#1252]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by RagnarLuthbRok** [comment]
If you want to wOrkwith Lerna you must contact #Gigabo or any others from the team itself.
Good Luck BolBol !!!!

**Comment by bolbol201288** [comment]
Thanks any way :)

**Comment by RagnarLuthbRok** [comment]
Welcome BrO 🥇

**Comment by evocateur** [comment]
Google?

Lerna doesn't cater to Angular2's weird "flat publish" pattern, so I'm not surprised few (if any) Angular projects use Lerna.
