### ISSUE TITLE
Lerna publishes entire repo for each tag instead of just the contents of that package

### ISSUE THREAD

**Issue by igloosi** [lerna/lerna#1255]
## Expected Behavior
Contents of the zip file for a package git tag should just be the package contents

## Current Behavior
Contents of the zip file for a package git tag is the entire repo from root

**Comment by diegovilar** [comment]
That's odd. Here it works as expected. Tags pushed to the repository are, as they should be, snapshots of the entire repo, but each packages published to the registry contains only the files related to each package.

**Comment by evocateur** [comment]
I can't debug it if you don't provide context (`lerna.json`, repo structure, commands run, etc)

**Comment by igloosi** [comment]
closing. reading it, it follows standard git tag
