### ISSUE TITLE
Adding package to lerna ecosystem without publishing

### ISSUE THREAD

**Issue by ashtar-veres** [lerna/lerna#1259]
## Expected Behavior
I'd like to be able to manage packages with lerna where not all of the packages should be published to npm eventually.

For example:
`@myproject/api` - npm package responsible for api requests
`@myproject/auth` - npm package responsible for the authentication
`@myproject/host` - host application that should be deployed on a server

I'd like lerna to handle and link all the dependencies for the `host` but not to publish it when I run `lerna publish`

## Current Behavior
lerna will publish all packages including the host.
setting the the package.json to private didn't help as lerna still tried to publish the package as private

## Possible Solution
add publish.excludePackages config to lerna configurations

### In case solution exist
In case solution exist I would add it into FAQ.

**Comment by dimkinv** [comment]
After rechecking again, `"private":true` does filter the package from being published
Closing this issue

**Comment by ashtar-veres** [comment]
After rechecking again, `"private":true` does filter the package from being published
`LublishCommand.js: 275`
