### ISSUE TITLE
Test only what's changed instead of the whole repo.

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [lerna/lerna#1263]
When running `lerna test`, use `git` to figure out which packages changed from `origin/master` (or from last time tested locally) and what are their dependencies. 
Only test those packages.

**Comment by bjankord** [comment]
From the project's readme:

Run the tests for all packages that have changed since master:

`$ lerna run test --since master`

**Comment by dev-matan-tsuberi** [comment]
Sorry, didn't see that, does exactly what I want.

**Comment by bjankord** [comment]
No worries, glad to help out.
