### ISSUE TITLE
Error on install of lerna with yarn

### ISSUE THREAD

**Issue by afenton90** [lerna/lerna#1264]
On install of lerna I get the following error when installing with yarn:
```
yarn install --ignore-engines
"Couldn't find any versions for "conventional-changelog-preset-loader" that matches "^1.1.3""
```

## Expected Behavior
Lerna installs without error.

## Current Behavior
Lerna doesn't install and I get the error:
```
"Couldn't find any versions for "conventional-changelog-preset-loader" that matches "^1.1.3""
```

## Possible Solution
Perhaps `conventional-changelog-preset-loader` has recently been released and lerna requires a change?

## Steps to Reproduce (for bugs)
1. Run `yarn add lerna --ignore-engines`

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context
This is currently stopping me from installing lerna, and is breaking my CI builds.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.8.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.3.2 |
| `node --version` | v8.9.4 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.6 |

**Comment by afenton90** [comment]
Related to https://github.com/conventional-changelog/conventional-changelog/issues/279

**Comment by viralpickaxe** [comment]
😡 pls learn how to npm

**Comment by forstermatth** [comment]
This is also happening when installing with NPM, as discovered not really a problem with Lerna.

```shell
core master : npm install lerna
npm ERR! code ETARGET
npm ERR! notarget No matching version found for conventional-changelog-preset-loader@^1.1.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'conventional-changelog'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!    https://gist.github.com/forstermatth/9bb297f82c5d9b1a4232c646045ac8a1
```

**Comment by simonweil** [comment]
Happening to us to... Please fix it

**Comment by bcoe** [comment]
this issue should now be addressed; there was a release error when attempting an emergency patch release to address a security vulnerability. Information about the vulnerability will be disclosed here:

https://github.com/conventional-changelog/conventional-changelog/issues/282

**Comment by simonweil** [comment]
Lerna installs now :)

**Comment by afenton90** [comment]
Closing as resolved by fix for https://github.com/conventional-changelog/conventional-changelog/issues/279
