### ISSUE TITLE
lerna run only displays the final output of a command

### ISSUE THREAD

**Issue by bensampaio** [lerna/lerna#1265]
## Expected Behavior

`lerna run <script>` should display the output of <script> while it is running and not only the final output.

## Current Behavior

`lerna run <script>` executes the <script> and displays only the final output in the console. For example, if the script is `webpack --progress` then while `webpack` is running it will display progress information. However, when running this script via `lerna` the progress information is not shown, instead only the final output is shown.

## Steps to Reproduce (for bugs)

1. On a monorepo with lerna installed create a new package with webpack as a dependency: `yarn add webpack`
2. Add an `index.js` file to the new package with the following content: `console.log('Hello World')`
2. Add the `webpack.config.js` to the new package with the following content:

```
module.exports = {
  entry: './index.js',
  output: {
    filename: 'app.js',
  },
};
```

3. Add the following to the package.json:

```
"scripts": {
  "build": "webpack --progress"
}
```

4. Run `lerna run build`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.8.0",
  "npmClient": "yarn",
  "packages": [
    "packages/*"
  ],
  "useWorkspaces": true,
  "version": "0.0.1"
}
```
</p></details>

## Context

In the case of `webpack`, for example, without output I cannot know what `webpack` is doing. I had a problem where `webpack` was hanging and simply `lerna` would never stop and would display no output. I had to install `webpack` globally to find out what was going on.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.8.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.3.2 |
| `node --version` | 9.5.0 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.2 |

**Comment by evocateur** [comment]
[`lerna run build --stream`](https://github.com/lerna/lerna#--stream)

**Comment by bensampaio** [comment]
That doesn't seem to work. I get the exact same result as before.

**Comment by bensampaio** [comment]
@evocateur could you reopen this issue, please? Your solution didn't fix my problem.
Please let me know if you need more information.

**Comment by evocateur** [comment]
Why aren't you building from the root, along with all other test/lint tasks?

In any case, `--stream` (and the related `--parallel` option) is the only way to get feedback from a script executed by `lerna run` as it is running. That being said, I doubt something like `webpack --progress` would work anyway, as the `--progress` flag implies a lot of console drawing shenanigans on a TTY.

So anyway, I suggest running webpack tasks that you want `--progress` from directly, in the root. I don't have time to debug what webpack's CLI is doing in that case that may or may not be interfering.

**Comment by bensampaio** [comment]
Because I have multiple projects inside of the same monorepo that are totally unrelated. Besides that, their webpack config is dependent on `process.cwd()` which must return the project root folder and not the monorepo root folder. Maybe there is a way to go around that but I think it would make my config even more complex.

**Comment by evocateur** [comment]
> multiple projects inside of the same monorepo that are totally unrelated

That's not a pattern lerna was meant to support. If there is no relationship between the managed packages, why bother with lerna at all?

**Comment by bensampaio** [comment]
Sorry I wasn't very clear. There is a relationship between most of the packages in my monorepo. Except the ones that have a webpack configuration. Let's say I have application A and B. Those two have a webpack.config.js and depend on several other packages in the monorepo but don't depend on each other.

**Comment by evocateur** [comment]
It would seem pretty straightforward to have npm scripts in the root that call `webpack path/to/app-a` and `webpack path/to/app-b`, etc?

**Comment by ericmorand** [comment]
@evocateur isn't Lerna `run` command doing exactly that? I expect it to do something like this under the hood for each packages iteration:

```
cd path/to/package && npm run <script>
```

**Comment by evocateur** [comment]
Yes, but that's irrelevant to the issue. The issue is anything like webpack that absolutely bombards stdio with data, along with progress bars that likely do not handle concurrent output from multiple processes very well, if at all.
