### ISSUE TITLE
Using Lerna with local repository manager

### ISSUE THREAD

**Issue by tdiluzio** [lerna/lerna#1270]
Hi everyone,

At work we need to host our own NPM packages within a local package manager such as Nexus OSS and I'm wondering if it is possible to use `lerna publish` in this context?
Thanks for your time

**Comment by 7yp0** [comment]
Hey,

It totally is possible! We are using it the same way, even with Nexus.
You just have to set up your `.npmrc` to use your private package manager (registry, authorization and stuff).
`lerna publish` will then publish it to your nexus.

**Comment by tdiluzio** [comment]
Hey @7yp0 this is a good news! Thanks for your answer

**Comment by evocateur** [comment]
Yep, just set up the right metadata as @7yp0 noted, and it will Just Work(tm).
