### ISSUE TITLE
More accurate versioning strategies for some packages

### ISSUE THREAD

**Issue by zxqfox** [lerna/lerna#1274]
I have a repo with a dozen of packages. Few of them are versioning customly.
For now I moved out these packages out of lerna control but I miss `bootstrap` behaviour.

Would be great if I somehow tell the version manager inside publish command to ask external script or plugin about version bump for these packages.

In ideal world I want to manage these packages with `lerna`:
```
./ — related on external things
  packages/
    a/ — related on external things
    b/ — independent manual versioning
    c/ — independent conventional versioning
    d/ — evergreen canary
```

## Expected Behavior

In few packages version bumped according to my own rules.
The rest uses strategy according to flags (current behaviour).

## Current Behavior

No way to customise version bump based on external data.

## Possible Solution

1. Pass a plugin or my own version strategy in lerna.json that will be used instead of the current behaviour with a fallback to it.
Also it would be nice to split current PublishConfig to a bunch of version strategies (with their own files) that will be used according to flags (instead of current monofunction).

2. Make an option in lerna.js to pass module in or shell script in package.json/scripts.

Probably I'm missing something and my problem can be solved without changing the code?

Feels like there are issues about the almost same as mine (like https://github.com/lerna/lerna/issues/1121)

**Comment by evocateur** [comment]
Regardless of any solution to this, we still have the problem of how lerna recognizes changes: annotated git tags. We would have to get a lot more complicated with the parsing of those to recognize when things did and _didn't_ change. Otherwise it becomes terribly difficult to figure out "does this package need to be published" on any given execution of `lerna publish`.

**Comment by zxqfox** [comment]
It's correct. I'll try to collaborate on this a lil bit more and make some specs on how `lerna` should recognize changes.
We having troubles with tags in our projects too but I feel like it's a solvable problem.
Thank you for the comment.
