### ISSUE TITLE
Lerna run script on prepublish, publish modified files and revert on postpublish

### ISSUE THREAD

**Issue by igloosi** [lerna/lerna#1275]
Essentially I looking at best ways to chain scripts for achieve the following:
In each package, autoprefix a scss file with postcss, publish that file (plus others) and then revert that file back to that non-prefixed file is there.
packages/my-package is my src directory

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.8 |
| `npm --version`  | 5.6 |
| `node --version` | 8.9 |

| OS | Version |
| macOS High Sierra | 10.13.3 |

**Comment by evocateur** [comment]
`lerna publish` will call the `version` [lifecycle](https://docs.npmjs.com/misc/scripts) (`preversion`, `version`, and `postversion`) for all packages, including the root manifest. The root `preversion` is called before any package is modified, root `version` is called after _all_ updated packages are modified, and root `postversion` is called after all changes have been committed.

> * preversion: Run BEFORE bumping the package version.
> * version: Run AFTER bumping the package version, but BEFORE commit.
> * postversion: Run AFTER bumping the package version, and AFTER commit.

Also, we just call `npm publish` in the package directories, any `prepublishOnly` and `postpublish` present will be called as well.

That said, you should just use the `prepare` lifecycle to build the SCSS into CSS, and include that output directory (e.g., `dist`) in the package's `files` array. You shouldn't need to modify versioned code like that, it's the whole point of using preprocessors like Sass in the first place.

**Comment by igloosi** [comment]
thanks for the version lifecycle explanation @evocateur 
the rest is not really what I'm asking. Not building scss into css or including an output directory, rather publishing scss files in the package. As packages is also my src directory I only want to autoprefix scss files that are published.
I guess i could do the transformation, publish the package  and the revert git status, but I assume that next time lerna would flag that the package has changed compared to published tag.

**Comment by evocateur** [comment]
I though auto-prefixing was the responsibility of whomever is compiling the CSS. I don't see why you need to do that, for a library source. (Consumers may have a different browser support matrix, for example, resulting in different prefix output)

**Comment by igloosi** [comment]
normally you would, but we need to provide the support for the browser matrix we've defined

**Comment by evocateur** [comment]
If the support matrix is already defined, you might as well commit those prefixes in the source code.

**Comment by igloosi** [comment]
that's tricky. postcss-scss requires new destination or new file name. either way @import sass statement would need to be rewritten for npm publishing
