### ISSUE TITLE
Is lerna expected to update versions for git url dependencies as well?

### ISSUE THREAD

**Issue by chris-dura** [lerna/lerna#1277]
## Expected Behavior

I expected (hoped that) `lerna publish` would update [Git URL dependencies](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) in the packages as well, e.g.:
```json
dependencies {
  "foo": "^1.2.4",
  "bar": "git+ssh://git@gitlab.mycompany.com:manyrepos/bar.git#v1.2.4",
  "baz": "git+ssh://git@gitlab.mycompany.com:manyrepos/baz.git#semver:^1.2.4"
}
```
would become:
```json
dependencies {
  "foo": "^1.3.0",
  "bar": "git+ssh://git@gitlab.mycompany.com:manyrepos/bar.git#v1.3.0",
  "baz": "git+ssh://git@gitlab.mycompany.com:manyrepos/baz.git#semver:^1.3.0"
}
```

## Current Behavior
Current behavior only seems to work when using typical semver ranges, and not when using URLs.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.9.0",
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "useGitVersion": true,
  "gitVersionPrefix": "v"
}
```
</p></details>

## Context
I'm in a situation where publishing to a public/private registry is not an option.
AFAIK, this means in order for other teams to use our packages, all they need to do is point to the Git URL of our package in their dependencies. Then, they can `npm install` it just like any other public package out on the npm registry.

It would be nice if lerna took this into account when it's running the `publish` command; otherwise I'm going to have to figure out how to write a script to go through and do that manually 😖 

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.6.0 |
| `node --version` | 9.4.0 |

| OS | Version |
| --- | --- |
| macOS El Capitan | 10.11.6 |

**Comment by evocateur** [comment]
Conveniently, #1278 does just that! (Except it doesn't support the `semver:` prefix right now)

However, this will only be released in the 3.x line, not 2.x. In v2.8.0, you need to pass `--use-git-version` (or `"useGitVersion": true` in lerna.json) to use this functionality.

As mentioned in [this comment](https://github.com/lerna/lerna/pull/1033#issuecomment-335894690), lerna doesn't provide any utilities for actually _doing_ the git splitting stuff, just updating metadata on the publish side.

**Comment by chris-dura** [comment]
@evocateur thanks, I must of missed the `--use-git-version` docs! 😖

**Comment by evocateur** [comment]
Yeah, a revamp of the docs is in order before 3.x general release.

**Comment by chris-dura** [comment]
@evocateur I'm still not seeing `lerna publish` update the dependencies...

```
my-mono-repo/
  package.json
  packages/
    brunch/
      package.json
    waffles/
      package.json
```
```json
// lerna.json
{
  "lerna": "2.9.0",
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "useGitVersion": true,
  "gitVersionPrefix": "v"
}
```
```json
{
  "private": true,
  "name": "brunch",
  "version": "1.0.0",
  "dependencies": {
    "waffles": "git+ssh://git@gitlab.company.com:my-mono-repo/waffles.git#v1.0.0"
  }
}
```
```json
{
  "private": true,
  "name": "waffles",
  "version": "1.0.0"
}
```
After this command...
```
lerna publish --skip-git --skip-npm --exact --use-git-version
```
The `package.json` files are updated with new `version`; however the `waffles` dependency does not...
```json
{
  "name": "brunch",
  "version": "1.1.0",
  "dependencies": {
    "waffles": "git+ssh://git@gitlab.company.com:my-mono-repo/waffles.git#v1.0.0"
  }
}
```
```json
{
  "name": "waffles",
  "version": "1.1.0"
}
```

**Comment by chris-dura** [comment]
I've thrown up an example monorepo which you can pull/fork if you want to reproduce the issue:
https://github.com/chris-dura/monorepo

Running `lerna publish --skip-npm --skip-git --exact --use-git-version` does not update the dependency git URLs.

**Comment by chris-dura** [comment]
Ok, the functionality does indeed seem to be working *except* when I try to update dependencies from our on-premise GitLab EE instance. So, it's most likely because our GitLab instance is configured in a way that lerna doesn't like? Perhaps 2FA? Any guidance related to how `lerna bootstrap` and `lerna publish` work in regards to `git` that I could pass on to our GitLab devops folks would be appreciated!

I did notice that when using our private repo in the dependencies, that `lerna bootstrap` actually created a `package-lock.json` file. However, when using dependencies from the public GitLab/GitHub sites, there was no `package-lock.json` created after running `lerna bootstrap`. I thought that might be the culprit; however, even when I turn off the lock files globally via `npm config set package-lock false`, it still didn't resolve my problems.

This works:

**Comment by evocateur** [comment]
Pretty sure this is because `hosted-git-info` doesn't recognize the `gitlab.mycompany.com` domain as a GitLab host. I don't know that there's a lot we can do about that directly, as npm doesn't seem to support that right now?

https://github.com/npm/hosted-git-info/pull/30
https://github.com/npm/npm/issues/19788

**Comment by chris-dura** [comment]
That certainly sounds like it might be the issue.

**Comment by chris-dura** [comment]
OK, so I think I can just write a script to do this one bit myself... and I won't continue to beat a dead horse. But, one final question...

I understand why the actual _publishing_ would require a domain to be recognized git host. And, obviously the dependency format should conform to the [Git URLs as dependencies](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)...

However, for the small functional bit that actually just bumps the version in the json, you're essentially just changing the `#vX.Y.Z` at the end of the URL, right? Seems odd that it would even care if the host is recognized or not, perhaps the only requirement for that bit should be that the URL is properly formatted like the npm docs spec out?

**Comment by evocateur** [comment]
We're at the mercy of `hosted-git-info` right now, unfortunately. I don't want to maintain a re-implementation of it.

**Comment by hiendv** [comment]
@evocateur Understood. But can we have a workaround for this? https://github.com/lerna/lerna/blob/v3.0.0-rc.0/core/package/index.js#L153-L154
