### ISSUE TITLE
Is there a way for lerna updated to check semver compatibility before publish

### ISSUE THREAD

**Issue by AtofStryker** [lerna/lerna#1279]
I have two packages, Module A and Module B. Module B has a dependency on Module A version ^1.0.0. I make changes to Module A and wish to patch it to version 1.0.1. However, when lerna updated or publish is run, it wishes to publish Module A and Module B as new releases. Module B does not need to be updated since the versioning is semver compatible with Module A. Is there a way around this?

I am on Lerna version 2.9

**Comment by evocateur** [comment]
Nope, this is by design. #707

**Comment by AtofStryker** [comment]
Thanks for the quick turn around!

**Comment by bertho-zero** [comment]
You can now use `lerna publish --dangerously-only-publish-explicit-updates-this-is-a-custom-flag-for-babel-and-you-should-not-be-using-it-just-deal-with-more-packages-being-published-it-is-not-a-big-deal`, `--only-explicit-updates` flag has been removed

**Comment by evocateur** [comment]
That flag is gone entirely in lerna v3, just so you know.
