### ISSUE TITLE
UpdatedPackagesCollector.isPackageDependentOf is super slow

### ISSUE THREAD

**Issue by thejameskyle** [lerna/lerna#128]
https://github.com/kittens/lerna/blob/master/src/UpdatedPackagesCollector.js#L81-L91

I'm pretty sure this check is like `O(n!)` (in the worst case) because I didn't really bother optimizing it. For repos with tons of packages that have tons of cross-dependents this even causes a `maximum call stack exceeded` error.

A fast solution might be to memoize the checks. Although that doesn't necessarily fix the max call stack issue.

In order to solve this completely we need to switch to an iterative algorithm that doesn't check the same packages multiple times.

**Comment by hzoo** [comment]
The recursive issue was fixed and there's a simple cache now
