### ISSUE TITLE
Compare package versions with --skip-git and using git tag command

### ISSUE THREAD

**Issue by igloosi** [lerna/lerna#1280]
Using lerna to publish to git creates a tag and release for each component which is as expected I guess but rather inconvenient. Example here https://github.com/material-components/material-components-web/releases

Should one use --skip-git and just use lerna to publish to npm and use the git tag command to only create one tag and a manual zip release, would lerna run into any difficulties on next `updated` by not finding package tags/ figuring out changes?

Update:
It seems it will, if the changes that are published in the npm package are also checked into git before creating a tag. (logical, but prohibits what i wanted to do in #1275)

**Comment by evocateur** [comment]
Your example doesn't look terribly "inconvenient" to me? It's much cleaner than the "independent" mode tag spam, anyhow.

I really fail to see the problem you're trying to describe. One git tag is made, in the example you posted, whenever lerna publishes a version. That's exactly how git tags work with "normal" npm packages (one-per-repo), and that's exactly the goal of lerna's default versioning mode.

**Comment by igloosi** [comment]
forgot to link back enough. they seem to have switched off independent mode now. https://github.com/material-components/material-components-web/tags?after=v0.22.0
Say example this repo:  https://github.com/igloosi/test

End goal is independently releasing packages that are not dependent of others.

Say we update breadcrumbs to v3. If we have an `all` package that has breadcrumb as a dependency, we'd want to bump that.
But we wouldn't want to bump say fieldset (as default, fixed lock does i guess) if it hasn't changed

Having done some testing, it's still possible to have lerna check if each package has been updated against single global git tag.

**Comment by evocateur** [comment]
In your updated example, a subsequent patch on `package-c` will be v0.1.1. That's the default "fixed"/"universal" versioning working as intended. There is an "independent" versioning mode that would allow you to choose v0.0.2 for `package-c`, but then it would also force you to choose independent versions for all the other packages.

I recommend sticking with the default versioning, it's less complicated and works just fine.

**Comment by igloosi** [comment]
yeah. tagging and comparing works fine with independent mode and single git tag so closing this
