### ISSUE TITLE
"add" failed to create scoped package in node-modules; subsequent bootstrap succeeded

### ISSUE THREAD

**Issue by estaub** [lerna/lerna#1284]
lerna version 2.9
macOS High Sierra 10.13.3

I added a local private scoped package to another, via 
 
`lerna add @s/shared --scope=@s/user1`

and it worked fine.
I then added the same package to another  

`lerna add @s/shared --scope=@s/user2`

and the `bootstrap` within `add` failed silently in an odd way.  It created the node_modules/@s subdirectory, but it didn't create the symlink to `shared`.

A subsequent `lerna bootstrap` fixed it.

**Comment by evocateur** [comment]
That's really weird. A minimal reproduction would be appreciated, if you have the time.

**Comment by estaub** [comment]
Yeah, weird!  I figure the main value is that, if and when someone else runs into it, you'll know that it's real and in a very weak sense reproducible.  I tried to repro and failed.  I'm very confident of what I saw, though, else I wouldn't have posted.  Feel free to close.

**Comment by evocateur** [comment]
Oh, I believe you. My hope (crossing fingers and toes) is that recent refactoring in the command lifecycle will stop swallowing transient errors like this, and we can get better insight into the root cause(s).

**Comment by bobbwhy** [comment]
I think i had this issue.  I tried to redo the --scope command by including the @project/[package] 

This seemed to work, but now when I try to work with the packages, i keep getting registry not found errors.

this was what I was trying to do: 
`lerna add constants --scope=app`
This gave me: 

> No packages found that match scope 'app'

When that did not work, I tried
`lerna add constants --scope=@pheme/app`
which seemed to work.. but when I tried to yarn add into the app package, 
registry error.

How can I reset the registry anyway? 
thanks

**Comment by evocateur** [comment]
@bobbwhy `--scope` arguments are globs of package names, which include a scope (if present).

> when I tried to yarn add into the app package

You ran `yarn add` from `./packages/app`? Yeah, that will fail, as it no doubt had local dependencies also specified, perhaps unpublished?

https://www.npmjs.com/package/constants itself has a big ol' disclaimer on it, so maybe don't use it?

> DO NOT USE: this library cannot be used because it's name conflicts with node's own internal module that goes by the same name.
>
> Use the renamed "node-constants" instead. Sorry for the inconvenience.

**Comment by evocateur** [comment]
Oh yeah, definitely in that case you need to pass the full package name (including package scope). I really hate that `--scope` is misleading like that. `lerna add @pheme/constants` should work.

**Comment by bobbwhy** [comment]
ok... so: 
I renamed constants to universals, just to avoid conflict...
`$ lerna add @pheme/universals --scope=@pheme/app
lerna info version 2.9.0
lerna info scope @pheme/app
lerna WARN No packages found in scope where @pheme/universals can be added.
`
So universals is in the packages directory and it has the name @pheme/universals in its package.json file....

**Comment by evocateur** [comment]
directory name is irrelevant, maybe don't pass `--scope`? `lerna add` should skip adding a package to itself.

**Comment by bobbwhy** [comment]
interestingly, even with the error message, it actually made the symlinks and added this to the package.json for app.
```
"dependencies": {
    "@pheme/universals": "^0.0.1"
  }
```
So that seems to work.... albeit a little rough... Lerna bootstrap was still looking for the package formerly known as constants, but i think i solved that by
