### ISSUE TITLE
Cancelling lerna publish exists with 0

### ISSUE THREAD

**Issue by igloosi** [lerna/lerna#1288]
Is there a way to determine if cancelling was intentional and so no other commands that are chained are not run?

say you have:
1) copy things
2) lerna publish --skip-git -skip-npm
3) git add & commit

Ideally wouldnt have to commit to git if lerna publish was cancelled by the user.
Any thoughts?

**Comment by igloosi** [comment]
related, if not the same https://github.com/lerna/lerna/issues/1066

**Comment by evocateur** [comment]
Yes, it is possible to detect if the process was killed via `Ctrl+c` or another signal. Is it really that valuable, in this context? I'm not so sure, in this context.

(The linked issue is worth looking into, however)
