### ISSUE TITLE
How to publish minor/patch versions without bumping package.json's carrot `^` dependencies

### ISSUE THREAD

**Issue by rcline** [lerna/lerna#1291]
## Question

In the Lerna documentation I see:

> Update all dependencies of the updated packages with the new versions, specified with a caret (^).

I am confused why this update is needed for anything but a major version release?

## Expected Behavior

Package A is at version 1.1.1.  Package B uses package A.  Package B's package.json file uses `"^1.0.0"` for the package A dependency.  When installing, 1.1.1 is installed for package A.  When making a minor release for package A, Package B's package.json file does not need to change.

## Current Behavior

When continually updating all the dependencies in every package.json file on every publish/release extra git conflicts are created.  This is probably a non-issue on small team projects, but as the teams grow and packages are added/removed/changed the noisy git conflicts increase.

## Possible Solution

Maybe a flag to turn off `^` version bumps on non-major releases?

## Steps to Reproduce (for bugs)

1. Change all package lerna dependencies to `^1.0.0`
2. Do a lerna publish of a minor or patch version
3. All package.json file dependencies are update to the new version when they could have been left the same `^1.0.0`

This library is amazing! ❤️

**Comment by evocateur** [comment]
#707 explains why this is not going to happen. Versions are cheap, basically.

**Comment by rcline** [comment]
@evocateur Thank you for the quick response and the link!

That link lead me to Issue # https://github.com/lerna/lerna/issues/718 which I had not seen when searching.  This is my exact issue that causes bloat leading to git conflicts in package.json files that are not cheap to fix after every release.

**Comment by evocateur** [comment]
The only way you would get git conflicts in leaf package manifests would be if you're publishing non-canary versions from multiple branches at the same time.

Simple solution: don't do that.
