### ISSUE TITLE
Lerna postversion lifecycle hook executed twice

### ISSUE THREAD

**Issue by mikestead** [lerna/lerna#1292]
I have top level `publish` lifecycle scripts for `version` and `postversion`, however `postversion` is being executed immediately after `version` I assume by yarn/npm's [run-script](https://docs.npmjs.com/misc/scripts) naming convention, and then again by lerna.

## Expected Behavior
I'd expect `postversion` to only be run after lerna has tagged the version.

## Current Behavior
`postversion` is executed twice, the first time before lerna has tagged the version.

## Possible Solution
I'm not really sure. If it is the naming convention triggering it then it may only be possible with a different one.

## Steps to Reproduce (for bugs)
1. create a simple lerna project with a package
2. add a `version` script and `postversion` script to the top level `package.json`
3. in `postversion` exit with code `1`
4. publish a package and see how `postversion` is executed twice, causing `version` to fail too

[Example project](https://github.com/mikestead/lerna-lifecycle-issue)

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.8.0",
  "packages": [
    "packages/*"
  ],
  "version": "1.0.0",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "registry": "https://registry.npmjs.org/"
}
```
</p></details>

<details><summary>package.json</summary><p>

```json
{
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "scripts": {
    "release": "lerna publish --yes --loglevel silly --skip-npm",
    "version": "echo \"version!\"",
    "postversion": "echo \"postversion!\" && exit 1"
  },
  "devDependencies": {
    "lerna": "^3.0.0-alpha.1"
  }
}
```
</p></details>

<details><summary>Log output</summary><p>

```txt
lerna info auto-confirmed
lerna sill addFiles [ 'lerna-lifecycle-issue/lerna.json' ]
lerna sill npmRunScript version [ '--silent' ] lerna-lifecycle-issue
lerna sill getExecOpts { cwd: 'lerna-lifecycle-issue' }
lerna ERR! publish error running version in undefined
lerna ERR! publish  Error: Command failed: yarn run version --silent
lerna ERR! publish error Command failed with exit code 1.
lerna ERR! publish $ echo "version!" --silent
lerna ERR! publish version! --silent
lerna ERR! publish $ echo "postversion!" && exit 1
lerna ERR! publish postversion!
lerna ERR! publish info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! publish
lerna ERR! publish     at makeError (lerna-lifecycle-issue/node_modules/execa/index.js:169:9)
lerna ERR! publish     at Promise.all.then.arr (lerna-lifecycle-issue/node_modules/execa/index.js:274:16)
lerna ERR! publish     at <anonymous>
lerna ERR! publish     at process._tickCallback (internal/process/next_tick.js:188:7)
lerna sill addFiles [ 'lerna-lifecycle-issue/packages/one/package.json' ]
lerna sill commit v1.0.1
lerna verb commit [ 'commit', '--no-verify', '-m', 'v1.0.1' ]
lerna sill addTag v1.0.1
lerna sill npmRunScript postversion [ '--silent' ] lerna-lifecycle-issue
lerna sill getExecOpts { cwd: 'lerna-lifecycle-issue' }
lerna ERR! publish error running postversion in undefined
lerna ERR! publish  Error: Command failed: yarn run postversion --silent
lerna ERR! publish /bin/sh: line 0: exit: too many arguments
lerna ERR! publish error Command failed with exit code 1.
lerna ERR! publish $ echo "postversion!" && exit 1 --silent
lerna ERR! publish postversion!
lerna ERR! publish info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! publish
lerna ERR! publish     at makeError (lerna-lifecycle-issue/node_modules/execa/index.js:169:9)
lerna ERR! publish     at Promise.all.then.arr (lerna-lifecycle-issue/node_modules/execa/index.js:274:16)
lerna ERR! publish     at <anonymous>
lerna ERR! publish     at process._tickCallback (internal/process/next_tick.js:188:7)
```
</p></details>

## Context
I need to execute a top level script before versioning happens, and then another one after, before publish.

Ref https://github.com/lerna/lerna/pull/1149

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-alpha.1 |
| `npm --version`  | 5.4.2 |
| `yarn --version` | 1.3.2 |
| `node --version` | 8.8.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
This is a great bug report, thanks for the detail and repro!

This didn't make sense to me at first, but then the coffee kicked in, and it makes total sense. It's painfully clear that our unit tests for this feature aren't sufficient, we should have included an integration test, at the least.

I have a hunch we _might_ be able to selectively call a particular phase if we pass `--ignore-scripts`, but I'm not 100% sure. I'll have to dig through npm/yarn source to verify.

**Comment by evocateur** [comment]
I made some progress in https://github.com/lerna/lerna/compare/master...evocateur:lifecycle-running, but it's incomplete.

**Comment by mikestead** [comment]
@evocateur Thanks for actioning this so quickly, and all the work on `Lerna`. I'll give it a run next week.

**Comment by mikestead** [comment]
@evocateur I'm trying out `v3.0.0-alpha.3` (looks like that had the fix in it) with the sample project above, and getting the following error now.

```
lerna info auto-confirmed
lerna sill addFiles [ 'lerna-lifecycle-issue/lerna.json' ]
lerna sill run-lifecycle version undefined
lerna info lifecycle undefined@undefined~version: undefined@undefined
lerna-lifecycle-issue/node_modules/npm-lifecycle/index.js:83
  return wd.lastIndexOf(pkg.name) !== wd.length - pkg.name.length
                                                           ^

TypeError: Cannot read property 'length' of undefined
    at _incorrectWorkingDirectory (lerna-lifecycle-issue/node_modules/npm-lifecycle/index.js:83:60)
    at lerna-lifecycle-issue/node_modules/npm-lifecycle/index.js:54:42
    at lerna-lifecycle-issue/node_modules/npm-lifecycle/index.js:186:12
    at lerna-lifecycle-issue/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
error Command failed with exit code 1.
```

I can open a new ticket if you prefer?

**Comment by evocateur** [comment]
I don’t suppose your root package.json has a name property? Although, given the nature of the comparison, should probably be defaulting that. A new issue would be appreciated, thanks.

**Comment by mikestead** [comment]
Adding a name property did indeed fix the problem. I've raised the issue over here https://github.com/lerna/lerna/issues/1305

**Comment by evocateur** [comment]
@mikestead Thanks!

**Comment by nemoDreamer** [comment]
Hi @evocateur ,
With Lerna `v2.11.0`, I'm still getting 2 fires of `preversion` and `postversion`.

Excuse the dirty repro here:

My root-level lifecycle scripts:
- `preversion`/`version`/`postversion`: dump lerna~ then a package-version into root-level `.version`

My package-level lifecycle scripts:
- `preversion`/`version`/`postversion`: dump lerna~ then current package-version into package-level `.version`

With my repo at version `0.24.0`, after running `lerna publish --skip-npm`, I get the following:

Root-level `.version` dump:
_(You'll notice that the package's version is behind Lerna's in the first fire of `preversion`, as I'd expect.)_
```
PREVERSION
  "version": "1.0.0",
  "version": "0.24.0",
PREVERSION
  "version": "1.0.0",
  "version": "1.0.0",
VERSION
  "version": "1.0.0",
  "version": "1.0.0",
POSTVERSION
  "version": "1.0.0",
  "version": "1.0.0",
POSTVERSION
  "version": "1.0.0",
  "version": "1.0.0",
```

Package-level `.version` dump:
_(Same for package-level dump)_
```
PREVERSION
  "version": "1.0.0",
  "version": "0.24.0",
PREVERSION
  "version": "1.0.0",
  "version": "1.0.0",
VERSION
  "version": "1.0.0",
  "version": "1.0.0",
POSTVERSION
  "version": "1.0.0",
  "version": "1.0.0",
POSTVERSION
  "version": "1.0.0",
  "version": "1.0.0",
```

**NOTE:** the last `POSTVERSION` addition in each file is only git staged, but not added to the tagged `v1.0.0` commit.

Also: the lifecycle scripts only run _if_ I have a `version` script... Took me forever to figure that one out, since I was only interested in a `postversion`... 🤣 😢

**Comment by nemoDreamer** [comment]
... sigh ... don't mind me ...
I saw the march merge date and assumed this was released.
Works fine on `alpha.3`! (Having weird issues w/ `beta.21`. Will create an issue if it doesn't exist yet.)
