### ISSUE TITLE
lerna publish --skip-git doesn't work in non git repository

### ISSUE THREAD

**Issue by rogeriorc** [lerna/lerna#1293]
## Expected Behavior
The flag --skip-git will publish to npm without running any of the git commands.

## Current Behavior
Using the flag in a svn repository throw an error "git binary missing, or this is not a git repository."

## Possible Solution
Skip the validation and git commands, and only update the package.json of the packages, using the --cd-version flag.

## Steps to Reproduce (for bugs)
1. run "lerna publish --skip-git" on a non git repository

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.9.0",
  "packages": [
    "widgets",
    "webapp-frontend",
    "webapp-backend"
  ],
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
lerna info version 2.9.0
lerna ERR! ENOGIT git binary missing, or this is not a git repository. Did you already run `git init` or `lerna init`?
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-alpha.1 |
| `npm --version`  | 5.6.0 |
| `yarn --version` |   |
| `node --version` | 8.9.4 |

| OS | Version |
| --- | --- |
| Windows 10 | 1709 |

**Comment by evocateur** [comment]
There's literally no way to determine _what_ version to publish without git available. Sorry.

**Comment by evocateur** [comment]
(Not even `--cd-version` provides that information)

**Comment by rogeriorc** [comment]
package.json:
```json
{
"version": "1.0.0"
}
```

```bash
lerna publish --cd-version=major
```

```json
{
"version": "2.0.0"
}
```

**Comment by evocateur** [comment]
Without git to identify which packages have changed, this version bump would be applied to all packages, every single time, regardless of their internal changes.

Basically, “skip git” is a terrible option name, as it does nothing more than skip the git commit and push, just as “skip npm” doesn’t actually prevent all execution of npm/yarn, it just omits the publish command.

**Comment by vrachels** [comment]
version bump being applied to all packages seems totally acceptable in this situation.
Maybe an additional warning to that effect would be acceptable?

**Comment by cwardcode** [comment]
I completely agree that bumping the version should be an acceptable answer. Good luck trying to publish a package via Lerna if you're using AWS codebuild. 👎
