### ISSUE TITLE
[Q] How to generate root changelog in fixed mode ?

### ISSUE THREAD

**Issue by hrasoa** [lerna/lerna#1294]
Hi, I saw that this is already available thanks to #1078 but I can't make it work.
```lerna.json```:

```
{
  "lerna": "2.9.0",
  "changelog": {
    "repo": "hrasoa/create-an-app",
    "labels": {
      "PR: Spec Compliancy :eyeglasses:": ":eyeglasses: Spec Compliancy",
      "PR: Breaking Change :boom:": ":boom: Breaking Change",
      "PR: New Feature :rocket:": ":rocket: New Feature",
      "PR: Bug Fix :bug:": ":bug: Bug Fix",
      "PR: Polish :nail_care:": ":nail_care: Polish",
      "PR: Docs :memo:": ":memo: Documentation",
      "PR: Internal :house:": ":house: Internal"
    }
  },
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "0.0.11"
}
```

Then when I run ```lerna publish --conventional-commits``` it still creates the changelogs inside each packages.

Also I would like to format the root changelog the same way as https://github.com/lerna/lerna-changelog do. Here is an example of result I have when generating my changelog manually with  ```lerna-changelog```: https://github.com/hrasoa/create-an-app/blob/8233dc847ff3864444d91907c8bbda9119f0de5f/CHANGELOG.md

_(My project was initially in independent mode before I changed it to fixed)._

Thanks.

**Comment by evocateur** [comment]
`--conventional-commits` does not support the format that `lerna-changelog` generates. You would need to find/write a preset for `conventional-changelog` to get the same output.

Does `lerna publish --conventional-commits` otherwise work? (I use it all the time in fixed mode and it updates the root fine)

**Comment by hrasoa** [comment]
```lerna publish --conventional-commits``` sill creates the changelogs inside the packages: https://github.com/hrasoa/create-an-app/commit/b5ec437d2bfe9a5309f83205c15841a7111918bd
