### ISSUE TITLE
i add a new module in packages, but lerna publish miss it

### ISSUE THREAD

**Issue by kakuyogy** [lerna/lerna#1295]
today i add a new module named `lego-ui`  in packages directory. 
![image](https://user-images.githubusercontent.com/32446924/36854349-bd9c97ec-1dab-11e8-88ca-e80b678a750d.png)
when i want to publish lego-ui with lerna publish, i found lerna miss it, like this,
![image](https://user-images.githubusercontent.com/32446924/36854380-d1bee6e4-1dab-11e8-935a-dd29cf9ad28c.png)
maybe i need execute any else lerna command, then lerna can manage it, thanks for you help.

**Comment by kakuyogy** [comment]
this is my lerna.json
```json
{
  "lerna": "2.8.0",
  "packages": [
    "packages/lego-ui"
  ],
  "commands": {
    "publish": {
      "ignore": [
        "lego-example*"
      ]
    }
  },
  "version": "independent"
}
```

**Comment by evocateur** [comment]
Your `packages` array is incorrect, it should be `["packages/*"]`.

(I'm not sure `--skip-git` is helping, either)

Also, you need to add the new package to git, otherwise lerna has no idea if it has changed (added/modified/deleted) from the previous tag.

**Comment by kakuyogy** [comment]
@evocateur thanks for your reply, but ["packages/*"] is not the key, if i set ["packages/*"], `lego-ui` also miss, 
![image](https://user-images.githubusercontent.com/32446924/36882107-e6da7eba-1e0c-11e8-933a-2e2b8f6f6019.png)
you can see, lego-ui is ignored.

**Comment by kakuyogy** [comment]
@evocateur i change lerna.json to
```json
{
  "lerna": "2.8.0",
  "packages": [
    "packages/*"
  ],
  "commands": {
    "publish": {
      "ignore": [
        "lego-example*"
      ]
    }
  },
  "version": "independent",
  "npmClient": "tnpm"
}
```
also miss.

**Comment by evocateur** [comment]
Without more context (or a reproduction) I’m not sure I can help any more. I’ve literally never had this problem, across multiple monorepos, with many new packages and such.
