### ISSUE TITLE
(Question) What benefit is there for running lerna bootstrap with npmClient=yarn + yarn workspaces?

### ISSUE THREAD

**Issue by hulkish** [lerna/lerna#1301]
Per my research, lerna is simply running `yarn install --mutex network:42424 --non-interactive`. I also see that yarn workspaces behavior seems to handle the bootstrap.

So, is there actually any **need** to run `lerna bootstrap` in this case?

**Comment by evocateur** [comment]
Nope, it's just a proxy for `yarn install`, really. The extra flags are only really relevant when _not_ using yarn workspaces, so you can ignore them.

**Comment by hulkish** [comment]
@evocateur thanks!
