### ISSUE TITLE
Using packages in multiple projects within a Docker-setup and keeping them synchronised with their repos

### ISSUE THREAD

**Issue by dj-hedgehog** [lerna/lerna#1303]
I am trying to get a proper Docker-based setup for my developers going.

We have multiple Node.js services which re-use some packages which we only privately host on our Git-host.

When I re-use the same packages (e.g. `package1`) managed by Lerna in multiple services (which reside in multiple containers) how will I keep the changes in sync with `package1` repo? I can't use `lerna link`.

The only solution I came up with is to enforce a certain folder structure for the developers and mount the packages inside the containers to the `node_modules` folder.

Can lerna help me with that project?

**Comment by evocateur** [comment]
No, lerna explicitly does not support anything other than multiple package development inside a unitary git repo. In your case I would just use normal package dependencies in each consuming service.

**Comment by dj-hedgehog** [comment]
Thank you for giving me an answer. I went with this solution: https://gist.github.com/eschwartz/8518b21d5d2854d8a4f7c7e7507f0561

The disadvantages are that there is a private key inside the repo (however only with read-access to the private packages) and that developing the packages with this setup is not possible.
