### ISSUE TITLE
Lerna clean does not remove node_modules folder at the root

### ISSUE THREAD

**Issue by bertho-zero** [lerna/lerna#1304]
## Expected Behavior
Lerna should delete the node_modules folder at the root.

## Current Behavior
Lerna clean does not delete the root node_modules folder.

## Steps to Reproduce (for bugs)

1. `lerna bootstrap`
2. `lerna clean`

<details><summary>lerna.json</summary><p>

```json
{
  "name": "oa",
  "version": "1.0.0",
  "description": "OpenAgenda monorepo",
  "main": "index.js",
  "repository": "https://bitbucket.org/openagenda/oa",
  "author": "OpenAgenda Dev Team",
  "license": "See license.txt",
  "private": true,
  "scripts": {
    "bs": "lerna bootstrap"
  },
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/react",
      "**/react-dom",
      "**/redbox-react",
      "**/create-react-class",
      "**/font-awesome"
    ]
  },
  "devDependencies": {
    "lerna": "^2.9.0"
  }
}

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | 8.9.1 |

| OS | Version |
| --- | --- |
| Ubuntu | 16.04 |

**Comment by evocateur** [comment]
Blowing away `./node_modules` would blow away the `lerna` dev dependency, in your example. That's not ideal.

In general, `lerna clean` is ...kinda cheesy? It's not adding anything that `git clean -fdx packages` can't do, and slower! I don't recommend using `lerna clean`, tbh.

Closing as "wont-fix" because it's not really a command that serves a useful purpose.

**Comment by bertho-zero** [comment]
I would have used it in development, I'm doing a `rm -rf **/node_modules` instead.
I thought I could use `lerna clean` and then make a fresh install only from package.json and lock files.

**Comment by evocateur** [comment]
`git clean -fdx` is way better.

**Comment by hon2a** [comment]
I've just run across this as well through a nasty issue after using `lerna clean` with the abovedescribed expectation for some time.

@evocateur If it's _"not really a command that serves a useful purpose"_, why is it provided at all? Providing a misleading API and then saying it shouldn't be touched, because it's useless anyway, makes no sense whatsoever IMO.

**Comment by evocateur** [comment]
How is "Remove the node_modules directory from all packages." in _any_ way misleading? It does exactly what it says on the tin. The root `node_modules` is _not_ a lerna-managed package.

I didn't write the subcommand, nor do I use it day-to-day. I'm fine with removing it, in fact, but I could do without the presumptive accusations of misleading folks.

**Comment by bertho-zero** [comment]
Lerna manage the root node_modules, I use yarn and its workspaces, that's why.

Almost all my packages are at the root.

**Comment by evocateur** [comment]
That's a yarn problem, then.

**Comment by RobertWSaunders** [comment]
I totally agree with @hon2a, working locally it is sometimes nice to clean out your `node_modules` directories and do a fresh install if you are running into some strange NPM issues. When running `--hoist` packages do get installed at the root and as a result the `lerna clean` command sort of breaks down and becomes less useful. To your point @evocateur, removing the root `node_modules` would remove your `lerna` dev dependancy (assuming you aren't using a globally installed version) which also isn't great. I think we have a couple of options here:

- Update the documentation to reflect this as a side effect of using `--hoist`.
- When using `lerna clean` remove any hoisted modules from the root `node_modules` folder.

I'm not sure what the feasibility of the second option is but if we can discuss here about a possible solution I might be able to find time to put up a PR.

**Comment by evocateur** [comment]
`lerna clean` is such a redundant command, though. `lerna exec -- rm -rf node_modules` does the exact same thing, except faster.

Chain that with `npm ci && npx lerna bootstrap` and you’re done. Use relative file specifiers, like lerna itself does, and all it takes is `npm ci` to reset everything (no lerna exec or bootstrap required).

Option 2 is heroically out of scope for lerna, I’d rather let package managers manage packages.

**Comment by RobertWSaunders** [comment]
Ok makes sense, I'll make a PR to update the documentation then. That said, if `lerna clean` truly is `redundant` I think it should be phased out, but I'll leave that to someone else if it matters so much.

**Comment by RobertWSaunders** [comment]
@evocateur I've added a small not in the README in #1492! 💯
