### ISSUE TITLE
lerna bootstrap failing as a postinstall step with yarn workspaces

### ISSUE THREAD

**Issue by ForbesLindesay** [lerna/lerna#1308]
## Expected Behavior

I want to put "lerna bootstrap" in the "postinstall" script so that people who don't realise that lerna has a boostrap step can just run "yarn" and have everything set up for them.

## Current Behavior

It hangs for ever on "lerna bootstrap". If I remove the "postinstall" step and run `yarn` and `lerna bootstrap` as separate steps, they each complete in a couple of seconds.

## Steps to Reproduce (for bugs)

1. clone https://github.com/pugjs/pug
2. open `package.json`
3. rename the "bootstrap" step to "postinstall"
4. run `yarn`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.9.0",
  "packages": ["packages/*"],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent",
  "registry": "https://registry.npmjs.org/"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
after a few minutes, it was still running and no log had appeared
```
</p></details>

<details><summary>package.json</summary><p>

```json
{
  "name": "pug-monorepo",
  "private": true,
  "devDependencies": {
    "coveralls": "^2.11.2",
    "jest": "^18.1.0",
    "lerna": "2.9.0",
    "prettier": "^1.3.1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/pugjs/pug.git"
  },
  "scripts": {
    "postinstall": "lerna bootstrap",
    "clean": "lerna clean",
    "release": "lerna publish",
    "pretest": "lerna run pretest",
    "test": "jest",
    "coverage": "jest --coverage",
    "coveralls": "npm run coverage && cat ./coverage/lcov.info | coveralls",
    "watch": "jest --watch"
  },
  "jest": {
    "testEnvironment": "node",
    "snapshotSerializers": [
      "./scripts/filename-serializer.js",
      "./scripts/prettier-javascript-serializer.js"
    ]
  },
  "license": "MIT",
  "workspaces": ["packages/*"]
}
```
</p></details>

## Context

People have to know to run `yarn bootstrap` after installing.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.3.2 |
| `node --version` | v8.9.4 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.3 |

**Comment by evocateur** [comment]
`lerna bootstrap` when you're using Yarn workspaces is literally redundant? All `lerna bootstrap --npm-client yarn --use-workspaces` (CLI equivalent of your lerna.json config) does is call `yarn install` in the root. With a `postinstall` that calls `lerna bootstrap` again, it's just going further down the infinitely recursive rabbit-hole.

Should we throw an error when people try `lerna bootstrap --npm-client yarn --use-workspaces`, telling them "just use yarn"?

**Comment by ForbesLindesay** [comment]
Yes, that would be a big improvement. It would also be good to add something to the readme along with the bits on setting up yarn workspaces.

**Comment by davidhouweling** [comment]
I just tried it but it doesn't look like it resolves sibling packages.

**Comment by davidhouweling** [comment]
So after a bit more experimenting and searching other issues, I had to run the  prepublish and prepare scripts of each package...

**Comment by evocateur** [comment]
That sounds like a yarn workspaces problem, then. Lerna is literally doing nothing special when you run bootstrap with workspaces enabled.

**Comment by davidhouweling** [comment]
@evocateur I think there is a difference of opinion there. From the [yarn blog](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/) itself:

> Jest relies on Yarn to bootstrap the project, and on Lerna for running the publish command(s).

**Comment by evocateur** [comment]
> I just tried it but it doesn't look like it resolves sibling packages. This is evident when you do testing for example.

Literally no context, example, etc etc etc. What "it" were you referring to?

> I think there is a difference of opinion there.

#899 (written by one of the yarn maintainers) disagrees with you.

Bootstrap has nothing at all to do with publishing. Lifecycles like `prepublish`, `prepare`, etc are all run by the npm client doing the publishing, not `lerna` (we only run a synthetic `version` lifecycle). If you're using `yarn` to bootstrap and publish, that's on `yarn` to fix their shit. `npm` does perfectly fine with `lerna publish`'s responsibilities.

If `lerna` is calling `yarn` incorrectly, that's something we _can_ fix. So far I have seen no evidence of this, however.

**Comment by davidhouweling** [comment]
Thanks for the response and I am sorry I was a bit vague with my first comment. "it' being using workspaces as directed by the blog post and lerna.

After a bit of digging on the yarn issues side, it at least is an issue on their end that is tracked as well: https://github.com/yarnpkg/yarn/issues/3911

For now, the work around as mentioned is to use `lerna run prepublish && lerna run prepare` but yes, I agree that it does not require work on lerna side but at yarn side.

Hopefully your comments and mine here for now will help with others who approach this as well.

**Comment by evocateur** [comment]
Closing as a duplicate of #1125
