### ISSUE TITLE
Allow lerna.json to be put in subdirectory or be implemented in package.json

### ISSUE THREAD

**Issue by LukasBombach** [lerna/lerna#1309]
As many of the developers I know, I am annoyed by all the config junk I have to put in the root directory of my project. As a way of having a clean project setup, I'd like to put all my config files in a place I see them fit (like a subfolder `config`).

## Expected Behavior

So what I would like to do is put my lerna.json in a subdirectory and have lerna look in the root directory by default, but maybe be able to pass the CLI a param to look in a different folder (like `--config config/lerna.json`)

For projects that only need a minimal configuration (although I am not sure on this one), I'd maybe suggest to be able to put the configuration in the package.json.

## Current Behavior
We need to put a lerna.json in the root directory or use a lot of CLI arguments

## Possible Solution

Add a CLI option `--config` to point to a config file

## Context
With my standard web application I end up with an array of config files that just "lie there" and I don't know why

**Comment by evocateur** [comment]
As I indicated [here](https://github.com/lerna/lerna/issues/1121#issuecomment-345016672), I'm open to cosmiconfig replacing our hand-rolled solution.

One problem with a `--config` option is that we currently use the location of `lerna.json` as the "logical root" of the monorepo (to support those who want other things in the "actual root", where `.git` lives).

Another problem is where to store the current lerna version (in the default "fixed" versioning mode). Even independent mode still needs the lerna.json "version" field as a sentinel value.

**Comment by LukasBombach** [comment]
Hey, thank you for picking this up and sorry for the late reply. cosmiconfig sounds awesome. As for the issues you mentioned I cannot estimate what lies behind these problems, but I know now you already have that on your radar so imma close this issue. Btw, thank you for lerna, it's really cool!
