### ISSUE TITLE
Respect tag property in package's own publishConfig

### ISSUE THREAD

**Issue by egoist** [lerna/lerna#1311]
## Expected Behavior

With `lerna publish` and such `packages/a/package.json`:

```json
{
	"publishConfig": {
		"tag": "next"
	}
}
```

It should publish the package under `next` tag instead of `latest` tag.

## Current Behavior

It was published under `latest` tag and `publishConfig.tag` in `package.json` was ignored.

## Possible Solution

Maybe just do not set it to `latest` by default? then `npm` will respect `publishConfig`.

https://github.com/lerna/lerna/blob/ce4a4b1159a3443c9f9066564b5265eb728ae142/commands/publish/index.js#L604

## Context

I have some packages under `latest` tag while others under `next` tag, so it will be helpful that Lerna respects package's own `publishConfig`

**Comment by evocateur** [comment]
I could have sworn that was already the case, but of course you’re right. I almost hit this very bug in lerna itself yesterday when I published the first beta of lerna 3.0. Definitely not the intention of lerna to overwrite a leaf package publishConfig.
