### ISSUE TITLE
`lerna link` should support `--reject-cycles` flag

### ISSUE THREAD

**Issue by wachunga** [lerna/lerna#1312]
## Expected Behavior

I would like `lerna link` to reject cycles in the same way as `lerna bootstrap` etc. I'm using lerna 2.7.2.

## Current Behavior

Currently, `--reject-cycles` only works with certain commands:

> Fail immediately if a cycle is found (in bootstrap, exec, publish or run).

which is somewhat surprising, given it's a "global option" in the source. (Maybe this has change in v3, which I just found out about?)

## Context

In CI, we do `lerna link` and would like the build to fail when hitting cycles. There are, of course, other ways to accomplish this, but it would be nice if we could do this with lerna.

**Comment by evocateur** [comment]
Short term plans for lerna 3:
1. make `--reject-cycles` the default
2. emphasize local [`file:` specifiers](https://github.com/npm/npm/pull/15900), deprecate `lerna bootstrap`
3. probably remove `lerna link`, as it's redundant(?)
    - if you want everything always linked, just use local `file:` specifiers + `npm install`

The reason it currently _doesn't_ respect that option is (mostly) because it's not doing any topographical sorting, which is where that analysis occurs. `lerna link` is simply blazing through the list of packages and symlinking willy-nilly.

Is there any particular reason you're not using `lerna bootstrap --reject-cycles`?

**Comment by evocateur** [comment]
If you’re using yarn, why not use workspaces? It completely replaces bootstrap as well, with only minor config duplication.

(I’m pretty much ignoring yarn as much as possible right now, been bitten by too many edge-cases ...such as this one!)

**Comment by amiller-gh** [comment]
The bugs with `file:` are a problem specifically when using Yarn workspaces, making `file:` relative paths completely un-usable with lerna at the moment.

Because `node-pakage-arg` does not support `link:` usage of `link:` seems to break *any* lerna command that needs to construct a package graph , throwing `Error: Unsupported URL Type "link:"`, including `lerna run test`. So, we can't use the `link` specifier either, even though it has the correct behavior.

For other reasons – that I'm happy to go into if need be – we do need to use relative paths to reference other packages in the workspace right now. Has to do with other edge-cases around linking together un-published modules...

**Comment by evocateur** [comment]
@amiller-gh I think that's a reasonable approach, given the hard-failure with the current setup. The `depVal` will always be there, it's not dependent on the presence of `depNode`.

I'll probably go with this:
```diff
diff --git a/core/package-graph/index.js b/core/package-graph/index.js
index 589338bb..12508375 100644
--- a/core/package-graph/index.js
+++ b/core/package-graph/index.js
@@ -70,7 +70,11 @@ class PackageGraph extends Map {
 
       Object.keys(graphDependencies).forEach(depName => {
         const depNode = this.get(depName);
-        const resolved = npa.resolve(depName, graphDependencies[depName], currentNode.location);
+        // Yarn decided to ignore https://github.com/npm/npm/pull/15900 and implemented "link:"
+        // As they apparently have no intention of being compatible, we have to do it for them.
+        // @see https://github.com/yarnpkg/yarn/issues/4212
+        const spec = graphDependencies[depName].replace(/^link:/, "file:");
+        const resolved = npa.resolve(depName, spec, currentNode.location);
 
         if (!depNode) {
           // it's an external dependency, store the resolution and bail
```

Thanks for all the detailed analysis!

**Comment by amiller-gh** [comment]
@evocateur, awesome 👍  By putting the fix here, does this also plug the holes left by `link:` when publishing a module – like we do with `file:`, added in https://github.com/lerna/lerna/pull/1262?

**Comment by evocateur** [comment]
Yep! Just added a test to verify :)

```diff
diff --git a/commands/__fixtures__/yarn-link-spec/.yarnrc b/commands/__fixtures__/yarn-link-spec/.yarnrc
new file mode 100644
index 00000000..19daacaa
--- /dev/null
+++ b/commands/__fixtures__/yarn-link-spec/.yarnrc
@@ -0,0 +1 @@
+workspaces-experimental true
diff --git a/commands/__fixtures__/yarn-link-spec/lerna.json b/commands/__fixtures__/yarn-link-spec/lerna.json
new file mode 100644
index 00000000..cbf807a5
--- /dev/null
+++ b/commands/__fixtures__/yarn-link-spec/lerna.json
@@ -0,0 +1,5 @@
+{
+  "version": "1.0.0",
+  "npmClient": "yarn",
+  "useWorkspaces": true
+}
diff --git a/commands/__fixtures__/yarn-link-spec/package.json b/commands/__fixtures__/yarn-link-spec/package.json
new file mode 100644
index 00000000..707937ab
--- /dev/null
+++ b/commands/__fixtures__/yarn-link-spec/package.json
@@ -0,0 +1,7 @@
+{
+  "name": "yarn-link-spec",
+  "private": true,
+  "workspaces": [
+    "workspaces/*"
+  ]
+}
diff --git a/commands/__fixtures__/yarn-link-spec/workspaces/package-1/package.json b/commands/__fixtures__/yarn-link-spec/workspaces/package-1/package.json
new file mode 100644
index 00000000..8eb2fba2
--- /dev/null
+++ b/commands/__fixtures__/yarn-link-spec/workspaces/package-1/package.json
@@ -0,0 +1,4 @@
+{
+  "name": "package-1",
+  "version": "1.0.0"
+}
diff --git a/commands/__fixtures__/yarn-link-spec/workspaces/package-2/package.json b/commands/__fixtures__/yarn-link-spec/workspaces/package-2/package.json
new file mode 100644
index 00000000..0e6aefb9
--- /dev/null
+++ b/commands/__fixtures__/yarn-link-spec/workspaces/package-2/package.json
@@ -0,0 +1,7 @@
+{
+  "name": "package-2",
+  "version": "1.0.0",
+  "dependencies": {
+    "package-1": "link:../package-1"
+  }
+}
diff --git a/commands/publish/__tests__/publish-command.test.js b/commands/publish/__tests__/publish-command.test.js
index b49cc699..1b710339 100644
--- a/commands/publish/__tests__/publish-command.test.js
+++ b/commands/publish/__tests__/publish-command.test.js
@@ -1204,6 +1204,16 @@ describe("PublishCommand", () => {
         "package-6": "6.0.0",
       });
     });
+
+    it("works around npm-incompatible link: specifiers", async () => {
+      const testDir = await initFixture("yarn-link-spec");
+
+      await lernaPublish(testDir)("--cd-version", "major", "--yes");
+
+      expect(updatedPackageJSON("package-2").dependencies).toMatchObject({
+        "package-1": "^2.0.0",
+      });
+    });
   });
 
   describe("in a cyclical repo", () => {
diff --git a/core/package-graph/index.js b/core/package-graph/index.js
index 589338bb..12508375 100644
--- a/core/package-graph/index.js
+++ b/core/package-graph/index.js
@@ -70,7 +70,11 @@ class PackageGraph extends Map {
 
       Object.keys(graphDependencies).forEach(depName => {
         const depNode = this.get(depName);
-        const resolved = npa.resolve(depName, graphDependencies[depName], currentNode.location);
+        // Yarn decided to ignore https://github.com/npm/npm/pull/15900 and implemented "link:"
+        // As they apparently have no intention of being compatible, we have to do it for them.
+        // @see https://github.com/yarnpkg/yarn/issues/4212
+        const spec = graphDependencies[depName].replace(/^link:/, "file:");
+        const resolved = npa.resolve(depName, spec, currentNode.location);
 
         if (!depNode) {
           // it's an external dependency, store the resolution and bail
```

**Comment by amiller-gh** [comment]
Beautiful! 😄

**Comment by evocateur** [comment]
https://github.com/lerna/lerna/commit/ddfb517ab9a061876378a925467b60c8abf17534

**Comment by vzaidman** [comment]
can i use this in "lerna.json"?

this does not seem to work (loglevel works):
```
{
  "lerna": "2.9.0",
  "version": "2.0.0",
  "packages": [
    "packages/*"
  ],
  "command": {
    "bootstrap": {
      "loglevel": "verbose",
      "reject-cycles": ""
    }
  }
}
```

**Comment by evocateur** [comment]
You need to pass `true` for the value of the “rejectCycles” key. (This option will soon be inverted, making it reject cycles by default)
