### ISSUE TITLE
Log note if using skip-git or skip-npm

### ISSUE THREAD

**Issue by rmccue** [lerna/lerna#1314]
## Expected Behavior

When using `--skip-git` or `--skip-npm`, I want to be certain that Lerna is not going to do any changes here. As Lerna allows unknown arguments (like `--no-git`), the UI should reassure the user.

## Current Behavior

Currently, there is no indication that git or npm are being skipped.

## Possible Solution

* If `--skip-git` is provided, output `lerna info Skipping git...`
* If `--skip-npm` is provided, output `lerna info Skipping npm...`

## Context

I misspelled the argument and almost published when I didn't mean to.

**Comment by evocateur** [comment]
Definitely!

**Comment by mishaor** [comment]
Can I work at this one?

**Comment by evocateur** [comment]
@mishaor You got it, thanks!

**Comment by mishaor** [comment]
The feature is kinda done locally, I need some repositories to test.

**Comment by mishaor** [comment]
This feature works but no test are written for it. https://hastebin.com/ofewinerat.sql

**Comment by evocateur** [comment]
Unit tests should be feasible with this sort of change. The [`loggingOutput()` helper](https://github.com/lerna/lerna/blob/4de055dc83c264f9996869bd9d1fc0fbf1a9c3ed/commands/publish/__tests__/publish-command.test.js#L1054) makes this pretty trivial.

```js
await lernaPublish(testDir)("--skip-git", "--skip-npm");

const logMessages = loggingOutput("info");
expect(logMessages).toContain("Skipping git...");
expect(logMessages).toContain("Skipping npm...");
```

**Comment by mishaor** [comment]
Well, somehow test doesn't pass :/

**Comment by evocateur** [comment]
If you open a PR the CI tests will run, and I can show you how to fix them.

**Comment by evocateur** [comment]
#1319 fixed this
