### ISSUE TITLE
Aligned package labels in parallel mode

### ISSUE THREAD

**Issue by mnutt** [lerna/lerna#1315]
## Expected Behavior

I'd like to be able to run `lerna run --parallel` and have each label be the same width. For example:

```
> lerna run ci:test --parallel

a-project:           ✓ this test passed
another-project:     ✗ this test did not pass
a-project:           ✓ this test also passed
yet-a-third-project: ✓ again, this test passed
```

## Current Behavior

Labels have no indentation, so it's really hard to scan down the rows and see which tests passed:

```
> lerna run ci:test --parallel

a-project: ✓ this test passed
another-project: ✗ this test did not pass
a-project: ✓ this test also passed
yet-a-third-project: ✓ again, this test passed
```

When there are thousands of lines it is nice to just scan straight down, looking for failures.

## Possible Solution

I think it should be possible to have the parallelization function calculate the length of the longest label and pass that length into the npm workers to justify the labels. I can investigate and open a pull request, if it seems like something that would be generally valuable.

**Comment by evocateur** [comment]
Your `ci:test` example would benefit from aligned labels, but I'm not sure it's generalizable to all `lerna run --parallel` executions. I would recommend running all the tests from the root, instead.

**Comment by mnutt** [comment]
I'm not quite sure I understand running tests from the root? The output above is running the test across all of our packages from the root of the repository, which is why the output from different packages get interleaved when running in parallel.

The reason I thought that might be generally useful was that it's pretty hard to visually parse _any_ interleaved output from multiple processes, such as in tools like foreman: http://blog.daviddollar.org/2011/05/06/introducing-foreman.html Would you be open to a command-line flag to enable it?

**Comment by evocateur** [comment]
By "from the root" I mean one call to `jest` (for example) that runs all the tests that it can find under `packages/**` (or wherever your leaf packages are), not executing an npm script in every leaf package.

`--parallel` isn't really meant to be especially readable, it's just prefixed so stdio logging doesn't lose all context. Interleaved output is messy.

`lerna run --concurrency 100` would log in package-specific chunks (not prefixed, but identified by `npm run` output), while still running nearly in parallel. Although that option does sorta mangle the newlines and color output, so not ideal either.

**Comment by evocateur** [comment]
> Would you be open to a command-line flag to enable it?

Yes, that sounds fair. `--aligned`, perhaps?
