### ISSUE TITLE
Lerna ignoring new added packages

### ISSUE THREAD

**Issue by lucantini** [lerna/lerna#1316]
## Expected Behavior
While adding a new folder with contents already written I expect that folder to have contents when pushing to a git repo.

## Current Behavior
While adding a new folder with contents already written, the content are ignored and the folder is not versioned by git. Leading into an empty folder on the repo.

## Steps to Reproduce (for bugs)
1. Create a folder and run ```lerna init```
2. Add a new folder with a new module inside of the packages folder
3. Git ignored the added package and when you push it to the repo it only shows as an empty folder(?)

```json
{
  "lerna": "2.9.0",
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}

```

## Context
I'm trying to add a new package.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.6.0 |
| `node --version` | 8.9.4 |

| OS | Version |
| Ubuntu | 17.10 |

**Comment by evocateur** [comment]
This sounds like a `git` problem, not a `lerna` problem. How is this related to lerna?

**Comment by lucantini** [comment]
Maybe I've misread some configuration or command that I have to set/run in order for git to see those folders.

**Comment by evocateur** [comment]
`git add packages/my-new-package` should be sufficient.

**Comment by lucantini** [comment]
That's the point, it simply doesn't see any changes, so I can't add them.

To create a new lerna package inside of the packages folder I just need to add the folder inside the packages folder, is this correct? Or do I have to run a command to create the package folder and then populate it with the files?

If by adding a package to the package folder it should be already in my packages list, then it's indeed a git problem.

**Comment by evocateur** [comment]
Just adding an empty directory won't actually add anything to git. You need to have files in the directory for git to add it to the index (and then the commit).

```
mkdir packages/foo
cd packages/foo
npm init --yes
cd ../..
git add packages/foo
git commit -m "feat: add packages/foo"
```

**Comment by lucantini** [comment]
I am adding a folder with contents inside. But if that should work, then it's probably a git problem.

**Comment by lucantini** [comment]
I found out what my problem was and it was related to the WebStorm IDE.
I'll leave a [link](https://stackoverflow.com/questions/14550802/what-does-fatal-bad-revision-mean) here in case anyone stumble upon it.

Thanks for the help :)
