### ISSUE TITLE
"useWorkspaces": true and "npmClient": "npm" causes "lerna bootstrap" to only install root dependencies

### ISSUE THREAD

**Issue by aholtkamp** [lerna/lerna#1318]
We have support for both "npm" and "yarn" in our mono-repo and use lerna to fill the gap for the workspace installation and to run scripts in inner packages. To enable support for either npm or yarn we change the "npmClient" configuration of the lerna.json.

This all works as intended but we need to save the actual "workspaces"/"packages" configuration redundantly: yarn expects that there is a "workspaces" configuration in the package.json of the root while lerna expects that there is a "packages" configuration in the lerna.json.

Reading the documentation revealed that there is support for yarn workspaces when setting the "useWorkspaces" configuration to "true" in lerna.json. But this causes problems when switching the "npmClient" to "npm" as it not only has impact on where the configuration for the workspace is coming from but also causes "npm run lerna bootstrap" to do much less.

## Expected Behavior

"npm run lerna bootstrap" will work the same way as with "useWorkspaces" set to false with the difference that the packageJson.workspaces configuration is used (and the lernaJson.packages can be omitted).

## Current Behavior

"npm run lerna boostrap" will install only the dependencies of the root package.

## Possible Solution

Adjust the "bootstrapPackages" function BootstrapCommand.js and take the "npmClient" into account:

```js
if (this.options.useWorkspaces && this.options.npmClient === "yarn") {
...
}
```

## Steps to Reproduce (for bugs)

1. Start with a clean workspace (remove all node_modules folders)
2. Change "npmClient" to "npm" in lerna.json
3. Change "useWorkspaces" to true in lerna.json
4. Run "npm run lerna bootstrap" from the workspace root.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.9.0",
  "useWorkspaces": true,
  "npmClient": "npm",
  "hoist": true,
  "concurrency": 1
}
```
</p></details>

## Context

see description

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.3.2 |
| `node --version` | 8.9.4 |

| OS | Version |
| --- | --- |
| Linux Mint | 18.3 |

**Comment by evocateur** [comment]
useWorkspaces was only ever intended for yarn, setting npmClient “npm” should be an error in that context. You should pick one or the other, otherwise your lockfiles will be out of sync.

**Comment by aholtkamp** [comment]
Hm...this was not explicitly stated in the documentation (or I might have missed something). The missing error leads to the assumption that this is just a bug. Everything else works fine in that constellation, "lerna run" delegates to the inner packages, even the "lerna clean" takes the sub packages into account again.

If changing this is no possibility, what about a "useWorkspacesEntry" configuration that just controls where the information is retrieved from (defaults to: useWorkspaces, if true use packageJson.workspaces and fallback to lernaJson.packages otherwise just use lernaJson.packages)?

**Comment by evocateur** [comment]
“workspaces” is owned by yarn right now, they’ve already broken the format once, and I’d rather not be coupled to an external config namespace (any more than we already are). If you’re using npm, you don’t need the workspaces config; if you’re using yarn, you don’t need the lerna.json “packages” config (assuming “useWorkspaces”: true is set at the root level).

**Comment by aholtkamp** [comment]
Ok, thanks for your input! I consider this issue as solved.
