### ISSUE TITLE
lerna exec -- npm publish ERR

### ISSUE THREAD

**Issue by lili21** [lerna/lerna#1320]
## Expected Behavior
I have executed the same command in terminal, it works. `lerna exec` should work too.

## Current Behavior
![image](https://user-images.githubusercontent.com/4456380/37381732-ba98a1bc-2779-11e8-8531-4052da68a21e.png)

## Possible Solution

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.9.0",
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "useWorkspaces": "true",
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'npm', 'publish', '--userconfig=/Users/li.li/.cnpmrc' ]
1 silly flags { _: [ 'exec' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   command: 'npm',
1 silly flags   args: [ 'publish', '--userconfig=/Users/li.li/.cnpmrc' ] }
2 verbose rootPath /Users/li.li/Work/bard
3 info version 2.9.0
4 silly existsSync /Users/li.li/Work/bard/VERSION
5 info versioning independent
6 silly initialize attempt
7 silly initialize success
8 silly execute attempt
9 error exec Errored while executing 'npm publish --userconfig=/Users/li.li/.cnpmrc' in '@lls/bard'
10 error execute callback with error
11 error Error: Command failed: npm publish --userconfig=/Users/li.li/.cnpmrc
11 error     at Promise.all.then.arr (/Users/li.li/Work/bard/node_modules/execa/index.js:236:11)
11 error     at <anonymous>

```
</p></details>

## Context

I want to publish the package to my private registry. I have executed `npm publish --userconfig=/User/li.li/.cnpmrc` in terminal, it works as expected. But `lerna exec -- npm publish --userconfig=/User/li.li/.cnpmrc` somehow just throw auth error. 

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | 9.8.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.1 |

**Comment by evocateur** [comment]
When using `npm`, the default user config is `~/.npmrc`, not `.cnpmrc`.

**Comment by lili21** [comment]
I know that, that's why I pass the `--userconfig` option.

**Comment by judewang** [comment]
@lili21 hi, I have the same issue, how did you fix it?

**Comment by lili21** [comment]
@judewang add `.npmrc` file in every package. and include the auth info in the file.

```bash
//private.registry.com/:_password=****
//private.registry.com/:username=***
//private.registry.com/:email=***
//private.registry.com/:always-auth=false
```

**Comment by judewang** [comment]
@lili21 I have my `NPM_TOKEN` inside `~/.npmrc`, but haven't try to add it to every pacakges. Will take it a try, thanks.

**Comment by lauriejones** [comment]
I am struggling through this at the moment trying to publish packages from CI. Is there no way to reference an `.npmrc` file in the project root rather than add one in each package?

**Comment by lauriejones** [comment]
From what I've read and experimented with, `lerna publish` does not support publishing private, scoped packages?

**Comment by evocateur** [comment]
As I (or someone at my company) do that literally every day, this is news to me.

**Comment by lauriejones** [comment]
Publishing scoped packages, privately to the default npm registry? Well that's great then! Are there any examples I can look at? 🙂  

Any time I tried to use the publish command with scoped packages they ended up public on the npm registry.

This section in the publish command readme suggests it is not possible. So perhaps it should be updated.

> Lerna will never publish packages which are marked as private (`"private": true` in the `package.json`).

**Note:** to publish scoped packages, you need to add the following to each `package.json`:

```json
  "publishConfig": {
    "access": "public"
  }
```

**Comment by judewang** [comment]
> Lerna will never publish packages which are marked as private ("private": true in the package.json).

I was also confused about this suggestion, then I tried just publishing scoped packages _without_ the public settings, and it just worked🤩

**Comment by evocateur** [comment]
Well, okay, clearly the access config isn't necessary for private scoped packages, the docs are trying to address a far more common case (and _not_ the default for scoped packages on the public registry).

**Comment by judewang** [comment]
@Hotell Hi, just try moving `publishConfig` from `package.json` 😉

**Comment by evocateur** [comment]
The `publishConfig` is correct. I don't recommend publishing from `lerna exec`. And you shouldn't need to pass `from-package` unless a previous `lerna publish` errored after the commit and tag were pushed.

**Comment by Hotell** [comment]
> And you shouldn't need to pass from-package unless a previous lerna publish errored after the commit and tag were pushed.

I don't trust/wanna rely on `lerna publish` solely. I'm using `lerna version` to get changelogs and version bumps. everything else is handled manually. That's why `lerna publish from-package` solved my issue :)

https://github.com/Hotell/ts-setup/blob/master/package.json#L42-L46

Anyways, thanks for help folks!
