### ISSUE TITLE
`"hoist": true` in lerna.json breaks bootstrap command.

### ISSUE THREAD

**Issue by chriseppstein** [lerna/lerna#1325]
## Expected Behavior

`"hoist": true` in lerna.json continues to work in 3.0.

## Current Behavior

`"hoist": true` causes an exception in minimatch.

## Possible Solution

I think option normalization should be centralized so that the logic for values that come from the cli shouldn't be different from what comes from json config. The tests seem to focus on using the cli to control various different set ups, so this would minimize the opportunity for divergent behavior without adding the need to double the amount of test cases to prevent future regressions.

## Work around

set `"hoist": "**"` in lerna.json instead of to`true`.

## Steps to Reproduce (for bugs)

1. set hoist to true in `lerna.json` (not via the cli, which converts true to `"**"`).
2. run `lerna bootstrap`

near as I can tell from the code this is going to affect all environments, so I didn't provide that info.

**Comment by evocateur** [comment]
What version of lerna?

**Comment by chriseppstein** [comment]
@evocateur Sorry, this is in `3.0.0-beta.2`.

**Comment by evocateur** [comment]
@chriseppstein Thanks, I'll check it out. Could have sworn the test coverage was decent on this score, but it isn't the first time the tests turned out to be misleading...

**Comment by chriseppstein** [comment]
@evocateur I'll let you know when I find a project with perfect tests. don't hold your breath tho.

**Comment by evocateur** [comment]
Published the fix in [v3.0.0-beta.4](https://github.com/lerna/lerna/releases/tag/v3.0.0-beta.4)

**Comment by chriseppstein** [comment]
@evocateur Thanks for the quick iteration. 👏
