### ISSUE TITLE
after lerna link still unmet depes

### ISSUE THREAD

**Issue by reggi** [lerna/lerna#1327]
> I am trying to install a lerna package globally, without any of the siblings published is this possible?

I ran `lerna clean` got rid of everything, as well as the root `node_modules`. I ran `lerna link` and theres one package a `cli` tool I'm trying to use `npm link` to install it globally. 

My method to get it to work was this:

```
lerna link
lerna bootstrap ---hoist
npm link
```

However I'm getting this:

```
➜  pkg-cli git:(master) ✗ npm link -f
npm WARN using --force I sure hope you know what you are doing.
npm ERR! code E404
npm ERR! 404 Not Found: @reggi/journey.is-promise@1.0.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thomas/.npm/_logs/2018-03-16T07_26_47_916Z-debug.log
```

And when I run `npm ls` in the dir I get this:

```
@reggi/pkg-cli@1.0.0 /Users/thomas/Desktop/abide/packages/pkg-cli
└─┬ @reggi/pkg@1.0.0 -> /Users/thomas/Desktop/abide/packages/pkg
  ├─┬ @reggi/journey@1.0.0
  │ ├── @reggi/journey.coerce-to-array@1.0.0
  │ ├─┬ @reggi/journey.fn-free@1.0.0
  │ │ └── UNMET DEPENDENCY @reggi/journey.is-promise@1.0.0
  │ ├─┬ @reggi/journey.fn-reduce@1.0.0
  │ │ ├── UNMET DEPENDENCY @reggi/journey.coerce-to-plain-object@1.0.0
  │ │ ├── UNMET DEPENDENCY @reggi/journey.is-promise@1.0.0
  │ │ └── UNMET DEPENDENCY @reggi/journey.pass-thru@1.0.0
  │ └── UNMET DEPENDENCY lodash@4.17.5
  ├── @reggi/journey.coerce-to-array@1.0.0
  ├── @reggi/pkg.is-local-module@1.0.0
  ├─┬ @reggi/pkg.read-json@1.0.0
  │ ├─┬ @reggi/journey@1.0.0
  │ │ ├── @reggi/journey.coerce-to-array@1.0.0 deduped
  │ │ ├── @reggi/journey.fn-free@1.0.0 deduped
  │ │ ├── @reggi/journey.fn-reduce@1.0.0 deduped
  │ │ └── UNMET DEPENDENCY lodash@4.17.5
  │ ├─┬ @reggi/pkg.fs@1.0.0
  │ │ └── UNMET DEPENDENCY bluebird@3.5.1
  │ ├─┬ @reggi/pkg.fs-file-exists@1.0.0
  │ │ └─┬ @reggi/pkg.fs@1.0.0
  │ │   └── UNMET DEPENDENCY bluebird@3.5.1
  │ ├── @reggi/pkg.json-parse@1.0.0
  │ └── @reggi/pkg.throw-error@1.0.0
  ├── UNMET DEPENDENCY bluebird@3.5.1
  └── UNMET DEPENDENCY lodash@4.17.5
```

It's obvious why I don't have `bluebird` and `lodash` in this example (because their hoisted). But the other lerna siblings should be available from `lerna link` no?

**Comment by evocateur** [comment]
`lerna link` isn't necessary if you're doing `lerna bootstrap --hoist` (it's not doing the same thing as `npm link`, for one starters). `lerna link` is _only_ symlinking local dependencies together, it's a weird workaround for people who didn't want to bootstrap correctly. With lerna 3, I would just use the relative `file:` specifiers and ignore `lerna bootstrap` and `lerna link`.

If you only have one CLI that you want to link, you could `npm link` it from the root `bin`. Lerna does it this way: https://github.com/lerna/lerna/blob/14fcc1b5646c13b6fd03259553f68d5d1af70788/package.json#L20-L22

**Comment by reggi** [comment]
Yeah I switched over to using `file:`, much better.

**Comment by captainkovalsky** [comment]
@evocateur Did you mean that we can use `npm i packages/*` when set deps to `file:../packages/<package>` ?

**Comment by evocateur** [comment]
Yes, but the sibling relative file: spec generally only needs one `..`, like `file:../my-neighbor`.
