### ISSUE TITLE
[Feature] Scripting Lerna

### ISSUE THREAD

**Issue by jamiebuilds** [lerna/lerna#133]
Any good CLI tool can be composed with others, so I would like to focus on that with Lerna.

Stuff like:

Making commands like `lerna ls` or `lerna updated` have easy to parse output.

``` sh
$ lerna ls
package-1
package-2

# instead of:

$ lerna ls
Lerna v2.0.0-beta.6
Independent Versioning Mode
- package-1
- package-2
```

``` sh
$ lerna updated
package-1
package-2

# instead of

$ lerna updated
Lerna v2.0.0-beta.6
Independent Versioning Mode
Checking for updated packages...

- package-1
- package-2
```

> This will require moving debug information behind a `--debug` flag.

There's also `lerna exec` in #130 

``` sh
$ lerna exec pwd
/path/to/repo/packages/package-1
/path/to/repo/packages/package-2
```

I would also like to be able to expose different config-like information from lerna:

``` sh
$ lerna get repo.version
2.0.0
# or
independent
$ lerna get paths.root
/path/to/repo
$ lerna get paths.packages
/path/to/repo/packages
```

This is all my ideas for now, but I'm definitely interested in anything that makes Lerna more scriptable.

**Comment by joscha** [comment]
Maybe we could adapt the git `--porcelain` flag for that. That way current scripts would continue working, just the output with --porcelain would allow composition and hide all debug output.

**Comment by jpnelson** [comment]
I'd prefer @joscha 's suggestion if it's the difference between a major version and a minor version

**Comment by thejameskyle** [comment]
What would break with current scripts? Are people using the output of Lerna already?

**Comment by joscha** [comment]
can't speak for other people, but we do:
```shell
# Get all packages so we now which ones to iterate through
ALL_PACKAGES=$($LERNA_LOC exec pwd\
| sed 1,2d)
```

**Comment by light24bulbs** [comment]
the --json flag covers this use case now, but unfortunately there isn't quite enough data in there.  It would be nice if `ls` also listed the package `path`

**Comment by evocateur** [comment]
@light24bulbs A lot of scriptable options been [implemented](https://github.com/lerna/lerna/commit/2e204af3f10d30f0fca37891aed721ddf15cf667) [recently](https://github.com/lerna/lerna/commit/6ecdd83d14f3b9d0cac62cc68b4066ec554e79ce), but not released yet. Trying to finish #1091 first.

**Comment by JamesHenry** [comment]
Hi Folks 👋 

In light of its age, and in order to allow our small team to focus on what matters most to Lerna v6 users in late 2022, I'm going to close this one. If you have any requests that could enhance your usage of Lerna 6, then please do let us know by opening a new discussion (for a feature) or issue (for a bug report) which as much context as possible.

You can also check out our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

Many thanks 🙏
