### ISSUE TITLE
Cannot find my packages (Bootstrapping 0 packages) on Windows 10

### ISSUE THREAD

**Issue by renatonmendes** [lerna/lerna#1331]
I´m just staring using lerna and gettting I´m having several difficulties on Windows 10. First I´ve installed lerna globally:

`d:\> npm install -g lerna`

All fine, then I created a folder:
```
d:\> mkdir test
d:\> cd test
d:\test\> lerna init
```

All fine, lerna files were created. Then I´ve configured everything:

**package.json**
```
{
    "workspaces": ["*"],
    "private": true,
    "devDependencies": {
                "lerna": "^2.9.0"
        }
}
```

**lerna.json**
```
{
  "lerna": "2.9.0",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```

My packages:

Auth package (`packages/auth`):

```
{
  "name": "@myorganization/auth",
  "version": "3.0.0",
  "author": "Myself",
  "license": "UNLICENSED",
  "dependencies": {
    "@myorganization/ux": ">=0.0.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

UX package (`packages/ux`):

```
{
  "name": "@myorganization/ux",
  "version": "3.0.0",
  "author": "Myself",
  "license": "UNLICENSED",
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  }
}
```

Now trying to bootstrap packages:
```
d:\> cd test\packages
d:\> lerna bootstrap
lerna info version 2.9.0
lerna info Bootstrapping 0 packages
lerna info hoist Finished installing in root
lerna success Bootstrapped 0 packages
```

It can´t find my packages, showing always Bootstrapping 0 packages. The node_modules is create on root, but none of the dependencies are created. 

I´ve tried reacreating, reinstalling lerna, changed folder attributes with no success. 

Are there any bug in windows version ? What may be causing that ? Am I doing something wrong ?

**Comment by renatonmendes** [comment]
My issue is related to:

```
  "npmClient": "yarn",
  "useWorkspaces": true,

```

After removing it, it started bootstrapping, but now I'm confused. Is using yard different than npm? Thy is the original not working? Also, how to bootstrap and hoist using yard?

**Comment by evocateur** [comment]
* Your `lerna.json`'s `version` property (which is `0.0.0` in the example) needs to match the version of the leaf packages, which are `3.0.0` in your posted examples.
* The sibling dependency ranges cannot be expressed as `>=0.0.0`, they need to be `^3.0.0` (the caret range of the sibling version).
    * `"@myorganization/ux": ">=0.0.0",` => `"@myorganization/ux": "^3.0.0",`

Yarn is in fact different than npm.

**Comment by renatonmendes** [comment]
Thanks @evocateur.

> Yarn is in fact different than npm.
Is there any docs on thats differences?

**Comment by evocateur** [comment]
> Is there any docs on thats differences?

Well, I mean, `lerna bootstrap --npm-client yarn --use-workspaces` calls `yarn install` in the root (using yarn's largely-undocumented linking algorithm), and `lerna bootstrap --hoist` uses npm, using lerna's custom linking algorithm. I explained above why your examples were failing to link as expected.

https://yarnpkg.com/en/docs/workspaces
