### ISSUE TITLE
outdated with hoisted dependencies

### ISSUE THREAD

**Issue by oliveti** [lerna/lerna#1334]
## Expected Behavior
Being able to detect dependencies which provide an update and trigger the update.

## Current Behavior
There is no way to see which library should be updated when hoisted.
When dependencies are hoisted, a MISSING version is displayed when the `npm outdated` command is ran. 

## Possible Solution
provide a command like `lerna update`or `lerna outdated`

## Steps to Reproduce (for bugs)
1. execute `lerna exec --bail false -- npm outdated`
2. Observe the following output.

![package json portal-2 0 2018-03-19 15-45-41](https://user-images.githubusercontent.com/1235503/37602423-a31054d8-2b8c-11e8-82c6-0d26a0d9918f.png)

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.7.1 |
| `node --version` | v9.8.0 |

| OS | Version |
| ---: | :--- |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
Yeah, the same problem exists for `file:`-hoisted trees as well. I'm almost done implementing `lerna create`; alongside the current `lerna add` I was envisioning `lerna upgrade`, `lerna remove` and `lerna outdated`.

Recent refactoring has made figuring out the "external" dependencies of a given leaf package fairly straightforward. From there, we need to do two things per-dependency: figure out the version currently installed, and make request(s) to figure out wanted/latest (using either [`pacote`](https://github.com/zkat/pacote#manifest) or [`package-json`](https://github.com/sindresorhus/package-json)). Then we knit them back together (when outdated) for the output.

Lots of overlap between the proposed implementation of `lerna outdated` and `lerna upgrade` (indeed, `npm update` itself currently uses `npm outdated` behind the scenes). Realistically, these new commands won't be implemented before lerna v3 gets out of beta, but they are definitely on the roadmap.

**Comment by afrasso** [comment]
Any update on the `lerna outdated` command?

**Comment by evocateur** [comment]
Sorry, haven't gotten around to it. Might as well reopen this to track it.

**Comment by hiro5id** [comment]
bump

**Comment by evocateur** [comment]
Honestly, I would rather use [`pnpm` workspaces](https://pnpm.js.org/en/workspaces) + [`pnpm outdated`](https://pnpm.js.org/en/cli/outdated) or [`yarn` workspaces](https://yarnpkg.com/en/docs/workspaces) + [`yarn outdated`](https://yarnpkg.com/en/docs/cli/outdated#search) at this point.

**Comment by nunocastromartins** [comment]
Couldn't a simple version of `lerna outdated` when using `npm` do something similar to what Lerna already does for installing hoisted dependencies? I.e. create a temporary root `package.json` with all the merged dependencies and simply run `npm outdated` on the root. I imagine that most of the code already exists for this. For `yarn` Lerna could simply run `yarn outdated`.

I'm sure that I'm over-simplifying the solution, but what am I missing? :D

**Comment by burtonator** [comment]
There needs to be a solution for this... npm audit doesn't work for the same reasons

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
