### ISSUE TITLE
lerna publish - update dependency in root package.json

### ISSUE THREAD

**Issue by penx** [lerna/lerna#1335]
If one of my packages is a CLI tool, and I want to use this CLI in an npm script in the root package.json, e.g.

`packages/my-tool/package.json`:

```js
{
  "name": "@my-namespace/my-tool",
  "version": "0.0.1",
  "bin": {
    "my-tool": "bin/my-tool"
  }
}
```

`package.json`:

```js
{
  "name": "my-application",
  "version": "0.0.1",
  "devDependencies": {
    "@my-namespace/my-tool": "0.0.1"
  },
  "scripts": {
    "docs": "my-tool"
  }
}
```

When I:

- make changes to `@my-namespace/my-tool`
- run `lerna publish`

I would expect that:

1. `@my-namespace/my-tool` updates to 0.0.2
2.  the version number in the root `package.json` devDependencies is also updated.

However, currently (Lerna 2.9.0), 1 happens but 2 does not.

Is there any way to include the root package.json in package updates when running `lerna publish`?

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | v8.9.4 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.3 |

**Comment by evocateur** [comment]
Is your root package also published? (I don't recommend that, btw)

If it's never published (i.e., `"private": true` in package.json), the version number is irrelevant, and you can just use a local `file:` specifier:

```
  "devDependencies": {
    "@my-namespace/my-tool": "file:packages/my-tool"
  },
```

This is how lerna itself provides private test helpers to all of the published packages: https://github.com/lerna/lerna/blob/master/package.json#L27-L48

**Comment by penx** [comment]
ah great, no it isn't published, so that should work, thanks!

**Comment by penx** [comment]
Unfortunately in my case this wasn't a straight swap, as the CLI works fine when I use:

```
  "devDependencies": {
    "@my-namespace/my-tool": "0.0.1"
  },
```


but when I swap to:

```
  "devDependencies": {
    "@my-namespace/my-tool": "file:packages/my-tool"
  },
```

I get

```
Error: Cannot find module '@babel/runtime/regenerator'
```

Will try dig a little deeper.

**Comment by penx** [comment]
`@babel/runtime` is in the dependencies of `@my-namespace/my-tool`

When I have the following in the root:
```
  "devDependencies": {
    "@my-namespace/my-tool": "0.0.1"
  },
```

`lerna boostrap` correctly installs `@babel/runtime` in the root node_modules folder.

When I use

```
 "devDependencies": {
    "@my-namespace/my-tool": "file:packages/my-tool"
  },
```

`@babel/runtime` is not installed in the root node_modules folder or in the `packages/my-tool/node_modules` folder.

Is this a separate bug? Want me to raise another ticket?

**Comment by penx** [comment]
FWIW I am using Yarn workspaces

**Comment by evocateur** [comment]
Oh, that is useful information, since `file:` specifiers act differently in yarn vs npm (which is what lerna itself uses).

Instead of adding a dependency on the leaf package to the root package, why not just call the leaf CLI directly? It's okay to hard-code "internal" paths, as you are in the same repo after all. It's on yarn to execute the proper script lifecycles that do the tranpsiling, etc.

```
  "scripts": {
    "docs": "./packages/my-tool/bin/my-tool"
  }
```
(or whatever path the executable binary lives at)

**Comment by penx** [comment]
that works, thanks 🙂
