### ISSUE TITLE
Ignored "nohoist" in lerna.json

### ISSUE THREAD

**Issue by VladimirGrenaderov** [lerna/lerna#1337]
## Expected Behavior
Lerna should respect "nohoist" option in config

## Current Behavior
3.0.0-beta.4 ignores this option

## Possible Solution
Looks like a bug - concat nohoist to hoisting array, it should be something like filter:

      if (nohoist) {
        // `--nohoist ...` or lerna.json `nohoist: [...]`
        hoisting = hoisting.concat(nohoist);
      }

**Comment by evocateur** [comment]
What config is triggering this? Does the github issue template no longer include `<!-- Please paste your lerna.json here -->`?

**Comment by evocateur** [comment]
Nevermind, I got a repro. The test snapshot isn't exactly clear. :/

**Comment by VladimirGrenaderov** [comment]
I'm sorry for confusing - I thought that buggy code snippet from https://github.com/lerna/lerna/blob/master/commands/bootstrap/index.js makes it clear. So, do you need any additional info?

**Comment by evocateur** [comment]
Nope, just dealing with publish issues because I forgot a flag 😭
