### ISSUE TITLE
yarn "nohoist" configuration breaking lerna commands

### ISSUE THREAD

**Issue by p-ob** [lerna/lerna#1338]
It looks like the [new yarn workspaces configuration](https://yarnpkg.com/blog/2018/02/15/nohoist/) (where `"workspaces"` can either be an array or an object with a `"packages"` array property and `"nohoist"` glob pattern) breaks lerna. I'm assuming it has to do with the behavior of using the workspaces configuration as a 1:1 replacement for lerna.json's `"packages"` array. I didn't see any errors or fixes for this new feature of yarn logged, so apologies if this is a duplicate.

Here's a snapshot of the errors being logged:

> lerna run build
lerna info version 3.0.0-beta.7
lerna info versioning independent
lerna ERR! TypeError: packageConfigs.some is not a function
lerna ERR!     at collectPackages (C:\Users\pobrien\AppData\Roaming\nvm\v9.4.0\node_modules\lerna\node_modules\@lerna\collect-packages\collect-packages.js:20:41)
lerna ERR!     at chain.then (C:\Users\pobrien\AppData\Roaming\nvm\v9.4.0\node_modules\lerna\node_modules\@lerna\command\index.js:195:30)
lerna ERR!     at <anonymous>
lerna ERR!     at process._tickCallback (internal/process/next_tick.js:160:7)
lerna ERR!     at Function.Module.runMain (module.js:703:11)
lerna ERR!     at startup (bootstrap_node.js:193:16)
lerna ERR! lerna packageConfigs.some is not a function

## Expected Behavior
lerna commands should succeeed (I've tested `lerna run ...` and `lerna bootrap` and both failed; I assume other commands will fail).

## Current Behavior
Above error message gets logged and commands fail.

## Possible Solution
Check if the root package.json `"workspaces"` is an array or object; if the latter, pull the `"workspaces.packages"` property off and use that for lerna's packages.

## Steps to Reproduce (for bugs)

1. Create a lerna repo with a root package json like so:
```json
...
"workspaces": {
    "packages": "packages/*",
    "nohoist": "**/some-package"
},
...
```
2. Execute any lerna command (e.g. `lerna bootstrap`)
3. See errors

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.0.0-beta.7",
  "npmClient": "yarn",
  "npmClientArgs": ["--no-lockfile"],
  "useWorkspaces": true,
  "version": "independent"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv { _: [ 'run' ],
0 silly argv   help: false,
0 silly argv   h: false,
0 silly argv   version: false,
0 silly argv   v: false,
0 silly argv   'reject-cycles': undefined,
0 silly argv   rejectCycles: undefined,
0 silly argv   sort: undefined,
0 silly argv   ci: false,
0 silly argv   stream: undefined,
0 silly argv   parallel: undefined,
0 silly argv   private: true,
0 silly argv   'include-filtered-dependencies': false,
0 silly argv   includeFilteredDependencies: false,
0 silly argv   lernaVersion: '3.0.0-beta.7',
0 silly argv   '$0': 'C:\\Program Files\\nodejs\\node_modules\\lerna\\cli.js',
0 silly argv   loglevel: undefined,
0 silly argv   concurrency: undefined,
0 silly argv   'max-buffer': undefined,
0 silly argv   script: 'build',
0 silly argv   'npm-client': undefined,
0 silly argv   scope: undefined,
0 silly argv   ignore: undefined,
0 silly argv   since: undefined }
1 info version 3.0.0-beta.7
2 verbose rootPath C:\zywave-git\framework\resources\js
3 info versioning independent
4 error TypeError: packageConfigs.some is not a function
4 error     at collectPackages (C:\Users\pobrien\AppData\Roaming\nvm\v9.4.0\node_modules\lerna\node_modules\@lerna\collect-packages\collect-packages.js:20:41)
4 error     at chain.then (C:\Users\pobrien\AppData\Roaming\nvm\v9.4.0\node_modules\lerna\node_modules\@lerna\command\index.js:195:30)
4 error     at <anonymous>
4 error     at process._tickCallback (internal/process/next_tick.js:160:7)
4 error     at Function.Module.runMain (module.js:703:11)
4 error     at startup (bootstrap_node.js:193:16)

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 AND 3.0.0-beta.7 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | 9.4.0 |

| OS | Version |
| --- | --- |
| Windows 10 | 1703 |

**Comment by evocateur** [comment]
I could have sworn #1254 covered this...

Reading the blog post, both fields (packages and nohoist) are expected to be arrays:
```
// flow type definition:
export type WorkspacesConfig = {
  packages?: Array<string>,
  nohoist?: Array<string>,
};
```

So I guess it's fair for lerna to do some bare-minimum validation that yes, this property is an Array, and throw an error otherwise. Beyond that, I'd say this is yarn's responsibility to validate.

**Comment by p-ob** [comment]
Well, I feel dumb. I definitely just provided an invalid workspace configuration... I'll close this issue as "user error." Lerna shouldn't have to validate something like this. 

My mistake! Thanks for looking into it.
