### ISSUE TITLE
Lerna publish prefers home .npmrc over repository .npmrc

### ISSUE THREAD

**Issue by theetrain** [lerna/lerna#1340]
## Expected Behavior

When running `lerna publish`, I expect it to publish using the .npmrc token in the directory it is run.

## Current Behavior

When running `lerna publish`, it attempts to publish my packages using the .npmrc token in `~/.npmrc` and not the project root.

## Possible Solution

Prioritise the .npmrc token in the project root when running `lerna publish`.

## Steps to Reproduce (for bugs)

1. Run `lerna publish`
2. Select package versions
3. Publish fails when reading incorrect .npmrc token in `~/.npmrc`

```json
{
  "lerna": "2.9.0",
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "commands": {
    "publish": {
      "ignore": ["*.md", "*.spec.jsx"]
    }
  }
}
```

```txt
Error: Command failed: yarn publish --tag latest --new-version 1.0.1
error publish error An unexpected error occurred:
"https://registry.yarnpkg.com/@tds%2fcore-input: You must provide a one-time pass.
Upgrade your client to npm@latest in order to use 2FA.".
```

## Context

I was attempting to publish packages using an .npmrc token that differs from the one I had in my `$HOME` directory.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | v8.2.1 |

| OS | Version |
| --- | --- |
| macOS | 10.13.3 |

**Comment by evocateur** [comment]
Note that you're using `yarn` to publish, so the only expectation is that `yarn` reads the local `.npmrc` properly, not `lerna`.

That being said, consider that `yarn publish` (or `npm publish`, for that matter) is being executed with a CWD of the leaf package directory (`packages/foo`), _not_ the lerna root (usually the repository root). Right now, you'll probably need to workaround this by setting environment variables (`NPM_TOKEN`, and possibly `NPM_CONFIG_OTP` if you need a one-time password).

**Comment by theetrain** [comment]
I appreciate the explanation even though my query was out of lerna's scope 😄. I'll report back if there's any further insight, and you're welcome to close this issue for now.

**Comment by manelpb** [comment]
I'm also having the same issue :/

**Comment by doug-wade** [comment]
closing per https://github.com/lerna/lerna/issues/1340#issuecomment-374806710
