### ISSUE TITLE
lerna add allows for hoisting with yarn, but bootstrap errors out

### ISSUE THREAD

**Issue by Aghassi** [lerna/lerna#1341]
https://github.com/lerna/lerna/blob/19774fe32bb33544f6971e8586a37744c8be40e7/commands/bootstrap/index.js#L32

I've noticed that there is a consistency issue in the documentation. If I set the `npmClient` to `yarn`, I can still run `lerna add react --dev --hoist` if I want, and will perform a hoist. However, if I try to run `lerna bootstrap --hoist`, it errors out. Which of these is the intended use case? If `--hoist` should be allowed with bootstrap, can the check be removed?

**Comment by evocateur** [comment]
Yeah, that is a bit weird. `lerna bootstrap --hoist --npm-client yarn` is definitely _not_ intended to be valid, as yarn has several issues with concurrency that lerna's hoisting algorithm exposes quite painfully.

I'm increasingly convinced that `lerna add` shouldn't be automatically chaining `lerna bootstrap`. It's really not that hard to do oneself, and it's not even desirable when calling `lerna add` several times in sequence.

In any case, it's also weird that `lerna add` is accepting options only valid for `lerna bootstrap`, and that should definitely stop. _If_ chaining bootstrap is desirable, it should be limited to the command itself (along with durable "commands.bootstrap" config from lerna.json, if any), not consuming `lerna add`'s `argv`.

**Comment by Aghassi** [comment]
Thing is, hoisting is a very useful feature. It is like doing a `yarn install` or `npm install` and validating that your set of dependencies is correct. I quiet like how it says when sub dependencies differ in someway and leaves it there. I assumed `bootstrap` is the same as `yarn install`, but for the whole repo with all the stuff in `packages`. While I mainly work with `yarn`, if it is a current performance problem with `npm` then I can understand not wanting it. Would be nice to have both in the future.

Just would like a way to resolve common deps like `hoist` does at a top level at the end of the day. We are in the early stages of experiementing with this tool, so we were flexing our ideas when we came across this.

**Comment by evocateur** [comment]
`yarn install` with workspaces enabled completely replaces `lerna bootstrap --hoist`. Any warnings desired in that context is a yarn issue.

`npm` with relative `file:` specifiers (how lerna itself uses it) also completely replaces `lerna bootstrap --hoist`, with a completely package-locked tree and lightning-fast `npm ci`. You have to move `devDependencies` to the root (they aren't installed otherwise), but that should've been the case already in a monorepo.

**Comment by Aghassi** [comment]
So, there is one caveat with `yarn workspaces` that I'm still hung up on. You can't publish the repo, it needs to be a private package. Due to how we have things currently structured, we would like to ship the entire repo in NPM for various reasons. That's pretty much the only reason I haven't fully gone down that rabbit hole.

**Comment by evocateur** [comment]
The root `package.json` of a monorepo should be responsible for the _monorepo_ (coordinating repetitive test/build/linting hoisted from the leaves), not a "leaf" package that it governs. In other words, publishing the root of a monorepo is violating a separation of concerns.

The fact that it's _possible_ to do so in lerna today is the result of an API design mistake.

**Comment by Aghassi** [comment]
Ok, glad to clarify that point. I will wait to hear back regarding the hoisting mechanism regardless as I am interested in knowing the expected functionality.
