### ISSUE TITLE
not all packages published

### ISSUE THREAD

**Issue by pixelass** [lerna/lerna#1344]
I published via lerna publish , but not all packages were published to npm.

## Expected Behavior

When I force publish packages I expect them to be available on npm

## Current Behavior

Some (random) packages are not published (despite lerna confirmtion).

## Steps to Reproduce (for bugs)

**package.json**

```json
{
  "scripts": {
    "babel:packages": "yarn run clean:lib && lerna run babel",
    "clean:lib": "rimraf @dekk/*/lib",
    "prerelease": "yarn run test && yarn run babel:packages",
    "release": "lerna publish --conventional-commits --force-publish=*"
  },
  "private": true,
  "workspaces": [
    "@dekk/*"
  ]
}
```

```
$ lerna publish --conventional-commits --force-publish=*
lerna info version 2.9.0
lerna info current version 1.2.3
lerna info Checking for updated packages...
lerna info Comparing with v1.2.3.
lerna info Checking for prereleased packages...

Changes:
 - @dekk/animation: 1.2.3 => 1.3.0
 - @dekk/autoplay: 1.2.3 => 1.3.0
 - @dekk/countdown: 1.2.3 => 1.3.0
 - @dekk/deck: 1.2.3 => 1.3.0
 - @dekk/dekk: 1.2.3 => 1.3.0
 - @dekk/fragment: 1.2.3 => 1.3.0
 - @dekk/icon: 1.2.3 => 1.3.0
 - @dekk/image: 1.2.3 => 1.3.0
 - @dekk/listener: 1.2.3 => 1.3.0
 - @dekk/local-storage: 1.2.3 => 1.3.0
 - @dekk/master-slides: 1.2.3 => 1.3.0
 - @dekk/master: 1.2.3 => 1.3.0
 - @dekk/paging: 1.2.3 => 1.3.0
 - @dekk/pubnub: 1.2.3 => 1.3.0
 - @dekk/slide: 1.2.3 => 1.3.0
 - @dekk/speaker-deck: 1.2.3 => 1.3.0
 - @dekk/speaker-notes: 1.2.3 => 1.3.0
 - @dekk/store: 1.2.3 => 1.3.0
 - @dekk/text: 1.2.3 => 1.3.0
 - @dekk/url: 1.2.3 => 1.3.0
 - @dekk/utils: 1.2.3 => 1.3.0

? Are you sure you want to publish the above changes? Yes
lerna info publish Publishing packages to npm...
lerna info published @dekk/image
lerna info published @dekk/countdown
lerna info published @dekk/icon
lerna info published @dekk/animation
lerna info published @dekk/paging
lerna info published @dekk/speaker-notes
lerna info published @dekk/store
lerna info published @dekk/text
lerna info published @dekk/utils
lerna info published @dekk/autoplay
lerna info published @dekk/listener
lerna info published @dekk/fragment
lerna info published @dekk/deck
lerna info published @dekk/slide
lerna info published @dekk/url
lerna info published @dekk/pubnub
lerna info published @dekk/local-storage
lerna info published @dekk/speaker-deck
lerna info published @dekk/master
lerna info published @dekk/dekk
lerna info published @dekk/master-slides
lerna info git Pushing tags...
Successfully published:
 - @dekk/animation@1.3.0
 - @dekk/autoplay@1.3.0
 - @dekk/countdown@1.3.0
 - @dekk/deck@1.3.0
 - @dekk/dekk@1.3.0
 - @dekk/fragment@1.3.0
 - @dekk/icon@1.3.0
 - @dekk/image@1.3.0
 - @dekk/listener@1.3.0
 - @dekk/local-storage@1.3.0
 - @dekk/master-slides@1.3.0
 - @dekk/master@1.3.0
 - @dekk/paging@1.3.0
 - @dekk/pubnub@1.3.0
 - @dekk/slide@1.3.0
 - @dekk/speaker-deck@1.3.0
 - @dekk/speaker-notes@1.3.0
 - @dekk/store@1.3.0
 - @dekk/text@1.3.0
 - @dekk/url@1.3.0
 - @dekk/utils@1.3.0
lerna success publish finished
✨  Done in 197.05s.
```

**Result on npm**

<img width="297" alt="screen shot 2018-03-22 at 15 16 31" src="https://user-images.githubusercontent.com/1148334/37775805-2b24a672-2de4-11e8-8561-cbe34bbdeb51.png">

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.5.1",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "1.3.0",
  "packages": [
    "@dekk/*"
  ]
}
```

</p></details>

## Context

I want to ensure consistent version numbers for all my packages. 
Currently this is not possible because not all packages are published. This breaks the simplicity of
using my library in different versions. 

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | v8.10.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.6 |

**Comment by sgwilym** [comment]
I'm having this problem all of a sudden with Lerna 2.8.0, and also when `force-publish` is _not_ being used. This problem coinciding with NPMs big website update seems a bit suspect, and I wonder if it's not some kind of change on NPM's part which is making packages not publish even when Lerna reports it as successfully done.

**Comment by pixelass** [comment]
I also got this issue without `-force-publish=*`.

I was hoping that the flag would fix the issue.

**Comment by sgwilym** [comment]
I hate to say it, but trying again worked, making me think this is definitely a hiccup on NPM's side.

**Comment by pixelass** [comment]
I also think it might be a hiccup somewhere. 
I experienced this twice in the last two days. 

It is uncertain to say though since I don't manually check all packages after publishing.

**Comment by bjoerge** [comment]
I'm also having this issue. Lerna reports that all packages were successfully published, but only some of the packages actually gets published. Not sure if the issue is on the lerna side or the npm side.

Manually publishing the missing packages from within each package subfolder works.

It's also possible to run `lerna exec --bail=false -- npm  publish` and ignore the errors for the conflicting versions.

**Comment by evocateur** [comment]
You... `--force-publish` _everything_ on _every_ release? That's, uh, interesting.

Notably, you're using `yarn` to publish, so this isn't necessarily an npm bug. Who knows what demons lurk in the yarn codebase. In my experience, there are harsh edge-cases with `yarn`.

**Comment by bjoerge** [comment]
I had this issue without `--force-publish=*` though.  And it happened when just publishing two packages for a patch release. One package got published, the other did not (lerna still reported both as successfully published).

But yeah, I'm using `yarn` as `npmClient`.

**Comment by pixelass** [comment]
> You... --force-publish everything on every release? That's, uh, interesting.

I actually only tried it to work around the issue (https://github.com/lerna/lerna/issues/1344#issuecomment-375329644)

> Notably, you're using yarn to publish, so this isn't necessarily an npm bug. Who knows what demons lurk in the yarn codebase. In my experience, there are harsh edge-cases with yarn.

I guess you are referring to this:

```json
{
  "npmClient": "yarn"
}
```

**Comment by evocateur** [comment]
Yes. `npm publish` has a lot of battle-tested code in it, whereas `yarn publish` is in many ways less mature, despite copious test coverage. There are even some edge cases where incompatible decisions were made by the yarn team, so it's hard to say exactly where the issue lies.

**Comment by byCedric** [comment]
Well, I'm not sure if I'm doing it wrong but I guess I also get this update. A package was updated, including the cross reference, when using `lerna publish`. But, and here is the fun part, the one that got published actually depends (in de dependencies list) on the newer version of the non-published package 😅 So that means that everyone who (partially) gets the new update will have a bad time of crashing npm when using exact versions... 

When trying to fix this with `--force-publish` I was also left in the cold. As @pixelass and @bjoerge point out already, the `--force-publish` doesn't do anything... So I guess I have to workaround this for now with `lerna exec --bail=false -- npm publish`. But please, keep in mind that this is not very user friendly for noobs like me.

**Comment by evocateur** [comment]
Lerna is only able to read the exit code of the CLI it calls to publish (npm or yarn), so I’m not really sure what lerna’s responsibility is here, other than calling the binaries with the correct arguments.

**Comment by byCedric** [comment]
Ah well, I guess you can safely say that I was doing it wrong then 😬 If its a constraint by NPM or the NPM registry, well, that kinda rules Lerna out as you said. But maybe its an idea to put information about these constraints somewhere in the docs? That way me, and my fellow noobs, will not raise unnecessary issues 😬

**Comment by pixelass** [comment]
Moving away from Github. Feel free to reopen if interested.
