### ISSUE TITLE
Using squashed commits for releases results in lerna publish listing all packages

### ISSUE THREAD

**Issue by penx** [lerna/lerna#1345]
## Our Workflow

- Developers that are able to propose a release do not have push access to master, all changes go via a pull request on GitHub.
- Pull requests are set to squash commit to master by default.
- A developer runs `lerna publish --skip-npm` on a branch of master and opens a pull request with the version increment.
- When merged, the default commit message added by GitHub is `v1.0.0 (#101)` which is the Lerna generated version number followed by the GitHub pull request ID.

## Expected Behavior

After following the workflow above, I would expect `lerna updated` to list no new changes on master immediately after a release.

## Current Behavior

All packages are listed as containing changes, I assume because Lerna is looking for a commit message of `v1.0.0` for a release, and does not match `v1.0.0 (#101)`.

## Possible Solution

When looking for published versions in commit messages, match an optional pull request ID following the version number (e.g. `v1.0.0 (#101)`) with a regex.

## Steps to Reproduce (for bugs)

Our release process is [here](https://github.com/penx/govuk-react/blob/master/CONTRIBUTING.md#releasing).

This is partially scripted [here](https://github.com/penx/govuk-react/blob/master/scripts/release.sh).

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | v8.9.4 |

**Comment by evocateur** [comment]
You're deleting the tag, so lerna has literally no idea what the diff from the "last release" was. (Squashing would mangle the tag anyway)

Why not wait until the PR is merged to publish? I don't understand encumbering the developer with `lerna publish --skip-npm`. If you're using `--conventional-commits`, the process is quite automated. I don't recommend publishing from feature branches at all.
