### ISSUE TITLE
[Q] Is there a way to reference older versions of packages?

### ISSUE THREAD

**Issue by Brantron** [lerna/lerna#1346]
within lerna I have packages `A` and `B`. 
`B` has a dependency on `A`
If a breaking change is published to `A`, how do we lock the last working version of package `A` in package `B` until there is time to resolve the issue?

**Comment by evocateur** [comment]
You can manually edit `B`'s package.json to depend on `"A": "^1.0.0"` (if `A` was bumped to `2.0.0`), and it will install the old version.

_However_, this does mean that during development, until resolved, `A` and `B` are no longer linked, so any "parallel" development won't actually be parallel. Part of the advantage of a monorepo is that you can address those breaking changes at the same time, so even when the packages are versioned independently, they still maintain compatibility.

**Comment by Brantron** [comment]
Thanks for the quick response. We assumed that we would lose the ability to symlink but changing the versions to a previous release does this
`lerna ERR! error Couldn't find any versions for "A" that matches "1.0.0"`

**Comment by evocateur** [comment]
Well, that requires that `A@^1.0.0` be published to the registry. This does effectively mean you lose the symlink that results from `lerna bootstrap`.

**Comment by Brantron** [comment]
Hmm, if it relies on the registry does that mean itcan not work with private repos? The idea is to fix the breaking changes as quickly as possible so we can regain the symlinks and parallel development.

**Comment by evocateur** [comment]
"Private" as in "never published to _any_ registry" or "published to a private registry, not https://registry.npmjs.org"?

I guess the assumption with a lerna-based monorepo is that you fix the consumer at the same time as the provider is being broken. It's one of the major value-propositions of a monorepo.

**Comment by Brantron** [comment]
Ahh, this makes sense. We've never published to any registry. Thanks! The hotfix happened before we needed to resort to anything else.
