### ISSUE TITLE
add bail argument to lerna run

### ISSUE THREAD

**Issue by ozsay** [lerna/lerna#1351]
`bail` is an argument for the `exec` command which is useful when you want to `bail` or not on arbitrary commands.

This argument can also be useful to run on `npm` scripts.

One example (my issue), is running a custom lint npm script without bailing to get a full repository report. now, when the lint fails in one of the packages, the command stops immediately.

## Expected Behavior
Should work the same as it's implemented in `exec`.

**Comment by evocateur** [comment]
Sounds reasonable to me.
