### ISSUE TITLE
Create command fails with npm not relative to node

### ISSUE THREAD

**Issue by Alxandr** [lerna/lerna#1353]
The create command fails, because it's trying to stat a file that doesn't exist:

![image](https://user-images.githubusercontent.com/112334/38114912-6e8189dc-33aa-11e8-897a-12c0a49a3dc9.png)

It should not assume npm to be relative to node.

## Expected Behavior

It should not crash.

## Current Behavior

It's crashing.

## Workaround

In my case, creating a symlink to `npm` next to the node executable solved the problem.

## Steps to Reproduce (for bugs)

1. Have node and npm not installed next to eachother. I have that via homebrew. My path to node is `/usr/local/Cellar/node/9.9.0/bin/node`, whereas `npm` is installed at `/usr/local/lib/node_modules/npm/bin/npm-cli.js`.
2. Run `lerna create <name>`.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv { _: [ 'create' ],
0 silly argv   help: false,
0 silly argv   h: false,
0 silly argv   version: false,
0 silly argv   v: false,
0 silly argv   'reject-cycles': undefined,
0 silly argv   rejectCycles: undefined,
0 silly argv   sort: undefined,
0 silly argv   ci: false,
0 silly argv   lernaVersion: '3.0.0-beta.11',
0 silly argv   '$0': '/usr/local/bin/lerna',
0 silly argv   loglevel: undefined,
0 silly argv   concurrency: undefined,
0 silly argv   'max-buffer': undefined,
0 silly argv   name: '@yolodev/workdir-pid',
0 silly argv   loc: undefined,
0 silly argv   access: undefined,
0 silly argv   bin: undefined,
0 silly argv   description: undefined,
0 silly argv   dependencies: undefined,
0 silly argv   'es-module': undefined,
0 silly argv   homepage: undefined,
0 silly argv   keywords: undefined,
0 silly argv   license: undefined,
0 silly argv   private: undefined,
0 silly argv   registry: undefined,
0 silly argv   tag: undefined,
0 silly argv   yes: undefined }
1 info version 3.0.0-beta.11
2 verbose rootPath /Users/alxandr/hub/yolodev-aspnet-utils
3 silly isInitialized
4 silly isInitialized true
5 error Error: ENOENT: no such file or directory, lstat '/usr/local/Cellar/node/9.9.0/bin/npm'
5 error     at Object.realpathSync (fs.js:1690:15)
5 error     at builtinNpmrc (/usr/local/lib/node_modules/lerna/node_modules/@lerna/create/lib/builtin-npmrc.js:12:26)
5 error     at CreateCommand.initialize (/usr/local/lib/node_modules/lerna/node_modules/@lerna/create/index.js:89:23)
5 error     at Promise.resolve.then (/usr/local/lib/node_modules/lerna/node_modules/@lerna/command/index.js:220:24)
5 error     at <anonymous>
```
</p></details>

## Your Environment

OSX, node installed from homebrew. Don't remember where npm is installed from, but considering it's path I'd say it's likely installed using `npm` itself.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-beta.11 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | v9.9.0 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.3 |

**Comment by Alxandr** [comment]
That may very well be so, but I think the community you'd have to convince is rather huge ^^

**Comment by evocateur** [comment]
Oh, sure, I didn't mean to imply I'm not going to fix this, I just completely forgot about this case.

**Comment by Alxandr** [comment]
Yeah, I got that. I was just joking :)

**Comment by evocateur** [comment]
Published in v3.0.0-beta.12

**Comment by Alxandr** [comment]
Wouldn't it be better to try to locate npm by way of `where npm` (ie. scan $PATH). That way you would get the noe the user is using (unless they specifically ran another one).

**Comment by evocateur** [comment]
The builtin npmrc is a rare edge-case; if it isn’t in the standard location, it’s not likely to exist anywhere.
