### ISSUE TITLE
jsonschema for lerna.json

### ISSUE THREAD

**Issue by Meir017** [lerna/lerna#1356]
I couldn't find anywhere the complete schema for a `lerna.json` file

The closest thing I found is https://github.com/lerna/lerna#lernajson

Would be nice to have a jsonschema for this, then we will have autocomplete in IDE's

**Comment by evocateur** [comment]
`lerna.json` isn't meant to be an actively-edited file, but rather to serialize CLI options to make things consistent for all contributors. It also sounds like a maintenance nightmare.

**Comment by Meir017** [comment]
for it to be a maintenance nightmare it would have to change a lot with will make its current documentation a maintenance nightmare.

**Comment by evocateur** [comment]
This assumes that the current documentation is accurate and complete...

**Comment by Meir017** [comment]
ok
