### ISSUE TITLE
lerna exec does not work correctly with glob patterns

### ISSUE THREAD

**Issue by nareshbhatia** [lerna/lerna#1358]
## Expected Behavior
Here are some scripts from my package.json - first version with `lerna exec`, the other without. All commands use a quoted glob pattern so that the pattern is expanded by the commands (eslint and prettier) and not by the shell. The expected behavior is that all js files in all packages be linted and prettified.

```
"scripts": {
    "lint": "lerna exec --parallel -- eslint 'src/**/*.js'",
    "lint-packages": "eslint 'packages/*/src/**/*.js'",
    "format": "lerna exec --parallel -- prettier --print-width 80 --tab-width 4 --single-quote --write 'src/**/*.js'",
    "format-packages": "prettier --print-width 80 --tab-width 4 --single-quote --write 'packages/*/src/**/*.js'",
}
```

## Current Behavior
Non-lerna versions of the commands are picking up all files as expected. The `lerna exec` versions are missing many files. My guess is that somehow the quoted glob patterns are being interpreted by the shell instead of the target command.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.8.0 |
| `node --version` | 8.7.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
In the case of `eslint` and `prettier`, you should be using the direct calls anyway. `lerna exec` is a redundant wrapper in those cases.

As for quoting globs, I think you're right, the command is being zapped by shell interpretation twice: once when `npm run` executes the script value, and then again when `lerna exec` executes the double-dashed parameters. If you escape the single quotes (normally not necessary, of course), perhaps that might work?

But seriously, just call `eslint` and `prettier` directly. All linting, testing, and build-related tasks in a monorepo should be hoisted to the root.

**Comment by nareshbhatia** [comment]
Sounds good, @evocateur. Thanks for the guidance.
