### ISSUE TITLE
useWorkspaces not working with nohoist config of yarn workspaces

### ISSUE THREAD

**Issue by gmfun** [lerna/lerna#1359]
{
      ...
      "npmClient": "yarn",
      "useWorkspaces": true
    }

This doesnt work when `package.json` has workspaces configured as follows

    "workspaces": {
        "packages": [
          "packages/*"
        ],
        "nohoist": [
          "**/js-cookie",
          "**/codelyzer"
        ]
      },

works fine it its like older config of workspaces

    "workspaces":[
          "packages/*"
     ],

## Expected Behavior
Should work with new workspaces config

## Current Behavior
throws an error `TypeError: packageConfigs.some is not a function`

**Comment by bertho-zero** [comment]
You can try to upgrade `yarn`.

**Comment by gmfun** [comment]
@bertho-zero on the latest version of yarn

**Comment by bertho-zero** [comment]
Ok, I use the new workspaces config shape and it works fine with lerna.

**Comment by gmfun** [comment]
yup my bad, updating lerna worked. Thanks
