### ISSUE TITLE
Can't publish on latest npm tag after published on next tag

### ISSUE THREAD

**Issue by drazik** [lerna/lerna#1364]
If I publish something with a dist tag, like "next", I cannot publish with no dist tag afterwards since lerna sees the git tags and thinks there is nothing to update.

## Expected Behavior

After publishing a version with a dist tag, when running publish again, it should be possible to publish the new version.

## Current Behavior

Lerna does not see anything to publish.

## Possible Solution

When adding a tag for a dist tag other than latest, lerna could put the name of the dist tag in the tag so that lerna can differentiate between a dist-tag publishing and a normal one.

## Steps to Reproduce (for bugs)

$ lerna publish --npm-tag next
$ lerna publish

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.4.0",
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn"
}
```
</p></details>

## Context

I published new versions of my packages on the `next` tag and now I want to publish it to the `latest` tag. But I can't without using `--force-publish`.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.8.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | 9.6.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Ubuntu | 16.04 |

**Comment by evocateur** [comment]
That's not how `lerna publish` is meant to be used in combination with dist-tags. Basically, once `lerna publish --npm-tag next` has completed, it's up to you to use [`npm dist-tag`](https://docs.npmjs.com/cli/dist-tag) to change the dist-tag pointer, not another `lerna publish`.

`lerna exec` can be used to set the `latest` dist-tag to the value of the `next` dist-tag (if it exists):

```sh
npx lerna exec --no-bail --no-private --no-sort --stream -- '[ -n "$(npm v . dist-tags.next)" ] && npm dist-tag add ${LERNA_PACKAGE_NAME}@$(npm v . dist-tags.next) latest'
```
(note the single quotes, they're important, delaying interpretation of the shell expressions)
