### ISSUE TITLE
lerna publish --no-verify option

### ISSUE THREAD

**Issue by hjylewis** [lerna/lerna#1366]
## Expected Behavior
Running `lerna publish` publishes to npm and pushes changes to git without going through prepush validation scripts.

## Current Behavior
When you run `lerna publish` and it goes to push the changes using git, it will silently trigger any prepush scripts. In the case where those scripts a while, it looks like lerna is hanging.

## Possible Solution
Add a `--no-verify` flag to `lerna publish` that pushes to git using the `--no-verify` flag. That or show the logging of the prepush scripts.

**Comment by evocateur** [comment]
We already pass `--no-verify` directly to [`git commit`](https://github.com/lerna/lerna/blob/d7e33c6e422934a37302f5e78e226423e3abcf04/core/git-utils/index.js#L53), I don't see why we can't do that for [`git push`](https://github.com/lerna/lerna/blob/d7e33c6e422934a37302f5e78e226423e3abcf04/core/git-utils/index.js#L109-L110) too (and maybe condense those two calls into one?). It's silly to validate lerna commits and pushes, as it's implied that any validation has been done already.

**Comment by hjylewis** [comment]
I agree. If you point me in the right direction, I won't mind making a PR.

**Comment by evocateur** [comment]
Yeah, basically those two places I linked, and then modifying relevant unit test assertions. I don't think we really have to go whole-hog and have an integration test with a pre-push hook, we can just assume `git` knows what its doing.

**Comment by hjylewis** [comment]
Whoops, missed your links. Sounds good!
