### ISSUE TITLE
Lerna fails to add scoped package from private registry

### ISSUE THREAD

**Issue by wsrast** [lerna/lerna#1368]
## Expected Behavior
Lerna add command installs new package

## Current Behavior
Error message:
@ C:\sources\proj-lerna
> lerna add @company/proj
lerna info version 2.10.1
lerna info versioning independent
lerna ERR! initialize callback with error
lerna ERR! RequestError: connect ETIMEDOUT 13.107.6.175:443
lerna ERR!     at ClientRequest.req.once.err (C:\Users\user\AppData\Local\Yarn\Data\global\node_modules\package-json\node_modules\got\index.js:73:21)
lerna ERR!     at Object.onceWrapper (events.js:272:13)
lerna ERR!     at ClientRequest.emit (events.js:180:13)
lerna ERR!     at TLSSocket.socketErrorListener (_http_client.js:395:9)
lerna ERR!     at TLSSocket.emit (events.js:180:13)
lerna ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
{ RequestError: connect ETIMEDOUT 13.107.6.175:443
    at ClientRequest.req.once.err (C:\Users\user\AppData\Local\Yarn\Data\global\node_modules\package-json\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:272:13)
    at ClientRequest.emit (events.js:180:13)
    at TLSSocket.socketErrorListener (_http_client.js:395:9)
    at TLSSocket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
  code: 'ETIMEDOUT',
  message: 'connect ETIMEDOUT 13.107.6.175:443',
  host: 'my-private-registry.pkgs.visualstudio.com',
  hostname: 'my-private-registry.pkgs.visualstudio.com',
  method: 'GET',
  path: '/_packaging/npm-feed/npm/registry/@company%2Fproj',
  exitCode: 1 }

## Steps to Reproduce (for bugs)
1. Create new folder
2. In folder, "lerna add @company/package"
3. Error

<details><summary>lerna.json</summary><p>

```json
{
	"lerna": "2.10.1",
	"packages": ["packages/*"],
	"version": "independent",
	"npmClient": "yarn"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ '@company/proj' ]
1 silly flags { _: [ 'add' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   args: [ '@company/proj' ] }
2 verbose rootPath C:\sources\proj-lerna
3 info version 2.10.1
4 silly isInitialized
5 silly isInitialized true
6 silly existsSync C:\sources\proj-lerna\VERSION
7 info versioning independent
8 silly initialize attempt
9 error initialize callback with error
10 error RequestError: connect ETIMEDOUT 13.107.6.175:443
10 error     at ClientRequest.req.once.err (C:\Users\user\AppData\Local\Yarn\Data\global\node_modules\package-json\node_modules\got\index.js:73:21)
10 error     at Object.onceWrapper (events.js:272:13)
10 error     at ClientRequest.emit (events.js:180:13)
10 error     at TLSSocket.socketErrorListener (_http_client.js:395:9)
10 error     at TLSSocket.emit (events.js:180:13)
10 error     at emitErrorNT (internal/streams/destroy.js:64:8)
```
</p></details>

## Context
Trying to set up a first-time Lerna monorepo to manage a large set of related modules

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.10.1
| `npm --version`  | 5.6.0
| `yarn --version` | 1.5.1
| `node --version` | 9.11.1

| OS | Version |
| --- | --- |
| Windows 10 | 10.0.15063 |

**Comment by wsrast** [comment]
It reports the package info as it should. All other use cases with NPM or Yarn work properly in any other reference frame.

**Comment by evocateur** [comment]
> All other use cases with NPM or Yarn work properly in any other reference frame.

Schucks, I was hoping for an easy fix. I wonder if [`package-json`](https://github.com/sindresorhus/package-json) might be the culprit? The underlying [registry-url](https://github.com/sindresorhus/registry-url/blob/master/index.js) doesn't consult any yarn-specific config, and could possibly be missing the custom registry config somehow?

**Comment by wsrast** [comment]
Can you recommend a course of action based on your assertion? I'm not sure how to proceed from that.

**Comment by evocateur** [comment]
In a lerna-based monorepo: `node -e 'require("package-json")("@company/proj").then(console.log)'`

If it errors, then that's the culprit. If it doesn't, then it's somehow lerna's fault, and I really don't have time to debug that rabbit's hole right now.

**Comment by wsrast** [comment]
Ah, that's great, thanks. I'll give that a try first thing tomorrow. Thanks for the quick response. I'll let you know what happens.

**Comment by wsrast** [comment]
Okay, so tried the above command, and it seems to do nothing at all, but there's also no error message. So, digging further, I first installed the package-json module to the root workspace (couldn't find it otherwise), then used the following code and ran it from the command line, using sindresorhus's example from the package-json docs.

test.js:
`const packageJson = require('package-json');

packageJson('@sindresorhus/df')
	.then(json => {
		console.log(json);
	})
	.catch(err => {
		console.error(err);
	});`

Received this error message:

`{ RequestError: connect ETIMEDOUT 13.107.6.175:443
    at ClientRequest.req.once.err (C:\sources\proj-lerna\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:272:13)
    at ClientRequest.emit (events.js:180:13)
    at TLSSocket.socketErrorListener (_http_client.js:395:9)
    at TLSSocket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
  code: 'ETIMEDOUT',
  message: 'connect ETIMEDOUT 13.107.6.175:443',
  host: 'proj-test.pkgs.visualstudio.com',
  hostname: 'proj-test.pkgs.visualstudio.com',
  method: 'GET',
  path: '/_packaging/npm-feed/npm/registry/@sindresorhus%2Fdf' }`

I then decided to eliminate Lerna as a variant, and created a separate folder outside the Lerna workspace, ported the same test.js code file above to that new folder, ran npm init, then added package-json to the project. I reran the test.js file, and received exactly the same error.

My suspicion is that because the private VSTS NPM registry requires authentication, that package-json isn't equipped to read the VSTS token out of the %userprofile%/.npmrc file, so every attempt to request a package will fail.

I tested this by using a "yarn add @company/proj" from that new project folder, and it worked perfectly; no issues with authentication or timeouts.

I then tried populating the HTTP_PROXY and HTTPS_PROXY DOS variables, just in case, and neither of those helped. I don't know of a way for me to tell whether package-json is failing because of the proxy or authentication.

Anyway, this doesn't look like Lerna's problem. Is there an easy way to shift this conversation onto package-json's plate?

**Comment by evocateur** [comment]
@wsrast Good investigation, thanks! I suspect https://github.com/sindresorhus/package-json/issues/35 (opened 9 months ago) might be related to this (if it's an SSL problem)?

Your research would merit opening an issue in `package-json`'s repo, demonstrating a minimal reproduction. Not sure what the ultimate fix is, though it doesn't hurt to start the conversation there.

**Comment by m11m** [comment]
As a temporary fix, we could pass the `rejectUnauthorized` through `got` library.

https://nodejs.org/api/tls.html#tls_new_tls_tlssocket_socket_options

**Comment by m11m** [comment]
https://github.com/sindresorhus/package-json/pull/44

**Comment by m11m** [comment]
Also, https://stackoverflow.com/questions/29283040/how-to-add-custom-certificate-authority-ca-to-nodejs
