### ISSUE TITLE
ignore a whole dedicated folder (../some-folder) when running lerna run foo) ?

### ISSUE THREAD

**Issue by SerkanSipahi** [lerna/lerna#1370]
Its possible to ignore a whole dedicated folder (`../some-folder`) when running `lerna run foo`)? I found nothing in the [commands](https://github.com/lerna/lerna#commands) that can resolve my problem and dont know if that possible! It seems like you can only exclude modules. 

I hope I could explain what I want to achieve.

My lerna file looks like this (see below)?

```
{
  "packages": [
    "./packages/*",
    "../some-folder/**/packages/*"
  ],
  "version": "0.0.0"
}
```
## My Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-beta.14 |
| `npm --version`  | 5.5.1 |
| `node --version` | 9.3.0 |

**Comment by evocateur** [comment]
`"../some-folder/**/packages/*"` is an extremely unexpected package location. It looks like a completely different monorepo, to be honest.

No, there isn't support for ignoring directories. If you need to ignore a directory, consider that that directory probably shouldn't be included in the monorepo?

`lerna run` already ignores packages that don't have a given script. If it's impossible to properly split the monorepo, I would just change the script name that you want to partially target.

**Comment by SerkanSipahi** [comment]
I found a solution/idea `lerna run foo --scope={$(getAllModulesCommaSeparated --folder=packages)}`

`getAllModulesCommaSeparated` is a simple script which returns comma separated each module name (folder) name from passed argument (--folder=packages)

**Comment by SerkanSipahi** [comment]
We all (many teams) work together on a huge project with many different dependencies (package.json) and lot of testing files. A deployment (pipeline) would take a lot of time, because of the integration (browser) tests! For this reason, we have decided to distribute the project in several monorepos and to consume them (different monorepo) when needed (only the packages, these usually do not have many dependencies). 

I hope that was understandable.

**Comment by evocateur** [comment]
No, I don't think this is generally useful, nor a pattern that I want to promote. Lerna is meant to manage npm packages, not deployment pipelines or multiple monorepos.

**Comment by SerkanSipahi** [comment]
your opinion: "not for deployment pipelines or multiple monorepos" but it can be used for that and it works well on very large teams with the advantages listed :) 

Thank you for your feedback.

**Comment by SerkanSipahi** [comment]
This was not what i meant in my last thread post! I already understood that you dont want to introduce the feature because of maintenance. I will solve it differently :)

What i meant was the context of the feature: 
>"not for deployment pipelines or multiple monorepos" but it can be used for that and it works well on very large teams with the advantages listed :)

BTW: thank you so much for maintaining lerna and make it future ready for v3 :)

**Comment by evocateur** [comment]
Thanks for understanding :)

**Comment by SerkanSipahi** [comment]
This is the command for those who want to run the run command in their monorepo:

`lerna run someCommand --scope=$(ls $(pwd)/packages | xargs echo | sed 's/ /,/g')`

**Comment by punkusha** [comment]
> This is the command for those who want to run the run command in their monorepo:
> 
> `lerna run someCommand --scope=$(ls ./packages | xargs echo | sed 's/ /,/g')`

you forgot to add braces, correct script:
`lerna run someCommand --scope={$(ls ./packages | xargs echo | sed 's/ /,/g')}`
