### ISSUE TITLE
allow lerna to specify the config file

### ISSUE THREAD

**Issue by zhaochy1990** [lerna/lerna#1371]
allow lerna to specify the config file, perhaps add a new options `--config`

## Expected Behavior

I meet the following requirements, for some project we need a lerna.json and another scenario we need another lerna.json, we hope lerna can specify the config file by `--config`, and the `lerna.json` are still worked as the default behavior.

the expected behavior would be like this:
```bash
lerna bootstrap --config configA.json
lerna publish --config configA.json
lerna clean --config configA.json

lerna bootstrap --config configB.json
lerna publish --config configB.json
lerna clean --config configB.json
```
## Current Behavior

current lerna use `lerna.json` as the config and can't dynamic config it

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.10.1 |
| `npm --version`  | 5.8.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | 8.10.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
One project, one lerna.json, one monorepo. If you have multiple projects, they should be in multiple monorepos. Sorry.
