### ISSUE TITLE
Show immediate log output of npm scripts on publish command

### ISSUE THREAD

**Issue by gemambu** [lerna/lerna#1372]
## Expected Behavior

It would be very useful to get the npm output when running publish command.

## Current Behavior

Running publish command, the npm output it not displayed, and it would be interesting when npm throws errors or other messages.

When I run publish command in an specific package, I can see npm logs, for example:

```
~/example/packages/myExample on git:master x [9:34:21]
$ npm publish --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'publish',
npm verb cli   '--verbose' ]
npm info using npm@5.6.0
npm info using node@v8.9.4

npm info lifecycle myExample@2.0.0~prepublish: myExample@2.0.0
...
npm verb getPublishConfig undefined
npm verb publish registryBase https://xxxx/npm/
npm verb request uri https://xxxx/npm/myExample
...
npm verb headers   date: 'Thu, 12 Apr 2018 07:34:33 GMT',
npm verb headers   'transfer-encoding': 'chunked' }
npm verb stack Error: cannot modify pre-existing version
npm verb stack     at conflictError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:189:11)
...
npm verb stack     at process._tickCallback (internal/process/next_tick.js:180:9)
npm verb pkgid myExample
npm verb cwd /example/packages/myExample
npm verb Darwin 17.4.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish" "--verbose"
npm verb node v8.9.4
npm verb npm  v5.6.0
npm ERR! code EPUBLISHCONFLICT
npm ERR! publish fail Cannot publish over existing version.
npm ERR! publish fail Update the 'version' field in package.json and try again.
npm ERR! publish fail
npm ERR! publish fail To automatically increment version numbers, see:
npm ERR! publish fail     npm help version
npm verb exit [ 1, true ]
...
npm ERR! A complete log of this run can be found in:
npm ERR!     /example/.npm/_logs/xxx-debug.log
```

And when I execute the lerna command to publish all the packages, the output it's similar to:

```
/example/packages on git:master x [11:00:50]
$ npm run publish

> test_npm@1.0.0 publish /example/test_npm
> lerna publish watch --stream --skip-git verbose -- --verbose

lerna info version 2.10.1
lerna info current version 3.3.4
lerna info Checking for updated packages...
lerna info Comparing with initial commit.
lerna info Checking for prereleased packages...
? Select a new version (currently 3.3.4) Patch (3.3.5)

Changes:
 - moduleExample1: 3.3.4 => 3.3.5
 - moduleExample2: 3.3.4 => 3.3.5

? Are you sure you want to publish the above changes? Yes
lerna info publish Publishing packages to npm...
lerna info published moduleExample1
lerna info published moduleExample2
Successfully published:
 - moduleExample1@3.3.5
 - moduleExample2@3.3.5
lerna success publish finished
```

## Possible Solution

Searching on Issues page, I found this one (https://github.com/lerna/lerna/issues/446): you added the information for run command, so maybe the solution for publish command is similar to this one.

## Context

We're having some problems publishing packages in my work, and we want to investigate deeper the error from npm. Normally, the publish command is excuted from bitbucket with CI: we cannot publish them manually, so we need more information to solve it as soon as possible.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.4.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.3.2 |
| `node --version` | v8.9.4 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.3 |

Thank you in advance for your help.

**Comment by evocateur** [comment]
This is one of the compromises lerna makes to facilitate concurrent publishing: the non-error logs are silenced to avoid confusing interleaved output. When _errors_ occur, they are duly logged by lerna before exiting non-zero.

We _do_ currently "swallow" [lifecycle script errors](https://github.com/lerna/lerna/blob/b4af3c9ebac8f7b4c22a0966c03b7e4fcfaed155/commands/publish/index.js#L434-L436) (logged, but not breaking the publish process) during `lerna publish`. Would a `--bail` option that forces those to re-throw the exception and halt the publish process help you?

**Comment by danielo515** [comment]
Hello @evocateur ,
I think in this case it will be enough to be able to pass the `--verbose`option to npm while publishing. While rethrowing errors may be useful to short-circuit automated processes, being able to see the verbose output of npm will be way more useful to debug them.
Is there any way to pass the `--verbose` flag to npm when publishing ?

Regards

**Comment by evocateur** [comment]
Yes, there is, of course. We could even pass our loglevel directly (it’s the same value), but it would be noisy as hell without _also_ making publish a sequential operation (that is, concurrency=1).

I’m of half a mind already to make publish sequential in order to make error handling and two-factor auth prompting work realistically.

**Comment by danielo515** [comment]
> but it would be noisy as hell without _also_ making publish a sequential operation (that is, concurrency=1).

We are desperate as hell, so seeing everything that is happening while debugging an issue that is driving us into madness sounds more like a bless than a problem. Specially knowing that you can deactivate it.

Is there any way to pass the `--verbose` option to npm publish at the current lerna version ? no matter how.

**Comment by evocateur** [comment]
No direct way via CLI flags, but you could specify the npm_config_loglevel env var. Still wouldn’t be much use at the moment, since the stdio from the `npm publish` is still swallowed (except on errors, which dump a log of all loglevels).

We can probably pass args after `--` to the publishes, but it’ll be undocumented behavior.

**Comment by bochen2014** [comment]
Have you tried loglevel=silly ?

**Comment by danielo515** [comment]
Hello @bochen2014,
Do you mean as environment variable or as lerna config?

**Comment by bochen2014** [comment]
`lerna publish --loglevel silly`
