### ISSUE TITLE
require('lerna'): requiring and running lerna  in a script, not cli ?

### ISSUE THREAD

**Issue by coderjonny** [lerna/lerna#1373]
Hi, 

I'd like to use lerna directly in a node script that I'm writing. 

Instead of using bash to call the lerna cli, can I use lerna directly in a file? 

Instead of this
```
const cp = require("child_process");

...

                cp.execFileSync(
                    "yarn",
                    [
                        "lerna",
                        "add",
                        `${module}@${myVersion}`,
                        "--scope",
                        "packages/*"
                    ],
                    {
                        stdio: "inherit"
                    }
                );

```

Can I expose lerna in a file something like this, to run a lerna command ?

```
const lerna = require('lerna');
```

thank you,

**Comment by evocateur** [comment]
Probably? Although it's terribly documented (if at all) right now.

The [default export](https://github.com/lerna/lerna/blob/master/commands/add/index.js#L17) of `@lerna/add`, for example, could theoretically be used like this:
```js
const lernaAdd = require('@lerna/add');

lernaAdd({ pkg: `${module}@${myVersion}` }).then(() => {
  console.log('done!');
});
```

I haven't tested it, though, so I might be mis-remembering.
