### ISSUE TITLE
discussion lerna sintax

### ISSUE THREAD

**Issue by lbottoni** [lerna/lerna#1378]
Hi all, 
after read all pages doc in lerna site i can not understand this line in my package.json

`lerna:generate:models": "lerna run generate:models --stream"`

**lerna** is the bin ok

Someone, can explain me the syntax aaaa:bbbb what is?

is there some tutorial where i can learn or investigate?

it's possibile have some link to understand?

**Comment by evocateur** [comment]
Those are the names of [npm lifecycle scripts](https://docs.npmjs.com/misc/scripts). An ecosystem convention has developed to "namespace" these scripts by using colons (":") to delimit namespace levels.

In your example, the script is named `lerna:generate:models`, and you would run it with the command `npm run lerna:generate:models`. The script calls `lerna run` itself, which finds `lerna` from the locally-installed `node_modules`.

`npx lerna run --help` will give you documentation for that command.
