### ISSUE TITLE
`lerna publish` script still bumps version of packages with `private: true`

### ISSUE THREAD

**Issue by amkoehler** [lerna/lerna#1379]
## Expected Behavior
When running `lerna publish`, any packages marked as `"private": true` should still have its dependencies updated any new package versions, but it should _not_ bump the `"version"` of the package. 

## Current Behavior
The docs state that when running `lerna publish`, "Lerna won't publish packages which are marked as private (`"private": true` in the package.json).". This is working as expected, but the script is still bumping the `"version"` field if there are changes detected. 

## Possible Solution
Packages marked as `"private": true` are not published to npm, so it seems like the `lerna publish` script should not be changing the package version even if `--cd-version` is specified. 

## Steps to Reproduce (for bugs)
1. Start with a repo containing one or more packages whose package.json contains `"private": true`
2. Make changes to any of the packages so that there's something to publish
3. Run `lerna publish --independent --exact --yes --cd-version "patch"`

The output I receive at this point indicates that the version for my private package is changing, even though it's not being published anywhere:

```shell
Changes:
 - privatepackage: v5.3.4 => 5.3.5 (private)
 - @org/package1: 4.0.4 => 4.0.5
 - @org/package2: 4.0.4 => 4.0.5
```

(note: our private package's `"version"` intentionally contains the `v` prefix)

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.9.0",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent",
  "command": {
    "publish": {
      "allowBranch": ["master", "develop", "feature/*"],
      "message": "publishing package(s) to npm [ci skip]"
    }
  }
}
```
</p></details>

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.5.1 |
| `yarn --version` | 1.5.1 |
| `node --version` | 8.9.3 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.3 |
| Ubuntu | 16.04 |

**Comment by evocateur** [comment]
> "Lerna won't publish packages which are marked as private"

That's still true. Lerna has _never_ made promises that _nothing_ would be modified in a `"private": true` package during `lerna publish`.

The version bumps are necessary to retain `lerna bootstrap` symlinks (when one isn't using the superior [relative `file:` specifiers](https://github.com/npm/npm/blob/latest/doc/spec/file-specifiers.md) pattern). That's not going to change, so I'd suggest avoiding a dependency on a specific format of the version number (intentional or not, it's [ignored](https://docs.npmjs.com/misc/semver#versions) in a package.json version field).

Consider, too, that you don't _have_ to manage this private package with lerna. Being private, it's already `devDependencies`-only, and thus it should be safe to use either relative `file:` specifiers, or just [hoist it to the root](https://github.com/lerna/lerna/blob/0b88ffbbcfe95543d71f6c72e7053087cdc7d19a/package.json#L27-L50) and use the `node_modules` resolution algorithm.

**Comment by amkoehler** [comment]
> The version bumps are necessary to retain lerna bootstrap symlinks

This makes sense for the dependency versions of that private package, but does the `"version"` key itself need to be bumped in that private package? By nature of this being marked `"private": true`, none of the other packages have the private package as a dependency.

**Comment by evocateur** [comment]
No, `"private": true` has one use: [preventing accidental publish](https://docs.npmjs.com/files/package.json#private). It has absolutely nothing to say about what local packages can have a dev dependency on it.

And really, if a private package in a monorepo has no local dependents or dependencies ...why bother putting it in the monorepo?

**Comment by amkoehler** [comment]
I might not be doing a good job explaining. This is roughly how the package.json looks for our private package:

```
{
  "name": "privatepackage",
  "version": "v5.3.4",
  "private": true,
  "dependencies": {
    "@org/pacakge1": "4.0.3",
    "@org/package2": "4.0.5",
    ...
  }
}
```

Where the `@org/**` packages are local dependencies in the monorepo. It makes total sense why the versions of the `@org/**` dependencies needs to be bumped when they have changes being published. I'm asking specifically about the `"version"` key. I'm not sure why it's getting bumped when, by nature of it being a private package, nothing is being published and no other packages in the monorepo rely on it. 

Appreciate your quick responses.

**Comment by evocateur** [comment]
`lerna publish` will always bump dependents of packages that change (#707 has the gory details, I'm tired of re-re-re-explaining them). So if `@org/package1` or `@org/package2` have changes, it will cause `privatepackage`'s version to be bumped (but not published). It's pretty innocent, really.

**Comment by amkoehler** [comment]
Sounds good. Shouldn't be too difficult for us to work around this. Thank for the clarification.
