### ISSUE TITLE
devDependencies are not installed when using npm@5

### ISSUE THREAD

**Issue by djskinner** [lerna/lerna#1380]
## Expected Behavior

`lerna run test` works in the minimal reproduction (see link below)

## Current Behavior

`lerna run test` fails with `eslint: command not found`

## Steps to Reproduce (for bugs)

1.  `mkdir lerna-test`
2. `cd lerna-test/`
3. `lerna init`
4. `lerna create package-a`
3.  `lerna add eslint --scope package-a --dev`
4.  `npm i`
6.  Modify packages/package-a/package.json:
```
  "scripts": {
    "test": "eslint"
  },
```
5.  `lerna run test`

Minimal reproduction: https://github.com/djskinner/lerna-test

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

## Context

Migrating from lerna 2 with yarn workspaces to lerna 3 with npm@5 and `file:` descriptors.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-beta.17 |
| `npm --version`  | 5.8.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | v8.11.1 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.6 |

**Comment by djskinner** [comment]
BTW `lerna bootstrap --hoist` does work in this example. However I'm seeing snippets of information in various issues about how `npm install` should be sufficient and that `lerna bootstrap` is obsolete when npm@5 is used

**Comment by evocateur** [comment]
`lerna bootstrap` _also_ works with `npm@5`, it's just that there are optimizations available with `lerna@3` that allow you to completely ignore `lerna bootstrap` (much like lerna itself now does).

Specifically:
1. _All_ `devDependencies` are moved to the root
   * (there's no reason you can't run `eslint` and `jest` from the root)
2. _All_ sibling dependencies are specified as relative [`file:` specifiers](https://github.com/npm/npm/blob/latest/doc/spec/file-specifiers.md)
3. Run `npm i packages/*` from the root once

Then you can replace `lerna bootstrap` with `npm install` (and `npm ci` in CI), and it all "Just Works".

**Comment by djskinner** [comment]
So when using this scheme do I *have* to put all devDependencies in the root?

**Comment by evocateur** [comment]
Yes, otherwise they'll never be installed by `npm`. You should be doing this anyway in a monorepo.

**Comment by djskinner** [comment]
Sounds good, I'll have a go at that today. I have a couple more questions if I may.

Is there a `lerna add` command for putting devDependencies in the root package.json only? `lerna add @types/node --dev` will add it to all package.json. Is the recommended approach simply `npm install @types/node`?

For `lerna/lerna` in https://github.com/lerna/lerna/blob/master/CONTRIBUTING.md it suggests using `npm i` rather than `npm i packages/*` or the equivalent for the lerna repo (which presumably would be a more complex command due to the multiple package directories). How is it that `npm i` works for `lerna/lerna`?

**Comment by djskinner** [comment]
Hmm, I think I'm going to have to go back to yarn workspaces as I just cannot get this to work for my requirements. For reasons I don't understand I simply cannot convince npm to add `node_modules/.bin` references to each package so that npm scripts work as expected yet yarn workspaces does this out of the box. 

> You should be doing this anyway in a monorepo.

I can see some sense in putting all devDependencies in the root is a viable option for some projects but this isn't going to work for me. Each package needs its own lint/test/build requirements and it would be overly complex if not impossible to have a single command at the root that does the right job for each package. Additionally, after thinking it thought I subscribe to the view described here: https://github.com/lerna/lerna/pull/1343#issuecomment-375577169

> We prefer to keep our package scripts designed in a way that's independent from the monorepo layout, so that any per-package script works on its own and can be invoked e.g. via cd packages/{name}; npm run build.

Is lerna not intended/intending to support this approach in the future?

**Comment by djskinner** [comment]
Going to close this as I managed to get things working very nicely with yarn workspaces. Hopefully I'll be able to achieve the same with npm in the future. Thanks for your help.
