### ISSUE TITLE
Use different package versions from the same monorepo without npm

### ISSUE THREAD

**Issue by valerybugakov** [lerna/lerna#1382]
## Expected Behavior

I'm trying to find a way to work with different package versions in monorepo without publishing them to npm. For example I have three packages: `a`, `b` and `core`, `a` depends on `core@1.0.0` and `b` depends on `core@1.0.1`. Would be nice if `lerna` could help with such setup.

## Current Behavior

If I specify versions without additional changes I receive an error: 
```
error Couldn't find package "core" on the "npm" registry. 
```
If I specify GitHub url using published tag `github:valerybugakov/monorepo#core@1.0.0` (it's mentioned [here](https://github.com/lerna/lerna#git-hosted-dependencies)) `lerna` puts the whole monorepo in `node_modules` after `lerna bootstrap`.

## Possible Solution

Not sure if it's already implemented. If not, we could specify package name from monorepo in GitHub url so then `lerna` could use this info to take out only this package from the monorepo and put it into `node_modules`?

## Your Environment

`lerna.json`
```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useGitVersion": true,
  "gitVersionPrefix": "v",
}
```

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-beta.17 |
| `npm --version`  | 5.7.1 |
| `yarn --version` | 1.6.0 |
| `node --version` | v8.9.4 |

| OS | Version |
| macOS Sierra | 10.13.2 |
| NAME | VERSION |

**Comment by valerybugakov** [comment]
@evocateur Thanks for a quick response.

 I'm trying to setup a monorepo for Web + React-Native application with shared code package. It will be a private repo on GitHub, that's why `core` is not published to `npm`. Ability to work with different versions of the core package is required here because two separate teams will work on web and native parts. If they develop with different pace managing shared code will be hard without version control. 

Do you think it's a bad case for monorepo and especially `lerna`?
I've tried `yarn workspaces` at first, but bumped into the same issue.

**Comment by evocateur** [comment]
Lerna vs Yarn workspaces is somewhat orthogonal, here. It sounds like you want two separate repositories, and maybe share some sort of pattern library via private npm packages. "Two separate teams" is a dead giveaway that a monorepo isn't appropriate for _all_ the code.

I've never heard of `react-native` playing nice with any other packages in the same repo (tons of edge cases, weird resolution semantics, etc), but that's my own bias speaking. It's simplest to separate the concerns, and if you _need_ to share packages, publish them to the registry with limited access (auth-required, etc).

**Comment by valerybugakov** [comment]
Definitely different teams neglect some benefits of code sharing through monorepo. 

React-Native works fine, there're some non standard changes that you need to make to get it up and running in repo with React project, but I have a working example already. The only issue is that we don't want to use private `npm` packages in case when one team moves slower and wants to stay on older version of the _shared_ code. Would be nice to have it in private GitHub repo and for `lerna` to maintain feature parity between GitHub and `npm` hosted packages. Is it something you would consider useful functionality?

**Comment by evocateur** [comment]
>  The only issue is that we don't want to use private npm packages in case when one team moves slower and wants to stay on older version of the shared code.

The beauty of packages is that you can specify exactly what you want; if one team doesn’t even want to take patches, they can use an exact version. If one team needs to make a breaking change, bump the major and the other team can upgrade at their convenience.

This even works when the shared code is inside the monorepo; when the dependency version diverges from the local package’s version, lerna will attempt to install it in the leaf package directly instead of symlinking the local sibling. To work, of course, it does require publishing the shared code to a registry.

> Would be nice to have it in private GitHub repo and for lerna to maintain feature parity between GitHub and npm hosted packages. Is it something you would consider useful functionality?

I only really envisioned lerna’s hosted git committish support to be limited to metadata (i.e., recognizing a local sibling based on an externally-extracted git dependency). Doing anything more means lerna starts to become a package manager, which is explicitly out of scope.
