### ISSUE TITLE
Ban use of --ignore and --scope with lerna publish

### ISSUE THREAD

**Issue by morewry** [lerna/lerna#1384]
## Expected Behavior

Currently, the `--scope` and `--ignore` flags affect most commands, including `publish`. What I would expect when using these is that whatever Lerna does in response to the command would only affect the packages that match `--scope` or do not match `--ignore`. And, at first glance, they appear to work in that useful way with `publish`.

If you run `publish` and have changes in 3 packages `a`, `b`, `c`, you'll be asked if you want to publish all 3 packages. If you run publish with `--scope a`, you'll only be asked if you want to publish package `a`. If you run publish with `--ignore c`, you'll only be asked if you want to publish packages `a` and `b`.

So this **looks like** it works initially. What I would expect to happen is that you could run `lerna publish` again and be able to publish the packages you skipped.

> **Update:** You can! If you also use --force-publish in the next `lerna publish`. In my case I started by trying to manually force publish of the lowest level dependency that we skipped. Possibly because its changes cascaded into the other skipped packages, this sufficed. I suspect a list e.g. `--force-publish=a,b` or all e.g. `--force-publish` would also be good choices depending on your exact situation.

## Current Behavior

But, unfortunately, it appears that the actions performed by Lerna still impact the packages that have been excluded from the `publish`. If you `lerna publish --scope a`, then run `lerna updated`, you'll see `No packages need updating`, I assume due to the explanation given in https://github.com/lerna/lerna/issues/1055.

Therefore, you can't publish the other packages normally again until they have _more_ changes.  (I have no idea if `--conventional-commits` versions correctly at that point; but given all this, it seems possible to me that it might not, although I certainly hope it does.)

> **Update:** Good news. After force publishing, it appeared to pick up versioning correctly. Packages were bumped correctly based on `feat`, `fix`, & `BREAKING CHANGES` of the various commit messages since the last normal/real publish--although why that works differently from the `lerna updated` change detection is a little confusing to me. 

## Possible Solution

- Ban the use of `--ignore` and `--scope` with the `lerna publish` command. Completely ignore their presence.
- Warn the developer about these unexpected and potentially very troublesome side effects when they're used together.

End of the day, don't let developers accidentally get themselves into this undesirable situation based on unintuitive and _explicitly misleading_ program behavior.

I'd certainly _like_ to be able to publish subsets of packages sometimes, because it can be very useful to be able to do this to prevent a developer from being blocked when circumstances dictate not everything in a branch is ready for publish at the same time. But that's not my priority here.

## Steps to Reproduce (for bugs)

1. Have changes in multiple packages
2. Run `publish` and restrict with `--scope` or `--ignore`
3. Observe the program output makes this seem like it's working fine
4. Try to `publish` the other packages
5. You can't, Lerna no longer detects them as changed

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.1.2",
  "version": "independent",
  "command": {
    "publish": {
      "conventionalCommits": true
    }
  },
  "packages": [
    "components/*",
    "packages/*",
    "primitives/*",
    "tools/*"
  ]
}
```
</p></details>

## Context

We have a monorepo that contains a design system, which is worked on by multiple developers. There is a great deal of interdependency between the packages, but it's possible in some packages to make changes that don't affect any other packages (that's partially why we're using `independent` versioning). Sometimes a developer wants to publish changes in a package, but also wants to avoid publishing changes another developer made elsewhere. 

We did this yesterday to publish a package in that situation and now I have a dozen changes that I intended to publish today that can't be done the usual way, but have to be handled ASAP. In my case it's complicated by the fact that more changes have landed, so I can't effectively backtrack on it, and that no one can else publish anything in their accustomed way until I deal with it (with the possible exception of the package we published yesterday).

This has negatively impacted several developers on our team and looks like it could end up wasting most of my day if I now have to do my own `--conventional-commits` analysis and hope that if I force publish the change detection behavior will begin working normally afterwards.

> **Update:** I was concerned I'd have to version and publish all the skipped packages individually and manually, but apparently if you get yourself in this situation and use `--force-publish` afterward, you can publish the other changes and Lerna will do its usual `independent` and `conventional-commit` behavior. Phew!

The fact that this is a known issue (https://github.com/lerna/lerna/issues/1055) and hasn't been fixed or even strongly called out in documentation is a big problem in my opinion. Perhaps I'm misunderstanding the previous issues I read, but I can't think of why this behavior would be desirable.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.6.0 |
| `node --version` | 8.9.1 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.6 |

**Comment by evocateur** [comment]
I'm definitely sympathetic. This would be a breaking change, so I'm not sure this would make it into the 2.x branch.

> After force publishing, it appeared to pick up versioning correctly. Packages were bumped correctly based on `feat`, `fix`, & `BREAKING CHANGES` of the various commit messages since the last normal/real publish--although why that works differently from the `lerna updated` change detection is a little confusing to me.

That's because only `lerna publish` actually runs the `conventional-changelog`-related stuff, `lerna updated` only uses git tags to detect changes, and never decides version bumps.

**Comment by morewry** [comment]
@evocateur I think that if you were to output a message when `--scope` or `--ignore` are used together with `publish`, saying something along these lines:

> Warning! Use of --scope and --ignore with publish isn't intentionally supported and should be avoided. You can proceed, but you will need to use --force-publish for the next publish of the packages that you skip this time. See (link to more details).

Where (link to more details) could be an entry on https://github.com/lerna/lerna/blob/master/doc/troubleshooting.md. 

That would be sufficient. Ideally if it's not supported, it wouldn't do anything, rather than kinda working, but in a way that's disconcerting. But worthwhile solutions don't have to be ideal.
