### ISSUE TITLE
`lerna clean` should delete lerna project's root `node_modules` folder

### ISSUE THREAD

**Issue by thecodejack** [lerna/lerna#1392]
When I execute `lerna clean` it deletes all packages node_modules folders. But with `workspaces` feature, most of packages dependencies are installed in project's root node_modules folder.

## Expected Behavior

`lerna clean` command should delete root `node_modules` folder. 

## Current Behavior

With `workspaces` feature, most of packages dependencies are installed in project's root node_modules folder. But when I run `lerna clean`, it doesn't delete all dependencies.

## Possible Solution

I can understand that local `lerna` might not allow to delete root node_modules folder. But if it's not the case, we should probably consider allowing same. If that's fine, I can put a PR for same.

**Comment by evocateur** [comment]
`lerna clean` really isn't worthwhile when you're using Yarn workspaces. Just `rm -rf node_modules` if that's what you want.

Also, nuking the root `node_modules` is removing `lerna` (which should _always_ be a local dev dependency), and that's not especially useful for a CLI to delete itself.
