### ISSUE TITLE
.DS_Store files published

### ISSUE THREAD

**Issue by tkrotoff** [lerna/lerna#1394]
When using `lerna publish (--skip-git)`, `.DS_Store` files are published and should not.
Example:
- source code: https://github.com/tkrotoff/react-form-with-constraints/tree/a9e7b1ba7653d623859fc45345058cdd2967af4a/packages/react-form-with-constraints
- published package: https://unpkg.com/react-form-with-constraints@0.8.0-beta.1/src/

npm publish [should ignore .DS_Store files by default](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) so I don't know who is the culprit here (+ I'm using [`"npmClient": "yarn"`](https://github.com/tkrotoff/react-form-with-constraints/blob/a9e7b1ba7653d623859fc45345058cdd2967af4a/lerna.json))

Also got an empty `package` directory: https://unpkg.com/react-form-with-constraints@0.8.0-beta.1/ that [I did not have before](https://unpkg.com/react-form-with-constraints-tools@0.7.0/) (and obviously I don't have this directory in my Git nor on my file system when running `lerna publish`).

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.10.1 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | v9.10.0 |

**Comment by evocateur** [comment]
I would say that is an egregious yarn bug, lerna has literally no control over what the package manager clients do during `npm publish`/`yarn publish`.

**Comment by tkrotoff** [comment]
@evocateur ok, thx
