### ISSUE TITLE
Support of a different config file other than `lerna.json`

### ISSUE THREAD

**Issue by huchenme** [lerna/lerna#1398]
## Expected Behavior
Ideally lerna should be able to support a different config file. Currently, I have setup lerna config to use `yarn` and `useWorkspaces` to true, but it breaks people who do not have yarn installed, I would want to have a config file for npm user as well, without setting npmClient to yarn and set useWorkspaces

## Possible Solution
Support a `--config` flag: `lerna --config lerna-config.json`

**Comment by huchenme** [comment]
I am happy to send a pull request regarding this :)

**Comment by evocateur** [comment]
If you're using Yarn workspaces, that's part of the requirements of contributing to your repo. `npm i -g yarn` isn't rocket-science.

We store the global version in `lerna.json` right now, so unfortunately we're tied to that for the time-being. Sorry.

**Comment by huchenme** [comment]
@evocateur There are some limitations on our corp environment while someone working using Macbook got no issue installing yarn and others working on Windows machines do not have access to install yarn the proper way. So we hope we can create a separate config file for those users, otherwise, we need to create scripts with 

```
"bootstrap:npm": "npm install --no-package-lock && lerna bootstrap --hoist --npm-client npm --no-use-workspaces -- --no-package-lock"
```

which is very ugly. 

Most projects (Jest, Webpack for example) support multiple ways of config and also support `--config` flag, I think it is a nice feature to have in lerna as well, I am happy to contribute to it and add this flag, any concern?

**Comment by evocateur** [comment]
Just ...use npm, then? I don’t understand why you persist with a package manager that can’t be installed by a non-trivial number of your fellow developers.

Like I said before, the global version is stored in lerna.json, so it’s not going to happen with the current infrastructure.
