### ISSUE TITLE
—no-sort

### ISSUE THREAD

**Issue by bochen2014** [lerna/lerna#1400]
I don’t quite understand how lerna manager concurrency. On one hand it says it has default concurrency to 4 but on the other hand it says everything happens in a topological order
I also notice that lerna bootstrap is slow, as it is sequential, but lerna publish is fast, as it appears to be multi- threaded.
I am talking about the default behaviour without any flags 

Can you please share some insights on this? Thanks!

**Comment by evocateur** [comment]
What does this issue have to do with `--no-sort`?

`lerna bootstrap` concurrency controls how many individual package directories are installed at one time. That's an expensive call (to `npm install`), no way to get around it. Topological order (the default) ensures no package tries to use something in a `prepare` lifecycle that isn't there (from a sibling package).

If your packages are small, go to town with `--concurrency`, the only thing it can hurt is your CPU's thermal paste.

JavaScript is single-threaded, there is no multi-threading.

**Comment by bochen2014** [comment]
thanks for your reply

1. `lerna bootstrap` defaults to topological order which constraint the concurrency level. Everything has to occur in a particular order in order to not break dependencies. Passing `--no-sort` , in my understanding, basically tells lerna to ignore that topological order and therefore go full concurrency, if things are broken, the developer should take responsibility, not lerna
2. `--concurrency` defaults to 4, so I don't have explicitly pass this flag. Right?
3. by 'multi-threading' I mean concurrency. I should have called it `multi-processed` as it's `npm` who does the heavy-lifting work

**Comment by evocateur** [comment]
the topological sort is batched (run `--loglevel=silly` and look for "batched"), so each level can be operated as concurrently as possible. if you've got a big long chain of transitive dependencies, this might mean you do indeed experience a sequential run. maybe don't have huge snake graphs?

`--concurrency` is a flag so users can tweak it (4 _isn't_ appropriate for _all_ uses, just _most_).

**Comment by bochen2014** [comment]
cool. thanks for the explanation!

**Comment by doug-wade** [comment]
Looks like we've answered this one; closing.  Feel free to reopen if I misunderstood.
