### ISSUE TITLE
canary publish in 3.x

### ISSUE THREAD

**Issue by bochen2014** [lerna/lerna#1402]
looks like 

https://github.com/lerna/lerna/blob/90df64633a858c9d5ff0c766021c58cd9ddac4ae/utils/collect-updates/collect-updates.js#L68

is newly introduced and I couldn't find a equivalent in `2.x`

does this mean there is a fundamental change in `canary `release in `3.x`? i.e.  in `2.x` , `canary` only bumps/publishes packages that last commits touched (`git diff --name-only lastCommit^..lastCommit` , but in `3.x`, it will bump every package and publish every package.  If that is true, I'm not sure if 
https://github.com/lerna/lerna/blob/90df64633a858c9d5ff0c766021c58cd9ddac4ae/utils/collect-updates/collect-updates.js#L30
is still relevant.

Also, what if last commit didn't touch the `packages/**` folder? shell we still bump? -- I didn't try this one but my guess would be yes, it defaults to a patch bump

**Comment by bochen2014** [comment]
got it

https://github.com/lerna/lerna/blob/5d73717230ab31bf5496a5b3e4c67370eda95d23/src/UpdatedPackagesCollector.js#L192

**Comment by evocateur** [comment]
Indeed, you're right. Here's the proof on the 2.x branch:
```patch
diff --git a/test/integration/__snapshots__/lerna-publish.test.js.snap b/test/integration/__snapshots__/lerna-publish.test.js.snap
index a7404de5..9afddefd 100644
--- a/test/integration/__snapshots__/lerna-publish.test.js.snap
+++ b/test/integration/__snapshots__/lerna-publish.test.js.snap
@@ -380,6 +380,17 @@ Changes:
 "
 `;
 
+exports[`stdout: updates canary 1`] = `
+"
+Changes:
+ - package-1: 1.0.0 => 1.1.0-alpha.hash
+ - package-2: 1.0.0 => 1.1.0-alpha.hash
+ - package-3: 1.0.0 => 1.1.0-alpha.hash
+ - package-4: 1.0.0 => 1.1.0-alpha.hash
+ - package-5: 1.0.0 => 1.1.0-alpha.hash
+"
+`;
+
 exports[`stdout: updates fixed versions 1`] = `
 "
 Changes:
diff --git a/test/integration/lerna-publish.test.js b/test/integration/lerna-publish.test.js
index 76609fde..0518313a 100644
--- a/test/integration/lerna-publish.test.js
+++ b/test/integration/lerna-publish.test.js
@@ -82,6 +82,18 @@ describe("lerna publish", () => {
     expect(stderr).toMatchSnapshot("stderr: canary default version");
   });
 
+  test.concurrent("updates canary after change", async () => {
+    const cwd = await initFixture("PublishCommand/snake-graph-2.x");
+    const args = ["publish", "--canary", "--skip-npm", "--yes"];
+
+    await execa("git", ["tag", "v1.0.0", "-m", "v1.0.0"], { cwd });
+    await commitChangeToPackage(cwd, "package-3", "feat(package-3): Add foo", { foo: true });
+
+    const stdout = await execa.stdout(LERNA_BIN, args, { cwd });
+    const hash = await lastCommitId(cwd);
+    expect(stdout.replace(new RegExp(hash, "g"), "hash")).toMatchSnapshot("stdout: updates canary");
+  });
+
   test.concurrent("uses meta suffix from canary flag", async () => {
     const cwd = await initFixture("PublishCommand/normal");
     const args = ["publish", "--canary=beta", "--skip-npm", "--yes"];
```
And here's master (3.x):
```patch
diff --git a/integration/__snapshots__/lerna-publish.test.js.snap b/integration/__snapshots__/lerna-publish.test.js.snap
index 2f7145f4..7893aa4f 100644
--- a/integration/__snapshots__/lerna-publish.test.js.snap
+++ b/integration/__snapshots__/lerna-publish.test.js.snap
@@ -373,6 +373,14 @@ Array [
 ]
 `;
 
+exports[`lerna publish updates differential canary: stdout 1`] = `
+
+Changes:
+ - package-3: 1.0.0 => 1.1.0-alpha.SHA
+ - package-5: 1.0.0 => 1.1.0-alpha.SHA (private)
+
+`;
+
 exports[`lerna publish updates fixed versions: commit 1`] = `
 v1.0.1
 
diff --git a/integration/lerna-publish.test.js b/integration/lerna-publish.test.js
index c30dcdd3..3986a106 100644
--- a/integration/lerna-publish.test.js
+++ b/integration/lerna-publish.test.js
@@ -97,6 +97,17 @@ describe("lerna publish", () => {
     expect(stdout).toMatchSnapshot("stdout");
   });
 
+  test("updates differential canary", async () => {
+    const { cwd } = await cloneFixture("normal");
+    const args = ["publish", "--canary", "--skip-npm", "--yes"];
+
+    await gitTag(cwd, "v1.0.0");
+    await commitChangeToPackage(cwd, "package-3", "feat(package-3): changed", { changed: true });
+
+    const { stdout } = await cliRunner(cwd)(...args);
+    expect(stdout).toMatchSnapshot("stdout");
+  });
+
   test("updates independent versions", async () => {
     const { cwd } = await cloneFixture("independent");
     const args = ["publish", "--skip-npm", "--cd-version=major", "--yes"];
```

So I wish we had better tests like these in the first place. The current `--canary` tests are kinda crap, only testing the "no tags ever, publish everything" case, which masked this issue rather well.

All that said, I think I still prefer the 3.x behaviour as it is now, _except_ I really have to fix #277 so the differential publish works as intended. The original spirit of `--canary` seems to match this experience better (why _else_ create the complicated `${sha}^..${sha}` commit comparator?), whereas 2.x seems to be a bug, an oversight due to fiendishly complicated code, or a weird undocumented historical artifact.

**Comment by bochen2014** [comment]
Thanks for the explanation, I am fine with the current behaviour.

Also, could you take a look at 
https://github.com/lerna/lerna/blob/90df64633a858c9d5ff0c766021c58cd9ddac4ae/utils/collect-updates/collect-updates.js#L69

I don’t quite understand what we are short circuiting. Or in another word, why can’t we always short circuit?

**Comment by evocateur** [comment]
If you're in a non-canary publish that didn't select _all_ of the located packages, it can't be short-circuited.

My brain is fried right now, so feel free to take out those lines and see if the tests pass. If they _do_ pass, then it's reasonable to assume that we can just skip the last bit?

**Comment by bochen2014** [comment]
In both case it returns [candidates], I can’t see what short circuit is for. Cool, will look into it once get in to office

**Comment by bochen2014** [comment]
PR https://github.com/lerna/lerna/pull/1406

**Comment by hbetts** [comment]
@bochen2014 what else needs to be discussed or completed for this issue?

**Comment by bochen2014** [comment]
PR merged. so close the issue
