### ISSUE TITLE
Meta: Slack link in README is broken?

### ISSUE THREAD

**Issue by austinmckinley** [lerna/lerna#1404]
Is the Slack channel still active? The link in the README brings me to https://slack.lernajs.io/, which shows a Heroku “No such app” page.

**Comment by doug-wade** [comment]
The slack instance is still up and running (I got a notification for this issue), but it seems our [slackin](https://github.com/rauchg/slackin) instance is down.  Maybe this issue belongs in https://github.com/lerna/website?

**Comment by austinmckinley** [comment]
@doug-wade Probably does, will make a new issue over there. Thanks!

**Comment by austinmckinley** [comment]
This is still a problem, and it's been quite a while...any updates? Is the slack still in use?

Link to website issue: https://github.com/lerna/website/issues/47

**Comment by evocateur** [comment]
I dunno who owns that pointer thingy. @hzoo?
