### ISSUE TITLE
Bug: Updated command and --since flag should consider root yarn.lock/package.json files

### ISSUE THREAD

**Issue by bdwain** [lerna/lerna#1412]
## Expected Behavior
If I run yarn upgrade (or update the root package.json) in a yarn workspaces project and then run `lerna updated`, it should mark all packages as updated because the root lockfile is shared across all packages and there is no way of knowing which packages are affected (short of parsing the lockfile, which is not worth it)

## Current Behavior
If i am using yarn workspaces and I run yarn upgrade (or update the root package.json), `lerna updated` says that no packages have changed, which is not true.

## Possible Solution
Treat changes to the root package.json and lockfile as affecting all packages. For added flexibility, the config file could take a list of files that affect all packages, but not sure that's necessary. 

## Steps to Reproduce (for bugs)
1. Create a monorepo with lerna and yarn workspaces
2. Update a dependency at the root and rerun yarn install
3. Run `lerna updated --since master`.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent"
}

```
</p></details>

## Context
If I update central dependencies across my monorepo (for example, the version of webpack I use to build everything), that should trigger all packages to get rebuilt, since their outputs would be different. 

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.6.0 |
| `node --version` | 9.11.1 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.4 |

**Comment by evocateur** [comment]
If `yarn upgrade` doesn't change the version ranges in the leaf package dependencies, then that's not lerna's problem? Unless it's a major, I'm sure yarn folks would disagree that the ranges _should_ be modified.

In the latter case, concerning build tool upgrades, that's something that can be worked around with `lerna publish --force-publish=*`. It happens rarely enough, and intentionally, that I don't see the benefit of baking it into lerna. I don't want to even attempt to judge what two different(!) lockfile formats are expressing, in terms of relevant changes, related to _n_ possible leaf packages.

**Comment by bdwain** [comment]
@evocateur Why is it not lerna's problem? If i have a monorepo that has lots of libraries and an app, and yarn upgrade changes my react version for 16.3.0 to 16.3.1, that change affects my app. If my app was not in a monorepo, the change from 16.3.0 to 16.3.1 would obviously trigger a new version of the app, so it seems like a monorepo should not be different. 

Obviously this would unintentionally bump the versions of libraries in the monorepo too, which would presumably have a peer dependency on react, but I'd rather release too often than not release when I have a change. 

Also, I can't use `lerna publish` because of #1286

**Comment by evocateur** [comment]
1. Because `lerna` !== `yarn`. `npm update` modifies dependency ranges when a package is upgraded, you'll have to ask the yarn maintainers why they chose a different behaviour.
1. Because your leaf package.json didn't change, and thus at _any_ time your consumers could be getting different versions of React (assuming the dependency was specified as `"react": "^16.3.0"`). From lerna's perspective, that's not a change to the package, it's just an in-band upgrade of an existing dependency. Those aren't generally considered candidates for a release...

..._Unless_ there are other changes in the package that utilize _new_ features in 16.3.1, and then `yarn upgrade` _is not_ sufficient, and you should be modifying the dependency range in the affected `package.json`s. That's how npm packages have worked for years, and it's among the patterns that lerna is enabling, not _replacing_.

**Comment by bdwain** [comment]
lerna has a useWorkspaces option and advertises itself as explicitly supporting yarn workspaces. it should take into account its behavior and not just npm's behavior then.

**Comment by evocateur** [comment]
`useWorkspaces` literally hands off to `yarn` during `lerna bootstrap`, there's no other special logic implied by that option.

**Comment by evocateur** [comment]
(other than where to get the package location globs, too)

**Comment by bdwain** [comment]
for 2, just because it's not a candidate for release doesn't mean it's not a change. If someone does not want to release due a to a yarn upgrade, they don't have to run publish. But if you do want to run yarn upgrade and publish all affected packages (maybe react 16.3.0 was buggy and 16.3.1 fixes it and that's all you changed), it seems odd that lerna would consider everything unchanged.

I get that the logic doesn't fully integrate everything with yarn, but that's not clear by looking at lerna.json, which says client: yarn and useWorkspaces: true. If lerna wants to fully support yarn, it should behave the same when doing a similar operation in both npm and yarn. If yarn doesn't change each nested package.json when upgrading dependencies (which I feel is correct, since package.json is for specifying a range, not an exact version), then in order to say it supports yarn, lerna needs to support that behavior also.

**Comment by evocateur** [comment]
> maybe react 16.3.0 was buggy and 16.3.1 fixes it

That means you need to change the range specified in the leaf package.json, thus eliciting a git diff under a package location, which lerna will then version and publish during the next release. There's really no way around this requirement, it's _exactly_ the same for any npm package, monorepo or not.

In other words, it doesn't matter how many times you publish a package if the affected dependency range isn't modified somehow. `yarn upgrade`'s behaviour is fine for the most part (if you're using the default `^` range specifiers), as long as none of your code depends on features/bugfixes in later versions of the dependency. When consumed, npm and yarn both will evaluate it to whatever satisfying version already exists in the tree, OR install the latest satisfying version at the time of execution.

**Comment by bdwain** [comment]
Hm that's fair. I guess I'm not thinking of this so much from a publishing standpoint as from a knowing what could be affected standpoint. What I want to do is make sure that whenever someone changes the lockfile, they have to run the pre-merge checks for all packages, because any given package could break if a new dependency is bad, and without parsing the lockfile, we dont know which packages are affected when it changes. Otherwise, someone could run yarn upgrade and break master because a dependency broke something. Is there a way I could do that? 

I suppose I could do something hacky like in my pre-merge step, see if the lockfile has changed since master, and if so, ignore lerna updated and instead just build all packages. But that seems hacky and not ideal.

**Comment by evocateur** [comment]
You'd need to check if the current commit contains changes to a package-lock.json && build all packages || build --since.

```
git diff --exit-code --name-only HEAD^ -- **/package-lock.json \
  && echo lockfile-changed=false \
  || echo lockfile-changed=true
```

Works on my local clone, but I haven't tested it in a shallow clone (à la CI)

**Comment by bdwain** [comment]
got it. thanks for the help.
