### ISSUE TITLE
run always exits with status code 0 if debug log cannot be written

### ISSUE THREAD

**Issue by onyxraven** [lerna/lerna#1413]
In the case that the filesystem is not writable, lerna will exit 0 even if the commands in `run` (eg `test`) fail

## Expected Behavior
If the called method returns a nonzero exit code, lerna should also return a nonzero exit code.  In the case there is trouble writing to a debug log, a warning should be printed but not affect the bubbling up of status codes, or an error should be thrown by lerna itself and produce a nonzero exit code.

## Current Behavior
If one of the packages fails (eg `npm test` fails), but the filesystem is not writable, lerna is printing 

```
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 23): Error: EACCES: permission denied, open '/commons/lerna-debug.log.1960086875'
```

and then showing a success status in the summary of that package.

## Possible Solution

* it looks like this is an unexpected promise rejection, so properly rescuing that promise should provide a more intentional behavior

## Steps to Reproduce (for bugs)
1. ensure one of the commands will fail (bogus npm test)
1. setup lerna to run in a docker container with an Read Only volume
1. run `lerna run test` inside the container
1. observe the output

> I'm happy to setup an example repo if requested, I wanted to write this issue before I forgot my place.

## Context
This makes CI difficult if trying to run via a container. This bit us with failing tests after merges that were failing in the container but still 'passing' in CI.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11 |
| `npm --version`  | 3.10.10 (and node 8.9's default) |
| `yarn --version` | 1.3.2 and 1.5.1 |
| `node --version` | 6.11 and 8.9 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Guest: Ubuntu | 16.10 |
| Host: Travis CI | trusty sudo |

**Comment by evocateur** [comment]
You should be running tests from the root, it's half the reason to use lerna in the first place (instead of repeating it in every leaf package).

That being said, it's quite likely we're dropping it on the floor. Would you mind trying in lerna 3 (`lerna@next`)? I refactored a lot of the internal promise handling, so even if it's not doing the most graceful logging, it _should_ be always catching the promise rejection.
