### ISSUE TITLE
changelog has no commit msg

### ISSUE THREAD

**Issue by soluteli** [lerna/lerna#1414]
In my project with **_lerna V^2.10.2_** [learn-lerna_fixed](https://github.com/soluteli/learn-lerna_fixed/commits/master), my commit msg is in angular format.    
After running`lerna publish --conventional-commits`, I had get CHANGELOG files in project Root and every package root, but there is no git commit log like `feat: add something` show in CHANGELOG.   
so, how could get this done?    
 
related links:
- [commits](https://github.com/soluteli/learn-lerna_fixed/commits/master)
- [changelog module1](https://github.com/soluteli/learn-lerna_fixed/blob/master/packages/neo-lerna_01/CHANGELOG.md)
- [changelog module2](https://github.com/soluteli/learn-lerna_fixed/blob/master/packages/neo-lerna_02/CHANGELOG.md)
- [changelog project](https://github.com/soluteli/learn-lerna_fixed/blob/master/CHANGELOG.md)

Thanks~

**Comment by evocateur** [comment]
I don't think underscores are valid characters in package names? The commit history is very erratic, I can't tell when `--conventional-commits` was enabled in lerna.json, for example. The root changelog messages also have a bunch of "undefined" where the name should be, so I'm not sure this is a lerna issue.

You may have better luck opening an issue in https://github.com/conventional-changelog/conventional-changelog, which is the utility that lerna uses to generate the changelogs.
