### ISSUE TITLE
lerna bootstrap hiding the new npm 6 security warnings

### ISSUE THREAD

**Issue by sethwenzel** [lerna/lerna#1418]
When bootstrapping with lerna, we noticed that with the new npm 6 we don't see any security warnings you now get with npm 6.

## Expected Behavior
A list of security warnings per bootstrapped package

## Current Behavior
silent output, no npm warnings on bootstrapped packages

## Possible Solution

npm output for each bootstrapped package that was a warning?

## Context

We'd love to gain visibility into the new npm security audit features when using lerna.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 6.0.0 |
| `yarn --version` | N/A |
| `node --version` | v8.11.1 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.4 |

**Comment by evocateur** [comment]
I suppose it's possible, although it has the potential to create a blizzard of noisy, hard-to-read output.

I'd recommend just upgrading to lerna 3, run `npx lerna link convert` (which uses relative `file:` specifiers), and kick `lerna bootstrap` to the curb (all you need is `npm install` in the root). This is what the lerna codebase (in `master`) does today.

**Comment by garthk** [comment]
Led here by npm/npm#20566; ran into problems with @evocateur's suggestion above and `3.0.0-beta.20`; will look for relevant issues.

**Comment by anandsuresh** [comment]
Any word on this issue?

**Comment by anandsuresh** [comment]
@evocateur Cool. Thanks.

**Comment by Graham42** [comment]
It seems this solution only works for node 11. I need to stick with LTS releases so am using node 10 and node 12 will not be LTS until October 2019. 

The audit output from npm install is only 3 lines. And only 1 of those is really important: the findings. I don't think that 1 line per package is overly noisy. Would really like lerna to include the audit output on `bootstrap`

**Comment by evocateur** [comment]
> It seems this solution only works for node 11.

Nope. I run with relative `file:` specifiers every single day on Node v8.x LTS (carbon).
