### ISSUE TITLE
[Feature] Allow git remote to be changed for publish

### ISSUE THREAD

**Issue by jamiebuilds** [lerna/lerna#142]
It'd be nice to allow either:

``` js
"publishConfig": {
  "gitRemote": "origin"
}
```

or

``` sh
$ lerna publish --git-remote origin
```

(The CLI flag should override the `publishConfig`)

The two places that need to be changed to support it are:
- https://github.com/lerna/lerna/blob/master/src/GitUtilities.js#L41-L45
- https://github.com/lerna/lerna/blob/master/src/commands/PublishCommand.js#L114

The [CLI help](https://github.com/lerna/lerna/blob/master/bin/lerna.js#L20-L25) will need to be updated.

And `publishConfig` is available on [`this.repository.publishConfig`](https://github.com/lerna/lerna/blob/master/src/Repository.js#L33-L35) inside the [Command](https://github.com/lerna/lerna/blob/master/src/Command.js#L14)

@NogsMPLS you said you'd like to take this. Let me know if you need any help.

**Comment by tdanecker** [comment]
We also need this feature, so I tried to implement it. Could you have a look at it?

**Comment by cezaraugusto** [comment]
wasn't this closed by #508?

**Comment by gre** [comment]
it would be great to be able to define the github repository in the lerna.json configuration and not only the gitRemote. when you work with the git flow, each developer will usually have a fork on his/her own repository. like `org/project` forked to `gre/project` . Some developer might not have named the upstream repository "upstream" so we can't do something really generic, however if we define the main repository, like `github:org/project` , lerna could check that the remote is the correct remote. (I guess maybe it might work if putting `git@github.com:org/project` as remote?)

**Comment by evocateur** [comment]
@gre Forks should _never_ run `lerna publish`. Lerna also has no opinion on what repository you clone from. `--git-remote` simply controls which remote the current branch is pushed to, overriding the default "origin".
