### ISSUE TITLE
Globs syntax and negating a scope ?

### ISSUE THREAD

**Issue by appsolutegeek** [lerna/lerna#1420]
Hi,

I am trying to execute a command using exec and passing in a scope, for example to attach all my pacakges for my ui, they end with .ui

This works perfectly

`lerna exec --scope @myorg/*.ui -- ls`

Now I would like to attack all projects there are NOT of @myorg/*.ui (hence, other projects)

I tried the following but it doesn't work (notice the exclamation mark next to the asterisk)

`lerna exec --scope @myorg/!*.ui -- ls`

Can anyone help, does it support this syntax ? If it does support the above - maybe I am just doing it wrong ?

What library does lerna use to support globs, I suppose checking the syntax would be handy

Any ideas, thanks in advance

**Comment by mlavina** [comment]
I think `--ignore` flag under the hood just does a negate, so you could just 

`lerna exec --ignore @myorg/*.ui -- ls`

**Comment by appsolutegeek** [comment]
Thank you , that works perfectly.

**Comment by doug-wade** [comment]
Woo!  Thanks for helping out @mlavina!  I haven't been keeping up as much with the issues as I'd prefer, so that really helps a lot.
