### ISSUE TITLE
lerna publish not use lifecycle `prepare`

### ISSUE THREAD

**Issue by MrChe** [lerna/lerna#1423]
Command `lerna publish` not use lifecycle `prepare` in each packages

## Expected Behavior
After use command `lerna publish` started lifecycle `prepare/prepublish` 

## Current Behavior
After use command `lerna publish` not started lifecycle `prepare/prepublish` 

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 6.0.0 |
| `yarn --version` | 1.6.0 |
| `node --version` | 9.11.1 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.4 |

**Comment by doug-wade** [comment]
We [have code](https://github.com/lerna/lerna/blob/3574466560f600828a0f288cec8d137a21404f15/commands/publish/index.js#L626) that runs `prepare` as part of publish, as well as a [test that checks it](https://github.com/lerna/lerna/tree/d40ffb776e3bda7c097931d28399f8c146368926/commands/bootstrap/__tests__/__fixtures__/ignored-scripts/packages/package-prepare) so I'm surprised by this.  Do you have a minimal repro repo that I can look at to investigate?

**Comment by doug-wade** [comment]
Hey @MrChe I'm going to close this for now.  If you manage to pull together a repro, feel free to reopen.

**Comment by MrChe** [comment]
@doug-wade i dont see logs on command `prepare` http://take.ms/vak3M

**Comment by evocateur** [comment]
We don't show the (non-error) logs because publish is run concurrently, and a mishmash of interpolated output helps no one.
