### ISSUE TITLE
Lerna seems changing the package-lock.json unnecessarily

### ISSUE THREAD

**Issue by dnepro** [lerna/lerna#1429]
## Expected Behavior
The `package-lock.json` shouldn't be updated if no dependency was changed, e.g. doing the following "Steps to Reproduce" shouldn't change the `package-lock.json`.

## Current Behavior
At the moment Lerna removes the "name" and "version" top level fields, as well as the "dev: true"-dependency level field.

<details><summary>git log for package-lock.json after executing the "Steps to Reproduce"</summary><p>

```json
 {
-  "name": "@mycompany/mypackage",
-  "version": "0.0.0",
-  "lockfileVersion": 1,
   "requires": true,
+  "lockfileVersion": 1,
   "dependencies": {
     "@babel/cli": {
       "version": "7.0.0-beta.44",
       "resolved": "https://registry.npmjs.org/@babel/cli/-/cli-7.0.0-beta.44.tgz",
       "integrity": "sha512-f+Yd3uZpZse9K3s1PcfyqlKoku3u/neAUFSDXFXkEuiD7m8GwP6NiDwa77qvFvH6jNzT4gteFr0SqjYMjg5Hzg==",
-      "dev": true,
       "requires": {
         "chokidar": "1.7.0",
         "commander": "2.13.0",
         "convert-source-map": "1.5.1",
         "fs-readdir-recursive": "1.1.0",
         "glob": "7.1.2",
         "lodash": "4.17.5",
         "output-file-sync": "2.0.1",
         "slash": "1.0.0",
         "source-map": "0.5.7"
       },
       "dependencies": {
         "anymatch": {
           "version": "1.3.2",
           "resolved": "https://registry.npmjs.org/anymatch/-/anymatch-1.3.2.tgz",
           "integrity": "sha512-0XNayC8lTHQ2OI8aljNCN3sSx6hsr/1+rlcDAotXJR7C1oZZHCNsfpbKwMjRA3Uqb5tF1Rae2oloTr4xpq+WjA==",
-          "dev": true,
           "optional": true,
           "requires": {
             "micromatch": "2.3.11",
             "normalize-path": "2.1.1"
           }
         },
         "chokidar": {
           "version": "1.7.0",
           "resolved": "https://registry.npmjs.org/chokidar/-/chokidar-1.7.0.tgz",
           "integrity": "sha1-eY5ol3gVHIB2tLNg5e3SjNortGg=",
-          "dev": true,
           "optional": true,
           "requires": {
             "anymatch": "1.3.2",
             "async-each": "1.0.1",
             "fsevents": "1.1.3",
             "glob-parent": "2.0.0",
             "inherits": "2.0.3",
             "is-binary-path": "1.0.1",
             "is-glob": "2.0.1",
             "path-is-absolute": "1.0.1",
             "readdirp": "2.1.0"
           }
         },
         "output-file-sync": {
           "version": "2.0.1",
           "resolved": "https://registry.npmjs.org/output-file-sync/-/output-file-sync-2.0.1.tgz",
           "integrity": "sha512-mDho4qm7WgIXIGf4eYU1RHN2UU5tPfVYVSRwDJw0uTmj35DQUt/eNp19N7v6T3SrR0ESTEf2up2CGO73qI35zQ==",
-          "dev": true,
           "requires": {
             "graceful-fs": "4.1.11",
             "is-plain-obj": "1.1.0",
             "mkdirp": "0.5.1"
           }
         }
       }
     }, ..........
```
</p></details>

## Possible Solution
Just don't change/remove unknown properties.

## Steps to Reproduce (for bugs)
1. `npm install`
2. commiting (not necessary but easier to track, the changes made by the next step)
3. `lerna bootstrap`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.9.0",
  "command": {
    "publish": {
      "allowBranch": "master",
      "message": "chore(release): publish %s",
      "conventionalCommits": true
    }
  },
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

## Context
I just don't want the file to be changed back and forth and have extra commits for this reason.

## Your Environment
Nothing speciall

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 5.10.0 |
| `node --version` | 9.11.1 |

| OS | Version |
| ---: | :--- |
| macOS HighSierra | 10.13.2 |

Thanks in advance 💯 and thank you very much for all the possibilities Lerna enables! ❤️

**Comment by doug-wade** [comment]
Iirc, what's happening is that we're [writing temporary package.json files](https://github.com/lerna/lerna/blob/master/utils/npm-install/npm-install.js#L48) ([same as in 2.x](https://github.com/lerna/lerna/blob/2.x/src/NpmUtilities.js#L39)) with the computed set of dependencies that need to be installed, and we don't distinguish devDependencies from normal dependencies, and don't include the name and version fields in the generated package.json.  We'd take a PR to fix this issue, but I'm not sure what you can do in the meantime (especially since its unlikely we backport this to 2.x).

One option is to hoist all of your devDependencies to the monorepo root, which sidesteps the issue of the dependencies vs devDependencies, but doesn't address the excess noise from the extra commits. Another might be to use the lerna-generated package-lock.json, but since npm respects the package-lock.jsons of installed libraries, this might lead to the installation of some dev dependencies in your customers dependency closures (I'm not sure of this, it's just a conjecture).

**Comment by evocateur** [comment]
v3 _does_ retain the distinction between `dependencies` and `devDependencies` (transform is [here](https://github.com/lerna/lerna/blob/ce5c4842e5c927beaa13779c6429a8d7c5b5a933/utils/npm-install/npm-install.js#L94)). It's not likely to get back-ported, just upgrade to lerna 3.

**Comment by mathieurousseau** [comment]
I am using lerna 3.x and I am having this issue.
I have it hoisted and my package-lock gets updated each time.

**Comment by ThisIsMissEm** [comment]
@mathieurousseau which version of lerna 3.x are you using — can you give the output of `lerna --version` please?

**Comment by mathieurousseau** [comment]
@ThisIsMissEm  3.4.0

**Comment by ThisIsMissEm** [comment]
@mathieurousseau can you share your package.json at the root?

**Comment by mathieurousseau** [comment]
I did a clean clone, then ran npm install, lerna bootstrap, then I commited and pushed the package-lock.json 
My packages.json is not fixing version (keeping ^ or ~) then each time a npm i is done, it installed newer version than the one in the package-lock.json

My more worrying problem is that the --ignore-changes has stopped working and I could not run lerna version without pushing the package-lock.json

**Comment by evocateur** [comment]
If you're using a lockfile, it needs to be versioned?

**Comment by mathieurousseau** [comment]
Yes it needs to be versioned.

I am using npm ci instead of npm i in my jenkins so now it works as npm ci (continuous integration) installs exactly the versions from the lock file.

**Comment by RyanAfrish7** [comment]
Any updates on this? I'm on `lerna --version` `3.13.1` and still face the same issue. Should we create a backup of package.lock.json as it does for package.json?

**Comment by piperchester** [comment]
For what it's worth, I also experience this intermittently using **`npm ci`**.

**Comment by sdirix** [comment]
Could you reopen this issue? We experience the same problem both with a `2.x` version as well as the latest `3.16.4`. In our case some packages in the lock are (apparently) nondeterministically set or unset to `optional` and or `bundled` with each run of `npm ci && lerna bootstrap --hoist --npm-ci-mode`.

**Comment by rambabusaravanan** [comment]
package-lock.json file is being modified even when running in ci mode

```sh
$ npm ci
$ git diff # # # no changes 👍 
```
```sh
$ npm run bootstrap

> root@ bootstrap /home/jenkins/workspace/somepath/my-project
> lerna bootstrap --ci

lerna notice cli v3.16.4
lerna info ci enabled # # # in ci mode 👍 
lerna info Bootstrapping 30 packages
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished bootstrapping root
lerna info Symlinking packages and binaries
lerna success Bootstrapped 30 packages

$ git diff 
	modified:   package-lock.json
```

@evocateur Is this issue needs to be reopened ..?

**Comment by goldhand** [comment]
There's all sorts of related issues in an open state or closed for being "marked as stale". As of today, this seems to be an issue without any planned solution :(
