### ISSUE TITLE
Allow running command for a specific package

### ISSUE THREAD

**Issue by joscha** [lerna/lerna#143]
Currently our setup uses `lerna run ...` for anything related to all packages (like running the tests for example). However in development, we'd like to be able to run a command for a single specified package.
Reason for this is, that our main repository contains the dependencies to some build tools (for example Karma) that we'd like to re-use.
For example one of our packages looks like this:
```json
...
scripts: {
    "test": "karma start ../../karma.conf.js --single-run",
    "test/watch": "../../node_modules/.bin/karma start ../../karma.conf.js",
    "prepublish": "webpack"
}
...
```

whereas `lerna run test` and `lerna run prepublish` work fine for all packages, the `test/watch` script would only make sense for a single package. However using the binary short form is not possible, because the package itself doesn't actually depend on karma, only our base package does, which means we need to link to the binary ourselves (`../../node_modules/.bin/...`).
Ideally we would be able to run something like

```console
lerna run-single my-component test/watch
```

Is this something you would accept a pull request for?

**Comment by thejameskyle** [comment]
Hmm, I'd almost rather extending the existing `lerna run` command to accept some way of filtering packages.

```sh
$ lerna run --matches-packages-idk-what-to-name-this-flag component-*
```

**Comment by joscha** [comment]
@thejameskyle I thought about that, the downside is that currently anything after the first argument to `lerna` is treated as the target script name - adding another flag in between would mean that we potentially some script out there might break, but I guess as 2.0 is still in the flow that would be fine.

maybe `lerna run --restrict-to component-* my-script`? I'd be happy to provide a PR for this feature.

**Comment by thejameskyle** [comment]
> the downside is that currently anything after the first argument to lerna is treated as the target script name

I'm pretty sure `meow` takes care of that for us. But idk

And yeah, I'd be happy to support this in some form. Lets see if you face any challenges when making a PR and work it out there.

**Comment by joscha** [comment]
@thejameskyle I opened #145, please let me know if there are any changes you'd like me to make in order to integrate it.
