### ISSUE TITLE
force lerna to install package in subdirectory, instead of hoisting

### ISSUE THREAD

**Issue by rbalicki2** [lerna/lerna#1436]
Thank you for this wonderful tool!

Is there a way to force lerna to install, say `webpack`, in a package's node_modules folder? I'm running into an issue due to the fact that one package requires webpack 4, and another breaks if webpack 4 is installed.

In particular, I have two deployable projects: `marketing-site` and `admin-panel`. These use other packages in common. `marketing-site` is a next.js project, and `admin-panel` is a plain ol webpack project.

`admin-panel`'s package.json requires webpack 4.8.0; marketing-site's package.json requires next.js, which depends on webpack 3.10.0.

If I require `"webpack": "^4.8.0"` in the `admin-panel`'s package.json, it installs webpack 4.8.0 at the top-level node_modules. 3.10.0 is installed under `node_modules/next/node_modules/webpack`. This causes something like: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/753 during the build process.

If I exclude webpack from `admin-panel`'s package.json, version 3.10.0 is installed at the top level. (Obviously, this would break admin-panel's build process).

Is there a way to force the admin-panel webpack to be installed in `admin-panel/node_modules`?

As far as I remember, I have never used the `--hoist` flag

**Comment by evocateur** [comment]
Please add more information, such as the lerna.json and other such information requested in the issue template.

**Comment by danielo515** [comment]
isn't the option `nohoist: [list of packages]` not enough ?

**Comment by hejiaji** [comment]
@danielo515 if use `nohoist: [list of packages]`, i would have to put everything here, is there a way just disable hoist??

**Comment by evocateur** [comment]
`--hoist` is always an explicit flag, it is never "on" by default. Just don't pass it (or configure it from lerna.json, remove any `"hoist": true` fields).

To select individual packages to avoid hoisting, use [`--nohoist`](https://github.com/lerna/lerna/tree/master/commands/bootstrap#--nohoist-glob).
