### ISSUE TITLE
Specify "secondary" packages

### ISSUE THREAD

**Issue by pshrmn** [lerna/lerna#1439]
I would like a way to specify a group of packages with a lower level of priority than regular packages. For my specific use case, these would be example packages that I would like to keep in sync with dev, but don't necessarily have to be installed immediately and would never be published.

## Desired Behavior
```js
// lerna.json
{
  "packages": ["packages/*"],
  "secondary": ["examples/**"]
}
```
lerna commands would normally only be called on the regular packages, but a flag could be used to specify that the secondary packages should be included as well. This would also make it easy to only run the "real" packages with continuous integration.

```bash
# only bootstrap regular packages
lerna bootstrap

# also bootstrap secondary packages
lerna bootstrap --all
```

Ideally this would also work with `lerna publish` so that the secondary package's have their dependency versions updated without lerna trying to update their versions. I'm not sure how technically feasible this is (and maybe this behavior isn't actually desirable?), but it was the main inspiration for me wanting this feature.

## Current Behavior

Currently, the `--ignore` flag combined with `"private": true` in each package's `package.json` would be the best way to accomplish this. In order to properly handle this, each package should have a name that can be group globbed.

```
examples/
  one/
    package.json # { "name": "example-one", "private": true }
  two/
    package.json # { "name": "example-two", "private": true }
  three/
    package.json # { "name": "example-three", "private": true }
```

```bash
# only regular packages
lerna bootstrap --ignore example-*

# include secondary
lerna bootstrap
```

## Context

I'm not sure how often this would be useful for other projects or if it is just me. In addition to the repo I have this feature in mind for (https://github.com/pshrmn/curi), it would make things slightly simpler in the React Router repo (we use `--ignore` to skip installing the docs website for CI builds).

The structure I included above was the first thing that came to mind, but I'm not married to that if you like this idea but have something else in mind. I mostly just like the idea of "ignore by default" that secondary packages provide.

**Comment by evocateur** [comment]
I don't really see this happening. Anything that you rarely install and never publish seems like it should be using local relative [`file:` specifiers](https://github.com/npm/npm/blob/latest/doc/spec/file-specifiers.md) instead.
