### ISSUE TITLE
lerna adds empty `dependencies` object to top level package.json

### ISSUE THREAD

**Issue by cpojer** [lerna/lerna#144]
Jest now doesn't have direct dependencies in its top level folder any longer. The init script adds `dependencies: {}` to package.json. I don't think it should do that :)

**Comment by hzoo** [comment]
It should be adding to devDependencies now https://github.com/lerna/lerna/pull/131

**Comment by thejameskyle** [comment]
Oh no #131 didn't update https://github.com/lerna/lerna/blob/master/src/commands/InitCommand.js#L38

**Comment by hzoo** [comment]
😞  Oh.. https://github.com/lerna/lerna/pull/147

**Comment by thejameskyle** [comment]
😜

**Comment by thejameskyle** [comment]
Fixed in #147
