### ISSUE TITLE
Automatically hoisting with NPM for bootstrap/add etc?

### ISSUE THREAD

**Issue by appsolutegeek** [lerna/lerna#1440]
Hi,

After moving away from yarn as i had a lot of issues with workspaces, I have decided to use npm.

The hoisting seems to work a lot better and allows me to no-hoist certain files which i need to do.

Is it possible to automatically hoist when ever i do a bootstrap, add etc ?

If there some kind of config setting in lerna.json or something?

Its just that sometimes i forget to add the --hoist :-)

If i was to be able to make it default and still be able to pass --no-hoist when i need to, then this would be great.

Thanks

**Comment by evocateur** [comment]
Add it to your lerna.json:

```json
{
  "command": {
    "bootstrap": {
      "hoist": true
    }
  },
  "packages": ["packages/*"],
  "version": "1.2.3"
}
```
Any flags passed on the CLI will overrule the keys configured in the `command.*` namespace.
