### ISSUE TITLE
Add option to skip package from publishing

### ISSUE THREAD

**Issue by slavafomin** [lerna/lerna#1446]
Hello!

Thank you for this great tool!

However, it would be very helpful if we had a "Skip this package" menu option during publishing when Lerna asks for "Select a new version".

Lerna is not always detecting the changes correctly and trying to update the packages, which actually hasn't changed. Such option will help to skip such unnecessary updates.

Also, we don't always want to release all packages, sometimes, some packages should be kept unreleased.

Thanks!

**Comment by evocateur** [comment]
#707 ad nauseam
