### ISSUE TITLE
Add option to log to stdout instead of stderr

### ISSUE THREAD

**Issue by yiochen** [lerna/lerna#1447]
Lerna uses [npmlog](https://github.com/npm/npmlog) for logging, which by default outputs to stderr stream. This makes it very confusing for our CI process, because it will prefix `[ERROR]` for all messages in stderr. I couldn't find an option in lerna to change stream.

## Expected Behavior

Add an option to change the stream for logging. 
## Current Behavior

Currently all logs goes to stderr stream.
## Possible Solution

Add an option, for example `--log-stream="stdout"`

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 6.1.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | v9.11.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
Your CI process is wrong. `stderr` is where logging belongs.
