### ISSUE TITLE
shell `lerna add ` support `--hoist` flag?

### ISSUE THREAD

**Issue by bochen2014** [lerna/lerna#1448]
I think it would be useful if it does

**Comment by evocateur** [comment]
To bootstrap? Just add `hoist: true` to your lerna.json:
```json
{
  "command": {
    "bootstrap": {
      "hoist": true
    }
  },
  "packages": ["packages/*"],
  "version": "1.2.3"
}
```
If you're using `--hoist` with bootstrap, that's what you _always_ want, and thus should be configuring it in lerna.json.

**Comment by bochen2014** [comment]
Thanks for your reply. 

No I am talking about lerna add. during develop stage I have to keep using lerna add,but dependencies were hoisted. At the moment lerna add doesn’t support hoist which is not convenient

**Comment by evocateur** [comment]
`lerna add` [calls](https://github.com/lerna/lerna/blob/1f885f1288f58da6e59261ac6c859f2507f12e3b/commands/add/index.js#L77-L83) `lerna bootstrap` internally after making its changes, which merges in lerna.json config.

**Comment by bochen2014** [comment]
i see.. thanks @evocateur !
