### ISSUE TITLE
Ability to opt of of using `npm ci`

### ISSUE THREAD

**Issue by quarterto** [lerna/lerna#1449]
## Expected Behavior
Being able to tell `lerna bootstrap` to explicitly use `npm install` instead of `npm ci`

## Current Behavior
Since 3.0.0-beta.15, `lerna bootstrap` uses `npm ci` if it's a version of `npm` that supports it and you pass the `--ci` flag. However, on CI environments the `--ci` flag is [always true](https://github.com/lerna/lerna/blob/5b015996e4824527f3aff684611c112562edddf6/core/cli/index.js#L58), and there's no way to turn it off without messing around with environment variables, which would have other side effects.

## Context
Since we're not committing package-lock.json files (our current tooling doesn't play nicely with them at present) `npm ci` errors, and we can't currently use `lerna` on CI with `npm@5.7`.

**Comment by evocateur** [comment]
`lerna bootstrap --no-ci` doesn't work?

**Comment by quarterto** [comment]
I tried it and it didn't seem to work 🤷‍♀️ https://github.com/Financial-Times/x-dash/commit/8a18f7efdd94c959c8d2bea1c1c61877090be74a

**Comment by evocateur** [comment]
Hrm, okay, that wasn’t intended. A CLI flag should always override file- or env-based configuration.

**Comment by quarterto** [comment]
did a bit of digging into yargs' parsing and it looks like `.config()` [takes precedence over command line args](https://github.com/yargs/yargs-parser/blob/f6e65994a07cddbd3526052877aee4b307925f9d/index.js#L280-L291)

**Comment by evocateur** [comment]
Good catch!

**Comment by track0x1** [comment]
What is the verdict on this? Can we `lerna bootstrap --no-ci`? Or better, can this functionality be changed to be explicit? There was nothing indicating that lerna would use `npm ci` when my build ran on AWS Codebuild. ☹️

**Comment by evocateur** [comment]
I plan on releasing the next version of lerna 3 sometime this week.

**Comment by raymondfeng** [comment]
@evocateur We cannot set the `ci` value in `lerna.json` even when `--ci` flag is not present on the CLI. Is it by design?

**Comment by evocateur** [comment]
Not intentional, no, but the result of a feature I personally haven't used in over a year. I'm not sure why you _wouldn't_ want a faster install during a CI build.

You should still be able to pass `--no-ci` to disable it, which is relatively easy to encode into your CI scripts. Switching to relative `file:` specifiers that serialize the whole tree at the root would be better long-term than relying on `lerna bootstrap`.

**Comment by raymondfeng** [comment]
@evocateur We don't check in package-lock.json files and `npm ci` fails for our build. 

`--no-ci` works for us. I was trying to do so in `lerna.json` as we configure other commands there. But the `ci` property is not honored.

**Comment by evocateur** [comment]
Yeah, that's an unfortunate side-effect from how the options are configured. I should probably move [this block](https://github.com/lerna/lerna/blob/ad649bf965a6452d5f4aad8026f4ed62a548cada/core/cli/index.js#L38-L48) into the base command constructor, where the options are merged with the config file...

**Comment by evocateur** [comment]
@raymondfeng Next release should fix this for you properly.

**Comment by raymondfeng** [comment]
@evocateur Great! We appreciate your prompt response.
