### ISSUE TITLE
I am confused about lerna import

### ISSUE THREAD

**Issue by motoko2501** [lerna/lerna#1450]
I have an existing app, call it App1.
I'd like it to share common components with App2 that I'm about to start writing.
So I'd like to have three folders in `packages`: `App1`, `App2`, `common`.

Also, I would like to use the existing App1 remote git repository for the new monorepo setup and maintain all App1 commit history. So I thought `lerna import` is the perfect choice.

However, when I do `lerna init`, I immediately have unstaged changes from Lerna itself. I cannot do an `import` before I commit them. 

So I set my remote repo to be that of App1 with `git remote add origin`, I commit unstaged changes from `lerna init`, I import my App1 from an external directory and it lands nicely in the packages folder and I commit that too. Now when I try to push all these changes to my remote repo, I get 
`
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@gitlab.com:XYZ.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.`

I'm not great with git, but it would seem that the initial commit required by Lerna has undercut my git history from App1. (Indeed, in `git log` I see that my `Lerna init` commit is the first one, before all my old App1 commits.)

So how do I go about importing my existing code and making it work wit current repo and history?

**Comment by evocateur** [comment]
You don't need to import an application that doesn't exist yet. Just add the lerna stuff (in the existing app1 repo) and then move the existing app into its new home.

```
mkdir -p packages/app1
git mv src test packages/app1/
cp package.json packages/app1/

npx lerna init
# modify root package.json appropriately
git commit -am "chore: convert to lerna monorepo"
```

**Comment by bjornicus** [comment]
when I tried this and then did `lerna list` it did not show my existing package, which made me think it did not work.  I then `lerna import` another repo and *that* one showed up, but not the one I moved manually to packages.  After some further poking around I found that I had `private:true` set in my package.json for that one and that causes it not to show in the `lerna list` output.
