### ISSUE TITLE
no name, version in package.json → broken Node Security Project

### ISSUE THREAD

**Issue by garthk** [lerna/lerna#1454]
Due to `lerna bootstrap` running `npm install` with a thinned `package.json`, the `package-lock.json` produced by `npm` lacks the `name` field required by `nsp`, the Node Security Project. This is similar to #1415's lack of an updated `version`.

## Expected Behavior

```
lerna bootstrap
cd package/xxx
node -e 'assert.equal(require("./package.json").name, require("./package-lock.json").name)'
echo $?
nsp check
```
→
```
0
(+) No known vulnerabilities found
```
… indicating success.

## Current Behavior

```
AssertionError [ERR_ASSERTION]: 'xxx' == undefined
    at [eval]:1:8
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
1
(+) Debug output: {"statusCode":400,"error":"Bad Request","message":"Error: child \"packagelock\" fails because [child \"name\" fails because [\"name\" is required]]","details":[{"message":"\"name\" is required","path":"packagelock.name","type":"any.required","context":{"key":"name"}}]}
(+) Error: Got an invalid response from Node Security, please email the above debug output to support@nodesecurity.io
```
… because there's no `name` or `version` in `package-lock.json`.

## Possible Solution

Write `name` and `version` to the temporary `package.json`

## Steps to Reproduce (for bugs)

This isn't a buggy implementation. Rather, it's correct implementation of an insufficiently good definition of "done". Easily fixed, but I'll skip the repro if you don't mind.
 
<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0",
  "hoist": false,
  "packages": [
    "pkg/*"
  ],
  "version": "independent",
  "commands": {
    "publish": {
      "ignore": [
        "*.md",
        "test/**"
      ]
    }
  }
}
```
</p></details>

## Context

> How has this issue affected you?

I can't check to see if any of my dependencies have security vulnerabilities.

> What are you trying to accomplish?

I'm trying to use `nsp` to check to see if any of my dependencies have security vulnerabilities.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 5.6.0 |
| `node --version` | v8.11.2 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.4 |

**Comment by evocateur** [comment]
I think you’ll find lerna 3 doesn’t mangle as much as v2, if you insist on using the hacky bootstrap method.

**Comment by garthk** [comment]
I tried 3.0.0-beta.20, @evocateur, but ran into #1419 forced hoisting with incorrect paths. If someone is willing to fix the hoisting or give me some hints on where in the code to fix it myself, I'll give it another shot with my full repo and isolating the incorrect paths part if it's still happening in beta 21.

**Comment by evocateur** [comment]
I don't understand your reticence to "hoist" your devDependencies to the root. It's how lerna should have behaved in the first place, imo.

**Comment by tivac** [comment]
Lerna automatically rewrites local path dependencies to monorepo packages during publishing. It's how I've published the last 9-10 `modular-css` releases.

**Comment by garthk** [comment]
Plain nightmare, I'm afraid. Try installing `gdal` whenever your version of Node hits a major upgrade before their build infrastructure catches up. One time, we ended up forking it just so we could store our own copy of the heavy artifact.

I'll double-check our workflow to see if we're up for `lerna publish` again. We stopped using it because of the obnoxious version bumping (#718 / #707).
