### ISSUE TITLE
Use local eslintrc on each package when testing

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#1455]
## Expected Behavior
I want lerna test to take in account the local eslint rules when running tests inside a package

## Current Behavior
Currently the only eslintrc file taken in account is the one defined at the root of the repository

## Context

I know one of the main goals of having a monorepo is managing all the dependencies, linting rules and build tools on one place and unified. However, there are some packages that require special linting rules. Currently, when running tests manually, going to the package folder and running npm test the eslint file of the package is used. However, when I run lerna test, the same eslint file (the one at the root of the repo) is used for all the packages, ignoring the local ones and producing linting errors.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 5.6.0 |
| `node --version` | 10.2.1 |

| OS | Version |
| --- | --- |
| macOS |  |

Thanks in advance

**Comment by evocateur** [comment]
You should still run `eslint` from the root, but [nesting config files](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) is definitely possible. I use the pattern myself in several private monorepos, and even the odd [public one](https://github.com/zillow/javascript) (hit `t` and search for `eslintrc.yaml`).

Nothing lerna does changes how eslint resolves its config files, so I'm going to close this.
