### ISSUE TITLE
MaxListenersExceededWarning when lerna run --stream with 3+ packages

### ISSUE THREAD

**Issue by amaurymartiny** [lerna/lerna#1459]
## Expected Behavior

I have 3 packages in my monorepo, each of them have a npm `build` script.

I run `lerna run build --stream` from the root folder, I expect to see the live output.

## Current Behavior

I see the live output but also:
```
(node:48783) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 4 error listeners added. Use emitter.setMaxListeners() to increase limit
```

## Steps to Reproduce (for bugs)

https://github.com/amaurymartiny/cra-lerna-electron/tree/am-try-no-npm

`yarn lint` works. `yarn lint --stream` outputs the warning.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "npmClient": "yarn",
  "packages": [
    "packages/*"
  ],
  "useWorkspaces": false,
  "version": "0.1.0"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 6.1.0 |
| `yarn --version` | 1.7.0 |
| `node --version` | 10.1.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.4 |

**Comment by goldenshun** [comment]
I see the same warning when I try to run `bootstrap`. `bootstrap` does not seem to support the `--concurrency` flag so I'm not sure how I can correct this.

**Comment by Enase** [comment]
I confirm the same issue with `npm` when I try to run `lerna bootstrap`, so u can add npm label as well.

**Comment by evocateur** [comment]
Regardless of npm client being used, this isn't a Lerna problem. It handles the number of listeners that _it_ adds [right here](https://github.com/lerna/lerna/blob/1bb152105f793e33eee37067ee7834c4e6adff1e/core/child-process/index.js#L49-L53). Lerna can't control what other programs do.

**Comment by hugebdu** [comment]
@evocateur might that be there's missing `.unpipe` call upon child's process exit?
