### ISSUE TITLE
Process for upgrading a shared dependency across a specified scope

### ISSUE THREAD

**Issue by p-jaya** [lerna/lerna#1461]
I'm wondering what the process for updating a shared external dependency across multiple packages should be.  This could be my lack of understanding and/or a feature request.

## Expected Behavior

Let's say you have a shared external dependency `shared-module` which gets updated.  You now want to update that dependency across two modules that use it:

```
$ lerna add shared-module scope=module-1,module-2 # add the latest version of shared-module to module-1 and module-2
$ lerna add shared-module@x.y.z scope=module-1,module-2 # add shared-module@x.y.z to module-1 and module-2
```

## Current Behavior

Lerna detects that `shared-module` is already a dependency of `module-1` (even though it's an older version) and does nothing:

```
$ lerna add shared-module@3.10.3 --scope=module-1
lerna info version 2.11.0
lerna info scope my-module
lerna WARN No packages found in scope where shared-module can be added. 
```

## Possible Solution

Perhaps some method akin to `npm install` and/or `npm upgrade` that can be applied across selected lerna scopes.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "packages": [
    "packages/apps/*",
    "packages/lib/*",
    "packages/services/*",
    "packages/tools/*"
  ],
  "version": "4.0.0"
}
```

## Context

Trying to manage a shared, external dependency (that we can't pull into the monorepo itself) and maintain consistent dependencies across our entire codebase

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 6.1.0 |
| `node --version` | 10.3.0 |

**Comment by ChrisBAshton** [comment]
To confirm - is there a plan for `lerna upgrade` to be implemented?

**Comment by evocateur** [comment]
It's something I'd like to do, and would certainly collaborate actively if someone wants to make a pull request.

**Comment by antony** [comment]
This still exists, stale bot is infuriating.

You can't update the version of a dependency via `lerna add` and there is no `lerna upgrade`. None of this is made clear in the documentation. Not sure what to do? :man_shrugging:

**Comment by toolness** [comment]
Hi @antony!  I'm new to lerna and figuring this all out myself... I'm not sure what to do either, but I noticed there is a slick-looking third-party tool called [Lerna Update Wizard](https://github.com/Anifacted/lerna-update-wizard#readme) that might help with this for now.  I haven't tried it yet, though.

**Comment by evocateur** [comment]
or just use `pnpm` or `yarn`, they do fine with managing workspace upgrades
