### ISSUE TITLE
Lerna doesn't respect selective resolutions from yarn

### ISSUE THREAD

**Issue by fyodorvi** [lerna/lerna#1464]
## Expected Behavior
During bootstrap when lerna creates a copy of package.json it needs to copy yarn's `resolutions` section to it.

## Current Behavior
The copy of package.json is missing `resolutions` section, which breaks support of yarn's selective resolutions: https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

## Possible Solution
Copy over `resolutions` section to a generated package.json during bootstrap.

## Steps to Reproduce (for bugs)
1. Create a package with following `package.json`
```
{
  "name": "tmp",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@types/sinon": "4.3.3",
    "@types/sinon-chai": "2.7.32"
  },
  "resolutions": {
    "@types/sinon": "4.3.3"
  }
}
```
2. Run `lerna bootstrap`
3. Observe that actual `@types/sinon` version is not `4.3.3`

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11 |
| `yarn --version` | 1.7 |
| `node --version` | 10.2.1 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.4 |

**Comment by evocateur** [comment]
I don't know why you would use yarn with lerna and _not_ use yarn workspaces (which completely replaces `lerna bootstrap`).

In any case, `lerna@3` no longer brutally mangles the _entire_ manifest during bootstrap, it only slices out the local siblings.

**Comment by evocateur** [comment]
That sounds complicated. Lerna 3 does what you want.
