### ISSUE TITLE
Move all packages from alpha to beta?

### ISSUE THREAD

**Issue by KyleAMathews** [lerna/lerna#1466]
I have a Lerna monorepo with a number of packages in alpha. Does Lerna have a way to trigger a release that changes all the alpha versions to beta? Or should I do that manually?

**Comment by evocateur** [comment]
If you're using `lerna@3`, all you need to do is change your `--preid` (most convenient to do in a lerna.json "durable" configuration).

For example, I recently changed `preid` [beta -> rc](https://github.com/zillow/javascript/commit/519a4244820539b46eaee4b47f9e3013b5a0df54) and then [published](https://github.com/zillow/javascript/commit/ab4ca826dfb7e8cb2065db88bde3bf6247de6daa) everything, even "unchanged" packages.

If you're on `lerna@2`, `lerna publish --force-publish` and then choose the appropriate prerelease id should do the trick.
