### ISSUE TITLE
Lerna add - add's to all scopes by default ?

### ISSUE THREAD

**Issue by appsolutegeek** [lerna/lerna#1467]
Loving _lerna_, I wondered if I am missing something. When I do a _lerna add_ and I don't specify a scope, then it adds it to every scope. This may be what I intended but maybe not :-)

I was wondering if its possible to avoid _lerna add_ from adding to all scopes ?

Maybe introduce a @scopeAll ?

Otherwise maybe either giving an error because no scope was provided or implicitly installing in the current scope (where the _lerna add_ command was run)

Also, would it be possible to follow the same parameters as NPM, for example, to force a save to development dependencies - currently you pass --dev

Would be great to pass in either -D or --save-dev

This would make it easier to use.

Thanks for the great work

Ian

**Comment by evocateur** [comment]
```
$ lerna -v
3.0.0-beta.21
```
```
$ lerna add -h
lerna add <pkg> [globs..]

Add a dependency to matched packages

Positionals:
  pkg    Package name to add as a dependency                                                    [string] [required]
  globs  Optional package directory globs to match                                            [array] [default: []]

Command Options:
  --dev, -D  Save to devDependencies
```

I don't think we need another alias, `-D` is expressive enough.
