### ISSUE TITLE
running lerna@3.0.0-beta.21 gives  Incompatible local version of lerna detected! error

### ISSUE THREAD

**Issue by dptoot** [lerna/lerna#1469]
## Expected Behavior
Lerna should work as expected.

## Current Behavior
I have lerna@3.0.0-beta.21 installed locally and globally.  Any usage via the CLI will result in 

```
lerna info version 2.9.0
lerna ERR! EMISMATCH Incompatible local version of lerna detected!
lerna ERR! EMISMATCH The running version of lerna is 2.9.0, but the version in lerna.json is ^3.0.0-beta.21.
lerna ERR! EMISMATCH You can either run 'lerna init' again or install 'lerna@^^3.0.0-beta.21'.
```

Running lerna init as suggested reverts lerna back to 2.9.  I believe I experience the same running lerna 2.11.

## Possible Solution
I wish I knew and I would PR it!  :)

## Steps to Reproduce (for bugs)

1. Install lerna@3.0.0-beta.21
2. try any command ```lerna add```

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "^3.0.0-beta.21",
  "packages": [
    "packages/*"
  ],
  "changelog": {
    "enterpriseUrl": "https://ghe.coxautoinc.com",
    "repo": "Autotrader/axl",
    "labels": {
      "tag: new feature": ":rocket: New Feature",
      "tag: breaking change": ":boom: Breaking Change",
      "tag: bug fix": ":bug: Bug Fix",
      "tag: enhancement": ":nail_care: Enhancement",
      "tag: documentation": ":memo: Documentation",
      "tag: internal": ":house: Internal",
      "enhancement": ":rocket: Enhancement",
      "bug": ":bug: Bug Fix",
      "chore": ":bug Housekeeping"
    },
    "cacheDir": ".changelog"
  },
  "command": {
    "bootstrap": {
      "npmClientArgs": [
        "--no-package-lock"
      ]
    },
    "clean": {
      "stream": "true"
    },
    "run": {
      "stream": "true"
    }
  },
  "version": "independent"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

Running windows.
| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | 5.3.0|
| `yarn --version` | VERSION |
| `node --version` | 8.6.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
Windows 10

**Comment by evocateur** [comment]
You shouldn't generally need to have `lerna` installed globally, thanks to `npx`. That logging seems to indicate `lerna@2` is actually installed in the local `node_modules`.

```
npm -g rm lerna
npm i -D lerna@next
npx lerna ls
```

**Comment by dptoot** [comment]
You are absolutely right!  Uninstalling lerna globally and using the local to init seemed to work the trick.  thanks!
