### ISSUE TITLE
"lerna add" still adds the version using a cart(^) even though I added exact into lerna.json

### ISSUE THREAD

**Issue by appsolutegeek** [lerna/lerna#1470]
Hi,

Using "lerna add ...." still adds the file into my package.json using a carat for external packages..

I found a pull request that appears to allow the use of exact in lerna.json here https://github.com/lerna/lerna/pull/661

and it was merged, maybe I am not using it correctly

Here is an example
`
lerna add lodash --scope=@mytest/testapp`

and then checking the package.json i find
`
    "lodash": "^4.17.10",`

This is my lerna, i presume I am doing it right ?

```
{
  "lerna": "2.11.0",
  "exact": true,
  "packages": [
    "applications/*",
    "packages/**/*",
    "services/*"
  ],
  "version": "independent",
  "npmClient": "npm",
  "hoist": true,
  "command": {
    "publish": {
      "ignore": [
        "*.md"
      ],
      "allowBranch": ["develop", "release/*"],
      "message": "chore(release): publish"
    },
    "bootstrap": {
      "nohoist": [
      ]
    }
  }
}

```

**Comment by appsolutegeek** [comment]
This is very strange, I also just passed in the --exact while doing the add, and I still get ^ (carat) for my versions. I am using the latest installable lerna.

So I removed the lerna.json flag i set and then tried the following command and it gave me a carat version again.

`lerna add lodash --exact -scope=@mytest/testapp`

**Comment by evocateur** [comment]
Yeah, `--exact` isn't supported right now. `lerna add -h` would describe it if it was enabled.

You can, however, pass an explicit version specifier and it will save the dependency as if `--save-exact` was passed to `npm install`:

```
lerna add lodash@4.17.10
```

**Comment by evocateur** [comment]
Err, didn't mean to close. Respecting `--exact` would be a nice PR.

**Comment by appsolutegeek** [comment]
Ah, ok, I didn't realize it wasn't implemented yet.

Yep agree, it would be nice get it fixed.

In the meantime i wrote a script
