### ISSUE TITLE
Question: could i custom conventional-changelog option？

### ISSUE THREAD

**Issue by QingLeiLi** [lerna/lerna#1471]
Hi, I'm using stash as a git server now, its URL structure is different from github, so I have to pass the option to it like this

`conventionalChangelog({
  issues: function(issueId) { return bugs.url + '/' + issueId; }
});
`

But I did not find a way to do this, how should I do?

`
lerna -v
2.11.0
`

**Comment by evocateur** [comment]
You would need to create your own conventional-changelog preset, and then upgrade to `lerna@3`, which allows presets for the changelog generator as well as the version bumper (`lerna@2` only supports passing presets for the latter).

Writing a conventional-changelog preset is out of scope for lerna.

**Comment by QingLeiLi** [comment]
Thanks for reply.
I read the source code of `lerna @ 3` roughly. It should meet my needs. I will try it.

Is there a approximate  date for the release of `lerna @ 3`?

**Comment by evocateur** [comment]
Out of beta? It probably should be already, since I’ve been using it “in production” for months now.

**Comment by QingLeiLi** [comment]
OK! 
Thanks for the great work.
