### ISSUE TITLE
How to use lerna with semantic-release

### ISSUE THREAD

**Issue by kopax** [lerna/lerna#1472]
We are using semantic-release for release step of all our packages.

Semantic-release does the publishing and release within a CI job.

We like lerna, because we can save time when working on large project that have complexe dependencies.

Will you support semantic-release and CI in the futur?

**Issue on semantic-release/semantic-release repo:** https://github.com/semantic-release/semantic-release/issues/819

**Comment by evocateur** [comment]
At this point, integration has stalled due to conflicting schedules (mostly my own, since I'm the only active maintainer of lerna and I have a very busy day-job). I'd like to improve the auto-publish in CI story, but I don't have a timetable right now.
