### ISSUE TITLE
Update fields in package.json before and after publish

### ISSUE THREAD

**Issue by diestrin** [lerna/lerna#1475]
## Expected Behavior
Provide a way to update fields in the package.json before publish. A roll back of the changes might be necessary as well.

## Current Behavior
There's currently a before/after publish script, but updating the package.json in those lifecycles makes no difference because the changes are ignored (probably because lerna already loaded the file in memory).

## Possible Solution
One solution might be for lerna to read again the file after the scrips are executed.

## Context
Working on a typescript project, you'll want other local modules to extract the typings from your source code, but on publish, after generating the compiled version, you might want the typings field to point to the generated `.d.ts` file.

**Comment by evocateur** [comment]
Lerna 3 currently runs these lifecycles (in order, but not necessarily contiguous) for every package being published:

1. `preversion`: before package version has been bumped
2. `version`: after a package version has been bumped, but before the package.json has been staged for commit.
3. `postversion`: _after_ the commit has been made
4. `prepare`/`prepublishOnly`: before package tarball is created
   - this is probably the phase you're looking for, as lerna does indeed serialize the in-memory package.json between this phase and the previous (adding the `gitHead` property that `npm publish` normally does automatically)
5. `postpublish`: after `npm publish` succeeds

Lerna automatically checks out any unstaged modifications made to package.json files after all publishes are finished.
