### ISSUE TITLE
force-publish doesn't work as expected

### ISSUE THREAD

**Issue by bertho-zero** [lerna/lerna#1480]
https://github.com/lerna/lerna/tree/master#--force-publish-packages

> This will skip the `lerna updated` check for changed packages and forces a package that didn't have a `git diff` change to be updated.

When I use `--force-publish` Lerna adds all` lerna updated` packages to the package I chose.

**Comment by bertho-zero** [comment]
`lerna publish --force-publish=templates,react-utils` should publish only `templates` and `react-utils`, no ?

**Comment by morewry** [comment]
`--force-publish` doesn't exclude anything, it forces the inclusion; so you get the effect you described, it publishes everything with changes _plus_ the packages you've forced. 

If you want to only publish those two, you _can_ (on Lerna 2.x.x) combine it with `--ignore`, but see https://github.com/lerna/lerna/issues/1384. `--ignore` apparently was not intentionally designed to be supported with `publish`. 

I've found it works okay for now, as long as you're aware that, once you've ignored updated packages during publish, you need to `--force-publish` them when you're ready to release them.

**Comment by bertho-zero** [comment]
In the doc it is written `This will skip the lerna updated check`, I understand that if lerna skip the updated packages he should not want to publish them.

So there is no way to publish a package without ignoring a bunch (more than 30 packages)?
When I choose to force the publication of packages I would like to publish only those ones, if I want to add the updated then I add the updated.

**Comment by evocateur** [comment]
Yeah, that particular part of the docs is wrong. It should have been something like @morewry described above.

> it publishes everything with changes _plus_ the packages you've forced

There's nothing stopping you from going into the subdirectory of the desired packages and doing your own `npm publish`. `--force-publish` was not designed to do what you intend.

Maybe publish more frequently if a large number of published packages in one changeset offends you?

**Comment by bertho-zero** [comment]
Ok I understand, maybe we could add an option that does that? I'm not the only one to ask this and it is true that often when I publish a patch version it is not necessary to publish a patch version in all that depends on it.

**Comment by kaore** [comment]
Hi,

Our project has several dozens of loosely coupled packages. It would be a pity to have to update the version of each and every package of the repo everytime one of them changes slightly - this tends to happen several times everyday. On 2.x.x, we just specify a scope and this fits our need well, but I understand that if we update this would no longer be possible.

What would the right approach be in our case?
