### ISSUE TITLE
Ignore `v` in `--repo-version`

### ISSUE THREAD

**Issue by HsuTing** [lerna/lerna#1483]
I want to publish with `circleci` and `git tag`. Normally I use `git tag` like `v1.0.0`, and publish in `circleci` like `yarn lerna publish --repo-version ${CIRCLE_TAG}`. As a result, `yarn lerna publish` will use `v1.0.0` to publish packages, but `--new-version` of `yarn publish` can not be a version with `v`. Maybe `v` should be ignored with `--repo-version`?

## Expected Behavior

```sh
yarn publish --repo-version v1.0.0
// publish packages with version `1.0.0`.
```

## Current Behavior

```sh
yarn publish --repo-version v1.0.0
// publish packages with version `v1.0.0`.
```

## Possible Solution

Add `repoVersion.replace(/^v/, '')` in [here](https://github.com/lerna/lerna/blob/master/commands/publish/index.js#L305).

## Steps to Reproduce (for bugs)

```sh
yarn lerna publish --repo-version v1.0.0
```

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  version: 1.0.0,
  commands: { 
    publish: { 
      ignore: [ 
        *.md,
        __tests__/**
      ]
    }
  },
  lerna: 2.11.0,
  npmClient: yarn,
  npmClientArgs: [ 
    --no-lockfile
  ],
  packages: [ 
    packages/*
  ]
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

I hope this can publish in `circleci` with my `git tag`, and I want to still have `v` in my `git tag`. Like `standard-version`, this will ignore `v` when I use `--release-as`. Maybe `lerna` can ignore, too.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 6.1.0 |
| `yarn --version` | 1.7.0 |
| `node --version` | 10.2.1 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.5 |

**Comment by evocateur** [comment]
This has been fixed in master, but is unlikely to make it into the 2.x release line as the codebase has changed dramatically.

**Comment by HsuTing** [comment]
@evocateur OK! Thank you 😁
