### ISSUE TITLE
loglevel silent does not remove lerna output

### ISSUE THREAD

**Issue by bdwain** [lerna/lerna#1485]
## Expected Behavior
I'm running a command  with lerna that fails in a subpackage. I was hoping to supress lerna's extra error output because the output from the packages themselves is enough. I ran

`lerna run build-branch --parallel --loglevel=silent`

## Current Behavior
After the commands fail, I see error output like this

```
    at Promise.all.then.arr (/Users/bwain/dev/project/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  code: 1,
  killed: false,
  stdout: 'A TON OF CONENT'
 .....
```

## Steps to Reproduce (for bugs)
I have a monorepo with 2 packages, each with a build-branch yarn task. At the root, I have a yarn task that says 
`lerna run build-branch --parallel --loglevel=silent`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent"
}
```
</p></details>

## Context
The output is distracting and I would like to suppress it.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.7.0 |
| `node --version` | 9.11.1 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.4 |

**Comment by evocateur** [comment]
Does this reproduce with lerna 3?

**Comment by jirutka** [comment]
lerna 3.0.0-beta.21 -- `lerna run lint --stream`, even with `--loglevel silent`, produces annoyingly duplicated output when some script fail.

**Comment by evocateur** [comment]
Linting should be run from the root.

**Comment by jirutka** [comment]
> Linting should be run from the root.

What do you mean? That `lint` script should be in the root package.json and run for all packages at once?

**Comment by evocateur** [comment]
Exactly.

**Comment by jirutka** [comment]
Okay, thanks for the advice. However, it doesn't change anything about the issue that lerna unnecessarily duplicates the output.

**Comment by bdwain** [comment]
Agreed. I actually delegate lint behavior to my subprojects as well. Regardless of what the command is actually doing though, it seems like loglevel="silent" should stop the duplication of all stdout from lerna's subtasks. If it's meant for something else though, maybe there could be a new option to suppress this output.
