### ISSUE TITLE
older versions won't be updated in package's package.json file after publish

### ISSUE THREAD

**Issue by veeramarni** [lerna/lerna#1486]
We have a dedicated a branch called `publish` for publishing and tagging of the packages. And we don't want to merge it with our master, so the newly generated published version only stays in `publish` branch. We want to do this as we noticed in past that when one of the package uses older version, `lerna bootstrap` deletes the packages due to issue described in #951 

The problem we having with our approach is when we merge master with publish and if the package's dependencies of other packages were overwritten from master to default version (which is `*`), those version won't be updated by `lerna publish`

## Expected Behavior

```
{
  "name": "my-application/sub-tool",
  "version": "0.0.15-63",
  "dependencies": {
    "@my-namespace/my-tool": "*"
  }
}
```
should be changed to

```
{
  "name": "my-application/sub-tool",
  "version": "0.0.15-63",
  "dependencies": {
    "@my-namespace/my-tool": "^0.0.15-63"
  }
}


```
## Current Behavior

```
{
  "name": "my-application/sub-tool",
  "version": "0.0.15-63",
  "dependencies": {
    "@my-namespace/my-tool": "*"
  }
}
```

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "commands": {},
  "packages": [
    "packages/*",
  ],
  "version": "0.0.15-63"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 6.1.0 |
| `node --version` | 8.9.4 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
You should publish from master. I don't know why you have a separate branch, isolating the tags that lerna creates and whatnot. There is no difference between `*` and `^0.0.15-63` as the version specifier for a local sibling package.

**Comment by veeramarni** [comment]
@evocateur 

My question was, why doesn't `lerna` update the versions of all the packages even if see some discrepancies like `*` to the latest updated version? I was expecting `lerna` when releases it releases all `dependencies` with the latest version instead it leaves the packages with `*` as it is.
