### ISSUE TITLE
Question: is there a way to not link some packages but copy them

### ISSUE THREAD

**Issue by slawiko** [lerna/lerna#1490]
In our application we have one module which is needed to be instantiated for each monorepo's module by itself. It means that this module cannot be linked in others modules: we need separate instances.

Currently this problem is resolved by publishing this "not-linkable package" in npm, and adding it in monorepo's modules dependencies. But as you can see it is not pure monorepo.

Is there any possibility to not link but copy dependencies in each `node_modules` where it's needed?

**Comment by evocateur** [comment]
It sounds like the module in question should be refactored into a factory, not a singleton. In any case, copying instead of linking is not in scope, sorry.
