### ISSUE TITLE
Different exit code between updated and publish

### ISSUE THREAD

**Issue by cncolder** [lerna/lerna#1496]
## Expected Behavior

`lerna publish` should have same exit code with `lerna updated`.
So that I can run `lerna publish && yarn another-job`
But now I must run `lerna updated && lerna publish && yarn another-job` for skip another-job when nothing publish.

## Current Behavior

If repo up-to-date. `lerna updated` exit code is 1. But `lerna publish` exist code is 0.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | VERSION |
| `yarn --version` | 1.7.0 |
| `node --version` | 10.6.0 |

| OS | Version |
| --- | --- |
| macOS | 10.13.5 |

**Comment by evocateur** [comment]
The exit codes for those two commands serve different purposes. If you need to run something after modules are actually published successfully, place it in a `postpublish` lifecycle in the root package.json file.
