### ISSUE TITLE
Support client option for hoist

### ISSUE THREAD

**Issue by oMaten** [lerna/lerna#1497]
Provide the option for hoist to set custom client.

## Expected Behavior

I notice that `lerna bootstrap --hoist` will ignore the client option since the client like `yarn` do not support flag `--global-style`
But i use the client like [cnpm](https://github.com/cnpm/cnpm) totally support the commands of npm
I expect a option to set custom client for hoist

## Current Behavior

`lerna ERR! 404 not found @private/module` happened, since npm can not install from private mirror

## Possible Solution

Provide the options for hoist and give a friendly hint

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` |  |
| `node --version` | 8.11.3 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.5 |

**Comment by evocateur** [comment]
Are you passing `--npm-client cnpm` (or configuring `"npmClient": "cnpm"` in lerna.json)? I don't see anything blocking any `--npm-client` _other_ than yarn from being called with `--hoist`.

**Comment by oMaten** [comment]
It's my misunderstanding about hint `Error: Command failed: npm install --global-style` , the problem has been solved, Thanks.
