### ISSUE TITLE
Lerna publish flag `--conventional-commits` doesn't work with `--npm-tag` flag

### ISSUE THREAD

**Issue by mocheng** [lerna/lerna#1498]
## Expected Behavior

I have one project that have one trunk branch to release with dist-tag `latest`. For next major version, there is another branch `task/v3` to release with dist-tag `v3`.

The script is like below:
```
lerna publish --conventional-commits --exact --npm-tag=v3
```
It is expected to publish all packages with conventional-commits and on dist-tag `v3`.

## Current Behavior

The script failed with message like below:
> npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! publish:v3: `lerna publish --conventional-commits --exact --npm-tag=v3`
npm ERR! Exit status 1

## Possible Solution

It looks that the two flags `--conventional-commits` and `--npm-tag` are not compatible.

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-beta.21 |
| `npm --version`  | 5.6.0 |
| `node --version` | v6.13.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.5 |

**Comment by bmuenzenmeyer** [comment]
@mocheng if you use one or the other, does it appear to work?

**Comment by mocheng** [comment]
@bmuenzenmeyer  It works well if I use either `--conventional-commits" or "--npm-tag=v3" only.

**Comment by evocateur** [comment]
I can't reproduce without your `lerna.json` and more detailed repo state.

**Comment by alampros** [comment]
I'm running into a similar issue with the `--canary` flag and `--conventional-commits`.

#### My `lerna.json`:
```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "conventionalCommits": true,
      "message": "chore(release): publish [skip-ci]"
    }
  },
  "ignoreChanges": [
    "packages/*/test/**",
    "packages/*/test-server/**"
  ]
}
```

#### Shell Output (scrubbed)
```sh
yarn ci-publish --canary --preid beta --npm-tag next --yes
yarn run v1.12.3
$ lerna publish --canary --preid beta --npm-tag next --yes
lerna notice cli v3.8.4
lerna info versioning independent
lerna info ci enabled
lerna info canary enabled
lerna WARN Yarn's registry proxy is broken, replacing with public npm registry
lerna WARN If you don't have an npm token, you should exit and run `npm login`
lerna info Looking for changed packages since 1bf4a0d^..1bf4a0d
Found 1 package to publish:
 - @[-org-]/[-packagename-] => 0.8.2-beta.2+1bf4a0d
lerna info auto-confirmed 
lerna info publish Publishing packages to npm...
lerna info Verifying npm credentials
lerna http fetch GET 200 https://registry.npmjs.org/-/npm/v1/user 313ms
lerna http fetch GET 200 https://registry.npmjs.org/-/org/[-user-]/package?format=cli 117ms
lerna success published @[-org-]/[-packagename-] 0.8.2-beta.2+1bf4a0d
lerna notice 
lerna notice 📦  @[-org-]/[-packagename-]@0.8.2-beta.2+1bf4a0d
lerna notice === Tarball Contents === 
lerna notice 2.2kB  package.json                
lerna notice 3.2kB  CHANGELOG.md                
lerna notice 2.8kB  index.js                    
lerna notice 5.7kB  lib/common.js               
...more files
lerna notice === Tarball Details === 
lerna notice name:          @[-org-]/[-packagename-]                        
lerna notice version:       0.8.2-beta.2+1bf4a0d                                  
lerna notice filename:      [-org-]-[-packagename-]-0.8.2-beta.2+1bf4a0d.tgz
lerna notice package size:  12.4 kB                                               
lerna notice unpacked size: 51.4 kB                                               
lerna notice shasum:        7e5d7feb65225b59da23b82ef1fb71ac21ed2305              
lerna notice integrity:     sha512-f1mj17DhxpREE[...]qSbfO/X0bOrlg==              
lerna notice total files:   14                                                    
lerna notice 
lerna http fetch PUT 200 https://registry.npmjs.org/[-org-]%2f[-packagename-] 4017ms
Successfully published:
 - @[-org-]/[-packagename-]@0.8.2-beta.2+1bf4a0d
lerna success published 1 package
Done in 5.85s.
```

This was run in a CI environment thru a yarn script:
```json
{
  "scripts": {
    "ci-publish": "lerna publish",
    ...
  }
  ...
}

**Comment by evocateur** [comment]
@alampros Did the dist-tag `next` get set correctly?

Uh, whoops, I think I may have found a bug where `--npm-tag` isn't being passed correctly...

(`--canary` and `--conventional-commits` have no relationship, as `--canary` skips `lerna version` logic)

**Comment by evocateur** [comment]
> Uh, whoops, I think I may have found a bug where `--npm-tag` isn't being passed correctly...

Sorry, [false alarm](https://github.com/lerna/lerna/blob/c7fa58029f7e0f057ed89b29caae36bc28e48f73/commands/publish/index.js#L96-L101). Still, itches enough that I'm going to add more tests so I can reassure myself.

**Comment by alampros** [comment]
@evocateur No, the dist-tag was not set. From the looks of it, npm defaulted it to `latest` on their side.

I'm not sure if it matters at all, but it might be worth mentioning that this is a private module.

Thanks so much for the quick response and for your work on this project – it is truly awesome!

**Comment by evocateur** [comment]
@alampros Thanks for following up. Hrm, that's disturbing that the dist-tag wasn't set correctly. I'll add a test combining `--canary` and `--conventional-commits` and see if it behaves differently than I expect. I'm not sure why it would ignore `--npm-tag` (all of my tests so far indicate that it _is_ respected, at least in the sense that lerna is passing `opts.tag` with the appropriate value)...

**Comment by alampros** [comment]
So I tried it again without `--conventional-commits` at all and it's still not taking it. I'll create a separate issue if I can narrow it down any further so as not to hijack this one.

**Comment by evocateur** [comment]
[v3.8.5](https://github.com/lerna/lerna/releases/tag/v3.8.5) should fix this
