### ISSUE TITLE
lerna3 rewrite git remote url after publish

### ISSUE THREAD

**Issue by cncolder** [lerna/lerna#1499]
## Expected Behavior

bump version
```diff
-git+https://user:token@gitlab.com/g/r.git#v0.0.1
+git+https://user:token@gitlab.com/g/r.git#v0.0.2
```

## Current Behavior

rewrite whole url
```diff
-git+https://user:token@gitlab.com/g/r.git#v0.0.1
+git+ssh://git@gitlab.com/g/r.git#v0.0.2
```

## Possible Solution

lerna2 correct handle this

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
  "version": "0.0.1",
  "packages": [
    "client/*",
    "server/*"
  ],
  "useGitVersion": true,
  "gitVersionPrefix": "v",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "cdVersion": "prerelease",
      "conventionalCommits": true,
      "preid": "beta",
      "exact": true,
      "message": "chore(release): publish %s"
    }
  },
  "ignoreChanges": [
    "**/tests/**",
    "**/*.md",
    "**/*.yaml",
    "**/Dockerfile"
  ]
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-beta.21 |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
It wasn't specific to gitlab, but it certainly was awkward, as your example demonstrates. Thanks for raising the issue!
