### ISSUE TITLE
Contributing: How to add a new dependency to lerna?

### ISSUE THREAD

**Issue by honzajavorek** [lerna/lerna#1500]
What is the preferred way to add a dependency to one of lerna's sub-packages? Let's say I developed a feature for lerna, but it needs an additional library. Should I add it to `commands/foo/package.json` manually? How to generate the root `package-lock.json` properly?

I'm missing this info in the `CONTRIBUTING.md`. I'm sorry if it's obvious. I'm willing to contribute the section if you guide me through it here in the comments.

**Comment by evocateur** [comment]
The procedure was correct, but the lockfile output should only have included the `fs-extra`-related changes, not the `bundled` packages.

In lerna itself, you can also use the `lerna add` command (after running `npm link` in the repo root).

**Comment by doug-wade** [comment]
Looks like we answered this question, so I'm going to close.  If I'm incorrect and there is something more to be asked, please reopen.
