### ISSUE TITLE
Do I need to publish my packages to npm?

### ISSUE THREAD

**Issue by joetidee** [lerna/lerna#1503]
I am wondering if I need to publish my packages within my Lerna project to npm, or can I simply use the packages as local packages? For example, say I have the following packages in my Lerna repo:

```
client-package
api-package
shared-package
```

(where shared-package is use by both client and api packages)

As part of my deployment pipeline, can I simply run `lerna bootstrap`, then copy client + shared packages to my client server, then api + shared package to my api server without needing to publish them to npm?

**Comment by negezor** [comment]
You can locally use the packages. It is not necessary to lay out in the NPM code that is not aimed at other developers, since it clutters NPM.

**Comment by evocateur** [comment]
If you're not publishing _anything_ to an npm registry, just use relative path `require`/`import`.
