### ISSUE TITLE
[Feature] Option to put all changed packages under one Git tag

### ISSUE THREAD

**Issue by ChrisBAshton** [lerna/lerna#1512]
If I have a repo with packages A, B and C
And I make a change to packages A and B - where each package's change is dependent on the other
When I run `lerna publish --independent`...

## Expected Behavior
...Then I would like to be able to tag that as ONE release on GitHub.

## Current Behavior
...Currently, a separate tag would be created for each updated package.

## Context
Often we have to make changes to multiple packages in order to deliver one distinct "feature". It makes no sense for us to treat each package update as a separate release - what's most useful is that we can go into GitHub releases and see that version X is the one that adds the feature. It's hard to otherwise pick apart exactly which combination of releases delivered the feature.

**Comment by evocateur** [comment]
You shouldn’t use “independent” versioning, then? The default “fixed” versioning mode does exactly what you’re asking for.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ChrisBAshton** [comment]
Almost, but not quite - we still want the freedom to publish independent versions. For example: package A is a major version release, package B is a minor version release, but they're both connected to each other so should only appear as one tag on GitHub.

Fixed/Locked mode would force package B to be a major release when we don't want it to be.

**Comment by ChrisBAshton** [comment]
Perhaps an extra flag would be useful? Something like:

```
lerna publish --independent --combined-git-tag
```

The great thing about Lerna is that it lets you manage code better, by having related packages in a monorepo where everything can be seen in one place - yet the freedom to make each package independently published & self-contained.

Git tagging is about code management, rather than NPM which is about having something versionable to consume as a third-party. So I don't think the `--independent` flag should have to apply to all parts of the publication pipeline 🤔

**Comment by evocateur** [comment]
How do you propose to synthesize multiple independent semantic versions into a single, concise, meaningful git tag?

I definitely sympathize with this desire, but it's not a simple problem (and the problem isn't coding, it's conceptual).

**Comment by ChrisBAshton** [comment]
Very good question!

If only one package has changed, the `--combined-git-tag` does nothing (treat as a normal release).

If more than one package has changed, the `--combined-git-tag` shows we want to override the Git tag behaviour, best handled in a Lerna prompt.

> Which package should form the basis of the Git tag?
> \- Package A
> \- Package B
> \- None

If a package is chosen, the version would be derived from that, perhaps with an identifier (e.g. `v8.0.2-combined`) to signify that other packages form part of the release.

If `None` is chosen, allow the dev to form their own tag name:

> Write the name of the desired Git tag: ________

This could even be made part of the CLI api to avoid the prompt completely, if the developer wishes!

`--combined-git-tag="custom-tag"`

That would be my suggestion. (I _had_ thought of adding a `"corePackage"` property to the [lerna.json](https://github.com/lerna/lerna#lernajson), as there's typically a 'master' package - e.g. `babel-core` - with multiple satellite dependencies that are all basically tied to the core major version. That worked great until I thought "what happens when a change is made to a _satellite_ dependency, and _not the core_"? So the solution would need to vary on a case by case basis!)
