### ISSUE TITLE
[Feature] Option to automatically 'publish' Releases on GitHub

### ISSUE THREAD

**Issue by ChrisBAshton** [lerna/lerna#1513]
When you push a tag to GitHub, it adds it to the list of Releases but is 'unpublished', therefore doesn't look like the most recent version:

![screen shot 2018-07-20 at 17 37 45](https://user-images.githubusercontent.com/5111927/43014306-a78c03f0-8c43-11e8-99de-34bbfcf0f447.png)

It would be really awesome if Lerna provided some option to automatically _publish_ each release with sensible defaults - perhaps e.g. with a prompt:

```
> Would you like to publish this release on GitHub releases? y/N
> Would you like to combine these updates into one release? y/N
# see https://github.com/lerna/lerna/issues/1512
> What should the release title be?
___
> What should the release description be?
____________
```

**Comment by phun-ky** [comment]
Would also love to combine this with lerna-changelog and/or github-release-notes

**Comment by ChrisBAshton** [comment]
Adding a comment to keep this 'fresh'. It's had a few +1s so looks like it's worth keeping open.

**Comment by evocateur** [comment]
#1864 is in the process of implementing this, at least for users of `--conventional-commits`.
