### ISSUE TITLE
lerna publish will pending always on node v10.7.0

### ISSUE THREAD

**Issue by tarol** [lerna/lerna#1515]
## Expected Behavior

publish package

## Current Behavior

terminal will pending always after select version

## Possible Solution

revert nodejs to v8.11.3

## Steps to Reproduce (for bugs)

1. npm publish
2. select version
3. pending...
4. pending...

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.9.0",
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "version": "independent"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 6.2.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | 10.7.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
Oh lovely, somebody changed the stdio semantics in core again...

**Comment by philippfromme** [comment]
Same here, using Node.js v10.7.0.

**Comment by evocateur** [comment]
So I was able to successfully publish 43 packages for lerna [v3.0.0-rc.0](https://github.com/lerna/lerna/releases/tag/v3.0.0-rc.0) last night using node v10.7.0 + npm 6.2.0. I also promoted lerna 3 to the "latest" dist-tag, so I would recommend upgrading. I'm not likely to have bandwidth to debug lerna 2.x anytime soon.
