### ISSUE TITLE
It would be nice if ls and updated --json would show the package directory

### ISSUE THREAD

**Issue by light24bulbs** [lerna/lerna#1516]
These commands are great for human readers, but not as great for scripting.  
## Expected Behavior
Include the package path in the json

## Current Behavior
Lerna just gives the package name and version, which is harder to script with.

## Summary

I realize it is possible to use `exec` with flags to achieve some of the same functionality.  What if I want to get the paths of all updated packages and then pass those into a script not running inside `lerna exec`?  
I could potentially do something with `lerna exec pwd --since` and pipe the output, but that's not as nice.

**Comment by Janpot** [comment]
+1
I would like to be able to dynamically generate an array of rollup configurations based on the packages in my repo. Preferably through a javascript API. But since that seems to be off the table in the short term, executing lerna in a childprocess would work just as well for me. But for that I'd need the package locations as well.
```js
export JSON.parse(execa.sync('lerna' [ 'ls', '--json', '--loglevel=silent' ]))
  .map(createConfig)
```

**Comment by evocateur** [comment]
Yeah, trying to get it released today.

**Comment by evocateur** [comment]
https://github.com/lerna/lerna/releases/tag/v3.0.0

**Comment by light24bulbs** [comment]
This is really great!  Thank you!

Why does `ls` only list public packages by default?  Is there a way to make it list private packages?  `--no-private` doesn't apply as that is the default behavior. 

 Is there currently any method for listing and filtering lerna package paths that include private packages?
