### ISSUE TITLE
Independent mode can't work with lerna command

### ISSUE THREAD

**Issue by NE-SmallTown** [lerna/lerna#1520]
## Expected Behavior
It works.

## Current Behavior

https://github.com/lerna/lerna/blob/06b88d4a0fbc4a8fc1923f621725208fc85789bc/core/command/index.js#L171
 will check the 'version' field in the package.json, but the [independent mode](https://github.com/lerna/lerna#independent-mode---independent) will ignore the 'version' field. This is contradictory because when I run any command like 'lerna add', 'lerna bootstrap'...., all of them will throw the Error

## Possible Solution

I don't know, maybe it's intended.

## Steps to Reproduce (for bugs)
See above.

<p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "command": {
    "publish": {
      "ignoreChanges": [
        "**/*.md"
      ]
    }
  }
}
</p></details>
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-beta.21|
| `npm --version`  | 5.6.0 |
| `yarn --version` | VERSION |
| `node --version` | 8.11.3 |

| OS | Version |
| macOS high Sierra | 10.13.4 |

**Comment by NE-SmallTown** [comment]
Seems like my lerna version is 2.x, uninstall globally and reinstall the 3.x will solve this problem.

**Comment by evocateur** [comment]
`this.project.version` points to the `version` field of lerna.json, which in independent mode is `"independent"`. This is distinct from `this.project.manifest.version`, which is the (currently meaningless) `version` field of the root package.json.
