### ISSUE TITLE
Lerna bootstrap doesn't add the 'bin' field to $PATH

### ISSUE THREAD

**Issue by NE-SmallTown** [lerna/lerna#1523]
## Expected Behavior
Lerna can add the 'bin' field to $PATH so I can run the command everywhere.

## Current Behavior
If packageA/package.json has a 'bin' field and I use Lerna bootstrap,  I can find packageA and ./bin directory in the packageB's node_modules，but the 'bin' field doesn't be added to the $PATH so I have to run './node_modules/./bin xxx ' in the packageB path but I can't run the command everywhere.

## Possible Solution
I don't know. Maybe add it to the $PATH manually

## Steps to Reproduce (for bugs)
See above.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "command": {
    "publish": {
      "ignoreChanges": [
        "**/*.md"
      ]
    }
  }
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-beta.21 |
| `npm --version`  | 5.6.0
| `node --version` | 8.11.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by NE-SmallTown** [comment]
Sorry for the wrong description, I update the issue, could you look through again? Is this intended?

**Comment by evocateur** [comment]
I have literally no idea, as you've failed to actually show the code demonstrating these problems.
