### ISSUE TITLE
lerna bootstrap fails after updating to 3.0.0-rc.0

### ISSUE THREAD

**Issue by tyler-johnson** [lerna/lerna#1525]
I updated lerna in my project to 3.0.0-rc.0 and then running `lerna bootstrap` failed with the following error (pulled from lerna-debug.log):

```
473 info hoist Finished pruning hoisted dependencies
474 silly getExecOpts { cwd: '/Users/tyler/Development/pagedip-framework',
474 silly getExecOpts   pkg: Package { name: 'pagedip-framework' } }
475 silly npmInstall [ 'npm', [ 'install' ] ]
476 silly npmInstallDependencies cleanup /Users/tyler/Development/pagedip-framework/package.json
477 error TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
477 error     at assertPath (path.js:39:11)
477 error     at Object.relative (path.js:1172:5)
477 error     at new Package (/Users/tyler/Development/pagedip-framework/node_modules/@lerna/symlink-binary/node_modules/@lerna/package/index.js:32:57)
```

I mostly just thought I should let someone know that I saw this error. I will say that I managed to "fix" it by running `lerna clean`, removing node_modules and doing a fresh bootstrap.

If this is expected or otherwise known, feel free to close this! Thanks.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-rc.0 |
| `npm --version`  | 6.2.0 |
| `node --version` | v10.6.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.6 |

**Comment by evocateur** [comment]
Oh geez, no, this is totes a bug. Disturbed that none of the unit or integration tests caught this...

**Comment by tyler-johnson** [comment]
So I keep hitting this issue so I did some investigating. It seems like in my case the issue is that @lerna/symlink-binary gets a different version of @lerna/package then everything else. As a result, [this `instanceof` check](https://github.com/lerna/lerna/blob/a656a0136d7d5d8b8bb709e2da2b8b2582036fe7/utils/symlink-binary/symlink-binary.js#L49) fails.

In my own code, I try to avoid `instanceof` checks for this exact reason. NPM tends to install multiple copies of the same packages which leas to this issue. Instead I like to attach a really specific, hidden property to classes that can be checked for.

**Comment by evocateur** [comment]
Yeah, that's fair. Thanks for the investigation!

**Comment by evocateur** [comment]
[v3.1.4](https://github.com/lerna/lerna/releases/tag/v3.1.4) fixes this
