### ISSUE TITLE
bootstrap doesn't take additional .npmrc files into account

### ISSUE THREAD

**Issue by stefanbuck** [lerna/lerna#1527]
I have all my public and private packages in one monorepo. A few private packages depending on other private packages which aren't part of this monorepo. Running `lerna bootstrap` fails, because it can't access those private packages. Adding a `.npmrc` file to the repo root solves this issue, but it updates all registry url in the lockfiles with the private registry.

## Expected Behavior
`lerna bootrap` takes `.npmrc` files from each package folder into account.

## Current Behavior
It fails with `lerna ERR! npm ERR! 404 Not Found ...`

## Possible Solution
`lerna bootrap` should check if a `.npmrc` file exists in a package folder before performing `npm install` 

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0
| `npm --version`  | 6.1.0
| `yarn --version` |
| `node --version` | 10.3.0

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.6 |

**Comment by doug-wade** [comment]
Why aren't those other private packages in the monorepo?

**Comment by stefanbuck** [comment]
Fair point, but I just started with that monorepo and most of our dependencies are still spread across different repositories / systems. Also I thought it would be a nice addition to lerna.

**Comment by evocateur** [comment]
Presumably you're using a scope to identify these private packages? Scoping the registry in the root `.npmrc` is the solution.

**Comment by stefanbuck** [comment]
Indeed, we do and it works partly. 

I added a `.npmrc` file in the repository root which point to our private registry. Adding a new decency at root level pulls the packages from our registry. If I add a new decency to a `packages/file-matcher-helper` it tries to pull this package from the public npm registry rather than our private one.

Maybe I have to duplicate the `.npmrc` file across all packages folder.

**Comment by stefanbuck** [comment]
`lerna add ...` with a `.npmrc` in the root does the trick.
