### ISSUE TITLE
lerna version command not recognized

### ISSUE THREAD

**Issue by Nitesoul** [lerna/lerna#1530]
I have updated lerna in our project to 3.0.0-rc.0.   I was planning on making use of the 'lerna version' command as noted in the documentation; however, it appears the command is not being recognized as it returns an Unknown argument error.

```
λ lerna -v
3.0.0-rc.0

λ lerna version
ERR! lerna Unknown argument: version
```

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.0.0-rc.0",
  "useWorkspaces": true,
  "npmClient": "yarn",
  "version": "independent"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-rc.0|
| `npm --version`  | 5.6.0|
| `yarn --version` |1.7.0 |
| `node --version` | 8.10.0|

| OS | Version |
| ---: | :--- |
| Windows 10 | 1709 |

**Comment by evocateur** [comment]
It hasn't been released yet, sorry. Soon.
