### ISSUE TITLE
conventional commits/changelog adds all previous commits to release

### ISSUE THREAD

**Issue by rumtraubenuss** [lerna/lerna#1532]
## Current Behavior
With a lerna setup with `version: independent` and `conventionalCommits: true` for the publish command in `lerna.json`: when publishing a new release with `lerna publish` lerna takes all previous commits into account and adds all commits again into `CHANGELOG.md` for this release and also raises the version respecting all previous commits.

## Expected Behavior
After publishing a release with `lerna publish` only commits are respected which came after the previous release.

## Steps to Reproduce
1. Add a feature commit `feat: add a new feature`
2. `lerna publish` // will raise minor version 1.0.0 -> 1.1.0
3. Add a fix commit `fix: fix a bug`
4. `lerna publish` // will raise minor version again 1.1.0 -> 1.2.0 but should only raise patch to 1.1.1

Also in the `CHANGELOG.md` for the second release both commits will be listed but only the latest one should be listed.

See this demo repo: https://github.com/rumtraubenuss/monorepo/blob/master/packages/foo/CHANGELOG.md

## Environment

```json
{
  "lerna": "3.0.0-rc.0",
  "packages": ["ui-lib/*"],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "commands": {
    "publish": {
      "allowBranch": "master",
      "conventionalCommits": true
    }
  }
}
```

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-rc.0 and 2.11.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.7.0 |
| `node --version` | 8.11.1 |

| OS | Version |
| --- | --- |
| macOS | 10.13.6 |

**Comment by evocateur** [comment]
Thanks for the example reproduction!

**Comment by rumtraubenuss** [comment]
I did some further investigation. Turns out that it is a "local" issue. Setting up the project on a coworkers machine the issue does not occur. Git, node, yarn versions are the same. I thought for a moment it could be related to the shell since I am using `zsh`, `iterm` and `tmux`. But when I switched my default shell to `bash` without `tmux` in macOS `Terminal.app` I got the same faulty behaviour.
Here are some more system informations:
git `git version 2.15.2 (Apple Git-101.1)`
yarn `1.9.2`
node `8.11.3` with `nodenv` as a node manager. But it is the same without `nodenv` and a default node version of `10.8.0`.
I am running out of ideas where this could be related. Could somebody else try to reproduce the issue?

**Comment by rumtraubenuss** [comment]
The issue is triggered by a format setting in my global git config `~/.gitconfig`:
```
[format]
	pretty = %Cblue%h%Creset %Cgreen[%cr]%Creset (%an) %s
```
Removing this and everything works as expected.

@evocateur Do you think that this is still related to `lerna` itself or rather to a dependency package like `conventional-changelog-core`?

**Comment by evocateur** [comment]
I believe this is the conventional changelog parser calling `git log` with a significant format. Lerna itself doesn't use `git log` internally.

**Comment by nemoDreamer** [comment]
I'd also banged my head against this... I'm the only one on my team that this is happening for. I tried so many different things: pegging revisions (but we already use `yarn.lock`...), installing a specific version of `git`, etc...

...but yes: I've got a custom `format.pretty` in my config... 😢 😭

**Comment by evocateur** [comment]
The `format.pretty` conflict leading to unexpected output is a good issue to raise [here](https://github.com/conventional-changelog/conventional-changelog/issues). I consider this fixed, from lerna's perspective.
