### ISSUE TITLE
--hoist option try to download from registry before symlinking

### ISSUE THREAD

**Issue by GMartigny** [lerna/lerna#1533]
## Expected Behavior
When using the "--hoist" options with the "bootstrap" command, lerna seems to try to download from registry local packages. (and fail when not possible)

## Current Behavior
I made a [repro-repo](https://github.com/GMartigny/lernahoist) so you can check the behavior.
Running `lerna bootstrap --hoist` result to an error because the sub-package is not find under NPM registry.

## Possible Solution
Running `lerna boostrap` returns no error, so it should have the same behavior.

## Steps to Reproduce (for bugs)
Have a dependency not present under NPM registry and use `--hoist` options when bootstraping.

[repro-repo](https://github.com/GMartigny/lernahoist)

## Context
I was expecting to save some time on CI build, because every-one of my sub-package use the same test runner. As I was adding a new sub-package (not yet published), the CI build fail.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-rc.0 |
| `npm --version`  | 6.2.0 |
| `node --version` | 10.6.0 |
| Ubuntu | 14.6 |

**Comment by evocateur** [comment]
Hoisting doesn't make much sense when you _also_ treat the root package as a lerna-managed package (`"packages": ["."]` in lerna.json). I really don't recommend a "rooted" leaf, the root manifest should only coordinate shared devDependencies and test scripts.

**Comment by GMartigny** [comment]
If it's the root cause of the problem, I can live with that. What I find strange is that `bootstrap` without hoisting don't trigger the error. 

In my case, I have a library with sub-modules. The root leaf just import all sub-module to pack them into one file (for CDN).

After all, I just wanted to save a few seconds on my build, not a very big deal.

**Comment by evocateur** [comment]
That's a good pattern that is perfectly capable of living as a sibling leaf under the packages directory. `--hoist` causes `npm install` to be run in the root first, with a mutated package.json including all hoisted dependencies, and apparently didn't expect local dependencies to live there too.
