### ISSUE TITLE
Interactively responding to lerna publish with `n` / `^C` fails to stop commits / publishes

### ISSUE THREAD

**Issue by tim-evans** [lerna/lerna#1534]
👋 Hello there! I started using the RC-0 version of lerna to use our custom conventional-commits preset, and encountered an issue while testing our plugin.

## Expected Behavior
Cancelling the publish by saying `n` or exiting the script using `^C` should undo git tags, commits, etc.

## Current Behavior
lerna adds git tags, a publish commit, and starts the process of building our TypeScript for publish.

## Steps to Reproduce (for bugs)

The repository that I was working on was this: https://github.com/CondeNast-Copilot/atjson

1. `lerna publish`
2. Respond with `n` or `^C`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.0.0-rc.0",
  "version": "independent",
  "packages": [
    "packages/@atjson/*"
  ],
  "command": {
    "publish": {
      "exact": true,
      "conventionalCommits": true,
      "changelogPreset": "./packages/@atjson/conventional-changelog-emoji"
    },
    "bootstrap": {
      "hoist": true,
      "npmClientArgs": [
        "--no-package-lock"
      ]
    }
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-rc.0 |
| `npm --version`  | 6.2.0 |
| `yarn --version` | N/A |
| `node --version` | v6.10.2 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.4 |

**Comment by evocateur** [comment]
Answering "n" at the prompt to continue isn't stopping? That's pretty bad, if reproducible.

`^C` once you've passed that prompt isn't really a deterministic thing, you could be halfway through uploads to the registry, and that really doesn't justify rolling back tags etc.

**Comment by tim-evans** [comment]
Yep! Less concerned about `^C`, but I did spam it last time 😅 and it continued trying to publish

**Comment by mAAdhaTTah** [comment]
Yeah... I'm having this issue as well. The `^C` not rolling back tags is fun, but it doesn't seem to terminate the process either.

**Comment by evocateur** [comment]
I guess I'll try a random `lerna publish` tomorrow and try to say "no" at the prompt...

**Comment by tim-evans** [comment]
Okieee! Thanks for the heads up! :)
