### ISSUE TITLE
Pass path to lerna.json as argument

### ISSUE THREAD

**Issue by zentoaku** [lerna/lerna#1537]
Is it possible to pass path to lerna.json as an argument?  If not would it be possible to have that kind of feature? Having that would not break the way the lerna works but would solve all kind of issues like https://github.com/lerna/lerna/issues/1282 and other similar.

**Comment by evocateur** [comment]
No, sorry. That wouldn't solve the linked issue, either.

**Comment by zentoaku** [comment]
@evocateur yes it would. If you could pass a separate "packages" list for each command you could choose to use parent folder or mentioned dist. The only requirement is that dist would have to have package.json inside.

Example for bootstrap:
```{
  "lerna": "2.11.0",
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}```

for publish:
```{
  "lerna": "2.11.0",
  "packages": [
    "packages/*/dist"
  ],
  "version": "independent"
}```

why wouldn't you add such feature? Shouldn't be much of a problem.

**Comment by evocateur** [comment]
http://neugierig.org/software/blog/2018/07/options.html

**Comment by zentoaku** [comment]
@evocateur and? This doesn't answer anything. The option I've mentioned doesn't break anything, doesn't make it harder to use or understand the lib so the document you've posted doesn't apply, at least from my perspective. You're already loading this file, just loading it from different location doesn't add much cost. Please consider stating your ground and explaining instead of just shutting the discussion down.
I don't want to offend you, I just like to understand reasons and not to take everything on trust.

**Comment by evocateur** [comment]
Options are always more burden for the maintainer, they are not free. It's also mildly offensive to assert adding a feature "shouldn't be much of a problem."

One immediate problem with your proposal: lerna stores the fixed version in lerna.json. How would you propose synchronizing that across multiple config files? ("I use independent versioning" isn't a solution)

**Comment by zentoaku** [comment]
@evocateur thank you for that. That's exactly the answer I was looking for. I'm not maintaining this one so I don't see all "pain points". Your answer I solid and you should have had start with that :)
