### ISSUE TITLE
Links in CHANGELOG.md files are broken when using conventional-commits

### ISSUE THREAD

**Issue by bennycode** [lerna/lerna#1538]
## Expected Behavior
Links in generated `CHANGELOG.md` files are broken because lerna adds "tree/master/packages/package-name" to the URL which is wrong.

**Live Example:** 
- https://github.com/wireapp/wire-web-packages/blob/master/packages/react-ui-kit/CHANGELOG.md

**Broken Links:**

```
https://github.com/wireapp/wire-web-packages/tree/master/packages/react-ui-kit/compare/@wireapp/react-ui-kit@2.1.3...@wireapp/react-ui-kit@2.2.0
https://github.com/wireapp/wire-web-packages/tree/master/packages/react-ui-kit/issues/936
https://github.com/wireapp/wire-web-packages/tree/master/packages/react-ui-kit/commit/def55c0
```

**Correct Links:**

```
https://github.com/wireapp/wire-web-packages/compare/@wireapp/react-ui-kit@2.1.3...@wireapp/react-ui-kit@2.2.0
https://github.com/wireapp/wire-web-packages/issues/936
https://github.com/wireapp/wire-web-packages/commit/def55c0
```

## Steps to Reproduce (for bugs)
1. Organize packages in a [sub-directory called "packages"](https://github.com/wireapp/wire-web-packages/tree/master/packages)
2. Run [lerna publish --conventional-commits](https://github.com/wireapp/wire-web-packages/blob/6c8164231195b1c6a0df0c056d91b6baa0808065/package.json#L47)

<details><summary>lerna.json</summary><p>

```json
{
	"lerna": "2.5.1",
	"npmClient": "yarn",
	"npmClientArgs": [
		"--exact"
	],
	"useWorkspaces": true,
	"version": "independent"
}
```
</p></details>

## Context
At Wire we have a monorepo that we manage with lerna. In [our monorepo](https://github.com/wireapp/wire-web-packages) there are several packages within a folder called "packages". To release all packages we run the following command:

> lerna publish -m \"[skip ci] chore: Publish\" --conventional-commits --loglevel=verbose --exact --allow-branch=master --registry=https://registry.npmjs.org/ --yes

The command above creates a release version for every package and adds `CHANGELOG.md` files to the directories of the individual packages. Unfortunately all the links in that CHANGELOG are broken because they include "tree/master/packages/package-name".

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 6.2.0 |
| `yarn --version` | 1.3.2 |
| `node --version` | 10.8.0 |

| OS | Version |
| --- | --- |
| Ubuntu | 14.04.5 LTS |

**Comment by evocateur** [comment]
I believe this is a [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) issue, as Lerna itself merely passes arguments to `conventional-changelog-core`, we don't do any url munging.

**Comment by evocateur** [comment]
Specifically [here](https://github.com/lerna/lerna/blob/3a5c079e3db01a1404b869b6ed585142be30587f/core/conventional-commits/lib/update-changelog.js#L49-L50) we are passing `options.lernaPackage` to `conventional-changelog-core`.
