### ISSUE TITLE
lerna add unable to retrieve package metadata from private repository

### ISSUE THREAD

**Issue by jd-carroll** [lerna/lerna#1539]
When attempting to install a package from a private repository (like Artifactory), lerna is unable to complete the installation because it cannot find the package.  The reason lerna is unable to find the package is because [`package-json`](https://www.npmjs.com/package/package-json) does not look at the repository configured via `npm config`.

The issue with `package-json` has been documented here: sindresorhus/package-json#45

However, there does not seem to be much movement on updating the package.

**Please use a different module to read package metadata from the configured npm repository**

**Comment by evocateur** [comment]
Lerna doesn't install packages, that's what npm and yarn do. Strikes me as an Artifactory problem if they can't support public registry APIs?
