### ISSUE TITLE
[Questions] filter options / scoping

### ISSUE THREAD

**Issue by zentoaku** [lerna/lerna#1543]
Hi, I would like to ask how to use --scope, --ignore, --force-publish.

I had setup with  lerna 2.11 like: 
`lerna publish --skip-git --force-publish=package1 --skip-npm --ignore "*(package2|package3|package4)"`
which worked perfectly and limited the packages being  publish to only one chosen packge. I've attached this approach to some scripts and was able to dynamicaly choose what I want to publish.

I had to upgrade to 3.0.0-rc.0 because I needed from-git param to use existing package versions (again managed by scripts). The problem is that now the first command doesn't seem to respect the --ignore pattern. Have something changed? Is it a bug? Or maybe I'm missing something? 
Additional thing is that adding --scope to publish command throws an error ("ERR! lerna Unknown argument: scope") but it isn't mentioned anywhere that some of the filter-options (https://github.com/lerna/lerna/tree/v3.0.0-rc.0/core/filter-options) are not available for all the commands.

Can you clarify my doubts about using those and the described issue? Thanks in advance.

**Comment by evocateur** [comment]
Publish should never be filterable by arbitrary packages, and 3.0 fixes accidental allowance of these filters. You're silently breaking the ability of `lerna publish` from properly recognizing future changes in the previously-ignored packages.

**Comment by zentoaku** [comment]
Ok, thanks.
