### ISSUE TITLE
A few questions about lerna

### ISSUE THREAD

**Issue by iliakan** [lerna/lerna#1545]
1) Is it ok that in `packages/` I have not only packages (with `packages.json`), but also regular modules, not packages? 

2) Let's say I have a monorepo with packages. Now I have another project with another repo, can I take a package from the monorepo? Is it what `lerna import` is for?

**Comment by evocateur** [comment]
1. Not illegal, but I wouldn't recommend it. Wherever you configure lerna-managed packages to be located, it's best if there are _only_ lerna-managed packages located there.

2. External consumers should use normal npm dependencies, which the lerna monorepo is designed to provide via publishing to a registry. `lerna import` is meant to import single-package repositories (aka "traditional" packages) into a lerna-managed monorepo, not the other way around.

**Comment by iliakan** [comment]
Thanks, now I got it.

Lerna is to support a monorepo, but installing into real projects is done a conventional way.
