### ISSUE TITLE
lerna with conventionalCommits raises semver for commits other than fix/feat/BREAKING CHANGE

### ISSUE THREAD

**Issue by rumtraubenuss** [lerna/lerna#1547]
## Current Behavior
When running lerna with `conventionalCommits: true` and creating a commit with a commit message like `refactor: change some lines` lerna will raise the version of the package with a patch version.

## Expected Behavior
Commit types like `chore:`, `refactor:`, `test:` and so on should not lead to a semver change for the package.

> https://conventionalcommits.org/ 
> Others: commit types other than fix: and feat: are allowed, for example commitlint-config-conventional (based on the the Angular convention) recommends chore:, docs:, style:, refactor:, perf:, test:, and others. We also recommend improvement for commits that improve a current implementation without adding a new feature or fixing a bug. Notice these types are not mandated by the conventional commits specification, and have no implicit effect in semantic versioning (unless they include a BREAKING CHANGE, which is NOT recommended). 

## Steps to Reproduce
1. Add a commit `refactor: change some lines`
2. `lerna publish`
This will raise patch version 1.0.0 -> 1.0.1 and add a line to the CHANGELOG.md like `Note: Version bump only for package...`

## Environment

```json
{
  "lerna": "3.0.0-rc.0",
  "packages": ["packages/*"],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "commands": {
    "publish": {
      "allowBranch": "master",
      "conventionalCommits": true
    }
  }
}
```

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-rc.0  |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.7.0 |
| `node --version` | 8.11.1 |

| OS | Version |
| --- | --- |
| macOS | 10.13.6 |

**Comment by rumtraubenuss** [comment]
The whole repository was published before. Then I just made a change in a single package (the demo repository only have a single package). So there is no local dependency to another package.

**Comment by evocateur** [comment]
> [T]here is no local dependency to another package.

Okay, just double-checking that there was no possible vector for lerna being responsible. This is an issue for [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog).

> the demo repository only has a single package

I don't see a demo repository linked?

**Comment by sthzg** [comment]
@evocateur Sorry for commenting on a closed issue. I am investigating the same topic and followed hints from issues all around to get an idea about the behavior:

1. The rough entry from the lerna-side to this topic seems to be here:   
[/core/conventional-commits/index.js#L6-L7][0]

2. Lerna will use the conventional changelog api to get the recommended bump level, which will always return the patch level (`2`) if it doesn't find a higher semver. 
[/packages/conventional-changelog-angular/conventional-recommended-bump.js#L8-L23][1]

3. According to the angular preset every type below here will not be put into the CHANGELOG: 
[/packages/conventional-changelog-angular/writer-opts.js#L44-L46][2]


This would explain why lerna creates a patch release, featuring only the generic CHANGELOG message `**Note:** Version bump only for package <foobar>`.

Given the explanation on https://www.conventionalcommits.org I would expect these other types to not trigger a release. 

In combination with the CHANGELOG that is generated it feels inconsistent, as it published the patch release but doesn't print the actual commit types inside there (as they are discarded in the `conventional-changelog-angular` preset).

I am interested if you think that there is something that can be improved in the way that lerna integrates/orchestrates the conventional-changelog APIs and which behaviour you think would be correct?

[0]: https://github.com/lerna/lerna/blob/master/core/conventional-commits/index.js#L6-L7
[1]: https://github.com/conventional-changelog/conventional-changelog/blob/d3eaacfe642eb7e076e4879a3202cc60ca626b59/packages/conventional-changelog-angular/conventional-recommended-bump.js#L8-L23
[2]: https://github.com/conventional-changelog/conventional-changelog/blob/03f0210e42dff58689ddf182694a8a6ca26e526b/packages/conventional-changelog-angular/writer-opts.js#L44-L46
