### ISSUE TITLE
Lerna Attempts To Publish When There's No Recommended Bump

### ISSUE THREAD

**Issue by hbetts** [lerna/lerna#1551]
The `publish` command for Lerna version `3` is giving us the undesirable version `null` when it attempts to release a package within a mono-repository if the package has _unreleasable_ changes, such as commits with the type `chore`.

Our company's `conventional-changelog` configuration package only recommends a release for new features, bug fixes, and breaking changes. If a commit does not contain any of those, then a `level` of `null` is returned, which is then returned by [`conventional-recommended-bump`](https://www.npmjs.com/package/conventional-recommended-bump).

[Lerna version `3` attempts to pass an `undefined` property](https://github.com/lerna/lerna/blob/cbac458b3ab3e0b184ebb9eefaffc542f62ee6a2/core/conventional-commits/lib/recommend-version.js#L32) (`undefined` because `level` was set to `null`), to the `semver.inc` function, which then returned `undefined` itself.

## Expected Behavior

We would like to see:

```bash
Changes:
 - @scope/package-a: 0.7.0 => 0.8.0
```

## Current Behavior

What we're seeing is:

```bash
Changes:
 - @scope/package-a: 0.7.0 => 0.8.0
 - @scope/package-b: 0.7.0 => null
 - @scope/package-c: 0.7.0 => null (private)
```

## Possible Solution

I'm currently using the latest published release of Lerna, so what I have access to is a little outdated from the latest code in this project.

However, the general idea is that if the recommended version is `undefined`, could Lerna remove the package from the set of packages to publish?

## Steps to Reproduce (for bugs)

Our project, and the `conventional-changelog` configuration package, are both private.

However, if the information here is insufficient, I will put together a set of projects that can reproduce this issue.

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  'conventionalCommits": true,
  "changelogPreset": "@scope/company",
};
```
</p></details>

I printed out the [value of `data` on line 27](https://github.com/lerna/lerna/blob/cbac458b3ab3e0b184ebb9eefaffc542f62ee6a2/core/conventional-commits/lib/recommend-version.js#L27) and it returned:

```bash
lerna sill independent for @scope/package-b at C:\Users\hbetts\Workspace\project\packages\project\packages\app
data { level: null,
  reason: 'There are 0 BREAKING CHANGES and 0 features' }
lerna verb independent increment 0.7.0 by undefined
```

## Context

We use `yarn lerna publish --concurrency 1 --exact --yes` to automatically release packages contained in a mono-repository.

This mono-repository, in addition to several others at our company, share a `conventional-changelog` configuration package (Which is only available internally at this time) that returns `level` of `null`, if a commit is not a feature, fix, or breaking change.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-rc.0 |
| `npm --version`  | 6.2.0 |
| `yarn --version` | 1.9.4 |
| `node --version` | v10.4.1 |

**Comment by hbetts** [comment]
Here's a copy from our CI logs:

```bash
16:50:21 lerna ERR! yarn publish --ignore-scripts --new-version  --non-interactive exited 1 in '@scope/package-b'
lerna ERR! yarn publish --ignore-scripts --new-version  --non-interactive stdout:
[1/4] Bumping version...
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
 
lerna ERR! yarn publish --ignore-scripts --new-version  --non-interactive stderr:
error Invalid version supplied.
```

**Comment by hbetts** [comment]
It was brought to my attention that there is a case where Lerna may need to override the recommendation.

If `package-b` depends on `package-a`, and `package-a` was released with a new version, Lerna may need to override the `undefined` recommendation and force a `patch` release with an update to `package-a` in the dependencies list of `package-b`, even if  `package-b` has no commits, or only _unreleasable_ commits.

**Comment by evocateur** [comment]
Ok, well, I fixed my issue.

I wasn't able to repro the `null` level or `releaseType: undefined` with the default angular plugin. It always returns patch, no matter what commit message prefix I use (or don't use):

```
{ level: 2,
  reason: 'There are 0 BREAKING CHANGES and 0 features',
  releaseType: 'patch' }
```

I can put in a fallback to `patch`, I guess, but it isn't going to be well-tested...

**Comment by evocateur** [comment]
nevermind, figured out a repro, fix incoming...

**Comment by hbetts** [comment]
> I wasn't able to repro the null level or releaseType: undefined with the default angular plugin.

I wasn't sure if you saw the `conventional-changelog-angular` code, but it always [defaults to a `patch`](https://github.com/conventional-changelog/conventional-changelog/blob/0e05028f70bbd3109e1a4b16262a9450153060de/packages/conventional-changelog-angular/conventional-recommended-bump.js#L9) release, regardless of the commit type.

I've put together my own personal configuration package that [defaults to `null`](https://gitlab.com/hyper-expanse/open-source/configuration-packages/conventional-changelog-config/blob/29d697e516b1a30aebfea8cecac29a3934022e13/src/conventional-recommended-bump.js#L9).

You can see the results of its [unit tests here](https://gitlab.com/hyper-expanse/open-source/configuration-packages/conventional-changelog-config/blob/29d697e516b1a30aebfea8cecac29a3934022e13/src/index.integration.spec.js#L59).

In any case, thank you for the fix. It's been appreciated :smile:
