### ISSUE TITLE
[Lerna 3] Cannot ping custom registry (Artifactory)

### ISSUE THREAD

**Issue by vysinsky** [lerna/lerna#1552]
## Expected Behavior

lerna publishes packages

## Current Behavior

lerna publish fails on npm registry verification

## Possible Solution

Provide and option to skip verification?

## Steps to Reproduce (for bugs)

1. Have a npm registry set to custom Artifactory registry
2. Run `lerna publish --yes`

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "lerna": "2.11.0",
  "packages": [
    "packages/*"
  ],
  "command": {
    "publish": {
      "exact": true,
      "registry": "https://artifactory.dsg-i.com/api/npm/npm-virtual/"
    }
  },
  "version": "independent"
}
```
</p></details>

## Context

The registry URL won't be available for you. We have it accessible from VPN. Also publishing worked whe I used Lerna 2.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.1 |
| `npm --version`  | 6.3.0 |
| `yarn --version` | 1.6.0 |
| `node --version` | v10.8.0 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.6 |

**Comment by evocateur** [comment]
I really wish JFrog/Artifactory would fix their shit. It's not like the public registry API is an [obfuscated proprietary secret](https://github.com/npm/npm-registry-client/blob/a55c119e50b52d35f54591a69949a746d149d39b/lib/ping.js#L14).

Anyway, time is finite and I realize bugs exist in all software. A `--no-verify-registry` option is a reasonable compromise.

**Comment by vysinsky** [comment]
Awesome. Thanks a lot! I know it is pita to fix others bugs...
