### ISSUE TITLE
Lerna 3.0.0-rc.0 to 3.0.0 caused breaking changes with split of lerna version from publish

### ISSUE THREAD

**Issue by kirbdee** [lerna/lerna#1553]
## Expected Behavior
`lerna publish` to accept version flags prior to handle version bumping publishing

## Current Behavior
have to explicitly call` lerna version` prior

## Possible Solution
This should have been considered a breaking change.

## Steps to Reproduce (for bugs)

`lerna publish --skip-npm --conventional-commits --yes`
Conventional was no longer being used

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
`lerna version --conventional-commits --yes` should work fine, is the error message not clear enough?

**Comment by kirbdee** [comment]
No that makes sense, I didn't notice it until I saw my CICD do something unexpected.

**Comment by evocateur** [comment]
That being said, we have [integration tests](https://github.com/lerna/lerna/blob/bb1cfb5faa8fd91b99e30d95b9e0551213a55c8a/integration/lerna-publish.test.js#L137-L166) that validate passing `--conventional-commits` to `lerna publish` passes it through successfully. I'll need a reproduction of your case to verify if it's an actual bug.

**Comment by kirbdee** [comment]
No worries, I've moved to 3.0.1 from the 3.0.0-rc.0 with the appropriate changes.

**Comment by evocateur** [comment]
I just realized I forgot to add a hidden `--skip-npm` yargs option to `lerna publish`, so this would indeed fail despite the internal aliasing already in place. Silly unit tests lying to me...
