### ISSUE TITLE
Does lerna support life-cicle npm scripts ?

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#1557]
Hello,

Reading documentation is not clear to me if lerna support all npm life-cicle scripts or not. I'm pretty sure it executes the pre-publish script, but I found situations where the post-publish script is not executed.

I also read something on a blog-post and on a lerna log about scripts folder, but I did not found any reference to this neither.

If there is some situation where post-publish is not executed I would love to hear when and why. If it is supposed to be executed always I'll investigate deeper and report a more focused issue.

Regards

**Comment by danielo515** [comment]
I just tested locally and when I run `lerna publish`  on the root of the repo it correctly executes all the scripts, including post-publish ones. Can it make a difference in CI environments ? Could it be related to the synchronous nature of the publish steps ?
I just activated verbose logging but I don't see anything that gives me a clue.

**Comment by evocateur** [comment]
What specific lifecycle scripts with which lerna command?

**Comment by danielo515** [comment]
The lifecycle script is post-publish and the lerna command is lernapublish.
But as I said, I executed it locally and it ran correctly. I don't know what could be different on Travis-Ci environment

**Comment by evocateur** [comment]
Yes, lerna explicitly runs the postpublish lifecycle after a package has been uploaded to the registry. I don't know why CI does not elicit the same behavior.

**Comment by danielo515** [comment]
Hello again @evocateur ,

Could you take a look at this log line ?
https://travis-ci.org/danielo515/packages/jobs/419344528#L2210

Seems that lerna is just executing a script at that path, but not the npm script.

Regards

**Comment by evocateur** [comment]
As far as I can tell (on mobile), that's a weird file-based lifecycle that basically only Babel ever used, and is only per-package, and as of v3 are opt-in with an option. They've never been run in the root of the repository.

**Comment by danielo515** [comment]
Thanks for looking at it @evocateur 
I thought it was a lerna thing. In any case, it is not run on the root what it is a problem, is te fact that it does not run the postpublish script on the package folder. I don't see any log about running it.

**Comment by evocateur** [comment]
The postpublish npm script is explicitly run in every package. A "scripts/postpublish.js" relative to a leaf package directory is only executed (via `require()`) if you pass `--require-scripts`.

**Comment by danielo515** [comment]
Hello @evocateur , I think I'm making you forget about the original problem. My package (just one) has indeed a postpublish npm script, which is not being executed. When I activated the silly log level I saw some log lines regarding executing some random post-publish script and I thought that could be interfering.

Here is my actual repository: 
  https://github.com/danielo515/packages
Particularly this package has a post-publish script:
  https://github.com/danielo515/packages/blob/master/packages/sanfu/package.json

When I run it locally, everything works as expected, that's why I have activated the silly log level on the CI env, to see what could be happening or differing. I don't understand what Is making lerna to not execute the post-publish script, but the logs show clearly that it is not doing it.

Thanks and regards

**Comment by evocateur** [comment]
Ah, sorry, this seems to be an issue with Lerna 2.x, which I really don't have bandwidth to debug right now. If this issue persists with Lerna 3.x, please re-open.

**Comment by danielo515** [comment]
If I try to upgrade to lerna v3 I get this error 

```
lerna ERR! Error: Command failed: git rev-list --left-right --count https://[secure]@github.com/danielo515/packages/master...master
lerna ERR! fatal: Invalid object name 'https'.
```

My publish command is like this:

```
  lerna publish --conventional-commits --message 'chore: Publish [skip ci] --yes --loglevel silly --git-remote https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}

```

Is something bad about it ?

**Comment by evocateur** [comment]
The `--git-remote` needs to be the name of a configured git remote (like "origin" or "upstream"), not an url.
