### ISSUE TITLE
publish: `npm pack --json` breaks npm 5 support

### ISSUE THREAD

**Issue by panjiesw** [lerna/lerna#1558]
Running `lerna publish` variants will cause error if user has npm5. This is because commit [627cfc2](https://github.com/lerna/lerna/commit/627cfc2) introduce forced `--json` npm pack flag/config, which isn't supported until npm6.

Added --json: [npm v6.0.0-next.0](https://github.com/npm/cli/blob/42a26b99761ef4017d7dd9116acf1fe972b0746d/lib/pack.js#L52)

## Expected Behavior

publish should work for npm5, or if not possible, provide documentation/warning about the requirement to upgrade to npm6.

## Current Behavior

publish error with npm5 and no documentation or warning about the npm6 requirement. Upgrading npm to v6 solve the problem

## Possible Solution

Provide documentation/warning about the requirement to upgrade to npm6 if it's not possible to support npm5

## Steps to Reproduce (for bugs)

1. Run `lerna publish` in a lerna project (any npm client)
2. Publish fail complaining about JSON error in `npm-publish.js`

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "lerna": "3.0.3",
  "version": "1.0.0-pre.0",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "packages": [
    "dev-packages/*",
    "packages/*",
    "examples/*"
  ],
  "command": {
    "run": {
      "stream": true
    }
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
Sorry to redact this, as this's still an internal project. I still include the important portion here

30 info publish Publishing packages to npm...
31 silly getCurrentSHA
32 verbose getCurrentSHA 985720efd8adde836a4d9ddf699ff9f92ee4eb58
33 verbose pack [ '@rcms/logger', '@rcms/types' ]
34 silly getExecOpts /home/panjiesw/dev/workspaces/srin/rcms undefined
35 silly exec npm [ 'pack',
35 silly exec   '/home/panjiesw/dev/workspaces/srin/rcms/packages/logger',
35 silly exec   '/home/panjiesw/dev/workspaces/srin/rcms/packages/types',
35 silly exec   '--json' ]
36 error SyntaxError: Unexpected end of JSON input
36 error     at JSON.parse (<anonymous>)
36 error     at proc.then (/home/panjiesw/dev/workspaces/srin/rcms/node_modules/@lerna/npm-publish/npm-publish.js:97:27)
36 error     at <anonymous>

```
</p></details>

## Context

I'm trying to publish packages using `lerna publish`

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.3 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.9.2 |
| `node --version` | 8.11.3 |

| OS | Version |
| --- | --- |
| Manjaro | 17.1.11 |

**Comment by evocateur** [comment]
Whoops, sorry, I completely missed that.

**Comment by panjiesw** [comment]
So which one is it? Is lerna only support latest NPM?

**Comment by evocateur** [comment]
I put the bug tag on this issue, and I've already spent time thinking about how to fix it. I did not intend to break npm5. Have patience, please.

**Comment by panjiesw** [comment]
thanks @evocateur! Didn't mean to rush, I just missed the bug tag intention.

Also if you don't mind, I encountered some more bugs in v3 still regarding publish but with yarn, so I'll submit some more issues after creating the repro.

**Comment by evocateur** [comment]
@panjiesw Thanks!

**Comment by evocateur** [comment]
(Also, thank you for the feedback, I will be clearer in the future with my intention to fix!)
