### ISSUE TITLE
Update versions in yeoman generators

### ISSUE THREAD

**Issue by doug-wade** [lerna/lerna#156]
We over at [React Server](https://github.com/redfin/react-server) have a [Yeoman generator](http://yeoman.io/) that lives in our repository and generates boilerplate for new projects.  We're [having trouble](https://github.com/redfin/react-server/pull/181/files) keeping the versions in the _generated_ package.json up-to-date with the rest of our monorepo.  It would be great if lerna also updated `package.json`s (or maybe some other sigil file, like `_package.json`, to prevent confusion) that are descendants of `/packages`, but not in `node_modules`.  It may also help with [babel init](https://phabricator.babeljs.io/T6956).

**Comment by thejameskyle** [comment]
I'm not entirely sure what you mean by this, what's the behavior you want from lerna?

**Comment by doug-wade** [comment]
When we run `lerna publish`, I'd like to see [these dependency versions](https://github.com/redfin/react-server/blob/master/packages/generator-react-server/generators/app/templates/package.json#L18) updated as well.

**Comment by hzoo** [comment]
Basically update a `package.json` that isn't in the top level of `packages`?

**Comment by doug-wade** [comment]
From a user's perspective: yeah, basically.

Thinking about the implementation, though, its slightly more complicated than that, since there are a lot of other `package.json`s that you wouldn't want to search and update

```
dougwade react-server/packages ‹react-server-cli-help*› » find . -name package.json -type f | wc -l
4091
```

My ideal algorithm for updating versions would be to start at lerna.json and for each subdirectory except `node_module`s, check for a `package.json` and update it if it is found, then recurse on each subdirectory.

Then, for the following project
```
bar/
    node_modules/
        dep/
            package.json
    package.json
packages/
    foo/
        node_modules/
            dep/
                package.json
        package.json
    generator-foo/
        node_modules/
            dep/
                package.json
        templates/
            package.json
        package.json
lerna.json
```
on publish, lerna would update `bar/package/json`, `packages/foo/package.json`, `packages/generator-foo/package.json`, and `packages/generator-foo/temlpates/package.json`, but would not update `bar/node_modules/dep/package.json`, `packages/foo/node_modules/dep/package.json`, or `packages/generator-foo/node_modules/dep/package.json`

**Comment by gigabo** [comment]
The `package.json` template in a yeoman generator can't be treated like other packages.  It doesn't have a fixed package name.  It can't be depended on by anything else in the monorepo, but it can _depend_ on others.

I don't actually have a good idea for a general-case solution.  It would be nice to have the dependencies updated automatically by lerna, but it's kind of a special case.  I would guess that we won't be the last project to run into this, though, given the popularity of `yo`.

**Comment by thejameskyle** [comment]
I don't think we should get away from the defined structure of the repo, that adds a complexity to the project. Instead I think we should enable you to build it on your own if you really wanted to. I don't see why you would *need* to though.
