### ISSUE TITLE
Add ability to duplicate changelog entries in multiple packages without needing to touch files.

### ISSUE THREAD

**Issue by fenduru** [lerna/lerna#1562]
## Expected Behavior

In my monorepo I have two libraries, one using Angular.js and one using Vue. They share a majority of their logic in a third package called `core`. Often when fixing a bug, we only need to change files in the `core` package, however since the angular/vue files weren't touched as part of the fix, the messages don't show up in the respective changelogs.

In a non-monorepo workflow, I would update my `package.json` to bump the required version of `core`, and that commit would include a message about the fixes. However with Lerna, that bump/commit is handled automatically so I have no hook to manually enter a changelog message.

It would be great if there was some syntax we could use in a commit message to tell Lerna to copy that message to dependent packages. For instance, I would write a commit message for a change in `core` like the following (syntax pending):

```
fix(myfeature): properly implement myfeature

LERNA_INCLUDE_IN_ALL_CHANGELOGS
```

This would include the message in the changelog for `core`, as well as all downstream consumers (though it could still be omitted from other packages that don't consume the package)

## Current Behavior

Currently features work fine, as they almost always are accompanied by documentation changes and/or manual exposing of APIs, however bug fixes typically don't change either of these. Often a consumer will ask "what version was bug 123 fixed in?", since they want to interface with the specific package they're consuming (not my core package that is essentially an implementation detail). Not only is this a bad experience for them, but then I must find the version of `core` that contained the change, and correlate that to the corresponding dependency bump in the actual package.

## Possible Solution

Some sort of marker in the commit message seems in line with other ways of communicating with Lerna re: changelogs. I'm interested in contributing this feature if there's an agreed upon strategy to go forward with.

**Comment by evocateur** [comment]
There's a long-standing TODO in the current `--conventional-commits` implementation to [replace](https://github.com/lerna/lerna/blob/0dea7f4ce7cc226acf7ffca27a39a960d1975499/core/conventional-commits/lib/make-bump-only-filter.js#L14-L15) the "Version bump only" message in a dependent package with an actual list of relevant changelog messages from the dependencies. Despite what the comment a few lines above the linked code says, whether or not `--force-publish` is involved is kinda irrelevant, it happens for all dependent packages that are bumped when their dependency (one or often more) has changes. The bump filter is called from the `writeChangelog()` promise chain [here](https://github.com/lerna/lerna/blob/0dea7f4ce7cc226acf7ffca27a39a960d1975499/core/conventional-commits/lib/update-changelog.js#L61).

It should definitely be marked with some sort of heading to distinguish it (`### Dependency Updates`?), but I don't think this sort of functionality needs another CLI option to guard against it (YAGNI, imo).

One complicated factor (and the reason we basically gave up when implementing it at first) is that the [calling code](https://github.com/lerna/lerna/blob/0dea7f4ce7cc226acf7ffca27a39a960d1975499/commands/version/index.js#L378-L393) in `lerna version` would need to be turned into a two-pass loop (one pass to generate all the changelogs without writing, another to knit the dependencies' changes into the dependents' changelogs, and then write it all). Maybe that's three loops, I dunno. It arguably means splitting `updateChangelog()` into (at least) two methods, perhaps `generateChangelog()` and `writeChangelog()`?

I don't think we need a special keyword in the message itself, we should just stick to what `conventional-changelog-core` gives us.

**Comment by fenduru** [comment]
I think it may be useful in some scenarios to always list dependency updates, but I fear that a majority of them would be noise, and only a small number of them would be relevent to my end users. For instance, a feature or fix that is only visible internally should not end up in the user-facing changelog IMO.

Another idea could be to say something like "A change that is a `fix` that has a `fixes #9999` in the commit message should be included in all dependents". I would advocate against including `feats`, as like I mentioned above those typically need to be exposed through API surface and/or documentation. For instance if I add a `feat` to my `core` package, but only expose it to my `vue` library, I don't want that showing up in the `angular` changelog as it is not truly there.

This is a very real example for me, FWIW, as we are beginning to migrate from Angular to Vue, and new features may not land in both, however we will be doing as much work as possible in a shared package to avoid duplication during this transition.

**Comment by evocateur** [comment]
It sounds like most of the requirements for your use case could be fodder for a [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) preset passed to lerna, not a lerna logic change (except for figuring out how to transfer transitive dependency changes). Most of the `--conventional-commits` functionality is just passing flags to various conventional-changelog utilities.

**Comment by fenduru** [comment]
@evocateur thats a good idea - do you know which piece of the lerna + conventional-changelog puzzle is responsible for deciding whether or not a commit applies to a particular package's changelog? (i.e. the one that currently checks "was a file in the subfolder touched in this commit").

**Comment by evocateur** [comment]
I usually start digging into presets by examining [conventional-changelog-angular](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular), which is a pretty robust and feature-ful example of a conventional-changelog preset (it's what lerna defaults to, in fact). [conventional-changelog-writer](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-writer) documents a lot of the significant configuration properties, and also provides a decent example of basic preset [templates](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-writer/templates).

**Comment by evocateur** [comment]
[Here](https://github.com/lerna/lerna/blob/fc771d97bfce5fd72373b79ce4498d75a9a48a77/core/conventional-commits/lib/update-changelog.js#L45-L54) is where lerna configures `conventional-changelog-core` to detect changelog messages for a given package location. There's not a lot there, which is why I suggested a custom preset to make deeper changes to its output.

**Comment by fenduru** [comment]
Hmm - looks like the options for `git-raw-commits` is pretty rudimentary and only takes a folder which Lerna always passes. So even if `git-raw-commits` had more options, it looks like it might be too late at that point.

I'm going to think on this one, but I generally agree that my actual logic would fit very nicely into a changelog preset. If that requires any Lerna changes to support I suspect they'd be minor and I'll file a PR.
