### ISSUE TITLE
`lerna publish` fails at npm-publish

### ISSUE THREAD

**Issue by teddybradford** [lerna/lerna#1563]
After running `lerna publish` and specifying new versions for my packages, lerna successfully pushes tags and then begins to publish a package to npm, but fails during the process:

```
? Are you sure you want to create these versions? Yes
lerna info git Pushing tags...
lerna success version finished
lerna info publish Publishing packages to npm...
ui-5.0.3.tgz░░⸩ ⠦ npm pack: verb getCurrentSHA e8c28518e4a10f8613f6cba317a6d62bee2f330e
lerna ERR! SyntaxError: Unexpected end of JSON input
lerna ERR!     at JSON.parse (<anonymous>)
lerna ERR!     at proc.then (/ui/node_modules/@lerna/npm-publish/npm-publish.js:96:27)
lerna ERR!     at <anonymous>
lerna ERR! lerna Unexpected end of JSON input
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.3 |
| `npm --version`  | 6.3.0 |
| `node --version` | v8.11.2 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.6 |

**Comment by Kikobeats** [comment]
I'm experimenting the same problem under node 10


Executable | Version
-- | --
lerna --version | 3.0.2
npm --version | 6.2.0
node --version | v10.8.0

**Comment by evocateur** [comment]
Can you try the latest version? I shifted some stuff around and it should now deal with empty JSON output better...

**Comment by teddybradford** [comment]
@evocateur It's working for me now. Thank you! 🙂

**Comment by evocateur** [comment]
Thanks for checking!

**Comment by visormatt** [comment]
Working for me as well 💯 also digging the additional logging 👍
