### ISSUE TITLE
lerna version --conventional-commits bumping non impacting commits

### ISSUE THREAD

**Issue by kirbdee** [lerna/lerna#1569]
## Expected Behavior

It's tedious to maintain a long list of --ignore-changes

## Possible Solution

While lerna has [--ignore-changes](https://github.com/lerna/lerna/tree/master/commands/version#--ignore-changes), it can be tedious to maintain with a large number of packages, within a package there could be various scripts and folders for tests/helper/utils etc. which could also vary between packages.

I'd like to request something along the lines off `--explicit-include-changes`. It would be nice to be able to explicitly tell lerna to watch for changes for a smaller set of constant files/folders to be tracked.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.1 |
| `npm --version`  | ^5 |
| `yarn --version` | VERSION |
| `node --version` | ^8 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
A list of globs in lerna.json isn't sufficient? How often do these sorts of things actually change?

```json
{
  "version": "independent",
  "ignoreChanges": [
    "**/__fixtures__/**",
    "**/__tests__/**",
    "**/*.md"
  ]
}
```

**Comment by kirbdee** [comment]
The issue I have with this is that if a package suddenly includes a build item or folder this list would need to be updated. If it ends up getting merged lerna would see it as a change.

Ideally I'd like to be able to target pretty much 1 directory.

Perhaps I'll try to ignore all except a specific named folder.

**Comment by kirbdee** [comment]
What I meant for build item, I meant more that each package could have its own toolkit for its build processed, including varied directories and scripts, and not actual artifacts or temp files.

While I could see for new packages we could enforce a practice to use a particular structure, migrating existing packages could still fall into this use case.

ie
```
packageA/
  builder/
  src/
packageB/
  bundler/
  src/
packageC/
  build.js
  source/
```
in this scenario I'd like to include `src` and `source` pattern matching

**Comment by evocateur** [comment]
If changes to build tools affect package output, I would say that's very relevant for versioning. Any package migrated to a monorepo should take the opportunity to move its tooling to the root, and any package that "can't" do that shouldn't be in a monorepo in the first place.

**Comment by kirbdee** [comment]
Moving to the root seems counter intuitive for independent packages, and lerna provided `lerna exec` to be able to be agnostic and to allow each package to define a script in package.json to interface with, aka`build` and `test` which has worked really well for the projects, and doesn't care how the build or any other util scripts are structured.

What I'm ultimately struggling with / trying to do really is around the --conventional-commits portion, 

Where I had a previous issue around why things like a commit w/ chore, test, style etc. which shouldn't get considered for a version bump, was bumping the package as a patch.

**Comment by kirbdee** [comment]
Additionally when something like a chore commit bumps the version of the package, all the packages dependent on it would also get affected.

**Comment by kirbdee** [comment]
It looks like this is what's causing the forced patch

https://github.com/lerna/lerna/blob/e330f6f3d91702e8e43d3697f5c68214c89693e1/core/conventional-commits/lib/recommend-version.js#L34-L36

from the actual convetional-commits recommendation undefined is a valid item since it doesn't fall into one of the normal categories. Which then not bump the version

conventional-commit-angular:
https://github.com/conventional-changelog/conventional-changelog/blob/d3eaacfe642eb7e076e4879a3202cc60ca626b59/packages/conventional-changelog-angular/conventional-recommended-bump.js

this would return level 0 for a "chore" or "style"

conventional-changelog:
https://github.com/conventional-changelog/conventional-changelog/blob/d146bdc0e64d90bd04dc361e8602576bc95f36dc/packages/conventional-recommended-bump/index.js#L78-L79

this would return undefined for releaseType.

not sure the reasoning for the forced patch in the lerna usage, but this seems like a bug / unintended check.

**Comment by kirbdee** [comment]
Testing it with 3.0.1 Prior to the defaulting, seems to still default to a patch type release. :slightly_frowning_face:

**Comment by kirbdee** [comment]
Digging deeper. Lerna is doing as intended. And seems that the conventional lib doesn't have a non bumping level as initially thought.

I thought in the level item being 0 would be because it was able tosee things like "chore" or "test" in some definition when parsing the notes. but notes ends up being empty from the parser...

```
{ type: 'test',
  scope: 'common',
  subject: 'update test ',
  merge: null,
  header: 'test(common): update test',
  body: null,
  footer: null,
  notes: [],
  references: [],
  mentions: [],
  revert: null,
  hash: '****' }
```

**Comment by kirbdee** [comment]
I think the solution on my side would actually be on having my own changelog-preset, and tell lerna the proper "release".

How does: `lerna version --conventional-commits --changelog-preset angular-bitbucket` work for a local preset?

**Comment by kirbdee** [comment]
That still doesn't seem to do what I'm after since the `semver.inc` would always be called, and throws and error.

I'm wondering what your thoughts would be on only calling that for a `semver.valid(release)` item?
The idea around this would be able to support the non impacting conventional commits, with a `noop` recommendation.

**Comment by evocateur** [comment]
Sorry, I didn't clarify that `--conventional-commits` is used by lerna to decide version numbers and generate changelogs _only_. That is, it does **not** use `conventional-changelog-core` to decide _what_ changed. That is decided by [collect-updates](https://github.com/lerna/lerna/blob/master/utils/collect-updates/collect-updates.js), using git tags and some [fancy diffing](https://github.com/lerna/lerna/blob/master/utils/collect-updates/lib/make-diff-predicate.js).

#707 explains why the dependents get bumped when a dependency has a recognized change. Globs provided to `--ignore-changes` are the only way to filter what `collect-updates` recognizes.

**Comment by kirbdee** [comment]
Yea that makes sense, but within the `recommend-version.js` shouldn't we be able to handle the version to use vs having `semver` manage the bump based on the releaseType? since semver itself doesn't cover some of the "non impacting" changes prescribed by `conventionalcommits.org`

```
commit types other than fix: and feat: are allowed, for example commitlint-config-conventional (based on the the Angular convention) recommends chore:, docs:, style:, refactor:, perf:, test:, and others. We also recommend improvement for commits that improve a current implementation without adding a new feature or fixing a bug. Notice these types are not mandated by the conventional commits specification, and have no implicit effect in semantic versioning (unless they include a BREAKING CHANGE, which is NOT recommended). 
```

Which states its not necessarily mandated, so thinking a change-log preset should have more control over what version it would tell lerna to use?

**Comment by evocateur** [comment]
I just explained what lerna does and _does not_ use conventional commits for. To repeat, it _does not_ use conventional commits to detect changes.

Lerna _will_ never do that, to be absolutely clear.

**Comment by kirbdee** [comment]
I got that lerna detecting changes is decoupled from conventional-commits is telling what version should be used.

What I was asking is on the version itself now. The `recommend-js` in the lerna core:

https://github.com/lerna/lerna/blob/e330f6f3d91702e8e43d3697f5c68214c89693e1/core/conventional-commits/lib/recommend-version.js#L29-L39

Shouldn't this be allowed to be configureable to actually tell lerna the version vs defaulting to using `semver.inc()`?

per the conventionalcommits lib anything not part of the normal release scheme should be allowed to be managed at your own discretion

So currently if I plugin my own changelog-preset and return a release type 'customRelease', semver would fail.

Aside:
I also looked at seeing if i can hook into using `lerna version [explicit version]` but there wasn't a way to scope it

**Comment by hbetts** [comment]
@kirbdee for clarification, you want to modify a source file, perhaps with documentation or style changes, but you **don't** want to publish the changes as a new version?

In that case, there's no alternative other than to **not** run `lerna version` when you know that you only have style or documentation related changes.

**Comment by kirbdee** [comment]
So --ignore-changes doesn't work for me and wanted to rely more on the conventional-commit to tell lerna essentially to **not** bump the version. but the current core in lerna always defaults to "patch"

if i run `lerna version --conventional-commits --changelog-preset someplugin` I'd like it to be able to follow the recommendation it was given.

if I commit "doc(package1): cleaned up comments" and per conventional-commit this shouldn't be a patch.

But again per above, I think it might be handy to be able to configure/plugin the "version recommender" vs defaulting to using the semver.inc which doesn't have the concept of a "non impacting commit"
