### ISSUE TITLE
Fails on Node 0.10 - child process has no method 'execSync'

### ISSUE THREAD

**Issue by nolanlawson** [lerna/lerna#157]
Running `lerna bootstrap`, I get this error:

```
/Users/nolan/workspace/pouchdb/node_modules/lerna/lib/ChildProcessUtilities.js:37
      return _child_process2.default.execSync(command, {
                                     ^
TypeError: Object #<Object> has no method 'execSync'
```

Seems `execSync` did not exist in 0.10. It works in 0.11.

Not sure if we actually want to fix this, or if we just want to say that Lerna only supports Node 0.11+.

**Comment by hzoo** [comment]
We can do a check like `if (!child_process.execSync) { }` and use https://www.npmjs.com/package/sync-exec?

**Comment by hzoo** [comment]
Lol that's why circleci failed for babel (since we are running 0.10 on it)
