### ISSUE TITLE
How to ignore node_modules of internal dependencies on bootstrapping packages

### ISSUE THREAD

**Issue by liliom55** [lerna/lerna#1571]
First thank you for the nice mono repo manager. I'm working on angular applications as my packages.For internal dependencies when the package1 is install in "node_module" of package2, if it( package1 ) includes "node_modules", I get an error that mentions like this "not found index.ts " and after adding it in tsConfig.json I face another issue "No NgModule metadata found for 'AppModule'" ( when I'm trying to run the app or build it ) but if I remove "node_modules" folder from package2/node_modules/@MyPackages/package1/**node_modules** , every thing is fine. So how can I ignore "node_modules" of internal dependencies on bootstrapping packages?

## Environment
"@angular/core": "^6.1.2",
"@angular/cli": "^6.1.3",
"typescript": "~2.9.2"

| Executable | Version |
| ---: | :--- |
| `lerna --version` | ^2.11.0|
| `npm --version`  | 5.6.0|
| `node --version` | v8.11.3|

| OS | Version |
| --- | --- |
| Windows7| |

**Comment by evocateur** [comment]
This looks like a TypeScript or Angular bug, not Lerna.

One thing to note is that lerna manages npm packages, not magical ng-packagr artifacts. Wherever your leaf package.json's [`main`](https://docs.npmjs.com/files/package.json#main) property points to is where node will resolve `import` (or `require()`) paths.

**Comment by liliom55** [comment]
Your right. Because after I upgrade angular from 5 to 6, this issue appeared. But can I bootstrap the internal packages while ignore "node_modules" folder in Lerna? because this approach is going to solve my issue. Right now I'm doing manually

**Comment by evocateur** [comment]
I'm afraid I don't understand what you mean by "bootstrap internal packages while ignoring `node_modules`".

**Comment by liliom55** [comment]
Actually the packages that I'm work on them they are runnable application as well, and I face the issue only when I want to run each packages. I think there is nothing that Lerna can do for me because the concept of Lerna is deferent as my expectoration. Lerna Only creates a shortcut of each internal dependencies. Thanks again for your quick response.

**Comment by evocateur** [comment]
Ah, yes, that sounds like it. Happy to help clarify usage expectations.

**Comment by liketurbo** [comment]
> You're right. Because after I've updated application from angular5 to 6, this issue appeared. But can I bootstrap the internal packages while ignore "node_modules" folder in Lerna? because this approach is going to solve my issue. Right now I'm doing manually

@liliom55, So how you fixed it? cause I got same error and for now I'm fixing it by removing node_modules manually
