### ISSUE TITLE
How symlink packages/* to the root-project's node_modules

### ISSUE THREAD

**Issue by zygeilit** [lerna/lerna#1580]
I have a project managed by “monorepo”, but the usage mode is different with the common usage in Babel or React. This is my project’s [directory structure](http://lc-cj3ctxdw.cn-n1.lcfile.com/392d00519ed8b8ffb9de.png).

Source code in “src”, components/* and utils/* are independent of npm modules,   index.js and dll-config.js  are the project’s page-index and config. 

This is my [learn.json](http://lc-cj3ctxdw.cn-n1.lcfile.com/36d07d5b6210a6b06111.png).

After this config i can debug the module witch in packages/* normal，but there also have some other code can not debug, like index.js and dll-config.js. So I want find a way to link the modules in packages/* and the root-project’s node_modules. I don’t want to put the root-project into packages/*  either. Is there have any API or config can do this?

The root-project is the "assess-components" in [directory structure](http://lc-cj3ctxdw.cn-n1.lcfile.com/392d00519ed8b8ffb9de.png).

Thank you very much. I look forward to your reply.

**Comment by evocateur** [comment]
The only way you can depend on something in Node is to add them as dependencies in package.json. Lerna doesn't change that.

You can use relative `file:` specifiers in the root to expose the requires to non-package code. Run `lerna link convert` to migrate. (And remove "useWorkspaces" from lerna.json, you're not actually using Yarn as far as I can tell)

**Comment by zygeilit** [comment]
Thank you very much for your reply. 

Very nice, the npm `local paths`(`"foo": "file:./foo"`) solved my problem. But after `lerna publish` I found a [unexpect git commit](http://lc-cj3ctxdw.cn-n1.lcfile.com/8b5e75aeb09f387e2b5f.png). Is there a way to replace `"file:../../*"` back to last version after `lerna publish`?

Thank you very much. I look forward to your reply.

**Comment by evocateur** [comment]
You don't need to re-run `lerna link convert` after the first time. Once run, you don't need to run `lerna bootstrap`, as `npm install` will do it all for you. The git change is expected when you run `lerna link convert`.

When publishing with relative `file:` specifiers, they are automatically replaced with the resolved version range. The source will be versioned with the relative paths, however.

**Comment by zygeilit** [comment]
I used `lerna link covert` command, all modules linked with `file:`. Then I  exec `npm install` in the root porject, but only the root project installed dependencies in [`node_modules`](http://lc-cj3ctxdw.cn-n1.lcfile.com/56563925fbaaa93bb933.png). 

How exec `npm install` in every modules witch configured in [lerna.json](http://lc-cj3ctxdw.cn-n1.lcfile.com/dca6f9e2776d802bae7e.png) automatically ? If not, I need `cd` every modules and exec `npm install`.

This is a sub-module's [package.json](http://lc-cj3ctxdw.cn-n1.lcfile.com/c094a9668619317885ff.png), there have some dependencies need to be installed before debug it. If do not exec `npm install`, there will be an [error](http://lc-cj3ctxdw.cn-n1.lcfile.com/397bf20e441ac13fc06f.png) when debug it.

**Comment by zygeilit** [comment]
I use the yarn client `npmClient, useWorkspaces`, want to install root and all packages/* dependencies automatically. And use yarn `link:` too, because if use `file:` yarn did not link all modules.

But there is a performance problem when use yarn's `link:`.  I gave up this plan.

Now, I use `lerna exec -- npm install` before exec `npm install` in root.

Do you have a better plan?

**Thank you very much. I am looking forward to your reply.**

**Comment by evocateur** [comment]
Like I said, use npm, `npm install` once in the root. That's all you need when using relative file specifiers. `lerna link convert` sets it all up.

**Comment by zygeilit** [comment]
Sorry, only `npm install` in the root after `npm link convert`, did not work. See [here](http://lc-cj3ctxdw.cn-n1.lcfile.com/f6d64b973ca598c47554.png).
After `npm install` in the root, the sub-modules's dependencies neither installed `independent` nor `hoisted` in the root.

**Comment by evocateur** [comment]
independent is irrelevant. you need to depend on your modules from the root package.json as relative `file:` specifiers. The leaf nodes should not have lockfiles. I can't help you any more.
