### ISSUE TITLE
How use --no-push option in lerna.json

### ISSUE THREAD

**Issue by zygeilit** [lerna/lerna#1585]
Use --no-push option in shell-command, its ok. But use it in lerna.json, not work. 
[lerna.json](http://lc-cj3ctxdw.cn-n1.lcfile.com/26f7fcd6e8036f39cdde.png)

**Comment by evocateur** [comment]
The `--no-` prefix means it's a [boolean negation](https://github.com/yargs/yargs-parser#boolean-negation), which means you use the camel-cased name without "no":

```json
{
  "command": {
    "version": {
      "push": false
    }
  }
}
```

**Comment by zygeilit** [comment]
Thanks a lot
