### ISSUE TITLE
Why the root manifest has local dependencies with `file:` specifiers, the lerna bootstrap just install root dependencies ?

### ISSUE THREAD

**Issue by zygeilit** [lerna/lerna#1587]
Why the root manifest has local dependencies with `file:` specifiers, the `lerna bootstrap` just install root dependencies ?

I saw the source code there [@lerna/bootstrap](http://lc-cj3ctxdw.cn-n1.lcfile.com/8546c4c0441031a09666.png)

I want to use `"file:./some-module"` in the root-project's package.json to debug root-project code. Use `lerna bootstrap` to install and link all modules in packages/* to debug sub-module.

Now, I blocked with [this code](http://lc-cj3ctxdw.cn-n1.lcfile.com/8546c4c0441031a09666.png), I don't know how to do that, can you gave me some help ?

This is the relevant [Issue](https://github.com/lerna/lerna/issues/1580), you tell me use `lerna link convert`, the npm `local paths`.

Thank you very much. I look forward to your reply.

**Comment by evocateur** [comment]
As I explained in the linked issue, `npm install` is all that is necessary after converting to relative `file:` specifiers. `lerna bootstrap` is not needed anymore.

If you have build steps in npm script lifecycles ("prepublish", "prepare", etc) that were executed by `lerna bootstrap`, you should run them in a root `prepare` lifecycle, which is automatically run after `npm install`.
