### ISSUE TITLE
After lerna link convert, how npm install in all packages/* ?

### ISSUE THREAD

**Issue by zygeilit** [lerna/lerna#1588]
Thank you very much for your previous reply.

I understand two things：
* When publishing with relative file: specifiers, they are automatically replaced with the resolved version range.
* after `lerna link convert`, don't need to run `lerna bootstrap` anymore.

But I still have a question, it may be the last one.

**The question is:**

When i converted(`lerna link covert`), then i use `npm install` in the root-project, but only the root-project installed `node_moduels`, the remaining submodules whitch defined in the lerna.json [`"packages"`](http://lc-cj3ctxdw.cn-n1.lcfile.com/7a411ad4383d13c6595e.png) are not, do I need to install it manually ( goto all modules and exec `npm install` )?

**Thank you very much. I am looking forward to your reply.**

**Comment by evocateur** [comment]
No, they are all dealt with by the root `npm install`. This takes advantage of the [`node_modules` resolution algorithm](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders).

**Comment by zygeilit** [comment]
Thank you all for your reply.
