### ISSUE TITLE
Improve support for bundling/deploying individual packages as self-contained, minimal-footprint bundles.

### ISSUE THREAD

**Issue by ajhool** [lerna/lerna#1589]
Improvement Request.

We use a monorepo that contains microservices designed for a serverless architecture. Ideally, each microservice (aka package) could be deployed to AWS Lambda or GCP Functions with a minimal code footprint. Hoisting is useful for development, building, and testing, but makes it difficult to find and bundle the dependencies that each individual microservice needs.

## Expected Behavior
If this functionality is currently supported, it would be helpful to provide a `deploy` section in the README that would make deploying microservices a first-class feature, alongside publishing. If the functionality is not currently supported, it would be helpful to provide a `lerna bundle` command that would bundle each individual package into a self-contained, deployable zip file.

## Current Behavior
As far as we can tell, lerna does not support building a self-contained, minimal footprint code bundle for each individual package.

## Context
We would like to use a monorepo to organize a serverless architecture. We use a build server that triggers on git pushes. The build server will retrieve the entire monorepo but should be able to push minimal code to AWS Lambda. The build server does have R/W access to privately scoped npm repos.

## Your Environment
Ubuntu
AWS Lambda
Typescript 3.0 (project references)

**Comment by evocateur** [comment]
Lerna manages the versioning and publishing of multiple npm packages in the same git repository. Period.

> bundle each individual package into a self-contained, deployable zip file

This is literally what `npm publish` does. Why not just install each published package in separate directories and archive that?

Better still, use the [`bundledDependencies`](https://docs.npmjs.com/files/package.json#bundleddependencies) field of the microservice package.jsons to delineate what dependencies should be included in the packed tarball. Then you can "deploy" the package wherever.
