### ISSUE TITLE
version: ENOGIT error in CI

### ISSUE THREAD

**Issue by randy-askin** [lerna/lerna#1595]
## Expected Behavior
In previous versions (v2, v3-beta), the `--skip-git` command worked as expected.

## Current Behavior
In v3+, even if we move to the new `--no-git-tag-version --no-push` flags specified in the deprecation message, our CI is failing on the `ENOGIT` error [here](https://github.com/lerna/lerna/blob/master/commands/version/index.js#L87-L89).

## Possible Solution
Should [this if check](https://github.com/lerna/lerna/blob/master/commands/version/index.js#L104-L108) be moved up in the code so that ENOGIT/ENOCOMMIT/ENOTALLOWED aren't triggered when the `--no-git-tag-version --no-push` flags are used?

## Steps to Reproduce (for bugs)
1. We are using `lerna version x.y.z --no-git-tag-version --no-push && lerna publish --yes`
2. ENOGIT error causes CI job to fail

<details><summary>lerna.json</summary><p>

```json
{
	"packages": ["packages/*"],
	"version": "0.0.19-rc.3",
	"command": {
		"init": {
			"exact": true
		}
	},
	"lerna": "3.1.1"
}
```
</p></details>

## Context
We are trying to use the skip git functionality because Jenkins/Maven take care of that in our company's CI process.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | worked in 3.0.0-beta.21 with `--skip-git`, broken in 3.0+ |
| `npm --version`  | 6.3.0 |
| `yarn --version` | n/a |
| `node --version` | 8.5.0 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.6 |

**Comment by evocateur** [comment]
`--skip-git` was the worst-named option because _it **never** skipped **all** git operations_, only `git commit`, `git tag`, and `git push`.

The ENOGIT error code should have been EDETACHED or something, cuz git obviously exists, you're just in a detached HEAD. `git checkout -B "${GIT_BRANCH#origin/*}" "${GIT_BRANCH}"` fixes that in Jenkins.

> We are trying to use the skip git functionality because Jenkins/Maven take care of that in our company's CI process.

Take care of ...what? Creating the commits and tags? That seems odd to me.

It's unclear why you're chaining `lerna version x.y.z --no-git-tag-version --no-push && lerna publish --yes` when you could just call `lerna publish x.y.z --no-git-tag-version --yes`?

(`--no-push` is implied by `--no-git-tag-version`)

**Comment by yorch** [comment]
We have the same problem, using Jenkins to publish to our NPM registry and something like:

```
lerna publish
        --exact
        --no-git-tag-version
        --no-push
        --yes
        --npm-tag=latest
        --force-publish=*
        $BUMP
```

We don't care that we are in a detached HEAD, we don't need to push changes to Git as in our current process it causes us other problems, so we just don't keep the versions on Git but somewhere else.

What's the point the Detached HEAD validation if we are not gonna commit / push changes to it?

**Comment by evocateur** [comment]
How do you expect lerna to otherwise detect what has changed, and thus needs to be published? Magic?

**Comment by randy-askin** [comment]
Apologies if the original issue was poorly worded, our team was very new to Lerna and Jenkins at the time and weren't quite sure _what_ we were trying to achieve. We were able to get our setup working a while back. We now use `lerna version` locally for all of the versioning and tagging (which is much easier with the interactive prompt for independent versioning and things), and just let Jenkins take care of the `lerna publish from-git` part.

**Comment by TimoWestland** [comment]
We ran into the same issue as well, our CI setup is very similar. We trigger it by creating a release in github and this a git tag. We want this version to be used as the version for lerna version and we do a force-publish=* on all packages. So besides skipping git commit, tag and push we would also like lerna to skip any checks on git HEAD, as we don't require it to check what has changed in our packages (we provide the version from git and force-publish all).

A flag to disable this behavior as well would be much appreciated as it prevents us to do `git checkout master` which is currently the only fix I could find.

**Comment by evocateur** [comment]
@TimoWestland If you're not using lerna to create the tagged release, and thus the package.json changes, I don't know what to tell you. A GitHub release tag isn't sufficient, you need to run `npx lerna version $BUMP --force-publish` (one reason I don't like `--force-publish` is that it looks silly in this context, you're not actually publishing when running `lerna version`). Then you call `npx lerna publish from-git --yes` in CI to publish the lerna-tagged packages.
