### ISSUE TITLE
lerna version prerelease/preminor --no-preid  or --preid="" are not working

### ISSUE THREAD

**Issue by sergiohgz** [lerna/lerna#1598]
From a monorepo with stable version (X.Y.Z), when running `lerna version` with `--no-preid` or `--preid=""`, it still uses default preid (`alpha`).

## Expected Behavior
With `lerna version prerelease --no-preid` or `lerna version prerelease --preid=""`:
> @sergiohgz/pkg1: 1.0.0 -> 1.0.1-0
> @sergiohgz/pkg2: 1.0.0 -> 1.0.1-0

With `lerna version preminor --no-preid` or `lerna version preminor --preid=""`:
> @sergiohgz/pkg1: 1.0.0 -> 1.1.0-0
> @sergiohgz/pkg2: 1.0.0 -> 1.1.0-0

## Current Behavior
With `lerna version prerelease --no-preid` or `lerna version prerelease --preid=""`:
> @sergiohgz/pkg1: 1.0.0 -> 1.0.1-alpha.0
> @sergiohgz/pkg2: 1.0.0 -> 1.0.1-alpha.0

With `lerna version preminor --no-preid` or `lerna version preminor --preid=""`:
> @sergiohgz/pkg1: 1.0.0 -> 1.1.0-alpha.0
> @sergiohgz/pkg2: 1.0.0 -> 1.1.0-alpha.0

## Possible Solution
I cannot find where `--no-preid` is accepted as an option (as `--nopreid` is rejected as option by `yargs`), but if that is provided, the default preid should be `undefined` , not `"alpha"` string.
The solution for `--preid=""` is having an extra control of the `preid` option defined at [this line](https://github.com/lerna/lerna/blob/master/commands/version/index.js#L196), because an empty string is a falsy value and continue to next possible option.

## Steps to Reproduce (for bugs)
Notes: the use of `--force-publish` option is for testing purposes
1. lerna version prerelease --no-preid --force-publish
2. lerna version prerelease --preid="" --force-publish
3. lerna version preminor --no-preid --force-publish
4. lerna version preminor --preid="" --force-publish

<details><summary>lerna.json</summary><p>

```json
"lerna": "3.1.4",
  "packages": [
    "packages/*"
  ],
  "version": "1.0.0",
  "command": {
    "version": {
      "message": "[ci-skip] %s"
    }
  }
```
</p></details>

## Context
According to [SemVer Specification, paragraph 9](https://semver.org/#spec-item-9), in pre-release versions are a identifier formed by ASCII alphanumeric numbers are mandatory (at least one), but a number itself is a correct identifier, so it is not necessary a keyword like 'alpha'.
If we recover the possibility to have an empty string as preid (or the `--no-preid` option working), we could have a behaviour like the `npm version` itself.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.1.4 |
| `npm --version`  | 6.4.0 |
| `node --version` | 8.11.0 |

| OS | Version |
| --- | --- |
| Fedora | 28 |
| Ubuntu | 16.04 |

**Comment by evocateur** [comment]
That was intentional. Prereleases without a preid are dangerously non-communicative.

**Comment by sergiohgz** [comment]
I understand your point of view @evocateur and make default "alpha" is a great idea but that is a little bit restrictive. I was thinking about, if somebody doesn't want a preid, Lerna could allow pass `--no-preid` flag and remove the default preid ("alpha"), being more permissive. The idea of set `--preid=""` is a little bit stupid having that flag :sweat_smile: . If you want I can make a PR with the `--no-preid` feat :wink:

**Comment by evocateur** [comment]
The `--no-` prefix is a Boolean negation. `--preid` is a string field. I don't want to mix up option types again.

The "restrictive"-ness is by design. If you don't like "alpha," you can always pass a different (non-empty) value.
