### ISSUE TITLE
"Using yarn as an npm client" link is broken in FAQ.md

### ISSUE THREAD

**Issue by knpwrs** [lerna/lerna#1599]
## Expected Behavior

The link in the docs should take me somewhere useful.

## Current Behavior

The link in the docs takes me to the README with no relevant information.

## Possible Solution

Fix the link.

## Steps to Reproduce (for bugs)

1. Go to https://github.com/lerna/lerna/blob/7200fd010a67cdea6b541117e68a0a3c6694e720/FAQ.md
1. Click [using yarn as an npm client](https://github.com/lerna/lerna#--npm-client-client)
1. The anchor is invalid and there is no relevant documentation pertaining to what you want to see.
1. Shake fist at sky.

## Context

I wanted to find out more information about using Lerna together with yarn. The path to find documentation has been less than ideal so far.

**Comment by tim-phillips** [comment]
I suppose it should link to https://github.com/lerna/lerna/tree/master/commands/bootstrap instead?

**Comment by gtsiolis** [comment]
This has been resolved in https://github.com/lerna/lerna/pull/1749. /cc @evocateur
