### ISSUE TITLE
bootstrap installs package peerDependencies when npm install doesn't

### ISSUE THREAD

**Issue by javamonn** [lerna/lerna#160]
Hi all,

I'm running lerna-2.0.0-beta.13 and npm 3.3.12.

It appears that running `lerna bootstrap` will install modules listed as package peerDependencies within the package. Is there a way to configure the behavior of `bootstrap` to match that of `npm@3` and not install peerDependencies by default?

**Comment by hzoo** [comment]
Yeah that probably would have to be an option, I guess opt-in to install peer to match npm 3?

**Comment by javamonn** [comment]
I think there's a separate issue here after playing around a bit more. Agreed that there should be opt-in to match `npm@3` not installing peer dependencies by default, but due to how lerna links local packages - requiring the absolute path of the package rather than fully "installing" it within the `node_modules` of the package listing it as a dependency, the peer dependencies of the depended upon package can never be satisfied as it exists within a different directory tree - `bootstrap` installing peer dependencies by default makes sense. 

This approach works for the majority of dependencies that can be duplicated but I'm currently having an issue with a package `A` that lists react as a peer, and a package `B` that lists react and package `A` as deps. 

After running `bootstrap`, package `B` breaks as react has been included twice. 

After running `boostrap` and pruning the installed  `react` from package `A`'s `node_modules`, package `B` will break on requiring package `A` as it can't resolve the react dependency. This issue doesn't exist when doing a full `npm install B` within `A`.

Is there a different build flow or organization I could use to get around this?

**Comment by javamonn** [comment]
Ended up with a (hacky) working solution:

1. add `react`, `react-dom` to top-level package dependencies
2. `npm install` at top level
3. `lerna bootstrap` to link everything together
4. prune all installs of `react` and `react-dom` from submodule's node_modules with `rm -rf ./packages/*/node_modules/react && rm -rf ./packages/*/node_modules/react-dom`

This seems really fragile and I would love to hear any alternatives :)

**Comment by hzoo** [comment]
That looks like what we're doing in [babel](https://github.com/babel/babel/blob/13c961d29d76ccd38b1fc61333a874072e9a8d6a/Makefile#L59-L62) actually. We don't want to link `babel-runtime` and want to use the 6.x version on npm so we depend on it at the top level and delete the other ones.

**Comment by lukebatchelor** [comment]
@javamonn Thanks! You just saved us so much time trying to debug the same issue.

@hzoo is there any reason that you create the npm install command by appending all the dependencies instead of just running `npm install`?
https://github.com/lerna/lerna/blame/master/src/NpmUtilities.js#L9

This would ensure that Lerna behaves the same way as whatever version of npm the consumer is using (1 and 2 would install peerDependencies 3 wouldn't).

Tagging @nadiam84 for visibility.

Cheers

**Comment by eranimo** [comment]
Any update on this? An option at least would be preferable to having to delete the peer deps them manually

**Comment by skidding** [comment]
Fixed in #318, shipped in [2.0.0-beta.29](https://github.com/lerna/lerna/releases/tag/v2.0.0-beta.29). Somebody close this.
