### ISSUE TITLE
lerna 3.x publish fails if there is no package.json for a configured package location

### ISSUE THREAD

**Issue by raymondfeng** [lerna/lerna#1602]
We have a sandbox folder configured in `lerna.json` to allow other modules to be tested against our monorepo, for example:
```json
{
  "lerna": "3.1.4",
  "packages": [
    "packages/*",
    "sandbox/*"
  ],
```
By default, there is no `sandbox/*/package.json`.

## Expected Behavior

`lerna publish` should work as it does with `lerna@2.x`.

## Current Behavior

```
lerna ERR! Error: Command failed: git checkout -- sandbox/*/package.json
lerna ERR! error: pathspec 'sandbox/*/package.json' did not match any file(s) known to git.
lerna ERR! 
lerna ERR!     at makeError (/Users/rfeng/Projects/loopback4/loopback-next/node_modules/execa/index.js:172:9)
lerna ERR!     at Promise.all.then.arr (/Users/rfeng/Projects/loopback4/loopback-next/node_modules/execa/index.js:277:16)
lerna ERR!     at <anonymous>
lerna ERR! lerna Command failed: git checkout -- sandbox/*/package.json
lerna ERR! lerna error: pathspec 'sandbox/*/package.json' did not match any file(s) known to git.
```
## Possible Solution

https://github.com/lerna/lerna/blob/master/commands/publish/index.js#L373

We should check the existence of `${pkgGlob}/package.json` to be safe.

## Steps to Reproduce (for bugs)

Running `npm run release` against https://github.com/strongloop/loopback-next

<details><summary>lerna.json</summary><p>

https://github.com/strongloop/loopback-next/blob/master/lerna.json

</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.1.4 |
| `npm --version`  | 6.4.0 |
| `yarn --version` | VERSION |
| `node --version` | 8.10.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
But that's... not a package? It _should_ fail if you pass invalid locations to the `packages` config. I'm unclear why lerna even needs to be aware of the sandbox.

**Comment by raymondfeng** [comment]
The idea is to have `sandbox` as a location to test packages without changing `lerna.json` . There are no existing packages from a fresh checkout but packages can be generated by our tests or any developers want to validate their applications or modules against our latest code in the monorepo.

Do you consider a `location` without any child packages invalid? Lerna 2.x supports it well as a placeholder.

**Comment by evocateur** [comment]
You could just as easily use relative `file:` specifiers for the former case, lerna bootstrap is not required. Likewise the latter. Even better for this use case, if you _really_ want to support it, is proper "nightly" prereleases (the original intention of `--canary`).

The lerna 2.x behavior was wrong, a completely unintentional side-effect. That it worked at all is an accident.

**Comment by raymondfeng** [comment]
If we believe that a location is invalid without any packages, `lerna bootstrap` should report the error.

`file:` is not a good option for us as we want to allow drop-in of apps/modules as-is without changing their own package.json. I'll check `--canary`. 

For now, we just add an `example` package under `sandbox` to work around it.

**Comment by virkt25** [comment]
Another reason `canary` releases isn’t the best solution is that a contributor may want to test a patch to monorepo against their own code before opening a PR (and `npm link`) can be painful if multiple packages are affected by a change.

**Comment by pksunkara** [comment]
We are encountering this in https://github.com/storybooks/storybook too.

**Comment by jure** [comment]
We're facing an issue with a similar cause. Our config goes something like:

```
{
  "packages": ["packages/*", "packages/components/!(test|config)"],
  "command": {
    "publish": {
      "conventionalCommits": true,
      "message": "chore(release): publish"
    }
  },
  "version": "independent"
}
```

And after the publish, the process exists with:
```
lerna ERR! Error: Command failed: git checkout -- packages/components/!(test|config)/package.json
lerna ERR! error: pathspec 'packages/components/!(test|config)/package.json' did not match any file(s) known to git.
lerna ERR! 
lerna ERR!     at makeError (/Users/juretriglav/.nvm/versions/node/v10.13.0/lib/node_modules/lerna/node_modules/execa/index.js:174:9)
lerna ERR!     at Promise.all.then.arr (/Users/juretriglav/.nvm/versions/node/v10.13.0/lib/node_modules/lerna/node_modules/execa/index.js:278:16)
```

I imagine the `!(test|config)` is a glob that git doesn't understand, but `globby` does?

**Comment by jure** [comment]
This has been fixed since.

**Comment by evocateur** [comment]
Yeah, lerna `packages` config does not support negation. Also, I don't recommend "clashing" globs (`packages/*` and `packages/components/*` are overlapping, the `components` directory should be a sibling of `packages` instead).
