### ISSUE TITLE
Split git tag/push operations out of lerna version

### ISSUE THREAD

**Issue by erquhart** [lerna/lerna#1603]
I realize you _just_ got done splitting `version` out of `publish`, but hear me out: some projects need to know their own version during the build. Because Lerna controls that, I need to know _from Lerna_ what version we're bumping to, then build, then run `version` and `publish`.

I'm aware that I can pass flags to stop tagging and pushing, but then there's no way to do those things (through Lerna) afterward without checking out Lerna's previous changes.

## Expected Behavior

To be able to execute the tag/push part of `lerna version` separately from the rest of the versioning operations.

## Current Behavior

Tagging and pushing occur as a part of `lerna version`.

## Possible Solution

I'd suggest that `lerna version` becomes comprised of three lower level commands: `lerna bump`, `lerna tag`, and `lerna push`. That way `lerna version` can continue doing what it already does, but we can drop down to these commands for more control. In that case, my task would look like:

```shell
lerna bump
npm run build
lerna tag
lerna push
lerna publish
```

## Context

In the netlify-cms project, we print the current version to the console on load to help with troubleshooting. We need to get just the version from Lerna before building, and then run tagging and pushing after the build so they don't occur if the build fails. We're currently able to do this by running `lerna version` with the `--no-git-tag-version` and `--no-push` flags, running the build, and then checking out the changes lerna made before running `lerna version` again without the flag. It's hacky, and I suspect our approach is causing some issues we've seen that we've yet to reproduce (hence I haven't filed issues for them).

Supporting this in a first class way would be really helpful.

**Comment by evocateur** [comment]
Sounds like you should be using the root `version` lifecycle to run the build?

```
// preversion:  Run BEFORE bumping the package version.
// version:     Run AFTER bumping the package version, but BEFORE commit.
// postversion: Run AFTER bumping the package version, and AFTER commit.
// @see https://docs.npmjs.com/misc/scripts
```

The root `version` lifecycle runs after all package versions have been bumped, but before the git commit.

**Comment by erquhart** [comment]
But Lerna handles versioning logic based on our conventional commits - how would I use `npm version` in tandem with Lerna?

**Comment by evocateur** [comment]
Lerna calls the same lifecycle scripts during its execution. I could have sworn this was documented. Anyway, there are very clear unit tests of the lifecycle script functionality.

**Comment by erquhart** [comment]
Awesome, thanks for explaining!
