### ISSUE TITLE
Lerna "add" creates entries in root node_modules instead of package node_modules

### ISSUE THREAD

**Issue by ericmorand** [lerna/lerna#1606]
I have a very common project structure, with a `packages` folder containing my packages and a lerna.json files that looks like this:

```
{
  "command": {
    "bootstrap": {
      "hoist": true
    }
  },
  "packages": [
    "packages/*"
  ],
  "version": "0.1.0"
}
```

When I use `lerna add <package> --scope foo`, `<package>` is installed in root's node_modules directory.

**Expected result**

Either `<package>` to be installed inside `packages/foo/node_modules` or at least that `<package>` is simlinked from root's node_modules into `packages/foo/node_modules`.

**Comment by evocateur** [comment]
That's expected behavior when you set `hoist: true`. Either don't hoist, or be okay with the root installation.
