### ISSUE TITLE
support adding multiple packages in one command

### ISSUE THREAD

**Issue by Janpot** [lerna/lerna#1608]
`npm install` works for multiple packages as in

```
npm install package1 package2 package3
```

Trying something similar with lerna

```
lerna --scope=target-package package1 package2 package3
```

results in errors

## Possible Solution

Allow to specify multiple packages to add at once. (a `rm` command would be usefull as well but that's a different issue I guess)

## Context

I'm expecting (maybe wrong) a sort of duality between `npm`/`yarn`commands and `lerna`. I wasted a lot of time figuring out why `lerna` refused to execute my command. After that I wasted a lot of time adding these packages one by one.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.1.4 |
| `npm --version`  | 6.1.0 |
| `yarn --version` | 1.7.0 |
| `node --version` | v10.7.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.6  |

**Comment by Janpot** [comment]
The help is relatively clear. It's just that tis command:
```
lerna add --scope=package3 package1 package2
```
returns
```
info cli using local version of lerna
lerna notice cli v3.1.4
lerna info filter [ 'package3' ]
lerna WARN No packages found where package1 can be added. 
```
Falsely assuming that `add` would `add` packages to the packages that are in `--scope` it seems to say "can't find package3" but actually it is saying "can't find package2". This completely threw me off and I went on trying to find issues in my project setup.

Then at some point I think I saw the help for `add` and tried
```
lerna add package1 package3
```
But it still returned the same error and that kind of confirmed my false assumption. In the end, just adding the packages one by one worked. After reading your comment I finally realise my stupidity:
```
lerna add package1 packages/package3
```
Which makes sense, but is a bit counterintuitive. as in "I want to add package1 to package3, but for the first I specify it by name, the second by folder".
The way to improve help would probably be by adding some examples of calling this command so it's clear the packages folder needs to be included. Maybe renaming `glob` to something like `target` would have helped as well.

**Comment by huafu** [comment]
So at the end the real answer to this issue title is:

> lerna does NOT support adding multiple packages to one or more scopes at once. If you want to install multiple packages, you need to run `lerna add` as many times as you have packages to install

right?

**Comment by Janpot** [comment]
Seems like it, yes.
