### ISSUE TITLE
Prevent version bump propagation through the PackageGraph when using --conventional-commits

### ISSUE THREAD

**Issue by Ojisama** [lerna/lerna#1609]
Hello!

Situation: Package Alpha imports package Bravo (`^1.0.3`), and a developer adds a Breaking Change to package Bravo.

## Expected Behavior
  `lerna version --conventional-commits` will bump package Bravo with a major (from 1.0.3 -> 2.0.0), but will not update the `package.json` of package Alpha with the new (2.0.0) version.

## Current Behavior
Currently, if you introduce a Breaking Change in package Bravo, `lerna version` will bump the `package.json` of package Alpha, and release Alpha with a patch bump (1.2.1 -> 1.2.2).

## Possible Solution
* During `lerna version`, lerna doesn't update the `package.json` of package Alpha.
* Add a `--no-propagation` flag to `lerna publish` to prevent any / breaking changes bumps to package Alpha.  

## Steps to Reproduce (for bugs)

1. Create a lerna repo with two packages Alpha and Bravo
2. Put Bravo as a dependency of Alpha
3. Make a breaking change on Bravo
4. Run `lerna version --conventional-commits` 
5. You will see 
![image](https://user-images.githubusercontent.com/25685118/44661168-1a27a200-aa0a-11e8-9430-a019abcf4329.png)
And the `package.json` of Alpha will have the new Bravo version (2.0.0)

MWE is available here: https://github.com/Ojisama/bumpPropagationLerna
1. Clone it
2. Run `lerna version --conventional-commits`
3. `git diff`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "version": "independent",
  "npmClient": "yarn"
}

```
</p></details>

## Context

We have several teams working on a monorepo managed by Lerna. Our packages can be used seperatly, but some packages have other packages from the monorepo as dependencies. All versioning/publication steps are automated on our CI.

Currently, if you introduce a Breaking Change in package Bravo, `lerna publish` will bump the package.json of package Alpha, and release Alpha with a patch bump (1.2.1 -> 1.2.2).

In our current configuration, this behaviour is error-prone because if someone merges a new feature to the package Alpha, it will trigger a minor bump (1.2.2 -> 1.3.0). Then, on the host project  the developer will bump Alpha from 1.2.1 to 1.3.0, and the update of the Bravo dependency with a Breaking Change would be hidden (or at least not clearly visible).

The only way for us to check for Breaking Changes is to check the changelogs for every package bump what corresponds to the `Note: Version bump only for package alpha` line.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.1.4 |
| `npm --version`  | 6.2.0 |
| `yarn --version` | 1.7.0 |
| `node --version` | 10.5.0 |

| OS | Version |
| --- | --- |
| Ubuntu | 16.04 |

Thanks in advance! :smiley:

**Comment by evocateur** [comment]
If Alpha didn't itself require any adaptation to the breaking change, does that not constitute an acceptable dependency bump? Nobody consuming Bravo should care at all about the version of Alpha _unless_ they _also_ have a dependency on Alpha. The whole point of lerna is to manage the versioning and publishing of multiple related packages in a shared cadence.

(If Bravo's tests don't adequately verify that Alpha's major bump did not break them, that's another matter, outside the scope of lerna)

**Comment by Ojisama** [comment]
Hi @evocateur, thanks for the reply!

Our context is that we are several teams working on quite different packages inside the monorepo. A developer that will change things in the sub-package Bravo may be not aware of all the impacts of its changes on packages importing Bravo, some (s)he never worked on.

We do not have a 100% coverage on our tests but that's not what we aim for: we would like each of our team to manage the bumps of internal packages like they would with external dependencies (React, Redux...). That is to say Changelogs reading, then manual bump, manual checks, then automated tests.

Since we do not have a "core team" that validates commits/features like an open source project as React, do you see why we think an automated bump is risky? 

We drafted a solution on a fork if you want to have a quick look: https://github.com/justinemignot/lerna/pull/1/files

**Comment by Ojisama** [comment]
We may not be in the expected use case for Lerna, but Lerna is helping us a lot :

- developing is way easier by updating dependencies in real time
- batching tests and CI builds
- reducing the number of PRs per feature
- automatic bumps for dependent packages
- unique project installation and documentation

We will be adding in the next couple of weeks more integration and e2e tests, but we think that these cannot prevent all bugs from being captured.

For our use case, we strongly believe that a command preventing automatic bumps of Breaking Changes would help a lot preventing bugs being shipped in production by imposing manual bumps and changelogs reading to test the impact once a week.

@evocateur, would you be ok if we opened a PR to propose an implementation of this feature in Lerna?

**Comment by Ojisama** [comment]
> For our use case, we strongly believe that a command preventing automatic bumps of Breaking Changes would help a lot preventing bugs being shipped in production by imposing manual bumps and changelogs reading to test the impact once a week.

> would you be ok if we opened a PR to suggest an implementation of this feature in Lerna?

@evocateur what do you think? :blush:

**Comment by evocateur** [comment]
Sorry for the delay in response.

I don't think it is appropriate for Lerna to be used as a tool to enforce
policies like "no breaking changes". That's more of a social problem, in my
experience. It's also something that Lerna only has one-dimensional insight
into, and only when using `--conventional-commits`: "does a commit message
created since the last release have the words BREAKING CHANGE somewhere in
its body?". Basically, Lerna only ever responds to human input, either
implicit or explicit; Lerna is not the enforcer.

Integration/end-to-end tests that fail when a public API breaks are the
only automated way to prevent breaking changes (and they're not 100%
reliable at that, even with "full" coverage). That responsibility is out of
scope for Lerna.

**Comment by pantoninho** [comment]
I actually see some use cases for this flag.

Given the following scenario:
- `package-a@1.0.0` and `package-b@2.0.0`
- `package-a` depends on `package-b@^2.0.0`
- a `fix` commit affects `package-b`

Running `lerna version --conventional-commits` would bump `package-b` to `2.0.1` (correctly) and would update `package-a` dependency on `package-b` to `^2.0.1`, causing a minor package bump to `package-a` (making it `1.0.1`).

This is quite a useless version bump (and future publish) as `package-b` new version still satisfies `package-a` original dependency version (`^2.0.0`). The same is true for `feat` commits, which introduce a new feature, but is useless for its dependants if they do not make use of it.

I have a bunch of packages that depend on one single common package. A bug fix on that common package creates a lot of meaningless version bumps on all the dependants.

+1 on this flag!

**Comment by evocateur** [comment]
@pantoninho This won't happen. Read #707 for background.
