### ISSUE TITLE
Fixed Versioning seems broken

### ISSUE THREAD

**Issue by codeNoobie** [lerna/lerna#1611]
With Fixed versioning, `Lerna Version` is only bumping the version of packages which had a change in the previous commit.

## Expected Behavior

Since I am using Fixed versioning, `Lerna Version` must bump version of all packages in my mono repo. 
## Current Behavior

Let's say we have a commit which contains `bug fix` in `package-1`. Other packages are not modified in this commit. Now I run `lerna version --conventional-commit`. It only modifies `package-1 's package.json` and the root `lerna.json` but doesn't modify any other package's version. It also creates git tag. The `changelogs` of other packages are also not modified.

Part 2: Now if you modify package-2 with a fix commit and repeat the process then package-2's version would take the version from lerna.json and bump it. So basically it will increment by 2.

**This workflow works fine if the commit contains a Breaking Change for any individual package.**

Can see this behavior in `lerna` repo as well.

<img width="1260" alt="screen shot 2018-08-27 at 9 40 04 pm" src="https://user-images.githubusercontent.com/5392144/44701138-144db300-aa42-11e8-8975-9dd7e4e0e146.png">

## Steps to Reproduce (for bugs)

1. Create a `fix` commit that modifies only one package.
2. Run lerna version --conventional-commit
3. Check the versions of packages.
4. Repeat 1,2 and 3 with a change in a different package.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "projects/*"
  ],
  "command": {
    "publish": {
      "conventionalCommits": true,
      "gitRemote": "origin",
      "message": "chore(release): publish %s"
    }
  },
  "npmClient": "yarn",
  "useWorkspaces": true,
  "loglevel": "silent",
  "version": "3.0.2"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
0 silly argv { _: [ 'version' ],
0 silly argv   progress: false,
0 silly argv   sort: true,
0 silly argv   ci: false,
0 silly argv   'conventional-commits': true,
0 silly argv   conventionalCommits: true,
0 silly argv   yes: true,
0 silly argv   loglevel: '',
0 silly argv   lernaVersion: '3.0.3',
0 silly argv   '$0': '<HOME>/node_modules/.bin/lerna' }
1 info version 3.0.3
2 verbose rootPath <HOME>
3 info current version 3.0.1
4 silly isAnythingCommitted
5 verbose isAnythingCommitted 1
6 silly currentBranch
7 verbose currentBranch master
8 silly isBehindUpstream
9 silly isBehindUpstream master is behind origin/master by 0 commit(s) and ahead by 6
10 silly hasTags
11 verbose hasTags true
12 info Looking for changed packages since v3.0.1.
13 silly diffSinceIn v3.0.1 projects/assets
14 silly diff
15 silly diffSinceIn v3.0.1 projects/common
16 silly diff
17 silly diffSinceIn v3.0.1 projects/components
18 silly diff projects/components/build.gradle
19 silly diffSinceIn v3.0.1 projects/test-config
20 silly diff
21 silly diffSinceIn v3.0.1 projects/test-decorators
22 silly diff
23 verbose updated @components
24 verbose version Overriding version of @components from 3.0.0 to 3.0.1
25 silly fixed for @components at <HOME>/projects/components
26 verbose fixed increment 3.0.1 by patch
27 info auto-confirmed
28 silly fixed for @components at <HOME>/projects/appd/components
29 silly fixed writing new entry: "<a name=\"3.0.2\"></a>\n## [3.0.2](<BITBUCKET>/compare/v3.0.1...v3.0.2) (2018-08-28)\n\n\n### Bug Fixes\n\n* **ui-ki:** updated components task ([95cea84](<BITBUCKET>/commits/95cea84))\n\n\n\n"
30 verbose fixed wrote <HOME>/projects/appd/components/CHANGELOG.md
31 silly root for ui-kit at /Users/anand.tiwary/appdynamics/ui-kit
32 silly root writing new entry: "<a name=\"3.0.2\"></a>\n## [3.0.2](<BITBUCKET>/compare/v3.0.1...v3.0.2) (2018-08-28)\n\n\n### Bug Fixes\n\n* **ui-ki:** updated components task ([95cea84](<BITBUCKET>/commits/95cea84))\n\n\n\n"
33 verbose root wrote <HOME>/CHANGELOG.md
34 silly gitAdd [ '<HOME>/projects/appd/components/package.json',
34 silly gitAdd   '<HOME>/projects/appd/components/CHANGELOG.md',
34 silly gitAdd   '<HOME>/CHANGELOG.md',
34 silly gitAdd   '<HOME>/lerna.json' ]
35 silly gitCommit chore(release): publish v3.0.2
36 verbose git [ 'commit', '-m', 'chore(release): publish v3.0.2' ]
37 silly gitTag v3.0.2
38 verbose git [ 'tag', 'v3.0.2', '-m', 'v3.0.2' ]
39 info git Pushing tags...
40 silly gitPush origin master
41 error Error: Command failed: git push --follow-tags --no-verify origin master
41 error remote:                             *%%%%%.
41 error remote:                         %%%         %%%
41 error remote:                      ,%#               %%
41 error remote:                     %%                   %%
41 error remote:                    %#                     %%
41 error remote:                   %%                       %
41 error remote:                   %(                       %%
41 error remote:                   %%%%%%%%%%%%%%%%%%%%%%%%%%%
41 error remote:                 %#%*%#///////%# %%///////%%%%%%
41 error remote:                ,% %*%%******%#   %%******%(%%,%
41 error remote:                  %%/ %%/**%%/%%%%%%%(**#%( %%#
41 error remote:                   %%          %%%          %(
41 error remote:                    %                      .%
41 error remote:                    *%        %%%%%       .%
41 error remote:                      %#                 %%
41 error remote:                       .%%            .%%
41 error remote:                       .%%.%%,     %%%.%%/
41 error remote:                 %%%%%%##%.  #%%%%%.  .%((%%%%%%
41 error remote:             %%#(((((((((%%,         #%%(((((((((#%%.
41 error remote:       %%%((((((((((((((((((%%%, .%%%((((((((((((((((((#%%*
41 error remote:     %%(((((((((((((((((((((((((%(((((((((((((((((((((((((#%.
41 error remote:   ,%(((((((((((((((((((((((((((((((((((((((((((((((((((((((%#
41 error remote:   %#((((((((((((((((((((((((((((((((((((((((((((((((((((((((%
41 error remote:   %%%%%%%%%%%%%(((((((((((((((((((((((((((((((((%%%%%%%%%%%%%
41 error remote:  %%            %####((((((###%%%%%%%%#(((((((((%            ,%
41 error remote: ,%             %%%%%%#.               %%%((((((%*            %%
41 error remote: #%                                       %%%#                %%
41 error remote: .%                             .%%%%%%%%%                    %#
41 error remote:  %                         #%%%                              %
41 error remote:  %                     %%%%                                  %*
41 error remote: /%************/#%%%%%%######%%*                        ..,*/(%%
41 error remote:               %%######(((((((##################%%
41 error remote:               %%######(((((((((((((((((((((((((%%
41 error remote: //////////////%%%%%%%%#########################%%/////////  ///
41 error remote: ----------------------------------------------------
41 error remote: Branch refs/heads/master can only be modified through pull requests.
41 error remote: Check your branch permissions configuration with the project administrator.
41 error remote: ----------------------------------------------------
41 error remote:
41 error remote:
41 error To ssh://BITBUCKET
41 error  ! [remote rejected] master -> master (pre-receive hook declined)
41 error  ! [remote rejected] v2.1.1 -> v2.1.1 (pre-receive hook declined)
41 error  ! [remote rejected] v3.0.0 -> v3.0.0 (pre-receive hook declined)
41 error  ! [remote rejected] v3.0.1 -> v3.0.1 (pre-receive hook declined)
41 error  ! [remote rejected] v3.0.2 -> v3.0.2 (pre-receive hook declined)
41 error error: failed to push some refs to 'ssh://git@BITBUCKET'
41 error
41 error     at makeError (<HOME>/node_modules/execa/index.js:172:9)
41 error     at Promise.all.then.arr (<HOME>/node_modules/execa/index.js:277:16)
41 error     at <anonymous>

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.3 |
| `yarn --version` | 1.9.2 |
| `node --version` | 8.11.3 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
That's exactly how fixed versioning works. It is _not_ a mode that versions every package every release, but only when a package or one of its dependencies has a change since the previous release.

**Comment by codeNoobie** [comment]
I see. But then, why does it update all the packages if the same commit has a Breaking change?

**Comment by evocateur** [comment]
Because breaking changes are different. They're not satisfied by the default `^` semver range, so all packages need to be bumped in order for the local sibling dependencies to match.

**Comment by codeNoobie** [comment]
I see. In the 2.x release, we used to bump versions of all packages even when a fix or feat commit only modified one package out of many. 

I remember raising a bug regarding this.  At that point, we were not updating the versions for breaking change commits, but we were bumping versions of all packages for feat and fix commits. Here is the reference.
https://github.com/lerna/lerna/issues/1383

Did something change in between that lead to change in functionality of 'lerna version/publish`?

**Comment by evocateur** [comment]
To be clear, the default "fixed" versioning scheme **does not** publish all packages for non-major bump _unless_ all packages (or their local dependencies) have changes since the previous release (annotated git tag). The non-major behavior has not changed since early lerna 2.x beta, only the "bump all when major" behavior is new.

What exactly are you asking?

**Comment by codeNoobie** [comment]
My understanding was that with `Fixed versioning`, versions of all packages will be bumped together for any commit so that the versions of all packages are consistent with each other at all time. I think 2.x was doing this thing and i remember the "version bump only" message in the change log in the unmodified package. 

With version 3.x, I am observing the following things. 

Example: 
package 1 -> 3.0.0 
package 2 -> 3.0.0
package 3 -> 3.0.0

- Added a fix commit for package 1. 
package 1: 3.0.0 -> 3.0.1
package 2: 3.0.0 -> 3.0.0
package 3: 3.0.0 -> 3.0.0

- Added a fix commit for package 2
package 1 -> 3.0.1 -> 3.0.1
package 2 -> 3.0.0 -> 3.0.2
package 3 -> 3.0.0 -> 3.0.0

- Added a fix commit for package 3
package 1 -> 3.0.1 -> 3.0.1
package 2 -> 3.0.0 -> 3.0.2
package 3 -> 3.0.0 -> 3.0.3

This makes it similar to independent versioning for non major bump changes. Is this correct behavior for Fixed versioning? Should it not updated all packages and keep a fixed consistent version across the mono-repo?

**Comment by evocateur** [comment]
No, 2.x never did this when operating under normal circumstances. If it did, it means the git tags from previous releases were mangled or completely missing, thus causing lerna to think _nothing_ had previously released, thereby choosing everything every time.

If your three example packages have no dependency relationship whatsoever (odd for a monorepo, tbh), then your example is 100% expected behavior.

**Comment by codeNoobie** [comment]
Thanks for explaining! I need to play around with it more to understand this completely.
