### ISSUE TITLE
Invalid version number when publishing as canary for the first time

### ISSUE THREAD

**Issue by spoldman** [lerna/lerna#1614]
I'm trying to create a new package in my repository but when I try to publish a canary/next version I get an invalid version. "ERR! Invalid version: "null-alpha.NaN+ab983f0"". I might be doing something wrong as I'm using @lerna/publish directly in code. Also it is worth mentioning that I'm using independent versioning and this package has not been published before.

## Expected Behavior
Version number for the new package should be something like: 1.0.0-alpha.next+ab983f0

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true
}

```
</p></details>

</p></details>

## Context
```javascript
import publish from '@lerna/publish'

....
await publish({
  canary: true,
  npmTag: 'next',
  yes: true,
  amend: true,
  verifyRegistry: false,
  verifyAccess: false,
})
...
```

The repository was created with lerna v2 but we are working on updating and changing a lot of other stuff

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.1.4 |
| `yarn --version` | 1.9.4 |
| `node --version` | 8.11.4 |

**Comment by spoldman** [comment]
I was just expirimenting with the options so maybe some of them do not make sense as you described. Thanks for all the info regarding the options. 

To answere your question  package.json has version: 1.0.0

**Comment by evocateur** [comment]
Ah, yes, that makes sense. I think I have a fix, validating it right now...
