### ISSUE TITLE
Please register an SPDX License Exception

### ISSUE THREAD

**Issue by chriseppstein** [lerna/lerna#1618]
Note: I'm not here to express support for or against this license change, I just want to make some suggestions on the implementation of this change, which I think could be done better.

The [`"license"` property of package json][licenseprop] uses the [SPDX identifier][spdx_list] so that code can make algorithmic legal decisions based on a project's license. The recent change to the license file changes the license of the project so that it is no longer using the MIT license but since it is *mostly* using MIT and most companies are unaffected, the new value of `license` as `SEE LICENSE IN LICENSE` will cause most automated tools treat this as a custom license, which is good, but it can be better.

IANAL but I'd also point out that this license text as written does not allow for a company to change policy in order to adopt this software. If the goal is to affect behavioral change in the companies listed, the text should allow for companies that discontinue their relationship with ICE to adopt the existing releases of the software retroactively. Furthermore because this lists specific companies, it doesn't apply to companies who take on new associations to ICE. You may want to consider simply forbid companies that meet some criteria. 🤷‍♂️ 

## Expected Behavior

Project license should be interpreted as MIT with a license exception. Then companies with license verification tooling that are affected can correctly opt out and unaffected companies can ignore the exception.

## Current Behavior

Automated systems at unaffected companies that could approve an MIT license will reject this.

## Possible Solution

A [license exception](https://spdx.org/licenses/exceptions-index.html) should be [registered with SPDX](https://spdx.org/spdx-license-list/request-new-license). 

It could be something like `Abolish-ICE-Exception-1.0".

And the the license field should then be updated to `"license": "MIT WITH Abolish-ICE-Exception-1.0"`

This also allows other projects to compose other licenses with this exception. It's like code-reuse but for legalese.

[licenseprop]: https://github.com/lerna/lerna/blob/19a7f5d4bd88b9cc50b603adcf171623227ec554/package.json#L18
[spdx_list]: https://spdx.org/licenses/

**Comment by freelerna** [comment]
Feel free to use this instead https://github.com/LernaOpenSource/LernaOpenSource

**Comment by nickmccurdy** [comment]
While I respect and mostly agree with Jamie's political views, I would recommend switching to LernaOpenSource to be safe: https://github.com/lerna/lerna/issues/1620#issuecomment-416906987

**Comment by pluma** [comment]
I think the exception can not really be meaningfully registered as it is as it's essentially a curated blacklist. Most of the companies on the blacklist are listed as having ties to ICE but some are more arbitrary (abusive behavior towards workers, anti-union etc). This sounds like an open ended list that might grow or change in the future.

If this is intended to be something more permanent it would be helpful to replace the explicit blacklist with language clearly identifying requirements for companies to be excluded from the license.

Maybe someone can come up with unambiguous wording and wave it at a lawyer to make sure it cuts the mustard.

**Comment by KarolS** [comment]
Licence exceptions are either:
* exceptions to conditions
* additional permissions

Since they remove restrictions and **do not add** restrictions, I don't think exceptions are an appropriate tool here.

SPDX tag for JSON License is `JSON`, not `MIT WITH no-evil-exception`

**Comment by jamiebuilds** [comment]
Good idea, I'll get started on that

**Comment by jamiebuilds** [comment]
Actually, I'm not sure how we'll be able to do it if we end up adding or removing companies from the list. It will have to be a versioned exception. Probably just easier to have it be custom

**Comment by chriseppstein** [comment]
Jamie, that’s why a list-based approach is problematic.

**Comment by jamiebuilds** [comment]
Well if some big company wants to help us write generic legal text that can replace this then that would be wonderful. Until then this is the best I'm comfortable attempting to do

**Comment by jcsalomon** [comment]
Particularly as the license is non-Free and non-Open Source, identifying it as a “modified” version of any F/L/OSS license is misleading.
