### ISSUE TITLE
How do I know if my stack is now illegal?

### ISSUE THREAD

**Issue by StoneCypher** [lerna/lerna#1624]
A lot of libraries use you.  You've recently made yourself illegal on basically every major hosting provider.

In particular, I am worried that I can no longer build `babel` on `travis-ci`, because `travis` runs on `AWS`, which is a problem because I use a custom `babylon` plugin to consume a custom programming language.

The only thing I know of that's similar to `travis` is `circle-ci`, which also runs at AWS

Do I have to now replace my entire continuous integration setup, because of your ICE gesture?

**Comment by pluma** [comment]
I think you're misunderstanding how licensing works. The existing releases remain MIT licensed with no exceptions:

https://github.com/lerna/lerna/blob/v3.2.1/LICENSE

Unless lerna unpublishes all existing versions, this shouldn't affect you until they release a new version.

However I would strongly urge the lerna maintainers to consider this license change (like any license change) a breaking change and thus release the next version as 4.0.0 even if it is API compatible.

This would also help companies that are not intentionally affected by the license change but need their third-party licenses to be vetted by lawyers.

**Comment by hallister** [comment]
I wouldn't worry about this too much. This type of virtue signaling kills projects, and likely will here. Maintainers of packages that use this software can simply port their dependencies to https://github.com/LernaOpenSource/LernaOpenSource, and the community, which very apparently opposes using popular libraries as political soap boxes, will follow as well.

**Comment by jamiebuilds** [comment]
If you do not install Lerna, you do not have to worry about this license change. If you do install Lerna, but you are not one of the companies listed in the license or one of their subsidiaries, you do not have to worry about this license change.

You may still choose to worry, but you don't have to.

**Comment by hallister** [comment]
Not unless you change the MIT license to some other license. You are currently advertising this is MIT licensed, which it no longer is, and should you release a version of Lerna with this license you are going to break a ton of automated license checkers for the companies you've decided to start this nonsense with. 

Change the license to something other than MIT so everyone can move to LernaOpenSource.
