### ISSUE TITLE
More-restrictive license is a breaking change and should require a version bump

### ISSUE THREAD

**Issue by ckknight** [lerna/lerna#1629]
I'm not here to argue about the content of https://github.com/lerna/lerna/commit/250ec4f68f07903ef1d1b34170f93a796895f266, but given that it is now a more-restrictive license and also by definition no longer Open Source (in terms of OSI-compatibility), users should be appropriately informed by at least a major version bump.

**Comment by phpnode** [comment]
dupe of #1628

**Comment by ckknight** [comment]
Ah, you're right. Thanks @phpnode

**Comment by jamiebuilds** [comment]
I already said it would be a major version bump

**Comment by botfap** [comment]
What version will it be?
