### ISSUE TITLE
Please remove jamiebuilds as maintainer for CoC violations

### ISSUE THREAD

**Issue by darthtrevino** [lerna/lerna#1630]
The statements in issues leveled at all employees of Palantir carte blanche appear to violate the Lerna code of conduct. Specifically: 

"Examples of unacceptable behavior by participants include the use of sexual language or imagery, _derogatory comments or personal attacks_, trolling, public or private harassment, insults, or other unprofessional conduct."

https://github.com/palantir/tslint/issues/4141
https://github.com/palantir/blueprint/issues/2877
https://github.com/palantir/blueprint/issues/2876

**Comment by SRGOM** [comment]
@jamiebuilds you wrote a heartbreaking message but unfortunately the issue was locked so to your  uninformed and fake outrage I say womp womp 

@kittens the threads linked above are serious violations . Please remove xir.

**Comment by jamiebuilds** [comment]
Nice try

**Comment by darthtrevino** [comment]
Can any other maintainer weigh in on this?

**Comment by Sieabah** [comment]
@jamiebuilds I think it's a honest concern that you are overlooking. Things are obviously pretty heated right now but this won't last. Either you will be removed or you will fade into obscurity.
