### ISSUE TITLE
How to enable independent mode after it was removed as an argument of the publish command?

### ISSUE THREAD

**Issue by marcofugaro** [lerna/lerna#1637]
Sorry if this is a question, but it's not clear from the README.

How do I enable independent mode?

From the readme
https://github.com/lerna/lerna#independent-mode---independent

Just hints to the argument `--independent`, but that argument has been removed from the `yarn publish` command. And it throws

```
$ lerna publish --independent

ERR! lerna Unknown argument: independent
```

So how do I enable independent mode?

**Comment by marcofugaro** [comment]
Thank you! I think this must be documented in the main readme

**Comment by evocateur** [comment]
Yes, @CamBurris is correct.
