### ISSUE TITLE
Lerna v3 tries to fails to retrieve "package" from Artifactory

### ISSUE THREAD

**Issue by kzvaigzne** [lerna/lerna#1640]
While attempting to publish packages to an Artifactory repository, Lerna seeming looks for "package" in the repository and throws an error when it's unable to find it

## Expected Behavior
Lerna publishes scoped packages to Artifactory repository

## Current Behavior
Throws an error stating that it can't find the "package" inside the repository
```
lerna info publish Publishing packages to npm...
lerna WARN ETHIRDPARTY Skipping ping of https://artifacts.<host>.com/artifactory/api/npm/<repository name> as most third-party registries do not support advanced npm functionality
npm http request GET https://artifacts.<host>.com/artifactory/api/npm/<repository name>/-/org/<user account name>/package?format=cli
npm http 404 https://artifacts.<host>.com/artifactory/api/npm/<repository name>/-/org/<user account name>/package?format=cli
npm http request GET https://artifacts.<host>.com/artifactory/api/npm/<repository name>/-/user/<user account name>/package?format=cli
npm http 404 https://artifacts.<host>.com/artifactory/api/npm/<repository name>/-/user/<user account name>/package?format=cli
npm ERR! code E404
npm ERR! 404 Registry returned 404 for GET on https://artifacts.<host>.com/artifactory/api/npm/<repository name>/-/user/<user account name>/package?format=cli
npm ERR! 404
npm ERR! 404  'package' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "registry": "https://artifacts.<host>.com/artifactory/api/npm/<repository name>"
    }
  }
}
```
</p></details>

## Context
Publishing packages with the command: `npx lerna publish`

## Your Environment

Root package.json:
```json
...
  "publishConfig": {
    "registry": "https://artifacts.<host>.com/artifactory/api/npm/<repository name>"
  },
...
```

.npmrc:
```
@SCOPE:registry=https://artifacts.<host>.com/artifactory/api/npm/<repository name>
```

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.2.1 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.9.4 |
| `node --version` | v8.9.1 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.6 |

**Comment by CamBurris** [comment]
I believe this is an issue with Artifactory not supporting all npm features. Lerna is running `npm access ls-packages` to verify the current user has access to publish packages to the registry. It seems like this command isn't supported in Artifactory. There are a couple of flags to `lerna publish` you can try to bypass this issue. There is a `--no-verify-access` flag, that should skip the call to npm access. There is also a `--no-verify-registry` flag. I believe the --no-verify-access flag should get you past this error.

**Comment by CamBurris** [comment]
https://github.com/lerna/lerna/blob/37642a066ed0243d6312240c49c635c3431a989b/commands/publish/lib/verify-npm-package-access.js#L40-L53

It seems there is already code that is suppose to handle private registries and not error out here. The code is explicitly looking for HTTP 500 or ECONNREFUSED from the server. Since Artifcatory returns a 404 it doesn't pass the exception check and thus errors out. Adding a check for E404 here should work.

**Comment by kzvaigzne** [comment]
Ah, @CamBurris, thanks - the registry access verification was the issue.
Tried publishing with `--no-verify-registry` and it worked like a charm, thank you very much for the quick response!

@evocateur Sorry for blaming Lerna, I didn't realize this was an Artifactory implementation issue -- not the first one we've had with them either..
