### ISSUE TITLE
Bump version of conventional-changelog-core 

### ISSUE THREAD

**Issue by mlavina** [lerna/lerna#1641]
## Expected Behavior
Lerna is using `conventional-changelog-core 2.x` while the latest is `3.x`. The main breaking change was dropping support for Node < 6, however `lerna` already only supports Node 6+ https://github.com/lerna/lerna/blob/master/package.json#L76 so this is a minimal change. 

## Context
There are issues our team has ran into where the old version of `conventional-changelog-core` has trouble with malformed git commits and ends up breaking our `lerna publish` command. This is fixed in `conventional-changelog-core 3.x`. 

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.2.1 | 
| `yarn --version` | 1.9.2 |
| `node --version` | 8.9.1 |

I am fine with making a PR with this change if I get the go ahead from the `lerna` core team

**Comment by evocateur** [comment]
Yes, please, that would be great! I wasn't even aware there was a new major available.

**Comment by evocateur** [comment]
Briefly scanning the commits (no Github releases entered :/), https://github.com/conventional-changelog/conventional-changelog/pull/301 and https://github.com/conventional-changelog/conventional-changelog/pull/335 might prove challenging for our upgrade (some snapshots will need updating, at the very least).

**Comment by hbetts** [comment]
> no Github releases entered

That is because we use Lerna, which stores changelogs in files. 😉 

Here's an example of a changelog with one of the breaking changes - [`conventional-recommended-bump` changelog](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-recommended-bump/CHANGELOG.md#400-2018-06-06)

Since it looks like I made both of those breaking changes, please let me know if you have any questions or concerns.

**Comment by evocateur** [comment]
@hbetts Yes, sorry, didn't mean for the comment to come across negatively. I still manually copy+paste the release notes into the Github release fields, which of course is prohibitive to do when versioning independently.

**Comment by hbetts** [comment]
> @hbetts Yes, sorry, didn't mean for the comment to come across negatively.

I did not take it like that. 👍 I just though it was ironic, and also timely. 😄  @mlavina and I were discussing earlier about Lerna's GitHub release notes, and how we wish it was a feature supported out of the box. We're both interested in #1023, but I, myself, don't have the time to contribute towards that 😢
