### ISSUE TITLE
The Long Cock of ICE Is All the Way Down The Maintainer's Throat

### ISSUE THREAD

**Issue by bludo222** [lerna/lerna#1642]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by Sieabah** [comment]
Congrats on reaching immaturity. Only a few more years to go before you understand how to interact with the general public.

**Comment by robbyoconnor** [comment]
Great job -- now grow up and act like an adult.
