### ISSUE TITLE
There is no way to resume publishing if it failed after tagging/pushing to github and before uploading to npm

### ISSUE THREAD

**Issue by wereHamster** [lerna/lerna#1643]
I've ran `lerna publish` and it did all the steps up until uploading the tgz to npm, which failed because I was not logged in. After I logged in, lerna refused to publish anything because there were no changes since the last 'release'. That's because lerna already created all the necessary git commits and tags and even pushed them github.

I was able to upload all packages to npm by going through each package folder and running `npm publish .` in each.

## Possible Solution

The `lerna publish` could check if any packages are tagged but not available in npm and then retry the upload.

**Comment by evocateur** [comment]
`lerna publish from-git` does exactly what you describe. You can effectively do `lerna version && lerna publish from-git` if you want to make the process _appear_ more recoverable.
