### ISSUE TITLE
lerna publish --force-publish is not working

### ISSUE THREAD

**Issue by thecodejack** [lerna/lerna#1647]
`lerna publish --force-publish` is not working with latest. it used to work with lerna@3.0.6. Updated today to 3.2.1 and observed that following command doesn't do force publish

```
lerna publish --force-publish=package1
``` 
## Expected Behavior
Command should start publish

## Current Behavior
Not publishing on force publishing

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version | 
| ---: | :--- |
| `lerna --version` | 3.2.1| 
| `npm --version`  | 5.6.0| 
| `yarn --version` | 1.6.0| 
| `node --version` | 8.10.0| 

| OS | Version | 
| --- | --- |
| Ubuntu| latest |

**Edit** : It was 3.0.0-beta.17 not 3.0.6 previously from where I updated to 3.2.1

**Comment by evocateur** [comment]
An isolated reproduction would be appreciated, thanks.

**Comment by thecodejack** [comment]
repro from my current env
https://github.com/thecodejack/lerna-publish-1647 

Publish all first with `3.0.0-beta.17` and later try force publish with 3.2.1

**Comment by evocateur** [comment]
What was the exact command you tried? It's not clear from the repo you posted.

I'm having difficulty reproducing in other lerna-based repositories with similar context (i.e., no recognized changes since the last tagged release). In [pectin](https://github.com/evocateur/pectin), for example:

```
$ git log --oneline 
8de783d (HEAD -> latest, origin/latest, origin/HEAD) chore: Add code of conduct
b0a1690 chore: Add badges [skip ci]
fa70a30 test: Fix mind-bending node v8.x problem with CLI tests
1910d4d chore: Travis
1f32de6 chore: Add lockfile and .yml files to 2-space overrides
a2674ca chore: add tabWidth overrides for yaml + json config files
6e9c571 (tag: v1.0.0) chore(release): v1.0.0
810de3e docs: Add #readme anchors to package links
ce2d5cb feat: open source

$ npx lerna changed
lerna notice cli v3.2.1
lerna info Looking for changed packages since v1.0.0
lerna info No changed packages found

$ npx lerna changed --force-publish
lerna notice cli v3.2.1
lerna info Looking for changed packages since v1.0.0
@pectin/api
@pectin/babelrc
@pectin/cli
@pectin/core
rollup-config-pectin
rollup-plugin-main-entry
rollup-plugin-subpath-externals
lerna success found 7 packages ready to publish

$ npx lerna changed --force-publish @pectin/cli
lerna notice cli v3.2.1
lerna info Looking for changed packages since v1.0.0
@pectin/cli
lerna success found 1 package ready to publish

$ npx lerna version --force-publish @pectin/cli
lerna notice cli v3.2.1
lerna info current version 1.0.0
lerna info Looking for changed packages since v1.0.0

Changes:
 - @pectin/cli: 1.0.0 => 1.0.1

? Are you sure you want to create these versions? (ynH) 
```

Despite no changes to `packages/*`, both `--force-publish` and `--force-publish <pkg>` appear to work as expected. (`lerna changed` is a quicker/safer way to test flags for `lerna version` and `lerna publish`)

**Comment by thecodejack** [comment]
I haven't tried using `lerna changed` and `lerna version`. I was trying `lerna updated` & `lerna publish`. Will try these and give you update.

**Comment by yeskunall** [comment]
Just tried this on my [repo](https://github.com/21kb/react-hooks) and it doesn’t seem to work:

![image](https://user-images.githubusercontent.com/14703164/47911787-c6539200-de6c-11e8-9cb1-f312950625de.png)

Any tips @evocateur?

**Comment by evocateur** [comment]
I'm not sure what lerna is supposed to publish when nothing has changed? This is one reason I dislike `--force-publish` in general: it leads to a false sense of purpose. If a given package didn't change, lerna won't publish it. Lerna certainly won't try to publish anything if there have been zero commits since the last release.

**Comment by imolorhe** [comment]
@evocateur The `force-publish` option is meant to be used by the developer when they know what they are doing I presume. In my case, I have the tag released to git and it's on the tag that the publishing in the CI is done to npm.

`lerna publish from-git --force-publish=* --yes` is the command I use and it says no changed packages to publish. I would assume that specifying force-publish should bypass the checks for changed files irrespective.

**Comment by roccomuso** [comment]
Looking for this param too and seems broken.

**Comment by evocateur** [comment]
I'm so close to deleting the `--force-publish` option entirely, it has given me nothing but pain, recently.

Convince me to keep it by contributing a PR to "fix" it. I'm done trying to make it work.

**Comment by imolorhe** [comment]
@evocateur If it helps, I got mine to `force-publish` by first checking out to the latest tag instead of the staging branch. Coupled with the `from-git` bump option, it publishes the changes in the CI each time I push a new tag with a new version. ✌🏾

**Comment by thecodejack** [comment]
@evocateur I keep publishing custom versions of my packages. But later if I want to do a proper minor/major release of a module I am unable to do with `lerna` since I get following. With `force-publish` I was able to handle this. But now I am kind of stuck to do manual releases.

```
user:/path/pakages> lerna publish
lerna notice cli v3.10.5
lerna info versioning independent
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.
```

**Comment by bochen2014** [comment]
@evocateur  version management is something more challenging than the actual development, as per my experience. we have run into so many issues in the past and when things go out of control, my manager always say (and I incline to agree with him) "lets bump everything to the next minor/major version, and start  fresh again"

what do you think?

**Comment by runspired** [comment]
@evocateur in my recent experience, `--force-publish` would be nice because lerna will refuse to publish unpublished work if it has previously created the commit/tag but failed to publish. I'm now stuck in a loop where I have to delete tags and commits :(

**Comment by evocateur** [comment]
@runspired [from-package](https://github.com/lerna/lerna/tree/master/commands/publish#bump-from-package) is what you're looking for.

**Comment by Ognian** [comment]
@evocateur --force-publish is needed as per your [FAQ](https://github.com/lerna/lerna/blob/master/FAQ.md#how-do-i-retry-publishing-if-publish-fails) and it looks like that it is not working in the latest version (3.14.1). What shall someone do in this case??

**Comment by evocateur** [comment]
>@evocateur --force-publish is needed as per your [FAQ](https://github.com/lerna/lerna/blob/master/FAQ.md#how-do-i-retry-publishing-if-publish-fails) and it looks like that it is not working in the latest version (3.14.1). What shall someone do in this case??

@Ognian Literally used `--force-publish` multiple times just yesterday, so I don't know what to say. Maybe open a new issue with a clear reproduction?

**Comment by Ognian** [comment]
@evocateur looks like it was my fault; after splitting up in ˋlerna versionˋ lerna run buildˋ and  ˋlerna publish from-gitˋ and removing prepublish  and prepare scripts everything works now.
Thanks
Ognian

**Comment by denissabramovs** [comment]
This option was removed? Can't find it in the latest docs anymore.

**Comment by kerryj89** [comment]
`--force-publish` wasn't allowing me to publish a package sometimes because there were no changes in said package.  That may be by design but I still wanted it to do what it said on the tin so I created a dummy file in the package(s) I wanted to publish before running `lerna version`.

All package
`lerna exec -- touch .lerna-changed-buster-$RANDOM`

Specific package
`lerna exec --scope "<your-package>" -- touch .lerna-changed-buster-$RANDOM`
