### ISSUE TITLE
Expose topological sorting of packages via command or option

### ISSUE THREAD

**Issue by jonrgold** [lerna/lerna#1652]
I'm hoping that we may be able to provide either a new command or a flag to `ls` to expose the topologically sorting of artifacts to a consumer.  

## Expected Behavior

* `lerna ls --toposort` (or similar) could return a list of artifacts but in the topologically sorted behavior

## Current Behavior
Currently `exec` / `run` support topological sorting, but there doesn't seem to be an easy way to the topologically sorted dependency structure via a command. 

Right now to get that structure, we're using `lerna exec $LERNA_PACKAGE_NAME`. 

## Possible Solution

* `lerna ls --toposort` (or similar) could return a list of artifacts but in the topologically sorted behavior
* https://github.com/lerna/lerna/issues/610

## Context

We have a few use cases:
1.  Getting a high level view of the dependency structure in our mono-repo to assist in refactoring. 
1.  Piping packages from this command into our own org-specific publish script that would already be sorted. 

I think this is kind of similar to https://github.com/lerna/lerna/issues/610 .  Was hoping it might be somewhat simple for me to create a PR where the results of `batchPackages` could be used to display this to user.

**Comment by evocateur** [comment]
Yeah, totally. `batchPackages` is exactly the ticket, I would imagine a conditional between [these two steps](https://github.com/lerna/lerna/blob/6dfea52415c765d97f1cb294a1950efa79072af8/commands/list/index.js#L22-L25):

```js
    chain = chain.then(() => getFilteredPackages(this.packageGraph, this.execOpts, this.options));

    if (this.options.toposort) {
      chain = chain.then(filteredPackages =>
        batchPackages(filteredPackages)
          // flatten batched packages for display
          .reduce((arr, batch) => arr.concat(batch), [])
      );
    }

    chain = chain.then(filteredPackages => {
      this.result = listable.format(filteredPackages, this.options);
    });
```

**Comment by morewry** [comment]
This would be useful for me right now :-) I'm having an issue where a build is failing. In logs it appears that `lerna run` is moving on / concurrently running a dependent's build before its dependency's build is complete. Be nice to verify whether the sort is right to help rule things out.
