### ISSUE TITLE
babel-loader fails to transpile imported packages. 

### ISSUE THREAD

**Issue by hannadrehman** [lerna/lerna#1656]
i am trying to give lerna one more try by converting our multiple front-end applications into one mono repo. it definitely is a good idea for managing local dependencies and manage entire code in just one repo. 
I have followed the documentation and created a test repo [here](https://github.com/hannadrehman/react-monorepo), I have also created some packages and one `react` project which uses `webpack` as a build tool.  and imports these other packages.
I have not pre-build the other packages. I don't want to. because the dependent packages will go continuous development and I don't want to build them every time before using them.

now when i try to build my project with webpack. it is giving me this error 

reading online some existing questions and solutions, it seems that the issue is with babel-loader, it is not able to resolve the symlinks somehow. (not sure about this). 

i have wasted enough time to fix this. all the solutions found online are not working in my favor. I can't waste more time on this.

## Expected Behavior
webpack should build and `babel-loader` should transpile the other packages also when i import them
## Current Behavior
while building webpack is giving this error.
```
ERROR in /Users/hannadrehman/workspace/open source/projects/react-production-monorepo/node_modules/@healthifyme/elements/src/Alert/Alert.component.jsx 9:2
Module parse failed: Unexpected token (9:2)
You may need an appropriate loader to handle this file type.
|   message, description, type, closable, onClose,
| }) => (
>   <div>
|     <Alert
|       message={message}
```

## Steps to Reproduce (for bugs)

1. clone [this](https://github.com/hannadrehman/react-monorepo)
2. hit `lerna bootstrap`
3. go to `packages/meme-dashboard`
4. hit `yarn start`

<details><summary>
lerna.json
</summary><p>

```
lerna.json
{
  "npmClient": "yarn",
  "useWorkspaces": true,
  "packages": [
    "packages/*"
  ],
  "version": "1.0.0"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

i am trying to convert our huge repository which contains a lot of `react` web applications to one mono repo.
## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.2.1 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.9.4 |
| `node --version` | v10.8.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.6 |

**Comment by hannadrehman** [comment]
so basically `babel-loader` will not transpile anything in `node_modules` . everything in `node_modules` is expected to be already transpiled module. i have already tried many things to tell babel to transform node_modules. but nothing seems to work.

**Comment by hannadrehman** [comment]
the issue is with `babel-loader` not considering `es6` modules inside `node_modules` for transpiration.

**Comment by hannadrehman** [comment]
out of curiosity what do u suggest? 
should I put raw `es6` in my packages and then import then in other packages. or should transpile `es6` modules and then import it in other packages.

former will be faster in development. and later will obviously be slow when developing the common packages.

**Comment by hannadrehman** [comment]
I was able to solve the problem by transpiling all packages independently with `@babel/cli` and shipping ES5 compatible modules from `main` entry point. I am also able to achieve react `hmr` with the same setup.  
there should be a guide or docs for setting up Lerna with for react applications that would really help people who are new to lerna and want to migrate their projects to a monorepo setup.

and thanks for replying and helping out.

**Comment by evocateur** [comment]
Thanks for following up. Improved documentation is definitely on my todo list.

**Comment by sibelius** [comment]
how can we make babel-loader to transpile all lerna packages?

**Comment by hannadrehman** [comment]
@sibelius you can use `@babel/cli` to do it.  you can try this  `babel src --out-dir lib --copy-files --ignore spec.js,spec.jsx`
