### ISSUE TITLE
lerna ls --sort prints packages in alphabetically order instead of topologically order.

### ISSUE THREAD

**Issue by yveskaufmann** [lerna/lerna#1658]
## Expected Behavior

Take the following project structure:

```
-packages
  +-A (depends on B, C)
  +-B
  +-C
```
The command `lerna ls --sort` prints the package names in topologically order., e.g.: B,C,A.

## Current Behavior

The command `lerna ls --sort`  prints the packages in alphabetically order, e.g.: A, B, C.

## Possible Solution

Use the same implementation as `lerna exec --sort` for the sorting of the packages.

## Steps to Reproduce (for bugs)
1. Create a lerna repository with three packages e.g. A,B,C
2. Define the packages B and C as dependency of A.
3. Invoke lerna ls --sort

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.3.0",
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "command": {
    "bootstrap": {
      "npmClientArgs": [
        "--no-package-lock"
      ]
    }
  },
  "ignoreChanges": [
    "**/package-lock.json",
    "**/fixtures/**",
    "**/test/**",
    "**/*.md"
  ]
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context
Write a make file that requires the packages names in topologically order but found the possible workaround:

```sh
lerna exec --sort --no-prefix 'node -p "require(\"./package.json\").name"'
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.3.0 |
| `npm --version`  | 6.4.1 |
| `node --version` | 8.11.4 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Ubuntu | 18.04 |

**Comment by evocateur** [comment]
Yes, it's an unintentional oversight. As for lerna exec, you can echo `$LERNA_PACKAGE_NAME` as well.

**Comment by evocateur** [comment]
A `--toposort` flag was added to `lerna ls` in [v3.6.0](https://github.com/lerna/lerna/releases/tag/v3.6.0). The default sorting is lexical directory sort (effectively alphabetical). It does not actually respect `--sort`.
