### ISSUE TITLE
Lerna wants to publish unchanged packages 

### ISSUE THREAD

**Issue by brmscheiner** [lerna/lerna#1660]
Our team at work uses lerna and encounters this issue on some of our systems. We have found that two computers can have many things in common but have different results when running lerna publish

Macbook Pros running High Sierra
lerna version 2.11.0
yarn version 1.7.0
node 8.11.2
on origin master

One asks to patch 30+ repos the other needs to patch only 4. The issue persists after blowing up node_modules and reinstalling, or even after downloading a brand new repo. `lerna clean` does not help, but I have been able to find a decent workaround:

```lerna publish --scope mypkg```

The only thing about that is that you have to track down the dependents of mypkg and make sure to bump them as well.

**Comment by evocateur** [comment]
That sounds like a difference in git state, possibly with missing git tags. The state of `node_modules` is largely irrelevant to `lerna publish` in 2.x. Does the issue persist with lerna v3?

**Comment by spacecowboyian** [comment]
Semi related.. is there a way to generate git tags for all of the current versions if you've maybe not used lerna like you should have for a while and managed your own versions without tags?

**Comment by brmscheiner** [comment]
@evocateur sorry for the very delayed response. Yes, I just tested and the issue does persist with 3.4.3

**Comment by evocateur** [comment]
I'd appreciate any demonstration repo you can provide with this reproduction. There are too many variables to debug without actual code/tags/branches etc to look at.
