### ISSUE TITLE
Missing license warning needs to be clarified, more actionable

### ISSUE THREAD

**Issue by patryk-bartoszek** [lerna/lerna#1666]
## Expected Behavior

Don't issue warring if license is provided in the package.json file. 
I shouldn't have to create LICENSE file if I'm using SPDX license identifier or expression.

## Current Behavior

Currently during publish I get the following message:
`lerna WARN ENOLICENSE Packages foo are missing a license`

I have following property set in package.json of foo package
```
  "license": "MIT"
```

## Possible Solution

This is the result of changes introduced in #1465
The current implementation of license check only looks for LICENSE / LICENCE files and ignores the license value provided in the package.json file.
https://github.com/lerna/lerna/blob/master/commands/publish/lib/get-packages-without-license.js

When using standard SPDX license string, there is really no need to provide license file. Tools such as license-checker work just fine with the default approach of defining license in package.json. 
I see no benefit to creating separate license file.

A possible solution would be to extend implementation so that it checks for license property in the package.json file. It would be nice to validate value according to rules provided in https://docs.npmjs.com/files/package.json#license
but that is optional from my point of view.

## Steps to Reproduce (for bugs)

1. Add licence field to package.json
2. run `lerna publish`

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.2.1 |
| `npm --version`  | 5.6.0 |
| `node --version` | v8.9.4 |

| OS | Version |
| ---: | :--- |
| Windows 10 | 1803 |

**Comment by evocateur** [comment]
As [explained](https://github.com/lerna/lerna/pull/1465#issuecomment-405184876) in that PR, I don't think that is the case. More context [here](https://github.com/babel/babel/pull/7308#issuecomment-367615152). The fact that tools like `license-checker` work without the file being present in the package tarball doesn't change the requirements of various licenses, such as MIT.

The license [pattern](https://github.com/lerna/lerna/blob/ac0baa7b1d5c378f794c960ab13d70242d19ddc8/core/project/index.js#L195) is very broad, allowing any (English) spelling, case, or file extension (or none at all). It is very easy to [provide a license file](https://help.github.com/articles/adding-a-license-to-a-repository/) in the root of a monorepo, and in any case, this warning does not adversely affect the performance of `lerna publish`. If you want to hide it, `--loglevel error` will do the trick.

Thank you for opening this issue. I believe it is in the best interest for every participant in the open-source ecosystem to err on the side of caution when it comes to licenses, and it is beneficial to the community for Lerna to promote this pattern.

**Comment by patryk-bartoszek** [comment]
@evocateur Thank you for taking the time to review this issue and for providing context.
I wasn't aware that some of the popular licenses required so that the actual text of the license is included (I totally missed that point while looking at PR for the first time).
This is indeed a compelling argument for the check and I fully agree with the current approach.

The only complaint I have is the actual text of the warning: "Packages foo are missing a license" didn't help me to figure out what the problem was. I had the license defined in package.json after all...  Only by looking at the source code I was able to understand that I was missing licence **file**.
I feel that including suggestion to add LICENSE/LICENCE file in the message would be helpful for many people.

**Comment by evocateur** [comment]
Ooh, yes, I agree! We should definitely clarify the message to be more actionable.

**Comment by ken-kenware** [comment]
This seems easy enough, I'll update the message and open a PR

**Comment by JackHowa** [comment]
Looks like this has been addressed. However, I'm curious what I should do if the project is UNLICENSED. https://github.com/lerna/lerna/blob/master/commands/publish/index.js#L451

**Comment by jasonk** [comment]
What I did was just create a `LICENSE.md` file that just says `This package is unlicensed, and is only usable internally at <Company>`.

**Comment by JackHowa** [comment]
Cool good syntax @jasonk. This removes the warning. (I think I just put a markdown file with just UNLICENSED alone in `LICENSE.md`.) Can probably close this issue @patryk-bartoszek

**Comment by patryk-bartoszek** [comment]
Closing the issue. Sorry for the delay.
The issue has been fixed, long ago.
