### ISSUE TITLE
Error: no test specified"npm ERR! Test failed.  See above for more details.

### ISSUE THREAD

**Issue by MahdiyeMellati** [lerna/lerna#1669]
when I run npm test, I see this message in bash.
Here is my pakage-jason :

{
  "name": "boilerplate",
  "version": "1.0.0",
  "description": "Simple react app",
  "main": "index.js",
  "scripts": {
  "test": "echo \"Error: no test specified\" && exit 1",
  "start": "node lib/server.js"
            },

I have added the script but still see this problem...!

Thanks

**Comment by evocateur** [comment]
That's literally what your `test` [script](https://docs.npmjs.com/misc/scripts) is configured to execute. You need to replace `"echo \"Error: no test specified\" && exit 1"` with an actual test command, like `"jest"` or `"mocha"`.

Closing as this is not a Lerna issue.
