### ISSUE TITLE
[Question] How can I put the output of publish in a json format 

### ISSUE THREAD

**Issue by CosminIonascu** [lerna/lerna#1673]
I would like to put the output of a publishing process in a json form like the ```changed --json`` command.
Currently, we are using 
```  "release": "lerna publish --conventional-commits --yes --no-verify-registry > version.txt"```  but this is not working when there are multiple changes, I don't know why.
Do you have any suggestions? 
Thanks,
Cosmin

**Comment by evocateur** [comment]
Hmm, theoretically that should be redirecting the stdout, but I don't know how useful that is. Are you trying to use the results in a post-release reporter/notifier of some kind?

**Comment by CosminIonascu** [comment]
Yes we need to use the results after the release, I managed to put the result in a txt file, you can close this, 
thanks
