### ISSUE TITLE
Suggestion (or question) about same external dependencies of cross-dependent multiple packages.

### ISSUE THREAD

**Issue by ru-web-designer** [lerna/lerna#1676]
There is a monorepo with two private local packages, boopler and woopler. The whole story with them and their problem is illustrated in [this repository](https://github.com/ru-web-designer/lerna-webpack-typescript).

boopler is depending on woopler, both of them have import * as $ from "jquery". boopler binds DOMReady event with it, woopler makes some DOM manipulations. Their deps are perfectly symlinked with Lerna.

Finally, there is index.ts in the root of the repo, which have import "boopler". It is an entry point for Webpack bundle.

The thing is in that both boopler and woopler packages has same jquery dependency version. However, it's included twice in the output main.js file. And this is the problem.

## Expected Behavior

Somehow, bundlers suppose to detect same external dependencies across packages and include them only once.

## Current Behavior

Webpack (or another thing, resolving packages) works simply: if something presents twice, it'll be bundled twice. In multi-repo, this problem does not exist, because the only way you can use the package is install it as dependency, so all sub-deps will be resolved from same `node_modules`.

## Possible Solution

Listed [here](https://github.com/ru-web-designer/lerna-webpack-typescript#possible-workarounds)

* Make some `shared` package, which have `jquery` dependency and make resolve alias to it's jquery.  Don't store jquery in `boopler` and `woopler` deps. Possible cons is static errors in IDE, maybe something else.
* Use `optimization.runtimeChunk: 'single'` in `webpack.config.js` [link](https://github.com/webpack/webpack/issues/2134#issuecomment-389124211)
* Using aliases with peer dependencies [link](https://github.com/webpack/webpack/issues/5455#issuecomment-369399064)

## Context

Full representation of this problem is here

[https://github.com/ru-web-designer/lerna-webpack-typescript#possible-workarounds](https://github.com/ru-web-designer/lerna-webpack-typescript#possible-workarounds)

**Comment by evocateur** [comment]
This doesn't strike me as a Lerna problem, but possibly Typescript or Yarn or Webpack (combined)? I don't use jQuery or Typescript, but I've literally never had the problem you describe here, across several dozen repositories and hundreds of modules.

It is very strange that your leaf package.json files point their `main` to a non-CommonJS file. That's not how npm packages are meant to work.

**Comment by ru-web-designer** [comment]
> It is very strange that your leaf package.json files point their main to a non-CommonJS file. That's not how npm packages are meant to work.

This is not important in this case.

This is really not a Lerna problem, cause even if leaf packages load the same dependency asynchronously, (i.e. not being bundled), it will be loaded twice.
