### ISSUE TITLE
Unexpected version bumps with conventional commits

### ISSUE THREAD

**Issue by daffl** [lerna/lerna#1677]
We recently moved [FeathersJS](https://feathersjs.com/) to Lerna and the initial publish from the new repository worked great 👍

Having moved to conventional commits to generate changelogs (we were using `github_changelog_generator` before), publishing subsequent versions does not appear to work the way I was expecting though. 

## Expected Behavior

`lerna version` will only bump versions of packages that show changes in `lerna diff`

## Current Behavior

With the [current master branch](https://github.com/feathersjs/feathers) (commit https://github.com/feathersjs/feathers/commit/c2fe22f0edd2c17cdeca3c90883091314c3a71e5) 

- `lerna diff` shows four changed files in two packages (`packages/commons` and `packages/errors`)
- `lerna version` however wants to patch bump _every_ package:

```
Changes:
 - @feathersjs/authentication-client: 1.0.4 => 1.0.5
 - @feathersjs/authentication-jwt: 2.0.3 => 2.0.4
 - @feathersjs/authentication-local: 1.2.3 => 1.2.4
 - @feathersjs/authentication-oauth1: 1.0.5 => 1.0.6
 - @feathersjs/authentication-oauth2: 1.2.2 => 1.2.3
 - @feathersjs/authentication: 2.1.9 => 2.1.10
 - @feathersjs/cli: 3.8.2 => 3.8.3
 - @feathersjs/commons: 3.0.0 => 3.0.1
 - @feathersjs/configuration: 2.0.2 => 2.0.3
 - @feathersjs/errors: 3.3.2 => 3.3.3
 - @feathersjs/express: 1.2.5 => 1.2.6
 - @feathersjs/feathers: 3.2.1 => 3.2.2
 - generator-feathers: 2.6.2 => 2.6.3
 - @feathersjs/primus-client: 1.1.2 => 1.1.3
 - @feathersjs/primus: 3.2.3 => 3.2.4
 - @feathersjs/rest-client: 1.4.3 => 1.4.4
 - @feathersjs/socketio-client: 1.1.2 => 1.1.3
 - @feathersjs/socketio: 3.2.4 => 3.2.5
 - @feathersjs/transport-commons: 4.1.3 => 4.1.4
```

## Notes

- There still are some circular dependencies which I know should be fixed but removing the circular dependency did not affect this behaviour.
- There were some commits made changing files in the root of the repository

## Steps to Reproduce (for bugs)

1. Clone https://github.com/feathersjs/feathers
2. In the cloned folder run `npm install`
3. Run `lerna diff`, observe diff
4. Run `lerna version`, see version bumps

## Your Environment

Node 10.9.0
Lerna 3.4.0, `independent` mode
Mac OS

**Comment by evocateur** [comment]
Lerna will bump dependents of packages with direct changes as well, conventional commits or not. #707 explains the reasoning.

**Comment by daffl** [comment]
I guess it means more versions to be released but it makes sense in order to avoid any conflicts with previous dependency versions.
