### ISSUE TITLE
`lerna run` in sequence of dependency graph

### ISSUE THREAD

**Issue by hannadrehman** [lerna/lerna#1681]
this may or may not be an issue.

let me try to explain my current project.

i have created a lerna repo with the following structure

```
|--packages
       |-- components
       |-- elements
       |-- services
       |-- utilities
       |-- dashboard-a
       |-- dashboard-b
       |-- server
```
all of these packages have independent builds (for now). 
so `dashboard-a` and `dashboard-b` will be importing `components,elements,utilities etc` and
both the dashboards are build by webpack.

while i am developing the projects i manually build and keep packages in watch mode, so my dashboards can import the build files.

now when i need to publish the projects, it will be done by our CI tool which is supposed to
run my commands to start unit tests, build and then deploy the applications. so far so good.
i am running `lerna run --parallel build`  

`build` is my command in each `package.json` which will start `jest` tests followed by `build` incase of web applications it will be build be `webpack` and incase of common packages `@babel/cli` 

## Current Behavior

 
i am not sure in what order the builds will be executed, since i am passing `--parllel` flag it means all build will happen in parllel, but what about dependency on other packages ?  my concern is before `webpack` build start. it must first finish the dependent pakages build first. the build will fail if lets say `elements` was not build first .

here is the output of my `lerna run --parallel build`
```
lerna success run Ran npm script 'build' in 6 packages:
lerna success - @pkg/components
lerna success - @pkg/constants
lerna success - @pkg/elements
lerna success - @pkg/meme-dashboard
lerna success - @pkg/todo-app
lerna success - @pkg/utilities
```
## Expected behaviour
i think `lerna run --parallel` will not care about what type of command you want to execute. it will simple run it in parallel. but that creates a problem when i need other packages to be build first.

i am really not sure if this is already implemented. but there should be a way to traverse through
all `package.json` and form a dependecy graph and based on that graph decide what packages should be build first. this would ensure no build fails because of other packages not being built. 

i cannot use `--scope` flag in `lerna run` because there will be alot if packages to be built.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna` | 3.2.1 |
| `npm`  | 6.4.1 |
| `yarn` | 1.9.4 |
| `node` | v10.8.0 |

| OS | Version |
| macOS Sierra | 10.13.6 |

**Comment by evocateur** [comment]
Don't pass `--parallel` and it works exactly as you desire. I don't recommend running test tasks inside a "build" script. You should run the tests from the root after a successful build.

**Comment by hannadrehman** [comment]
@evocateur  that's perfect 👍
