### ISSUE TITLE
--scope is not working

### ISSUE THREAD

**Issue by acostaf** [lerna/lerna#1683]
Reopen please --scope is not working on "lerna": "^3.4.0"

npm run this "build:dep": "lerna run --scope common build"

I get lerna ERR! EFILTER No packages remain after filtering [ 'common' ]

my Lerna file   
"packages": [
    "common",
...
  ],

**Comment by phun-ky** [comment]
You've to follow this syntax, which sadly is poorly documented:

    lerna --scope @yourprojectname/commin exec  -- npm run build

**Comment by evocateur** [comment]
It's notable that `--scope` matches package _names_, not directories. I highly doubt you are the owner of the "common" package on npm.

**Comment by evocateur** [comment]
(Scope applies perfectly well to `lerna run`, but it won't execute in packages that lack the target script)

**Comment by acostaf** [comment]
@evocateur common it is my own project, the script name exist but you are right about package name, I was calling the folder, thanks
