### ISSUE TITLE
lerna publish --registry flag not respected in VSTS build

### ISSUE THREAD

**Issue by phun-ky** [lerna/lerna#1684]
## Expected Behavior

With this code:

Root `.npmrc`:
```
@foo:registry=https://bar.myget.org/F/fooz/npm/
@fooz:registry=https://bar.myget.org/F/fooz/npm/
//bar.myget.org/F/fooz/npm/:_authToken=${NPM_TOKEN}
```

```bash
lerna publish --loglevel=warn --registry=https://foo.myget.org/F/bar/auth/${bar_NPM_TOKEN}/npm/ --yes --no-verify-access --no-verify-registry -- --unsafe-perm --loglevel=warn
```
Should publish the scoped packages to the private registry with the preauthenticated feed URI

## Current Behavior

Errors out on the first package to be published:
```bash
lerna ERR! npm publish --ignore-scripts foo-component-1.18.0.tgz exited 1 in '@foo/component'
lerna ERR! npm publish --ignore-scripts foo-component-1.18.0.tgz stderr:

npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

## Possible Solution
It seems that, from the error message, the `--registry` flag is not present in the command. Do I have to log in with the registry, as I do locally?:

```bash
npm adduser --registry=https://bar.myget.org/F/foo/npm/ --scope=@foo
```
If so, how do I do this in a CI?

**EDIT:** I see that from this issue: https://github.com/lerna/lerna/issues/361, the root `.npmrc` is not respected, but I have this in my `lerna.json` and I though `lerna publish` would respect this:

```json
    "publish": {
      "message": "chore(release): :bookmark: publish %s",
      "conventionalCommits": true,
      "npmClient": "npm",
      "verifyAccess": false,
      "verifyRegistry": false,
      "registry": "https://foo.myget.org/F/bar/auth/<token>/npm/"
    }
```

## Steps to Reproduce (for bugs)

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "changelog": {
    "repo": "baz/foo",
    "cacheDir": ".changelog",
    "labels": {
      "problems: breaking change": "💥 Breaking Change",
      "additions: feature": "✨ New Feature",
      "problems: bug": "🐛 Bug Fix",
      "improvements: enhancement": "💅 Enhancement",
      "improvements: upgrade deps": "⬆️ Upgrade deps",
      "improvements: optimization": "⚡️ Optimization",
      "mindless: chore": "🏠 Internal",
      "mindless: documentation": "📝 Documentation"
    }
  },
  "version": "1.17.0",
  "command": {
    "init": {
      "exact": true
    },
    "publish": {
      "message": "chore(release): :bookmark: publish %s",
      "conventionalCommits": true,
      "npmClient": "npm",
      "verifyAccess": false,
      "verifyRegistry": false,
      "registry": "https://bar.myget.org/F/foo/auth/token/npm/"
    }
  }
}

```
</p></details>

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.6|
| `npm --version`  | 6.4.1 |
| `node --version` | 8|

VSTS Hosted Linux Preview

**Comment by evocateur** [comment]
Are you calling Lerna from a Yarn-executed script, by chance? Also, you might consider upgrading Lerna, 3.4.0 adds much more useful authentication checks. A per-package `publishConfig.registry` field is another way to configure custom registries.

**Comment by phun-ky** [comment]
Not using yarn at all. Tested with 3.4.0, it worked, switched origin from VSTS to github (same build pipeline, same code). It failed, same error. 😡 Testing now with `publishConfig` per package, but I am using a pre-authenticated URL with a token in the URI, can I use a env var for this, like in the `.npmrc`-file?

**Comment by phun-ky** [comment]
🤦‍♂️  Yeah, the sources did differ.. The solution using a ``.npmrc`-file per package worked, no need to use `publishConfig`. Closing issue

**Comment by MiracleBlue** [comment]
@phun-ky Sorry to bump this thread with a somewhat off-topic question, but at my work we also use VSTS, and I'm looking at properly setting up a release pipeline that can do the npm publishing, rather than having to do it from my own machine.  So far I haven't found anything for using git tags as a trigger in VSTS (except for a bit of a branch trigger hack)

Might I ask, are you running your publish step from VSTS as well?  If so, what are you using as your trigger?  Were you able to get it to trigger on new git tags?

Sorry if this is a bad place to ask, I've just been struggling to find any useful information out there about this topic specifically.

**Comment by phun-ky** [comment]
@MiracleBlue we use a `master`-only approach, so on every PR merged, we do a new publish (bump build and push): https://gist.github.com/phun-ky/600db3677421d19589e43b9b56048c24
