### ISSUE TITLE
v3: lerna throws errors on publish even though we never want to commit or tag

### ISSUE THREAD

**Issue by dylang** [lerna/lerna#1688]
## Expected Behavior

With `--skip-git` it skipped `tag`, `commit`, and `push`. This was perfect, because our CI doesn't have permission to commit back to `master`. (Only approved PR's can be committed to master.) We use `0.0.0` in our code, and we tell lerna what version to use with some simple code to see what the latest published version is. All builds and publishes happen in a gitignore'd directory, so there would be nothing to check in anyway.

## Current Behavior

`--skip-git` has been replaced with `--no-git-tag-version --no-push` - however even with these settings, `lerna` still uses git during publish and throws errors when it doesn't work as expected. 

It won't publish when this is happening:

```js
if (this.currentBranch === "HEAD") {
      throw new ValidationError("ENOGIT", "Detached git HEAD, please checkout a branch to choose versions.");
    }

```

Since we're not checking anything back in, we don't need that validation error.

If we work around that, it will publish, but it will still error out:

```
lerna info published @scope/module-name 1.2.3-alpha.4
lerna sill gitCheckout */package.json
lerna ERR! Error: Command failed: git checkout -- */package.json
lerna ERR! error: pathspec '*/package.json' did not match any file(s) known to git.
lerna ERR! 
lerna ERR!     at makeError (<repoPath>/node_modules/execa/index.js:174:9)
lerna ERR!     at Promise.all.then.arr (<repoPath>/node_modules/execa/index.js:278:16)
lerna ERR! lerna Command failed: git checkout -- */package.json
lerna ERR! lerna error: pathspec '*/package.json' did not match any file(s) known to git.
lerna ERR! lerna 

Exit code: 1
```

Caused by this:

```js
resetChanges() {
    // the package.json files are changed (by gitHead if not --canary)
    // and we should always leave the working tree clean
    return pReduce(this.project.packageConfigs, (_, pkgGlob) =>
      gitCheckout(`${pkgGlob}/package.json`, this.execOpts)
    ).then(() =>
      // --skip-git should not leave unstaged changes behind
      gitCheckout(this.project.manifest.location, this.execOpts)
    );
```

## Possible Solution
Bring back `--skip-git`, or add a new option `--no-git` that basically means `don't do anything with git.` This would fix the problem for us, and could also be useful for teams not using git.

## Steps to Reproduce (for bugs)

1. Publish should work in detached head.
2. Publish should work if there is no `${pkgGlob}/package.json` to check out.
3. Publish should work if `git` is not available.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

Our CI does not have permission to check things back into git. 

## Your Environment

We do all builds and publishing in a `.gitignore`'d directory.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.0 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.9.4 |
| `node --version` | 10.8.0 |

**Comment by WetHippie** [comment]
Same request - we need lerna to completely disconnect from git. 

This is a breaking change for us since we build our code using AWS Codepipeline/CodeBuild. AWS downloads a ZIP code of the source, so there's no .git directory to use, so anything that goes near git instantly breaks the publish process.

**Comment by evocateur** [comment]
Broken record: `--skip-git` wasn't skipping _all_ git operations, just the commit and push. Git is necessary to determine which packages changed since the last release.

**Comment by dylang** [comment]
Skip that too then?

**Comment by evocateur** [comment]
This can be worked around by passing the new `--no-git-reset` flag, introduced in #1791 .
