### ISSUE TITLE
Sequential sorted running of certain commands

### ISSUE THREAD

**Issue by kirill-konshin** [lerna/lerna#1689]
When building complex projects often times it has some libs along with actual apps, for example two or more React apps along with a bunch of shared libs. Those libs can depend on each other.

During the initial bootstrap we currently have to build libs one by one in a certain sequential order to make sure libs that depend on other libs will be built after them (especially on TS projects where compiler will look for `.d.ts` files and so on).

Later on watch phase order is not so critical because changes propagate through packages like a ripple, but this first initial kick has to be ordered.

## Expected Behavior

It would be great if Lerna will provide some way to tell the order in which command has to be executed in packages.

## Possible Solution

Something like this can work:

```json
{
  "lerna": "3.2.1",
  "packages": [
    "libs/*",
    "apps/*"
  ],
  "command": {
    "bootstrap": {
      "sequence": [
        "scope-1",
        "scope-2"
      ]
    }
  },
  "version": "independent"
}
```

Or through CLI:

```bash
npx lerna bootstrap --hoist --sequence=scope-1,scope-2
```

**Comment by evocateur** [comment]
As long as those packages have proper dependencies on the sibling packages that they must run before, that's ...exactly what happens? If you're hoping for a magical way to avoid configuring proper dependency relationships, I'm afraid you're going to be disappointed.

`lerna bootstrap`, `lerna exec`, `lerna run`, and `lerna publish` all operate on packages in batched topological order (all dependents before dependencies) by default. To disable this topological sorting, you can pass `--no-sort` (though honestly I don't know why you would in 98% of cases).
