### ISSUE TITLE
Question: How can I publish only one package?

### ISSUE THREAD

**Issue by Gcaufy** [lerna/lerna#1691]
How can I publish only one package?

If I have 5 packages, and all those 5 packages are changed. They are independent, and I just want to publish one of them, because the others they are not ready yet.

## Possible Solution
Can we simply add a `Ignore` option when doing `leran publish`?

```
$ lerna publish
>   Patch (x.x.x)
    Minor (x.x.x)
    .....
    Ignore
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.0 |
| `npm --version`  | 6.0.1 |
| `node --version` | 8.9.4 |

| OS | Version |
| --- | --- |
| macOS Sierra | --- |

**Comment by jimmytb** [comment]
I believe you can't, you have to do it manually by going to the folder and run:

``` npm publish ```

Than manually update the version of the package in the other packages.

This is the way i do it. Hope there is an other way

**Comment by Gcaufy** [comment]
@jimmytb yup, this is what I am doing right now. I hope lerna can support publish one single package. then you don't care about the package.json and the git tag and git commits .

**Comment by evocateur** [comment]
You can't. A Lerna-managed monorepo doesn't work that way.

**Comment by Gcaufy** [comment]
@evocateur any reason why not to support it?

**Comment by evocateur** [comment]
Because it breaks the fundamental mechanism Lerna uses to determine which packages need to be published? Absolutely nothing stopping you from _not_ placing several packages in the same monorepo that apparently shouldn't be.
