### ISSUE TITLE
How can I add an NPM package to one of my packages and hoist it right away.

### ISSUE THREAD

**Issue by kevinbeaudoin** [lerna/lerna#1693]
We have a monorepo with several packages.  
We are using npm as npm client.  
Our node module is hoisted to the root dir.  

The issue is that when we try to add a new dependency to one of our packages the lerna add command runs a bootstrap but there is no way to indicate we want that bootstrap to hoist dependencies.

ex: lerna add some-new-dependency --scope my-package

## Expected Behavior

At first we thought we could simply pass the --hoist option to lerna add but doing so gives us the following error : ERR! lerna Unknown argument: hoist

## Current Behavior

So far I haven't found a simple solution to do this.  There must be a way to install a new depencendy and hoist it without having to clean after lerna add and call a bootstrap --hoist afterward?

## Possible Solution

Adding hoist support to lerna add would be great...

## Steps to Reproduce (for bugs)

1. lerna add some-package --scope my-package --hoist

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.0 |
| `npm --version`  | 6.0.1 |
| `yarn --version` | NA |
| `node --version` | v8.9.4 |

| OS | Version |
| --- | --- |
| Windows 8.1| ? |

**Comment by Lloyc** [comment]
Add to your lerna json:
```
"command": {
    "bootstrap": {
      "hoist": true
    }
  }
```
