### ISSUE TITLE
is `useWorkspaces` deprecated?

### ISSUE THREAD

**Issue by Hypnosphi** [lerna/lerna#1694]
I can't find any documentation on this option anymore. It seems to work with Lerna 3 though.

**Comment by Hypnosphi** [comment]
OK it's moved to bootstrap command docs. What's confusing is that's also a `lerna.json` field
    "lerna": "^3.3.0",
https://github.com/lerna/lerna/tree/master/commands/bootstrap

**Comment by evocateur** [comment]
The CLI option [`--use-workspaces`](https://github.com/lerna/lerna/tree/master/commands/bootstrap#--use-workspaces) is equivalent to the lerna.json key `"useWorkspaces": true`.
