### ISSUE TITLE
lerna team should be lobbying for better OOTB support from npm and yarn

### ISSUE THREAD

**Issue by danderson00** [lerna/lerna#1699]
First up - kudos for building a popular tool that solves a common problem. However, let's be honest here - lerna is a workaround for the very poor support that npm and yarn provide for the multiple package scenario.

From a personal perspective, me experiences with lerna have not been particularly positive. Aside from `lerna add` simply not working as advertised, I'm currently in a situation where a dependency is not being linked correctly, resulting in two distinct instances of the package being loaded into memory (a symlinked version and an npm installed version). I suspect I am not alone.

A situation like this is extremely costly for organisations, and commercial / financial realities strongly discourage me from digging in to the lerna code.

A *much* better solution to the multi-package scenario would be to lobby npm to provide better out of the box support for the scenario. lerna receives over 180,000 downloads per week at the time this issue was posted. Surely, as a community, we have the power to make the npm team listen and support such scenarios.

As a lone developer, I don't have the influence to trigger such a change. However, I'm more than happy to assist with such an effort.

Thoughts?

**Comment by CamBurris** [comment]
Yarn already has excellent support for multiple packages with [workspaces](https://yarnpkg.com/lang/en/docs/workspaces/).

**Comment by evocateur** [comment]
> A situation like this is extremely costly for organisations, and commercial / financial realities strongly discourage me from digging in to the lerna code.

It seems like it isn't costly _enough_ to your organization if you can't justify spending time to contribute a fix.

> A much better solution to the multi-package scenario would be to lobby npm to provide better out of the box support for the scenario.

The npm cli team is very aware of this, and has told me directly that they plan on implementing the Yarn workspaces spec within the next year. They are a (growing!) team of two people, so please have patience.

**Comment by danderson00** [comment]
Not sure what you're suggesting. What should I / my organization contribute a fix for? The lack of support for monorepos in npm?

Regardless, that's great news. Thank you for sharing.

**Comment by evocateur** [comment]
> Not sure what you're suggesting. What should I / my organization contribute a fix for?

- "`lerna add` simply not working as advertised"
- "a dependency is not being linked correctly, resulting in two distinct instances of the package being loaded into memory"

I can't wait for the day when lerna can let package managers manage packages. Lerna isn't good at it, quite frankly. We can't fix bugs we're not aware of, however.

**Comment by danderson00** [comment]
Unfortunately, I'm not able to reproduce either issue. Previously, `lerna add` was adding all packages as dependencies of each other, but on a quick test, it's no longer doing that. The second issue was resolved by deleting all node_modules folders and running `lerna bootstrap`. The package was then linked correctly, and I'm unable to repro again. Sorry I can't provide more detail.

Please don't feel that this was an attack on lerna - you do awesome work that the community wholeheartedly appreciates, even if sometimes we don't seem to. Thank you!
