### ISSUE TITLE
Question: No commit with `lerna publish --no-git-tag-version`?

### ISSUE THREAD

**Issue by chris-dura** [lerna/lerna#1700]
## Expected Behavior
```
lerna publish --no-git-tag-version
```
I expected that to either:
1. Bump versions
2. Publish
3. Commit changes and push to origin

Or
1. Bump versions
2. Publish
3. Leave changes on my repo to commit/push/tag manually myself.

## Current Behavior
```
lerna publish --no-git-tag-version
```
This successfully bumps versions and publishes to our artifactory; however, there are no changes registered in git and my working directory is clean.

## Steps to Reproduce (for bugs)

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "bootstrap": {
    "npmClientArgs": ["--no-package-lock"]
  },
  "command": {
    "publish": {
      "allowBranch": "master",
      "message": "chore: Publish %s :tada:"
    }
  }
}
```
</p></details>

## Context

Initially (before we had a private registry) our release/publish workflow required several "manual" steps.

1. Bump package versions and dependency versions
2. Update changelog, and various other custom "pre-publish" steps
3. Publish each package to it's own "manyrepo" on GitLab
4. Tag monorepo as released and push

We now have a private registry, and I'm trying to adapt this workflow to utilize `lerna`, and even though `lerna version` and `lerna publish` are now separate processes, I'm getting unexpected behavior. I can adjust the workflow so that I do all the custom steps _after_ the `lerna` steps.

1. Run `lerna` to bump versions, and publish to artifactory.
2. Update changelog, and various other custom steps
3. Tag monorepo and push

I do _not_ want to git tag every package on the commit, and when I run `lerna version --no-git-tag-version` I'm left with all the `package.json`s with changes to their version numbers. This is fine, and perhaps preferable, because I can just commit them myself. However, I do not get the same behavior when I run `lerna publish`.

Is there some combination of `lerna version` and `lerna publish` that I can use to accomplish this?

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.0 |
| `npm --version`  | 6.4.1 |
| `node --version` | v8.11.4 |

| OS | Version |
| --- | --- |
| macOS El Capitan | 10.11.6 (15G22010) |

**Comment by wbern** [comment]
@evocateur I'd also like to know if it's possible to commit and push version changes to package json files, without tagging? I'd like my pre-releases to not contain changelogs, but when I do major releases, I'd like the major releases to include changelogs from all the pre-releases. The best way I found this to work was to not tag pre-releases.

Often times, we also run into issues when publishing on feature branches, so we figured not tagging the prerelease also saves us some headaches, so we don't have to manually delete the tags every time.

**Comment by evocateur** [comment]
The answer to both questions is to use `lerna version` with appropriate flags and then `lerna publish from-package`. I'll have to add details later, almost off my bus.

**Comment by trollepierre** [comment]
@evocateur : are you off your bus now? :D

**Comment by evocateur** [comment]
I cycle to work now, so...

**Comment by evocateur** [comment]
More seriously, I think you're looking for [`--no-git-reset`](https://github.com/lerna/lerna/tree/master/commands/publish#--no-git-reset), allowing you to make your own git commit from the changes created by lerna publish.

**Comment by trollepierre** [comment]
Great. That is what I had been doing. 

I believe this issue can be closed.

**Comment by ahadyekta** [comment]
if anyone is struggling with "fatal tag [packagName@version] already exists" error in the pipeline, you can simply use `--force-git-tag` to avoid this error.
