### ISSUE TITLE
Creating Dockerfile with root package.json and packages/my-project/package.json

### ISSUE THREAD

**Issue by titho** [lerna/lerna#1703]
How do I link the 2 package.json files so that when I run docker-compose it installs all the needed node_modules in the container?

The first package.json is the root one and the second is the one that I have in packages/my-project/

Is there a possible way to dockerize only the project?

P.S. One way I found out is to use a npm package that merges the 2 package.json files, but I think there should be a more practical way that I dont see.

**Comment by HosseinAgha** [comment]
Hi. If I understood correctly you want to `docker build` a single project in monorepo.  
You need to have the monorepo `yarn.lock` or `package-lock.json` in addition to 2 package.jsons in your build context.  
__TL;DR__: for production add a `.dockerignore` to your root folder and configure it to exclude everything but your project directory and monorepo `package.json`, `lock` and `lerna.json` files. something like this:    
```ignore
*/

# add project directories to include here
!/packages/my-project

# exclude these even in the included project directories
node_modules
.git
```
Beware that in this method _lerna_ have to download your package dependencies from npm unless you also add dependencies to `.dockerignore`. Eventually if you want to use dependency packages from monorepo you may end up sending the whole monorepo as the docker daemon context but the idea here is to download packages from npm registry.  
Unfortunately as docker does not support multi context builds changing `.dockerignore` on each build (maybe using a script in CI/CD) was the only solution I could come up with.   
If you are in a development environment mounting the whole monorepo into the container is the best solution.

**Comment by evocateur** [comment]
I would suggest using `npm` to address npm packages. That's what `lerna` does. Lerna is not a Docker tool.
