### ISSUE TITLE
Setup .npmrc in home directory if you use Travis and Npm to publish

### ISSUE THREAD

**Issue by cyril-lakech** [lerna/lerna#1705]
If you want to publish lerna based packages from Travis with Npm, having a .npmrc in your root project directory is not enough. You have to setup a .npmrc in the $HOME directory or you will get a 401 error.
## Expected Behavior

Having a .npmrc in project root directory should be enough

## Current Behavior

You have to copy your .npmrc into $HOME directory

## Steps to Reproduce (for bugs)

1. Setup a Travis deploy with script mode and lerna publish
2. If you don't setup your home directory .npmrc then you face a 401

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4 |
| `npm --version`  | 6.2 |
| `node --version` | 8 lts |

| OS | Version |
| --- | --- |
| Linix | 42 |

I post this issue to help others because we have lost so many hours on this.

**Comment by cyril-lakech** [comment]
Travis errors logs: https://travis-ci.com/AxaGuilDEv/react-oidc/builds/86311923#L683

**Comment by evocateur** [comment]
Well, you probably need to provide an [`NPM_TOKEN`](https://docs.npmjs.com/private-modules/ci-server-config) env var in Travis, then?

**Comment by cyril-lakech** [comment]
yes we have this var

**Comment by Siilwyn** [comment]
I think this is unrelated to Lerna. Setting the npm token from your CI scripts can be done in multiple ways like: `echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc`.

**Comment by wahengchang** [comment]
@cyril-lakech , did you find a way to complete CI/CD of `lerna` + `travis-ci` ?
