### ISSUE TITLE
`lerna publish`: "Current HEAD is already released" while actual package is not released to npm

### ISSUE THREAD

**Issue by boxmein** [lerna/lerna#1709]
## Expected Behavior

When running `lerna publish`, and the command fails on the first run, fixing the issue and running `lerna publish` again should retry all actions that were not performed in the first publish run.

`lerna publish` should essentially be transactional. If any part of a `lerna publish` command fails, the project should be left unchanged.

## Current Behavior

Given a project with the following .npmrc:

    //registry.npmjs.org/:_authToken=${NPM_TOKEN}

If `$NPM_TOKEN` is left undefined, then running `lerna publish` will error at the `npm publish` step.

However, lerna will still create a Git tag, modify package.json, create a commit, and push the commit. 
On subsequent runs of `lerna publish` (the $NPM_TOKEN variable now being defined), lerna will not attempt to publish the package.

## Possible Solution

- Roll back changes to git after any step in the `lerna publish` pipeline fails, and don't automatically push the git repository to master. This prevents broken tags and commits (that don't actually correspond to a release) from being published. Additionally, that helps clean up the mess after a failed `lerna publish` since the only affected repo will be the developer's own computer.
- `lerna` should also not use Git as the source of truth for "has this package been deployed yet?". A perfectly valid alternative, such as `npm view $package_name version` exists.

## Steps to Reproduce (for bugs)
1. Create a private monorepo:
   1. lerna.json linked below
   2. one package named `"package-name-is-redacted"`
2. create npmrc in the monorepo root
3. clear the `NPM_TOKEN` variable
4. attempt to publish
5. set the NPM_TOKEN variable
6. attempt to publish again
7. run `npm view package-name-is-redacted version` - version has not changed

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv { _: [ 'publish' ],
0 silly argv   composed: 'publish',
0 silly argv   lernaVersion: '3.4.0',
0 silly argv   '$0': 'lerna' }
1 notice cli v3.4.0
2 verbose rootPath FOLDER_NAME_REDACTED
3 info versioning independent
4 info Verifying npm credentials
5 silly npm whoami received {"username":"username-redacted"}
6 silly argv { _: [ 'publish' ],
6 silly argv   composed: 'publish',
6 silly argv   lernaVersion: '3.4.0',
6 silly argv   '$0': 'lerna' }
7 verbose rootPath FOLDER_NAME_REDACTED
8 silly isAnythingCommitted
9 verbose isAnythingCommitted 1
10 silly currentBranch
11 verbose currentBranch master
12 silly isBehindUpstream
13 silly isBehindUpstream master is behind origin/master by 0 commit(s) and ahead by 1
14 silly hasTags
15 verbose hasTags true
16 silly git-describe.sync "@namespace/package-name-is-redacted@0.1.7-1-gc9b801c" => {"lastTagName":"@namespace/package-name-is-redacted@0.1.7","lastVersion":"0.1.7","refCount":"1","sha":"c9b801c","isDirty":false}
17 info Looking for changed packages since @namespace/package-name-is-redacted@0.1.7
18 silly diffSinceIn @namespace/package-name-is-redacted@0.1.7 packages/package-name-is-redacted
19 silly diff packages/package-name-is-redacted/filename.ts
20 verbose updated @namespace/package-name-is-redacted
21 verbose git-describe undefined => "@namespace/package-name-is-redacted@0.1.7-1-gc9b801c"
22 silly git-describe parsed => {"lastTagName":"@namespace/package-name-is-redacted@0.1.7","lastVersion":"0.1.7","refCount":"1","sha":"c9b801c","isDirty":false}
23 silly batched [ PackageGraphNode {
23 silly batched     name: '@namespace/package-name-is-redacted',
23 silly batched     externalDependencies: Map {},
23 silly batched     localDependencies: Map {},
23 silly batched     localDependents: Map {} } ]
24 silly gitAdd [ 'FOLDER_NAME_REDACTED/packages/package-name-is-redacted/package.json' ]
25 silly gitCommit Publish
25 silly gitCommit
25 silly gitCommit  - @namespace/package-name-is-redacted@0.1.8
26 verbose git [ 'commit',
26 verbose git   '-F',
26 verbose git   '/private/var/folders/v5/n8764vkn4yxbtk2hd3bnz8nc0000gq/T/4f0fdd4e-de18-4fd0-aa8c-5ebdc18199d8/lerna-commit.txt' ]
27 silly gitTag @namespace/package-name-is-redacted@0.1.8
28 verbose git [ 'tag',
28 verbose git   '@namespace/package-name-is-redacted@0.1.8',
28 verbose git   '-m',
28 verbose git   '@namespace/package-name-is-redacted@0.1.8' ]
29 info git Pushing tags...
30 silly gitPush origin master
31 silly batched [ PackageGraphNode {
31 silly batched     name: '@namespace/package-name-is-redacted',
31 silly batched     externalDependencies: Map {},
31 silly batched     localDependencies: Map {},
31 silly batched     localDependents: Map {} } ]
32 info publish Publishing packages to npm...
33 silly verifyNpmPackageAccess
34 warn ENOLICENSE Packages @namespace/package-name-is-redacted are missing a license
35 silly getCurrentSHA
36 verbose getCurrentSHA 75153849815af7e09f392f930a71263a498a63e3
37 silly getExecOpts FOLDER_NAME_REDACTED undefined
38 silly exec npm options { cwd: 'FOLDER_NAME_REDACTED',
38 silly exec   env: { npm_config_json: true },
38 silly exec   stdio: [ 'ignore', 'pipe', 'inherit' ] }
39 verbose pack [ '@namespace/package-name-is-redacted' ]
40 silly exec npm [ 'pack',
40 silly exec   'FOLDER_NAME_REDACTED/packages/package-name-is-redacted' ]
41 error Error: Command failed: npm pack FOLDER_NAME_REDACTED/packages/package-name-is-redacted
41 error
41 error     at makeError (FOLDER_NAME_REDACTED/node_modules/execa/index.js:174:9)
41 error     at Promise.all.then.arr (FOLDER_NAME_REDACTED/node_modules/execa/index.js:278:16)
41 error     at <anonymous>
```
</p></details>

## Context

This issue affects user experience - if I want to publish the repo but forget to define the environment variable, `lerna publish` currently prevents me from re-attempting to publish at all.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.0 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.9.4 |
| `node --version` | v8.11.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS | 10.14 |

**Comment by glebmachine** [comment]
i've got exacts the same error

**Comment by evocateur** [comment]
If your initial publish failed, but the version tags got pushed, you can recover by calling `lerna publish from-package`, which will publish any package whose version is not present in the configured registry, irrespective of current tag etc.
