### ISSUE TITLE
[Question] How to add pre release step?

### ISSUE THREAD

**Issue by Kikobeats** [lerna/lerna#1713]
I'm a happy user of `lerna`, but currently I have to modify some files (basically compiling a webpack bundle) before the `lerna publish` command.

Currently, I'm doing that creating a commit before the `lerna publish`:

<img width="951" alt="screen shot 2018-10-03 at 13 08 03" src="https://user-images.githubusercontent.com/2096101/46406917-68b51400-c70d-11e8-917d-a8b075d69cb2.png">

Although it works, it adds a lot of noise into the git history.

The thing that I want to achieve is to add these file in the same `lerna publish` commit

is it possible?

**Comment by evocateur** [comment]
Yes! Lerna runs the `version` (`preversion`, `version`, and `postversion`), `prepare`, `prepublishOnly`, and `pack` (`prepack` and `postpack`) lifecycles in the root during `lerna publish` in addition to those run in each leaf package.

1. root preversion
2. leaf preversion
3. leaf version
4. root version
5. leaf postversion
6. root postversion
7. root prepare
8. root prepublishOnly
9. root prepack
10. leaf prepublishOnly
11. leaf prepack
etc etc

**Comment by Kikobeats** [comment]
Thanks! I didn't see it evident to do.

I'm going to explore it and make a PR for improving the documentation

**Comment by evocateur** [comment]
Thanks, I appreciate it!
