### ISSUE TITLE
lerna run --parallel not working for rollup watch

### ISSUE THREAD

**Issue by tomwayson** [lerna/lerna#1714]
## Expected Behavior
I have a npm script `dev:umd` that runs rollup in watch mode, and I expect to be able to run `lerna run dev:umd --parallel` to start rollup watching files in any package w/ that script.

## Current Behavior
It runs the script but returns before the watch starts. See https://github.com/Esri/hub.js/pull/79 for command line output and further details.

## Possible Solution
Seems like the rollup output is not being interpreted as ongoing. Seems related to https://github.com/lerna/lerna/issues/826

## Steps to Reproduce (for bugs)
1. `git clone https://github.com/Esri/hub.js.git`
1. `git checkout 197b322607fe8c6522d6cd06ac400ba411477d8d`
1. `npm i`
1. `lerna run dev:umd --parallel`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0",
  "packages": [
    "packages/*",
    "demos/*"
  ],
  "version": "1.3.0"
}
```
</p></details>

## Context

I'm trying to run watch commands only in certain packages. npm scripts that run `tsc` in watch mode work w/ `lerna run --parallel`, but this one that runs `rollup` in watch mode does not. I can run rollup in watch mode from that directory (though due to dependency hoisting, I have to run `../../node_modules/.bin/rollup -w -c ../../umd-base-profile.js`).

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.8.0 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.9.4  (not using yarn in this monorepo though)|
| `node --version` | v8.11.4 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS El Capitan | 10.11.4 |

**Comment by tomwayson** [comment]
Thanks @CamBurris.

I was on an older version of rollup (`0.53.4`), but upgrading to the latest (`0.63.5`) did not help.

```bash
➜  hub.js git:(chore/upgrade-rollup) ✗ lerna run --scope=@esri/hub-auth dev:umd --parallel
lerna info version 2.8.0
lerna info scope @esri/hub-auth
lerna info run in 1 package(s): npm run dev:umd
@esri/hub-auth: > @esri/hub-auth@1.3.0 dev:umd /Users/tom/code/hub.js/packages/auth
@esri/hub-auth: > rollup -w -c ../../umd-base-profile.js
@esri/hub-auth: rollup v0.63.5
@esri/hub-auth: bundles ./src/index.ts → dist/umd/auth.umd.js...
lerna success run Ran npm script 'dev:umd' in packages:
lerna success - @esri/hub-auth
```

**Comment by CamBurris** [comment]
0.63.5 isn't the latest version of rollup. They are currently on 0.66.4. Watchers work for me on 0.66.1.

**Comment by tomwayson** [comment]
Thanks @CamBurris! I'm not sure how/why I only went up to 0.63.5, but you are right, after going to `0.66.4` it works!
