### ISSUE TITLE
include/exclude via CLI/configuration

### ISSUE THREAD

**Issue by brewster1134** [lerna/lerna#1718]
i know there is the ability to exclude packages using `private: true`, but is there a way to include or exclude certain packages via the CLI, or with a config entry? what i am trying to accomplish are, we have several different teams that consume these packages differently. for example, some teams might only need packages A, C and E, and other need B, and D. is the currently possible with existing lerna features?

**Comment by Siilwyn** [comment]
Assuming you are talking about the bootstrapping, yes with the flags: `--ignore` and `--private`. See `npx lerna bootstrap --help` for more information.

**Comment by evocateur** [comment]
Yes, the options are confusingly-named `--scope` and `--ignore` (I would  _like_ to rename them `--include` and `--exclude`, but it's pretty far down on my priority list). This is distinct from `"private": true` in a package.json, which only prevents that package from being published to a registry.
