### ISSUE TITLE
Changelog generation causes lerna version to fail

### ISSUE THREAD

**Issue by mattcosta7** [lerna/lerna#1720]
Running lerna publish generates a changelog and updates the package.json in each of my packages. Then calls lerna version, which fails due to the uncommited changes.

This succeeds if a canary flag is present, and did work in earlier versions (althought I don't recall offhand how far back it worked, as we haven't updated these packages on on a new private npm instance, and dont have access to the previous one to see)

## Expected Behavior

Lerna should commit the changes so that it can version and publish

## Current Behavior

lerna writes changelog and updates package.json versions then 

>my-repo@0.0.1 version /Users/costabma/workspace/my-repo
> npx lerna version

lerna notice cli v3.4.3
lerna info versioning independent
lerna info Looking for changed packages since my-package@1.10.4
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.

## Steps to Reproduce (for bugs)

1. write packages
2. lerna publish
3. fails due to the uncommitted changes

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "version": "independent",
  "command": {
    "publish": {
      "conventionalCommits": true,
      "message": "chore(release): publish"
    }
  }
}

```
</p></details>

## Context

Trying to publish my packages with generated changelog

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 6.4.2 |
| `node --version` | 10.10 |

| OS | Version |
| macOS Sierra | 10.12.3 |
| NAME | VERSION |

**Comment by mattcosta7** [comment]
npm run publish

[13:05:52] (develop) rotor-web-components
// $ npm run publish -- --log-level=silly

> rotor-web-components-monorepo@0.4.1 publish /Users/costabma/workspace/rotor-design-system/rotor-web-components
> npx lerna publish "--log-level=silly"

lerna notice cli v3.4.3
lerna info versioning independent
lerna info Verifying npm credentials
lerna http fetch GET 200 https://artifactory.dx.utc.com/artifactory/api/npm/npm/-/whoami 249ms
lerna info Looking for changed packages since @utdx/docs-site@1.10.4

Changes:
 - @utdx/rotor-icons: 0.23.0 => 0.24.0
 - @utdx/rotor-react-wc-shim: 0.1.0 => 0.2.0
 - @utdx/rotor-docs: 1.11.0 => 1.12.0 (private)
 - @utdx/rotor-web-components: 0.13.0 => 0.14.0

? Are you sure you want to publish these packages? Yes
lerna info lifecycle rotor-web-components-monorepo@0.4.1~version: rotor-web-components-monorepo@0.4.1

> rotor-web-components-monorepo@0.4.1 version /Users/costabma/workspace/rotor-design-system/rotor-web-components
> npx lerna version

lerna notice cli v3.4.3
lerna info versioning independent
lerna info Looking for changed packages since @utdx/docs-site@1.10.4
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.
lerna info lifecycle rotor-web-components-monorepo@0.4.1~version: Failed to exec version script
lerna ERR! lifecycle "version" errored in "rotor-web-components-monorepo", exiting 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rotor-web-components-monorepo@0.4.1 publish: `npx lerna publish "--log-level=silly"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rotor-web-components-monorepo@0.4.1 publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/costabma/.npm/_logs/2018-11-15T18_06_19_844Z-debug.log

**Comment by mattcosta7** [comment]
The issue is that the working tree does not have uncommited changes until I run publish.  it updates the changelog, and package.jsons, but fails to recommit them before continuing

**Comment by ThisIsMissEm** [comment]
Hi Matthew, 

Reading this, I believe it's a dupe of #1729. Check your package json for a preversion/version/postversion script.

Emelia

**Comment by mattcosta7** [comment]
it definitely is.  thanks!  makes total sense too.  closing, but commenting here in case anyone comes across this.

needed to remove a script "version" from the package.json to allow this to run correctly.
