### ISSUE TITLE
Getting an E404 for @lerna/run-parallel-batches@^3.0.0 when running on CI

### ISSUE THREAD

**Issue by tim-evans** [lerna/lerna#1721]
Hello! 👋 

I'm getting an `E404` from the npm registry for `@lerna/run-parallel-batches@^3.0.0` when running our test suite on TravisCI.

The [🏗 build](https://travis-ci.org/CondeNast-Copilot/atjson/builds/439682444) is failing out on `npm install` with `lerna`. I'm not sure if this is related to `npm` or this is related to `lerna` or this is something to do with TravisCI's npm installs (or I have a misconfigured `package.json`)

## Expected Behavior
`npm install` doesn't bail out on `@lerna/run-parallel-batches@^3.0.0`.

## Current Behavior
`npm install` fails, giving a 404 error on `@lerna/run-parallel-batches@^3.0.0`.

## Steps to Reproduce (for bugs)
1. Rerunning https://travis-ci.org/CondeNast-Copilot/atjson/builds/439682444 on TravisCI consistently fails

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "packages": [
    "packages/@atjson/*"
  ],
  "command": {
    "publish": {
      "exact": true,
      "conventionalCommits": true,
      "changelogPreset": "./packages/@atjson/conventional-changelog-emoji"
    },
    "bootstrap": {
      "hoist": true,
      "npmClientArgs": [
        "--no-package-lock"
      ]
    }
  }
}
```
</p></details>

## Context
This is affecting me because I'm trying to merge in / publish a pull request! 😄 

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 8.12.0 |
| `node --version` | 6.4.1 |

| OS | Version |
| --- | --- |
| Ubuntu | 14.04.5 |

**Comment by tim-evans** [comment]
I'm still encountering this; it looks like something related to TravisCI; thanks for the help! ❤️

**Comment by arumsey** [comment]
I just tried running `npm install lerna -g` on MacOS and got the same error. No TravisCI in the picture for me.

`node --version = 10.3.0`
`npm --version = 6.4.1`

**Comment by arumsey** [comment]
I also tried `npm install @lerna/run-parallel-batches` for fun and got the same 404 error.

I can however load `https://registry.npmjs.org/@lerna%2frun-parallel-batches` into a browser so it seems to be more node related than an actual network issue.

**Comment by arumsey** [comment]
I deleted my `~/.npmrc` file and the install then worked. All good now but still not sure why it occurred.

**Comment by tim-evans** [comment]
It’s an invalid npm token. I resolved this through the lovely npm folks

**Comment by kitho-pwc** [comment]
Not understand too
