### ISSUE TITLE
RFC: Watch mode

### ISSUE THREAD

**Issue by andreytrofimov** [lerna/lerna#1722]
## Problem statement
Current behaviour of `lerna exec`: commands execute in a topologically sorted order. Lerna waits for commands in package dependencies to finish before moving on. This will block execution when you run "watch" commands, since they typically never end. 

There is a workaround for “watch” commands to use `--parallel` and `--concurrency=9999` flags, but it has some drawbacks:

* dependent packages usually need output files from their dependencies (that are generated during “watch”). Attempt to “watch” all packages in parallel with missing files leads to errors.
* it's possible to build all packages first and then run watchers in parallel. But it is not optimal, because it basically requires to do the work twice (typically “watch” is doing the “build” under the hood).

## Change proposal
Add some way for executed commands to tell lerna that it can proceed execution for dependent packages. This could be done via an event that is sent through node’s child_process IPC channel, or via 3rd party IPC library.

On webpack side it could be a simple plugin that sends a message to lerna on `afterEmit` event.

## Questions
What mechanism to use to send messages?

* this could be a node’s child_process IPC channel (https://nodejs.org/api/child_process.html#child_process_options_stdio)
    * pros:
        * It built into node.js and don’t require any dependencies
        * It is simple to use when IPC channel established
    * cons:
        * The running command should be a node.js process, so it is not possible to use scripts on other languages.
        * To use IPC channel, executed command should run without any intermediaries (i.e. this may not be a `npm run watch` that runs another command).

**Comment by evocateur** [comment]
I don't see this as within Lerna's scope. Lerna isn't a watcher interface, nor does it provide one. There are packages available to retrieve Lerna's topological computation without burdening `lerna exec` with additional complexity.

**Comment by kanoshin** [comment]
@evocateur do you have any suggestions/best practices regarding development with watch in monorepos? I'm pretty sure that many developers are having trouble figuring this out. Approach with `--parallel` is very far from ideal.

**Comment by kanoshin** [comment]
> There are packages
Could you also please give a clue regarding where to find those.

**Comment by evocateur** [comment]
General CLI:
https://www.npmjs.com/package/chokidar-cli
https://www.npmjs.com/package/nodemon
https://www.npmjs.com/package/onchange

Babel + Rollup:
https://www.npmjs.com/package/@pectin/cli

Programmatic API:
https://www.npmjs.com/package/glob-watcher
