### ISSUE TITLE
lerna create @package-name --es-module

### ISSUE THREAD

**Issue by lifeiscontent** [lerna/lerna#1723]
Hi, I was wondering if there is an example setup that follows the default structure of --es-module using babel or some other build tool?

**Comment by evocateur** [comment]
Sorry about the bot noise. I don't believe we have anything documented, as such. [Pectin](https://github.com/evocateur/pectin#pectin) is a tool I wrote to streamline modules created with `lerna create --es-module`, it works out of the box with #zero-conf.

**Comment by lifeiscontent** [comment]
@evocateur sorry, not a fan of rollup. it minifies modules in a way that doesn't personally make sense to me. I'd rather just use a pure babel solution.

**Comment by evocateur** [comment]
Babel isn't a module bundler, Rollup isn't a transpiler, and I wasn't aware I was stopping you from creating your own solution.
