### ISSUE TITLE
Lerna creates an undefined@null tag if packages/ folder contains a non-package

### ISSUE THREAD

**Issue by ChrisBAshton** [lerna/lerna#1724]
If we have a folder:

```
packages/
    package-1/
        package.json
    package-2/
        package.json
    helpers/
        (there is no package.json in this folder)
```

## Current Behavior
...when we run `lerna publish --independent`, we're prompted to define a version for `undefined` package, and at the end of the publish, lerna has created an `undefined@null` tag and pushed that tag to GitHub.

## Expected Behavior
I would expect Lerna to skip over any directories in `packages/` that are missing a `package.json`.

## Possible Solution
Check for the presence of `package.json` in each `packages/` subdir and either skip or warn if missing.

## Steps to Reproduce (for bugs)

1. Create an empty subdir in your `packages/` folder
2. Run `lerna publish --independent`

## Context
We have a fair bit of shared code that our packages rely on, but that shouldn't be published independently in their own right.

Perhaps we should move the helper code outside of the `packages/` directory - but then the code feels somewhat disconnected. We'd prefer to keep them close together.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | n/a |
| `node --version` | 9.11.1 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.3 |

**Comment by ChrisBAshton** [comment]
True, it should probably be a package. Happy to close.

But this still feels like a bug - worth catching with a validation error ("One of the directories under packages/ is missing a package.json!") or just skipping altogether.

**Comment by ThisIsMissEm** [comment]
I'd agree with this warning; thoughts @evocateur?

**Comment by evocateur** [comment]
It's weird that the directory lacking a package.json is getting found in any case.
