### ISSUE TITLE
Question: ignore tagging of private packages

### ISSUE THREAD

**Issue by priley86** [lerna/lerna#1725]
Is there any way possible to ignore private packages from tagging and/or releases? I.e. I have a repo like the following:

```
patternfly-lerna-root (private / not released)
---> patternfly3 (private / not released)
------> patternfly-package-A (public/released)
------> patternfly-package-B (public/released)
---> patternfly4 (private / not released)
------> patternfly-packageC (public/released)
------> patternfly-packageD (public/released)
```

Currently I have marked patternfly3 and patternfly4 packages as `private:true` since they are simply specifying the specific build and lint dependencies for those major versions of our project, however they should not be released or tagged. This is creating multiple entries in our lerna-changelog for the package "roots":
https://github.com/patternfly/patternfly-react/blob/master/CHANGELOG.md

Can you suggest any simple way to exclude those packages?

**Comment by evocateur** [comment]
Don't address them as lerna packages? This is how lerna itself uses [test-only packages](https://github.com/lerna/lerna/blob/eae5619840c385fdebceadfca8f280a515ddd445/package.json#L27-L55) that are never versioned or included in changelogs.

**Comment by slawiko** [comment]
@evocateur is works only for "test-only packages", but what if we want to have some package to be built in monorepo, but we marked them as `private`? Currently we have a huge amount of unused git tags which is very annoying. Would be good if `lerna publish` will have some flag for skipping private packages from being git-tagged

**Comment by evocateur** [comment]
Unclear to me why you need lerna to manage those private packages. Relative `file:` paths work just fine, the "test-only" pattern I linked earlier is by no means limited to "test-only" packages.

**Comment by slawiko** [comment]
> Unclear to me why you need lerna to manage those private packages. Relative `file:` paths work just fine, the "test-only" pattern I linked earlier is by no means limited to "test-only" packages.

but what if we want to use `lerna run` in those packages?

**Comment by buz-zard** [comment]
I have a `demos/*` and `packages/*` file structure and relative `file:../../packages/*` paths don't seem to work fine with yarn. For me package updating is odd I always have to delete node_modules for `:../../packages/*` changes to be caught also the `interactive-upgrade` is also affected - some upgradable packages simply aren't shown.

Anyway these are yarn issues, but maybe you would reconsider that skipping tagging is viable feature request?

**Comment by Codermar** [comment]
Why has this issue been so stubbornly ignored for so long? and why is it closed? It is ABSOLUTELY annoying having to manually manage the tags created to PRIVATE packages. Why can't this just be fixed by providing a flag?

**Comment by m-mayank** [comment]
Any update on this issue please, i am also facing the same issue while having the release branches managed by lerna.

**Comment by m-mayank** [comment]
Just found lerna does not publishes the private packages is we use `--no-private` flag in publish command.

Reference: https://github.com/lerna/lerna/tree/master/commands/version#--no-private

**Comment by karolis-sh** [comment]
As @m-mayank mentioned, from [`lerna@3.21.0`](https://github.com/lerna/lerna/blob/master/CHANGELOG.md#3210-2020-05-13) `--no-private` flag solves this 🎊
