### ISSUE TITLE
Using the '--since' argument results in "error: unknown option 'first-parent'" on CentOS7

### ISSUE THREAD

**Issue by busybeaver** [lerna/lerna#1726]
## Expected Behavior

Using the `--since` argument works as expected on CentOS7, without resulting in an error.

## Current Behavior

When running lerna commands with the `--since` argument on CentOS7, we receive the following error (see the _lerna-debug.log_ for more details):
`Error: Command failed: git describe --always --long --dirty --first-parent; error: unknown option 'first-parent'`.

The issue seems to be related to a rather old version of git that CentOS7 is using: 1.8.3.1

It seems this problem isn't exclusive to lerna:

* ansible/awx/issues/985
* palantir/gradle-git-version/issues/63
* ansible/awx/issues/1045
* google/earthenterprise/issues/1032

It works fine on OSX.

## Possible Solution

An obvious solution would be to update the git version. However, the issues happen on our CI build servers (which for some reason use CentOS), so I can - unfortunately - not really change the environment lerna runs on since these machines aren't maintained by me/RnD. But maybe there is an workaround in lerna to make it work with this (old) git version.

## Steps to Reproduce (for bugs)

1. Use CentOS7 (or just git version 1.8.3.1)
2. Run a lerna command with the `--since` argument

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "command": {
    "publish": {
      "conventionalCommits": true,
      "allowBranch": [
        "master"
      ],
      "message": "chore: publish",
      "sign-git-commit": true,
      "sign-git-tag": true,
      "temp-tag": false,
      "npmClient": "npm"
    }
  },
  "ignoreChanges": [
    "**/*.md",
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "reject-cycles": true,
  "sort": true
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv { _: [ 'ls' ],
0 silly argv   long: true,
0 silly argv   l: true,
0 silly argv   since: '',
0 silly argv   lernaVersion: '3.4.1',
0 silly argv   '$0': '/home/ciuser/buildAgent/work/8e4dd23f31c094a1/node_modules/.bin/lerna' }
1 notice cli v3.4.1
2 verbose rootPath /home/ciuser/buildAgent/work/8e4dd23f31c094a1
3 info versioning independent
4 info filter [ '!@rnd-mannheim/lp-authentication',
4 info filter   '!@rnd-mannheim/documentify' ]
5 silly hasTags
6 verbose hasTags true
7 error Error: Command failed: git describe --always --long --dirty --first-parent
7 error error: unknown option `first-parent'
7 error usage: git describe [options] <committish>*
7 error    or: git describe [options] --dirty
7 error
7 error     --contains            find the tag that comes after the commit
7 error     --debug               debug search strategy on stderr
7 error     --all                 use any ref
7 error     --tags                use any tag, even unannotated
7 error     --long                always use long format
7 error     --abbrev[=<n>]        use <n> digits to display SHA-1s
7 error     --exact-match         only output exact matches
7 error     --candidates <n>      consider <n> most recent tags (default: 10)
7 error     --match <pattern>     only consider tags matching <pattern>
7 error     --always              show abbreviated commit object as fallback
7 error     --dirty[=<mark>]      append <mark> on dirty working tree (default: "-dirty")
7 error
7 error
7 error
7 error     at makeError (/home/ciuser/buildAgent/work/8e4dd23f31c094a1/node_modules/@lerna/child-process/node_modules/execa/index.js:174:9)
7 error     at Function.module.exports.sync (/home/ciuser/buildAgent/work/8e4dd23f31c094a1/node_modules/@lerna/child-process/node_modules/execa/index.js:338:15)
7 error     at Object.execSync (/home/ciuser/buildAgent/work/8e4dd23f31c094a1/node_modules/@lerna/child-process/index.js:22:16)
7 error     at Function.sync (/home/ciuser/buildAgent/work/8e4dd23f31c094a1/node_modules/@lerna/describe-ref/lib/describe-ref.js:44:31)
7 error     at collectUpdates (/home/ciuser/buildAgent/work/8e4dd23f31c094a1/node_modules/@lerna/collect-updates/collect-updates.js:24:56)
7 error     at chain.then.filteredPackages (/home/ciuser/buildAgent/work/8e4dd23f31c094a1/node_modules/@lerna/filter-options/lib/get-filtered-packages.js:17:23)
```
</p></details>

## Context

This issue prevents us to use lerna in our CI environment (running it also in CI is obviously a must if we want to use lerna at all). Not sure if the `first-parent` argument is necessary/required for lerna to work properly... if so, maybe you can think of a workaround to to circumvent the issue (via a code change/fix or via configuration).

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.1 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.10.1 |
| `node --version` | 8.12.0 |
| `git --version` | 1.8.3.1 |

| OS | Version |
| --- | --- |
| CentOS | 7 (3.10.0-862.9.1.el7.x86_64) |

**Comment by 1234567atv** [comment]
![15977830_1181849395269993_8320618178533171456_n](https://user-images.githubusercontent.com/24604748/47604550-1c0ae300-da04-11e8-8c57-85dcf7d819da.jpg)

**Comment by ThisIsMissEm** [comment]
I'd say the solution to this problem is to update `git`, as at some point lerna needs to depend on certain features to perform certain functionality. Do you need to use the `--since` command as it's unsupported given your system configuration?

**Comment by evocateur** [comment]
`--since` needs a certain level of Git support, which could likely be better communicated/error-handled, but isn't going to be "fixed" by Lerna.

**Comment by slawiko** [comment]
@evocateur at least documented. You suppose that your customers use the same version as you? That's bold assumption :)
