### ISSUE TITLE
bootstrap --hoist should imply --no-ci

### ISSUE THREAD

**Issue by vidartf** [lerna/lerna#1728]
Recently after upgrading my lerna (from 2.x to 3.x), my CI broke. Everything worked normally locally though, so I started googling the error, which was related to `npm ci`. After a bit of digging, I found out that lerna was using `npm ci` instead of `npm install` if it detected it was on CI. I was using `lerna bootstrap --hoist`, and a bit of searching led me to an statement that `npm ci` cannot be used with the `--hoist` option. As such, I am led to believe that the `--hoist` option should imply `--no-ci`.

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | N/A |
| `node --version` | 10.11.1 |

CI platforms of failure: Travis (linux) + Appveyor

**Comment by evocateur** [comment]
At least for the root install, sure. I'd recommend migrating away from `lerna bootstrap`, however. It's days are numbered.

**Comment by doug-wade** [comment]
I tried to take a swing at this one, but I couldn't find a `no-ci` option in bootstrap, either in `command.js` defined for yargs, or in `index.js` the body of the command.  This leaves the tests failing with

```
    Implications failed:
     hoist -> no-ci
```

Am I missing something?

**Comment by evocateur** [comment]
@doug-wade The conditional assignment [here](https://github.com/lerna/lerna/blob/16611be12d684e6e6b549a2164c689426fc0313e/commands/bootstrap/index.js#L74) needs to be guarded better, nothing needs to change in the options config.

**Comment by evocateur** [comment]
This has been implemented in a recent release.

**Comment by sohkai** [comment]
@evocateur Curious about

> At least for the root install, sure. I'd recommend migrating away from `lerna bootstrap`, however. It's days are numbered.

Is there documentation available for migrating off of `bootstrap`? Should we use `link` instead?

**Comment by evocateur** [comment]
@sohkai run `npx lerna link convert` once, then just `npm install` (or `npm ci`) in the root.
