### ISSUE TITLE
Is there a way to use the modules in the lerna mono repo without publishing. 

### ISSUE THREAD

**Issue by nanandn** [lerna/lerna#1730]
Is there a way to use the modules in the lerna mono repo without publishing? I am working on new components as well an application that uses those components. I am not ready to publish yet. 

I have a lerna mono repo with components

1. Component A
2. Component B which depends on Component A. I have Component A as dependency in Component B's package.json

I have an application that depends on Component B. When I run yarn install in my application, I get an error saying cannot find component A required by component B. 

I have linked Component B in my application using yarn link. 

What's the best (recommended) way to use the modules in the mono repo without publishing?

Thanks
Anand

**Comment by evocateur** [comment]
Yes, but you need to `lerna bootstrap` in the monorepo, too. This means that if your leaf packages require a build, they must also be built for the linked application's import to succeed.

**Comment by cdtinney** [comment]
To clarify @evocateur's comment:

1. Run `lerna bootstrap` in root to link component B to component A
1. Build Component A (`yarn build`?)
    * If you are developing component A in parallel, you'll need to run a server with live reloading to update the build
