### ISSUE TITLE
Command Line Option --npm-tag Has No Effect

### ISSUE THREAD

**Issue by pahund** [lerna/lerna#1733]
I've updated from Lerna 2 to Lerna 3. When I try to publish a beta version, I use the command line option `--npm-tag beta`. Since the update, Lerna seems to completely ignore that option. 

I'm also able to reproduce this issue with a brand new repository bootstrapped with Lerna 3.

## Current Behavior

* Create a new monorepo with Lerna 3 as described in [Getting Started](https://github.com/lerna/lerna#getting-started)
* Add at least one package
* Execute command: `npx lerna publish premajor --npm-tag beta`

Output from Lerna:

```
Changes:
 - @lerna-test-pahund/hello1: 0.0.1 => 1.0.0-alpha.0
 - @lerna-test-pahund/hello2: 0.0.1 => 1.0.0-alpha.0
```

## Expected Behavior

* Create a new monorepo with Lerna 3 as described in [Getting Started](https://github.com/lerna/lerna#getting-started)
* Add at least one package
* Execute command: `npx lerna publish premajor --npm-tag beta`

Output from Lerna:

```
Changes:
 - @lerna-test-pahund/hello1: 0.0.1 => 1.0.0-beta.0
 - @lerna-test-pahund/hello2: 0.0.1 => 1.0.0-beta.0
```

(Lerna should pick up the command line option `--npm tag beta` and set the version accordingly)

## Steps to Reproduce (for bugs)

Example repository: https://github.com/pahund/lerna-test-pahund

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```
</p></details>

## Context

How has this issue affected you? I can only release prerelease versions with npm tag “alpha”, not custom, e.g. ”beta”

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 6.4.1 |
| `node --version` | 8.9.4 |

| OS | Version |
| --- | --- |
| macOS High Sierra  | 10.13.6 |

**Comment by SpookyCorridor** [comment]
The npm tag is for tagging at the repository level ... so in this case 1.0.0-alpha.0 would be linked to the beta tag at the repository you're publishing to. Users would recieve 1.0.0-alpha.0 by requesting it with `npm install component@beta` 

What you're looking for is to change the actual semver tag name which can be done with --preid 

`npx lerna publish premajor --preid beta` will give you 1.0.0-beta.0

**Comment by pahund** [comment]
👍🏻 Thanks for clearing this up

Two things I'm still confused about:

* Do I have to use both *preid* and *npm-tag* to have a beta release to the npm repository? If I use only *preid*, I get the correct version `1.0.0-beta.0`, but it's not tagged as beta version in the npm registry; would `npx lerna publish premajor --preid beta --npm-tag beta` be the correct command?

* After publishing a beta version with *premajor --preid beta*, how can I update the beta version, e.g. to version `1.0.0-beta.0`?

**Comment by SpookyCorridor** [comment]
Yes preid is only for git and npm-tag is for npm distribution. If you don't specifcy an npm-tag it defaults to "latest".

**Comment by evocateur** [comment]
`--npm-tag` controls the dist-tag, not the semver `--preid`. The two are actually orthogonal, you can use any string identifier as a dist-tag, it's just a pointer to a given version, which is an arbitrary semver-compatible string.

So yes, a prerelease that uses the `beta` preid under the `beta` dist-tag would need to use _both_ `--npm-tag` and `--preid` options.
