### ISSUE TITLE
Feature request: package registry migration

### ISSUE THREAD

**Issue by korob93** [lerna/lerna#1734]
## Expected Behavior
It would be nice to be able to publish monorepo packages to another npm registry.
In this scenario we do not need incrementing package version or doing some git stuff, just resolving local dependency links (so `lerna exec "npm publish --registry=http://my.new.registry"` doesn't always fit)

## Current Behavior
As you know, now `lerna publish` does resolve local dependency links, but it also increments package versions and commits to git

## Possible Solution
I think it could be achieved by adding a new lerna command. Something like `lerna migrate http://my.new.registry` or stuff like that, which can also modify `.npmrc` or `package.json` configuration to set new npm registry url (or maybe not)

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 5.6.0 |
| `node --version` | 8.11.4 |

| OS | Version |
| --- | --- |
| Ubuntu | 18.04 |

**Comment by ThisIsMissEm** [comment]
I think this might be possible by modifying `lerna publish` to support a `--mirror` option which adds a different path to [findVersionedUpdates](https://github.com/lerna/lerna/blob/master/commands/publish/index.js#L179-L191) which would just return all the packages and their current versions

**Comment by evocateur** [comment]
This will largely be fixed by #1708 , no extra complexity required.
