### ISSUE TITLE
How to retrieve a repository environment variable inside a module ?

### ISSUE THREAD

**Issue by ludogithub** [lerna/lerna#1739]
Hi,

I'm working on a VueJS app (+ webpack + lerna) with the following code architecture :

package.json
lerna.json
packages/
modules/
plugins/
All the submodules (modules + packages) make calls to a REST API.

So far the REST API URL is defined during the build step using webpack DefinePlugin, either directly inside the code, either with a cross-env command :

cross-env API_URL=http://www.the_api_url.com npm run bootstrap --hoist

I would like the REST API URL to be defined when the server starts (not during the build) using repository environment variables (process.env at the root of the repository).

I tried having a .env file at the root, but it didn't manage to access its data inside a module. The module seems to be only reading its own .env file.

Do you have any solution or can you point me into the right direction to obtain the same result in another way ?

Thanks, Ludovic

**Comment by evocateur** [comment]
A `.env` file sounds like you're trying to use [dotenv](https://www.npmjs.com/package/dotenv) or something like it. Absolutely orthogonal to Lerna.
