### ISSUE TITLE
[Internal] Lerna should be a lerna repo

### ISSUE THREAD

**Issue by gigabo** [lerna/lerna#174]
Straw man proposal: Every lerna command should be a dedicated package in a lerna repo.
- `lerna-bootstrap`
- `lerna-publish`
- ...

They should live along side:
- `lerna-core`: Exposes a programmatic API (`Package`, `Command`, `Repository`, etc).
- `lerna-cli`: Exposes commands via `lerna <command>`.

Benefits:
- Lerna can serve as its own demonstration.
- Can [share test helpers](https://github.com/lerna/lerna-changelog/pull/18#issuecomment-223697607) and other infrastructure between packages.
- Can generate a changelog using [`lerna-changelog`](https://github.com/lerna/lerna-changelog).
- Self hosting is cool.  So is eating your own dog food.
- Commands can be pluggable.
  - A dev can publish `lerna-frobnicate` and let people `lerna frobnicate`.
  - Awesome commands can be easily pulled into the project with [`lerna import`](https://github.com/lerna/lerna/pull/173).

There it is.  Tear it apart. :feelsgood:

**Comment by thejameskyle** [comment]
Hmm that would be interesting to play around with

**Comment by Alxandr** [comment]
This has been sitting here for more than half a year with one comment and lots of positive reaction-emojis. Should this maybe be added to the new v2.0 milestone? Also, do you want someone to work on this?

**Comment by evocateur** [comment]
I'd be interested in driving this, I have some hacking time at work coming up soon.

**Comment by dylang** [comment]
Would be helpful to have an api to get the array of package paths.

**Comment by light24bulbs** [comment]
What is the state of the programmatic API?  Was any progress made on invoking lerna from nodejs directly?

**Comment by evocateur** [comment]
Aside from a lack of explicit documentation, all of the individual commands are callable from node directly. All of the internals previously exposed as named exports are also available as distinct packages.

That being said, there is no (useful) main entry of the `lerna` package itself, and that could certainly be improved.

**Comment by light24bulbs** [comment]
@evocateur that's interesting!  Are you saying I can do `const lerna = require('lerna')`?  Doesn't seem to be working for me. 
What are the commands that are exposed?  For posterity, can you give an example of invoking a Lerna command from node?

Scriptability could go a long way towards making Lerna more extensible.  If you look at a package like Webpack, it eventually won out because it was SO extendable.

**Comment by evocateur** [comment]
@light24bulbs 

> Are you saying I can do `const lerna = require('lerna')`?

No, sorry, that's what I meant with "no (useful) main entry". I don't see a huge bonus from that entry, given the myriad individual packages now available.

> What are the commands that are exposed?

Literally [all of them](https://www.npmjs.com/search?q=keywords%3Alerna%20command&ranking=quality) (with the `@lerna` scope, I couldn't figure out how to filter that part of the search). Here's how you could run `lerna publish` without the CLI:

```js
'use strict';

const lernaPublish = require('@lerna/publish');

module.exports = main;

async function main() {
  const cfg = {
    cwd: process.cwd(),
    // additional options...
  };

  await lernaPublish(cfg);
  // nothing really useful returned by the command factory,
  // but you can chain `.then()` and `.catch()` if you wanna

  console.log('🎉');
}
```

> Scriptability could go a long way towards making Lerna more extensible.

It's great that Webpack is so flexible. It's not really one of the goals of lerna right now, especially with so few active maintainers. My focus right now is to make `lerna` a first-class CLI, using `stdout` and exit codes effectively to create compound behavior via pipe chains (the [unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy)).
