### ISSUE TITLE
The lerna build is very slow, always (+30 minutes)

### ISSUE THREAD

**Issue by ludogithub** [lerna/lerna#1740]
Hi,

I'm just joining a new VueJS / Webpack based on a Lerna code architecture :

package.json
lerna.json
packages/
modules/
plugins/

Approximately each page of the application has been set as a separated module which I find strange and although not an expert I'm not sure this is the correct way of setting up a Lerna architecture.

Nevertheless, the package.json defines the following :

"scripts": {
"bootstrap": "npm install && npm run lerna && npm run app-build",
"lerna": "lerna bootstrap --hoist --nohoist=axios --nohoist=vue-chartist --nohoist=chardist",
"publish": "lerna publish",
"clean": "lerna clean",
"test": "lerna run test --parallel",
"start": "lerna run start --stream --scope=main-module",
"app-build": "lerna run build --stream --scope=main-module",
"doc": "good-doc"}

And the app, although of medium size I would say (500Mo with node_modules, 8 modules, 6 packages, 6 plugins) takes always+30 minutes to build (lerna bootstrap). At each build. The builds are executed like this :

cross-env BACK_URL=back_url npm run bootstrap --hoist

The team seems not to use publish and update functionnalities.

Is there any good pratices to have a quicker build ? Any ideas of what could have been set wrong in my project ? Or maybe this is just normal...

Many thanks, Ludovic

**Comment by evocateur** [comment]
Lerna just runs things, it is not the reason your build is slow. I would recommend migrating away from `lerna bootstrap --hoist` and instead run `lerna link convert` once and then you only need to `npm install` once in the root from then on.

(also, it's extremely weird to call `npm install` from inside an npm script)
