### ISSUE TITLE
Template for created projects

### ISSUE THREAD

**Issue by raijinsetsu** [lerna/lerna#1742]
It would be great if we could specify one or more templates in the lerna.json to simplify the creation of new packages.

## Possible Solution
In the lerna.json file, add a new property which is a map of the template name to the directory containing the template. Example:
``` json
{
    "templates": {
        "plugin": "templates/plugin"
    }
}
```
In the "template/plugin" folder, I would have an index.js file which can be used to build the files or make modifications. Lerna would need to pass various pieces of information on the cli:
- output directory (ex. packages/{package name})
- package name

Then, from the command line:
``` bash
lerna create --from-template plugin project-plugin-b
```
Lerna would do what it currently does (generating some standard directories and files) and then invoke the plugin.

Thoughts?

**Comment by evocateur** [comment]
I think this is functionality better-suited to an external tool. `npm init` has plenty of customization options nowadays.

**Comment by raijinsetsu** [comment]
The functionality is already a part of Lerna - it has a built-in template that is uses when creating new packages. It's just not exposed to users.
Your argument would be to remove the "lerna create" command completely and rely on existing templating tools?

**Comment by evocateur** [comment]
>  remove the "lerna create" command completely and rely on existing templating tools?

Yes, essentially. There are too many cross-cutting concerns for a module initializer, I should have never added this command (which fulfills my own requirements,  as I extracted it from a private tool I wrote).

It (and many other esoteric subcommands) would be better as a pluggable CLI, like git allows `git-{addon}` executables found in the path to be called as `git {addon}` and so forth.

You're basically asking to support [`--init-module`](https://docs.npmjs.com/misc/config#init-module), but `lerna create` has _way_ too tightly-coupled filesystem modifications to make any third-party module initializer tractable. Of course, one could always bail early if `--init-module` was customized, but then you might as well run `npm init --init-module=my-initializer-module`?

**Comment by danm** [comment]
Whats the advice here? make our own scripts which drop a bunch of config templates rather than use `lerna create`

for example, creating a `src` directory, and a test folder which generates a `.ts` file rather than javascript?

do I need to do anything to let lerna know that new package exists? not sure what magic `create` does which is necessary.

Or is this all that is needed...
```
{
  "packages": [
    "services/*"
  ]
}
```

**Comment by evocateur** [comment]
`lerna create` is just a fancy wrapper around `npm init`. You can literally `mkdir packages/foo && cd packages/foo && npm init` and it will work. Use whatever `create-*` module to do the TS templating, or just use a Yeoman generator.

**Comment by JamesHenry** [comment]
Hi Folks 👋

There have been a number of duplicate/highly related issues concerned with customizing new package creation.

I have therefore created a single source of truth for all future development and planning in this area here: #3444

Please kindly subscribe to/upvote that issue if you interested in this capability!

Many thanks 🙏
