### ISSUE TITLE
hoisting of ts-loader importing incorrect typescript package

### ISSUE THREAD

**Issue by mikehaas763** [lerna/lerna#1743]
## Expected Behavior

I'm not sure that this is a bug. I'm looking for some help.

## Current Behavior

We are using hoisting with `lerna bootstrap`. From my package `A`, `webpack` and `ts-loader` are hoisted. `typescript` is not hoisted from `A` because a couple of other packages depend on a newer version of typescript. A newer version is instead hoisted. This causes issues because my build now uses the incorrect version of typescript when building project `A`.

When I run `npm run build` from package `A`, it invokes webpack via a local `.bin` tool that is symlinked up to the parent folder packages (since webpack is hoisted). Webpack pulls in ts-loader from the parent node_modules dir. ts-loader expects the project to have its own dependency on typescript, and so it imports it. The problem is that my project `A` has it's own version of typescript declared, but it's not being used because when ts-loader imports typescript, it's getting that newer version since it's already in a more parent node_modules.

Is this an issue with the ts-loader and webpack tooling that needs to be fixed? If so, does anyone have a recommended fix for this type of thing?

Does lerna provide anything directly to help with this issue?

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.0 |
| `npm --version`  | 6.4.1 |
| `node --version` | 8.12.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.13.6 |

**Comment by evocateur** [comment]
I would say you need to harmonize the version of `typescript` used in a given monorepo. Otherwise, I'm not sure that outdated dependent really belongs in that monorepo (if it _can't_ be updated, why is it different from the others to such a degree?).

**Comment by mikehaas763** [comment]
One valid use case would be incremental upgrades (especially in really large code bases), since typescript in strict mode is not backward compatible. In the same vein, as type inference gets better with newer versions of typescript, type errors can occur that are not behind configuration options

**Comment by evocateur** [comment]
Sounds like a job for codemods, tbh

**Comment by mikehaas763** [comment]
True, that is an option, but for the constraints of many, incremental updates are a must. In my use case, we just turned hoisting off as it was causing more problems than it was worth for brownfield systems, so I don’t personally need this capability anymore

**Comment by JamesHenry** [comment]
Oh hai @mikehaas763 👋 I hope you're well!

I'll close this one out
