### ISSUE TITLE
Despite repeated calls for a new code of conduct by developers, 

### ISSUE THREAD

**Issue by SRGOM** [lerna/lerna#1744]
@jamiebuilds and pink haired women, the owners of this project have failed to take action. . I invite everybody to pressure the owners into adopting a CoC. SQLite recently adopted one and I like it's tone.

**Comment by vroudge** [comment]
If we could focus on code instead of drama that'd be nice

**Comment by evocateur** [comment]
@SRGOM This is your first and only warning. Adhere to our [code of conduct](https://github.com/lerna/lerna/blob/master/CODE_OF_CONDUCT.md), or find another project.
