### ISSUE TITLE
Feature Request: lerna publish --prerelease-only

### ISSUE THREAD

**Issue by mattfelten** [lerna/lerna#1748]
We have a npm script to do a full release to `latest` and an additional npm script to make a beta release to the `next` tag. That way we don't accidentally put in the wrong tag. 

I've recently run into issue cutting beta releases where we've accidentally done a full `minor` release to our `next` tag instead of a `preminor`. I'd love if there was an option with `lerna publish` that only displays the `premajor | preminor | prepatch | prerelease` instead of all the options.

```
$ lerna publish
? Select a new version (currently 1.0.0) (Use arrow keys)
❯ Patch (1.0.1)
  Minor (1.1.0)
  Major (2.0.0)
  Prepatch (1.0.1-alpha.0)
  Preminor (1.1.0--alpha.0)
  Premajor (2.0.0--alpha.0)
  Prerelease
  Custom
```

Request
```
$ lerna publish --prerelease-only
? Select a new version (currently 1.0.0) (Use arrow keys)
❯ Prepatch (1.0.1-alpha.0)
  Preminor (1.1.0--alpha.0)
  Premajor (2.0.0--alpha.0)
  Prerelease
  Custom
```

**Comment by mattfelten** [comment]
The patch, minor, major options are actually helping remove user error the most. `prerelease` seems to be a black box to do anything, which might make the issue worse. I'll try it out though. My request above would still help.

**Comment by SpookyCorridor** [comment]
I still don't really see the problem? You can also use prepatch/preminor/premajor as the positional and set the --preid to whatever you want instead of "alpha"

**Comment by mattfelten** [comment]
It's less a problem and more of an improvement for us. Everything works fine now except for user error. We have npm scripts that are doing build steps and then running `lerna publish`.

```
"scripts": {
        "release": "npm run build && lerna publish --npm-tag latest",
        "alpha": "npm run build && lerna publish --npm-tag next"
}
```

I could create 6 new scripts specifically setting the patch/minor/major but that seems a bit excessive.
```
"scripts": {
        "release-patch": "npm run build && lerna publish patch --npm-tag latest",
        "release-minor": "npm run build && lerna publish minor --npm-tag latest",
        "release-major": "npm run build && lerna publish major --npm-tag latest",
        "alpha-patch": "npm run build && lerna publish prepatch --npm-tag next",
        "alpha-minor": "npm run build && lerna publish preminor --npm-tag next",
        "alpha-major": "npm run build && lerna publish premajor --npm-tag next"
}
```

It would be an improvement to our workflow to still use the cli interface but control what options are available within it.
```
"scripts": {
        "release": "npm run build && lerna publish --npm-tag latest",
        "alpha": "npm run build && lerna publish --npm-tag next --prerelease-only"
}
```

**Comment by SpookyCorridor** [comment]
You may want to consider the conventional-commits route or some type of CI integration then

**Comment by evocateur** [comment]
`prerelease` is identical to `prepatch`, in practice.

That being said, I'm not sure you need prereleases here? Essentially, you should never be publishing to the default `latest` dist-tag if you have a "staging" dist-tag (like "next"). The promotion of a given version (after test validation, or the like) only needs to use `npm dist-tag`, not overcomplicated lerna incantations.

**Comment by mattfelten** [comment]
Can you move a release from one dist-tag to another??

**Comment by LeeeeeeM** [comment]
> Can you move a release from one dist-tag to another??

that a good promotion， i need a command to remove my npm dist-tag in a batch.
such as `npx lerna revoke --dist-tag next`
instead of  `cd packages/p1  && npm dist-tag rm next  && cd packages/p2  && npm dist-tag rm next`
