### ISSUE TITLE
Lerna assumes the repo is already been initialized with `git init`.

### ISSUE THREAD

**Issue by hzoo** [lerna/lerna#175]
I think if you lerna init in a folder that isn't a git repo already it errors? It's an edge case but we can run `git init` if it isn't

if we do this, we can remove the the line I added in the init section of the readme

**Comment by kaicataldo** [comment]
Oh cool, can I work on this?

**Comment by thejameskyle** [comment]
Yeah I'd like to see this

**Comment by thejameskyle** [comment]
I don't know if I would remove that from the README though, I want people to know that this is really just git and npm behind the scenes.
