### ISSUE TITLE
lerna exec seems to cancel the action on package.json

### ISSUE THREAD

**Issue by erossignon** [lerna/lerna#1750]
Node-opcua is using lerna. We are using npm-check-update on our package;json to bump external package version number to the their latest version.

This is done with a command like
```
$ lerna exec npm-check-updates -- -au
$ lerna exec -- ncu  -au
$ lerna exec -- npm-check 
```

However, it looks like lerna revert the work done by npm-check-update in the package;json at the end of the run. 

Note : the same applies with ```npm-check```

In the previous version of Lerna ( v2 ?) , this was working fine and we could update packge easily.

## Expected Behavior

lerna should allow exec command to modify the package.json file.

Alternatively, lerna could provide an embedeed command to upgrade external package version number across all sub packages , à la npm-check or npm-check-update.
 
## Steps to Reproduce (for bugs)

1. check out a somewhat old version of node-opcua

       $ git clone https://github.com/node-opcua/node-opcua
       $ git checkout v0.4.6

2.    installl ncu ( from npm-check-updates)    

       $ npm install -g npm-check-updates

3.  run ncu -au inside all packages using lerna ( version >3.4)

      $ lerna exec -- ncu -au

Note that ncu is detecting package to upgrade and changes the package.json files

4.  run lerna bootstrap

     $ lerna bootstrap --ignore-scripts --hoist

Note lerna complaining about HOIST package not having the same version

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "lerna": "3.2.1",
  "hoist": true,
  "packages": [
    "packages/*"
  ],
  "version": "0.4.6"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

none -> command succeeds
```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3|
| `npm --version`  | 6.4.1|
| `yarn --version` | N/A |
| `node --version` | v10.12.0 |

| OS | Version |
| --- | --- |
| Windows 10 | 18XX|
| Ubuntu | 16.10 |
-->

**Comment by evocateur** [comment]
Actually, this is `lerna bootstrap` that is resetting the leaf manifests, not `lerna exec`. _Especially_ with `--hoist`, which is doing a whole bunch of mangling to the dependencies specs.

I would recommend inserting a `git add .` before running `lerna bootstrap`.

**Comment by erossignon** [comment]
running ```git add . ``` after running ```lerna exec -- ncu -au``` to incorporate all packages.lock files to the index and before running ``` lerna bootstrap --hoist --ignore-scripts``` works like a charm ! 
Thank you

**Comment by evocateur** [comment]
Also, note that you don't need to install `npm-check-updates` globally to access the `ncu` binary from `lerna exec`; a local devDependencies install is sufficient (and more portable) as Lerna uses a library that automatically adds `{root}/node_modules/.bin` to the `PATH` when executing its script arguments.
