### ISSUE TITLE
Packages' `package-lock.json` file shows changes after a fresh install...

### ISSUE THREAD

**Issue by busticated** [lerna/lerna#1754]
hey again :wave:

i have a monorepo with a handful of packages. all my `devDependencies` are managed at the top-level (`./my-proj/package.json`) otherwise `dependencies` are specified in each package's `package.json`  file (`./my-proj/my-package-name/package.json`). all deps are external, no `file:` links or hoisting (yet).  i use `npm-shrinkwrap.json` at the top-level and `package-lock.json` files for each package to ensure stable dependency versioning between installs.

over the course of development, i've used the same version of `npm`, the same major version of `node` (see below) and always installed package `dependencies` using the `add` command:

```
lerna add module-foo --scope my-package-name
```

this nicely adds the dependency to the package specified via the `--scope` flag updating both `package.json` and `package-lock.json`.

now if i blow away my various `node_modules` directories and run `npm i` then `lerna bootstrap` at the top-level, i end up with changes in my packages' `package-lock.json` files like:

```
-                               "isexe": "2.0.0"
+                               "isexe": "^2.0.0"
```

that is, from _exact_ to _ranges_

i know lerna does some munging of `package.json` data but i'm fairly clueless as to what / where exactly.

thanks in advance :pray:
-matt

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 5.10.0 |
| `yarn --version` | N/A |
| `node --version` | 8.12.0 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.6 |

**Comment by busticated** [comment]
perhaps related 👉 https://github.com/lerna/lerna/issues/1429

**Comment by evocateur** [comment]
That's actually a side-effect of npm v5.10.0 and higher. They changed the lockfile format to include the requested ranges, not the resolved versions.
