### ISSUE TITLE
Lerna add with hoist errors.

### ISSUE THREAD

**Issue by celticdarren** [lerna/lerna#1757]
## Expected Behavior
Expect hoist to create a node_modules at the root

## Current Behavior
Running the lerna add with --hoist results in an error.
`ERR! lerna Unknown argument: hoist`

## Steps to Reproduce (for bugs)
1. lerna add react --hoist

<details><summary>lerna.json</summary><p>

```json
{
  "command": {
    "bootstrap": {
      "hoist": true
    }
  },
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 6.1.0 |
| `node --version` | 8.9.4 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS High Sierra | 10.13.1 |

**Comment by ThisIsMissEm** [comment]
@celticdarren where have you found this option? It's not supported as per `lerna add --help` in lerna `3.4.3`

**Comment by celticdarren** [comment]
@ThisIsMissEm It can be found here https://github.com/lerna/lerna/blob/master/doc/hoist.md
I'm following a guide that suggested its use to hoist node_modules to the root.

**Comment by ThisIsMissEm** [comment]
@celticdarren ah, this appears to be for `lerna bootstrap` not for all lerna commands, as far as I understand it. We likely need to make the documentation clearer.

@evocateur could you clarify?

**Comment by celticdarren** [comment]
@ThisIsMissEm That makes sense! Thanks for getting back to me.

**Comment by ThisIsMissEm** [comment]
If that resolves your issue, can you please close this issue. Thanks!
