### ISSUE TITLE
Unable to install Lerna beyond version 3.1.x

### ISSUE THREAD

**Issue by goodbomb** [lerna/lerna#1759]
## Expected Behavior

I should be able to install Lerna using `npm install lerna`

## Current Behavior

When running `npm install lerna` I receive the following error:

```
npm ERR! code E404
npm ERR! 404 Not Found: @lerna/run-parallel-batches@^3.0.0
```

This error only seems to occur in v3.2.0 and above. I can install version 3.1.0 without issue.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.2.0 or newer |
| `npm --version`  | 5.5.1 |
| `node --version` | 8.9.1 |

| OS | Version |
| --- | --- |
| Windows 10 | build 16299 |

**Comment by ThisIsMissEm** [comment]
Can you do a `npm view @lerna/run-parallel-batches@^3.0.0`? If it finishes, but does not output anything, then that's something we can look into. `@lerna/run-parallel-batches@^3.0.0` is published in the npm registry: https://www.npmjs.com/package/@lerna/run-parallel-batches

**Comment by goodbomb** [comment]
This is what I'm seeing:

```
> npm view @lerna/run-parallel-batches@^3.0.0
npm ERR! code E404
npm ERR! 404 Not Found : @lerna/run-parallel-batches
npm ERR! 404
npm ERR! 404  '@lerna/run-parallel-batches' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bescott\AppData\Roaming\npm-cache\_logs\2018-11-05T20_54_22_803Z-debug.log
```

I've also updated my version of nodeJS to v10.13.0 and npm to v6.4.1

**Comment by goodbomb** [comment]
And I can confirm that I'm now able to `npm install lerna@3.4.3` after running `npm login`. Weird issue...

**Comment by ThisIsMissEm** [comment]
@goodbomb hm, this is odd, as it's not a private scoped package, as far as I can tell.

@evocateur can you check this in the web UI?

**Comment by goodbomb** [comment]
It's probably worth noting that the repository in which I'm using Lerna is a private scoped package that's being published to an internal instance of Artifactory. Our package is scoped and we have to log in to artifactory as well, so this could potentially be causing an issue, not sure.

**Comment by ThisIsMissEm** [comment]
I can’t reproduce locally (logout, clear cache, npm view) — could you post the output of `npm view @lerna/run-parallel-batches@^3.0.0 —loglevel silly`

Thanks!

**Comment by evocateur** [comment]
It sounds like you need to blow away the Artifactory cache that insists the package doesn't exist?

**Comment by goodbomb** [comment]
I know what the issue is now. It's my global `.npmrc`. @evocateur gave me the idea to check it, as I had it configured for deploying to artifactory locally.

```
registry=https://registry.npmjs.org/
@scqt:registry=<artifactory URL>
//artifactory.ea.com/artifactory/api/npm/scqt-npm-local/:_password="<password>"
//artifactory.ea.com/artifactory/api/npm/scqt-npm-local/:username=<username>
//artifactory.ea.com/artifactory/api/npm/scqt-npm-local/:email=<email>
//artifactory.ea.com/artifactory/api/npm/scqt-npm-local/:always-auth=true
_auth="<Base 64 username:password>"
email=<email>
always-auth=true
```

After I remove that stuff, `npm view @lerna/run-parallel-batches@^3.0.0` works.

To fix it, I had to swap the order of the registry entries, like this:

```
@scqt:registry=<artifactory URL>
//artifactory.ea.com/artifactory/api/npm/scqt-npm-local/:_password="<password>"
//artifactory.ea.com/artifactory/api/npm/scqt-npm-local/:username=<username>
//artifactory.ea.com/artifactory/api/npm/scqt-npm-local/:email=<email>
//artifactory.ea.com/artifactory/api/npm/scqt-npm-local/:always-auth=true
_auth="<Base 64 username:password>"
email=<email>
always-auth=true

registry=https://registry.npmjs.org/
always-auth=false
```
