### ISSUE TITLE
How can I make lerna install devDependencies with "lerna bootstrap --hoist"?

### ISSUE THREAD

**Issue by wbern** [lerna/lerna#1765]
https://github.com/lerna/lerna/issues/505

## Expected Behavior

I'd like to run `lerna bootstrap --hoist` and have each package get their devDependencies installed, either in its own directory or in the root.

## Current Behavior

devDependencies are ignored.

## Possible Solution

Here's a workaround, in the package package.json

`"prepare": "if-env lerna=1 && npm install --only=dev || echo 'skipping devDependencies"`
actually this doesn't really seem to work either.

## Steps to Reproduce (for bugs)

1. make a package
2. add a devDependency to it
3. run `lerna bootstrap --hoist`
4. the devDependency is nowhere to be found

<details><summary>lerna.json</summary><p>

```json
{
    "version": "0.0.0",
    "packages": [
      "micro-apps/*/*",
      "shared-apps/*"
    ],
    "command": {
      "publish": {
        "ignoreChanges": [
          "ignored-file",
          "*.md"
        ],
        "independent": true
      },
      "bootstrap": {
        "npmClientArgs": []  
      }
    },
    "useWorkspaces": false
  }
 
```
</p></details>

## Context

We have a monorepo where the root project dir is another legacy project.

We therefore don't want to stash all our devDependencies into the project root package.json, because it will generate confusion what belongs where.
Someday we might move the legacy project to a sub package directory, but we can't do that right now.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | VERSION |
| `node --version` | 8.11.3 (LTS) |

| OS | Version |
| --- | --- |
| Ubuntu | 17.x |

**Comment by wbern** [comment]
Ok, so I'm slightly confused but it might make sense too, hear me out.

If I have sub packages in my lerna monorepo, and do `lerna bootstrap` or `lerna bootstrap --hoist`, the devDependencies get installed in either case.

If I however have sub packages just like before, but also _install_ them in the root directory's `package.json`-file, the packages get installed as external dependencies instead, and external dependencies as as a general rule in the world of npm, rightfully skips devDependencies.

I guess this is correct?

In our case, it doesn't quite help us. We might need to execute some npm command to install devDependencies in each sub package.. I'll update here when we've done it.

**Comment by wbern** [comment]
Ok, I found the best possible work-around.

Add the packages in the root as "devDependencies". If they are consumed by webpack (like in my case), it doesn't matter if they are in devDependencies, webpack will produce them in the output directory anyway.

Here's some discussion about whether it's right or not to use devDependencies. https://github.com/webpack/webpack/issues/520

**Comment by evocateur** [comment]
I would just run `npx lerna link convert` and stop worrying about `bootstrap` or hoisting. I'm a little unclear why you need to keep the root in some legacy state, seems like the transition to lerna would be a good opportunity to shed that technical debt...

**Comment by wbern** [comment]
@evocateur I think the bootstrapping is an awesome function. We don't always want to symlink things if we don't consume the latest versions of things, and we have a lot of duplicate dependencies which hoist helps us take care of.

Yes, we plan to move the root soon but it's a lot of stuff to move. We have a huge AngularJS app and it's been tricky to transition to micro frontends using lerna, but we're definitely getting there.

**Comment by wbern** [comment]
Closing this issue, I feel it's resolved.
