### ISSUE TITLE
Add option to limit Lerna to symlink only packages defined in scope

### ISSUE THREAD

**Issue by ibezkrovnyi** [lerna/lerna#1766]
A - monorepo packages

S - scope packages, list of packages combined together by `--scope`, `--include-filtered-dependents`, `--include-filtered-dependencies`, `--since`

N - 'not in scope' packages: **A** - **S**

## Expected Behavior
Lerna symlinks only projects from list **S** to their dependents from list **S**.

## Current Behavior
Lerna symlinks projects from list **A** to their dependents from list **A**

## Tested locally

https://github.com/lerna/lerna/blob/d6e6a42b7a820f2416869e2c71b920ee689ee315/core/package-graph/index.js#L116

If I change above line into:

```js
const local = forceLocal || resolved.fetchSpec === depNode.location || depNode.satisfies(resolved);
if (local && depName !== 'project-name') {
```

then `node_modules/project-name` in all lerna.json packages will not be replaced with symlink.

## Solution

We need to filter out some packages from being symlinked

### Option 1
To add cli parameter (let's say, `--exclude-from-local-dependencies`) and pass its argument (list of packages or minimatch patterns) into PackageGraph (for all commands).
But is more like tricky workaround - we will need to manually calculate difference between `lerna ls` and `lerna ls --since --include-filtered-dependents`, and pass diff to `--exclude-from-local-dependencies`

### Option 2 (best solution)
To add cli parameter (let's say, `--exclude-non-scope-from-local-dependencies`, or `--scope-local` by analogy with `force-local`) and auto-diff by lerna and pass result to PackageGraph (for all commands). **It would be the best solution**

## Context
We have couple of monorepos with ~200 projects in each, and with current behavior of Lerna we have to manually build almost all our projects just to test couple of them.

## Related issues
#1421 - is about `--ignore` option, and this issue is about `scope`

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 6.4.1 |
| `node --version` | 10.13.0 |

| OS |
| --- |
| NAME |
| RedHat |
| Windows |

**Comment by olvnikon** [comment]
We faced a similar problem. I'm also interested in the solution.

**Comment by ibezkrovnyi** [comment]
For anyone who will have this issue there is workaround with writing custom script:
https://github.com/lerna/lerna/issues/1421#issuecomment-453038004

It still is not as perfect as native lerna functionality, but at least it solves this issue without touching Lerna code.

**Comment by evocateur** [comment]
I don't believe altering the initial graph painting is the right place, it should be a method similar to `PackageGraph`'s [`partitionCycles()`](https://github.com/lerna/lerna/blob/fc7463fe68ce493986902400910a277e251a5467/core/package-graph/index.js#L193), but instead returns a brand new `PackageGraph` with the unchanged siblings excluded.
