### ISSUE TITLE
How to use $LERNA_ROOT_PATH in package.json scripts

### ISSUE THREAD

**Issue by codedbypaul** [lerna/lerna#1768]
My project directory structure is as follows:

```
packages
-- my-package
scripts
-- build.js
```

My package.json build script is ```"build": "lerna exec -- node ./scripts/build.js"``` Of course this tries to run ```my-package/scripts/build.js```

I've tried to use $LERNA_ROOT_PATH as mentioned [here](https://github.com/lerna/lerna/tree/master/commands/exec#readme) but can't see how to use it inside of package.json.

```"build": "lerna exec -- node \$LERNA_ROOT_PATH/scripts/build.js",```

## Expected Behavior
Lerna runs a script from the root of the project.

## Current Behavior
I get an invalid escape string from the Lerna command in my package.json

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.10.1 |
| `node --version` | 10.12.0 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14 |

**Comment by evocateur** [comment]
I'm a little unclear where this particular `build` script is located: the leaf package.json or the root package.json?

**Comment by codedbypaul** [comment]
It's in the root package.json.

**Comment by evocateur** [comment]
Okay, thanks for clarifying. Have you tried putting single quotes around the expression after the `--` (instead of the backslash escape)?

**Comment by codedbypaul** [comment]
Seems to have got me a bit further along. My LERNA_ROOT_PATH has a space in ie:

`/Volumes/HD Name/`

Is there a way to escape the path, or am I just better renaming the hd to something without spaces?

**Comment by evocateur** [comment]
I would definitely remove the space in the path, independent of this issue. If this was a direct shell execution, you could do fancy inner-quoting, but because this is JSON, I'm not sure if this would work:
```json
"build": "lerna exec -- 'node \"${LERNA_ROOT_PATH}\"/scripts/build.js'",
```

**Comment by codedbypaul** [comment]
I’ll give it a go and close this issue as it’s been answered.
