### ISSUE TITLE
Package glob "*/*/*" includes node_modules and cause lerna to error

### ISSUE THREAD

**Issue by sinedied** [lerna/lerna#1771]
## Expected Behavior

Using this lerna config:
```json
{
  "packages": [
    "*/*/*"
  ],
  "version": "0.0.0"
}
```
The root `node_modules` folder and its subsequent paths should be ignored when exploring packages.

## Current Behavior
The root `node_modules` folder is not ignored with with glob and it cause errors thrown like `Error: Invalid package name "rxjs/ajax": name can only contain URL-friendly characters`.

## Possible Solution
If negated blob path worked it could have solved the issue (as it's supported by globby), ie:
```json
{
  "packages": [
    "!node_modules/*/*",
    "*/*/*"
  ],
  "version": "0.0.0"
}
```

## Steps to Reproduce (for bugs)
Use a wildcard at the root for package path, on any lerna repo.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "*/*/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context
I'm working on an enterprise-wide pseudo-monorepo (built like one on the CI, but using different repositories as source), and the folder structure is imposed as such:
```
/ (workspace root)
/team1/project1/package1
/team1/project1/package2
/team1/project2/package1
/team2/project1/package1
...etc
```
Hence the `*/*/*` package glob set for lerna. The issue is that I could not find a way to filter out the `node_modules/*/*` folders that are included in the blob, and those makes lerna error.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.2 |
| `npm --version`  | 6.4.1 |
| `node --version` | 8.11.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.13.6 |

**Comment by evocateur** [comment]
Got behind on issues over the holidays, sorry. I'm not sure this is in scope for lerna, to be quite frank. If you're going whole-hog on a monorepo, why can't you use globstars (`**`) instead?

**Comment by sinedied** [comment]
@evocateur I'm currently doing that, but globstars include way more than what I need and cause other issues in addition to worse performance, as https://github.com/lerna/lerna/issues/1784

I think those 2 issues can be solved with the same simple solution: allowing to blacklist packages through negative blobs. I'm willing to propose a PR if you are ok with that?
Would you be more in favor of negative blobs support (ie `!<blob>` in the existing `packages` array) or an additionnal setting like `ignorePackages`?

**Comment by sinedied** [comment]
Whoop, sorry for the delay that made the issue closed :(

And thanks @evocateur for the feedback, I will find some time to propose a PR then, and yes my idea was to catch the negative blobs and treat them separately using the same logic that ignore `node_modules` to avoid breaking things ;) And I will be extra careful regarding Yarn workspace, thanks for the warning.
