### ISSUE TITLE
What is the correct workflow to promote pre-release

### ISSUE THREAD

**Issue by raijinsetsu** [lerna/lerna#1774]
How do we promote a pre-release if no changes have been made yet?

`lerna version prerelease --preid rc`
Assuming there are changes, this correctly updates the package versions from "0.0.0" to "0.0.1-rc.0" and tags "v0.0.1-rc.0" and, if there are no changes, nothing is changed. This is expected.

`lerna version --preid rc`
`lerna version 0.0.1 --preid rc`
`lerna version minor --preid rc`
None of these promote the pre-release. My expectation was that the version would move to "0.0.2" and a tag for "v0.0.1" would be created.

It seems very strange that we can only promote a pre-release after more changes have been made or by using passing `--force-publish` option. We typically do not make any changes between the last pre-release and it's promotion.

I looked through the documentation, but I could not find any pre-documented workflows that might explain why we are expected to have changes before promotion.

**Comment by caseyduquettesc** [comment]
Have you tried `lerna version`?

I use that command which I found in this document (https://github.com/lerna/lerna/tree/master/commands/version#graduating-prereleases) and it promotes my pre-releases just fine.

**Comment by jenniesyip** [comment]
From [semver.org](https://semver.org/): 

> A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal. Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

As you work on your pre-release, it will be versioned:
0.0.0
0.0.1-rc.0
0.0.1-rc.1
0.0.1-rc.2 
... etc

When you are ready to promote a pre-release, you are usally removing the pre-release identifier, which in this example is `rc`. The next expected version of your package would then be `0.0.1`. If you want to bump it to another pre-release identifier instead, then you need to specify something different, i.e. `alpha` to `beta` to `rc`.

**Comment by SamVerschueren** [comment]
I have the same issue. The `lerna version` command isn't promoting my prerelease with the message

> Current HEAD is already released, skipping change detection.

I also read that the [docs](https://github.com/lerna/lerna/tree/master/commands/version#prerelease) state

> If you have any packages with a prerelease version number (e.g. 2.0.0-beta.3) and you run lerna version with and a non-prerelease bump (major, minor, or patch), it will publish those previously pre-released packages as well as the packages that have changed since the last release.

But for me, it doesn't work. I use `lerna@3.15.0`.

**Comment by evocateur** [comment]
@SamVerschueren You're using `--conventional-commits` with `--conventional-graduate`? If so, please open a new bug with reproduction, thanks.

**Comment by SamVerschueren** [comment]
@evocateur I created an issue because I thought it was a bug. I found out about those two flags before reading your comment. See https://github.com/lerna/lerna/issues/2143#issuecomment-503660162. It wasn't very clear from the documentation, hence the thing I quoted above. If those two flags are the ones that should do the trick, it does for me :).
