### ISSUE TITLE
Create custom folder using lerna create

### ISSUE THREAD

**Issue by Pk-T** [lerna/lerna#1779]
As the title suggests is it possible to create a custom folder using lerna create. I checked the file @lerna/create, it has no option to modify the structure or directory name...what i wanted was whenever i use the command(lerna create <pkg>) I get a src folder, different folder for stories and few extra files that i require to build those particular packages etc.

**Comment by evocateur** [comment]
Sounds like you should make your own custom [initializer](https://docs.npmjs.com/cli/init). That's all `lerna create` is, after all. I suppose we could support a custom [init-module](https://docs.npmjs.com/misc/config.html#init-module), if you really wanted to keep using `lerna create`.

**Comment by Fyre91** [comment]
I need it anyway for my project, should I have a go at it? if it's something that could be added and be of some help.

**Comment by stephanepericat** [comment]
it would be so great to have this feature; it would save a lot of time from moving files around manually...

**Comment by MaxMilton** [comment]
I'd love to see this implemented in a way that developers can choose which template to create with. Either a list of options to select from or maybe something like a `lerna create --src <templateDir>` flag?

**Comment by evocateur** [comment]
Don't confuse `--src`, just use `--template`.

Although there's a bit more going on than just a template, I'd rather not reimplement yeoman inside lerna. I am happy to point to external clis or yeoman templates, in retrospect this probably wasn't a good command to add to lerna in the first place.

**Comment by detj** [comment]
I would go as far as to say `lerna create` should be dropped as a feature. There are some solutions around this in the form of [hygen](http://www.hygen.io/) & [plop](https://plopjs.com/).

Or if lerna create could seamlessly work with any existing templating solution.

**Comment by songlairui** [comment]
> See #1814 for more details

redirect here in #1814

**Comment by adamgen** [comment]
I suggest we have an option to add a git repo as the template source.  So we can use:

- `lerna create --url="https://github.com/my/template"` 
- `lerna create --template="/source/to/template"`

or:

- `lerna create --src="https://github.com/my/template"` 
- `lerna create --src="file:/source/to/template"`

**Comment by Sajjon** [comment]
Hi all! I'm a JS/TS/Node noob coming from Swift world and recently started doing JS dev. What is the status of this issue?

I'm trying to setup a Monorepo using yarn v2 a.k.a. _Berry_ together with Lerna.

I just tried the `yarn lerna create` command and it created a new package with a file structure that I didn't like I think. It creates the this file structure:

```
my-lerna-repo/
    package.json
    packages/
        Foo/
            package.json
            README.md
            lib/
                foo.js
            __tests__/
                foo.test.js

        Bar/
            package.json
            README.md
            lib/
                bar.js
            __tests__/
                bar.test.js
```


But I think I would much rather get this:

```
my-lerna-repo/
    package.json
    packages/
        Foo/
            package.json
            README.md
            src/
                foo.js
            test/
                foo.test.js

        Bar/
            package.json
            README.md
            src/
                bar.js
            test/
                bar.test.js
```

As seen in [Zilliqa's monorepo](https://github.com/Zilliqa/Zilliqa-JavaScript-Library), e.g. package [`@zilliqa-js-blockchain`](https://github.com/Zilliqa/Zilliqa-JavaScript-Library/tree/dev/packages/zilliqa-js-blockchain).

So I wonder, how have Zilliqa achieved this? Did they not use `lerna create` at all? But rather create this file structure **manually**? And then... use `lerna add`? (I think that is what the `add` command is for? Existing packages..?)

**Comment by Sajjon** [comment]
It would also be interesting to know if it is possible for new packages to use _tsconfig_ "inheritance" using a _base_ config [like Zilliqa does with`tsconfig.base.json`](https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/dev/tsconfig.base.json) which then individual `tsconfig.json` files inside [each package _extends_, like so](https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/dev/packages/zilliqa-js-blockchain/tsconfig.json#L2)

**Comment by JamesHenry** [comment]
Hi Folks 👋

There have been a number of duplicate/highly related issues concerned with customizing new package creation.

I have therefore created a single source of truth for all future development and planning in this area here: #3444

Please kindly subscribe to/upvote that issue if you interested in this capability!

Many thanks 🙏
