### ISSUE TITLE
Packages graph check throws because it's done before applying the filters

### ISSUE THREAD

**Issue by sinedied** [lerna/lerna#1784]
## Expected Behavior
Here is some example repo:
```
/packages/good -> package name: "good"
/packages/bad1 -> package name: "duplicate"
/packages/bad2 -> package name: "duplicate"
```
In the `lerna.json`, the config is like this: `"packages": ["*/**"]`.

When I run `lerna bootstrap --scope good` it should work and ignore the badly named packages.

## Current Behavior
When I run `lerna bootstrap --scope good`, it fails with this error:
```
lerna notice cli v3.4.3
lerna ERR! ENAME Package name "duplicate" used in multiple packages:
lerna ERR! ENAME        /Users/x/projects/bad1
lerna ERR! ENAME        /Users/x/projects/bad2
```
Because the filter occurs after all the packages are globbed in and checked, instead of applying the filter before checking the resulting graph.

**Some additional context about this issue:**
Of course in this simple case you should just rename the bad package names, but I'm using Lerna at the root of a big company monorepo to a address a build from trunk use case, and I do not have the hand on all existing projects and some are failing this way (some even have an undefined name, causing the same error).

I understand this is not the primary use case for Lerna, but it's actually working very well except for this small problem 😉 

## Possible Solution

There is 2 ways in my opinion to solve this issue:
1. Make the `--ignore`, `--scope` etc filter to be applied before checking the package graph
2. Add an `ignorePackages` setting to allow a blacklist of packages to exclude from the initial package search (that would be directly added to the `globOpts.ignore` array in https://github.com/lerna/lerna/blob/62843b04e3a5a03012ceabe465519b39a09fbcc1/core/project/lib/make-file-finder.js#L27

The second solution would the best for use because maintaining a black list is way simpler than having to use a whitelist.

If you're not against the idea, I would like to propose a PR for this.

## Steps to Reproduce (for bugs)
Create a new lerna repo with this structure:
```
/packages/good -> package name: "good"
/packages/bad1 -> package name: "duplicate"
/packages/bad2 -> package name: "duplicate"
```

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "*/**"
  ],
  "version": "0.0.0"
}
```
</p></details>

An run `lerna bootstrap`

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 5.6.0 |
| `node --version` | 8.11.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by sinedied** [comment]
> npm package names are always required to be universally unique
This is true for packages that aims to be published, but private internal packages can reuse the same name.

Regarding the `*/**` blob, it works just fine, even though I would have preferred just `*/*/*` for my use case but `node_modules` are added to the ignore list only if there's a `**` wildcard present. One more reason to add support for custom ignore rules 😉 

I know our use case is not really the vanilla Lerna use case, but except for that issue it works very well within a repo containing thousands of repository (the wildcard isn't even that slow, only a few seconds to match all packages).

Maybe it wasn't that clear in the issue, but this issue was to clarify my use case and gather feedback on whether you would accept a PR implementing solution 1 or 2.
I personally think being able to extend the ignore list via the configuration would be the best and would benefits other use cases as well.

**Comment by evocateur** [comment]
Global uniqueness of package names _managed by Lerna_ isn't optional. If you want package.json files with duplicate names, don't configure them as lerna packages.

Is it really that hard to configure a targeted list of package globs that don't use a globstar? I can appreciate the desire to avoid the burden of a whitelist, but this isn't exactly a frequently-changing configuration.

**Comment by sinedied** [comment]
> Global uniqueness of package names managed by Lerna isn't optional. If you want package.json files with duplicate names, don't configure them as lerna packages.

Hence the need of a blacklist, via the `ignoreGlobs` option :)

> Is it really that hard to configure a targeted list of package globs that don't use a globstar? I can appreciate the desire to avoid the burden of a whitelist, but this isn't exactly a frequently-changing configuration.

Yes it is, the company being wide spread on several countries with new repositories being added every day, having to setup a whitelist configuration (coupled with the associated code reviews each time a new repo is added) would be a burden to maintain (and we know this well as whitelists are used for other services with legacy tech...). Having the option to blacklist certain paths would definitely help there.
