### ISSUE TITLE
How to publish specific packages (from a partially successful prior publish)?

### ISSUE THREAD

**Issue by bengourley** [lerna/lerna#1785]
Forgive me if there is a previous issue that mentions how to resolve this problem – I searched in the docs for `publish` and in the issue tracker but I couldn't find it.

For a monorepo with about 20 modules, I did:

```
NPM_CONFIG_OTP=xxxxx lerna publish from-git --npm-tag next
```

During this command, the OTP expired so only about a third of the modules successfully got published. If I try to re-run the same command with a new OTP code, the failure to publish the modules that already went up causes it to fail.

How can I re-run the publish step to push up the modules that didn't succeed the first time, without needlessly bumping a version.

## Expected Behavior
Ability to resume a partially successful `publish` command.

## Current Behavior
Cannot resume a partially successful `publish` command, nor run `publish` for a single/set of specific package(s).

## Possible Solution
Ability to run `publish` for a single/set of specific package(s)
or
Tolerate "already published" errors from the npm registry during publish.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "packages": [
    "packages/*"
  ],
  "version": "5.0.0-rc.1"
}
```
</p></details>

**Comment by elie222** [comment]
Using `--scope`?
