### ISSUE TITLE
Incompatible package globs passed to `git checkout` after publish

### ISSUE THREAD

**Issue by cspotcode** [lerna/lerna#1786]
## Expected Behavior

`lerna publish` works correctly when using this package glob: `packages/!(__template__)`

## Current Behavior

Lerna tries to run `git checkout -- packages/!(__template__)/package.json` which fails because git doesn't understand the glob pattern.

https://github.com/lerna/lerna/blob/master/commands/publish/index.js#L411

```
lerna ERR! Error: Command failed: git checkout -- packages/!(__template__)/package.json
lerna ERR! error: pathspec 'packages/!(__template__)/package.json' did not match any file(s) known to git.
```

## Possible Solution

Use lerna's glob expansions to generate a list of package.json files, then pass them to `git checkout`

## Steps to Reproduce (for bugs)

```
lerna version patch -m "chore(release): publish [skip ci]" --no-push
lerna publish from-git --yes
```

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/!(__template__)"
  ],
  "version": "independent",
  "command": {
    "publish": {
      "allowBranch": "master",
      "ignoreChanges": [
        "*.md"
      ]
    },
    "bootstrap": {
      "npmClientArgs": [
        "--no-package-lock"
      ]
    }
  }
}

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `yarn --version` | 1.6.0 |
| `node --version` | 8.11 |

OS is Debian Stretch, via CircleCI's nodejs docker image: circleci/node:8.11.3-stretch

**Comment by evocateur** [comment]
Yeah, that's probably better than trying to be fancy with globs. We already know which manifests changed, so the loop can be pretty simple.
