### ISSUE TITLE
`publish from-git` is unable to locate tagged packages if Lerna project root is not same as git repository root

### ISSUE THREAD

**Issue by patryk-bartoszek** [lerna/lerna#1792]
There is an issue with publishing packages tagged with `lerna version` if lerna.json file is not located at the root of git repository.
Example repository structure:
```
git-repository/
└── project/
    ├── packages/
    │    └──foo/
    │        └── package.json
    ├── lerna.json
    └── package.json
```

## Expected Behavior

`lerna publish from-git` publishes packages tagged using `lerna version` (even if repository root is not the same as lerna project root)

## Current Behavior

Lerna is unable to locate changed packages:
```
lerna success No changed packages to publish
```

## Possible Solution

Pass repository root  instead of `this.project.rootPath` to `getTaggedPackages` method in publish command :
https://github.com/lerna/lerna/blob/master/commands/publish/index.js#L215

## Steps to Reproduce (for bugs)

1. Move existing lerna project to subdirectory eg. "project"
2. commit changes 
3. cd into "project" dir
4. `lerna version`
5. `lerna publish from-git` 

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3|

**Comment by evocateur** [comment]
What if we passed [`--relative`](https://git-scm.com/docs/git-diff-tree#git-diff-tree---relativeltpathgt) to `git diff-tree`? Would that work in this case?

**Comment by patryk-bartoszek** [comment]
Yes, adding `--relative` option works! I just tested it.

**Comment by evocateur** [comment]
A PR would be great!
