### ISSUE TITLE
lerna bootstrap --hoist --nohoist= doesn't work

### ISSUE THREAD

**Issue by guillaumevincent** [lerna/lerna#1794]
When I run the command `lerna bootstrap --hoist --nohoist=b` the `packages/b` is not ignored in hoisting. I tried to follow the [bootstrap command documentation](https://github.com/lerna/lerna/tree/master/commands/bootstrap#--nohoist-glob)
Tell me if I'm using it incorrectly.

## Expected Behavior
dependencies for the package b should be installed in `packages/b/node_modules`

## Current Behavior
dependencies for the package b are installed in the root `node_modules` folder

## Steps to Reproduce (for bugs)

a bash script showing the bug

```bash
rm -rf /tmp/test_nohoist
mkdir /tmp/test_nohoist
pushd /tmp/test_nohoist
npm init -f
lerna init --independent
cat package.json
npm install
mkdir packages/a
echo '{"name": "a","version": "1.0.0"}' >> packages/a/package.json
mkdir packages/b
echo '{"name": "b","version": "1.0.0","dependencies": {"uuid": "^3.3.2"}}' >> packages/b/package.json
lerna bootstrap --hoist --nohoist=b
# lerna bootstrap --hoist --nohoist=**/b
# lerna bootstrap --hoist --nohoist=**/b*
# lerna bootstrap --hoist --nohoist=packages/b
ls node_modules/uuid
ls packages/b/node_modules/uuid
popd
```

result: 
`ls: cannot access 'packages/b/node_modules/uuid': No such file or directory`

## Context
I want to ignore hoisting only package b in my packages list

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.12.3 |
| `node --version` | 10.13.0 |

| OS | Version |
| --- | --- |
| Fedora | 29 |

**Comment by evocateur** [comment]
`--nohoist` arguments are globs for dependency names (e.g., `uuid` or `react*`), not the names of lerna-managed local (aka "leaf") packages.

**Comment by guillaumevincent** [comment]
Ack
thank you for your answer
