### ISSUE TITLE
lerna bootstrap consume huge memory

### ISSUE THREAD

**Issue by kyasbal-1994** [lerna/lerna#1798]
I'm trying to execute `npx lerna bootstrap` on my CI environment in CircleCI.
I have an error of out of memory error in the bootstrap.

```
#!/bin/bash -eo pipefail
npx lerna bootstrap
lerna notice cli v3.5.0
lerna info Bootstrapping 5 packages
lerna info Installing external dependencies
lerna ERR! npm ci exited 1 in '@XXX/api-schema'
lerna ERR! npm ci stderr:
WARN tar ENOMEM: not enough memory, write
WARN tar ENOMEM: not enough memory, write
WARN tar ENOMEM: not enough memory, write
WARN tar ENOMEM: not enough memory, write
WARN tar ENOMEM: not enough memory, write
WARN tar ENOMEM: not enough memory, write
WARN tar ENOMEM: not enough memory, write
WARN tar ENOMEM: not enough memory, write
WARN tar ENOMEM: not enough memory, write
WARN tar ENOMEM: not enough memory, write
WARN tar ENOMEM: not enough memory, write
npm ERR! Unexpected end of JSON input

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2018-11-28T15_04_10_320Z-debug.log

lerna ERR! npm ci exited 1 in '@XXX/api-schema'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
Exited with code 1
```

I think lerna execute several install command in parallel. Then that fails the problem.
Is there any way to solve this?

## Expected Behavior

Rational memory consume

## Current Behavior

Huge memory consume preventing complete bootstrap

## Possible Solution

I don't know at this time.

## Steps to Reproduce (for bugs)

1. Make a repository with lerna have 5 or more projects
2. Install mandatory tools such as webpack babel ...etc
3. CI will fail by memory error

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | ? |
| `node --version` | 8 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
|CircleCI ubuntu instance| Unknown|

**Comment by kyasbal-1994** [comment]
I could fix by limiting max concurrency with the command `lerna bootstrap --concurrency=2`.
I've found several issues related to this and they use `--mutex ` also. Is this actually needed?
I wonder they are not related to memory issue.

**Comment by evocateur** [comment]
`--mutex` is a yarn-related flag, I doubt it has any effect on `npm ci` calls. I personally don't use `lerna bootstrap` anymore, and recommend migrating to [relative `file:` specifiers](https://github.com/npm/cli/blob/latest/doc/spec/file-specifiers.md), like the lerna source does.

`--concurrency` is probably a good idea in CI environments, anyway, since they often have far fewer CPUs available and all the filesystem-intensive operations cause things to go much slower than normal. Could have sworn the default concurrency was 4, in any case.

**Comment by kyasbal-1994** [comment]
@evocateur Thank you for replying me. After fixing the concurrency to 2, the error wont show again. It seems solved perfectly. Thank you.
