### ISSUE TITLE
lerna publish successful, but no release on npm

### ISSUE THREAD

**Issue by FezVrasta** [lerna/lerna#1802]
## Expected Behavior
The new package should be available on my private registry

## Current Behavior
The new package is not available on my private registry

```
xxx-ui git/master
❯ lerna publish --yes --no-verify-access --registry https://xxx.jfrog.io/xxx/api/npm/npm-xxx/
lerna notice cli v3.3.2
lerna info Verifying npm credentials
lerna http fetch GET 401 https://xxx.jfrog.io/xxx/api/npm/npm-xxx/-/whoami 1125ms
Unable to authenticate, need: Basic realm="Artifactory Realm"
lerna WARN EWHOAMI Unable to determine npm username from third-party registry, this command will likely fail soon!
lerna info current version 1.0.1
lerna info Looking for changed packages since v1.0.1

Changes:
 - @xxx/test-travis: 1.0.1 => 1.0.2

lerna info auto-confirmed
lerna info git Pushing tags...
lerna info publish Publishing packages to npm...
lerna WARN ENOLICENSE Packages @xxx/test-travis are missing a license
lerna notice
lerna notice 📦  @xxx/test-travis@1.0.2
lerna notice === Tarball Contents ===
lerna notice 155B package.json
lerna notice 735B CHANGELOG.md
lerna notice 27B  index.js
lerna notice 92B  index.test.js
lerna notice === Tarball Details ===
lerna notice name:          @xxx/test-travis
lerna notice version:       1.0.2
lerna notice filename:      xxx-test-travis-1.0.2.tgz
lerna notice package size:  678 B
lerna notice unpacked size: 1.0 kB
lerna notice shasum:        7f345957856f6527b228bf0b44b24e69aaa2e20c
lerna notice integrity:     sha512-0dydgwiEAWppQ[...]ENyoUIm7Lv0lg==
lerna notice total files:   4
lerna notice
lerna info published @xxx/test-travis 1.0.2
Successfully published:
 - @xxx/test-travis@1.0.2
lerna success published 1 package
lerna publish --yes --no-verify-access --registry   3.96s user 1.07s system 41% cpu 12.264 total
```

## Possible Solution
Tt seems like Lerna is creating a tar.gz package rather than publishing to the registry?

## Steps to Reproduce (for bugs)
1. run `lerna publish --yes --no-verify-access --registry https://<PRIVATE_REGISTRY_HERE>`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.3.2",
  "version": "1.0.2",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "conventionalCommits": true,
      "ignoreChanges": ["*.md"]
    }
  }
}
```
</p></details>

## Context

N/A

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.3.2 |
| `npm --version`  | N/A |
| `yarn --version` | 1.12.1 |
| `node --version` | 11.1.0 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.14 |

**Comment by evocateur** [comment]
Lerna creates a tarball (via `npm pack`) and then publishes it. Since this is an Artifactory issue, I would take it up with them.

**Comment by FezVrasta** [comment]
Sorry I forgot to update the issue, it's actually (I think) a Yarn issue, there was something off with the authentication, but yarn was all happy thinking everything was fine, if I ran yarn with `--verbose` it reported a 401 error on the `put` command... I think yarn should throw an error there rather than letting people think everything was fine.
