### ISSUE TITLE
How to pass NODE_DEBUG to `yarn run test`

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [lerna/lerna#1808]
Whenever I invoke `lerna run test` I would like to pass the **NODE_DEBUG=libwsserver** to the underlying `yarn run test` command in a `libwsserver` package.

Following is an excerpt from libwsserver's package.json file:
```
  "scripts": {
    "lint": "./node_modules/.bin/eslint ./",
    "test": "yarn run lint && env NODE_DEBUG=libwsserver ./node_modules/.bin/mocha --opts ../../test/mocha.opts"
  },
```

I use the following code to print debug log:
`const debuglog = require('util').debuglog('libwsserver');`

## Expected Behavior
The yarn should receive the **NODE_DEBUG=libwsserver** variable and the **debuglog** should output some logs to console.

## Current Behavior
When run via `lerna run test`, the **debuglog** does not output anything. When run via `yarn run test` in the **libwsserver** directory the **debuglog** does output logs to console.

<details><summary>lerna.json</summary><p>

```json
{
  "useWorkspaces": true,
  "npmClient": "yarn",
  "npmClientArgs": [
    "--no-sort",
    "--conventional-commits",
    "--production",
    "--no-optional",
    "--use-workspaces",
    "--hoist"
  ],
  "packages": [
    "packages/**",
    "clients/**",
    "services/**",
    "deployments/**"
  ],
  "version": "0.0.0",
  "command": {
    "run": {
      "npmClient": "yarn"
    }
  }
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.5.0 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.10.1 |
| `node --version` | 11.3.0 |

| OS | Version |
| --- | --- |
| macOS Mojave | 11.14.1 |

**Comment by evocateur** [comment]
I'm not sure what `env NODE_DEBUG=libwsserver` is supposed to do? `env` isn't called to set a value for a single execution. You might need to use `cross-env`?

Tangential: In lerna.json, `npmClientArgs` is the wrong place to pass arguments to lerna. Those are passed verbatim to `yarn`, in this instance. Pretty sure `--conventional-commits` and `--hoist` are meaningless to yarn. (`--hoist` should never be used with yarn workspaces, in any case)

**Comment by anyexinglu** [comment]
@evocateur, do you mean, `yarn bootstrap --hoist` cannot works with `npmClient: yarn`?

I've tried many ways to use this and failed.

Since this article(https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/) told me:

> Starting with Lerna 2.0.0, when you pass the flag --use-workspaces when running Lerna commands, it will use Yarn to bootstrap the project

 I thought they works well together.

**Comment by evocateur** [comment]
I'm saying that `npmClientArgs` is not the place to put arguments intended for `lerna` itself. `--use-workspaces` is already covered by `useWorkspaces: true` in your lerna.json.
