### ISSUE TITLE
Incremental import of existing repo

### ISSUE THREAD

**Issue by pengisgood** [lerna/lerna#1809]
## Expected Behavior

After import an existing repo the first time, we have all the history commits of this version. When the existing repo releases new versions separately, I want to import the incremental commits since last import.

## Current Behavior

We can't import twice for the same repo.

## Possible Solution

Calculate the sha range before create the patch. I don't know whether it is feasible or any other options.

**Comment by pengisgood** [comment]
🌝 🌝 🌚 🌚 
No one interested in the feature?

**Comment by evocateur** [comment]
Not generally, no. Once you import, that's it. Kill the old repo (or at least the subpath that was imported). Anything else is asking for trouble.
