### ISSUE TITLE
Abort git push on publish error

### ISSUE THREAD

**Issue by timkinnane** [lerna/lerna#1813]
## Expected Behavior
When npm publish is unsuccessful, due to config or version issues, the publish process should abort before adding tags and pushing.

## Current Behavior
On errors in publish config etc, the npm packages aren't published, but the version tags are added to the repo. This adds steps when debugging release flow.

I'm still learning Lerna and getting my config right, practicing with local npm registry etc. I'm often needing to roll back my HEAD and go to github and delete tags because the publish action failed but the git changes proceeded as if it succeeded.

## Possible Solution
Put git actions after publish, so if it exits early they don't happen.

## Steps to Reproduce (for bugs)
Release with a bad config, e.g. no token or a version that already exists.

## Version
Lerna 3.5.0

**Comment by evocateur** [comment]
The git operations are independent of the npm operations, though. npm has literally no opinion whether or not your code is actually versioned, tagged, or pushed to the remote.

In any case, you have a couple options:
1. `--no-push` with explicit `git push`:
```
lerna publish --no-push && git push
```
You could configure this in `lerna.json` like this:
```json
{
  "command": {
    "publish": {
      "push": false
    }
  },
  ...
}
```
2. Recover from completely failed npm publish with `from-git` keyword:
```
lerna publish from-git
```
This will skip the git commit and tagging and just rerun the `npm publish` steps.

**Comment by evocateur** [comment]
"A version already exists" seems like a drastically bad state that _should_ fail?

"No token" we could probably do with better preparation during `lerna publish`, but is rather hampered by the use of a third-party registry that likely doesn't implement anything useful in terms of validating endpoints (e.g., `npm ping`, `npm whoami`, or `npm profile get`).

**Comment by timkinnane** [comment]
Thanks @evocateur I assumed that an error from npm could cause the lerna publish process to exit, thereby preventing the git actions from occurring. When you say they're independent, do you mean it's two parallel processes? So they both run regardless of each other's success?
Just wanted to clarify that if you could. I'm happy to close the issue and use the `--no-push` approach, thanks for pointing that out.
