### ISSUE TITLE
lerna add does not support --hoist flag

### ISSUE THREAD

**Issue by compulim** [lerna/lerna#1815]
Since `lerna add` does not support `--hoist`, the underlying `lerna bootstrap` will run without hoist, which will localize/unhoisting package it is adding new dependency to.

`lerna add --hoist` is supported in `lerna@2`.

## Expected Behavior

`lerna add p-defer --hoist` would work. The dependencies are added to the root (hoisted behavior). No extraneous `package-lock.json` created under the target project.

## Current Behavior

`lerna add p-defer --hoist` will error out with `ERR! lerna Unknown argument: hoist`.

## Possible Solution

There are two workarounds:
- Add `{ bootstrap: { hoist: true } }` to `lerna.json`, or, 
- After `lerna add`, re-run `lerna bootstrap --hoist` again, also remove the extraneous `package-lock.json` inside the target package

## Steps to Reproduce (for bugs)

1. `lerna add p-defer --hoist`

## Context

This is a pitfall for everyone with a hoisted package trying to run `lerna add`. They may missed out the `--hoist` option and accidentally unhoisted some of their packages.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.1.4 and 3.5.1 |

It was working in lerna@2 (possibly 2.11.0).

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Windows 10 | 1809 |

**Comment by evocateur** [comment]
I'd rather enforce (via lerna.json's `command.bootstrap.hoist` property) that `--hoist` is _always_ serialized into the config file, whenever `lerna bootstrap --hoist` is run. I don't think `lerna add` needs `--hoist`. Very shortly `lerna add` will support `--no-bootstrap`, so at least there's one additional workaround directly on `lerna add`.

**Comment by Undistraction** [comment]
FWIW I'm not seeing this behaviour. If I run `lerna add alpha --scope bravo`, I often hit an issue with missing deps in one or more packages and need to run `lerna bootstrap --hoist` afterwards, though this issue seems to be intermittent. Strangely the missing dependency is often not the dependency I've added, but one that was available before the add. 

My `lerna.json`:
```
{
  "command": {
    "bootstrap": {
      "hoist": true
    }
  },
  "packages": [
    "packages/*"
  ],
  "version": "0.2.7"
}
```

**Comment by compulim** [comment]
I also like the idea of "enforce `--hoist` in `lerna.json`" because it would help to reduce human mistakes (forget to add `--hoist`).

Please feel free to close this bug as dupe if you have the "enforce" bug opened. In the meantime, I will tell my team to change to `command.bootstrap.hoist` property. :)

**Comment by martinsik** [comment]
Could this issue be reopened? It looks like this hasn't been resolved and was closed automatically.

**Comment by LeeBurton** [comment]
I would also like to see this addressed
