### ISSUE TITLE
Missing Remote Dependencies After lerna add.

### ISSUE THREAD

**Issue by Undistraction** [lerna/lerna#1816]
Sometimes packages that rely on hoisted dependencies are missing these dependencies after using `lerna add` to add a new (remote) package. 

## Expected Behavior
With the below config I would expect `lerna add alpha --scope bravo` to add a dependency of `alpha` to `bravo`, and hoist that dependency to the root, without effecting the other dependencies already hoisted to the root.

## Current Behavior
Intermittently, adding a dependency will result in one or more unrelated dependencies declared in other packages being removed from the root, i.e they are unhoisted. Lerna is definitely hoisting, outputs its progress to the console, and the added package *is* hoisted.

## Steps To Reproduce
```bash
lerna add alpha --scope beta
```

<details><summary>lerna.json</summary><p>

```json
{
  "command": {
    "bootstrap": {
      "hoist": true
    }
  },
  "packages": [
    "packages/*"
  ],
  "version": "0.2.7"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 6.4.0 |
| `node --version` | v8.11.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
Is this a duplicate of #1815?

**Comment by Undistraction** [comment]
@evocateur perhaps. I'm a little unclear about the current behaviour. If I have `hoist: true` in my config, should `lerna add` result in hoisted dependencies? Even if it should, I think there is something amiss here. I'll try and narrow down exactly what is causing this issue and update this issue.

**Comment by Undistraction** [comment]
So the specific behaviour is this:

I have a packages called `@example/dev` that has a devDependency on an npm-hosted package called `nps` and `nps-utils`. If I run `lerna bootstrap --hoist` these packages are installed in my keen root's `node_modules`. 

If I run `lerna add ...` and add any package, local or remote, with or without scope, I see the package installed and I see the output from lerna running `bootstrap`, however once this has finished, `npx` and `nps` are no longer in the root `node_modules` dir. The only way to get them back is to run `lerna hoist --boostrap` again.

**Comment by Undistraction** [comment]
@evocateur 

1. I use those packages in other packages that are outside the monorepo, so keeping them together and in a single location that I can publish makes sense.

2. I prefer to keep the root as clean as possible and only add things to the root `package.json` that are specific to the monorepo.

Are you saying this isn't a bug? Or that it is a known bug but that there are workarounds?

**Comment by evocateur** [comment]
> I prefer to keep the root as clean as possible and only add things to the root package.json that are specific to the monorepo.

I would migrate away from `lerna bootstrap --hoist`, then: run `lerna link convert` once and from then on a simple `npm install` is all that is necessary. `lerna bootstrap` is a pile of hacks that I haven't used personally in over a year. Better to let package managers manage packages, I always say.
