### ISSUE TITLE
Any way to use np to publish packages?

### ISSUE THREAD

**Issue by FezVrasta** [lerna/lerna#1817]
## Expected Behavior
Basically, #1282, which is marked as "solved" but it's not.

## Current Behavior
It's impossible to publish a package subfolder instead of the package root.

## Possible Solution
I think a possible solution to the problem is to allow to specify a different publish script instead of npm or yarn, I see that [np](https://github.com/sindresorhus/np) supports this feature.

## Context
I want to publish a package that exposes a lot of React components and I'd like the import API to be `import Button from '@my/pkg/Button'` rather than `import Button from '@my/pkg/dist/Button';`

**Comment by evocateur** [comment]
Not at the moment, no. I'm about to switch to [libnpmpublish](https://github.com/npm/libnpmpublish), so sure, why not. I'm tired of arguing.
