### ISSUE TITLE
Programatically call lerna run

### ISSUE THREAD

**Issue by sebald** [lerna/lerna#1819]
I couldn't find any information on the progress of #167. Is there any? 🙂

### Context
I am already using `@lerna/project` and `@lerna/package` to get information about the project structure and use this to adapt some commands for the usage with TypeScript (e.g. "custom" `lerna create`).

I also want to programmatically call `lerna run` (and not use `execa`) to set the `--scope` based on some project settings. I could use `@lerna/run` but this seems wrong to me, because the README in the repo doesn't show any programatic usage.

**Comment by evocateur** [comment]
It's a bit twisted up in various `yargs`-related command APIs...

But in theory:
```js
const run = require("@lerna/run");

// argv is an object with certain significant values (most automatically provided by yargs)
// the values here are the defaults
const argv = {
  cwd: process.cwd(),
  // "script" is the only _required_ argument ("test", "build", "foo:bar:baz", etc)
  script: '',
  // "--" is an extremely awkward way to pass arguments to `npm run`, probably don't need it
  "--": [],
  npmClient: "npm",
  bail: true,
  prefix: true,
  parallel: false,
  stream: false,
  // pretty much anything else documented in `npx lerna run --help`, but camelCased
};

(async () => {
  await run(argv);
  // 🎉 
}());
```

It calls `execa` internally, so I'm not sure how you're going to get around that.

**Comment by evocateur** [comment]
Also, the logging is a bit hostile to library usage patterns like this. (`npmlog` will be spamming your `stderr` with a bunch of output when you run it as I described, and there is _currently_ no config option that you can override to disable this)

**Comment by sebald** [comment]
Hey, thanks for you answers.

I ended up just using `execa` for this and it works butter smooth 🙂
My thinking was that if I "just" call lerna like this, it will definitely pick up the `lerna.json` and the command will run as usual.

```ts
export const getLernaBinary = async (cwd: string) => {
  const { stdout } = await execa('yarn', ['bin', 'lerna'], { cwd });
  return stdout;
};

export type LernaCommand =
  | 'publish'
  | 'version'
  | 'bootstrap'
  | 'list'
  | 'changed'
  | 'diff'
  | 'exec'
  | 'run'
  | 'init'
  | 'add'
  | 'clean'
  | 'import'
  | 'link'
  | 'create';

export const createLernaRunner = async (
  cwd: string,
  defaultOptions: Options = {}
) => {
  const bin = await getLernaBinary(cwd);
  return async (
    cmd: LernaCommand,
    args: string[] = [],
    options: Options = {}
  ) =>
    execa(bin, [cmd, ...args], {
      stdio: 'inherit',
      ...defaultOptions,
      ...options,
    });
};
```

PS: Would still be nice though if the API was a little bit more accessible. There is so much room for cool thinks to build on top of lerna 🙂 For example, I needed the run api (and project + package) to have a development script that automatically figures out which packages need to be build to build a chosen packages (via lerna's excellent dependency graph).

**Comment by jd-carroll** [comment]
I also agree that there are many cool things that could be done on top of the lerna API. Are there any leanings on the future of lerna? Specifically, would folks be open to gradually moving it closer to having an official api & cli interface?

Right now I am doing thins like:
```javascript
const PackageGraph = require('@lerna/list');

async function bootstrap() {
  const graph = new PackageGraph({ '_': [ 'ls' ] });
  await graph.runner;

  graph.packageGraph.forEach((graphNode: any, packageName: string) => {
    // ...
  });

  // ...
}

bootstrap()
  .then(/* ... */)
  .catch(/* ... */);
```

I know this is way not supported, but the lerna (hidden) api is just so powerful that I will put up with any headaches to manage this.

It would also be great if types were published for lerna or even migrate the whole project to typescript! 😄 But I open a new issue for a discussion on types support.
