### ISSUE TITLE
IncludeMergedTags not working when publishing a canary version

### ISSUE THREAD

**Issue by spoldman** [lerna/lerna#1820]
I'm trying to use includeMergedTags with a canary build and I noticed in the code that it is not passed on to the describeRef of the collectUpdates function inside detectCanaryVersions. 

So my question is should it not be part of when calculating canary versions?

**Comment by spoldman** [comment]
Just wanted to give a little bit more context

I'm trying to do CI builds of develop (canary) but all releases are tagged on master. If I have tagged 1.3 on master it is still buildin 1.2-alpha..... on develop.

**Comment by evocateur** [comment]
I wouldn't recommend using a `develop` branch, it just makes things overly complicated.

As to why this isn't happening for canary releases, it looks like it was just an oversight.

**Comment by spoldman** [comment]
I was testing the fix and found out that it was not completely working.

If you look at https://github.com/lerna/lerna/blob/master/commands/publish/index.js#L318
 you can see that describeRef is only called with one parameter but expects 2. The second parameter should be includeMergeTags flag. This can also be found in line 333 in the same file.

**Comment by evocateur** [comment]
Yep, you're right. This is what happens when I don't get enough sleep. 😢

**Comment by evocateur** [comment]
https://github.com/lerna/lerna/releases/tag/v3.10.0 has the fix
