### ISSUE TITLE
Code: 402 You must sign up for private packages : @org1/pkgname

### ISSUE THREAD

**Issue by Vinod1161987** [lerna/lerna#1821]
## Current Behavior
Able to publish package only after giving "access: public" but don't want to give access publicly for download. Want to restrict from outside world. When I am removing this publishConfig setting getting below error:

npm ERR! publish Failed PUT 402
npm ERR! code E402
npm ERR! You must sign up for private packages : @org1/pkgname

## Possible Solution
Is there any setting where we can publish packages by giving "access: private" something like this?
Or do we need to do any configuration at our end?

## Steps to Reproduce (for bugs)
1. created package folder by running "ng build" angular cli command
2. run npm login. Then logged in successfully 
3. npm publish @org/pkgName
4.Getting error
```npm ERR! publish Failed PUT 402
```npm ERR! code E402
```npm ERR! You must sign up for private packages :

**Comment by LinusU** [comment]
@Vinod1161987 private packages are a paid feature of Npm, unless you are paying for private packages for the org you are trying to publish to, you won't be able to publish private packages there...

**Comment by dalefrancis88** [comment]
To anyone in the future that finds this, as this is what comes up from google, this is what you're looking for

https://github.com/lerna/lerna/tree/master/commands/publish#per-package-configuration

**Comment by ddoronin** [comment]
When publishing scoped packages, the access level defaults to restricted. If you want your scoped package to be publicly viewable (and installable) run this command:

`npm config set access public`

https://docs.npmjs.com/misc/config#access

**Comment by taktakpeops** [comment]
just adding `"private": false` in the package.json of your org module works smoothly

**Comment by pcowgill** [comment]
> To anyone in the future that finds this, as this is what comes up from google, this is what you're looking for
> 
> https://github.com/lerna/lerna/tree/master/commands/publish#per-package-configuration

@dalefrancis88 Thanks for linking to this! That per-package configuration goes somewhere in the leaf packages, right? Does it go in a new `lerna.json` file there? In the `package.json`? Other? It's not clear from the lerna docs.

**Comment by pcowgill** [comment]
> > To anyone in the future that finds this, as this is what comes up from google, this is what you're looking for
> > https://github.com/lerna/lerna/tree/master/commands/publish#per-package-configuration
> 
> @dalefrancis88 Thanks for linking to this! That per-package configuration goes somewhere in the leaf packages, right? Does it go in a new `lerna.json` file there? In the `package.json`? Other? It's not clear from the lerna docs.

Based on [this project](https://github.com/ethers-io/ethers.js), it looks like it goes in the `package.json` for each leaf package.
