### ISSUE TITLE
lerna changed does not support positional bump

### ISSUE THREAD

**Issue by kabalage** [lerna/lerna#1826]
## Expected Behavior
I expect `lerna changed prerelease` to show packages that would be updated via `lerna version prerelease`.

## Current Behavior

Currently `lerna changed` does not pass a bump argument to `lerna version`. I have to use `lerna changed --cdVersion prerelease` which is deprecated.

## Context

I need to run custom scripts on changed packages without bumping them.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.6.0 |

**Comment by evocateur** [comment]
I'm afraid `lerna changed` doesn't work like that? I can assure you it _does_ [pass](https://github.com/lerna/lerna/blob/462b15c196bc46ae437a94b9e2d24352ebd93300/commands/changed/index.js#L25) [`<bump>`](https://github.com/lerna/lerna/blob/462b15c196bc46ae437a94b9e2d24352ebd93300/commands/changed/command.js#L18) to [collect-updates](https://github.com/lerna/lerna/blob/462b15c196bc46ae437a94b9e2d24352ebd93300/utils/collect-updates/collect-updates.js#L59), which is the real engine of decision-making shared by `lerna version`, `lerna publish`, and `lerna changed`.

What `lerna changed` does _not_ do is report what the bumped version _would_ be.

It would be clearer if you could create a failing test to demonstrate your use case.
