### ISSUE TITLE
lerna run <script> -- [..args]  how to use ,can you offer a example

### ISSUE THREAD

**Issue by xiaoyanzheng** [lerna/lerna#1828]
lerna run <script> -- [..args] 
how to use , can you offer a example

parent directory package.json content
     "scripts": {
        "build": "node_modules/lerna/cli.js run --scope @mypackage  build -- a=common/file.js",
     }

packages/mypackage/package.json content
"scripts": {
        "build": "webpack --config  $a"
  }

I hope $a is parent common/file.js 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by doug-wade** [comment]
Your example is correct.  Script `local` would be executed, and the argument `index.js` would be passed to it.

**Comment by xiaoyanzheng** [comment]
> Your example is correct. Script `local` would be executed, and the argument `index.js` would be passed to it.

yes, index.js is passed to BBB local script , but  the terminal execute command is：
please look attatch image
<img width="579" alt="46c6ea362407a3c39935d7f238b62a44" src="https://user-images.githubusercontent.com/7248432/50262798-f02d3c00-044d-11e9-875b-acfa7e0a725c.png">

**Comment by evocateur** [comment]
you need to pass an extra `--` to get it past npm.

```bash
lerna run foo -- bar --baz
# > npm run foo bar --baz
# script process.argv.slice(2) === []

lerna run foo -- -- bar --baz
# > npm run foo -- --bar
# script process.argv.slice(2) === ["bar", "--baz"]
```
