### ISSUE TITLE
`lerna run my-script -- --my-arg=true`.  This would iterate through all packages and run the npm script `my-script`, providing the argument `--my-arg=true` to each script.

### ISSUE THREAD

**Issue by xiaoyanzheng** [lerna/lerna#1829]
_Originally posted by @doug-wade in https://github.com/lerna/lerna/issues/1828#issuecomment-448474304_

**Comment by doug-wade** [comment]
I don't understand your issue.  What is wrong with my comment?

**Comment by evocateur** [comment]
if you think the issue isn't closed, reopen it instead of creating a new issue. thanks
