### ISSUE TITLE
[Feature] 'lerna install <args>' as alias for 'npm install <args>'

### ISSUE THREAD

**Issue by adamdoyle** [lerna/lerna#1831]
## Expected Behavior

**Situation:**  Suppose I have a Lerna-based monorepo and I want to convert one of my packages, `packages/myComponent`, from Javascript to Typescript.  Let's say this conversion involves installing typescript, tslint, gulp, gulp plugins, and some DefinitelyTyped `@types/packagename`-style typings as devDependencies.  Maybe there are also some additional non-dev dependencies you'd want to add as well.

**Expected behavior:** Not have to perform the extra steps explained in "Current Behavior" below.

## Current Behavior

Currently, as I understand it, you would choose one of the following two options:

**Option One:**
```bash
cd packages/myComponent
npm install --save-dev typescript tslint gulp gulp-watch gulp-plumber ts-node @types/node @types/gulp @types/gulp-watch @types/gulp-plumber
npm install --save @polymer/lit-element rxjs
lerna bootstrap
```

**Option Two:**
```bash
lerna add --dev typescript
lerna add --dev tslint
lerna add --dev gulp
lerna add --dev gulp-watch
lerna add --dev gulp-plumber
lerna add --dev ts-node
lerna add --dev @types/node
lerna add --dev @types/gulp
lerna add --dev @types/gulp
lerna add --dev @types/gulp-watch
lerna add --dev @types/gulp-plumber
lerna add @polymer/lit-element
lerna add rxjs
```

Some of the inconveniences include:  (1) `lerna add` only allows you to add one dependency at a time, (2) `lerna add` doesn't use the familiar `--save` and `--save-dev` parameters from `npm install`, instead replacing with no parameter and `--dev`, respectively, and (3) running `npm install` without manually following up with a `lerna bootstrap` breaks the build.

## Possible Solutions

- **Possible Solution 1:** add `lerna install` and `lerna remove` commands that takes all of the arguments after `install` (or `remove`), spawns an `npm install` (or `npm remove`) process with those arguments, and then runs `lerna bootstrap` automatically afterwards.  This would resolve Inconvenience (1) and (2), from above, while providing a workaround for Inconvenience (3).
- **Possible Solution 2:** instead of aliasing `lerna install` to `npm install` and aliasing `lerna remove` to `npm remove`, basically reimplement the `npm install` and `npm remove` functionality in the same way that `lerna add` does when adding new external/third-party dependencies, mirroring npm's install/remove API while making non-API-breaking changes.  This could be a stepping stone towards having `lerna` serve as a "more-capable" version of the `npm` command.  Maybe eventually `lerna` could be a superset (of sorts) of the `npm` command.  (e.g. `lerna <whatever>` acts exactly the same as `npm <whatever>`, except for the additional functionality it adds w.r.t. monorepos and symlinked-dependencies)

**Note:** Obviously Possible Solution 1 is significantly less time-consuming/difficult than Possible Solution 2, but perhaps the former could serve as a short-term stop-gap while working long-term towards the latter.  (assuming it's the case that the Lerna author[s]/contributors/users also face the same inconveniences and agree with my characterization of the problem and potential solutions)

**Comment by doug-wade** [comment]
Would instead `lerna exec --scope myComponent -- npm install --save-dev typescript tslint gulp gulp-watch gulp-plumber ts-node @types/node @types/gulp @types/gulp-watch @types/gulp-plumber` serve your need instead?  It's only an extra 7 characters and its far and away the easiest to maintain.

**Comment by adamdoyle** [comment]
Is that fundamentally any different from this?
`npm install --save-dev typescript tslint gulp gulp-watch gulp-plumber ts-node @types/node @types/gulp @types/gulp-watch @types/gulp-plumber; lerna bootstrap`

Because I think that's actually fewer characters.  Ideally I'd just hook `lerna bootstrap` into a stage of the npm lifecycle, but I don't really think there's a lifecycle stage for "after running install".  My understanding is that `post-install` is more for after the project has been installed as a dependency in a different project.

For me it's just yet another learning curve (or "lerna curve" 😉) for the people I'm trying to convince to adopt the tool.  A familiar API, in my opinion, would go a long way towards easing adoption.

**Comment by evocateur** [comment]
I'm not sure why you'd need to install all the devDependencies in every package of the project. Why not just in the root? Does typescript not play well with the node resolution algorithm?

**Comment by adamdoyle** [comment]
I wouldn't install them in every package.  But using 'npm install' inside a package breaks the symlinks.  So you have to run 'lerna bootstrap' to fix them again.  I was just suggesting that if one could use a Lerna command with a similar API as 'npm install', it could *not* break the inter-package symlinks when installing a third party external dependency.

**Comment by evocateur** [comment]
Okay, but as I noted in the parenthesis, how do you propose to solve the UI of such a command? `npm install` works the way it does, in part, because it only ever has to work on _one_ package.json file. It's significantly more complicated with a lerna command.

**Comment by adamdoyle** [comment]
That's a fair point.  `npm` doesn't have to deal with the requirement for managing multiple package.json files, and that does seem to complicate things.

Out of curiosity, what is the use case for managing via lerna CLI the dependencies for a different package than the one that lives in your current directory?  Is it something like:  you're working on a package that consumes an in-house library and you realize that the library needs an additional dependency?  In that case, wouldn't you have to `cd` to that project directory anyways to make the necessary changes to the source files?

The default behavior could be operate-on-the-project-within-current-filesystem-scope and the [arguably] less-common tasks such as "go off and change dependency for one of my other packages in this monorepo" could be relegated to a [more-verbose] flag like `--scope`.

### Sample

#### Sample Project Hierachy
```
    ┌ project/
    ├───┬ packages/
    │   ├──┬ library/
    │   │  └─── libmain.js
    │   │  └─── package.json
    │   ├──┬ application1/
    │   │  └─── app1main.js
    │   │  └─── package.json
    │   └──┬ application2/
    │      └─── app2main.js
    │      └─── package.json
    └─── package.json
```

#### Example Session
##### Adding/removing external dependencies
`cd packages/library`
`lerna install --save rxjs` ←modify project/library/package.json to add rxjs as dependency
`lerna install --save-dev gulp` ←modify project/library/package.json to add gulp as dev dependency
`cd ../application2`
`lerna remove typescript` ←modify project/application2/package.json to remove a dev dependency 

##### Adding/removing internal dependencies
`cd packages/application1`
`lerna install --save ../library` ←relative path¹ disambiguates internal dependency from potentially same-named external libraries
`lerna remove library` ←remove existing internal dependency

##### Hoisting
Haven't really used hoisting much yet, so it's entirely possible I'm overlooking something related to that.

##### Notes
¹ Other possible solutions for disambiguation include:  (1) auto-select by prioritizing internal over external, or (2) automatically add all subdirectories of the `packages/` directory upon any run of lerna CLI [or at least during `lerna bootstrap`], potentially supporting a blacklist and/or whitelist that is potentially modifiable via lerna CLI.
