### ISSUE TITLE
Lerna error: `package.json` does not exist, have you run `lerna init`?

### ISSUE THREAD

**Issue by artemirq** [lerna/lerna#1835]
I run `lerna bootstrap`

## Current Behavior

```
> lerna bootstrap
lerna notice cli v3.8.0
lerna ERR! ENOPKG `package.json` does not exist, have you run `lerna init`?
```

## Expected Behavior

Should work

## Specs

<details><summary>lerna.json</summary><p>

```json
{
  "version": "0.0.5-alpha.0",
  "packages": ["packages/*"],
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
</p></details>

<details><summary>package.json</summary><p>

```json
{
  "private": true,
  "workspaces": [
    "packages/*",
    "examples/*"
  ],
  "devDependencies": {
      "lerna": "^3.8.0"
  }
}
```
</p></details>

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.8.0 |
| `npm --version`  | 6.5.0 |
| `yarn --version` | 1.13.0 |
| `node --version` | v11.4.0 |

| OS | Version |
| --- | --- |
| Windows 10 x64 | 1703 |

**Comment by artemirq** [comment]
It's work if i add `name` field to `package.json` with value `root`

**Comment by artemirq** [comment]
It's strange behavior, because lerna in [some](https://github.com/pedronauck/docz/blob/master/package.json) projects works without field `name` in `package.json` :/

**Comment by evocateur** [comment]
You're using Yarn workspaces, why bother with `lerna bootstrap` at all? It's just calling `yarn install`.

**Comment by artemirq** [comment]
@evocateur I just started recently using `monorepo` architecture with `lerna` + `yarn workspaces` . I don't know `how to better`. I have no found best practices guides to get started with this technologies, therefore i just learned it by [examples on Github](https://github.com/Quramy/lerna-yarn-workspaces-example). I would be glad if you would guide me on the right path ^^

**Comment by evocateur** [comment]
We should definitely improve the error message in this case, I agree.

**Comment by artemirq** [comment]
Up!###

**Comment by christophercr** [comment]
I confirm that the solution mentioned by @artemirq works: add a `"name": "root"` field to the `package.json` solves the issue.

And indeed, this error happens sometimes 😕 

@evocateur do you foresee any fix for this problem?

**Comment by aalexgabi** [comment]
Same error when version field is missing in lerna.json

**Comment by jalovatt** [comment]
I've just started seeing this issue after upgrading a Yarn 2 project that's been working fine with Lerna to v4, but we already have the config options mentioned above as causing trouble if they're absent:

```
// lerna.json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```

**Comment by artemirq** [comment]
@jalovatt Why you needed Lerna? Yarn contain most of functionality for working with workspaces.

**Comment by jalovatt** [comment]
> @jalovatt Why you needed Lerna? Yarn contain most of functionality for working with workspaces.

That's what we ended up doing. Our biggest use for Lerna was the versioning tool, but `yarn version check -i` is close enough.

**Comment by Rhuaer** [comment]
> I confirm that the solution mentioned by @artemirq works: adding a `"name": "root"` field to the `package.json` solves the issue.
> 
> And indeed, this error happens sometimes 😕
> 
> @evocateur do you foresee any fix for this problem?

I think I find the exception reason.
Your project folder name, like `Z2l0bGFiLmd6LmN2dGUuY24vc3NwYy9vcHMvc2VudHJ5LWphdmFzY3JpcHQuZ2l0LTQ3Mzk=` , is incompatible with the package, named `npm-package-arg`, [code here](https://github.com/lerna/lerna/blob/main/core/package/index.js#L95) will throw an exception, and `this.project.manifest` will be `undefined`. Finally you will get this issue.

That will happen when you clone a repo and you specific invalid target folder name.

**Comment by wpyoga** [comment]
@Rhuaer Yes, you are right. If the directory (folder) name is not a valid name [as defined here](https://github.com/npm/validate-npm-package-name#naming-rules), and `"name": "root"` property is missing, then this error will come up.

How to reproduce:

```shell-session
$ mkdir test-lerna@1
$ cd test-lerna@1
$ yarn add lerna
$ yarn lerna init
```

At this point, open package.json and remove the `name` property. Then:

```shell-session
$ yarn lerna bootstrap
yarn run v1.22.17
$ /home/william/Documents/wpyoga/test-lerna@1/node_modules/.bin/lerna bootstrap
lerna notice cli v4.0.0
lerna ERR! ENOPKG `package.json` does not exist, have you run `lerna init`?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Note that if the directory name is valid, then `yarn lerna init` won't create the `name` property at all, and `yarn lerna bootstrap` will succeed.

So it seems to me that `yarn lerna init` knows that the directory name is invalid and proactively adds the `name` property with the value `root`. We can see that `validate-npm-package-name` labels the directory name as an invalid npm package name:

```nodejs
> require('validate-npm-package-name')('test-lerna@1')
{
  validForNewPackages: false,
  validForOldPackages: false,
  errors: [ 'name can only contain URL-friendly characters' ]
}
> require('validate-npm-package-name')('test-lerna')
{ validForNewPackages: true, validForOldPackages: true }
```

I think it would be super helpful if `lerna bootstrap` can detect this fact and inform the user, so corrective actions can be taken.

I ran into this problem when I was making a patch for docusaurus, I made a branch for the commit and used a worktree directory named `docusaurus@not-require-use-ssh`. Eventually everything worked after I added the `"name": "root"` property to package.json .

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
