### ISSUE TITLE
docs(version): `--conventional-commits` flag could be fleshed out better

### ISSUE THREAD

**Issue by revelt** [lerna/lerna#1838]
Currently, the `--conventional-commits` flag, as in `lerna publish --conventional-commits`, is not mentioned among flags in https://github.com/lerna/lerna/tree/master/commands/publish

The flag is used by other serious projects, for example, https://github.com/conventional-changelog/conventional-changelog/blob/master/package.json#L33 so let's document this flag.

Having said that, maybe other flags are missing in `publish` or other commands' documentation pages?

**Comment by evocateur** [comment]
That's because it's documented under `lerna version`, [here](https://github.com/lerna/lerna/tree/master/commands/version#--conventional-commits). Is that not clear enough?

**Comment by revelt** [comment]
@evocateur not really.
Let's document `--conventional-commits`; if `publish` has separate page, let's list all commands that it accepts, at least link to `version` page maybe? What do you think?

**Comment by evocateur** [comment]
> at least link to `version` page maybe? 

That's literally what's [happening](https://github.com/lerna/lerna/tree/master/commands/publish#options):

<img width="748" alt="image" src="https://user-images.githubusercontent.com/5605/50569169-7893c280-0d13-11e9-98dc-55de09c44d6d.png">

The docs for `--conventional-commits` could certainly be beefed up, but they don't need to be moved. PRs welcome.
