### ISSUE TITLE
What the right way to load lerna package?

### ISSUE THREAD

**Issue by wizardnet972** [lerna/lerna#1839]
I'm new to lerna, I read the documentation and other videos about monorepo and lerna technologies but still, I have questions without answers.

Directory tree
```
org-repo/
  apps/
    app1/
      package.json
    admin/
      package.json
  packages/
    core/
      package.json
    errors/
      package.json
```

if I want to add `core` package to the admin app, what command should I use? I saw in video tutorials that they write the package name in package.json then do `lerna bootstrap`. I know that I can not do `npm i core` because it is not in npm registry. - 

so this is the only way to attach this package to my admin app? 

if so, what version to give? the current version of the core package?

**Comment by veeramarni** [comment]
If I'm not wrong, the Lerna team was suggesting to not to use `lerna bootstrap` instead use `lerna link convert` for the time when the repo setup and perform `npm install` followed by any compilation of packages. 

Reference: https://github.com/lerna/lerna/issues/1526

**Comment by evocateur** [comment]
Also, for the specific question of "how to add a local dependency?", you have two options:

1. `lerna add`
    ```
    npx lerna add @my-org/core ./apps/admin
    ```
    This command automatically runs `lerna bootstrap`, leaving the `node_modules` tree in the correct state.

2. Manual edit + `lerna bootstrap`

    In `apps/admin/package.json`:

    ```patch
       "dependencies": {
    +    "@my-org/core": "file:../../packages/core",
         "external-dependency": "^1.0.0"
       },
    ```
    Then `npm install` in the root (or `npx lerna bootstrap`, same diff)

**Comment by revelt** [comment]
**Team**, what if we added a separate file under `lerna/doc/faq.md` (or similar) and covered all common maintenance scenario questions (like this) there? Let's put a link on `readme` to it.

I'd contribute few more common questions like this to such document. For example, this issue above should actually tackle two cases: a) adding a dep onto a lerna package (not root); BUT also, b) adding a dep onto root `package.json`.

Then, **maintenance** issue, ie. `node-check-updates` feature set, but applied to Lerna: c) finding out what package dependencies are outdated, a la `npm outdated` but per-package; d) _automatically updating_ all package dependencies: **d.1** - within semver, a la `npm update`, **d.2** - bumping major, a la `ncu -a`. Now, all this should cover root `package.json` packages as well, separately.

I'm happy to help to compile the questions and even some answers :)

What do you think?

**Comment by wbern** [comment]
I think this would be nice. It's hard to realize all the options you have at first.

**Comment by revelt** [comment]
another new option — [lerna-link-dep](https://www.npmjs.com/package/lerna-link-dep) CLI can link local dependencies within the same monorepo
