### ISSUE TITLE
If "version" script is defined in package.json, should show meaningful error

### ISSUE THREAD

**Issue by azu** [lerna/lerna#1844]
## Expected Behavior

If `"version"` script is defined in `package.json`, `lerna version {version}` show meaninful error.

## Current Behavior

`lerna version {version}` show unuseful message.

> "EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing"

```
> monorepo-sandbox@1.0.0 version /Users/azu/.ghq/github.com/azu/monorepo-sandbox
> lerna version --conventional-commits

lerna notice cli v3.8.1
lerna info versioning independent
lerna info Looking for changed packages since initial commit.
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.
lerna info lifecycle monorepo-sandbox@1.0.0~version: Failed to exec version script
lerna ERR! lifecycle "version" errored in "monorepo-sandbox", exiting 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Possible Solution

- Lerna: show meaningful error message for this case
- User: Remove `"version"` life-cycle script or rename `"version"` script.

Related: 

- https://github.com/lerna/lerna/issues/1729#issuecomment-438452416
- https://github.com/lerna/lerna/issues/1720

## Steps to Reproduce (for bugs)

1. Define "script.version" in `pacakge.json`
2. `lerna version patch`

package.json:
```json5
  "scripts": {
    "bootstrap": "lerna bootstrap",
    "version": "lerna version --conventional-commits",
    "version:patch": "lerna version patch --conventional-commits",
    "version:minor": "lerna version minor --conventional-commits",
    "version:major": "lerna version minor --conventional-commits",
    "publish": "lerna publish from-package"
  },
```

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
lerna notice cli v3.8.1
lerna info versioning independent
lerna info Looking for changed packages since initial commit.
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.
lerna info lifecycle monorepo-sandbox@1.0.0~version: Failed to exec version script
lerna ERR! lifecycle "version" errored in "monorepo-sandbox", exiting 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</p></details>

## Context

I think that some user define `"version"` script.
I have seen the error and search it in lerna repository.
I found multiple similar issues.

- https://github.com/lerna/lerna/issues/1729
- https://github.com/lerna/lerna/issues/1720

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.8.1 |
| `npm --version`  | 6.5.0 |
| `yarn --version` | 1.12.3 |
| `node --version` | v10.13.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS | 10.14.2 |

**Comment by evocateur** [comment]
Sure, I suppose I can't force everyone to use reasonable script names. The "publish" and "version" lifecycles are also called by `npm publish` and `npm version`, which are too close to `npm run publish` and `npm run version` for comfort. I personally recommend naming the script "release", `npm run release` is unambiguous and easily pre- and post-hooked.
