### ISSUE TITLE
lerna can't publish to two registries

### ISSUE THREAD

**Issue by Orange-C** [lerna/lerna#1845]
Some of my packages are published to private registry. I set `publishConfig.registry` in `package.json` of each package. I logged in both npm and private registry. I can publish  if I enter the package folder and run `npm publish`. But I got **401** when I run `lerna publish --no-verify-registry --no-verify-access`. 

It seems to be a **bug** because my colleague who has lerna 3.5.0 with old dependencies can publish while I can't even I set lerna to 3.5.0 because the dependencies were updated. And my lerna is 3.8.0.

## Expected Behavior
1. Packages are published to npm and private registry successfully

## Current Behavior
1. Got 401 when publishing to private registry

## Steps to Reproduce (for bugs)
1. Two packages published to two different registries with two different accounts
2. run `lerna publish`

Here is my `lerna.json` and  `package.json` 
``` json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "xnpm",
  "command": {
    "publish": {
      "npmClient": "npm"
    }
  }
}
```
``` json
"publishConfig": {
   "registry": "http://registry.npm.foo.com"
 }
```

##  Environment
macOS Mojave 10.14.2 

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.8.0 |
| `npm --version`  | 6.5.0 |
| `node --version` | 8.14.0 |

**Comment by evocateur** [comment]
Do you have an auth token in your npm config for that registry? In a `.npmrc` file, it would look something like
```
//registry.npm.foo.com:_authToken="<base64String>"
```

**Comment by Orange-C** [comment]
> Do you have an auth token in your npm config for that registry? In a `.npmrc` file, it would look something like
> 
> ```
> //registry.npm.foo.com:_authToken="<base64String>"
> ```

Yes, here is my `.npmrc` in root. `npm publish` works fine but `lerna publish` got 401

```
email=
//registry.npmjs.org/:_authToken=somehashblabla
//registry.npm.foo.com/:_password=bar
//registry.npm.foo.com/:username=foo
//registry.npm.foo.com/:email=foo@bar.com
//registry.npm.foo.com/:always-auth=false
```

**Comment by Orange-C** [comment]
> Yeah, I figured it was a legacy auth-related problem. I really wish third-party registries would get on board the `_authToken` train.

Thanks, I'll talk about this with the admin of our registry. 

And is there any way I could use `lerna publish` now? I mean maybe some old version of lerna was fine but didn't work for me because the dependencies were updated. Maybe I could lock the version of some dependencies but which? I'll be appreciated if you help me out:)~

**Comment by Orange-C** [comment]
I talked with my admin, he said there is no plan to support `_authToken `😢

Is there any possibility to make some old version of lerna compatible with the old auth? I'll figure my way out to temporarily solve the problem, and I'll be really appreciated if you are going to make old version compatible.😊

**Comment by evocateur** [comment]
Does this still reproduce with the latest lerna v3.8.4?

**Comment by Orange-C** [comment]
> Does this still reproduce with the latest lerna v3.8.4?

v3.8.4 is fine! Thanks a lot~I'll close the issue.
