### ISSUE TITLE
lerna --scope does not support comma separated package names

### ISSUE THREAD

**Issue by gitowiec** [lerna/lerna#1846]
Calling `lerna add external-package-name --scope=internal-package-1,intenal-package-2` throws error
```
lerna notice cli v3.8.4
lerna info filter [ 'internal-package-1,internal-package-2 ]
lerna ERR! EFILTER No packages remain after filtering [ 'internal-package-1,internal-package-2' ]
```

## Expected Behavior
Lerna should split the string after `--scope=` by a comma `,` and iterate resulting array.

## Current Behavior
Here is a dump of stdout when trying to issue command line with multiple package names:
### Tryout 1, resulting error
```
$ lerna add react --exact --scope=components,frontend-admin,frontend-public
info cli using local version of lerna
lerna notice cli v3.8.4
lerna info filter [ 'components,frontend-admin,frontend-public' ]
lerna ERR! EFILTER No packages remain after filtering [ 'components,frontend-admin,frontend-public' ]
✘-1 ~/workspace/s24 [master|●1✚ 5…2] 
```
### Tryout 2, resulting error
```
$ lerna add react --exact --scope components,frontend-admin,frontend-public
info cli using local version of lerna
lerna notice cli v3.8.4
lerna info filter [ 'components,frontend-admin,frontend-public' ]
lerna ERR! EFILTER No packages remain after filtering [ 'components,frontend-admin,frontend-public' ]
✘-1 ~/workspace/s24 [master|●1✚ 5…2] 
```
### Tryout 3, resulting success
```
$ lerna add react --exact --scope=components --scope=frontend-admin --scope=frontend-public
info cli using local version of lerna
lerna notice cli v3.8.4
lerna info filter [ 'components', 'frontend-admin', 'frontend-public' ]
lerna info Adding react in 3 packages
lerna info filter [ 'components', 'frontend-admin', 'frontend-public' ]
lerna info bootstrap root only
yarn install v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 3.13s.
```

## Possible Solution
If package name contains comma `,`, split it.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
</p></details>

## Context
I would like to add package to multiple packages without writing to much.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.8.1 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.12.3 |
| `node --version` | 8.11.4 |

| OS | Version |
| --- | --- |
| Ubuntu | 18.04 |

**Comment by madbence** [comment]
it's a _glob_ pattern, so you can `lerna add react --exact --scope '{components,frontend-admin,frontend-public}'` (use quotes to prevent glob expansion by the shell).

**Comment by gitowiec** [comment]
Thanks, I didn't know that. Somehow I learnt that it is possible to mention all packages in comma separated list - I don't remember where I read it. Another thing is I never used such glob patter as your example, I limited myself to the single or double asterisk patterns. Got to learn that more.

**Comment by madbence** [comment]
indeed, it'd be nice to have a convenient way to specify multiple packages. `lerna` uses `yargs` under the hood to parse the arguments, maybe `--scope` could be interpreted as `array` instead of `string`, so `--scope foo bar baz` will be interpreted as `--scope foo --scope bar --scope baz`.

**Comment by evocateur** [comment]
I personally dislike comma-delimited option values, but then again, I speak native `glob`. I'd be open to falling back to `str.indexOf(',') > -1 && str.split(',')` if the initial glob fails.

I'd rather make globbing more intuitive, though, as positional args of some sort.

**Comment by mattfysh** [comment]
This doesn't work, using `--scope '{pkgA,pkgB}'` - definitely using quotes, and I still get EFILTER

**Comment by evocateur** [comment]
@mattfysh clone lerna and run this command and you'll find that it definitely ...does?

```sh
$ npx lerna ls --scope '{lerna,*/cli}'
lerna notice cli v3.10.6
lerna info filter [ '{lerna,*/cli}' ]
@lerna/cli
lerna
lerna success found 2 packages

# the following command yields identical output:
# npx lerna ls --scope '{lerna,@lerna/cli}'
```

A silly logged reproduction (pass `--loglevel silly`) of your command that generated the EFILTER would be appreciated.

**Comment by mattfysh** [comment]
@evocateur my bad, I was using the directory name, and not the package.json name. Sorry!

**Comment by mplis** [comment]
In case anyone else runs into this, I had to double quote the argument passed to `--scope`, maybe because I'm running `lerna` via `yarn`?

```
yarn lerna run start --scope "'@my-prefix/{service1,service2}'"
```

**Comment by JabbyPanda** [comment]
The slight problem with glob pattern that uses `{ }` as delimiter, that it does not support single value, e.g. `--scope '{pkgA}`

**Comment by fagia** [comment]
@JabbyPanda it should work if you add a trailing comma, eg: `--scope '{pkgA,}'`
