### ISSUE TITLE
Scoped packages

### ISSUE THREAD

**Issue by sonnyp** [lerna/lerna#185]
We switched [node-xmpp](https://github.com/node-xmpp/node-xmpp) to a monorepo and lerna is working great for us thanks!

We're now working on splitting packages and are using the `@xmpp` scope.

Unfortunately it seems lerna doesn't support scoped packages.

Obviously we can't use `@xmpp/*` as folders name in `packages`. My proposal is to read each `packages/*/package.json` instead of relying on the folder name. It also has the benefit of allowing users to remove redundant packages prefix (eg `babel-` or `node-xmpp-`) from their `packages` folder names.

I'm willing to work on this but I'd like to know if you're okay with that or if you'd tackle this differently.

**Comment by sonnyp** [comment]
Hmmm I just realized lerna now has scoped packages support https://docs.npmjs.com/misc/scope

**Comment by sonnyp** [comment]
My bad, all is right, I just had a bad dependency.

Lerna :metal:

**Comment by arunsn43** [comment]
I am looking for a similar solution to deal with scoped packages by using lerna. Any pointers? Appreciate your help!

**Comment by evocateur** [comment]
@arunsn43 The directory name does not have to match the `name` field of package.json. It merely needs to be unique, and _should_ be as similar as possible (like, the package name without the scope). I use scoped packages in directories that lack the scope name literally every day.
