### ISSUE TITLE
Lerna does not lock dependencies when install globally

### ISSUE THREAD

**Issue by GuyMograbi** [lerna/lerna#1851]
Lerna broke due to one of its dependencies which was automatically upgraded. 
Lerna should lock its dependencies so these incidents will not happen. 

## Expected Behavior
Lerna to have reproducable installation. 
So installing Lerna@3.8.5 will always install the same thing. 

## Current Behavior
Installing globally Lerna@3.8.5 use fast-glob version 2.2.4 a couple of days ago, 
and install globlly Lerna@3.8.5 now will provide fast-glob version 2.2.5 which is broken. 

## Possible Solution
Lock versions. 

## Steps to Reproduce (for bugs)
1. See lerna version published on January 3rd
2. See fast-glob 2.2.5 version was published after lerna. 
3. run `npm install -g lerna@3.8.5`
4. See fast-glob/package.json installed is for version 2.2.5

Best reproduced on a clean docker image to avoid cache.

**Comment by GuyMograbi** [comment]
brought up as part of : https://github.com/lerna/lerna/issues/1850 which was mistakenly identified as an upstream bug. 

Solution was suggested by @evocateur https://github.com/lerna/lerna/issues/1850#event-2058506291 as a suggestion to users instead of actual fix to lerna.

**Comment by evocateur** [comment]
Lerna didn't "break", this was a bad publish from an upstream dependency. As the issue is now resolved, there is literally nothing for Lerna to do. Don't install `lerna` globally.
