### ISSUE TITLE
Option to disable CHANGELOG generation

### ISSUE THREAD

**Issue by azz** [lerna/lerna#1852]
Quick question. Is there a way to skip generation of `CHANGELOG.md` files when using `conventional-commits`?

```json
{
  "lerna": "3.8.4",
  "command": {
    "publish": {
      "message": "chore: publish",
      "allowBranch": "master",
      "conventionalCommits": true,
      "changelogPreset": null <-- ???
    }
  },
  "useWorkspaces": true,
  "npmClient": "yarn",
  "version": "independent"
}
```

## Context

For our uses, the CHANGELOG files are not particularly useful. Would be nice to have a way to omit them.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.8.4 |
| `npm --version`  | 6.2.0|
| `yarn --version` | 1.10.1 |
| `node --version` | v10.9.0 |

**Comment by evocateur** [comment]
Yeah, the version bump suggestions and changelog generation are currently conflated behind the `--conventional-commits` option.

I'd rather provide a boolean negated flag (`--no-changelog`) than overload the preset option (the preset also controls how the version bumps are suggested). PRs welcome.
