### ISSUE TITLE
Npm postinstall and lerna bootstrap

### ISSUE THREAD

**Issue by kirill-konshin** [lerna/lerna#1857]
We're using Lerna @ 3.4.0 (also tried on 3.9.1) and we have the following in `package.json`:

```json
{
    "postinstall": "npm run bootstrap",
    "bootstrap": "lerna bootstrap --no-ci --hoist --loglevel warn --concurrency 4",
}
```

It used to work fine until yesterday.

We did not change dependencies, we even haven't committed anything to the codebase, but starting Jan 8 6:01 AM UTC we get infinite loops on bootstrap, even in old branches.

It seems that it could be related to something like https://github.com/lerna/lerna/issues/1103#issuecomment-345065560 but I can't figure out what has changed.

We use strict versions everywhere and on other project same setup works fine (but it has different set of underlying deps).

It begins to work properly if we rename `postinstall` to something else and run it manually.

Another solution is to do `npm install --ignore-scripts` and then do `npm run postinstall`.

**Comment by joetidee** [comment]
I have recently had postinstall errors when deploying to AWS Elastic Beanstalk:
```
  tidee-life@ postinstall /tmp/deployment/application
  lerna bootstrap
  
  lerna notice cli v3.1.1
  lerna info Bootstrapping 7 packages
  lerna info Installing external dependencies
  lerna ERR! npm install exited 1 in 'tidee-life-server'
  lerna ERR! npm install stderr:
  npm ERR! code E404
  npm ERR! 404 Not Found: tidee-life-config@1.0.0
```

Not sure why this is happening as all my package versions are `1.0.0` in each `package.json` file.

**Comment by evocateur** [comment]
@kirill-konshin If you move the `postinstall` to `prepare` does the issue persist?

@joetidee That's not a `postinstall` error, that's a misconfigured sibling dependency. Does it succeed if you pass `--force-local` to your `lerna bootstrap` call?

**Comment by kirill-konshin** [comment]
**Prepare trick DID NOT WORK.**

Team has investigated, looks like the root cause is usage of non-strict lerna dependencies:

![image](https://user-images.githubusercontent.com/1530410/50918245-8cff4b80-13f4-11e9-9b8b-61428db1eca9.png)

Actual issue is probably caused by this commit https://github.com/lerna/lerna/commit/944e36fbd1849fcd3fee554e5598e686d5429fde#diff-f132f0ed53f33747644da180a09d15baR170

Considering that we did not change the lerna version this is a major bug to me.

Also team has figured that the following works:

```diff
-    "postinstall": "npm run bootstrap",
-    "bootstrap": "lerna bootstrap --no-ci --hoist --loglevel warn --concurrency 4",
+    "postinstall": "lerna bootstrap --no-ci --hoist --loglevel warn --concurrency 4 ",
```

E.g. place `lerna bootstrap` directly to `postinstall` script instead of into `bootstrap` script called from `postinstall`.

**Comment by evocateur** [comment]
If you didn't change the version of lerna, then why exactly weren't you _also_ using a lockfile? Seems pretty odd to expect an install to stay stable over time without a lockfile.

And yes, it appears my trick of checking the `npm_lifecycle_event` env var for a _specific_ match isn't sufficient when the script is a nested execution. Sorry about the hassle.

**Comment by evocateur** [comment]
[v3.10.2](https://github.com/lerna/lerna/releases/tag/v3.10.2) should resolve this.

**Comment by kirill-konshin** [comment]
We were not using lockfile because it turned out to be completely useless as we have 30+ developers working on same codebase and most of the times devs resolve conflicts inside lockfile by erasing it :) otherwise over time it was polluted with weirdness. But that's a side question...

More important one is why breaking changes sneaked in minor version update.

[v3.10.2](https://github.com/lerna/lerna/releases/tag/v3.10.2) fix confirmed.

**Comment by evocateur** [comment]
> More important one is why breaking changes sneaked in minor version update.

Humans make mistakes?
