### ISSUE TITLE
Lerna dart

### ISSUE THREAD

**Issue by rrousselGit** [lerna/lerna#1858]
Hello!

I would like to port lerna to the dart world, by handling `pubpsec.yaml` instead of `packages.json`. 
So I've been wondering:

- Would this be possible to host the project on `/lerna/lerna.dart`?
- If not, can I use the name "lerna.dart" and host it under `/rrousselGit/lerna.dart`?
- In the continuation, can I use lerna logo/badge? [![lerna](https://img.shields.io/badge/maintained%20with-lerna-cc00ff.svg)](https://lernajs.io/)

**Comment by evocateur** [comment]
Forgive my ignorance of Dart, but do these packages live on the npm registry? If they don't use a package.json, I will make the assumption that they don't. A brief scan of docs says pub.dartlang.org is where Dart packages live. If your project isn't managing npm packages in some capacity, I'm not sure the Lerna "brand" is appropriate.

I would prefer if you didn't use the Lerna name, but of course I can't stop you. It would be amusing to name it something related to Lerna's inspiration, the [Hydra of Lerna](https://en.wikipedia.org/wiki/Lernaean_Hydra) (`typhon`?), or perhaps a town near [Lerna](https://en.wikipedia.org/wiki/Lerna) (I think `argos` has a nice ring to it).

I don't have the bandwidth to manage more projects under the lerna GitHub org, sorry. I also don't think Lerna has a monopoly on the concept of a monorepo, so it shouldn't be necessary to co-locate. I hope you can understand my reasons.

Good luck!

**Comment by rrousselGit** [comment]
Indeed Dart is unrelated to Npm, it has its own dependency management.

I'm asking this mostly because while monorepo is not specific to lerna, this is _how to deal with monorepo_ that I want to port to Dart.

Dart dependency system has many things in common with NPM, which means that most of the Lerna features could potentially apply here too.

I'm entirely fine with using different names/host/whatever. But by principle, since it would have so many common points with the actual lerna cli, I thought it'd be worth asking.
