### ISSUE TITLE
EUNCOMMIT should provide the list of uncommited changes

### ISSUE THREAD

**Issue by growtofill** [lerna/lerna#1860]
When there are uncommited changes in the working tree, lerna fails with:
```
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.
```
It would be helpful if lerna also provided the list of those changes, similar to `git status --short`.

**Comment by evocateur** [comment]
Is the error message unclear? I don't believe it is `lerna`'s job to run _all_ `git` commands for you.

**Comment by foo4u** [comment]
The error message is clear. However, when running Lerna on a CI server you can't always ssh in and run `git status` to see what went wrong.

**Comment by evocateur** [comment]
@foo4u Fair enough.

**Comment by priley86** [comment]
a big +1 here... have been stuck on this error all day after migrating from lerna 2 -> lerna 3. This would be helpful for many others stuck with this same error I'm guessing...

**Comment by hipstersmoothie** [comment]
Yeah this one is killing me

**Comment by priley86** [comment]
adding a simple `git status` in Travis prior to lerna publish might prove useful... particularly if your team is checking in `yarn.lock`'s with varying hashes/versions of yarn.  In our case, this was the culprit... Travis was using 1.0.7 (and team had upgraded to Yarn 1.13).

At the very least, this should help you find the culprit and either gitignore it or find a way to isolate it prior to running lerna...
https://github.com/patternfly/patternfly-react/blob/master/.travis/after_success.sh#L13

**Comment by evocateur** [comment]
PRs welcome, if the tags didn't make that clear.

**Comment by azz** [comment]
(Issue still relevant)

**Comment by evocateur** [comment]
Goddamnit stale bot, that's your final warning. I guess it's too hard to respect the list of tags I configured to be left alone...

**Comment by growtofill** [comment]
Closing as it has been implemented.
