### ISSUE TITLE
`lerna bootstrap --hoist` fails in CI with `npm ci`

### ISSUE THREAD

**Issue by coreyfarrell** [lerna/lerna#1865]
## Expected Behavior
No errors from `npm ci`.

## Current Behavior
https://github.com/istanbuljs/istanbuljs/pull/269 fails travis-ci in node.js 8.  lerna `^2.11.0` is known to work correctly.

See https://travis-ci.org/istanbuljs/istanbuljs/builds/478060155

## Steps to Reproduce (for bugs)
See PR.

1. Upgrade lerna from 2.x to 3.x, update package-lock.json to match.
2. Submit PR with travis-ci enabled for node.js 8.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.10.3",
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```
</p></details>

## Context
This blocks istanbul from updating to lerna@3.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.10.3 |
| `npm --version`  | 6.4.1 |
| `node --version` | 8.15.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Ubuntu | Ubuntu 14.04.5 LTS |

**Comment by evocateur** [comment]
If you want to use `npm ci` with a lockfile of the entire tree, you need to call `npx lerna link convert` once and stop using `lerna bootstrap`.

A much smaller workaround is to add `--no-ci` to the `lerna bootstrap --hoist` call. (I could have sworn we already disabled the use of `npm ci` internally when bootstrap was called with `--hoist`...)
