### ISSUE TITLE
[Bug] preinstall script during bootstrap shouldn't set npm_config_prefix

### ISSUE THREAD

**Issue by ibezkrovnyi** [lerna/lerna#1866]
We need to run `npm update` in some project as `preinstall` script during `lerna bootstrap` process.

## Expected Behavior
`npm update` is run sucessfully 

## Current Behavior
`npm update` is run with `npm_config_prefix` set to some location which is wrong

Directory where "preinstall" script with `npm update` was run by `lerna bootstrap` is polluted with all files updated by `npm update` command.

## Workaround that doesn't work
`npm --prefix ./ update`

## Workaround that works
`npx crossenv npm_config_prefix=\"\"&&npm update`

## Possible Solution

To comment line
https://github.com/lerna/lerna/blob/a059afd39e7d872b02ef8325486be1377b6e247f/utils/run-lifecycle/run-lifecycle.js#L78

## Steps to Reproduce (for bugs)
1. inside some project (let's name it project A) in any monorepo create "preinstall" script: `"preinstall": "npm update"`
2. run `lerna bootstrap`
3. observe polluted project A's directory

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.10.1 |
| `npm --version`  | 6.5.0 |
| `node --version` | 8.11.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
This seems like the wrong place to run `npm update`, tbh. When the `preinstall` lifecycle is run, it is perfectly acceptable to have `process.env.npm_config_prefix` defined, otherwise it might inherit the _wrong_ value from an enclosing script shell (such as the root).

**Comment by evocateur** [comment]
Also, note that v3.10.2 removed the extra root install lifecycle execution, as it caused more trouble than it was worth. Not sure what you'd expect from an `npm update` other than ...updates?

**Comment by evocateur** [comment]
...unless I'm completely wrong. Wouldn't be the first time this week, or even today. -_-

**Comment by evocateur** [comment]
cuz like, yeah, just running `npm run env | grep npm_config_prefix` in the root of lerna's repo _definitely_ doesn't set it to the CWD. so i must have misread something somewhere when i was extracting that bit.

thanks for your patience, @ibezkrovnyi

**Comment by evocateur** [comment]
So, digging into it, `npm_config_prefix` is _always_ set, it's just that it defaults to the _global_ prefix (`npm c get prefix`), not the `localPrefix` (as it is referred to internally). Would that be sufficient?

**Comment by ibezkrovnyi** [comment]
> This seems like the wrong place to run npm update, tbh. When the preinstall lifecycle is run, it is perfectly acceptable to have process.env.npm_config_prefix defined, otherwise it might inherit the wrong value from an enclosing script shell (such as the root).

1) If I comment line:
https://github.com/lerna/lerna/blob/a059afd39e7d872b02ef8325486be1377b6e247f/utils/run-lifecycle/run-lifecycle.js#L78

`npm update` in `preinstall` script works well

2) if in some circumstances `process.env.npm_config_prefix` can be wrong, is it possible to set it to empty string "" instead of wrong path

3) I think projectDir is wrong value for prefix because `npm` command itself is run with base directory `projectDir`, so current behavior is (please correct me if i'm wrong):

```
npm_config_prefix=packages/projectA
exec_in_folder(packages/projectA) `npm run preinstall` (which executes `npm update`)
```

which is equivalent of:

```
cd packages/projectA
npm update --prefix packages/projectA update
```

which is obviously wrong as we are already inside directory packages/projectA, no need for additional prefix which comes to us from `npm_config_prefix` env variable.

### Possible solution
Is it possible to just erase this env variable? (`config.prefix = ""`)

Update:
> So, digging into it, npm_config_prefix is always set, it's just that it defaults to the global prefix (npm c get prefix), not the localPrefix (as it is referred to internally). Would that be sufficient?

Will test this later, 2 AM now :)

**Comment by evocateur** [comment]
No worries, thanks. Digging through the npm source, I'm fairly confident this value always defaults to the global prefix. Gonna push a patch that omits setting our custom value, and it should probably be fine for your use case.

**Comment by evocateur** [comment]
[v3.10.5](https://github.com/lerna/lerna/releases/tag/v3.10.5)
