### ISSUE TITLE
lerna bootstrap installs incorrect versions of external packages in child packages

### ISSUE THREAD

**Issue by kbbqiu** [lerna/lerna#1867]
I'm having issues with package versions in dependencies within dependencies when there are multiple versions. In this case, some of our older packages are currently on an extremely outdated version of graphql, namely v0.11.8. With our new packages, we're on the latest version of graphql, v14.0.2. The old and new packages share multiple imports--below, i've only included `graphql-type-json`. graphql-type-json has a dependency on graphql. Now on `lerna bootstrap`, we're running into the problem where packageB ends up installing 2 different versions of graphql. 

I've added `"nohoist": ["**/graphql-*/**", "**/graphql/**"]` to the root package.json file so that the package installations are duplicated.

```
lerna-repo
├── lerna.json
├── node_modules
├── package.json
├── packages
│   ├── packageA
│   │   └── node_modules
│   │       ├── graphql <-------------------- 14.0.2
│   │       └── graphql-type-json
│   │           └── node_modules
│   │               └── graphql <------------ 14.0.2
│   └── packageB
│       └── node_modules
│           ├── graphql <-------------------- 0.11.7
│           └── graphql-type-json
│               └── node_modules
│                   └── graphql <------------ 14.0.2
├── services
└── yarn.lock
```

## Expected Behavior

I expect that in `packageB/node_modules/graphql` to be v0.11.7

## Current Behavior

Currently `packageB/node_modules/graphql` is v14.0.2

## Possible Solution

Hopefully someone can help with a solution.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "commands": {
    "publish": {
      "ignore": [
        "*.md",
        "test/**",
        "tests/**",
        "test-deliveries/**",
        "__test__/**",
        "__tests__/**",
        "spec/**"
      ]
    },
    "bootstrap": {
      "ignore": ["graphql"]
    }
  },
  "packages": [
    "packages/*",
    "services/*",
    "infra/*",
    "lambdas/*"
  ]
}

```
</p></details>

</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | VERSION |
| `yarn --version` | 1.13.0 |
| `node --version` | 8.11.3 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.1 |

**Comment by evocateur** [comment]
You're using Yarn Workspaces, this isn't a Lerna bug. All `lerna bootstrap --npm-client yarn --use-workspaces` does is call `yarn install` in the root.
