### ISSUE TITLE
Lerna publish without changing version

### ISSUE THREAD

**Issue by microcipcip** [lerna/lerna#1868]
How do I publish a package to github/npm without changing the version? For example when updating the README.md file?

**Comment by evocateur** [comment]
You can't, sorry. I would think that sort of change constitutes a patch-level change, yes? Why the reticence to publish a new version?

(Or just wait until other changes accrue in that package, it's not like documentation will break a consumer)

**Comment by microcipcip** [comment]
Sometimes I publish a new version and I always find some small typos and I have to publish a new version for that, I feel like it may not be needed, but thanks for confirming that this is not possible ATM.

**Comment by evocateur** [comment]
It's pretty much the same with "normal" `npm publish`. New patch versions aren't especially a big deal, if you believe the typo fixes to be important.

**Comment by microcipcip** [comment]
Ok, having always used Lerna I wasn't aware that the standard `npm publish` forces you to update the version.
