### ISSUE TITLE
Fake write option to automagically fix incremental builds while watching

### ISSUE THREAD

**Issue by MarcoScabbiolo** [lerna/lerna#1870]
This is a feature request/discussion for an ugly fix to a hard to solve problem, feel free to say no :)

When running more than one watch build with `exec --parallel` some builds will fail because some of the dependents packages do not have its required files from its dependencies yet, because they are yet to be built. This is really easy to solve, but tedious, just write a file (without any changes) in the packages being depended on to trigger an incremental build up in the chain. 

Can lerna do it? Im guessing it would take an option to know what type of file to fake-write, and a clever mechanism (maybe also parameterized with an option) to recognize when a spawned process has "finished" and/or "failed", probably reading from stdout/stderr.

My specific use case, if you're wondering, is with TypeScript:

```
lerna exec --parallel 'tsc --outDir lib --watch'
```

I'm happy to help if its decided that its worth it.

**Comment by evocateur** [comment]
Seems like you should be able to use [Project References](https://www.typescriptlang.org/docs/handbook/project-references.html) to run `tsc` for all of the given leaf nodes (`--watch` or not), not one-per-leaf. I don't use TS, though, so I'm probably wrong?

> Can lerna do it?

There's no generalizable pattern in the context of lerna's core mission, so I'm going to say "no, this is out of scope." Adding options is all well and good, but the heuristic to determine "i'm borked, plz halp" is a nightmare of inconsistency and we really don't have the bandwidth to manage those.
