### ISSUE TITLE
Ignore some packages using negative glob

### ISSUE THREAD

**Issue by slavafomin** [lerna/lerna#1874]
Hello!

Thank you for this great tool!

However, some of our packages, when compiled, emit additional `package.json` files in their `dist` directories. Lerna finds those files and throws an error, because it can't find what `package.json` is a canonical one:

> Package name "@acme/package-name" used in multiple packages:

Is it possible to make lerna ignore all the files in nested `dist` directories?

The ideal solution would look like this in `lerna.json`:

```
{
  "packages": [
    "library/**",
    "!library/**/dist/**"
  ]
}

```

However, it looks like negative globs are not supported. Is that so? Maybe there are alternative configuration options for this use case, which I couldn't find? Or maybe this feature worth implementing?

Thank you!

---

I see lerna is using [globby](https://github.com/sindresorhus/globby) under the hood, which supports negative patterns. Actually lerna is adding the following pattern to the `ignore` option: "`**/node_modules/**`". However, it's not working when I specify `!**/dist/**` in my `lerna.json` for some reason.

**Comment by evocateur** [comment]
I would suggest not using globstars (`**`) in your `packages` config, then. It may feel like a lot of work, but in my experience it is better to be explicit about these sorts of things.

I explain why we can't add support for negation in a [similar issue](https://github.com/lerna/lerna/issues/1771#issuecomment-452512783). Yarn Workspaces don't even allow globstars, so negations are extremely unlikely.

**Comment by Mathias54** [comment]
If someone still have the same problem I would like to share my solution. 

This problem happened before I put `resolveJsonModule` in my `tsconfig.json` file. It makes my Nest.js build process get my `package.json` and put it on my dist. 

I changed my approach to `process.env.npm_package_version` instead. I don't have any error anymore. 

I hope I helped.
