### ISSUE TITLE
npmClientArgs being merged with CLI args

### ISSUE THREAD

**Issue by Andarist** [lerna/lerna#1876]
lerna.json
```json
{
    "packages": ["packages/*"],
    "version": "0.0.1",
    "command": {
        "bootstrap": {
            "npmClientArgs": ["--no-package-lock"]
        }
    }
}
```

npm script
```
"bootstrap": "lerna bootstrap --ignore-scripts --hoist",
```

## Expected Behavior

Lerna exexuting:
```
npm ci --no-lockfile
```

## Current Behavior

Lerna exexuting:
```
npm ci --ignore-scripts --no-lockfile
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.10.5 |

**Comment by evocateur** [comment]
You're passing `--ignore-scripts` to `lerna bootstrap`, thus it is passed on to the underlying npm command. Which scripts are you trying to ignore?

Notably, v3.10.4 no longer uses `npm ci` when configured with `--hoist`. (#1865)

**Comment by Andarist** [comment]
🤦‍♂️ I was not aware (or forget about it) that `--ignore-scripts` is also a flag for npm. I thought it's bootstrap specific ( https://github.com/lerna/lerna/tree/master/commands/bootstrap#--ignore-scripts ) and thought that it might get passed to `npm` by accident.
