### ISSUE TITLE
if optional dependency installation fails, lerna bootstrap fails

### ISSUE THREAD

**Issue by starpit** [lerna/lerna#1879]
lerna bootstrap --hoist fails with an exit code of 1 if an `optionalDependencies` fails to install

## Expected Behavior

if one specifies an optionalDependencies of say `fileicon`, one would expect the npm install to succeed on macOS, and only issue warnings on linux. this is the case for a standard `npm install`. thus `lerna bootstrap --hoist` should have the same non-failing behavior.

## Current Behavior

instead, with `lerna bootstrap --hoist`, lerna fails with an exit code of 1

## Steps to Reproduce (for bugs)

1. mkdir opttest && cd opttest && npm init -y
2. npm install lerna && npx lerna init
3. mkdir -p packages/oops
4. echo '{ "name": "oops", "optionalDependencies": { "fileicon": "^0.2.2" } }' > packages/oops/package.json
5. npx lerna bootstrap --hoist
6. echo $?

the above succeeds on macOS, but fails with exit 1 on linux. the expected behavior is to exit 0 on linux as well, with the same warnings on stderr one would get from a regular npm install

on macOS, the final line of the output of the above command sequence is:
```bash
lerna success Bootstrapped 1 package
0 <-- the exit code
```

on linux:
```bash
lerna ERR! npm install exited 1 in 'opttest'
130 <-- the exit code
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.10.5 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | VERSION |
| `node --version` | v8.15.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
Isn't `130` the exit code for `SIGINT`? Without reading the npm source, I can't tell you why that is the exit code. `lerna bootstrap` is just calling `npm install`, after all. You could modify your call to bootstrap to workaround this:
```
npx lerna bootstrap --hoist -- --no-optional
```

**Comment by starpit** [comment]
oof. sorry the 130 was a mistake. the exit code is 1. --no-optional doesn't seem to work, when used in tandem with --hoist.

here is what i get on linux for `(cd packages/oops && npm install)`:
```bash
npm WARN oops@ No description
npm WARN oops@ No repository field.
npm WARN oops@ No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fileicon@0.2.2 (node_modules/fileicon):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fileicon@0.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

for `(cd packages/oops && npm install --no-optional)`, the output is identical without the last two lines

for `npx lerna bootstrap`, no errors

for `npx lerna bootstrap --hoist`, i get the errors above, same with `-- --no-optional`

if i ctrl+z the bootstrap midway through, it looks like lerna is hoisting optional deps to be regular deps at the top-level. this seems to be the root of the problem. i don't know if i'm looking in the right place, but bootstrap seems to merge optional, dev, and regular deps into a single map?

**Comment by evocateur** [comment]
Oh, yeah, you're right. You might be able to `--nohoist` the offending optional deps, but then that doesn't have any awareness of cross-platform status. Ultimately we'd need to be smarter about what _kind_ of dependency collection we are sticking the hoisted deps into.

At the end of the day, you can avoid all of this pain and suffering by allowing `npm` to deal with it all by using relative `file:` references (like Lerna itself does; run `npx lerna link convert` once and then `npm install` in the root). The drawback there is that `lerna link convert` doesn't currently have affordances for the "type" of dependency, and you'll kinda be in the same boat (without some manual fixes).
