### ISSUE TITLE
[question] all my package.json's now contain gitHead key. What to do about it?

### ISSUE THREAD

**Issue by revelt** [lerna/lerna#1880]
hi Daniel and all contributors,

Please answer few questions about `gitHead` key which appears on all `package.json` files after `publish`. I didn't see any explanations of it in readme or existing open or closed tickets.

1. What is the purpose of `gitHead` key in `package.json`?
2. Should package.json key `gitHead` ever be present in the committed `package.json`? (Or should we aim to get it deleted and not ever committed?).
3. In "default" scenario (how things were meant to go, in theory), please explain when exactly is `gitHead` discarded? (ignore this question if we should keep it). Consider two step release scenario, of 1) `lerna version --conventional-commits` and then 2) `lerna publish from-package --yes`.
4. I [saw](https://github.com/evocateur/pectin) `git clean -fdx packages`, is its only purpose to wipe the `gitHead`s from `package.json`'s? If not, or not "only", then what is its purpose?

---

If you need more context here's the publish script from my [monorepo](https://bitbucket.org/codsen/codsen/src/master/) where last concoction of `git add . && git commit -m \"chore: Automated updating of git head entries\" --no-verify && git push` is used to ensure `gitHead` gets committed:

`"publish": "FORCE_COLOR=1 lerna version --conventional-commits && git add packages/*/changelog.md && npm run readme:generate && git add readme.md && lerna publish from-package --yes && git add . && git commit -m \"chore: Automated updating of git head entries\" --no-verify && git push"`

I ended up with this concoction above because without splitting `publish` into two stages, 1) `lerna version --conventional-commits` and 2) `lerna publish from-package --yes`, the **changelogs end up missing from release**. The last chain of `git` commands is used to commit all those changed `package.json`s with new `gitHead` keys. Without that, `git push` refuses to push.

The setup above is flawed because once I commit `package.json`'s with all those new `gitHead`s, all packages end up "changed" since the last release, `lerna changed` reports that every package has changed. Something is wrong with this setup and I suspect `gitHead` and I need your advise.

Thank you.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | `3.10.6` |
| `npm --version`  | `6.4.1` |
| `yarn --version` | n/a |
| `node --version` | `10.15.0` |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.14.2 |

**Comment by evocateur** [comment]
1. `gitHead` provides metadata for packages in the registry, and is based on the [existing behavior](https://github.com/npm/read-package-json/blob/6bac747004d5bc334a9f37c3799a965954d16641/read-json.js#L363) of `npm publish`.
2. It is not meant to be versioned. `lerna publish` should always be [resetting those changes](https://github.com/lerna/lerna/blob/5a7392e59e6ae5ee8aea10467ffb4b12f3b1e3d1/commands/publish/index.js#L180-L182), unless `--no-git-reset` is passed.
3. `gitHead` is a temporary property only meant to exist during `lerna publish` when it is constructing the package tarballs. I don't know why it is appearing in your use case.
4. `git clean -fdx packages` is meant to ensure that the build outputs of the various packages are cleaned before running `pectin`, not to clean temporary build metadata off the package.json files.

**Comment by MMT-LD** [comment]
The same is happening for me... running lerna publish, publishes my tarball to private verdaccio and then errors... i can still pull my updated package though but i guess thats not the point.

```
> lerna publish

lerna notice cli v3.10.6
lerna info versioning independent
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.
lerna info lifecycle packages@undefined~publish: Failed to exec publish script
```

the only change is the new githead ref, which is now uncommitted... any ideas? sorry this code is in a private repo.

Maybe i'm missing something?

**Comment by evocateur** [comment]
@MMT-LD You appear to have a `publish` script defined in a package.json somewhere? It probably shouldn't be named `publish`, as that is quite significant in npm-land. The `EUNCOMMIT` error indicates you tried to run `lerna publish` when there were unversioned changes in the working tree.

**Comment by evocateur** [comment]
@revelt I'm not sure why your monorepo's `lerna.json` file has a [lifecycle key](https://bitbucket.org/codsen/codsen/src/a364eedd7a7ea1a8ed1862614b07d0eed5de780e/lerna.json?at=master&fileviewer=file-view-default#lerna.json-8:10), that looks like it should be a `version` script (that doesn't `git add .` indiscriminately).

**Comment by MMT-LD** [comment]
@evocateur thanks for pointing this out. So i assume i should not have "publish" in my top level package.json file... like so;

```
"scripts": {
    "publish": "lerna publish",
    "prepublish": "yarn build",
  },
```
i think i can see why this would conflict. Thanks. I'll give it a go.

**Comment by evocateur** [comment]
yeah, I would recommend naming the script you place `lerna publish` in "release" so you don't run the risk of confusing `npm run publish` with `npm publish`, as well as the lifecycle overloading...

Also, `"prepublish"` is a deprecated lifecycle, you should be using `"prepare"` or `"prepublishOnly"`.

**Comment by MMT-LD** [comment]
@evocateur Thanks all is working as expected now - not sure if this has been added to the docs or not, but it could help others just knowing not to include publish script in package.json... But maybe it was just overlooked from my part :-)

**Comment by JackHowa** [comment]
I'm having the same problem. Any update updates all githead keys in the packages' `package.json`

**Comment by revelt** [comment]
@JackHowa it's hard to advise without seeing the code but if it helps, check my CI setup https://gitlab.com/codsen/codsen/-/blob/master/.gitlab-ci.yml and scripts in monorepo root's package.json https://gitlab.com/codsen/codsen/-/blob/master/package.json — I'm not using `lerna publish` (relying on npm publish ran in each monorepo package and where `version` is not bumped, npm refuses to publish so all works) — setup is not ideal but it works and I'm using it since last since 2018 Christmas — GitLab CI publishes all npm packages upon each `git push`. Also, not really a cure but rather an ointment — an updater CLI from yours truly [`update-versions`](https://gitlab.com/codsen/codsen/tree/master/packages/update-versions/) removes all `githead`'s it encounters. But `githead`s should not appear at the first place, check the scripts (I know, easier said than done).

I'll close this issue because it's a question and it has been answered by Daniel.

**Comment by JackHowa** [comment]
ok thanks @revelt

**Comment by egemon** [comment]
I had the same problem - it helped for me 
1. to remove gitHead from all package jsons
2. run lerna publish from-package

**Comment by Domiii** [comment]
It appears that there is no self-healing process to clean up temporarily added `gitHead`s after a failed command, so we added a [lerna-fix.js](https://github.com/Domiii/dbux/blob/master/scripts/lerna-fix.js) step to the end of the publish run.

The gist of it, add the following to a file in `scripts/lerna-fix.js`:

```js
function main() {
  const folder = fs.realpathSync('.');
  const pkg = readPackageJson(folder);
  if (pkg.gitHead) {
    const fpath = path.join(folder, 'package.json');
    console.debug(`Deleting gitHead from ${fpath}...`);
    delete pkg.gitHead;
    fs.writeFileSync(fpath, JSON.stringify(pkg, null, 2) + '\n');
  }
}

function readJsonFile(fpath) {
  const content = fs.readFileSync(fpath);
  return JSON.parse(content);
}

function readPackageJson(folder) {
  const packageJsonPath = path.join(folder, 'package.json');
  return readJsonFile(packageJsonPath);
}

main();
```

and then in `package.json` -> `scripts`:
> "lerna-fix": "lerna exec -- node ../scripts/lerna-fix.js"

(NOTE: Our packages are all in the mono root, not in a `packages` sub-folder, hence the `../scripts` relative location.)

**Comment by RyanGuild-TF** [comment]
> I had the same problem - it helped for me
> 
> 1. to remove gitHead from all package jsons
> 2. run lerna publish from-package

Can this be added to to `lerna.json` possibly an enum or flag such as `commands.publish.source` : `from-package` | `from-git`
