### ISSUE TITLE
Follow symlinked packages?

### ISSUE THREAD

**Issue by mvonkeil** [lerna/lerna#1881]
It seems to be impossible to bootstrap symlinked packages inside a monorepo. While this is not an issue in most use cases, there might be a need to do so. 

## Expected Behavior
A symlinked monorepo package should be detected when bootstrapping the repository.

## Current Behavior
Symlinked packages are ignored.

## Possible Solution
Change `followSymlinkedDirectories` to `true` in `lib/make-file-finder.js:14` of the `@lerna/project` package (or even provide a command line option to enable this) 

## Steps to Reproduce (for bugs)
1. Create a new monorepo
2. Create a symlink to an external local package inside the repository
3. run `lerna bootstrap` -> the package won't be detected.

## Context
This is a rather exotic scenario: I'm creating a monorepo on the fly that requires a couple of local packages from outside of the monorepo directory. Making hard copies of those packages is not applicable because it would break HMR and nodemon scenarios, so I need to symlink them into the repository.

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 5.8.0 |
| `yarn --version` | 1.6.0 |
| `node --version` | v8.11.4 |

| OS | Version |
| ---: | :--- |
| Ubuntu | 18.10 |
| (Probably all other unix based systems as well) |  |

**Comment by evocateur** [comment]
This is outside the scope of lerna, sorry.

**Comment by elado** [comment]
Also have the same use case of a wrapper around multiple symlinks. Is there a reason `followSymlinkedDirectories` is turned off by default?

**Comment by aaaaaaaaargh** [comment]
I was wondering the same. Sadly since there was no real interest shown in dealing with the solutions proposed, I had to drop Lerna entirely for a number of projects. I doubt that now, more than a year later, anyone would care to change this behaviour, sorry.

**Comment by elado** [comment]
As a workaround, I ended up listing all symlinked packages in lerna.json, instead of using `pacakges/*`. that worked. could also automate generation of `lerna.json` if list comes from a different place.
