### ISSUE TITLE
Running lerna bootstrap with node_modules doesn't update lockfile

### ISSUE THREAD

**Issue by tanhauhau** [lerna/lerna#1883]
## Steps to Reproduce (for bugs)

1. lerna bootstrap
2. remove a external dependency from package.json for 1 of the package
3. lerna bootstrap again 
4. nothing happens

## Expected Behavior

- remove the dependency from node_modules/
- update `yarn.lock` or `package-lock.json`

## Current Behavior

- nothing happens

## Possible Solution

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 6.6.0 |
| `yarn --version` | 1.12.3 |
| `node --version` | v8.12.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
From the _root_ `node_modules`? Please post your `lerna.json` and the _exact_ command you ran.

**Comment by tanhauhau** [comment]
I realise that if all dependencies are satisfied, lerna will not `do anything`, but what if there's extraneous dependencies? it would be good if we can have a way to `npm prune` / `yarn install` that will optimise/remove extraneous package in the `node_modules` and update the lock file, yet still maintain the symlink within local dependencies.

**Comment by tanhauhau** [comment]
After reading through the other issues, I guess the better long term solution is to have `lerna remove`, I've created an issue for that: https://github.com/lerna/lerna/issues/1886

**Comment by evocateur** [comment]
Gonna close this in favor of #1886, then.
