### ISSUE TITLE
lerna version --conventional-commits should follow exactly conventional commits

### ISSUE THREAD

**Issue by amaurymartiny** [lerna/lerna#1888]
Following #1554. With a commit message
```
chore: bump some-package from 1.0.0 to 2.0.0
```

Then running `lerna version --conventional-commits`, will bump version +0.01, and the reason is explained in https://github.com/lerna/lerna/issues/1554#issuecomment-412213584.

However I think lerna should not bump packages *at all* in this case, to follow conventional commits.

In #1554, the author updated tests and committed with `test: update tests`. Putting all test files inside `ignoreChanges` solves the problem. However, in my case, I updated `my-package`.
- Should I put my `yarn.lock` in `ignoreChanges`?
- If `some-package ` introduces a breaking change in my code, I need to update `./src/main/super_important_file.js`, so I'm forced to bump +0.01, even though it's just a chore.

## Expected Behavior
Should not bump +0.01.

## Current Behavior
Bumps +0.01.

## Possible Solution

Right now, as a workaround, I add a `[ci skip]` message in the commit title.

## Steps to Reproduce (for bugs)

1. git commit -m "chore: bump some-package from 1.0.0 to 2.0.0"
2. lerna version --conventional-commits

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.4.3",
  "npmClient": "yarn",
  "packages": [
    "packages/*"
  ],
  "useWorkspaces": true,
  "version": "4.0.2"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | VERSION |
| `yarn --version` | 1.12.3 |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| macOs Sierra | 10.14 |

**Comment by evocateur** [comment]
As I explained elsewhere, we only use conventional commits to suggest the bump and generate changelogs. Use a different commit type or write your own changelog preset, this isn't changing.
