### ISSUE TITLE
[Question] How to ignore symlink during install for some of the packages

### ISSUE THREAD

**Issue by huchenme** [lerna/lerna#1889]
This might be a niche use case.

We have a repository with a set of active maintained packages and a set of legacy packages and those packages we dont want to maintain.

Let's say we have packages of `active-a` and `active-b`, and `legacy-a` and `legacy-b`. `active-b` depend of `active-a` and `legacy-a` depend on `active-a` as well.

We use `useWorkspaces` to work together with `yarn`

Is there any way that `yarn install` at root will only do symlink between `active-a` and `active-b` but fetch from `npm` registry for `legacy-a` and `legacy-b`, even if the version of `active-a` used in `legacy-a` is same as `active-a`.

We could setup the way that `packages` does not include `legacy` packages, but we want to use lerna to help generate changelog and publish to registry

What is the best way to achieve these?

**Comment by evocateur** [comment]
If you don't want to maintain the packages, why haven't you deleted them from the repository? Use semver correctly and the legacy packages (which will live on in the registry no problem) will just continue on, oblivious.

**Comment by evocateur** [comment]
To be clear, since you're using Yarn Workspaces, this isn't a Lerna problem. Take it up with the Yarn folks.
