### ISSUE TITLE
Allow leaving out non-working links from changelogs

### ISSUE THREAD

**Issue by eemeli** [lerna/lerna#1891]
When dealing with private/on-prem git servers, the commit links included in the changelog generated by conventional-commits are often broken as the server isn't set up to handle them at the expected `repository/commits/:id` path. Also related: #1538

At its core, this is caused by the hosted-git-info dependency of get-pkg-repo ([used by](https://github.com/conventional-changelog/conventional-changelog/blob/cdef2828e34132020845cc6db23077c2c9c8dc1c/packages/conventional-changelog-core/lib/merge-config.js#L160) conventional-changelog-core) [not supporting on-prem solutions](https://github.com/npm/hosted-git-info/issues/11). This is probably not generally fixable.

## Expected Behavior
To fix this, it would be good to expose somehow the [`linkReferences`](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-writer/README.md#linkreferences) context option of conventional-changelog, which allows leaving out these broken links.

## Current Behavior
[Currently](https://github.com/lerna/lerna/blob/b16451a2ed8b8535af6b3cb47289e3c4f6a1563f/core/conventional-commits/lib/update-changelog.js#L34) only the version string is passed in to the conventional-changelog context.

## Possible Solution
I'd be willing to submit a PR adding a new CLI option for `lerna version`, if that's desirable?

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.10.7 |

**Comment by evocateur** [comment]
You can pass your own [`--changelog-preset`](https://github.com/lerna/lerna/tree/master/commands/version#--changelog-preset) to avoid this. I don't want Lerna to get any _more_ tightly coupled to `conventional-changelog` than it already is.
