### ISSUE TITLE
breaking changes in lerna publish between 3.8.0 and 3.10.5

### ISSUE THREAD

**Issue by fkleuver** [lerna/lerna#1895]
## Expected Behavior

When running the following command in a monorepo via the lerna API:
`lerna(['publish', newVersion, '--npm-tag', tag, '--no-git-tag-version', '--no-push', '--no-verify-registry', '--no-verify-access', '-y']);`

I expect the publish to work, as it has been working perfectly for the past few months on our nightly publish.

## Current Behavior

The first failure occurred here: https://circleci.com/gh/aurelia/aurelia/13061 (scroll down and expand the `npm run publish:dev` bit:
```
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.
```
This is after upgrading to 3.10.5.

Note that lerna didn't complain about this before, at 3.8.0: https://circleci.com/gh/aurelia/aurelia/12803

Context: we publish a nightly version to a `dev` tag with the current date appended to the version in a specific format. We manually parse and write back the updated dependency versions to the package jsons and lerna.json because lerna didn't seem to be able to handle this correctly (and I read in an issue somewhere that you didn't want to support non-standard stuff, etc).

But alright, I modified the CI so that it would commit the version bump to the develop branch to get a clean working directory. Then we got this: https://circleci.com/gh/aurelia/aurelia/13778

It fails with:
```
lerna ERR! JSONError: Unexpected end of JSON input while parsing near '' in packages/aot/package.json
lerna ERR!     at module.exports (/home/circleci/repo/node_modules/parse-json/index.js:26:19)
lerna ERR!     at parse (/home/circleci/repo/node_modules/@lerna/project/node_modules/load-json-file/index.js:8:29)
lerna ERR!     at pify.then.data (/home/circleci/repo/node_modules/@lerna/project/node_modules/load-json-file/index.js:10:67)
lerna ERR! lerna Unexpected end of JSON input while parsing near '' in packages/aot/package.json
```

You'll see `bump-version` script above it, but that's not actually modifying anything. It just retrieves the version (I haven't updated the logging output yet) which it passes directly to lerna via the API.

## Possible Solution

As clarified under **context**, it seems an empty file content is passed to the json parser at some point. I don't know enough about lerna internals nor was I able to debug it very effectively, but it smells like some kind of timing+caching issue esp. because the error appeared to be transient-ish.

Additional logging capabilities (`--loglevel`, `verbose` doesn't seem to do anything when passed via the API) would certainly be helpful here.

## Steps to Reproduce (for bugs)

1. `git clone git@github.com:aurelia/aurelia.git`
2. `cd aurelia`
3. `git checkout develop`
4. `npm ci`
5. `npm run publish:dev`

## Context

I spent a solid 3 hours trying to debug lerna with vscode, but it seems like it doesn't actually go wrong if I debug it because it got all the way to `npm publish`.

I see the same behavior if I manually call the command `lerna publish 0.3.0-dev.20190127 --npm-tag dev --no-git-tag-version --no-push --no-verify-registry --no-verify-access -y` (then it gets all the way to publish with an auth error (as expected))

What I noticed is that even if I explicitly specify the version, it still modifies the package.jsons and adds a caret (`^`) to the cross-package dependencies:
![image](https://user-images.githubusercontent.com/9655331/51807055-36ae5b80-2282-11e9-9954-60bdb09fb728.png)

This worries me. We really don't want this - it needs to be absolutely pinned. All packages are always bumped together and published with the same version. Probably has nothing to do with the issue though.

Some troubleshooting notes:
- I added `console.log` statements around `node_modules\parse-json\index.js:26:19` and `node_modules\load-json-file\index.js:8:29` to see the exact JSON being passed into them. I noticed that `parse-json` is receiving an empty string as input, which would explain the strange error. The path is correct though

<details><summary>node_modules/load-json-file/index.js</summary>

Note: none of these console.logs print anything to the console
```js
'use strict';
var path = require('path');
var fs = require('graceful-fs');
var stripBom = require('strip-bom');
var parseJson = require('parse-json');
var Promise = require('pinkie-promise');
var pify = require('pify');
console.log('HELLO FROM LOAD-JSON-FILE');

function parse(x, fp) {
  console.log('parse - x: \n' + x);
  console.log('parse - fp: \n' + fp);
	return parseJson(stripBom(x), path.relative(process.cwd(), fp));
}

module.exports = function (fp) {
  console.log('module.exports - fp: \n' + fp);
	return pify(fs.readFile, Promise)(fp, 'utf8').then(function (data) {
    console.log('pify - data: \n' + data);
    console.log('pify - fp: \n' + fp);
		return parse(data, fp);
	});
};

module.exports.sync = function (fp) {
  console.log('module.exports.sync - fp: \n' + fp);
	return parse(fs.readFileSync(fp, 'utf8'), fp);
};
```

</details>
<details><summary>node_modules/parse-json/index.js</summary>

```js
'use strict';
const errorEx = require('error-ex');
const fallback = require('json-parse-better-errors');

const JSONError = errorEx('JSONError', {
	fileName: errorEx.append('in %s')
});

module.exports = (input, reviver, filename) => {
	if (typeof reviver === 'string') {
		filename = reviver;
		reviver = null;
	}

	try {
		try {
      console.log('INPUT: \n' + input);
      console.log('REVIVER: \n' + reviver);
      console.log('FILENAME: \n' + filename);
			return JSON.parse(input, reviver);
		} catch (err) {
			fallback(input, reviver);

			throw err;
		}
	} catch (err) {
		err.message = err.message.replace(/\n/g, '');

		const jsonErr = new JSONError(err);
		if (filename) {
			jsonErr.fileName = filename;
		}

		throw jsonErr;
	}
};

```

The last bit of log output:

```
    "tslib": "^1.9.3",
    "tslint": "^5.12.0",
    "tslint-microsoft-contrib": "^6.0.0",
    "tslint-sonarts": "^1.9.0",
    "typescript": "^3.2.2",
    "webpack": "^4.28.4"
  }
}
REVIVER:
null
FILENAME:
packages\fetch-client\package.json
INPUT:

REVIVER:
null
FILENAME:
packages\aot\package.json
```

</details>

</br>

- If I remove this package from the lerna config, the next package in the project fails with the same error
- I tried `npm cache clean --force` locally (although I didn't really expect this to matter since the docker on CircleCI always starts fresh anyway)
- I tried downgrading to `lerna@3.8.0` as well as upgrading to `lerna@3.10.7` and tried multiple versions in between (can't guarantee though that those installs were consistent as lerna's dependencies seem to vary freely)
- **on my first attempt to downgrade to 3.8.0 the publish script worked, but then on consecutive attempts it failed again**
- I have not tried tossing my PC out the window yet, but that option is getting closer 😖 

<details><summary>lerna.json</summary><p>

Note: this is the modified version on the `develop` branch, it's changed every day.

```json
{
  "lerna": "3.10.7",
  "packages": [
    "packages/aot",
    "packages/debug",
    "packages/fetch-client",
    "packages/jit",
    "packages/jit-html",
    "packages/jit-html-browser",
    "packages/jit-html-jsdom",
    "packages/jit-pixi",
    "packages/kernel",
    "packages/plugin-parcel",
    "packages/plugin-requirejs",
    "packages/plugin-svg",
    "packages/plugin-webpack",
    "packages/router",
    "packages/runtime",
    "packages/runtime-html",
    "packages/runtime-html-browser",
    "packages/runtime-html-jsdom",
    "packages/runtime-pixi",
    "packages/testing",
    "packages/validation"
  ],
  "version": "0.3.0-dev.20190127"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

Note: this is from running locally

```txt
0 warn deprecated --npm-tag has been renamed --dist-tag
1 silly argv { _: [ 'publish' ],
1 silly argv   'git-tag-version': false,
1 silly argv   gitTagVersion: false,
1 silly argv   push: false,
1 silly argv   'verify-registry': false,
1 silly argv   verifyRegistry: false,
1 silly argv   'verify-access': false,
1 silly argv   verifyAccess: false,
1 silly argv   y: true,
1 silly argv   yes: true,
1 silly argv   loglevel: 'verbose',
1 silly argv   composed: 'publish',
1 silly argv   lernaVersion: '3.10.7',
1 silly argv   '$0': 'scripts\\publish.ts',
1 silly argv   bump: '0.3.0-dev.20190127',
1 silly argv   distTag: 'dev',
1 silly argv   'dist-tag': 'dev' }
2 notice cli v3.10.7
3 verbose rootPath D:\Projects\aurelia-5
4 error JSONError: Unexpected end of JSON input while parsing near '' in packages\aot\package.json
4 error     at module.exports (D:\Projects\aurelia-5\node_modules\parse-json\index.js:29:19)
4 error     at parse (D:\Projects\aurelia-5\node_modules\@lerna\project\node_modules\load-json-file\index.js:8:29)

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.10.7|
| `npm --version`  | 6.6.0|
| `node --version` | 10.15.0|

| OS | Version |
| --- | --- |
| Windows 10 Pro | 1803 |
| Debian| Stretch (docker) |

**Comment by fkleuver** [comment]
**update**: The reported error was a problem between chair and keyboard. In refactoring our nightly publish script I neglected the fact that importing `scripts/bump-version.ts` had the side-effect of calling the update-versions script.

As @bbosman from our team pointed out to me, this promise is not awaited, causing the script to write to the package.jsons while lerna is trying to read from them, resulting in the empty file content issue.

I separated things out and it all seems to work again. However I'd like to keep this issue open if you're okay with that @evocateur to address the following concerns:
- The breaking change of the working directory having to be clean before publishing. While it does not affect us anymore, I still think there should be the option to ignore this. I can't find an explicit option for this, so it used to be possible and now it's not anymore. Or am I missing something?
- It could be a point of improvement to verify whether files can actually be read / are in use, and throw a more meaningful error if that is not the case. Don't know if it's possible or not. This particular scenario might be too rare/convoluted for that be worth the trouble though.
- The passed-in version is not respected. Is there a way to tell lerna *not* to add the caret, or even better, tell lerna to just use the existing version as-is? 

I realize in bypassing the various checks and automatic versioning stuff I may be placing us outside of the "supported scenarios".
However, having a nightly publish with a custom date tag seems like a legitimate use case even in the context of semantic versioning. Is this something you want to consider supporting with lerna? I wouldn't mind helping a hand with the implementation if you can point me to the right places in the code to be doing this.

**Comment by evocateur** [comment]
The way to avoid prefixing the version with `^` is to pass [`--exact`](https://github.com/lerna/lerna/blob/master/commands/version/README.md#--exact). The positional version argument should otherwise be respected, it's used to set the `version` field of changed packages, the inter-package dependencies default to `^` ranges unless you specify `--exact`.
