### ISSUE TITLE
Private npm repo auth failure in CI with lerna publish from-git

### ISSUE THREAD

**Issue by eemeli** [lerna/lerna#1899]
When run in our CI environment (Jenkins, using a fresh Docker container) our snapshot publish job works, but the release publish does not.

## Expected Behavior
The job should succeed, as it does when run locally:

<details><summary>Local success: <code>npx lerna publish from-git</code></summary><p>

```
lerna notice cli v3.10.6
lerna info versioning independent

Found 1 package to publish:
 - @foo/bar => 2.2.1

? Are you sure you want to publish these packages? Yes
lerna info publish Publishing packages to npm...
lerna notice Skipping all user and access validation due to third-party registry
lerna notice Make sure you're authenticated properly ¯\_(ツ)_/¯
lerna WARN ENOLICENSE Packages @foo/bar are missing a license
lerna success published @foo/bar 2.2.1
lerna notice
lerna notice 📦  @foo/bar@2.2.1
lerna notice === Tarball Contents ===
lerna notice 2.2kB   package.json
lerna notice 244.3kB bundle.css
lerna notice 1.9MB   bundle.css.map
lerna notice 141.1kB bundle.js
lerna notice 517.9kB bundle.js.map
lerna notice 2.5kB   CHANGELOG.md
lerna notice 775B    README.md
lerna notice === Tarball Details ===
lerna notice name:          @foo/bar
lerna notice version:       2.2.1
lerna notice filename:      op-bar-2.2.1.tgz
lerna notice package size:  1.5 MB
lerna notice unpacked size: 7.1 MB
lerna notice shasum:        d5aaf187086322f3690a1f421a416ef77695f699
lerna notice integrity:     sha512-AVfVMPCo23QuK[...]gA36XY1PICbIQ==
lerna notice total files:   72
lerna notice
lerna http fetch PUT 201 https://artifactory.local/api/npm/npm-local/@foo%2fbar 5066ms
Successfully published:
 - @foo/bar@2.2.1
lerna success published 1 package
```
</p></details>

## Current Behavior
<details><summary>CI success: <code>lerna publish prerelease --yes --no-push --dist-tag=snapshot --preid=snapshot.201901291031.gc6aa39e5</code></summary><p>

```
lerna notice cli v3.10.7
lerna info versioning independent
lerna info ci enabled
lerna info Looking for changed packages since @foo/baz@2.1.2

Changes:
 - @foo/bar: 2.2.0 => 2.2.1-snapshot.201901291031.gc6aa39e5.0

lerna info auto-confirmed 
lerna info execute Skipping git push
lerna info publish Publishing packages to npm...
lerna notice Skipping all user and access validation due to third-party registry
lerna notice Make sure you're authenticated properly ¯\_(ツ)_/¯
lerna WARN ENOLICENSE Packages @foo/bar are missing a license
lerna success published @foo/bar 2.2.1-snapshot.201901291031.gc6aa39e5.0
lerna notice 
lerna notice 📦  @foo/bar@2.2.1-snapshot.201901291031.gc6aa39e5.0
lerna notice === Tarball Contents === 
lerna notice 2.2kB   package.json                                                     
lerna notice 244.3kB bundle.css                                                       
lerna notice 1.9MB   bundle.css.map                                                   
lerna notice 141.1kB bundle.js                                                        
lerna notice 518.0kB bundle.js.map                                                    
lerna notice 2.6kB   CHANGELOG.md                                                     
lerna notice 775B    README.md                                                        
lerna notice === Tarball Details === 
lerna notice name:          @foo/bar                                           
lerna notice version:       2.2.1-snapshot.201901291031.gc6aa39e5.0                    
lerna notice filename:      foo-bar-2.2.1-snapshot.201901291031.gc6aa39e5.0.tgz
lerna notice package size:  1.5 MB                                                     
lerna notice unpacked size: 7.1 MB                                                     
lerna notice shasum:        e28be7ae6d422dc42b28cdb3bfe66424934417e3                   
lerna notice integrity:     sha512-lJubz0n/EZOQK[...]psIAk8mcPRUvg==                   
lerna notice total files:   72                                                         
lerna notice 
lerna http fetch PUT 201 https://artifactory.local/api/npm/npm-local/@foo%2fbar 569ms
Successfully published:
 - @foo/bar@2.2.1-snapshot.201901291031.gc6aa39e5.0
lerna success published 1 package
```
</p></details>

<details><summary>CI failure: <code>npx lerna publish from-git --yes</code></summary><p>

```
lerna notice cli v3.10.7
lerna info versioning independent
lerna info ci enabled

Found 1 package to publish:
 - @foo/bar => 2.2.1

lerna info auto-confirmed 
lerna info publish Publishing packages to npm...
lerna notice Skipping all user and access validation due to third-party registry
lerna notice Make sure you're authenticated properly ¯\_(ツ)_/¯
lerna WARN ENOLICENSE Packages @foo/bar are missing a license
lerna http fetch PUT 401 https://artifactory.local/api/npm/npm-local/@foo%2fbar 134ms
lerna ERR! E401 Unable to authenticate, need: Basic realm="Artifactory Realm"
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
</p></details>

## Possible Solution
Is `lerna publish` doing something subtly different depending on whether it's called with `from-git` or not?

Does is matter that the CI env uses a global `npmrc` file for its configuration, including npm user authentication?

## Steps to Reproduce (for bugs)
With apologies, I can't even reproduce this on my local machine but only in the CI environment. The npm repo that's used here is an on-prem JFrog Artifactory Professional 6.5.13 rev 60513900.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "command": {
    "bootstrap": {
      "hoist": true
    },
    "publish": {
      "allowBranch": "master",
      "ignoreChanges": [
        "README.md"
      ],
      "message": "chore(release): publish",
      "registry": "https://artifactory.local/api/npm/npm-local/"
    },
    "version": {
      "conventionalCommits": true
    }
  },
  "version": "independent"
}
```
</p></details>

## Context
Running `lerna publish` in a Jenkins job to publish packages to a private npm repo.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.10.7 |
| `npm --version`  | 5.6.0 |
| `node --version` | 8.10.0 |

| OS | Version |
| --- | --- |
| Ubuntu | 18.04.1 |

**Comment by evocateur** [comment]
Forgive me, but I'm rather non-plussed with JFrog's half-assed implementation of an npm registry. There are any number of reasons it could be failing, and I gave up trying a few patch releases ago to even figure out why.

(eek, that's an old version of npm...)

Briefly:
- Maybe _you_ can convince JFrog to implement bearer token auth instead of relying on legacy basic auth? It would make things sooooo much easier.
- Is Artifactory even returning the right error status? I feel like they might be incorrectly returning the auth error when they _meant_ to return `409 Conflict` because `@foo/bar@2.2.1` already exists...
- Unless your global npmrc (assuming it's at `$GLOBAL_PREFIX/etc/npmrc`) has a nerf darts _exactly_ matching `//artifactory.local/api/npm/npm-local/:_auth=<user>:<base64-password>`, I'm not sure that would work?
- There might even be a [just-fixed bug](https://npm.community/t/npm-6-6-0-broke-authentication-with-npm-registry-couchapp/4752/5) in the `_auth` nerf dart, although your local executions passing would seem to indicate that isn't the case...

I'm not sure why `lerna publish from-git` would have a different auth flow from `lerna publish prerelease` (which merely calls `lerna version` internally instead of detecting the tagged packages immediately, skipping `lerna version` entirely). If your Jenkins job isn't doing a _full_ clone of all the tags etc, this might be a problem?

The fact that your `prerelease` version has a `.0` appended to it seems to indicate that there is _some_ tag, _somewhere_...

**Comment by eemeli** [comment]
My gut feeling is that this isn't (only) an Artifactory issue, but some mismatch with the way the Jenkins server is set up. As clues towards that, the prerelease publish works from there, publication to latest works from other jobs (not using Lerna), and running the exact same publish job works in other environments.

Is there a debug flag I can enable to get really verbose logs of the network traffic headers between Lerna and the npm repo? Also, as fair warning, I'm travelling for the next couple of weeks so may not be able to take this further until late February.

**Comment by eemeli** [comment]
This is still an issue for me, and I'd still be interested in a way to verbosely log Lerna's network traffic to be able to figure out what's happening here.

**Comment by hipstersmoothie** [comment]
I would like guidance on more verbose network logging too. Currently we are on Artifactory and get 403s when publishing a certain package. More logs might help our situation

**Comment by evocateur** [comment]
`--loglevel silly`?

**Comment by joekrump** [comment]
We are running into issues as well when trying to publish to Artifactory via CI. This error only shows up when we add a `.npmrc` file to the root of the repo where we have `lerna` set up:
```bash
npm ERR! 404 Not Found: @lerna/run-parallel-batches@3.13.0
```
We need to have a .npmrc file in the project as it contains the credentials to authenticate with Artifactory so that we can publish.  This is what our `.npmrc` file contains:

```
_auth = <USERNAME>:<PASSWORD> (converted to base 64)
email = youremail@email.com
always-auth = true
```
When we remove the `.npmrc` file from our repo then the error goes away and the `npm ci` succeeds, however we then get a 401 when trying to publish to artifactory as we no longer have the required auth configuration in an `.npmrc` file.

**Comment by joekrump** [comment]
Update: I was able to resolve the issue by using package scopes. 
In each package's `package.json`. Ex.
```json
{
  ...
  "name": "@joe/ds-core",
  ...
}
```

In my `.npmrc` file example. (found this in the JFrog Artifactory docs).

```bash
@joe:registry=https://joe.jfrog.io/joe/api/npm/registry-name/
//joe.jfrog.io/joe/api/npm/registry-name/:_auth=${ARTIFACTORY_NPM_TOKEN}
//joe.jfrog.io/joe/api/npm/registry-name/:username=${ARTIFACTORY_USERNAME}
//joe.jfrog.io/joe/api/npm/registry-name/:email=${ARTIFACTORY_USERNAME}
//joe.jfrog.io/joe/api/npm/registry-name/:always-auth=true
```

**Comment by eemeli** [comment]
Finally found a workaround. For some reason, having a JS script that calls `require('child_process').exec('lerna publish ...')` works, provided that it's called from an npm script that in turn is called from a Jenkins execute-shell script.

I have no idea why that particular level of detachment works, and how its running environment might be different from e.g. calling `npx lerna publish ...` directly from the Jenkins script.
