### ISSUE TITLE
Yarn with workspaces vs NPM differences

### ISSUE THREAD

**Issue by richsoni** [lerna/lerna#1900]
I was looking at this issue: https://github.com/lerna/lerna/issues/1349

and it seems like @evocateur recommends npm.  I am wondering what the drawbacks are to using lerna with npm vs. yarn with workspaces?

This seems like something that would benefit from having a doc explaining.  If it does not exist already.  More than happy to help put that together once I have a more clear understanding

**Comment by evocateur** [comment]
Yeah, it's kinda a big question. I feel like I've answered it fifteen times already.

**Comment by ncphillips** [comment]
You should definitely put the answer somewhere that's more public ;)

**Comment by JamesHenry** [comment]
Hi Folks, I am going to close this one. Now in 2023, `npm`, `yarn` and `pnpm` are all really good and work well with `lerna`.

Make sure you move away from lerna's own legacy package management capabilities that needed to exist before we had these three awesome package managers to choose from (i.e. stop using `lerna add`, `lerna bootstrap` and `lerna link` and use lerna with `useWorkspaces` enabled instead).

More reading:

https://lerna.js.org/docs/getting-started
https://docs.npmjs.com/cli/v9/using-npm/workspaces
https://yarnpkg.com/features/workspaces
https://pnpm.io/workspaces
