### ISSUE TITLE
lerna in gitlab-ci ends up with ERR! EUNCOMMIT 

### ISSUE THREAD

**Issue by MerkAndreas** [lerna/lerna#1901]
We are using lerna to manage our central npm packages. As versioning and build pipeline we are using a private GitLab-CE with GitLab-CI followed by a private npm registry.  

The `package.json` looks like this:

```json
{
  "private": true,
  "scripts": {
    "clean": "lerna clean --yes",
    "bootstrap": "lerna bootstrap --ci --registry {my-private-registry}",
    "build": "lerna run build",
    "lint": "lerna run lint",
    "test": "lerna run test",
    "release": "lerna publish --loglevel 5 --registry {my-private-registry}",
    "release-ci": "lerna publish from-package --no-git-reset --yes --loglevel 5 --registry {my-private-registry}"
  },
  "devDependencies": {
    "lerna": "^3.10.7"
  }
}

```

If I run **`yarn release`** local on my dev-system, everything works fine.  

The `.gitlab-ci.yml` looks like this and runs **`yarn release-ci`**:

```yml
script:
    - apk add --no-cache git
    - npm install lerna --global --registry ${REGISTRY}
    - npm run bootstrap --ci --private --registry ${REGISTRY}
    - npm run build
    - echo registry = ${REGISTRY}:_authToken=${NPM_TOKEN} > .npmrc
    - cat .npmrc
    - npm run release-ci
```

Before the pipeline runs, all version changes are done.

## Expected Behavior

`lerna publish` deploys the packages

## Current Behavior

The CI pipeline breaks with:
```
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.
```
The `lerna publish` changed the `gitHead` in all `package.json`, despite of the cmd runs with the attributes `from-package --no-git-reset`. I don´t know, why lerna changes the gitHead??

I searched a lot on google and tried a lot ideas from this issue list, without a working solution.

How is it possible to use lerna publish in gitlab-ci??

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "1.2.123-alpha.2",
  "command": {
    "publish": {
      "verifyAccess": false
    }
  }
}
```
</p></details>

</p></details>

## GitLab Environment

|        Executable | Version |
| ----------------: | :------ |
| `lerna --version` | 3.10.7  |
|   `npm --version` | 6.4.1   |
|  `yarn --version` | 1.9.4   |
|  `node --version` | v8.12.0 |

| OS                 | Version |
| ------------------ | ------- |
| docker node-alpine | v8      |

## local dev Environment

|        Executable | Version |
| ----------------: | :------ |
| `lerna --version` | 3.10.7  |
|   `npm --version` | 6.3.0   |
|  `yarn --version` | 1.12.3  |
|  `node --version` | v8.12.0 |

| OS         | Version |
| ---------- | ------- |
| Windows 10 | 1803    |

**Comment by thecodejack** [comment]
@MerkAndreas I had similar issue. Fixed it by removing publish script as mentioned in https://github.com/lerna/lerna/issues/1880#issuecomment-456502998

**Comment by MerkAndreas** [comment]
Thank you for the response!
This wasn´t the issue, but brought me to the solution. I´ve changed the .npmrc-file in the gitlab-ci.yml to log into the registry with `- echo registry = ${REGISTRY}:_authToken=${NPM_TOKEN} > .npmrc` and this was the uncommited change and not the gitHead.

Thank you!!

**Comment by tgelu** [comment]
@MerkAndreas May I ask how did you solve it? :) I have the exact same scenario

**Comment by MerkAndreas** [comment]
@tgelu My solution was to add the following lines to the .gitlab-ci.yml
```
before script:
  - npm config set //path-to-repository/npm-registry/:_authToken=${NPM_TOKEN}

build:
  script:
    - npm install --registry ${REGISTRY}
    - npm run bootstrap --ci --private --registry ${REGISTRY}
```
