### ISSUE TITLE
Does `lerna publish` open source code?

### ISSUE THREAD

**Issue by dlombardi** [lerna/lerna#1902]

**Comment by evocateur** [comment]
`lerna publish` merely uploads tarballs to an npm registry (public by default). The license of the software being published is what determines if it is "open source" or not. You certainly don't have to have the code hosted on a public GitHub repo to use `lerna publish` (or `npm publish`, for that matter).

**Comment by dlombardi** [comment]
so as a result of running `lerna publish` code intended to be private will not end up accessible to the public on the npm registry?

**Comment by evocateur** [comment]
That's up to your configured `--registry` or, if you're using [scoped packages](https://docs.npmjs.com/misc/scope), what the value of the `publishConfig.access` property of a given leaf node's package.json is (it's `"private"` by default).

To be clear, whether or not a package is public or private has nothing to do with whether or not it is considered "open source" or not. That's a licensing decision, which`lerna publish` does not affect in any way.
