### ISSUE TITLE
document --scope and --ignore flags

### ISSUE THREAD

**Issue by JLarky** [lerna/lerna#1904]
Hey guys, just sharing my feedback. I was trying to piece together patterns for --scope and --ignore using all kinds of `+`s and `*` just to realize one hour later that you can pass multiple --ignore and --scope flags at the same time, i.e. I needed to ignore two packages and it was just `--ignore=package1 --ignore=package2`. So maybe better documentation and/or examples? I remember that I was trying to do exact same thing a year ago and docs didn't seem to improve since then :)

Right now docs for those options are literally `--ignore <glob>` what is glob? what kind of syntax I can use? help?

**Comment by evocateur** [comment]
All the commands that accept filter options link to these docs in their readmes: https://github.com/lerna/lerna/tree/master/core/filter-options#options

These tests are the best demonstration of what you can pass to `--scope` and `--ignore`:
https://github.com/lerna/lerna/blob/c0a750e0f482c16dda2f922f235861283efbe94d/commands/list/__tests__/list-command.test.js#L305-L356

"glob" is shell lingo for a pattern that matches files or directories. The best summary is here: https://github.com/isaacs/node-glob#glob-primer

PRs welcome to improve the docs. ✨

**Comment by JLarky** [comment]
Still don't see it documented or in tests. Example `"--ignore", "package-{3,4}"` but I'm talking about `--ignore mypackage-1 --ignore somepackage-2`. Although maybe `package-@(2|3|4)` can do this, but in my case I couldn't make it work

**Comment by evocateur** [comment]
I made it even clearer just the other day:
https://github.com/lerna/lerna/blob/45a05acf2d52a46f553fc1efadf9a32312aca82b/core/filter-options/__tests__/get-filtered-packages.test.js#L54-L72

**Comment by JLarky** [comment]
Yes, looks great, I guess docs can at least link to tests then :)

**Comment by peanutenthusiast** [comment]
I can look into this documentation PR !

**Comment by peanutenthusiast** [comment]
@evocateur Upon running `npm i` => `npm test`, a number of tests fail.

by running, `npm i` => `lerna bootstrap` => `npm test`, all tests pass. 

Do you suppose the [CONTRIBUTING](https://github.com/lerna/lerna/blob/master/CONTRIBUTING.md) needs updating as well?
