### ISSUE TITLE
Version command do not take semver into account with local dependencies on independent mode

### ISSUE THREAD

**Issue by barakd** [lerna/lerna#1907]
When using Lerna in independent mode, and conventional commits,
running the `lerna version` command will not take into consideration semver, when updating local dependencies.

E.G:
With the following packages graph:
- package alpha@1.0.0
- package usage@1.0.0 -> this package is using package `alpha`, with semver definition of `^1.0.0`.

Assuming we make a change in package `alpha` with the following commit message:
`
feat: break something
BREAKING CHANGE
a breaking change!
`
## Expected Behavior
1. Lerna will update the version of package `alpha` to `2.0.0`
2. It **won't** update the version of package `usage` due to the fact that it relies on package `alpha` with a minor version range.

## Current Behavior
1. Lerna updates package `alpha` version to `2.0.0` (as expected)
2. Lerna updates a minor version to package `usage`, and changes the semver range of package `alpha` to `^2.0.0`. (**not** expected)

## Possible Solution
Not sure how to implement it, or why it happens, I started debugging it, but I don't have any conclusions yet.

If you have any guidance I don't mind to try a create PR myself to fix this.

## Steps to Reproduce (for bugs)
You can easily see this behavior in this git log:
https://github.com/barakd/lerna-issue-example/pull/1/commits

In case you want to reproduce:
1. Fork this repo https://github.com/barakd/lerna-issue-example.git
2. run `lerna bootstrap` 
3. run `npm run commit` and make sure to say `y` to the breaking changes question.
![image](https://user-images.githubusercontent.com/7824284/51985154-e44d8480-24a5-11e9-8ff4-c90bd578ac61.png)
4. run `lerna version`
5. say yes to the prompt
6. you end up as described above.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.10.7",
  "version": "independent",
  "command": {
    "publish": {
      "conventionalCommits": true
    },
    "version": {
      "message": "chore(release): update versions [ci skip]"
    }
  },
  "packages": ["packages/*"]
}
```
</p></details>

## Context
I am using lerna to manage my packages CI.
I want to automate my CI, so it will manage my packages releases.
This issue is very disturbing as it colud lead my CI to update a package with breaking changes without my knolwedge.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | v3.10.7 |
| `npm --version`  | v6.4.1 |
| `yarn --version` | v1.12.3 |
| `node --version` | v8.11.3 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14 |

**Comment by evocateur** [comment]
This _is_ actually expected, and demonstrates one of the limitations of automating Lerna right now.

Unless you are using relative `file:` specifiers, Lerna establishes the relationship of local packages by "matching" the semver range of a local dependent in a local sibling's dependencies. If it does _not_ `semver.satisfy()` (generally a different major than the local sibling), it is "disconnected" and will _not_ be updated as you've described.

It is assumed that your tests are sufficient to validate that the local siblings continue to successfully interoperate. If that is not the case, I suggest you improve your test suite.

When making breaking changes in a given leaf node, _if_ any modification to local consumers is necessary (not all breaking changes break all consumers), you would make those adjustments in the same commit (or close to it, as your tests should have failed in the consumer after making an atomic commit in the origin package). This is one of the advantages of a monorepo, and Lerna expects that to be the case.

Arbitrarily choosing a minor bump when a dependency bumps its major is a bit awkward, sure, but it's "less bad" than the alternative, which is suddenly allowing your local packages to drift apart silently.

**Comment by evocateur** [comment]
I agree that the "version bump only" message kinda sucks, but the fact that local dependents will be bumped when a local dependency changes is one of the bedrock principles of Lerna as it exists today and *will not* be changing.

> I am using Lerna to hold many packages which aren't necessarily maintained by the same groups or people.

If sufficient test coverage between modules isn't possible to determine whether or not a given breaking change is _actually_ breaking, respectfully, I would suggest that they shouldn't be in the same monorepo. Lerna can't fix development processes, and it wasn't designed to replace proper package dependency relationships _entirely_.
