### ISSUE TITLE
how to ignore symlink when use lerna bootstrap

### ISSUE THREAD

**Issue by soulcm** [lerna/lerna#1910]
When run `lerna bootstrap`, lerna will create symlink for related dependencies, now I just want to use real `npm install` but not symlink for dependencies.

Is there any method working for this scene?

Thanks.

**Comment by wbern** [comment]
This might help. https://github.com/lerna/lerna/issues/1889

**Comment by evocateur** [comment]
You can choose exactly which dependencies to bootstrap with the `--scope` option. Any other local dependencies that don't match this argument will be installed from the registry.

```
npx lerna bootstrap --scope $my_singleton_package
```
