### ISSUE TITLE
Powershell see lerna logs as errors

### ISSUE THREAD

**Issue by PsykoSoldi3r** [lerna/lerna#1911]
TFS/Windows Powershell catches outputs of lerna as errors. This means that the automatisch build runs in TFS will always fail.

![lerna_powershell](https://user-images.githubusercontent.com/2241262/52134109-206a1c00-2643-11e9-8b14-68a7bf8baa50.png)

## Expected Behavior
Lerna output that's not a error must not be logged as a error

## Current Behavior
The logs of lerna is received by Powershell as a error

## Context
Running a build definition in TFS will fail, because Lerna give for every output an error.

## Your Environment
TFS, Windows 10

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.10.7 |
| `npm --version`  | 6.4.1 |
| `node --version` | 10.15.0 |

| OS | Version |
| --- | --- |
| Windows Server 2016 | 1607 |

**Comment by evocateur** [comment]
`stderr` is for error messages _and_ diagnostics (i.e., logging that is not program output). [This blog post](https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout) explains the history. An _actual_ error is signified by a [non-zero exit code](https://www.tldp.org/LDP/abs/html/exit-status.html), not messages sent to `stderr`. It would be nice if Powershell followed 30-year-old shell conventions.

Cursory googling indicates you can turn of this "feature": https://stackoverflow.com/a/44564657/5707

This is a bug with Powershell, not lerna, thus closing.
