### ISSUE TITLE
How to point to a branch externally?

### ISSUE THREAD

**Issue by sartaj10** [lerna/lerna#1913]
Hi there,

I have a lerna repo https://github.com/esnet/react-network-diagrams and I'm currently working on a branch, multipoint. I haven't released a version of this branch yet since it's still in development.

I would like to point to this branch from another project and I was wondering how could I acheive that?

## Expected Behavior

I would expect that I can install and point to this particular branch externally without any issues. 

## Current Behavior

I've tried the following...

```
"react-network-diagrams": "git+https://github.com/esnet/react-network-diagrams.git#multipoint"
```

OR

```
"react-network-diagrams": "esnet/react-network-diagrams#multipoint"
```

But none of these seem to work. I get an error saying that the package can't be found.

Could you please let me know how to achieve this?

## Steps to Reproduce (for bugs)

1. Create a new react app
2. Add this dependency and point to a github branch
3. Start the app

This is my top level package.json
```json
{
    "scripts": {
        "start": "cd packages/website && npm run start",
        "precommit": "lint-staged"
    },
    "lint-staged": {
        "*.ts": [
            "prettier --print-width 100 --tab-width 4 --write",
            "git add"
        ]
    },
    "devDependencies": {
        "husky": "^0.13.3",
        "lerna": "^2.0.0",
        "lint-staged": "^3.4.0",
        "prettier": "^1.7.0"
    },
    "dependencies": {},
    "main": "packages/react-network-diagrams/lib/index"
}
```

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "lerna": "2.0.0",
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0 |
| `npm --version`  | 6.0.1 |
| `yarn --version` | 1.10.1 |
| `node --version` | v10.1.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.6 |

**Comment by evocateur** [comment]
You should start by using a modern version of lerna, v2 is basically dead now. I also need your lerna.json, or maybe you could just tell me if you're using Yarn Workspaces (which if that's the case makes this a Yarn bug)?

**Comment by evocateur** [comment]
As for the actual git dep, Lerna doesn't do anything fancy, you'll need to follow the correct syntax and let npm sort it out: https://docs.npmjs.com/about-packages-and-modules#npm-package-git-url-formats

**Comment by sartaj10** [comment]
@evocateur 
I'll update it to use v3. Additionally, i've updated the lerna.json above.

That's what I thought. It shouldn't be an issue trying to point it to a git branch.

**Comment by evocateur** [comment]
If you can `npm install` in the root of the repo with that exact specifier successfully, then we might have a bug in `lerna bootstrap`. Until then, I can't say.
