### ISSUE TITLE
"Couldn't publish package "xxx" Not Found" trying to migrate to new registry

### ISSUE THREAD

**Issue by FezVrasta** [lerna/lerna#1915]
## Expected Behavior
I'm trying to migrate a monorepo from a private registry to the public npm one.

I updated the registry and credentials, but when I try to publish I get:

```
error Couldn't publish package: "https://registry.npmjs.org/@quid%2freact-layouts: Not Found"
```

## Current Behavior
```
error Couldn't publish package: "https://registry.npmjs.org/@quid%2freact-layouts: Not Found"
```

## Steps to Reproduce (for bugs)

1. publish some packages to a public registry
2. try to publish them to a different registry

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.3.2",
  "version": "1.30.4",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "conventionalCommits": true,
      "ignoreChanges": [
        "*.md"
      ]
    }
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
[1/4] Bumping version...
info Current version: 1.31.0
[2/4] Logging in...
[3/4] Publishing...
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
lerna ERR! yarn publish --ignore-scripts --new-version 1.31.0 --non-interactive --no-git-tag-version quid-react-layouts-1.31.0.tgz stderr:
error Couldn't publish package: "https://registry.npmjs.org/@quid%2freact-layouts: Not Found"
lerna ERR! yarn publish --ignore-scripts --new-version 1.31.0 --non-interactive --no-git-tag-version quid-react-layouts-1.31.0.tgz exited 1 in '@quid/react-layouts'
Script failed with status 1
```
</p></details>

## Your Environment
Travis CI

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.3.2 |
| `npm --version`  | none |
| `yarn --version` | 1.13.0 |
| `node --version` | 10.x |
-->

**Comment by evocateur** [comment]
First of all, you're using Yarn, whose `yarn publish` command is not _nearly_ as robust as `npm publish`. Secondly, you should update Lerna, 3.3.2 is extremely old (newer versions of Lerna don't even use subprocess CLI calls to publish anymore).

With modern versions of Lerna, you should be able to do the following to migrate the packages at their existing version to the new registry:

```bash
npx lerna publish from-package
```

You can run that command as many times as you like, as it only attempts to publish versions of a package that do not already exist on the configured registry.

**Comment by FezVrasta** [comment]
Thanks for the info! I'll update
