### ISSUE TITLE
Question: Can lerna add support for npm RFC 10?

### ISSUE THREAD

**Issue by styfle** [lerna/lerna#1918]
Hello 👋 

I have only briefly used lerna so I'm asking a question before making a full feature request.

Is it feasible for lerna to support [npm RFC 10](https://github.com/npm/rfcs/blob/latest/accepted/0010-monorepo-subdirectory-declaration.md)?

I ask because I'm not sure if lerna ever modifies the `/packages/<name>/package.json` file.

My guess is that `lerna create` would be a good place to create `package.json` with the proper `repository` and `directory` key defined (thus supporting RFC 10).

Thoughts? 😄

**Comment by evocateur** [comment]
Sure, I guess? Lerna itself would have no use for the property, of course. [Here](https://github.com/lerna/lerna/blob/45a05acf2d52a46f553fc1efadf9a32312aca82b/commands/create/lib/lerna-module-data.js#L182-L192) is where `lerna create` would need it, somehow. Notably, [here](https://github.com/lerna/lerna/blob/45a05acf2d52a46f553fc1efadf9a32312aca82b/commands/create/index.js#L320) is how one might compute the `directory` value.

**Comment by evocateur** [comment]
I added `repository.directory` fields to Lerna itself in aec5023a

**Comment by styfle** [comment]
@evocateur Awesome! 👍 


I think once I start using learna, I'll be more comfortable creating a PR, but that might not happen anytime soon so feel free to add it yourself 😄

**Comment by evocateur** [comment]
Stale bot is clearly broken, sorry for the confusion. This is still something a PR is welcome for.

**Comment by styfle** [comment]
@evocateur Thanks, I am not able to PR right not but I am currently using lerna in a real project so maybe soon 😄

**Comment by JamesHenry** [comment]
Hi Folks 👋 I am going to close this one in favour of the new source of truth for improvements to customizing the output of `lerna create` here: https://github.com/lerna/lerna/issues/3444
