### ISSUE TITLE
Github Release errors

### ISSUE THREAD

**Issue by tivac** [lerna/lerna#1920]
## Expected Behavior

Lerna should create a new GitHub release for me when publishing new packages.

## Current Behavior

I get an error:

```
? Are you sure you want to publish these packages? Yes
lerna info git Pushing tags...
lerna info github Creating GitHub releases...
lerna ERR! HttpError: Not Found
lerna ERR!     at response.text.then.message (C:\Users\tivac\Documents\GitHub\modular-css\node_modules\@octokit\request\lib\request.js:55:27)
lerna ERR! HttpError: Not Found
lerna ERR!     at response.text.then.message (C:\Users\tivac\Documents\GitHub\modular-css\node_modules\@octokit\request\lib\request.js:55:27)
lerna ERR! lerna Not Found
`error.code` is deprecated, use `error.status`.
`error.code` is deprecated, use `error.status`.
npm ERR! code ELIFECYCLE
npm ERR! errno 404
```
## Steps to Reproduce (for bugs)

1. https://github.com/tivac/modular-css
2. Create a `./.env` file containing a `GH_TOKEN=...` value
3. `npm run release`

<details><summary>lerna.json</summary><p>

```json
{
  "version": "22.1.3",
  "command": {
    "publish": {
      "conventionalCommits": true,
      "message": "release: %s :tada: :rocket:"
    },
    "version": {
      "conventionalCommits": true,
      "githubRelease": true
    }
  },
  "packages": [
    "packages/*"
  ]
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
114 error HttpError: Not Found
114 error     at response.text.then.message (C:\Users\tivac\Documents\GitHub\modular-css\node_modules\@octokit\request\lib\request.js:55:27)

```
</p></details>

## Context

I'd like to automatically create GitHub releases when publishing with Lerna.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.11.0 |
| `npm --version`  | 6.5.0 |
| `node --version` | 10.14.2  |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Windows 10 | 1703 |

**Comment by evocateur** [comment]
I don't have a lot of depth on the Github API, perhaps @milesj has some insight on this mysterious 404?

**Comment by milesj** [comment]
What version of the `@octokit` packages are installed?

**Comment by tivac** [comment]
I'm not on the PC that experienced this error currently, I'll be able to check in like... 10 hours.

**Comment by evocateur** [comment]
It's whatever Lerna installs, which in the last week would have been `@octokit/request` v2.3.0 and `@octokit/rest` v16.15.0.

**Comment by wKich** [comment]
I have same error on fresh GitHub repo. And packages that installed has same version as you said `@octokit/request` v2.3.0 and `@octokit/rest` v16.15.0.

**Comment by milesj** [comment]
Are these private repositories? Did you give your token repo access?

<img width="493" alt="screen shot 2019-02-14 at 20 54 06" src="https://user-images.githubusercontent.com/143744/52835296-b74ec380-309a-11e9-846e-a13ffadc1339.png">

**Comment by wKich** [comment]
Hm... Seems I create private repo and generate token with `repo:public_repo` access. After switching to public it works. Thanks.

I think it would be great if docs will have some clarification about repo access levels for token.

**Comment by tivac** [comment]
I'll try with a different token. An explanation of the required token values would be great as it's totally possible that I guessed wrong when setting that up.

**Comment by milesj** [comment]
Yeah, let use know if the "repo" access in the token is all that's required to fix it. If so we'll update the docs.

**Comment by wKich** [comment]
[Here](https://www.appveyor.com/docs/deployment/github/) it says that:
> Minimal token scope is `repo` or `public_repo` to release on private or public repositories respectively.

So I think for private repos you should create token with `repo:*` scope. And I agree that for public repo is enough `repo:public_repo`.

**Comment by tivac** [comment]
Just published https://github.com/tivac/modular-css/releases/tag/v22.1.4 with a token that only had `repo:public_repo` scope, so 🎉!

Thanks for all the feedback & info in the thread everybody, this has been really helpful and saved me from a bunch of digging.

**Comment by mbulfair** [comment]
I am seeing errors with this
```133 verbose git [ 'config', '--get', 'remote.upstream.url' ]
134 error HttpError: Not Found
```
I have an upstream set, but it's via SSH, is SSH just not supported?

**Comment by evocateur** [comment]
I think I may have found the bug, at least when publishing independently: https://github.com/lerna/lerna/compare/master...evocateur:fix-github-release-tag-search

Just needs a test to validate.

@mbulfair Not sure if this is related to your error, SSH is definitely supported (Lerna itself uses it with `--github-release`).

**Comment by kisenka** [comment]
@evocateur are you planning to make a PR with this fix? :)

**Comment by mbulfair** [comment]
@evocateur not sure if it is, but I get the same error for doing releases, all other operations I use for `lerna version` work, tagging and pushing to my `upstream` branch. I am also using github enterprise, and have all the tokens, api, and version set, just no matter what I got that httpError not found.

**Comment by milesj** [comment]
@mbulfair Where is it failing? Do you have a firewall or VPN or something that is blocking it?

**Comment by tivac** [comment]
@milesj here's the error I've gotten both times I tried to publish tonight:

```
lerna info github Creating GitHub releases...
lerna ERR! HttpError: Not Found
lerna ERR!     at response.text.then.message (C:\Users\tivac\Documents\GitHub\modular-css\node_modules\@octokit\request\lib\request.js:56:27)
lerna ERR! HttpError: Not Found
lerna ERR!     at response.text.then.message (C:\Users\tivac\Documents\GitHub\modular-css\node_modules\@octokit\request\lib\request.js:56:27)
lerna ERR! lerna Not Found
{ Deprecation: [@octokit/request] `error.code` is deprecated, use `error.status`.
    at HttpError.get (C:\Users\tivac\Documents\GitHub\modular-css\node_modules\@octokit\request\lib\http-error.js:18:17)
    at Array.globalOptions.usage.demandCommand.recommendCommands.strict.fail (C:\Users\tivac\Documents\GitHub\modular-css\node_modules\@lerna\cli\index.js:40:23)
    at Object.fail (C:\Users\tivac\Documents\GitHub\modular-css\node_modules\yargs\lib\usage.js:40:17)
    at handlerResult.then (C:\Users\tivac\Documents\GitHub\modular-css\node_modules\yargs\lib\command.js:242:47)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'Deprecation' }
```

**Comment by mbulfair** [comment]
> @mbulfair Where is it failing? Do you have a firewall or VPN or something that is blocking it?

The same spot this issue is mentioning, HttpError, it can't find the branch under upstream, like I said I use SSH and all other lerna and git operations work fine, I am behind a corporate firewall, and use github  enterprise.

**Comment by milesj** [comment]
@mbulfair Have you set the github enterprise env vars?

@tivac The problems seem to be originating from octokit. Perhaps dig around there on why this error is being thrown?

**Comment by ReidBraswell** [comment]
@milesj when you set the GitHub Enterprise env vars, does `lerna version` automatically load those into the `process.env` if there is a `.env` file present in the root of the project directory (local development)?

**Comment by milesj** [comment]
@ReidBraswell I'm not super versed in Lerna internals, but I'm pretty sure it doesn't do that.

**Comment by ReidBraswell** [comment]
@milesj no worries! I ended up checking out @tivac's repo and noticed he was using [`env-cmd`](https://www.npmjs.com/package/env-cmd) and was able to pull that in and use it with `lerna version`. Worked like a charm!

I ended up writing a small script and borrowed the logic from the lerna [`github-client.js`](https://github.com/lerna/lerna/blob/master/utils/github-client/lib/github-client.js) file to test local auth on my machine to GHE.

Thanks again for the quick response and work on lerna! Love the tool!

**Comment by milesj** [comment]
@ReidBraswell Glad you got it working!

**Comment by mbulfair** [comment]
After upgrading Lerna to 3.16.4, I am still getting this error

```
lerna notice cli v3.16.4
lerna info versioning independent
lerna info execute Creating releases...
lerna info git Pushing tags...
lerna ERR! HttpError: Not Found
lerna ERR!     at response.text.then.message (/Users/XXXX/Projects/components-react/node_modules/@octokit/request/dist-node/index.js:66:23)
lerna ERR! lerna Not Found
{ Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (/Users/XXXX/Projects/components-react/node_modules/@octokit/request-error/dist-node/index.js:29:17)
    at Array.globalOptions.usage.demandCommand.recommendCommands.strict.fail (/Users/XXXX/Projects/components-react/node_modules/@lerna/cli/index.js:40:23)
    at Object.fail (/Users/XXXX/Projects/components-react/node_modules/yargs/lib/usage.js:40:17)
    at handlerResult.then (/Users/XXXX/Projects/components-react/node_modules/yargs/lib/command.js:242:47)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'Deprecation' }
npm ERR! code ELIFECYCLE
npm ERR! errno 148
npm ERR! components-react@0.0.0 release: `lerna version --conventional-commits --no-commit-hooks --git-remote upstream --create-release github`
npm ERR! Exit status 148
```

I am using the correct key, the correct API url, and the correct GHE_Version, in this case `2.16`

Anyone have suggestions on getting this to work correctly?

**Comment by milesj** [comment]
@mbulfair Does your token have the correct scope (`repo`)?

**Comment by mbulfair** [comment]
> @mbulfair Does your token have the correct scope (`repo`)?

Yes it does, I actually see it say it was used when I attempted to do this yesterday. So it's failing somewhere else.

**Comment by milesj** [comment]
Yeah, should of looked closer. It passes on creating releases then seems to fail on tags?

Shot in the dark, but do you already have an existing tag that may be conflicting?

**Comment by mbulfair** [comment]
@milesj I am running this with lerna version, not publish, it creates the tags in the same step

**Comment by milesj** [comment]
There's not enough info here to debug further. You're going to have to add console logs into the code manually and see what's happening.

Here's all the code for creating releases: https://github.com/lerna/lerna/blob/master/commands/version/lib/create-release.js

And where they get enqueued: https://github.com/lerna/lerna/blob/master/commands/version/index.js#L268

**Comment by mbulfair** [comment]
I tried the local `.env` and I still have this error from the learna-debug

```
234 verbose git [ 'config', '--get', 'remote.upstream.url' ]
235 silly createGitHubClient
236 error HttpError: Not Found
```

I run the command from my fork to upstream. Does that have something to do with this?
@milesj

**Comment by waitingsong** [comment]
Same problem.
```sh
node -v
v12.14.0

npm -v
6.13.4

lerna -v
3.20.2
```

run in git-bash:
```sh
export GH_TOKEN=6faxxxxxxxxxxx
lerna version  --conventional-commits --create-release github
// OR
lerna publish  --conventional-commits --create-release github
```

got:
```
lerna info execute Creating releases...
lerna info git Pushing tags...
lerna ERR! HttpError: Not Found
lerna ERR!     at E:\myproject\node_modules\@octokit\request\dist-node\index.js:67:23
lerna ERR!     at processTicksAndRejections (internal/process/task_queues.js:93:5)
lerna ERR! lerna Not Found
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (E:\myproject\node_modules\@octokit\request-error\dist-node\index.js:29:17)
    at Array.<anonymous> (E:\myproject\node_modules\@lerna\cli\index.js:40:23)
    at Object.fail (E:\myproject\node_modules\@lerna\cli\node_modules\yargs\lib\usage.js:41:17)
    at E:\myproject\node_modules\@lerna\cli\node_modules\yargs\lib\command.js:247:38
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'Deprecation'
}
```
- The version tag and commit has been pushed to github successfully.
- The token page `https://github.com/settings/tokens`  shows the token `Never used`

**Comment by mstrk** [comment]
Hey guys just bumped in this issue as well. I used a token from a bot account, my problem was that the repo had a rule to only allow a team to do stuff on it. Adding the bot account to the team fixed the issue.

Github API will not tell you when you do not have permissions to do operations instead it will return a 404 for privacy concerns. So make sure the token you are using is from an account that has the right permissions for what you're trying to do.

Hope it helps someone looking for this issue in the future.

**Comment by JamesHenry** [comment]
Hi Folks 👋

In light of its age, and in order to allow our small team to focus on what matters most to Lerna v6 users in late 2022, I'm going to close this one. If you have any requests that could enhance your usage of Lerna 6, then please do let us know by opening a new discussion (for a feature) or issue (for a bug report) with as much context as possible.

You can also check out our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

Many thanks 🙏
