### ISSUE TITLE
lerna list should respect --include-filtered-dependents

### ISSUE THREAD

**Issue by ibezkrovnyi** [lerna/lerna#1922]
For most my cases list of changed projects is needed. What I have tried:

### lerna changed
I understand why `lerna changed` doesn't respect and will never respect `--include-filtered-dependents`.
`lerna changed` always returns list of projects changed **+ list of dependent projects**

### lerna list --since
lerna list by itself [respects](https://github.com/lerna/lerna/tree/master/commands/list#options) `--include-filtered-dependents` filter option.

But it seems like if I pass `--since`, lerna list enables `--include-filtered-dependents` and I cannot disable that option.

## Expected Behavior

```
# only projects in scope should be listed
lerna list --scope={,some-project-A}

# only changed projects should be listed
lerna list --since

# projects in scope + dependent projects should be listed
lerna list --scope={,some-project-A} --include-filtered-dependents

# changed projects + dependent projects should be listed
lerna list --since --include-filtered-dependents
```

## Current Behavior

```
# GOOD - only projects in scope are listed
lerna list --scope={,some-project-A}

# BAD - changed projects + dependent projects are listed
lerna list --since

# GOOD - projects in scope + dependent projects are listed
lerna list --scope={,some-project-A} --include-filtered-dependents

# GOOD - changed projects + dependent projects are listed
lerna list --since --include-filtered-dependents
```

## Possible Solution
Remove the following 2 lines:
https://github.com/lerna/lerna/blob/45a05acf2d52a46f553fc1efadf9a32312aca82b/utils/collect-updates/collect-updates.js#L72-L73

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.10.6 |
| `npm --version`  | 6.5.0 |
| `node --version` | 8.11.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by ibezkrovnyi** [comment]
Currently, as temporary workaround we are using `patch-package` which just removes following 2 lines:
https://github.com/lerna/lerna/blob/45a05acf2d52a46f553fc1efadf9a32312aca82b/utils/collect-updates/collect-updates.js#L72-L73

And everything works fine. But obviously this is awful solution.

**Comment by evocateur** [comment]
`--since` was added long after `--include-filtered-dependents`, and there's not really any explicit guarantee that they work together in any specific way. `--include-filtered-dependents` and `--include-filtered-dependencies` were originally designed to work with `--scope` and `--ignore`, which they do quite ably.

`lerna ls --since` has identical output to `lerna changed` because it's basically the same code path (only a little more roundabout). The reason updates always include dependents is largely explained in #707, and that isn't going to change.
