### ISSUE TITLE
tag-version-prefix is not documented

### ISSUE THREAD

**Issue by kirill-konshin** [lerna/lerna#1924]
Argument `tag-version-prefix` is not documented except in `version` command's help: https://github.com/lerna/lerna/blob/f84a631402d37b67053f6c1196e6bdf1eccaae05/commands/version/command.js

But in fact it should be used twice in some cases like this one:

```bash
#locally
lerna version --tag-version-prefix=''
#on ci
lerna publish from-git --tag-version-prefix='' 
```

I suggest to add this to `lerna.json` config for consistency.

**Comment by evocateur** [comment]
Yes, we definitely should document that in https://github.com/lerna/lerna/blob/master/commands/version/README.md

**Comment by kirill-konshin** [comment]
Thanks, stale bot :) lol, I've pushed the PR for this.

Still, I suggest to introduce a `lerna.json` option for this in order to get rid of duplication.
