### ISSUE TITLE
troubled with the version when own package publish.

### ISSUE THREAD

**Issue by konojunya** [lerna/lerna#1925]
When cli is created, if you change the version of cli to depend on the version of package.json of that package, you will upgrade version of package.json when doing `lerna publish`, so when building The file of the deliverable to be created becomes the version before publish.

How is the best solution to this problem?

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "yarn",
  "packages": [
    "packages/*"
  ],
  "version": "0.0.3"
}
```
</p></details>

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.11.0 |
| `npm --version`  | 6.7.0 |
| `yarn --version` | 1.13.0 |
| `node --version` | v10.14.0 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14 |

**Comment by evocateur** [comment]
Sorry, I'm unclear what the problem is. Could you demonstrate it in a simple example, perhaps?
