### ISSUE TITLE
How can I make `lerna changed` recognize uncommitted changes?

### ISSUE THREAD

**Issue by wbern** [lerna/lerna#1926]
## Expected Behavior

`npx lerna changed` to output packages that have been modified but not committed.

## Current Behavior

`npx lerna changed` only outputs packages that have changed according to commits made.

## Possible Solution

Add a parameter `npx lerna changed --include-uncommitted`.

## Steps to Reproduce (for bugs)

1. Have a package, commit all changes
2. `npx lerna version prerelease`
3. Modify the package
4. `npx lerna changed`

<details><summary>lerna.json</summary><p>

```json
{
    "version": "independent",
    "packages": [
      "micro-apps/*/*",
    ],
    "command": {
      "publish": {
        "ignoreChanges": [
          "ignored-file",
          "*.md"
        ],
        "independent": true
      },
      "bootstrap": {
        "npmClientArgs": ["--no-package-lock"] 
      }
    },
    "useWorkspaces": false
  }
```
</p></details>

## Context
We'd like to only compile packages that have changed since last publish. Packages that are 1:1 with the published release should have their tar.gz contents downloaded from the npm registry.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.11.0 |
| `npm --version`  | 5.6.0 |
| `node --version` | 8.11.4 |

| OS | Version |
| --- | --- |
| Ubuntu | 18.04.1 LTS |

**Comment by evocateur** [comment]
`git diff`? Lerna is not a general replacement for everyday `git` commands.

`lerna version` doesn't allow uncommitted changes, so `lerna changed` doesn't really have any need to recognize unversioned changes.

**Comment by wbern** [comment]
I still have to figure out which package has the change, which git diff only gives me paths to figure out.

**Comment by evocateur** [comment]
Surely your package directory names aren't _that_ obfuscated or divergent from the package names?

**Comment by wbern** [comment]
Closing, I'll have to figure this out soon.
