### ISSUE TITLE
How to publish the same packages to multiple npm registries?

### ISSUE THREAD

**Issue by abulyshkin** [lerna/lerna#1928]
Is there any way to publish all packages to multiple npm-registries? Maybe run lerna publish with any flag that will check all packages that were published last time and publish it to another npm-registry?

**Comment by evocateur** [comment]
With a reasonably up-to-date lerna, you can run `lerna publish` as many times as you have registries:

```sh
# create tags and push commits
$ npx lerna version

# publish tagged packages to the default registry
$ npx lerna publish from-git --yes

# then for each additional registry...
$ npx lerna publish from-package --yes --registry ${MY_AWESOME_REGISTRY}
$ npx lerna publish from-package --yes --registry ${MY_TUBULAR_REGISTRY}
# et cetera
```

The `--yes` flag skips repetitive prompts (decisions you've already made in `lerna version`, basically).

**Comment by vvscode** [comment]
After this I have ```error https://npm.xxx/@tamm%2fui-lib-styles/-/ui-lib-styles-0.2.3.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"```

what can I check?

**Comment by vvscode** [comment]
But everything is extracting manually

**Comment by evocateur** [comment]
That sounds like a third-party registry problem, possibly coupled with an obscure npm bug? `Extracting tar content of undefined failed` isn't a message that Lerna generates itself. You'd need to locate the actual tarball in the designated registry (`npm v $pkg dist.tarball`) and curl it down manually to check it.

**Comment by vvscode** [comment]
@abulyshkin  suppose we can close this one
