### ISSUE TITLE
Change default concurrency from 4 to available number of cpus

### ISSUE THREAD

**Issue by bdwain** [lerna/lerna#1929]
## Expected Behavior
It would be nice if concurrency defaulted to `os.cpus()`

## Current Behavior
Concurrency defaults to 4 no matter what.

## Possible Solution
Change the DEFAULT_CONCURRENCY variable to be `os.cpus()`.
Alternatively, enable this only with a flag to avoid a breaking change.

## Context
This would allow jobs to scale easily with different instance sizes when running in things like EC2. I have some tasks that run sometimes in a 4 core machine and sometimes in a 16 core machine or even larger.

Most local machines have 4 cores anyway, so they would remain unchanged. But it's hard to maximize concurrency using only the CLI right now.

```json
"run-stuff": "lerna run task --concurrency 8"
```

If I have a package.json task like above, it's hard to access the number of available CPUS to set the concurrency level. I need to instead run the lerna task from a node script, which is less convenient. Ideally, it would always maximize concurrency without needing to avoid the CLI. Or at least have that be available with a flag, like `--maximize-concurrency`. 

If this is something you'll consider, I'm happy to do a PR to add it.

**Comment by evocateur** [comment]
Sounds good to me, looks like #1931 beat you to it. :)

**Comment by evocateur** [comment]
(To be clear, I don't think we need a `--maximize-concurrency` flag, let's just change the default)

**Comment by bdwain** [comment]
Sweet! Thanks!

**Comment by andrewkincaid** [comment]
Is there a way to default the concurrency in `lerna.json`?  A few people on our team have noticed that when we run any `lerna` command, since it take all available CPUs, our laptops slow way down and our IDEs (IntelliJ IDEA) tend to lock up.  I don't mind hardcoding something like `"concurrency": 4,`, but I'm not sure that's an available option?  Thank you!

**Comment by andrewkincaid** [comment]
My apologies!  Setting `concurrency` in `lerna.json` works.

**Comment by nikshevchenko** [comment]
@worc 
I think that `concurrency` is valid. You can find some information on this page (https://github.com/lerna/lerna/tree/master/core/global-options#--concurrency)
