### ISSUE TITLE
Greenkeeper

### ISSUE THREAD

**Issue by ianwremmel** [lerna/lerna#193]
I'm not really sure where to ask this question, but I figure you folks are more likely to have considered it than Greenkeeper at this point. Is there any way to wireup greenkeeper with a monorepo layout?

**Comment by hzoo** [comment]
Right now there isn't - @nolanlawson was investigating this with pouchdb and lerna and would be probably better as a greenkeeper issue.

**Comment by ianwremmel** [comment]
Gotcha, thanks for the quick response! I found [his issue](https://github.com/greenkeeperio/greenkeeper/issues/139) on greenkeeper for anyone else with similar concerns.
