### ISSUE TITLE
"core" folder missing on NPM registry (not a Lerna issue)

### ISSUE THREAD

**Issue by TheOptimisticFactory** [lerna/lerna#1932]
**DISCLAIMER**: this is not a bug from Lerna but an issue arising from one of its dependency => [npm-packlist](https://github.com/npm/npm-packlist)

## Expected Behavior
- A few days ago, publishing a project containing any folder named `core` would lead to all non-blacklisted files to be included in the tarball sent onto NPM registry

## Current Behavior
- Since release of [npm-packlist v1.3.0](https://github.com/npm/npm-packlist) which included the changes introduced by the [pull-request n°8](https://github.com/npm/npm-packlist/pull/8#discussion_r171022093), any folder named `core` has suddenly become blacklisted by default without notice
- (This is where npm-packlist is declared: https://github.com/lerna/lerna/blame/master/utils/pack-directory/package.json#L33)

## Possible Solution
- The current workaround is to set either `!core` or `!/path/to/core` in `.npmignore` at the root of your Lerna package to explicitly whitelist the now blacklisted folder back.
- Currently, there is no option to toggle this behavior on [npm-packlist](https://github.com/npm/npm-packlist) so I have opened the following ticket: https://github.com/npm/npm-packlist/issues/24

## Steps to Reproduce (for bugs)
1. Have a project containing a folder named `core` anywhere in the tree with a file "path/to/core/index.js"
2. Using Lerna 3.0, `path/to/core` and any of its content will be included in the tarball on publish
3. Using the latest Lerna revision, `path/to/core` and any of its content will be missing from the tarball on publish

**Comment by evocateur** [comment]
Yikes, that's a nasty surprise. Thanks for the heads up and opening the issue upstream!

**Comment by evocateur** [comment]
(I'll leave this open until we get some resolution on npm/npm-packlist#24)

**Comment by TheOptimisticFactory** [comment]
The upstream issue has been resolved with: https://github.com/npm/npm-packlist/commit/9230bb88bfafac94e828cdc5cf3cb29a0248f85f

-- It was also impacting [NPM v6.8.0](https://npm.community/t/npm-pack-leaving-out-files-6-8-0-only/5382)

This fix got released in [`npm/npm-packlist v1.4.0`](https://github.com/npm/npm-packlist/commits/master) and onward 🎉

**Comment by Jeach** [comment]
Had the same issue with NPM v6.8.0 ... but fortunately, I knew I had a version I could update to, so when I updated (ie: 'sudo npm install -g npm'), it installed v6.9.0 and the problem seems to have been resolved. It now includes my 'core' sub-directory.

**Comment by evocateur** [comment]
Update to lerna v3.13.1 and you will no longer encounter this problem when running `lerna publish`
