### ISSUE TITLE
`lerna publish from-package` fails in AWS CodeBuild

### ISSUE THREAD

**Issue by samlecuyer** [lerna/lerna#1933]
AWS CodePipeline does not provide the `.git` directory or `git` executable to CodeBuild jobs, even when sourcing the code from a CodeCommit repository. The step to add `gitHead` to each package fails and cannot publish due to the error.

## Expected Behavior
lerna should be able to publish in a non-git environment using `from-package`

## Current Behavior
```
> lerna publish from-package --no-git-reset
 lerna notice cli v3.11.1
lerna ERR! ENOGIT The git binary was not found, or this is not a git repository.
```

## Possible Solution
Maybe make the `gitHead` step optional or fail silently in non-git environments.

## Steps to Reproduce (for bugs)

1. Create a monorepo with at least one package
2. Remove `git` from your path and `.git`, if any exist
3.  `lerna publish from-package`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.1.0"
}
```
</p></details>

## Context
I'm investigating using a monorepo with our existing infrastructure, which is AWS. We cannot use lerna with AWS Developer Tools unless it can publish gitless. I do not expect `version` to work without git (that should be done by people on their dev machines), but `publish` should.

## Your Environment
Running in AWS CodeBuild, Ubuntu, Node.JS 10.14.1.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | v3.11.1 |
| `npm --version`  | 6.7.0 |
| `yarn --version` | VERSION |
| `node --version` | 10.14.1 |

**Comment by samlecuyer** [comment]
Digging into the [CodeBuild docs](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html), it looks like there's a `CODEBUILD_SOURCE_VERSION` env var that's passed to the build job. A possible solution to this might also be to allow a hash to be passed so that the publish step doesn't need git.

`lerna publish from-package --with-git-head 44d86a1...`

**Comment by evocateur** [comment]
Yep, that certainly makes sense. A similar approach to #1908 is what I'm thinking (noodling locally right now). There are a couple more places we need to be aware of "do i need git", but it's actually not bad.

I think a (simplified) `--git-head` option would be a nice DX improvement, to preserve the gitHead metadata available from the registry.

**Comment by evocateur** [comment]
@samlecuyer How does [this](https://github.com/lerna/lerna/compare/master...evocateur:gitless-from-package?expand=1) look?

**Comment by samlecuyer** [comment]
@evocateur this is amazing, thank you for being so responsive! API-wise, it looks good to me
