### ISSUE TITLE
lerna publish with prepublishOnly executes in leaf 

### ISSUE THREAD

**Issue by veeramarni** [lerna/lerna#1935]
When running `lerna publish`, it fails at `prepublishOnly` script as it runs on the leaf only instead from root.
## Expected Behavior

`lerna publish` should run `prepublishOnly` script from root similar to `lerna exec --scope <component> npm publish`
## Current Behavior

It fails at `prepublishOnly` script as it requires some binaries linking and we use `lerna bootstrap --nohoist` which doesn't creates any `.bin` files like in `lerna@2version`.

And hence it fails

package.json
--
```
  "scripts": {
    "prepublishOnly": "npm run build",
    "build": "npm run build:clean && npm run build:lib",
    "build:clean": "rimraf lib",
    "build:lib": "webpack"
}
```

Error
--
```
> rimraf lib

sh: rimraf: command not found
```

The `rmraf` exist in the root `node_modules` but not in the leaf.

cmd (here `lerna` is an external command)
---
```
lerna publish 
```

but following run as expected when running through the script

```
 lerna publish --cd-version=prerelease --force-publish=* --no-verify-access
```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.0 |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
I'm a little confused by exactly when and where you expect the `prepublishOnly` lifecycle script to be executed. I can assure you that it _is_ executed, **when present**, [in a leaf node as well as the root](https://github.com/lerna/lerna/blob/9a47201f3fdd1df09cfb1922f26329d1dc4c8cc5/commands/publish/__tests__/publish-lifecycle-scripts.test.js#L30-L62) (after all leaves).

If your leaf nodes don't express a dev dependency on `rimraf`, `lerna bootstrap` won't link it into the leaf node's `node_modules`.

**Comment by veeramarni** [comment]
I mean my issue was, the lerna doing differently when we run `lerna` command externally.
For example:

package.json
--
  "scripts": {
    "prepublish": "lerna version --conventional-commits && lerna publish from-package --conventional-commits",
}

Which runs publish script in all the packages as expected and we don't get any errors like I got above.


But when we ran through the external command like (here `lerna` was from global  npm package)

`lerna version --conventional-commits && lerna publish from-package --conventional-commits`

It fails with the following error.

```

**Comment by bennypowers** [comment]
This was confusing for me, since the advice given elsewhere is to specifically *not* add devDependencies to packages.

In my case, they are needed for each package's `prepare` step - so installation works fine, but publishing breaks.

**Comment by riker09** [comment]
I had the same issue. The solution is to to use the npm script instead of lerna.

**Bad**: `lerna publish --from-package`
**Good**: `npm run publish`

My root `package.json` looks like this:

```json
{
  "name": "root",
  "private": true,
  "scripts": {
    "bootstrap": "lerna bootstrap --hoist",
    "clean": "lerna run clean",
    "build": "lerna run build",
    "pub": "lerna publish",
    "publish": "lerna version --conventional-commits && lerna publish from-package --conventional-commits"
  }
}
```

**Comment by evocateur** [comment]
Don't use a global installation of `lerna`, only use a local install in the root `devDependencies`. `npx lerna` if you must run the commands outside of npm scripts.
