### ISSUE TITLE
Allow packages to define their own independent npm tags

### ISSUE THREAD

**Issue by villesau** [lerna/lerna#1936]
## Expected Behaviour

Being able to manage NPM tags on per-package basis independently using Lerna.

#### Background

[flow-typed](https://github.com/flow-typed/flow-typed) is a central repository for [Flow](https://github.com/facebook/flow) library definitions, a bit similar to Definitely-typed.

We maintain hundreds or thousands of library definitions (depending how you count them) that we should like to publish in NPM.

For this task we would like to use Lerna. The problem is that one version of library (libdef) might match _multiple versions of flow_, and each of them should be accessible separately form NPM. We'd like to have folders structure something like this:

```
  ├── alasql
  │   └── alasql_v0.3.x
  │       └── flow_v0.25.x-
  │           └── index.js
     │       └── package.json
  ...
  └── lodash
     ├── lodash_v3.x.x
     │   └── flow_v0.28.x-
     │       └── index.js
     │       └── package.json
     ├── lodash_v4.x.x
     │   └── flow_v0.28.x-v0.37.x
     │       └── index.js
     │       └── package.json
     │   └── flow_v0.38.x-v0.46.x
     │       └── index.js
     │       └── package.json
     │   └── flow_v0.63.x-
     │       └── index.js
     │       └── package.json
```

where each index.js would be published to NPM separately. But e.g in case of lodash, it has two versions (3.x.x and 4.x.x), and multiple _flow_ version ranges under each version. We'd like to have different Flow versions as tags, and the Lodash version as an actual version. 

Here is an example of DefinitelyTyped library definitions utilizing tags: https://www.npmjs.com/package/@types/uuid <- see versions tab.

## Current Behaviour

As far as I know it's not currently possible to manage independent NPM tags in scale using Lerna.

## Possible Solution

If each packages package.json could define their own metadata (e.g `tag` field) to instruct Lerna how to manage versions and tags, that would be very helpful.

More discussion in flow-typed repository: https://github.com/flow-typed/flow-typed/issues/3083

**Comment by evocateur** [comment]
Literally what [`pkg.publishConfig`](https://docs.npmjs.com/files/package.json.html#publishconfig) is for (and not specific to Lerna at all). [`access`](https://docs.npmjs.com/misc/config#access), [`registry`](https://docs.npmjs.com/misc/config#registry), and [`tag`](https://docs.npmjs.com/misc/config#tag) are the relevant fields configurable under `publishConfig`.

**Comment by villesau** [comment]
This is indeed exactly what we're looking for! Didn't think that NPM would has builtin support for such features. Thanks a lot!
