### ISSUE TITLE
Scope commands based on package sets

### ISSUE THREAD

**Issue by ggascoigne** [lerna/lerna#1937]
## Expected Behavior
I'd like to find a simple pattern to run one set of commands on javascript based packages, and a separate set of commands on all typescript based projects.  One way I'd thought about this was by naming the package folders with a trailing -js or -ts, then use something like directory scoping  based on *-js or *.ts.  

Alternatively, in the lerna.json, create a mapping to sets of packages that can then be referenced by the commands.

e.g.

```json
{
  "packageSets": {
    "ts": ["foo1", "foo2"],
    "js": ["foo3"],
    "xx": ["foo1", "foo3"]
  }
}
```

I don't mind listing this out explicitly once, I just don't want to have to maintain it across multiple commands.

## Current Behavior

The only thing I've come up with so far is naming the packages explicitly to include this meta data, and that seems needlessly messy.

**Comment by evocateur** [comment]
I would suggest not conflating the two contexts at all and keep the JS and TS packages in separate monorepos.

**Comment by ggascoigne** [comment]
Well that would work, but it sort of defeats the point of my using a monorepo for this project.  Sadly, that might still be the most workable solution.

**Comment by 0gust1** [comment]
We have a somewhat similar need.
Our lerna mono-repo holds a design system, with components and design tokens.

Components are built in one way (using rollup and a common config), Design tokens are built in an other way.

I wished that `--scope` and `--ignore` flags could use the `packages` array  of `lerna.json` to restrict commands to parts of the monorepo package list

Our current `packages` field :
```
"packages": [
      "components/*",
      "design-tokens/**",
      "examples/**"
    ] 
```

**Comment by evocateur** [comment]
This isn't happening, sorry.
