### ISSUE TITLE
[Q] How to disable publish tarball file?

### ISSUE THREAD

**Issue by imcuttle** [lerna/lerna#1940]
I used npm@6 and lerna@^3.13.0 for publishing my package in customized npm registry. but it throw the error.

```
ZlibError: zlib: Cannot read property 'length' of null
    at Gzip.Zlib.(anonymous function) (/Users/yucong02/baidu/erp-fe/edam-vendor/node_modules/minizlib/index.js:126:21)
    at Gzip.write (/Users/yucong02/baidu/erp-fe/edam-vendor/node_modules/minizlib/index.js:247:21)
    at Object.source.on.chunk (/Users/yucong02/baidu/erp-fe/edam-vendor/node_modules/@lerna/pack-directory/node_modules/tar/lib/pack.js:340:18)
    at Object.emit (events.js:159:13)
    at Object.emit (/Users/yucong02/baidu/erp-fe/edam-vendor/node_modules/minipass/index.js:307:25)
```

However it's successful with npm@<6.

## Possible Solution
I guess the reason is that the customized registry does not support tarball file to publish. so How to disable publish tarball file?

<details><summary>lerna.json</summary><p>

```json
{
    "packages": ["packages/*"],
    "version": "independent",
    "command": {
        "publish": {
            "skipGit": true,
            "registry": "http://registry.npm.baidu-int.com",
            "conventionalCommits": true,
            "changelogPreset": "befe",
            "message": "chore(release): publish %s"
        },
        "bootstrap": {
            "hoist": ["jest", "edam"],
            "npmClientArgs": []
        }
    },
    "ignoreChanges": ["**/__fixtures__/**", "**/__tests__/**"]
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv { _: [ 'add' ],
0 silly argv   dev: true,
0 silly argv   D: true,
0 silly argv   scope: '**',
0 silly argv   globs: [],
0 silly argv   lernaVersion: '3.11.1',
0 silly argv   '$0': 'lerna',
0 silly argv   pkg: 'npm@5' }
1 notice cli v3.11.1
2 verbose rootPath /Users/yucong02/baidu/erp-fe/edam-vendor
3 info versioning independent
4 error ZlibError: zlib: Cannot read property 'length' of null
4 error     at Unzip.Zlib.(anonymous function) (/Users/yucong02/baidu/erp-fe/edam-vendor/node_modules/minizlib/index.js:126:21)
4 error     at Unzip.write (/Users/yucong02/baidu/erp-fe/edam-vendor/node_modules/minizlib/index.js:247:21)
4 error     at Unzip.flush (/Users/yucong02/baidu/erp-fe/edam-vendor/node_modules/minizlib/index.js:206:10)
4 error     at Unzip.end (/Users/yucong02/baidu/erp-fe/edam-vendor/node_modules/minizlib/index.js:213:10)
4 error     at Object.end (/Users/yucong02/baidu/erp-fe/edam-vendor/node_modules/pacote/node_modules/tar/lib/parse.js:416:21)
4 error     at PassThrough.onend (_stream_readable.js:598:10)
4 error     at Object.onceWrapper (events.js:254:19)
4 error     at PassThrough.emit (events.js:164:20)
4 error     at endReadableNT (_stream_readable.js:1054:12)
4 error     at _combinedTickCallback (internal/process/next_tick.js:138:11)
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.0 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.9.4 |
| `node --version` | 9.2.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
The debug file you posted is the output of `lerna add npm@5`, not `lerna publish`. What exactly are you trying to achieve? Can you attach a complete debug log from a failed `lerna publish` instead?

The code Lerna uses to publish packages to a registry is literally the same code (http://npm.im/libnpmpublish, etc) that npm@>=6.6.0 ([changelog](https://github.com/npm/cli/blob/latest/CHANGELOG.md#v660-2019-01-17)) uses to publish packages, which was itself extracted from npm.

This looks like it is an issue with the [tar](http://npm.im/tar) library, possibly dealing with incompatible transitive dependency versions?

**Comment by jbockle** [comment]
I was having this same issue with lerna@3.13.1, and by using `--loglevel verbose` I was able to determine it was coming from only specific packages during '@lerna/pack-directory'.  Seems like its an issue with the latest npm packlist not playing nice with package.json's files propery.  Haven't looked at it deeper yet, but I had `"files":["dist"]` in a few of the packages.  Removing the files key as a temporary workaround.

**Comment by soederpop** [comment]
In my CI environment, I'm getting a lot of errors during the npm pack stage inside the lerna publish command.  It happens randomly, and it happens in different packages each time, but the error comes from tar and the minizlib library.  

In this same environment, single threading the npm publish commands for each package in lerna updated, using the actual npm publish command never runs into this issue.

the issue happens inside tar / minizlib, but it only started happening in recent versions of lerna.

i know this isn't helpful but this has been a really hard thing for me to trace down.

**Comment by jbockle** [comment]
@soederpop any of your packages' package.json have `files`? if so try removing it, as this may be a problem with **npm-packlist** dependency that was upgraded with **@lerna/pack-directory**, if so this issue should be opened on **npm-packlist**'s repo

**Comment by soederpop** [comment]
I was really hopeful when I saw that comment in case somebody might have put that in there but no, they don't 😦

**Comment by iamdriz** [comment]
Is there any resolution to this? We're also having this issue when using Lerna with Verdaccio and it basically blocking our publish mechanism...

**Comment by JamesHenry** [comment]
Hi Folks, it looks like this one was resolved, so closing
