### ISSUE TITLE
Yarn audit showing handlerbar vulnerability

### ISSUE THREAD

**Issue by nahumzs** [lerna/lerna#1941]
When running `yarn audit` the console shows multiple vulnerabilities by handlebars, which is being used by `conventional-changelog-core` and `conventional-changelog-writer` I wonder if this should be addressed directly from those packages or Lerna can do something about it.

## Expected Behavior
Shouldn't display any audit error related to lerna package. 

## Possible Solution
Upgrade handlebar on `conventional-changelog-core` and `conventional-changelog-writer`  and then upgrade the dependencies of those packages in lerna. 

## Steps to Reproduce (for bugs)
Run `yarn audit`using lerna

<img width="570" alt="screen shot 2019-02-19 at 11 47 04 am" src="https://user-images.githubusercontent.com/19418590/53043176-c89e2400-343c-11e9-964a-6bccfc232411.png">

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "ignoreChanges": ["ignored-file", "*.md"]
    }
  },
  "version": "independent"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | ^3.0.5 |
| `npm --version`  | - |
| `yarn --version` | 1.13.0 |
| `node --version` | v10 |

| OS | Version |
| --- | --- |
| macOS | VERSION |

**Comment by hutson** [comment]
@nahumzs the `handlebars` dependency was [upgraded in the `conventional-changelog` packages several days ago](https://github.com/conventional-changelog/conventional-changelog/commit/1041d815d69aef13180df39b501ab00047e3a553).

It looks like @evocateur then upgraded the minimum version of `conventional-changelog-core` in [Lerna version `v3.13.0`](https://github.com/lerna/lerna/commit/d632d1bacccd2df30ab04ddea84c3952689479de#diff-d20459c83aa975af1e7cdda6a1ccd765).

Can you please update your version of Lerna and re-test? (Also, can you please add the results of `lerna --version` to the table under _Your Environment_?)

**Comment by nahumzs** [comment]
you are correct, upgraded to `v3.13.0` and everything is 💯 now! thank you.

**Comment by melissafzhang** [comment]
I'm still getting this same vulnerability and I'm on 3.14.0

**Comment by evocateur** [comment]
It's a transitive dev dependency that only ever gets called when generating changelogs during `lerna version`. It's basically the most worthless security "warning" ever.
