### ISSUE TITLE
[Feature Request] Support Gitlab Releases

### ISSUE THREAD

**Issue by wldcordeiro** [lerna/lerna#1943]
I had noticed when publishing recently that the `github releases` step is skipped, and Gitlab has recently added support for a similar API. It'd be very useful to be able to have it work with Gitlab too.

**Comment by evocateur** [comment]
Yep, sounds like a great opportunity for a PR!

**Comment by JamesHenry** [comment]
Closing as gitlab releases have been supported for a number of years AFAIK
