### ISSUE TITLE
[Feature Request] lerna add <package> --peer

### ISSUE THREAD

**Issue by Jahans3** [lerna/lerna#1947]
Add peer dependencies with `lerna add` by using a command similar to yarn's `--peer`

**Comment by LucasRuy** [comment]
+1

**Comment by unadlib** [comment]
+1

**Comment by paschaldev** [comment]
+1

**Comment by evocateur** [comment]
Basic issue etiquette: Don't post comments like "+1". Use the emoji responses to the OP if that's all you have to contribute to the thread.

**Comment by evocateur** [comment]
Closed by #2334
