### ISSUE TITLE
Command to clear out node_modules directories

### ISSUE THREAD

**Issue by thejameskyle** [lerna/lerna#195]
Something like `lerna clean` that just does `rm -rf packages/*/node_modules`

I find myself doing that every now and then because of npm sucking somehow.

**Comment by gigabo** [comment]
Heh, we've got [this](https://github.com/redfin/react-server/blob/master/package.json#L7) in our `package.json`:

```bash
$ grep nuke package.json
    "nuke": "rm -r node_modules; for d in packages/*/node_modules; do echo $d; rm -r $d; done"
```

Mind if I take this?

**Comment by thejameskyle** [comment]
Oh man I would love a `lerna nuke` command

> Mind if I take this?

Yeah, go for it

**Comment by hzoo** [comment]
Yeah I had to do that in babel today (rm -rf packages/*/node_modules, rm -rf node_modules) since I didn't see that babylon update caused tests to fail

**Comment by maciej-gurban** [comment]
Is there a reason why `lerna clean` would not also remove root level `node_modules`?

**Comment by evocateur** [comment]
Your root `node_modules` contains lerna itself and many other devDependencies. `lerna clean` was not designed to be a general replacement for `rm`, only convenience for removing any `node_modules` directories under package locations.
