### ISSUE TITLE
[Question]Is there a way to push a git tag using lerna without bumping up any version? 

### ISSUE THREAD

**Issue by shridharkalagi** [lerna/lerna#1951]
Is there a way to push a git tag using lerna without bumping up any version/without pushing any commit? 

I want to run a command from my CI machine where it tags a particular commit with a static string like 'ReleasedToProd' post the deployment. 

There are multiple versions published in every sprint using lerna and one of the versions will be released at the end of sprint. How can I tag this version with a static string using the existing lerna setup?

**Comment by shridharkalagi** [comment]
This is as simple as 
`git tag ReleasedToProd`
`git push --tags`

**Comment by evocateur** [comment]
I don't understand why Lerna has anything to do with your desired CI git commands.
