### ISSUE TITLE
[Question] Use --canary for testing feature branches?

### ISSUE THREAD

**Issue by gmeans** [lerna/lerna#1952]
We are trying to work on deploying a shared package used on both Google Cloud Functions and Google App Engine. Both of these environments install your dependencies when you deploy, based on your package.json file.

We have a private npm registry set up, and we were hoping to use the `--canary` feature to help us test code prior to release on our dev and staging environments.

The issue is that when we run `publish --canary` it only looks for changes since the last commit. What we're looking for is for lerna to detect changes across all commits in the current branch so we can deploy canary releases for the "latest" version of what we have in the feature branch. 

Is there a workflow w/ lerna that would support this? What would be nice is if we could use the `--since` flag with the `--canary` flag or something similar.

**Comment by davidhouweling** [comment]
Have you tried `lerna publish --preid=alpha`? It does create git tags and pushes them to the branch you're on though. The behaviour described by OP was the behaviour in version 2 but was changed in version 3 (unsure as to why).

**Comment by gmeans** [comment]
Closing this as it was more a question than a specific request.
