### ISSUE TITLE
[feature request]run lerna script against staged-files

### ISSUE THREAD

**Issue by mortenko** [lerna/lerna#1955]
I would like to run lerna scripts against packages that have staged files. It similar to --since flag. I would recommend to add new filtered flag --staged (git diff --cached). 

## Expected Behavior
Run pre-commit git hook with husky using lint-staged package on packages that have staged files. 
The command should looks like: `lerna run pre-commit --staged` 

## Current Behavior
There is not such possibility yet

**Comment by nchandran3** [comment]
For the exact same use case, I was able to use `lerna run pre-commit --since HEAD`. 

This will only run the pre-commit script on packages that have staged changes within them.

**Comment by evocateur** [comment]
`--since HEAD` seems more than sufficient for this sort of thing.

**Comment by rfgamaral** [comment]
The proposed `--since HEAD` solution will run the command on every package with **changed** files not **staged** ones. Could this be reopened and the feature request reconsidered?

**Comment by evocateur** [comment]
[This solution](https://github.com/lerna/lerna/issues/1955#issuecomment-482248470) seems appropriate to me. If you're not using a pre-commit hook runner that properly stashes unstaged changes, you should probably use one that does. (or husky from the root, no need for lerna just to run pre-commit tests/linting)

**Comment by prajaktagharpure** [comment]
I am trying to implement this in my project and encountering the below error? 
package.json
` "husky": {
    "hooks": {
      "pre-commit": "lerna run test --concurrency 1 --stream --no-prefix"
    }
  }`

error
`git commit -m "TEST"
husky > pre-commit (node v10.15.3)
lerna notice cli v3.20.2
lerna ERR! ENOGIT The git binary was not found, or this is not a git repository.
husky > pre-commit hook failed (add --no-verify to bypass)`

**Comment by the-homeless-god** [comment]
```sh
    "test": "lerna run test --concurrency 1 --stream --no-prefix && echo",
```

Helps when `pre-commit` passed paths into lerna env
