### ISSUE TITLE
Question: How to execute a command only in packages that are modified?

### ISSUE THREAD

**Issue by savvyjindal** [lerna/lerna#1958]
I am trying to publish docker images for all the individual packages I have in my lerna repo.I have created command for doing the same.

I am looking for a solution where I can execute specific commands other than version and release which uses lerna changed for packages that are modified since last release.

It gets executed in all the packages irrespective of how many packages were modified since last release which ends up in creating the images for all the packages.

**Comment by poteirard** [comment]
Have you checked this: https://github.com/lerna/lerna/tree/master/core/filter-options#--since-ref ?

**Comment by evocateur** [comment]
```
npx lerna exec --since -- 'my awesome command'
```
