### ISSUE TITLE
Unchanged independent versions with lerna version

### ISSUE THREAD

**Issue by pshrmn** [lerna/lerna#1963]
There is no way to select that a package's version should remain unchanged when using the interactive CLI triggered by calling `lerna version`, so it would be nice to have an option for this.

I can open a PR to make the change if it is acceptable, but I wanted to get feedback first.

## Expected Behavior

In a project that uses independent versions, the interactive CLI triggered by `lerna version` should have an "unchanged" option for packages whose version is not changed.

## Current Behavior

In order to replicate the desired behavior, my current workaround is to select the `Custom Version` option and manually enter the current version.

## Possible Solution

Add an `Unchanged` option to the interactive version prompt.

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "packages": [
    "packages/*"
  ]
}

```
</p></details>

## Context

This would just be a quality of life tweak. I publish infrequently enough that it isn't terrible to type the unchanged versions out when I do make a release, but it can be annoying.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.7.0 |
| `node --version` | 11.10.1 |

**Comment by evocateur** [comment]
You're attempting a back-door `--ignore` for `lerna publish`, which will _never_ happen. #707 etc etc etc
