### ISSUE TITLE
use conventionalCommits makes `learn version` can not select version

### ISSUE THREAD

**Issue by catshub** [lerna/lerna#1967]
when the `conventionalCommits` is `true`, `lerna version` command can not select version

## Expected Behavior
![image](https://user-images.githubusercontent.com/25862498/54014241-f2827500-41b6-11e9-8c00-53cd00cd5877.png)

## Current Behavior
it makes choice itself
![image](https://user-images.githubusercontent.com/25862498/54014278-15ad2480-41b7-11e9-8b9a-aa2006839a81.png)

## Possible Solution

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "command": {
    "version": {
      "conventionalCommits": true
    }
  },
  "version": "independent"
}

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.0 |
| `npm --version`  | 6.8.0 |
| `yarn --version` | VERSION |
| `node --version` | 9.11.2 |

| OS | Version |
| --- | --- |
| macos mojave | 10.14.2 |

**Comment by yj7810520113** [comment]
Have you solved this problem？
