### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by NE-SmallTown** [lerna/lerna#1973]
Could we provide a hook to allow us do something **after** we `publish`?

I try `await execa('lerna', ['publish'])` but doesn't work

**Comment by tanhauhau** [comment]
have it in the `postpublish` script?

**Comment by NE-SmallTown** [comment]
I tried set it in 'postpublish'(e.x `"pospublish": "node ./foo.js"`)， but seems that when execute foo.js, the publish process haven't done, so if I do some remove operations in `foo.js`, the final files which be published to npm is incomplete because we do publishing while removing

**Comment by tanhauhau** [comment]
where did you add the `postpublish` script?
I not sure what you trying to do, but you can add a `postpublish` script at `<root>/package.json`. It will get executed after publishing all packages.

**Comment by NE-SmallTown** [comment]
Yea, I add it in '<root>/package.json' but can't work like I described above

**Comment by evocateur** [comment]
To execute a thing only after success, from the CLI, would look like this:
```
npx lerna publish && node ./foo.js
```

Or use a root `postpublish` lifecycle, as @tanhauhau pointed out. I can guarantee you it _is_ being called after all changed packages have been published to the registry.

**Comment by revelt** [comment]
From my experience, I had exactly the same challenges setting up Lerna to manage bunch of npm packages — how to manage publishing to npm, git commit the published files and ensure tags are pushed and don't cause further CI builds. If you need a reference, feel free to peek in my [GitLab CI script](https://gitlab.com/codsen/codsen/blob/master/.gitlab-ci.yml) (also some scripts are in package.json) — it publishes all changed npm packages to npm and git-commits everything in my name.

Having said the above, I found `lerna publish` does not give me enough control over the process, I ended up using `lerna version` only and then continuing from there on using non-lerna alternatives, git commands and native `npm` CLI. The main idea is, npm will not publish packages if they haven't been updated (version is the same). Yes, it means CI tries to publish all packages under Lerna each time but system does work (I need to somehow pipe `lerna changed` into `npm publish`). Conceptually, the workflow is just chained npm/CI scripts just like Dan says above.

---

@NE-SmallTown please update, are you happy to close this issue or do you need further help and if so, please provide arguments against proposed script chaining approach (via `&&` in package.json or script sequence in CI in .yml file or makefiles or similar).
