### ISSUE TITLE
./bin/ symlinks are numbers, not names

### ISSUE THREAD

**Issue by ericprud** [lerna/lerna#1974]
A node_modules/.bin/command1 link created for a `"bin": ["bin/command1"]` in a contained package.json is named `0` rather than `command1`.

## Expected Behavior
`node_modules/.bin/0 -> ../../../sibling-package/bin/command1` should be called `command1`

## Current Behavior
`npx lerna add sibling-package packages/test-package` creates symlinks like:
```
0 -> ../../../sibling-package/bin/command1
1 -> ../../../sibling-package/bin/otherCommand
...
```

## Possible Solution
Rummage around in the stack for the script name.

## Steps to Reproduce (for bugs)
See [precise steps in a lerna tutorial](https://github.com/ericprud/lerna-repo-tutorial/tree/testing#bin-names-are-numbers). In broad strokes here:
1.create a nested package with bin scripts.
2.`lerna add` link to that package in another subpackage.
3.`ls -l` the subpackage's `node_modules/.bin` directory

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

## Context
I'm trying to testing on bin scripts and contribute a tutorial to teach the world to do the same.

## Your Environment
generic Ubuntu 18.10

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.5.0-next.0 |
| `yarn --version` | N/A |
| `node --version` | v11.6.0 |

| OS | Version |
| --- | --- |
| Ubuntu | 18.10 |

**Comment by evocateur** [comment]
I'm not sure how you expect an illegally-formatted [`bin`](https://docs.npmjs.com/files/package.json.html#bin) field to work? It should be a string (if you only have one bin, named identically to your package) or an object.

**Comment by ericprud** [comment]
oops, my bad. I stole the bin idiom from from an apparently bad or old example.  I don't see evidence that this is a common problem but if someone has counter evidence, they could add something like this to `core/package/index.js`'s `Package` constructor:

``` javascript
if (pkg.bin.constructor === Array)
  pkg.bin = pkg.bin.reduce((acc, name) => {
    acc[name.substr(name.lastIndexOf("/") + 1)] = name;
    return acc;
  }, {}),
```
or just throw Error("package.json's bin attribute must be a string or map from command name to path").
