### ISSUE TITLE
lerna bootstrap --hoist doesn't symlink packages unless --force-local is provided

### ISSUE THREAD

**Issue by wbern** [lerna/lerna#1977]
As the title says, I have a monorepo with a lot of packages that specify dependencies to other packages in the same same repository, each dependency is listed with a "*", to accept any version and therefore should use the local version (symlink).

## Expected Behavior

* Have Package A and B.
* Specify dependency to Package C in A and B.
* do `lerna bootstrap --hoist`
* A symlinked directory of each dependency is created in the root of the project's node_modules

## Current Behavior

* Have Package A and B.
* Specify dependency to Package C in A and B.
* do `lerna bootstrap --hoist`
* A simple directory of each dependency is created in the root of the project's node_modules, but is not a symlink.

## Possible Solution

I can make it work with --force-local, but that will make us unable to "sticky" an older version of a package if we decide to do that.

<details><summary>lerna.json</summary><p>

```json
{
    "version": "independent",
    "packages": [
      "micro-apps/*/*",
      "libraries/*"
    ],
    "command": {
      "publish": {
        "ignoreChanges": [
          "ignored-file",
          "*.md"
        ],
        "independent": true
      },
      "bootstrap": {
        "npmClientArgs": ["--no-package-lock"] 
      }
    },
    "useWorkspaces": false
  }
```
</p></details>

## Context

I want to use `lerna bootstrap --hoist` and at the same time get symlinking (which seems to be advertised for lerna bootstrap?).

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.11.0 |
| `npm --version`  | 5.6.0 |
| `node --version` | 8.11.4 |

| OS | Version |
| --- | --- |
| Ubuntu | 18.04.1 LTS |

**Comment by evocateur** [comment]
The `*` specifier isn't actually recommended, and in any case, absolutely unnecessary for Lerna to recognize local siblings _as long as the range satisfies the local version_.
