### ISSUE TITLE
lerna publish --force-publish --canary triggering publish lifecycle on root package.json

### ISSUE THREAD

**Issue by elisiariocouto** [lerna/lerna#1978]
Hello. I have a 40-package monorepo. In the root `package.json`, I have a `lerna publish --conventional-commits --force-publish` that we run when we want to do a release.
In addition, we have a CI job that does `lerna publish --force-publish --canary` on every commit. This job fails because lerna is triggering the root `package.json` `publish` script.
Lerna states that it is going to publish 40 packages but, in addition, it runs publish also for the root package.

Is this intended?

## Expected Behavior
Publish 40 packages.

## Current Behavior
Publishes 40 packages and fails to publish the root package.

## Possible Solution
Option to ignore root package.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/lib/*",
    "packages/services/*"
  ],
  "version": "1.7.4"
}
```

</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.4.1 |
| `node --version` | v10.15.3 |

| OS | Version |
| --- | --- |
| Node Alpine Docker Image | node:10-alpine |

**Comment by tanhauhau** [comment]
In most cases you are not supposed to publish the root package, and should mark the `<root>/package.json` with `"private": true`.

During `lerna publish`, lerna will run lifecycle scripts `publish` and `postpublish` in the root package accordingly. This is intended. I think if you want to add a custom script in `package.json`, you should avoid using the [npm lifecycle scripts](https://docs.npmjs.com/misc/scripts#description) unless intended.

**Comment by elisiariocouto** [comment]
I have the root `package.json` as a private package. If I'm understanding correctly, `lerna publish` should had skipped the root package, right?

To workaround this, I renamed my custom `publish` script to `release`.

**Comment by tanhauhau** [comment]
lerna is not publishing the root package, just running the `publish`, `postpublish` lifecycle scripts in root package.

This allows you to have project wide lifecycle events when running `lerna publish`

**Comment by tanhauhau** [comment]
you can take a look at the [merge request when this is added](https://github.com/lerna/lerna/pull/1348)

**Comment by elisiariocouto** [comment]
Got it. Thanks for the clarification.
