### ISSUE TITLE
lerna create - Error: Command failed: git config --get user.name

### ISSUE THREAD

**Issue by flyfishMT** [lerna/lerna#1979]
Hello, On Windows 10, I am receiving an error trying to run lerna create -

```
C:\dir\test-monorepo>lerna create dummy
info cli using local version of lerna
lerna notice cli v3.13.1
lerna ERR! Error: Command failed: git config --get user.name
lerna ERR!
lerna ERR!
lerna ERR!     at makeError (C:\dir\test-monorepo\node_modules\execa\index.js:174:9)
lerna ERR!     at Function.module.exports.sync (C:\dir\test-monorepo\node_modules\execa\index.js:338:15)
lerna ERR!     at Object.execSync (C:\dir\test-monorepo\node_modules\@lerna\child-process\index.js:22:16)
lerna ERR!     at CreateCommand.gitConfig (C:\dir\test-monorepo\test-monorepo\node_modules\@lerna\create\index.js:181:34)
lerna ERR!     at CreateCommand.initialize (C:\dir\test-monorepo\test-monorepo\node_modules\@lerna\create\index.js:103:46)
lerna ERR!     at Promise.resolve.then (C:\dir\test-monorepo\test-monorepo\node_modules\@lerna\command\index.js:271:24)
lerna ERR! lerna Command failed: git config --get user.name
lerna ERR! lerna
lerna ERR! lerna
```
However, if I run the command, I do in fact have a user.name:

```
C:\dir\test-monorepo>git config --get user.name
flyfishMT
```

## Expected Behavior
I expected this command to create package "dummy"
This did work for me in the windows subystem for linux bash shell.

<details><summary>lerna.json</summary><p>

```json
{
  "name": "root",
  "private": true,
  "devDependencies": {
    "lerna": "^3.13.1"
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv { _: [ 'create' ],
0 silly argv   lernaVersion: '3.13.1',
0 silly argv   '$0':
0 silly argv    '..\\..\\..\\AppData\\Roaming\\npm\\node_modules\\lerna\\cli.js',
0 silly argv   name: 'dummy' }
1 notice cli v3.13.1
2 verbose rootPath C:\dir\test-monorepo
3 error Error: Command failed: git config --get user.name
3 error
3 error
3 error     at makeError (C:\dir\test-monorepo\node_modules\execa\index.js:174:9)
3 error     at Function.module.exports.sync (C:\dir\test-monorepo\node_modules\execa\index.js:338:15)
3 error     at Object.execSync (C:\dir\test-monorepo\node_modules\@lerna\child-process\index.js:22:16)
3 error     at CreateCommand.gitConfig (C:\dir\test-monorepo\node_modules\@lerna\create\index.js:181:34)
3 error     at CreateCommand.initialize (C:\dir\test-monorepo\node_modules\@lerna\create\index.js:103:46)
3 error     at Promise.resolve.then (C:\dir\test-monorepo\node_modules\@lerna\command\index.js:271:24)

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` |  3.13.1 |
| `npm --version`  | 6.4.1 |
| `node --version` | v10.15.1 |

| OS | Version |
| --- | --- |
| Windows 10 |  1803 |

**Comment by Hulago** [comment]
Set git user.name by executing

```bash
git config --global user.name "Your Name"
```

**Comment by gcharis** [comment]
@flyfishMT

Solved it by setting user.name and user.email locally to the project.

`git config user.name flyfishMT`
`git config user.email <your-email>`

If that doesn't work for you, you could tweak the internal packages of lerna. The internal implementation of lerna cli makes use of the execa package. The command you should look for is inside **_@lerna\child-process\index.js_**. Search for `execSync` and maybe use a try catch statement to get access to the full error.

That is if you still have the above error which I doubt.

**Comment by evocateur** [comment]
I would recommend using a POSIX shell, git on anything Windows has been garbage for eons. I don't have time to debug Windows' pitiful excuse for a (non-WSL) shell.

WSL sounds like it fits the bill.

**Comment by declspec** [comment]
For me this was happening because lerna clobbers your `process.env.HOME` environment variable:
https://github.com/lerna/lerna/blob/master/utils/npm-conf/lib/defaults.js#L26

On Windows `os.homedir()` does not respect the `HOME` environment variable so you end up with a mismatch between `os.homedir()` and `process.env.HOME`.

Most programs under Windows do respect the HOME directory (i.e. `git`, `ssh`, `vim`, `vscode`, etc.) but node does not for whatever reason. 

I would personally prefer the default to be:

```js
if (home)
    process.env.HOME = process.env.HOME || home;
...
```
