### ISSUE TITLE
Lerna fails on identical package names

### ISSUE THREAD

**Issue by villesau** [lerna/lerna#1980]
## Expected Behaviour

Being able to manage multiple packages with same name but different tag.

#### Background

[flow-typed](https://github.com/flow-typed/flow-typed) is a central repository for [Flow](https://github.com/facebook/flow) library definitions, a bit similar to Definitely-typed.

We maintain hundreds or thousands of library definitions (depending how you count them) that we should like to publish in NPM.

For this task we would like to use Lerna. The problem is that one version of library (libdef) might match _multiple versions of flow_, and each of them should be accessible separately form NPM. We'd like to have folders structure something like this:

```
  ├── alasql
  │   └── alasql_v0.3.x
  │       └── flow_v0.25.x-
  │           └── index.js
  │           └── package.json
  ...
  └── lodash
     ├── lodash_v4.x.x
     │   └── flow_v0.28.x-v0.37.x
     │       └── index.js
     │       └── package.json
     │   └── flow_v0.38.x-v0.46.x
     │       └── index.js
     │       └── package.json
     │   └── flow_v0.63.x-
     │       └── index.js
     │       └── package.json
```

where each index.js would be published to NPM separately. But e.g in case of lodash, it has one version (4.x.x), but multiple _flow_ version ranges under each version. We want to define flow version ranges in PublishConfig as tags, but to have the same version `4.0.0` in this case.

Here is an example of DefinitelyTyped library definitions utilizing tags: https://www.npmjs.com/package/@types/uuid <- see versions tab.

## Current Behaviour

Currently Lerna gives following error:

```
lerna ERR! ENAME Package name "@flow-typed/a11y-dialog" used in multiple packages:
lerna ERR! ENAME        /Users/path/to/code/experimental/definitions/a11y-dialog/a11y-dialog_v5.x.x/flow_v0.25.x-v0.67.1
lerna ERR! ENAME        /Users/path/to/code/experimental/definitions/a11y-dialog/a11y-dialog_v5.x.x/flow_v0.68.x-

```

## Possible Solution

A) provide `--ignore-version-check` flag or similar.
B) provide `ignoreVersionCheck` as an lerna.json option

More context in flow-typed repository: https://github.com/flow-typed/flow-typed/issues/3083

**Comment by goodmind** [comment]
@evocateur

**Comment by evocateur** [comment]
I don't see this happening in Lerna core. Far too many footguns for the general use case to outweigh the benefit for one convoluted project.

You might try resolving (with Yarn) a different fork of `@lerna/package-graph` (like Babel [does with `@lerna/collect-updates`](https://github.com/babel/babel/commit/d35f2ad92b322c3bb9c6792e2683807afae0b105#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R73)) that removes the [duplicate name check](https://github.com/lerna/lerna/blob/4e3f8d8087e0e2e8e83c7ea79558c517203583c2/core/package-graph/index.js#L82-L89). I can't speak to the success of the publish command once you do that, however.

**Comment by villesau** [comment]
Hi @evocateur ! Thanks for the tip, I'd be happy to try it out. Are there instructions on how to run & test Lerna locally? Looks like https://github.com/lerna/lerna/blob/master/CONTRIBUTING.md is either outdated or incomplete.

```
$ git clone git@github.com:lerna/lerna.git && cd lerna
$ npm i
$ npm test
```

above just results tons of errors.

**Comment by polkovnikov-ph** [comment]
I'm not sure about creating another issue, so I'll add 2 cents here. A run of `npm version` results in

```
lerna notice cli v4.0.0
lerna info versioning independent
lerna ERR! ENAME Package name "@scope/package-name" used in multiple packages:
lerna ERR! ENAME        C:\Users\user\Documents\proj\scope\packages\package-name
lerna ERR! ENAME        C:\Users\user\Documents\proj\scope\packages\package-name
```

Yes, with 2 identical package names. The package is depended upon by 2 other packages. I don't think version check works well here.

**Comment by rdzidziguri** [comment]
https://github.com/lerna/lerna/issues/1980

**Comment by JamesHenry** [comment]
Hi Folks 👋 

In light of its age, and based on the response of the previous maintainer, I am going to close this as duplicate packages names in the same workspace is not something we are looking to support.

Many thanks!
