### ISSUE TITLE
Temporarily un-convert local file specifiers

### ISSUE THREAD

**Issue by pshrmn** [lerna/lerna#1981]
I have a monorepo that has some example packages. In development, having file specifiers for their dependencies is fine. However, these example packages can also be run by users (e.g. with CodeSandbox), where the actual dependency versions are needed.

My current setup is that I have a `master` branch where the example dependencies are always "real". Development is done in a `dev` branch. When that gets merged onto `master`, I have a script to convert the file specifier dependencies to real dependencies (and then the dependencies are re-converted when `master` is rebased onto `dev`).

```bash
git checkout master
git merge dev
# run script to convert deps and make a commit
git checkout dev
git rebase master
npx lerna link convert
```

This works, but it would be nice if Lerna provided similar functionality. I know that `lerna publish` does something similar, but I'm not sure how easily that could be adapted.

## Expected Behavior

Lerna provides a command for setting "real" dependencies.

## Current Behavior

A custom script is required to set the dependency versions.

## Context

This would just be a quality of life change. I'm not sure how common my setup (examples that can be run online) is, so it is hard for me to say if other people would also find this useful. I'm fine sticking with my script, but I wanted to throw this out there.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.9.0 |
| `node --version` | 11.11.0 |

**Comment by tanhauhau** [comment]
If you take a look at how this repo is structured, you would [see that](https://github.com/lerna/lerna/blob/master/commands/add/package.json) the dependencies are specified as relative `file:` links.

And during publish the `file:` links will be converted to actual version and reverted back to `file:` after publish.

I am not really sure with your actual project setup, but hope this repo can offer some reference for you.

**Comment by pshrmn** [comment]
@tanhauhau my issue isn't with publishing, but with running example packages.

For example, I have [this example package](https://github.com/pshrmn/curi/tree/master/examples/react/basic). On the `master` branch, I [hard code the dependencies](https://github.com/pshrmn/curi/blob/master/examples/react/basic/package.json#L12-L13) so that the example can be run [on CodeSandbox](https://codesandbox.io/s/github/pshrmn/curi/tree/master/examples/react/basic).

In the `dev` branch, the dependencies [use file specifiers](https://github.com/pshrmn/curi/blob/dev/examples/react/basic/package.json#L12-L13), which result in errors [on CodeSandbox](https://codesandbox.io/s/github/pshrmn/curi/tree/dev/examples/react/basic).

**Comment by tanhauhau** [comment]
@pshrmn why don't you use dependencies on dev branch as well?
when `lerna bootstrap`, if the version specified matches the version of the local package in the lerna project, [Lerna will symlink the local copy to your `node_modules/`](https://github.com/lerna/lerna/tree/master/commands/bootstrap#readme)

**Comment by pshrmn** [comment]
I am under the impression that one of the reasons to use file specifiers is that they make `lerna bootstrap` unnecessary. I suppose that a hybrid approach could work, but I appreciate the simplicity of having everything work with just an `npm install` in dev.

**Comment by tanhauhau** [comment]
I am not sure about what's the best practice too. But what hold you back from using `lerna bootstrap` ?

**Comment by pshrmn** [comment]
I suppose that not knowing what the "right" answer is is what is holding me back. It feels odd to me to use a mix of file specifiers and bootstrapping, but maybe I just have an odd setup.

**Comment by tanhauhau** [comment]
Well, I am not the maintainer of Lerna so I don't know what's right too.
I am using version specifier and `lerna bootstrap` for symlinking the packages for my project and so far is working for me, so, I am interested to see how different people setup differently and why.

**Comment by pshrmn** [comment]
I was running into an issue with some converted examples (not directly a Lerna issue, but I needed a dependency left in my dev deps for codesandbox), so I've switched to bootstrapping the examples.
