### ISSUE TITLE
lerna bootstrap fails to symlink dependencies in all packages

### ISSUE THREAD

**Issue by anandsuresh** [lerna/lerna#1986]
Using `file:../packageName` dependencies in `package.json` results in lerna symlinking dependencies in some, but not all packages.

## Expected Behavior

Running `lerna bootstrap` should symlink all internal dependencies correctly, as listed in the respective `package.json` files in each of the packages.

## Current Behavior

Using the `npm` package manager, lerna rewrites the `package.json` files eliminating all internal dependencies, runs `npm install` to install all external dependencies, then attempts to symlink internal dependencies. However, code in the `@lerna/symlink-dependencies` checks for `file:` links and assumes that `npm` would take care of creating the required symlinks, BUT, that isn't the case (I'm not sure if we need additional configuration in lerna or npm to handle the case).

## Possible Solution

In the `@lerna/symlink-dependencies` package, eliminate the check at https://github.com/lerna/lerna/blob/master/utils/symlink-dependencies/symlink-dependencies.js#L38-L41, forcing the creation/handling of internal symlinks.

Alternately, allow the use of the `--force-local` option for `lerna bootstrap` to avoid the above-mentioned checks.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.13.1",
  "version": "independent",
  "packages": [
    "packages/*"
  ],
  "ignoreChanges": [
    "**/*.md"
  ],
  "npmClient": "npm"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

We are using lerna to handle the management of internal dependencies in our monorepo.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.9.0 |
| `node --version` | 10.9.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.13.6 |

**Comment by anandsuresh** [comment]
Please let me know if I can perform additional steps to get more information required to debug this issue.

**Comment by anandsuresh** [comment]
Just realized the mistake I had made. It works fine as long as I remember to correctly add the required dependencies in the root package.json. Closing this out.

**Comment by sinasita** [comment]
Hello @anandsuresh. I have the same issue and - I hope I understood correctly - adding the file: dependencies to the root package.json just ended up in not installing any node-modules in sub-packages at all. Can someone help? Or how did you solve it? I'm not able to start any subpackes with `file: ` locally, because the symlinks where not generated. Thanks!
