### ISSUE TITLE
Enable integration with Yarn Workspaces， run lerna link packages not inside the workspace root.

### ISSUE THREAD

**Issue by ziyi2** [lerna/lerna#1988]
## Expected Behavior

Enable integration with Yarn Workspaces，when i run `lerna link`，symlink together all packages that are dependencies of each other，for example 

 **workspace-a/package.json**
``` javascript
{
  "name": "workspace-a",
  "version": "1.0.0"
}
```

 **workspace-b/package.json**
``` javascript
{
  "name": "workspace-b",
  "version": "1.0.0",

  "dependencies": {
    "workspace-a": "1.0.0"
  }
}
```

Finally, run `lerna link` somewhere, ideally inside the workspace root.

``` javascript
/package.json
/yarn.lock

/node_modules
/node_modules/workspace-a -> /workspace-a

/workspace-a/package.json
/workspace-b/package.json
```

## Current Behavior

but i got 

``` javscript
/package.json
/yarn.lock

/node_modules

/workspace-a/package.json
/workspace-b/package.json
/workspace-b/node_modules/workspace-a  -> /workspace-a
```

## Possible Solution

when i run `lerna bootstrap`，it works well. But i don't want to run `yarn install`  when i run `lerna bootstrap`. Please tell me if missed something.

## Steps to Reproduce (for bugs)

1.   `lerna bootstrap`
2.   `lerna create`
3.   `lerna link`
4.

<details><summary>lerna.json</summary><p>

```json
{
  "useWorkspaces": true,
  "npmClient": "yarn",
  "version": "0.1.0"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

nothing

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1|
| `npm --version`  | 6.1.0 |
| `yarn --version` | 1.13.0 |
| `node --version` | v10.3.0 |

| OS | Version |
| --- | --- |
| Windows 10 | |

**Comment by Yzrsah** [comment]
I had the same problem as you but I resolved the problem by removing Lerna from the project.

You can add a `nohoist` section to your yarn workspaces:

https://yarnpkg.com/blog/2018/02/15/nohoist/

I doubt we'll ever use Lerna again.

**Comment by Yzrsah** [comment]
I had the same problem as you but I resolved the problem by removing Lerna from the project.

You can add a `nohoist` section to your yarn workspaces:

https://yarnpkg.com/blog/2018/02/15/nohoist/

Everything is linked and works correctly, you don't even need to run link.

I doubt we'll ever use Lerna again.

**Comment by ziyi2** [comment]
> I had the same problem as you but I resolved the problem by removing Lerna from the project.
> 
> You can add a `nohoist` section to your yarn workspaces:
> 
> https://yarnpkg.com/blog/2018/02/15/nohoist/
> 
> Everything is linked and works correctly, you don't even need to run link.
> 
> I doubt we'll ever use Lerna again.

Anyway，i'm very grateful for the yarn link you provided，but it can't solve my problem. `lerna bootstrap` can solve my problem，but i can't stand it needs to install all the dependencies again. 

The link you gave me just let me know that there is a config `nohoist` parameter to disable the selected modules from being hoisted to the project root.

**Comment by Yzrsah** [comment]
@ziyi2 

Packages/workspace-a/package.json
```
{
  "name": "@ziyi/workspace-a",
  "version": "1.0.0"
}
```

Packages/workspace-b/package.json
```
{
  "name": "@ziyi/workspace-b",
  "version": "1.0.0",

  "dependencies": {
    "@ziyi/workspace-a": "1.0.0"
  }
}
```

package.json
```
  "workspaces": {
    "packages": [
      "Packages/*",
    ],
    "nohoist": [
      "**"
    ]
  }
```

.yarnrc:
```
workspaces-experimental true
```

When you're done, you type 1 command:
```
yarn
```

That is all.

**Comment by ziyi2** [comment]
> @ziyi2
> 
> Packages/workspace-a/package.json
> 
> ```
> {
>   "name": "@ziyi/workspace-a",
>   "version": "1.0.0"
> }
> ```
> Packages/workspace-b/package.json
> 
> ```
> {
>   "name": "@ziyi/workspace-b",
>   "version": "1.0.0",
> 
>   "dependencies": {
>     "@ziyi/workspace-a": "1.0.0"
>   }
> }
> ```
> package.json
> 
> ```
>   "workspaces": {
>     "packages": [
>       "Packages/*",
>     ],
>     "nohoist": [
>       "**"
>     ]
>   }
> ```
> .yarnrc:
> 
> ```
> workspaces-experimental true
> ```
> When you're done, you type 1 command:
> 
> ```
> yarn
> ```
> That is all.

 You are right， simple application does not require lerna，but I still see a lot of good features of lerna，such as `lerna publish`、`lerna build`.  I can release patch version with`npm publish` in each package，and release minor version with  `lerna publish`. So i should mix yarn and lerna.

**Comment by Yzrsah** [comment]
> ## Expected Behavior
> Enable integration with Yarn Workspaces，when i run `lerna link`，symlink together all packages that are dependencies of each other，for example
> 
> **workspace-a/package.json**
> 
> ```js
> {
>   "name": "workspace-a",
>   "version": "1.0.0"
> }
> ```
> 
> **workspace-b/package.json**
> 
> ```js
> {
>   "name": "workspace-b",
>   "version": "1.0.0",
> 
>   "dependencies": {
>     "workspace-a": "1.0.0"
>   }
> }
> ```
> 
> Finally, run `lerna link` somewhere, ideally inside the workspace root.
> 
> ```js
> /package.json
> /yarn.lock
> 
> /node_modules
> /node_modules/workspace-a -> /workspace-a
> 
> /workspace-a/package.json
> /workspace-b/package.json
> ```
> 
> ## Current Behavior
> but i got
> 
> ```
> /package.json
> /yarn.lock
> 
> /node_modules
> 
> /workspace-a/package.json
> /workspace-b/package.json
> /workspace-b/node_modules/workspace-a  -> /workspace-a
> ```
> ## Possible Solution
> when i run `lerna bootstrap`，it works well. But i don't want to run `yarn install` when i run `lerna bootstrap`. Please tell me if missed something.
> 
> ## Steps to Reproduce (for bugs)
> 1. `lerna bootstrap`
> 2. `lerna create`
> 3. `lerna link`
> 
> lerna.json
> lerna-debug.log
> ## Context
> nothing
> 
> ## Your Environment
> Executable	Version
> `lerna --version`	3.13.1
> `npm --version`	6.1.0
> `yarn --version`	1.13.0
> `node --version`	v10.3.0
> OS	Version
> Windows 10


> You are right， simple application does not require lerna，but I still see a lot of good features of lerna，such as `lerna publish`、lerna build. I can release patch version with`npm publish` in each package，and release minor version with `lerna publish.` So i should mix yarn and lerna.

You asked for linking outside of the root. That command is `yarn` which uses the `workspace-aggregator` to automatically resolve commands at the workspace level. You can run `yarn` inside the package directories and all updates are performed, including linking.

If your issue was resolved by the above steps (removal of lerna for bootstrap/link), then you can ask the author to update documentation in order to not mislead you into using `lerna boostrap` or `lerna link`, so that you can have more free time to contribute to issues which focus on other parts of lerna you still want to use.

**Comment by Yzrsah** [comment]
> ## Expected Behavior
> Enable integration with Yarn Workspaces，when i run `lerna link`，symlink together all packages that are dependencies of each other，for example
> 
> **workspace-a/package.json**
> 
> ```js
> {
>   "name": "workspace-a",
>   "version": "1.0.0"
> }
> ```
> 
> **workspace-b/package.json**
> 
> ```js
> {
>   "name": "workspace-b",
>   "version": "1.0.0",
> 
>   "dependencies": {
>     "workspace-a": "1.0.0"
>   }
> }
> ```
> 
> Finally, run `lerna link` somewhere, ideally inside the workspace root.
> 
> ```js
> /package.json
> /yarn.lock
> 
> /node_modules
> /node_modules/workspace-a -> /workspace-a
> 
> /workspace-a/package.json
> /workspace-b/package.json
> ```
> 
> ## Current Behavior
> but i got
> 
> ```
> /package.json
> /yarn.lock
> 
> /node_modules
> 
> /workspace-a/package.json
> /workspace-b/package.json
> /workspace-b/node_modules/workspace-a  -> /workspace-a
> ```
> ## Possible Solution
> when i run `lerna bootstrap`，it works well. But i don't want to run `yarn install` when i run `lerna bootstrap`. Please tell me if missed something.
> 
> ## Steps to Reproduce (for bugs)
> 1. `lerna bootstrap`
> 2. `lerna create`
> 3. `lerna link`
> 
> lerna.json
> lerna-debug.log
> ## Context
> nothing
> 
> ## Your Environment
> Executable	Version
> `lerna --version`	3.13.1
> `npm --version`	6.1.0
> `yarn --version`	1.13.0
> `node --version`	v10.3.0
> OS	Version
> Windows 10


> You are right， simple application does not require lerna，but I still see a lot of good features of lerna，such as `lerna publish`、lerna build. I can release patch version with`npm publish` in each package，and release minor version with `lerna publish.` So i should mix yarn and lerna.

You asked for linking outside of the root. That command is `yarn` which uses the `workspace-aggregator` to automatically resolve commands at the workspace level. You can run `yarn` inside the package directories and all updates are performed, including linking.

If your issue was resolved by the above steps (removal of lerna for bootstrap/link), then you can ask the author to update documentation in order to not mislead you into using `lerna boostrap` or `lerna link` so that you can have more free time to contribute to issues which focus on other parts of lerna you still want to use.

**Comment by Yzrsah** [comment]
> ## Expected Behavior
> Enable integration with Yarn Workspaces，when i run `lerna link`，symlink together all packages that are dependencies of each other，for example
> 
> **workspace-a/package.json**
> 
> ```js
> {
>   "name": "workspace-a",
>   "version": "1.0.0"
> }
> ```
> 
> **workspace-b/package.json**
> 
> ```js
> {
>   "name": "workspace-b",
>   "version": "1.0.0",
> 
>   "dependencies": {
>     "workspace-a": "1.0.0"
>   }
> }
> ```
> 
> Finally, run `lerna link` somewhere, ideally inside the workspace root.
> 
> ```js
> /package.json
> /yarn.lock
> 
> /node_modules
> /node_modules/workspace-a -> /workspace-a
> 
> /workspace-a/package.json
> /workspace-b/package.json
> ```
> 
> ## Current Behavior
> but i got
> 
> ```
> /package.json
> /yarn.lock
> 
> /node_modules
> 
> /workspace-a/package.json
> /workspace-b/package.json
> /workspace-b/node_modules/workspace-a  -> /workspace-a
> ```
> ## Possible Solution
> when i run `lerna bootstrap`，it works well. But i don't want to run `yarn install` when i run `lerna bootstrap`. Please tell me if missed something.
> 
> ## Steps to Reproduce (for bugs)
> 1. `lerna bootstrap`
> 2. `lerna create`
> 3. `lerna link`
> 
> lerna.json
> lerna-debug.log
> ## Context
> nothing
> 
> ## Your Environment
> Executable	Version
> `lerna --version`	3.13.1
> `npm --version`	6.1.0
> `yarn --version`	1.13.0
> `node --version`	v10.3.0
> OS	Version
> Windows 10


> You are right， simple application does not require lerna，but I still see a lot of good features of lerna，such as `lerna publish`、lerna build. I can release patch version with`npm publish` in each package，and release minor version with `lerna publish.` So i should mix yarn and lerna.

You asked for linking outside of the root. That command is `yarn` which uses the `workspace-aggregator` to automatically resolve commands at the workspace level. You can run `yarn` inside the package directories and all updates are performed, including linking.

If your issue was resolved by the above steps (removal of lerna for bootstrap/link), then you could ask the author to update documentation in order to not mislead you into using `lerna boostrap` or `lerna link` so that you can have more free time to contribute to issues which focus on other parts of lerna you still want to use.

**Comment by ziyi2** [comment]
@Yzrsah Thank you very much for taking the time to answer me.
