### ISSUE TITLE
lerna ERR! E403 You do not have permission to publish !

### ISSUE THREAD

**Issue by rohyadav** [lerna/lerna#1992]
Hi,

I am getting this error, somebody help me how do i fix this.

![Screen Shot 2019-03-17 at 7 02 46 PM](https://user-images.githubusercontent.com/21152844/54491826-6f180080-48e7-11e9-81e0-cd0038c28d81.png)

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | 1.13.0 |
| `node --version` | 11.6.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by rohyadav** [comment]
I have short it out, so i am closing this issue

**Comment by JohnTheo13** [comment]
how?

**Comment by vin1992** [comment]
> how?

just change the package name ,  I guess
