### ISSUE TITLE
EUNCOMMIT when publishing from CI - package-lock.json

### ISSUE THREAD

**Issue by bennypowers** [lerna/lerna#1994]
Thank you for publishing and maintaining this package.

## Expected Behavior
Packages publish lickety-split

## Current Behavior
```
Publishing packages...
lerna notice cli v3.13.1
lerna info versioning independent
lerna info canary enabled
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.
```

The uncommitted changes are all in package-lock.json, are all more or less:

```patch
-          "resolved": false,
+          "resolved": "",
```

## Possible Solution
reset the package lock in CI? 

## Steps to Reproduce (for bugs)
CI runs the following steps:
1. npm ci
3. linting, testing, etc
4. this script runs to publish packages:
```bash
echo "Authenticating with Registry..."
npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN -q

echo "Configuring CI Git User..."
git config --global user.email octocat@github.com
git config --global user.name Github Actions

git status
git diff

echo "Publishing packages..."
npx lerna publish --canary --yes
```

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "command": {
    "publish": {
      "conventionalCommits": true
    },
    "version": {
       "message": "chore: release new versions",
       "conventionalCommits": true
    }
  }
}

```
</p></details>

## Context
I've got a monorepo of web components. each one has a build step via rollup, then we (hope to ) publish with semantic release. This is my initial attempt to publish

## Your Environment
CI is running on github actions, with the Github actions for NPM action, running "npm run deploy:ci"

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.5.0 |
| `node --version` | v10.15.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
Github actions for NPM | `actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680`|

**Comment by bennypowers** [comment]
My disconcerting but seemingly effective solution was to run `git stash` before running `lerna publish`

**Comment by maecapozzi** [comment]
@bennypowers, did you try running `npm install` locally? It could be that you didn't run `npm install` locally, which would've updated your `package-lock.json`. If you're CI script is running correctly, it's probably `npm install`ing every time, which would mean it generates a new `package-lock.json`. 

To fix - locally make sure to run `npm install`. If it generates a new `package-lock.json` file, then commit it and push it up.

**Comment by evocateur** [comment]
Without a log of any sort, or concrete reproduction, I literally have no idea why this error is occurring. What _is_ the diff that it complains about? (yes, yes, there is an open PR to add the logging of this diff to this _very_ error...)

**Comment by kaminskypavel** [comment]
yup still there. 

```
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove the following changes before continuing:
lerna ERR! EUNCOMMIT  M package-lock.json
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@ lerna:publish: `lerna publish --yes`
npm ERR! Exit status 1

```

**Comment by JordanBonitatis** [comment]
@kaminskypavel - is the `npm` version you are using locally the same that you're using in your CI environment?

**Comment by a613** [comment]
> an open PR

What is it?

**Comment by egemon** [comment]
Stashing works fine. For me it was some utils files created in repo by JJ

**Comment by DavideDaniel** [comment]
This is also a problem with build state and install state file variations in ci.. for example, circle creates a file, which I'd never run into until recently:

**Comment by jstarmx** [comment]
> yup still there.
> 
> ```
> lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove the following changes before continuing:
> lerna ERR! EUNCOMMIT  M package-lock.json
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! root@ lerna:publish: `lerna publish --yes`
> npm ERR! Exit status 1
> ```
> 
> as a wo `git checkout` can be used, but I dont feel like its the correct way.

I know this is quite old but just ran into the same problem, eventually resolved it by using `npm install --no-package-lock` in the CI environment which prevented it from generating a modified `package-lock.json`. Not sure if it's the best solution, but it works.
