### ISSUE TITLE
How to add the root as a managed location?

### ISSUE THREAD

**Issue by Aqours** [lerna/lerna#1996]
## Expected Behavior

lerna link root's dependencies to packages' directories ([FAQ.root-package.json](https://github.com/lerna/lerna/blob/master/FAQ.md#root-packagejson))

## Current Behavior

It's not working

## Possible Solution

symlink root binary to packages binary with a command. maybe like [link-parent-bin](https://www.npmjs.com/package/link-parent-bin)

## Steps to Reproduce (for bugs)

1. create a monorepo(`package.name: monorepo`)
2. create a package: `lerna create demo`
3. install tslint in root dir: `npm i -D tslint` (I not found lerna command to add packages to root package.json)
4. run lerna bootstrap: `lerna bootstrap --hoist`
5. check tslint in demo dir: `cd packages/demo`, `npx --no-install tslint -v`
6. log **not found: tslint**

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*",
    "monorepo" // I also try input: "./", "./package.json", "./monorepo", 
  ],
  "version": "independent"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | VERSION |
| `node --version` | 10.10.0 |

| OS | Version |
| --- | --- |
| Windows 10 | 1809 |

**Comment by evocateur** [comment]
You don't need to make the root package.json a publishable package just to run `tslint` (or any other build/test-related command) from the root. Any linter worth its salt has fairly simple mechanisms for targeting its behavior.

**Comment by Aqours** [comment]
@evocateur You are right. But I want to run bundler(e.g: webpack. `lerna run webpack --since`) in sub-project independently, and run `tslint` etc. independently when I import my old projects which might use different tslint.json configration.

**Comment by craveytrain** [comment]
Is there a way to do this in the `lerna.json`? I've tried all sorts of relative paths `.`, `./`, `./*`, `../*`, `*`, `pacakage.json` and none of them seem to work.

My intent is for lerna to update the root package.json version with the fixed version of my other packages.

Thank you.

**Comment by evocateur** [comment]
`{ "packages": [".", "packages/*"] }`

You're gonna have a bad time if you use a lock file (and you should): the lock file version is not currently synchronized when the manifest version is bumped.

I really, _really_ don't recommend adding the root manifest to the managed package targets. It's just an enormous hassle compared to any perceived benefits. It is one of the things I am considering removing in the next major, it's so bad.

**Comment by craveytrain** [comment]
Thank you for your candid advice. Would it be advised to remove the suggestion in the FAQ or or caveat it as you have?

**Comment by evocateur** [comment]
Yeah, probably should remove that bit from the FAQ.

**Comment by jpolo** [comment]
This feature would greatly simplify the import of a project in a lerna repo. At the moment I have to change every scripts manually by prefixing `../../node_modules/.bin/`.

**Comment by IMBurbank** [comment]
I really like allowing lerna to manage the root package. It allows us to keep a root lerna devDependency as well as all dependencies needed to run our multi-package build/deploy pipelines. 

@evocateur I think the versioning issue on the root packages can be overcome with minimal effort. My current solution is to have a `version` hook in the root package.json that runs a script like this:

```javascript
// scripts/versionRootPackage.js

const fs = require("fs");
const { exec } = require("child_process");


const root = "..";
const pJsonName = "package.json";
const pLockName = "package-lock.json";

const pJson = require(`${root}/${pJsonName}`);
const { version } = require(`${root}/lerna.json`);

let pLock;


const updateVersion = (file, version, json) => {
  json.version = version;

  return fs.writeFileSync(
    file,
    JSON.stringify(json, null, 2).concat("\n"),
    { encoding: "utf8", flag: "w" },
  );
}


updateVersion(pJsonName, version, pJson);

if (fs.existsSync(pLockName)) {
  pLock = require(`${root}/${pLockName}`)
  updateVersion(pLockName, version, pLock);
}

exec(`git add ${pJsonName} ${pLockName}`, (stdout, stderr) => {
  if (stdout) {
    console.log(stdout);
  }

  if (stderr) {
    console.log(stderr);
  }
});

```

**Comment by alvis** [comment]
Another workaround to have the root managed and yet avoid the `postinstall/prepare` loop during `bootstrap` is to ignore the root package by `lerna bootstrap --ignore <root package name>`.
