### ISSUE TITLE
How to connect sibling packages?

### ISSUE THREAD

**Issue by reggi** [lerna/lerna#200]
The doc says that `bootstrap`

> Link together all Lerna packages that are dependencies of each other.

How do I go about making one package a dep of another?
1. `npm install ../my-sibling —save`
2. `npm install @nspace/my-sibling —save` (does it have to be published first)?
3. `npm link ../my-sibling —save`

**Comment by gigabo** [comment]
Your package that depends on `my-sibling` needs the dependency to be specified in its package.json.

If `my-sibling` hasn't been published yet you'll need to add that dependency yourself by editing the JSON file.  Once the dependency is added `lerna bootstrap` will create the "link" regardless of whether `my-sibling` has been published.

**Comment by thejameskyle** [comment]
I was considering at one point to have a replacement install command like this:

```sh
$ lerna install [package] [dependency][@version] [--save,--save-dev,...]
```

And if you installed a local dependency with the matching version or no version specified then Lerna would link them together.

There's probably a ticket for this already, but if there isn't there should be

**Comment by reggi** [comment]
@thejameskyle I'd love this and it would be nice to have tabbed auto completion because all of the options for what to install or where to install are in `packages`. :)

**Comment by hzoo** [comment]
Kinda in https://github.com/lerna/lerna/issues/53 but could be cleared up to desired behavior/cli

**Comment by thejameskyle** [comment]
Merging into #53

**Comment by spudly** [comment]
> If my-sibling hasn't been published yet you'll need to add that dependency yourself by editing the JSON file. Once the dependency is added lerna bootstrap will create the "link" regardless of whether my-sibling has been published.

@gigabo, When you say add the dependency yourself, do you mean as a local dependency? Like this?

```json
{
  "dependencies": {
    "my-other-pkg": "file:../my-other-pkg",
  }
}
```

**Comment by gigabo** [comment]
@spudly Actually a caret-ranged version dependency, like:

```js
{
  "dependencies": {
    "my-other-package": "^0.0.1",
  }
}
```

^ That assumes that the package.json for `my-other-package` has `"version": "0.0.1"`, but `my-other-package` doesn't need to have been published yet.

Incidentally Asini recently got an [`add` command](https://github.com/asini/asini/pull/46), which is basically a yarn-flavored version of what is described in https://github.com/lerna/lerna/issues/200#issuecomment-225063191.  Maybe we should port that over.
