### ISSUE TITLE
[Question] How does this compare to alternatives?

### ISSUE THREAD

**Issue by lonix1** [lerna/lerna#2000]
The docs are good, but something is missing. How does this compare to similar tools, e.g. [nx](https://github.com/nrwl/nx)?

Can someone please advise the factors to consider when choosing the one or the other (or other alternatives)? Presumably there is overlap, but also I would assume one is better suited for some scenarios and the other is suitable for others.

Any advice would be appreciated!

**Comment by revelt** [comment]
I feel your sentiment, Lerna has quite a steep learning curve. It cost me all my spare time during last Christmas, trial and error, to learn and implement it. But if one has many software projects, it means that one must be quite advanced-level developer at the first place. And Lerna is best learnt by practice, trial and error.

In my case, after my npm package count grew past 80, it became a hassle to update them. I'd bump the dependencies and [release](https://www.npmjs.com/package/np) libraries with names `array-` and `ast-` on Monday, then do "c"-to-"e" on Tuesday and so on, all week long. I could spend all morning, every day, just maintaining packages. And some of them had even [circular](http://npm.anvaka.com/#/view/3d/email-comb) dependencies. I had pain and chose Lerna as a painkiller.

> Flux libraries are like glasses: you’ll know when you need them. — Dan Abramov

Same with monorepos. You'll know when you need them.

It's best to code projects first, then, when you need to solve a certain problem, seek a solution. If your inner demons obstruct you from making projects by making you research more efficient ways to make projects, it's a wrong way.

Having said that, there are alternatives for web-oriented monorepos and different programming languages, check out https://github.com/korfuri/awesome-monorepo
