### ISSUE TITLE
Add multiple packages in a single command

### ISSUE THREAD

**Issue by jordanbtucker** [lerna/lerna#2004]
## Expected Behavior

The following command would allow a user to add the `bar` and `baz` packages to the `foo` package.

```
lerna add --scope=foo bar baz
```

## Current Behavior

Currently you can only add one package at a time. To achieve the goal of the previous example, you must run the following.

```
lerna add --scope=foo bar
lerna add --scope=foo baz
```

## Context

It's quite common to install multiple npm packages as dependencies.

```
npm i -D eslint eslint-config-standard eslint-plugin-standard eslint-plugin-node eslint-plugin-import eslint-plugin-promise eslint-plugin-react
npm i -D @babel/core @babel/preset-env @babel/preset-react
npm i -D react react-dom redux react-redux react-router-dom
npm i -D webpack webpack-cli webpack-dev-server babel-loader file-loader css-loader style-loader
```

Intuitively, lerna should also allow this behavior. 

#1608 was opened to request this feature, but no discussion came from it. The result was essentially "lerna doesn't do this" and the reason given was vague.

> The ambiguity of targets forced a simplification of logic.

I'm not sure what that is supposed to mean, but this behavior caught me out the first time I tried to use lerna because I just expected it to work like npm.

**Comment by JabbyPanda** [comment]
Supported glob patterns for `--scope` and its opposite counterpart `--ignore` can be looked upon in existing tests for `get-filtered-packages` utility 

https://github.com/lerna/lerna/blob/master/core/filter-options/__tests__/get-filtered-packages.test.js#L56-L64

![image](https://user-images.githubusercontent.com/255913/65586067-d0e6b080-df83-11e9-94ae-f522953bac0b.png)

**Comment by jordanbtucker** [comment]
@JabbyPanda This issue has nothing to do with `--scope`.

**Comment by JabbyPanda** [comment]
`--scope` does not support passing value as array 

https://github.com/lerna/lerna/issues/1846
https://github.com/lerna/lerna/issues/689

**Comment by jordanbtucker** [comment]
@JabbyPanda This still has nothing to do with `--scope`. This issue is about `add`ing multiple packages in the same command, regardless of the scope. Basically, this should work:

```bash
# This works with npm:
npm install bar baz

# This does not work with lerna:
lerna add bar baz
```

I just added `--scope` to the command since it's a common option used. It's more common to add a package to only one of your monorepo packages than it is to add it to all of your packages.

**Comment by georgyfarniev** [comment]
Cast @evocateur, it's extremely inconvenient to call lerna add multiple times for installing more than one package.

**Comment by wingleung** [comment]
Created a WIP PR (#2311) to be able to add multiple packages in one go. Needed to move the second argument (glob) to a separate option (--destination). 

Originally anything after the first argument was part of the destination definition. For example, the following would install package-name to all packages under `submodules`, `packages`, `commands`. 
```
lerna add package-name submodules/* packages/* commands/*
```

This would change in #2311 to..
```
lerna add module-1 --destination submodules/* packages/* commands/*
``` 
Making it possible to accept multiple packages in one command like the following..
```
lerna add module-1 module-2 module-3 --destination packages/*
```
If the proposed PR is accepted, I'll fix the tests accordingly

**Comment by hinell** [comment]
You may want to use something like [`adddep`][0] combined with `lerna exec ... adddep <dependencies>` as ad-hoc solution but it's buggy.

[0]: https://github.com/19h/npm-adddep

**Comment by lazarljubenovic** [comment]
Jesus the error message when you try to add multiple packages is so cryptic, it took me ages to find out what's wrong.

Hopefully writing the error message here helps someone googling: “No packages found where can be added.”

**Comment by Domiii** [comment]
Same as @lazarljubenovic. Please fix the error message and #saveMe2HoursOfDebuggingTime. Love <3

**Comment by cliffordfajardo** [comment]
I also ran into this the `No packages found where can be added` message. I thought this was strange since  `lerna`'s `--scope` option flag supports glob patterns like so:


### `--scope`
**✅ Add `@my-company/utils` into `@my-company/ui` and `@my-company/data**

```
lerna add '@my-company/utils --scope '@my-company/{ui,data}'   
```

So I expected this to work work for `add` subcommand as well:

### `lerna add`
**❌ Add `@my-company/utils` and `@my-company/types` into `@my-company/ui` and `@my-company/data`**
```
lerna add '@my-company/{utils,types}' --scope '@my-company/{ui,data}'   



// I have to do this instead
lerna add '@my-company/utils' --scope '@my-company/{ui,data}' 
lerna add '@my-company/types' --scope '@my-company/{ui,data}'
```


I haven't dived into the `lerna` codebase much but something similar needs to be added to lerna's [`add` subcommand](https://github.com/lerna/lerna/tree/master/commands/add) just like how we allow it for the `--scope` optional flag.

**Comment by nephix** [comment]
+1

**Comment by OmarZeidan** [comment]
@jordanbtucker 

You can perform this via

`lerna exec -- yarn add package-1 package-2 package-3 -D --scope YOUR_PACKAGE`

**Comment by dustinlacewell** [comment]
Pls fix..

**Comment by sixiakun** [comment]
Pls..

**Comment by mjgp2** [comment]
I mean it's not ideal but -

`echo -n @mine/foo jest-environment-jsdom @nestjs/testing mockdate ts-jest | gxargs -d ' ' -l1 yarn lerna add --scope @mine/bar`

**Comment by jordanbtucker** [comment]
> I mean it's not ideal but

Nor is it cross platform.

**Comment by jordanbtucker** [comment]
@OmarZeidan 

> You can perform this via
>
>     lerna exec -- yarn add package-1 package-2 package-3 -D --scope YOUR_PACKAGE

I think you also need to run `lerna bootstrap` after for the command to be equivalent to `lerna add`.

**Comment by frsnic** [comment]
I change the command for fix package scope.
```
lerna --scope YOUR_PACKAGE exec -- yarn add package-1 package-2 package-3 -D
```

**Comment by ZielMartin** [comment]
second this!
maybe make it possible to quote the packages to add like this?
`npx lerna add "@nestjs/typeorm typeorm" --scope=myapp`

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
