### ISSUE TITLE
Option - Use root `package.scripts` for `lerna run`

### ISSUE THREAD

**Issue by jagretz** [lerna/lerna#2005]
It would be nice to be able to run an npm script that is included the root (lerna) package.json that is ran against all children in  `packages`. 

## Expected Behavior

_Using `eslint` as an example._

Today, if you run `lerna run eslint` this will look at each sub-package and run the packages `package.script.eslint`.  It would be nice to provide an option to run the root (lerna) package `package.scripts.eslint` instead of having to declare the same script in each child in `packages`.

## Current Behavior

The current behavior only allows (as far as I know) the script to be invoked _if_ there is a corresponding script in the `packages` package.scripts. ie for example project `foobar-lerna`

```
/foobar-lerna
-- package.json
-- packages
   -- /foo
       -- package.json
       -- /src
   -- /bar
       -- package.json
       -- /src
```

If foo/package.json has a script for `eslint`. `lerna run eslint` will run the eslint script for `foo` that is specified in the `foo` package.json.

If bar/package.json _DOES NOT_ have a script for `eslint`. `lerna run eslint` will run any script in  `bar`.

This addition (a flag perhaps?) would allow you to run the exact same script across all children.

## Possible Solution

Add a flag to run the script that is included with the root package. ie `foobar-lerna` package.json or in the lerna.json. To be honest, I thought this was the "default" functionality of `lerna run <my script>` until I read into it. Since it is not the default functionality I think the addition of a new flag would be most appropriate in order to maintain backwards compatibility with the existing command.

_(I am certainly not tied to the names I chose for these 2 flags, using them just to get the point across.)_
```bash
# used with `lerna run <my script>
--from-root          # run script from root package
--ignore-children    # ignore same scripts from children in packages
```

## Context

Reduce the amount of overhead that is necessary to maintain the same npm script that exists in every package. Currently, when you want to update an npm script that exists in each of the `packages`, you must to apply the update against _all_ `packages`

**Comment by evocateur** [comment]
Assuming `"scripts": { "lint": "eslint ./packages" }` in the root package.json, this is all you need:
```sh
npm run lint
```

All repetitive test scripts should be run from the root anyway, it's half the benefit of a monorepo in the first place.

**Comment by jagretz** [comment]
Thanks for the response @evocateur. I think I am coming to realize more and more through experience when a monorepo is appropriate and when it is not. `eslint` isn't the best example here but it still works to illustrate my "wants". While running from the root is great, it doesn't work perfect in all situations. 

For example, you can specify an additional eslint config within a sub-package that will be "picked up" by and used by eslint when linting. However, the same is not true for the `.eslintignore` configuration. That configuration is not overridden nor inherited further up the directory tree. 

Therefore you have to add anything you wish to ignore in sub-packages to the roots `.eslintignore. Then you are stuck adding glob patterns every time you want to ignore a new directory or file in a sub-package, ie

```yaml
/packages/**/node_modules
/packages/**/coverage
/packages/**/build
```

Well, that is annoying, but it's specific to the tool so what can you do ¯\_(ツ)_/¯

So now let's say you want to run eslint from the sub-package, let's use `packages/foo`.  You either have to have a globally installed version of eslint or eslint installed locally as a dev-dependency -- which is what I do. You'd think, no problem, so you create your npm script for eslint, ie

```json
"scripts": {
    "eslint": "eslint ./",
```

Then run `npm run eslint` from `/foo` (because it is the only package you are touching atm) thinking everything is hunky-dory except wait a minute, nothing is being ignored! Crap, you need to have a local `.eslintignore` file... ok, so you add one, run the script again and you start getting a bunch of new eslint warnings/errors (or none at all). What's the matter? Oh, that's right, package `/foo` only has a subset of eslint config... ok, hmmm

Well luckily enough, eslint provides cli options that allow you to use specify a particular configuration and ignore location. So then you are stuck writing a script along the lines of,

```json
"scripts": {
    "eslint": "eslint ./ --config ../../.eslintrc.js --ignore-path ./eslintignore",
```

At this point I can run eslint at the root and for the sub-package `/foo` -- success! I got want I wanted, but crap that was a lot of effort for something so small. And to do this for every sub-package and every tool (eslint is just one) would be a total pain and require a lot of unnecessary knowledge imo.

So here is was I have think I have realized... after some trial and error I began to use lerna simply as a tool to manage symlinking sub-packages and npm dependencies between the disparate packages. Maybe for the types of packages I am trying to manage together, a monorepo isn't the right choice.  

Anyways, I thought some more explanation was due. Perhaps my original proposed solution would be beneficial to some, but it might just mean a monorepo isn't the right choice. Cheers

**Comment by evocateur** [comment]
I really don't understand why your need for ornate `.eslintignore` settings disqualifies running eslint from the root. You're in a monorepo, it's _intentional_ to condense one's build/test config in the root. If you're perturbed by that, perhaps a monorepo really isn't for you.

**Comment by jagretz** [comment]
Yup! As I said, it's a good learning experience, but not suited for this use case -- eslint is obvious just used as an example, it applies to all builds, tests, etc. 
I like the idea behind a monorepo, and using lerna helps manage many packages when they're all very similar like babel plugins, or a component library. I'm actually using lerna for a monorepo I've setup for use with a component library and it works great to manage interdependent packages.
I am curious to see how other companies use monorepos with many large disparate apps. The few I've peeked into use internal tooling to manage; google, microsoft. I'll have to dig in deeper at some point.
