### ISSUE TITLE
`lerna pulish --exact` fails since publish and version was split

### ISSUE THREAD

**Issue by despairblue** [lerna/lerna#2008]
Running `lerna publish --exact --dist-tag next --force-publish` fails with 

```
ERR! lerna Unknown argument: exact
ERROR: "lerna publish --exact --force-publish" exited with 1.
```

## Expected Behavior
According to the documentation all flags `version` supports should be supported by `publish` as well.

## Current Behavior
`lerna publish --exact` fails after publishing to npm, without committing to the repo.

## Possible Solution
Make it not fail ^^

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by despairblue** [comment]
Nevermind this, this happened because the script for publishing was called `publish` as well, so it seams lerna invoked itself during the release. This is new, the script was always called publish :confused: 

I read this comment by accident: https://github.com/lerna/lerna/issues/1880#issuecomment-456502998

Maybe lerna could check for this and output a warning?

**Comment by evocateur** [comment]
Without filling out the issue template (versions, config, debug log) I have no way of helping you.
