### ISSUE TITLE
"lerna add" requires package to be present in remote registry (adding unpublished dependencies)

### ISSUE THREAD

**Issue by slavafomin** [lerna/lerna#2011]
Hello!

Thank you for your hard work.

However, when using [`lerna add`](https://github.com/lerna/lerna/tree/master/commands/add) command like this: `npx lerna add @acme/button --scope @acme/app` it fails with an error: `'@acme/button' is not in the npm registry`.

I'm trying to add one local unpublished package to the other one.

In order to work around this I have to add the dependency manually to the `package.json` of the `@acme/app` package and then run: `npm run bootstrap` again, which takes some time to process  the dependencies.

I think that lerna should be able to effectively add local unpublished dependencies to local packages, which is the point of using the monorepo in the first place.

Probably, the algorithm should be updated to first look for the specified dependency in the local monorepo's tree, before trying the remote registry.

What do you think?

**Comment by evocateur** [comment]
> [The] algorithm should be updated to first look for the specified dependency in the local monorepo's tree, before trying the remote registry.

That's exactly what happens?
https://github.com/lerna/lerna/blob/4e3f8d8087e0e2e8e83c7ea79558c517203583c2/commands/add/index.js#L183-L211

There are several tests to this effect. It would be helpful if you could provide a repository (or gist) with a reproduction.

**Comment by slavafomin** [comment]
Thank you for the clarification. That's weird, because it was not working in my case. It would be hard to extract this from our big monorepo.

**Comment by 1010543618** [comment]
I got the same problem

Test repo: https://github.com/1010543618/lerna-test

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.2 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.13.0 |
| `node --version` | v10.15.1 |

**`lerna add @zjf/pkg1 --scope=@zjf/pkg2` get error**

```bash
zjffu@DESKTOP-QOA2E6D MINGW64 /d/test/lerna-test (master)
$ lerna clean
info cli using local version of lerna
lerna notice cli v3.13.2
lerna info Removing the following directories:
lerna info clean packages\pkg1\node_modules
lerna info clean packages\pkg2\node_modules
? Proceed? Yes
lerna info clean removing D:\test\lerna-test\packages\pkg1\node_modules
lerna info clean removing D:\test\lerna-test\packages\pkg2\node_modules
lerna success clean finished

zjffu@DESKTOP-QOA2E6D MINGW64 /d/test/lerna-test (master)
$ lerna add @zjf/pkg1 --scope=@zjf/pkg2
info cli using local version of lerna
lerna notice cli v3.13.2
lerna info filter [ '@zjf/pkg2' ]
lerna info Adding @zjf/pkg1 in 1 package
lerna notice filter including "@zjf/pkg2"
lerna info filter [ '@zjf/pkg2' ]
lerna WARN bootstrap Installing local packages that do not match filters from registry
lerna info Bootstrapping 1 package
lerna info Installing external dependencies
lerna ERR! npm install --no-save exited 1 in '@zjf/pkg2'
lerna ERR! npm install --no-save stderr:
npm ERR! code E404
npm ERR! 404 Not Found: @zjf/pkg1@^1.0.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zjffu\AppData\Roaming\npm-cache\_logs\2019-04-16T09_54_15_607Z-debug.log

lerna ERR! npm install --no-save exited 1 in '@zjf/pkg2'
lerna ERR! npm install --no-save exited 1 in '@zjf/pkg2'
lerna ERR! npm install --no-save stderr:
npm ERR! code E404
npm ERR! 404 Not Found: @zjf/pkg1@^1.0.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zjffu\AppData\Roaming\npm-cache\_logs\2019-04-16T09_54_15_607Z-debug.log

lerna ERR! npm install --no-save exited 1 in '@zjf/pkg2'
```

**then `lerna bootstrap` success**

```
zjffu@DESKTOP-QOA2E6D MINGW64 /d/test/lerna-test (master)
$ lerna bootstrap
info cli using local version of lerna
lerna notice cli v3.13.2
lerna info Bootstrapping 2 packages
lerna info Symlinking packages and binaries
lerna success Bootstrapped 2 packages
```

**Comment by evocateur** [comment]
@1010543618 Notable in your example repo, the root lerna.json version field (0.0.0) does not match the version fields of the leaf packages (1.0.0). So that's kind of weird.

**Comment by 1010543618** [comment]
Oops... I made a mistake. Modifying to the correct version works fine.

I use `npm init` create pkgs, so the version of pkgs are (1.0.0). I should use `lerna create`.

**Comment by 1010543618** [comment]
@evocateur 

It didn't works fine...

New test repo: https://github.com/1010543618/lerna-test.git

The selfSatisfied is true:

![图片](https://user-images.githubusercontent.com/25266120/56355037-e18e4000-6207-11e9-8baf-950ca226b543.png)

but the isSatisfied is false and then download from npm:

![图片](https://user-images.githubusercontent.com/25266120/56355371-b2c49980-6208-11e9-9c10-48e97f40408e.png)

Is it a bug? Pleased to pull request.

**Comment by naishe** [comment]
I am facing the same issue. `lerna add ams-sdk --scope=ams-api` does not add `ams-sdk` to `ams-api`

```
lerna add ams-sdk --scope=ams-api
lerna notice cli v3.13.3
lerna info filter [ 'ams-api' ]
lerna info Adding ams-sdk in 1 package
lerna notice filter including "ams-api"
lerna info filter [ 'ams-api' ]
lerna WARN bootstrap Installing local packages that do not match filters from registry
lerna info Bootstrapping 1 package
lerna info Installing external dependencies
lerna ERR! npm install --no-save exited 1 in 'ams-api'
lerna ERR! npm install --no-save stderr:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ams-sdk@^0.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'ams-api'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nishant/.npm/_logs/2019-05-10T11_51_49_538Z-debug.log

lerna ERR! npm install --no-save exited 1 in 'ams-api'
lerna ERR! npm install --no-save exited 1 in 'ams-api'
lerna ERR! npm install --no-save stderr:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ams-sdk@^0.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'ams-api'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nishant/.npm/_logs/2019-05-10T11_51_49_538Z-debug.log
```

**Comment by zhipenglin** [comment]
I am facing the same issue. and this problem does not exist in version 2.x

**Comment by hilleer** [comment]
Experiencing similar problem, having same error thrown when lerna tries to npm install in child package.json's.

**Comment by evocateur** [comment]
I would appreciate a PR with a failing test that demonstrates this issue. I've literally never encountered it.

**Comment by shanshanyang** [comment]
experienced similar problem, it turned out that in my lerna.json packages array, the regex was not correct, lerna couldn't find the component locally to add, so it tried download from registry

**Comment by nchandran3** [comment]
@shanshanyang Can you give an example of what exactly your `lerna.json` `packages` array was before and what you changed it to? Along with your project hierarchy? If you have a commit id of the change you made on a public repo that would be even better. 

I'm hoping this might fix the issue I'm having as well with not being able to add local packages properly.

**Comment by shanshanyang** [comment]
@nchandran3 here is what i changed
old: `
"packages": [
    "src/components/",
    "src/projects/"
  ],
`
updated: `
"packages": [
    "src/components/**",
    "src/projects/**"
  ],
`

**Comment by nchandran3** [comment]
Unfortunately, changing the regex didn't work for me when adding a local *unpublished* package to another package. 

Even though running `npx lerna ls` does find the new package, running `npx lerna add` still attempts to find the new package in the registry for some reason and errors during the `npm install` step. 

When adding a package that has been previously published, it works fine (because it goes to the registry and pulls it down). In the case that it pulls from the registry, it creates a symlink as I would expect.

**Comment by revelt** [comment]
hi guys, if anybody needs a quick interim solution to link local monorepo dependencies, check out https://www.npmjs.com/package/lerna-link-dep — I made it for myself, it simply creates symlinks of the package you requested (also tackles CLI linking correctly, puts into `.bin`)

**Comment by marcushultman** [comment]
We had a similar issue when adding `local-package` (a new, unpublished package) to `some-other-package` dependencies. When using `npx lerna add local-package packages/some-other-package`, `local-package` also ended up in the root `package-lock.json` (where `some-other-package` is declared a dependency using `file:packages/some-other-package`)  causing the error message above.

| Package | version  |
|---|---|
| lerna | 3.16.4  |
| node | 12.1.0  |
| npm | 6.9.0  |


To work around it it, first run without bootstrapping: `npx lerna add --no-bootstrap local-package some-other-package`. Then convert the dependency to a `file:`-dependency using `npx lerna link convert`. Now you should be able to run `npx lerna bootstrap` without it going to the registry for the unpublished dependency.

Adding by relative path (`npx lerna add packages/local-package packages/some-other-package`) seem to not work at all. By reading source it seems like the AddCommand expects a `name` from the `spec`, which is not returned by `npm-package-arg` for file system local packages.

**Comment by atifsyedali** [comment]
This seems to work:

`lerna add @my-scope/dependencyPackageFrom packages/dependentPackageTo`

`From` is a scope, and `to` is a relative path to the package.

**Comment by madroneropaulo** [comment]
Still happens in 2020, any update?

**Comment by samrith-s** [comment]
Encountered the same issue. I have the follows:
```properties
# .npmrc in root
"@scope:registry"=<link-to-custom-registry>
```

```shell
lerna add @scope/theme-package packages/my-package
```

Though the `@scope/theme-package` is not present in the registry (it's a local package) Lerna tries to add it from the registry and I end up with this error:

```shell
Error: 403 Forbidden - GET <registry>/@scope%2ftheme-package
```

**Comment by NogaMan** [comment]
check if `@scope` you are using when running the command `lerna add @scope/some-lib packages/other-lib` is the `name` field in the root `package.json`

**Comment by danawoodman** [comment]
> Still happens in 2020, any update?

Still happens in 2021, any updates? 😅

**Comment by slavafomin** [comment]
> Still happens in 2021, any update?

We've switched to [Microsoft Rush](https://rushjs.io/) and it works great for us. It also looks much more mature and enables predictable releases via change files.

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
