### ISSUE TITLE
[Question] When is lerna appropriate for monorepo management?

### ISSUE THREAD

**Issue by lonix1** [lerna/lerna#2016]
Hi @evocateur...I'm trying out lerna. You mentioned in passing [here](https://github.com/lerna/lerna/issues/1079#issuecomment-421394973), [here](https://github.com/lerna/lerna/issues/1061#issuecomment-335653147), [here](https://github.com/lerna/lerna/issues/1321#issuecomment-375363739), [here](https://github.com/lerna/lerna/issues/1034#issuecomment-333588506) that there are cases where you don't recommend it.

Our use case is more general/common - our monorepo has an express server, angular client, and shared libraries (using `file:../shared` to link them). We use pnpm to avoid npm's  space/time waste.

I don't *publish* to npm... I don't even have an npm account. However I do *deploy* the `dist` directory to our VPS.

In this very common use case, is lerna overkill?

*(Not trolling you, lerna is really cool, I'm just unsure about this use case. The docs weren't clear.)*

**Comment by blieque** [comment]
I'm using for a collection of front-end applications and some common packages. We have a `packages/` directory and a `sites/` directory. The former contains common styling, common Vue components, utilities, etc. and the latter contains Vue applications. I think Lerna works well for this application. I would personally recommend categorising your packages (perhaps `clients`, `apis`, and `packages`), particularly if you foresee there being several more packages in the future. We also don;t currently publish packages, but I think Lerna is still worth it for the lack of multi-repository overhead, shared dependency versioning, and easy scripting (`lerna exec`).

**Comment by lonix1** [comment]
@blieque Thanks for the real-word advice! Seems we have similar use cases.

Setting up unit tests and integration tests is surprisingly hard in monorepos. Is it easy to configure lerna for testing? I gave up on nx (similar to lerna) because its testing config is horrible. (I'm using Jest and Cypress.)

**Comment by blieque** [comment]
I confess we've been pretty lax with testing and haven't really tried since pulling together the monorepo. We were using Jest before, though, particularly for testing utilities. What troubles are you running into?

**Comment by lonix1** [comment]
@blieque No the testing trouble was with nx (testing config is buggy and convoluted), which is why we're gonna swap that out for lerna.

Thanks for your comments, most lerna users seem to use it for OSS / npm-related work, so I needed some from-the-trenches advice for our use case... thanks!

**Comment by evocateur** [comment]
I think I've been pretty consistent on this, but if you're _never_ going to publish any of the packages, it really doesn't make sense to burden yourself with the extra complexity of Lerna. Just use relative paths, they're not evil. You only need one package.json in the root. Whatever you're bundling with is presumably smart enough to ignore dependencies that it doesn't need.

**Comment by evocateur** [comment]
> Setting up unit tests and integration tests is surprisingly hard in monorepos.

That is astonishingly the opposite, in my experience (Jest, eslint). Any test framework that makes it difficult isn't worth using, imo.

**Comment by lonix1** [comment]
@evocateur Actually configuring nx and jest is impossibly complex and buggy (at time of this writing). That's why I was investigating lerna.

**Comment by blieque** [comment]
We may well start to publish packages, but I get your point that Lerna isn't strictly required for a monorepo.
