### ISSUE TITLE
[Question] When publishing, why are git tags pushed before prepublish hook?

### ISSUE THREAD

**Issue by nickjanssen** [lerna/lerna#2018]
When I run `lerna publish`:

```
? Are you sure you want to publish these packages? Yes
lerna info execute Skipping GitHub releases
lerna info git Pushing tags...
```
However, my prepublish scripts run tests and they sometimes fail. But git tags are already pushed. Why is this behaviour? Should I put my testing elsewhere?

**Comment by FredyC** [comment]
Got burned by this several times as well. It's very painful to be reverting tags manually because one build script has failed. And it has to be done locally and remote 🙄 

Only, the workaround seems to be `lerna run prepublish` just to try out builds, but it's rather annoying.

In my opinion, any tagging should happen only after the packages are successfully in the NPM, not sooner.

**Comment by evocateur** [comment]
The two actions, `lerna version` and `lerna publish`, are atomic. Lerna 3.x `publish` _happens_ to automatically chain `lerna version` before it, if necessary; this will no longer be the case with Lerna 4.x. Just like `npm version` is a separate step, `lerna publish` will soon have _one_ responsibility: publishing the designated packages (either the currently tagged release, packages without matching versions in the registry, or nightly "canary" releases).

I would suggest gating your call to `lerna publish` with the tests, not relying on leaf node scripts. You should be running the test/build scripts from the root anyway.

> In my opinion, any tagging should happen only after the packages are successfully in the[registry], not sooner.

This doesn't match the requirements of `npm publish` itself, which is generally the experience I pattern `lerna publish` after. `npm publish` doesn't give a fig what the git status of the package contents are, or even _if_ it's a git repo. Lerna does, and there are multiple methods to recover after a failed publish that may or may not have been successfully tagged.

**Comment by FredyC** [comment]
> Lerna does, and there are multiple methods to recover after a failed publish that may or may not have been successfully tagged.


I would be really interested in those methods, I haven't found anything in the docs. Imagine 10 packages being published, one fails. Now you have to figure which are the tags that were made and manually remove them from local repo AND from remote as well. God forbid if you miss one and try to publish again, it fails a whole operation and you to do the same thing. Trust me, it's very tedious, done that several times in the last weeks.

Either way, looking forward to Lerna 4, that sounds like a step in the right direction with the ability to choose when the tagging (and push happens).

**Comment by FredyC** [comment]
@evocateur I am wondering if there some actual issue tracking Lerna 4? Or is it just a theoretical idea to do that version for now? :)

**Comment by evocateur** [comment]
> in case I want to publish one package manually for whatever reasons.

You should never do that. It's one tradeoff of being in a monorepo.

> I would be really interested in those methods, I haven't found anything in the docs. Imagine 10 packages being published, one fails.

[`npx lerna publish from-package --yes`](https://github.com/lerna/lerna/tree/master/commands/publish#bump-from-package)

There is no v4 milestone yet, but #1767 has a bunch of the high-level goals outlined.

**Comment by FredyC** [comment]
> You should never do that. It's one tradeoff of being in a monorepo.

Well, with `independent` version I don't see any harm in that. Thing it that Lerna that at one moment I changed package that others are depending on and Lerna wanted to release all those packages. So I had to bypass Lerna and release just that package. Really strange behavior.

**Comment by evocateur** [comment]
@FredyC #707, etc etc til the heat death of the universe

**Comment by nmccready** [comment]
> @FredyC #707, etc etc til the heat death of the universe

Can you please explain how exactly that issue marked above resolves this issue. This is seriously by far the worst caveat of lerna. 

I would prefer if it wouldn't push tags to the remote  a successful publish. That way if there is a failure it is easier to back out and is more consistent to how npm operates already.

**Comment by Robbie-Cook** [comment]
It's 2021 and this is still a problem. Damn.

**Comment by FredyC** [comment]
I stopped using Lerna a while ago, the https://github.com/atlassian/changesets/ is by far superior for package publishing in monorepo.

**Comment by Robbie-Cook** [comment]
Thanks @FredyC , I'll use that instead. I'm always behind the times. Thanks for keeping me up to date.
