### ISSUE TITLE
Is Lerna pushing packages to different repositories?

### ISSUE THREAD

**Issue by kuworking** [lerna/lerna#2026]
Sorry for the newbie question, but it seems I can't find the answer to this question. I have a monorepo with `Yarn workspaces` and  `Lerna`

```
/lerna.json
/package.json (with a github repo)
/packages/A
/packages/A/package.json (with a github repo)
/packages/B
/packages/B/package.json (with a github repo)
/packages/C
/packages/C/package.json (with a github repo)
/site
/site/package.json (with a github repo)
```

Then, my beliefs are that with `Lerna` I can develop the site and packages all together with ease, which is done with `Yarn workspaces`, and then `npm-publish`  packages `A`, `B` and `C` and `site` separately. I have been able to do this, but, here is what I don't understand:

Before publishing to `npm`, I expected Lerna to push the changes to each `github` repository, and to do it _without publishing_ with `lerna version`. 

But I cannot get this done. Then, is this supposed to work? can I `git push` changes of all packages to their respective repositories? Or this is precisely what is not being done in a monorepo?

If I want this, do I need to implement `subtrees` or something similar?

Cheers,

**Comment by kuworking** [comment]
At the end I have implemented this with subtree, my understanding is that Lerna has nothing to do with github or alternatives, it only pushes to npm. Thanks for the project :)

**Comment by TrejGun** [comment]
@kuworking can you please share your solution, because https://github.com/lerna/lerna/issues/161 was closed long ago

**Comment by evocateur** [comment]
Lerna does not support `git subtree`.
Lerna does not _depend_ on Github, just `git`.
Lerna does not "push" to npm, it publishes npm packages to the configured registry (npm's public registry by default).

**Comment by kuworking** [comment]
> @kuworking can you please share your solution, because #161 was closed long ago

I am just following this workflow:

```
- use lerna with --no-push to update the versions of the updated workspace packages / site
- git subtree split --prefix="folder of the package / site" -b "branch_name"
where I have the folder written for each case in the workspace `package.json`, and I read it a simple `const workspace_pjson = require('./package.json')`
- git checkout new_branch
- git tag "tag" (where I create the tag based on the version of each package  site)
- git push url_repo (from package.json) "tag"
- git push url_repo new_branch:master --force (I have a repo for all packages / site)
- git checkout master
- git branch --delete --force new_branch
```

and that's it, it works for me but sometimes it goes slow

**Comment by TrejGun** [comment]
@kuworking thanks

**Comment by kuworking** [comment]
@TrejGun I've just changed my implementation for a more understandable approach based on https://github.com/johno/actions-push-subdirectories/blob/master/entrypoint.sh and https://github.com/gatsbyjs/gatsby/blob/8933ca9b3bf2c9b4fd580dd437d8695c3be705b7/scripts/clone-and-validate.sh

It that's of interest for you

**Comment by TrejGun** [comment]
@kuworking thanks, i dont need this now but will keep in mind
