### ISSUE TITLE
Lerna dependencies from a nested package

### ISSUE THREAD

**Issue by btestjeremy** [lerna/lerna#2027]
I would like to do an architecture like sequelize did with `pg` and `mysql2` libraries [here][1] but with custom packages.

Then if I understand Lerna well, that should be the following architecture with Lerna

```
|_ packages
  |_ package1
    |_ commonpackage
  |_ package2
    |_ commonpackage
  |_ package3
    |_ commonpackage
  |_ core
  |_ full
    |_ core
    |_ package1
    |_ package2
    |_ package3
```

Basically, the `package1`, `package2` and `package3` can only be used with the `core` package but they are not mandatory (kind of a plugins architecture, you can load either one, two or all). This is a light weight package.

The `full` package contains all the others packages, this is a full package with everything with also the not necessary stuff for some cases.

Unfortunately, I'm getting an error on running the tests on the `full` package because the `core` package does not find (MODULE_NOT_FOUND) the `package1`, `package2` and `package3` and does not have them as a dependency (only added as peerDependencies into the `core` package).

How can I do that with Lerna please?

  [1]: https://github.com/sequelize/sequelize/blob/master/package.json#L76

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "1.0.0"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.9.0 |
| `node --version` | v11.13.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.14.4 |

**Comment by revelt** [comment]
What if you put them into one, single level structure? If a package is optional for let's say `core`, don't wire it up to be consumed there (don't put `import` etc). And on the opposite, put the references to those optional ones in `full` (`import`/`require` them). Because `commonpackage` could be bootstrapped to the top, `core` would not get anything and `full` would get Lerna-symlinked `core` and all `package1/2/3`.

What do you think?

**Comment by evocateur** [comment]
I don't understand what you're asking for. If you can do it with "normal" npm packages, you can probably do it with Lerna. [`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies) sounds like what you're looking for.
