### ISSUE TITLE
[Bug] Bootstrap breaks for scoped dependencies if called more than once

### ISSUE THREAD

**Issue by dbettini** [lerna/lerna#203]
Calling lerna bootstrap more than once when a package has scoped dependencies breaks with EEXIST error for some reason. It doesn't happen when manually calling npm install for a package with scoped dependencies.

Example: all [angular 2](https://github.com/angular/angular) packages are installed under the same @angular scope, which means they will be in the same folder. After calling lerna bootstrap again, it will say that @angular file already exists, and to move it away and try again.

[lerna-debug.log.txt](https://github.com/lerna/lerna/files/308035/lerna-debug.log.txt)

**Comment by thejameskyle** [comment]
This seems like an issue with npm to me
