### ISSUE TITLE
[Question] Injecting global config for all packages

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [lerna/lerna#2032]
I am trying to implement Lerna in a typescript project where we will be having ``tsconfig.json`` for compilation stage. Is there any way we can inject ``tsconifg.json`` globally so all files will pick up the same config instead of having many replications of the config file.

The example repo can be found [here](https://github.com/JayaKrishnaNamburu/lerna-basic-setup)

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "npmClientArgs": [
    "--no-lockfile"
  ],
  "version": "1.0.0",
  "useWorkspaces": true
}
```
</p></details>

**Comment by JayaKrishnaNamburu** [comment]
Closing this as we can achieve this by manually specific -p to tsc, but would like to know if there is a feature available.

**Comment by evocateur** [comment]
https://www.typescriptlang.org/docs/handbook/project-references.html
