### ISSUE TITLE
lernajs.io is down

### ISSUE THREAD

**Issue by adeolabadmus** [lerna/lerna#2033]
I can't reach the site at https://lernajs.io/. It looks like a DNS records issue. See screenshot below.

<img width="1252" alt="Screen Shot 2019-04-12 at 11 35 00 AM" src="https://user-images.githubusercontent.com/7715469/56027915-48e35600-5d17-11e9-9ce2-7eb166020676.png">

**Comment by rewathkafley** [comment]
I am also facing the same issue.

**Comment by TrungRueta** [comment]
i need read document but main site down and no way to find full document in other places. Please help !

**Comment by adeolabadmus** [comment]
Hey @evocateur!

Any ideas?

**Comment by ChristianMurphy** [comment]
In the mean time, there is a version available in the way back when time machine
https://web.archive.org/web/20190409184153/https://lernajs.io/

**Comment by icirellik** [comment]
How is this still down? I'm glad I only used this for a test project, definitely won't be recommending it for production usage... 😞

**Comment by evocateur** [comment]
It's still down because I'm on vacation, and I don't even own the domain. But go ahead and keep believing the stability of a volunteer-run marketing/documentation website has any bearing at all on the quality of the CLI.

**Comment by herman-rogers** [comment]
Is there a way we can help with this? Despite the above I quite like lerna and do suggest we use it in production. Would be nice to create a pathway where we can maintain this perhaps via the domains suggested in the referenced issue.

**Comment by evocateur** [comment]
This will be resolved as soon as https://github.com/js-org/js.org/pull/2967 is merged and the DNS propagates. https://lerna.js.org/ will be the new address. Big thanks to @ChristianMurphy for opening a very helpful PR!

**Comment by tommedema** [comment]
I'd setup a 302 redirect at https://lernajs.io/ (which is #1 on google)

**Comment by evocateur** [comment]
I don't own the .io domain, so `¯\_(ツ)_/¯`
