### ISSUE TITLE
create: toggle initial file generation

### ISSUE THREAD

**Issue by nicolaisueper** [lerna/lerna#2039]
Hello there! First of all: Thank you for this awesome tool! :heart: 

`lerna create` writes inital files (```README.md```) / folders (```__tests__, lib```) into newly created packages and I end up deleting them every time I use the command.
## Expected Behavior

It would be nice, if there was an option for toggling the behavior.
## Current Behavior

`lerna create` writes initial files and folders into created packages 
## Possible Solution
`lerna create` exposes a flag (like --minimal) which only creates files necessary for this package to work with lerna. I could imagine this may be just the package.json

## Context

I am using lerna to manage my pattern library based on storybook. I use lerna to bootstrap my component packages, so the default file structure does not meet my needs
## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.2 |
| `npm --version`  | 6.4.1 |
| `node --version` | 10.15.3 |

| OS | Version |
| --- | --- |
| Ubuntu | 18.10 |

**Comment by nicolaisueper** [comment]
Also, if you decide this to be realized, I'd love to work on this issue. :)

**Comment by evocateur** [comment]
Just like I mentioned in #1779, I don't think Lerna should be in the templating business anymore. Surely there are better tools for this sort of thing.
