### ISSUE TITLE
Can we prevent Lerna from changing the semver in package.json?

### ISSUE THREAD

**Issue by arikimolloy** [lerna/lerna#2040]
This is likely just how Lerna is, but I'm wondering if there is a way around this.

On publish, Lerna automatically changes dependency versions of sibling packages to point to the latest minor version, so it adds the caret (e.g. ^2.5.3). Is there a way to have it point to the latest patch version of sibling dependencies (e.g. ~2.5.3) instead?

**Comment by evocateur** [comment]
Currently the only customization available is `--exact` (no range prefix, i.e. `2.5.3`) and `^`. I don't really see a great benefit of `~`, as `^` has been the default for npm for several years now, and `~` is overly restrictive.

**Comment by arikimolloy** [comment]
@evocateur Thank you, I think this fix will work for us for now. Our use case is that we do patches on older releases, while Lerna is meant for only forward-fixes. So we need to be able to point to 2.5.x without it pulling down 2.6.x, because a team might want patches from 2.5.x but not anything from 2.6.x (we make breaking changes on minor versions sometimes, we don't follow semver unfortunately, and I know that Lerna is restrictive in this way (as it should be)).

**Comment by web-padawan** [comment]
Is there any chance for this issue to be reconsidered? Or should I create a new issue?
Using `~` is really important when maintaining multiple minor branches.

It's really disappointing that `savePrefix` is currently hardcoded and can't be configured:

https://github.com/lerna/lerna/blob/674ffd369cf446ca2d7c2811d882a5462c8bbfd7/commands/version/index.js#L103-L104
