### ISSUE TITLE
How to specify custom CHANGELOG.md file

### ISSUE THREAD

**Issue by kevinwolfcr** [lerna/lerna#2043]
Hello! I am using a fixed versioning strategy but I want to generate **only** 1 changelog. This is because I have a website in which I want to show the changelogs, rather than adding the `CHANGELOG.md` file to each package.

Is this possible?

**Comment by evocateur** [comment]
Not really, why would you need this? In fixed mode, the root `CHANGELOG.md` contains all of the changes from all leaf `CHANGELOG.md` files. The leaf packages have them because that is a standard pattern in npm packages to include a changelog in the published tarball.

**Comment by kevinwolfcr** [comment]
Because I have a website using MDX and I want to put the changelog into `./docs/src/pages/changelog.mdx`

**Comment by evocateur** [comment]
I don't really see this happening. There are plenty of tools available to generate your own changelogs during a lifecycle phase, Lerna isn't doing anything special.
