### ISSUE TITLE
Running a script with optional arguments and --no-bail

### ISSUE THREAD

**Issue by furstenheim-geoblink** [lerna/lerna#2044]
I have a lerna project. In some of the subprojects I have the following script defined in package json `"lint": "eslint ."`. 
From the parent directory I can run `yarn lerna run lint`, this runs lerna which in turn runs lint in every package. So far so good.
I can run as well `yarn lerna lint -- -- --fix` which effectively runs `lerna run lint -- --fix` which in turns means `eslint . --fix`, which is what I want.

However, I'm not able to execute the same command with no-bail. If I do
`yarn lerna run --no-bail lint -- -- --fix `, lerna complains of the following: `ERR! lerna Not enough non-option arguments: got 0, need at least 1
`
Yarn version 1.12.3
Lerna version 3.13.1

**Comment by evocateur** [comment]
Maybe just run it from the root? I really don't understand everyone's fascination with running lint/test scripts from every single leaf package directly.

`yarn lerna lint` isn't a command that lerna understands.

**Comment by furstenheim-geoblink** [comment]
I explained my self poorly. When I said "parent directory" I meant the root directory.
I don't understand your comment on `yarn lerna lint`. I'm executing `yarn lerna run lint` which runs lint in each leaf package, which is defined in corresponding package jsons

**Comment by evocateur** [comment]
> I can run as well `yarn lerna lint -- -- --fix` which effectively runs `lerna run lint -- --fix`

I'm just quoting you. It is extremely confusing.

Does it work if you pass `--no-bail` _after_ the `lint` positional argument?

**Comment by slorber** [comment]
Hey,

I'd be curious to have a solution.

I have the following script that works fine:

```
"tsc:watch": "lerna run --parallel --no-private tsc -- --watch"
```

`yarn tsc:watch` works fine and forward the --watch option appropriately to my packages

(tsc is a script of all my subpackages, that's why I use run instead of exec yarn tsc)

---

I tried things like:

```
yarn lerna run --parallel --no-private tsc --  --watch
```

And various other potential solutions involving quotes, double -- -- ..., none of them worked.

repo is https://github.com/facebook/docusaurus
