### ISSUE TITLE
npm outdated doesn't work

### ISSUE THREAD

**Issue by simoneb** [lerna/lerna#2048]
Running `npm outdated` or even `lerna exec npm outdated --scope {package}` in a package which references packages from the monorepo fails.

This has been brought up before in #1468 and #1501 but it still doesn't seem to work for me.

## Expected Behavior

I would expect npm to be able to tell me the outdated dependencies of a package even if it references packages in the monorepo.

## Current Behavior

```
$ lerna exec npm outdated --scope {package}
info cli using local version of lerna
lerna notice cli v3.13.1
lerna info filter [ '{package}' ]
lerna info Executing command in 1 package: "npm outdated"
npm ERR! code E404
npm ERR! 404 Not found : {other package in monorepo}
npm ERR! 404
npm ERR! 404  '{other package in monorepo}' is not in the npm registry.
```

## Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.3|
| `npm --version`  | 6.5.0 |
| `node --version` | v11.9.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Windows 10 | 1607 |

**Comment by evocateur** [comment]
This is, to some extent, completely dependent on _which_ version of npm you're using (try a more recent version?) and whether or not you use `lerna bootstrap --hoist`, local `file:` specifiers, or what.

**Comment by Waqqars987** [comment]
I am having a lerna package as a dependency in another lerna package (package "alpha"). Now when I run npm outdated command in package alpha, it fails with error given in this issue. My packages are hoisted. Is there any solution to this?

**Comment by fahslaj** [comment]
The recommendation for modern version of Lerna is to rely on the workspaces functionality of whichever package manager you are using. I would suggest checking out the [legacy package management](https://lerna.js.org/docs/legacy-package-management) page in the Lerna docs. 

Older versions of Lerna that don't support workspaces are no longer supported.
