### ISSUE TITLE
Question: How to bump all affected packages the same way with conventional-commits

### ISSUE THREAD

**Issue by kobiburnley** [lerna/lerna#2049]
Situation: Package "ui" (5.11.19) imports package "util" (5.10.9), a change is made to "util" package committed with "feat" prefix.
run `lerna version --conventional-commits`

## Expected Behavior
bump package "util" with a minor 5.10.9 => 5.11.0
bump package "ui" with a minor 5.11.19 => 5.12.0
(as if running `lerna version bump minor`)

## Current Behavior
bump package "util" with a minor 5.10.9 => 5.11.0
bump package "ui" with a **patch** 5.11.19 => 5.11.20

## Steps to Reproduce (for bugs)

1. Create a lerna repo with two packages ui and util
2. Put util as a dependency of ui
2. Make a `feat:` change on util
3. Run `lerna version --conventional-commits`

```json
{
  "packages": [
    "packages/ui",
    "packages/util"
  ]
}
```

## Context
After bumping `util` with minor, there should be a hotfix for `util` (i.e 5.10.9 => 5.10.10).
But this hotfix fails, because it will try to bump also `ui` (5.11.19 => 5.11.20), but 5.11.20 is already published.

**Comment by evocateur** [comment]
"hotfix" doesn't really make sense in most npm scenarios, "fix forward" is the preferred pattern.

Dependent bumps (#707 et al) with no direct changes of their own will always be semver `patch`. The logic is perhaps flawed, but in any case where a dependency is bumped by even a major, if _no_ changes were necessary in the dependent consumer, there's not really a strong argument imo about changing that.

**Comment by gwardwell** [comment]
In my case, I have a [Stencil](https://stenciljs.com/) component library as a package and an implementation of that library for React, which requires additional wrapping code to make React happy. The repo looks kinda like this:

```
|- packages
|  |- ui
|  |- ui-react
```

I want to allow independent versioning because `ui-react` may need changes to be more react friendly that `ui` will not need to reflect. I also want to use conventional commits.

Now here's my scenario. Let's say that I add a button to `ui`:

```
|- packages
|  |- ui
|  |  |- UiButton.tsx
|  |- ui-react
|  |  |- UiButton.tsx
``

When I release, I would end up with:

*   `ui@0.1.0`
*   `ui-react@0.0.1`

That's probably fine. But what if I completely refactor the `ui` button, with breaking changes. I wouldn't need to change anything for Rect to make it play nice, but I would end up with these versions when I publis:

*  `ui@1.0.0`
*  `ui-react@0.0.2`

That's a huge problem for the consumers of my `ui-react` library. What I would like to see if the version bumps types of the dependent packages _match_ the package they are dependent on.

As an alternative, what if conventional commits without `yes` could have a new option to change the versions? That way it could analyze the changes, make the recommendation, and I could override? That seems like a reasonable workaround.

```
$ npx lerna version

Changes:
 - ui-react: 0.0.1 => 0.0.2
 - @kds/ui: 0.1.0 => 1.0.0

? Are you sure you want to create these versions? (yncH)
```

In that example, selecting `c` (for "change") would run you through the manual versioning process, or ask how you would want to change each one. Maybe something like this:

```
? Select a new version for ui-react (currently 0.0.1, recommended 0.0.2) Major (1.0.0)
? Select a new version for ui (currently 0.1.0) Major (1.0.0)
```

**Comment by gwardwell** [comment]
What I'm suggesting as a workaround is kinda like running `lerna version` without `yes`, seeing the version resolution, choosing `n` (no), and then running `lerna version [version string]`. Example:

```
$ lerna version

Changes:
 - ui-react: 0.0.1 => 0.0.2
 - @kds/ui: 0.1.0 => 1.0.0

? Are you sure you want to create these versions? (ynH)

$ n
$ lerna version major

Changes:
 - ui-react: 0.0.1 => 1.0.0
 - @kds/ui: 0.1.0 => 1.0.0

? Are you sure you want to create these versions? (ynH)

$ y
```

**Comment by gwardwell** [comment]
Can this issue be reopened/reconsidered? I do think there's value here with packages that apply a thin compatibility on top of other packages within the monorepo. And there are major flaws in the workaround I identified above.
