### ISSUE TITLE
How *bootstrap root only* work when using local file dependence in the root?

### ISSUE THREAD

**Issue by zjffun** [lerna/lerna#2051]
Thank you for your hard work.

However when i add a local file dependence in my root repo, bootstrap root only triggered, so other packages' modules didn't install.

I find lerna is using this mode, but no relevant docs were found.

https://github.com/lerna/lerna/blob/86017d769bb83dfd1abb88f4cf560f73651ad494/commands/bootstrap/index.js#L199-L201

Pleased to PRs, but I need more infomation about this.

**Comment by evocateur** [comment]
If you want to use local `file:` specifiers, you should run [`lerna link convert`](https://github.com/lerna/lerna/blob/090e180ac084f84dd0c789c60a355a9cb0bc7c4e/commands/link/command.js#L20-L21) once. Then you no longer need to use `lerna bootstrap`, just `npm install` (or `npm ci`) in the root.

**Comment by remi-gelinas** [comment]
@evocateur If we convert local specifiers, should we be running `npm install` in each sub-package as well as the root when bootstrapping a project? Otherwise outlier packages won't be dealt with, if `lerna bootstrap` only deals with the root.

**Comment by 1010543618** [comment]
@remi-gelinas In my humble opinion When you run `npm install`, NPM will install **all** dependencies (every node in dependence tree) in current node_modules. If all packages in root dependence tree and use the same devDependencies, you needn't install them.

eg:
root's dependence are pkg1, pgk2
pkg1's dependence is foo(v2.0.0)
pgk2's dependence is foo(v1.0.0)

Run `npm install` in root folder, the node_modules folder will like

```
pkg1
pgk2
  node_modules 
    foo(v1.0.0)
foo(v2.0.0)
```

You can check `package-lock.json` file or using `npm ls` for more detail.

If you need install in respective folder, you can use `lerna exec npm install`. I used this, becaue my chaotic project has some packages in lerna.json but needn't add to root dependence, and each package has different devDependencies :c.

**Comment by zjffun** [comment]
@remi-gelinas I just read doc and evocateur's reply again and find I made some mistake before.

If all packages are in the root dependence tree and  runed `lerna link convert` bofore, you needn't install sub-packages.

**Comment by zjffun** [comment]
@evocateur Thanks for your patient answer. But I can't find a good palce in the document to add this. I modified the title so others can find it.

**Comment by evocateur** [comment]
@morgrimm No install necessary in leaf packages when using relative `file:` specifiers. Just `npm install`/`npm ci` in the root.

**Comment by Aqours** [comment]
@evocateur Sometimes we need install in leaf packages when using file: specifies. e.g: we want run command in topological graph

**Comment by ryancat** [comment]
@evocateur I use the file specifiers and encountered this issue #2083. Did you know anything about that?

Thanks for the hard work!
