### ISSUE TITLE
bootstrap: packages not found after bootstrapping

### ISSUE THREAD

**Issue by anshumanv** [lerna/lerna#2052]
Packages are not found even after bootstrapping

https://github.com/webpack/webpack-cli

## Expected Behavior
Packages should be available once symlinked.

## Current Behavior
After running lerna bootstrap, I tried using absolute import and ran into this issue
![image](https://user-images.githubusercontent.com/21009455/56558767-6046fc80-65bd-11e9-940c-6384aec283dd.png)

## Steps to Reproduce (for bugs)

1. lerna bootstrap
2. npm changed to absolute import by package
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.4.0",
  "packages": [
    "packages/*"
  ],
  "version": "0.1.5"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.12.3 |
| `node --version` | 10.15.3 |

| OS | Version |
| --- | --- |
| macOS Mojave  | 10.14.4 |

Please do lmk if I missed anything, thanks! 😄

**Comment by evocateur** [comment]
You shouldn't be using subpath imports like that, especially in a Typescript project (that is, the file `path-utils.js` does not exist in the leaf package directory).

Also, unclear why a test of a local file is using the absolute package name. That just doesn't make sense, even forgetting the Typescript detour.

**Comment by psachs21** [comment]
@evocateur just for clarification, what do you mean by not using subpath imports? I'm looking to introduce lerna into our major projects, and I frequently import files nested within our packages:

eg:

```jsx
import SomeComponent from "@company/lib/components/X";
```

Where the actual published package is `@company/lib`. Is it just because @webpack-cli is a monorepo in itself?

**Comment by evocateur** [comment]
1. A test file should import the file it is testing with a relative path.
2. Sub-path imports tightly couple the internal structure of your package (an implementation detail) to your public API. In most cases, those subpaths should be separate packages (Lerna makes this relatively easy).

**Comment by psachs21** [comment]
@evocateur I agree that it is not ideal, but it is also currently common practice, and it should be supported (perhaps with warnings) as a way to allow migration to lerna without large changes to the codebase.

**Comment by evocateur** [comment]
I'm not saying you _can't_ shoot yourself in the foot, I'm just saying there are better options when it comes to feet.

I _am_ saying that there is _no_ way Lerna can magically make this work for unbuilt modules (or modules that do wacky prepublish modifications to the package structure) when required locally by the full package name. Even _npm_ can't make this work for unbuilt/wacky packages. Lerna isn't magic, you should use relative imports for tests.
