### ISSUE TITLE
JSON output for `lerna publish`

### ISSUE THREAD

**Issue by azz** [lerna/lerna#2053]
## Expected Behavior
When I run `lerna publish`, I would like to get a machine-readable output alongside the regular logging.

## Current Behavior
There is no JSON output.

## Possible Solution
```sh
lerna publish --summary-file lerna-publish.json
```

This would write the following to `lerna-publish.json`:

```json
{
  "published": [
    { "name": "@scope/module-a", "version": "1.2.3", "tag": "latest" },
    { "name": "@scope/module-b", "version": "1.1.1", "tag": "latest" }
  ]
}
```

## Context

The use case for this file is to kick off deployments in CI pipelines that depend on the packages that were just published.

Here is the horrible bash script that I want to kill! :fire:

```bash
lerna publish | tee lerna-output.log

# Extract published packages from the output log
published_packages=$(grep -A 1000 'Successfully published' lerna-output.log \
  | grep -e '^ - @[a-z]\+/' \
  | sed 's/^ - //' \
  | sed 's/@\([0-9].*\)$/ \1/'
)

while read -r module_name version; do
  echo "Do something with ${module_name}@${version}."
done <<< "${published_packages}"
```

**Comment by azz** [comment]
After posting this issue I realised it's fairly straight forward to get this information from the git tags.

```sh
published_packages=$(git tag --points-at HEAD | sed -rn 's/^(@?[^@]*)@(.*)$/\1 \2/p')
while read -r module_name version; do
  echo "Do something with ${module_name}@${version}."
done <<< "${published_packages}"
```

**Comment by azz** [comment]
Closing this as I'm happy enough with reading git tags. Feel free to re-open if you think there's wider value.

**Comment by evocateur** [comment]
It's an interesting use-case, certainly. I think it might be more interesting in a pluggable infrastructure, or perhaps an [aliased](https://github.com/npm/rfcs/blob/latest/implemented/0001-package-aliases.md) private fork of `@lerna/publish`.

**Comment by alex-hall** [comment]
+1 for this change since there is (seemingly) no way to actually see what package got published after the fact. 

Our use-case is that we only want to kick off builds in CI based upon which packages needs to be re-deployed (same as above).

Wondering why not just pass the same flag (-p) you pass to lerna changed? Seems like if the format is useful in that case, why isn't it useful in this case? 

This is especially useful in the case wherein we have 10+ packages and don't want to necessarily build the world on every commit in dev-world. 

Pair: @johncouldbe

**Comment by creatyvtype** [comment]
+1 to this. Also for CI and updating comments in PRs, trying to get a result of publishing beta versions right now requires ugly code to reduce the output of `lerna publish` into something meaningful.

**Comment by amorscher** [comment]
Another workaround/approach is to use a postpublish script in npm to collect all needed information about the published package and then put it into a corresponding format. In my case this did the job. Here my script if someone is interested:

```
import fs from "fs";
import path from "path";
import cp from "child_process";
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const packageJson = JSON.parse(fs.readFileSync("./package.json", { encoding: "utf8" }));

const version = packageJson.version;
const packageName = packageJson.name;
const rootDir = path.resolve(__dirname, "..");
const projectFolder = process.cwd().replace(rootDir + "/", "");

var gitRevParse = cp.spawnSync("git", ["rev-parse", "HEAD"], { encoding: 'utf8' });
const currentCommitHash = gitRevParse.stdout.replace(/(\r\n|\n|\r)/gm, "");
const changeLogLink = `http://wathever/${currentCommitHash}/${projectFolder}/CHANGELOG.md`;

//write the information to file
const publishLogLocation = path.join(__dirname, "..", "publish-log");
fs.writeFileSync(path.join(publishLogLocation, `${packageName}.json`), JSON.stringify({ packageName, version, projectFolder, changeLogLink }));
 ```
