### ISSUE TITLE
publish --conventional-commits Changelog not committed

### ISSUE THREAD

**Issue by rjhilgefort** [lerna/lerna#2055]
`lerna publish --conventional-commits` works well, but doesn't fully commit everything- usually leaving a lingering changelog that I have to commit by hand after. It seems to commit some change logs but not all.

## Expected Behavior
Should commit all changelogs

## Current Behavior
Always leaves one changelog that I have to commit by hand (publishes others) 

## Steps to Reproduce (for bugs)
1. Make changes to a package and make sure lerna changed sees it
2. Make a conventional commit
3. `lerna publish --conventional-commits`
4. Observer there's a changelog hanging around after the operation completes

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "version": {
      "message": "chore(release): publish %s"
    },
    "publish": {
      "conventionalCommits": true
    }
  },
  "ignoreChanges": ["**/__fixtures__/**", "**/__tests__/**", "**/*.md"]
}
```
</p></details>

## Context
I'm just trying to automate publishing versions and changelogs

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.2 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | 1.15.2 |
| `node --version` | 10.15.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.14.4 |

**Comment by evocateur** [comment]
Are there any complicated/git-mutating lifecycle scripts that might be causing this? I've been dogfooding `--conventional-commits` in Lerna itself for over a year and never hit this (also in several private `--independent` monorepos, same story).

**Comment by rjhilgefort** [comment]
Not that I can think of, I have `commitlint` hooked up, but that's the only hook and I don't have any `pre*` npm scripts either. Can you clarify what you mean by git mutating? maybe it'll spark something. I am using commitizen through a `commit` script. So I go through this flow-

1. Make changes
1. `yarn commit`, go through commitizen things.
1. `commitlint` checks things for me.
1. `lerna changed` to see what changed (Not super relevant, but I do it)
1. `lerna publish --conventional-commits`
1. Things succeed but I have to commit the errand change log

**Comment by evocateur** [comment]
If `commitlint` is run in a `precommit` git hook, it's quite likely causing it to fail? You can pass `--no-commit-hooks` to disable these during Lerna's `git` operations.

**Comment by rjhilgefort** [comment]
I tried it with `--no-commit-hooks` and saw the same behavior. I'm not doing anything else outside the norm. Based on no one else having the issue, I'm sure it's something with my setup, but do you have any other debugging suggestions or work-arounds you can think of? Any additional help would be much appreciated.

**Comment by rjhilgefort** [comment]
After a bunch of tinkering, trial and error... I noticed that that a few or our changelog files were lowercase: `changelog.md` instead of `CHANGELOG.md`. Interestingly enough, it would put the change in that file, but not stage it to be committed I guess.

I renamed it to be uppercase and everything is working! Thanks for jumping in here so quickly and trying to help!

**Comment by rjhilgefort** [comment]
Not that I'm aware of. I just renamed all my `changelog.md` files.
