### ISSUE TITLE
command for batch rm dist-tag

### ISSUE THREAD

**Issue by LeeeeeeM** [lerna/lerna#2058]
**promotion**

Since i use `lerna version` and `lerna publish from-git --dist-tag next ` to publish packages to the `next` tag.

Now i need a command to remove my npm dist-tag in a batch.
such as `npx lerna revoke --dist-tag next`
instead of `cd packages/p1 && npm dist-tag rm next && cd packages/p2 && npm dist-tag rm next`

or is there any tutorial i can get?

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.4 |

**Comment by evocateur** [comment]
I have a one-liner in my snippets file that I run in these situations to "promote" `next` to `latest`:
```sh
npx lerna exec --stream --no-bail --concurrency 1 -- 'PKG_VERSION=$(npm v . dist-tags.next); [ -n "$PKG_VERSION" ] && ( npm dist-tag add ${LERNA_PACKAGE_NAME}@${PKG_VERSION} latest && npm dist-tag rm $LERNA_PACKAGE_NAME next ) || exit 0'
```

Spaced out:
```sh
npx lerna exec --stream --no-bail --concurrency 1 -- \
  'PKG_VERSION=$(npm v . dist-tags.next); \
  [ -n "$PKG_VERSION" ] && ( \
    npm dist-tag add ${LERNA_PACKAGE_NAME}@${PKG_VERSION} latest && \
    npm dist-tag rm $LERNA_PACKAGE_NAME next \
  ) || exit 0'
```
(not sure if that will run spaced out, but the one-liner definitely does)

Obviously this is less than ideal. Something like `npx lerna promote --dist-tag next` would be more ergonomic.

**Comment by LeeeeeeM** [comment]
thx a lot
