### ISSUE TITLE
[Discussion] lerna ecosystem

### ISSUE THREAD

**Issue by joscha** [lerna/lerna#206]
How would you feel about having
https://github.com/atlassian/cz-lerna-changelog (lerna-friendly https://github.com/commitizen/cz-conventional-changelog)
and 
https://github.com/atlassian/lerna-semantic-release (lerna-friendly https://github.com/semantic-release/semantic-release)
be part of the lerna organisation?

cc @jpnelson

**Comment by thejameskyle** [comment]
It would be nice to have other integrations. But with your examples I was hoping to find a way to support stuff like them in one project: https://github.com/lerna/lerna-changelog/issues/23

**Comment by joscha** [comment]
We'd be happy to create some integrations, however one thing why didn't look at lerna changelog is, it assumes github as your platform, which is not correct for us, as we are on bitbucket.

**Comment by thejameskyle** [comment]
>  as we are on bitbucket.

Well why can't Atlasssian switch to GitHub :trollface: 

Kidding, thats the sort of thing we want to abstract away.

**Comment by joscha** [comment]
:trollface: 😆  awesome, do you have a future in mind which integrates these three pieces of technology? If you do, maybe there is something I can work towards already?

**Comment by thejameskyle** [comment]
It's not that fleshed out, but the basic idea is to have some form of providers that asynchronously return data in a format that can be used by lerna-changelog to generate a changelog file.

**Comment by joscha** [comment]
and you would use the information of the files in the commit to find which components are affected by what or use something like conventional-changelog?

**Comment by jarrydfillmore** [comment]
Nice suggestion!

**Comment by hzoo** [comment]
@joscha the only related to github atm the is way we are getting labels and its just a ajax request and definetely can be substituted or removed in place of another place to tag commits (when the commit message itself, etc)

**Comment by jpnelson** [comment]
If `lerna-semantic-release` used / cooperated with `lerna-changelog`, would we be ok with contributing `lerna-semantic-release` back to the lerna ecosystem?

**Comment by thejameskyle** [comment]
If you want them to exist independently that would be fine, but I really would like to see you all collaborate on something that works for more people

**Comment by doug-wade** [comment]
@jpnelson now that we're a lerna monorepo ourselves, I feel like a merger would be significantly easier, and I'm in favor of it.

However, this issue is a discussion issue that hasn't seen any discussion in years, so I'm going to close it.
