### ISSUE TITLE
mix of npm and yarn projects

### ISSUE THREAD

**Issue by rhyek** [lerna/lerna#2068]
If I have a combination of projects some using yarn and others npm (all have their respective lock files). If I import them all to one lerna-managed monorepo, will `lerna bootstrap` do the right thing and respect the package manager used for each project?

Thank you.

**Comment by marsprince** [comment]
+1

**Comment by evocateur** [comment]
Nope, sorry. It's one or the other, at this point. I don't see it changing, in that regard, either. One of the tradeoffs of a monorepo.
