### ISSUE TITLE
cant install workspaces dependencies in npm mode

### ISSUE THREAD

**Issue by xxholly32** [lerna/lerna#2072]
## Expected Behavior

cant install workspaces dependencies in npm mode

## Current Behavior

it can only work when npmClient :"yarn"
## Possible Solution

the problem  is npm cant install workspaces dependencies, but [yarn can](https://www.yarnpkg.com/blog/2017/08/02/introducing-workspaces/), is any possible to install when running `lerna bootstrap` with npm node? or  have another solution ?

## Steps to Reproduce (for bugs)

demos:

[lerna-yarn-workspaces-example](https://github.com/Quramy/lerna-yarn-workspaces-example)

[my-repo](https://github.com/xx-helloworld/how-to-build-a-project)

**steps**:
+ change npmClient mode to npm
+ run `npm install` `lerna bootstrap`
+ fail at `npm run build`

```
Cannot find module '@quramy/x-core'.
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.1.0 |
| `yarn --version` | 1.13.0 |
| `node --version` | 10.5.0 |

| OS | Version |
| --- | --- |
| Windows 10 | 1607 |

**Comment by evocateur** [comment]
npm doesn't support workspaces yet. Yarn does. This isn't a Lerna problem.
