### ISSUE TITLE
How to install a sub-package of a forked lerna repository as a node dependency?

### ISSUE THREAD

**Issue by woodgear** [lerna/lerna#2074]
which could maybe not releate lerna.but i am curious how should do.
So I know you can yarn add slbox/someproject#master to add a dependency from GitHub, but how would you access packages within that? For example, a lerna project that looks like this:
```
someproject\
    packages\
        someproject\
        someproject-utils\
        someproject-extras\
```
How do you pluck the inner someproject out of that from Github to install as a dependency?

[orgin question](https://stackoverflow.com/questions/53094067/how-to-install-a-sub-package-of-a-forked-lerna-repository-as-a-node-dependency)

**Comment by LukeeeeBennett** [comment]
@woodgear If you want to fork, you can clone the github repo locally and remove the `.git` repo. You can use [`lerna import`](https://github.com/lerna/lerna/tree/master/commands/import) if you want to import the git history. You will likely have to use `--flatten`.

**Comment by evocateur** [comment]
Unless that fork publishes their changes to an available registry, there's no way to do this with an npm `git://` dependency at present. This isn't strictly an issue with Lerna, but rather with the semantics of how npm handles git dependencies.

**Comment by TimDaub** [comment]
So just to confirm, lerna breaks the `npm i github:username/repo` command? I think that's a bug and it should be fixed.

**Comment by thelinuxlich** [comment]
I was able to use https://gitpkg.vercel.app/ for this

**Comment by dmatora** [comment]
@thelinuxlich thank you very much!
you saved my day!

**Comment by thelinuxlich** [comment]
Glad to help @dmatora
