### ISSUE TITLE
How do you control the pace of updates with frequent updates

### ISSUE THREAD

**Issue by xxholly32** [lerna/lerna#2078]
when i no use lerna, i used to close a bug with a commit id .so developer can reinstall `npm i repo@commit` so problem solve.

but now , i need publish a tag when i close every issue.  i think it cant be right

## Expected Behavior

I want a solution to the problem of frequent version switching

## Current Behavior

 i need publish a tag when i close every issue. or the bug can`t be fixed

## Possible Solution

 :disappointed:

## Steps to Reproduce (for bugs)

same as top

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.0 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.13.0 |
| `node --version` | v10.15.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
`npm i repo@commit` is installing a git dependency. That's not the same thing as a package published by npm, which is what Lerna coordinates in a monorepo.

If you want packages to be available, you need to publish them. Perhaps in CI, though Lerna has its own problems in that area. I don't know what to tell you.

**Comment by xxholly32** [comment]
ty, @evocateur 

I publish each package as you said.  

but when monorepo need a tag, the other packages maybe unstable.  `lerna publish` doesn`t have an api to ignore the unstable repos. 

`--ignore-scripts` or `--ignore-prepublish` can help me to ignore them or just need an api ?

**Comment by evocateur** [comment]
No, those flags don't do what you need. It doesn't sound like you should be using a monorepo with that sort of strict ticketing requirement.

**Comment by xxholly32** [comment]
ok thank you.
