### ISSUE TITLE
Lerna run test hung up before last test case.  

### ISSUE THREAD

**Issue by Kshirodram** [lerna/lerna#2080]
## Expected Behavior

It should run all the command `npm run test` inside packages and should exist.

## Current Behavior
it is running the test cases upto second last and not exiting. Its stuck before executing last package.

<details><summary>lerna.json</summary><p>

```json
{
  "name": "mozart",
  "scripts": {
    "bootstrap": "lerna bootstrap",
    "clean": "lerna clean && rimraf ./packages/*/dist",
    "precommit": "lerna run lint && lerna run test"
  },
  "dependencies": {
    "husky": "^2.2.0",
    "lerna": "^3.13.2",
    "rimraf": "^2.6.3"
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.2 |
| `npm --version`  | 6.7.0 |
| `node --version` | 11.13.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
You should run linters and test frameworks from the root. They're more than capable, nowadays.

**Comment by revelt** [comment]
@Kshirodram please update, do you still experience this issue or have you fixed it since?
