### ISSUE TITLE
Log 404 error when add a local package

### ISSUE THREAD

**Issue by uni-zheng** [lerna/lerna#2086]
Log 404 error when add a local package

## Steps to Reproduce (for bugs)
`node`: v10.14.2
`npm`: v6.4.1
`lerna`: v3.13.4

I created two local package in packages folder, and ran `npm init` in those package.
There log 404 error when I run `lerna add A --scope=B`.

There is same issue #1953 . But it closed by it submitter.

**Comment by evocateur** [comment]
An isolated reproduction (or a failing test PR) would be very helpful.

**Comment by rpgeeganage** [comment]
Hi everyone,
Can I look into this?

**Comment by uni-zheng** [comment]
Hi @evocateur I'm very sorry that I was too busy to response late. I will try again to see if issue repeat. 

@rpgeeganage yes, please

**Comment by rpgeeganage** [comment]
@uni-zheng ,
It seems I can't reproduce it. :(
