### ISSUE TITLE
Uses incorrect version of dependency.

### ISSUE THREAD

**Issue by PhaninderAmphora** [lerna/lerna#2093]
Uses incorrect version of dependency.

Example:

packages/module-1 -> requires react-redux(^7.0.0), connected-react-router.
&nbsp;&nbsp;&nbsp;&nbsp; And connected-react-router has peer dependency-> react-redux(^6.0.0)

packages/module-2 -> requires graphql-voyager.
&nbsp;&nbsp;&nbsp;&nbsp; And graphql-voyager has dependency-> react-redux(^5.0.0)
          
After ```lerna bootstrap``` I see
```
node_modules/react-redux(^5.0.0)
node_modules/connected-react-router
packages/module-1/node_modules/react-redux(^7.0.0)
```

## Expected Behavior
```connected-react-router``` should use ```packages/module-1/node_modules/react-redux(^7.0.0)``` to run

## Current Behavior
When I run ```lerna run start --scope=module-1``` it fails due to ```connected-react-router``` using incompatible ```node_modules/react-redux(^5.0.0)``` instead of ```packages/module-1/node_modules/react-redux(^7.0.0)```

<summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent"
}

```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.4 |
| `yarn --version` | 1.15.2 |
| `node --version` | v10.15.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Mojave | 10.14.3 |

**Comment by evocateur** [comment]
You're using Yarn workspaces, so this isn't a Lerna bug.

(I _would_ recommend synchronizing the major version of `react-redux` that `module-1` depends on with `connected-react-router`'s peer, as-is you're technically violating the `peerDependencies` of the router dep)
