### ISSUE TITLE
[BUG] lerna exec doesn't execute command in all packages in 3.14.x

### ISSUE THREAD

**Issue by trxcllnt** [lerna/lerna#2094]
## Expected Behavior
```sh
lerna exec --include-filtered-dependencies --scope $pkg -- $cmd
```
`lerna exec` should run `$cmd` in `$pkg` and all monorepo packages which `$pkg` depends on.

## Current Behavior
After updating to 3.14.0 (also tried .1), `lerna exec` seems not to execute in all packages.

## Steps to Reproduce (for bugs)
We have a lerna + yarn workspaces mono-repo with scoped packages. Not all packages share the same scope prefix (e.g "@scope1/some-module", "@scope2/another-module").

This command should print the paths of all the mono-repo dependencies of $PKG:
```sh
npx lerna exec \
    --include-filtered-dependencies \
    --loglevel=silent --scope $PKG \
    -- echo \${PWD}
```

It seems like version 3.14.x is only visiting the packages under one package scope, e.g. all the modules whose package name starts with "@scope1/" but not the ones which have "@scope2/" or "@scope3/". Downgrading to 3.13.4 is a temporary solution.

<details><summary>lerna.json</summary><p>

```json
{
    "version": "2.12.0",
    "npmClient": "yarn",
    "skipGit": true,
    "useWorkspaces": true,
    "packages": [
        "modules/scope1/*",
        "modules/scope2/*",
        "modules/scope3/*",
        "modules/scope4/*"
    ]
}
```
</p></details>

## Context

We have a multistage docker-in-docker build that uses lerna to get the filtered dependencies list of various node services in order to build and ship just the subset of the mono repo the service depends on.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.14.1 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | 1.15.2 or 1.16.0 |
| `node --version` | v12.1.0 |

| OS | Version |
| --- | --- |
| Ubuntu | 18.04 |

**Comment by evocateur** [comment]
Does `npx lerna ls -la` match the expected number of packages? I'm having difficulty reproducing this, across several monorepos with scoped and unscoped siblings. It _shouldn't_ have anything to do with Yarn + `useWorkspaces: true`.

(Unless the `workspaces` / `workspaces.packages` field in the root package.json doesn't match lerna.json's `packages` list, which is _actually_ where your package globs are configured when `useWorkspaces` is `true`)

The scope of the dependencies shouldn't matter, the pattern passed in `--scope` is only used to select the initial list, which is then extended via the package graph relationships, not matching package names.

**Comment by trxcllnt** [comment]
@evocateur thanks for the comment about the mismatched entries, I hadn't even thought to check. git does indeed show a bad merge caused the two to diverge. The workspaces entry in package.json is correct, but not the lerna.json. Unclear if that's a new bug, but I'd be happy to open another issue if so.

**Comment by evocateur** [comment]
I could have sworn the root manifest `workspaces` config _always_ trumps lerna.json's `packages` list when `useWorkspaces` is enabled...
