### ISSUE TITLE
[Docs] `lerna` field in 3.x `lerna.json` 

### ISSUE THREAD

**Issue by piperchester** [lerna/lerna#2095]
Does the `lerna` field in `lerna.json` have any use in v3.x? I see it being using in 2.x, but don't see it called out in the [`lerna.json` link in the readme](https://github.com/lerna/lerna#lernajson). 

If so, happy to update but wanted to pose the question here first!

**Comment by evocateur** [comment]
Indeed, it does not! Perhaps a subsection on "Legacy Fields" is warranted?

#1122 ensured that Lerna 3+ always imports the locally-installed `lerna`, which made the check redundant.
#1225 removed references to it.

**Comment by piperchester** [comment]
Neat! Thanks for the context. I'll open a PR to clarify.

**Comment by piperchester** [comment]
Opened here: https://github.com/lerna/lerna/pull/2108

I tried to push a separate branch for a PR but didn't have permissions - is that because I'm not a collaborator or part of the org?

**Comment by evocateur** [comment]
You should be forking the repo into your own user, then pushing a branch up to your fork, not `lerna/lerna`.
