### ISSUE TITLE
Having a dedicated info command to print out the local environment information

### ISSUE THREAD

**Issue by jamesgeorge007** [lerna/lerna#2097]
I think it is good to have a dedicated `info` command which will print out the local environment information that proves to be useful while submitting bug reports.
## Proposed API
`lerna info`

```bash
Environment Info:

  System:
    OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
    CPU: (2) x64 Intel(R) Pentium(R) CPU G2020 @ 2.90GHz
  Binaries:
    Node: 8.11.4 - /usr/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.81
    Firefox: 65.0
```

I would be happy to work on this :clap:

**Comment by jamesgeorge007** [comment]
@jamiebuilds @evocateur Thoughts :thinking:

**Comment by evocateur** [comment]
I feel like there has to be an existing CLI package that fulfills this need? (If there isn't you should build it!) Perhaps we could employ the programmatic API of such a package to append this information to any `lerna-debug.log` dumps?

I'm not certain a top-level subcommand like `lerna info` is justified by this, however. (Lerna already has too many, tbh)

**Comment by jamesgeorge007** [comment]
@evocateur There is an already an available package for the purpose - [envinfo](https://www.npmjs.com/package/envinfo)

**Comment by jamesgeorge007** [comment]
I guess there is no harm in having yet another command for the respective purpose as most of the scaffolding tools out there comes shipped with.

**Comment by evocateur** [comment]
Sure, why not, `lerna info`. I figure these options would be sufficient for our needs:
```js
{
  System: ['OS', 'CPU'],
  Binaries: ['Node', 'Yarn', 'npm'],
  Utilities: ['Git'],
  npmPackages: ['lerna'],
}
```

**Comment by jamesgeorge007** [comment]
@evocateur As per what I see each and every command is available as an npm package.  How are we gonna implement this :thinking:

**Comment by evocateur** [comment]
Yes, the subcommands are separate packages under `./commands`. I would say the `list` subcommand is a good starting point, since all you're going to do is call `envinfo` and emit the result to `stdout` (`@lerna/output`).

**Comment by jamesgeorge007** [comment]
@evocateur Have a look at #2106 This is just an initial workaround. Kindly suggest the required changes (Especially writing unit tests).
