### ISSUE TITLE
publish fails on git add -- when a package is a git submodule

### ISSUE THREAD

**Issue by mjgchase** [lerna/lerna#2099]
## Expected Behavior
git add -- should not include git sub-modules 

## Current Behavior
git add -- fails with fatal : pathSpec...see more detail below

## Possible Solution
maybe exclude sub modules from git add command and run git submodule foreach --recursive git add .

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context
When running publish my private application packages in git submodules are getting version bumped , the application packages are git sub modules and the git add -- command fails as the package.json from the sub-module is included.

fatal: Pathspec 'packages/application/package.json' is in submodule 'packages/application'
## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.14.1 |
| `npm --version`  | 6.9 |
| `node --version` | 10.15.3 |

| OS | Version |
| --- | --- |
| Linux | Mint 19.1 |

**Comment by evocateur** [comment]
Lerna does not support git submodules, sorry.

**Comment by mjgchase** [comment]
> Lerna does not support git submodules, sorry.

So no chance of putting in a function to exclude them or handle them when adding through GIT upon publish? , you are building a development which co-exists along side git , seems strange you aren't willing or unable to handle that scenario?

**Comment by evocateur** [comment]
I am making the choice to say no, that is not worth the extra complexity. A git submodule does not make sense in a monorepo.

**Comment by dobromyslov** [comment]
@evocateur It's only partially correct for some people. And it does make sense in a monorepo for others. Please have a look at these links: 
* https://blog.nrwl.io/dev-workflow-using-git-submodules-and-yarn-workspaces-14fd06c07964
* https://github.com/nrwl/nx/issues/3843
* https://github.com/lerna/lerna/issues/2517
* https://github.com/lerna/lerna/issues/2719
* https://github.com/lerna/lerna/issues/2342

**Comment by tony** [comment]
> I am making the choice to say no, that is not worth the extra complexity. 

That's understood

> A git submodule does not make sense in a monorepo.

I have a private monorepo w/ public submodule packages. It's awesome.

Easy to modify in integrated liveserver, easy to publish.  I suppose I could choose to not use submodules - but then the overhead of pushing to GitHub is way too much.
