### ISSUE TITLE
conventional prerelease not generating a prerelease version

### ISSUE THREAD

**Issue by gustavo-depaula** [lerna/lerna#2100]
## Expected Behavior
one of these inputs:
```
lerna version --conventional-commits --conventional-prerelease
lerna version --conventional-commits --conventional-prerelease=@loggi/fake-package
lerna version --conventional-commits --conventional-prerelease=*
```
generating this output:
```
Changes:
 - @loggi/fake-package: 6.4.0 => 6.5.0-alpha.0
```

## Current Behavior
always generating this output:
```
Changes:
 - @loggi/fake-package: 6.4.0 => 6.5.0
```

## Possible Solution
* i'm using the cli wrong

<details><summary>lerna.json</summary><p>

```json
{
  "version": "6.4.0",
  "changelog": {
    "repo": "loggi/fake-ui",
    "cacheDir": ".changelog",
    "labels": {
      "PR: Breaking Change :boom:": ":boom: Breaking Change",
      "PR: New Feature :rocket:": ":rocket: New Feature",
      "PR: Bug Fix :bug:": ":bug: Bug Fix",
      "PR: Polish :nail_care:": ":nail_care: Polish",
      "PR: Docs :memo:": ":memo: Documentation",
      "PR: Internal :house:": ":house: Internal"
    }
  },
  "packages": ["apps/*", "components/", "libs/*", "targets/*"]
}

```
</p></details>

## Context
i'm trying to setup an automated prerelease setup (version & publish), but can't get the `version` command right.
```
lerna version prerelease --conventional-commits --conventional-prerelease
```
worked, but bumped a `patch` instead of following conventional commits and bumping a `minor`. (committed using `feat`)

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.4.1 |
| `node --version` |8.15.1 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
`lerna version --conventional-prerelease` was released in [v3.14.0](https://github.com/lerna/lerna/releases/tag/v3.14.0). You report `lerna --version` as 3.13.1, so...

```
npm rm -D lerna
npm i -D lerna@latest
```

**Comment by gustavo-depaula** [comment]
@evocateur thank you, it worked!!!

On another note, despite of #1654, major versions with conventional commits still cause a major version on unversioned packages:
![image](https://user-images.githubusercontent.com/732422/58259856-c5704800-7d4b-11e9-895f-3fff49ea6643.png)
is this a known issue? should i open a new issue?

**Comment by evocateur** [comment]
@gustavo-depaula Hrm, yes, that does seem unexpected. I'm not sure if it's already been reported.

**Comment by gustavo-depaula** [comment]
@evocateur should i open a new issue?
