### ISSUE TITLE
Lerna : create - handle the case when several packages directories are defined in lerna.json

### ISSUE THREAD

**Issue by 0gust1** [lerna/lerna#2102]
I have two packages directories in lerna.json :
````
{
    "packages": [
      "components/*",
      "design-tokens/**"
    ],
    "version": "independent"
}
````
## Expected Behavior
I would want to create a new package in the `design-tokens/` directory.

## Current Behavior
Using lerna create, the package keeps creating in `components/` directory.

## Possible Solution

Make some changes around https://github.com/lerna/lerna/blob/285bd7e9dbc2ead8a764e2e64fddb866f70fee86/commands/create/index.js#L59

## Steps to Reproduce (for bugs)

I tried : 
* `node_modules/.bin/lerna create icons ./design-tokens/`
* `node_modules/.bin/lerna create icons "design-tokens/icons"`
* `node_modules/.bin/lerna create icons "design-tokens/*"`
and some variants.

<details><summary>lerna.json</summary><p>

```json
{
    "packages": [
      "components/*",
      "design-tokens/**"
    ],
    "version": "independent"
}
```
</p></details>

## Context

I have two packages directories in lerna.json :
````
{
    "packages": [
      "components/*",
      "design-tokens/**"
    ],
    "version": "independent"
}
````
I would want to create a new package in the `design-tokens/` directory using the `lerna create` command.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.14.1 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | VERSION |
| `node --version` | v10.15.3 |

**Comment by evocateur** [comment]
Yeah, the check is pretty cheesy right now. `npx lerna create <pkg> design-tokens` should work, in your case. (I've used it several times in lerna's own monorepo with that pattern)

**Comment by 0gust1** [comment]
Ok, thanks ! The command works. 
I suppose you can close the issue, sorry for the noise.

**Comment by evocateur** [comment]
I think we can do better, though! I would love to see a PR with improvements in this area, I would expect the patterns you tried to work.

**Comment by jacobuid** [comment]
+1
