### ISSUE TITLE
Elegant Deployment Solution

### ISSUE THREAD

**Issue by j** [lerna/lerna#2103]
I saw the new commit regarding deployment in the docs, but I wanted to chime in and explain how we're currently using Lerna for private-only packages and also deploying using Lerna.  Perhaps instead of just saying this isn't a deploy tool, to aid users into the best way to use Lerna to develop private mono-repo packages and deploy them since that's 99% of what we really do.

I can, if interested, write up and/or create an example repository when I have time to demonstrate how we do this, but for now, I'll just simply explain the steps we use that feel the best at the moment.  For the sake of faster deployment, we don't even bump package versions.  We leave them at 1.0.0 and publish to a private clean Verdaccio registry in CI.

Steps (old, and sort of copy pasted from CI, can be updated):
```sh
yarn global add verdaccio@4.0.0-alpha.7 verdaccio-memory@2.0.0
npm config set registry http://localhost:4873
yarn config set registry http://localhost:4873
verdaccio --config verdaccio.yml
yarn install
yarn clean
yarn build
lerna publish from-package --registry http://localhost:4873 --yes
```

The above publishes everything onto the local Verdaccio.

The next thing to do is that each deployable service creates a `dist` folder with it's package.json and built files.  i.e. `mkdir dist && copyfiles package.json .env* dist && cp -Rf lib/ dist/lib/`, then install them, `cd dist && yarn install --registry http://localhost:4873 --production --skip-integrity-check`, and the `dist/` folders are ready to deploy!

We're doing this right now with a `packages` and `services` and a root sam.yml.  CircleCI builds & deploys.  So far it's deployed without failure and doesn't feel like a hack and we don't need to worry about NPM publishing.

**Comment by evocateur** [comment]
Lerna isn't deploying the code in your example, it's just publishing the packages to a (temporary?) private registry instance. Then your build is (presumably) creating an archive of the `dist` after the packages are installed, etc. The _actual_ deployment is shipping that tarball to a server somewhere and extracting it. Lerna has nothing to do with that step, and it is not intended to do so.

**Comment by j** [comment]
That's where the SAM comment came in as well as me offering to get more in depth to help the 100s of people who use Lerna and wish to have better deployables.  SAM / CloudFormation creates zips of my dist/ folders based on my configuration.  You could BYO service to deploy to using the method I mentioned above.  Not a single word in what I typed above claimed that Lerna has anything to do with "that step".  I'm offering a solution for people who give up on your project in their organization because you tell them that this isn't for them when mono-repositories fit quite nicely.

I commented with the intention of helping people who give up on Lerna mono-repositories being used in private organizations due to your lack of wanting to help aid them in a proper direction.
