### ISSUE TITLE
Unknown command "init"

### ISSUE THREAD

**Issue by toastman** [lerna/lerna#211]
There is a problem with "getting started" tutorial.  
I installed lerna globally (lerna@1.1.3)    
When i run `git init lerna-repo && cd lerna-repo && lerna init` i get `Unknown command "init"` in CLI. 

Tech details:
 * `node v6.2.0`   
 * `npm 3.8.9`  
 * `OSX`

**Comment by toastman** [comment]
Sorry, my bad

I just miss that "init" should be used only from v2.0.0 

Everything works as expected ))

**Comment by hzoo** [comment]
Sorry, the readme/website is updated now (and yeah right now `npm install` installs the latest tag which is still `1.1.3`

**Comment by toastman** [comment]
Thanks, 

i just started reading/learning about `lerna` and it will be great to have some examples/tutorials because from the docs i can't really understand how to use it properly (

**Comment by hzoo** [comment]
Yeah we're planning on writing a workflows/usage doc somewhere - https://github.com/lerna/lerna/issues/102. https://github.com/lerna/lerna#what-can-lerna-do the basics are: setup with `lerna init`, `lerna bootstrap`, and then `lerna publish` when necessary
