### ISSUE TITLE
'lerna publish | version' fails to identify changes correctly, not bump version or taging, fail on commit

### ISSUE THREAD

**Issue by Padamieo** [lerna/lerna#2111]
Currently unable to publish changes to three of my six packages, when running publish | version, where my colleague working on iOS has been able to publish, my other lerna repositories are unaffected, leading me to believe this is a configuration that is not supported by lerna somehow.
Lack of error information has made this difficult to debug.

## Expected Behavior
Expecting the recent package changes to be noticed, guided by the command line GUI (graphical user interface) into bumping / updating versions of packages. Resulting in tags, package.json being updated and being committed to both git and npm.

## Current Behavior
An error is thrown at the git commit stage, this error is correct as far as i can see as nothing on the system has been changed no tag has been added, no package.json version changed. Resulting in a `nothing to commit, working tree clean` error-ing correctly.

The lerna-commit.txt looks pretty standard. But have included in anyway.
<details><summary>lerna-commit.txt</summary><p>

```json
Publish

 - @playtwo/cli@0.1.1-alpha.2
 - @playtwo/core@0.1.1-alpha.3
 - @playtwo/mock-core@0.1.1-alpha.3
 - @playtwo/platform@0.1.1-alpha.3
 - @playtwo/public@0.1.0-alpha.2
 - @playtwo/restricted@0.1.1-alpha.3
```
</p></details>

## Possible Solution
It maybe that i need to supply an additional command when running publish to allow my setup to work, however i have not found what that would be yet. Things i have experimented with and found that may bring clarify to the source of the problem are as follows.

1. Initially I managed to get one repository to publish by running `lerna publish from-package` this now results in the following.
```
lerna info versioning independent
lerna notice from-package No unpublished release found
lerna success No changed packages to publish
```
2. All bar the one I manged to committed by myself with the command used above do not have a gitHead addition to the package.json, this is common on my other repository. I presumed this is the standard operation of lerna.

3. I have noticed that when attempting to run `lerna publish --canary` it selects a single packages (which does contains changes needing publishing), attempts to publish, fails on uncommitted changes to the package.json but has not added tags. It has appended the sha as expected.

4. running `lerna version --no-push` results in no error or change and logically no push. `lerna updated` flags :  Assuming all packages changed.

5. I am able to manually tag, publish each package without issue and have had to do so now.

## Possible problems
1. our top level package.json is `"private": true,`
2. possible git / npm access issue
3. husky hooks runs : "pre-commit": "pretty-quick --staged"
4. the -alpha part of the version (prerelease format) is the source of the error?

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
35 error Error: Command failed: git commit -F C:\Users\Adam\AppData\Local\Temp\37c09c06-edb3-4440-b23e-7f7db8b76214\lerna-commit.txt
35 error husky > pre-commit (node v8.12.0)
35 error 🔍  Finding changed files since git revision 61d2297.
35 error 🎯  Found 0 changed files.
35 error ✅  Everything is awesome!
35 error On branch development
35 error Your branch is up to date with 'origin/development'.
35 error
35 error nothing to commit, working tree clean
35 error
35 error     at makeError (C:\Users\Adam\playtwo-client-sdk\node_modules\execa\index.js:174:9)
35 error     at Promise.all.then.arr (C:\Users\Adam\playtwo-client-sdk\node_modules\execa\index.js:278:16)
35 error     at <anonymous>

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.14.1 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.16.0 |
| `node --version` | 8.12.0 |
| `git --version` | 2.16.0.windows.2 |

| OS | Version |
| --- | --- |
| Windows 10 | 1803 |

**Comment by evocateur** [comment]
Your `lerna-debug.log` seems to indicate a pre-commit hook is running, possibly mangling/destroying the current git state, or returning a bad exit code somewhere. If you pass `--no-commit-hooks` to either command, does it succeed?

**Comment by JamesHenry** [comment]
Hi Folks,

Based on the thumbs up reaction, it looks like this one got resolved so closing.

Many thanks!
