### ISSUE TITLE
[Feature] Allow custom publish subdirectory

### ISSUE THREAD

**Issue by aleclarson** [lerna/lerna#2113]
Related: #91 #901 #1282 #1817

I'm setting up `react-spring` to use Lerna, and I want `lerna publish` to use `npm publish ./dist` instead of `npm publish ./`, but Lerna's maintainers have declined such a feature request in the past.

For each package in `packages/` directory, there exists a stub `package.json` with only a little bit of metadata. The rest of the metadata is copied from the root `package.json` using a custom build script. I want the published contents to be excluded from source control (via `.gitignore`), so I don't want to mutate the stub `package.json` before publish. I *could* use the `prepublish` and `postpublish` scripts, but that can interfere with uncommitted changes and I need to keep the published contents around for local development.

One workaround is to put my package stubs in the `.packages/` directory, but I'd like to avoid that, because some platform-specific code *will* exist in these package stubs, and I want that code to be easily discoverable by contributors. It's better to put the package stubs in `packages/` since that's the "standard" for mono repos.

LMK if you have any questions. 👍

**Comment by aleclarson** [comment]
> Especially nowadays with ES module exports and whatnot combined with tree-shaking module bundlers, there’s really no fundamental _necessity_ for false-basedir publishing. https://github.com/lerna/lerna/issues/901#issuecomment-350423290

@evocateu It's a useful feature for cross-platform libraries, I think. Tree-shaking can't solve the issue of platform differences in TypeScript definitions, for example.

**Comment by aleclarson** [comment]
Ah, I just noticed the `--contents` flag for the `publish` command.

https://github.com/lerna/lerna/tree/master/commands/publish#--contents-dir

**Comment by aleclarson** [comment]
@evocateur It looks like Lerna doesn't use the `package.json` in the `--contents` directory. Should that be fixed?

**Comment by evocateur** [comment]
> Tree-shaking can't solve the issue of platform differences in TypeScript definitions

That sounds like a TypeScript problem, not a Lerna problem.

**Comment by evocateur** [comment]
Also, I think I have a true fix for the underlying issue.

**Comment by aleclarson** [comment]
Which issue exactly? I've had so many while setting up this monorepo (not all Lerna related). 😅 

Anyway, the monorepo is up and running now. Note: It's still using `patch-package` for Lerna.
See here: https://github.com/react-spring/react-spring/tree/v9

**Comment by evocateur** [comment]
Specifically, not using the subdirectory package.json when publishing. I'm also adding the ability to configure `--contents` per-leaf via `pkg.publishConfig.directory` (inspired by #2109).

**Comment by aleclarson** [comment]
> Specifically, not using the subdirectory package.json when publishing.

Perfect, thanks for the help!

> I'm also adding the ability to configure `--contents` per-leaf via `pkg.publishConfig.directory` (inspired by #2109).

Nice I was just needing that!

**Comment by evocateur** [comment]
Published [v3.14.2](https://github.com/lerna/lerna/releases/tag/v3.14.2) with these changes

**Comment by aleclarson** [comment]
The `getUnpublishedPackages` function doesn't respect `pkg.publishConfig.directory` when looking for non-private packages.

**Comment by aleclarson** [comment]
The `getUnpublishedPackages` function doesn't respect `pkg.publishConfig.directory` while filtering out private packages.

**Comment by evocateur** [comment]
When `getUnpublishedPackages` is called, no package (or root) lifecycle has been called yet, so I wouldn't generally expect the `--contents` directory to even _exist_ yet. I'm not inclined to accept the PR, or even fix it by other means?

Why can't you configure `pkg.publishConfig.directory` in the "real" leaf package.json? In the repo you linked to, all the leaves have `"private": true` set for no apparent reason?

**Comment by aleclarson** [comment]
> Why can't you configure `pkg.publishConfig.directory` in the "real" leaf package.json?

Huh? Lerna needs `pkg.publishConfig.directory` in `packages/*/package.json` to know where the published `package.json` is located. How else would it know to publish `packages/*/dist/package.json` instead?

> In the repo you linked to, all the leaves have `"private": true` set for no apparent reason?

Making the leaves private prevents anyone from naïvely running `npm publish` in `packages/*` instead of `packages/*/dist`.

**Comment by evocateur** [comment]
I guess I'm saying: remove the `"private": true` from your leaves, and it will work just fine. Document why your contributors _shouldn't_ run `npm publish` in the leaf directories, and assume anyone that has publish access isn't a complete knob.

**Comment by aleclarson** [comment]
Mistakes happen, but fair enough. ;)

**Comment by evocateur** [comment]
Mistakes happen indeed, but package publishing is among the easier mistakes to rectify once discovered. :)
