### ISSUE TITLE
Browserify Issue

### ISSUE THREAD

**Issue by reggi** [lerna/lerna#212]
I have a module `/packages/alpha` that uses a module `knex` and `/packages/beta` uses `/packages/alpha` and when I build `/packages/alpha` with browserify I’m getting an related to `knex`. I’m not sure how this works on the browserify side of things, but in the `knex` `package.json` it states `browser` and an object of all the modules that should be ignored / shimmed.

Could `lerna` be disrupting this? Because `lerna bootstrap` doesn’t pull in all of `package.json` right?

[Here's the `knex` `package.json](https://github.com/tgriesser/knex/blob/e3ea261cd167277354737408fdd5426bbce65776/package.json#L84-L98).

I hate symlinks but here's on idea. `lerna` could symlink the sibling-package's `packages.json` and and create the mocked stub given whatever `main` is set to. So if it’s `./lib/index.js` we create the `lib` and stubbed `index.js` file like we currently have.

We need a way one can update their sibling `package.json` and have the change permeate through to other siblings using that module.

**Comment by nolanlawson** [comment]
Related: https://github.com/tgriesser/knex/issues/809

**Comment by nolanlawson** [comment]
I think this is actually a bug in `knex`. Now that I look more closely at their `package.json`, `sqlite3` is a `devDependency` rather than a `dependency`. It ought to be a `dependency` or `optionalDependency`.

**Comment by reggi** [comment]
@nolanlawson I'm not sure I agree. 

From the [knex docs](http://knexjs.org/)

> The primary target environment for Knex is Node.js, you will need to install the knex library, and then install the appropriate database library: pg for PostgreSQL, mysql for MySQL or MariaDB, or sqlite3 for SQLite3.

```
$ npm install knex --save

# Then add one of the following (adding a --save) flag:
$ npm install pg
$ npm install sqlite3
$ npm install mysql
$ npm install mysql2
$ npm install mariasqlas 
$ npm install strong-oracle
$ npm install oracle
```

So it makes sense that they aren't `dependencies`, and if they are used for testing it make sense that they are `devDependencies`.

Not sure how adding it to `optionalDependencies` or removing it to `dependencies` will still get `bootstrap` to realize that because I used `lerna` to install the package I need another way for it to know what modules are being shimmed.

**Comment by reggi** [comment]
Gah! I don't know whats happening! 

I just added `browser` to the bootstrap process and realized that my package doesn't have any `browser` explicitly in it.

https://github.com/lerna/lerna/blob/master/src/commands/BootstrapCommand.js#L77-L82

I really don't don't understand how `browserify` looks for `browser`. Or what's actually going on here.

**Comment by nolanlawson** [comment]
Hmmm, try putting `"browser": {"sqlite3": false}` in your`package.json`?

**Comment by nolanlawson** [comment]
Also see https://github.com/defunctzombie/package-browser-field-spec

**Comment by thejameskyle** [comment]
I'm not able to follow what is happening here

**Comment by reggi** [comment]
@thejameskyle I do think `lerna` will need to support the `browser` prop, and it's a simple add. It's not actually just not what I need right now. I'm gonna close this issue because it is confusing.

**Comment by nolanlawson** [comment]
@reggi Lerna doesn't have anything to do with the `browser` field; it just runs `npm install` for all your packages. This sounds like it might be a postinstall/prepublish issue.

**Comment by reggi** [comment]
@nolanlawson you could be totally right.

The only reason I believe it does deal with the browser field because it stubbs `package.json`. So if one of your sibling packages uses browser it wont be imported when using `lerna bootstrap`. It generates a fake `package.json` without any of your custom props.

<img width="671" alt="screen shot 2016-06-13 at 12 02 14 am" src="https://cloud.githubusercontent.com/assets/296798/15996819/38f9052e-30fa-11e6-8232-0162fded77a4.png">

**Comment by nolanlawson** [comment]
Right, but that stub project just contains an index.js that points back to the original project. So it shouldn't matter (I believe)
