### ISSUE TITLE
Lerna publish - GitHub API rate limit exceeded

### ISSUE THREAD

**Issue by forforeach** [lerna/lerna#2122]
I'm getting the **API rate limit exceeded for user xxxxxx** from GitHub when running `publish` command during my CD flow on TeamCity. The command that I'm running is:

`npx lerna publish --conventional-commits --github-release --yes`

## Expected Behavior
Run publish using conventional commits, create GitHub release and update CHANGELOG files. 

## Current Behavior
The command fails with 
```
info git Pushing tags...
info github Creating GitHub releases...
ERR! HttpError: API rate limit exceeded for user ID xxxxxxx.
ERR!     at response.text.then.message (~/node_modules/@octokit/request/dist-node/index.js:85:23)
ERR! HttpError: API rate limit exceeded for user ID xxxxxxx.
ERR!     at response.text.then.message (~/node_modules/@octokit/request/dist-node/index.js:85:23)
ERR! lerna API rate limit exceeded for user ID xxxxxxx.
{ Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (~/node_modules/@octokit/request-error/dist-node/index.js:29:17)
    at Array.globalOptions.usage.demandCommand.recommendCommands.strict.fail (~/node_modules/@lerna/cli/index.js:40:23)
    at Object.fail (~/node_modules/yargs/lib/usage.js:40:17)
    at handlerResult.then (~/node_modules/yargs/lib/command.js:242:47)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'Deprecation' }
Process exited with code 147
```

## Possible Solution
In a code of `version` command, there is a [`map`](https://github.com/lerna/lerna/blob/master/commands/version/index.js#L663) loop that iterates over release notes for all changed packages and sends [`createRelease`](https://github.com/lerna/lerna/blob/94fed6097c0d7a56e2632a247f0d853a0b381987/commands/version/index.js#L673) requests. Those requests are concurrent and may cause an `abuse rate limiting` as stated here -> https://octokit.github.io/rest.js/#octokit-routes-repos-create-release. 
Following GitHub API best practices:
> If you're making a large number of POST, PATCH, PUT, or DELETE requests for a single user or client ID, wait at least one second between each request.

Ref: https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits

So maybe the solution is to add a throttling

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "command": {
    "version": {
      "message": "chore(release): [skip ci] publish new versions"
    }
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.14.1 |
| `npm --version`  | 6.2.0 |
| `node --version` | 10.9.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Ubuntu | 16 |

**Comment by XBeg9** [comment]
Any suggestions/ideas how to solve this issue? We are not getting GitHub git tags (limit by 3 per query).

**Comment by artemv** [comment]
I'm not sure how to implement it in Lerna, but in my case (6 packages in a monorepo sometimes publishing together in one push) I worked around it by switching off commenting on issues and pull requests with [this config](https://github.com/artemv/simple-semantic-config/blob/master/index.js#L35) by semantic-release' Github plugin.
