### ISSUE TITLE
Feature Request: Add option to run npm audit fix in bootstrap command

### ISSUE THREAD

**Issue by evenstensberg** [lerna/lerna#2124]
## Expected Behavior

Right now, I've tried to make lerna bootstrap run `npm audit fix` for the monorepo packages with no luck. I'd like to run lerna bootstrap to fix any sec vulnerabilities for the packages in the monorepo

## Current Behavior

Doesn't provide `npm audit fix` support as lerna only is concerning flags passed, not commands.

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. Clone webpack-cli
2. Run lerna bootstrap
3. Try to run it with the `--` override

## Context
Improving project-wide security without having to navigate to each package and manually running `npm audit fix`

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.14.1 |
| `npm --version`  | 6.9 |
| `node --version` | 11.4 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.5 |

**Comment by mchelen** [comment]
how about `lerna exec npm audit fix` ?

**Comment by k3n** [comment]
@mchelen NPM doesn't like that approach and throws `ELOCKVERIFY` in many of my packages complaining about "Errors were found in your package-lock.json, run  npm install  to fix them" and then listing symlinked packages. As such it doesn't complete the audit actions.

**Comment by agorovyi** [comment]
I'm experiencing the same issue when trying to run `npm audit` within packages that have symlinked dependencies that don't exist in `package-lock` file.

Have anyone had any workarounds on how to audit packages without running `npm install` in them?

**Comment by svettwer** [comment]
Hiho! Maybe this helps you out until lerna provides an audit option itself.
https://www.npmjs.com/package/lerna-audit

BR
Sven

**Comment by mesqueeb** [comment]
Also related:
https://github.com/lerna/lerna/issues/1663

This feature should be very high priority security wise!

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
