### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by mozgbrasil** [lerna/lerna#2127]
## Expected Behavior

    Hello Brother

    I would like to ignore some projects when executing the command `lerna bootstrap`

## Current Behavior

    Hello Brother

    I'm using the model lerna.json

    But the error is being returned

    When you remove the

    "ignore": "component- *",

    Works as expected

## Steps to Reproduce (for bugs)

    $ lerna ls
    lerna notice cli v3.14.1
    component-casper-magento
    @mozg/crawler-prices
    hackathon-casperjs
    @mozg/magento-base
    @mozg/nodejs-base
    @mozg/reactjs-workers
    isomorphic-jwt-login
    lerna success found 7 packages

    $ lerna bootstrap
    lerna notice cli v3.14.1
    lerna notice filter excluding "component-*"
    lerna info filter [ '!component-*' ]
    lerna ERR! TypeError: Cannot read property 'split' of undefined
    lerna ERR!     at Minimatch.match (/home/marcio/.nvm/versions/node/v12.1.0/lib/node_modules/lerna/node_modules/minimatch/minimatch.js:717:9)
    lerna ERR!     at /home/marcio/.nvm/versions/node/v12.1.0/lib/node_modules/lerna/node_modules/minimatch/minimatch.js:691:15
    lerna ERR!     at Array.filter (<anonymous>)
    lerna ERR!     at Function.minimatch.match (/home/marcio/.nvm/versions/node/v12.1.0/lib/node_modules/lerna/node_modules/minimatch/minimatch.js:690:15)
    lerna ERR!     at /home/marcio/.nvm/versions/node/v12.1.0/lib/node_modules/lerna/node_modules/multimatch/index.js:25:33
    lerna ERR!     at Array.reduce (<anonymous>)
    lerna ERR!     at module.exports (/home/marcio/.nvm/versions/node/v12.1.0/lib/node_modules/lerna/node_modules/multimatch/index.js:17:18)
    lerna ERR!     at filterPackages (/home/marcio/.nvm/versions/node/v12.1.0/lib/node_modules/lerna/node_modules/@lerna/filter-packages/filter-packages.js:44:28)
    lerna ERR! lerna Cannot read property 'split' of undefined

    $ cat lerna.json
    {
      "version": "1.1.3",
      "npmClient": "yarn",
      "command": {
        "publish": {
          "ignoreChanges": ["ignored-file", "*.md"],
          "message": "chore(release): publish"
        },
        "bootstrap": {
          "ignore": "component-*",
          "npmClientArgs": ["--no-package-lock"]
        }
      },
      "packages": ["packages/**"]
    }

![Captura de tela de 2019-06-06 11-10-27](https://user-images.githubusercontent.com/17202780/59040536-3dab3300-884d-11e9-8e69-b617d652c434.png)
![Captura de tela de 2019-06-06 11-10-43](https://user-images.githubusercontent.com/17202780/59040537-3dab3300-884d-11e9-946f-156d25a084c6.png)

## Your Environment

| Executable | Version |
| ---: | :--- |

    $ lerna --version
    3.14.1
    $ npm --version
    6.9.0
    $ yarn --version
    1.16.0
    $ node --version
    v12.1.0

| OS | Version |
| --- | --- |

    | Ubuntu | 18.04 |

**Comment by evocateur** [comment]
Do all of your leaf packages have a `name` field in their package.json files?

**Comment by mozgbrasil** [comment]
Yes, we see in the image

  $ lerna ls
  lerna notice cli v3.14.1
  component-casper-magento
  @mozg/crawler-prices
  hackathon-casperjs
  @mozg/magento-base
  @mozg/nodejs-base
  @mozg/reactjs-workers
  isomorphic-jwt-login
  lerna success found 7 packages

**Comment by mozgbrasil** [comment]
It's working, had a package without the name

Thank you

**Comment by cbovis** [comment]
Thanks @evocateur. I had the same issue and your comment solved the problem for me too. Root package didn't have a name because it doesn't get published.

**Comment by trusktr** [comment]
Can the error message be improved?
