### ISSUE TITLE
Global type conflict between packages when using TypeScript

### ISSUE THREAD

**Issue by Yserz** [lerna/lerna#2128]
I have a Lerna project with multiple typescript packages. Most of the packages use `Jasmine` as a testing framework but in one of them I want to use `Jest` instead of `Jasmine`. The current behaviour of Lerna is to gather all dependencies in the `parent node_modules` folder. This also applies for `@types/jasmine` and `@types/jest`. 

Since typescript is scanning for types it picks `@types/jasmine` as well as `@types/jest` from the parent `node_modules` folder for every project. Since both type definitions write for example `afterEach` into the global type namespace I'm facing a conflict.

## Expected Behavior
No type conflicts between `@types/jasmine` and `@types/jest`.

## Current Behavior
Conflict between `@types/jasmine` and `@types/jest` since they are in the same node_modules folder.

## Possible Solution
Maybe keeping types always local to the packages? I'm open for suggestions.

## Steps to Reproduce (for bugs)
1. Create a typescript package with `@types/jasmine` dependency
2. Create a typescript package with `@types/jest` dependency
3. Compile

<details><summary>lerna.json</summary><p>

```json
{
  "command": {
    "publish": {
      "allowBranch": "master",
      "conventionalCommits": true,
      "message": "chore: Publish [skip ci]"
    }
  },
  "exact": true,
  "ignoreChanges": ["**/demo/**"],
  "loglevel": "verbose",
  "npmClient": "yarn",
  "npmClientArgs": ["--exact"],
  "registry": "https://registry.npmjs.org/",
  "useWorkspaces": true,
  "version": "independent",
  "yes": true
}

```
</p></details>

## Context
Trying to run typescript packages with jasmine and others with jest

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.14.1 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | 1.16.0 |
| `node --version` | v12.3.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Mojave | 10.14.5 |

**Comment by Yserz** [comment]
Oi, just found https://github.com/lerna/lerna/tree/master/commands/bootstrap#--nohoist-glob where I can specify dependencies that should not be hoisted!

**Comment by evocateur** [comment]
You're using Yarn workspaces, so this isn't really a Lerna bug anyway. (`lerna bootstrap` will just run `yarn` with your posted config)
