### ISSUE TITLE
maxBuffer exceeded because of using exec instead of spawn

### ISSUE THREAD

**Issue by laurentdesmet** [lerna/lerna#213]
My CI builds are failing at `lerna bootstrap` because the npm logging level is set to info instead of warn, which causes a lot of logs and a maxBuffer exceeded error as explained here http://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process.

This is because the default maxBuffer is used when using the exec command  (https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback). This could be fixed by setting a bigger maxBuffer size (but then the next question is, how big this size should be...), or by using `child_process.spawn`.

**Comment by hzoo** [comment]
Related to https://github.com/lerna/lerna/pull/181 as well? what's the difference between exec/spawn?

**Comment by gigabo** [comment]
Somewhat related to #181, though in that case (`lerna run`) the output from each package is buffered and later emitted by Lerna.  In `bootstrap` it looks like the output is discarded, so Lerna could use spawn's [stdio option](https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_options_stdio) to simply ignore it.

**Comment by laurentdesmet** [comment]
Indeed, somewhat related to #181: there an error is thrown because the `stderr` buffer is exceeded. In my case, it is the `stdout` buffer. `exec` will buffer the stdout and stderr channels of a process, where `spawn` will stream these channels. `spawn` is recommended if your child process emits a lot of data through `stderr` or `stdout`, see this article: http://www.hacksparrow.com/difference-between-spawn-and-exec-of-node-js-child_process.html. In this case, `spawn` would be more suited.
