### ISSUE TITLE
lerna publish URL econdes a scoped package name, triggers ERR! E404 error

### ISSUE THREAD

**Issue by RodrigoMattosoSilveira** [lerna/lerna#2131]
The `lerna publish` command URL encodes the @anviltech/wuf-web-message scoped package name, changing it to @anviltech%2fwuf-web-message, causing the command to fail and to issue the `lerna ERR! E404 Not found` error message.

## Expected Behavior

*The `lerna publish` command **does not** URL encodes the @anviltech/wuf-web-message scoped package name

## Current Behavior

The `lerna publish` command URL encodes the @anviltech/wuf-web-message scoped package name, changing it to @anviltech%2fwuf-web-message, causing the command to fail and to issue the `lerna ERR! E404 Not found` error message.

**Note**: I experimented with [bolt](https://github.com/boltpkg/bolt) and observed the same behavior!

## Possible Solution

Do not allow the scoped package name URL encoding to cause the `lerna ERR! E404 Not found` error.

## Steps to Reproduce (for bugs)

1. Use brach `FM-423-lerna` in the [WUF](https://github.com/anvil-open-software/wuf) public repository
2. Run the following:  `lerna publish from-package --ignore-scripts --yes —skip-git`
3. Observe the failure. Additionally, please notice that the  `--ignore-scripts` option does not work.
4. Also, observe, at the top of the `lerna publish` command, that `lerna` retrieved the correct package names.

<details><summary>lerna.json</summary><p>

```json
{
    "lerna": "3.4.0",
    "packages": [
        "packages/*",
        "projects/anviltech/*"
    ],
    "version": "independent",
    "npmClient": "yarn",
    "useWorkspaces": true
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

</p></details>

## Context

I'm unable to use lerna to publish packages in a mono repo with many packages.

## Your Environment

1. Angular CLI: 7.3.6
1. OS: darwin x64
1. Angular: 7.2.10

| Executable | Version |
| ---: | :--- |
| `lerna --version` 3.15.0
| `npm --version`  6.9.0
| `yarn --version`  1.15.2
| `node --version` 10.15.3

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.5 |
-->

**Comment by RodrigoMattosoSilveira** [comment]
I found and fixed the problem. Embarrassingly, I was not an organization member! I wish the error message was more clear.

**Comment by lewiscutey** [comment]
> I found and fixed the problem. Embarrassingly, I was not an organization member! I wish the error message was more clear.

How to solve this problem?
