### ISSUE TITLE
Local packages not in yarn.lock

### ISSUE THREAD

**Issue by Designer023** [lerna/lerna#2132]
I'm trying to install my app on my hosting (Netlify) and am attempting to deploy using:

```
lerna bootstrap && lerna run --scope @org/app build --stream
```
However when it's built it fails because it's missing all my packages that I also have in the repo:
```
Cannot find module: '@org/pkg1'. Make sure this package is installed.
@org/pkg1: You can install this package by running: yarn add @org/pkg1
```

These are all published (privately) via npm and my NPM token is setup on the env... I know that works because installing via npm directly from the app folder works fine. It was only when updating to use lerna (for the lock file) that the problem occurs.

I'm not sure how to resolve it because I want the locked down packages of yarn.lock but also need the (published) packages in the same repo.

Is there a way to generate a lock with the local packages (I'm guessing not since it would cause circular dependencies)

I don't want to do it with `lerna link` as I want it to be locked to a certain package.

I'm open to any suggestions

**Comment by evocateur** [comment]
Lerna is not a deployment tool. I would suggest installing the packages from your private registry _outside_ of the lerna monorepo, say, in the application. Then you can have all the lockfiles you want.
