### ISSUE TITLE
Lerna with Yarn Workspaces and symlinking

### ISSUE THREAD

**Issue by adampetrie** [lerna/lerna#2137]
Hello!

I have setup a monorepo using lerna and yarn workspaces. A bunch of the monorepo packages consume other monorepo packages as dependencies. When my team is developing locally we would like to see changes in one package reflected in another. We have tried various attempts at linking these packages together without luck.

The general package layout is:

```.
├── lerna.json
├── package.json
├── packages
│   ├── identity-access-token-decoder
│   ├── identity-reliant-party-middleware
│   └── identity-reliant-party-proxy
└── yarn.lock
```

Where `identity-access-token-decoder` is a dependency in ` identity-reliant-party-middleware` and ` identity-reliant-party-middleware` is a dependency in `identity-reliant-party-proxy`. Each of the `package.json` files specifies their sibling dependencies as:

```
"dependencies": {
   "@prodigy/identity-access-token-decoder": "file:../identity-access-token-decoder",
}
```

## Expected Behavior
By running either of `yarn install` or `lerna bootstrap` I would like to see all of the packages hoisted to the root and symlinked to their local package.

## Current Behavior
Looking at the root workspaces node_modules I see this:
```
./node_modules/@prodigy/.
├── identity-access-token-decoder -> ../../packages/identity-access-token-decoder
├── identity-reliant-party-middleware -> ../../packages/identity-reliant-party-middleware
├── identity-reliant-party-proxy -> ../../packages/identity-reliant-party-proxy
```
which appears to imply that the linking has happened correctly. However, I am not seeing changes reflected as I work. If I look at the packages themselves I see: 

```
./packages
├── identity-access-token-decoder
├── identity-reliant-party-middleware
│   ├── node_modules
│   │   └── @prodigy
│   │       └── identity-access-token-decoder
└── identity-reliant-party-proxy
    └──  node_modules
        └── @prodigy
            └── identity-access-token-decoder
            └── identity-reliant-party-middleware
```
My lerna.json looks like this:

```
{
  "packages": ["packages/*"],
  "version": "0.0.2",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "version": {
      "allowBranch": "master"
    }
  }
}
```
and I have specified my workspaces like this in my root package.json:

```
"workspaces": {
    "packages": [
      "packages/*"
    ]
  },
```
Lastly, running `yarn why` I get this:

```
yarn why v1.16.0
[1/4] 🤔  Why do we have the module "@prodigy/identity-reliant-party-middleware"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@prodigy/identity-reliant-party-middleware@0.0.2"
info Has been hoisted to "@prodigy/identity-reliant-party-middleware"
info Reasons this module exists
   - "workspace-aggregator-38aacd5d-6614-4340-a08c-6c2f257725df" depends on it
   - Specified in "dependencies"
   - Hoisted from "_project_#@prodigy#identity-reliant-party-middleware"
info Disk size without dependencies: "1008KB"
info Disk size with unique dependencies: "5.54MB"
info Disk size with transitive dependencies: "91.21MB"
info Number of shared dependencies: 176
=> Found "@prodigy/identity-reliant-party-proxy#@prodigy/identity-reliant-party-middleware@0.0.2"
info This module exists because "_project_#@prodigy#identity-reliant-party-proxy" depends on it.
info Disk size without dependencies: "1008KB"
info Disk size with unique dependencies: "5.54MB"
info Disk size with transitive dependencies: "91.21MB"
info Number of shared dependencies: 176
✨  Done in 1.66s.
```

I suspect that this is a crossed wire between `yarn` and `lerna` but Im nor sure what's going on. I have tried running `lerna link convert` and it places all of the sibling deps in the root with `file:` specifiers, but that made no difference.

I'd really like to use lerna for tooling but I need the productivity boost of symlinked packages. Any help would be appreciated.

Thanks!

**Comment by DannyHinshaw** [comment]
I've recently run into something similar and was going to open a separate issue (still can if someone asks me too), but I think it could live here as well...

When you run `lerna link convert` it uses the `file:` specifier for packages regardless of whether you are using yarn or npm (apparently). The issue is that if you are using yarn, that `file:` specifier should actually be `link:`, this should resolve your issues and make your IDE able to detect changes in the other package source files without needing to rebuild via `lerna bootstrap`.

As an aside, because of this (and the fact that I'm not publishing) I have removed lerna from my monorepo and am just using yarn workspaces as it properly handles everything well enough on it's own for my use case.

Hope that helps someone

**Comment by adampetrie** [comment]
I've been meaning to update this for a while. Apologies to anyone who has been hoping for a conclusion.

We solved this by allowing Yarn to manage dependencies within the monorepo. We replaced all `file:` references with version numbers and yarn seems to handle installations just fine.

At this point the big benefit of Lerna for us is running scripts across the entire repo as well as creating new releases of our modules. It is detecting and updating the versions of dependant packages inside the monorepo correctly across releases and it _drastically_ reduces the overhead in managing this manually.

**Comment by sebastienfi** [comment]
We've met the same issue. We solved it that way:

`package.json`
```json
{  
  "scripts": {
    "setup-dev": "yarn && yarn bootstrap && yarn link-all && yarn build",
    "bootstrap": "lerna bootstrap",
    "build": "lerna run build",
    "link-all": "yarn unlink-all && lerna exec --parallel yarn link",
    "unlink-all": "lerna exec --parallel --bail=false yarn unlink"	
  }
}
```
