### ISSUE TITLE
lerna publish not response

### ISSUE THREAD

**Issue by anthinkingcoder** [lerna/lerna#2146]
## Expected Behavior
This should be published successfully

## Current Behavior
No matter whether I press any key, no response。
![image](https://user-images.githubusercontent.com/17498633/59859833-16597780-93b0-11e9-86ee-510c04fe6f73.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "packages": [
    "packages/*"
  ],
  "version": "1.0.0"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.15.0 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | 1.3.2 |
| `node --version` | 9.11.1 |

| OS | MacOS Mojave | 10.14 |
| --- | --- |
| NAME | VERSION |

**Comment by vincentbriglia** [comment]
this is related to https://github.com/SBoudrias/Inquirer.js/issues/811 and isn't a lerna issue per-se. A solution is to add the following snippet to your package.json (if you are using yarn)
```
  "resolutions": {
    "inquirer": "6.3.1"
  }
```

**Comment by anthinkingcoder** [comment]
> this is related to [SBoudrias/Inquirer.js#811](https://github.com/SBoudrias/Inquirer.js/issues/811) and the release of inquirer to version 6.4.0 (at time of writing, 11 hours ago) so this isn't a lerna issue per-se. A solution is to add the following snippet to your top-level package.json (if you are using yarn)
> 
> ```
>   "resolutions": {
>     "inquirer": "6.3.1"
>   }
> ```
> 
> I am typing from a phone, if someone could make a PR for
> 
> https://github.com/lerna/lerna/blob/9a47201f3fdd1df09cfb1922f26329d1dc4c8cc5/core/prompt/package.json#L34
> 
> and change
> ```
>     "inquirer": "^6.2.0",
> ```
> 
> to
> 
> ```
>     "inquirer": "~6.3.1",
> ```
> 
> that would possibly be a quick fix

thank you

**Comment by vincentbriglia** [comment]
@anthinkingcoder ... can you leave this issue open? others might have the issue until this is fixed
