### ISSUE TITLE
question: can we split commit and tagging when using lerna version?

### ISSUE THREAD

**Issue by maapteh** [lerna/lerna#2147]
At the moment we have PR's in which we are creating alpha releases in npm but not tagging them since they have no value other then consuming the output during a PR.
The option to "not tag" with lerna version is combined with the actual commit of the version changes in sub packages. But these versions we do want to commit, so we are able to publish (else publish command will not see any difference).

```
--no-git-tag-version
By default, lerna version will commit changes to package.json files and tag the release. Pass --no-git-tag-version to disable the behavior.
```

## Expected Behavior
Is it possible to only exclude tagging?

## Current Behavior
Passing 'no-git-tag-version' to lerna version will not tag it but also not commit the changed version numbers.

## Possible Solution
I have no clue yet so that's why i decided to open a ticket

## Steps to Reproduce (for bugs)
Not really a bug

<details><summary>lerna.json</summary><p>

```json
{
    "lerna": "3.15.0",
    "packages": ["packages/*"],
    "npmClient": "yarn",
    "useWorkspaces": true,
    "version": "independent",
    "command": {
        "version": {
            "npmClient": "npm",
            "allowBranch": ["master", "feature/*", "bugfix/*"],
            "message": "chore(release): versioning",
            "conventional-commits": true,
            "no-changelog": true,
            "no-commit-hooks": true,
            "yes": true,
            "exact": true
        },
        "publish": {
            "npmClient": "npm",
            "conventionalCommits": true,
            "no-verify-access": true,
            "yes": true
        }
    },
    "registry": "https://***/artifactory/api/npm/npm/",
    "ignoreChanges": [
        "**/__fixtures__/**",
        "**/__mocks__/**",
        "**/__tests__/**",
        "**/*.md",
        "**/*.spec.ts"
    ]
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
Changes:
 - @###-beta/browserslist-config: 0.2.8 => 0.2.9-5aad186.0
 - @###-beta/web-dev: 0.1.24 => 0.1.25-5aad186.0
 - @###-beta/web-utils: 0.1.13 => 0.1.14-5aad186.0

lerna info auto-confirmed 
lerna info execute Skipping git push
lerna info execute Skipping releases
lerna success version finished

```
</p></details>

## Context
For PR's we only want to publish canary versions, we already make sure the version is including a preid commithash so they are unique (people can work on same time on same modules). But we do not want to have tags for them since they have no real meaning other then giving the developer the option to consume the package in another app for testing.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.15 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.16.0 |
| `node --version` | 10.14.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.3 |

**Comment by maapteh** [comment]
@evocateur is it possible to help me a little further :)

**Comment by evocateur** [comment]
The behavior of `--no-git-tag-version` is basically identical to that of [npm itself](https://docs.npmjs.com/cli/version#git-tag-version). Tagging is pretty integral to Lerna's primary function (publishing changed packages since the last release), so I'm not especially inclined to allow it to be disabled when serviceable workarounds exist for such complicated use-cases as your own.

For example, a root lifecycle script that your developers can run (instead of `npx lerna ...` directly):
```json
{
  "scripts": {
    "prerelease:alpha": "lerna version --no-git-tag-version --conventional-prerelease --yes && git add -u .",
    "release:alpha": "lerna publish from-package --pre-dist-tag next",
    "postrelease:alpha": "git commit -m 'chore(release): Publish alpha' && git push"
  }
}
```

Incidentally, you _really_ shouldn't configure `yes: true` in your lerna.json, that's disallowing anyone from validating their changes are as they expected. If folks are confident or need to skip the prompts due to 10x-ness, they can pass `--yes` themselves:
```
npm run release:alpha -- --yes
```

**Comment by maapteh** [comment]
Thank you Daniel!
