### ISSUE TITLE
[Question] How to bump major version from initial development with conventional commits

### ISSUE THREAD

**Issue by takakobem** [lerna/lerna#2150]
This is just a question.
I don't know how to bump version from `0.x.y` to `1.0.0` using `lerna version --conventional-commits`, with generating CHANGELOG.md.
Is there any options to do this?

**Comment by maapteh** [comment]
its the conventional commit so the word: BREAKING CHANGE in the body is enough. See https://www.conventionalcommits.org/en/v1.0.0-beta.4/

**Comment by takakobem** [comment]
@maapteh Yes, I know the word, but what I want to do is just bumping the version up without any additional commits including the word.

**Comment by maapteh** [comment]
then run `yarn lerna version major` and it will create major bump
