### ISSUE TITLE
AWS Lambda Layers & Lerna.js

### ISSUE THREAD

**Issue by MaxVinogradov** [lerna/lerna#2154]
Hi! I'm trying to use Lerna.js to create Serverless monorepo, in bench with AWS Lambda Layers.
Technically I want to share my root node_modules between Lambdas as Layer.

But I faced with problem that my own lerna sub-packages exist in node_modules as symlink, and it's a problem.
Do you have any guide, advice, how symlink could be replaced with "real" folder in node_modules in context of lerna.js usage?

![image](https://user-images.githubusercontent.com/13771219/60075211-755f1980-972d-11e9-9202-9d24fc80c0d2.png)

**Comment by tempofeng** [comment]
You can turn on "nohoist" mode in config. Please see: https://github.com/lerna/lerna/blob/master/doc/hoist.md

Below is how we config our root package.json:

```
{
  "private": true,
  "devDependencies": {
    "lerna": "3.4.3"
  },
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/vuetify",
      "**/server/**",
    ]
  }
}

```

**Comment by MaxVinogradov** [comment]
@tempofeng thank you, but now I have next error:
```
lerna ERR! EWORKSPACES --hoist is not supported with --npm-client=yarn, use yarn workspaces instead
```
![image](https://user-images.githubusercontent.com/13771219/60136030-d4fc0a00-97ab-11e9-8797-f598498d9f6e.png)

Do you have any ideas how can I solve this problem (seems you use )?
+ I'm not sure that I configured `nohoist` section correctly...

**Comment by tempofeng** [comment]
add `.yarnrc` in your root directory with:

```
workspaces-experimental true
```

**Comment by MaxVinogradov** [comment]
Nothing changed:
![image](https://user-images.githubusercontent.com/13771219/60367183-429b7680-99f6-11e9-9f8a-c9a490f354db.png)

Seems like Lerna is not appropriate solution for AWS Lambda + Layers... or I cook it in the wrong way.

**Comment by evocateur** [comment]
Lerna is not a deployment tool. Use something like [serverless-jetpack](https://github.com/FormidableLabs/serverless-jetpack) instead.

**Comment by MaxVinogradov** [comment]
@evocateur thanks!
