### ISSUE TITLE
lerna bootstrap command does not install the local yarn packages in docker container

### ISSUE THREAD

**Issue by soubhikchatterjee** [lerna/lerna#2158]
I am trying to install my local npm packages (using yarn workspaces) in my docker container but it does not seem to be installing the local packages. Though it does install the global packages successfully.

Also, when I bash into the container and run "lerna bootstrap", that installs my local packages successfully. I have been searching all over the internet why is this happening.

My docker file's content looks like

    FROM node:12.4.0-alpine
    
    RUN apk add --no-cache bash
    RUN apk add --no-cache yarn
    WORKDIR "/app"
    

    RUN yarn global add lerna
    COPY . .
    RUN yarn install
    RUN lerna bootstrap
    
    
    CMD ["npm", "run", "dev"]

My root package.json file looks like

    {
      "name": "my-test",
      "version": "1.0.0",
      "description": "Test",
      "main": "app.js",
      "private": true,
      "workspaces": [
        "packages/**"
      ],
      "scripts": {
        "start": "node app.js",
        "dev": "nodemon -L app.js"
      },
      "author": "Phantom",
      "license": "ISC",
      "dependencies": {
        "config": "3.0.1",
        "dotenv": "7.0.0",
        "express": "4.16.4",
        "node-locale": "2.0.0",
      },
      "devDependencies": {
        "lerna": "^3.15.0",
        "@lerna/bootstrap": "3.8.5",
        "nodemon": "1.18.10",
      }
    }

My lerna.json file looks like

    {
      "version": "1.0.0",
      "npmClient": "yarn",
      "useWorkspaces": true,
      "packages": ["packages/*"]
    }

As a workaround, I am runing the following docker command once the container is up.

    docker exec -w /app <my-container-name> lerna bootstrap

I know this is not a proper solution, so can someone please help me out?

**Comment by nukeop** [comment]
Do you see anything like `cannot run in wd` in the logs after bootstrap? I'm getting the same problem.

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
