### ISSUE TITLE
Keeping certain packages unpublished

### ISSUE THREAD

**Issue by bkniffler** [lerna/lerna#216]
Hey, 
I love lerna, its a great for managing multiple projects. I'm writing modules that help me creating web-apps, so projects that contain a lot of the boilerplate necessary for nodeJS/react.

So, I got these projects that I'd like to publish to git/npm and multiple web-apps that use these projects, but should remain unpublished and ignored by git.

The private apps have defined `private: true` within the `package.json`, and I put them into my lerna repository's `.gitignore`. This does exactly what I need, but when doing `lerna publish`:

```
Errored while running PublishCommand.execute
Error: Command failed: git add /xxx/lerna/packages/xxx/package.json
The following paths are ignored by one of your .gitignore files:
packages/xxx/package.json
Use -f if you really want to add them.
```

Also, when using `lerna publish  --skip-git`, I'm getting:

```
npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx/Documents/Projekte/lerna/packages/xxx/npm-debug.log
```

The messages make sense. Would you consider making this scenario possible? Maybe we could have `privatePackages` in `lerna.json`.

What'd be even more great would be to allow specifying custom paths in lerna repository's `lerna.json`, like a `externalPackages` property that contains: 
```
"externalPackages": {
   "xxx": "/user1/documents/xxx"
}
```

But for now, allowing private / unpublished / .git-ignored modules, that get their dependencies updated by lerna, would be greatly appreciated.

Keep it up!

**Comment by gigabo** [comment]
So the private packages aren't under revision control?

Would you still like Lerna to update their dependencies (but just not try to commit the updates)?

**Comment by bkniffler** [comment]
Yes, absolutely! The whole point of lerna is to manage dependency versions, but I'd really like it to be less opinionated on how I organize my git repos (mono-repo vs multiple repos), my folders and how/what I publish.

After giving it a few more thought, I suggest 3 things:
- Respect `private: true` in a projects' package.json file and don't run the publishing then
- Check if a project is a git repository and run scripts on that instead on always trying to use the mono-repo
- Add the `externalPackages` option mentioned above to include other folders
```json
"externalPackages": {
   "xxx": "/user1/documents/xxx"
}
```

I imagine these are big points that might involve a few changes after looking into the source code. What do you think though?

**Comment by gigabo** [comment]
> Respect private: true in a projects' package.json file and don't run the publishing then

This _should_ already work.  We [have](https://github.com/redfin/react-server/blob/master/packages/react-server-test-pages/package.json#L4) [private](https://github.com/redfin/react-server/blob/master/packages/react-server-integration-tests/package.json#L3) [packages](https://github.com/redfin/react-server/blob/master/packages/react-server-examples/package.json#L3) in our repo, and they haven't caused problems.

> Check if a project is a git repository and run scripts on that instead on always trying to use the mono-repo

That's a cool idea.  It's a totally different way of thinking about Lerna.

It would, I think, be a pretty big change.

> Add the externalPackages option mentioned above to include other folders

This has been [suggested before](https://github.com/lerna/lerna/issues/126).  Maybe worth reconsidering in this context.

**Comment by bkniffler** [comment]
Thanks @gigabo!
Its true, it respects private, my bad. But it will still fail if the file is gitignored, so its a different problem :(

Yes, I think it would be extremely useful. Working on a UI library, the server, utility libraries, tools and last but not least the applications, some of them being mono-repos, some of them being a repo per package, some not on npm, some private, some public, but all depending on one another isn't such an unusual scenario for people working on their full nodeJS + frontend stack, and using a more powerful lerna to prototype changes on your micro-packages in your final apps would be very cool and could encourage people to write better code.

To reevaluate my suggestions:
- Have a `sources` or `packages` property that contains an array of folders. A folder could be either multiple packages (like with the current default `packages` directory) or a single package. 
- Allow for `lerna.json` in these folders to specify packages/package-specific options (like for example, if they should be published).
- Use the nearest .git repository to perform git operations on each package using the `cwd` working-directory option on child_process (so adding a `gitRoot` property to the `packages` class that is handed to git operations)

What do you think?

**Comment by thejameskyle** [comment]
My understanding of this is that you want more than just the `--skip-git` flag, you want to make it so that lerna doesn't attempt to `git add` things that are `gitignore`'d?

**Comment by AlastairTaft** [comment]
I don't think it does respect private packages. I'm on lerna version "2.0.0-beta.26" and when I run `lerna publish` it tries to publish my private package.

```
? Are you sure you want to publish the above changes? Yes

Publishing packages to npm...
Attempting to retry publishing redacted...
Error: Command failed: cd /Users/redacted && npm publish --tag lerna-temp
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish" "--tag" "lerna-temp"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3

npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/redacted/npm-debug.log

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by gigabo** [comment]
Hi @AlastairTaft, sorry to hear you got left in a bad state by Lerna.  Unfortunately private packages don't work in `2.0.0-beta.26`.  The fix from #321 landed in `2.0.0-beta.28`.  An upgrade should get this working for you.

If you get a chance to try it out, and find that it does work correctly, please post back here and we'll close this ticket.

**Comment by AlastairTaft** [comment]
Ah excellent. i'll try that thanks.

**Comment by AlastairTaft** [comment]
When I made changes to my private package then ran `lerna publish` it seemed to respect it was private and gave the message.

```
Alastairs-MacBook-Pro:REDACTED alastairtaft$ lerna publish
Lerna v2.0.0-beta.28
Current version: 0.1.7
Checking for updated packages...
Errored while running PublishCommand.initialize
Error: No updated packages to publish.
    at PublishCommand.initialize (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:94:18)
    at PublishCommand._attempt (/usr/local/lib/node_modules/lerna/lib/Command.js:161:21)
    at PublishCommand.runCommand (/usr/local/lib/node_modules/lerna/lib/Command.js:145:12)
    at PublishCommand.run (/usr/local/lib/node_modules/lerna/lib/Command.js:69:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/lerna/bin/lerna.js:58:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

So I tried running with force to see if it would publish the others and ignore the private one and got exactly the same message, should of it published the others here?
```
Alastairs-MacBook-Pro:REDACTED alastairtaft$ lerna publish --force-pubish=*
Lerna v2.0.0-beta.28
Current version: 0.1.7
Checking for updated packages...
Errored while running PublishCommand.initialize
Error: No updated packages to publish.
    at PublishCommand.initialize (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:94:18)
```
I then went and edited one of my none private packages and tried to publish again.

```
Alastairs-MacBook-Pro:REDACTED alastairtaft$ lerna publish
Lerna v2.0.0-beta.28
Current version: 0.1.7
Checking for updated packages...
? Select a new version (currently 0.1.7) Patch (0.1.8)

Changes:
- @luna/redacted-non-private-package: 0.1.7 => 0.1.8
- @luna/redacted-private-package: 0.1.7 => 0.1.8

? Are you sure you want to publish the above changes? Yes

Publishing packages to npm...
Pushing tags to git...

To https://github.com/redacted.git
   9340a40..b3619a9  master -> master
To https://github.com/redacted.git
 * [new tag]         v0.1.8 -> v0.1.8
Successfully published:
 - @luna/redacted-non-private-package@0.1.8
 - @luna/redacted-private-package@0.1.8
```

It told me that my private package was published however `npm view` tells me otherwise.

```
npm view @luna/redacted-private-package
 
{ name: '@luna/redacted-private-package',
  description: '',
  'dist-tags': { latest: '0.1.7' },
  versions: [ '0.1.6', '0.1.7' ],
...
```

It seems to respect not publishing the private package, however it shouldn't of told me that it had?

**Comment by gigabo** [comment]
Hi @AlastairTaft I think there may be a few things going on here.

Firstly there's an open issue with [`--force-publish=*`](https://github.com/lerna/lerna/issues/266).  Please be sure that shell expansion isn't foiling you here.

Secondly, does your private package _depend_ on your public package?  If so, Lerna should update the dependency version and the package version _locally_ (within the repo).  It then lists the package as "changed".  But Lerna shouldn't _publish_ the package (so `npm view @luna/redacted-private-package` shouldn't show you the new version.  If you do a `git show v0.1.8` you should see that the package.json was updated, though.

**Comment by AlastairTaft** [comment]
Thanks, I'm relatively new to lerna, that would explain it.

**Comment by gigabo** [comment]
Yeah, it's all a little confusing.  We recently [added annotations for private packages](https://github.com/lerna/lerna/pull/329) in the `update` command.  Maybe we should do something similar for the list of "changes" during publish, too...

**Comment by gigabo** [comment]
^ Filed #337 for that.

@AlastairTaft Sounds like you're basically set here (modulo confusing log output).

Closing for now.  Please reopen (or, better yet, file a new ticket) if you run into more trouble!
