### ISSUE TITLE
Unable to publish on CI

### ISSUE THREAD

**Issue by tusharmath** [lerna/lerna#2162]
## Expected Behavior
- I should be able to publish through Travis CI

## Current Behavior
- Authentication Error

## Possible Solution
- Use `GH_TOKEN`

## Steps to Reproduce (for bugs)

1. Sample Build URL: https://travis-ci.com/action-land/action-land/builds/117467520
2. Error:
```

lerna info git Pushing tags...
lerna ERR! Error: Command failed: git push --follow-tags --no-verify origin master
lerna ERR! remote: Invalid username or password.
lerna ERR! fatal: Authentication failed for 'https://github.com/action-land/action-land.git/'
lerna ERR! 
lerna ERR!     at makeError (/home/travis/build/action-land/action-land/node_modules/execa/index.js:174:9)
lerna ERR!     at /home/travis/build/action-land/action-land/node_modules/execa/index.js:278:16
lerna ERR! Error: Command failed: git push --follow-tags --no-verify origin master
lerna ERR! remote: Invalid username or password.
lerna ERR! fatal: Authentication failed for 'https://github.com/action-land/action-land.git/'
lerna ERR! 
lerna ERR!     at makeError (/home/travis/build/action-land/action-land/node_modules/execa/index.js:174:9)
lerna ERR!     at /home/travis/build/action-land/action-land/node_modules/execa/index.js:278:16
lerna ERR! lerna Command failed: git push --follow-tags --no-verify origin master
lerna ERR! lerna remote: Invalid username or password.
lerna ERR! lerna fatal: Authentication failed for 'https://github.com/action-land/action-land.git/'
lerna ERR! lerna 
```

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "packages": [
    "modules/*"
  ],
  "version": "4.2.0",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
</p></details>

## Context
Trying to publish a mono repo via Travis

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.15.0 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.16.0 |
| `node --version` | v12.2.0 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.5 |

**Comment by fabiontop** [comment]
I have the same error in GitLab. I have set the GL_TOKEN as Environment Variable. This is my CI Configuration:
```
stages:
  - version

versioning:
  image: node:lts-alpine
  stage: version
  before_script:
    - apk update && apk upgrade && apk add git
    - npm install -g lerna
    - git checkout $CI_COMMIT_REF_NAME
    - git config --global user.email "...." && git config --global user.name "...."
  script:
    - lerna bootstrap
    - lerna version -y --create-release gitlab
```
I get the same error but in GitLab:
```
lerna info auto-confirmed 
lerna info execute Skipping releases
lerna info git Pushing tags...
lerna ERR! Error: Command failed: git push --follow-tags --no-verify origin master
lerna ERR! remote: You are not allowed to upload code.
lerna ERR! fatal: unable to access 'https://gitlab-ci-token:[MASKED]@gitlab.com/......': The requested URL returned error: 403
lerna ERR! 
lerna ERR!     at makeError (/builds/......./node_modules/execa/index.js:174:9)
lerna ERR!     at Promise.all.then.arr (/builds/....../node_modules/execa/index.js:278:16)
lerna ERR! lerna Command failed: git push --follow-tags --no-verify origin master
lerna ERR! lerna remote: You are not allowed to upload code.
lerna ERR! lerna fatal: unable to access 'https://gitlab-ci-token:[MASKED]@gitlab.com/....': The requested URL returned error: 403
```

**Comment by MikeSquall** [comment]
Hi !
I don't know if this is a good practice or not but as I run the `publish` command in a bash script, 
I do this before:
```bash
set_git_remote() {
    git remote set-url origin https://${GH_ACCESS_TOKEN}@github.com/<username>/<reponame>
}
```
with `GH_ACCESS_TOKEN` set as a variable in Travis settings.

**Comment by evocateur** [comment]
I really don't recommend generating git commits in CI. If you're unwilling to split versioning and publishing entirely (only running `lerna publish from-git --yes` in CI), then I guess you need to enable the Travis host to push commits back to Github (which is outside the scope of lerna).

**Comment by jieliu218** [comment]
> I have the same error in GitLab. I have set the GL_TOKEN as Environment Variable. This is my CI Configuration:
> 
> ```
> stages:
>   - version
> 
> versioning:
>   image: node:lts-alpine
>   stage: version
>   before_script:
>     - apk update && apk upgrade && apk add git
>     - npm install -g lerna
>     - git checkout $CI_COMMIT_REF_NAME
>     - git config --global user.email "...." && git config --global user.name "...."
>   script:
>     - lerna bootstrap
>     - lerna version -y --create-release gitlab
> ```
> 
> I get the same error but in GitLab:
> 
> ```
> lerna info auto-confirmed 
> lerna info execute Skipping releases
> lerna info git Pushing tags...
> lerna ERR! Error: Command failed: git push --follow-tags --no-verify origin master
> lerna ERR! remote: You are not allowed to upload code.
> lerna ERR! fatal: unable to access 'https://gitlab-ci-token:[MASKED]@gitlab.com/......': The requested URL returned error: 403
> lerna ERR! 
> lerna ERR!     at makeError (/builds/......./node_modules/execa/index.js:174:9)
> lerna ERR!     at Promise.all.then.arr (/builds/....../node_modules/execa/index.js:278:16)
> lerna ERR! lerna Command failed: git push --follow-tags --no-verify origin master
> lerna ERR! lerna remote: You are not allowed to upload code.
> lerna ERR! lerna fatal: unable to access 'https://gitlab-ci-token:[MASKED]@gitlab.com/....': The requested URL returned error: 403
> ```

Add this line will solve issue:

 - git remote set-url origin "https://gitlab-ci-token:$GL_TOKEN@gitlab.example.fi/example.git"


GL_TOKEN is set in GITLab env

**Comment by jieliu218** [comment]
@fabiontop   Check my reply if you still have this issue

**Comment by semoal** [comment]
> > I have the same error in GitLab. I have set the GL_TOKEN as Environment Variable. This is my CI Configuration:
> > ```
> > stages:
> >   - version
> > 
> > versioning:
> >   image: node:lts-alpine
> >   stage: version
> >   before_script:
> >     - apk update && apk upgrade && apk add git
> >     - npm install -g lerna
> >     - git checkout $CI_COMMIT_REF_NAME
> >     - git config --global user.email "...." && git config --global user.name "...."
> >   script:
> >     - lerna bootstrap
> >     - lerna version -y --create-release gitlab
> > ```
> > 
> > 
> > I get the same error but in GitLab:
> > ```
> > lerna info auto-confirmed 
> > lerna info execute Skipping releases
> > lerna info git Pushing tags...
> > lerna ERR! Error: Command failed: git push --follow-tags --no-verify origin master
> > lerna ERR! remote: You are not allowed to upload code.
> > lerna ERR! fatal: unable to access 'https://gitlab-ci-token:[MASKED]@gitlab.com/......': The requested URL returned error: 403
> > lerna ERR! 
> > lerna ERR!     at makeError (/builds/......./node_modules/execa/index.js:174:9)
> > lerna ERR!     at Promise.all.then.arr (/builds/....../node_modules/execa/index.js:278:16)
> > lerna ERR! lerna Command failed: git push --follow-tags --no-verify origin master
> > lerna ERR! lerna remote: You are not allowed to upload code.
> > lerna ERR! lerna fatal: unable to access 'https://gitlab-ci-token:[MASKED]@gitlab.com/....': The requested URL returned error: 403
> > ```
> 
> Add this line will solve issue:
> 
> * git remote set-url origin "https://gitlab-ci-token:$GL_TOKEN@gitlab.example.fi/example.git"
> 
> GL_TOKEN is set in GITLab env

The correct one with the next Gitlab api is:

GL_TOKEN is not anymore a Gitlab env variable.
```
- git remote set-url origin "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/x/xx/xxx.git"
```

**Comment by JounQin** [comment]
I have similar issue on GitHub Actions:

```sh
fatal: could not read Username for 'https://github.com': Device not configured
```

**Comment by aibolik** [comment]
I believe this should be taken care by `lerna` itself. We've switched to `lerna` and wanted to simulate what `semantic-release` was giving us. With `lerna` we have to do a lot of setting `git` to be able to commit and push, whereas `semantic-release` was doing everything for us. I am not sure how it is exactly implemented in `semantic-release`, but that'd be nice to have it here too.

**Comment by TheLooseCannon** [comment]
@aibolik [is this the semantic-release](https://github.com/atlassian/lerna-semantic-release) you are talking about? in there all we have to do is add adapter to commitizen and then run their commands...but im getting error command not found

where as in here....

lerna publish works all right....

```
        - echo $CI_COMMIT_REF_NAME
        - git checkout $CI_COMMIT_REF_NAME
        - git config --global user.email "qrst@uvw.com"
        - git config --global user.name "lmnop"
        - npm install --global lerna
        - npm install
        - lerna publish --conventional-commits --conventional-prerelease -y --force-publish=abcd,efgh,hijk
    
```

this is my CI....

This works fine at times and at times it doesn't update the version
any idea why? it doesn't publish since there is no updation change.....and i get messages like 

```
lerna WARN EBEHIND Local branch 'feat_adding_CI_to_test' is behind remote upstream origin/feat_adding_CI_to_test, exiting
```

**Comment by TheLooseCannon** [comment]
@semoal did your CI work...?

**Comment by jenniferpham** [comment]
I was able to get my CI to work and publish through Github Actions.  Even if you're not using Github Actions, maybe this could give you an idea of what to do.  I added SSH-key and Github token which had write access to the repo.

```
    steps:
      - name: Copy repo code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

     - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish New Version and Release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          lerna publish --yes
```
