### ISSUE TITLE
How  do you update an npm dependency?

### ISSUE THREAD

**Issue by sarink** [lerna/lerna#2170]
If I run `bootstrap` after I've changed a version number in `package.json`, a new `package-lock` file is not generated.

`lerna add` simply yields `lerna WARN No packages found where <npm-module> can be added.` - although it will update the dependency version in `package.json` (just not `package-lock.json`, making it effectively useless)

`npm install`, as well as `lerna exec install` fail because npm cannot find one of the local/symlinked packages in the registry (obviously)

How does one update a dependency? Is this something crazy with my setup or a bug?

**Comment by charlie632** [comment]
Having the exact same issue

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
