### ISSUE TITLE
More reliable canary bump

### ISSUE THREAD

**Issue by kirill-konshin** [lerna/lerna#2171]
As stated in https://github.com/lerna/lerna/issues/1583#issuecomment-424596666 Lerna cannot properly bump canary releases in shallow Git repo.

Currently we have to use something incremental and reliable, Travis's job number or Gitlab's pipeline IID works just fine:

```bash
$ lerna publish --canary --preid=$TRAVIS_BRANCH.$TRAVIS_JOB_NUMBER --dist-tag=$TRAVIS_BRANCH --yes --no-push --no-git-tag-version
```

Unfortunately this results in versions like `19.4.1-feature-npm.4247.1` where `.1` is that improperly working increment, which is always the same.

In order to fix this we can count previous releases in NPM under same `dist-tag` instead. Either inside Lerna or externally if you don't want to have this in your code. But then please provide a way to manually set the `canary-increment` during `publish`:

```bash
$ lerna publish --canary --preid=$TRAVIS_BRANCH --canary-increment=$TRAVIS_JOB_NUMBER --dist-tag=$TRAVIS_BRANCH --yes --no-push --no-git-tag-version
```

So as a summary, one of the options would work:

1. Lerna counts increments based on something more reliable than Git because it can be shallow
2. Lerna supports new variable to set increment explicitly

**Comment by evocateur** [comment]
`git fetch --unshallow` doesn't work?

**Comment by kirill-konshin** [comment]
I guess it will work, but it can ruin performance on a large size repo...

**Comment by evocateur** [comment]
Well, there's all sorts of fancy new flags in [git fetch](https://git-scm.com/docs/git-fetch) that could be used to mitigate that (assuming your CI host has a reasonably up-to-date `git`).

**Comment by kirill-konshin** [comment]
Why not just get latest tags/versions from NPM? It's the source of truth after all, isn't it? Or like I said in the original post — let the CI job to define the increment.
