### ISSUE TITLE
lerna publish --dist-tag does not add tag

### ISSUE THREAD

**Issue by LoicPoullain** [lerna/lerna#2176]
## Expected Behavior

```
lerna publish --cd-version=major --dist-tag next
```

All packages should be published with the new version and the dist tag `next`.

## Current Behavior

All packages got published with the correct version but with the `latest` tag.

## Steps to Reproduce (for bugs)

See command above.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.4.0",
  "packages": [
    "packages/*"
  ],
  "version": "1.0.0"
}

```
</p></details>

## Context
I published the version 1 of the framework [FoalTS](https://github.com/FoalTS/foal). I wanted to add the `next` tag to be able to make additional tests before publishing it as the new release.

Before my additional tests, `npm install @foal/core` would still install the version 0.8.9.

Once I do my tests, I would add the `latest` tag to each version 1 so as `npm install @foal/core` installs version 1.

## Your Environment
Mac OSX. Terminal loaded in VSCode.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 6.7.0 |
| `node --version` | v8.11.3 |

| OS | Version |
| --- | --- |
| Mac OS X | VERSION |
| macOS Mojave | 10.14.5 |

**Comment by evocateur** [comment]
You seem to be using Lerna v2.x. I would suggest using the current major, v3.x, as I don't believe `--dist-tag` is supported on v2 (it was named `--npm-tag` then).

**Comment by LoicPoullain** [comment]
Oh, thanks! I'll test with version 3 in the next release then. Closing this
