### ISSUE TITLE
Lerna: Semver convention was broken

### ISSUE THREAD

**Issue by iamkevinwolf** [lerna/lerna#2177]
Hello guys! I have been using lerna to release my monorepos for a while, and it have been a good fit all the time.

## But...

Yesterday I was setting up a new monorepo, and seeing at [the logs](https://travis-ci.org/iamkevinwolf/devtools/builds/557091065#L588) generated by mi CI, I've saw that the release was skipped.

By taking a look at the [latest release](https://github.com/lerna/lerna/releases/tag/v3.15.0), I've saw that `githubRelease` was deprecated in favour of `createRelease`.

I think this broke the semver specification, which says that *every breaking change should be a major release".

Any thoughts?

**Comment by evocateur** [comment]
It's still functional, just deprecated. The issue you're experiencing is that you're using the `command.publish` namespace to configure `githubRelease`, and we missed that during the [refactoring](https://github.com/lerna/lerna/commit/4974b78866faac3afec98ca83c46fe8d999cdf30#diff-0450c85a73670cf460e9ce9c771f100f). We did not intentionally violate semver.
