### ISSUE TITLE
lerna based on yarn berry?

### ISSUE THREAD

**Issue by askbeka** [lerna/lerna#2178]
[Yarn version 2](https://github.com/yarnpkg/berry) is being built in a way to be extended and built on top of. Basically you could build you own CLI with more control on package management.

After I've red through the docs, my immediate thought was that lerna can be a good candidate?

**Comment by evocateur** [comment]
A good candidate for what, specifically?

**Comment by askbeka** [comment]
for building lerna?
Since it has lower level primitives just for that, or alternatively build plugins for yarn,
and use them as documented [here](https://yarnpkg.github.io/berry/features/plugins)

I am not sure, what you have in mind for lerna, but seems like yarn is a good tool for monorepos and is going to be even better with expandability, even possibility to support other languages/platforms.

Just wanted to know what your thoughts are? I could try creating couple of plugins for yarn using lerna, 
I know it possible to use lerna pragmatically, and I did, but it lacks documentation and I am not sure if I can rely on this approach, which is probably the main reason why I am asking:)

**Comment by evocateur** [comment]
Lerna is intended to be independent of package manager CLI. If something Lerna does is done better by a package manager CLI, then by all means, use the package manager CLI instead of Lerna.

To be frank, I'm not particularly interested in implementing something with alpha-quality software.

>  but it lacks documentation

PRs welcome.

**Comment by askbeka** [comment]
Ok. Thanks, for taking time to respond and for being frank.

I get where you stand. I can proceed now with what works best for me and try to contribute back to lerna where I see fit.
