### ISSUE TITLE
Import keeping branches

### ISSUE THREAD

**Issue by PaulTondeur** [lerna/lerna#2179]
I have a monorepo managed by Lerna. Next to that there is a very active team working on a product that has its own git repository that should become part of the monorepo. The team keeps working on branches and never reaches a moment where it has closed all feature branches, so we can run our lerna import.
Is there a way we can run lerna import, preserving the feature branches, so once the import is completed, all devs can continue their work from the feature branch in the monorepo?

**Comment by evocateur** [comment]
No, that won't be supported by Lerna. `lerna import` is just a series of git commands, so there's probably(?) a way to do that with git alone.

**Comment by tgroutars** [comment]
@PaulTondeur Did you eventually find a way to do this? We're facing the same issue with my team right now, would be awesome to see how you handled it :)

**Comment by Anand2489** [comment]
@evocateur Can you guide through if you have done something similar?

**Comment by PaulTondeur** [comment]
This issue is from a long time ago, I am no longer working on the same project and can't remember how and if we solved this back then, so I am unable to provide any further input on this.
