### ISSUE TITLE
TypeError: Cannot set property 'committish' of undefined

### ISSUE THREAD

**Issue by jtenner** [lerna/lerna#2180]
I got an error when trying to publish my package to npm. At this point, I'm pulling out my hair trying to get this to work.

## Expected Behavior

```
npx lerna publish
```

This should publish my package to npm 🤷‍♂ .

## Current Behavior

I applied a console.log() to `C:\Users\jtenner\Desktop\projects\as-pect\node_modules\@lerna\package\index.js:220:25` just to see what was going on.

```
Changes:
 - @as-pect/assembly: 2.1.2 => 2.1.3
 - @as-pect/cli: 2.1.2 => 2.1.3
 - @as-pect/core: 2.1.2 => 2.1.3

? Are you sure you want to create these versions? Yes
lerna info execute Skipping releases
{
  type: 'git',
  registry: undefined,
  where: undefined,
  raw: '@as-pect/assembly@git:github.com/jtenner/as-pect/assembly#v2.1.2',
  name: '@as-pect/assembly',
  escapedName: '@as-pect%2fassembly',
  scope: '@as-pect',
  rawSpec: 'git:github.com/jtenner/as-pect/assembly#v2.1.2',
  saveSpec: 'git:github.com/jtenner/as-pect/assembly#v2.1.2',
  fetchSpec: 'git:github.com/jtenner/as-pect/assembly',
  gitRange: undefined,
  gitCommittish: 'v2.1.2',
  hosted: undefined
}
lerna ERR! TypeError: Cannot set property 'committish' of undefined
lerna ERR!     at Package.updateLocalDependency (C:\Users\jtenner\Desktop\projects\as-pect\node_modules\@lerna\package\index.js:220:25)
lerna ERR! lerna Cannot set property 'committish' of undefined
```

Repo is here: https://github.com/jtenner/as-pect

## Steps to Reproduce (for bugs)

1. `git clone`
2. `npm install`
3. `npx lerna bootstrap`
4. `npx lerna publish`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "2.1.2"
}
```
</p></details>

## Context

Just spent the last week converting everything in `as-pect` to a mono repo and I can't seem to publish my software.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | v3.15.0 |
| `npm --version`  | v6.9.0 |
| `node --version` | v12.6.0 |

| OS | Version |
| Windows 10 | 1607 |

## Questions:

- Is there anything I can do to help? 

## Update:

I managed to fix the package.json configurations to match the example. For instance, here is the CLI `package.json`

```json
{
  "repository": {
    "type": "git",
    "url": "https://github.com/jtenner/as-pect/tree/master/packages/cli"
  },
  "dependencies": {
    "@as-pect/assembly": "github:jtenner/assembly#v2.1.3",
    "@as-pect/core": "github:jtenner/core#v2.1.3",
  }
}
```

I don't know if this is correct, because when I try to install the cli I get the following error in the console:

```
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/jtenner/assembly.git
npm ERR!
npm ERR! Warning: Permanently added the RSA host key for IP address '{IP Address}' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jtenner\AppData\Roaming\npm-cache\_logs\2019-07-15T14_01_36_156Z-debug.log
```

**Comment by jtenner** [comment]
At this point I think I got it. I had to add each package as a peer dependency. It wouldn't change the package.json to resolve to `@as-pect/cli`. I think that this got very frustrating because there isn't a lot of documentation on exactly how to configure each package to run correctly.

I'm not even sure what I missed at this point.

**Comment by evocateur** [comment]
Why are you using `github:` references for local siblings? What does this accomplish?

**Comment by jtenner** [comment]
Absolutely nothing :).

What is the correct way to cause siblings to depend on each other?

**Comment by evocateur** [comment]
Just use the same version specifiers you would as if the packages were all living in their own repos (e.g., `"my-local-sibling": "^1.0.3"` where `my-local-sibling`'s version is 1.0.3). Lerna will find them, and update them appropriately when changes are detected.

**Comment by jtenner** [comment]
So in this case, I should use: `"@as-pect/core": "^2.1.4"`

Okay.

Will lerna pick up the `@as-pect` organization?

**Comment by evocateur** [comment]
Yep, it will handle the package scope just fine. The details of org membership are beyond the scope of Lerna, that's handled on the npm side (associated with your login token).
