### ISSUE TITLE
`lerna bootstrap` does not observe "files" field in package.json

### ISSUE THREAD

**Issue by arthur-chan-leapyear** [lerna/lerna#2184]
## Expected Behavior
I have the following directory structure
```
packages/
  library-1/
    package.json (that has "files": [ "dist" ] specified)
    src/source-code-lives-here
    dist/files-get-built-to-here
  library-2/
    package.json
    src/source-code-lives-here
    dist/files-get-built-to-here
apps/
  app-1/
    package.json
package.json (root level)
```

When I do `lerna bootstrap`, I want the `apps/app-1/node_modules/library-1` to point to `packages/library-1/src`.

## Current Behavior
When I set up `lerna` without yarn workspaces, I can get `lerna` to link and publish the `dist` folder in my packages. When I do a `lerna bootstrap`, it goes into each package, compiles it, and then in `app-1`, I can simply do an `import 'library-1/stuff'`.

This is great. Everything works the same in "dev" as it does in "prod," with the major annoyance being that I still have to bump package versions and `lerna bootstrap` any time I change the code in `library-1` or `library-2` before it's available in `app-1`.

So this is the problem that yarn workspaces was meant to solve.

I set up yarn workspaces by adding `"workspaces": [ "packages/*" ]` to my root level package.json, and it works nicely with lerna. Instead of building the packages, `lerna bootstrap` will link directly to the workspaces.

The one kink in all of this is that lerna has stopped observing the `files` field in the package.json. I can change the field to `src` instead but it just doesn't observe it at all. How are we supposed to have lerna link to a subdirectory in the package, instead of the package root?

## Possible Solution
* *Maybe* `lerna bootstrap` should observe the `files` field in the package.json, when yarn workspaces are used?

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*",
    "apps/*"
  ],
  "version": "independent"
}
```
</p></details>

## Context

We are trying to set up a mono-repo where we can develop our code without going through any publishing steps.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.15.0 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | 1.16.0 |
| `node --version` | v12.3.1 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.14.5 |

**Comment by evocateur** [comment]
`lerna bootstrap` has _never_ "observed the `files` field". Neither does `npm install`, for that matter.

When you use Yarn workspaces, `lerna bootstrap` is just calling out to `yarn`, it does nothing special. So I guess what I'm saying is, this is a Yarn bug, not a Lerna bug. That, or you're missing the appropriate lifecycle script.

> the major annoyance being that I still have to bump package versions and `lerna bootstrap` any time I change the code

That should, uh, never be necessary? It's half the reason to use a monorepo: local siblings can use up-to-date code without publishing. You need to fix your build (or watcher?), it sounds like.

**Comment by arthur-chan-leapyear** [comment]
Hmm... that was not the impression I got from this:
https://github.com/lerna/lerna/issues/1282

> That should, uh, never be necessary? It's half the reason to use a monorepo: local siblings can use up-to-date code without publishing. You need to fix your build (or watcher?), it sounds like.

Maybe there's some miscommunication here. Unless I'm using workspaces, when I do bootstrap, it seems that `lerna bootstrap` is going into each package and running `yarn build` in it. And this seems to be what other people experience as well:
https://hackernoon.com/4-ways-to-go-monorepo-in-2019-ea5d19fc1f08

**Comment by evocateur** [comment]
Presumably the build script is called from a `prepare` lifecycle? Which explains why it is being called by `lerna bootstrap`. (it does not call `yarn build` directly, trust me)

The issue you linked to requires [explicit config](https://github.com/lerna/lerna/tree/master/commands/publish#--contents-dir), it does not automagically happen just because you specify a `files` array.

**Comment by arthur-chan-leapyear** [comment]
Okay, well scratch that... I did it over in a newly cloned directory, without yarn workspaces. Lerna is linking to the package root. It's not doing any build or observing the package.json `files`. So, I don't know what I did the first time...
