### ISSUE TITLE
[docs] add `lerna run/list` with `--inculde-merged-tags` docs

### ISSUE THREAD

**Issue by Aqours** [lerna/lerna#2186]
## Expected Behavior
`lerna list --all --since` list changed packages

## Current Behavior
`lerna list --all --since` list all packages

## Possible Solution
`lerna list --all --since --include-merged-tags`. Now the `--include-merged-tags` only mention in @lerna/version docs.

## Steps to Reproduce (for bugs)

1. n/a
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "command": {
    "version": {
      "exact": true,
      "allowBranch": "master",
      "message": "chore(release): publish %s"
    }
  },
  "npmClient": "npm",
  "ignoreChanges": [
    "**/dist/**",
    "**/coverage/**",
    "**/LICENSE",
    "**/OWNERS",
    "**/*.txt",
    "**/*.log",
    "**/*.md",
    "**/.*",
    "yarn.lock",
    "package-lock.json"
  ],
  "version": "2.9.4"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context
All git tags are generated by lerna with gitlab merge request.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.15.0 |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
`--include-merged-tags` is only available from `lerna version` or `lerna changed`. There's no documentation to add.

**Comment by Aqours** [comment]
In my case, I can use lerna run or lerna list with --include-merged-tags, and it works fine.

**Comment by Aqours** [comment]
When run with this flag, lerna version will also consider tags of merged branches during package change detection.
———
I think lerna run and lerna list would detect package changes too.
