### ISSUE TITLE
Support for typescript packages

### ISSUE THREAD

**Issue by zkochan** [lerna/lerna#219]
I would love to use lerna in a typescript monorepo.

It shouldn't be hard to add typescript support. Currently lerna adds a "symlink-package" to `node_modules` to reference the package in the monorepo. It has only an `index.js`. If the package has a typings file, lerna could also add a "symlink" to that file. It would be an `index.d.ts` file like this:

```ts
export * from '/home/user/src/monorepo/packages/foo/index.d.ts'
```

I can work on a pull request, if you have no objection about this enhancement

**Comment by rygine** [comment]
this would be fixed using the updated bootstrapping process i've created.

more info here: https://github.com/lerna/lerna/issues/215

**Comment by zkochan** [comment]
OK, great! I think I'll keep it open till that one is done and a typescript strategy is implemented.

**Comment by thejameskyle** [comment]
If we are unable to get real symlinks working, I wouldn't mind a system for creating pseudo-linked files like this one, but I want it to be more generic.

**Comment by calebmer** [comment]
What’s the status on this?

**Comment by bradleyayers** [comment]
I'm also hitting the problem with trying to use TypeScript because everything from `package.json` is stripped except `name` and `main`.

I'm curious why real symlinks weren't/aren't a workable solution? Is there an issue specific to that that I can follow?

**Comment by zkochan** [comment]
Hey @calebmer and @bradleyayers!
I think we have to subscripb to this issue: [Nested directory support](https://github.com/lerna/lerna/issues/11)

**Comment by bradleyayers** [comment]
I propose we re-open this, as adding TypeScript basic support will be far easier than the nested directory support (which seems to have stalled for the moment). @zkochan's proposal is mostly good, but it doesn't cater for default exports, so instead the file should be:

```
import * as module from '/home/user/src/monorepo/packages/foo/index.d.ts';
export = module;
```

**Comment by bradleyayers** [comment]
I've added a PR for this, keen to hear thoughts.

**Comment by rygine** [comment]
@bradleyayers PR #237 has been very active lately and is ready for final review/merge. give it a try and see if it works for you!

**Comment by bradleyayers** [comment]
Have tried and can confirm it works for me! Thanks for pointing me in the right direction.

**Comment by danvk** [comment]
@bradleyayers @zkochan do you have examples you can point to of using lerna in a TS monorepo? Would be great to have a template for setting this up.

**Comment by zkochan** [comment]
Well, I created a sample of how pnpm can be used for a monorepo [here](https://github.com/rstacruz/pnpm/tree/master/examples/monorepo). I used lerna with pnpm for [this](https://github.com/mosjs/mos) project of mine, but I had to make a fork of lerna and replace npm usages with pnpm usages.

**Comment by xogeny** [comment]
No news on this?  I see that #237 is merged, but does that also resolve this issue?

**Comment by markvincze** [comment]
Was this issue fixed?
I'm not sure if it's the same thing or related, but I'm also struggling with a TS+lerna issue probably caused by symlinking, here is the issue with a compact repro: https://github.com/Microsoft/TypeScript/issues/20945

**Comment by evocateur** [comment]
It's effectively fixed if you `--hoist` or use yarn workspaces. Not a lot can be done to workaround the symlink issue for an unhoisted install.

**Comment by malbernaz** [comment]
I took me a while to figure out how to solve this issue, so I'm dropping here the solution I've found that is to set `moduleResolution` to "node" in your tsconfig.json. Maybe it can help someone.
