### ISSUE TITLE
allow lerna to specify the config file

### ISSUE THREAD

**Issue by vlavella** [lerna/lerna#2191]
I know it has been multiple conversations around this, and those petitions have been rejected.
On my case, I have one monorepo that worked perfect and we love lerna but when you try to deploy this on some using tools such a stackery, lerna force us to create workarounds like indicating build paths in order to be able to deploy the packages (this is because the way commits hooks works).
That is a little hacky and can be easily prevented by allowing users to indicate the alternative lerna.json to handle it. Which is at least the way we have to handle it (just replacing the package).

**Comment by evocateur** [comment]
For the <i>n</i><sup>th</sup> time, Lerna is not a deployment tool.

You should be creating a deployable artifact (tarball) using npm to install the packages that Lerna helps publish, not expecting `git clone <my monorepo> && lerna ...` to do that for you.

**Comment by vlavellauruit** [comment]
I'm not saying that Lerna is a deployment tool. I'm not sure when you understood that, but I wasn't the idea. 
I just was pointing another scenario when this small feature will be useful. 
1. We wrote code on a mono repo, 
2. We use Lerna to share our common packages
3. We need to deploy our code.
4. We use Stackery for deploy and Lerna has some limitations that make hard to deploy using aws code build, that's it.

I think that Lerna is a great tool and thanks for pointing me how to deploy my code, but I don't think that you've tried to understand this scenario (or the other that the community asked).
