### ISSUE TITLE
`lerna publish --canary` doesnt upgrade private packages

### ISSUE THREAD

**Issue by dizel3d** [lerna/lerna#2206]
`lerna publish --canary --no-git-reset --force-publish` doesn't upgrade versions of private packages nor update their dependencies.
By **private** package I mean `"private": true` in `package.json`.

I have a private package `app`. `app` depends on a public package `lib1`. `lib1` depends on a public package `lib2`.
The command above is called on CI. It upgrades `lib1` and `lib2`, but doesn't upgrade `app`. Then CI builds new docker image from `app` with outdated `lib1`.

## Expected Behavior
The command should upgrade package `app` as well.

## Current Behavior
The command doesn't upgrade package `app`.

## Possible Solution
As workaround we can use some hack based on `lerna version` or not use private packages.

## Steps to Reproduce (for bugs)
1. Create a monorepo with packages: `app` (private), `lib1` (public) and `lib2` (public). Make `app` depend on `lib1`, `lib1` depend on `lib2`.
2. Call `lerna publish --canary --no-git-reset --force-publish`

`app/package.json` won't be changed.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
</p></details>

## Context
I want CI build a docker image in nightly builds.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.16.0 |
| `node --version` | 8.14.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.6 |

**Comment by dizel3d** [comment]
Here is my workaround:
```
lerna version prepatch --yes --exact --no-commit-hooks --no-push --no-git-tag-version --no-changelog --allow-branch ${branch} --preid ${branch}-${sha} --force-publish ${changedPackages}
git commit --no-verify --allow-empty -am canary
lerna publish from-package --yes
git reset --soft HEAD~1
```

**Comment by evocateur** [comment]
That's not what `lerna publish --canary` is for. It is non-sensical to "publish" packages that are private.

**Comment by dizel3d** [comment]
> That's not what lerna publish --canary is for. It is non-sensical to "publish" packages that are private.

No, I don't want private packages to be published. But I want them to be bumped.

**Comment by evocateur** [comment]
Lerna isn't a deployment tool.

**Comment by dizel3d** [comment]
`--no-git-reset` description:
```
By default, lerna publish ensures any changes to the working tree have been reset.

To avoid this, pass --no-git-reset. This can be especially useful when used as part of a CI pipeline in conjunction with the --canary flag. For instance, the package.json version numbers which have been bumped may need to be used in subsequent CI pipeline steps (such as Docker builds).
```

So it is absolutely my case. Do you agree? And it lt's not obvious that the option doesn't suit for private packages. `lerna version` bumps private packages. So I think `lerna publish --canary --no-git-reset` should bump them as well. Why not?

How to make `--canary` version of a private package?

**Comment by evocateur** [comment]
Yes, I (regrettably) gave in to the whinging in that case. It still doesn't change the fact that Lerna is not a deployment tool. Re-think why you _need_ a private package at all, I'm willing to bet you can find a solution that doesn't need this existential weirdness.

`--canary` when the package is private is non-sensical, and isn't happening.
