### ISSUE TITLE
Lerna bootstrap not working

### ISSUE THREAD

**Issue by Gum-Joe** [lerna/lerna#221]
Hi,
When attempting to use lerna in my project ([`bedel`](https://github.com/Gum-Joe/bedel)), I found `lerna bootstrap` did not link my packages.
The `name` field in my `package.json` is set to `bedel`, with the installed dependency I am trying to link called `bedel-logger`.

Specs:

- **OS:** Windows 10
- **Lerna Version:** `^2.0.0-beta.20`
- **Project url for `bedel`:** https://github.com/Gum-Joe/bedel (not on `npm`)
- **Dependency I am trying to install:** https://github.com/Gum-Joe/bedel-logger (on `npm`)

Thanks in advanced!

**Comment by thejameskyle** [comment]
Why don't you have a packages directory?

Lerna does not link across separate repos, if thats what you are trying to do then you are misusing it.

**Comment by Gum-Joe** [comment]
I have a packages directory, but not commited as it is empty.
Do I have to put the package in my repo for development, instead of a separate repo?
Here what I thought the process was:

- Put package in a repo
- Publish to `npm`
- Add to lerna

**Comment by thejameskyle** [comment]
Lerna is a tool for managing single repositories with many packages.

**Comment by Gum-Joe** [comment]
Got error -4058

**Comment by thejameskyle** [comment]
Idk what that means

**Comment by cchamberlain** [comment]
@thejameskyle 

I'm getting similiar results converting to a lerna monorepo on Windows 10. The commands were working from OSX last night but I get the error -4058 on Windows.

![image](https://cloud.githubusercontent.com/assets/424694/16095649/70530784-32fa-11e6-89c2-265a1d60259d.png)

![image](https://cloud.githubusercontent.com/assets/424694/16095718/ca283112-32fa-11e6-92e9-e680ecb95dc5.png)


**lerna-debug.log in top level**
```
lerna(info)    Lerna v2.0.0-beta.20
lerna(debug)   Attempting running BootstrapCommand.initialize
lerna(debug)   Successfully ran BootstrapCommand.initialize
lerna(debug)   Attempting running BootstrapCommand.execute
lerna(info)    Linking all dependencies
lerna(error)   Errored while running BootstrapCommand.execute
    -4058
```

**es-proxy package.json deps**
![image](https://cloud.githubusercontent.com/assets/424694/16095769/02669546-32fb-11e6-8fa8-0f07a86a331d.png)

**koaproxy-core package.json header**
![image](https://cloud.githubusercontent.com/assets/424694/16095792/224cab52-32fb-11e6-9bc8-95ba87488875.png)


**versions**
![image](https://cloud.githubusercontent.com/assets/424694/16095831/43697a90-32fb-11e6-982c-babe0c06846a.png)

**Comment by hzoo** [comment]
Was it because of `sync-exec`? What happens on beta.19?

**Comment by cchamberlain** [comment]
Yes.

![image](https://cloud.githubusercontent.com/assets/424694/16096022/fb1bb9f0-32fb-11e6-81e8-b29dc9485564.png)

Thank you!

**Comment by hzoo** [comment]
https://github.com/lerna/lerna/pull/220/files - need to look at this again I guess? It's checking if `child.execSync` is defined, otherwise not so I don't see why that would change any behavior. Maybe a publishing issue

**Comment by cchamberlain** [comment]
Oh wow `0.10`, how legacy.

**Comment by cchamberlain** [comment]
Maybe a `const hasExecSync = !/v0\.1?[01]\.[0-9]+/.test(process.version)` test instead?

**Comment by ifiokjr** [comment]
I'm still seeing this issue within a new lerna based repo on Windows 7. 

`lerna bootstrap` fails for me. 

```
{
  "lerna": "2.0.0-beta.23",
  "version": "0.0.0"
}
```

**Comment by thejameskyle** [comment]
This issue is a mess, for help with the `-4058` error go to #226. If you have a problem with something else, search for an issue and if it doesn't exist create a new one.
