### ISSUE TITLE
`postpublish` in root does not run after publish successfully on CI

### ISSUE THREAD

**Issue by JounQin** [lerna/lerna#2210]
## Expected Behavior

Run `postpublish` lifecycle script

## Current Behavior

Does not run

https://travis-ci.com/rx-ts/eslint-mdx/builds/121870771#L455-L457

## Steps to Reproduce (for bugs)

1. `prepublishOnly`: `lerna version "$(jq -r '.version' package.json)" --amend --yes`
2. `lerna publish from-package --amend --yes`
3. `postpublish`: `git push --follow-tags origin $TRAVIS_BRANCH`

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "$schema": "http://json.schemastore.org/lerna",
  "version": "0.9.3",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "graphType": "all"
    },
    "version": {
      "allowBranch": "master"
    }
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.10.2 |
| `yarn --version` | 1.17.3 |
| `node --version` | v12.7.0 |

| OS | Version |
| --- | --- |
| linux/amd64
 | 18.06.0-ce |

**Comment by evocateur** [comment]
Dunno what to tell you, it certainly [does work](https://github.com/lerna/lerna/blob/c5676bb69f1d52006084e544016a97c7d58706a3/integration/lerna-publish-lifecycle-silent.test.js#L43). It looks like you're doing a lot of very hacky things.
