### ISSUE TITLE
Possibility to run lerna command in changed packages only

### ISSUE THREAD

**Issue by Und3Rdo9** [lerna/lerna#2211]
Is it possible to somehow pass the result of `lerna changed` to `lerna run --scope` or `lerna exec -- --scope`  ? 
It seems like lerna already does all the git magic necessary to get the packages that changed, but how can you easily use this result to run commands (for example I want to deploy to netlify instead of publish to npm or only run tests in my ci in changed packages) without getting the previous git tag manually yourself (if you are on master branch) to use with the `since` flag or comparing to master using `since` if you are on a feature branch?

## Expected Behavior
Allow multiple packages to be passed to scope filter or allow lerna changed to be used in conjunction with a flag like `since` for example.

## Current Behavior
It does not, see above.

## Possible Solution
See expected behavior.

**Comment by csi-lk** [comment]
Came across this when searching for the same thing, method seems to be to use [`lerna run` with `--since` flag](https://github.com/lerna/lerna/tree/master/core/filter-options#--since-ref)

eg

```
lerna run test --since master
```

you don't need to run `lerna changed`

**Comment by Und3Rdo9** [comment]
In my case, how would this work if I am already on `master`? But I want to run in changed packages since the last tag, without first fetching the last tag?

**Comment by csi-lk** [comment]
Maybe I've misunderstood, if you're up to date with master, then change the 'foo' package then run `lerna run test --since master` it will run the npm script `test` within the 'foo' scope only

**Comment by somenathghosh** [comment]
lerna run test --since master does not work on master branch. What is the solution do I have to run commands only for changed packages?

**Comment by evocateur** [comment]
It's right there in the [docs](https://github.com/lerna/lerna/tree/master/core/filter-options#--since-ref):
> If no ref is passed, it defaults to the most-recent tag.

When in `master`, `npx lerna run test --since` will do what everyone in this thread seems to want.

**Comment by phun-ky** [comment]
@evocateur I'm interested in something similar, how do I run lerna command (or npm command) in only on packages with non-commited changed files?

**Comment by evocateur** [comment]
@phun-ky You can pass `--since HEAD` to `lerna exec` or `lerna run` to do that. I don't believe `npm` itself has this capability, though you could call `npm` in each changed root with `lerna exec`, e.g. `lerna exec -- 'npm v $LERNA_PACKAGE_NAME dist.tarball'`.

**Comment by prajaktagharpure** [comment]
@evocateur on trying to run `lerna exec test --concurrency 1 --stream --since HEAD` in husky pre-commit hook, it errors out with the below error 

>  git commit -m "TEST"           
husky > pre-commit (node v10.15.3)
lerna notice cli v3.20.2
lerna ERR! ENOGIT The git binary was not found, or this is not a git repository.
husky > pre-commit hook failed (add --no-verify to bypass)
error Command failed with exit code 1.

I might be missing something really basic or obvious? Not sure why it should complain about not being a git repo when it is. git binary file exists in the utmost root folder. I have my apps and various dependencies from a single folder that sits 2 below the utmost root folder. Wonder if thats conflicting with something?

**Comment by stefaneg** [comment]
The ```--since``` option does not work with Jenkins, while ```lerna changed``` does. This is probably because Jenkins checks out commits, not branches, resulting in a detached head state. So I would suggest this to be a valuable parameter to have.

**Comment by latica-jp** [comment]
The `--since` options seem to ignore private packages, so how can we include private packages as well?

**Comment by matthieusieben** [comment]
`lerna changed `, under the hood, performs `git describe --always --long --dirty --first-parent` to get the last tag.

We can leverage that to perform the same behavior:
```
lerna run test --since $(git describe --always --long --dirty --first-parent | sed -e 's/-[0-9]-g[^-]*$//g')
```
