### ISSUE TITLE
[Feature] Option to skip devDependencies with lerna bootstrap

### ISSUE THREAD

**Issue by onplanetnowhere** [lerna/lerna#2212]
Same as #505, however the original feature request was closed without a good resolution. There is no way to only bootstrap normal dependencies during production, because regardless of options, lerna will always bootstrap all packages, dev or not, into the root under normal dependencies. Thus, doing `lerna bootstrap -- --production` has no effect as devDependencies are included in dependencies. This has issues such as inflating docker image size due to installing all devDependencies.

The only way to achieve this is to move all devDependencies to the root and use npm arguments in the lerna command. It has been recommended to use `lerna link convert` instead, however it is preferable that the devDependencies remain in the original packages so that they are clearly separated.

Perhaps there is another way to do this I am not aware of, or am I not doing this the correct way?

**Comment by hannadrehman** [comment]
i am using yarn and `lerna bootstrap --production` is skipping some dependencies like `@babel/preset-env` .

**Comment by evocateur** [comment]
> it is preferable that the devDependencies remain in the original packages so that they are clearly separated

You should move your `devDependencies` to the root, it's really nice to deal with them all in one place. If your `devDependencies` _can't_ do that, that's an indication you have too many divergent packages in your monorepo.

You also shouldn't expect Lerna to manage your Docker image, that's not it's purpose. You should be using good ol' `npm install` in a separate directory to create your "production" builds, like [serverless-jetpack](https://github.com/FormidableLabs/serverless-jetpack) does.

**Comment by felixhayashi** [comment]
> You should move your devDependencies to the root, it's really nice to deal with them all in one place. If your devDependencies can't do that, that's an indication you have too many divergent packages in your monorepo.

Please correct me if I misunderstood your point but every monorepo that comes with at least a frontend and a backend already includes a fairly diverged set of dev dependencies. So I would argue that divergent dev packages are fairly common naturally.

Moving all dev-dependencies to the root makes it really hard to understand and maintain those dev dependencies, especially nowadays with the zillion packages involved in a compilation process. It also violates the idea that every project is meant to be consistent in its setup.

It also creates some kind of locked-in syndrom: If one moves all dev dependencies to the root and after a while needs to outsource a project from the monorepo – e.g. to turn it into an external library in a separate git project – one now has to spent much unecessary time evaluating which dev packages need to be carried over, something that courld have been avoided in the first place.

**Comment by TrejGun** [comment]
same issue.. should be an option to strictly distinct devDependencies from hoisted installation
