### ISSUE TITLE
[feature request]scope alias

### ISSUE THREAD

**Issue by kgtkr** [lerna/lerna#2213]
When a package name is long, it is difficult to enter a long package name when executing run or exec.

example:

```sh
$ lerna run --scope @scope/longlonglong-package-name build
```
So I want a scope name alias feature

**Comment by evocateur** [comment]
You can use globs, you know.

https://github.com/lerna/lerna/blob/bb048cb306b5cfcb039aa98f667cf3751cf0ad20/core/filter-options/__tests__/get-filtered-packages.test.js#L56-L64
