### ISSUE TITLE
Bootstrap with hoist deletes package if local dependency cannot be fulfilled

### ISSUE THREAD

**Issue by mr-flannery** [lerna/lerna#2215]
Suppose I have a project with two packages, `one@1.0.0` and `two@0.1.0`. Now add a dependency `two@1.0.0` to package `one`. This dependency cannot obviously not be fulfilled, since there is no `1.0.0` of `two`.
If I run `lerna bootstrap`, I get an error saying that the dependency cannot be found.
If I run `lerna bootstrap --hoist`, I get the same error, and suddenly package `two` is deleted from my filesystem!

## Expected Behavior
I expect `lerna bootstrap --hoist` to fail without deleting my code.

## Current Behavior
`lerna bootstrap --hoist` deletes the local package.

## Possible Solution
My hypothesis is that his has something to do with symlinks, but ultimately the fix should just be that bootstrap does not delete stuff from the project.

## Steps to Reproduce (for bugs)

https://github.com/mr-flannery/bootstrap-hoist-bug

1. clone repo
2. cd into folder
3. `(npx) lerna bootstrap --hoist`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "1.0.0"
}
```
</p></details>

## Context

To be honest, the whole reason that this even occurs in our project is that we have a lot of generated packages that are not managed by git, which is the reason why this inconsistency happens in the first place. Working around this is easy for us, but I guess that bootstrap deletes local code is still not intended.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.5.0-next.0 |
| `node --version` | v11.6.0 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.5 |

**Comment by evocateur** [comment]
I don't recommend using `lerna bootstrap`, it's a bunch of hacks on top of hacks that are largely unnecessary when Yarn workspaces and `pnpm recursive` exist. (maybe one day NPM workspaces, lol)

**Comment by mr-flannery** [comment]
What about adding this to the documentation then?

**Comment by evocateur** [comment]
That would be great.
