### ISSUE TITLE
Lerna version not triggering CI with more than three tags at once

### ISSUE THREAD

**Issue by iurykrieger** [lerna/lerna#2218]
I have a monorepo containing four packages. One of the four packages is used as a dependency for the other three packages, so when you made changes to this dependency package, `lerna version` will generate one tag for each of the four packages.

The problem happens when all these four tags are pushed to Github since Github has [this limitation](https://developer.github.com/v3/activity/events/types/#createevent) for [CI hooks](https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag) based on the number of tags pushed at the same time. Since `lerna version` pushes all the generated tags at once, Github doesn't trigger any webhooks for CircleCI, which happens to be unable to trigger any workflows based on those tags.

## Expected Behavior
`lerna version` command should have an option to push tags in serial mode, avoiding the Github limitation, once said that is expected from a monorepo to generate more and more tags based on the number of its packages.

## Current Behavior
Currently, `lerna version` will push a `Publish` commit with all the generated tags at once. We're using those generated tags to trigger [specific workflows](https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag) at CircleCI.

## Possible Solution
I think the best solution here is to create a `lerna version` option to push generated tags in serial mode, avoiding this [Github limitation](https://developer.github.com/v3/activity/events/types/#createevent).

## Steps to Reproduce (for bugs)

1. Create any GitHub webhook version listener (CircleCI tag workflows or any other)
2. Use lerna `independent` versioning mode
3. Generate changes for more than three packages
3. Use `lerna version` to `git push` the four tags at once
4. You'll see that the Github will not notify the webhook listener

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.9.0 |
| `node --version` | v10.16.1 |

| OS | Version |
| --- | --- |
| Ubuntu | 16.10 |

**Comment by evocateur** [comment]
Or just use the default "fixed" versioning scheme? It only generates one tag per publish.

**Comment by tpluscode** [comment]
How is this closed? `version: independent` and one will often run into a >3 new tags scenario

**Comment by dnln** [comment]
For anybody else who ends up here, here's my super hacky workaround:

`push-tags-one-by-one.sh`
```bash
#!/bin/bash

# get all tags on this commit
TAGS=$(git tag --points-at HEAD | cat)

# only push tags one by one if there are more than 3
if (($(echo "$TAGS"| wc -l) > 3))
then
  echo "Pushing tags one by one to avoid GitHub webhook limit of 3"
  echo "$TAGS" | while read line ; do git push origin $line; done
fi
```

`package.json`
```json
{
  ...
  "scripts": {
    "postversion": "./push-tags-one-by-one.sh"
  },
  ...
}
```

This pushes the tags one at a time (where there are more than 3) after Lerna tags the commit but before it pushes all tags at once.

**Comment by mikob** [comment]
@dnln  thanks!

I also added `--no-follow-tags` to the `do git push origin...` line to make it explicit, because my local git config has follow tags on, and it would make all the tags push at once with the first iteration of the loop.

**Comment by dnln** [comment]
Hey @JamesHenry. Thanks for picking this up. I'm very happy for that to be added to the docs, but I also wonder whether a `--push-tags-one-by-one` (or similar) option on `publish` which automatically does this in the background might be neater?

However, as you say, this is a GitHub limitation not a Lerna one, so perhaps a documented work around is all that's needed  for now.

**Comment by vitebo** [comment]
It looks like we've got [this beta feature](https://github.blog/changelog/2022-06-15-block-potentially-destructive-git-pushes/) on GitHub to work around that issue now.

![image](https://github.com/lerna/lerna/assets/19560693/09e2a398-24f1-45c0-8d99-6fe5367f8436)

**Comment by StarpTech** [comment]
@vitebo I tested the beta feature but it didn't work. I set the limit 10 and pushed 5 tags. No trigger.
