### ISSUE TITLE
Lerna used in non conventional commit workflow not supported when manually selecting prerelease version and bump to release in CI

### ISSUE THREAD

**Issue by aarym** [lerna/lerna#2219]
In a Developer / Release workflow, where a developer manually selects the prelease version using lerna version, and the CI process automatically publishes the prerelease version to release version when merging to master.

See below steps for full workflow. It would be good if lerna version could work better with lerna publish and see the prerelease is from git and to enable publish to npm with the release version without having to go and manually do this in lerna version for a new commit.

## Expected Behavior

Step 7. ci triggers build and publish to npm feed without the preid (when the version is non prerelease)

## Current Behavior

1. developer creates branch from master & commits change to local git
2. developer runs `lerna version prerelease`
3. developer commits & pushes to origin
4. ci triggers build and publish to our npm feed `lerna publish from-git --yes`
5. npm feed now has pre release version
6. developer merges branch to master
7. ci triggers build and publish to npm feed but doesn't recognise any changes

## Possible Solution

The issue here is, we're wanting developers to think about the version. We could go down the conventional commit path for this & considering this. But right now once prerelease is done, we want to run publish command in ci for the release version & not have to make any changes in the repo to force this through another version selection (no prerelease).

Another option I looked at without conventional commits is to use
1. `lerna publish --canary`
2. `lerna publish --yes`

But in CI situation I want the `lerna pubish --yes` to publish the canary release without the preid, i.e. canary is 1.0.1-alpha.0 and once in master to be 1.0.1

## Steps to Reproduce (for bugs)

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

As above this seems like a workflow limitation for a common developer release process.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | v3.13.1|
| `npm --version`  | 6.4.1|
| `yarn --version` | n/a|
| `node --version` | v10.13.0|

| OS | Version |
| Windows 10 | 1607 |
-->

**Comment by aarym** [comment]
@evocateur wondering if I can gain your expertise in this one? If valid use case around managing packages through git/tags with version prerelease and enabling bumping to release like publish canary then happy to perhaps work on this one to contribute to this great library.

**Comment by evocateur** [comment]
This use case isn't really supported right now. There are lots of hacks to make it kinda-sorta work, but they're all working "against the grain" of Lerna's core.

I have tentative plans for a `lerna release` subcommand that would address some of the issues you've described, but I can't give a timetable for its availability.

In the meantime, I would recommend investing in conventional commits. They do a great job of "[making] developers [think] about the version", in my experience.
