### ISSUE TITLE
[Feature] Copy checks from np

### ISSUE THREAD

**Issue by jamiebuilds** [lerna/lerna#222]
We should do all the same checks before publishing as https://github.com/sindresorhus/np

**Comment by bertho-zero** [comment]
I find this idea cool, is there news about that?

**Comment by evocateur** [comment]
I assume he meant the checks in https://github.com/sindresorhus/np/blob/master/lib/prerequisite.js, which seem very reasonable to me.

**Comment by bertho-zero** [comment]
I was looking for a practical release manager, I finally turn to [semantic-release](https://github.com/semantic-release/semantic-release) in the hope that one day it will support lerna.

Thanks @evocateur
