### ISSUE TITLE
Relative glob patterns don't permit matching parent directories 

### ISSUE THREAD

**Issue by jpettit** [lerna/lerna#2220]
The docs state that lerna accepts globs relative to `lerna.json`.  I couldn't find anything that discusses glob patterns matching parent directories.

EDIT: I see that the `list` command doesn't have any test cases for packages in parent directories, and doing a simple `lerna la` also does not find packages residing in relative parent directories.

## Expected Behavior
Lerna version can match a glob pattern to a parent directory relative to `lerna.json` such as: `.?/packages/foo/*` that would find a package.json in: `../packages/foo/package.json`

## Current Behavior
The lerna version command does not match relative glob patterns to parent directories relative to `lerna.json`.

## Possible Solution
😿 

## Steps to Reproduce (for bugs)
Setup a basic lerna project with the following directory structure, then run `lerna version --force-publish`

```bash
Users/jpettit $ mkdir myproject myproject/packages myproject/packages/foo myproject/lerna_root
Users/jpettit $ touch myproject/packages/foo/package.json myproject/lerna_root/lerna.json
Users/jpettit $ cd myproject/lerna_root/
drwxr-xr-x  3 jpettit  staff   96 Aug  9 09:02 .
drwxr-xr-x  4 jpettit  staff  128 Aug  9 09:02 ..
-rw-r--r--  1 jpettit  staff    0 Aug  9 09:02 lerna.json

myproject/lerna_root $ echo .?/packages/foo/*
../packages/foo/package.json
```

## Context
In my project I'm trying to glob pattern match to the following relative path: `../.hidden/package/package.json`.  I've also tried making the `.hidden` directory not hidden to no avail.  I can't seem to get `lerna version` to find anything in a parent directory.

## Your Environment

```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

| Executable | Version |
| ---: | :--- |
| `npx lerna --version` | 3.16.4 |

| OS | Version |
| --- | --- |
| Ubuntu | 18.04.2 LTS |
-->

**Comment by evocateur** [comment]
Wherever the `lerna.json` is found is considered the "root" in terms of package globbing. Going "above" that location is not supported.
