### ISSUE TITLE
type-checking fails when importing working project

### ISSUE THREAD

**Issue by erikdstock** [lerna/lerna#2221]
I'm trying to combine https://github.com/erikdstock/roses and its documentation site into a single repo. Typechecking is fine in my lone repo, but after doing `lerna import ../roses` and bootstrapping, I get a number of type-checking errors.

## Expected Behavior

Typechecking passes, same as it does on my no-lerna branch.

## Possible Solution

Something is wrong about my config
I need to understand setup better.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.2.6",
  "useWorkspaces": true,
  "npmClient": "yarn"
}
```
</p></details>

## Context

I also have it set up with npmClient yarn and workspaces, and I have tried moving my tsconfig file up (so its `exclude` key would be next to the node_modules folder). That didn't seem to help. I've also re-set it up several times trying with `bootstrap --hoist` and `import --flatten`

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `yarn --version` | 1.17.3 |

**Comment by evocateur** [comment]
TypeScript errors are not a Lerna problem. Try [Project References](https://www.typescriptlang.org/docs/handbook/project-references.html) for starters.
