### ISSUE TITLE
[question] merging after lerna version breaks later publish, tags aren't recognized

### ISSUE THREAD

**Issue by MirKml** [lerna/lerna#2222]
I use `lerna version` locally in my branch as recommended. This branch is later merged through pull request on Azure DevOps into master and on this master I tried to run `lerna publish from-git` but no tags are recognized.
command 

    git tag --sort version:refname --points-at HEAD

on master writes nothing.

I saw that it's caused by merging master into my branch after `lerna version`, because there where some conflicts in pull request.
Then tags aren't on HEAD but after some commits which are from merged master.

What's is your recommendation for such situations, when `lerna version` in branch is used but later merging master (or another commits) is necessary? Remove tags? Always rebase?

Thanks.

**Comment by evocateur** [comment]
You probably need `lerna publish from-package` in master, if you persist with mangling your tags via merging. I don't recommend tagging in feature branches, basically.
