### ISSUE TITLE
publish command does not have --git-remote option

### ISSUE THREAD

**Issue by Glen-Moonpig** [lerna/lerna#2223]
The **publish** command uses the **version** command but does not pass through the --git-remote option, so I am unable to specify a remote name.

## Expected Behavior

The publish command should have a --git-remote option and pass the value through the version command.

## Current Behavior

There is no way to specify a remote during publish

## Possible Solution

Add a --git-remote option and pass the value value through the version command.

## Context

I don't want to overwrite the origin remote, I want to add a new remote for use with the publish command.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.8.1 |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
As [documented](https://github.com/lerna/lerna/blob/b62088e873b71bbac0f6325394d16542c4551deb/commands/publish/README.md#options):
> `lerna publish` supports all of the options provided by [lerna version](https://github.com/lerna/lerna/tree/master/commands/version#options) in addition to the following:

So yes, it most definitely _does_ accept the `--git-remote` option, at least for Lerna 3.x. You should update your version of Lerna, [3.8.1](https://github.com/lerna/lerna/releases/tag/v3.8.1) is fairly ancient.

**Comment by Glen-Moonpig** [comment]
> As [documented](https://github.com/lerna/lerna/blob/b62088e873b71bbac0f6325394d16542c4551deb/commands/publish/README.md#options):
> 
> > `lerna publish` supports all of the options provided by [lerna version](https://github.com/lerna/lerna/tree/master/commands/version#options) in addition to the following:
> 
> So yes, it most definitely _does_ accept the `--git-remote` option, at least for Lerna 3.x. You should update your version of Lerna, [3.8.1](https://github.com/lerna/lerna/releases/tag/v3.8.1) is fairly ancient.

Ok _bro_. It most definitely _did not_ though when I was looking at it.

**Comment by evocateur** [comment]
The line I referred to was added [over a year ago](https://github.com/lerna/lerna/commit/8b97394f5e84eea15de06efd238daa57ccde1446#diff-afd35d92053195d1f03497360645ac8b).
