### ISSUE TITLE
Question: unhoist specific package for specific module

### ISSUE THREAD

**Issue by georgyfarniev** [lerna/lerna#2227]
Hello. How can I unhoist external dep only for specific module inside my monorepo, not all of them? If I just specify different version in my module package.json, I get the following warning:

`lerna WARN EHOIST_PKG_VERSION "@myns/mypackage" package depends on css-loader@^2.1.1, which differs from the hoisted css-loader@^3.0.0.`

What is the proper way to do it? Thanks in advance :)

**Comment by evocateur** [comment]
That's just a warning, not an error. It will behave as you desire, it's warning because that's often _not_ what you want to have happen when hoisting dependencies.

**Comment by georgyfarniev** [comment]
@evocateur I understand it, but there's no way to tell lerna that I want it, to suppress warning when I want to do this explicitly.
