### ISSUE TITLE
Option to upload packages to a different registry

### ISSUE THREAD

**Issue by Ceane** [lerna/lerna#223]
At my company, we have our npm packages hosted on [Gemfury](https://gemfury.com/help/npm-registry). I'm not sure of any registries that others are using, however I propose support for publish plugins, that way others can extend the process more easily.

**Comment by hzoo** [comment]
Can you not modify this in a .npmrc or something or does this have to be a lerna config change?

**Comment by rygine** [comment]
If you don't want to set your registry globally in `.npmrc`, you can use the `publishConfig` key in `package.json` to set a registry per package.

https://docs.npmjs.com/files/package.json#publishconfig

**Comment by Ceane** [comment]
@rygine Currently researching this right now, however I don't want to put the Gemfury key in the package.json, I think I may be onto a way to publish this with the scoped package's registry being referenced in the `.npmrc`. Right now I'm getting failures saying I'm not an auth'd user

**Comment by Ceane** [comment]
@hzoo I don't think that this is easy as `.npmrc` configuration. I've already got the registry set to point to Gemfury, however Gemfury doesn't have a CouchDB interface, as expected of `npm`, so any requests fail. I think a PR for this would be easier, but that would require a change to lerna that I think we will have to discuss before I blindly submit a solution.

**Comment by thejameskyle** [comment]
Put it in your [`package.json#publishConfig`](https://docs.npmjs.com/files/package.json#publishconfig) for each package

**Comment by gigabo** [comment]
> Put it in your package.json#publishConfig for each package

Packages are not always tied to one registry.

We _usually_ publish to the public registry, but _sometimes_ publish a private registry.

When we publish to our private registry we do:

```sh
$ npm config set registry <private-registry>
$ lerna publish
$ npm config set registry https://registry.npmjs.com
```

Not ideal, but it works.

**Comment by Ceane** [comment]
@thejameskyle Gemfury works differently than npm expects, unfortunately all of the solutions above fail. It is very simple, you compress your package with `npm pack` and then push it to the server using the URL that has your account name and API key.

**Comment by thejameskyle** [comment]
Oh geez, they really should just use the built in way of publishing packages to other registries. I'm not sure something like that should be supported. The publish process is complicated enough

**Comment by Ceane** [comment]
I agree. I've sent them an email to see if they would like to fix this.

**Comment by Ceane** [comment]
[Gemfury documentation now highlights support for `npm publish`](https://gemfury.com/help/npm-registry) closing this issue!

**Comment by markolofsen** [comment]
It's really easy if are you using special tool for publications.
It's works in your browser, without any special dependencies.

Try this library for that https://github.com/markolofsen/how_to_upload_package_to_npm
