### ISSUE TITLE
When publihing several packages, some packages gets published to the same package

### ISSUE THREAD

**Issue by oskarkvamme** [lerna/lerna#2231]
##  Expected Behavior
When I publish several packages to Github package registry in one go, I expect that the assets is published to the correct packages.

## Current Behavior
Some packages gets assets from several packages, and some have no assets. The assets from the packages that has no assets I have found on the packages that have several assets.

When I try to install a package with no asset I get a status code 404, and when I try to install a package which have several packages I get status code 409.

Im not sure if its a bug in lerna or a bug in the Github package registry (which is in beta).

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.16.4",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "command": {
    "publish": {
      "npmClient": "npm",
      "verifyAccess": false,
      "allowBranch": [
        "master",
        "v*.x"
      ],
      "conventionalCommits": true,
      "ignoreChanges": [
        ".eslintrc",
        ".gitattributes",
        ".gitignore",
        ".npmignore",
        ".npmrc"
      ],
      "message": "chore: publish"
    }
  }
}
```
</p></details>

## Context
Trying to publish my monorepo to Github package registry

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | 1.17.3 |
| `node --version` | 10.16.0 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.5 |

**Comment by evocateur** [comment]
Without an example reproducing this error I (nor anybody else) cannot help you.
