### ISSUE TITLE
Lerna import is too opinionated

### ISSUE THREAD

**Issue by anand-sundaram-zocdoc** [lerna/lerna#2232]
## Expected Behavior
Suppose my lerna.json has ```"packages": ["packages/**"],```.
If I run:
```lerna import ../original_foobar --dest="packages/components/foobar"```

Ideally I would like this to import all the code with commit history from the original_foobar directory into a newly created directory called components/foobar.

## Current Behavior
Instead of the desired behavior I described, lerna import will:
1) complain that "packages/components/foobar" is not a packages directory, even though it is within the packages directory
2) not support moving the code except into a destination directory that is named the same as the source directory

## Workaround
To make it work how I wanted, I had to:
1) rename original_foobar to foobar on my machine first before running lerna import
2) Change lerna.json to have "packages/components/foobar/**" as an additional entry in the packages list
3) Run lerna import lerna import ../foobar --dest="packages/components"
4) Change the lerna.json back because that's just silly

## Possible Solution
We could:
1) Change the implementation of the package directory validation check in https://github.com/lerna/lerna/blob/bb048cb306b5cfcb039aa98f667cf3751cf0ad20/commands/import/index.js#L65 to allow subdirectories of a package directory to be chosen as targets
2) change https://github.com/lerna/lerna/blob/bb048cb306b5cfcb039aa98f667cf3751cf0ad20/commands/import/index.js#L71 to make the target dir name customizable instead of just forcing it to be the name of the source directory

## Steps to Reproduce (for bugs)
N/A; see expected behavior above.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/**"
  ],
  "version": "independent",
  "command": {
    "publish": {
        "allowBranch": "master"
    },
    "version": {
        "allowBranch": "master",
        "conventionalCommits": true,
        "message": "chore(publish): update versions"
    }
  }
}

```
</p></details>

## Context
I want to move code into a monorepo, but instead of moving it from the source repo into the monorepo as one package, I want to move different subfolders of a single source repo into the monorepo as separate subpackages. Lerna import does not handle this use case so I have been hacking together a combination of git subdirectory filters on the source repo followed by lerna imports. Trying to make Lerna support handling all the work for my desired code migration strategy cleanly would be way more ambitious; all I'm looking for here is buy-in to make the import command a little easier to use.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.9.0 |
| `node --version` | v12.1.0 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.6 |

**Comment by evocateur** [comment]
`lerna import` _is_ an opinionated wrapper around `git` commands. Nothing is stopping you from running the `git` commands of your choice.
