### ISSUE TITLE
How to patch older versions of packages?

### ISSUE THREAD

**Issue by nchandran3** [lerna/lerna#2233]
I'm wondering what the general workflow would be for patching a certain older version of a package without changing the entire state of the monorepo? 

Let's say I have package A which is currently at version 2.0. 

I realize that there's a bug in 1.5.0 and need to patch it. 

The current state of the repo is at master.

Is the workflow to checkout the tag that refers to the buggy version of the package, commit the bug fix, run lerna publish, and then checkout master again? 

Will that cause issues? 

I don't see any documentation on this specific workflow, and its something that my project will have pending in the near future. 

Thanks!

**Comment by evocateur** [comment]
Check out lerna's own [2.x branch](https://github.com/lerna/lerna/compare/2.x).

```sh
git checkout master
git pull origin master
git checkout -b 1.5.x v1.5.0
# make commits as necessary
git push -u origin 1.5.x
npx lerna publish
```

That's it, basically.
