### ISSUE TITLE
lerna exec --parallel does not return exit codes for each project

### ISSUE THREAD

**Issue by sipayRT** [lerna/lerna#2236]
I'm trying to run tests in parallel by command `npx lerna exec --no-bail --parallel -- node scripts/some-tests-runner.js`.
How can I get exit codes (or execution result) for each project?

## Expected Behavior
Ability to get execution result for each run

## Current Behavior
Common exit code for all runs

## Possible Solution
Maybe you can add to process result information about each child-process from projects. For example:

```js
{
  status: 1,
  results: [
    {
      name: 'project1'
      status: 0
    },
    {
      name: 'project2'
      status: 1
    }
  ]
}
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | v3.14.1 |
| `npm --version`  | 6.2.0 |
| `node --version` | 8.6.0 |

| OS | Version |
| ---: | :--- |
| macOS Mojave | 10.14.6 |

**Comment by evocateur** [comment]
Lerna is not a test runner. Try Jest, it works really well with the constraints you've identified.

**Comment by sipayRT** [comment]
> Lerna is not a test runner

@evocateur em... okey, I can change example to `npx lerna exec --no-bail --parallel -- node do-something.js`. 
Or lerna is not do-something-runner?

**Comment by evocateur** [comment]
If you want the functionality, build it yourself. There are more than enough granular `@lerna/*` packages to get you 80% of the way there already.
