### ISSUE TITLE
Use lerna exec to run a command in the root scope

### ISSUE THREAD

**Issue by rheaditi** [lerna/lerna#2237]
(question)
Is there a way to use `lerna exec/run` to run a specific script/command in the root scope?

## Expected Behaviour

We already use something like `lerna run --scope=a <script>`, but we'd like to be able to use lerna to execute a root script from a package script. Given a structure like:

```sh
.
├── lerna.json
├── package-lock.json
├── package.json
├── packages
│   ├── a
│   └── b
└── ...
```

Is there a way that a script "prestart" in `packages/a/package.json` can use lerna to run a script "xyz" which is in root `package.json`.

Something like:
```json
// package.json
"xyz": "do-something-in-root-scope"
```

```json
// packages/a/package.json
"prestart": "npx lerna run --scope <root> xyz"
```

## Current Behaviour

According to [this comment](https://github.com/lerna/lerna/issues/1996#issuecomment-482135827), it's a bad idea to add the root as a managed package.

Unsure how to proceed. Any help would be appreciated! Thank you :)

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | `3.16.4` |
| `npm --version`  | `6.10.2` |
| `yarn --version` | N/A |
| `node --version` | `12.8.1` |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.5 |

**Comment by evocateur** [comment]
This seems more than sufficient for your use case:
```json
    "prestart": "cd ../.. && npm run xyz"
```

**Comment by vivekbhagwat** [comment]
@evocateur I strongly disagree that this is sufficient, as it relies on assuming a directory structure and the point is to keep the scope. if lerna kept track of the root path, that would be more stable and useful. Please reopen this.

**Comment by evocateur** [comment]
> it relies on assuming a directory structure

I mean, yes? Like, your packages don't have a habit of changing their location in the directory tree often, do they?

> if lerna kept track of the root path

`$LERNA_ROOT_PATH` is available to [`lerna exec`](https://github.com/lerna/lerna/tree/master/commands/exec#usage).
