### ISSUE TITLE
Topological sorting doesn't take into account peerDependencies

### ISSUE THREAD

**Issue by samdenty** [lerna/lerna#2238]
## Expected Behavior

Dependencies specified in `peerDependencies` should be accounted for in the sorter (`lerna ls --toposort`), same as `dependencies`

## Current Behavior

Dependencies specified in `peerDependencies` are ignored by the sorter, preventing commands from running in the desired order.

## Possible Solution

Add peerDependencies to

https://github.com/lerna/lerna/blob/8ca18bedecf4f141c6242a099086e84b2ced72de/core/package-graph/index.js#L224

## Context

I'm using `lerna run` with packages that depend on each other in `peerDependencies`.

Currently the only way I can get the correct build order, is by manually building the packages. Or, by using dependencies instead of peerDependencies -- which I can't do

**Comment by evocateur** [comment]
If a package (A) expresses a relationship to another package (B) in `peerDependencies`, A should _also_ have an explicit relationship to B in `devDependencies`. This is the standard pattern for `peerDependencies` in "normal" npm packages. Otherwise, how would you test them locally?
