### ISSUE TITLE
lerna run (and related commands): Want to ignore a package but not its dependents

### ISSUE THREAD

**Issue by bdwain** [lerna/lerna#2240]
## Expected Behavior
When using the --since flag and the --ignore flag, I would like to be able to ignore a package, but not its dependents (maybe with a new option?)

For example, imagine a setup where package A depends on B which depends on C, and B has changed since master. 

`lerna run foo --since origin/master --ignore B --new-option`

I would like the above command to run foo in A (and anything else that depended on B) but not run it in B itself. 

## Current Behavior
`lerna run foo --since origin/master --ignore B` would not run foo at all in the example above, where only B changed. I am proposing an option that would still run foo in A, but not B.

## Possible Solution
The option could be called `--dont-ignore-dependents`? Or maybe a new option, `--ignore-only` to replace `--ignore` in the example above.

## Context
I normally treat all packages the same. However, I recently noticed one package had an especially slow test suite that used a lot of memory and would crash my build machine. I want to run the tests for that one package separately from the remaining packages, while still testing its dependent packages with the rest.

**Comment by JamesHenry** [comment]
Hi @bdwain,

I'm vert sorry for how long this went unaddressed. I'm pleased to say that the behaviour you describe is how modern lerna works already, and you additionally have far more control these days over configuring the relationships between tasks: https://lerna.js.org/docs/concepts/task-pipeline-configuration

Many thanks!
