### ISSUE TITLE
[question] Is there a way to update a component dependencies version but not it's own version?

### ISSUE THREAD

**Issue by diegocvl** [lerna/lerna#2242]
Hi, I'm using Lerna v3.10.6

I just joined a team that has a repo like this:
```
/--
    |--website
    |--components
        |--comp1
        |--comp2
```

comp1 depends on comp2 and website depends on them both.

If I run `lerna version` to bump versions at the components folder level, it will update:
 - comp2 version
 - comp1 version and it's dependency version on comp2

I wish to also automatically update the website dependency versions so if I use Lerna at the root level and treat website as another "component", it will update:
 - comp2 version
 - comp1 version and it's dependency version on comp2
 - website version and website dependency versions on comp1 and comp2

Is there a way I could just update website dependency versions but not the website version itself?

Thanks a lot =)

**Comment by jpettit** [comment]
Try this? https://www.npmjs.com/package/lerna-update-wizard

**Comment by evocateur** [comment]
@sapeish If the `website` component is never published to a repository, why does the "version" matter? Without seeing your `lerna.json`, I can't tell you why it's not currently being bumped when either `comp1` or `comp2` are updated.
