### ISSUE TITLE
Lerna publish publishes non changed packages

### ISSUE THREAD

**Issue by bedlaj** [lerna/lerna#2244]
`lerna publish patch` publishes all packages, if any of packages changed.

## Expected Behavior
Publish only changed packages.

## Current Behavior
`lerna changed` shows correct results, but `lerna publish`publishes all packages. `lerna version patch` also attempts to bump all packages. 

If none of packages changes, the changes are not published - correct
If one of packages changes, all packages are published

Reproducer project in https://github.com/bedlaj/lerna_playground
Versions with tag <= 0.0.7 were created with lerna 3.16.4 - change of one module trigered publish of all modules.
Version with tag 0.0.8 was created with lerna 2.0.0 and it published correctly just one changed package.

## Steps to Reproduce (for bugs)
1. Fork https://github.com/bedlaj/lerna_playground
2. `git clone <FORK>`
3. `echo "/* some modification */" > packages/silly_empty_package/index.css`
4. `git add packages/silly_empty_package/index.css`
5. `git commit -m "Test"`
6. `lerna publish patch`

</p></details>

## Your Environment
The same behavior occurs on Windows WSL and Linux Mint.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | 1.17.3 |
| `node --version` | v10.16.0 |

| OS | Version |
| ---: | :--- |
| Windows 10 - Linux subsystem | 10.0.18362 |
| Linux Mint  | 19.1 Tessa |

**Comment by bedlaj** [comment]
I had to set `"version": "independent"` in `lerna.json`. Not sure why this was working without version i lerna 2.0.0.

**Comment by RafaelloLoliop** [comment]
@bedlaj 
I had similar problem. Version must be just  > 0.1.0 (before 1st minor release, every patch is breaking)
