### ISSUE TITLE
[question] lerna ERR! EBADSEMVER invalid semver

### ISSUE THREAD

**Issue by coreybruyere** [lerna/lerna#2245]
This error hasn't been helpful when trying to debug. Hoping someone can point me in the right direction? I'm trying to version a newly created package in fixed mode. I've created my new package to  be set at the same version as the other packages in my monorepo.

I'm also trying to publish from a feature branch as an alpha release. So it could be an error in my workflow all together.

## Expected Behavior
Run `lerna run build && lerna publish --contents dist` and have each package version 

## Current Behavior
Publish fails because of error

<details><summary>lerna.json</summary><p>

```json
{
	"packages": [
		"packages/*"
	],
	"version": "0.6.0-alpha.0"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
```
lerna ERR! EBADSEMVER invalid semver:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ publish: `lerna run build && lerna publish --contents dist`
npm ERR! Exit status 1
npm ERR!
```

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.9.0 |
| `node --version` | v8.11.3 |

**Comment by KyDenZ** [comment]
I have a same problem
