### ISSUE TITLE
Lerna --stream removing chalk colors log

### ISSUE THREAD

**Issue by paramsinghvc** [lerna/lerna#2246]
## Expected Behavior

Chalk colors should be shown in the terminal. That's the whole point of using chalk in the first place.

<img width="731" alt="Screenshot 2019-08-31 at 17 53 24" src="https://user-images.githubusercontent.com/4329912/64063879-41661000-cc18-11e9-9c35-6d6304eb594f.png">

## Current Behavior

`lerna run --stream` command gives below kind of output. All the colors go away!! :(

<img width="900" alt="Screenshot 2019-08-31 at 17 49 35" src="https://user-images.githubusercontent.com/4329912/64063870-1976ac80-cc18-11e9-9934-e290920b2f73.png">

## Possible Solution

Please allow colors in `lerna run --stream`

## Steps to Reproduce (for bugs)

1. Run node filename_having_chalk_logs.js It'll print proper chalk logs
2. Now run the same command through lerna run <npm command> --stream, it won't show the colors

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "packages": [
    "packages/**"
  ],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

I'm running a Koa server to proxy api requests coming from my react app to relay them to the  backend servers, I've applied morgan logs for intercepting requests and spent lot of time in making the output colorful, but sadly all in vain cause of lerna. Please help.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.15.0 |
| `npm --version`  | 6.10.2 |
| `yarn --version` | 1.17.3 |
| `node --version` | 12.6.0 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.6 |

**Comment by Akryum** [comment]
I made a package that supports colors: https://github.com/Akryum/monorepo-run :cat2:

**Comment by muehre** [comment]
```javascript
const chalkInstance = new chalk.Instance({
  level: 1,
})
chalkInstance.green('SomeString')
```

Works for me

**Comment by jacksaunders** [comment]
Hey were you able to figure this out? i'm having a similar issue

**Comment by MaxmaxmaximusGitHub** [comment]
extremely annoying problem
![image](https://user-images.githubusercontent.com/60403187/82522940-8a0d8280-9b33-11ea-9303-e2616b2effe1.png)

**Comment by chaddjohnson** [comment]
I have found that colors disappear when using `lerna run` but not with `lerna exec`.

`lerna run` is a more robust option in general as it only runs commands in packages where the commands actually exist, whereas `lerna exec` will fail if a command does not exist in a package.

It would be great if `lerna run` would preserve color output. For me, this is particularly important for linting.

**Comment by a7madgamal** [comment]
Can someone at least explain we have this behavior?

**Comment by hangtwenty** [comment]
following up on what @chaddjohnson said —

what do you think about this:

* refactor `lerna run` implementation to pull out the preflight validation you mentioned
* add option to `lerna exec` that would call that same validation foreach. 

why: `lerna exec -- npm run` doesn't make sense to repeat a bunch of times, plus the loss of formatting.

caveat: i'm not sure if `lerna run` and `lerna exec` differ in other notable ways or if this would just provide two ~equivalent calls.

thoughts? i could take a stab at it

**Comment by hangtwenty** [comment]
also, @chaddjohnson said --

> It would be great if `lerna run` would preserve color output. For me, this is particularly important for linting.

+1, i use [`xo`](https://github.com/xojs/xo) partly because the default (no-config) has colors that are really clear to me. i end up keeping the code cleaner, when i have the color output from `xo`

**Comment by pi0** [comment]
`FORCE_COLOR=1` should also fix the problem for chalk :)

**Comment by JamesHenry** [comment]
Hi Folks 👋 

Looks like this one got a well liked resolution a long time ago, so I'm going to close it.

Additionally, please be aware that these days `lerna` ships with a modern task runner these days (powered behind the scenes by Nx's battled tests task-runner, instead of its original usage of `p-map` and `p-queue`), and I was not able to reproduce any colour issues when using it.

Please update to the latest lerna (v6 at the time of writing) to ensure you are getting the best experience and feel free to open a new issue if you encounter any problems.

Many thanks!
