### ISSUE TITLE
Specify custom template for CREATE command

### ISSUE THREAD

**Issue by kibertoad** [lerna/lerna#2247]
## Expected Behavior

User can pass additional commandline option, pointing to custom package.json template

## Current Behavior

Default, highly opinionated package.json is used for creating new Lerna package.

## Possible Solution

Additional CLI parameter, support for package.json template file.

## Context

Trying to reduce amount of time spent setting up new Lerna packages

**Comment by kibertoad** [comment]
If there is approval for this feature, I can look into implementing it myself.

**Comment by kibertoad** [comment]
@evocateur Would it be possible to get this proposal reviewed and either accepted (so that I could start working on it) or rejected?

**Comment by ntwb** [comment]
This looks like a duplicate of #1742
