### ISSUE TITLE
Prevent installation of packages on bootstrap

### ISSUE THREAD

**Issue by swashcap** [lerna/lerna#225]
It looks like lerna installs all packages via `npm install` when bootstrapping, _then_ links everything in _/packages_. This leads to a bunch of extraneous packages in each package’s _node_modules_. Can anything be done?

**Comment by gigabo** [comment]
Lerna [skips packages that will later be linked](https://github.com/lerna/lerna/blob/master/src/commands/BootstrapCommand.js#L102-L106) when installing external dependencies during bootstrap.

**Comment by thejameskyle** [comment]
Yup @gigabo is correct, @swashcap you might be using an old version of Lerna
