### ISSUE TITLE
npmClient does not work when lerna publish

### ISSUE THREAD

**Issue by tarol** [lerna/lerna#2250]
## Expected Behavior
when publish, lerna use the npmClient i specified

## Current Behavior
when publish, lerna use npm to do it

## Steps to Reproduce (for bugs)

1.  set npmClient in lerna.json
2.  lerna publish

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.13.0 |
| `node --version` | 10.15.0 |

| windows | 10 |
| --- | --- |
| NAME | VERSION |

**Comment by AndreGeng** [comment]
+1

**Comment by starandtina** [comment]
learn@3 publish doesn't support npmClient, please use lerna@2 if you wanna make it work.

**Comment by AndreGeng** [comment]
may I ask why we do not support it any more? Besides what is the recommended way to publish to a private registry currently when using lerna@3?

**Comment by gztchan** [comment]
Is there anybody who can explain that why 3.x removed the feature `npmClient` in commands except bootstrap?

**Comment by orangeyyy** [comment]
got the same problem

**Comment by crazymousethief** [comment]
got the same problem too, who can explain it

**Comment by evocateur** [comment]
> Is there anybody who can explain that why 3.x removed the feature `npmClient` in commands except bootstrap?

`lerna bootstrap` is the only remaining subcommand where `npmClient` is relevant.

**Comment by evocateur** [comment]
Lerna 3.x uses the same tools that npm does to publish packages to the configured registry. What is the downside you are experiencing?

**Comment by tarol** [comment]
> Lerna 3.x uses the same tools that npm does to publish packages to the configured registry. What is the downside you are experiencing?

I use xnpm which forked npm and works with a fixed registry. I need to download packages from this registry and publish to this registry. Now I must configure npm's registry and proxy but not resolve by `npmClient`

**Comment by starandtina** [comment]
> > Is there anybody who can explain that why 3.x removed the feature `npmClient` in commands except bootstrap?
> 
> `lerna bootstrap` is the only remaining subcommand where `npmClient` is relevant.

Is it possible to support `npmClient` for other lerna subcommands?

**Comment by evocateur** [comment]
@tarol 
>  I need to download packages from this registry
Not relevant to `--npm-client`, that's controlled by your local `.npmrc` or `--registry` argument.

> and publish to this registry.
`--npm-client` _never_ controlled this, fwiw. Use `--registry` or [`publishConfig.registry`](https://docs.npmjs.com/files/package.json#publishconfig) in each leaf node's `package.json`.

**Comment by evocateur** [comment]
@starandtina 

> Is it possible to support npmClient for other lerna subcommands?

_Why?_ It's utterly useless to everything but `lerna run`, which **already** [supports it](https://github.com/lerna/lerna/tree/master/commands/run#--npm-client-client).

**Comment by starandtina** [comment]
> @starandtina
> 
> > Is it possible to support npmClient for other lerna subcommands?
> 
> _Why?_ It's utterly useless to everything but `lerna run`, which **already** [supports it](https://github.com/lerna/lerna/tree/master/commands/run#--npm-client-client).

For security reasons, the third party publishing tool(npm/yarn) was forbidden within the company, so I have to rollback to lerna@2 as it supports `npmClient` customization

**Comment by rdmclin2** [comment]
@starandtina same problem, any idea?

**Comment by starandtina** [comment]
> @starandtina same problem, any idea?

A quick solution: just use lerna@2.x

**Comment by evocateur** [comment]
Literally all of the code used is open source, so "security reasons" is weak tea. Anyway, it's not going to change in Lerna going forward, so I'm closing this issue.
