### ISSUE TITLE
Lerna should allow scoped bootstrap with yarn

### ISSUE THREAD

**Issue by baflo** [lerna/lerna#2254]
## Expected Behavior
With npm as package manager, Lerna allows to scope `bootstrap`, such that only selected packages are bootstrapped. This is useful for larger monorepos, where one only wants to work on a subset of package, e.g. `--include-filtered-dependencies`.

## Current Behavior
All packages are bootstrapped, no matter what scope is set.

## Possible Solution
Before running `yarn install`, the workspaces in root `package.json` should be patched, so only the filtered packages are listed.

**Comment by evocateur** [comment]
If you're using Yarn workspaces, this isn't a Lerna bug, it's a Yarn workspaces bug.

**Comment by baflo** [comment]
That's true. It would be better if the yarn workspaces supported this. However, npm does not support workspaces at all and lerna makes it possible by patching the package.json files, then installing the dependencies.

I reckon Lerna could patch the package.jsob before running `yarn` so only a subset of packages are bootstrapped.

@evocateur Could you please re-open this?
