### ISSUE TITLE
npm link - no matching version

### ISSUE THREAD

**Issue by jleck** [lerna/lerna#2255]
Hi,

I have an external project which I'd like to alias by modules into. It used to work before, but I'm not sure what has changed. Any module which now has a dependency on another module now errors with:

`No matching version found for...`

They aren't published to npm (or anywhere yet), but it used to just work before.

Any pointers? Or alternatives to npm link? I would use npm install with a local path, but it changes the package.json.

**Comment by dominikfoldi** [comment]
I think I have the same issue. I have two packages in the packages folder: package-a, package-b where package-b has package-a as its devDependency and peerDependency. The packages are private so not published anywhere but our customers have to install it from local tgz packages.

After I run `lerna bootstrap` then `lerna exec -- npm link` package-a is linked correctly but linking of package-b throws an error:
```
npm ERR! code E404
npm ERR! 404 Not Found: package-a@*
```

package-b is a CLI so we would like to test it locally this is why the linking is needed. 

Any ideas?
