### ISSUE TITLE
lerna add uses symlinks for inter-module dependencies but this solution is not suitable in all cases (e.g. when using docker)

### ISSUE THREAD

**Issue by ohjames** [lerna/lerna#2256]
## Current Behavior

Say `lerna-package` and `consuming-package` are both packages in my monorepo.

Then:

```bash
lerna add lerna-package consuming-package
```

Adds a symlink to `consuming-package/node_modules` pointing at `lerna-package`.

The problem is, say I'm using `docker` inside `consuming-package` to run the software. Now docker can't see the destination that `consuming-package/node_modules/lerna-package` points to because it links to a file *above* the Dockerfile.

Is there a way to have `lerna` copy module dependencies instead of using symlinks?

If there was a `postbootstrap` script hook I could manually do the replacement with a script. Or I could force my users to run `npm run bootstrap` and have that do `lerna bootstrap && npm run replace-symlinks`. Neither are ideal though, but maybe that's what I'll have to do?

**Comment by evocateur** [comment]
Short of moving your Dockerfile to the root? I'm not sure.

Lerna isn't built to facilitate Docker, however. It's for managing many npm packages in the same git repository (primarily versioning and publishing them).

**Comment by ohjames** [comment]
Yeah I get it, we stopped using `lerna bootstrap` and moved to `lerna run install`.

Azure IOT uses a docker image per module (package) so there wasn't much else we could do. It makes testing updates to libraries super hard, for that we are still looking for a solution.

**Comment by insidewhy** [comment]
@brandonros Using https://github.com/insidewhy/mirror-directories which has a watch mode to get directories in sync during development.
