### ISSUE TITLE
why after running react-native run, say me "Unable to resolve module

### ISSUE THREAD

**Issue by mohammad-khosrojerdi** [lerna/lerna#2258]
hi, i have a monorepo project with lerna and i have app, web and common packages in monorepo folder. my app package is react-native project and my web package is react-native-web project. i add common dependency in web and app package from lerna add command. the result of my web project is fine but when i run app project, alert me "Unable to resolve module". while i find the common folder in node_modules folder in app package root. why react-native not found my common dependency?

![Screenshot from 2019-09-12 08-43-26](https://user-images.githubusercontent.com/10862208/64762379-549ba880-d553-11e9-83fe-2762dac9ae17.png)

![Screenshot from 2019-09-12 08-49-19](https://user-images.githubusercontent.com/10862208/64762397-5bc2b680-d553-11e9-89ae-822be2f5f261.png)

**Comment by iamgina** [comment]
I have the same issue.

**Comment by iamgina** [comment]
@mohammad-khosrojerdi Were you able to resolve the issue?

**Comment by mohammad-khosrojerdi** [comment]
> @mohammad-khosrojerdi Were you able to resolve the issue?

No, not resolve my issue. so i use another structure in my project without lerna.
