### ISSUE TITLE
lerna bootstrap fails with "-4058"

### ISSUE THREAD

**Issue by Daniel15** [lerna/lerna#226]
I'm trying to build Jest, and Lerna is failing:
```
> @ postinstall C:\src\jest
> node ./scripts/postinstall.js && node ./scripts/build.js

Setting up Jest's development environment...
-> running: C:\src\jest\node_modules\.bin\lerna.cmd bootstrap cwd: C:\src\jest
Lerna v2.0.0-beta.20
Linking all dependencies
babel-plugin-jest-hoist
Errored while running BootstrapCommand.execute
-4058
-> failed running: C:\src\jest\node_modules\.bin\lerna.cmd bootstrap
```

Windows 10, node v4.4.3, npm v2.15.1, Lerna v2.0.0-beta.20

**Comment by hzoo** [comment]
I'm trying to figure out the issue - might just need to republish or it's `sync-exec` - https://github.com/lerna/lerna/issues/221 but beta.19 should work.

**Comment by gigabo** [comment]
Doesn't look like `sync-exec` is made to work on windows.

Building paths with [string](https://github.com/gvarsanyi/sync-exec/blob/master/js/sync-exec.js#L43) [concatenation](https://github.com/gvarsanyi/sync-exec/blob/master/js/lib/read-pipes.js#L14) [all](https://github.com/gvarsanyi/sync-exec/blob/master/js/lib/read-pipes.js#L31) [over](https://github.com/gvarsanyi/sync-exec/blob/master/js/lib/create-pipes.js#L22).

But that should only be an issue on node `0.10`, right?


Looks like [`-4058` is `ENOENT`](http://stackoverflow.com/questions/36696605/nodejs-in-windows-file-system-path-error-4058-enoent).

**Comment by Daniel15** [comment]
String concatenation should actually be fine, Windows handles both `\` and
`/`. There's probably some environmental assumptions made somewhere and
it's just coincidentally working on common Linux systems. I'll try to take
a closer look.

One of the main advantages of using JavaScript is that it's cross platform,
so it's silly for a Node library to only work on Linux (unless there's some
native component of course).

"-4058" and "ENOENT" are both terrible error messages. It's unfortunate but
Node.js is pretty well known for having unintelligible error messages.

Sent from my phone.

Doesn't look like sync-exec is made to work on windows.

Building paths with string
<https://github.com/gvarsanyi/sync-exec/blob/master/js/sync-exec.js#L43>
concatenation
<https://github.com/gvarsanyi/sync-exec/blob/master/js/lib/read-pipes.js#L14>
all
<https://github.com/gvarsanyi/sync-exec/blob/master/js/lib/read-pipes.js#L31>
over
<https://github.com/gvarsanyi/sync-exec/blob/master/js/lib/create-pipes.js#L22>
.

But that should only be an issue on node 0.10, right?

Looks like -4058 is ENOENT
<http://stackoverflow.com/questions/36696605/nodejs-in-windows-file-system-path-error-4058-enoent>
.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lerna/lerna/issues/226#issuecomment-226925013>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAFnHVJdyNPSa-bN9U34cHxcIQQ878U3ks5qM47hgaJpZM4I4DTn>
.

**Comment by Daniel15** [comment]
> But that should only be an issue on node 0.10, right?

I'm on Node v4.4.3 as per this issue.

**Comment by Daniel15** [comment]
Just confirmed that Lerna v2.0.0-beta.19 works as expected.

I'm not sure it's directly related to `sync-exec` though. I just tested with a standalone project and it works fine:
```
var syncExec = require('sync-exec');
var result = syncExec('dir');
console.log('RESULT: ', result.stdout);
```

```
C:\src\testappwithjest  (testappwithjest@1.0.0)
λ node test.js
RESULT:   Volume in drive C is Windows
 Volume Serial Number is C6A7-A39E

 Directory of C:\src\testappwithjest
.....
```

Additionally, I'm on Node v4 so Lerna shouldn't even be using the sync-exec module. I wonder if it's some other change that was included in beta 20.

**Comment by hzoo** [comment]
Right I kept thinking that was the only change but I see some other stuff like I added the add-module-exports plugin and also changed the main key in package.json

**Comment by gigabo** [comment]
Yeah, seems like it must be something else.  Here's the [full change set](https://github.com/lerna/lerna/compare/3d9687d2...70a1bd) for beta-20.

The switch from `exec` to `spawn` in `NpmUtilities.installInDir` is another possibility.

Could it be that `npm` is a [`.bat` or `.cmd` file on windows](https://nodejs.org/dist/latest-v4.x/docs/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows)?

> `.bat` and `.cmd` files are not executable on their own without a terminal and therefore cannot be launched using `child_process.execFile()` (or even `child_process.spawn()`).

**Comment by Daniel15** [comment]
> Could it be that npm is a .bat or .cmd file on windows?

Yes, that's correct. `npm` is a `.cmd` file that calls `node` passing the right parameters. All Node.js scripts in the `node_modules/.bin` directory are also `.cmd` files on Windows.

**Comment by gigabo** [comment]
![image](https://cloud.githubusercontent.com/assets/115908/16175022/f50ba804-3594-11e6-9198-4221e930a1f5.png)

So... [that change](https://github.com/lerna/lerna/pull/217) was made to fix #213.  Lerna was slurping up all output from `npm` and failing if it exceeded `maxBuffer`.  Don't want to regress there.

@Daniel15 - Is there a common pattern for working around this limitation of `spawn` on windows?  Is [`win-spawn`](https://www.npmjs.com/package/win-spawn), or something like it, going to be the answer here?

**Comment by Daniel15** [comment]
Looks like win-spawn is deprecated and [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) and [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async)  are the replacements. I imagine that'd work though :+1: 

It really sucks that a core Node.js function isn't cross-platform. That's the entire point of a core library - to not have to worry about things like this. :(

**Comment by laurentdesmet** [comment]
I made a pull request that replaces `child_process.spawn`. Fixing PR #230 would also be a next step in having more robust Windows support.

**Comment by cchamberlain** [comment]
I tried out `beta.24` on Windows to see if anything changed and I do not even receive an error anymore, it just stops. Any roadmap or PR / testing needed?

![image](https://cloud.githubusercontent.com/assets/424694/16886240/db601f04-4a87-11e6-9ad5-96a94ab1fb18.png)

**Comment by hzoo** [comment]
I think you would need to test on https://github.com/lerna/lerna/pull/236 since it's definetely not working right now

**Comment by hzoo** [comment]
@Daniel15 @cchamberlain can everyone test on the latest version, beta 26?

**Comment by cchamberlain** [comment]
Appears to be fixed for me, thanks!

**Comment by Daniel15** [comment]
Working with Jest for me now, thanks!
