### ISSUE TITLE
Starting Multiple Projects in Parallel and Respecting Topology

### ISSUE THREAD

**Issue by martinmckenna** [lerna/lerna#2260]
I have 2 projects in my lerna repo.  Package A depends on Package B.

Both have start scripts that run the projects in watch mode so I can make live changes to both at the same time.

Because of this I use `lerna run start --parallel`, which starts both in watch mode, but doesn't respect topology (as expected), and I end up with console errors, since they're both started ASAP

I've also tried `lerna run start --concurrency 2 --stream` but that still only starts 1 project and never moves on to the second

## Expected Behavior

I'd like an option to run projects in parallel mode, but still respect the dependencies of each.

So maybe `lerna run start --parallel --sort package-a package-b`

**Comment by martinmckenna** [comment]
Right now I've opted to do something similar to

```
lerna run build --scope package-a && lerna run start --parallel
```

ensuring that the package-a is built first.

**Comment by serhiiromaniuk** [comment]
@martinmckenna Hello there. But if in the project repo there are 100 packages?) I am trying to find the right way to `lerna`.
