### ISSUE TITLE
lerna tries to install cross-dependency from npm when bootstrapping

### ISSUE THREAD

**Issue by insidewhy** [lerna/lerna#2262]
I've made a repo that demonstrates the issue. Here I'm using `devDependencies` but the same thing happens if I switch them over to `dependencies`.

`git clone git@github.com:insidewhy/lerna-bug.git && cd lerna-bug && npm i && npx lerna bootstrap`

In this repo, each of the cross-dependencies were added using `npx lerna-add`.

## Expected Behavior
`npx lerna bootstrap` should create symlinks from `pack1` to the `node_modules` of `pack2`, and from `pack2` to the `node_modules` of `pack3` and `pack4`.

## Current Behavior
```
% npx lerna bootstrap
lerna notice cli v3.16.4
lerna info Bootstrapping 4 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in 'pack2'
lerna ERR! npm install stderr:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for pack1@1.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/james/.npm/_logs/2019-09-14T01_42_24_522Z-debug.log

lerna ERR! npm install exited 1 in 'pack2'
```

## Steps to Reproduce (for bugs)
1. git clone git@github.com:ohjames/lerna-bug.git
2. cd lerna-bug
3. npm i
4. npx lerna bootstrap

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "npm",
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}

```
</p></details>

## Your Environment
arch linux

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.11.2 |
| `node --version` |v10.16.3  |

| OS | Version |
| --- | --- |
| archlinux | rolling |

**Comment by eborned** [comment]
Did you ever fix this issue? I'm currently experiencing the same issue.

**Comment by insidewhy** [comment]
@eborned no
