### ISSUE TITLE
package.json setup for scoped packages and lerna ERR! E402 You must sign up for private packages

### ISSUE THREAD

**Issue by kushalmahajan** [lerna/lerna#2264]
I'm using lerna with yarn workspaces. I built my library with command `yarn workspace @org/package-1 build:lib` as mentioned below.
`dist` folder is generated. After that I run `npx lerna publish`. But it fails saying there's no package.json in `dist` folder
Why does lerna needs to have package.json inside dist folder? How can I fix the same? 

```
{
  
    "main": "dist/index.js",
    "types": "dist/index.d.ts",
    "workspaces": [
        "packages/*"
    ],
    "publishConfig": {
        "access": "public",
        "directory": "dist"
    },
    "scripts": {
        "build:lib": "rm -rf dist & tsc -p ./tsconfig-lib.json",
    },
    "files": [
        "README.MD",
        "dist"
    ]
}
```

Then if I provide a script to copy the files inside dist folder anyway, Lerna picks up that. Here are my modifications.

```
{
    "main": "index.js",
    "types": "index.d.ts",
    "publishConfig": {
        "access": "public"
    },
    "scripts": {
        "bundle": "rm -rf dist & tsc -p ./tsconfig-lib.json",
        "copy": "cp README.MD package.json dist/",
        "build:lib": "yarn run bundle; yarn run copy;"
    },
   "files": [
        "README.MD",
        "**"
    ]
}
```
Then this time it does picks and strangely publishes the tarball content as new package. But in the end there's this error - `lerna ERR! E402 You must sign up for private packages`

I've a public package on npm.

**Comment by lazd** [comment]
You need to set `access=public`.

https://github.com/lerna/lerna/tree/master/commands/publish#publishconfigaccess

https://docs.npmjs.com/misc/config#access

**Comment by kushalmahajan** [comment]
This was due to another empty package.json having no property `publishConfig`. Closing this
