### ISSUE TITLE
Need the ability to 'lerna version patch' without using git.

### ISSUE THREAD

**Issue by burtonator** [lerna/lerna#2265]
I'm using git submodules as my package is public and private.

Lerna works just fine for my use BUT I can't increment the version.

Right now it generates an error but the version is bumped to I'm able to continue using it but I can't put this into a CI system to do iterative releases.

If there was just a ```--no-commit``` mode then it would work fine for my use case.

Is this possible?

**Comment by joebowbeer** [comment]
Are you using `--no-git-tag-version` option?

**Comment by burtonator** [comment]
I haven't but will try that now!

**Comment by burtonator** [comment]
You're the man!  That worked!
