### ISSUE TITLE
When I run serve command with lerna I got enormous of outputs rows

### ISSUE THREAD

**Issue by wizardnet972** [lerna/lerna#2266]
I'm using lerna to run serve command. this command call vue/cli which call webpack to analyze all the files and build the bundle.
I also get it when I run the angular/cli in the project.

So I run lerna run serve --stream in vue/cli application and I get the output of a lot of rows in webpack progress:
```
myapp-vue: <s> [webpack.Progress] 93% asset optimization
myapp-vue: <s> [webpack.Progress] 94% after asset optimization
myapp-vue: <s> [webpack.Progress] 94% after seal
myapp-vue: <s> [webpack.Progress] 95% emitting
myapp-vue: <s> [webpack.Progress] 95% emitting HtmlWebpackPlugin
myapp-vue: <s> [webpack.Progress] 95% emitting vue-cli:pwa-html-plugin
myapp-vue: <s> [webpack.Progress] 95% emitting CopyPlugin
myapp-vue: <s> [webpack.Progress] 95% emitting fork-ts-checker-webpack-plugin
```
Its also happend when I run the `angular/cli`.
What can I do to not have all the rows? (just to have in one line - every time the line will erase and have new information) and I don't want to lose the webpack progress. maybe to create a buffer for every 3 seconds?

**Comment by gcoda** [comment]
Some kind of debounce-throttle for streams would be really nice, but for now i am using multiview, makes it a lot more tolerable.

`npm i multiview -D`

```json
{
  "name": "root",
  "private": true,
  "scripts": {
    "dev": "multiview [npm run dev:app] [npm run dev:web] -e",
    "dev:app": "lerna run dev --stream --no-prefix --ignore=@therobot/*-web",
    "dev:web": "lerna run dev --stream --no-prefix --scope=@therobot/*-web"
  }
}
```
![Screenshot-20191216094344-510x196](https://user-images.githubusercontent.com/556999/70888268-9de31480-1fe8-11ea-8d67-beb32a831ffb.png)
