### ISSUE TITLE
Error install lerna

### ISSUE THREAD

**Issue by mchavarriae** [lerna/lerna#2268]
I'm trying to install lerna@3.4.3 globally

## Expected Behavior
Install lerna

## Current Behavior
The npm install is throwing an error
747 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...ersion":"8.10.29","de'
747 verbose stack     at JSON.parse (<anonymous>)
747 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
747 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
747 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
748 verbose cwd /workspace/tevix/tvx-monorepo
749 verbose Darwin 18.7.0
750 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "lerna@3.4.3" "-g"
751 verbose node v10.13.0
752 verbose npm  v6.4.1
753 error Unexpected end of JSON input while parsing near '...ersion":"8.10.29","de'
754 verbose exit [ 1, true ]

| Executable | Version |
| ---: | :--- |
| `npm --version`  | 6.4.1 |
| `node --version` | v10.13.0 |

| OS | Version |
| macOS Sierra | 10.14.6 |

**Comment by MikeYermolayev** [comment]
Having the same error but saying 'Unexpected end of JSON input while parsing near '...7.1","@lerna/run-life''

**Comment by evocateur** [comment]
This looks like a network error, more than anything. Not sure why you need an ancient version of Lerna, either.
