### ISSUE TITLE
A small typo in README

### ISSUE THREAD

**Issue by gamtiq** [lerna/lerna#227]
It seems there is a typo in `README.md`:
> some projects will organize their codebases into multi-package _repostories_

**Comment by hzoo** [comment]
Do you want to make the fix in a PR?

**Comment by gamtiq** [comment]
I suppose that such a trivial change does not need a PR. :-)
But I can make the PR, if you would like.

**Comment by hzoo** [comment]
Just wanted to check if you wanted to (maybe you would of already then), otherwise I can

**Comment by hzoo** [comment]
https://github.com/lerna/lerna/commit/02ffb9620e03e021ae75c4aa05f7d977596a32f0
