### ISSUE TITLE
Problem with changed packages and the gitHead key

### ISSUE THREAD

**Issue by matt-ganz** [lerna/lerna#2275]
Update: The unchanged package was showing up as changed because it carried the second package as a dependency. The version is bumped automatically so you don't see the change but it does happen. Ok, I get that. However, the "gitHead" value still gets added after publish. I've seen the issue related to gitHead here and I've made sure that my other package.json files don't also have a publish command. 

I've got the following scripts in my root package.json in my lerna repo:

`"scripts": {
    "lerna-changed": "npx lerna changed",
    "lerna-diff": "npx lerna diff",
    "lerna-publish": "npx lerna publish"
  }`
In my repo I've got two packages. I make a change to the index.js file in one package and commit it to my repo.

I run npm run lerna-changed and expect only my changed package, but I get both packages. So I run lerna-diff and all I see is the changed package. Why is the unchanged one showing up after lerna-changed?

So when I publish it prompts me to semver both packages. I'm using independent versioning and only want to be publishing one.

And lastly, after the publish I see a "gitHead" key in my package.json file of both packages (not the root.json). What is happening?

**Comment by matt-ganz** [comment]
I believe the reason for this is because my lerna publish is failing. I mean, it pushes the tags to the repo but it's not publishing to my registry - user error. I know that gitHead is a temporary key and my guess is that when I fix the publishing issue it will go away.

**Comment by evocateur** [comment]
"independent" versioning is only with respect to which version number is used for a given package, not avoiding automatic bumps of sibling dependents.
