### ISSUE TITLE
[Feature] check if git init has been run in lerna init

### ISSUE THREAD

**Issue by reggi** [lerna/lerna#228]
I was having some issues yesterday with beta 2.0 where I would `lerna init` in a dir and it would init no files would be in my working path they would be one dir above. I'm having trouble recreating because it was happening intermittently.

**Comment by hzoo** [comment]
is it an issue with beta.20 only? maybe we should revert the sync-exec package change and then either find another way or not support node 0.10

**Comment by reggi** [comment]
I only had it with `2.0.0-beta.20`. I never ran `init` with other betas on a fresh dir, I was just updating the existing. Sorry I can't be of more help. I really was trying to recreate it a bunch. With different combos of `npm init` in dirs above and below my working dir. It wasn't consistent in any way.

**Comment by Shany100** [comment]
``` git init  ``` first.

**Comment by thejameskyle** [comment]
Yup, `git init` needs to be run in the directory you want first. We should probably make this smarter

**Comment by doug-wade** [comment]
[this has been implemented](https://github.com/lerna/lerna/blob/master/commands/init/index.js#L36); closing
