### ISSUE TITLE
`lerna list` _excludes_ `"private": true` packages when it shouldn't

### ISSUE THREAD

**Issue by jamie--stewart** [lerna/lerna#2281]
## Expected Behavior

In a lerna monorepo, when I run 

`lerna list`

I expect to see _all_ packages, regardless of whether they are set to be private.

## Current Behavior

Currently, with `"private": true` in one of my packages, it is **not** shown when I run:

`lerna list`

If I unmark the package (i.e. remove `"private": true`), it does appear, so the package is found by lerna. I can also run other commands (like `lerna add` to the private package) when it doesn't appear in `lerna list`

## Steps to Reproduce (for bugs)

I created a reproduction repo at: https://github.com/jamie--stewart/lerna-private-bug-repro

* Clone the code
* `npm i`
* `npx lerna list` 

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
	"packages/*",
	"storybook"
  ],
  "version": "independent",
  "command": {
	"publish": {
	  "allowBranch": "master"
	}
  }
}
```
</p></details>

## Context

My storybook isn't intended to be publishable, but I'd like to see it in the list of packages.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | N/A |
| `node --version` | v10.13.0 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.6 |

**Comment by sergi** [comment]
Private packages are normally hidden. You can use `npx lerna list -a` to see all packages.

**Comment by jamie--stewart** [comment]
I see that now, [https://github.com/lerna/lerna/tree/master/commands/list#--all](https://github.com/lerna/lerna/tree/master/commands/list#--all)

Thanks for pointing that out, sorry for not being more careful to read the docs.
