### ISSUE TITLE
Lerna fails yarn audit

### ISSUE THREAD

**Issue by lekoaf** [lerna/lerna#2282]
When running `yarn audit` in our project, we found vulnerabilities with lerna.

Apparently you're using the `handlebars` package which has issues.

https://www.npmjs.com/advisories/1164

Same error as #1941.

**Comment by lekoaf** [comment]
We solved it temporarily by adding `handlebars` as a `resolutions` in package.json.

```json
"resolutions": {
  "handlebars": "^4.3.0"
}
```

**Comment by evocateur** [comment]
https://github.com/lerna/lerna/issues/1941#issuecomment-511966277
