### ISSUE TITLE
Revert everything when `lerna publish` fails?

### ISSUE THREAD

**Issue by FezVrasta** [lerna/lerna#2285]
## Expected Behavior

Sometimes it happens that my CI publish fails, and I get into an inconsistent state, with Git tags already published, release commits pushed, and sometimes even some packages published while others not (because the build of those failed).

I would expect Lerna to revert all those changes if a publish task fails at any point.

## Current Behavior

Right now Lerna simply quits with an error, leaving the mess behind.

## Possible Solution

I would like Lerna to _at least_ delete the Git tags, and revert (or not push at all?) the release commit.

It would be great if it could even unpublish the packages (I know npm allows a short time frame to do that).

**Comment by ncphillips** [comment]
I've hit this a couple times, especially as I try to configure lerna to do exactly what I want. It is incredibly frustrating

**Comment by evocateur** [comment]
https://github.com/lerna/lerna/pull/2243#issuecomment-539141339

If we can improve the error logging or exit code to make these sorts of issues easier to respond to, then let's do that.

Nothing about the git state is _required_ by `npm publish`, for example. Recovery from failed publish (partial or complete) after a successful tag + push is as simple as a local `npx lerna publish from-package --yes`.

**Comment by jmeyers91** [comment]
Any update on this? I'm currently dealing with lerna saying everything is up-to-date, but the publish failed, so my packages don't match the version in the commit. One of my packages just isn't published, and I'm not sure how I can fix it without making a whitespace change and publishing a new minor version.

**Comment by rr-justin-hanselman** [comment]
I know I'm adding this way late, but I've tried implementing the solution in #2243 and "--no-push" actually seems to push to git still.

`git push && git push --tags`

I'm not sure if I don't understand what --no-push means or if this is a bug, but the workaround is a lot more complex than what I would've liked.

It looks like I have to add "--no-git-tag-version" to avoid committing to my remote git.  

This leaves 2 problems here:

1. The "postrelease" script above does nothing in its current state.
2. If I use "--no-git-tag-version", I have to run my own git tagging solution in my the postrelease script.

Both of these solutions feel unintuitive from what their options seem to imply.  Am I missing something?

I do see that this PR was opened a while ago and didn't seem to get merged for fear of adding more options.  https://github.com/lerna/lerna/pull/2358

If you don't want to add more options, maybe a doc update for maintainers that mentions manual deleting tags in the remote repo and manually rolling back the version commit would be in order.

**Comment by JamesHenry** [comment]
Closing in favour of #455
