### ISSUE TITLE
lerna add not using semver

### ISSUE THREAD

**Issue by ZebraFlesh** [lerna/lerna#2288]
When using `lerna add`, I can't get lerna to add a dependency using a semver range -- it's always installed with an exact version. Since my CI pipeline runs `npx lerna bootstrap --ci --hoist --strict`, this creates an error. I've tried different forms (package@version, package@^version, package@^version --exact), but they all yield the same result.

## Expected Behavior
`npx lerna add --scope=foo --dev serverless@1.52.0` adds a devDependency to foo's package.json with a range of `^1.52.0`.

## Current Behavior
`npx lerna add --scope=foo --dev serverless@1.52.0` adds a devDependency to foo's package.json with a range of `1.52.0` (exact version instead of semver range).

## Steps to Reproduce (for bugs)
1. Starting with a clean repo, `npm install` at the root
2. `npx lerna bootstrap --ci --hoist --strict` at the root
3. `mkdir workers/foo`
4. `pushd workers/foo`
5. `npm init -y`
6. `popd`
7. `npx lerna add --scope=foo --dev serverless@1.52.0`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "libraries/*",
    "workers/*"
  ],
  "version": "1.0.1"
}
```
</p></details>

## Context
I'm trying to figure out the right way to add a dependency to a new package.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.4.1 |
| `node --version` | 10.15.3 |

| OS | Version |
| --- | --- |
| Windows 10 | 18362 |

**Comment by ZebraFlesh** [comment]
Pretty sure this is still an issue

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
