### ISSUE TITLE
The "--help" flag shows "cli.js" instead of "lerna"

### ISSUE THREAD

**Issue by fjoshuajr** [lerna/lerna#2291]
When I run the command `lerna --help` the instructions mention "cli.js" instead of "lerna".

## Expected Behavior
I expect the help to list lerna as the root command instead of cli.js

## Current Behavior
![image](https://user-images.githubusercontent.com/12100397/66383649-b23ddc00-e9bd-11e9-9ebd-1d91af9dab02.png)

## Possible Solution
I'm not familiar with the codebase.

## Steps to Reproduce (for bugs)
1. `lerna --help`

## Context
I wanted a list of available commands for lerna.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.5 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | 1.19.0 |
| `node --version` | 10.16.3 |

| OS | Version |
| --- | --- |
| Windows 10 | 1903 |

**Comment by fjoshuajr** [comment]
If this is worth pursuing, I'd like to work on a PR 😅

**Comment by evocateur** [comment]
So I'm a bit confused, firstly. When I do this:
```
$ npm i -g lerna
${NVM_DIR}/versions/node/v10.16.3/bin/lerna -> ${NVM_DIR}/versions/node/v10.16.3/lib/node_modules/lerna/cli.js
+ lerna@3.16.5
added 697 packages from 375 contributors in 47.793s
```

I get this (truncated) output when I pass `--help`:
```
$ lerna --help
Usage: lerna <command> [options]

Commands:
  lerna add <pkg> [globs..]  Add a single dependency to matched packages
  lerna bootstrap            Link local packages together and install remaining package dependencies
[...]
```

I've been meaning to update `yargs` to the latest version, we seem to have fallen behind a bit. I'm not really sure if that would fix it, but it might provide a more explicit, Windows-proof way of specifying `$0`...
