### ISSUE TITLE
Fail `lerna publish` when no changes in any packages

### ISSUE THREAD

**Issue by fabb** [lerna/lerna#2292]
We run `lerna publish` on a CI server. In case nothing has been changed in packages, the command should fail so we know that no new package versions have been released.

## Expected Behavior
In case no package was released, the `lerna publish` command should fail.

## Current Behavior

In case the current commit was already released before:
```
lerna notice Current HEAD is already released, skipping change detection.
lerna success No changed packages to publish
```

In case there are newer commits, but no changes to any source files of any packages:
```
lerna success No changed packages to publish
```

## Possible Solution
If just failing `lerna publish` is not deemed a good solution, maybe rather introduce a new flag.

## Context
We are running lerna in a CI environment and send out Slack messages on success with all released packages.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.4.1 |
| `node --version` | v10.14.0 |

| OS | Version |
| --- | --- |
| macOS Catalina | 10.15 |

**Comment by evocateur** [comment]
If you run `lerna changed`, it will exit non-zero when no changed packages are found. It's intended to be a guard used like 

```
lerna changed && lerna publish
```

Used that way in an npm script (or bash-like shell), the non-zero exit code will be preserved and fail the build, just as you desire.

**Comment by fabb** [comment]
Thank you!
