### ISSUE TITLE
when package is `private` dependencies versions don't change if it has `file` reference

### ISSUE THREAD

**Issue by veeramarni** [lerna/lerna#2293]
When we publish packages, if we have package that is `private` and have dependencies on rest all published packages, those versions are not updated in its `package.json` file.

## Expected Behavior

```
{
  "name": "sample-stack-frontend-server",
  "version": "0.0.38-alpha.13",
  "private": true,
  "description": "Sample Client server",
  "dependencies": {
    "@sample-stack/client-react": "^0.0.38-alpha.13",
    "@sample-stack/client-state": "^0.0.38-alpha.13",
    "@sample-stack/core": "^0.0.38-alpha.13",
    "@sample-stack/counter-module-browser": "^0.0.38-alpha.13"
 }
}
```

## Current Behavior

```
{
  "name": "sample-stack-frontend-server",
  "version": "0.0.38-alpha.13",
  "private": true,
  "description": "Sample Client server",
  "dependencies": {
    "@sample-stack/client-react": "file:../../packages/sample-client-react",
    "@sample-stack/client-state": "file:../../packages/sample-client-state",
    "@sample-stack/core": "file:../../packages/sample-core",
    "@sample-stack/counter-module-browser": "file:../../packages-modules/counter/browser"
 }
}
```

## Possible Solution

It seems to be a bug when using `file` reference.

If I manually update to a version and then publish, it is working as expected. 

For example, if I manually correct it and then publish it, it changes to next version `^0.0.38-alpha.14`
```
{
  "name": "sample-stack-frontend-server",
  "version": "0.0.38-alpha.13",
  "private": true,
  "description": "Sample Client server",
  "dependencies": {
    "@sample-stack/client-react": "^0.0.38-alpha.13",
    "@sample-stack/client-state": "^0.0.38-alpha.13",
    "@sample-stack/core": "^0.0.38-alpha.13",
    "@sample-stack/counter-module-browser": "^0.0.38-alpha.13"
 }
}
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | "3.16.5" |
| `npm --version`  | 6.4.1 |
| `yarn --version` | VERSION |
| `node --version` |10.15.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
Why would you expect a private package to be published to the registry? That's the only point at which the local `file:` specifiers are rewritten. Your expectations are not aligned with how Lerna works with `file:` specifiers (you should be using them for _all_ sibling relationships in your monorepo, Lerna resolves the public packages before packaging).

**Comment by veeramarni** [comment]
@evocateur  thanks for your feedback. But have a case where it needs to be updated especially in the non-root package.json file. Can we create a PR for this?

**Comment by evocateur** [comment]
Your options are 1) use relative `file:` specifiers, and 2) don't use relative `file:` specifiers. Option 2 _will_ cause private deps to be updated when they change.

**Comment by veeramarni** [comment]
We still need to use a relative `file:`. Is there a way we can create our own plugins or extension in `lerna` and use that custom plugin for our needs?

**Comment by evocateur** [comment]
You can always fork.
