### ISSUE TITLE
lerna WARN EREPLACE_EXIST @package1 is already installed for  @package2 Replacing with symlink...

### ISSUE THREAD

**Issue by VimalrajVelumani** [lerna/lerna#2297]
I have packages where I run npm install inside every packages and individual package.lock.json is created, when I run lerna bootstrap --ci , I am getting this below error.

lerna WARN EREPLACE_EXIST @package1 is already installed for  @package2 Replacing with symlink...

## Expected Behavior

It should not replace the he created package.lock.json

## Current Behavior

I am gettting the above error

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | VERSION |
| `node --version` | v12.3.1 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.6 |

**Comment by kamranayub** [comment]
This is (probably) due to the recently released feature to respect `publishConfig.directory` when linking, see #2274 

We've been seeing this now due to that and it's not an error or a "real" warning, it's what we _expect_ to happen because top-level node_modules symlink may differ from `packages/*/node_modules` links.

I was going to propose lowering the level of this warning to `debug` perhaps or to detect if it's following the `publishConfig.directory` and ignoring that case and not printing a `WARN` since it's expected.

**Comment by evocateur** [comment]
@VimalrajVelumani If you've _manually_ run  `npm install` in every leaf package, why do you need `lerna bootstrap`? There's a lot of extra hackiness involved with `lerna bootstrap`, so lockfiles that it generates are not compatible with a manual `npm install` (they strip out local sibling packages, for one thing).

**Comment by evocateur** [comment]
@kamranayub I literally don't use `lerna bootstrap`, so if there's an issue with this you think needs fixing you'll need to drive that.

**Comment by kamranayub** [comment]
@evocateur This is from running `lerna link`, not sure about `bootstrap` (we don't use it much either). It isn't _quite_ at the threshold yet of being a priority yet but maybe one of these Fridays.

![image](https://user-images.githubusercontent.com/563819/67422527-4734fd80-f598-11e9-90bc-c3d276ccfe52.png)

**Comment by RobbertWolfs** [comment]
any updates?
