### ISSUE TITLE
Question - lerna publish stable version after alpha (preid)

### ISSUE THREAD

**Issue by vikas027** [lerna/lerna#2302]
## Current Behavior
Hello Everyone,
I am new to lerna and javascript, just trying to help out my team with semantic versioning.

I am trying to implement semantic versioning for Jacascript packages and so far below command is working great for us to create alpha releases and publish them to NPM repository (Jfrog Artifactory) and GitHub.

```
$ lerna publish --no-verify-access --conventional-commits --dist-tag latest --exact --yes --preid=alpha
```

This command bumps up the version in `package.json` of each package (and appends `alpha` i.e. `1.0.0` to `1.0.1-alpha.0`), and commit to GitHub.

Now, once developers are happy with the `alpha` release, how they can publish a stable release of the package i.e. update `package.json` and commit to GitHub. In my example `1.0.1-alpha.0` to `1.0.1`

## Context
I am trying to use semantic versioning for alpha and stable releases.

## Your Environment
```
# yarn lerna --version
yarn run v1.17.3
$ /data/node_modules/.bin/lerna --version
3.16.4
Done in 0.68s.
#

# npm --version
5.6.0
#

# yarn --version
1.17.3
#

# node --version
v8.10.0
#
```

**Comment by evocateur** [comment]
If you use the [`--conventional-graduate`](https://github.com/lerna/lerna/tree/master/commands/version#--conventional-graduate) option, I believe you'll get what you want. You might need to pass `--force-publish` if there have been no changes since the prerelease.

**Comment by vikas027** [comment]
Thanks @evocateur , this helped a ton.

**Comment by xsawn** [comment]
> If you use the [`--conventional-graduate`](https://github.com/lerna/lerna/tree/master/commands/version#--conventional-graduate) option, I believe you'll get what you want. You might need to pass `--force-publish` if there have been no changes since the prerelease.

----
this will publish all packages in the workspace, what should i do if I have just one package that need publish stable version(this package is alpha now)
