### ISSUE TITLE
lerna bootstrap links whole folder, even if files and main are specified

### ISSUE THREAD

**Issue by UnchartedBull** [lerna/lerna#2304]
## Expected Behavior
I've tried to exclude the src, test and node_modules folder from the linked package. I've tried adding them to a .npmignore file and adding the files to the `main` and `files` property of the package.json (in each subproject)

package.json includes:
![Screen Shot 2019-10-16 at 18 00 01](https://user-images.githubusercontent.com/19818061/66936926-d002e500-f03e-11e9-80aa-bad53576eb0e.png)

linked package looks like this however:
![Screen Shot 2019-10-16 at 18 00 08](https://user-images.githubusercontent.com/19818061/66936942-dabd7a00-f03e-11e9-9c96-78dffaa79433.png)

## Current Behavior
Lerna copies the whole folder, including the node_modules, src and test folder

<details><summary>lerna.json</summary><p>

```json
{
    "packages": [
        "packages/*",
        "services/*"
    ],
    "version": "0.0.0",
    "npmClient": "npm"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.18.1 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | - |
| `node --version` | 10.16.3 |

| OS | Version |
| ---: | :--- |
| macOS Catalina | 10.15 |

**Comment by ishaantaylor** [comment]
I'm having an issue that seems similar enough to have the same root cause here:
```
> lerna bootstrap --no-ci --nohoist **

ERR! lerna Unknown arguments: VoxerKit.podspec, VoxerStyle.md, assets, bodies, docs, lerna-debug.log, lerna.json, logs, node_modules, package.json, packages, pids, scripts, secure
```

> ## Your Environment
> Executable	Version
> `lerna --version`	3.18.1
> `npm --version`	6.9.0
> `yarn --version`	-
> `node --version`	10.16.0
> OS	Version
> macOS 10.14.6

**Comment by evocateur** [comment]
@UnchartedBull You're probably looking for [`pkg.publishConfig.directory`](https://github.com/lerna/lerna/blob/master/commands/bootstrap/README.md#publishconfigdirectory) (or `--contents` if it's global). All the other stuff you describe has literally no effect when bootstrapping, as no copying or packing is occurring.

**Comment by evocateur** [comment]
@ishaantaylor That's a separate issue, but unless you've configured `"hoist": true` in your lerna.json, you don't need to pass `--nohoist`. Wrapping the argument with single quotes will prevent the premature shell expansion (`--nohoist '**'`).

**Comment by evocateur** [comment]
@UnchartedBull And actually, I don't quite understand what your problem is? Linking to the directory where the package.json lives with the `"main": "dist/index.js"` is _exactly_ what should be happening (even when transpiling your source). Unless you're trying to do complicated angular/typescript crap, then yeah, `--contents` or `pkg.publishConfig.directory` is what you want.

**Comment by UnchartedBull** [comment]
It is a weird setup, I have to admit that. The problem is that the packages don't get published to npm or any other repository. Each package represents a Lambda Stack, which gets uploaded via the serverless tool. The problem here is, that this will copy the symlinked folder to AWS, including lots of unnecessary files. Therefore I'd like lerna only to link the files, that would be published to npm, without publishing to npm.

I give that a thorough look on Monday and update this issue then. Thanks for the reply!

**Comment by evocateur** [comment]
https://www.npmjs.com/package/serverless-jetpack sounds like something you'd be interested in, then.

**Comment by UnchartedBull** [comment]
I didn't manage to get publishDirectory working ... If I add this to my package.json:
![Screen Shot 2019-10-29 at 17 07 04](https://user-images.githubusercontent.com/19818061/67786387-14df4080-fa6f-11e9-80b1-62c7af4153cd.png)
it will still symlink the whole folder.

However serverless jetpack seems like a really good solution. I set this up and everything seems to be working mostly fine. The `node_modules` folder is excluded correctly from the deployment to AWS, the `src` folder as well as the `test` folder, `README.md` and `tsconfig.json` are still present though. This seems to be an issue with my setup / jetpack, rather than lerna itself.

Thank you so much for this awesome tool and support!

**Comment by UnchartedBull** [comment]
I managed to get this all done with jetpack and Include/Exclude.  Thanks!

**Comment by cevr** [comment]
@evocateur  Where is pkg.publishConfig.directory meant to go? As @UnchartedBull said, it still seems to symlink the whole folder.

**Comment by evocateur** [comment]
@cevr https://docs.npmjs.com/files/package.json#publishconfig

**Comment by cevr** [comment]
> @cevr https://docs.npmjs.com/files/package.json#publishconfig

Thank you for the response. It doesn't seem if it is clear in the docs, but is setting the publishConfig.directory meant to make `lerna bootstrap` only symlink the publishConfig.directory? If so, I am not able to get it working.

@evocateur Any tips? Thank you and happy holidays 🌲

**Comment by evocateur** [comment]
@cevr I linked to the docs [earlier](https://github.com/lerna/lerna/issues/2304#issuecomment-543836298):
> You're probably looking for [`pkg.publishConfig.directory`](https://github.com/lerna/lerna/blob/master/commands/bootstrap/README.md#publishconfigdirectory) (or `--contents` if it's global).

I don't personally use `lerna bootstrap`, so your guess is as good as mine.
