### ISSUE TITLE
no-git-push not working after 3.18.0

### ISSUE THREAD

**Issue by uncleramsay** [lerna/lerna#2305]
```
15:41:24 $ lerna publish prerelease --canary --exact --yes --no-git-tag-version --no-git-push --no-git-reset --no-changelog --dist-tag=pr-157 --preid=alpha-52b7893
15:41:24 ERR! lerna Unknown arguments: git-push, gitPush
15:41:24 error Command failed with exit code 1.
```

## Expected Behavior
Prior to 3.18.0, this does not error out, and publishes without pushing to git.

## Current Behavior
Errors out as in above example

## Steps to Reproduce (for bugs)

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "conventionalCommits": true,
  "registry": <enterprise artifactory url>,
  "verifyAccess": false,
  "verifyRegistry": false,
}
```
</p></details>

## Context
I'm currently unable to publish alphas without locking to a lower version of lerna.

## Your Environment
Running on jenkins

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.18.1 |
| `npm --version`  | 6.10.1 |
| `yarn --version` | 1.15.2 |
| `node --version` | 8.9.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by tkissing-work** [comment]
Other options are also affected:

> ERR! lerna Unknown arguments: git-reset, gitReset, verify-access, verifyAccess, npm-client, npmClient

**Comment by evocateur** [comment]
@uncleramsay There is no `--no-git-push` option, it's called [`--no-push`](https://github.com/lerna/lerna/blob/master/commands/version/README.md#--no-push).

@tkissing-work Which command elicited that error?

**Comment by uncleramsay** [comment]
That's very odd. Prior to 3.18.0 --no-git-push definitely works

**Comment by tkissing-work** [comment]
`lerna version --exact --force-publish --loglevel=verbose --no-git-reset --no-push --no-verify-access --npm-client=npm --yes --no-git-tag-version --preid=20191018175119.master.gitish-7d39735d40 prerelease`

Works fine with 3.17.0, breaks with 3.18.0 and 3.18.1

**Comment by mlavina** [comment]
Hey @evocateur thanks for the quick response, but this still feels like something is wrong. If @uncleramsay had the wrong command and it was working fine and then all they upgraded was to `3.18` wouldn't that same wrong command still work.

Sure it would git push when he didn't want it to, but clearly it was working before. Unless, Lerna added some better error checking and this is an error that the command specified doesn't exist and it just didn't error out before, but that's probably still a break if bad commands worked before.

**Comment by evocateur** [comment]
@tkissing-work 
* `--npm-client` only applies to `lerna bootstrap` and `lerna run`.
* `--no-git-reset` and `--no-verify-access` only apply to `lerna publish`, not `lerna version`.

**Comment by evocateur** [comment]
@mlavina Yargs has been configured with [`.strict()`](https://github.com/yargs/yargs/blob/master/docs/api.md#strictenabledtrue) for [almost two years now](https://github.com/lerna/lerna/blob/0687939004910186a7f2d78373bca3701d84fa5a/src/cli.js#L41). It appears Yargs 14 fixes some bugs that were previously obscuring it.

**Comment by tkissing-work** [comment]
For every version prior to 3.18.x "only applies to" meant "is ignored otherwise". Now it means "breaks your build". That's not SemVer minor. I don't even care if that is directly in your code or was pulled in via a dependency bump. Minor versions of lerna should not break my build.

**Comment by evocateur** [comment]
Your build had silent errors before. I'd say that's much worse than a temporarily broken build.

**Comment by tkissing-work** [comment]
my build updated the package.json files and a later `lerna publish` pushed them to npm. That's exactly what I expected it to do.

**Comment by tkissing-work** [comment]
And SemVer doesn't care if breaking my build now is "better" than silent errors, it only cares about compatibility. lerna 3.18.x is not compatible to 3.17.x.
If lerna does not want to do SemVer, than at the very least you should put a warning into your readme and possibly switch to version numbers that do not suggest SemVer, so consumers know not to let renovate auto-update this dependency.

**Comment by evocateur** [comment]
I'm sorry my fuckups have caused you pain. Please stop berating me, now.

**Comment by mlavina** [comment]
@tkissing-work while I agree in principle clearly this was not @evocateur fault but an underlying package.

It's not fair to put the blame on him. And even if you do feel there is responsibility, you should not be so rude. 

Relax, I get the frustration, but let's be civil. Let's not make the person who runs a massive open source project almost by himself job harder than it needs to be.

**Comment by tkissing-work** [comment]
I was quite polite until I was asked to be thankful for my builds breaking without warning. Unintended breaking changes happen, but blaming it on the consumers is not an appropriate response.

**Comment by evocateur** [comment]
> [...] until I was asked to be thankful for my builds breaking without warning.

When exactly did I say that, @tkissing-work?

* If you're not using a lockfile, then the only one to blame for your builds breaking "without warning" is yourself.
* If you _are_ using a lockfile, then it was an explicit change you made (upgrading `lerna`) that caused the breakage, not a dastardly plan on my part to cause you pain.

The fact remains that the long-standing _intention_ of `lerna`'s argument parsing was to be strict, throwing errors when unrecognized options were passed. There was a bug in yargs 12 that silently perverted this intention, and yargs 14 fixed it.

**Comment by tkissing-work** [comment]
> Your build had silent errors before. I'd say that's much worse than a temporarily broken build.

"I'd say that's much worse than" sounds like you did me a favor, but all I got was extra work.

> If you are using a lockfile, then it was an explicit change you made (upgrading lerna) that caused the breakage

The whole point of SemVer is that this "explicit change" can be made by a machine. The author of a library categorized upgrades into breaking and non-breaking. Software like renovate can then pick certain updates and apply them automatically based on this categorization.

> If you're not using a lockfile, then the only one to blame for your builds breaking "without warning" is yourself.

The condescending attitude aside, a lockfile alone does not help here. Updating lerna necessarily means my lockfile changes. My direct usage of yargs was "protected" by the lockfile, because the selector `yargs@^12.0.1` still gave me 12.0.5 at `node_modules/yargs/`. But without forced hoisting (and thus forced conflict resolutions) that has no impact on what is in `node_modules/lerna/node_modules/yargs/`

> not a dastardly plan on my part to cause you pain

I am not saying you planned this.
Your update broke something for some consumers without being SemVer major. That is unfortunate, but it's a mistake that can happen. 
However, your reaction to the mistake being brought to your intention is somewhere between condescending and hostile.
You could have said "sorry, this was not intended, let me roll back and re-release as 4.0.0" and it would be fine.
You could have said "sorry, I didn't consider that the yargs API practically becomes part of the lerna API, I will make sure that future SemVer major updates of yargs only happen in SemVer major updates of lerna"
Instead you said that it's good that your mistake broke my build.
