### ISSUE TITLE
Lerna commands throw yargs warning

### ISSUE THREAD

**Issue by markypython** [lerna/lerna#2306]
When I run Lerna commands, i.e. `lerna list`, I get the following warning.

```
Configuring yargs through package.json is deprecated and will be removed in a future major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in a future major release, please use the JS API instead.
```

## Expected Behavior
No yargs warning

## Current Behavior
yargs warning is present

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "yarn",
  "packages": ["packages/*"],
  "useWorkspaces": true,
  "version": "independent"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.5 |
| `npm --version`  | 6.10.3 |
| `yarn --version` | 1.19.1 |
| `node --version` | v10.16.1 |

| OS | Version |
| --- | --- |
| macOS Catalina | 10.15 |

**Comment by evocateur** [comment]
I'm not sure how you got a more advanced version of yargs with lerna v3.16.5, which is still using yargs `^12.0.1`. In any case, upgrade to `lerna@latest` (v3.18.1) and the issue goes away, as I upgraded to yargs `^14.2.0` in 3.18.0.

**Comment by sraisty1c** [comment]
I'm seeing this same warning with lerna v3.18.3, so I am still stumped.

**Comment by evocateur** [comment]
@sraisty1c Which command elicited this warning for you?

**Comment by Tassfighter** [comment]
> I'm seeing this same warning with lerna v3.18.3, so I am still stumped.

Same here:
`lerna bootstrap --ignore=@cq/*server`

**Comment by conor-mac-aoidh** [comment]
I am still seeing this error. Is there any workaround?

**Comment by Joshua-rose** [comment]
Issue appears to still be present in v3.20.2 🙁

**Comment by YoDaMa** [comment]
ditto seeing this warning in lerna v3.20.2, but we have no yargs that are being configured.

**Comment by GianfrancoCorrea** [comment]
why is closed?

**Comment by levenleven** [comment]
I had the same problem with global lerna installation (v3.20.2). Uninstalling and installing again fixed the problem (likely fixed dependencies)

**Comment by Sayan751** [comment]
For me it was a problem with global installation. Removed the global package, and used `npx lerna ...` in package root. Fixed it for me.

**Comment by sivaraj-v** [comment]
I'm using  "lerna": "^3.22.1" still I see this issue, let me know what is exact solution to resolve this issue
