### ISSUE TITLE
v3.18.0: `--hoist` no longer accepts multiple string values (yargs v14 change)

### ISSUE THREAD

**Issue by uqcgreen** [lerna/lerna#2307]
## Expected Behavior

The bootstrap command should run and host the included packages as per a previous version:

> lerna bootstrap --ignore-scripts --no-ci --hoist {rollup,postcss-cli,webpack-cli,babel-loader,npm-run-all}

lerna notice cli v3.16.4
lerna info versioning independent
lerna info Bootstrapping 10 packages
lerna info Installing external dependencies
lerna info hoist Finished bootstrapping root
lerna info Symlinking packages and binaries
lerna success Bootstrapped 10 packages

## Current Behavior

$ npx lerna --version
3.18.1

> lerna bootstrap --ignore-scripts --no-ci --hoist {rollup,postcss-cli,webpack-cli,babel-loader,npm-run-all}

ERR! lerna Unknown arguments: postcss-cli, webpack-cli, babel-loader, npm-run-all
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @project-styleguide/project-styleguide@ lerna:bootstrap: `lerna bootstrap --ignore-scripts --no-ci --hoist {rollup,postcss-cli,w
ebpack-cli,babel-loader,npm-run-all}
npm ERR! Exit status 1

## Possible Solution

Not sure, seems like the globbing method has been changed so it only accepts the first argument.

## Steps to Reproduce (for bugs)

1.  As above.

<details><summary>lerna.json</summary><p>

```json

  "lerna": "2.11.0",
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "npm",
  "command": {
    "bootstrap": {
      "npmClientArgs": ["--no-package-lock"]
    },
    "version": {
      "allowBranch": ["releases"]
    }
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

We had to roll back the version.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.18.1 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | n/a |
| `node --version` | 10.14.2 |

| OS | Version |
| --- | --- |
| Oracle linux | 7.6 |
-->

**Comment by evocateur** [comment]
Oops, bitten by a yargs change from v12 to v14. Dang. (Also, `--hoist` is a criminally overloaded option, supporting boolean, string, and multiple strings, and this was probably inevitable).

What happens if you quote the glob?
```
lerna bootstrap --ignore-scripts --no-ci --hoist `{rollup,postcss-cli,webpack-cli,babel-loader,npm-run-all}`
```

Alternatively, specify this list in your lerna.json:
```json
{
  "command": {
    "bootstrap": {
      "hoist": [
        "rollup",
        "postcss-cli",
        "webpack-cli",
        "babel-loader",
        "npm-run-all"
      ]
    }
  },
  ...
}
```

**Comment by uqcgreen** [comment]
Thanks for your response.  Yes quoting seems to fix it, but I think I'll go with specifying them in the lerna.json as you say above.   

(I'm actually brand new to Lerna and working on a script someone else wrote so I couldn't tell you the quoting is 100% working as intended, but it runs happily without error)

**Comment by evocateur** [comment]
Technically, it _used_ to work when the shell auto-expanded a bracketed list (`{foo,bar,baz} == "foo bar baz"`) due to what I assume was a bug with the Yargs parser. The `--hoist` option has _always_ been severely overloaded, and it was only a matter of time before our dirty hacks ran afoul of parser correctness.

I would appreciate a PR that documents this wrinkle (proposing the alternatives you've moved towards). I don't think we should spend any time hacking Yargs to "understand" our mutant usage.

**Comment by aarefiev** [comment]
Hi, guys. Thanks for this issue. It was very helpful.
@evocateur I'd added a note to the bootstrap command readme. Please, check.

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, given it seemingly got to the point where Daniel agreed on the solution was documentation, and that documentation was provided, I'm going to go ahead and merge the docs PR and close this issue.

If you run into any issues on the latest version of lerna, please feel free to open a new issue and follow the instructions:
https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏
