### ISSUE TITLE
Scope flag with regex for one package does not work

### ISSUE THREAD

**Issue by lucas-rudd** [lerna/lerna#2308]
I have a NodeJS script which executes Lerna programmatically using `spawn`. This script provides some basic 'quality-of-life' behaviors for developers, including additional easy-to-understand flags and commands.

Part of this allows developers to pass in a flag to run a deployment script in multiple services through the use of a `-s` flag.

This flag ends up calling 
```javascript
lerna run deploy --scope={${flags[FLAGS.SERVICE_FLAG]}}
```

Where `flags[FLAGS.SERVICE_FLAG]` is a comma separated string for services you wish to deploy.
## Expected Behavior

I would expect that passing in one service to the pattern described by scope (e.g. `--scope={device-service}`) would run the command in _only_ the device service.

## Current Behavior

When passing in multiple services, the command looks something like this, and works as expected
```
lerna run deploy --scope={device-service,customer-service}
```

However when passing in one service, the command looks like this, and does not work
```
lerna run deploy --scope={device-service}
```
Lerna provides the following output

```
lerna notice cli v3.18.1
lerna notice filter including "{device-service}"
lerna info filter [ '{device-service}' ]
lerna ERR! EFILTER No packages remain after filtering [ '{device-service}' ]
```

## Steps to Reproduce (for bugs)

1. Using a mono-repo managed by Lerna
2. Run a command at the root with the `--scope={package1,package2}`, where `package1` and `package2` are two packages that exist in the repo
3. Run the same command at root with the `--scope={package1}` flag

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "yarn",
  "useWorkspaces": true,
  "packages": [
    "packages/*",
    "services/*"
  ],
  "version": "0.0.0"
}

```
</p></details>

## Context

I'm trying to develop a script which is able to generically and dynamically run scripts with certain scopes, providing an easier way to interact with the mono-repo for developers who are not used to lerna's complexities.

Simply allow for a single package to be passed into the scope brackets.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.16.0 |
| `node --version` | v10.15.3 |

| OS | Version |
| --- | --- |
| macOS Catalina | 10.15 |

**Comment by evocateur** [comment]
Semantic nit: the values for `--scope` are globs, not regular expressions.

We use [multimatch](https://www.npmjs.com/package/multimatch) for parsing this, which is a wrapper around [minimatch](https://www.npmjs.com/package/minimatch). [Playing around with minimatch](https://npm.runkit.com/minimatch), the conclusion I come to is a `{}` list with only one item is an invalid glob:
```js
var minimatch = require("minimatch")

console.log("single braced = %j", minimatch("my-lib", "{my-lib}"));
// => "single braced = false"

console.log(" multi braced = %j", minimatch("my-lib", "{my-lib,}"));
// => " multi braced = true"
```

In the second test _any_ value after the comma works, including an empty string. So you should probably add a trailing comma to your interpolated value. Also, I recommend wrapping that glob with single quotes to prevent premature shell expansion, ensuring the literal value makes its way correctly to `multimatch`.

**Comment by lucas-rudd** [comment]
Thanks for the work-around @evocateur , that works on my end.
I was curious to know if this adhered to the glob standards. This is not a bug in `minimatch`, this is actually how glob patterns work on Linux systems as well. So, I guess this was just a case of me lacking knowledge.

Thanks again @evocateur

**Comment by evocateur** [comment]
As far as I know, `minimatch` makes a great effort to be as compatible as possible with POSIX globs. Single-quoting globs you want passed as-is to scripts (instead of being interpreted and expanded by the shell) is a good habit to get into for general shell scripting.
