### ISSUE TITLE
How is the command or configuration for nohoist a lerna managed local package

### ISSUE THREAD

**Issue by billygl** [lerna/lerna#2309]
`--nohoist` arguments are globs for dependency names (e.g., `uuid` or `react*`), not the names of lerna-managed local (aka "leaf") packages.

_Originally posted by @evocateur in https://github.com/lerna/lerna/issues/1794#issuecomment-442253483_

**Comment by evocateur** [comment]
`--nohoist` only applies to external dependencies. It literally makes no sense when applied to local Lerna-managed packages.

**Comment by billygl** [comment]
ok.
In my case, i have two packages: one for react native and other for react web. Both are local but they have external dependencies.
But I don't want to hoist react native packages.
