### ISSUE TITLE
Customize `packages` folder

### ISSUE THREAD

**Issue by danderu** [lerna/lerna#231]
Is it possible to place my modules in a different directory than `packages`? Let's se, if I don't like the name `packages` and I would place all of them under `modules`?. This line: https://github.com/lerna/lerna/blob/master/src/PackageUtilities.js#L15 could be reading some key from lerna.json, for instance. Makes sense?

Also, is it possible to link packages recursively under the `packages` folder For instance, with this structure?

```
packages
|_ui-components
|__input
|__button
|_apps
|__some-app
|__yet-another-app
|_my-app-core
```

**Comment by thejameskyle** [comment]
> Is it possible to place my modules in a different directory than packages?

No but I'm happy to allow for that.

> Also, is it possible to link packages recursively under the packages folder For instance, with this structure?

No it is not possible, and I don't think it ever will be

**Comment by zkochan** [comment]
If it will be configurable, I would suggest to allow specifying patterns.

**Comment by jameswomack** [comment]
I would also love for it to be configurable. It's a minor issue, but one that I'm happy to open a PR for. Having a directory with such a similar name to package.json makes semantic sense—but makes ZSH autocomplete less effective. I use autocomplete to quickly open files in vim and package.json is one of the files I most frequently open with vim. I'm sure there are other better reasons to have it configurable too ;)

If I open a PR that allows a field folderName (or directoryName) in lerna.json to point to a directory that can be reached via `Path.resolve(Path.basename(lernaJSON, folderName)`, is that something you might merge?

**Comment by zkochan** [comment]
I have a project in which the subpackages are all in the root directory. They're just prefixed with some word. That's why I'd need the possibility to specify a pattern, not just one dir name.

**Comment by hzoo** [comment]
From http://staltz.com/setting-up-a-javascript-monorepo.html: packages are also in the root directory for https://github.com/cyclejs/cyclejs

**Comment by gigabo** [comment]
@danderu I think #332 should provide what you're looking for here.

Please take a look if you get a chance.

**Comment by thejameskyle** [comment]
See #365
