### ISSUE TITLE
https-proxy-agent Machine-In-The-Middle high vulnerability advisory

### ISSUE THREAD

**Issue by dominikfoldi** [lerna/lerna#2310]
Today the advisory went live about https-proxy-agent that it is vulnerable  to Machine-In-The-Middle attacks. https://www.npmjs.com/advisories/1184

We should upgrade it to >=3.0.0 ASAP!

**Comment by evocateur** [comment]
This is an upstream issue, Lerna has no direct dependency on this package: https://github.com/npm/make-fetch-happen/pull/6

**Comment by flosch-hb** [comment]
Hey @evocateur, wouldn't it be better to leave this open for now?
I guess the dependencies will still need to be updated when the upstream issue is resolved (unless I miss something)?

**Comment by evocateur** [comment]
@flosch-hb There's nothing Lerna can do, so I would encourage you to have patience. Nobody runs Lerna in production, so the attack vector here is minuscule.

**Comment by flosch-hb** [comment]
@evocateur I understand that, and also the risk, which can in almost every case be saved by forcing the resolution of `https-proxy-agent` to 3.0.0, but once the upstream issue will be fixed, there will still be a need for updating lerna’s package.json, right?

My thoughts regarding leaving issues open is about not losing track of them, hence my question, but perhaps you keep track of those differently?

**Comment by evocateur** [comment]
I just don't see what's actionable about this issue. Lerna doesn't specify a direct dependency on this package, thus there is literally nothing for me to do?

**Comment by dkorobeinikov** [comment]
The [PR](https://github.com/npm/make-fetch-happen/pull/6) for `make-fetch-happen` is closed, but it seems like the issue is fixed with v5.0.1
