### ISSUE TITLE
GitHub Action for lerna publish > Detached HEAD despite git checkout

### ISSUE THREAD

**Issue by jpvalery** [lerna/lerna#2314]
I'm trying to get lerna publish to run in a GitHub Action in order to stop relying on Travis for that. 

All my workflow works well until I try to publish (see [example](https://github.com/narative/gatsby-theme-novela/commit/4b722f9f9dd6f8c54bfc88e5884484d5ffc3acda/checks?check_suite_id=274657864)). 

Workflow: https://github.com/narative/gatsby-theme-novela/blob/master/.github/workflows/publish.yml

Here's the step that is running into an error:
```yaml
    - name: Publish with Lerna
      run: git remote add -f pub https://${GH_TOKEN}@github.com/narative/gatsby-theme-novela.git && git checkout pub/master && yarn lerna publish --yes --registry https://registry.npmjs.org/:_authToken=${NPM_TOKEN} --git-remote pub
```

Any hint or help is appreciated - totally understand if it's out of your scope and should rather be addressed with GitHub support.

## Expected Behavior
I'd expect lerna publish to run without error

## Current Behavior
```
HEAD is now at 4b722f9 fix: revert change for git checkout
yarn run v1.19.0
$ /home/runner/work/gatsby-theme-novela/gatsby-theme-novela/node_modules/.bin/lerna publish --yes --registry https://registry.npmjs.org/:_authToken=*** --git-remote pub
lerna notice cli v3.16.4
lerna info versioning independent
lerna ERR! ENOGIT Detached git HEAD, please checkout a branch to choose versions.
```

Despite checking out, I still get the error for a detached git HEAD

## Possible Solution
Is this because the command is not running in the right directory? Should I `cd /home/runner/work/gatsby-theme-novela/gatsby-theme-novela`?

## Context
I'm trying to get lerna publish to run in a GitHub Action in order to stop relying on Travis for that. 

## Your Environment
GitHub Action running on ubuntu-latest

**Comment by evocateur** [comment]
I'm not sure adding a remote and running `git checkout pub/master` is going to do the trick for you. There are several solutions to the "detached HEAD" problem here: https://github.com/actions/checkout/issues/6

**Comment by jpvalery** [comment]
I was basing myself on the travis.yml we had set up but looks like this did the trick! 

![image](https://user-images.githubusercontent.com/4112343/67246475-8a725d80-f42c-11e9-9591-6b3ee8881aea.png)

Thank you so much!

**Comment by StephanBijzitter** [comment]
Had the same on Codeship, for me this worked:
```
git fetch origin +refs/heads/master:refs/remotes/origin/master;
git checkout master;
git reset --hard "$CI_COMMIT_ID";

// lerna stuff
```
The above could also work, no idea, didn't try. Just listing an alternative :-)

**Comment by fabb** [comment]
i'm doing it like this in Gitlab:
```
git fetch
set +e
git symbolic-ref -q HEAD > /dev/null || (git branch -d ${CI_COMMIT_REF_NAME} || true && git checkout -b ${CI_COMMIT_REF_NAME} && git branch --set-upstream-to=origin/${CI_COMMIT_REF_NAME} ${CI_COMMIT_REF_NAME})
set -e
```

**Comment by vadivkanag** [comment]
For me the same issue got sorted by checking out the source branch, btw this issue happens to me during PR runs.
```
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          clean: true
          fetch-depth: 0
```
