### ISSUE TITLE
Can no longer use lerna publish, fails with error

### ISSUE THREAD

**Issue by phun-ky** [lerna/lerna#2315]
We can no longer publish packages when using `lerna publish`, it fails with error:

```bash
ERR! lerna bump must be an explicit version string _or_ one of: 'major', 'minor', 'patch', 'premajor', 'preminor', 'prepatch', 'prerelease', 'from-git', or 'from-package'.
```
It seems I'm suddenly hitting this: https://github.com/lerna/lerna/blob/ac8385d77e931397b68b068ded7ac83dd1a19d68/commands/version/command.js#L254

For no apparent reason..

## Expected Behavior
Using this _unchanged_ command:

```bash
$ lerna publish --exact --loglevel=warn --registry=https://<projec>.myget.org/F/<category>/auth/<token>/npm/ --yes --no-verify-access --no-verify-registry -- --unsafe-perm --loglevel=warn
```
I expect that packages are published
## Current Behavior
I'm getting the formentioned error. 

## Possible Solution
This worked 7+ days ago, did something break? A breaking change?

## Steps to Reproduce (for bugs)
Run above command

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "packages": [
    "packages/*"
  ],
  "changelog": {
    "repo": "...",
    "cacheDir": ".changelog",
    "labels": {
      "problems: breaking change": "💥 Breaking Change",
      "additions: feature": "✨ New Feature",
      "problems: bug": "🐛 Bug Fix",
      "improvements: enhancement": "💅 Enhancement",
      "improvements: upgrade deps": "⬆️ Upgrade deps",
      "improvements: optimization": "⚡️ Optimization",
      "mindless: chore": "🏠 Internal",
      "mindless: documentation": "📝 Documentation"
    }
  },
  "version": "8.3.6",
  "command": {
    "init": {
      "exact": true
    },
    "publish": {
      "message": "chore(release): :bookmark: publish %s ***NO_CI***",
      "conventionalCommits": true,
      "npmClient": "npm",
      "verifyAccess": false,
      "verifyRegistry": false,
      "registry": "---"
    }
  }
}

```
</p></details>

## Context
Cant publish packages
## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.18.2, works locally with 3.13.0 (package) or 3.4.0 (global)|
| `npm --version`  | latest from build environment|
| `node --version` | v8.14.0 or higher |

| OS | Version |
| --- | --- |
| Ubuntu | 18.04 |

**Comment by evocateur** [comment]
This is definitely a bug, thanks for the report. I believe I have a workaround.

**Comment by evocateur** [comment]
Also, note that arguments after `--` are no longer passed to subprocess executions of `npm`, since [v3.7.0](https://github.com/lerna/lerna/releases/tag/v3.7.0).

**Comment by evocateur** [comment]
[v3.18.3](https://github.com/lerna/lerna/releases/tag/v3.18.3)

**Comment by phun-ky** [comment]
@evocateur thanks! btw, where can I find documentation on the subprocess executions? (passing args after `--` ?

**Comment by evocateur** [comment]
https://github.com/lerna/lerna/tree/master/commands/exec#usage and https://github.com/lerna/lerna/tree/master/commands/run#usage are the places that document when/if a `--` is necessary. Those are the only commands that need it.

**Comment by hjr3** [comment]
I ran into this error due to an empty string at the end of the publish command:

`lerna publish --yes --npm-tag latest --repo-version 1.0.0 ''` - notice the `''` at the end.

The above publish command was generated inside a bash function that sometimes took a parameter:

```bash
lerna_publish_to () {
  lerna publish --yes --npm-tag latest --repo-version 1.0.0 "$1"
}
```

When the parameter was not included in the function call, we get the above command and lerna throws the error.

```bash
lerna_publish_to --skip-git # works
lerna_publish_to # fails
```

The fix is some arcane bash:

```bash
lerna_publish_to () {
  lerna publish --yes --npm-tag latest --repo-version 1.0.0 ${1:+"$1"}
}
```
