### ISSUE TITLE
lerna ERR! lerna ENOENT: no such file or directory open `package.json`

### ISSUE THREAD

**Issue by coreybruyere** [lerna/lerna#2317]
When attempting to publish through Lerna I'm getting this error after creating a new release version number and after Lerna has pushed tags (`lerna run build && lerna publish --contents dist`). Lerna is building and publishing each package as it always has for me but this new package is halting the entire process since it can't find `package.json`. When I run `npm pack` on this package the generated files has a `package.json` so I'm not sure why my Lerna set up isn't able to access `package.json`. 

This issue is due to my lack of package publishing and I'm hoping to get a better understanding of it while figuring this out. 

Generally speaking, when a bundler (webpack, rollup, etc) bundles src files and outputs them into an out directory (`.dist/` in my case) does package.json get pulled into those out files as well when executing a build? (using rollup, not sure what magic is really happening)

## Your Environment
Using rollup.js to bundle this package. 

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.12.0 |
| `yarn --version` | 1.7.0 |
| `node --version` | v12.13.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
No, the `--contents` option is a dirty hack for people who _insist_ they need to recreate the _entire_ package structure in a subdirectory. A traditional `dist` directory that you point to in your package.json's `main` (or `module`) field absolutely does **not** require `--contents` to be employed.

Just omit it entirely, and you'll be fine. I've published literally thousands of versions of hundreds of packages that use transpiled output (with Rollup, Babel, _or_ Webpack) without ever needing to use `--contents` with `lerna publish`.

**Comment by navono** [comment]
without `--contents`, stll get the error.

**Comment by stdavis** [comment]
@coreybruyere Did you ever solve your problem? I'm having the same issue.

**Comment by coreybruyere** [comment]
I don't recall how I resolved this issue. I remember doing things like running `npm run clean && npm i`, and simplifying my project structure to get a better understanding of what was happening.
