### ISSUE TITLE
Please provide an option to not use `publishConfig.directory` for `lerna bootstrap`

### ISSUE THREAD

**Issue by crusoexia** [lerna/lerna#2318]
Provide an option to let `lerna bootstrap` link to packages directly instead of link to `publishConfig.directory`.

## Expected Behavior

`lerna bootstrap` should provide an option to directly link to package.

## Current Behavior

After upgrade to lerna 3.18, `lerna bootstrap` will link to `publishConfig.directory`, which break our build.

## Possible Solution

`lerna bootstrap --direct-link` or `lerna bootstrap --ignore-publishConfig` to ignore the `publishConfig.directory`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "4.1.0",
  "conventionalCommits": true
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.18.0 |
| `npm --version`  | 6.12.0 |
| `node --version` | 10.15.0 |

| OS | Version |
| --- | --- |
| macOS | 10.14.6 |

**Comment by evocateur** [comment]
Please use the issue template, it's there for a reason.

**Comment by crusoexia** [comment]
@evocateur updated.

**Comment by crusoexia** [comment]
Now I'm using lerna publish --contents to publish the subdirectories instead of `publishConfig.directory`, so don't care about this issue anymore.

**Comment by nelson6e65** [comment]
https://github.com/lerna/lerna/issues/3103
