### ISSUE TITLE
Execute commands right before execution of the version command

### ISSUE THREAD

**Issue by aledpardo** [lerna/lerna#2320]
Hi Lerna team!

Thanks for this fantastic tool!

I have the following idea/request and would like to hear your comments/thoughts.

## Expected Behavior

Execute additional commands per package during the version command.
## Current Behavior

Version command exits with error if there are uncommitted changes.
## Possible Solution

Add flag to execute a command during the version command. Add the changes to the commit. Verification of a clean branch remains in the beginning.
## Steps to Reproduce (for bugs)

1. Execute actions that modifies files before running Lerna version
2. Stage the changes
3. Run Lerna version
4. Lerna version exits with error 

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

There may be additional changes to the affected packages that must be done at the same time the version tag is created.
## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.18.0 |

**Comment by aledpardo** [comment]
By studying the `version` command I found out that the behavior I'm looking for might be already supported.

I should rely on the `preversion`, `version`, `postversion` scripts. Those are executed after the initial validation of the working tree being dirty.

I'll try it out and write here the outcome.

**Comment by aledpardo** [comment]
I've just run my tests and confirmed the above behavior.

This issue can be closed as the expected behavior is already fulfilled.

**Comment by evocateur** [comment]
If there's anything we can do to improve the documentation, PRs welcome!
