### ISSUE TITLE
Question: how to prevent lerna from creating git tag and pushing it when publishing package?

### ISSUE THREAD

**Issue by georgyfarniev** [lerna/lerna#2322]
Subj

UPD: I tried to publish with **from-package** option, but it says that no packages changed since last upload, but my registry are empty. So how can I publish packages with lerna WITHOUT modifying anything in git (no commit, no push), just publish packages if current version are not present in registry?

**Comment by i11v** [comment]
Please, try the [`--no-git-tag-version` option](https://github.com/lerna/lerna/tree/master/commands/version#--no-git-tag-version) to prevent a tag creating

**Comment by evocateur** [comment]
You need to change the package versions somehow (`lerna version --no-git-tag-version` if you don't want to keep track in git, I guess), then `lerna publish from-package` will work.
