### ISSUE TITLE
How should we correctly handle cyclic dependencies with lerna

### ISSUE THREAD

**Issue by alesmenzel** [lerna/lerna#2327]
# Use case: 
Imagine a package (e.g. a logger) that has some plugins (e.g. log to console/file/etc.).

package: **logger**
_dependecies_:
 - console - used as a default transport

package: **console**
_devDependencies_:
 - logger - used to test (acceptance) the transport

# The problem
The current setup warns on circular dependency.

**Comment by edenworky** [comment]
As another use case, I'm building a testing tool that had some more generally useful stuff in it, which I extracted to a separate package to reuse.

But my testing tool has a `dependency` on my extracted package, and my extracted package has a `devDependency` on my testing tool.
