### ISSUE TITLE
Relative paths in file proxy

### ISSUE THREAD

**Issue by sveisvei** [lerna/lerna#233]
**Problem**: Absolute paths does not allow for renaming project folder, or moving the folder around. 
My specific issue is that I would like to host/run the dev-setup with `lerna bootstrap` and friends on an Heroku instance, but Heroku does move the projectfolder after a successful build/install.

**Solution a**: Write relative paths. My suggestion is to try to `require.resolve()` first, then fallback to relative folder require. Code/PR: https://github.com/lerna/lerna/compare/master...sveisvei:relative-paths

Is this a feature that would be interesting?

**Alternative/Other solution** for this setup is to run `lerna bootstrap`another time before npm start after the build/install-step.

**Comment by ianwremmel** [comment]
I'd love to see something like this. I'm working a project that needs to be distributed to partners several months before I can release it publicly. I'm relatively confident that this would let me use bundleddependendencies to distribute a tarball.

**Comment by sveisvei** [comment]
I think this is better solved with using symlinks (https://github.com/lerna/lerna/pull/237), so I will close this :).

**Comment by arbesfeld** [comment]
Hi @sveisvei, I'm not sure if symlinks fixes this problem. On Heroku I have to run `bootstrap` before `npm start` to achieve the desired effect.

**Comment by sveisvei** [comment]
I think lerna bootstrap now does linking, so it should be fine :).

**Comment by arbesfeld** [comment]
Thanks @sveisvei, symlinking does work for me, but lerna seems to do linking with relative paths.

On heroku I see the following symlink:

`foo -> /tmp/build_3d04f79d2cd3d7f7b8320df7a1686d93/foo19b7aa6f936076ccad3a4cb4697ef777ba241c35/packages/@apphub:foo`

Is there a way to make the symlinking process use relative paths?

**Comment by JaapRood** [comment]
@arbesfeld did you resolve this at some point? I'm running into the same problem on Heroku and stuck with running `lerna bootstrap` as part of app runtime instead of compile time.
