### ISSUE TITLE
Audit Issue - Machine-In-The-Middle

### ISSUE THREAD

**Issue by ma-jahn** [lerna/lerna#2330]
There is a NPM Audit issue related to lerna.
https://www.npmjs.com/advisories/1184

https-proxy-agent is a sub dependecy of several lerna packages.

## Expected Behavior
`yarn audit` doesn't list any vulnerable lerna package.

## Current Behavior
`yarn audit` currently shows several Issues related to subdependencies of lerna

| high | Machine-In-The-Middle |
| ---: | :--- |
| Package       | https-proxy-agent                                            |
| Patched in    | >=2.2.3                                                      |
| Dependency of | lerna                                                        |
| Path          | lerna > @lerna/add > @evocateur/pacote >                     |
|               | @evocateur/npm-registry-fetch > make-fetch-happen >          |
|               | https-proxy-agent                                            |
| More info     | https://www.npmjs.com/advisories/1184                        |

| high | Machine-In-The-Middle |
| ---: | :--- |
| Package       | https-proxy-agent                                            |
| Patched in    | >=2.2.3                                                      |
| Dependency of | lerna                                                        |
| Path          | lerna > @lerna/create > @evocateur/pacote >                  |
|               | @evocateur/npm-registry-fetch > make-fetch-happen >          |
|               | https-proxy-agent                                            |
| More info     | https://www.npmjs.com/advisories/1184                        |

| high | Machine-In-The-Middle |
| ---: | :--- |
| Package       | https-proxy-agent                                            |
| Patched in    | >=2.2.3                                                      |
| Dependency of | lerna                                                        |
| Path          | lerna > @lerna/publish > @evocateur/pacote >                 |
|               | @evocateur/npm-registry-fetch > make-fetch-happen >          |
|               | https-proxy-agent                                            |
| More info     | https://www.npmjs.com/advisories/1184                        |

| high | Machine-In-The-Middle |
| ---: | :--- |
| Package       | https-proxy-agent                                            |
| Patched in    | >=2.2.3                                                      |
| Dependency of | lerna                                                        |
| Path          | lerna > @lerna/publish > @evocateur/libnpmaccess >           |
|               | @evocateur/npm-registry-fetch > make-fetch-happen >          |
|               | https-proxy-agent                                            |
| More info     | https://www.npmjs.com/advisories/1184                        |

| high | Machine-In-The-Middle |
| ---: | :--- |
| Package       | https-proxy-agent                                            |
| Patched in    | >=2.2.3                                                      |
| Dependency of | lerna                                                        |
| Path          | lerna > @lerna/publish > @evocateur/npm-registry-fetch >     |
|               | make-fetch-happen > https-proxy-agent                        |
| More info     | https://www.npmjs.com/advisories/1184                        |

| high | Machine-In-The-Middle |
| ---: | :--- |
| Package       | https-proxy-agent                                            |
| Patched in    | >=2.2.3                                                      |
| Dependency of | lerna                                                        |
| Path          | lerna > @lerna/publish > @lerna/npm-dist-tag >               |
|               | @evocateur/npm-registry-fetch > make-fetch-happen >          |
|               | https-proxy-agent                                            |
| More info     | https://www.npmjs.com/advisories/1184                        |

| high | Machine-In-The-Middle |
| ---: | :--- |
| Package       | https-proxy-agent                                            |
| Patched in    | >=2.2.3                                                      |
| Dependency of | lerna                                                        |
| Path          | lerna > @lerna/publish > @lerna/npm-publish >                |
|               | @evocateur/libnpmpublish > @evocateur/npm-registry-fetch >   |
|               | make-fetch-happen > https-proxy-agent                        |
| More info     | https://www.npmjs.com/advisories/1184                        |

| high | Machine-In-The-Middle |
| ---: | :--- |
| Package       | https-proxy-agent                                            |
| Patched in    | >=2.2.3                                                      |
| Dependency of | lerna                                                        |
| Path          | lerna > @lerna/add > @evocateur/pacote > make-fetch-happen > |
|               | https-proxy-agent                                            |
| More info     | https://www.npmjs.com/advisories/1184                        |

| high | Machine-In-The-Middle |
| ---: | :--- |
| Package       | https-proxy-agent                                            |
| Patched in    | >=2.2.3                                                      |
| Dependency of | lerna                                                        |
| Path          | lerna > @lerna/create > @evocateur/pacote >                  |
|               | make-fetch-happen > https-proxy-agent                        |
| More info     | https://www.npmjs.com/advisories/1184                        |

| high | Machine-In-The-Middle |
| ---: | :--- |
| Package       | https-proxy-agent                                            |
| Patched in    | >=2.2.3                                                      |
| Dependency of | lerna                                                        |
| Path          | lerna > @lerna/publish > @evocateur/pacote >                 |
|               | make-fetch-happen > https-proxy-agent                        |
| More info     | https://www.npmjs.com/advisories/1184                        |

## Steps to Reproduce (for bugs)
Run `yarn audit` after installing latest version of lerna

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.18.3 |
| `yarn --version` | 1.17.3 |
| `node --version` | 10.15.3 |

**Comment by evocateur** [comment]
Reset your lockfile (or `npm rm -D lerna && npm i -D lerna`) and your fears will be calmed.
