### ISSUE TITLE
Scope option does not work when node option is specified.

### ISSUE THREAD

**Issue by gr4vitonn** [lerna/lerna#2331]
## Expected Behavior
Scoped build should work even if node options are specified.

## Current Behavior
I have the following build script in my `package.json`:

```
"scripts": {
	"build": lerna exec -- node --max-old-space-size=10000 ./build
}
```

When I run the following command, scope is ignored: `npm run build -- --scope @myorg/mypackage`.

When I remove the node option, and I run the same script, the scoped package is respected:
1. `"build": lerna exec node ./build`
2. `npm run build -- --scope @myorg/mypackage`

## Your Environment
lerna 2.11.0
npm 6.11.3
node 10.16.3

**Comment by evocateur** [comment]
That's because `npm run build -- --scope @myorg/mypackage` is passing `"--scope" "@myorg/mypackage"` to the end of the script, which when using the `--` _in_ the script means it is always ignored by lerna.
