### ISSUE TITLE
bootstrap --hoist: no bin symlink

### ISSUE THREAD

**Issue by sveyret** [lerna/lerna#2340]
I have a monorepo. I execute the command:

    npx lerna bootstrap --hoist

It installs everything. Then I run

    npx lerna run build

The first executed package has a dev-dependency to `typescript`, but it fails because it cannot find the `tsc` binary (typescript compiler) which did not install itself locally, even if the `lerna-bootstrap --hoist` documentation says the contrary:

> Any binaries from these dependencies will be linked into dependent package `node_modules/.bin/` directories so they're available for npm scripts.

## Expected Behavior

A link should be made from `node_module/.bin/tsc` to the appropriate `typescript` file.

## Current Behavior

No link is made, and `tsc` cannot be executed.

    tsc : command not found

Note that when using `yarn` workspace, the link is made appropriately.

## Steps to Reproduce (for bugs)
1. `npx lerna bootstrap --hoist`
2. `npx lerna run build`

<details><summary>lerna.json</summary><p>

```json
{
  "useWorkspaces": true,
  "version": "1.1.0-alpha.0"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.18.4 |
| `npm --version`  | 6.12.0 |
| `yarn --version` | 1.19.1 |
| `node --version` | 12.13.0 |

| OS | Version |
| --- | --- |
| Gentoo | 17.1 |

**Comment by fahslaj** [comment]
It is no longer recommended to use lerna bootstrap. The recommendation for modern version of Lerna is to rely on the workspaces functionality of whichever package manager you are using. I would suggest checking out the [legacy package management](https://lerna.js.org/docs/legacy-package-management) page in the Lerna docs.

Older versions of Lerna that don't support workspaces are no longer supported, and alternatives to workspaces are outlined in that doc.
