### ISSUE TITLE
How to make jest tests that involve components imported from other packages?

### ISSUE THREAD

**Issue by skywickenden** [lerna/lerna#2341]
If I have a component that imports a second component from another package in the same monorepo then Jest doesn't import it correctly

## Steps to Reproduce (for bugs)
packages/components/src/Bar.js

    import React from 'react'
    function Bar({ children }) {
      return <div>{children}</div>
    }
    export default Bar

packages/main/src/Foo.js

    import React from 'react'
    import { Bar } from 'components'

    function Foo() {
      return <Bar>Foo</Bar>
    }
    export default Foo

packages/main/src/Foo.test.js

    import React from 'react'
    import { render } from '@testing-library/react'
    import Foo from './home'

    describe('Foo', () => {
      test('Renders', () => {
        const { getByText } = render(<Foo />)

        expect(getByText('Foo'))
      })
    })

jest and @testing-library-react are installed in the `main` package and run from there.

The test fails with 

    Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check the render method of `Foo`.

      5 | describe('Foo', () => {
      6 |   test('Renders', () => {
    >  7 |     const { getByText } = render(<Foo />)
        |                           ^
      8 | 
      9 |     expect(getByText('Foo'))
      10 |   })

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "yarn",
  "useWorkspaces": true,
  "packages": [
    "packages/*",
    "hasura"
  ],
  "version": "0.0.0"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.18.4 |
| `yarn --version` | 1.19.1 |
| `node --version` | 12.12.0 |

| OS | Version |
| ---: | :--- |
| macOS Catalina | 10.15.1 |

**Comment by boverU** [comment]
> If I have a component that imports a second component from another package in the same monorepo then Jest doesn't import it correctly
> 
> ## Steps to Reproduce (for bugs)
> packages/components/src/Bar.js
> 
> ```
> import React from 'react'
> function Bar({ children }) {
>   return <div>{children}</div>
> }
> export default Bar
> ```
> 
> packages/main/src/Foo.js
> 
> ```
> import React from 'react'
> import { Bar } from 'components'
> 
> function Foo() {
>   return <Bar>Foo</Bar>
> }
> export default Foo
> ```
> 
> packages/main/src/Foo.test.js
> 
> ```
> import React from 'react'
> import { render } from '@testing-library/react'
> import Foo from './home'
> 
> describe('Foo', () => {
>   test('Renders', () => {
>     const { getByText } = render(<Foo />)
> 
>     expect(getByText('Foo'))
>   })
> })
> ```
> 
> jest and @testing-library-react are installed in the `main` package and run from there.
> 
> The test fails with
> 
> ```
> Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check the render method of `Foo`.
> 
>   5 | describe('Foo', () => {
>   6 |   test('Renders', () => {
> >  7 |     const { getByText } = render(<Foo />)
>     |                           ^
>   8 | 
>   9 |     expect(getByText('Foo'))
>   10 |   })
> ```
> 
> lerna.json
> ## Your Environment
> Executable	Version
> `lerna --version`	3.18.4
> `yarn --version`	1.19.1
> `node --version`	12.12.0
> OS	Version
> macOS Catalina	10.15.1
Passed 2 years, but still, Did you solve the problem?

**Comment by fahslaj** [comment]
Closing this issue as it is extremely old. If you feel like this is still an issue with Lerna, feel free to follow up and we can try to help.
