### ISSUE TITLE
Question: Does lerna support working with git submodules?

### ISSUE THREAD

**Issue by miguelmota** [lerna/lerna#2342]
Does lerna support working with git submodules?

**Comment by evocateur** [comment]
No, sorry.

**Comment by miguelmota** [comment]
@evocateur do you mind elaborating on why not to help me understand?

**Comment by evocateur** [comment]
Searching a repo's issues before opening your own is often fruitful: https://github.com/lerna/lerna/search?q=submodules&unscoped_q=submodules&type=Issues

**Comment by miguelmota** [comment]
> Searching a repo's issues before opening your own is often fruitful: https://github.com/lerna/lerna/search?q=submodules&unscoped_q=submodules&type=Issues

I did search and didn't find anything helpful which is why I asked this question to get a more up-to-date elaborate answer on the technical challenges.

**Comment by hinell** [comment]
@miguelmota Hey, how are you doing? 
Have any plans to fork off lerna and implement support for git sumbodules? I would like to discuss it.

**Comment by miguelmota** [comment]
Hey there @hinell , yeah would like to discuss the challenges of supporting git submodules to see if I can be of any help since this feature is much needed

**Comment by hinell** [comment]
@miguelmota What features you expect Lerna to have to be able to handle submodules? 

I recently came to a conclusion that Lerna would work well without supporting sub modules (in any way) if you only need versioning recorded in the root repo. Otherwise sub modules may be handled by basic `npm version` or `git tag`s separately.

Any thoughts?

**Comment by btakita** [comment]
@hinell I ran into this issue as well. So far, the only issue I have come across is with `lerna publish`.

It seems to error when performing the commit. With the submodule, the commit should occur in the submodule repo instead...

**Comment by hinell** [comment]
@btakita 
Does lerna complain when your remove submodules's `.git/` sub folder?
I'm not a maintainer but just want know more about issues related to the submodules handling cause I'm planning to use it in the project where there are a lot of submodules.

**Comment by btakita** [comment]
It throws an error when `git add` is attempted. You can skip the `git add` using `lerna version --skip-git` or writing your own code using lerna's objects.

I'm working on a submodule-specific `lerna publish` script. I'll probably just post the gist & move on b/c I'm pretty swamped atm. But if I have time to circle back & create a PR I'll do so.
