### ISSUE TITLE
double dash arguments passing deprecated

### ISSUE THREAD

**Issue by moki** [lerna/lerna#2349]

**Comment by brianjquinn** [comment]
@moki once again you reference test cases for the `version` command. The referenced issue is with respect to `lerna run` and `lerna exec`

**Comment by moki** [comment]
> @moki once again you reference commits/test cases for the `version` command. The referenced issue (#2348) is with respect to `lerna run` and `lerna exec`

you are wrong, one should "quote" their shell commands inside npm scripts. regarding you case i misread it still my first comment it right and relevant to the original problem, also i believe functionality is shared between commands.
