### ISSUE TITLE
npm vulnerability warning "handlebars"

### ISSUE THREAD

**Issue by aalibaabaa** [lerna/lerna#2350]
Please update your `conventional-changelog-core` dependency as soon as they did their `handlebars` update.

<img width="730" alt="Screenshot 2019-11-18 at 10 53 05" src="https://user-images.githubusercontent.com/1275328/69042619-cda2fa80-09f1-11ea-8fe1-13e0b40cdbe5.png">

**Comment by evocateur** [comment]
Run the `npm update` command suggested by `npm audit` and your problems are solved.

`conventional-changelog-core@^3` has the exact same dependency on `conventional-changelog-writer@^4` as `conventional-changelog-core@latest`, which ultimately has the same exact dependency on `handlebars@^4`.
