### ISSUE TITLE
Lerna bootstrap does not link local dependencies

### ISSUE THREAD

**Issue by matsev** [lerna/lerna#2352]
I have configured two modules in a mono repo to use lerna with a local dependency. I expected that

```bash
$ lerna bootstrap
$ lerna run test
```

would be sufficient to download all external dependencies, link a local dependency and execute and pass all tests in all modules.

## Expected Behavior
As per the [lerna bootstrap](https://github.com/lerna/lerna/tree/master/commands/bootstrap#usage) documentation:

> 2. Symlink together all Lerna packages that are dependencies of each other.

Thus, I expected that `lerna bootstrap` would create a symlink in `module-b/node_modules` below that points to `module-a` (which then would allow the tests to be executed and pass).

## Current Behavior

No linking occurs, which cause the tests to fail:

> lerna ERR! yarn run test exited 1 in 'module-b'
> lerna ERR! yarn run test stdout:
> yarn run v1.19.1
> $ jest
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> lerna ERR! yarn run test stderr:
> FAIL ./import.test.js
>   ● Test suite failed to run
> 
>     Cannot find module 'module-a' from 'import.test.js'
> 
>     > 1 | const moduleA = require('module-a');
>         | ^
>       2 | 
>       3 | test('should import module-a', () => {
>       4 |   moduleA();
> 
>       at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
>       at Object.<anonymous> (import.test.js:1:1)
> 

## Steps to Reproduce
1. Create the folder structure below
2. Copy the files inlined to their corresponding directory
3. Execute `$ lerna bootstrap` followed by `$ lerna run test`

```
project-root
   + packages
   |       + module-a
   |       |      + package.json
   |       |      + index.js
   |       |
   |       + module-b
   |       |      + package.json
   |       |      + import.test.js
   |
   +  lerna.json     
```

<details><summary>packages/module-a/package.json</summary><p>

```json
{
  "name": "module-a",
  "version": "1.0.0",
  "private": true,
  "main": "index.js",
  "scripts": {
    "test": "echo \"Test passed in module-a\""
  }
}
```
</p></details>
<details><summary>packages/module-a/index.js</summary><p>

```javascript
module.exports = () => console.log('Log in module-a');
```
</p></details>

<details><summary>packages/module-b/package.json</summary><p>

```json
{
  "name": "module-b",
  "version": "1.0.0",
  "private": true,
  "main": "index.js",
  "scripts": {
    "test": "jest"
  },
  "dependencies": {
    "module-a": "file:../module-a"
  },
  "devDependencies": {
    "jest": "^24.9.0"
  }
}
```
</p></details>
<details><summary>packages/module-b/import.test.js</summary><p>

```javascript
const moduleA = require('module-a');

test('should import module-a', () => {
  moduleA();
});
```
</p></details>

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "yarn",
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```

</p></details>

## Observation

Executing [lerna link --force-local](https://github.com/lerna/lerna/tree/master/commands/link#--force-local) does not change status quo, the test still fails because `module-b/node_modules/` still does not contain a reference to `module-a`.

## Context

I would like to have a build script that executes all tests in all modules as well as having a simple instruction for new project members so that they can be productive in our multi-module project.

I cannot use yarn workspaces because module-b is an Electron app and the electron builder expects its dependencies to be installed in the packages/module-b/node_modules/ folder.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.18.4 |
| `npm --version`  | 6.11.3 |
| `yarn --version` | 1.19.1 |
| `node --version` | v12.12.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Mojave | 10.14.6 |

**Comment by T0astBread** [comment]
I'm experiencing the same issue. Additionally, `bootstrap` removes all entries for the local dependencies from `package-lock.json`

**Comment by MrDevinB** [comment]
I am also experiencing this issue. Even when using `file: ../package-a` to symlink packages together.

**Comment by remipassmoilesel** [comment]
Same issue here !

**Comment by OoDeLally** [comment]
Same here.
Lerna 3.20.2
npm 6.14.4
node 13.12.0

**Comment by aalexgabi** [comment]
Same here:
```
% lerna info
lerna notice cli v3.20.2

 Environment info:

  System:
    OS: Linux 5.5 Manjaro Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 13.7.0 - ~/.fnm/current/bin/node
    Yarn: 1.22.0 - /usr/bin/yarn
    npm: 6.13.6 - ~/.fnm/current/bin/npm
  Utilities:
    Git: 2.25.1 - /usr/bin/git
```

I'm using `file:../lib` with yarn npm client

**Comment by OoDeLally** [comment]
In the end, I am using Yarn Workspaces without Lerna, which seems to achieve the same thing, and the symlinks are correctly created. No point of using Lerna.

**Comment by aalexgabi** [comment]
@OoDeLally I wanted to use that but I ran into problems when trying to deploy into production. I did not find a way to do a `yarn install --production` for a package in such a way that the node_modules folder for that package does not contain any symlink.

**Comment by kylemh** [comment]
@OoDeLally Lerna will still be helpful for managing releases.

What command did you use to bootstrap sibling packages?

**Comment by OoDeLally** [comment]
I followed https://classic.yarnpkg.com/en/docs/workspaces/
So a basic `yarn install` works. It create symlinks at the root's `node_modules`. And all the packages can find these links if they need.

Now with this solution, I am struggling with adding new packages, yarn doesn't let me for some reason, so I'm forced to use `npm install that-package` :trollface: 

I find it hard to believe that such simple features are so buggy.

**Comment by kylemh** [comment]
So I think you're doing things correctly with using `yarn` workspaces by installing at the root.

When you want to add new dependencies, you'll need to use the workspace command to do so: https://classic.yarnpkg.com/en/docs/cli/workspace/

If it's a dependency shared across multiple packages, you'll wanna add it to the root via `yarn add PACKAGE_NAME -W [--dev]` (dev flag is optional

**Comment by OoDeLally** [comment]
@kylemh yarn workspaces seem to be a bit broken too. I was stuck with this issue
https://github.com/yarnpkg/yarn/issues/3973
But found the solution here
https://github.com/yarnpkg/yarn/issues/3973#issuecomment-603655172

**Comment by W0lfw00d** [comment]
For me it suddenly stopped working today (yesterday it works for me and team members).

I was able to resolve it using `lerna link`. 


Don't know why because `Lerna bootstrap` used to do this and if you look at the help it should still do (reverting to a older version did nothing) 🤷

**Comment by samvv** [comment]
Just new to Lerna, and I was scratching my head why it didn't seem to do anything. Note: I am not using `yarn`, just `npm`.

**Comment by xrobert35** [comment]
same here 

```
lerna info     
info cli using local version of lerna
lerna notice cli v3.20.2

 Environment info:

  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Utilities:
    Git: 2.20.1 - /usr/bin/git
  npmPackages:
    lerna: ^3.20.2 => 3.20.2 
```

here is my structure information 
```
- lerna.json
- packages
  - api
      package.json  with dependency  (  "shared" : "../shared" )
  - shared
      package.json ( name : "shared" )
```

here's my lerna.json

```
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.1"
}
```
if I run **npm ci** in the **api** folder the link is correctly created

**Comment by xrobert35** [comment]
Ok in fact, if I directly use the correct version of my "shared" project instead of a local link it work, I get a symlink to my shared projet in my api node_modules, which is the logical way to do this..

- lerna.json
- packages
  - api
      package.json  with dependency  (  "shared" : "1.0.0" )
  - shared
      package.json ( name : "shared", version : "1.0.0" )

**Comment by matsieftw** [comment]
I still haven't found reliable ways to use lerna with sibling dependencies. Is there anywhere that has good workflow documentation since the lerna docs do not really indicate how to properly use the lerna ecosystem?

**Comment by rohit-gohri** [comment]
Some clarity on this in the docs would be appreciated. The docs make it seem like "magic" but then it's very difficult to know what is being done by `bootstrap` or `link`.

It would be great if it outputs what all packages were linked, or what local packages were not linked because of a version mismatch.

With loglevel debug, current output of `lerna link` is like:

```
lerna sill actions finished test-example
lerna sill actions finished @scope/deploy
lerna sill actions finished @scope/test
lerna sill actions finished @scope/template
```

I'm using `@scope/test` in `test-example` with `file:../test` in package.json. I don't know if it is working because of the `file` or because of `lerna link`.

**Comment by Domiii** [comment]
I also thought that `lerna bootstrap --force-local` takes care of everything (at least it promises that in the docs), however some local packages are linked, but most are not. I don't know what the pattern is either.

Luckily, this workaround at least added the local links (however, it did not link all hoisted `dependencies`, only some; again, seemingly at random):

`lerna bootstrap --force-local && lerna link --force-local`

**Comment by ericprud** [comment]
Tweaking @NiGhTTraX's [skeleton example](https://github.com/NiGhTTraX/ts-monorepo), I can confirm that changing [a dependency](https://github.com/NiGhTTraX/ts-monorepo/blob/npm/packages/bar/package.json#L17) from `"^1.0.0"` to `"file:../foo"` prevents bootstrap from creating the node_modules symlink iff it's not in the root package.json. Specifically, `utils/symlink-dependencies/symlink-dependencies.js` skips symlink creation [if (resolved.type === "directory")](https://github.com/lerna/lerna/blob/main/utils/symlink-dependencies/symlink-dependencies.js#L38).

I can confirm two workarounds for this issue:

1. use the versioned dependency (which needs updating every time you change a major number).
2. add devDependencies in the root package.json: ```"@nighttrax/foo": "file:packages/foo"``` (works for anything robust enough to crawl up the directory hierarchy looking for package.jsons; worked for typescript).

Disabling that if made the symlink appear as expected; if someone teaches me how to run tests, and they miraculously all pass, I can create a PR. Blame suggests that this code has exists since a 2018 commit ["Convert command lifecycle from callbacks to Promises"](https://github.com/lerna/lerna/commit/377d45a5#diff-9741353a17de52884a10ffc66d0fb9311e02ff74056339c5b7cfedb2a7bc4788R41).

**Comment by Strate** [comment]
Looks like lerna do not link package if package's "version" field is empty or not satisfy pattern "a.b.c"

**Comment by porkus1990** [comment]
Still facing this "issue". 
We have a prepare hook (which runs the build) and it fails for lerna bootstrap. With running  lerna link --force-local before lerna bootstrap --force-local or after it.

Anything new on this problem/issue?

**Comment by Kartik2016** [comment]
Facing the same issue with Lerna 4.0.0. Build runs fine on github workspaces when using windows 2016 server. However build fails when running on Ubuntu 20.0 LTS. Error thrown: Cannot find module 'pack.a'
One observations: The package json for 'pack.a' has the name field set to "pack.a", however the directory containing it is named packrepo.a
Using npm, node v12
Any solutions, suggestions?

**Comment by Jameskmonger** [comment]
I can confirm that @ericprud 's suggestion of adding all shared local packages as `devDependencies` (with `file:` paths) into the root `package.json` works

**Comment by stefan-toubia** [comment]
The issue with using `file:`, at least with yarn, is that it's highly inefficient and slows everything down due to the fact that all files are copied into node_modules as well as yarn cache. Everytime you install something, a new hash for those local deps are created and a new entry is added to yarn cache. Yarn cache balloons very quickly.

**Comment by ericprud** [comment]
That's a bummer; I'd hoped for an easy way to make these intra-mono-repo refs less brittle.

Both yarm and npm now have support for workspaces; can we let them take care of the links (hopefully efficiently) and let lerna take care of rev'ing and publishing changed packages?

**Comment by JabbyPanda** [comment]
Started to face this issue when running `lerna bootstrap` on Linux machine as well after altering `package.json` 

Running `lerna link` explicitly *before* `lerna bootstrap`  had helped us to workaround the issue with Lerna _bootstrap_ command not recognizing local symlinked packages

**Comment by jpSimkins** [comment]
I also wanted to make note, this seems to happen to me on new packages only. 
Once I push the package to NPM, then the local link works as expected. 

By running `lerna link` before the bootstrap, this works for new packages.

**Comment by iSuslov** [comment]
Same issue here. Will we please get any comments from @evocateur or what?

**Comment by froyo-naux** [comment]
if you use babel or any parser, may be you need build first before test.

**Comment by ChristianTucker** [comment]
I've tried every fix here, nothing has worked. What is even the point of using lerna if the main attraction doesn't work.

**Comment by MrParkerZ7** [comment]
I have resolve this issue differently by using `yarn lerna run tsc` to generate all packages lib source.

because when you are building your node it will compile all relates source into node_modules from git or registry
also for your source lerna local, it not gonna take your source from src directly, because it only take compiled source from node_modules and lib or dist from your local project

hope it might help some 

root module
![image](https://user-images.githubusercontent.com/12726028/169688671-bdd972f7-0ab0-4096-9a4c-49db49ea6f43.png)


child modules 
![image](https://user-images.githubusercontent.com/12726028/169688629-59bf52ea-341d-4683-87a7-21a7e81cdc9e.png)

**Comment by Jameskmonger** [comment]
I solved all of my issues by migrating my project to use "Yarn Workspaces" natively, and ditching Lerna ☹️

(my project is a TypeScript/Node/React monorepo, I will be publishing some of the internal packages at some point)

It's a shame, as I liked the Lerna toolset for the version bumping etc, but it was too much work with too many esoteric solutions to get it up and running properly. Yarn Workspaces worked pretty much out-of-the-box

**Comment by ifedu** [comment]
Using `lerna exec npm install` we can use `npm install` in each package, so this workaround works for me to be able to use `npm install` and install all the dependencies without problems:
```json
{
  --
  "scripts": {
    "postinstall": "lerna bootstrap && lerna exec npm install"
  },
  "dependencies": {
    "lerna": "^4.0.0"
  }
}
```

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
