### ISSUE TITLE
Linked sub-package can't resolve peerDependency

### ISSUE THREAD

**Issue by matewka** [lerna/lerna#2354]
I have a lerna project which has the following (simplified) structure:

- lerna-project
  - packages
    - my-ui-lib
       peerDependencies:
       - styled-components
    - my-client-app
       dependencies:
       - my-ui-lib
       - styled-components

## Expected Behavior

When I bootstrap the project, I would like to have styled-components package and my-ui-lib in the same node_modules folder so my-ui-lib can rely on them.

## Current Behavior

my-ui-lib is included in the root node_modules, while styled-components are included in the my-client-app's node_modules.

Therefore, I get an error:

`Module not found: Error: Can't resolve 'styled-components' in ...`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by thiagog3** [comment]
Hey @matewka! Did you found any solution for this?

**Comment by matewka** [comment]
Hi @thiagog3 ,
The problem was related to multiple versions of styled-components package.
To avoid it, you should make sure that you end up with the same version across all packages.
Only then, the dependency will be saved in the root node_modules
