### ISSUE TITLE
`lerna bootstrap` skipping packages it expects to have been installed in root already (`--production`)

### ISSUE THREAD

**Issue by felixhayashi** [lerna/lerna#2356]
Lerna falsly assumes root packages to be present when building non-root packages. 

Say a package is listed both in `devDependencies` in the "root" package and also as `dependencies` in a non-root package (let's call it "my-sub-package"). And let's assume one did not install (and hoist) any dependencies of any package in the repo yet so the "root" `node_modules` folder does not exist yet, neither exists any sub-package `node_modules` folder. 

Now one executes:

```
npm run lerna -- bootstrap --loglevel silly  --hoist --scope "my-sub-package" -- -- --production
```

then the following is expected:

## Expected Behavior

lerna installs all packages registered as dependencies in "my-sub-package" and hoists them to the "root" `node_modules`.

## Current Behavior

lerna skips installing dependencies that are registered as `dependencies` or `devDependencies` in the root package.

So say I have a package `common-tags` registered in a sub-package as well as in `devDependencies` in the root package then I will get the following output:

```
hasDependencyInstalled root common-tags
```

However, as mentioned before, the package (e.g. `common-tags`) has never been installed before and thus it will be missing in the `node_modules` folder and hence break the build during runtime.

## Possible Solution

* Option a) Lerna respects the `--production` flag and distinguishes between `dependencies` and `devDependencies` when checking for `hasDependencyInstalled`.
* Option b) Lerna allows us to explicitly exclude the root package from any checks via `--ignore "root"`.

## Steps to Reproduce (for bugs)

1. install lerna globally with e.g. `npm i -g lerna`
1. Create a root package json with e.g. `common-tags` registered as `devDependencies`
2. Create a subpackage named "my-sub-package" with  `common-tags` package registered as `dependencies`
3. execute `npm run lerna -- bootstrap --loglevel silly --hoist --scope "my-sub-package" -- --production`
4. see that the `common-tags` package is missing in the `node_modules` folder,

## Context

This affects the automatic building of monorepo package dependencies.

## Your Environment

lerna v3.18.5

**Comment by evocateur** [comment]
Yep, that looks like a bug.

I wouldn't recommend using `lerna bootstrap` when package managers do well with this sort of thing nowadays (Yarn workspaces, [pnpm workspaces](https://pnpm.js.org/en/workspaces), and soon npm v7 workspaces)

**Comment by indexzero** [comment]
Yet those same package managers say that they don't do what `lerna` does (see: [`yarn` docs on `lerna`](https://classic.yarnpkg.com/en/docs/workspaces/#toc-how-does-it-compare-to-lerna), which is contradictory.

If workspaces are a "low level primitive" wouldn't _someone_ (`lerna` or otherwise) be responsible for implementing the more complex logic on top of them? 

Regardless to that – would a PR that fixes this issue be accepted?

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
