### ISSUE TITLE
reopen bootstrap removes node_modules from root (during hoist)

### ISSUE THREAD

**Issue by felixhayashi** [lerna/lerna#2361]
Hi, this is a vote to repopen https://github.com/lerna/lerna/issues/889#issue-237423886 which was closed due to inactivity.

---

> Can you provide an example repo? I'm a bit mystified by the context of this error.
> (https://github.com/lerna/lerna/issues/889#issuecomment-312334120)

Say we have a lerna repo which contains of two packages "p1" and "p2":

```
{
  "name": "p1",
  "dependencies": {
    "lodash": "latest"
  }
}
```

and

```
{
  "name": "p2",
  "dependencies": {
    "underscore": "latest"
  }
}
```

and now one executes:

```
lerna bootstrap --hoist --include-dependencies --scope p1
```

...then `lodash` is hoisted to the root's `node_modules`,

Now one executes:

```
lerna bootstrap --hoist --include-dependencies --scope p2
```

...then `lodash` disappears from the root's `node_modules` and instead `underscore` is hoisted.

It would be great if this could be controlled via a flag, e.g. `--keep-existing-node-modules`.

It is often desired to keep already existing node_modules in the root when working on several projects
at the same time and it is annoying if one project removes the deps of another project.

**Comment by endreymarcell** [comment]
I just bumped into this - bootstrapping with hoisting enabled seems to clear the root `node_modules` entirely. This is absolutely undesirable behavior in our case. We store a number of packages in the root `node_modules` that are used to manage the monorepo itself - including Lerna. This means that after bootstrapping with hoist, we can't even execute another bootstrap without running `npm install` in the root... Or am I missing something?

@evocateur can you please share what your take is on this issue?

**Comment by felixhayashi** [comment]
> This means that after bootstrapping with hoist, we can't even execute another bootstrap without running npm install in the root... Or am I missing something?

yup, this is exactly our experience – after bootstrapping with hoist we lose access to lerna and have to reinstall it (or rely on npx or a globally installed lerna to execute lerna commands, which is of course undesired as we cannot pin down the lerna versions for different projects anymore).

**Comment by khawajaumarfarooq** [comment]
I am also hitting this issue and it is puzzling me why the existing node_modules in the root would be obliterated by hoisting. Seems rather pointless behaviour.

**Comment by endreymarcell** [comment]
My guess is that this helps avoid version incompatibility problems by always starting with a clean slate. Then again, hoisting is simply unusable for us this way.

**Comment by evocateur** [comment]
`lerna bootstrap --hoist` is a brilliant, complicated hack that was _necessary_ when it was written (almost) four years ago. It is now no longer necessary because package managers have either implemented workspaces or plan to in near future (with acceptable workarounds in the meantime). You should use these alternatives instead of `lerna bootstrap`:

* Yarn [workspaces](https://classic.yarnpkg.com/en/docs/workspaces/)
* pnpm [workspaces](https://pnpm.js.org/en/workspaces)
* npm with relative `file:` specifiers
   * `npx lerna link convert` will [set this up](https://github.com/lerna/lerna/commit/f59bf3cff4524e7d7fb9b6a154b32c3043242b7e), this is how Lerna's own monorepo works
   * npm [workspaces](https://github.com/npm/rfcs/pull/103) coming soon

**Comment by endreymarcell** [comment]
Thanks for the answer.
Our monorepo hosts multiple independent frontend components in separate packages (but with shared dependencies). So our main use case is bootstrapping some packages, but not all of them. My understanding is that if we were to switch to yarn or pnpm workspaces, we could only bootstrap the entire monorepo all at once, which is something we want to avoid. But do correct me if I'm wrong.
Also, for dependencies within the monorepo, we need to be able to tell what version of another package our package depends on. We lose that information with relative file `file:` specifiers.
