### ISSUE TITLE
Workflow for test-publishing to a local registry, e.g. Verdaccio

### ISSUE THREAD

**Issue by AlanSl** [lerna/lerna#2363]
As discussed on https://github.com/lerna/lerna/issues/805 there's no Lerna "unpublish" command or general support for overwriting an existing published version because `lerna publish` is intended for best-practice publication to a public registry like NPM.

I'm wondering what would be a good approach for test-publishing to a local registry, such as  Verdaccio running on `http://localhost:4873`, where you might want to repeatedly publish locally to the same version number, until the published version works as intended and you are ready to publish a real new version to the public repository.

Is there an intended approach for this? There are lots of good pointers on using things like `from-git` and `from-package` with CI but I can't see anything clean for this case.

**Comment by AlanSl** [comment]
Currently I'm experimenting with something like this, which seems to work reasonably well for my case (several prepublish and postpublish scripts, plus a `create-*` package intended to be used from the registry with `npm init` or `yarn create`). I've also seen similar scripts to my `local-unpublish-all` in the wild:

```
{
  ...
  "scripts": {
    "local-publish": "lerna publish --no-git-tag-version --no-push --registry=\"http://localhost:4873/\"",
    "local-unpublish": "lerna exec -- npm unpublish --registry=\"http://localhost:4873/\" \"\\${LERNA_PACKAGE_NAME}@\\$(npm view \\$LERNA_PACKAGE_NAME version)\"",
    "local-unpublish-all": "lerna exec -- npm unpublish -f --registry=\"http://localhost:4873/\" \"\\${LERNA_PACKAGE_NAME}\"",
    ...
  },
  ...
}
```

...where the usual workflow to test that everything in a branch works correctly when published and pulled from a registry is:

 - `npm run local-unpublish`, unless there's nothing on the local registry (e.g. if this is the first time this has been done or `local-unpublish-all` has been done to start again after something went wrong)
 - `npm run local-publish`, optionally passing a version number if all packages are intended to be locally published to the same version, e.g. `npm run local-publish 0.0.1`
 - Test that everything works and is bundled as expected when pulled from the registry; repeat if it doesn't.

Is there anything existing or in the roadmap that fits this kind of local testing better than the above?

**Comment by akrawchyk** [comment]
@AlanSl I have a CI workflow setup using Verdaccio to provide this in test environments. 

I also use [`npmrc`](https://github.com/deoxxa/npmrc) locally to switch between different configs as I make changes to package source code. There's definitely some amount of danger here because it's easy to forget what profile you have loaded, it's a good idea to output the current one in your prompt. I don't have a good workflow for unpublishing though, I generally just publish with `--canary --dist-tag next` so I can keep using `example-package: 'next'` while continuing to republish the same package.

Here's an example Gitlab CI config for reference too:

```
default:
  image: node:10
  services:
    - verdaccio/verdaccio:4
  before_script:
    - npm install -g npm@latest
    - npm set registry $CI_NPM_REGISTRY
    - npm ci
    - npx lerna bootstrap --ci

variables:
  CI_NPM_REGISTRY: http://0.0.0.0:4873

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npx npm-auth-to-token@1.0.0 -u user -p password -e user@example.com -r $CI_NPM_REGISTRY
    - >
      npx lerna publish from-package
      --yes
      --force-publish
      --registry $CI_NPM_REGISTRY
      --exact
      --no-commit-hooks
      --no-git-tag-version
      --no-push
      --dist-tag next
    - npx lerna run test
```

**Comment by gaurav5430** [comment]
@AlanSl 
I like the idea of repeatedly publishing the same version in a private/local registry before it is ready to be published as a stable version 

Did you figure out if lerna publish can help with this ?

Currently i use npm publish to publish beta versions on a private registry and then unpublish the version once i am ready to publish the final version, but I am not sure if there is a way to keep publishing to the same beta version through lerna or npm

**Comment by evertonfraga** [comment]
`lerna publish` was meant to do a lot. And that's OK. Personally, I think it's an unnecessary risk having to add several tags to suppress "production" behaviors (I could end up publishing git tags to remote unknowingly).

I'd rather play on the safe side, using `lerna exec "npm publish …"` 

It executes commands in a bottom-up way, so leaf packages are executed first, which is perfect for my use case. A few more shell script tricks and you can have a generic solution for that.

@gaurav5430 so you can simply run: 

```
# publish
lerna exec "npm publish --registry http://localhost:4873"

# unpublish
lerna exec "npm unpublish \$LERNA_PACKAGE_NAME --registry http://localhost:4873"
```

**Comment by qfox** [comment]
Unfortunately, we wrote a lot of scripts around lerna commands but ideas can be useful if we decide to implement them to lerna.

We using something like lerna changed to calculate changes, then store it in artefact, then in other task we reuse it to run something like lerna vesion and bootstrap only affected packaged to run pack in each, then we store ready to publish packages in artefact, and then, in the last task, reuse ready packages to publish to Verdaccio (ye, we use it too).
The last one needed to precheck packages building and separate publish process from pushing commits to VCS.

Another idea was to publish packages in draft mode (or start transaction) in Verdaccio and then (if VCS accepted our version changes) just commit them, or revert if VCS failed.

Prob these would be helpful. I hope so ;-)
