### ISSUE TITLE
What config options are valid in lerna.json?

### ISSUE THREAD

**Issue by arkhamRejek** [lerna/lerna#2365]
In https://github.com/lerna/lerna/pull/844 i see that it states that All CLI options should be configurable so i'm not sure wether or not i'm doing this incorrectly or it's working as intended. 

## Expected Behavior
All flags configured in the lerna.json to be applied when the command is run.

## Current Behavior
It's inconsistent, some flags are picked up from the config some are ignored. If i add the flags on the CLI via --some-flag it works fine

## Possible Solution
I love this repo, used it for years but never really needed to configure lerna.json, i'd love to work on the docs and update them for the config section if someone could point me in the right direction. I'm not sure if the lerna.json is doing that purposely

## Steps to Reproduce (for bugs)
1. configure lerna.json with the changed command and set conventional-commits to true
2. run lerna changed at the root of your project

<details><summary>lerna.json</summary><p>

```json
{
    "packages": [
        "schema/*",
        "salesforce/*",
        "api/*"
    ],
    "npmClient": "yarn",
    "useWorkspaces": true,
    "version": "independent",
    "command": {
        "publish": {
            "verifyAccess": false,
            "registry": "https://test.jfrog.io/test/api/devnpm"
        },
        "version": {
            "allowBranch": ["dev"],
            "exact": true,
            "conventionalCommits": true,
            "message": "chore(release): JIRA-000000 new version",
            "include-merged-tags": true,
            "no-push": true
        },
        "changed":{
            "conventional-commits": true,
            "include-merged-tags": true
        }
    },
    "ignoreChanges": [
        "**/__tests__/**",
        "**/test/**",
        "**/*.md",
        "**circleci**"
    ]
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.18.1 |
| `npm --version`  | 6.11.3 |
| `yarn --version` | 1.19.1 |
| `node --version` | 12.12.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.14 |

**Comment by gaurav5430** [comment]
Any updates on this? 
having a hard time figuring out what options can be configured in lerna.json. Does it have a one to one mapping between the commands and the corresponding keys in lerna.json?

or is there a convention like all flags need to converted to camelCase when mentioned in lerna.json?

are some flags not configurable from lerna.json ?

How do you specify something like this in lerna.json: `lerna version --conventional-commits --conventional-graduate`
