### ISSUE TITLE
lerna includes devDependencies in change detection

### ISSUE THREAD

**Issue by Torsten85** [lerna/lerna#2368]
Hello,

I have two packages in my lerna mono repo:

`Package A` works standalone
`Package B` has a peerDependency to `A@*` (version doesn't matter atm) and a devDependency to `A@file:../A`

making changes in `A`, commit and executing `lerna version from-git` always tags a new version for package `B` because of the devDependency (there are no changes in B!). So I constantly push new version without any changes.

Is there a way around this?

it seems that default is to include "devDependencies" (https://github.com/lerna/lerna/blob/master/core/package-graph/index.js#L19) and there seems to be no way to add options (https://github.com/lerna/lerna/blob/master/core/command/index.js#L264)

Thanks

**Comment by alfonsomunozpomer** [comment]
I’m experiencing this issue as well. The `publish` command admiths the flag `--graph-type dependencies` (which is the default), which would seem to indicate that a change in `devDependencies` wouldn’t result in a new package, which seems to be in conflict with the behaviour of `version` as described above.

**Comment by alfonsomunozpomer** [comment]
This seems to be a duplicate of https://github.com/lerna/lerna/issues/1898.
