### ISSUE TITLE
Fixed mode doesn't always publish vesrions?

### ISSUE THREAD

**Issue by ianstormtaylor** [lerna/lerna#2369]
I'm sort of confused. I've been using the `independent` mode for [Slate](https://github.com/ianstormtaylor/slate) forever, which allows packages to change versions independently of each other.

I'd like to change to the `fixed` mode to make it easier for people to see which ones are compatible. But... it sounds like it only ever publishes versions when code changes inside a package still?

For example, if I had two packages:

```
a: 1.0.0
b: 1.0.0
```

`b` depends on `a`.

If I make a breaking change to `b` that happens to not require any changes to `a`, then when I went to publish (and select `major` because it contains a breaking change) I'd end up with:

```
a: 1.0.0
b: 2.0.0
```

Since `a` didn't have any source code changes. Is that right?

But now users can't just line up the versions anymore? What's the purpose of `fixed` mode if it doesn't actually ensure that there are always matching versions of each package?

**Comment by evocateur** [comment]
"Independent" mode has never been about _which_ packages are published, only the freedom to choose differing versions per-package. The default "fixed" (or "universal") mode merely constrains the "independently" chosen versions to one choice, applied to all changed packages since the last release.

Major version bumps in "fixed" versioning mode are a special case: _all_ packages in the monorepo are bumped to the new major. Any other semver "lesser than" major still only versions packages that have changed (or have local dependencies that have changed) since the last release. This is because Lerna defaults to using `^` as the range specifier, which makes this "just work" for consumers.

**Comment by ianstormtaylor** [comment]
@evocateur thanks for the explanation!

Is there a way to keep the packages **minor**-consistent or **patch**-consistent with Lerna?

It feels like something that either should be configurable, or have a better default of **patch** being allowed to diverge but **major** and **minor** not. Because just looking at a few of the most-popular examples:

- `react` ensures that their packages (`react`, `react-dom`, `react-is`, etc.) are always exactly equivalent to the **patch** level. This makes it super easy to upgrade all of the inter-dependent ones when you need to in a `package.json`.

- `react-router` doesn't go quite as far (although maybe they would if was easier), and they ensure that their packages (`react-router`, `react-router-dom`, `react-router-native`, etc.) are always equivalent to the **minor** level.

The current default of **major** seems too loose.

And how does it handle pre-`1.0.0` packages? Does it know that people tend to think of `0.6 -> 0.7` as being major changes and factor that in? (A **minor** default would side step this issue. And a configurable option would allow the maintainer to handle it.)

**Comment by denieler** [comment]
I agree, it would be amazing to have in Lerna. This thing is blocking us to release properly a CLI tool (as monorepo), where we have one single main package and multiple supportive packages, which meant also to be released. This fact also forcing to look for alternatives to Lerna 😞

**Comment by ianstormtaylor** [comment]
FWIW, I’ve been using Changesets instead of Lerna now for publishing and it’s been pretty nice—bit more work to configure at first. (And with Yarn supporting workspaces you can get rid of Lerna entirely I believe.)
