### ISSUE TITLE
lerna version not using latest releaase

### ISSUE THREAD

**Issue by pladaria** [lerna/lerna#2370]
`lerna version` not using latest release tag

```
$ yarn lerna version
yarn run v1.19.0
$ /home/pladaria/bra/webapp/node_modules/.bin/lerna version
lerna notice cli v3.19.0
lerna info versioning independent
lerna info Looking for changed packages since webapp-k8s-245.0.0
```
But my latest tag is:
```
$ git describe --tags --abbrev=0
webapp-k8s-696.0.0
```

`webapp-k8s-245.0.0` is a very old release tag

## Expected Behavior

`lerna version` should use latest tag

## Current Behavior

Not using latest release tag for versioning

## Possible Solution

1. use a different git command, for example: `git describe --tags --abbrev=0` (instead of `--first-parent`)
2. allow passing a tag as command option: `lerna version tag=my-tag`

## Steps to Reproduce (for bugs)

I guess this could be reproduced picking an old branch, merge master and use that branch to work

## Context

I'm unable to use lerna for this reason

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.19.0 |
| `npm --version`  | 6.12.1 |
| `yarn --version` | 1.19.0 |
| `node --version` | v12.13.1 |

| OS | Version |
| ---: | :--- |
| Linux Mint | 19 Tara |

```
$ cat lerna.json 
{
    "npmClient": "yarn",
    "useWorkspaces": true,
    "version": "independent"
}
```

**Comment by chunkhang** [comment]
You might need to do `lerna version --include-merged-tags`.

**Comment by evocateur** [comment]
Your release tags need to be annotated for lerna to see them (it never passes `--tags` to `git describe`). "Lightweight" tags do not suffice. Quoting from the [`git tag` docs](https://git-scm.com/docs/git-tag#_description):

> Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels. For this reason, some git commands for naming objects (like `git describe`) will ignore lightweight tags by default.

I don't know how your tags are being created (they're not formatted in any recognizable pattern that Lerna itself generates), so that's my best guess. (`--include-merged-tags` doesn't enable lightweight tags, it only omits `--first-parent`)

**Comment by pladaria** [comment]
@chunkhang using `lerna version --include-merged-tags` I get an even older changeset

@evocateur, thanks for the tip, we will review our CI pipeline to make sure we use annotated tags, will come back with the results
