### ISSUE TITLE
Generate changelog during publish and be able to select package's version

### ISSUE THREAD

**Issue by lffg** [lerna/lerna#2374]
How can I get that select version prompt with the conventional commit option turned on?

I am talking about this prompt:

![image](https://user-images.githubusercontent.com/23662020/70381433-c86a0900-1928-11ea-9c88-8cd0f7e9c809.png)

But when I set the `conventionalCommits` to `true` in my `lerna.json` file, that prompt does not appear anymore.

My `lerna.json`:

```json
{
  "useWorkspaces": true,
  "npmClient": "yarn",
  "version": "independent",
  "packages": ["packages/*"],
  "registry": "https://registry.npmjs.org/",
  "loglevel": "success",
  "command": {
    "publish": {
      "message": "chore: Publish",
      "conventionalCommits": true
    }
  },
  "ignoreChanges": ["**/CHANGELOG.md"]
}
```

So, how I can generate changelogs during the `publish` **and** be able to choose each package's  version?

Thanks,

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | `3.19.0` |
| `npm --version`  | `6.11.3` |
| `yarn --version` | `1.19.1` |
| `node --version` | `12.x` |

**Comment by kylemh** [comment]
That's the point of using conventional commits. It automates the versioning decision for you.

If you'd like to use conventional commits locally, but create your own changelogs you can do so via the CLI: https://github.com/conventional-changelog/conventional-changelog

In that situation, you'd remove `conventionalCommits` from your `lerna.json`, publish, and then generate a changelog after the fact.
