### ISSUE TITLE
Results of `lerna diff` and `lerna changed` are inconsistent 

### ISSUE THREAD

**Issue by taozi0818** [lerna/lerna#2378]
My packages are as follows: 
```
$ lerna list --graph

{
  "taoz1_itest1": [],
  "taoz1_itest2": [
    "taoz1_itest1"
  ]
}
```
I updated something in package `taoz1_itest1` , but no codes changed  in package `taoz1_itest2` 
 and  committed the codes.

Then run `lerna changed`:
![image](https://user-images.githubusercontent.com/18347146/70704380-da72ef80-1d0c-11ea-90b9-c87b67060bd3.png)

then run `lerna diff taoz1_itest2`, but get no difference.

Why `lerna diff` and `lerna changed` get different results after the same commit? Lerna should display the changes for all packages which includes no code updated but will be upgraded

**Version:** 
lerna: 3.19.0
NodeJS: 10.15.1
npm: 6.4.1
MacOS: 10.14.2

**Comment by thesocialdev** [comment]
+1

**Comment by matheusggds** [comment]
+1

**Comment by xiaozhi93** [comment]
+1

**Comment by rocklee889** [comment]
+1

**Comment by tylerkilburn** [comment]
+1

**Comment by taozi0818** [comment]
@tylerkilburn  According to the code and  README of these commands, `diff` just equals `git diff` and `changed` means packages which will be upgrade.

[`diff` README](https://github.com/lerna/lerna/tree/main/libs/commands/diff#readme)
[`changed` README](https://github.com/lerna/lerna/tree/main/libs/commands/changed#readme)

If you want to get  packages which should be upgrade include dependencies after creating a new commit, you should use `lerna changed`. 

Closed.
