### ISSUE TITLE
lerna run swallows errors

### ISSUE THREAD

**Issue by giladgray** [lerna/lerna#238]
this is similar to #119 but larger: the issue seems to include other commands as well.

`lerna run task` only gives me the exit code and swallows all logging the task may have given, which usually includes the compiler error message.

here's the output from `lerna tun ts`:

```
Lerna v2.0.0-beta.13
Independent Versioning Mode
Errored while running npm script 'ts' in '@elements/blueprint'
Error: Command failed: /bin/sh -c npm run ts

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "run" "ts"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! @elements/blueprint@2.29.0 ts: `tsc --project .`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @elements/blueprint@2.29.0 ts script 'tsc --project .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @elements/blueprint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc --project .
npm ERR! You can get their info via:
npm ERR!     npm owner ls @elements/blueprint
npm ERR! There is likely additional logging output above.
```

and here's the output from running the first lerna task directly in its project directory:

```
> @elements/blueprint@2.29.0 ts /Users/ggray/palantir/blueprint/packages/blueprint
> tsc --project .

error TS6053: File 'src/generated/iconClasses.ts' not found.
error TS6053: File 'src/generated/iconStrings.ts' not found.

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "run" "ts"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! @elements/blueprint@2.29.0 ts: `tsc --project .`
npm ERR! Exit status 2
```

i've noticed other similar discrepancies between the logging during a `lerna run *` versus during a direct `npm run *` in the project, where lerna gives much less information. perhaps there's an extended buffer on the logger?

**Comment by hzoo** [comment]
I see you are using beta.13, does updating help? (I know there are still some issues with logging)

**Comment by gigabo** [comment]
Looks like it actually just [swallows everything from `stdout`](https://github.com/lerna/lerna/blob/master/src/commands/RunCommand.js#L57-L61) on error.

**Comment by giladgray** [comment]
@gigabo seems to have hit it. updating does not help.

**Comment by thejameskyle** [comment]
So you just want stdout to be output at all times?

**Comment by rygine** [comment]
i'm also running into this when linting all packages
