### ISSUE TITLE
Copy local package files to node_modules instead create symlink

### ISSUE THREAD

**Issue by Soufraz** [lerna/lerna#2381]
I am using lerna with a few apis and those apis are sharing one package that I am developing locally. I am using docker container for each package inside packages folder in lerna. When I up docker-compose the shareable package that I am developing and using locally goes to node_modules with a symlink .../../../ and I'd like to have all files of this package inside node_modules. 

## Expected Behavior
When bootstrap would be nice a param to copy real files instead create symlink.

## Current Behavior
Only a symlink is created and when project files goes to container the symlink is unuseful.

## Possible Solution
A param --no-symlink or --copy-package-files (something like that) would be nice.

Is that a viable solution or the package does not fits with this?

**Comment by dyaa** [comment]
I have the same issue & I would really like to see lerna supporting this param

**Comment by shenky1** [comment]
Same issue, please implement

**Comment by mischkl** [comment]
This is really important for publishing node application images, where the symlinks will be broken as soon as the application is packaged up.

**Comment by lmcarreiro** [comment]
It is a common problem. I do not know a solution.

https://stackoverflow.com/questions/56294568/should-a-developer-be-able-to-create-a-docker-artifact-from-a-lerna-monorepo-in

https://stackoverflow.com/questions/59320343/how-to-build-docker-images-in-a-lerna-monorepo-without-publishing

https://stackoverflow.com/questions/61189279/how-to-develop-build-javascript-monorepo-project-like-visual-studio-projects

https://github.com/lerna/lerna/issues/2158

https://github.com/lerna/lerna/issues/2381

**Comment by adamgajzlerowicz** [comment]
Is it a matter of performing copy instead of symlink? Probably this won't be possible if installing with hoist?
Is there an issue anyone is working on? Should we start working on this?

**Comment by marcoantoni0** [comment]
I also came across the same issue today.

Is there any intention of implementation?

**Comment by tristangodfrey** [comment]
I would also like to see this feature, currently using a horrible workaround to avoid the docker symlink issue (running a local npm registry on docker build). Would happily dive into the code and create a PR if maintainers agree it would be useful (perhaps i'm missing a very obvious alternative approach?)

**Comment by jeremyhamm** [comment]
Also having this issue, would really appreciate this addressed

**Comment by adamgajzlerowicz** [comment]
As a workaround, I skipped the Lerna packager.

* Removed local dependencies from package.json
* Added custom `bootstrap` scripts - one for development and one for production/ci/dockerized build
* development version creates symlinks to the `src` dir giving me the instant compilation updates when something changes in the common
* production/ci/docker build uses `copy` to the src dir, so the packager has also access to those files

Not perfect, but when scripted right, the switch happened fully transparent

**Comment by tristangodfrey** [comment]
Quick update for people who are still stuck on this; you can combine lerna with nx (https://github.com/nrwl/nx), nx allows you to "render" each package into its own directory with dependencies referenced locally (regardless of how many libraries you might be linking in)

**Comment by adamgajzlerowicz** [comment]
> Quick update for people who are still stuck on this; you can combine lerna with nx (https://github.com/nrwl/nx), nx allows you to "render" each package into its own directory with dependencies referenced locally (regardless of how many libraries you might be linking in)

Interesting. Is it possible to use NX without hoisting? So for example, if I have one package in react 14 and the other one with react 17, will they still work together in one repo?

**Comment by tristangodfrey** [comment]
@adamgajzlerowicz afaik you still need lerna to manage multiple versions of the same package, but being quite new to NX I could be wrong, will update once I get there :)

**Comment by anthonyalayo** [comment]
I've been following this thread, and I created another SO question for this:
https://stackoverflow.com/questions/66879588/dealing-with-docker-images-in-a-javascript-typescript-monorepo-with-unpublished

Unfortunately I haven't received any answers or found any clear alternatives. If there's any clean ones out there, please let me know. :-)

**Comment by adamgajzlerowicz** [comment]
Update:

It is possible to use a multi stage Docker build.
The COPY between stages will copy the content of the symlinked directory so once you have your Builder created you can do:

```
###

FROM node:12-alpine

WORKDIR /app

COPY --from=builder /app/packages/frontend/dist/ ./dist/
COPY --from=builder /app/packages/frontend/node_modules/ ./node_modules/

CMD ["node", "dist/main"]

```

**Comment by anthonyalayo** [comment]
@adamgajzlerowicz that seems to be the consensus, I changed my search terms around and found an answer with yarn workspaces (which is an overlapping problem):
https://stackoverflow.com/questions/50215553/how-to-build-a-docker-image-from-a-nodejs-project-in-a-monorepo-with-yarn-worksp

**Comment by davidmeirlevy** [comment]
@Soufraz why is this issue got closed? it seems that it's still a problem.

**Comment by davidmeirlevy** [comment]
@Soufraz why did you close this issue?

**Comment by marc-scrypt** [comment]
I have the same problem with `nx`, so I'm looking whether there is a built in solution. Seems not, but since we're on Linux, the solution is simple, with `tar` option `h`, symbolic link targets are copied to the archive, so you can simply create a dereferenced copy of anything you need, including a `node_modules`:

```bash
marc@localhost:/tmp$ mkdir a b c
marc@localhost:/tmp$ touch a/a b/b
marc@localhost:/tmp$ cd a
marc@localhost:/tmp/a$ ln -s ../b .
marc@localhost:/tmp/a$ cd ..
marc@localhost:/tmp$ tree a b c
a
├── a
└── b -> ../b
b
└── b
c

3 directories, 2 files
marc@localhost:/tmp$ tar ch a | tar xC c
marc@localhost:/tmp$ tree a b c
a
├── a
└── b -> ../b
b
└── b
c
└── a
    ├── a
    └── b
        └── b

6 directories, 4 files
```

So one additional line in the `Dockerfile` solves this problem, just copy to `/tmp` and import `node_modules` from there:
```
FROM mwaeckerlin/nodejs-build AS build
RUN mkdir temp
COPY --chown=${BUILD_USER} . .
RUN npm install
RUN npx nx build myApi

FROM mwaeckerlin/nodejs-build AS node-modules
ENV NODE_ENV 'production'
COPY --chown=${BUILD_USER} . .
RUN npm install
RUN tar ch node_modules | tar xC /tmp

FROM mwaeckerlin/nodejs as production
EXPOSE 4000
COPY --from=build --chown=${RUN_USER} /app/temp /app/temp
COPY --from=build /app/backends/myApi/dist /app/dist
COPY --from=build /etc/ssl/cert.pem /etc/ssl/cert.pem
COPY --from=node-modules /tmp/node_modules /app/node_modules
CMD [ "/usr/bin/node", "/app/dist/src/main" ]
```
