### ISSUE TITLE
Is --scope filtering by package name or directory name

### ISSUE THREAD

**Issue by jdm-hexagon** [lerna/lerna#2382]
I'm having trouble creating a glob pattern to find multiple packages with a common naming convention. Am I searching against the directory path or the name field in the package.json?

Directory Structure
packages/
    prefix-module-postfix
    prefix-module-postfix
    prefix-module-postfix
    prefix-platform-postfix
    prefix-platform-postfix

Package Naming convention
@nameSpaceScope/prefix-module-postfix
@nameSpaceScope/prefix-platform-postfix

## Current Behaviour
I'd like to run a command for just the *module* packages or just the *platform* packages.
I've tried globs for:
`--scope *module*`
`--scope **/*module*`
`--scope packages/*module*`
`--scope @nameSpaceScope/*module*`
`--scope @nameSpaceScope/+(*module*)`

The closest glob that gets anything is `--scope packages/*module*`, but it only finds the first module.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.1"
}
```
</p></details>

**Comment by alexandros-megas** [comment]
Having a similar issue to this:

I have some packages with names like `@clarifai-private/foo` and others with names like `@clarifai/bar`, so I'm trying to grab them all with a scope pattern `@clarifai*` but it's not working:

```
$ lerna exec --scope "@clarifai*" rm -rf dist
lerna info version 2.11.0
lerna info versioning independent
lerna info scope @clarifai*
lerna ERR! EPACKAGES Errored while collecting packages and package graph
lerna ERR! Error: No packages found that match scope '@clarifai*'
lerna ERR!     at Function.filterPackages (/builds/clarifai/front-end/front-end/node_modules/lerna/lib/PackageUtilities.js:252:17)
lerna ERR!     at ExecCommand.runPreparations (/builds/clarifai/front-end/front-end/node_modules/lerna/lib/Command.js:333:60)
lerna ERR!     at /builds/clarifai/front-end/front-end/node_modules/lerna/lib/Command.js:209:18
lerna ERR!     at new Promise (<anonymous>)
lerna ERR!     at ExecCommand.run (/builds/clarifai/front-end/front-end/node_modules/lerna/lib/Command.js:193:14)
lerna ERR!     at Object.handler (/builds/clarifai/front-end/front-end/node_modules/lerna/lib/commands/ExecCommand.js:45:14)
lerna ERR!     at Object.self.runCommand (/builds/clarifai/front-end/front-end/node_modules/lerna/node_modules/yargs/lib/command.js:233:22)
lerna ERR!     at Object.Yargs.self._parseArgs (/builds/clarifai/front-end/front-end/node_modules/lerna/node_modules/yargs/yargs.js:990:30)
lerna ERR!     at Object.Yargs.self.parse (/builds/clarifai/front-end/front-end/node_modules/lerna/node_modules/yargs/yargs.js:532:23)
Error: No packages found that match scope '@clarifai*'
```
