### ISSUE TITLE
Maxbuffer

### ISSUE THREAD

**Issue by gilesbradshaw** [lerna/lerna#2384]
The max buffer exceeded error constantly bugs me

I think I have now fixed it by not using --verbose switch

however is there any reason why it is 10000000?  That seems like an arbitrary number to me..

## Expected Behavior
Lerna should not crash with max buffer exceeded

## Current Behavior
lerna crashes with max buffer exceeded

## Possible Solution

either make it bigger, infinite or configurable

**Comment by adibaranga** [comment]
As far as I know, this was fixed in execa since quite a while, latest version is already using 100MB. So just updating the version of execa should have this fixed.

**Comment by flotwig** [comment]
Would love to see a fix for this issue before the bot auto-closes it :upside_down_face: @gilesbradshaw bump?

I think this open PR even closes this issue: #2898

**Comment by JamesHenry** [comment]
Hi Folks, I have taken a look into this, and I just want to understand if it is still an issues with latest version of lerna.

The latest version of lerna uses `execa` v5, which has a much larger 100MB max buffer (not the original 10MB mentioned in this and other issues).

Please could someone (e.g. @flotwig as you flagged this up) confirm they are breaching the 100MB cap? That seems like a very large amount of logs to be producing for a given invocation

**Comment by JamesHenry** [comment]
Hi Folks, given the 100MB buffer from `execa` in the last two major version of lerna seems to have addressed this issue I am going to close this. If you experience any issues with lerna v5 please feel free to open a new issue
