### ISSUE TITLE
Inconsistent behavior of 'lerna changed' vs 'lerna version'

### ISSUE THREAD

**Issue by yairy** [lerna/lerna#2385]
Inconsistent behavior of 'lerna changed' vs 'lerna version'

## Expected Behavior
Accoring to the documentation of `lerna changed`

> The output of lerna changed is a list of packages that would be the subjects of the next `lerna version` or `lerna publish` execution.

Therefore, I expect both commands to list the same packages.

In the example below:I expect `lerna version` to only bump the version of pkg1, because only pkg1 is reported as changed by `lerna changed`

## Current Behavior
`lerna version` bumps the version of all packages. In the example below, I don't understand why pkg2 is bumped. Is this a bug in lerna? In the docs? In my head?

## Steps to Reproduce
1. mkdir lerna-repo && cd $_
2. lerna init 
3. lerna create pkg1 --yes
4. lerna create pkg2 --yes
5. git add .
6. git commit -m "message1"
7. lerna version patch --yes --no-push _(this creates version 0.0.1)_
8. vim packages/pkg1/README.md _(change something)_
9. git commit -am "message2"
10. lerna changed

![Screen Shot 2019-12-18 at 9 27 03](https://user-images.githubusercontent.com/3206243/71064798-a1a5a100-2178-11ea-9c1c-366b92addaba.png)
11. lerna version patch --no-push

<img width="577" alt="Screen Shot 2019-12-17 at 22 39 29" src="https://user-images.githubusercontent.com/3206243/71064972-ed584a80-2178-11ea-80cc-6c1a7eec851b.png">

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.2"
}
```
</p></details>

## Context
I'm trying to implement lerna in my organisation as we have a new monorepo, and this causes me confusion about how lerna manages versioning. I don't know if it's a bug, or I got something wrong.
AFAIK, In fixed mode, lerna should only bump the version of packages that were actually changed since the last tag, or that depend on a package that was changed. Neither is the case in the example above.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.19.0 |
| `npm --version`  | 6.13.1 |
| `yarn --version` | 1.19.2 |
| `node --version` | v13.3.0 |

| OS | Version |
| --- | --- |
| macOS Catalina | 10.15 |

**Comment by wrdls** [comment]
You need to use `independent` versioning if you don't want all packages to be bumped: https://lerna.js.org/#command-init.

You can change this manually by setting `version` from `0.0.2`  to `independent` in your `lerna.json` file.

**Comment by RafaelloLoliop** [comment]
@yairy 
You must have version > 0.1.0 (before 1st minor release, every patch is breaking)
