### ISSUE TITLE
hoist turns optional dependencies to regular dependencies

### ISSUE THREAD

**Issue by vince1995** [lerna/lerna#2386]
I've currently noticed that running `lerna bootstrap` with `--hoist` lerna is putting the optional dependencies from the packages into regular dependencies.

Example: Have a package with `fsevents` (or another package which will fail on some platforms intentionally) as optional dependency. Run `npm bootstrap --hoist` on a non MacOS platform. This will fail.

**Comment by farion** [comment]
Is there a solution in the meantime? This is a major problem as lerna becomes basically useless for cross platform projects without supporting optional dependencies.

**Comment by vince1995** [comment]
https://github.com/lerna/repro/pull/3

**Comment by JamesHenry** [comment]
Hi @vince1995  👋

Thank you very much for taking the time to provided the reproduction.

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

Please therefore look to transition your current usage of bootstrap and hoisting here to instead lean on the package manager you are already using.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
