### ISSUE TITLE
Please no "^" after "lerna publish" in my "package.json"s

### ISSUE THREAD

**Issue by TokugawaTakesi** [lerna/lerna#2397]
All libraries versions in my `package.json` are exact (no `^`):

![image](https://user-images.githubusercontent.com/41653501/71553994-369f7880-2a5c-11ea-97e4-7d0a1a51e159.png)

After `lerna publish`, old versions of internal dependencies has been replaced to newest version, but begins from `^`：

![image](https://user-images.githubusercontent.com/41653501/71554706-34421c00-2a66-11ea-932b-86d459ebed65.png)

There is no `lerna publish -E` option yet. Please provide something like it.

## Expected Behavior

For the case of my monorepo (`hikari-automation` depends on `hikari-es-extensions` and `hikari-frontend`):

![image](https://user-images.githubusercontent.com/41653501/71554723-82efb600-2a66-11ea-8636-492611989154.png)

when I execute `lerna publish -E` and publish, for example, version `0.0.35`, versions of  `hikari-es-extensions` and `hikari-frontend` in package.json of `hikari-automation` must be `0.0.35`, not `^0.0.35`.

## Current Behavior

Current version is `0.0.22`, so lerna added `^` to it:
![image](https://user-images.githubusercontent.com/41653501/71554760-001b2b00-2a67-11ea-85ee-47c4fc3035f4.png)

## Possible Solution

Please add new option for `lerna publish` which makes possible "Expected Behavior" functionality.

## Context

 Maybe everything will be all right until all packages has same version, but I feel unsafety and irritation when see "^" in my `package.json`. It is not ASAP, but I ask you to fix it.

**Comment by evocateur** [comment]
[`--exact`](https://github.com/lerna/lerna/tree/master/commands/version#--exact) is what you're looking for (lerna itself [uses it via json config](https://github.com/lerna/lerna/blob/2b9b210c0b6ac69853ffb01f0dbac9109ab419c5/lerna.json#L15)). It's an option of `lerna version`, but you can pass it to `lerna publish` as well*. There is no `-E` shorthand alias.

* This implicit call of `lerna version` from `lerna publish` will be removed in the next major version.

**Comment by TokugawaTakesi** [comment]
Thank you for the answer!
