### ISSUE TITLE
ls --graph doesn't notice peer dependencies

### ISSUE THREAD

**Issue by ghost** [lerna/lerna#2398]
I have a simple case. An angular project, with two libraries: a, and b. a depends on b, as a peer dependency.  The entire lib is hoisted, meaning that only one common node_modules library exists. 

Really, what I expect is that root/dist/b will be symlinked to root/node_modules/b. 

I am using yarn.

**Comment by evocateur** [comment]
What does `lerna ls --graph` have to do with this? Please follow the issue template.
