### ISSUE TITLE
hoist always

### ISSUE THREAD

**Issue by vince1995** [lerna/lerna#2401]
I've forgot multiple times to add `--hoist` to the bootstrap command. Is there a solution to add this in the `lerna.json` file?

**Comment by evocateur** [comment]
Yes, you can set `hoist: true` in the [lerna.json](https://github.com/lerna/lerna/tree/v3.20.2#lernajson) `command.bootstrap` namespace:

```json
{
  "command": {
    "bootstrap": {
      "hoist": true
    }
  },
  "version": "1.2.3"
}
```

You could also set it at the root level of `lerna.json`, but it doesn't apply to any other subcommand, so using the `command.bootstrap` namespace is clearer.

**Comment by vince1995** [comment]
Thanks. Would be great if this is anywhere documented.
