### ISSUE TITLE
support --token=npmToken in lerna Publish

### ISSUE THREAD

**Issue by hardfist** [lerna/lerna#2404]
## Expected Behavior

since npm publish cannot use NPM_TOKEN as environment, user must write token into .npmrc in order to do lerna publish in CI|CD environment, which is kind of annoying, I think pass token as parameter is more convenient just like what beachball is doing https://microsoft.github.io/beachball/ci-integration
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
`lerna publish` supports the exact same pattern as `npm publish` with respect to environment variables in [npmrc files](https://docs.npmjs.com/files/npmrc). Once `NPM_TOKEN` is configured in the CI variables, add this to your project root `.npmrc` file:
```ini
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```

Note that the only `.npmrc` file respected by Lerna is the project root. Per-package (leaf node) npmrc files are ignored entirely. There's also nothing special about the `NPM_TOKEN` variable name, it's just a convention.

**Comment by hardfist** [comment]
unlike other variable name that we can put variable in environment variable, we must write token in .npmrc file, in a shared environment writing .npmrc will corrupt other user's .npmrc file, and it's also unsafe

**Comment by kylemh** [comment]
If I put `//registry.npmjs.org/:_authToken=${NPM_TOKEN}` into a root-level `.npmrc` and try to commit without a valid NPM_TOKEN in my path, I get an error saying:

`error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".`

I understand _why_ this happens, but this would be preventative for somebody working in this repo in an open source capacity - they wouldn't be able to contribute.
