### ISSUE TITLE
`lerna bootstrap` fails with local entry in `package.json`

### ISSUE THREAD

**Issue by graphan** [lerna/lerna#2410]
## Expected Behavior
`lerna bootstrap` does not fail when we have the following entry in `package.json`:
```
...
"dependencies": {
   "react-native-webview": "file:./../node_modules/react-native-webview"
}
...
```

## Current Behavior
At the moment `lerna bootstrap` fails, because cannot find `../node_modules/react-native-webview` - it is hoisted from another package:

```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "../node_modules/react-native-webview" as it does not contain a package.json file.
```

## Possible Solution
Provide a way to bypass checking the existence of local dependencies.

## Steps to Reproduce (for bugs)
Let's imagine we have the following code structure:
```
- components
- native_app
- node_modules
```
where:
- `node_modules` contains a React Native Library hoisted from `components`
- `native_app` contains a React Native App

then you can link the library with the app running:
`cd native_app && react-native link react-native-webview`

**But**, this requires the following entry in `native_app/package.json`:
```
...
"dependencies": {
   "react-native-webview": "file:./../node_modules/react-native-webview"
}
...
```

And this is a problem, because then `lerna bootstrap` is failing with the error mentioned above.

## Context
It is very important to fix especially for linking React Native Libraries.

A similar issue occurs also for `yarn workspaces`: yarnpkg/yarn#7678 (comment)

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | 1.21.1 |
| `node --version` | 10.16.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Mojave | 10.14.6 |

**Comment by watery** [comment]
I'm unsure I got your request right, though I want to share that I managed to have a local dependency among two packages in the same monorepo:

```
/root-folder
    +-- lerna.json
    +-- ...
    +-- packages
        +-- local-dep
            +-- src
            +-- lib
            +-- babel.config.js
            +-- ...
        +-- myapp
            +-- src
            +-- lib
            +-- babel.config.js
            +-- ...
```

I added the (local) dependency like if it was a regular one:

`lerna create local-dep --private`

That contains some React components, hence:

`lerna run build --scope local*`

Then I added the client application

`lerna create myapp --private`

and added the other package as dependency

`lerna add local-dep --scope myapp`

myapp is a create-react-app, so I run it with

`lerna run start --scope myapp --stream`

All Lerna commands where run from `root-folder`.

HTH

**Comment by shellbj** [comment]
Is this not related to the way yarnpkg handles `file:` vs. `link:` in `package.json`?  There is a closed, but relevant issue to make it follow the same behavior as `npm@5`: https://github.com/yarnpkg/yarn/issues/5768
