### ISSUE TITLE
lerna failed to use the correct git binary

### ISSUE THREAD

**Issue by zypA13510** [lerna/lerna#2418]
Some background, I'm using CentOS + [Git 2.18 SCL](https://www.softwarecollections.org/en/scls/rhscl/rh-git218/), since lerna requires git `--first-parent` switch the vendor-provided git 1.8 does not have (#1726).

The bug is, even after git 2.18 has been enabled for the current shell, lerna keeps using the old 1.8.3 version. It seems to be a bug of `execa@^1.0.0`.

## Expected Behavior

Git 2.18 is used, and no error is thrown.

## Current Behavior

Git 1.8.3 is used, and the following error is thrown:
```
lerna ERR! Error: Command failed: git describe --always --long --dirty --first-parent --match v*.*.*
lerna ERR! error: unknown option `first-parent'
```

## Possible Solution

Upgrade `execa`.

In the same directory lerna is setup (thus using `execa@^1.0.0`), the following script
```js
const childProcess = require('child_process')
const execa = require('execa')
childProcess.exec('which git', (error, stdout, stderr) => console.log(stdout))
childProcess.exec('git --version', (error, stdout, stderr) => console.log(stdout))
execa('which', ['git']).then(({stdout}) => console.log(stdout))
execa('git', ['--version']).then(({stdout}) => console.log(stdout))
```
outputs
```
/opt/rh/rh-git218/root/usr/bin/git
git version 2.18.1
/usr/bin/git
git version 1.8.3.1
```

However, in a folder with the latest `execa@^4.0.0` installed, the above script outputs:
```
/opt/rh/rh-git218/root/usr/bin/git
git version 2.18.1
/opt/rh/rh-git218/root/usr/bin/git
git version 2.18.1
```

## Steps to Reproduce (for bugs)

1. [Set up and enable rh-git218 for current shell](https://www.softwarecollections.org/en/scls/rhscl/rh-git218/)
2. Run `lerna publish --canary --preid rc --pre-dist-tag next`

<details><summary>lerna.json</summary><p>

```json
{
  "version": "0.1.0",
  "npmClient": "yarn",
  "command": {
    "publish": {
      "message": "chore(release): publish",
      "registry": "https://gitlab.com/api/v4/projects/12345678/packages/npm/"
    }
  },
  "useWorkspaces": true,
  "packages": [
    "packages/*"
  ]
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.13.6 |
| `yarn --version` | 1.21.1 |
| `node --version` | v10.18.1 |

| OS | Version |
| --- | --- |
| CentOS | 7.7.1908 |

**Comment by zypA13510** [comment]
I'd love to help resolve this issue, but I'm at a loss with tracing all the dependents of execa, and from what I see, some of these dependents (e.g. core/child-process) expose the execa API further downstream. And it becomes hard to find all references of the API and remove any deprecated ones. @evocateur I see that you have done this before in 748ae4e, any idea?

**Comment by darrylsepeda** [comment]
got same error message when I run `lerna publish from-git`:

```
lerna notice cli v3.22.1
lerna ERR! Error: Command failed: git describe --always --long --dirty --first-parent
lerna ERR! fatal: bad revision 'HEAD'
lerna ERR! 
lerna ERR!     at makeError (/Users/*/.nvm/versions/node/v12.13.0/lib/node_modules/lerna/node_modules/execa/index.js:174:9)
lerna ERR!     at /Users/*/.nvm/versions/node/v12.13.0/lib/node_modules/lerna/node_modules/execa/index.js:278:16
lerna ERR! lerna Command failed: git describe --always --long --dirty --first-parent
lerna ERR! lerna fatal: bad revision 'HEAD'
lerna ERR! lerna 
```

**Comment by MarcoEscaleira** [comment]
What git version are you using ? Using git 2 or above solves this issue

**Comment by zypA13510** [comment]
> What git version are you using ? Using git 2 or above solves this issue

The issue is not about git version, but when two different versions of git executable exist on the system, lerna failed to use the correct one (git 2 or above).

Like I said, upgrading the dependency to `execa@^4.0.0` will solve this issue, which also proves it's not a setup issue.

**Comment by evocateur** [comment]
[v4.0.0](https://github.com/lerna/lerna/releases/tag/v4.0.0) is now available as `lerna@next`, which should resolve this issue. Please update if that's not the case.
