### ISSUE TITLE
Can Lerna base the version off git tag history vs. package.json?

### ISSUE THREAD

**Issue by darewreck54** [lerna/lerna#2419]
Sorry, this might not be the right place for this question since it's not a bug but more of a feature request.

I'm trying to figure out the best way to use lerna in a full CI system.  Ideally, in a CI system you want the build to be isolated from the release phase.  The normal flow for a CI is

```
PullRequest --> Trigger Build --> Build/Unit Test --> Publish Artifacts
```

When semantic versioning with lerna is introduced the process becomes

```
Pull Request --> Trigger Build --> Build/Unit Test --> Read Package.json & Generate Next Semantic Version -> Commit new package.json --> Publish Artifacts
```

The problem with the second flow is that you are actually modifying the code your building by updating the package.json and commiting it again which in some ways invalidates your original build.  You can build it again, but you would have to have some logic to by pass the whole versioning and publishing again.  In this case, Lerna just won't publish it again since there is no major/minor/patch change since only the package.json got updated

**Question**
For a CI system, you don't want to be modifying code that you are building and publishing.  Is there a way for lerna to not depend on the package.json but on the git tags that are generated for the release.  It can just grab the latest git tag and increment the major,minor, patch accordingly.  

Let me know what your thoughts on this or any suggestions?
Thanks,
Derek

**Comment by joebowbeer** [comment]
Can you compare and contrast what you are looking for with the `from-package` option added for #1648?

**Comment by darewreck54** [comment]
I don’t believe you can. The main issue is that the logic is based off the package.json which needs to be checked in. So versioning is based off a file that then needs to be updated and committed. If git tags were used for the last version, this wouldn’t be an issue.

Sent from my iPhone

On Jan 22, 2020, at 6:43 PM, Joe Bowbeer <notifications@github.com> wrote:

﻿

Can you compare and contrast what you are looking for with the from-package option added for #1648<https://github.com/lerna/lerna/issues/1648>?

**Comment by darewreck54** [comment]
@joebowbeer is this something that can be supported by lerna?

**Comment by joebowbeer** [comment]
I'm not understanding the request or the question.

In the default case, git tags are used, right?

How is`lerna publish from-git` not what you are requesting?

`lerna publish from-package` was added later for retrying a failed publish. And to accommodate a CI workflow where CI cannot push commits or tags, and the bumped package.json is committed before CI is triggered.

**Comment by hipstersmoothie** [comment]
> How is lerna publish from-git not what you are requesting?

I thought this too but after investigation `from-git` will only make a release for packages tagged in the HEAD commit, *but* it uses the version in the package.json rather than the version in the tag. 

ex:

- HEAD tagged with `@my/package@1.0.0-next.0` and package.json has `version: 1.2.3`
- Run `lerna publish from-git`
- lerna will try to release `@my/package@1.2.3` instead of `@my/package@1.0.0-next.0`

@evocateur This seems like a bug to me. I would expect `from-git` to use the version in the tag.

**Comment by hipstersmoothie** [comment]
It seem like the functionality described in https://github.com/lerna/lerna/issues/2337 is what both I and @darewreck54 are looking for. A `from-tag` positional that can manage the version based only on tags. @evocateur would you be open to me submitting a PR for this functionality?

For the best API it should probably be composed of two parts:

1. Add `--no-commit` flag to `lerna version`
2. Add `from-tag` positional to `lerna publish`

Would be used as follows:

```sh
lerna version --no-commit patch
lerna publish from-tag
```

What I mainly want to use this for is creating `next` releases in [auto](https://github.com/intuit/auto). For `next` releases we manage the version solely using a git tag. Currently if I want this functionality I will have to:

1. Manually create tags and update package.json without commiting
2. run `lerna publish --no-git-reset` to publish the tag
3. Reset any changes to package.json
