### ISSUE TITLE
can't skip `git add package-lock.json` when `publish`?

### ISSUE THREAD

**Issue by bluelovers** [lerna/lerna#2430]
## Expected Behavior

do not `git add package-lock.json`  when package-lock.json is inside of `.gitignore`

## Current Behavior

![image](https://user-images.githubusercontent.com/167966/73367293-54c1f800-42ea-11ea-8d1d-b237ef477830.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.12.0 |
| `yarn --version` | 1.21.1 |
| `node --version` | v13.7.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by sunlanterns** [comment]
Hi there! I noticed your issue looks really similar to #2391 - is it possible the solution presented there could fix your issue as well?
