### ISSUE TITLE
lerna exec does not work with redirection

### ISSUE THREAD

**Issue by dan-cooke** [lerna/lerna#2436]
Given 6 packages in my `packages` directory, if I run
```
lerna exec -- printf "hello" > test
```
## Expected Behavior
I would expect to see 6 files called `test` in each, with the string `hello`

## Current Behavior
1 file is created at the root with the following contents
```
hellohellohellohellohellohello
```

## Lerna JSON
```json
{
  "npmClient": "yarn",
  "useWorkspaces": true,
  "packages": [
    "packages/**"
  ],
  "version": "independent",
  "command": {
    "version": {
      "allowBranch": ["develop"]
    },
    "publish": {
      "conventionalCommits": true,
      "message": "chore(release): publish %s"
    }
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.10.7 |
| `npm --version`  | 6.13.6 |
| `yarn --version` |1.19.1 |
| `node --version` | v13.7.0 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.6 |

**Comment by AlexJeffcott** [comment]
I have run into the exact same issue on lerna 4, node 16 and npm 8

**Comment by JamesHenry** [comment]
Hi Folks 👋 

This one makes sense that it wouldn't work. You should wrap the overall command in quotes so that it is all captured.

```sh
npx lerna exec -- "printf \"hello\" > test"
```

I tried this just now in the lerna repo itself and it worked fine:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/900523/223772940-2469baa9-2e0b-490a-85c9-7f12dc976813.png">
