### ISSUE TITLE
lerna publish with --contents results in a 403 

### ISSUE THREAD

**Issue by pdylanross** [lerna/lerna#2439]
I'm using lerna to manage subpackages in a node+express app so that I can generate an angular client library for the service's api contracts and correlate that client lib with the service's version. The client lib is generated with OpenAPITools/openapi-generator and then built with ng-packagr. 

Due to some interactions with ng-packgr, the build output, and the modified package.json, I need to use the --contents flag with lerna so that I can publish just the build output. The npm packages are then being published to a private azure devops npm feed, and the build is performed on a hosted azure devops build agent. Because of how azure devops artifact feeds work we've found that the easiest path to managing private feed authentication is to simply check a .npmrc into the repo. This works just fine with a variety of other packages that we've produced and all has worked as expected, however for some reason with this workflow around ng-packagr and the --contents flag we get 403's from the private feed. I've confirmed that the same build publishes correctly without the contents flag and simply enabling that results in the 403's. 

## Expected Behavior
* `lerna publish from-package -y --contents dist` successfully publishes packages
* `lerna publish from-package -y` successfully publishes packages

## Current Behavior
* `lerna publish from-package -y --contents dist` results in a 403 from azure devops private npm feeds. 
* `lerna publish from-package -y` successfully publishes packages

## Steps to Reproduce (for bugs)
1. Create a package that requires usage of the contents flag
2. Publish package to a private feed
3. (will fill out as I figure out more)

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "1.0.15",
  "command": {
    "publish": {
      "registry": "https://pkgs.dev.azure.com/REDACTED/_packaging/REDACTED/npm/registry/"
    }
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
lerna notice cli v3.20.2
lerna info ci enabled
lerna info current version 1.0.15
lerna notice FYI git repository validation has been skipped, please ensure your version bumps are correct
lerna info Looking for changed packages since v1.0.15
lerna WARN version Skipping working tree validation, proceed at your own risk

Changes:
 - @REDACTED/XXX-client-angular: 1.0.23 => 1.0.27
 - @REDACTED/XXX-client-axios: 1.0.15 => 1.0.27

lerna info auto-confirmed 
lerna info execute Skipping git tag/commit
lerna info execute Skipping git push
lerna info execute Skipping releases
lerna success version finished
[feature/init 25c9ea0] lerna inprogress
 6 files changed, 14 insertions(+), 19 deletions(-)
lerna notice cli v3.20.2
lerna info ci enabled

Found 2 packages to publish:
 - @REDACTED/XXX-client-angular => 1.0.27
 - @REDACTED/XXX-client-axios => 1.0.27

lerna info auto-confirmed 
lerna info publish Publishing packages to npm...
lerna notice Skipping all user and access validation due to third-party registry
lerna notice Make sure you're authenticated properly ¯\_(ツ)_/¯
lerna WARN ENOLICENSE Packages @REDACTED/XXX-client-angular and @REDACTED/XXX-client-axios are missing a license.
lerna WARN ENOLICENSE One way to fix this is to add a LICENSE.md file to the root of this repository.
lerna WARN ENOLICENSE See https://choosealicense.com for additional guidance.
lerna http fetch PUT 403 https://pkgs.dev.azure.com/REDACTED/_packaging/REDACTED/npm/registry/@REDACTED%2fXXX-client-angular 222ms
lerna ERR! E403 Forbidden

```
</p></details>

## Context
Probably not related, however one thing that might be of note is that because of the ci/cd scenario this runs through and the service that this is being emitted from, we are not using lerna's versioning strategies. The express app is being built into a docker container that is then going to be deployed into k8s, so we already had a semver based versioning strategy in place based on git tagging. The end desire of this workflow is twofold: 1. Rapid api development with a tight iteration path between client and server side. 2. Correlation of frontend and backend versions via package dependencies. 

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.13.1 |
| `node --version` | 13.3.0 |

| OS | Version |
| --- | --- |
| Ubuntu | 18.04 |
-->

**Comment by pdylanross** [comment]
I've figured it out. 

Azure devops returns a 403 when you're trying to upload a package with a version that already exists, and the error was in my custom versioning scheme. I performed the versioning operation after the build, which meant that the package in /dist was never getting that version number applied. The fix was a simple change in the order of operations there. 

There could perhaps be enhancements made around output of error responses from npm - it seemed silly that I had to drop to 'silly' log verbosity to find that out, but that's neither here nor there. Closing the issue now.

**Comment by CodeByAlex** [comment]
Hey @pdylanross - Thanks for documenting this. Ran into a similar issue today and this really helped 💯

**Comment by petermikitsh** [comment]
To add on to @pdylanross's follow-up comment: This occurs if you use Artifactory too. In our particular use case, we were re-running CI jobs that publish NPM packages. The first run would succeed, but the 2nd...n'th runs would fail, as the packages had already been published. I also was conflating 401 and 403, assuming there was an issue with my authentication credentials, which was not the case; the credentials supplied were correct.

Also, we were observing the 403 response without using the `--contents` option.
