### ISSUE TITLE
Version Comparison Links in CHANGELOG Don't Work on Bitbucket

### ISSUE THREAD

**Issue by jamiechong** [lerna/lerna#2451]
I'm using `lerna publish --conventional-commits`, which works amazingly well for our organization. So thanks! The CHANGELOG updates provide links to differences between tagged versions. In bitbucket it seems that the URLs aren't correct. They point to a 404 in Bitbucket. 

## Expected Behavior
Clicking Version link in the changelog should take me to a page in Bitbucket that compares the version against the previous one.

## Current Behavior
The link takes me to a 404

## Possible Solution
It seems like there's a few things wrong with the URL. When I compare two versions manually, the portion of the URL after: `.../compare/` is URL Encoded. Also the separator between the two versions seems to be `%0D` not `...` which is in the URL in the CHANGELOG.

## Steps to Reproduce (for bugs)
1. Run `git commit -m "feature: My new awesome feature"` so that step 2 produces an entry in the CHANGELOG
2. Run `lerna publish --conventional-commits`
3. View the generated/updated `CHANGELOG.md` file to see the erroneous URL.

**Comment by davidsierradz** [comment]
Modify your changelog generation settings:

lerna.json:

```json
{
  "command": {
    "version": {
      "changelogPreset": "./changelog-preset.config.js"
    }
  }
}
```

changelog-preset.config.js

```javascript
module.exports = Promise.resolve()
  .then(() => require('conventional-changelog-conventionalcommits'))
  .then(presetPromise => presetPromise())
  .then(preset => {
    preset.writerOpts.commitUrlFormat =
      '{{host}}/{{owner}}/{{repository}}/commits/{{hash}}'
    preset.writerOpts.compareUrlFormat =
      '{{host}}/{{owner}}/{{repository}}/compare/{{currentTag}}%0D{{previousTag}}'
    return preset
  })
```
See:
- [Customize changelog and additional git add files · Issue #2333 · lerna/lerna](https://github.com/lerna/lerna/issues/2333)
- [conventional-changelog-config-spec/README.md at master · conventional-changelog/conventional-changelog-config-spec](https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md)

**Comment by hitmands** [comment]
Hi,
I have the same issue: https://github.com/lerna/lerna/issues/2604

totally unable to change [issueurlformat-string](https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md#issueurlformat-string)

___

I have also tried to use a custom `changelog-preset.config.js`, 
the file is executed but the returned preset is ignored...

**Comment by creage** [comment]
Same here - custom preset is not applied. Any tip how to fix it?

**Comment by phun-ky** [comment]
TBH, this should be supported out of the box. Not everyone uses github. 

@creage Got it to work, thanks! But how do we fix the compare tags link? I noticed that the link is created with handlebars, instead of via js, so it's harder to fix :(

**Comment by creage** [comment]
@phun-ky well, this one is a bit trickier, but not impossible. Since the compare link is generated in the `handlebars` template - we have to overwrite it in `preset.writerOpts.headerPartial` as well:

```javascript
const _ = require('lodash');

const header = `
{{#if isPatch~}}
  ##
{{~else~}}
  #
{{~/if}} {{#if @root.linkCompare~}}
  [{{version}}](
  {{~#if @root.repository~}}
    {{~#if @root.host}}
      {{~@root.host}}/
    {{~/if}}
    {{~#if @root.owner}}
      {{~@root.owner}}/
    {{~/if}}
    {{~@root.repository}}
  {{~else}}
    {{~@root.repoUrl}}
  {{~/if~}}
  /_git/MyRepo/branches?baseVersion=GT{{previousTag}}&targetVersion=GT{{currentTag}}&_a=commits)
{{~else}}
  {{~version}}
{{~/if}}
{{~#if title}} "{{title}}"
{{~/if}}
{{~#if date}} ({{date}})
{{/if}}
`;

module.exports = Promise.resolve()
    .then(() => require('conventional-changelog-angular'))
    .then(preset => {

        if (!preset.writerOpts._wrapped) {

            preset.writerOpts.headerPartial = header;

            preset.writerOpts._wrapped = true;

            preset.writerOpts.transform = _.wrap(preset.writerOpts.transform, function (_super, commit, context) {

                context.repository = 'tfs/DefaultCollection/MyProject';

                context.commit = '_git/MyRepo/commit'

                context.issue = '_workitems/edit';

                commit = _super(commit, context);

                if (commit && commit.references) {

                    commit.references = commit.references
                        .reduce((unique, item) => unique.find(e => e.issue === item.issue) ? unique : [...unique, item], []) // filter our duplicates
                        .map(reference => Object.assign(reference, { repoUrl: context.repoUrl.replace('/_git', '') })); // references should not include /_git
                }

                return commit;
            });
        }

        return preset;
    });
```

**Comment by phun-ky** [comment]
@creage nice! thanks!

**Comment by bertho-zero** [comment]
It is now possible with the `lerna.json`:

```json5
{
  // ...
  "command": {
    "version": {
      "conventionalCommits": true,
      "changelogPreset": {
        "name": "conventionalcommits",
        "commitUrlFormat": "{{host}}/{{owner}}/{{repository}}/commits/{{hash}}",
        "compareUrlFormat": "{{host}}/{{owner}}/{{repository}}/branches/compare/{{currentTag}}..{{previousTag}}"
      }
    }
  }
}

**Comment by phun-ky** [comment]
@bertho-zero  how do you combine your answer with @creage 's answer?

**Comment by bertho-zero** [comment]
@phun-ky I don't understand for what purpose, @creage created a custom preset and I am using the conventional-commits preset with commitUrlFormat and compareUrlFormat which were unusable a short time ago with lerna.

I think you can keep these 2 options and your custom preset should be a function that receives the config.

**Comment by NathTech** [comment]
@bertho-zero I have tried adding the `changelogPreset` option to my `lerna.json` file but to no avail.
What command are you then running it with / what modules need installing to make it work?

```
  // lerna.json
  // ...
  "command": {
    "publish": {
      "conventionalCommits": true
    },
    "version": {
      "conventionalCommits": true,
      "changelogPreset": {
        "name": "conventionalcommits",
        "commitUrlFormat": "{{host}}/{{owner}}/{{repository}}/commits/{{hash}}",
        "compareUrlFormat": "{{host}}/{{owner}}/{{repository}}/branches/compare/{{currentTag}}%0D{{previousTag}}"
      }
    }
  }
```
with command
`npx lerna version --conventional-commits --changelog-preset conventionalcommits`
and I installed  `conventional-changelog-conventionalcommits` as well but still no joy.

I've really struggled to find some docs that explain how to use the preset options in the context of a lerna.json file :(

**Comment by kerryj89** [comment]
> @bertho-zero I have tried adding the `changelogPreset` option to my `lerna.json` file but to no avail.
> What command are you then running it with / what modules need installing to make it work?
> 
> ```
>   // lerna.json
>   // ...
>   "command": {
>     "publish": {
>       "conventionalCommits": true
>     },
>     "version": {
>       "conventionalCommits": true,
>       "changelogPreset": {
>         "name": "conventionalcommits",
>         "commitUrlFormat": "{{host}}/{{owner}}/{{repository}}/commits/{{hash}}",
>         "compareUrlFormat": "{{host}}/{{owner}}/{{repository}}/branches/compare/{{currentTag}}%0D{{previousTag}}"
>       }
>     }
>   }
> ```
> 
> with command
> `npx lerna version --conventional-commits --changelog-preset conventionalcommits`
> and I installed `conventional-changelog-conventionalcommits` as well but still no joy.
> 
> I've really struggled to find some docs that explain how to use the preset options in the context of a lerna.json file :O(
> 
> any help much appreciated thanks

I tried installing `npm install conventional-changelog-conventionalcommits` to root and package directories but no go.  For what it's worth, what finally worked for me was installing it globally `npm i conventional-changelog-conventionalcommits -g`.

**Comment by jessy1092** [comment]
Hi all, I use custom changelog preset in 2021.

version
```
"conventional-changelog-conventionalcommits": "^4.5.0",
"lerna": "^3.20.2",
```

`changelog-preset.config.js`
```js
const config = require('conventional-changelog-conventionalcommits');

module.exports = config({
   commitUrlFormat: "{{host}}/{{owner}}/{{repository}}/commits/{{hash}}",
   compareUrlFormat: "{{host}}/{{owner}}/{{repository}}/branches/compare/{{currentTag}}%0D{{previousTag}}"
});
```

Command line 
```
lerna version --conventional-commits --changelog-preset ./changelog-preset.config.js
```
