### ISSUE TITLE
Lerna modified existing project package.json files without warning.

### ISSUE THREAD

**Issue by trusktr** [lerna/lerna#2452]
Seems like `lerna init` should give a warning that it will replace the root package.json or re-write package.json files in `packages/*` folders. 

For example, it was surprising that lerna went into the package.json files of all my projects in `packages/` and deleted all their `scripts` sections, and also it overwrote my whole root package.json file.

There was also some lerna temporary files left behind. EDIT: Those were package.json.lerna_backup files. Maybe that's where the scripts were placed. Why does it need to move those?

**Comment by trusktr** [comment]
Looks like it is temporary, and that it places things back later. I'm still curious why it needs to do this.

**Comment by ktamas77** [comment]
I ran into the same issue - has any explanation surfaced yet?

**Comment by nickwelp** [comment]
I deleted all my scripts. It did not put them back.

**Comment by trusktr** [comment]
> yet

Yes, Lerna removes a bunch of stuff from package.json during the `bootstrap` process in Lerna 6 or lower.

This is so that it can do a pure install of all non-linked dependencies without any interference from scripts.

It then links everything, and then puts back all the stuff, and finishes.

However, if there was a failure in Lerna itself, it may fail to restore the content from `package.json.lerna_backup` back to `package.json`, in which case you could do that manually.

# But!

Lerna 7 no longer does any installation and package management. It only does the other stuff. So this problem is long gone! Use lerna 7 for running scripts, publishing, etc, but use `yarn`, `pnpm`, or `npm` for workspace bootstrap and linking.
