### ISSUE TITLE
Lerna >> lerna/run-lifecycle >> npm-lifecycle >> node-gyp >> request [deprecated dependency]

### ISSUE THREAD

**Issue by vcpablo** [lerna/lerna#2458]
As announced by the _request_ package maintainer, it is now fully deprecated.
I noticed that it is an indirect dependency of _lerna_ following this tree:

![image](https://user-images.githubusercontent.com/4389464/74731400-a6450f00-5226-11ea-919a-63d226064ad7.png)

Is this something we should concern about?
Should we do something to solve this?

**request deprecation warning**
https://www.npmjs.com/package/request

**node-gyp note**
https://github.com/nodejs/node-gyp/issues/2047

**Please correct me (or ignore this issue) if I am wrong.**

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.2 |
| `npm --version`  | 6.13.6 |
| `node --version` | 13.8.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Catalina | 10.15.3 |

**Comment by evocateur** [comment]
Thanks for the notice, but this isn't something Lerna can fix directly, it's up to `node-gyp`. Following the issue you linked is the best course, going forward.
