### ISSUE TITLE
lerna publish errors with a 403 when publishing packages to a private repo

### ISSUE THREAD

**Issue by dliu120** [lerna/lerna#246]
I have a publishConfig set to a private npm repo for each package under the packages/ folder, but when I run lerna publish, it fails on the npm dist-tag ls <my-package> command with a 403, because they are not in the public NPM repository.

npm ERR! dist-tag ls Couldn't get dist-tag data for foo-package
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ldavi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "dist-tag" "ls" "foo-package"
npm ERR! node v4.4.5
npm ERR! npm  v3.8.3
npm ERR! code E403

npm ERR! Registry returned 403 for GET on https://registry.npmjs.org/-/package/foo-package/dist-tags
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\dev\aria-portal\aria-data-apps\npm-debug.log

**Comment by gigabo** [comment]
Hi @dliu120, how are you specifying your registry?  In your `package.json#publishConfig`?

Here's one possible [workaround](https://github.com/lerna/lerna/issues/223#issuecomment-228210043).

**Comment by dliu120** [comment]
Yes, we set our private repo in the publishConfig. 

That workaround will be fine for now...but only if the publisher has npmjs.org set as the registry initially. A better workaround is perhaps to detect the original registry and reset the registry to its original. It sounds like we'll have to write a script to do this until Lerna can handle this.

Ideally, Lerna should detect the publishConfig in each package's package.json and run its npm commands in that registry during the publish if it exists

**Comment by dliu120** [comment]
Ok the fix is actually really simple for me. Since ALL of our packages are private, we put an .npmrc in the root lerna directory to point to the private repo, and it works.
