### ISSUE TITLE
How do I depend on sibling packages 

### ISSUE THREAD

**Issue by lemiesz** [lerna/lerna#2463]
The documentation does not seem to be very friendly to users that are not familiar with monorepos. 

Currently I have a structure like this 

packages
 -game-renderer
 -game-state
 -game-core

game-core depends on render and state + some external npm libraries. 

I run `lerna add game-state game-renderer`. 
then `lerna bootstrap` 

from inside the game-core package. 

For some reason this adds those dependencies to every other package. Then when I try to do a regular npm install it tells me they can not be found. What am I doing wrong. 

My questiosn are: 

1.) How do i properly do inter package dependencies? Do I have to publish all my packages to NPM.

**Comment by redbugz** [comment]
https://github.com/lerna/lerna/tree/master/commands/add#examples

Assuming you have your packages in a `packages` directory.
I typically do `lerna add game-state packages/game-renderer`
Or you can do:
`lerna add game-state --scope=game-renderer`
