### ISSUE TITLE
lerna commands occasionally delete package source code

### ISSUE THREAD

**Issue by redbugz** [lerna/lerna#2468]
Not enough information to be helpful, but I want to capture what we are experiencing in case more details arise or others can help diagnose.

## Expected Behavior

lerna should not delete source code

## Current Behavior

We are still struggling to find a pattern or trigger, but across several engineers and a couple of our projects that use lerna, now and then (a few times a month?) after running `npm install`, or a lerna command, one of our package directories will be deleted. We just revert the deletion in local git before committing, but it's disconcerting and has caused some minor intermediate changes to be lost that had to be re-done.

## Possible Solution

Maybe something with a clean following symlinks when it shouldn't or something?
It does seem to be a small set of packages that are deleted, not random, but some timing trigger or dependency trigger? But a few of our packages seem to be the ones more likely to be deleted, but it's not always the same one.

## Steps to Reproduce (for bugs)
I wish we knew. 

It happened a couple times when `lerna add` failed with `cb() never called!` error, which we get fairly regularly, but we chalk that up to a npm bug. So I thought perhaps that was the trigger, but we've had it happen since then without that npm error, so probably a red herring.

<details><summary>lerna.json</summary><p>

```json
{
  "command": {
    "publish": {
      "ignoreChanges": [
        "**/package-lock.json",
        "**/jest.config.js",
        "*.md",
        "**/tests/**",
        "**/Demo/**",
        "**/Details/**"
      ]
    },
    "diff": {
      "ignore": [
        "**/package-lock.json",
        "**/jest.config.js",
        "*.md",
        "**/tests/**",
        "**/Demo/**",
        "**/Details/**"
      ]
    }
  },
  "packages": ["packages/*"],
  "version": "independent"
}

```
</p></details>

## Context
We have 3 projects using lerna, one large one with 40-ish packages, one with several and one with just a couple packages. It happens the most in the large one it seems, but hard to know because it gets worked on the most and exercised the most as well, so size may not be relevant. It has happened in the medium one once. Haven't seen it in the small one yet. There are lots of interdependencies between the packages with sometimes different versions as dependencies.

## Your Environment
npm with package-locks disabled
postinstall runs:
`    "bootstrap": "lerna bootstrap --hoist --no-ci -- --no-package-lock --loglevel error",`

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.13.4 |
| `node --version` | v12.16.0 |

| OS | Version |
| NAME | VERSION |
| macOS Mojave | 10.14.6 |
| macOS Catalina | 10.15? |

**Comment by redbugz** [comment]
I have a reproducible case in a local folder now. I can get it to delete a package every time I run `lerna bootstrap`. It looks like it might be caused by different version dependencies. When I get some time, I will try and debug it and identify what is triggering the deletion.

**Comment by ValeryVS** [comment]
I can confirm, that `lerna bootstrap` with endbled hoisting delete package if it's dependency of other packages and version is not synced between them.

**Comment by ValeryVS** [comment]
#2181 #2683 Related

There is, probably, useful workaround in #2181 

> I run lerna bootstrap --no-hoist * to prevent hoisting...

Filtering internal packages with `no-hoist`, is potential workaround.
