### ISSUE TITLE
Exclude certain deps from hoisting in certain packages?

### ISSUE THREAD

**Issue by achingbrain** [lerna/lerna#2471]
Is it possible to exclude certain deps from hoisting in certain packages only?

I have a project like

```
lerna.json
└── packages/
    ├── a
    ├── b
    └── c
```

Packages `a`, `b` and `c` all depend on external module `d`, published on npm.

`a` and `b` are vanilla node modules which don't mind that `d` has been hoisted to the root.

`c`, on the other hand requires that `d` be in it's `node_modules` folder due to the tooling it uses (`react-scripts` in this case, unlikely to change it's behaviour).

I can exclude `d` from hoisting globally in `lerna.json` but I'd like to only exclude it from hoisting for package `c`.  So `a` and `b` would use the copy of `d` hoisted to the root and `c` would get its own copy in its own `node_modules` folder.  Is this possible? 

The reason being that `c` is an example project of how to use `a` and `b` so I don't care that it has duplicated/unhoisted deps as it's rarely used, but I do care that excluding `d` from hoisting globally affects all packages in the project.

**Comment by dwjohnston** [comment]
I'm trying to solve the same problem. 


You can use the `--ignore` flag to not bootstrap a dependency.

**Comment by trusktr** [comment]
Yep, that will likely not link things correctly.

**Comment by harrisj1** [comment]
Just ran into this issue. Trying to integrate a Docusaurus site into my monorepo, and it depends on Webpack 5, while my other packages use a hoisted Webpack 4.

Would be great to be able to exclude the Docusaurus site package from having any of its dependencies hoisted, while still being able to get the symlinks to my other packages.

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
