### ISSUE TITLE
Symlinks for binaries do not work for yarn users on windows

### ISSUE THREAD

**Issue by TimHolzherr** [lerna/lerna#2472]
The lerna release v3.16.2 introduces a bug for yarn users on windows. Symlinks for binaries (in node_modules/.bin) are no longer created. This bug is not present in v3.16.1 but exists in all newer versions.

Interestingly this behavior only occurs for yarn users, it works fine with npm.
Please see my minimal reproducible example at  https://github.com/TimHolzherr/reproduce-lerna-bug

## Expected Behavior
- Lerna creates symlinks for binaries also for yarn users on windows.
- [minimal reproducible example](https://github.com/TimHolzherr/reproduce-lerna-bug) succeeds

## Current Behavior
- Lerna does not create symlinks for binaries for yarn users on windows.
- [minimal reproducible example](https://github.com/TimHolzherr/reproduce-lerna-bug) fails

## Possible Solution
- It is likely that this regression was introduced either with commit [c3f7998](https://github.com/lerna/lerna/commit/c3f7998) or with [60d1100](https://github.com/lerna/lerna/commit/60d1100)

## Steps to Reproduce (for bugs)
1. git clone https://github.com/TimHolzherr/reproduce-lerna-bug.git 
2. yarn && yarn bootstrap && yarn test-binary-symlink

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["bar", "foo"],
  "npmClient": "yarn",
  "version": "0.0.0"
}
```
</p></details>

## Your Environment
- yarn@1.22.0
- node@v12.13.0
- Windows 10 (19041.84)

**Comment by evocateur** [comment]
Thanks for the detailed notes and reproduction!

**Comment by dcheung2** [comment]
I having random .bin folder lost too.
But I am linux and I am using npm. I don't think it is same problem.

It is annoying because it is RANDOM,

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
