### ISSUE TITLE
lerna version -include-merged-tags calls git --first-parent

### ISSUE THREAD

**Issue by askbeka** [lerna/lerna#2482]
In my CI where I have no control over the version of git `--first-parent` flag is not supported
but when I pass the flag `--include-merged-tags` according to [describe-ref](https://github.com/lerna/lerna/blob/6c4ee5294002c0e464f557b149516017eccf2a07/utils/describe-ref/lib/describe-ref.js#L27) logic it should be omitted.
But when `@lerna/version` [uses check-working-tree](https://github.com/lerna/lerna/blob/6c4ee5294002c0e464f557b149516017eccf2a07/commands/version/index.js#L246), which [uses describe-ref](https://github.com/lerna/lerna/blob/6c4ee5294002c0e464f557b149516017eccf2a07/utils/check-working-tree/lib/check-working-tree.js#L15) without passing `includeMergedTags`. This flag is still being passed.

I do not see why this behavior is logical, Is this behavior intended?
## Expected Behavior

`--first-parent` flag should not be set when `includeMergedTags` is `true`

## Current Behavior

`--first-parent` flag is set when `includeMergedTags` is `true`

## Possible Solution

pass the flag down to `check-working-tree` which will pass it to `describe-ref`
## Steps to Reproduce (for bugs)

1. install git version 1
2. run `lerna version --include-merged-tags`

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "packages": ["packages/*/*"],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "version": {
      "allowBranch": ["master"],
      "conventionalCommits": true,
      "message": "chore(release): publish"
    }
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `yarn --version` | 1.22.0 |
| `node --version` | v10.18.1 |
| `git --version` | 1.8.3.1 |

| OS | Version |
| --- | --- |
| rhel | 7 |

**Comment by creage** [comment]
@evocateur can we something about it?

Because it actually breaks changes detection based on merged tags.

```git tag
git tag
v2020.3.3 // tag on merged branch
v2020.3.4 // *** TAG ON MAIN BRANCH ***
v2020.3.6 // tag on merged branch
v2021.0.2 // tag on merged branch
v2021.0.3 // tag on merged branch
```
And

`lerna version 2021.0.4 --conventional-commits --include-merged-tags --yes`

collects all changes made since `v2020.3.4`, and not since `v2021.0.3` which to me looks broken.

**Comment by aigoncharov** [comment]
Also happens when I run `lerna publish --canary --preid next --dist-tag next --yes --no-verify-access --include-merged-tags` on CentOS 7

**Comment by aigoncharov** [comment]
I believe I found the root cause.
1. `lerna publish --canary` calls [detectCanaryVersions](https://github.com/lerna/lerna/blob/f6e7a13e60fefc523d701efddfcf0ed41a77749b/commands/publish/index.js#L330).
2. It calls [verifyWorkingTreeClean](https://github.com/lerna/lerna/blob/f6e7a13e60fefc523d701efddfcf0ed41a77749b/commands/publish/index.js#L345)
3. Which call [describeRef](https://github.com/lerna/lerna/blob/f6e7a13e60fefc523d701efddfcf0ed41a77749b/commands/publish/index.js#L251) without the `includeMergedTags` flag.
