### ISSUE TITLE
Add option to store config in package.json

### ISSUE THREAD

**Issue by roginfarrer** [lerna/lerna#2483]
## Expected Behavior

Instead of needing a `lerna.json` file in the root of my repo, I'd like to place the config in my package.json. Many other tools provide similar flexibility:

* [Prettier](https://prettier.io/docs/en/configuration.html)
* [Eslint](https://eslint.org/docs/user-guide/configuring)
* [lint-staged](https://github.com/okonet/lint-staged#configuration)

To name a few.

Example:

```json
// package.json
{
  "workspaces": [...],
  "scripts": { ... },
  "lerna": {
    "npmClient": "yarn",
    "useWorkspaces": true,
    "version": "independent"
  }
}
```

## Current Behavior

I have to use a separate file for the lerna configuration. It's not terrible, but ideally we could have the flexibility to reduce the number of tooling config files in our repo 😄

**Comment by dodtsair** [comment]
or maybe in the config section of package.json so that json schema validators do not get annoyed:
https://docs.npmjs.com/files/package.json#config
