### ISSUE TITLE
lerna remove chalk colors

### ISSUE THREAD

**Issue by wizardnet972** [lerna/lerna#2490]
## Expected Behavior

output with colors

## Current Behavior

no color in the output

## Steps to Reproduce (for bugs)

1. npm init -y
2. lerna init
3. npm i chalk
3. mkdir packages/package1
4. mkdir packages/package2
5. packages1/app.js
```
const chalk = require('chalk');
console.log(chalk.blue('app1'));
```
6. packages2/app.js
```
const chalk = require('chalk');
console.log(chalk.red('app2'));
```
7. package.json: "start": "node app.js",
8. run `lerna run start --stream`.

Now you will get the output without red and blue colors.

<details><summary>lerna.json</summary><p>

lerna version 3.20.2.

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.14.2 |
| `yarn --version` | VERSION |
| `node --version` | 12.13.1 |

| OS | Version |
| --- | --- |
Windows 10

**Comment by wizardnet972** [comment]
Right now require('colors') works, do I don't know if I should be close this issue

**Comment by davidsierradz** [comment]
Confirming that `colors` works out of the box with `lerna run`

**Comment by pi0** [comment]
`FORCE_COLOR=1` should also fix the problem :)
