### ISSUE TITLE
lerna ERR! lerna graphDependencies[depName].replace is not a function

### ISSUE THREAD

**Issue by Vishesh30** [lerna/lerna#2496]
I have started facing the below error in lerna bootstrap --hoist step:-

lerna ERR! lerna graphDependencies[depName].replace is not a function

Earlier this was not the case but recently i have started facing the issue.

Lerna version - 3.17.0

**Comment by Arwid** [comment]
I experienced this same issue. The root cause for me was having `"//":` in the dependency list which I expected to be reserved for comments.

https://groups.google.com/g/nodejs/c/NmL7jdeuw0M/m/yTqI05DRQrIJ?pli=1
> That's why the "//" key will never be used by npm for any purpose, and is reserved for comments.
