### ISSUE TITLE
Lerna version show all packages to upgrade even when only one package is modified

### ISSUE THREAD

**Issue by otakustay** [lerna/lerna#2497]
I have already published all my packages as `1.0.0` according to #2487, however when I simply updated one package and `git diff --names-only` confirms my modification:

```
packages/hover/package.json
packages/hover/src/__tests__/index.test.js
packages/hover/src/index.ts
```

In this case `lerna version --conventional-commits --no-push` still try to update all versions.

## Expected Behavior

Lerna should show only `@huse/hover` as updated.

## Current Behavior

All packages are ready to update:

```
lerna notice cli v3.20.2
lerna info versioning independent
lerna info Looking for changed packages since @huse/action-pending@0.9.3
lerna info ignoring diff in paths matching [
lerna info ignoring diff in paths matching   '**/*.md',
lerna info ignoring diff in paths matching   '**/example/**',
lerna info ignoring diff in paths matching   '**/__tests__/**',
lerna info ignoring diff in paths matching   '**/.eslintrc.js',
lerna info ignoring diff in paths matching   '**/tsconfig.json'
lerna info ignoring diff in paths matching ]
lerna info getChangelogConfig Successfully resolved preset "conventional-changelog-angular"

Changes:
 - @huse/action-pending: 1.0.0 => 1.0.1
 - @huse/boolean: 1.0.0 => 1.0.1
 - @huse/click-outside: 1.0.0 => 1.0.1
 - @huse/collection: 1.0.0 => 1.0.1
 - @huse/debounce: 1.0.0 => 1.0.1
 - @huse/debug: 1.0.0 => 1.0.1
 - @huse/derived-state: 1.0.0 => 1.0.1
...
```

## Possible Solution

I have no idea what was going wrong.

## Steps to Reproduce (for bugs)

1. `git clone git@github.com:ecomfe/react-hooks.git`
2. `git checkout hover-delay`
3. `yarn`
4. `lerna version --conventional-commits --no-push`

<details><summary>lerna.json</summary><p>

```json

{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "ignoreChanges": [
        "**/*.md",
        "**/example/**",
        "**/__tests__/**",
        "**/.eslintrc.js",
        "**/tsconfig.json"
      ]
    }
  }
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.13.7 |
| `yarn --version` | 1.22.0 |
| `node --version` | v13.10.1 |

| OS | Version |
| --- | --- |
| macOS Catalina | 10.15.3 |

**Comment by otakustay** [comment]
It seems `git describe` is pointing a much older version tag

```shell
git describe
@huse/action-pending@0.9.3-22-g74be940
```

But I can't figure out why this happens, an obviously newer tag exists

```shell
git show @huse/action-pending@1.0.0 | cat | head -n 4
tag @huse/action-pending@1.0.0
Tagger: otakustay <otakustay@gmail.com>
Date:   Sat Mar 14 17:52:43 2020 +0800
```

**Comment by donaldpiret** [comment]
@otakustay did you ever find a solution to this? I'm running into the exact same issue.

**Comment by otakustay** [comment]
My case is that I was doing `lerna version` in branch and created a pull request to master, also I choose "Rebase And Merge" on pull request page, actually this changed the commit id when merged to master so that a future `lerna version` can't find the latest tag in master's history, thus considering all packages to be updated.

To solve, I forced to have `lerna version` on master by adding these to `lerna.json`:

```json
{
  "command": {
    "version": {
      "allowBranch": "master",
    }
  }
}
```
