### ISSUE TITLE
npm audit error because minimist package

### ISSUE THREAD

**Issue by EdsonAlcala** [lerna/lerna#2508]
Hello, I'm getting an error in npm audit cause the minimist package

![Screenshot 2020-03-23 at 08 15 01](https://user-images.githubusercontent.com/3077635/77295808-7cc44b00-6cde-11ea-9fcc-cf4524f91d92.png)

Any idea how to fix it?

Thanks

**Comment by kommander** [comment]
`optimist` package is deprecated and not maintained anymore. `handlebars` should use minimist directly and the recent version for this matter.

**Comment by JamesHenry** [comment]
Hi @EdsonAlcala, following on from the note above, looking at this issue specifically the relevant packages have all since been patched and there are no such audit warnings when using our latest v5 packages we released since we took over.

Many thanks again!
