### ISSUE TITLE
import: might fail with Merged PRs

### ISSUE THREAD

**Issue by giuseppeg** [lerna/lerna#251]
When I try to `lerna import` [a package of mine](https://github.com/giuseppeg/suitcss-components-form)
I get the following error:

```bash
suitcss-toolkit ⎇  master $ lerna import ../components-form
Lerna v2.0.0-beta.23
About to import 11 commits into from ../components-form into packages/components-form
? Are you sure you want to import these commits onto the current branch? Yes
Import complete!
Errored while running ImportCommand.execute
Error: Command failed: git am
error: patch failed: packages/components-form/README.md:178
error: packages/components-form/README.md: patch does not apply
error: patch failed: packages/components-form/lib/form.css:21
error: packages/components-form/lib/form.css: patch does not apply

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

I am not sure why it is failing but the current `HEAD` is a merged PR so
[d7c1cf4ecb0160e339691a56895aa7993131ff90](https://github.com/giuseppeg/suitcss-components-form/commit/d7c1cf4ecb0160e339691a56895aa7993131ff90) and [a90a45ac74c3aa88edaa16a632948651a2ec1a07](https://github.com/giuseppeg/suitcss-components-form/commit/a90a45ac74c3aa88edaa16a632948651a2ec1a07) are related. Might that be the reason why it is failing? 

cc @gigabo

**Comment by gigabo** [comment]
Interesting... also not great that it says `"Import complete!"` right before failing. 😆 

Thanks for reporting, @giuseppeg!  I'll take a look!

**Comment by giuseppeg** [comment]
@gigabo that one is easy to fix :)

We may need to invoke `git am` with `--reject` or `--3way`, see:
https://git-scm.com/docs/git-apply
http://stackoverflow.com/questions/25846189/git-am-error-patch-does-not-apply

Up to you to pick one.
I'd also suggest that along with the error message we provide a link to either this issue or some docs that explain how to resolve the issue.
