### ISSUE TITLE
Error gitlab Request returned 404 Not Found on publish/version command

### ISSUE THREAD

**Issue by ruddenchaux** [lerna/lerna#2511]
The gitlab release task returns **error gitlab Request returned 404 Not Found** on publish/version command.

The repository url is in non standard form: https://domain/extra_path/repo_group/repo_name.git

The launched command is
`GL_TOKEN=token GL_API_URL=https://domain/extra_path/api/v4 lerna publish`

The log of command 
```txt
45 silly parseGitRepo
46 verbose git [ 'config', '--get', 'remote.origin.url' ]
47 silly Creating a GitLab client...
48 silly Requesting GitLab releases https://domain/extra_path/api/v4/projects/extra_path%2Frepo_group%2Frepo_name/releases
49 error gitlab Failed to create release
49 error gitlab Request returned 404 Not Found
```

Line 48 of the log shows how lerna build the url of the gitlab request: the url built is incorrect.

## Expected Behavior

I expect the release to be created in my gitlab repository successfully with the right url of the gitlab request: https://domain/extra_path/api/v4/projects/repo_group%2Frepo_name/releases

## Current Behavior

The relese on gitlab is not created and the url built by lerna for the request is https://domain/extra_path/api/v4/projects/extra_path%2Frepo_group%2Frepo_name/releases

## Possible Solution
The problem could be solved by adding a parameter in configuration that allows you to specify the id of the gittlab project

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["projects/eng-ds/*"],
  "version": "independent",
  "command": {
    "publish": {
      "conventionalCommits": true,
      "createRelease": "gitlab"
    }
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
45 silly parseGitRepo
46 verbose git [ 'config', '--get', 'remote.origin.url' ]
47 silly Creating a GitLab client...
48 silly Requesting GitLab releases https://domain/extra_path/api/v4/projects/extra_path%2Frepo_group%2Frepo_name/releases
49 error gitlab Failed to create release
49 error gitlab Request returned 404 Not Found
```
</p></details>

## Context
The error appears when trying to create a release on gitlab when the repository url does not meet the standard

## Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.14.3 |
| `node --version` | 12.13.0 |

| OS | Version |
| --- | --- |
| Linux Mint Tricia | 19.3 |

**Comment by sandrina-p** [comment]
I have the same error:

```
lerna http fetch PUT 404 https://gitlab.com/api/v4/packages/npm/@awesome-package%2fcore 303ms
lerna ERR! E404 404 Not Found
```

But if I do the normal `npm publish`, it works.

**Comment by ronangaillard** [comment]
Same here 

`lerna http fetch PUT 404 https://gitlab.com/api/v4/packages/npm/@XXXXXXXXX%2fYYYYYY 263ms`

**Comment by MatBdry** [comment]
I got the same error :/ But if you run npm publish, it works

**Comment by thomasgermain** [comment]
Same here, lerna is trying to access the `releases` endpoint by using the project name:
`https://xx.intra/api/v4/projects/xx%2Fxx%2xx/releases`
instead of using the id:
`https://xx.intra/api/v4/projects/123/releases`

Here is the doc: https://docs.gitlab.com/ee/api/releases/

**Comment by zhuanyongxigua** [comment]
I have the same error
