### ISSUE TITLE
lerna publish omit 'dist' folder 

### ISSUE THREAD

**Issue by bullettoothaxe** [lerna/lerna#2514]
I have *.gitignore* with *dist* note
My build script creates files in *dist*
In *package.json* I have note 
```
"files": [
    "dist",
    "src"
  ],
```
But on publishing by `lerna publish --conventional-commits --yes`
 lerna notice === Tarball Contents === has no dist files...

With `npm pack` _dist_ added as well

- Removing from `.gitignore` will cause pushing `dist` after publishing along with _CHANGELOG_ and _package.json_ changes
- `.npmignore` doesn't help

## Expected Behavior
*dist* should be sent to package

## Current Behavior
It doesn't

## Possible Solution
Remove *dist* from *.gitignore*

| Executable | Version |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.14.3 |
| `node --version` | 12.13.1 |

| OS | Version |
| macOS Mojave | 10.14.6 |

**Comment by bullettoothaxe** [comment]
my bad... it was an error and build didn't trigger

**Comment by dheerajk02** [comment]
> my bad... it was an error and build didn't trigger

@bullettoothaxe what was the issue here? I am facing the same issue. I am bootstrapping my source first, and then publishing. but no dist tag
