### ISSUE TITLE
--ci should be the default, both locally and on CI servers

### ISSUE THREAD

**Issue by trusktr** [lerna/lerna#2515]
Just a friendly note: packages should not be published with lock files.

This defeats the purpose of semver version ranges, because then if a dependency's dependencies are locked, ranges can not be satisfied, which breaks the workings of semver.

`npm publish` ignores package-lock.json files and will not publish them to the registry. The [docs](https://docs.npmjs.com/configuring-npm/package-lock-json.html) mention

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package.

but they don't go into much more detail.

Let me explain why packages should not rely on lock files.

Imagine that you test your package always using `npm ci` with lock files. Great, now you are certain your package works with specific versions of dependencies.

In practice, and because `package-lock.json` is _never_ published to npmjs.com, users receive versions of packages that satisfy version ranges of dependencies.

If an in-range version of some package breaks your user's experience because it breaks your package, you'll never know because you've always tested with `npm ci` and assumed the versions of dependencies would never change. If you use the regular `npm install` while developing and testing packages, you'll be able to catch breaking changes that would affect your users and be able to remedy the problem for them sooner.

Another problem is, if every single dependency of you package were to be version pinned, this would increase the chances of causing problems with dependencies that expect their export to be a singleton. As an example, the popular `react` library expects its APIs to be a singleton. When a component instance created from one version of React is passed to another version of React, it can self destruct :boom:. When versions are locked in a dependency you don't control, then it becomes difficult to manage when such issue arise (I've experienced it).

For these reasons use of lock files is not recommended for most packages.

Lock files are great for _applications_, or for _CLI programs_ which are in effect applications, but not for most packages. The generic rule is that "top most" packages may usually have lock files, but this is only a guideline and there may be exceptions. Generally speaking, the majority of packages should not use lock files.

---

Contrary to [this article](https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/), I believe instead we should all strive to test our code better and prevent in-range breaking changes. 

Greenkeeper [found](https://www.tomsquest.com/blog/2018/10/better-npm-ing/) that about 15% of in-range updates introduce breaking changes.

Now that GitHub Actions are out, it may become easier for authors to add CI and testing to their libraries. Let's strive to make the ecosystem and conventions better.

## Conclusion

As such, I believe that the behavior of `--no-ci` should be the default, because that is inline with `npm publish` functionality, and people should be testing for that use case, unless they use Lerna to manage an application and application-specific dependencies.

---

 P.S. 
I opened this issue because when I tried running `lerna bootstrap` in a CI environment for the first time, `npm ci` failed.

**Comment by intafon** [comment]
What defines the environment as being a CI environment?

I thought I had read a while back that "lerna bootstrap" always ran with "npm ci", except when using "--hoist", and I can't find good documentation that describes the exact expected behavior. This has been a source of pain since in some cases, all the sudden the tree is dirtied by a changed package-lock file resulting from running bootstrap. 

Can anyone point me the exhaustive documentation on the expected behavior?

**Comment by trusktr** [comment]
> What defines the environment as being a CI environment?

That I don't know. But I have evidence that local bootstrap is different than CI bootstrap:

- Running `lerna bootstrap` works fine locally.
- On CI, it fails with `npm ci` errors due to missing `package-lock.json` files (I do not commit those, see https://github.com/lerna/lerna/issues/2516)
- Locally, I delete `package-lock.json` files that Lerna automatically creates, and I have no issues with `lerna bootstrap` which is a hint that it is using `npm install` instead of `npm ci`, otherwise it would fail with the same error.
- To get CI to work (GitHub Actions in my case), I must run it with `lerna bootstrap --no-ci`

**Comment by intafon** [comment]
Yes, that seems to actually be the case.

`lerna bootstrap --loglevel debug` shows that npm install is used.

`export CI=true; lerna bootstrap --loglevel debug` shows that bootstrap uses npm ci when CI env variable is set (true as a value works, not sure what it should be, haven't messed with github actions).

Thanks for the tip!

Note: I confirmed, via testing and as noted in https://github.com/lerna/lerna/blob/master/doc/hoist.md, that invoking  either of `lerna bootstrap --hoist --ci --loglevel debug` or `export CI=true; lerna bootstrap --hoist --loglevel debug` does NOT use npm ci, but instead uses npm install.

**Comment by matthias-ccri** [comment]
@trusktr did you mean `--no-ci` in the title? Your post says "As such, I believe that the behavior of --no-ci should be the default".
