### ISSUE TITLE
[Feature Request] Configurable conventional-changelog

### ISSUE THREAD

**Issue by bertho-zero** [lerna/lerna#2526]
I use the `conventional-changelog-conventionalcommits` preset to generate changelogs, it is configurable and due to the following line it is not possible to configure it with lerna. 
https://github.com/lerna/lerna/blob/d4a16a59d8d7fa70be177e95e0ef05e9d0680e95/core/conventional-commits/lib/get-changelog-config.js#L26

Instead of a callback it is possible to put a config as the first parameter. Would it be possible to improve this behavior or would you have a solution for it?
I wish I could change the types displayed in changelogs.

**Comment by mcsmcs** [comment]
I assume you can update the types via the same method: https://github.com/lerna/lerna/issues/2451

**Comment by dgonzalezr** [comment]
With standard-version which also use conventional-commits preset, we're able to set configurations like:

```json
{
  "header": "# CHANGELOG\n\nAll notable changes to this project will be documented in this file.\n\nThe format is based on [Conventional Commits 1.0.0](https://www.conventionalcommits.org/en/v1.0.0/)\nand this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.html)\n\n",
  "types": [
    { "type": "feat", "section": "**Features**" },
    { "type": "fix", "section": "**Fixed**" },
    { "type": "chore", "section": "**Commits**" },
    { "type": "docs", "section": "**Commits**" },
    { "type": "refactor", "section": "**Commits**" },
    { "type": "style", "hidden": true },
    { "type": "perf", "hidden": true },
    { "type": "test", "hidden": true }
  ],
  "commitUrlFormat": "https://dev.azure.com/<company>/Design%20System/_git/design-system/commit/{{hash}}",
  "compareUrlFormat": "https://dev.azure.com/<company>/Design%20System/_git/design-system/branchCompare?_a=commits&baseVersion=GT{{previousTag}}&targetVersion=GT{{currentTag}}"
}
```

Unfortunately, `types` and `compareUrlFormat` are completely ignored within `changelogPreset` on lerna.json :-/

**Comment by bertho-zero** [comment]
@dgonzalezr I have a config like this and it seems to work:

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "allowBranch": "master",
      "message": "chore: publish"
    },
    "version": {
      "conventionalCommits": true,
      "changelogPreset": {
        "name": "conventionalcommits",
        "commitUrlFormat": "{{host}}/{{owner}}/{{repository}}/commits/{{hash}}",
        "compareUrlFormat": "{{host}}/{{owner}}/{{repository}}/branches/compare/{{currentTag}}..{{previousTag}}"
      }
    }
  }
}
```

These are the `commitUrlFormat` and `compareUrlFormat` for bitbucket.

**Comment by dgonzalezr** [comment]
> These are the `commitUrlFormat` and `compareUrlFormat` for bitbucket.

@bertho-zero for Azure DevOps the URL is slightly different, as you can see in my previous comment, I expect the URL to be defined as in the `json` config and replace only the placeholder used in there, something that actually works with standard-version.

**Comment by bertho-zero** [comment]
Is it in the `version.changelogPreset` config ? You also need a `name`.
