### ISSUE TITLE
Why does lerna symlink in CI environments?

### ISSUE THREAD

**Issue by JordanSalinas** [lerna/lerna#2529]
When I run a build in gitlab Lerna correctly detects continuous integration, however it then symlinks local dependencies. Why is that? I guess I assumed linking was for development. Since we know we're not doing development in CI environments then why symlink local packages?

Also a related thought, maybe a nice counterpart for --force-local  could be --force-external? I don't always want local dependencies when I'm developing locally. Currently symlinking requires me to run a build for components I have set up. I considered rigging up something to auto-build these on install or something, but --force-external would save me some work. And I could use it to force external dependencies in CI. Thought that may not be the best solution in that case.

Here's the gitlab output if it matters at all:
> lerna bootstrap
 lerna notice cli v3.20.2
 lerna info versioning independent
 lerna info ci enabled
 lerna info Bootstrapping 18 packages
 lerna info Installing external dependencies
 lerna info Symlinking packages and binaries
 lerna success Bootstrapped 18 packages

**Comment by artursvonda** [comment]
I think if you don't need the local packages, you don't really need lerna in CI environment. You can just do `npm install` in the package you want to test/install. That will use public versions of all dependencies.
