### ISSUE TITLE
Is lerna publish able to add only prerelase part without touching major.minor.patch ?

### ISSUE THREAD

**Issue by jacek-jablonski** [lerna/lerna#2543]
I am setting up lerna on CI/CD environment. I would like to be able to set versions in package.json by myself and lerna would only add prelease part to these versions. Is it possible?

## Expected Behavior
Version manually set in package.json: "1.0.1"
`lerna publish prepatch --someparam --preid initial`
```
Changes:
 - somepackage: 1.0.0 => 1.0.1-initial.0
```

## Current Behavior
Version manually set in package.json: "1.0.1"
`lerna publish prepatch --preid initial`
```
Changes:
 - somepackage: 1.0.1 => 1.0.2-initial.0
```
In this case version 1.0.1 is never published, it'll be skipped.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | v3.20.2 |
| `npm --version`  | 6.14.4 |
| `node --version` | v13.6.0 |

**Comment by customcommander** [comment]
Try this instead:

```shell
lerna publish prepatch --preid initial
```

Does that help?

**Comment by jacek-jablonski** [comment]
@customcommander unfortunatelly it doesn't help. I would like lerna never to bump any of major.minor.patch numbers.
