### ISSUE TITLE
Add build-metadata to lerna version / publish

### ISSUE THREAD

**Issue by jonathanmorley** [lerna/lerna#2545]
The semver standard provides for a 'build-metadata' section in the version number, which is separated from the pre-release identifers by a plus-sign (+).

The examples given are `+001`, `+20130313144700`, `+exp.sha.5114f85`.

I would like to see an argument to lerna version and publish that would apply this build metadata consistently across all packages in the repo (irrespective of independent vs fixed versioning)

This is not currently workaroundable with something like `--preid=foo+bar`, because:
1. This would create a version number like `1.0.0-foo+bar.0`, rather than `1.0.0-foo.0+bar`
2. build-metadata is valid to append to release versions (not just pre-releases)

**Comment by rrhodes** [comment]
Hey @jonathanmorley, not sure if anyone else is looking into this, but I'm looking into it in my own time to see if I can implement a solution. Hopefully have something to present in the coming week or two depending how complex this proves to be, will share an update if I have any success. :)

**Comment by rrhodes** [comment]
Quick update from me: I think I have all the code changes required to support this, just need to verify the logic with some integration tests. Hope to have something open for review either this week or early next.

**Comment by josteph** [comment]
@rrhodes hey good work on the PR!

Can you help to publish it temporarily (with fork disclaimer perhaps) so that I could have a way to test it as well?

**Comment by rrhodes** [comment]
> @rrhodes hey good work on the PR!
> 
> Can you help to publish it temporarily (with fork disclaimer perhaps) so that I could have a way to test it as well?

Hello @josteph, if you would like to test my changes for Lerna, you should be able to [run this from your machine](https://github.com/lerna/lerna/blob/main/CONTRIBUTING.md#local-cli-testing) if you pull down [my branch of work](https://github.com/rrhodes/lerna/tree/feature/2545-apply-build-metadata-to-packages). 

Hoping to have these changes reviewed soon - waiting to hear from Lerna maintainers.

**Comment by rrhodes** [comment]
[PR linked above](https://github.com/lerna/lerna/pull/2880). Although I think Lerna is no longer maintained, unless I'm mistaken? So I suspect this may not be merged into `master`.

**Comment by erictuvesson** [comment]
Ahh, missed that 👍 

> Although I think Lerna is no longer maintained, unless I'm mistaken? So I suspect this may not be merged into `master` within this repository.

It is maintained https://github.com/lerna/lerna/issues/3121

**Comment by rrhodes** [comment]
> Ahh, missed that 👍
> 
> > Although I think Lerna is no longer maintained, unless I'm mistaken? So I suspect this may not be merged into `master` within this repository.
> 
> It is maintained #3121

Ah, that's great news! Thanks for the head's up. In which case, @jeffbcross and team may be able to help here, not sure how this may fit into any considered roadmaps?
