### ISSUE TITLE
Version is not bumping 0.x packages correctly

### ISSUE THREAD

**Issue by tpluscode** [lerna/lerna#2549]
## Expected Behavior

NPM treats pre-v1 versions a little differently from standard SemVer. A breaking change should bump minor. `feat` and `fix` should both bump patch.

For example, I have a package `v0.1.3`. WIth a breaking change commit I should see

`0.1.3 => 0.2.0`

`standard-version` has been working this way for a while now.

## Current Behavior

Lerna always bumps major for braking changes

`0.1.3 => 1.0.0`

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.13.6 |
| `node --version` | v13.7.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.15.3 |

**Comment by bajtos** [comment]
FYI: I believe this has been fixed by #2486 in [v3.22.0](https://github.com/lerna/lerna/releases/tag/v3.22.0) and thus this issue can be closed as resolved now.
