### ISSUE TITLE
Can't publish with uncommitted changes when bumping "from-package"

### ISSUE THREAD

**Issue by arizonatribe** [lerna/lerna#2550]
## Expected Behavior

If I'm bumping from `patch` , for example, I can force it to publish a package even though there are uncommitted (git) changes in the repository. This is the same with any of the other bump options _except_ for `from-package`.

## Current Behavior

If you change the bump type from one of the ones supported by `version` to the ones supported by `publish`, some of the version flags are not being honored. There seems to be a bit of code commenting in the `lerna/commands/publish/index.js` indicating there is an optimistic attempt/hope that the `from-package` will work without git (but no guarantees). However I believe this one is a fairly simple fix.

## Possible Solution

I don't personally know the history and use of many of the flags, so I don't want to dictate the best solution.

But I noticed these lines in the `lerna/commands/publish/index.js`:

```javascript
    // attempting to publish a release with local changes is not allowed
    chain = chain
      .then(() => this.verifyWorkingTreeClean())
```

However in the `lerna/commands/version/index.js` the logic is a bit different:

```javascript
    // amending a commit probably means the working tree is dirty
    if (this.commitAndTag && this.gitOpts.amend !== true) {
      const { forcePublish, conventionalCommits, conventionalGraduate } = this.options;
      const checkUncommittedOnly = forcePublish || (conventionalCommits && conventionalGraduate);
      const check = checkUncommittedOnly ? checkWorkingTree.throwIfUncommitted : checkWorkingTree;
      tasks.unshift(() => check(this.execOpts));
    } else {
      this.logger.warn("version", "Skipping working tree validation, proceed at your own risk");
    }
```

My thought/suggestion is to make it so that the `throwIfUncommitted` in the `publish` command is (somewhat) similar to the logic in the `version` command. Is it possible to inspect the `options` in the `publish` command (since it honors those from `version`) and see if one of those (such as `forcePublish`) is provided before throwing that error?

## Steps to Reproduce (for bugs)

Make some local changes and then attempt to run a `lerna publish from-package --no-git-reset --no-push --no-git-tag-version --force-publish`

You can also try that same command, but change `from-package` to some other bump option (like `patch`)

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```

## Context

Noticed it today. I'm trying to create a publish script that will work in both a CI/CD environment _and_ during local development into a local registry (ie, verdaccio). The multi-package repo I'm working on has a mix of NPM packages and several APIs (all marked as `private: true`). 

Sometimes an author of one of those APIs wishes to build the associated docker container for that API, and so we can make that work by first publishing the un-published NPM packages into a local registry (using the same publish script we use for publishing to the real registry, but fed a local registry URL instead). That way they can know _before_ merging branches into develop/master that their API is going to build.

We are 99% of the way there and the only hang-up at the moment is having to force all the package publishes to be `patch` instead of relying on the way we prefer (to manually set them in the `package.json` files themselves).

To be clear though, this isn't a docker issue and I'm not looking for nor do I need any docker support or compatibility. I'm just looking for the git uncommitted changes to be able to be ignored for `from-package` as they can be for `patch` / `minor` , etc.

## Your Environment

lerna 3.20.2
node >= 11.0 < 13.0
Mac and Linux

**Comment by JamesHenry** [comment]
Given it's been the best part of a year, wanted to add my specific approach, particularly in case I am being dumb and there is a better way to achieve what I want...

What I want:

- A pipeline to just push a prerelease of the next major of my library as I collect up breaking change PRs on a release branch. No git commits or publishes.

What I tried:

```yml
- name: Publish all packages to npm to the "next" tag (no github commit or release)
  run: |
    npx lerna version premajor --loglevel=verbose --exact --force-publish --no-git-tag-version --no-push --yes
    npx lerna publish from-package --no-git-reset --dist-tag=next --yes
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

This doesn't work because, as noted above, from-package will error due to the dirty repo state caused by lerna version

**Comment by JamesHenry** [comment]
Hmm actually I think the git commit will be unavoidable in my case because otherwise lerna won't know how to keep incrementing the prerelease will it?
