### ISSUE TITLE
when run lerna version at a new branch , all packages are detected as changed and all versions are bumped

### ISSUE THREAD

**Issue by lancewuz** [lerna/lerna#2551]
## Expected Behavior
only versions of the packages changed are bumped

## Current Behavior
all versions are bumped

## Possible Solution
when pull a new branch, all files are new. the change detetion solutions fails on this situation.

## Steps to Reproduce (for bugs)
1. create a new branch
2. change a package on the new branch
3. run 'lerna version'

```json
{
  "version": "independent",
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "ignoreChanges": [
    "packages/*/dist/**",
    "**/*.test.ts",
    "**/*.e2e.ts",
    "**/test/**"
  ]
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by jonnyweb** [comment]
Have you tried using `--include-merged-tags` when running `lerna version`?

**Comment by lancewuz** [comment]
> Have you tried using `--include-merged-tags` when running `lerna version`?

this option solves my problem, thanks!
