### ISSUE TITLE
bootstrap --ci seems to not clean packages/*/node_modules

### ISSUE THREAD

**Issue by OctoD** [lerna/lerna#2552]
According to `bootstrap` command documentation:

To force it during a local install (where it is not automatically enabled), pass --ci:

```
$ lerna bootstrap --ci
```

This can be useful for "clean" re-installs, or initial installations after fresh cloning.

I would expect to reinstall all packages modules and symlinks, but it does not happen.

## Expected Behavior

It should remove all packages `node_modules` dirs

## Current Behavior

It seems to skip the `--ci` flag, performing a normal `bootstrap` command

## Steps to Reproduce (for bugs)

1. adds to the root `package.json` file a `postInstall` script `lerna bootstrap --ci`
2. run `npm ci` from root
3. re-run `npm ci` from root

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

## Context

On production server, each time I merge on master a new build occurs. Just before building libs and web-apps, we run a `npm ci` command to ensure that the `node_modules` dir is always clean

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 6.12.1 |
| `node --version` | 12.16.1 |

| OS | Version |
| --- | --- |
| freeBSD | 12.1-RELEASE-p3 |

**Comment by sd65** [comment]
Intrigued by this behaviour too :+1:
