### ISSUE TITLE
React native Invariant Violation: Module AppRegistry...

### ISSUE THREAD

**Issue by GlisboaDev** [lerna/lerna#2557]
I'm setting up a monorepo with a  typescript react native project, and have been facing an error when trying to import my shared code into my RN project.
The error is: `Invariant Violation: Module AppRegistry is not a registered callable module` and if I refresh the app it changes to `Invariant Violation: No callback found with cbID 2 and callID 1 for module <unknown>. Args: '[{"app_state":"active"}]'`
I've seen comments and issues telling people to restart the packager with `--reset-cache` or reinstall node_modules, and so on, none of those work.

If I comment out the import/usage of imported element from the other package it stops giving me the error and works fine. (packages/supplier_mob/App.tsx line `28` and `54`)

Have anyone experienced it and know how to fix it? Let me know if any questions.

## Steps to Reproduce (for bugs)
I've stripped the sensitive code and created a minimal reproducible repo  at https://github.com/GlisboaDev/learna_mr

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}

```
</p></details>

## Context
The end goal is to have an environment where I can share code between multiple react-native and reactJS projects.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.13.7 |
| `yarn --version` | 1.22.4 |
| `node --version` | v13.11.0 |

| OS | Version |
| --- | --- |
| macOS Catalina | 10.15.3 |

**Comment by acollazomayer** [comment]
@GlisboaDev Did you manage to solve this? I have the same issue

**Comment by juliopereirab** [comment]
In my case I have been able to avoid this error by running the app resetting the cache: npm start --reset-cache

**Comment by yayanartha** [comment]
I also have this issue when applied react-native-navigation

**Comment by sousadgaspar** [comment]
I'm also having the sabe issue. npm start --reset-cache did not solve.

**Comment by msmurgui** [comment]
Im also having the same issue, npm start --reset-cache couldn't solve it

**Comment by espenhogbakk** [comment]
I'm also having the same issue, `--reset-cache` did not solve it. I'm not using Lerna, just "regular" yarn workspaces. Anyone found a fix?

**Comment by newdaveespionage** [comment]
> I'm also having the same issue, `--reset-cache` did not solve it. I'm not using Lerna, just "regular" yarn workspaces. Anyone found a fix?

Same situation on my end, just using plain yarn workspaces.

This issue has popped up multiple times in trying to get a monorepo going with local dependencies for use with react native (a key use case for a monorepo.) The root cause in many cases appears to be the cross dependency including hoisted dependencies that then have a local copy installed due to `nohoist` and in my own experience seemed to cause infinite recursions of modules not being found. 

What I did find resolved the issue

- following this guide https://engineering.brigad.co/react-native-monorepos-code-sharing-f6c08172b417 
- removing all `nohoist` items
- clean out all `node_modules` (root and packages)
- `yarn` and `pod install`

What's odd is this is the best bug report I've seen for this as of yet, but it's in the Lerna repo rather than react-native or yarn 🤔

**Comment by joaoantunes87** [comment]
Hi all,

After following the article mentioned by @newdaveespionage I could solve it for a small repository I have [here](https://github.com/joaoantunes87/monorepo/pull/1). However, while trying to migrate those ideas to a bigger project I started getting the following errors:

`error: Error: Unable to resolve module `react-native/Libraries/Image/AssetRegistry` from `../../node_modules/@react-navigation/stack/src/views/assets/back-icon.png`: react-native/Libraries/Image/AssetRegistry could not be found within the project.`

Has anyone passed for this problem as well?

Thanks and Happy new year!

**Comment by impulse** [comment]
I could also resolve my issue by reading the article that @newdaveespionage linked. 

I have a monorepo that uses lerna + yarn workspaces. The error mentioned above appeared after setting up `react-navigation`. Adding the following aliases to `babel.config.js` seems to have fixed it (both android and ios).

```js
alias: {
  react: require.resolve("react", {
    paths: [path.join(__dirname, "./")],
  }),
  "^react-native$": require.resolve("react-native", {
    paths: [path.join(__dirname, "./")],
  }),
  "^react-native/(.+)": ([, name]) =>
    require.resolve(`react-native/${name}`, {
      paths: [path.join(__dirname, "./")],
    }),
  "^@react-navigation/(.+)": ([, name]) =>
    require.resolve(`@react-navigation/${name}`, {
      paths: [path.join(__dirname, "./")],
    }),
},
```

**Comment by joaoantunes87** [comment]
Thanks for the help @impulse. I had thought about that, unfortunately, keeps not working. I will keep experimenting with it.

Thanks!

**Comment by BenjaminWatts** [comment]
Hi - I am having similar issues unfortunately. Anyone made any progress at all?

**Comment by Tyerlo** [comment]
Nope, tried the things above, I'm using yarn workspaces with react-navigation.

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
