### ISSUE TITLE
Security Issue with dot-prop and yargs-parser versions used

### ISSUE THREAD

**Issue by Vishesh30** [lerna/lerna#2575]
The current version of the dot-prop npm package and yargs-parser package which is used is having security vulnerabilities and causing problems.

Below is dependency is tree for both package:-

xxxxxxx@ZZZM56584888A:~/Git/x<repo_name>$npm ls dot-prop
xxxxxx@0.1.0 /Users/xxxxxxx/Git/<repo-name>
└─┬ lerna@3.20.0
  ├─┬ @lerna/add@3.20.0
  │ └─┬ @lerna/command@3.18.5
  │   └─┬ @lerna/project@3.18.0
  │     └── dot-prop@4.2.0 
  └─┬ @lerna/version@3.20.0
    └─┬ @lerna/conventional-commits@3.18.5
      └─┬ conventional-changelog-angular@5.0.6
        └─┬ compare-func@1.3.2
          └── dot-prop@3.0.0 

xxxxxxx@ZZZM56584888A:~/Git/x<repo_name>$npm ls yargs-parser
xxxxxxx@0.1.0 /Users/xxxxxxx/Git/<repo-name
└─┬ lerna@3.20.0
  ├─┬ @lerna/cli@3.18.5
  │ └─┬ yargs@14.2.3
  │   └── yargs-parser@15.0.1 
  └─┬ @lerna/version@3.20.0
    └─┬ @lerna/conventional-commits@3.18.5
      └─┬ conventional-changelog-core@3.2.3
        └─┬ conventional-changelog-writer@4.0.11
          ├─┬ handlebars@4.7.4
          │ ├─┬ yargs@15.3.1
          │ │ └── yargs-parser@18.1.3 
          │ └── yargs-parser@18.1.3  extraneous
          └─┬ meow@5.0.0
            └── yargs-parser@10.1.0 

Can please update the version of these dependencies as these contain security vulnerability.?

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.10.1 |
| `node --version` | 10.16.0 |

| OS | Version |
| macOS Sierra | 10.12.3 |

**Comment by jimmyandrade** [comment]
+1

**Comment by JamesHenry** [comment]
Hi @Vishesh30, following on from the note above, looking at this issue specifically the relevant packages have all since been patched and there are no such audit warnings when using our latest v5 packages we released since we took over.

Many thanks again!
