### ISSUE TITLE
Is there any possibility to build lerna but not publish?

### ISSUE THREAD

**Issue by extempl** [lerna/lerna#2577]
I found package which uses lerna, and fixed some issue there. 
But until the PR is merged, I'd like to use this package from my forked repo (this is kinda blocker for me).
So, can I in any way build/compose this lerna package w/o publishing it? Just to be served as a simple package from my fork/ `build-{ver}` branch?

Checked docs first, of course, with no luck.

**Comment by chefjuanpi** [comment]
I have the same issue. I try to install an unpublished package from a lerna project direct from github.

A temporary solution is download the lerna project in your machine and use the local path for install the package in your project. 

 at the root of your project use something like that:

`yarn add 'c:/git/LERNA_PACKAGE/packages/THE_PACKAGE_YOU_NEED'`

someone know a better solution?
