### ISSUE TITLE
Security Vulnerabilities with globby, pacote and conventional-changelog-core versions

### ISSUE THREAD

**Issue by vic-nik** [lerna/lerna#2579]
The current versions of the following npm packages have security vulnerabilities. Can you please upgrade them to the latest version?
- globby (used by @lerna/create@3.18.5)
- pacote (used @lerna/add@3.20.0) 
- conventional-changelog-core (used @lerna/conventional-commits@3.18.5)

The vulnerable packages in dependecy tree are:
kind-of v. < 6.0.3
minimist v. < 0.2.1

Below are related dependency trees:

`-- lerna@3.20.2
  +-- @lerna/add@3.20.0
  | `-- @lerna/command@3.18.5
  |   `-- clone-deep@4.0.1
  |     +-- kind-of@6.0.3
  |     `-- shallow-clone@3.0.1
  |       `-- kind-of@6.0.3  deduped
  `-- @lerna/create@3.18.5
    `-- globby@9.2.0
      `-- fast-glob@2.2.7
        `-- micromatch@3.1.10
          +-- braces@2.3.2
          | +-- fill-range@4.0.0
          | | `-- is-number@3.0.0
          | |   `-- kind-of@3.2.2
          | `-- snapdragon-node@2.1.1
          |   +-- define-property@1.0.0
          |   | `-- is-descriptor@1.0.2
          |   |   +-- is-accessor-descriptor@1.0.0
          |   |   | `-- kind-of@6.0.3  deduped
          |   |   +-- is-data-descriptor@1.0.0
          |   |   | `-- kind-of@6.0.3  deduped
          |   |   `-- kind-of@6.0.3  deduped
          |   `-- snapdragon-util@3.0.1
          |     `-- kind-of@3.2.2
          +-- define-property@2.0.2
          | `-- is-descriptor@1.0.2
          |   +-- is-accessor-descriptor@1.0.0
          |   | `-- kind-of@6.0.3  deduped
          |   +-- is-data-descriptor@1.0.0
          |   | `-- kind-of@6.0.3  deduped
          |   `-- kind-of@6.0.3  deduped
          +-- extglob@2.0.4
          | `-- define-property@1.0.0
          |   `-- is-descriptor@1.0.2
          |     +-- is-accessor-descriptor@1.0.0
          |     | `-- kind-of@6.0.3  deduped
          |     +-- is-data-descriptor@1.0.0
          |     | `-- kind-of@6.0.3  deduped
          |     `-- kind-of@6.0.3  deduped
          +-- kind-of@6.0.3  deduped
          +-- nanomatch@1.2.13
          | `-- kind-of@6.0.3  deduped
          `-- snapdragon@0.8.2
            +-- base@0.11.2
            | +-- cache-base@1.0.1
            | | +-- has-value@1.0.0
            | | | `-- has-values@1.0.0
            | | |   `-- kind-of@4.0.0
            | | `-- to-object-path@0.3.0
            | |   `-- kind-of@3.2.2
            | +-- class-utils@0.3.6
            | | `-- static-extend@0.1.2
            | |   `-- object-copy@0.1.0
            | |     `-- kind-of@3.2.2
            | `-- define-property@1.0.0
            |   `-- is-descriptor@1.0.2
            |     +-- is-accessor-descriptor@1.0.0
            |     | `-- kind-of@6.0.3  deduped
            |     +-- is-data-descriptor@1.0.0
            |     | `-- kind-of@6.0.3  deduped
            |     `-- kind-of@6.0.3  deduped
            `-- define-property@0.2.5
              `-- is-descriptor@0.1.6
                +-- is-accessor-descriptor@0.1.6
                | `-- kind-of@3.2.2
                +-- is-data-descriptor@0.1.4
                | `-- kind-of@3.2.2
                `-- kind-of@5.1.0

`-- lerna@3.20.2
  +-- @lerna/add@3.20.0
  | `-- @evocateur/pacote@9.6.5
  |   `-- mkdirp@0.5.1
  |     `-- minimist@0.0.8
  +-- @lerna/create@3.18.5
  | `-- @lerna/child-process@3.16.5
  |   `-- strong-log-transformer@2.1.0
  |     `-- minimist@1.2.0
  `-- @lerna/version@3.20.2
    `-- @lerna/conventional-commits@3.18.5
      +-- conventional-changelog-core@3.2.3
      | +-- conventional-changelog-writer@4.0.11
      | | `-- handlebars@4.7.2
      | |   `-- optimist@0.6.1
      | |     `-- minimist@0.0.8  deduped
      | +-- get-pkg-repo@1.4.0
      | | `-- meow@3.7.0
      | |   `-- minimist@1.2.0
      | +-- git-raw-commits@2.0.0
      | | `-- meow@4.0.1
      | |   `-- minimist@1.2.0
      | `-- git-semver-tags@2.0.3
      |   `-- meow@4.0.1
      |     `-- minimist@1.2.0
      `-- conventional-recommended-bump@5.0.1
        `-- meow@4.0.1
          `-- minimist@1.2.0

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.10.1 |
| `node --version` | 10.16.0 |

| OS | Version |
| --- | --- |
| Windows 10 | 1607 |

**Comment by kibertoad** [comment]
Most likely the problem with updating `conventional-changelog-core` is that latest major version is Node 10+, while Lerna is Node 8+. So this would require a major version bump from Lerna side, although since Node 8 is deprecated already, that doesn't sound like a big deal.

**Comment by musbaig** [comment]
Any updates on when this issue might get resolved? We'd like to use lerna for our current project, but, Nexus is flagging and quarantining lerna. We tried going a few minor and at least one major version back, but, to no avail.
