### ISSUE TITLE
Moving dependencies to root

### ISSUE THREAD

**Issue by davidstellini** [lerna/lerna#2580]
Hi,

I'm trying to understand how to move dependencies - not dev dependencies - of a package to root.
Breaking it down, if I have:
packages/package-a -> depends on -> some-external-npm-package

What command do I need to run so that some-external-npm-package is a `dependency` in the root package.json?

What I tried:

`lerna bootstrap`
`lerna bootstrap --hoist`
`lerna link convert` 

`lerna link convert`, as per docs, seems to move only dev dependencies to the root package.json (why only dev dependencies?).

The only thing that seems to work is:
`lerna exec npm install `
to automatically run npm install for all packages. But in that case I have to ask - is this a normal or intentional workflow? It feels like I'm doing something wrong.

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
