### ISSUE TITLE
extract version number from publish to use in CI

### ISSUE THREAD

**Issue by jrwpatterson** [lerna/lerna#2581]
Hi All,

I'm wondering if there is a way that I've missed from the Doco to get the version number from somewhere. I am using Circle CI with it publishing as a patch for master builds and publishing as a canary for feature branch builds. 

I am hoping to create a slack integration to let the developer know the package id that was just released, (especially with the SHA from canary publishes) 

But I need to get the build number out of the system, for that

**Comment by bmuenzenmeyer** [comment]
Cicle CI likely has env vars set for things like the PR number
