### ISSUE TITLE
Move gitHead away from package.json

### ISSUE THREAD

**Issue by vlopp** [lerna/lerna#2586]
**Lerna 3.20.2**

Currently, Lerna adds the `gitHead` field to package.json's of all subpackages.
Since I'm using Docker, this change (which happens every publish) invalidates Docker's caching, and I'm forced to rebuild all of the containers (including - most notably - downloading all dependencies), even if they did not change at all.

Is there something I can do to make Lerna store gitHead somewhere else?

**Comment by evocateur** [comment]
`gitHead` is added by `npm publish` before packing up the tarball. Lerna provides the field as compatibility.

Lerna is not a Docker tool, it manages the publishing of npm packages.
