### ISSUE TITLE
[Feature] Syncing external dependencies across packages

### ISSUE THREAD

**Issue by christophercliff** [lerna/lerna#259]
Suppose all of my packages depend on Lodash. Does Lerna provide a mechanism for ensuring the same version of Lodash is used in every package?

**Comment by thejameskyle** [comment]
You mean making sure that `package-a` and `package-b` both depend on the same semver range of `lodash` (i.e. `"^1.0.0" === "^1.0.0"`)?

**Comment by christophercliff** [comment]
Yes.

**Comment by thejameskyle** [comment]
Hmm... if there is enough utility in it. I feel like `lerna exec -- npm outdated` would be what most people actually wanted

**Comment by rygine** [comment]
@christophercliff PR #237 does exactly this

it scans your packages and finds common external dependencies, which it then installs at the root node_modules folder. node will walk the directory tree and find the modules it needs there for your packages. this can potentially cause other issues though.

**Comment by christophercliff** [comment]
@thejameskyle thanks, that's useful.

Suppose my dependency is deliberately out of date--where I can't update it or haven't gotten around to it yet--but I want to make sure it's consistent across packages. It would be useful to have a command with output like:

```
$ lerna version lodash

package-a/
  lodash@1.0.0
package-b/
  lodash@2.0.0
```

**Comment by gigabo** [comment]
We have a `pin-dependency` command in our internal lerna-like tool at Redfin that's invaluable for managing external dependencies.

How about something like this?

```bash
$ lerna pin lodash@^1.0.0
```

**Comment by christophercliff** [comment]
For just listing versions, `lerna exec -- npm view lodash version` does the trick.

Might be nice if `lerna exec` output each package name before running the command.

**Comment by zouxuoz** [comment]
@thejameskyle what status for this feature? Can I try do it and send PR? :)

**Comment by flux627** [comment]
Just here to add a 👍 for the `pin` command.

**Comment by evocateur** [comment]
I have stubs for `lerna upgrade` and `lerna remove` in master right now (complementing the existing `lerna add`), I'm just trying to find time to implement them (as well as a graceful `lerna outdated`).
