### ISSUE TITLE
Topographical sort should respect local tarballs

### ISSUE THREAD

**Issue by JacobLey** [lerna/lerna#2592]
Hello, I've started using Lerna and want to maintain all my packages locally.

That is to say I want to `npm pack` each package into a tarball, and add that tarball as a dependency in another package.
The packing I am handling manually, although some existing issues appear to address that https://github.com/lerna/lerna/issues/2134

An example simple repo:
```
.
├── lerna.json
├── package.json
├── packages
│   ├── bar
│   │   ├── package.json
│   └── foo
│       ├── package.json
│       └── my-scope-foo-1.0.0.tgz
```

`packages/bar/package.json` will look something like:
```
{
  "name": "@my-scope/bar",
  "dependencies": {
    "@my-scope/foo": "file:../foo/my-scope-foo-1.0.0.tgz"
  }
}
```

## Expected Behavior
`lerna ls --toposort` should print:
> @my-scope/foo v1.0.0 packages/foo
> @my-scope/bar v1.0.0 packages/bar
> lerna success found 2 packages

Note that foo comes before bar (despite coming second in the default alphabetical sort).
That is because foo is acknowledged as a dependency of bar.

## Current Behavior
`lerna ls --toposort` should print:
> @my-scope/bar v1.0.0 packages/bar
> @my-scope/foo v1.0.0 packages/foo
> lerna success found 2 packages

Lerna displays bar before foo. This behavior impacts scripts such as `lerna run` and `lerna exec` which might be dependent on topographical sort.

If the dependency is changed to 
```
"@my-scope/foo": "file:../foo
```
order is correct (although that logically produces a different dependency with links)

## Possible Solution
https://github.com/lerna/lerna/pull/2593
check if the local file is a tarball that would have been generated by that package. If so, acknowledge it as a local dependency.

I don't suspect this logical change would be backwards incompatible for most users (i.e. that means someone is using tarball and explicitly _not_ respecting order), but if it were, could adjust the `lerna.json` to include some `allowLocalTarballs: true` argument.

## Context
As noted in the intro, I want to locally pack and install dependencies.

"Alternatives" I don't want to do:
* npm link (lernas default for local dependencies)
    * There is some weirdness with accessing and de-duping sub-dependencies, and acknowledging `.npmignore`.
* publish packages
    * repository is private, can't use public npm
    * Don't want to pay for private npm or self-host the registry.

In a non-monorepo world I've handled these private dependencies by pushing packages to github and use git-based dependencies, but individual git pushes/installations seems hacky at best for a monorepo.

I wouldn't quite classify this as a bug because it seems like _currently_ intentional behavior, but it is an improvement that supports local-only monorepos using existing npm install-from-tarball functionality.

What is even most misleading is when running `lerna ls --graph` will result in:
```
{
  "@my-scope/bar": [
    "@my-scope/foo"
  ],
  "@my-scope/foo": [ ... ]
}
```
Which at first glance does seem to acknowledge the local dependency of bar -> foo.

I intend to open a PR with a suggested fix, but am opening this issue to allow non-implementation-specific discussion about this feature

**Comment by evocateur** [comment]
Why isn't a relative `file:` specifier that points to the sibling directory itself sufficient? It's what Lerna itself does, seems to work just fine (and doesn't require publishing to any registry).

```patch
{
  "name": "@my-scope/bar",
  "dependencies": {
-    "@my-scope/foo": "file:../foo/my-scope-foo-1.0.0.tgz"
+    "@my-scope/foo": "file:../foo"
  }
}
```

As long as your root manifest has relative `file:` specifiers configured correctly (`npm i ./packages/*` or `npx lerna link convert`), it "just works" with npm v6.

**Comment by JacobLey** [comment]
Thanks for the tip I wasn't familiar with `lerna link convert` so I messed around with that a bit now...

I had a couple install problems, but I think that is node's fault and not lerna's. (A lot of various `no such file or directory, rename '<root>/node_modules/.staging/fsevents-826f5674' -> '<root>/packages/<my-package>/node_modules/fsevents'`)

Once I got passed those, it appears it is still the same issue I have with `npm link`, except now all the packages are stored in the root.

I agree this solution works well in a lot of cases, especially ones like lerna itself where the root module is the one being packaged and imported elsewhere.

I can go into a bit more depth of why I don't want to use `npm link` (or wrappers around that functionality).
* Creates a symbolic link to the package, rather than packing/unpacking into individual node_modules
    * Lack of a pack->install step means scripts like `pre/postpack` or `pre/postinstall` are never executed.
    * `.npmignore` is irrelevant. _Every_ file from the directory is included, in my cases examples of unwanted files are: entire `/tests`, `/coverage` and `/.nyc_output` directories, `tsconfig.json`, `.mocharc.js`, and ironically the `.npmignore` itself.
* Packages are not "self-contained". I intend to dockerize many of my packages, ideally with a single docker image per packages (one Dockerfile per package).
    * Docker [best practice](https://nodejs.org/fr/docs/guides/nodejs-docker-webapp/) is to perform install within Dockerfile. Going back to symbolic links, that means the dependency packages must already be installed, and `.npmignore` can't ignore useless files (unnecessary image bloat).
* Accessing a sub-dependency does not work with linked packages.
    * Using the *foo*/*bar* example above (*bar* is dependent on *foo*), lets say *foo* has a dependency on common packages I want available everywhere (for example [express](https://expressjs.com/) or [mocha](https://mochajs.org/).
    * In a "traditionally packed" environment, running `require('express')` in *bar* will work, because all of *foo*'s dependencies are available in *bar*'s node_modules
    * This makes *foo* a single source of truth for all my common modules + versions.
    * _Arguably_ this is an anti-pattern and it is better to use `peerDependencies`, but the perks of a monorepo is I _can_ have a single source of truth that automatically propagates everywhere.
    * Despite anti-pattern arguments, this is a definite behavior change between dependency on a registry package/tarball vs locally linked directory, and goes against my goal of removing excess bloat files and de-duping packages.

Admittedly I might be over-complicating (and over-justifying) my use case, but the main point of this issue is to ensure file dependencies are treated as "local dependencies" even if they do not match the currently expected link format. e.g. a "local dependency" should be agnostic to how it is actually installed.

It also means I am now responsible for all the packing itself, but `lerna exec -- npm pack` mostly handles that for me. (Actually its a bit more complicated than that, but I feel like I've rambled off topic enough, happy to share more if relevant)
