### ISSUE TITLE
lerna bootstrap yarn install v1.22.4 stuck

### ISSUE THREAD

**Issue by wangdanting** [lerna/lerna#2596]
lerna bootstrap yarn install v1.22.4 stuck

## Expected Behavior

'lerna bootstrap' Execution stuck

## Current Behavior

![image](https://user-images.githubusercontent.com/16220538/82806896-52973100-9eb9-11ea-9ee2-fb58681fae4d.png)
Execution stuck
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.14.4 |
| `yarn --version` | 1.22.4 |
| `node --version` | v12.16.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by Moudicat** [comment]
It may be a problem caused by mutex server in yarn

try `ping localhost`  It should resolve to 127.0.0.1

or try mutex/file 

`lerna.json` 
```json
{
 ...
  "command": {
    "bootstrap": {
      "mutex": "file",
    }
  },
}
```
