### ISSUE TITLE
`changed` command lists all packages even though there nothing to `publish`

### ISSUE THREAD

**Issue by YuriGal** [lerna/lerna#2599]
Lerna says "assuming all packages changed" on `changed` command even though there's no changes since packages were published (`publish from-package` says there's nothing to publish). 
```
 ./.bin/lerna changed
lerna notice cli v3.20.2
lerna info versioning independent
lerna info Assuming all packages changed
@acl-services/cors-middleware
@acl-services/fastify-adapter
@acl-services/parameters
@acl-services/jwt-client
@acl-services/jwt-middleware
@acl-services/node-vendorer
@acl-services/typescript-conventions
lerna success found 7 packages ready to publish
✨  Done in 0.64s.

./.bin/lerna publish from-package
lerna notice cli v3.20.2
lerna info versioning independent
lerna notice from-package No unpublished release found
lerna success No changed packages to publish 
✨  Done in 2.13s.
```

## Expected Behavior
`lerna changed` should only list packages changed since last publish

## Current Behavior
`lerna changed` lists all packages, including unchanged

## Steps to Reproduce (for bugs)
1. Clone a repo with already published packages to local machine
2. Install dependencies
3. Run `lerna changed`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "command": {
    "publish": {
      "registry": "https://npm.pkg.github.com/"
    }
  },
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent"
}
```
</p></details>

## Context
Need to loop only thru changed packages to perform some manipulations on them. Hence `lerna changed` is needed.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.17.3 |
| `node --version` | v10.15.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Catalina | 10.15.4 |

**Comment by YuriGal** [comment]
I ended up using `lerna ls --since master` instead. Since all PRs in our case are done from other branches into master, comparing working branch to master seems to make sense.

**Comment by rayallen001** [comment]
Possibly you have executed `git tag xxx` without `-m` parameter. If you execute `git tag` yourself instead of using `lerna version` or `lerna publish`, you should add `-m` parameter to make the tag annotated. Ref: https://github.com/lerna/lerna/issues/1357#issuecomment-438162152

**Comment by eonae** [comment]
It will behave like this where `--force-publish`
