### ISSUE TITLE
Lerna should ignore peer/dev dependencies of symlinked packages. 

### ISSUE THREAD

**Issue by dwjohnston** [lerna/lerna#2605]
Repro for this here:  https://github.com/dwjohnston/lerna-react-monorepo

## Expected Behavior

If a have package a with: 

```
  "devDependencies"
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }, 
  "peerDependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }

```

and package-b depends on package a: 

```
  "dependencies" : {
      "package-a": "..."
  }

```

Then I don't want package-b to have access to the `react` and `react-dom` modules in package-a's node_modules. 

## Current Behavior

package-b, when importing the code from package-a, will resolve `react` to the `react` module in package-a's node-modules. 

This causes this common error: https://github.com/facebook/react/issues/14257#issuecomment-508808246

The work around to this, is to hoist all dev dependencies (ie. `lerna link convert` ). Where this would potentially be problematic is if you had different versions of a dev dep in different packages and so it wouldn't be hoisted. 

Alternative solution is to use webpack aliasing. 

## Possible Solution

 Either by default, or provide a 'don't symlink peer dependencies' option. 

Surely this is fairly feasible - at the symlink step, first check any for any peer dependencies, and don't symlink those. 

This does sound like though - that you would not be symlinking the whole folder and instead be symlinking individual folders in the node_modules folder. Which I think this issue is suggesting: 
https://github.com/lerna/lerna/issues/1321

Is it possible to exclude folders from a symlink?

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

 Trying to create a basic react monorepo where you have

 ```
    packages/
       app1/
       app2/
       common-react-components/
```

And you run into this 'two different versions of react' issue. 

## Your Environment

See repro - Have been trying with both npm and yarn. 

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by heygrady** [comment]
We are fighting similar issues on our app. It is common in react packages to have singleton context objects, which breaks when the package is resolved to multiple places in the filesystem. In particular, `react-router` is very sensitive to this. Any package that dealt with react context singletons might be caught in the trap.

Two sibling workspace packages cannot share certain singleton-reliant dependencies during development mode, and may have problems during final build if you are using webpack.

We landed on moving those "there shall be only one" deps out of the app (there were only a few that affected dev) to the repo-level `package.json`, which at least helped ensure that we were always getting the same one.

There does not seem to be a workspace setting for "please, oh please, ensure that only one copy of this package exits in the entire repo".

That feature is desirable for local development or for bundling an app to be deployed. Currently there is no way (AFAIK) to ensure only one single copy of a dependency is installed; even with the same version number in every workspace package.

Ultimately this feels like a missing yarn workspaces feature.

```json
// obviously dreaming; in the repo-level package.json
{
  // conceptually similar to defining a "resolutions" in every workspace package
  // would install these in the repo-level node_modules folder _only_
  "singletonDependencies": {
    "react": "*", 
    "react-dom": "*",
    "react-router": "*",
  }
}

**Comment by Xilis** [comment]
Facing similar issues: a lerna monorepo that includes a nextjs frontend app - `frontend`, a nodejs backend app - `backend`, and a shared components package - `components` (for other todo frontend apps).

The `components` package includes `react` and `react-dom` as peer/devDependencies, not prod dependencies. Bootstraping the monorepo symlinks `./packages/components` to `./packages/frontend/node_modules`. When the `import * as react from 'react';` is executed (inside `components`), the "multiple instances of react" is triggered, as it gets resolved into `./packages/components/node_modules/react`, and not into `./packages/frontend/node_modules/react`.


I have another "question" or something I'd like to confirm; if my understanding around lerna is correct based on comments from the maintainer in other github issues, lerna (at least the bootstraping part) should practically not be used in CI steps, thus the "shared packages" should be published either way for production (in which case the "multiple instances of react" would not happen as there would only be a single `react` dependency.

In the example above, we would dockerize the frontend and backend seperately, and seperate the dockerization into multiple stages / intermediate images (so in one step/image install devDependencies and build/compile the package, in another step install only production dependencies and copy over the compiled code from the previous step). Publishing the `components` package makes this straight forward, I'm just wondering if there is some "best practice" usage that uses lerna and does not require publishing.

**Comment by TonyApuzzo** [comment]
I have a similar but seemingly different issue with peer dependencies.  I've been thinking that the way to solve my issue would be for either lerna or maybe yarn workspaces to do a peer/optional dependency resolution as a pre-install step.

The idea would be that when installing to traverse the dependency graph and collect a list of all referenced peer and optional dependencies, then traverse the dependency graph again and note all external dependencies that WILL BE installed later that match higher-level peer/optional dependencies.  Anything matching should be pre installed so that the higher level dependencies will see those modules already.

So would the algorithm I jankily outlined above solve the OP's issue?  If so it seems like it could be a generic solution for these peer/optional resolutions.

**Comment by dwjohnston** [comment]
Ok, so I'll note that yarn 2 does seem to solve this issue. 

See the branch here: 

https://github.com/whispir/yarn2-example/tree/demo/4b-singleton-deps

Note that here, I have in my `shared-react`: 

```
  "devDependencies": {
    "@types/react": "^17.0.20",
    "react": "17.0.1",
    "typescript": "^4.4.2"
  },
  "peerDependencies": {
    "react": "^17.0.1"
  },

```

and in app1 

```
  "dependencies": {
    "react": "17.0.2",
    "react-dom": "17.0.2",
  },

```

(I've intentionally used non-caret versioning to force two versions React to appear). 

In this case yarn2 will use 17.0.2 - which is what we want.

**Comment by lee1409** [comment]
Any workaround for this issue?

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
