### ISSUE TITLE
Question: How do I run npm scripts that reference binaries from the root package?

### ISSUE THREAD

**Issue by aeisenberg** [lerna/lerna#2608]
I am hoping to keep all shared `devDependencies` in the root package to avoid duplication, but this prevents us from running npm scripts directly from the sub-packages. Here's a concrete example:

Each sub-package defines scripts like this:

```
  "scripts": {
    ...
    "check": "gts check"
    ...
  }
```

Our root package is the only package that declares a dependency to `gts`:

```
  "packages": {
    ...
    "gts": "^1.1.2",
    ...
  }
```

I can run this with no problem:

```
$ lerna run check
<SUCCESS!>
```

However, we cannot run this from a sub-package (the reason we want to do this is to speed up the running of the scripts, especially when most devs only focus on one of the sub-packages at a time):

``` 
$ npm run check
sh: gts: command not found
npm ERR! code ELIFECYCLE
...
```

This makes sense since gts is not in the sub-package's `node_modules/.bin` folder. I could fix the problem if I change the scripts in each sub-package to something like this:

```
  "scripts": {
    ...
    "check": "PATH=$PATH:../../node_modules/.bin && gts check"
    ...
  }
```

but, this isn't ideal. For one thing, it does not work on Windows. Another possibility would be to explicitly push all devDependencies down to the sub-packages and _nohoist_ them all. This is not ideal either since we are now duplicating a lot of our packages.

Is there a better solution that doesn't involve package duplication or explicitly adding paths to each of our scripts?

**Comment by dcheung2** [comment]
Using relative path to the cli without change path should work for you

```
"scripts": {
...
"check": "../../node_modules/.bin/gts check"
...
}

```

I don't see a prefect way to do it.
Even if lerna add some cli to resolve the path,   the sub-projects doesn't even know lerna unless you install it as a global tool in your PATH.


another workaround would be,
use a shell with the PATH environment variable to the root node_modules/.bin  before start working of the day.

which could cause another problem if you work on multiple projects.

**Comment by aeisenberg** [comment]
Unfortunately, using a relative path won't work because gts expects tsc and tslint to be on the path as well. This will work fine if you have tsc and tslint globally installed, but we don't on our CI servers (and it just hides the bigger problem). 

Thanks for your help, though. I'll keep looking for a good solution and will post here if I find one.

**Comment by faeron** [comment]
We have/had the same issue, but settled with using the ``--scope`` flag to run scripts only for some packages e.g. ``npx lerna --scope "my-package-name" test``

**Comment by aeisenberg** [comment]
I am no longer using Lerma. Feel free to close.
