### ISSUE TITLE
Install error with lerna and yarn workspace

### ISSUE THREAD

**Issue by ali-master** [lerna/lerna#2614]
I implemented Lerna and yarn workspaces in my project
## Expected Behavior

My local packages and dependencies should be installed as well.
## Current Behavior

When I gonna install packages, it says 
```txt
error Couldn't find package "@kratos/core@^1.0.1" required by "@kratos/storybook@1.0.1" on the "npm" registry.
```
Whereas these ```@kratos/core``` and ```@kratos/storybook``` packages exist in the packages folder and they are local packages.

I tried these commands but facing the below error:

- lerna add @kratos/core --scope @kratos/renderer: 
- lerna add @kratos/core packages/renderer
```txt
lerna notice cli v3.22.0
lerna info versioning independent
lerna notice filter including "@kratos/renderer"
lerna info filter [ '@kratos/renderer' ]
lerna WARN No packages found where @kratos/core can be added. 
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
	"useWorkspaces": true,
	"packages": ["packages/*"],
	"command": {
		"publish": {
			"ignoreChanges": [
				"test/**/*",
				"*.test.*",
				"*.spec.*",
				"cypress",
				"*.md",
				"scripts",
				"lib",
				"tslint.json",
				"tsconfig.json"
			]
		},
		"run": {
			"npmClient": "yarn"
		}
	}
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.0 |
| `npm --version`  | 6.14.4 |
| `yarn --version` | 1.22.4 |
| `node --version` | 12.18.0 |

| OS     | Version |
| ------ | ------- |
| Ubuntu | 18      |

 Thanks, Lerna for having a lot of problems without useful documentation.

**Comment by Tallyb** [comment]
In most cases, this is because it is already in the destination package.json
