### ISSUE TITLE
Is there a way to push tags to Github one by one

### ISSUE THREAD

**Issue by ludohenin** [lerna/lerna#2616]
I realized that Github is not sending webhook event when pushing more than [3 tags at once](https://developer.github.com/webhooks/event-payloads/#push). I really need to catch those events to trigger some build stuffs.

I'm then wondering if there's a way to instruct Lerna to push tags one by one to Github ?

If not, what would you suggest me to do ?

Note that (to keep things simple) I only run `lerna publish` cmd

EDIT:

I've tried with `concurrency` set to 1 in `version` command options but having the same result.

**Comment by mikob** [comment]
related to #2218

**Comment by JamesHenry** [comment]
Closing in favour of #2218
