### ISSUE TITLE
Lerna publish dosen't finish process (it stops in lerna info execute Skipping releases)

### ISSUE THREAD

**Issue by avallonazevedo** [lerna/lerna#2621]
Lerna publish does not finish proccess

## Expected Behavior
When running `lerna publish`, we should publish the packages, but the process is always stuck in `lerna info execute Skipping releases`.

## Current Behavior
The process is stopped in `lerna info execute Skipping releases`, it never moves on to the other steps. The same is true with the `lerna version`. There seems to be some problem with commitlint / commitzen.

When run `lerna publish`,  console return is:

```
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Assuming all packages changed
Select a new version ()...

? Are you sure you want to create these versions? Yes
lerna info execute Skipping releases
```

And nothing else happens.

## Steps to Reproduce (for bugs)
1. lerna publish
2. not happens

**lerna.json**

```
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "conventionalCommits": true,
      "registry": "private-nexus-registry-link"
    }
  }
}

```

```
40 error Error: Command failed: git commit -F /tmp/c557c2aa-0b11-4e47-815a-5c7b26c6aaff/lerna-commit.txt
40 error husky > pre-commit (node v10.18.1)
40 error ℹ No staged files match any configured task.
40 error husky > prepare-commit-msg (node v10.18.1)
40 error cz-cli@4.1.2, cz-conventional-changelog@3.2.0
40 error
40 error ? Select the type of change that you're committing: (Use arrow keys)
40 error ❯ feat:     A new feature
40 error   fix:      A bug fix
40 error   docs:     Documentation only changes
40 error   style:    Changes that do not affect the meaning of the code (white-space, for
40 error matting, missing semi-colons, etc)
40 error   refactor: A code change that neither fixes a bug nor adds a feature
40 error   perf:     A code change that improves performance
40 error (Move up and down to reveal more choices)[41D[41Chusky > commit-msg (node v10.18.1)
40 error ⧗   input: Publish
40 error
40 error  - @bexs/dollar-hooks@1.0.1
40 error  - @bexs/dollar-icons@1.0.1
40 error  - @bexs/dollar-tokens@1.0.1
40 error  - @bexs/dollar@1.0.1
40 error ✖   subject may not be empty [subject-empty]
40 error ✖   type may not be empty [type-empty]
40 error
40 error ✖   found 2 problems, 0 warnings
40 error ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
40 error
40 error husky > commit-msg hook failed (add --no-verify to bypass)
40 error error Command failed with exit code 1.
40 error
40 error     at makeError (/home/avallonazevedo/apps/bexs-projects/go/src/bexs-ui-kit/node_modules/execa/index.js:174:9)
40 error     at Promise.all.then.arr (/home/avallonazevedo/apps/bexs-projects/go/src/bexs-ui-kit/node_modules/execa/index.js:278:16)
```

The commitlint and the commitzen are working normally, but this still appears in lerna-debug.

## Context
I can't publish any of my packages.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `npm --version`  | 6.13.4 |
| `yarn --version` | 1.22.4 |
| `node --version` | 10.18.1 |

| OS | Version |
| --- | --- |
| Ubuntu | 18.04 |

**Comment by HanamDo-TF** [comment]
Sorry to bring this back up @avallonazevedo.  Did you find out what happened here? I'm also stuck as well.

**Comment by avallonazevedo** [comment]
> Sorry to bring this back up @avallonazevedo. Did you find out what happened here? I'm also stuck as well.

Hello @HanamDo-TF,

In my case, the problem was caused by an incorrect configuration in the **commitlint** release message.

My message was configured like this: chore: `@bexs/dollar release`.

The end of the sentence was not allowed, so I removed it and everything went back to working.

Try to check your release message. I hope this helps you.
