### ISSUE TITLE
Splitting / Parallelism support via filter flags

### ISSUE THREAD

**Issue by buschtoens** [lerna/lerna#2632]
Many CI services offer split job execution on multiple runners in parallel. For instance, [CircleCI calls this feature "parallelism"](https://circleci.com/docs/2.0/parallelism-faster-jobs/#using-environment-variables-to-split-tests).

You could configure your build job with `parallelism: 3`, which would spawn 3 runners in total, each with these environment variables:

1. `CIRCLE_NODE_TOTAL=3`, `CIRCLE_NODE_INDEX=0`
2. `CIRCLE_NODE_TOTAL=3`, `CIRCLE_NODE_INDEX=1`
3. `CIRCLE_NODE_TOTAL=3`, `CIRCLE_NODE_INDEX=2`

It would be awesome, if `lerna` could natively support deterministic splitting on the filter flags level, to make commands like `lerna run` "just work". 

For instance, with command flags inspired from [`ember-exam`](https://github.com/ember-cli/ember-exam#splitting):

```bash
$ yarn lerna run \
  --stream \
  --concurrency 1 \
  --split $CIRCLE_NODE_TOTAL
  --partition $CIRCLE_NODE_INDEX
  test
```

Would you be open to a pull request implementing that feature?

---

**Edit:** I published [`lerna-parallelism`](https://github.com/ClarkSource/lerna-parallelism), which does exactly that.

**Comment by buschtoens** [comment]
Related StackOverflow question someone asked on May 12th: https://stackoverflow.com/questions/61759348/is-there-a-way-to-split-my-tests-and-have-them-run-parallel-in-my-lerna-monorepo

**Comment by buschtoens** [comment]
Hmm, looking at the implementation of e.g. `lerna run`, which does some further filtering _after_ `getFilteredPackages`, it may make sense to add splitting as an extra stage after that still, instead of making it part of `getFilteredPackages`.

https://github.com/lerna/lerna/blob/f6e7a13e60fefc523d701efddfcf0ed41a77749b/commands/run/index.js#L42-L48

**Comment by davidgtu** [comment]
Hey, thanks! I was the person who wrote that question on StackOverflow and I'm glad someone else ran into this. I was wondering if this _could_ be achieved but I suppose Lerna doesn't quite support parallelism yet. 

While Lerna's a great tool, it does tend to eat up a lot of memory when running it in CircleCI with medium resources (about 2GB) which will lead to **error 137: Out of memory.**

That said, I would love a feature like this!

**Comment by buschtoens** [comment]
We extended `lerna run` for our internal projects at @ClarkSource to accept `--split` & `--partition` as described in the OP. It works great! 🚀 

I should be able to get permission to either open-source this, or even better yet upstream this feature back into `lerna` core, if the project maintainers would like that. 😊

**Comment by buschtoens** [comment]
Yeah, so I got permission to open-source our solution. If the maintainers would like a PR, I could start one. Otherwise I'd just publish this as is, effectively depending on and extending `lerna run`.

**Comment by davidgtu** [comment]
@buschtoens if you don’t mind, could you point to your open source solution? I’d be interested in taking a cursory glance!

**Comment by buschtoens** [comment]
Here you go: https://github.com/ClarkSource/lerna-parallelism

**Comment by davidgtu** [comment]
> Here you go: https://github.com/ClarkSource/lerna-parallelism

It's still private 😛

**Comment by buschtoens** [comment]
🤦 omg, I didn't notice. Sorry, it's published now. 😅
