### ISSUE TITLE
[request] tweak publish lifecycle scripts

### ISSUE THREAD

**Issue by bluelovers** [lerna/lerna#2635]
## Expected Behavior

allow add update files during prepublishOnly ( build file, add commit, update package json ... etc )

1. publish
2. update package.json version and githead, ~~changelog~~
3. prepublishOnly
3.5 reload git commit changes, package json changes, update githead, changelog
4. ... others
4.5 allow run root `postpublish` after git push

## Current Behavior

1. publish
2. update package.json version and githead, changelog
3. prepublishOnly
4. ... others

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by matheo** [comment]
Hi @bluelovers 
Have you ran the `publish` process with `--loglevel silly`?
I'm sure you can see where to hook into the process with the verbose output.

I saw that the process is quite robust already
check the lerna output of the script executed and you will know which script to implement.

**Comment by bluelovers** [comment]
update package.json during  `prepublishOnly` will ignore by lerna

**Comment by matheo** [comment]
I was able to override the version changes by lerna in the `version` hook
and you can add stuff to the git commit there too

**Comment by bluelovers** [comment]
when error during publish

next time re-publish will lost publish some package
because lerna already update git tag, it make some package can't be re-publish

**Comment by matheo** [comment]
@bluelovers you might delete the git tags from your repo manually
and then retry the publish process ;)
