### ISSUE TITLE
[Question/Bug]  Independent versioning not detecting version properly?

### ISSUE THREAD

**Issue by JamesSingleton** [lerna/lerna#2645]
I recently changed a [lerna repo](https://github.com/americanexpress/one-app-cli) from being fixed to independent as it was bumping packages that had no changes and we quickly went from `v6.0.0` to `v6.5.0` in some of those packages without any changed. However, one of the packages remained at `v6.1.1`. Now when running `lerna version --no-git-tag-version --no-push`, I get the following:

```shell
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Looking for changed packages since v6.1.1
lerna WARN version Skipping working tree validation, proceed at your own risk
lerna info getChangelogConfig Successfully resolved preset "conventional-changelog-angular"

Changes:
 - @americanexpress/eslint-plugin-one-app: 6.7.0 => 6.8.0
 - @americanexpress/generator-one-app-module: 6.7.0 => 6.8.0
 - @americanexpress/one-app-bundler: 6.7.0 => 6.8.0
 - @americanexpress/one-app-runner: 6.7.0 => 6.8.0
```

Now when I run `lerna diff`, the only change is to `packages/generator-one-app-module`

## Expected Behavior

Running the lerna version command should only show the one package from `lerna diff`

## Current Behavior

It is trying to detect changes from `6.1.1` for some reason. However, the lerna.json had `"version": "independent"` when `6.7.0` was rolled out (even though it still bumped a bunch of packages). Ideally it should only suggest the package that shows up in `lerna diff` correct?

## Steps to Reproduce (for bugs)

1. Fork the repo linked above
2. Run `lerna diff` and observe the diff
3. Run `lerna version --no-git-tag-version --no-push`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "command": {
    "version": {
      "conventionalCommits": true
    }
  },
  "version": "independent"
}
```
</p>
</details>

## Context

This is impacting me because lerna is suggesting version bumps to packages that have no changes causing unnecessary version bumps (especially with independent versioning).

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `npm --version`  | 6.14.5 |
| `yarn --version` | 1.22.4 |
| `node --version` | 12.18.1 |

| OS | Version |
| --- | --- |
| macOS Catalina | 10.15.5 |

**Comment by gabrielsch** [comment]
Same issue here, it seems that lerna doesn't work properly with ```--no-git-tag-version``` flag
