### ISSUE TITLE
Lerna run take all cpu resources

### ISSUE THREAD

**Issue by memao** [lerna/lerna#2648]
## Current Behavior

I am using "lerna run build --scope {packge1} --concurrency 1 --stream --profile". I have a 6 core CPU. According to the document, if I set concurrency to 1, only one thread will be generated. But I noticed that all of my CPUs are at 100% usage even for one package. There are more than 10 node.exe process generated by lerna and another two cmd.exe process. 

I also run "lerna run build --scope {packge1,package2} --concurrency 2 --stream --profile" for 2 packages. I noticed that the same package took longer when scope is 2 packages vs 1 package. The during increase as I increase more packages in the scope. It seems even when I run 1 package, lerna takes all the CPU resources on my computer.

## Expected Behavior
What I was expected is that when I set --concurrency=1, only one thread will be generated by lerna. Also when I run 2 packages in the scope, the package1 should take same during as the thread are parallel for both packages.

I am wondering what did I do wrong in my parameters? how does lerna run works, and what is the correct behavior?

## Context
We have a big project that we need to build bundles in 13 apptypes. Each apptype take around 1.2 mins on a 6 core cpu locally. We need to run lerna run <npm command> --scope {all 13 packages} --stream on a build agent, which is 16 core. It currently take 5 mins.5 mins is too long for us. I would expect it take a lot less. How do I reduce the time? 

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.21.0|
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by Ziv-Barber** [comment]
Thanks for the undocumented --concurrency 1 feature!
It giving a workaround to the lerna run always parallel bug!

**Comment by bconnorwhite** [comment]
Seeing a similar issue: `lerna run <command>` takes significantly longer than `cd ./packages/... && yarn run <command>` (if it completes at all). Also maxes out CPU.
