### ISSUE TITLE
Have an option to publish all packages even those unchanged 

### ISSUE THREAD

**Issue by stefstelea** [lerna/lerna#2650]
## Expected Behavior
Publish all packages even those that are not updated 

## Current Behavior
Only publish updated packages 

## Possible Solution
Potentially add a flag to pass in to update-all-packages. It looks like this used to be the behaviour until it got "fixed" here https://github.com/lerna/lerna/issues/1357 but in some cases there is need for all packages to be published even if they weren't changed.

**Comment by phun-ky** [comment]
`lerna version --force-publish` and `lerna publish from-package` works for me :)

**Comment by stefstelea** [comment]
thank you, I missed that on the readme 👀
