### ISSUE TITLE
In independent mode, can `lerna version` be aware of changes to tests, docs, and other non-published changes?

### ISSUE THREAD

**Issue by tom-sherman** [lerna/lerna#2654]
This is an issue for us when using `independent` mode. We only want to publish packages that have changed (and their dependants) which works great, but `lerna version` will also pickup on changes to non-published changes.

For example if I make a docs only change, I don't want Lerna to pickup on that change and prompt me to bump the package version - this new version is completely useless and clutters up the version history.

Can this be done?

**Comment by tom-sherman** [comment]
We're not using conventional commits, does that offer a solution? Do `chore:` commits for example get ignored when versioning?

**Comment by danielmatthew** [comment]
@tom-sherman, from my experience – and what I came here to search for! - is that `chore` commits might be ignored, but not other generic conventional-commit types. Here's a recent excerpt from my git log:

```
* 2a67a03 (tag: @accessible-web-components/tabs@0.2.1) chore(release): publish
* 9e61ae3 docs: update tabs readme and demo
* ec81d44 chore(ci): use small for release job
* 416e080 (tag: @accessible-web-components/tabs@0.2.0) chore(release): publish
```

I don't think that should be happening – certainly from my experience using `standard-release` in another project, `chores`, `refactors`, `docs` are all ignored as expected.
