### ISSUE TITLE
How to clear lerna's cache? Adding new packages not been added

### ISSUE THREAD

**Issue by Ziv-Barber** [lerna/lerna#2656]
My previous lerna.json:

```
{
  "packages": ["packages/*", "tools/*"],
  "version": "independent",
  "command": {
    "publish": {
      "conventionalCommits": true,
      "ignoreChanges": ["*.md"]
    }
  },
  "npmClient": "yarn",
  "useWorkspaces": true,
  "stream": true
}
```

I changed it to:

```
{
  "packages": ["packages/*", "common/*", "tools/*", "examples/*"],
  "version": "independent",
  "command": {
    "publish": {
      "conventionalCommits": true,
      "ignoreChanges": ["*.md"]
    }
  },
  "npmClient": "yarn",
  "useWorkspaces": true,
  "stream": true
}
```

I added 2 new groups of sub-projects ("common/*" and "examples/*") but lerna keep ignoring this change.
lerna list not showing the new projects, lerna bootstrap not adding them. lerna run ... not working on the new projects.
Even removing node_modules didn't work.

## Expected Behavior
A command or something to clear the secret lerna cache that preventing changing the projects list.

## Current Behavior
There's a secret cache somewhere with no way to remove it.

## Your Environment
```
$lerna info
info cli using local version of lerna
lerna notice cli v3.22.1
lerna info versioning independent

 Environment info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
  Binaries:
    Node: 13.11.0 - e:\nodejs\node.EXE
    Yarn: 1.22.4 - e:\nodejs\yarn.CMD
    npm: 6.13.7 - e:\nodejs\npm.CMD
  Utilities:
    Git: 2.27.0. - C:\Program Files\Git\cmd\git.EXE
  npmPackages:
    lerna: ^3.22.1 => 3.22.1
```

**Comment by Ziv-Barber** [comment]
OK, I found it:

When using yarn workspaces don't use the packages settings in lerna.json

**Comment by seanWLawrence** [comment]
I'm using Yarn Workspaces and running `yarn` worked for me.
