### ISSUE TITLE
lerna create not work when set access is public in lerna.json

### ISSUE THREAD

**Issue by daolou** [lerna/lerna#2669]
when set access is public in lerna.json, use `lerna create A`, then A's `package.json` have not `{"access": "public"}`

## Expected Behavior

It can include `{"access": "public"}`

## Current Behavior

have not `{"access": "public"}`

## Steps to Reproduce (for bugs)

1. `lerna init`
2. set `command.create.access` is public
3. `lerna create utils`
4. `utils/package.json.publishConfig` have not `{"access": "public"}`

<details><summary>lerna.json</summary><p>

```json
{
  "command": {
    "bootstrap": {
      "hoist": true
    },
    "create": {
      "access": "public"
    },
    "version": {
      "allowBranch": ["main"],
      "conventionalCommits": true,
      "createRelease": "github",
      "message": "Release: %s :tada: :rocket:"
    },
    "publish": {
      "verifyAccess": false,
      "registry": "https://registry.npmjs.org/"
    }
  },
  "npmClient": "yarn",
  "useWorkspaces": true,
  "ignoreChanges": [
    "**/*.md"
  ],
  "version": "independent"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.22.4 |
| `node --version` | 10.15.3 |

| OS | Version |
| --- | --- |
| macOS Catalina| 10.15.5 |

**Comment by baixiaoyu2997** [comment]
same
