### ISSUE TITLE
[Feature] Flag for turning off progressbar

### ISSUE THREAD

**Issue by sveisvei** [lerna/lerna#267]
I would like an explicit flag/env-variable for turning off the progress bar, because NODE_ENV=test might create other side effects. My specific issue is with travis.

Error with travis:

```
project/node_modules/progress/lib/node-progress.js:131
  complete = Array(completeLength + 1).join(this.chars.complete);
             ^
RangeError: Invalid array length
```

`https://github.com/lerna/lerna/blob/b75a2374b73e8a2a58a4613aab7e9c753296662f/src/progressBar.js#L21`

Maybe `LERNA_CONFIG_PROGRESS=false` or something?

**Comment by thejameskyle** [comment]
I would just copy whatever flag npm already uses for this, I believe it's `--no-progress`
