### ISSUE TITLE
Lerna uses alternate version of npm-registry-fetch which does not include recent security fix

### ISSUE THREAD

**Issue by keving17** [lerna/lerna#2670]
## Expected Behavior

Lerna uses dependency `@evocateur/npm-registry-fetch` which appears to be an unmaintained version of `npm/npm-registry-fetch`. Last month `npm/npm-registry-fetch` released an update that resolves a security vulnerability where logs stored user credentials. Logs should not include sensitive data: https://exchange.xforce.ibmcloud.com/vulnerabilities/184667

## Current Behavior

Logs currently store user credentials since `@evocateur/npm-registry-fetch` has not been updated to pull in the security fix.
https://github.com/evocateur/npm-registry-fetch/blob/latest/check-response.js#L34

## Possible Solution

Lerna can use the original `npm/npm-registry-fetch` or needs to get `@evocateur/npm-registry-fetch` to update with the security fix. Here is the PR that appears to have resolved issue for `npm/npm-registry-fetch`: https://github.com/npm/npm-registry-fetch/pull/29

## Steps to Reproduce (for bugs)

1. Check logs to see if user credentials appear

**Comment by JamesHenry** [comment]
Hi @keving17, following on from the note above, looking at this issue specifically the relevant packages have all since been refactored/patched and there are no such audit warnings when using our latest v5 packages we released since we took over.

Many thanks again!
