### ISSUE TITLE
Invalid Package Name

### ISSUE THREAD

**Issue by goofrnzik** [lerna/lerna#2671]
I am working on an Angular mono repo workspace that has about 12 components in it.
At the end all the components should be under one package in NPM (similar to Angular material ui package) so the name of the each package should be "prefix/container-package-folder/package-name" for an example if I have a component with the name of "gallery" in the package json file the name should be "@prefix/workspace/gallery".
When running "ng build" everything is builidng successfully but when trying to run it with Lerna it return an error.
"Invalid package name".

## Expected Behavior
Should not raise an error maybe warning or at least add an option to ignore.
If Angular allows this build why should Lerna prevent it? 

## Current Behavior
 An error.
"Invalid package name".

## Possible Solution
Add an option to ignore it

## Steps to Reproduce (for bugs)

1. ng new workspace
2. ng g component
3. change package name to contain a sub folder.
4. lerna run build

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.0|
| `npm --version`  | 6.4.1|
| `node --version` | 10.14.1|

| Windows| 10 |

**Comment by lerickson-ds** [comment]
I have a similar issue. We use a package alias named "_". We use yarn and can install/build just fine via yarn, but when using lerna we get the following error:
lerna ERR! Error: Invalid package name "_": name cannot start with an underscore
