### ISSUE TITLE
Private packages install with git url

### ISSUE THREAD

**Issue by borisdamevin** [lerna/lerna#2674]
I try to build on private repository with Lerna, but I can't find a way to work with git url install `npm install git+ssh://my-repo-url` for install packages build with Lerna.

## Expected Behavior

Lerna work with `npm install git+ssh://my-repo-url` for private repo without NPM registry.

## Current Behavior

NPM install the repo in normal way.

## Context

On GitLab self-hosted for my compagny. Buy private repositories on NPM is not an option for now.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1|
| `npm --version`  | 6.14.7 |

| OS | Version |
| --- | --- |
| Windows 10 | 20H2 |

**Comment by borisdamevin** [comment]
No one has idea about that? :(

**Comment by borisdamevin** [comment]
@evocateur @jamiebuilds Sorry to ping you, but do you have any idea about that? I need to find one solution.

**Comment by fchpr** [comment]
AFAIK for GitLab you should try:

```sh
npm install ssh+gitlab ...
```

Which to me works for monolithic repos.

But since `lerna` is made for publishing the packages into a registry, I dunno how can one reference a `yarn` workspace and/or `lerna` package from the kind of URLs I mentioned above.
