### ISSUE TITLE
security: lerna installs vulnerable dot-prop dependency

### ISSUE THREAD

**Issue by AviVahl** [lerna/lerna#2679]
## Expected Behavior
No vulnerabilities when installing `lerna`.

## Current Behavior
`npm i lerna` results in `found 21 high severity vulnerabilities`.

## Possible Solution
Upgrade dependencies?

## Steps to Reproduce (for bugs)
`mkdir test-lerna; cd test-lerna; npm init -y; npm i lerna`

## Context
GitHub popped a yellow notification in repositories I'm admin at, saying: "We found a potential security vulnerability in one of your dependencies."

## Your Environment
Irrelevant, but see below.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `npm --version`  | 6.14.7 |
| `yarn --version` | 1.22.4 |
| `node --version` | 14.7.0 |

| OS | Version |
| --- | --- |
| Fedora | 32 |

**Comment by khitrenovich** [comment]
Dupe of #2606
