### ISSUE TITLE
[Feature] Customize the commands used by lerna

### ISSUE THREAD

**Issue by zkochan** [lerna/lerna#268]
I would love to use [pnpm](https://github.com/rstacruz/pnpm) for installation during `lerna bootstrap`.

I think the solution might be to add the possibility of overriding the commands used by lerna for different actions. `lerna.json` could have a section called `scripts` with those overrides. For instance, something like this would override the installation to use `pnpm` and [np](https://www.npmjs.com/package/np) for publishing:

``` json
{
  "scripts": {
    "install": "lerna link ../pkg-1 && pnpm install",
    "publish": "np $version"
  }
}
```

**Comment by thejameskyle** [comment]
oi, that could be difficult to support.

**Comment by zkochan** [comment]
You might be right...

There are some more important issues for now that lerna should resolve. Later we can return to this one.

Although I would prefer having the possibility to configure these stuff via lerna instead of creating a fork.

**Comment by thejameskyle** [comment]
I'm going to close this, we're going to push everyone to using Yarn eventually using a node api and won't be running commands.
