### ISSUE TITLE
Lerna uses version of dot-prop@4.2.0 which does not include recent security fix

### ISSUE THREAD

**Issue by VancheeZze** [lerna/lerna#2682]
## Expected Behavior

Lerna has some packages that depend on the outdated version of the `dot-prop` package which does not include recent security fix.

For example:
```
lerna > @lerna/run > @lerna/command > @lerna/project > dot-prop
lerna > @lerna/run > @lerna/version > @lerna/project > dot-prop
lerna > @lerna/run > @lerna/publish > @lerna/project > dot-prop
...
```

Result of the `npm ls dot-prop`:
```
└─┬ lerna@3.22.1
  ├─┬ @lerna/add@3.21.0
  │ └─┬ @lerna/command@3.21.0
  │   └─┬ @lerna/project@3.21.0
  │     └── dot-prop@4.2.0 
```

More info about vulnerabilities introduced here: https://npmjs.com/advisories/1213

## Current Behavior

After running `npm audit`, results include vulnerabilities related to the outdated `dot-prop` package which is a dependency of Lerna.

## Possible Solution

Update `dot-prop` package to at least `>=5.1.1 ` - or the latest.

## Steps to Reproduce (for bugs)

1. Run `npm audit` in the project root where lerna is installed.

**Comment by eps1lon** [comment]
`dot-prop@5.x` requires node 8: https://github.com/sindresorhus/dot-prop/releases/tag/v5.0.0. Since `@lerna/project` supports node >= 6.9 this might be problematic.

**Comment by jimmyandrade** [comment]
+1

**Comment by kyoto** [comment]
`dot-prop` v4.2.1 has now also been released with this security fix: https://github.com/sindresorhus/dot-prop/releases/tag/v4.2.1

**Comment by saulonunesdev** [comment]
thanks for the solution @roboswank  works for me

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, it looks like the dot-prop dependency was upgraded sometime ago and so this can be closed.

If you run into any issues on the latest version of lerna, please feel free to open a new issue and follow the instructions:
https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏
