### ISSUE TITLE
'nohoist' doesn't work for '@types/*'

### ISSUE THREAD

**Issue by db42** [lerna/lerna#2688]
I am using lerna with hoisting but don't want to hoist `@types` packages. Therefore, I've added the following to `lerna.json`.

```
"nohoist": [
    "@types/*"
]
```

## Expected Behavior

`@types/` packages shouldn't get hoisted in the root `node_modules` directory.

## Current Behavior
`@types/` packages get hoisted in the root `node_modules` directory.

## Steps to Reproduce (for bugs)

1. Checkout branch `nohoist` from https://github.com/db42/lerna-with-react-native (direct branch link: https://github.com/db42/lerna-with-react-native/tree/nohoist)
2. Run `lerna bootstrap --hoist` from the root directory `lerna-with-react-native`
3. Check `@types` directory in root `node_modules` - `lerna-with-react-native/node_modules/@types/react-native`
4. Expected: `lerna-with-react-native/node_modules/@types/react-native` shouldn't be present. `@types/react-native` is a dependency of lerna-with-react-native/packages/MobileApp and shouldn't be hoisted in the root node_modules.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "nohoist": [
    "@types/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.19.0 |
| `node --version` | v10.15.3 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.15.6 |

**Comment by AnthonyDugarte** [comment]
According to [this](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/), it should be either:

```json
"nohoist": [
    "**/@types"
]
```

or

```json
"nohoist": [
    "**/@types/**"
]
```

**Comment by dvirtz** [comment]
works for me with version `5.1.6`
```
{
  "packages": [
    "packages/*"
  ],
  "useNx": false,
  "version": "0.0.0",
  "nohoist": [
    "@types/*"
  ]
}
```

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
