### ISSUE TITLE
Slow build times when running `lerna run build` from root of lerna project

### ISSUE THREAD

**Issue by coreybruyere** [lerna/lerna#2702]
I opened an issue in [another library(TSDX)](https://github.com/formium/tsdx/issues/808) I'm using to handle Typescript configuration in a small React + Typescript component library set up as a monorepo (using lerna). Build times always took a couple minutes but after upgrading TS versions they take noticeably longer. This all sounds like issues related to the bundler, but when I run `npm run build` from within each package build times aren't long at all (a few seconds for one, and less than a minute for the other). Then when I go run `lerna run build` from the root of my package the build times are 6x slower.

**tl;dr:** My issue is painfully slow build times from running the `build` command in each package via `lerna run build` which is odd since running `npm run build` from each package doesn't result in long build times.

Is there a configuration I'm not aware of that should be initialized inside of `lerna.json`?  I'm not using yarn workspaces. I use npm. I've seen a few threads mention things about workspaces. Is there a npm counterpart for workspaces that might resolve this issue? Not sure how I would even debug this issue.

## Your Environment
Lerna monorepo using TSDX to configure each React-based Typescript package. 

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.12.0 |\
| `node --version` | v12.13.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.5  |

**Comment by grimnomad** [comment]
I have a similiar issue, where running `npm run build` in the root folder leads to build times of about three minutes per package. But if I run every package separately, the build takes only 2 - 3 seconds.

**Comment by coreybruyere** [comment]
are you running `lerna run build` from the root and getting slower build times. I tried running `lerna exex npm run build` thinking accessing cli directly would help but it didn't

**Comment by grimnomad** [comment]
Sorry for the slow response. Yes, I run `lerna run build` from the root directory.

**Comment by grimnomad** [comment]
My colleague found the problem. We are behind a corporate proxy. Every new process tries to run `update-notifier` which does not support proxies. Lerna is waiting until update-notifier finished before it runs the next command. You can create an entry in your .nmprc file with `update-notifier=false`. At least this is what has helped us.

**Comment by gkgeorgiev** [comment]
Hi all,

I tried what @grimnomad has offered as a solution ... but in my case didn't change at all. When I run `lerna run lint`, this takes 190 seconds sharp, while running it directly via NPM - around 30 seconds. I tried to get some more verbose Lerna logs with the --loglevel silly ... but not much more than just a few useless extra lines.

**Comment by coreybruyere** [comment]
@gkgeorgiev - I'll try your solution. I'm still having issues with slow built times and have resorted to building inside of each packages instead of running from the root or just waiting for the build 👎

**Comment by coreybruyere** [comment]
From the root of my monorepo I changed any build related scripts from `lerna run build` to `lerna exec npm run build` and have faster build times. Although, my builds are still taking around 3 minutes which are still extremely slow for a small of a bundle it is.

**Comment by DavidWells** [comment]
I'm seeing this as well. Very slow builds from root dir using lerna. This wasn't the case until recently... 

Is there some cache file or something somewhere that might need to be purged?

**Comment by as-zlynn-philipps** [comment]
When using yarn, you may need `disable-self-update-check true` in a `.yarnrc`: https://classic.yarnpkg.com/en/docs/yarnrc

Just added it and it appears to be helping. 🤷‍♂️

**Comment by JamesHenry** [comment]
Hi Folks 👋 

Due to its age I am going to close this one.

Since this issue was reported, our team took over stewardship of the project and shipped a modern advanced task runner implementation for `lerna run`, which is totally different to the one being referenced here.

https://lerna.js.org/docs/features/run-tasks

If you encounter any problems with modern lerna please feel free to open an issue with as much information as possible.

Many thanks!
