### ISSUE TITLE
[feature]Support lerna run custom script

### ISSUE THREAD

**Issue by TotooriaHyperion** [lerna/lerna#2707]
## Expected Behavior
lerna run 'rm -rf ./lib' --parallel

or

specify the common script in lerna.json
{
  "scripts": {
    "cleanup": "rm -rf ./lib"
  }
}
and when using lerna run cleanup,
1. try run cleanup script in every package
2. if some package don't have a script named cleanup, then run "rm -rf ./lib" in them.

so you can use default script write only once in lerna.json
and if needed, specify a unique script for those package which needs different behavior on that script

## Current Behavior
lerna run cleanup --parallel
with every package has a script "cleanup": "rm -rf ./lib"
you need to write cleanup script in every package.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by TotooriaHyperion** [comment]
This is a feature request.

**Comment by JamesHenry** [comment]
Hi Folks 👋 

I am going to close this one as it seems to be describing the [lerna exec](https://github.com/lerna/lerna/tree/4b045a18eeff622d7832a164a326a96a0a55ecd4/libs/commands/exec#readme) command, which is already supported.

Many thanks!
