### ISSUE TITLE
ERR! lerna Unknown argument: private

### ISSUE THREAD

**Issue by ghost** [lerna/lerna#2713]
I'm sorry for my bad english
I want to use ```filter-options(--no-private)``` when using ```lerna --force-publish``` to avoid detecting private package。
But it doesn't work sometimes
## Expected Behavior
```lerna publish patch --force-publish --no-private``` can work

## Current Behavior
Sometimes it succeeds, sometimes it fails。
```Error```: lerna Unknown argument: private

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "command": {
    "publish": {
      "message": "chore(release): publish"
    }
  },
  "version": "independent",
  "npmClient": "yarn"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1|3.20.2(npx lerna) |
| `npm --version`  | 6.14.6 |
| `yarn --version` | 1.22.5 |
| `node --version` | 10.19.0 |

| OS | Version |
| Ubuntu | 20.04.1 LTS |

![ci失败](https://user-images.githubusercontent.com/57625669/93066224-50492480-f6ac-11ea-8c4e-2d624bf2d283.png)
Failed in jenkins ci

![private失败](https://user-images.githubusercontent.com/57625669/93070541-91900300-f6b1-11ea-94d4-d55f358dae1b.png)
failed in local。and last week was successful

![pirvate成功](https://user-images.githubusercontent.com/57625669/93070560-9654b700-f6b1-11ea-8ae4-bd288e5bad65.png)
successful in local

**Comment by tavisca-rarora** [comment]
I am facing similar issue in 3.21.0
