### ISSUE TITLE
Define migration plan if this cannot be maintained

### ISSUE THREAD

**Issue by goldhand** [lerna/lerna#2717]
*This is part of the proposal in https://github.com/lerna/lerna/issues/2703#issuecomment-693679020*

If this really can't be maintained, the focus should be on establishing a migration path for existing consumers. I would prioritize this more after the first 2 suggestions have time to attempt to yield positive results. I am assuming the migration would be to npm workspaces.

**Comment by JamesHenry** [comment]
Hi @goldhand 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.
