### ISSUE TITLE
TS4053 error with typescript. Why a project's inner ts file is recognized to be external module

### ISSUE THREAD

**Issue by haha370104** [lerna/lerna#2721]
I am trying to generate a multi-packages project with lerna and typescript, here is my repo of demo: https://github.com/haha370104/lerna-typescript-error

But when I try to import some variables(class) from a in-package file, it will always be recoginzed to be an external module, and has ts error as "TS4053: Return type of public method from exported class has or is using name 'TestEnum' from external module "/Users/admin/lerna-test/packages/ts-error2/src/class" but cannot be named". I'm not sure this is a lerna or tsc issue or my mistake, but how should I fix this?

These file just like

```typescript
// packages/ts-error/src/class.ts

export const enum TestEnum {
    Test1 = '123123',
    Test2 = '12312312312',
}

export interface ITest {
    [TestEnum.Test1]: string;
    [TestEnum.Test2]: string;
}

export class A {
    getA(): ITest {
        return {
            [TestEnum.Test1]: '123',
            [TestEnum.Test2]: '123',
        };
    }
}

```

```typescript
// packages/ts-error/src/index.ts

import {A} from './class';

export class B extends A {
    getA() { // TS4053 error
        return {
            ...super.getA(),
            a: '123',
        };
    }
}


```

## Steps to Reproduce (for bugs)
1. git clone https://github.com/haha370104/lerna-typescript-error.git && cd lerna-typescript-error
2. lerna bootstrap
3. yarn build
4. now you can see the error

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `typescript --version`  | 4.0.3 |
| `yarn --version` | 1.22.4 |
| `node --version` | v12.18.2 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.15.6 |

**Comment by hinell** [comment]
As indicated by `TS4053` it's TS isssue, not the Lerna's one. Please, close the Issue.
