### ISSUE TITLE
When hoisting, top-level dependencies can be lost

### ISSUE THREAD

**Issue by bsyk** [lerna/lerna#2722]
## Expected Behavior
lerna bootstrap with --hoist should install the listed packages at the top-level alongside any dependencies explicitly listed in the top-level package.json
 
## Current Behavior
When using lerna bootstrap with --hoist. The top-level dependencies are lost after running the bootstrap command.

## Steps to Reproduce (for bugs)
https://github.com/lerna/repro/pull/1
1. Clean checkout
2. npm install
3. ls node_modules | grep lerna
```
@lerna
lerna
```
4. npm run bootstrap
5. ls node_modules | grep lerna
`-- lerna is gone from top-level node_modules.`

## Context
Trying to use hoist to pull common dev tools into the top-level. When lerna is no-longer available at the top-level as a command, you can't use lerna in any npm scripts. I'm aware that I _could_ directly install these dependencies at the top-level to avoid this issue, but then I'd have to maintain the versions in 2 places. One of the packages is a collection of dev tools that's included in other packages for consistency.
A work-around is to also hoist lerna.

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `npm --version`  | 6.14.5 |
| `yarn --version` | N/A |
| `node --version` | v12.18.0 |

| OS | Version |
| --- | --- |
| macOS Catalina | 10.15.6 |

**Comment by andreujuanc** [comment]
I just had the same issue, can't believe we are the only ones locally installing lerna. My two potential workarounds:
- Globally install lerna 😠 
- Create a "dummy" project and add lerna dependency there instead of on the top-level package.json 😭

**Comment by bsyk** [comment]
My "work-around" is to have the top-level depend on learna and the sub-project, mark the sub-project as ignored when bootstrapping and don't hoist.
One downside is that it won't use the "live" version of the sub-project, but will be using the last published version instead. Not a big deal in my case, but may be a blocker for you.

**Comment by bsyk** [comment]
Repro available: https://github.com/lerna/repro/pull/1

**Comment by JamesHenry** [comment]
Thanks so much for providing the repro @bsyk!

I am slowly but surely familiarizing myself with the internals of lerna. Bootstrap is a really interesting one because it predates the broad support for workspaces we now have in all package managers which perform this kind of hoisting automatically.

Based on experimenting with your repro it seems this case is very specific to when you are explicitly providing particular packages to hoist.

For example, in this particular case you are hoisting all relevant packages, so if you were to swap the usage with either `"hoist": true` in your `lerna.json` or just `--hoist` in the bootstrap command, it would be functionally equivalent. When I do either of those things on your repro, the issue does not occur.

I will look into why this difference might occur

**Comment by bsyk** [comment]
Thanks for looking at this.

Note that this is an example. In the real use-case I don’t want to hoist
everything. Although, I’m not sure if there are any downsides to doing so,
so that could be a solution.

It would be interesting to see if this feature could be migrated to work on
top of non workspaces and delegate package management to that.

**Comment by JamesHenry** [comment]
Hi @bsyk  👋

Thank you very much again for taking the time to provided the reproduction, there's an important update in this area.

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

Please therefore look to transition your current usage of bootstrap and hoisting here to instead lean on the package manager you are already using.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
