### ISSUE TITLE
Lerna tags release even when publish fails

### ISSUE THREAD

**Issue by brandones** [lerna/lerna#2726]
See https://github.com/lerna/lerna/issues/1719 , including the completely correct comment from its author,

> You are aware that prepublish is a part of npm lifecycle that is meant to prevent broken packages from being published?

The [npm documentation](https://docs.npmjs.com/misc/scripts) makes it clear that running tests before publishing is a first-class concern of `prepublish` and related hooks:

> A new event, prepublishOnly has been added as a transitional strategy to allow users to avoid the confusing behavior of existing npm versions and only run on npm publish (for instance, running the tests one last time to ensure they’re in good shape).

Therefore the behavior of Lerna should account for the possibility that a prepublish hook will fail. It should do this by running prepublish and related scripts *before* committing and pushing tags.

**Comment by brandones** [comment]
Relatedly, the instructions in https://github.com/lerna/lerna/blob/master/FAQ.md#how-do-i-retry-publishing-if-publish-fails no longer work.

**Comment by gabrielliwerant** [comment]
Lerna will also commit and push version updates even when it encounters a 403 from npm. So I have a situation where Lerna/repo is out of date with npm because it changed package versions and pushed changes despite the npm publish failure.

**Comment by MickL** [comment]
Related to: https://github.com/lerna/lerna/issues/2807
