### ISSUE TITLE
[Question]: Can I pass command to lerna version to put current date into package.json?

### ISSUE THREAD

**Issue by acidiney** [lerna/lerna#2727]
Hi,
I'm using lerna to manage version of my system... I already use the version from package.json to display what version system is.
But now I need to show the current version and date that was released.
I checked the CHANGELOG file, and I see that Lerna generates a version with the date on the title.

My question is, can I pass any command to Lerna version to add the current version to package.json? This it is possible?

Thank you, for this awesome work and project.

**Comment by jamiehaywood** [comment]
@acidiney did you ever find a solution for this?
