### ISSUE TITLE
"lerna bootstrap" doesn't install anything

### ISSUE THREAD

**Issue by jdanyow** [lerna/lerna#273]
I have a brand new repo where I've configured lerna.  No linked packages yet, nothing published to npm.  
- When I execute `lerna ls` the two packages in the repo are listed :white_check_mark: 
- When I execute `lerna clean` lerna deletes the `node_modules` folder in both packages :white_check_mark: 
- When I execute `lerna bootstrap` lerna creates `node_modules` folder in both packages but nothing else happens- no errors, no installs :x: 

I'm probably doing something wrong or maybe it's because I'm on windows :disappointed: ?

<details>
![commands](http://i.imgur.com/lmezdyT.png)
</details>

**Comment by zkochan** [comment]
I had similar issues. Has to be fixed after merging this pull request https://github.com/lerna/lerna/pull/236

**Comment by thejameskyle** [comment]
Has this started working since Windows support was added?

**Comment by chadoh** [comment]
What is the status of this issue?

**Comment by zxqfox** [comment]
Feels like it does not actual anymore. It should works fine for now
