### ISSUE TITLE
feat: support custom command like `@lerna/remove`

### ISSUE THREAD

**Issue by imcuttle** [lerna/lerna#2742]
I saw the source code: 
https://github.com/lerna/lerna/blob/f6e7a13e60fefc523d701efddfcf0ed41a77749b/core/lerna/index.js#L5-L47

I hope lerna supports to extend custom command like `@lerna/remove` and more.

- `lerna.json`
```json
{
   "moreCommand": ["@lerna/remove/command"]
}
```

**Comment by a1300** [comment]
Duplicate of #1886

**Comment by imcuttle** [comment]
@a1300 It's not duplicate, I means lerna should support more custom command, like https://github.com/imcuttle/lerna-cli#custom-commands
