### ISSUE TITLE
npm ERR! peer dep missing: @octokit/core@>=3, required by @octokit/plugin-request-log@1.0.1`

### ISSUE THREAD

**Issue by nicojs** [lerna/lerna#2744]
## Expected Behavior
After running `npm i lerna`, `npm ls` should exit without error

## Current Behavior

`npm ERR! peer dep missing: @octokit/core@>=3, required by @octokit/plugin-request-log@1.0.1`

## Steps to Reproduce (for bugs)

Run this:
```
mkdir tmp && cd tmp && npm init --yes
npm i -D lerna
npm ls
```

And see the error.

Result of  `npm ls @octokit/plugin-request-log`:

```
tmp
└─┬ lerna@3.22.1
  └─┬ @lerna/version@3.22.1
    └─┬ @lerna/github-client@3.22.0
      └─┬ @octokit/rest@16.43.2
        └── @octokit/plugin-request-log@1.0.1
```

**Comment by HeroicHitesh** [comment]
@nicojs Maybe discussion over [here](https://github.com/octokit/plugin-request-log.js/pull/124#issuecomment-718772143) helps resolve your issue.

**Comment by kaiyoma** [comment]
Seems like this is still an issue. I think the problem is that `@lerna/github-client` is pulling in an old package version:

```
$ yarn why @octokit/rest
yarn why v1.22.5
[1/4] Why do we have the module "@octokit/rest"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@octokit/rest@16.43.2"
info Reasons this module exists
   - "_project_#lerna#@lerna#version#@lerna#github-client" depends on it
   - Hoisted from "_project_#lerna#@lerna#version#@lerna#github-client#@octokit#rest"
```

`@octokit/rest` is up to version 18.1.0. According to [this issue](https://github.com/octokit/plugin-request-log.js/issues/162), the latest version should be used.

**Comment by gr2m** [comment]
let me know if you need help upgrading `@octokit/rest`

**Comment by evocateur** [comment]
[v4.0.0](https://github.com/lerna/lerna/releases/tag/v4.0.0) is now available as `lerna@next`, which should resolve this issue (`@octokit/rest@18` has core as an explicit dependency). Please update if that's not the case.
