### ISSUE TITLE
[Bug] stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by KnisterPeter** [lerna/lerna#278]
Hi,

while preparing my project to build with lerna I'll encountered this error.
Any hint on what is going on here? I've done `lerna boostrap` before.
It may be relevant to note that the `build` script in my packages are compiled using typescript and I'm using debian linux with node 4.x.

```
~/source/paeckchen (multiple-packages)$ ./node_modules/.bin/lerna run build
Lerna v2.0.0-beta.23
Independent Versioning Mode
Errored while running npm script 'build' in 'paeckchen-core'
Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:266:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
Errored while running RunCommand.execute
Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:266:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)

```

**Comment by thejameskyle** [comment]
@gigabo didn't you fix something with this?

**Comment by KnisterPeter** [comment]
I've tried to build 'paeckchen-core' inside the packages folder with `npm run build` and it does fail but there is at least some output.
The problem here was that with `lerna boostrap` an `npm install` was done but the `postinstall` script did not execute. After fixing this the build was fine and now `lerna run build` does work as well.

There might be two different problems here, one with `lerna boostrap` and one with stdout and `lerna run task`.

**Comment by thejameskyle** [comment]
I think the issue is that we're using an api that stores the buffer until the script is completed rather than streaming it.

**Comment by gigabo** [comment]
The fix in #217 was specifically for output from `npm` during `bootstrap` (which was being ignored anyway).

The output from `npm run` scripts is intentionally captured so that the output from different packages doesn't get interleaved.

There are two potential solutions here:

1. Increase `maxBuffer`.
2. Allow output from `npm run` scripts to be interleaved.

**Comment by thejameskyle** [comment]
What would people prefer of those two options?

**Comment by KnisterPeter** [comment]
I would prefer increasing the maxBuffer.
Interleaved output in the run scripts may be completly unreadable.

**Comment by doug-wade** [comment]
I would prefer the output of `npm run` scripts to _not_ be interleaved -- it would make it prohibitively difficult to read the output if you used the script to inform (for instance, when running a task that runs [david](https://github.com/alanshaw/david) for every dependency, you wouldn't be able to tell where deps were updated)

**Comment by thejameskyle** [comment]
What would be a sane choice for the maxBuffer then?

**Comment by doug-wade** [comment]
> What would be a sane choice for the maxBuffer then?

Aye, there's the rub 😉  -- `npm` silly logs can get pretty large; I've seen them be in excess of a mb.

**Comment by KnisterPeter** [comment]
I think a sane default would be some megabyte but there should be a configuration option in the lerna.json to define it.
Lerna by itself could never know how much log output will be generated.

**Comment by thejameskyle** [comment]
If we were just creating a string out of it would we have to mess with maxBuffer at all?

**Comment by thejameskyle** [comment]
> I think a sane default would be some megabyte but there should be a configuration option in the lerna.json to define it.

I would like to avoid the default solution to things always being another config option. I want to keep things simple and not end up with users having hundreds of options to configure

**Comment by rtsao** [comment]
Could https://github.com/feross/multistream be used instead? Then output stream order could be preserved.

**Comment by thejameskyle** [comment]
Maybe, never used it before.

**Comment by glortho** [comment]
+1. we generally can't use `lerna bootstrap` or `lerna run <some build>` because of this.

**Comment by screendriver** [comment]
Any news about that? I'm running into the same issue here.

**Comment by gigabo** [comment]
@rygine increased `maxBuffer` in Asini in https://github.com/asini/asini/pull/16.

I've ported that over here in https://github.com/lerna/lerna/pull/442.

**Comment by gigabo** [comment]
`maxBuffer` has been increased in [lerna@2.0.0-beta.31](https://github.com/lerna/lerna/releases/tag/v2.0.0-beta.31).  Hope that does the trick!

**Comment by pepe79** [comment]
The problem still persists. If anyone else is running into this: lerna cli option --stream fixes this for me.

**Comment by vjpr** [comment]
@pepe79 `lerna bootstrap --stream` did not work for me with 2.5.1.

**Comment by vjpr** [comment]
@gigabo This is still an issue for me. Its blocking my use of lerna entirely. What is the quickest fix? Maybe add a `maxBuffer` flag?
