### ISSUE TITLE
publish with canary makes weird version.

### ISSUE THREAD

**Issue by walt1992** [lerna/lerna#2780]
## Expected Behavior

My current version is 0.5.0. 
and I pre-released the next tags by running below.

```
 lerna publish --canary --preid next --pre-dist-tag next --yes
```

## Current Behavior

This command made new canary version successfully. But created version is different with what is expect.
I expect it generate `0.5.0-next.0`. But It generated `0.0.39-next.1`.

I cannot understand where `0.0.39` come from..
Is it bug? or is there my mistake?

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "conventionalCommits": true
    }
  }
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `yarn --version` | 1.22.10 |
| `node --version` | 12.18  |

**Comment by ChiefORZ** [comment]
duplicate of https://github.com/lerna/lerna/issues/2622
and we fixed is with following changes in our forked lerna: https://github.com/lerna/lerna/pull/2572

**Comment by reallifeliver** [comment]
> duplicate of #2622
> and we fixed is with following changes in our forked lerna: #2572

@ChiefORZ This Fix is not released, right?

**Comment by ChiefORZ** [comment]
> > duplicate of #2622
> > and we fixed is with following changes in our forked lerna: #2572
> 
> @ChiefORZ This Fix is not released, right?

@reallifeliver no, unfortunately not -  but we needed it desperately and thats why we packaged it on our own in our private registry...
