### ISSUE TITLE
lerna: command not found on ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by tafadzwagonera** [lerna/lerna#2783]
## Expected Behavior
After running `yarn global add lerna` and `lerna --version` The Lerna version should be displayed on the terminal

## Current Behavior
Running `lerna --version` displays `lerna: command not found`

## Steps to Reproduce (for bugs)
1. Install `yarn` version `1.22.5` on `ubuntu 20.04 LTS`
2. `yarn global add lerna`
3. `lerna --version` 

<details><summary>lerna.json</summary><p>

```
{
  "packages": [
    "src/packages/*"
  ],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent",
  "command": {
    "publish": {
      "yes": true,
      "conventionalCommits": true,
      "registry": "https://registry.npmjs.org",
      "message": "docs: changelog [skip ci]"
    }
  }
}
```
</p></details>

## Context
I'm trying to run an app locally and setting up `lerna` is a part of that process.

## Your Environment
`yarn 1.22.5`
`node v14.13.0`
`npm 6.14.8`

| OS | Version |
| `ubuntu | 20.04 LTS`

**Comment by Lexouden** [comment]
You may already have tried it but.
Did you reopen your terminal after globally installing, this usually helps when I get the error message after globally installing a CLI package.

**Comment by tafadzwagonera** [comment]
You're right I've tried that and I've also verified that `$PATH` contains the `yarn` bin folder. Everything was it should be. I bought a laptop a few weeks ago and set up Ubuntu 20.10. I installed `lerna` globally, ran `lerna --version` and `lern --help` successfully. I can't figure out why I was struggling with `lerna` installation on the other laptop.

**Comment by Nocturnal-2** [comment]
I am facing the same issue on Ubuntu | 20.04 LTS. @tafadzwagonera what was the solution? Thanks!

**Comment by tafadzwagonera** [comment]
@Nocturnal-2 I couldn't get to the bottom of the matter. I'm presuming you've tried all the steps I've documented to no avail. I'm sorry the bug is a mystery since I can't reproduce it anymore. I'm afraid I don't have any answers.

**Comment by leviathan88** [comment]
Hi, this worked for me
`$ npm config get prefix`
the output should be something like
`/home/<user>/.npm-global`

then run
`$ export PATH=$PATH:~/.npm-global/bin`

and your global deps should be available, 
of course in order to persist this change save this PATH to .bashrc

**Comment by ijiki16** [comment]
This worked for me.
@tafadzwagonera @Nocturnal-2 

unistall:
```bash
yarn global remove lerna
````

install:
```bash
sudo yarn global add lerna
````
<img src="https://pics.me.me/whats-the-magic-word-to-get-what-you-want-sudo-66017437.png"
     alt="Markdown Monster icon"
     style="float: left; margin-right: 10px;" />
