### ISSUE TITLE
How to make lerna bootstrap install only dependencies for a given package

### ISSUE THREAD

**Issue by bhr** [lerna/lerna#2786]
I'm using lerna to develop multiple front-end applications that share modules. When building app A I want to bootstrap only the dependencies of app A, but not B.

For example when bootstrapping application a, I don't want to install the dependencies of h. Or when bootstrapping application b, I only want to install packages e, f, g and h, but not c and d.

![50825278-f1f56b80-1338-11e9-9bc0-e84c7450e5c5](https://user-images.githubusercontent.com/557660/103154522-b48d8100-478f-11eb-99e2-921a82aa4c5e.png)

How do I go about this? I've tried using `--scope` without success.

## Expected Behavior

`lerna bootstrap --scope app_a --include-dependencies` to install only dependencies for app a

## Current Behavior

`lerna bootstrap --scope app_a --include-dependencies` installs all dependencies for the workspace

## Possible Solution

Any pointers would be helpful. I've been digging through earlier issues but haven't found a way that works in my environment.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*",
    "apps/*"
  ],
  "version": "independent",
  "useWorkspaces": true,
  "npmClient": "yarn"
}
```
</p></details>

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `npm --version`  | 6.14.8 |
| `yarn --version` | 1.22.10 |
| `node --version` | 12 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Big Sur | 11.1.1 |

**Comment by diegoaguilar** [comment]
Did you come up to a resolution on this?
