### ISSUE TITLE
[Feature] bootstrap does not respect npm pre- or postscripts

### ISSUE THREAD

**Issue by KnisterPeter** [lerna/lerna#279]
When running `lerna boostrap` lerna itself executes an `npm install somepackage@version...` process.
When installing npm packages like this the preinstall and postinstall scripts are not executed.

**Comment by KnisterPeter** [comment]
I think this issue is invalid due to https://github.com/npm/npm/issues/3059#issuecomment-13062546

**Comment by seansfkelley** [comment]
This isn't necessarily invalid -- I just ran into this issue in a Typescript-based project where the `postinstall` task is used to install typings in some of the packages. Given that I used Lerna to replace a silly `cd`-and-`npm install` script, among other things, it seems arguably useful.

Until then, I'm going to use `lerna run postinstall`, but it's kinda sad. :(

**Comment by thejameskyle** [comment]
It probably makes sense to run those scripts manually in Lerna for compatibility

**Comment by thejameskyle** [comment]
Added in #358
