### ISSUE TITLE
On lerna publish, ".npmignore" do not overrides "files" key in subdirectory

### ISSUE THREAD

**Issue by himanshumehta1114** [lerna/lerna#2796]
## Expected Behavior

According to [package.json#files](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#files) documentation, `.npmignore` should override `files` key in subdirectory.
For e.g 
My project structure is
```
.
+-- packages/
      +-- package1
             +-- package.json
             +-- myDir
                    +-- .npmignore
                    +-- package.json
```

.npmignore
```sh
package.json
```

Package.json 
```json
files: ["myDir"]
```

The published package should not include the `myDir/package.json` file and the `.npmignore` file.

## Current Behavior

The published package includes the `myDir/package.json` and `.npmignore` file.

## Possible Solution

`@lerna/pack-directory` package filters list of files and folders and exports package bundle. It internally uses [npm-packlist](https://github.com/npm/npm-packlist) package which is outdated right now. This issue was addressed in `npm-packlist v2`. Hence, upgrading it to latest version would fix the issue.

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "npm",
  "command": {
    "version": {
      "allowBranch": "master",
    },
    "publish": {
      "message": "chore: publish packages",
      "registry": "http://localhost:8000"
    }
  },
  "packages": ["packages/*"],
  "version": "independent"
}

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `npm --version`  | 7.0.14 |
| `yarn --version` | 1.17.3 |
| `node --version` | 15.3.0 |

| OS | Version |
| ---: | :--- |
| macOS catalina | 10.15.7 |

**Comment by evocateur** [comment]
[v4.0.0](https://github.com/lerna/lerna/releases/tag/v4.0.0) is now available as `lerna@next`, which should resolve this issue. Please update if that's not the case.
