### ISSUE TITLE
Package versions not always being bumped

### ISSUE THREAD

**Issue by TomHancock2** [lerna/lerna#2802]
## Expected Behavior
Make a change to one package but not the other. Both packages get bumped to the same version upon `lerna publish`

## Current Behavior
Occasionally we find that not all packages are being bumped to the same version. It is my understanding that, unless using `versions: "independent", that all packages should have the same version number.

## Steps to Reproduce (for bugs)
It seems to happen at random but will always effect a package that has not been touched. This has been noticed twice on patch and minor releases.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "1.15.0",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "message": "chore: publish [skip ci]",
      "conventionalCommits": true
    }
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context
We are going to be exposing our libraries via CDN and for this we would need all packages to remain on the same version to make it simpler to consume.

Are there any cases where this observed behaviour is expected?

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | `3.22.1` |
| `npm --version`  | `6.13.4` |
| `yarn --version` | `1.22.4` |
| `node --version` | `12.16.1` |

`lerna publish` run in a CI. 

| OS | Version |
| --- | --- |
| Linux | VERSION |

Runs in node docker version 12.18.2

**Comment by jd1048576** [comment]
I believe the [--force-publish](https://github.com/lerna/lerna/tree/main/commands/version#--force-publish) option from the version command is what you need. The publish command calls the version command behind the scenes which is mentioned in the [usage](https://github.com/lerna/lerna/tree/main/commands/publish#usage).
