### ISSUE TITLE
Should `lerna publish --canary` detect unpublished packages?

### ISSUE THREAD

**Issue by LeonardDrs** [lerna/lerna#2803]
Hi, more of a question than an issue.

I tried to canary publish a module that have not been published yet and `lerna publish --canary` did not detect it.
`lerna changed` did detect the module.
`lerna publish from-package --canary` did detect the module but didn't wanted to publish a canary version (which is understandable looking at [the source code](https://github.com/lerna/lerna/blob/main/commands/publish/index.js#L169)).

I was able to force the behavior I wanted with `lerna publish --canary --force-publish="@scope/my-package"` but it's not easily scalable.

It seems that this behavior is [intended](https://github.com/lerna/lerna/blob/72414ec1c679cf8a7ae4bfcefce52d50a6120a70/commands/publish/index.js#L347), so I'm wondering what are the reasons?
Would publishing a canary version of a not-yet-published module be discussed?

Lerna version: 3.22.1
Mode: independent

**Comment by diem98** [comment]
Want to publish a Canary version of a new package that has never been published before. But `lerna publish from-package --canary` publishes an official version

**Comment by SalimBensiali** [comment]
@LeonardDrs I am encountering this on the same version of Lerna as yours. Did you end up resolving your issue?

**Comment by LeonardDrs** [comment]
@SalimBensiali Nop, I'm still using `lerna publish --canary --force-publish="@scope/my-package"` for now

**Comment by SalimBensiali** [comment]
Thanks @LeonardDrs . If you are concerned about scalability of your workaround, you could go with
```bash
lerna publish --canary --force-publish=$(lerna changed | sed 'N;s/\n/,/')
```

@evocateur was canary publishing meant to ignore changes in packages that have not been published yet? If not, I would be keen to contribute a fix.

**Comment by LeonardDrs** [comment]
Created a new discussion (https://github.com/lerna/lerna/discussions/3150) since I couldn't create a discussion from this issue :anguished:
