### ISSUE TITLE
Having a remote named something other than 'origin' breaks `lerna publish`

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [lerna/lerna#2808]
## Expected Behavior
In a project with a default branch named something other than `'master'`, and/or a default remote named something other than `'origin'`, I should be able to `lerna publish` without receiving an error.

## Current Behavior
Attempting `lerna publish` yields the following error:

```
❯ excmd master ⟰  lerna publish       
lerna notice cli v3.20.2
lerna info current version 1.0.0-secondary-rollup-package.0
lerna ERR! ENOREMOTEBRANCH Branch 'master' doesn't exist in remote 'origin'.
lerna ERR! ENOREMOTEBRANCH If this is a new branch, please make sure you push it to the remote first.
```

## Possible Solution
Providing a flag to disable the `ENOREMOTEBRANCH` checks, or better yet, not hardcoding any assumptions at all about branch/remote names into the tool, would be ideal. <3

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
   "packages": ["packages/*"],
   "command": {
      "bootstrap": {
         "hoist": true,
         "strict": true,
         "nohoist": ["bs-*", "ppx-*", "**/bs-*", "**/ppx-*"]
      },
      "run": {
         "stream": true
      }
   },
   "version": "1.0.0-secondary-rollup-package.0"
}
```
</p></details>

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.14.5 |
| `node --version` | v12.16.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Big Sur | 11.1 |

**Comment by MickL** [comment]
Github even renamed "master" to "main" for all new projects

**Comment by dman777** [comment]
Hitting this issue also

**Comment by j710328466** [comment]
solved?

**Comment by xavierfuentes** [comment]
no news?

**Comment by li2go** [comment]
6 months past.

**Comment by adamduncan** [comment]
Does the [--git-remote-name](https://github.com/lerna/lerna/blob/main/commands/version/README.md#--git-remote-name) flag take care of the remote/`origin` aspect of the issue here?

**Comment by mantou132** [comment]
I have the same problem, my reason is the same name of Tag

**Comment by rbirkgit** [comment]
"--git-remote xxx" solved it for me. With it I was able to use a different remote name than origin.

**Comment by JamesHenry** [comment]
Hi folks closing this one as it looks like this is exactly what the `--git-remote` option was added to allow. You can pass it on the CLI or set it in your lerna.json to have it always apply.

Many thanks!

**Comment by Nokel81** [comment]
Could that flag be documented somewhere please? It isn't part of the `lerna publish` command

**Comment by fahslaj** [comment]
@Nokel81 it is documented as an argument for `lerna version`, which are all valid arguments for `lerna publish` also when performing both steps with just a single `lerna publish` command.

See https://github.com/lerna/lerna/tree/main/libs/commands/version#--git-remote-name

**Comment by Nokel81** [comment]
Sure, but running `lerna publish --help` should also have it, or at least mention that all the flags of version are supported.
