### ISSUE TITLE
dependencies are throwing error from package's package.json and prepack command is failing in publish stage 

### ISSUE THREAD

**Issue by kavya983** [lerna/lerna#2809]
**Project folder structure**
Project
|--package.json
|--packages--> A --> package.json

**Package A's package.json:**
scripts:{
    "prepack": "yarn build",
    "build": "yarn clean && yarn compile:js && yarn types",
    "compile:css": "postcss src/**/*.module.css --base src --dir dist",
    "types": "tsc -d --emitDeclarationOnly --p tsconfig.types.json",
    "prepublish": "yarn compile:css"
}
                  
We use lerna to manage the mono repo. There is a dependency **babel-plugin-react-css-modules** in Package A's package.json and we use this command **npx lerna publish from-package --yes** to publish the package to artifactory. 

## Current Behavior

1) While publishing the package in jenkins pipeline, we see this error:
$ postcss src/**/*.module.css --base src --dir dist
Error: Cannot find module 'postcss-modules'
Require stack:
- /project/packages/A/postcss.config.js
- /project/node_modules/cosmiconfig/dist/loaders.js
- /project/node_modules/cosmiconfig/dist/ExplorerBase.js
- /project/node_modules/cosmiconfig/dist/Explorer.js
- /projectr/node_modules/cosmiconfig/dist/index.js
- /project/node_modules/postcss-load-config/src/index.js
- /project/node_modules/postcss-cli/index.js
- /project/node_modules/postcss-cli/bin/postcss
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/project/packages/button/postcss.config.js:3:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19) {
  code: 'MODULE_NOT_FOUND'
}
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna info lifecycle A@4.0.12~prepublish: Failed to exec prepublish script
lerna ERR! lifecycle "prepublish" errored in "A", exiting 1
script returned exit code 1

If we move this dependency **babel-plugin-react-css-modules**  to root package.json, prepublish command is working perfectly fine. But, we don't want to move the package specific dependency to root.
 
2) prepack is failing in publish stage.
We are using the same prepack command in build stage as well in our jenkins pipeline. But in build stage it is passing and failing in prepack step.
Here is the error:
$ tsc -d --emitDeclarationOnly --p tsconfig.types.json
error TS2688: Cannot find type definition file for 'babel__core'.
error TS2688: Cannot find type definition file for 'babel__template'.

If we add these packages to root @types/babel__core and @types/babel__template, prepack is getting succeeded. 
So we wanted to know the reason why the same command is passed in build stage but not in publish stage without these packages(@types/babel__core and @types/babel__template).

## Expected Behavior
1) We don't want to move the package specific dependency(**babel-plugin-react-css-modules**) to root. We would like to keep it in package A's package.json itself. 
2) Prepack command should pass in publish stage as well without these packages(@types/babel__core and @types/babel__template). 

## Steps to Reproduce (for bugs)
1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent",
  "command": {
    "publish": {
    	"artifactory": "ARTIFACTORY_LINK"
    }
  }
}

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | v3.22.1 |
| `yarn --version` | v1.22.10 |
| `npm --version` | v6.9.0 |
| `node --version` | v12.5.0 |

**Comment by zoltanseer** [comment]
I have kind of the same issue, have you found a fix for your error?

**Comment by kavya983** [comment]
@zoltanseer 
it's because of git version. we were using a git version 1.8.3. Upgrading the git solved the issue

**Comment by kavya983** [comment]
closing this issue
