### ISSUE TITLE
How to publish using a custom version without a prompt

### ISSUE THREAD

**Issue by ktalebian** [lerna/lerna#2813]
I want to be able to publish a package using a custom version _without_ a prompt. I tried both `version` and `publish` and both gave me the same error:

```
➜ ./node_modules/.bin/lerna publish --force-publish="*" --no-git-tag-version --no-push --yes test1
ERR! lerna bump must be an explicit version string _or_ one of: 'major', 'minor', 'patch', 'premajor', 'preminor', 'prepatch', 'prerelease', 'from-git', or 'from-package'.

➜ ./node_modules/.bin/lerna version test1 --force-publish="*" --no-git-tag-version --no-push --yes
ERR! lerna bump must be an explicit version string _or_ one of: 'major', 'minor', 'patch', 'premajor', 'preminor', 'prepatch', or 'prerelease'.
```

How do I do this without a prompt? I basically want to have a nightly force publishes and use the timestamp as the version instead of a SemVer.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "4.19.0"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `npm --version`  | 6.14.11 |
| `node --version` | v12.18.3 |
| macOS Catalina | 10.15.7 |

**Comment by matheo** [comment]
lerna.json:
```
{
  ...
  "command": {
    "publish": {
      "yes": true,
      ...
```

**Comment by maecapozzi** [comment]
As far as I know, this isn't possible.
