### ISSUE TITLE
v4.0.0 published in npm as @next

### ISSUE THREAD

**Issue by matheo** [lerna/lerna#2817]
![image](https://user-images.githubusercontent.com/260185/107733273-95f43280-6cc8-11eb-8579-6b505696c432.png)

**Comment by metasean** [comment]
This was intentional. evocoteur has asked people to let him know if anything blows up in that version.

https://github.com/lerna/lerna/issues/2703#issuecomment-777089520

**Comment by matheo** [comment]
woops, then I just blowed my company's monorepo?
I see it building as usual, why not release a `beta` if the idea was to test?
