### ISSUE TITLE
lerna .git binary not found

### ISSUE THREAD

**Issue by prajaktagharpure** [lerna/lerna#2818]
Some context:
I am trying to integrate husky and lerna for pre-commits. and my mono repo structure is a below
```

.git (root)
application 
  folder1
    folder2
      MainClient
        packages
          package1
          .........
          package20
      lerna.json
      package.json (MAIN)

```

in the Main package.json i am adding the below

```
"husky": {
    "hooks": {
      "pre-commit": "lerna run test --concurrency 1 --stream --since HEAD"
    }
  }
```

which potentially should run `test` for only CHANGED packages for all PRE commits.

However it errors out as below

```git commit -m "some change"
husky > pre-commit (node v10.15.3)
lerna notice cli v3.22.1
lerna ERR! ENOGIT The git binary was not found, or this is not a git repository.
husky > pre-commit hook failed (add --no-verify to bypass)
error Command failed with exit code 1.
```

This is because my .git is in the ROOT of my repo while my client is down below the folder structure. 

I really CANT change the folder structure as its got some legacy code that i do not want to touch.

Is there any WORKAROUND where i can RUN tests on changed packages for precommits? 

Any help would be highly appreciated

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `husky --version` | 4.3.8 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.13.0 |
| `node --version` | 10.15.3 |

| OS | Version |
| --- | --- |
| macOS Catalina | 10.15.7 |

**Comment by jaramberri-verimatrix** [comment]
Hey! Did you find a solution for this? Having same issue here :(

**Comment by FreeYeti** [comment]
> Hey! Did you find a solution for this? Having same issue here :(

Me too :(

**Comment by nable-denis-gulin** [comment]
try to use `git init` command before running lerna

**Comment by pz-uc** [comment]
Having the same issues on our Bitbucket pipelines :( 

![image](https://user-images.githubusercontent.com/85098723/177925065-28a5e0ce-90a3-40c4-9d2e-930c7d192fcc.png)

**Comment by pz-uc** [comment]
✅  Found the issue:
I used `node:18.4.0-slim` as my pipeline base image, but I guess `git` is just not installed on the slim version. works fine by using `node:18.4.4` as base image

**Comment by JamesHenry** [comment]
Hi Folks, thanks a lot for your patience on this. I'm sorry that it fell through the cracks during the period when lerna was not so actively maintained before the Nx team took over stewardship.

There is no need to run `git init` before `lerna init`, it will handle that for you (see below).

<img width="767" alt="image" src="https://user-images.githubusercontent.com/900523/227210580-49fe7a71-e402-4987-b9ee-80e95a18743f.png">

But yes you do need to make sure git is installed in whatever environment you are running lerna in.

Many thanks!
