### ISSUE TITLE
lerna does not prompt or wait for input

### ISSUE THREAD

**Issue by s1mrankaur** [lerna/lerna#2819]
"deploy": "lerna run deploy" does not prompt or wait for the user input of MFA code. The command being run for deployment is sls deploy which if run directly prompts to input the MFA code. Lerna wouldn't show the prompt by default and just gets stuck at that point. Event if MFA code is added when it gets stuck, it does not take the user input. 
## Expected Behavior

1. Should show the logs from the command it's running on debug action and should take the user input.

## Current Behavior

gets stuck when it needs user input for MFA code

A similar issue has been reported here: https://github.com/aws/aws-cdk/issues/12143

It has to do with lerna and not CDK.

**Comment by dgorini-ca** [comment]
I am also stuck with this.
"lerna run deploy --stream" solves the problem of not prompting the MFA Code, but the script is does not capture the keyboard input so entering the MFA code does not really work.
