### ISSUE TITLE
[feature-request] `lerna publish` serially

### ISSUE THREAD

**Issue by evantahler** [lerna/lerna#2827]
It would great to have a flag to tell `lerna publish` to upload my packages one-at-a-time, rather than in parallel.  This is helpful when you have a slow connection or are publishing large packages and seeing [timeouts](https://github.com/npm/cli/issues/1023).

## Expected Behavior
`lerna publish --serial` would publish all the packages in my monorepo, one at a time. 

## Current Behavior
`lerna publish` tries to publish lots of packages at once.

**Comment by evantahler** [comment]
I'm bad at reading the docs! You can use the [`--concurrency`](https://github.com/lerna/lerna/tree/main/core/global-options#--concurrency) flag for this

**Comment by jamiehaywood** [comment]
@evantahler if this is issue no longer stands, please close 🙂
