### ISSUE TITLE
A way to get  versions of packages we are about to publish ?

### ISSUE THREAD

**Issue by rottenMonke** [lerna/lerna#2833]
Hello 

When we publish packages the log output contains something like this

```
Found 3 packages to publish:
 - @super-app/core => 1.5.1-alpha.180+4799bdd496
 - @super-app/utils => 1.6.1-alpha.180+4799bdd496
 - @super-app/ui => 1.2.1-alpha.180+4799bdd496
 
 Are you sure you want to publish these packages ?
```

So the question is, does Lerna provide a way to get the same output without intention to publish packages.
For example if we need artifacts  (versions) for CI pipeline 

Thank you

**Comment by kerryj89** [comment]
I couldn't find any option to do this, but with some piping you might be able to get somewhere:

i.e.

`echo -en 'n\n' | lerna version | grep '@super-app/core' | rev | cut -d ' ' -f1 | rev`

**Comment by azakaWow** [comment]
@kerryj89 Thank you very much for the help, not sure if that is what I need but I'll give it a try.

**Comment by kerryj89** [comment]
No problem.  I realize now the downside of that command is that the project needs to have something changed for it to work.
