### ISSUE TITLE
Latest version 4.0.0 has a leak somewhere - all NodeJS threads are left opened after stopping Lerna on Windows

### ISSUE THREAD

**Issue by ghiscoding** [lerna/lerna#2841]
## Expected Behavior
I saw the latest version of Lerna got bumped to 4.0.0 and I saw that it was mainly related to updating a whole bunch of dependencies, unfortunately it seems to be leaking somewhere. I tried my project on 3 different computers and they all leak with latest version of Lerna. At first, I thought it was TypeScript but after trying to upgrade/downgrade every npm packages that changed in the last couple days, I found out it's Lerna 4.0.0 causing the leak.

## Current Behavior
I run my project in Development mode via `lerna run build:demo --parallel` and when I stop the execution, all of the NodeJS threads remain open (I didn't count them 1 by 1 but I see a whole lot staying open after stopping the process).

## Possible Solution
Downgrading to previous version `3.22.1 does fix the issue in my case, so I know there's something wrong `4.0.0`

## Steps to Reproduce (for bugs)

1. You can git clone my project [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal)
2. Upgrade to Lerna 4.0.0, on this [line](https://github.com/ghiscoding/slickgrid-universal/blob/master/package.json#L69)
3. Follow the [installation instructions](https://github.com/ghiscoding/slickgrid-universal#installation) of my project
4. Start the project via the npm script `npm run dev:watch`
5.  Stop the process and see it leak (with Task Manager on Windows), it doesn't seem to stop any of my threads. The print screen below was taken **after** stopping the Lerna command and as you can see it doesn't look like any of the thread are being released. 
![image](https://user-images.githubusercontent.com/643976/110221678-a51b6a00-7e9b-11eb-8478-649e484555cb.png)

I then have to go and end all threads manually to get rid of the opened threads, it's painful and for that reason I have to downgrade back to Lerna `3.22.1` and that fixes it. Also note that I tried multiple times, upgrade/downgrade and it's consistently does the same, a downgrade always fixes it while an upgrade consistently breaks and does the behavior described in this issue.

## Context
Keeping all my npm packages up to date

## Your Environment
Windows 10 environment, ranging from Windows 10 (build 2003) at work to insider builds (20H2) on 2 of my personal computers. So in total I tried on 3 different computers with the same project. 

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 7.5.0 |
| `yarn --version` | 1.19.0 |
| `node --version` | 14.15.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by dman777** [comment]
This does not happen in Unix like systems(MAC and Linux). Try doing in this in WSL if you must use Windows. Most development tools are native to Unix like systems.

**Comment by cabelitos** [comment]
I can confirm that this problem is also affecting me. Unfortunately I can't change to unix due to contractor restrictions.

**Comment by justinbhopper** [comment]
> This does not happen in Unix like systems(MAC and Linux). Try doing in this in WSL if you must use Windows. Most development tools are native to Unix like systems.

As far as I know, Lerna is not currently intended to require using WSL to operate properly on Windows OS.  I suspect most are more willing to move away from Lerna than to change their entire development environment.

**Comment by dman777** [comment]
It's the developers responsibility to use their appropriate tools. You should be using a unix-like system if you are having memory issues.

If you don't want to use WSL then try to git bash. Regardless, this issue does not exist in unix-like systems.

**Comment by justinbhopper** [comment]
@dman777 The fact that the memory leak does not appear on unix systems does not make this a non-issue.  You are not adding anything helpful to the discussion by suggesting that others stop using tools or environments that are intended to be supported by Lerna and NPM/Yarn.

**Comment by dman777** [comment]
I respectfully disagree. I am offering something helpful with mentioning WSL and git bash. Both are freely available on Windows.

**Comment by silltho** [comment]
Hey,
i thought about upgrading to lerna v4 when i stepped over this issue. Since we have devs in out team who are working on windows this is definitely blocking us from moving on.

@dman777 i appreciate your help by mentioning alternatives/workarounds. However for me a workaround is not a fix. If lerna doesn't want support windows natively in the future that's totally fine but it should be discussed in a separate ticket.

**Comment by SyedUmerHasan** [comment]
This is also happening in my Linux environment. These processes are taking my whole memory out there which is causing my machine to freeze 

[Lerna memory leak in v4.0.0- linux enviroment](https://media.discordapp.net/attachments/821977143214997505/841579516203106304/IMG_20210511_123427.jpg?width=819&height=614)

**Comment by SyedUmerHasan** [comment]
Kindly make this issue generic for Linux and macOS environments.
I am also facing this issue while working on Linux and macOS platforms both @ghiscoding 

![IMG_20210511_123427](https://user-images.githubusercontent.com/24965764/117789911-42ab6500-b262-11eb-949c-c0658934e549.jpg)

**Comment by ghiscoding** [comment]
@JamesHenry the fix is in PR #2946, which is 1 line code change, it simply needs to be merged.

**Comment by JamesHenry** [comment]
@feryardiant change was applied in https://github.com/lerna/lerna/pull/3156

Thanks again!
