### ISSUE TITLE
Configure publish commit message

### ISSUE THREAD

**Issue by ianwremmel** [lerna/lerna#285]
I've got lerna publish running as a build step, then pushing back to master. I'd like to add "[skip ci]" to the release commit message so that my infrastructure doesn't rebuild all the code that just finished getting tested. Is that currently possible?

Alternatively, more flexibility with --skip-git would solve it...I could use  something like --skip-git-push to make additional alterations before pushing.

**Comment by gigabo** [comment]
Would this work for you?

```bash
lerna publish --skip-git --repo-version=$VERSION
git commit -am "[skip ci] $VERSION"
git tag $VERSION
git push origin master $VERSION
```

It's a few extra steps, but if you're scripting it maybe it's not too bad?

**Comment by ianwremmel** [comment]
That's kinda what I'm doing at the moment, but supplying my own $VERSION is kinda inconvenient, especially for canary releases.

At the moment, my plan is to (a) remove canary releases and (b) use empty commits with messages along the lines of `#publish 0.7.1` to supply to version to the build script. I guess this issue can be closed for my needs, but I think it's worth considering in the future.

**Comment by gigabo** [comment]
Oh, yeah, with `--canary` that would be tricky...

Having a `--skip-push` would work here, but your original idea actually seems easier to work with: Configurable commit message.  How about something like `--commit-message='[skip ci] $LERNA_PACKAGE_VERSION'`?  The environment variable seems like a natural pair with [`$LERNA_PACKAGE_NAME`](https://github.com/lerna/lerna/pull/276).

Oh, wait... that won't work with `--independent`.  The commit message there is built up from all of the individual `package@version` pairs. 😖 

Definitely seems like there's _something_ we could do here, but if you're not blocked on this I'd say let's wait and see if other people run into similar problems and a good solution emerges.

Closing for now.  Please re-open if inspiration strikes!

**Comment by darrylhodgins** [comment]
@gigabo, I'd definitely find a configurable commit message very handy.  Our build system requires a [TICKET] reference.

**Comment by gigabo** [comment]
Hi @darrylhodgins unfortunately I'm no longer a Lerna maintainer.

I'd suggest pinging one of the [remaining maintainers](https://github.com/orgs/lerna/people).  Thanks for adding your input here!
