### ISSUE TITLE
lerna hangs randomly while publishing packages to local Verdaccio registry

### ISSUE THREAD

**Issue by kaiyoma** [lerna/lerna#2855]
## Expected Behavior
Publishing packages should finish correctly.

## Current Behavior
Publishing sometimes hangs at this spot:

```
12:38:53  lerna success published <package> 0.11.0
12:38:53  lerna notice 
12:38:53  lerna notice package: <package>@0.11.0
12:38:53  lerna notice === Tarball Contents === 
12:38:53  lerna notice 1.1kB   LICENSE                                                     
12:38:53  lerna notice 8.7kB   dist/styles.css                                             
12:38:53  lerna notice 318.8kB dist/index.js                                               
12:38:53  lerna notice 3.4kB   package.json                                                
12:38:53  lerna notice 12.0kB  CHANGELOG.md                                                

...       ...

12:38:53  lerna notice === Tarball Details === 
12:38:53  lerna notice name:          <package>                   
12:38:53  lerna notice version:       0.11.0                                  
12:38:53  lerna notice filename:      <package>-0.11.0.tgz         
12:38:53  lerna notice package size:  90.5 kB                                 
12:38:53  lerna notice unpacked size: 365.3 kB                                
12:38:53  lerna notice shasum:        2005af6e076f97278a82447ddaad11ddd4780fe1
12:38:53  lerna notice integrity:     sha512-hbh/YjhGaAcNj[...]dFZJU1b4G6j9w==
12:38:53  lerna notice total files:   50                                      
12:38:53  lerna notice 
```

## Steps to Reproduce (for bugs)
Use lerna to publish packages to Verdaccio inside a Jenkins CI system.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent",
  "registry": <redacted>,
  "command": {
    "publish": {
      "allowBranch": "trunk",
      "verifyAccess": false,
      "ignoreChanges": ["**/.babelrc", "**/.eslintrc", "**/.gitignore", "**/*.md", "**/test/**"]
    }
  }
}
```
</p></details>

## Context
The package publish task we've defined in our CI system fails randomly and leaves the ecosystem in an inconsistent state, because tags have been pushed to the repo, but the packages themselves have not. We have to resort to publishing the packages manually when this happens.

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `npm --version`  | 6.14.8 |
| `yarn --version` | 1.22.5 |
| `node --version` | 14.15.0 |

| OS | Version |
| --- | --- |
| Debian | 9 |

**Comment by azakaWow** [comment]
Had the same problem with the verdaccio repo. Probably not a network/infrastructure problem. (But you never know)

build	TIME	lerna verb publish @package/sub-package
build	TIME	lerna sill  FetchError: request to http://domainname:7777/@package%2fsub-package failed, reason: socket hang up
build	TIME	lerna sill     at ClientRequest.<anonymous> (/PATH/node_modules/minipass-fetch/lib/index.js:97:14)
build	TIME	lerna sill     at ClientRequest.emit (events.js:315:20)
build	TIME	lerna sill     at Socket.socketOnEnd (_http_client.js:493:9)
build	TIME	lerna sill     at Socket.emit (events.js:327:22)
build	TIME	lerna sill     at endReadableNT (internal/streams/readable.js:1327:12)
build	TIME	lerna sill     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
build	TIME	lerna sill   code: 'ECONNRESET',
build	TIME	lerna sill   errno: 'ECONNRESET',
build	TIME	lerna sill   type: 'system'
build	TIME	lerna sill }

**Comment by artyil** [comment]
@azakaWow @kaiyoma hi guys. Any resolutions or insights, I have a similar issue when publish ends up with ‘socket hang up’ error

**Comment by kaiyoma** [comment]
We've continued to see this problem even after abandoning lerna, so I don't think it's a lerna issue. We're still not sure why it happens, so my workaround is to run the publish command in a loop until it passes.

**Comment by artyil** [comment]
@kaicataldo thanks a lot for prompt response 👍 it is very useful

**Comment by kaicataldo** [comment]
You're welcome! I don't think I did anything though 😆
