### ISSUE TITLE
Error at run lerna add <pkg@version> --scope=['folder']

### ISSUE THREAD

**Issue by armandopbringas** [lerna/lerna#2871]
## Expected Behavior
By only using the command `lerna add <dependency>`, all `packcage.json` files within `packages/` will get updated.
However I can't get it working for individual packages by using `--scope` passing the folder where I need to change an individual dependency.

## Current Behavior
At use the command lerna add with the flag `--scope=[folder]` it doesn´t works, this not update the dependency what i chose for the folder what i want

## Example of command executed
`lerna add react@16.0.0 --scope=shared-ui `

### Console message
```bash
$ lerna notice cli v4.0.0
$ lerna notice filter including "shared-ui"
$ lerna info filter [ 'shared-ui' ]
$ lerna ERR! EFILTER No packages remain after filtering [ 'shared-ui' ]
```

| ---: | :--- |
| `lerna --version` | ^4.0.0 |
| `yarn --version` | 1.22.10 |
| `node --version` | 10.9.0 |

| macOS Big Sur | 11.2.3 |

**Comment by vdua** [comment]
You need to pass the name of the package as specified in the package.json of that package and not the folder name.

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
