### ISSUE TITLE
Question: how to debug "lerna publish doesn't bump the version" when using conventional-commit

### ISSUE THREAD

**Issue by izikl** [lerna/lerna#2876]
On the CI machine when running `lerna publish` with conventional-commit enabled, only the patch version is bumped and the changelogs aren't updated with any of the changes. I think only the latest commit is taken into consideration when deciding how to bump the version and how to update the changelogs. However, I am not sure how to prove, debug or fix it.   

My question is, what is the best way to investigate this type of error? Is there a log/trace in `lerna publish` that shows the command that gets all the commits?  

Running command:
```
lerna publish --yes --tag-version-prefix='packages-v'
```
publish config in lerna.json:
```
"command": {
    "publish": {
      "ignoreChanges": [
        "ignored-file",
        "*.md"
      ],
      "registry": "<my-registry>",
      "message": "chore(release): publish %s",
      "conventionalCommits": true,
      "tagVersionPrefix": "packages-v"
    }
  },
  "packages": [
    "packages/*"
  ]
}
```

output from lerna publish (I masked with *** the projects' names):
```
lerna notice cli v3.22.1
lerna info ci enabled
lerna info current version 2.2.6
lerna info Assuming all packages changed
lerna info getChangelogConfig Successfully resolved preset "conventional-changelog-angular"

Changes
 - @***: 2.2.6 => 2.2.7
 - @***: 2.2.6 => 2.2.7
 - @***: 2.2.6 => 2.2.7
 - @***: 2.2.6 => 2.2.7
 - @***: 2.2.6 => 2.2.7
 - @***: 2.2.6 => 2.2.7
 - ***: 2.2.6 => 2.2.7 (private)
 - ***: 2.2.6 => 2.2.7 (private)
 - ***: 2.2.6 => 2.2.7 (private)

lerna info auto-confirmed 
lerna info execute Skipping releases
lerna info lifecycle ***@undefined~version: ***@undefined

> ***@undefined version /__w/1/s/***
```

OS: Linux

**Comment by Rhuaer** [comment]
try command argument: `--loglevel=verbose`

**Comment by izikl** [comment]
Thanks @Rhuaer for the tip. 
I have tried --loglevel=verbose and --loglevel=silly. 

and I got this:
```
lerna verb updated ***
lerna verb updated ***
lerna verb updated ***
lerna verb updated ***
lerna verb updated ***
lerna verb git-describe undefined => "733870cc"
lerna sill git-describe parsed => {"refCount":"1","sha":"733870cc","isDirty":false}
lerna sill fixed for *** at /__w/1/s/***
lerna verb getChangelogConfig using preset "conventional-changelog-angular"
lerna sill npa Result {
lerna sill npa   type: 'tag',
lerna sill npa   registry: true,
lerna sill npa   where: undefined,
lerna sill npa   raw: 'conventional-changelog-angular',
lerna sill npa   name: 'conventional-changelog-angular',
lerna sill npa   escapedName: 'conventional-changelog-angular',
lerna sill npa   scope: undefined,
lerna sill npa   rawSpec: '',
lerna sill npa   saveSpec: null,
lerna sill npa   fetchSpec: 'latest',
lerna sill npa   gitRange: undefined,
lerna sill npa   gitCommittish: undefined,
lerna sill npa   hosted: undefined
lerna sill npa }
```

the `undefined` in this line caught my eye: 
```
lerna verb git-describe undefined => "733870cc"
```

The trace in describe-ref.js shows that the undefined is "options.match":
```
log.verbose("git-describe", "%j => %j", options && options.match, stdout);
```

How `lerna publish` gets the list of commits to conventional commit? My understanding is that it uses all the commits from tag `<tag-version-prefix><version>`, is that correct? If so, shouldn't options.match include `<tag-version-prefix>*`?

**Comment by Rhuaer** [comment]
I'm new to lerna.
You can try to debug the code when excuting publish command.
Just use the script debug feature in vscode.

**Comment by z3dev** [comment]
Here's what I learned recently about versioning, the HARD WAY!

**IF VERSIONS ARE WRONG THEN THE TAGS ARE WRONG!!!
DO NOT SQUASH MERGES OF RELEASES!!!**
Determine next version:
  git describe --always --long --dirty --first-parent
Check the tags:
  git show @jscad/cli@2.1.0
Correct/add a tag:
  git checkout master
  git tag -a @jscad/cli@2.1.0 HEAD -f
  git push origin --tags -f

Also, if you are using publishing releases on branches then add '--include-merged-tags'

This information should be in the manuals.

**Comment by z3dev** [comment]
Also, you can just call 'version' to simulate this part of the lerna processing. I added a special script in the NPM config.
`    "publish-dryrun": "lerna version --no-private --no-push --conventional-commits"`

**Comment by izikl** [comment]
Thanks @z3dev @Rhuaer. I have used some of your ideas and I am still looking at this issue. Unfortunately, it doesn't repro on my local machine only on the CI machine which makes it much harder to debug. I will keep this thread updated once I will figure this out (and maybe someone could benefit from it in the future).

**Comment by z3dev** [comment]
> Thanks @z3dev @Rhuaer. I have used some of your ideas and I am still looking at this issue. Unfortunately, it doesn't repro on my local machine only on the CI machine which makes it much harder to debug. I will keep this thread updated once I will figure this out (and maybe someone could benefit from it in the future).

Just one more comment. Each version of Lerna has slightly different behaviors. It probably best to keep NPM, NODE, and LERNA at the latest versions. I never use ‘latest’. Pick a version the works and stay there.

Also, Lerna on Windows is pretty flaky.

**Comment by izikl** [comment]
@z3dev luckily I am running on linux, but so far had no issues with lerna on windows (when I tested it locally). 

I figured out why the version hasn't changed. I was using git's fetchDepth: 1 on our CI machine, which caused only one commit to be fetched. 

Thanks a lot for your help @z3dev  and @Rhuaer. I am closing this question.
