### ISSUE TITLE
Lerna symlinks not pointing to built library code

### ISSUE THREAD

**Issue by rnarcos** [lerna/lerna#2884]
### My work tree:
```
.
├── lerna.json
├── package-lock.json
├── package.json
├── ui-components
│   ├── README.md
│   ├── dist
│   │   ├── Button.js
│   │   ├── Button.js.map
│   │   ├── Image.js
│   │   ├── Image.js.map
│   │   ├── Input.js
│   │   ├── Input.js.map
│   │   ├── Switch.js
│   │   ├── Switch.js.map
│   │   ├── Typography.js
│   │   ├── Typography.js.map
│   │   ├── index.esm.js
│   │   └── index.esm.js.map
│   ├── package-lock.json
│   ├── package.json
│   ├── rollup.config.js
│   ├── setupTests.js
│   └── src
│       ├── components
│       │   ├── Button
│       │   ├── Image
│       │   ├── Input
│       │   ├── Switch
│       │   └── Typography
│       ├── index.d.ts
│       └── index.js
└── widgets
    └── widget-1
        ├── babel.config.js
        ├── dist
        │   ├── index.esm.js
        │   └── index.esm.js.map
        ├── package-lock.json
        ├── package.json
        ├── rollup.config.js
        ├── setupTests.js
        └── src
            ├── components
            └── index.js
```

My lerna.json:
```json
{
  "version": "independent",
  "packages": [
    "widgets/*",
    "ui-components"
  ],
}
```

widget-1's package.json:
```json
{
  "name": "widget-1",
  "version": "0.0.1",
  "main": "dist/index.js",
  "module": "dist/index.esm.js",
  "files": [
    "dist"
  ],
  "devDependencies": {
    //...,
  },
  "dependencies": {
    //...,
    "ui-components": "^0.0.1"
  }
}
```

widget-1's node_modules:
```
.
...
└── ui-components
    ├── dist
    │   ├── Button.js
    │   ├── Button.js.map
    │   ├── Image.js
    │   ├── Image.js.map
    │   ├── Input.js
    │   ├── Input.js.map
    │   ├── Switch.js
    │   ├── Switch.js.map
    │   ├── Typography.js
    │   ├── Typography.js.map
    │   ├── index.esm.js
    │   └── index.esm.js.map
    ├── package-lock.json
    ├── package.json
    ├── rollup.config.js
    ├── setupTests.js
    └── src
        ├── components
        │   ├── Button
        │   ├── Image
        │   ├── Input
        │   ├── Switch
        │   └── Typography
        ├── index.d.ts
        └── index.js
```

## Expected Behavior
To be able to use a sym-linked library (`ui-components` in this example) in the same manner as if it was being fetched from npm.

## Current Behavior
`ui-components` under widget-1's node_modules looks exactly like the `ui-components` folder as previously stated under [my work tree](#my-work-tree). Which makes it impossible to import my built code (residing within dist) without making changes to the import statements.

## Steps to Reproduce (for bugs)
1. Create one package named ui-components.
2. Create another package named widget-1.
3. Add ui-component as a dependency of widget-1 package.
4. Run `npm run lerna bootstrap`.
5. Try to import something that is within the dist folder from the ui-components built package (such as `import Button from 'ui-components/Button';`).
6. Recieve an error.

## Context
I want to be able to use my lerna-symlinked package in the same manner as I would if the package would come from npm itself (by importing things that are actually residing within my dist folder).

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 7.6.0 |
| `yarn --version` | 1.22.19 |
| `node --version` | 15.11.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Big Sur | 11.1 |

**Comment by SalimBensiali** [comment]
See https://github.com/lerna/lerna/issues/2883#issuecomment-824496429

**Comment by ctaylor4874** [comment]
Same issue here in version `4.0.0`, reverting back to `3.22.1` resolves the issue
