### ISSUE TITLE
Publish scoped packages on npmjs.org

### ISSUE THREAD

**Issue by ad-m** [lerna/lerna#2902]
We have private repository for scoped package eg. `@scoped`. That repository is used for publishing private package and for proxy public packages. Some our scoped packages is public (published on npmjs.org) and some are not (published on private repository).

Developer set scoped repository via ```npm config set @scoped:registry {uri}``` to able install scoped packages.

When developer attempt to publish packages with `publishConfig.registry = "https://registry.npmjs.org/"` in `package.json` it is uploaded to npm. Npm favor to use the `package.json` registry over registry from `npm config`. This makes private packages available to be published to npmjs.org if `packageConfig.registry` in `package.json` for the package is updated.

## Expected Behavior

When I set :

* `npm config` point to private registry 
* `workspace/package/package.json#packageConfig.registry` point to npmjs.org
* `workspace/package.json#packageConfig.registry` point to npmjs.org
* `workspace/lerna.json#command.registry` point to npmjs.org

package should be published to npmjs.org.

## Current Behavior

When all configuration above happend package is published to private registry.

I notice that settings ``workspace/lerna.json#command.registry`` as npmjs.org have small effect, because it enforce check of credential. Despite of check of credentials package is published in private registry.

## Possible Solution

Prefer configuration in `workspace/lerna.json#command.registry` over `npm config` configuration.

## Steps to Reproduce (for bugs)

All steps is mentioned above.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/**",
    "extensions/**"
  ],
  "npmClient": "yarn",
  "version": "2.0.32",
  "ignoreChanges": [
    "**/*.md"
  ],
  "useWorkspaces": true,
  "command": {
    "publish": {
      "ignoreChanges": [
        "*.md"
      ],
      "registry": "https://registry.npmjs.org",
      "message": "chore(release): publish"
    }
  }
}
```
</p></details>

## Context

I would like manage all organisation packages as scoped package. Some of them I would opt-in make it publicly available on npmjs.org. I use verdaccio as private registry.

Publishing all packages as scoped can be seen as some layer of protection against "dependency confusion" attacks that have been widely described recently: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 7.11.2 |
| `yarn --version` | 1.22.10 |
| `node --version` | v16.1.0 |

| OS | Version |
| --- | --- |
| Linux Mint  | 20.1 |

**Comment by z3dev** [comment]
Not sure if this will help, but the 'initial' publishing of a package needs to be controlled via configuration, otherwise it will default to 'private' for scoped packages. I add the following to package.json for new packages.

```
  "publishConfig": {
    "access": "public"
  },
```

**Comment by ad-m** [comment]
I am aware of this. In this case, the package was previously publicly published on `npmjs.com`, so that configuration was in-place. After that private registry and `npm config set @scoped:registry` was introduced, which moved the publication location to a private registry. Currently, "npm config delete" is used as a workaround before publication to `npmjs.com`, but - for many reasons, but most of all for security - it is not an solution.

**Comment by ad-m** [comment]
I have found solution for that. Thanks to npmrc load order ( https://docs.npmjs.com/cli/v7/configuring-npm/npmrc ) it is enought to create file in project directory named `.npmrc` with content:

```
@scoped:registry = "https://registry.npmjs.org" 
```
