### ISSUE TITLE
yarn install --mutex network:42424 --non-interactive 

### ISSUE THREAD

**Issue by bestofyour** [lerna/lerna#2908]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by pureliumy** [comment]
same issue

**Comment by nmsn** [comment]
+1

**Comment by pureliumy** [comment]
> same issue

I fix this by disable the strict ssl check.
```bash
yarn config set strict-ssl false
```

**Comment by joshxyzhimself** [comment]
At my lerna.json, this fixed it

```diff
        {
-         "npmClient": "yarn",
+         "npmClient": "npm",
          "packages": [
            "packages/*"
          ],
          "version": "2.8.1"
        }
```

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, no information has been provided to assist with looking into the problem. Please kindly head over to https://github.com/lerna/repro and apply any minimal changes necessary to reproduce the behavior.

Many thanks 🙏
