### ISSUE TITLE
[Feature] lerna-scripts

### ISSUE THREAD

**Issue by ianwremmel** [lerna/lerna#292]
I'm not entirely sure what this would look like, but I'd like to be able to define something like

```
lerna-scripts: {
  test: "mocha ."
}
```

at the top level of my project. Then, if I run `lerna run test`, it should execute `mocha .` in each package directory with the top-level's set of node_modules and .bins. Further if a given package defines its own script via npm scripts, that script should be executed instead.

**Comment by hzoo** [comment]
Does either `lerna run` or `lerna exec` not cover it?

https://github.com/lerna/lerna#run `lerna run test` would already run `npm test` in each package that has it

It sounds like instead you are saying you want something like a global `lerna run test` so you don't have to define it in each package?

**Comment by ianwremmel** [comment]
right, it's the top level default that i'm looking for; i'd like e.g. `lerna run test` to use something defined at the top level unless there's defined to the specific package being tested.

Additionally, i believe the current implementation would require e.g. mocha to be installed for each package; ideally, `lerna run test` would use the mocha installed at the top level rather than needing to define one in every package (unless of course the package needs a special version, in which case that one should be preferred).

**Comment by gigabo** [comment]
I'm not sure generic "tests" are the best example here.  Sure, you can omit `"test": "mocha ."` from your package.json, but you still need _actual tests_ in each package directory. ;)

But `eslint`?  `nsp`?  Yeah, might be nice.

Either way, using a binary from a dependency at the repo root would be great!

**Comment by ianwremmel** [comment]
True, each directory would still need to contain test files, but, the majority of them should need the same command. In my example, it's `mocha .`, but in practice, it's something more like `mocha -r babel -R junit -O outDir=./reports ./test/unit/spec/** && mocha -r babel -R junit -O outDir=./reports ./test/integration/spec/**`.

In one case, though, I've got a yeoman generator and yeoman provides its own set of tools for running test, so, for that directory, i want to specify a test command in package.json which invokes the appropriate script.

At the moment, I'm currently solving this problem two Gruntfiles (one of which is largely unreadable).

**Comment by ziflex** [comment]
+1 for this.
For example,  I want to use Babel for all packages, but don't want to write build tasks for each project, I just want to write one generic and apply it for each package.

**Comment by evocateur** [comment]
Since [`v2.0.0-rc.2`](https://github.com/lerna/lerna/releases/tag/v2.0.0-rc.2), you can call dependency binaries from the root _or_ leaves in `lerna exec`. So for the babel case, it's as simple as a regular `npm` script in your root package.json:

```json
{
  "name": "monorepo-root",
  "private": true,
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "lerna": "^2.0.0-rc.4"
  },
  "scripts": {
    "babel": "lerna exec -- babel src -d lib"
  }
}
```

`npm run babel` and Bob's your uncle.
