### ISSUE TITLE
Security vulnerability [critical] affecting `lerna/conventional-commits` -> `handlebars`

### ISSUE THREAD

**Issue by dariagrudzien** [lerna/lerna#2920]
## Expected Behavior

No critical security vulnerability related to Lerna.

## Current Behavior

Critical security vulnerability as per https://www.npmjs.com/advisories/1670

Path:  lerna > @lerna/version > @lerna/conventional-commits > conventional-changelog-core > conventional-changelog-writer > handlebars

## Possible Solution
Patch this dependency or a dependency further upstream.

## Steps to Reproduce 
`yarn audit`

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 7.6.0 |
| `yarn --version` | 1.22.5 |
| `node --version` | 14.5.0 |

| OS | Version |
| --- | --- |
| MacOS | BigSur |

**Comment by JamesHenry** [comment]
Hi @dariagrudzien 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, we already addressed the outdated dependencies mentioned here as part of our v5 release of lerna.

If you run into any issues on the latest version of lerna, please feel free to open a new issue and follow the instructions:
https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏
