### ISSUE TITLE
Lerna Bootstrap -- Legacy Peer Deps Flag?

### ISSUE THREAD

**Issue by shaneajeffery** [lerna/lerna#2921]
Our team is using React 17 and still have some external NPM packages that have not been updated.  We need to be able to run the equivalent of `npm install --legacy-peer-deps` with the `lerna bootstrap` command, but I am not seeing any such flags for that.

We are using the latest version of Lerna and what not.

Any help would be appreciated or any workarounds.

**Comment by shaneajeffery** [comment]
Found the solution in the last response of this: https://github.com/lerna/lerna/issues/2703

`lerna bootstrap -- --legacy-peer-deps`

**Comment by khuezy** [comment]
@shaneajeffery What version of lerna are you using? I'm trying to run the bootstrap command w/ that flag but it's not recognizing it. `Unknown arguments: legacy-peer-deps`

**Comment by shaneajeffery** [comment]
@khuezy Not sure why'd you have to pass another `--`, but glad it worked for you!

**Comment by brionmario** [comment]
If you need to add this to the `lerna.json`, do the following:

```json
{
    ...,
    "command": {
        "bootstrap": {
            "npmClientArgs": [
                "--legacy-peer-deps"
            ]
        }
    }
}
```

Hope this helps someone!

**Comment by zvickery** [comment]
As an update, with lerna 8 the only way forward is to use the `lerna.json` approach above.  Attempts to pass extra arguments will fail with:
```
WARN EDOUBLEDASH Arguments after -- are no longer passed to subprocess executions.
WARN EDOUBLEDASH This will cause an error in a future major version.
```
