### ISSUE TITLE
Question: is it possible to customize conventional commit detection/parsing?

### ISSUE THREAD

**Issue by binaryunary** [lerna/lerna#2923]
Hi,

Azure DevOps prepends PR merge commits with `Merged PR #XYZ:`, unfortunately this is not configurable. Is it perhaps possible on the lerna end to change how the commit messages are parsed to determine the correct bumps and build the changelog? It seems that this is possible in `conventional-recommended-bump` (which I assume lerna is using under the hood).

Thanks

**Comment by mihkeleidast** [comment]
You can make and use your own changelog preset that parses things the way you need it: https://github.com/lerna/lerna/tree/main/commands/version#--changelog-preset

**Comment by binaryunary** [comment]
Thanks. I assumed that changelog presets would only be related to changelog generation and not the actual commit parsing.
