### ISSUE TITLE
[Support] npm dist-tag not available on Nexus, looking for workaround

### ISSUE THREAD

**Issue by MaartenVerbaarschot** [lerna/lerna#293]
Hi,

We have a private NPM registry at our company, using Nexus. They don't support npm dist-tag yet ([NEXUS-9862](https://issues.sonatype.org/browse/NEXUS-9862)). Since Nexus is pretty common for private NPM registries I imagine other people are also getting blocked by this. 

Of course, ideally Nexus introduces npm dist-tag soon and this issue would be resolved. But in the meantime, I would like to check if there is a workaround :). 

When I run `lerna publish` I get the following error:

```
Error updating version as latest
Error: Command failed: npm dist-tag ls mypackagename
npm ERR! registry error parsing json
npm ERR! dist-tag ls Couldn't get dist-tag data for mypackagename
```

I've looked a bit at the [usages of npm dist-tag in the source code](https://github.com/lerna/lerna/blob/49e2ade19cc76b1fc65badfdbd87aef151edd297/src/commands/PublishCommand.js#L394-L404), and because they're in a try/catch block, the publishing still succeeds. However, my Jenkins build will be marked as 'broken' because there are errors.

I was wondering if the npm dist-tag is strictly needed to work with Lerna? It only marks the published packages as the latest, right? So, am I correct that we could work around this error by working with exact version numbers in all our package.json files (thus not depending on what is marked as the 'latest')?

And if the above is correct, would you be open to introducing an option for lerna to skip the use of dist-tag? (e.g. `lerna publish --skip-npm-dist-tag`)

**Comment by dliu120** [comment]
Try putting a .npmrc file pointing to your private NPM repo -- this solved it for me.

**Comment by MaartenVerbaarschot** [comment]
dliu120: The private repo in the .npmrc is what's causing the error in the first place, as it is our private repo that is not supporting the dist-tag.

Which software are you using for your private repo? (Not Nexus I presume? :))

**Comment by dliu120** [comment]
We set up our own private NPM hosted on Azure.

It says [here](http://larrymyers.com/tech/2016/06/05/private-npm-with-nexus.html) that Nexus provides full functionality of NPM, so I'm surprised that dist-tag does not work.

**Comment by timche** [comment]
Nexus is working really well with Lerna except the `npm dist-tag` thing :/ Looking for a workaround as well.

**Comment by timche** [comment]
I've just tried out Lerna with [sinopia](https://github.com/rlidwka/sinopia) and everything is working fine 👍

**Comment by szarouski** [comment]
@timche I wonder how it worked for you? On official sinopia readme it says that tags are not supported: https://github.com/rlidwka/sinopia. I'm getting same error as @dliu120

**Comment by timche** [comment]
@szarouski It just worked for me with Sinopia, sorry 😞

**Comment by szarouski** [comment]
Worked for me after https://github.com/lerna/lerna/issues/246#issuecomment-238424464. Thanks.

**Comment by jogelin** [comment]
@MaartenVerbaarschot Did you find a workaround ? It seems that a ticket is open on the nexus side but no news :-1: [(NEXUS-9862)](https://issues.sonatype.org/browse/NEXUS-9862)

**Comment by hzoo** [comment]
We could do an option to not publish to the temp dist-tag which would fix this. (also fixes the readme issue technically as well). The only reason why we publish to `lerna-temp` then `latest` is to prevent publishing 1 package that succeeds when the others fail though if that makes sense.

**Comment by jogelin** [comment]
@hzoo I think it's a good idea to give the possibility to publish directly to the latest. It's also blocking on my side because my company only uses nexus but I want to introduce lerna so I am doing some `lerna exec npm publish`... :-(

`lerna publish --force-latest-tag=*` ?

**Comment by hzoo** [comment]
I don't think we need the `=*` if we do this.

basically need to skip around doing

https://github.com/lerna/lerna/blob/aeb775d1fec9988f9165cbfad82db2d4fb796c7b/src/commands/PublishCommand.js#L356-L408

**Comment by gigabo** [comment]
Oh, nice this would be a handy option for updating READMEs!

Maybe `--skip-temp-tag`?  Fits in with `--skip-npm`, `--skip-git`...

**Comment by hzoo** [comment]
Done in https://github.com/lerna/lerna/issues/620
