### ISSUE TITLE
Lerna publish leaves updated versions after getting an unauthorized error

### ISSUE THREAD

**Issue by xenyal** [lerna/lerna#2945]
## Expected Behavior
I had an `.npmrc` that didn't have the correct `AUTH_TOKEN` when running `lerna publish` - which led to the eventual publish failing with:

```
Changes:
 - @myorg/my-package: 0.0.1 => 0.0.2

? Are you sure you want to publish these packages? Yes
lerna info execute Skipping releases
lerna info git Pushing tags...
lerna info publish Publishing packages to npm...
lerna notice Skipping all user and access validation due to third-party registry
lerna notice Make sure you're authenticated properly ¯\_(ツ)_/¯
lerna http fetch PUT 401 https://npm.pkg.github.com/@myorg%2fmy-package 109ms
lerna ERR! E401 Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
```

However, I figured that the version bump might be rolled back as the publish failed midway. That ways, I should be able to publish again with the correct `AUTH_TOKEN` so that the new versions can be promoted to a remote repository.

## Current Behavior
- Attempt to publish
- Publish fails due to unauthorized error
- Local versions get updated via lerna, but updated versions remain the same
- Attempting to publish again so that the new versions can be pushed up to the remote repository fails as no new changes are detected.

## Possible Solution
- I'm fairly certain there's a part of the documentation that I missed, as this feels like something a different command could help synchronize between local versions and remote package repo version.

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "npm",
  "packages": ["projects/*"],
  "version": "independent",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "registry": "https://npm.pkg.github.com",
      "ignoreChanges": [
        "**/*.md",
        "**/test/**"
      ]
    }
  }
}
```
</p></details>

## Context
Trying to publish a new version of a local package - however, once the initial publish fails, I'm unable to attempt the publish again as my local versions have already been updated by the initial publish.

## Your Environment
Mac OS iTerm 3

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `npm --version`  | 6.14.12 |
| `yarn --version` | N/A |
| `node --version` | 14.16.1 |

| OS | Version |
| --- | --- |
| macOS Big Sur | 11.4 |

**Comment by mjansen-dc** [comment]
I think the `from-package` positional exists for this reason.

> Similar to the `from-git` keyword except the list of packages to publish is determined by inspecting each `package.json` and determining if any package version is not present in the registry. Any versions not present in the registry will be published. This is useful when a previous `lerna publish` failed to publish all packages to the registry.

See [here](https://github.com/lerna/lerna/tree/main/commands/publish#positionals).

**Comment by xenyal** [comment]
Awesome, that's exactly what I was looking for. Thanks @mjansen-dc
