### ISSUE TITLE
Canary releases get marked as "latest"

### ISSUE THREAD

**Issue by ianwremmel** [lerna/lerna#295]
I've got people complaining about bugs because they're unexpectedly installing canary versions. Aparently, `--canary` is adding the `latest` dist-tag so `npm install --save ciscospark` gets the not-yet-ready alpha release rather than the current stable release.

**Comment by ianwremmel** [comment]
So, looking at the code, I don't actually see how the latest tag is getting added to a canary release, but I've definitely seen it happen.

**Comment by hzoo** [comment]
Hmm that shouldn't be happening - https://github.com/lerna/lerna/blob/master/src/commands/PublishCommand.js#L394-L404

**Comment by ianwremmel** [comment]
yea, agreed. i'm keeping an eye on build builds to see if I can figure out what's happening. 

here's the command I'm using to publish:

```bash
NPM_CONFIG_LOGLEVEL=info npm run lerna -- publish --skip-git --canary --yes
```

**Comment by ianwremmel** [comment]
oh! I think i see what's happening.

after using `lerna publish`, I'm using the following to fix the readme issue. I bet when I unpublish it, npm switches "latest" to "most recently published" rather than "previous latest".

```bash
npm run lerna -- exec --scope ciscospark -- npm version --no-git-tag-version "${NEW_VERSION}-readmehack"
npm run lerna -- exec --scope ciscospark -- npm publish
npm run lerna -- exec --scope ciscospark -- npm unpublish ciscospark@"${NEW_VERSION}-readmehack"
```

**Comment by ianwremmel** [comment]
So, not really a lerna issue after all, but I'm guessing changing to the following will fix it.

```
npm run lerna -- exec --scope ciscospark -- npm publish --tag=readmehack
```

Sorry for spamming you with another non-issue, and thanks for making a great tool!
