### ISSUE TITLE
cannot having a path in "packages" containing "node_modules" directory

### ISSUE THREAD

**Issue by toussa** [lerna/lerna#2964]
In lerna.json, when defining packages, I cannot define a path containing a directory "node_modules" in it.

## Expected Behavior

Although it seems normal to not include "node_modules" directory when using "*" or "**" stars, it should not throw errors when we define a path containing a "node_modules" folder, without using glob stars.

## Current Behavior

when doing `lerna list -la`, we got the error:
```
$ lerna list -la
lerna notice cli v4.0.0
lerna ERR! EPKGCONFIG An explicit node_modules package path does not allow globstars (**)
error Command failed with exit code 1.
```

but our packages array looks like:
```
"packages": [
    "NodeRed/packages/node_modules/@node-red/editor-client",
    "NodeRed/packages/node_modules/@node-red/nodes",
    "NodeRed/packages/node_modules/@node-red/util",
    "NodeRed/packages/node_modules/@node-red/registry",
    "NodeRed/packages/node_modules/@node-red/runtime",
    "NodeRed/packages/node_modules/@node-red/editor-api",
    "NodeRed/packages/node_modules/node-red"
  ],
```
**with no globstars**

## Steps to Reproduce (for bugs)

<summary>lerna.json</summary><p>

```json
{
  "packages": [
    "NodeRed/packages/node_modules/@node-red/editor-client",
    "NodeRed/packages/node_modules/@node-red/nodes",
    "NodeRed/packages/node_modules/@node-red/util",
    "NodeRed/packages/node_modules/@node-red/registry",
    "NodeRed/packages/node_modules/@node-red/runtime",
    "NodeRed/packages/node_modules/@node-red/editor-api",
    "NodeRed/packages/node_modules/node-red"
  ],
  "version": "0.0.1",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
</p>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 6.14.14 |
| `yarn --version` | 1.22.5 |
| `node --version` | v14.17.4 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by Jason3S** [comment]
Is there a reason you nested them under `node_modules`? That can lead to some strange behavior. Or was it an old work around to avoid dynamic/symbolic linking?

**Comment by toussa** [comment]
Actually I don't know the reason behind this. This is part of the node-red opensource project : https://github.com/node-red/node-red

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, it is certainly an unusual setup and I can imagine it causing problems in various ways beyond the usage with lerna. It also seems like the project in question has proceeded without lerna, so I'm going to close this one for now as there does not seem to be any action to be taken.

Many thanks 🙏
