### ISSUE TITLE
lerna 和 yarn 共同使用，babel配置core-js依赖版本冲突问题

### ISSUE THREAD

**Issue by arleyGuoLei** [lerna/lerna#2965]
## 问题描述

项目使用`lerna`和`yarn`搭建，开启了`yarn Workspaces`，项目中存在两个子包A和B，A中配置`babel`及安装`core-js@3`，`babel presets`配置简略如下

```JavaScript
// A包 babel 配置
presets: [
  ['@babel/preset-env', {
    targets: 'defaults',
    // 根据targets按需引入
    useBuiltIns: 'usage',
    // 从core-js@3中引入 polyfill
    corejs: 3
  }]
]
```

B包中，使用了`babel-cli@^6.24.1`，间接依赖安装了`core-js@2`

当在项目根目录执行`yarn`进行依赖安装时，启用了`hoist`模式，表示把共用的依赖包安装到根目录的`node_modules`，此时，**core-js@2**被安装在了根目录的`node_modules`中，在A包的`node_modules`中单独安装了**core-js@3**

当A包使用上述babel配置时，默认会到根目录下读取`core-js`，由于配置的是**3**，但是根目录的版本为**2**，导致打包错误

## 目前有两种想法

- 根目录下应该抽取的是**core-js@3**版本，**core-js@2**应该单独放在B包下

- A包babel配置应该读取自己目录下的node_modules中的core-js，而不是根目录下的node_modules的core-js

有没有什么配置项能解决目前遇到的问题？

**Comment by m-xz** [comment]
阿波巴

**Comment by parkeeers** [comment]
lerna启用yarn worksapce来管理依赖共享。
使用yarn workspace的nohoist来禁止依赖提升
参考：https://classic.yarnpkg.com/blog/2018/02/15/nohoist/

**Comment by parkeeers** [comment]
> ## 问题描述
> 项目使用`lerna`和`yarn`搭建，开启了`yarn Workspaces`，项目中存在两个子包A和B，A中配置`babel`及安装`core-js@3`，`babel presets`配置简略如下
> 
> ```js
> // A包 babel 配置
> presets: [
>   ['@babel/preset-env', {
>     targets: 'defaults',
>     // 根据targets按需引入
>     useBuiltIns: 'usage',
>     // 从core-js@3中引入 polyfill
>     corejs: 3
>   }]
> ]
> ```
> 
> B包中，使用了`babel-cli@^6.24.1`，间接依赖安装了`core-js@2`
> 
> 当在项目根目录执行`yarn`进行依赖安装时，启用了`hoist`模式，表示把共用的依赖包安装到根目录的`node_modules`，此时，**core-js@2**被安装在了根目录的`node_modules`中，在A包的`node_modules`中单独安装了**core-js@3**
> 
> 当A包使用上述babel配置时，默认会到根目录下读取`core-js`，由于配置的是**3**，但是根目录的版本为**2**，导致打包错误
> 
> ## 目前有两种想法
> * 根目录下应该抽取的是**core-js@3**版本，**core-js@2**应该单独放在B包下
> * A包babel配置应该读取自己目录下的node_modules中的core-js，而不是根目录下的node_modules的core-js
> 
> 有没有什么配置项能解决目前遇到的问题？

---------------->

lerna启用yarn worksapce来管理依赖共享。
使用yarn workspace的nohoist来禁止依赖提升
参考：https://classic.yarnpkg.com/blog/2018/02/15/nohoist/
