### ISSUE TITLE
[Question] dependencies of dependencies are not installed into node_modules

### ISSUE THREAD

**Issue by rotemmiz** [lerna/lerna#297]
I noticed that `lerna bootstrap` does not install dependencies are not installed into node_modules.

Let's say I have two projects in my repo:

```
repo
|_ main_project
|_direct-dependency
```

direct-dependency had `lodash` as a dependency.

running `lerna bootstrap` will not install lodash in `main-project/node_modules`

I have prepared a demo setup:
https://github.com/rotemmiz/lerna-dependency-issue-demo

**Comment by gigabo** [comment]
Hi @rotemmiz, thanks for putting together such a thorough report.

This is expected behavior for Lerna, given the current linking strategy for dependencies within the repo.  What negative impact is this having for you?

**Comment by naorye** [comment]
I get negative impact from that linking strategy :)

I have two projects: A and B where A depends on B (A needs B). Both A and B contain React as a dependency. Executing "lerna bootstrap"  installs React both on A and B. When running project A I get an exception that resulted from multiple versions of React.

I believe I miss something or I don't use the best approach for my situation and I appreciate a solution if there is one.

**Comment by andreigabreanu** [comment]
I also kind of see this as an issue. Here is a real world example:

Package A depends on "react" externally (via "dependencies" in package.json)
Package B depends on Package A (via "dependencies" in package.json)
Package C depends on Package A and B (via "dependencies" in package.json)
---
Running lerna bootstrap I would assume I would see in node modules of C a symlink to A and B and "react" installed in the root of C (that's how node would normally run w/o lerna).

Is this something not expected to happen?

**Comment by doug-wade** [comment]
It is not.  For react, hoisting to the monorepo root is the correct solution.
