### ISSUE TITLE
Is this project still ongoing?

### ISSUE THREAD

**Issue by richardkazuomiller** [lerna/lerna#2975]
I've noticed that although there have been some PRs made, none have been merged in about six months. Do the maintainers plan on continuing development?

**Comment by richardkazuomiller** [comment]
A bit more than a week has gone by. I guess Lerna won't be getting any more updates 😢

**Comment by chevtek** [comment]
After working with Lerna on a decently sized team for a while now I'm not sold on it anyway. Feels like crashing into Lerna issues, bugs, shortcomings, etc. take up more time than just doing things manually or creating some bash macros. I'm forced to use it for work but I'm personally not a fan and the lack of activity and support for this project just makes that worse. I'm still a fan of monorepo architecture. I'm just not sure Lerna is the ideal tool for working in such a space.

**Comment by MirKml** [comment]
lerna is mostly unmaintained from end of last year, see https://github.com/lerna/lerna/issues/2703#issuecomment-744601134

**Comment by chevsunrun** [comment]
@MirKml ah, thank you for the link. It's good to have confirmation instead of just being left to wonder.

**Comment by chevtek** [comment]
@MirKml ah, thank you for the link. It's good to have confirmation instead of just being left to wonder.

**Comment by evocateur** [comment]
You should use something else, or, y'know, stop bothering with monorepos entirely, they were a mistake.

**Comment by richardkazuomiller** [comment]
@evocateur I beg to disagree that monorepos are a mistake. While there are downsides to monorepos, in an organization organization where two packages are very closely related, but still need to be decoupled for whatever reason, a monorepo removes a lot of the overhead that would be involved in maintaining a separate repository for each thing. Lerna has saved me and my colleagues a bunch of time.

That said, if you're not interested in maintaining Lerna anymore, I think that's totally fine. I'm thankful for the work you have put in 😄. I just hope you will consider passing the torch to someone who is willing to do so 🙏 .

**Comment by paleite** [comment]
> You should use something else, or, y'know, stop bothering with monorepos entirely, they were a mistake.

@evocateur I'm genuinely curious as to why you consider them being a mistake. Personally, for my use-case it has helped immensely, but I'm really interested in your thoughts on the subject.

Having been the maintainer of this project I assume that at some point you thought it WAS a good idea, so I'm assuming you know something I don't, since you've changed your mind.

Would love to hear more about it.

**Comment by DennisKuhn** [comment]
In my opinion hybrid repos are much better. I tried extending Lerna a little bit, I agree a re-write with new goals would be great. E.g. different modules:
- publish different
- live in different repos
- ...
Lerna has a lot of strength and it would be awesomest to create a new project and port some core building blocks over.

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

**Comment by chevtek** [comment]
Awesome! I hope this project gets some much needed TLC 😊
