### ISSUE TITLE
Support hybrid mode

### ISSUE THREAD

**Issue by bebraw** [lerna/lerna#298]
Currently lerna supports fixed and independent models of versioning. Fixed (aka the Babel way) is great in that it's easy to keep packages in sync at series level. Independent model works better for experimental work due to SemVer.

I believe a third mode, hybrid, would fit between these two. From my perspective fixed mode is too rigid and independent is too lax. Hybrid would combine the best sides of both. Here's how it would work on file system level.
- `./packages` - Fixed versioned packages (i.e., series locked to each other).
- `./experimental` - Independently versioned packages (0.x etc.)

The idea is that as **experimental** packages mature, they can graduate and be moved below `packages`.

I feel this model is ideal for projects that want to grow new packages within the monorepo itself while following SemVer.

You could do something like this right now with two separate monorepos (one fixed, one independent) but that would go against the idea of a monorepo.

**Comment by thejameskyle** [comment]
If you are using independent mode there isn't anything actually stopping you from keeping your packages in lockstep versions.

I guess it sucks that you'd have to enter the same version a bunch of times, but that seems easier than some complicated to configure and support feature where we're half in independent mode, half in locked mode.

**Comment by bebraw** [comment]
@thejameskyle Yeah, I was thinking maybe if Lerna was more modular (using lerna itself), perhaps it would be possible to run two in parallel with some npm script level hacks. In this case you would point one half to stable (fixed) and one half to independent (experimental) directory.

This would push the complexity outside of Lerna but in order to do this I would have to be able to point Lerna to custom **lerna.json** and allow it to use some other directory than **packages** (extra field at config?) at least. There may be some other requirements I'm missing.
