### ISSUE TITLE
`lerna create <pkg> [loc]`, can use relative path to create package or warn right format

### ISSUE THREAD

**Issue by boyan1010** [lerna/lerna#2980]
can use relative path to create package

When I read the lerna documentation for the first time, I thought loc should be a path. But the absolute path is too long, so I used a relative path. As a result, it will always be created in the fist package directory. 

I have two packages directories in lerna.json :

```json
"packages": [
    "apps/*",
    "libs/*"
  ],
```

## Expected Behavior
when I run command `lerna create core ./libs`,  I would want to create a new package  in the libs/ directory.

## Current Behavior
Using lerna create, the package keeps creating in apps/ directory.

before run command 
```
├── apps/
└── libs/
```

run command `lerna create core ./libs`
```
├── apps/
 |  └── core/
 |     ├── __tests__/
 |     └── lib/
└── libs/
```
## Possible Solution
Location  current supports absolute path and packageName, I think it should support relative path too, eg `lerna create core ./libs` or warn right location format.

```json
"packages": [
    "apps/*",
    "libs/*"
  ],
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0  |
| `npm --version`  | 7.21.1 |
| `yarn --version` | 1.22.10 |
| `node --version` | v16.8.0 |

| OS | Version |
| --- | --- |
| macOS Big Sur  | 11.2.3 |

**Comment by JamesHenry** [comment]
Hi @boyan1010 thank you for reporting this!

FYI it seems to work if the leading `./`, i.e. in your case this works `lerna create core libs`

It should not be necessary to omit the leading `./` IMO so I have labelled this as a bug, and a PR would be welcome if you have time!

**Comment by JamesHenry** [comment]
Actually there appears to be an older issue with much more engagement on it around this issue, so closing in favour of that one: https://github.com/lerna/lerna/issues/2520
