### ISSUE TITLE
Update deps of run-lifecycle package

### ISSUE THREAD

**Issue by jdalrymple** [lerna/lerna#2987]
Since npm 7, npm-lifescyle has been deprecated and its suggested to use @npmcli/run-script: https://github.com/npm/npm-lifecycle. This would also remove outdated deps, such as node-gyp@5.0.2

## Expected Behavior
No security alerts

## Current Behavior
Security alert because node-gyp@5.0.2 has a dep on tar@4.4.12

## Possible Solution
Update the deps

**Comment by SaraKevorkian-BO** [comment]
[Now that macOS 12.3 has officially removed Python 2](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes), lerna fails to install due to the deprecated/outdated npm-lifecycle and node-gyp packages. Are there plans to migrate to @npmcli/run-script?

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, we already addressed the outdated dependencies mentioned here as part of our v5 release of lerna.

If you run into any issues on the latest version of lerna, please feel free to open a new issue and follow the instructions:
https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏
