### ISSUE TITLE
lerna bootstrap crashes (infinite loop)

### ISSUE THREAD

**Issue by bebraw** [lerna/lerna#299]
For some weird reason, `lerna bootstrap` crashes in my project (dep issue?). Here's how to repro:

1. Clone https://github.com/reactabular/reactabular
2. `npm install` at project root. This will take a while.
3. `lerna bootstrap` (assumes beta-24).

After 3. you should see something like this:

```bash
reactabular [master] $ lerna bootstrap
Lerna v2.0.0-beta.24
Linking all dependencies
reactabular-sticky                                 ╢███████████████████████████████████░░░░░░░░░░░╟/usr/local/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:110
          return !node.dependencies.filter(function (dep) {
                                    ^

RangeError: Maximum call stack size exceeded
    at Array.filter (native)
    at /usr/local/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:110:37
    at Array.filter (native)
    at bootstrapBatch (/usr/local/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:108:34)
    at /usr/local/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:134:13
    at /usr/local/lib/node_modules/lerna/node_modules/async/lib/async.js:726:13
    at /usr/local/lib/node_modules/lerna/node_modules/async/lib/async.js:52:16
    at replenish (/usr/local/lib/node_modules/lerna/node_modules/async/lib/async.js:314:29)
    at /usr/local/lib/node_modules/lerna/node_modules/async/lib/async.js:330:15
    at _parallel (/usr/local/lib/node_modules/lerna/node_modules/async/lib/async.js:717:9)
```

It could easily be my error, but even then lerna shouldn't crash.

**Comment by gigabo** [comment]
Thanks for reporting @bebraw.  Definitely a deficiency with Lerna (that [I introduced](https://github.com/lerna/lerna/pull/250#discussion_r68813654) with a faulty assumption).  Thanks for reporting.  Will get it fixed up for you.

**Comment by gigabo** [comment]
Hi @bebraw and @jsonmaur.  This should be fixed in `lerna@2.0.0-beta.25`.  Thanks for reporting!

**Comment by bebraw** [comment]
Thanks for the fix. I realized the circular dependency was actually an issue in my project. Maybe it would be nice to have some mechanism (`lerna check-deps`) to warn since often you want to explicitly avoid those.

**Comment by kevnk** [comment]
Thanks for the fix @gigabo 

FYI - for everyone who installed `lerna` globally, make sure you update your global version or else you'll get `Lerna version mismatch` message.

```
$ npm install -g lerna@2.0.0-beta.26
```
