### ISSUE TITLE
Whether lerna bootstrap can include private packages

### ISSUE THREAD

**Issue by zaleGZL** [lerna/lerna#2990]
Whether lerna bootstrap can include private packages,  Because I am converting multiple existing projects into one. monorepo, but one of my sub packages is yarn workspace

## Current Behavior
When running lerna bootstrap , private packages are ignored, the node_modules not install.

## Possible Solution
Is there a parameter to the bootstrap command that forces the inclusion of private packages?

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "version": "independent"
}

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 6.14.13 |
| `yarn --version` | 1.22.11 |
| `node --version` | 14.17.3 |

| OS | Version |
| --- | --- |
 macOS Big Sur | 11.5.1 |

**Comment by pratyushj** [comment]
Did you find any resolution?

**Comment by zaleGZL** [comment]
> Did you find any resolution?

Hi, I found that lerna would not install the dependencies because the package.json in the root of the workspace sub-package did not have any dependencies, you can force a dependency to be installed in the root of the workspace package.
