### ISSUE TITLE
README.md does not get pushed  to npm

### ISSUE THREAD

**Issue by yilmazbingo** [lerna/lerna#2993]
I push the code npm with this script:

```js
 "publish": "lerna publish --no-push"
```

I expected README.md file also gets pushed to npm.

However, README.md was not pushed. Currently my package is on npm but i cannot add a description. readme.md is just blank.

I added README.md to each package, but that did not help neither. 

this is the folder structure:

![npm](https://user-images.githubusercontent.com/47233790/133497912-071f5826-dbfe-43f0-bca8-501b5afd6a0e.png)

here is lerna.json

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "1.0.15"
}

```

here is lerna-debug.log

```txt
0 silly argv   '$0': 'lerna',
0 silly argv   pkg: '@node/types'
0 silly argv }
1 notice cli v4.0.0
2 verbose rootPath /home/tesla/Documents/projects/typescript/jbook
3 error HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@node%2ftypes - Not found
3 error     at /home/tesla/Documents/projects/typescript/jbook/node_modules/pacote/node_modules/npm-registry-fetch/check-response.js:134:15

```

## My Environment
I am on Kali linux.

 "lerna": "^4.0.0"
| `npm --version`  |  6.14.13 |
| `node --version` | v14.17.3  |

|

**Comment by Jason3S** [comment]
In general each package under `packages` should have its own `package.json`, LICENSE, and README.md.

Is that your case?

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, @Jason3S is correct in that each package needs to have a `package.json` which specifies the relevant `files` it is responsible for.

Please see https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files for more information on configuring packages ready for publishing to npm.

If you run into any issues on the latest version of lerna, please feel free to open a new issue and follow the instructions:
https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏
