### ISSUE TITLE
Working tree has uncommitted changes, please commit or remove the following changes before continuing

### ISSUE THREAD

**Issue by hangaoke1** [lerna/lerna#2998]
## Expected Behavior

```
lerna version --conventional-commits
```
git add . and git commit automatic，and add git tag 

## Current Behavior

get errors
![image](https://user-images.githubusercontent.com/19623160/134464949-f68bc102-9fe2-4bed-a729-e819ea156a9a.png)

## Steps to Reproduce (for bugs)

1. make some change in sub packages
2. commit the change
3. run lerna version --conventional-commits
4. get errors

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "version": "independent",
  "npmClient": "npm",
  "useWorkspaces": false,
  "packages": ["packages/*"],
  "command": {
    "publish": {
      "verifyAccess": false,
      "verifyRegistry": false,
      "message": "chore(release): publish %s"
    }
  },
  "granularPathspec": false,
  "ignoreChanges": [
    "**/*.md",
    "**/*.test.ts",
    "**/*.e2e.ts",
    "**/demos/**",
    "**/fixtures/**",
    "**/dist/**",
    "**/lib/**",
    "**/es/**",
    "**/test/**"
  ]
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 6.14.13 |
| `yarn --version` | VERSION |
| `node --version` | v14.17.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by hangaoke1** [comment]
I solved my self

don't config package.json with this scripts key name
```json
{
  scripts: {
     "version": "lerna version --conventional-commits",
     "publish": "lerna publish --conventional-commits"
   }
}
```
the key name `version` and `publish` will casuse some error，just use other key name，forExample,
```json
{
  scripts: {
     "ysf:version": "lerna version --conventional-commits",
     "ysf:publish": "lerna publish --conventional-commits"
   }
}
```

**Comment by TylerSustare** [comment]
This should really be highlighted more in the Lerna docs. There are quite a few issues with this. And the classic "you should know better" isn't a good alternative.
