### ISSUE TITLE
specify for dependency package *not* to be linked for particular dependent package?

### ISSUE THREAD

**Issue by trusktr** [lerna/lerna#2999]
Is there a way to specify that for a dependent package (listed in lerna.json) that a dependency package (also listed in lerna.json) should not be linked into the dependent, even though the version number of the dependency package would normally cause the dependency package to be linked?

For example, suppose we have packages A, B, C, and D in our repo. Suppose that B, C, and D all depend on `A@^1.0.0` and A is at version `1.1.0`.

Normally, A will get linked into B, C, and D because A is in-range for them all.

Can we specify somehow not to link A into C like it normally would be, but let the other packages B and D have A linked as usual?

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
