### ISSUE TITLE
lerna bootstrap install the local version of a sibling instead the published version

### ISSUE THREAD

**Issue by diegoazh** [lerna/lerna#3008]
I have a monorepo with two packages and one of them consumes the other but when I run `lerna bootstrap` this command install the local version not the published version on the npm registry, I note that because I published the `dist` folder as the root folder of the package but when I take a look on the `node_modules` it has the `src` folder, `.prettierrc` and other files that are used for development porpuses but they are not published on the tarball, I'm sure about that because I download the last release of my package and unzipped to confirm that the `dist` folder was published as the root folder.

## Expected Behavior
Install the published version, on npm registry, of the sibling instead of the local version

## Current Behavior
It install the local version of the sibling with the development structure, that brokes all imports because it is different in the local version you need to import from `<pacakge-name>/dist/types` for example and in the published version you import from `<pacakge-name>/types`.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
  "command": {
    "version": {
      "message": "chore(release): publish release"
    }
  },
  "conventionalCommits": true,
  "ignoreChanges": [
    "**/__fixtures__/**",
    "**/__tests__/**",
    "**/*.md"
  ],
  "npmClient": "npm",
  "packages": [
    "packages/*"
  ],
  "useWorkspaces": false,
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 8.0.0 |
| `yarn --version` | 1.22.15 |
| `node --version` | 14.18.1 |

| OS | Version |
| --- | --- |
| Ubuntu | 20.04 |

**Comment by Jonny-Zou** [comment]
I  also met, you solved it？

**Comment by diegoazh** [comment]
No, I move to `pnpm` workspaces.
