### ISSUE TITLE
`package-lock.json` not used when installed dependency at least satisfies `package.json`.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [lerna/lerna#3011]
lerna has unexpected behavior not reading from `package-lock.json` when dependencies are already installed into `node_modules`. When running `lerna bootstrap`, it seems to skip checking what to install via `package-lock.json` if it detects the already installed dependency in `node_modules` satisfies the entry in `package.json`, which is different from regular npm behavior.

Full repro repo is [here](https://github.com/AndrewSouthpaw/lerna-package-lock-bug-repro.git).

Text copied from the repro here for convenience:

## Repro

Notice how `zod@^3.2.0` is specified in `foo/package.json`. We have `zod@3.9.8` currently installed in `node_modules`. Our `foo/package-lock.json` specifies `zod@3.3.4`.

1. `git clone https://github.com/AndrewSouthpaw/lerna-package-lock-bug-repro.git`
1. `cd lerna-package-lock-bug-repro`
1. `npx lerna bootstrap`

**Expected result**: `zod@3.3.4` is installed into `foo/node_modules`. This is what would happen if you ran `npm i` in `foo`.

**Actual result**: No change; `zod@3.9.8` remains in `foo/node_modules`

## Further discussion

You can get the expected result if you *delete first* `foo/node_modules` and then run bootstrap. It seems like lerna is erroneously skipping the check of `package-lock.json` because it detects that the currently installed package at least satisfied `package.json`. By removing the installed package, it then correctly reads `package-lock.json`.

## Setup

These were the steps to create this repo.

1. `npx lerna init`
1. `npx lerna add foo`
1. `cd packages/foo && npm i zod@^3.2.0`
1. Have `zod@^3.2.0` specified in `packages/foo/package.json`.
1. Manually overwrite `foo/package-lock.json` entry for `zod` to this, another valid package:

```
{
  "name": "foo",
  "version": "0.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "zod": {
      "version": "3.3.4",
      "resolved": "https://registry.npmjs.org/zod/-/zod-3.3.4.tgz",
      "integrity": "sha512-g5V20IUn3QBpbMKjZxKp58ocUOO9/L0OlJ5+rl84QSeN6tK5ea/yQboYA59t2D8Puc/qVyz4YflhCgqR2uMtaA=="
    }
  }
}
```

## Context

It's easy to bump into this case; person A already has their packages installed, person B makes a change to a dependency that updates `package-lock.json`, and person A won't get those changes until they happen to wipe their `node_modules`. It's led to many confusing edge cases in our build recently on our team.

## Your Environment

<details><summary>npx envinfo</summary>

$ npx envinfo

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 108.04 MB / 32.00 GB
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    Watchman: 2021.10.04.00 - /usr/local/bin/watchman
  Managers:
    Cargo: 1.55.0 - ~/.cargo/bin/cargo
    CocoaPods: 1.8.4 - /usr/local/bin/pod
    Homebrew: 3.2.15 - /usr/local/bin/brew
    pip3: 21.2.4 - /usr/local/bin/pip3
    RubyGems: 3.0.9 - /Users/andrew/.rvm/rubies/ruby-2.6.6/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.24.0 - /usr/local/bin/git
    Clang: 11.0.0 - /usr/bin/clang
    Subversion: 1.10.4 - /usr/bin/svn
  Servers:
    Apache: 2.4.46 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.8 - /usr/local/bin/docker
    VirtualBox: 6.0.12 - /usr/local/bin/vboxmanage
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.2, 29.0.3
      System Images: android-27 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Emacs: 22.1.1 - /usr/bin/emacs
    Nano: 2.0.6 - /usr/bin/nano
    Sublime Text: 3176 - /Users/andrew/bin/subl
    VSCode: 1.61.0 - /usr/local/bin/code
    Vim: 8.2 - /usr/local/bin/vim
    WebStorm: 2021.2.2
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Bash: 5.0.11 - /usr/local/bin/bash
    Java: 1.8.0_232 - /usr/bin/javac
    Perl: 5.34.0 - /usr/local/bin/perl
    PHP: 7.1.33 - /usr/bin/php
    Protoc: 3.14.0 - /usr/local/bin/protoc
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.7 - /usr/local/bin/python3
    Ruby: 2.6.6 - /Users/andrew/.rvm/rubies/ruby-2.6.6/bin/ruby
    Rust: 1.55.0 - /Users/andrew/.cargo/bin/rustc
  Databases:
    PostgreSQL: 10.18 - /usr/local/opt/postgresql@10/bin/postgres
    SQLite: 3.24.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 94.0.4606.81
    Edge: 94.0.992.50
    Firefox: 93.0
    Safari: 14.1.2
  Monorepos:
    Lerna: 4.0.0
</details>

cc @liamuk

**Comment by liamuk** [comment]
Very confusingly, even using `lerna --ci` seems to not have any effect here. I would expect `node_modules` to get deleted prior to running it, as is the documented behavior for `npm ci` but that doesn't seem to happen.

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
