### ISSUE TITLE
`lerna bootstrap` installing `peerDependencies` if its package scope occurs in `dependencies`

### ISSUE THREAD

**Issue by timvandam** [lerna/lerna#3014]
## Expected Behavior

`lerna bootstrap` should not install peer dependencies for scoped dependencies that are in both `dependencies` and `peerDependencies`. This works with `npm`

## Current Behavior

`lerna bootstrap` *does* install peer dependencies for scoped dependencies that are in both `dependencies` and `peerDependencies`

## Steps to Reproduce (for bugs)
https://github.com/timvandam/lerna-installing-peer-deps
Instructions are in the readme in there^

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}

```
</p></details>

## Context

`@deepkit/type` only works properly if there is just one installed instance, so it breaks my project :cry: (unless I make all `@deepkit/*` a `peerDependency`)

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 7.19.1 |
| `node --version` | v16.5.0 |

| OS | Version |
| --- | --- |
| Ubuntu |  20.04.1 LTS (Focal Fossa) |

**Comment by corydm92** [comment]
@timvandam - Hello, I ran into this issue myself. I noticed that your lockfileVersion is 2, which was added in version npm v7. I found that downgrading to version 6 removed the issue of peerDependencies being installed to our package level node_modules.

Hopefully, this helps and I hope I'm wrong but it seems that this project lacks maintainers and might not have a better fix for this any time soon.

**Comment by timvandam** [comment]
> @timvandam - Hello, I ran into this issue myself. I noticed that your lockfileVersion is 2, which was added in version npm v7. I found that downgrading to version 6 removed the issue of peerDependencies being installed to our package level node_modules.
> 
> 
> 
> Hopefully, this helps and I hope I'm wrong but it seems that this project lacks maintainers and might not have a better fix for this any time soon.

Great to know, thank you! I get the same impression and will be using an actively maintained alternative the next time around

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, it looks like @timvandam was able to resolve their issue so I am going to close this for now.

If you run into any issues on the latest version of lerna, please feel free to open a new issue and follow the instructions:
https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏

**Comment by Ai01** [comment]
https://github.com/lerna/lerna/issues/2921#issuecomment-853968249

l found another slove in this answer, Hope that can help you.
