### ISSUE TITLE
make `lerna publish` atomic

### ISSUE THREAD

**Issue by eladchen** [lerna/lerna#3018]
## Expected Behavior

I recently wrote a package to automate release workflows, called [atomic-release](https://github.com/abstracter-io/atomic-release).
I'm interested in integrating it with `lerna publish`, and was wondering what are your thoughts about this before doing anything.

## Current Behavior
From what I understand, errors encountered when executing `lerna publish` will not automatically  
roll back any action taken.

Using atomic release will help ensure releases always start from a clean slate.

**Comment by JamesHenry** [comment]
Closing in favour of #455
