### ISSUE TITLE
-p does not output parseable, but path

### ISSUE THREAD

**Issue by y-nk** [lerna/lerna#3019]
## Expected Behavior

```
$ npx lerna list --scope=@myorg/pkg --parseable
pkg path something else useful separated by \s
```

## Current Behavior

```
$ npx lerna list --scope=@myorg/pkg --parseable
/path/to/lerna/packages/pkg
```

## Possible Solution

I think changing the expanded name of the parameter to `--path` would be the best fix. This command is useful and i dont think it should disappear, but it's just that `parseable` is a deceptive name for what it does.

## Context
I'm building a backend/microservice monorepo with lerna, and for such i needed to separate packages between lib and services (very much like nx's libs/apps). in further build scripts, i need path access to package.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |

**Comment by evocateur** [comment]
It's copying the behavior of the npm CLI flag of the same name, and won't be changing.
