### ISSUE TITLE
lerna bootstrap doesn't work

### ISSUE THREAD

**Issue by breezefaith** [lerna/lerna#3030]
It doesn't work and I don't get any response for a long time When I run this command "lerna bootstrap".
![error](https://user-images.githubusercontent.com/20924601/142637408-48a42446-ef18-4544-af5e-7af5ec9cbb6f.png)

## Config
lerna.json
```json
{
  "packages": [
    "packages/*",
    "apps/*"
  ],
  "version": "0.0.0",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "registry": "https://registry.npm.taobao.org",
  "publishConfig": {
    "access": "public",
    "registry": "https://registry.npmjs.org"
  }
}
```

## Environment
Windows 10
Node v10.15.3
Yarn 1.22.1
lerna 3.22.1

**Comment by breezefaith** [comment]
The issue is the same as  #2596 .

**Comment by evocateur** [comment]
You're using Yarn and workspaces. I don't see why you need to run `lerna bootstrap` when `yarn` is right there.
