### ISSUE TITLE
how to publish after `version`

### ISSUE THREAD

**Issue by taoliujun** [lerna/lerna#3034]
## Expected Behavior

I want to integrate `version` and `publish` in my cli tool that can generate version automaticly by `version` or manually by `publish`.  `publish from-package` was need when version was generated automaticly by `version` because latest tag was generated. but `from-package` must be ignored when i specify version after cancel `version`.

how can i do?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by taoliujun** [comment]
i resolve it use `changed` to check if has changed files at latest tags and push from-package beto publish

**Comment by JamesHenry** [comment]
It seems like this was resolved
