### ISSUE TITLE
Lerna bootstrap command doesn't generate yarn.lock file

### ISSUE THREAD

**Issue by sunakshitejwani** [lerna/lerna#3037]
## Expected Behavior

Lerna bootstrap command to generate yark.lock file in individual sub packages.

## Current Behavior

lerna bootstrap comand doesnt generate yarn.lock file. 

## Steps to Reproduce (for bugs)

1. install yarn 1.22.10
2. install lerna 4.0.0 
3. if you have a multi module setup, run lerna bootstrap in root folder. 

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "version": "0.0.0",
  "npmClient": "yarn",
  "packages": ["sample/*", "sample2/*"],
  "ignore": ["@sample/example"],
  "command": {
    "bootstrap": {
      "npmClientArgs": ["--legacy-peer-deps"]
    }
  }
}
```
</p></details>

## Context

I am using yarn with lerna to manage multi module Javascript project.
However it is NOT generating yarn.lock for each sub-project while running lerna bootstrap command
It is necessary step to generate yarn.lock file in Jenkins pipeline for OSS scan report.
How to fix this?

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0|
| `npm --version`  | 7.10.0|
| `yarn --version` | 1.22.10|
| `node --version` | 14.8.1|

**Comment by vlad-ostrovski** [comment]
there's also no node_modules state file in each package node_modules.. so I can't `yarn run build`..

**Comment by lior-a** [comment]
is it fixed? I still have this problem. lerna 4

or it is intended to be like that

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
