### ISSUE TITLE
Lerna command on commiited files

### ISSUE THREAD

**Issue by qualityTestPostman** [lerna/lerna#3039]
## Issue
I'm using husky, lint staged, and lerna to run some tests on the files in the packages which are recently committed using this one 
`yarn run lerna run --concurrency 1 --stream prepush --since HEAD --exclude-dependents`
When I use this command in the pre-commit hooks it works perfectly on the staged files. But I need to use the same command to run the tests on flies that are committed.

I want to run some tests related to the files which are recently changed before push

## Current Behavior
The current behavior is this when I run the above command on the committed files I get this msg
`lerna success run No packages found with the lifecycle script 'prepush'`.

Any help is appreciated.

**Comment by mh1622** [comment]
@qualityTestPostman how did you solve this issue? I am currently experiencing it with lerna 4 and husky 7.

**Comment by yuriburk** [comment]
Any solution?
