### ISSUE TITLE
`lerna publish` not respectiving `"private": true`

### ISSUE THREAD

**Issue by jherdman** [lerna/lerna#3042]
## Expected Behavior

When attempting to publish, packages with the private flag set to `true` should be ignored and not published.

## Current Behavior

We have a monorepo that looks like this:

```
root
|---- apps/<many apps>
|---- packages/<supporting packages>
```

Each app's `package.json` has `"private": true` explicitly set, each package can be published whilst we finish transitioning to our monorepo.

When I run `lerna publish` I see this output...

```shell
$ lerna publish
lerna notice cli v4.0.0
lerna info versioning independent
lerna WARN Yarn's registry proxy is broken, replacing with public npm registry
lerna WARN If you don't have an npm token, you should exit and run `npm login`
lerna info Assuming all packages changed
? Select a new version for SOME_APP (currently 0.0.0) (Use arrow keys)
```

Where SOME_APP absolutely should not be published.

## Possible Solution

`¯\_(ツ)_/¯`

## Steps to Reproduce (for bugs)

See above.

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "yarn",
  "useWorkspaces": true,
  "packages": [
    "apps/**",
    "packages/**"
  ],
  "version": "independent"
}
```
</p></details>

## Context

See above.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | v4.0.0 |
| `npm --version`  | 6.14.10 |
| `yarn --version` | 1.22.5 |
| `node --version` | v14.15.4 |

| OS | Version |
| macOS  Monterey | 12.0.1 |

**Comment by jherdman** [comment]
I believe I can close this issue, but there is some unexpected behaviour that may need to be documented in the publishing docs.

If your package.json marks as private, **and** you have a version number, Lerna will try and bump the version number regardless. This is both surprising and undocumented.

**Comment by ntucker** [comment]
" This is both surprising and undocumented." - why isn't it even possible to do something unsurprising with a configuration option?

**Comment by jherdman** [comment]
Can you ask your question a different way?

**Comment by cefn** [comment]
Agreed this feature violates the fundamentals of npm as declared in the npm documentation which I consider to be more primary than lerna conventions... 
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#private

Given the definition of `private:true` in the npm documentation, the reverse should be true meaning there should be a flag to override the default - which would be respecting `private: true`.

In my view an invocation of lerna should not require a --no-private option to prevent publishing of packages which are already instructed explicitly not to be published [this surprising requirement is explained in the Lerna Documentation](https://lerna.js.org/docs/getting-started#publishing).

**Comment by ntucker** [comment]
Yes! Lerna should never publish private; we still want those packages to point to the latest versions of the published ones tho!

The most common use case for private packages in a monorepo is examples.

**Comment by cefn** [comment]
OK, so is it that `publish --no-private` isn't saying don't ___publish___ private, it's saying don't update private packages' tags, commits, dependency versions to align when you are publishing the ___public access___ packages?

If so, why is this option being used so explicitly in the reference examples. How bad would it be just to complete the steps using the defaults? I found this very confusing as a command and assumed it prevented publishing private packages... https://lerna.js.org/docs/features/version-and-publish

**Comment by matthew-dean** [comment]
I'm also confused by the new documentation on this option. I want private packages' versions to be incremented, but not published. What is the option for that?

**Comment by fahslaj** [comment]
@matthew-dean this is the default behavior of Lerna - `lerna version` will version all packages, including ones marked `private`. However, `lerna publish` will only actually publish the ones that are not private. 

If you just use `lerna publish` without `lerna version` first, then it will prompt you for a version number to apply to all updated packages (including private ones), then it will proceed to publish only those that are not private.

The output will look something like this:
<img width="548" alt="image" src="https://github.com/lerna/lerna/assets/6913035/545db3bf-5e27-4e59-98ca-fa9af741a806">

Notice the `lerna success published 1 package` line at the end of the output.

**Comment by ntucker** [comment]
@fahslaj it may not publish to npm but it creates a github release. Do you think github release without an npm package is a good idea?

**Comment by fahslaj** [comment]
Lerna assumes that there can be value in versioning private packages, which is why they are included by default with `lerna version`. This includes bumping their version numbers, managing their change logs, and as you pointed out, creating github releases. If this is undesirable, then it can be easily disabled with the `--no-private` option.
