### ISSUE TITLE
[Support] Caching node_modules on Heroku/CircleCI

### ISSUE THREAD

**Issue by arbesfeld** [lerna/lerna#305]
What is the recommended way to handle the caching for `node_modules` of nested packages? Currently we have to list all of the packages in `circle.yml` and the root `package.json` file which is not ideal. It would be nice to have some way to symlink all of the dependencies from another location.

**Comment by giuseppeg** [comment]
@arbesfeld hi, I put together [a gross hack](https://github.com/giuseppeg/suitcss-toolkit/blob/master/Makefile#L59) to reduce build time in CI

**Comment by doug-wade** [comment]
[save_cache](https://circleci.com/docs/2.0/configuration-reference/#save_cache) takes a list of directories which should be added to the cache; adding all of the node_modules of nested packages should do the trick.
