### ISSUE TITLE
Circular dependencies between packages

### ISSUE THREAD

**Issue by jsonmaur** [lerna/lerna#306]
How do I handle circular dependencies? Not sure if there would even be a solution for this, due to bad setup on my part, or if it is related to https://github.com/lerna/lerna/issues/299. But the following error happens when I have two packages referencing each other. e.g. `pkg2` has `pkg1` as a peerDependency, `pkg1` has `pkg2` as a devDependency (for testing purposes).

```
Errored while running BootstrapCommand.execute
RangeError: Maximum call stack size exceeded
    at Array.filter (native)
    at /Users/jsonmaur/n/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:110:37
    at Array.filter (native)
    at bootstrapBatch (/Users/jsonmaur/n/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:108:34)
    at /Users/jsonmaur/n/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:134:13
    at /Users/jsonmaur/n/lib/node_modules/lerna/node_modules/async/lib/async.js:726:13
    at /Users/jsonmaur/n/lib/node_modules/lerna/node_modules/async/lib/async.js:52:16
    at replenish (/Users/jsonmaur/n/lib/node_modules/lerna/node_modules/async/lib/async.js:314:29)
    at /Users/jsonmaur/n/lib/node_modules/lerna/node_modules/async/lib/async.js:330:15
    at _parallel (/Users/jsonmaur/n/lib/node_modules/lerna/node_modules/async/lib/async.js:717:9)
```

This is with `v2.0.0-beta.24`. Thanks!

**Comment by gigabo** [comment]
Hi @jsonmaur, thanks for reporting.  This was previously reported in #299.  There's a patch ready in #302.  Just need to get that merged and published!

Going to close this now, since it's a dupe.

**Comment by jsonmaur** [comment]
Great, wasn't sure if it was a dupe or not. Appreciate the great work!
