### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by DaiQiangReal** [lerna/lerna#3062]
Is this project dead? Since there were 0 commit for half a year 。

**Comment by JackHowa** [comment]
Yeah I wasn't sure as well. I noticed the author listed a bio of "burned out OSS maintainer". We definitely want to be respectful in this respect

**Comment by leerle** [comment]
>

Where did the author say that. I was wondering if I could get the address to look it

thank you

**Comment by JackHowa** [comment]
https://mobile.twitter.com/evocateur @leerle

**Comment by Kikobeats** [comment]
main issue for this: https://github.com/lerna/lerna/issues/2703

**Comment by phillipplum** [comment]
I think this is the answer of your question @DaiQiangReal: https://mobile.twitter.com/evocateur/status/1483311321860886530

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.
