### ISSUE TITLE
--ignore doesn't seem to apply to lerna exec

### ISSUE THREAD

**Issue by ianwremmel** [lerna/lerna#307]

**Comment by rygine** [comment]
as per the CLI help:

```
  --ignore [glob]      Ignores packages with names matching the given glob (Works only in combination with the 'bootstrap' command).
```

the `ignore` flag is only supported in the bootstrap command. submit a PR to add support for the exec command! 😄

you may also be able to use a negative glob to achieve the same effect with the `scope` flag.

**Comment by steelbrain** [comment]
I've added ignore support to `exec` command in our fork of lerna in https://github.com/motion/lerna/pull/3
You are welcome to reopen it against this repo :)

**Comment by gigabo** [comment]
@steelbrain That would be great to have in Lerna.  Why only patch in your fork?

**Comment by steelbrain** [comment]
I'll upstream all the changes soon, currently fixing everything that's directly affecting our company stuff :)

**Comment by DavideDaniel** [comment]
Still doesn't work for exec.. or possibly it doesn't work in tandem with --since
