### ISSUE TITLE
Lerna bootstrap doesn't consider root directory package.json

### ISSUE THREAD

**Issue by silverbucket** [lerna/lerna#3070]
## Expected Behavior

`lerna bootstrap` should not just install each of the `packages/**/package.json` but also the root package.json if it exists.

## Current Behavior

Each of the subpackages get their dependencies installed, however the root of the repository does not. This means a separate `yarn install` is required in the root directory - however, if `yarn install` is defined in the package.json as `lerna bootstrap` this becomes an issue, as adding a `yarn install` would create an endless loop.

The only workaround I could find was to come up with a new dependency install name `yarn run deps` which runs `yarn install && lerna bootstrap`

## Possible Solution

If `lerna bootstrap` also considered a root package.json, this wouldn't be an issue.

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
