### ISSUE TITLE
`lerna exec` argument processing error

### ISSUE THREAD

**Issue by Mertico** [lerna/lerna#3087]
## Current Behavior
Run commnad
`"build": "lerna exec --parallel -- tsup ./index.ts --clean --minify --sourcemap --dts --format esm,cjs --watch --onSuccess \"npm -v\"",` 

In the final execution of the command, running onSuccess after assembly will be called with an error due to the loss of quotes in the argument.  Exec npm without -v arg.

## Possible Solution
Wrap arguments that include spaces in quotation marks

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | any |
| `yarn --version` | any |
| `node --version` | any |

**Comment by ghiscoding** [comment]
@Mertico you can use the single quote instead, see this other [issue](https://github.com/lerna/lerna/issues/1965#issuecomment-480817161), also note that Lerna is no longer maintained but you're welcome to use [Lerna-Lite](https://github.com/ghiscoding/lerna-lite) which is a new fork with a little less commands or switch to other tools. Cheers

**Comment by JamesHenry** [comment]
Hi Folks 👋 

I am going to close this one as rewriting the command to use an applicable set of quotes was the solution.

Many thanks!
