### ISSUE TITLE
Support a `lerna export` capability

### ISSUE THREAD

**Issue by scriptjs** [lerna/lerna#309]
Monorepos are great but there are times you may not wish to expose an entire code base to a developer to have them work on a  package. Temporary help or contracting are possible examples.

For the scenario where a developer is asked to start a new package, we have `lerna import` so the code and its history can come into the monorepo at some point in time when the person has completed the work.

If the package was previously started, there is currently no help in lerna. By supporting a `lerna export` capability, the package could be extracted from the repo with its history – then imported back into the monorepo at a later time, incorporating its full history following the completion of the work.

git subtree or git filter-branch seem reasonable candidates for doing this.

**Comment by thejameskyle** [comment]
I don't know if I'd suggest using Lerna in that way. However, I do like `lerna export` for other reasons.

As I've said elsewhere I like the quality that lerna is easy to opt-out of. Having a `lerna export` command that maintains history would be cool.

**Comment by thejameskyle** [comment]
Oh wait, I don't see a way for that to work. Commits can easily and often touch things outside of a single package so you'd have no way of cleanly splicing them.
