### ISSUE TITLE
How to unpublish?

### ISSUE THREAD

**Issue by ZinLiao** [lerna/lerna#3099]
## Expected Behavior

support "lerna unpublish"

## Current Behavior

unsupport

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by JamesHenry** [comment]
Hi @ZinLiao there are no special lerna concerns when it comes to unpublishing a package. You simply run `npm unpublish` by following the documentation and guidance from npm https://docs.npmjs.com/cli/v9/commands/npm-unpublish (making sure to align the docs to the specific version of npm you are using.
