### ISSUE TITLE
--skip-npm for "lerna bootstrap"?

### ISSUE THREAD

**Issue by bebraw** [lerna/lerna#310]
I realized `lerna bootstrap` triggers `prepublish` per each package (happens because the way `prepublish` has been [defined by npm](https://github.com/npm/npm/issues/3059), it gets called on `npm install`). The problem is that I've set  up [an aggregate package](https://github.com/reactabular/reactabular/tree/master/packages/reactabular) that generates a `dist` build at the project root and then updates that. So if I trigger `lerna bootstrap`, that happens too. Not ideal.

How would you suggest I solve this? I'll try setting up [in-publish](https://www.npmjs.com/package/in-publish) for now, but a better solution would be nice. Perhaps `lerna bootstrap --skip-npm` would be alright as it could skip hooks like that perhaps.

**Comment by gigabo** [comment]
@bebraw Did the `in-publish` workaround get you past this?

**Comment by bebraw** [comment]
@gigabo Yeah. You can see my approach [here](https://github.com/reactabular/reactabular/tree/master/packages/reactabular). See package.json for details.

I'm not sure if that's the right way, but it works for me.

**Comment by gigabo** [comment]
Thanks @bebraw that looks like a reasonable workaround.  Maybe not ideal, but pretty straightforward.  The aggregate package setup you're using here strikes me as not so common.  I think unless this comes up again we can leave it at that.  Please reopen if you disagree.

**Comment by bebraw** [comment]
Yeah, it's ok. :+1:
