### ISSUE TITLE
Generate Index For Exposed CSS

### ISSUE THREAD

**Issue by nruhe** [lerna/lerna#311]
It has become common practice to expose a package's main CSS file via the `style: ''` descriptor in _package.json_. I know that several of our packages expose a CSS file in addition to the main JS file. Lerna should generate an additional _index.css_ file that uses the `@import` syntax to link to the file pointed to in _package.json_. Bonus points if it could be flexible enough to support sass and less files as well (there are some bad habits in our repo...).

**Comment by nruhe** [comment]
I'd be willing to submit a pull request with this feature since our use of Lerna is going to be contingent on its support.

**Comment by boxxxie** [comment]
seems like this would be an easy fix, in the code there are only 2 files copied, index.js being one of them. could add a line that also copies a styles.css file as well

**Comment by gigabo** [comment]
> It has become common practice to expose a package's main CSS file via the style: '' descriptor in package.json.

Whoa, that's cool.  I hadn't seen that, but it makes sense.  Any reading you can recommend?

> I'd be willing to submit a pull request

Awesome!

**Comment by boxxxie** [comment]
I'm actually working on a pr. I don't like the way it's going, but basically I'm checking for a source file and then copying it.  I think it would be better to pull in the package. json file and copy listed file mentioned in it. any recommendations?

**Comment by boxxxie** [comment]
i'm editing the PR to use the package.json file like in the first comment

**Comment by boxxxie** [comment]
i'm getting these eslint errors
```
Suspicious state from syntax checker javascript-eslint: Checker javascript-eslint returned non-zero exit code 1, but no errors from output: Cannot find module 'eslint-config-babel'
Referenced from: /home/pauli/lerna/.eslintrc
Error: Cannot find module 'eslint-config-babel'
Referenced from: /home/pauli/lerna/.eslintrc
    at Object.ModuleResolver.resolve (/usr/lib/node_modules/eslint/lib/util/module-resolver.js:75:19)
    at resolve (/usr/lib/node_modules/eslint/lib/config/config-file.js:479:33)
    at load (/usr/lib/node_modules/eslint/lib/config/config-file.js:496:24)
    at /usr/lib/node_modules/eslint/lib/config/config-file.js:392:36
    at Array.reduceRight (native)
    at applyExtends (/usr/lib/node_modules/eslint/lib/config/config-file.js:363:28)
    at Object.load (/usr/lib/node_modules/eslint/lib/config/config-file.js:530:22)
    at loadConfig (/usr/lib/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/usr/lib/node_modules/eslint/lib/config.js:136:23)
    at Config.getConfig (/usr/lib/node_modules/eslint/lib/config.js:263:22)

Checker definition probably flawed.
```

**Comment by gigabo** [comment]
@boxxxie - That's a [recent addition](https://github.com/lerna/lerna/pull/291) to Lerna.  You might need to `npm i` to pick it up.

```sh
$ grep eslint-config-babel package.json
    "eslint-config-babel": "^1.0.1",
```

**Comment by boxxxie** [comment]
i wasn't able to fix the errors. totally breaks my emacs.

i think the code changes are good enough for you guys. i think that this doesn't effect the huge refactor of the bootstrap very much.

**Comment by boxxxie** [comment]
if anyone else is interested, my PR is getting errors on windows... i'm not sure how to fix them, i don't have a windows dev box either. 
I will not be able to fix these errors, and i am happy using my branch as i only care about linux and mac systems.

**Comment by nruhe** [comment]
@gigabo Admittedly, it seems to be a generally accepted but not discussed standard. What informed me about it was the commit that added it to the bootstrap library, which linked to [this](http://techwraith.com/your-css-needs-a-dependency-graph-too/) blog post. Since then, I've seen it in multiple CSS based npm libraries, especially icon-font libraries.

**Comment by gigabo** [comment]
Thanks for the link @nruhe.  Does @boxxxie's PR look like it provides what you're looking for?

**Comment by nruhe** [comment]
I don't think so. Correct me if I'm wrong, but isn't @boxxxie ripping the contents from the CSS files and combining them into a single CSS file that gets included in the requiring module's node_modules folder? If so, that kind of defeats the purpose of bootstrapping since you will have to rerun bootstrap every time you make a change. We should be making an index css file that uses [@import](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) to point to the exposed CSS file, as I mentioned above so that CSS changes get immediately updated in all requiring apps. Also, just like the main definition, which only allows you to specify a single path to the primary JS file for your application, style should not take an array, but rather a single file-path.

**Comment by boxxxie** [comment]
I'm not doing that. I'm preserving the files, no modification is taking place.

**Comment by boxxxie** [comment]
if I had a move file command, I would have used it

**Comment by boxxxie** [comment]
style is sorta a placeholder name.  any filename you put in there will be moved. in a future patch this will be redundant as the whole module will be symlinked.

**Comment by nruhe** [comment]
My mistake @boxxxie, I only had time to quickly skim the changes. Still, I think we should try to keep to the traditionally standard behavior of exposing a single file rather than an array. And either way, doesn't copying a file like that still run into the earlier issue I mentioned? Even if we will be replacing this with symlinks later, it doesn't change the fact that the behavior should be consistent with what's already there.

**Comment by boxxxie** [comment]
I can add a test for string and convert it to an array.

**Comment by boxxxie** [comment]
@nruhe i implemented your request.
i didn't add a test for it. feel free to add one. i have a feeling that this PR isn't getting merged

**Comment by gigabo** [comment]
Hi @nruhe, this should work for you in `lerna@2.0.0-beta.28`, which includes #237.

If you get a chance, please verify and close if so.

**Comment by nruhe** [comment]
I'll verify this tonight.

**Comment by thejameskyle** [comment]
This should work now that Lerna bootstrap uses symlinks
