### ISSUE TITLE
Announcement: Passing the torch

### ISSUE THREAD

**Issue by evocateur** [lerna/lerna#3121]
Howdy folks! I have some exciting news to share, as alluded to in the title.

First, some long-delayed closure: Effective today, **I am stepping down as lead maintainer of Lerna**. I will transition to an "emeritus" status, and largely end any remaining day-to-day responsibilities. I won't be able to pick up any threads dropped, and for that (among many other things), I sincerely apologize.

Burnout is real, friends, so I'll keep this brief.

I want to thank all past contributors to Lerna for helping make it what it is today. I am so grateful to the Lerna community for trusting me; for your patience and understanding. Maintaining Lerna has been one of the most challenging, far-reaching, and rewarding experiences of my career. I couldn't have done it without all of you.

So, here's the announcement, effective immediately:

# [Nrwl](https://nrwl.io/) is taking over stewardship of Lerna

One of my recurring nightmares, when considering who to pass the burden of maintenance onto, was that I chose wrong, enabling some nefarious scoundrel to inject a bitcoin miner (or some other disastrous toolchain attack) into Lerna. We've had enough examples over the years of well-meaning, smart folks making one tiny mistake and causing lots of pain in the package ecosystem.

However! I am truly excited that Nrwl has stepped up to take ownership of Lerna's future. Nrwl, for those that don't know, is the company behind [nx](https://nx.dev/), a tool I've already recommended to many folks [looking for a Lerna replacement](https://github.com/lerna/lerna/issues/2703#issuecomment-1021733489). They really [_get_](https://monorepo.tools/) monorepos, y'know? They're also committed to healthy open source, which is extremely important to me.

One of the biggest arguments in favor of Nrwl stewarding future Lerna development, in my mind, is that they represent corporate sponsorship from a company _well-aligned_ with the goals of Lerna itself _and_ the community of multi-package monorepo enthusiasts. Because so much of Lerna 3 was effectively subsidized by my former employer, I believe this bodes well for the health of the project.

I will leave further details (spoiler: _a roadmap!_) to be announced by @nrwl folks (@jeffbcross et al), just wanted to get the message out.

**Comment by goldhand** [comment]
Thank you so much @evocateur for your work on this paradigm-shifting, game-changing, revolutionizing work! You're truly one of the giants who's shoulders we build software on. I hope you enjoy some well-earned rest and relaxation.
Cheers 🍻

**Comment by jeffbcross** [comment]
Thanks, @evocateur for your work pioneering monorepos in JS! We're excited to get our hands dirty, and to start working on a roadmap with the community!

**Comment by gziolo** [comment]
Exciting news! Thank you, @evocateur, for all the fantastic work on the project. It's been a massive help for the WordPress project to maintain publishing over 80 packages with independent versioning for the last few years 🎉

**Comment by LoicPoullain** [comment]
Glad to see this! A big thank you to you @evocateur  for the work you have done over the last few years and for the transition you are making. I've been using lerna for the past four years to deploy [FoalTS](https://github.com/FoalTS/foal) packages and it has always worked very well. Many thanks to you!

**Comment by wesleygrimes** [comment]
Great news! Thanks for the hard work over the years @evocateur! Congrats to @jeffbcross and team.

**Comment by lirantal** [comment]
Thank you @evocateur and many appreciation for all the hard work put into open source maintenance ❤️

**Comment by abarke** [comment]
Thanks @evocateur for your hard work and commitment to OSS. I know it hard to pass the baton, but you rightfully did it 👊 
Live long and prosper Sir 🖖

**Comment by nicojs** [comment]
Thanks for all the hard work @evocateur! Bless you, and I hope you recover well from your burnout.

**Comment by ThisIsMissEm** [comment]
Thanks for all your work over the years @evocateur! You've had a lasting impact and always done your best!

@ nrwl, I'd still be happy to stay on as a contributor, even though I've not had the time to contribute actively over the past few years

**Comment by mwood23** [comment]
@evocateur Fantastic work maintaining this over the years. Can't tell you how helpful this package has been for my development workflow. Wish you all the best in the future!

**Comment by radiorz** [comment]
That is great!

**Comment by vladdof** [comment]
Thanks for all your work over the years @evocateur :fire:

**Comment by davedx** [comment]
Just want to say thanks for making and maintaining `lerna`, I often have to fight to advocate monorepos, and if tools like lerna didn't exist I think defending my position would have been that much harder. Great work, and thanks for all the fish!

**MONOREPOS RULE**

#MONOREPOS 4LIFE

**Comment by porkus1990** [comment]
Thank you both @evocateur and Nrwl. Great news

**Comment by xff1874** [comment]
Thank you for all your hard work.

**Comment by kuhe** [comment]
This is the corresponding announcement from Nrwl: https://blog.nrwl.io/lerna-is-dead-long-live-lerna-61259f97dbd9

> in the coming weeks, we are going to define a set of action items, prioritize them and elaborate a proper roadmap as well, which we will share with the community as soon as we have a more concrete plan. Since we know many organizations still depend on Lerna or may not be able to migrate away soon, some of our immediate to mid-term actions will be to provide critical bug fixes and security updates to the project and regularly release those to NPM.

I'd like to link to their "roadmap" from this issue when it is ready.

**Comment by juristr** [comment]
@kuhe I will make sure to link it here once it is ready. We already started doing some cleanup, version bumps etc. on the repo 😄

**Comment by DennisKuhn** [comment]
Thank you @evocateur for running this awesomest tool for so long and thanks a lot for @Nrwl taking it on ;-)

**Comment by dearsaturn** [comment]
Thank you for all of your hard work, everything you've done is truly appreciated, and this decision is admirable to say the least.

**Comment by InBrewJ** [comment]
You are one of my all time favourite OSS heros, thanks @evocateur!

**Comment by ntedgi** [comment]
Thanks 🙏 @evocateur

**Comment by koolamusic** [comment]
Amazing and welldone @evocateur for all the hard work put into lerna. Can't wait to see how @jeffbcross and the Nrwl team pioneer the next frontiers for lerna.

**Comment by iroy2000** [comment]
Thanks @evocateur for all the contributions into Lerna!

**Comment by juristr** [comment]
Hey all, we just released Lerna v5. It is a "maintenance release" but we bumped the major just to be cautious. Here are some more details:
https://twitter.com/NxDevTools/status/1529136719471079424

Let us know if you face any issues

**Comment by juristr** [comment]
And here comes the new announcement 🎉. We just published 5.1 beta with some huuuuge speed improvements 🚀 

All the details here:
https://blog.nrwl.io/lerna-used-to-walk-now-it-can-fly-eab7a0fe7700?source=friends_link&sk=6c827ec7c9adfc1c760ff2e3f3e05cc7

If you try it out on your Lerna repo, plz let us know how it goes.

**Comment by acikgozb** [comment]
Awful article title disrespecting all the past work. Where's the thumbs down button?

**Comment by acikgozb** [comment]
> And here comes the new announcement 🎉. We just published 5.1 beta with some huuuuge speed improvements 🚀
> 
> All the details here: https://blog.nrwl.io/lerna-used-to-walk-now-it-can-fly-eab7a0fe7700?source=friends_link&sk=6c827ec7c9adfc1c760ff2e3f3e05cc7
> 
> If you try it out on your Lerna repo, plz let us know how it goes.

Awful article title disrespecting all the past work. Where's the thumbs down button?

**Comment by juristr** [comment]
@acikgozb I'm sorry if this came over as disrespectful. That was for sure never the intention. If you read our messaging, we highly respect the previous maintainers' work and effort that went into building Lerna. Open source is at the core of the work we do, so we know how hard it is.

I can see how the title might have been interpreted that way, so quickly changed it 😃. Thx for reaching out 🙇

**Comment by DennisKuhn** [comment]
@juristr I perceived it positive and respectful, thanks for continuing this project :-)

**Comment by eyaldar** [comment]
> And here comes the new announcement 🎉. We just published 5.1 beta with some huuuuge speed improvements 🚀
> 
> All the details here: https://blog.nrwl.io/lerna-used-to-walk-now-it-can-fly-eab7a0fe7700?source=friends_link&sk=6c827ec7c9adfc1c760ff2e3f3e05cc7
> 
> If you try it out on your Lerna repo, plz let us know how it goes.

Hi, can't find this version in npm, also, lerna used to write in the logs which workspace initiated the action and logs, this is missing (at least from the alpha), is that something you plan on bringing back?

as an example, output from v4:

![image (9)](https://user-images.githubusercontent.com/5829836/170955255-7318248a-61e0-47ed-8a9d-80bdc33f2652.png)

output from v5.1-alpha.0:

![image](https://user-images.githubusercontent.com/5829836/170959291-7f80e7e7-8ae0-4a4b-bc85-a8711916bd56.png)

Also, it seems that "--stream" is not respected

**Comment by juristr** [comment]
yeah sorry my bad. We went with alpha :) => [5.1.0-alpha.0](https://www.npmjs.com/package/lerna/v/5.1.0-alpha.0)

**Comment by jessebond2** [comment]
Thanks for the great tool and all the hard work @evocateur! You gotta do what's best for you at the end of the day 😃

**Comment by TerryZ** [comment]
Thanks for all your work.

**Comment by StevenX911** [comment]
Thanks for all your work over the years @evocateur

**Comment by donatocayurin** [comment]
Thank you ❤️🙏

**Comment by donatocayurin** [comment]
❤️🙏
