### ISSUE TITLE
WSL2 Lerna Bootstrap lacking permission

### ISSUE THREAD

**Issue by zainen** [lerna/lerna#3125]
I cant seem to find an answer so am hoping for a little guidance. 

I cannot run lerna bootstrap on my ubuntu 20.04 container on my WSL2  in windows

## Expected Behavior
should build the node_modules for each of the packages in the project

## Current Behavior
`
 sudo npm run bootstrap

> @ bootstrap /home/zainen/code/taquito
> lerna bootstrap

lerna notice cli v4.0.0
lerna info Bootstrapping 20 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in 'integration-tests'
lerna ERR! npm install stdout:

> node-hid@2.1.1 install /home/zainen/code/taquito/integration-tests/node_modules/node-hid
> prebuild-install --runtime napi || node-gyp rebuild

lerna ERR! npm install stderr:
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config libusb-1.0 --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.10.102.1-microsoft-standard-WSL2
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/zainen/code/taquito/integration-tests/node_modules/node-hid
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@2.1.1 install: `prebuild-install --runtime napi || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-hid@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-11T17_01_33_523Z-debug.log
lerna ERR! npm install exited 1 in 'integration-tests'
lerna WARN complete Waiting for 5 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-11T17_01_33_573Z-debug.log
`

## Steps to Reproduce (for bugs)
1. git clone git@github.com:ecadlabs/taquito.git
2. cd <directory of clone>
3. npm install
4. npm install -g lerna
5. npm run bootstrap | lerna bootstrap --force-local

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

trimmed a lot for browser
```txt
1189 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
1190 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
1191 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
1191 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
1191 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
1191 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
1192 verbose stack Error: node-hid@2.1.1 install: `prebuild-install --runtime napi || node-gyp rebuild`
1192 verbose stack Exit status 1
1192 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
1192 verbose stack     at EventEmitter.emit (events.js:198:13)
1192 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1192 verbose stack     at ChildProcess.emit (events.js:198:13)
1192 verbose stack     at maybeClose (internal/child_process.js:982:16)
1192 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
1193 verbose pkgid node-hid@2.1.1
1194 verbose cwd /home/zainen/code/taquito/integration-tests
1195 verbose Linux 5.10.102.1-microsoft-standard-WSL2
1196 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
1197 verbose node v10.19.0
1198 verbose npm  v6.14.4
1199 error code ELIFECYCLE
1200 error errno 1
1201 error node-hid@2.1.1 install: `prebuild-install --runtime napi || node-gyp rebuild`
1201 error Exit status 1
1202 error Failed at the node-hid@2.1.1 install script.
1202 error This is probably not a problem with npm. There is likely additional logging output above.
1203 verbose exit [ 1, true ]

```
</p></details>

## Context
One of the Devs on Taquito. newer to coding on wsl however not sure how different it would be from linux having a similar issue since all the files are contained inside of the ubuntu container

## Your Environment

windows 10 
WSL2 ubuntu20.04

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 8.9.0 |
| `yarn --version` | NA |
| `node --version` | v16.15.0 |

| Windows 10 | 21H2 |
| WSL2 | Ubuntu | 20.04 |

**Comment by JamesHenry** [comment]
Hi @zainen, I am not a WSL developer so have no way to reproduce this directly.

However, I can see in your WSL logs that (in contrast to what you have written on this issue), the node and npm versions you are interacting with are:

```
1197 verbose node v10.19.0
1198 verbose npm  v6.14.4
```

These are very old, and no longer supported (neither by node themselves, nor us on lerna).

I would suggest that look into troubleshooting why your WSL container might be running an older version of node when compared to your Windows OS.

It's likely that if you can get your WSL container to use the modern versions of node and npm, that things will work as you expect.

Best of luck!
