### ISSUE TITLE
Trying to run/test my branch of lerna

### ISSUE THREAD

**Issue by boxxxie** [lerna/lerna#313]
i'm not clear how to do this. when i see the files that are part of the lerna command line util, there is a `lib` folder, and the lerna.js file uses this lib folder (it's almost the `src` folder). how do you make this folder, or how do i build lerna so that i can use my own version of it?

**Comment by boxxxie** [comment]
ok, solved this issue
i have to build lerna using itself `npm run build`
then i have to remove the lib folder from .gitignore so i can push to github

is there a better way someone can offer me?

**Comment by hzoo** [comment]
Right `npm run build` does `"build": "babel src -d lib",` which compiles everything in src into `lib`.

Why do you need to push lib to github? Oh, well we modify the `src` files even though we are eventually running the lib files.

**Comment by gigabo** [comment]
@boxxxie Sounds like you got this figured out.  The source is in `src`, but the published module uses `lib`, which is build by babel.  You can `npm run build` (or `npm install`) locally to compile.
