### ISSUE TITLE
[Support] How to use grunt plugins that call npm.commands.install?

### ISSUE THREAD

**Issue by hugoduncan** [lerna/lerna#314]
I have some packages that use a grunt plugin to deploy to aws-lambda.  The plugin works by calling `npm.commands.install` to build a directory with all the package's dependencies, that it then zips.

The plugin fails to run, because `npm.commands.install` fails to find sibling packages that are `dependencies`.

Is there some any way of getting this to work at the moment?

**Comment by gigabo** [comment]
Hi @hugoduncan, not sure if Lerna has a solution for that, actually.

The deps on sibling packages are linked by lerna during `bootstrap`, but as far as `npm.commands.install` is concerned they're just normal deps.  So, unless you've just published you won't get up-to-date modules.

**Comment by thejameskyle** [comment]
Yeah I have no idea how to solve this without forcing things to become published packages.

Maybe you could update your tooling to use Lerna internally?
