### ISSUE TITLE
Lerna publish command hangs in terminal

### ISSUE THREAD

**Issue by damilareolowoniyi** [lerna/lerna#3143]
## Expected Behavior
when I run the command `lerna publish
`  it should publish the packages to www.npmjs.com 
## Current Behavior
Instead the command hangs after the it starts to package the component 

```
lerna WARN ENOLICENSE One way to fix this is to add a LICENSE.md file to the root of this repository.
lerna WARN ENOLICENSE See https://choosealicense.com for additional guidance.
⸨     ░░░░░░░░░░░░░⸩ ⠸ publish: verb packed src/modules/examples/component

```
its stops at `⸨     ░░░░░░░░░░░░░⸩ ⠸ publish: verb packed src/modules/examples/component
` and literally does nothing 

## Steps to Reproduce (for bugs)

1 run `lerna publish` 

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "src/modules/examples/*"
  ],
  "version": "independent",
  "npmClient": "npm",
  "publish": {
    "ignoreChanges": [
      "ignored-file",
      "*.md"
    ],
    "message": "chore(release): publish",
    "registry": "https://npm.pkg.github.com/xxxxx"
  },
  "repository": "https://github.com/xxxx/xxxxx"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>
I dont get any errors 
```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context
Im simply trying to publish the packages. Not sure why it keeps hanging when i run the command

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 8.3.1 |
| `yarn --version` | 1.22.17 |
| `node --version` | v16.14.0 |

| OS | Version |
| --- | --- |
 
| macOS Monterey | 12.3.1 |
 
-->

**Comment by damilareolowoniyi** [comment]
hey @nelson6e65 i resolved the issue by upgrading the version yesterday. Ill close this ticket.

**Comment by VictorOnwukwe** [comment]
Hey @damilareolowoniyi I'm experiencing this exact issue, and I've upgraded to the latest lerna version (6.1.0) and it's still getting stuck. Please what version of lerna did you upgrade to? And did you retain the node version 16.14.0 in your successful run?
