### ISSUE TITLE
More accurate explanation of recommended version  is needed in v5 release note.

### ISSUE THREAD

**Issue by akasai** [lerna/lerna#3144]
## Expected Behavior
More accurate explanation of recommended version  is needed in v5 release note.

## Current Behavior
In v5.0.0 [release note](https://github.com/lerna/lerna/releases/tag/v5.0.0), explain recommend version.
```
Node v10.x and v12.x are no longer supported.

Please upgrade to the latest LTS release of Node (we recommend either v14 or v16).
```

But actual warning message shows more accurate version. (In my case, using Node 14.15.4)
```
The engine "node" is incompatible with this module. Expected version "^14.19.3 || >=16.0.0". Got "14.15.4"
```

## Context
So I suggest fix recommend version more accurately (^14.19.3)

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 5.0.0 |
| `node --version` | 14.15.4 |

**Comment by nelson6e65** [comment]
Node 14.19.3 is the minimum version.

You should upgrade your Node.js to latest v14.x release.

**Comment by akasai** [comment]
@nelson6e65 Yes. i know
However, after reading the release note of v5.0.0, I thought it didn't matter.
Because minimum version was v14 and i thought v14 meant minor version of all v14.

My suggestion is that more accurate information should be displayed in the release notes.
So, the description of changing the recommended version should not be `recommended either v14 or v16` (above sentence), but `recommended either v14.19.3 or v16`.

**Comment by marcoreni** [comment]
Is this really necessary? Why it is required to use the latest NodeJS version? LTS tells us that there are no breaking changes in a major version...

**Comment by IlCallo** [comment]
LTS doesn't mean no more features
Some packages may rely on features which has been added into Node newer versions and backported in a minor patch into previous Node version
Eg. this happened for ESM support and many projects have a min Node version which is a late patch version of the v12 LTS

**Comment by nelson6e65** [comment]
Exactly! Maybe this tool need a minor feature added in [v14.19](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.19.0) which is not available in v14.18 or less.

Latest LTS v14 means the latest minor and patch from v14. As mentioned, there are not breaking changes between 14.0 and 14.19, just new minor features. So, in theory, is safe to update v14 to its latest patch in your server.

**Comment by akasai** [comment]
Guys!
I already know that I need to upgrade the Node version of my server. 
And I know what Node LTS version means.
But, many users may not be using the LTS version or higher for personal reasons. (just my opinion)

As above mentioned, I think the **purpose of the release notes is to deliver accurate and detailed information.**
Therefore, my suggestion is to change the **sentence more accurately that shows the recommended version.**

**Comment by nelson6e65** [comment]
I think this should be moved to Discussions. You can add a patch (PR) with that change (reduce minimum to 14.0.0) if this package does not require exactly the latest v14.19 patch and 14.0 is enough.

But that will require a **new release**. You can't change a release note, since it is part of the release itself.

**Comment by akasai** [comment]
@nelson6e65 It doesn't mean to reduce the minimum version. 
It means to provide more accurate information.

> But that will require a new release
But as you said, I think it need too much work, such as new release, for just my suggestion.
So, Close this issue.
