### ISSUE TITLE
lerna publish fails with latest version(v5.0.0)

### ISSUE THREAD

**Issue by raviteja83** [lerna/lerna#3146]
`lerna publish from-package --dist-tag latest --yes --no-verify-access`
This is the command that is used to publish to npm. This used to work before v5.0.0. 
## Expected Behavior

Publish packages to npm without any errors.

## Current Behavior

The publish command fails at prepare npm lifecycle which internally calls build command. 
`lerna run build --stream` does work.

**Additional Info:**
I have multiple packages in the repo. There is a package A that is dependent on package B. The folder name of package B is different from that of the package name mentioned in package.json. 
In the publish command, it is trying to get the package from npm via folder name instead of package name from package.json which is resulting in 404. It should not be trying to fetch from npm as the version of that package is not yet published. it is just updated with `lerna version` locally.

This used to work in previous version of lerna. Just updated to latest yesterday and this is broken.

<details><summary>lerna.json</summary><p>
{
  "packages": ["packages/*", "apps/*"],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "useNx": true,
  "command": {
    "version": {
      "message": "build: update version"
    },
    "publish": {
      "registry": "https://registry.npmjs.org/"
    }
  }
}

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 5.0.0 |
| `npm --version`  | 8.5.5 |
| `yarn --version` | v1.22.18 |
| `node --version` | 16.15.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by JamesHenry** [comment]
@raviteja83 i see you have useNx enabled - are you sure you are using 5.0.0? useNx did not exist in that version, so either that flag is doing nothing for you or you are using the prerelease of 5.1

If it is the latter, it would please be good to know if the behaviour is the same when disabling useNx

**Comment by raviteja83** [comment]
@JamesHenry I have tried by disabling the useNx flag as well. Still failing. 

**This is the scenario:** 
The folder name  of a package is test-package-web, package name is test-package in package.json, while building a package that is  depending on this, it is trying to find test-package-web in npm registry, which is returning 404.


on a sidenote, which version supports the useNx flag?

**Comment by raviteja83** [comment]
I have tried upgrading to the prerelease version as well. Same error there as well.

**Comment by raviteja83** [comment]
Working with 5.3.0

**Comment by JamesHenry** [comment]
Great, thanks for confirming @raviteja83! Sorry for the issue
