### ISSUE TITLE
npm doesn't resolve "^x.x.x-beta.x"

### ISSUE THREAD

**Issue by christophercliff** [lerna/lerna#315]
If you run `lerna publish --repo-version x.x.x-beta.x`, you can't install cross dependencies from npm. Does Lerna have a workflow for dealing with this use case?

Not necessarily a Lerna bug, feel free to close.

**Comment by gigabo** [comment]
Hi @christophercliff.  Not sure I understand.  What is failing?  Not the publish, but a subsequent bootstrap?  Or something else?  If you can provide an error message or, better yet, steps to reproduce the error that would help.

**Comment by christophercliff** [comment]
The above command will update `packages/*/package.json` with dependencies like `"my-package": "^x.x.x-beta.x"` (note the `^`). If I publish these packages to npm and then try to install something that depends on `my-package`, npm will fail because `^x.x.x-beta.x` doesn't resolve.

I saw you guys were using a similar version scheme and thought you might have automated that somehow.

**Comment by gigabo** [comment]
Do you mean _literal_ `x.x.x-beta.x`?

A version like `1.0.0-beta.3` should [satisfy](http://jubianchi.github.io/semver-check/) `^1.0.0-beta.2`.

![image](https://cloud.githubusercontent.com/assets/115908/18293281/b1b0b78e-7446-11e6-85c6-9b1c4c724da4.png)

**Comment by christophercliff** [comment]
I no longer have the error handy but it's possible this is on the npm side.

**Comment by gigabo** [comment]
Okay, going to close this for now.  @christophercliff if you run into this again please reopen and paste the error output (and steps to reproduce, if possible) here.
