### ISSUE TITLE
`lerna@5.1.1` still has vulnerable transitional dependency `ansi-regex@2.1.1`

### ISSUE THREAD

**Issue by vitoyucepi** [lerna/lerna#3165]
## Current Behavior

After installing `lerna` into a new project, vulnerable `ansi-regex` is still installed as a transitional dependency for chain `lerna > npmlog > gauge > strip-ansi > ansi-regex`.

I tried to discus this problem in #3010.

The cause of problem is outdated version of `npmlog@^4.1.2`.
Most of the `@lerna` namespace packages use outdated `npmlog`.

## Expected Behavior

I think `lerna` should update `npmlog@4.1.2` to at least `npmlog@5.0.0`.
This will update `ansi-regex@2.1.1` to `ansi-regex@5.0.1`

## Steps to Reproduce

1. `npm init`
1. `npm add lerna@5.1.1`
1. `npm list ansi-regex`

**Comment by JamesHenry** [comment]
Thanks for this @vitoyucepi, I still find it strange the `npm audit` no longer considers this an issue, perhaps it knows about the actual usage and didn't find lerna's code to be exposed.

Regardless I have gone ahead and updated all dependencies that transitively pulled in a version of ansi-regex which was not patched per the advisory notice.

It will go out in the next version of lerna

**Comment by vitoyucepi** [comment]
@JamesHenry I use snyk as an additional tool to maintain my own project. Though I can't really recommend it, because I haven't fully integrated it into the workflow.
