### ISSUE TITLE
Minor typo on lernajs.io

### ISSUE THREAD

**Issue by intrinsitech** [lerna/lerna#317]
From the homepage:

To solve these (and many other) problems, some projects will organize their codebases into multi-package **repostories**

**Comment by hzoo** [comment]
The website repo is https://github.com/lerna/website - feel free to make a pull request to change it!

**Comment by intrinsitech** [comment]
Awesome, will do. Thanks!

**Comment by hzoo** [comment]
https://github.com/lerna/website/pull/5
