### ISSUE TITLE
Lerna cannot build library generated by nx.

### ISSUE THREAD

**Issue by h3adache** [lerna/lerna#3191]
## Current Behavior

```
npx lerna run build
lerna notice cli v5.1.4

 >  Lerna (powered by Nx)   Cannot find project '@myorg/lib-test'
```
Interestingly, if you remove the scope from the package then it works fine.
But obviously that creates an issue when publishing the npm package to an org using that scope.

## Expected Behavior

Should not error 😄 

## Steps to Reproduce

1. create empty project
1. follow steps https://lerna.js.org/docs/getting-started
1. add `npmScope` to `nx.json`
1. create library `npx nx g @nrwl/js:lib lib-test --skipTsConfig --unitTestRunner none --config npm-scripts`
1. Run `lerna bootstrap`
1. Run `lerna run build`

https://github.com/h3adache/lerna-nx

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "useNx": true,
  "version": "0.0.0"
}
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

### Environment

```
lerna notice cli v5.1.4

 Environment info:

  System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 18.4.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.12.1 - /usr/local/bin/npm
  Utilities:
    Git: 2.36.1 - /usr/local/bin/git
  npmPackages:
    lerna: ^5.1.4 => 5.1.4
```

**Comment by JamesHenry** [comment]
Hi @h3adache, if you are making use of Nx generators and `nx.json` then you have the full power of the Nx task runner available to you already, and so it is not expected that you would be using `lerna run` in this scenario, you would instead use `nx run`.

`lerna run`, and being able to delegate some of its implementation details to Nx, are intended for cases where users are not leveraging the wider capabilities of Nx and using lerna as their primary monorepo tool.

Hope that makes sense, if you have issues with `nx run` then please kindly open an issue on https://github.com/nrwl/nx
