### ISSUE TITLE
Parallel commands with useNx

### ISSUE THREAD

**Issue by lukasbach** [lerna/lerna#3198]
> ### Discussed in https://github.com/lerna/lerna/discussions/3192
> 
> <div type='discussions-op-text'>
> 
> <sup>Originally posted by **lukasbach** June 20, 2022</sup>
> I have a lerna monorepo with a command that should run in all packages simultanuously, i.e. run a typescript watch server in all packages and keep them running indefinitely until they are stopped forcefully, with the code `lerna run start --scope=web --include-dependencies --parallel`. That works fine, but not anymore with switching the `useNx` flag to true, since then it only seems to run the first 3 packages (since the parallel max count is set to three) and then stalls because these 3 packages never end (by design). What is the intended way of getting these always-running commands to work that should run on more than 3 packages with the useNx flag?
> 
> Also, slightly unrelated, if I would switch the command from lerna to nx run-many, is there a way to replace the `--include-dependencies` with something supported by nx so I can only specify one package and it will automatically run all its transitive dependencies?
> 
> Thanks in advance!</div>

I've created an issue for now since, after further investigations, that does seem like a regression to me. From what I read, `useNx` should not break existing commands, but to me it looks like the `--parallel` argument is not respected as it was before when nx is enabled for lerna.

**Comment by nicholasgriffintn** [comment]
I am getting this as well, I only noticed today after updating, while using 'useNx: true`, only the first 3 packages will be ran in parallel.

**Comment by JamesHenry** [comment]
Thanks folks, I have merged a fix to address this, I will release it now

**Comment by philipduiqmetrix** [comment]
@lukasbach @nicholasgriffintn  Can you confirm if this fix resolved the issue for you? As i update the dependencies to try this and it doesn't work if i run `lerna run start --parallel` but the build script using nx cache feature is working well
