### ISSUE TITLE
How to enable "nx generators" to a "lerna" project

### ISSUE THREAD

**Issue by prakashraman** [lerna/lerna#3202]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

From the [documentation](https://nx.dev/getting-started/nx-setup#add-nx-to-an-existing-project) I see that there is an `nx` command to setup `nx` for a `lerna` project

```
npx nx add-nx-to-monorepo
```

Which does executed successfully, however, I don't see the folder structure that the above documentation page mentions

_note: I did not choose "nx cloud" option_

```
myorg/
├── apps/
├── libs/
├── tools/
├── workspace.json
├── nx.json
├── package.json
└── tsconfig.base.json
```

----
In particular, I am looking to use the "generator" workflow of "nx" and I am unable to get that to work.

Is there a different way I should set this up?

Thanks

**Comment by JamesHenry** [comment]
Hi @prakashraman in this setup you have everything you need to use nx generators, you can take a look at the page for nx generate here: https://nx.dev/cli/generate

Essentially the usage is:

```sh
nx generate [plugin]:[generator-name] [options]

# E.g. for react
nx generate @nrwl/react:component mycmp --project=myapp
```

So the only thing you need to do next is decide what kind of things you want to generate and see if there is an existing Nx Plugin for that.

The Nrwl team manage many plugins for popular tools directly:

![image](https://user-images.githubusercontent.com/900523/175552830-d2dbfe50-d057-4062-9c9e-504c2f28bcb9.png)


(Screenshot taken from sidebar of nx.dev)

And there is a an ever growing list of community maintained plugins too!

You can search on here: https://nx.dev/community

Once you have decided on what plugins you want want to use, you just need to install them.

E.g.

```sh
npm i -D @nrwl/react
```

If you go for official `@nrwl/...` plugins make sure you use the exact same version as the version you have for the `nx` package in your package.json

Hope that helps! 🙏

**Comment by JamesHenry** [comment]
P.S. I notice you said "but I couldn't get that to work" - if you run into issues running generators then please report those on the Nx repo directly: https://github.com/nrwl/nx/issues/new/choose
