### ISSUE TITLE
Feature: Upgrade `@lerna/prompt` to inquirer `v9`

### ISSUE THREAD

**Issue by Julien-Marcou** [lerna/lerna#3210]
## Description

Upgrade `@lerna/prompt` to inquirer `v9`

## Motivation

Inquirer v7 uses RxJS v6, wich uses tslib v1.

Upgrading to Inquirer v9 would upgrade RxJS to v7 and tslib to v2.

This would allow for cleaner node_modules dependencies for modern projects, as of now, I'm manually adding `"tslib": "^2.0.0"` to my projects, which means I have tslib 1 et tslib 2 installed in the node_modules folder.

**Comment by ghiscoding** [comment]
that is probably not doable at this point and probably won't be for a long time, since v9 is ESM only and the project is not setup to use ESM only dependencies, latest version that can be used is the one before it which is v8.2.3

**Comment by Julien-Marcou** [comment]
That is a problem indeed, unless we can import `inquirer`  inside an `async` function.

But migrating to ESM would even be better 😄

**Comment by jordanmbell** [comment]
Upgrading to 8.2.3 would also fix this problem, as the dependency was updated before the v9 upgrade. The breaking change to version 8 was dropped support for node 10, which is already unsupported in lerna.

https://github.com/SBoudrias/Inquirer.js/blob/9baee326b04b4e8565e815b1fa577c36e0b93727/packages/inquirer/package.json#L51

**Comment by ghiscoding** [comment]
As a side note, I have already upgraded to v8.2.4 of Inquirer in [Lerna-Lite](https://github.com/ghiscoding/lerna-lite) which is the last non-ESM version. I have setup Renovate to run once a week in Lerna-Lite (perhaps they should do that in Lerna as well), which updates deps weekly (except for ESM because the project isn't ready for that either), I keep PRs in sync with Lerna as well.

**Comment by JamesHenry** [comment]
Hi folks, we just released version `5.2.0` of lerna: https://github.com/lerna/lerna/releases/tag/v5.2.0

Amongst other things, we bumped the `inquirer` version to `8.2.4`, which, as noted, is the latest version we can move to prior to going all-in on ESM.

Many thanks! 🙏

**Comment by Julien-Marcou** [comment]
Thanks 👍
