### ISSUE TITLE
Stdio is not inherited anymore in Lerna 5 

### ISSUE THREAD

**Issue by BenoitZugmeyer** [lerna/lerna#3214]
## Current Behavior

I am using a `version` npm script to open an editor and let the developer check and edit the CHANGELOG before a release. With Lerna 4, it worked flawlessly. Starting with 5.0.0, Lerna captures the standard input and output when running a npm lifecycle, so terminal editors like Vim don't show up anymore.

## Expected Behavior

Restore the Lerna 4 behavior. When running a npm lifecycle, stdio should be inherited so the script can be interactive. 

## Steps to Reproduce

Minimal example to reproduce: https://github.com/lerna/repro/pull/4

```
$ git clone https://github.com/BenoitZugmeyer/lerna-repro  
$ cd lerna-repro
$ npm i
$ npx lerna version --no-push --no-git-tag-version -y major                                                                                    
lerna notice cli v5.1.4
lerna info current version 0.0.0
lerna notice FYI git repository validation has been skipped, please ensure your version bumps are correct
lerna info Assuming all packages changed
lerna WARN version Skipping working tree validation, proceed at your own risk

Changes:
 - test: 0.0.0 => 1.0.0

lerna info auto-confirmed
lerna info execute Skipping git tag/commit
lerna info execute Skipping git push
lerna info execute Skipping releases
lerna info lifecycle lerna-repro@undefined~version: lerna-repro@undefined

> lerna-repro@undefined version /Users/benoit.zugmeyer/tmp/lerna-repro
> vim CHANGELOG.md
```
Then the script is stuck, vim does not show up.

### Notes

If you run the same steps but install Lerna 4 instead, it works as expected.

Changing `pipe` to `inherit` [here](https://github.com/lerna/lerna/blob/54b693d4029b942223f56380a23d43bb9d57180e/utils/run-lifecycle/run-lifecycle.js#L120) fixes the issue.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

Nothing special:

```json
{
  "packages": ["packages/*"],
  "version": "0.0.0"
}
```

</p></details>

### Environment

```
 Environment info:

  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.15.0 - ~/.volta/tools/image/node/16.15.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.5.5 - ~/.volta/tools/image/node/16.15.0/bin/npm
  Utilities:
    Git: 2.36.1 - /opt/homebrew/bin/git
  npmPackages:
    lerna: ^5.1.4 => 5.1.4
```

**Comment by ghiscoding** [comment]
I think the latest PR #3262 will fix your issue

**Comment by JamesHenry** [comment]
Thanks so much for the reproduction @BenoitZugmeyer!

#3262 won't fix this issue, as that only dealt with an issue I had observed on `lerna publish` (this repro deals with `lerna version`). I will work on a fix for this
