### ISSUE TITLE
Security: Authorization Bypass in parse-path via parse-url@6.0.2

### ISSUE THREAD

**Issue by danmarshall** [lerna/lerna#3227]
Dependabot is giving a moderate security alert on 

```
lerna@5.1.2 requires parse-path@^4.0.4 via a transitive dependency on parse-url@6.0.2
The earliest fixed version is 5.0.0

Authorization Bypass Through User-Controlled Key in GitHub repository ionicabizau/parse-path prior to 5.0.0.
```
Could be fixed by updating to `parse-url@7` ?

**Comment by BrianMcBrayer** [comment]
Looks like there's a PR in progress https://github.com/lerna/lerna/pull/3226

I was already 90% of the way to finishing up my PR when I saw this 🤦

**Comment by danmarshall** [comment]
Thanks @BrianMcBrayer , I'll close this since the PR predates my issue.
