### ISSUE TITLE
package scripts not executed since 5.1.3

### ISSUE THREAD

**Issue by simllll** [lerna/lerna#3233]
## Current Behavior

we have a mono repo with about 100 packages, 
running `lerna run build` does not execute all build scripts anymore since 5.1.3.

Even though the output is showing that it executes 100 packages, it does only run it in about half of it.
I tested it by putting "exit 1" inside of a build script of one packgae that wasn't executed, it fails (as supposed to) in 5.1.2, but runs wihtour any errors (and the script is therefore not executed) since 5.1.3.

## Expected Behavior

Should execute the defined script in each package, like the output even says.

## Steps to Reproduce

The issue causing this is this change here: https://github.com/lerna/lerna/pull/2874/files

Removing this check, fixes the issue for me.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
	"packages": [
		"packages/*",
		"services/*",
		"docs",
		"infrastructure/*"
	],
	"version": "independent",
	"command": {
		"publish": {
			"message": "chore: publish"
		}
	},
	"hoist": true,
	"forceLocal": true,
	"conventionalCommits": true,
	"reject-cycles": true,
	"ignoreChanges": ["**/__tests__/**", "**/*.md", "**/*.tmp"]
}
```

</p></details>

### Environment

 Environment info:

  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Utilities:
    Git: 2.32.0 - /usr/bin/git
  npmPackages:
    lerna: ^5.1.3 => 5.1.3

**Comment by simllll** [comment]
I ran into the same thing today again, but now I don't have any circular dependencies.. still not sure what's going on (lerna 5.2.0), but it's for sure that even though the package list on lerna run build --no-private says it has exectued the packages, it does not run the commands.

**Comment by simllll** [comment]
Alright, now I found the culrpitn again, it's still a dependency circle, BUT, since the last fix https://github.com/lerna/lerna/pull/2874 it doesn't show any dependecy circles anymore.
running `lerna bootstrap --npm-client=npm --use-workspaces=false --reject-cycles`
with lerna 5.0.0:
```
lerna ERR! ECYCLE Dependency cycles detected, you should fix these!
lerna ERR! ECYCLE @hokify/dashboard-announcement-service -> @hokify/dashboard-service -> @hokify/hubspot -> @hokify/dashboard-announcement-service

```

with latest lerna, no error message, and the weird behaviour that packages get skipped during execution.

Propoesd change: when running with reject-cycles, the alreadyVisited nodes check gets skipped?

**Comment by ghiscoding** [comment]
@simllll  perhaps the new PR #3262 from today has something to do with your issue?
