### ISSUE TITLE
jenkins CI  Error TS2307: Cannot find module '' or its corresponding type declarations.

### ISSUE THREAD

**Issue by DreamPWJ** [lerna/lerna#3239]
![image](https://user-images.githubusercontent.com/16730031/177899819-6650f045-f512-43ca-826c-1102b8c2be68.png)
![image](https://user-images.githubusercontent.com/16730031/177899836-c116bf82-540c-43b4-ae47-810f177658ee.png)
I have been clear that all kinds of caches still do not work。 use  lerna v5.1.8   run  ` lerna bootstrap --ci` 。It's good to work locally。

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
