### ISSUE TITLE
Lerna exec lies/fails to execute command in all packages when there is a cycle

### ISSUE THREAD

**Issue by alasdairhurst** [lerna/lerna#3242]
## Current Behavior

"useNx" is true in lerna.json config.

If I run `lerna exec -- npm pkg get name`, it get the following output:
Obviously 48 packages are not printed out here (even though it says so right at the end). There's no error that certain packages were skipped either. The warning about the dependency cycle is something we put up with for a while without issue so didn't seem related. `lerna run` seems to do the job right with cycles  but it seems like the cycle has a big impact on `lerna exec`.

```bash
lerna notice cli v5.1.4
lerna info versioning independent
lerna info Executing command in 48 packages: "npm pkg get name"
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE @axway/api-builder-sdk -> @axway/api-builder-test-utils -> @axway/api-builder-sdk
"@axway/api-builder-dc-sql-core"
"@axway/api-builder-oas-style"
"@axway/api-builder-config"
"@axway/api-builder-plugin-ft-cron"
"@axway/api-builder-plugin-ft-timer"
"axway-schema"
"@axway/api-builder-plugin-fn-dot"
"@axway/api-builder-project-utils"
"axway-flow-schema"
"@axway/api-builder-uri-utils"
"axway-flow-graph"
"@axway/requester"
"arrow-orm"
"@axway/api-builder-plugin-dc-mssql"
"@axway/api-builder-plugin-dc-mongo"
"@axway/api-builder-plugin-prometheus"
"@axway/amplify-api-builder-cli"
"@axway/api-builder-plugin-dc-mbs"
"arrow-admin-ui"
"openapi-doc"
"@axway/api-builder-plugin-dc-mysql"
"@axway/api-builder-plugin-dc-oracle"
"@axway/api-builder-openapi-upgrade"
"@axway/api-builder"
lerna success exec Executed command in 48 packages: "npm pkg get name"
```
Upon breaking the cycle by deleting a dependency, all 48 packages are listed.

## Expected Behavior

I expect `lerna exec` to either ensure all packages are executed regardless of cycle. (some sub optimal way, or exactly how lerna run works), or at the very least it should print additional warnings for skipped modules, or even terminate since it's not behaving as expected.

## Steps to Reproduce

I've created a simpler use case here. It can probably be simplifed further. I couldn't reproduce it with three packages.
https://github.com/lerna/repro/pull/6

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
	"npmClient": "npm",
	"packages": [
		"packages/*"
	],
	"command": {
		"bootstrap": {
			"nohoist": [
				"codemirror",
				"react-bootstrap-typeahead",
				"react-intl-loader"
			],
			"npmClientArgs": [
				"--no-package-lock"
			]
		}
	},
	"version": "independent",
	"useNx": true
}


```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```

</p></details>

### Environment

```
❯ npx lerna info
lerna notice cli v5.1.8
lerna info versioning independent

 Environment info:

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.6.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Utilities:
    Git: 2.35.1 - /usr/local/bin/git
  npmPackages:
    lerna: ^5.1.4 => 5.1.8 

```

**Comment by Sebi11** [comment]
Hi!
I have the same issue with the `lerna version` command, probably due to some circular dependencies... It was working fine with lerna 5.1.2 though.

**Comment by ghiscoding** [comment]
It might have been fixed in `v5.4.0`, see this [comment](https://github.com/lerna/lerna/issues/3261#issuecomment-1208181095).

If it's still a problem, then it might be related to this other open issue #3233 with a possible solution #3234 you could try to apply the code change to confirm if it works and advise maintainers

**Comment by turadg** [comment]
Works for me in 5.6.2.

**Comment by fahslaj** [comment]
This appears to be working in the latest (v7.1.4) as well. I am closing this issue, but feel free to open another one if anyone continues to experience problems on the latest version of Lerna.
