### ISSUE TITLE
`--no-git-reset` On `publish` Does Not Work When `from-package`

### ISSUE THREAD

**Issue by JRedOW** [lerna/lerna#3251]
## Current Behavior

When running `publish from-package` with `--no-git-reset` while uncommitted changes, it fails as if `--no-git-reset` is not used.

## Expected Behavior

The packages should push as if there were no uncommitted changes.

## Steps to Reproduce

Run `lerna publish from-package --no-git-reset` with uncommitted changes.

### Environment

Environment info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
  Binaries:
    Node: 16.14.2 - /tmp/yarn--1657847323774-0.913813022429915/node
    Yarn: 1.22.19 - /tmp/yarn--1657847323774-0.913813022429915/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Utilities:
    Git: 2.35.1 - /usr/bin/git
  npmPackages:
    lerna: 5.1.8 => 5.1.8

**Comment by JRedOW** [comment]
The error is an `EUNCOMMIT` error.

**Comment by royi-frontegg** [comment]
Any updates on this issue ?

**Comment by gecugamo** [comment]
Experiencing the same `EUNCOMMIT` error when running `lerna publish from-git --no-git-reset`.
lerna version 6.0.6
lerna cli version 5.6.2

**Comment by TylerSustare** [comment]
Same

**Comment by hummal** [comment]
Still existing?

**Comment by JRedOW** [comment]
This issue seems to be a documentation issue rather than a usage issue. Perhaps their should be more clear documentation on what `--no-git-reset` is actually doing.

**Comment by pduchesne** [comment]
Can we get a clarification on what `--no-git-reset` is supposed to do, and whether this is a bug or a feature ?

From the documentation, i also understand it as a way to ignore uncommitted local changes, in particular when publishing a canary version. And that's what I'd need it to do.

**Comment by comp615** [comment]
Hey y'all, clear documentation can be found here:
https://github.com/lerna/lerna/tree/main/libs/commands/publish#--no-git-reset

Maybe it requires the context of the second paragraph, but what it reads as to me is that as part of publishing, the package.json files need to be manipulated (this is how npm works right?)...by default, it resets these changes after so you never see them. If you passed this, the result would be more similar to running `lerna version` which leaves/commits the changes.

Nothing to do with the state of the tree going into the publish as that still cannot be dirty

**Comment by fahslaj** [comment]
Yes, @comp615 is correct. The --no-git-reset option just ensures that the files changed during the publish action are not reset. It is not intended to function as a way to ignore uncommitted changes.
