### ISSUE TITLE
lerna publish fail leaves project in dirty state

### ISSUE THREAD

**Issue by boxxxie** [lerna/lerna#327]
If i'm not allowed to publish to npm then i get dirty git state. i have a commit that i don't want, and i have a bunch of tags that i have to manually delete.
I have also run into the problem where i ended up with dist-tags on each of my packages that were causing me to not be able to publish, so my git tags would increment, and my npm publish wouldn't work.

there are a few steps that lerna does when we ask it to publish. i think that each step should be a command, each step should output a log of what it does, and for each command there should be a revert-command that does or does not use this log.

**Comment by rygine** [comment]
this is a duplicate of https://github.com/lerna/lerna/issues/56

**Comment by boxxxie** [comment]
sorry, i didn't see that when browsing the issues
