### ISSUE TITLE
version 5.1.3 broken version bump for internal monorepo packages

### ISSUE THREAD

**Issue by gmcestari** [lerna/lerna#3285]
## Current Behavior

When using version 5.1.3 or above more than half of our packages don't get their version correctly updated. The UI correctly lists all packages and shows the version correctly (which is misleading) but after checking `git status` we can see that only 8 packages got updated.

## Expected Behavior

All versions get updated in multiple package.json files for each of the packages our monorepo has.

## Steps to Reproduce

Unfortunately I don't have a repro to provide you since our project is not open source.
But I have confirmed that until 5.1.2 all our package versions get correctly updated, however from 5.1.3 less than half of the packages get updated.

We ran the following command:

`npx lerna version --no-git-tag-version --no-push --no-commit-hooks --loglevel debug --exact 6.0.0`

I've also tried with different parameters etc but no impact.

**Comment by ghiscoding** [comment]
most probably related to #3233, there's an open PR in there that you can try to apply (3 lines of code change) to your node_module to test if the solution works (most probably will).

**Comment by gmcestari** [comment]
> 

hello @ghiscoding - happy to confirm I was able to test that code and it indeed fixed the issue.
Once that gets merged and released it will also fix my issue here.
Thank you,
Guilherme

**Comment by ghiscoding** [comment]
in case that helps, the fix was already applied in [Lerna-Lite](https://github.com/ghiscoding/lerna-lite) or you could wait for it to be applied here. Nice to see more confirmation of the issue & fix. Thanks

**Comment by gmcestari** [comment]
thank you for your help, I'm happy to close this issue now

**Comment by JamesHenry** [comment]
Thanks for reporting this @gmcestari let us know if you have any issues with lerna `5.4.1` which includes the fix for this
