### ISSUE TITLE
CONTRIBUTING.md is outdated

### ISSUE THREAD

**Issue by bytemain** [lerna/lerna#3286]
### Documentation issue

- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://github.com/lerna/lerna/blob/main/CONTRIBUTING.md

### Additional context or description

I have ran `npm ci` done.

and use:
![CleanShot 2022-08-11 at 11 36 48@2x](https://user-images.githubusercontent.com/13938334/184061036-9b060d9d-615c-4cc3-b2a2-f6ea6e59fe67.png)
<img width="932" alt="CleanShot 2022-08-11 at 11 37 22@2x" src="https://user-images.githubusercontent.com/13938334/184061049-775aed08-c88a-4223-a6b7-45ea000db111.png">

that will raise error:

<img width="1328" alt="CleanShot 2022-08-11 at 11 37 38 2@2x" src="https://user-images.githubusercontent.com/13938334/184061070-bf55572b-fc5a-4b30-9575-59f73b3e8f98.png">

**Comment by JamesHenry** [comment]
Thank you @bytemain this has now been updated please take a look at the latest instructions for how to work with the e2e tests and local CLI publishing
