### ISSUE TITLE
inconsistent behavior of lerna run scope

### ISSUE THREAD

**Issue by YousefED** [lerna/lerna#3289]
## Steps to Reproduce
- lerna init
- add two packages (a and b), both with the same "dev" command
- make package a depend on b
- run `npx lerna run --scope a dev --stream`

## Current Behavior
if `useNx` is set, it will run the command in a and b

## Expected Behavior

if `useNx` is not set, it will run the command in a only

**Comment by James-Reilly** [comment]
+ 1 also seeing this behavior after updating

**Comment by MirKml** [comment]
I think, without Nx, `lerna run --scope a dev` runs always only `dev` command in `a` package.
If you want to include dependencies, it's necessary to use `--include-dependencies` flag. It is and was pure lerna default, I think.

Maybe Nx presence changed this behaviour.

**Comment by ifatregev** [comment]
**+1**
I also tried to integrate Lerna with NX using the `useNx` flag, and see that `lerna run` behaviour changed.
I want to run only the project which is specified with the `scope` flag, **without dependencies.**

**Comment by ifatregev** [comment]
@YousefED can you please mention in the title that this is happening upon integration with NX?

**Comment by AlonMiz** [comment]
+1 we expect some kind of a flag to exclude dependencies, or even better, preserve the previous behaviour from lerna...

**Comment by JamesHenry** [comment]
Hi folks, this should be resolved in 5.5.1 thanks to @fahslaj
