### ISSUE TITLE
Impossible not to use workspaces after lerna 5

### ISSUE THREAD

**Issue by descampsk** [lerna/lerna#3296]
## Current Behavior

Trying to launch `yarn lerna bootstrap` without workspaces.

But I have this error : 

`TypeError: workspaces config expects an Array` 

## Expected Behavior

Lerna should install all packages and set the links to internal packages.

### Failure Logs / Configuration

- works on lerna 4.0.0
- fail on lerna 5.1.1

If I put `workspaces: []` in the package.json I have the following error

```
lerna ERR! EWORKSPACES Yarn workspaces are configured in package.json, but not enabled in lerna.json!
lerna ERR! EWORKSPACES Please choose one: useWorkspaces = true in lerna.json, or remove package.json workspaces config
``` 

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "services/*",
    "packages/*"
  ],
  "useWorkspaces": false,
  "engines": {
    "node": ">=14.18 <15"
  },
  "npmClient": "yarn",
  "npmClientArgs": [
    "--production=false"
  ],
  "useNx": true,
  "version": "2.1255.2"
}
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv {
0 silly argv   _: [ 'bootstrap' ],
0 silly argv   lernaVersion: '5.1.1',
0 silly argv   '$0': '/mnt/c/XXXXXX/monorepo/node_modules/.bin/lerna'
0 silly argv }
1 notice cli v5.1.1
2 verbose rootPath /mnt/c/XXXXXX/monorepo
3 silly npmConfig {
3 silly npmConfig   registry: undefined,
3 silly npmConfig   npmClient: 'yarn',
3 silly npmConfig   npmClientArgs: [ '--production=false' ],
3 silly npmConfig   mutex: 'network:42424'
3 silly npmConfig }
4 info Bootstrapping 40 packages
5 verbose lifecycle preinstall
6 silly lifecycle No script for "preinstall" in "deployer", continuing
....
46 silly hasDependencyInstalled YYYYY prettier
...
56 error TypeError: workspaces config expects an Array
56 error     at getError (/mnt/c/XXXXXX/monorepo/node_modules/@npmcli/map-workspaces/lib/index.js:66:24)
56 error     at getPatterns (/mnt/c/XXXXXX/monorepo/node_modules/@npmcli/map-workspaces/lib/index.js:36:11)
56 error     at mapWorkspaces (/mnt/c/XXXXXX/monorepo/node_modules/@npmcli/map-workspaces/lib/index.js:82:20)
56 error     at Arborist.[loadWorkspaces] (/mnt/c/XXXXXX/monorepo/node_modules/@npmcli/arborist/lib/arborist/load-workspaces.js:22:30)
56 error     at Arborist.[loadActualActually] (/mnt/c/XXXXXX/monorepo/node_modules/@npmcli/arborist/lib/arborist/load-actual.js:183:32)
56 error     at async pMapSeries (/mnt/c/XXXXXX/monorepo/node_modules/p-map-series/index.js:9:15)
56 error     at async Promise.all (index 0)

```

</p></details>

### Environment
  System:
    OS: Linux 4.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
  Binaries:
    Node: 14.18.3 - /tmp/yarn--1660738731038-0.39457618939152983/node
    Yarn: 1.19.1 - /tmp/yarn--1660738731038-0.39457618939152983/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
  Utilities:
    Git: 2.17.1 - /usr/bin/git
  npmPackages:
    lerna: 5.1.1 => 5.1.1

**Comment by fahslaj** [comment]
Hello @descampsk, thank you for submitting this issue. Unfortunately, I have not been able to reproduce it. My attempt at a reproduction is here: https://github.com/lerna/repro/tree/3296. Could you please reproduce the issue using that branch as a base? Thanks!

**Comment by descampsk** [comment]
Thanks for your answer. I will try to reproduce from your branch.

**Comment by descampsk** [comment]
Ok my bad.
The issue was that in some package.json inside services/ there was the following attributes
```
  "workspaces": {
    "nohoist": [
      "angular"
    ]
  },
```
It seems it worked in 4.0.0 but not anymore in > 5.0.
I remove this configuration and it works now well.
Thanks for your time and help, I close the issue.
