### ISSUE TITLE
lerna publish skip "prompt" for CI publishing

### ISSUE THREAD

**Issue by dtothefp** [lerna/lerna#331]
Not sure if this is already a thing but I'd like to be able to publish via a CI tool like Travis, and skip the "major,minor,patch" version prompts. Is there a way to do something like this already, or would I need to write a script that responds to the prompts from within the CI tool?

Seems kinda related to https://github.com/lerna/lerna/issues/127 but not really?

**Comment by gigabo** [comment]
@dtothefp Would [`lerna publish --canary --yes`](https://github.com/lerna/lerna#--yes) work for you?

**Comment by jwbay** [comment]
+1 to this. My use case is an independently versioned collection of modules. We'd be bumping versions as part of the PR process in our org and want the CI server publishing any updated modules as things are merged.

**Comment by thejameskyle** [comment]
Merging into #389
