### ISSUE TITLE
How do I add pdfjs dist containing viewer.html into my multi package project?

### ISSUE THREAD

**Issue by tiwari-abhigyan** [lerna/lerna#3320]
I've a project with three packages.

We want to integrate pdfjs dist (js based) and use its viewer.html to render in our react based package. If we place it in public folder in one of package, it doesn't resolve from url. The public folder has other static assets which are resolved.

Any help on this would be much appreciated!

Thanks.

**Comment by JamesHenry** [comment]
Hi @tiwari-abhigyan, there is not enough information here to determine if this is related to lerna in any way. Therefore I am going to close this for now. In future please kindly provide a specific and minimal reproduction of any issues you face
