### ISSUE TITLE
lerna add command not allowing the user to update the package version of a lerna package into another

### ISSUE THREAD

**Issue by Waqqars987** [lerna/lerna#3340]
## Current Behavior

I need to update the version of a **package-a** which is a dependency to **package-b**. Both package-a and package-b are lerna packages. When I run ```lerna add package-a@latest --scope package-b```, I get the following output:
```
info cli using local version of lerna
lerna notice cli v5.5.0
lerna info versioning independent
lerna notice filter including "package-b"
lerna info filter [ 'package-b' ]        
lerna WARN No packages found where package-a can be added.
```

lerna doesn't let me update the version of package-a into package-b.
Please help me resolve this.

## Expected Behavior
lerna add command should update the version of package-a in package-b's package.json and package-lock.json.

<details>
<summary>lerna.json</summary>
```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```
</details>

### Environment
Windows 10 version 20H2
Node.js v14.16.1
Lerna v5.5.0

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏

**Comment by languanming** [comment]
when I ran "lerna add npmlog utils/log", I got lerna warn like below:

reusing global emitter
info cli using local version of lerna
lerna notice cli v6.6.1
lerna WARN No packages found where npmlog can be added.

How can I fix thiss problem?
