### ISSUE TITLE
question: Why lerna@2.x is still in beta stage

### ISSUE THREAD

**Issue by douglasduteil** [lerna/lerna#335]
Hi @hzoo @gigabo

I'm really enjoying this project but I don't understand why the 2.x version that I'm using is still in beta stage. Is it some kind of comparability problem with the 1.x branch or features you what to have ?
 
Are they some kind of list of requirement that I can consult to know what you're expecting from the 2.x branch ? 

Thanks

**Comment by hzoo** [comment]
Yeah it probably should of been 2.0 a while ago - I think we're just not sure the direction.

I think we should make it a lerna repo before the 2.0 release though? https://github.com/lerna/lerna/issues/174.

**Comment by douglasduteil** [comment]
Yes it feels legit to eat your own *lerna* food :)

**Comment by gigabo** [comment]
Yeah #174 is probably a major version change.

But 2.0 has been a long time coming... and we have some issues that IMO are more urgent:

- [Configurable package locations](https://github.com/lerna/lerna/pull/332)
- [Automatic hoisting of external deps](https://github.com/lerna/lerna/issues/334)

I don't think those involve breaking changes (hoisting might, depending on whether it's optional).

Maybe a for-real 2.0 could happen soon?  And the urgent usability issues could be 2.x?

Then #174 as 3.0?

**Comment by douglasduteil** [comment]
Wow ! :goat:  for it ! 
The 2.0.0-beta.26 version was already stable enough for my use.
