### ISSUE TITLE
build fails when upgrading lerna from 4.0 to 5.X

### ISSUE THREAD

**Issue by sachet-mittal** [lerna/lerna#3352]
## Current Behavior

We have mutliple monorepos and we want to upgrade the lerna.
All of our monorepos are running fine with lerna 5.X but there is just one that fails with the following error.

I understand this is a failure on webpack and not lerna but all I changed is the lerna version and we ran into the error mentioned below

lerna 4.0.0 -> 5.5.2

but I got the same error on 5.1.0 as well.

## Expected Behavior

 
Build should succeed

yes it used to work on 4.0.0

### Failure Logs / Configuration

```
<root_of_repo>/node_modules/webpack-sources/lib/ConcatSource.js:42
                        source += typeof child === "string" ? child : child.source();
                                                                            ^

RangeError: Invalid string length
    at ConcatSource.source (<root_of_repo>node_modules/webpack-sources/lib/ConcatSource.js:42:56)
    at CachedSource.source (<root_of_repo>/node_modules/webpack-sources/lib/CachedSource.js:28:44)
    at writeOut (<root_of_repo>/node_modules/webpack/lib/Compiler.js:454:29)
    at <root_of_repo>/node_modules/webpack/node_modules/mkdirp/index.js:30:20
```

```json
{
  "lerna": "5.5.2",
  "packages": [
    "packages/*"
  ],
  "command": {
    "bootstrap": {
      "hoist": true,
      "ignorePrepublish": true,
      "strict": true
    },
    "add": {
      "noBootstrap": true
    },
    "version": {
      "allowBranch": [
        "mainline"
      ]
    },
    "publish": {
      "conventionalCommits": true,
      "message": "chore: publish"
    }
  },
  "ignoreChanges": [
    "**/__snapshots__/**",
    "**/*.md"
  ],
  "rejectCycles": "true",
  "concurrency": 8,
  "version": "independent"
}
```

</p></details>

</p></details>

### Environment

```
lerna notice cli v5.5.2
lerna info versioning independent

 Environment info:

  System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.19 - ~/xbcb/XbcbWorkOrderAuthority/node_modules/.bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Utilities:
    Git: 2.37.3 - /usr/local/bin/git
  npmPackages:
    lerna: 5.5.2 => 5.5.2 
```

**Comment by fahslaj** [comment]
Hi @sachet-mittal , thank you for reporting this issue. Unfortunately, this is not enough information for us to investigate effectively. Using https://github.com/lerna/repro as a base, can you please create a minimal reproduction of the issue?

We will also need to know which package installation and bootstrapping commands you are using and the build command being run in order to try to reproduce the issue.

**Comment by JamesHenry** [comment]
Now that about 6 weeks have passed without more information being provided I am going to close this one, please feel free to reopen with a reproduction of the issue

**Comment by sachet-mittal** [comment]
sorry I missed the update here. It turned out to be a bug in some other dependency.  Thanks for helping close this issue out.
