### ISSUE TITLE
bootstrapping should not be recommended

### ISSUE THREAD

**Issue by cyrfer** [lerna/lerna#3353]
### Documentation issue

The following makes new users believe bootstrapping is recommended, but the reason is not accurate. lerna is not required to:
> enables different projects in the same repository to import each other without having to be published to a registry.

That functionality is built into NPM, for a while now.

I believe the bootstrapping method should be moved to a section supporting legacy NPM versions.

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.
https://lerna.js.org/docs/getting-started#bootstrapping-projects

### Additional context or description

When reading the lerna documentation, readers think they need to run `lerna bootstrap` so their repo in order to allow their code to import from other workspaces within the same monorepo. This works without lerna in recent NPM versions.

**Comment by JamesHenry** [comment]
This has been resolved, thank you @cyrfer!
