### ISSUE TITLE
Security issue in axios via nx

### ISSUE THREAD

**Issue by The-Code-Monkey** [lerna/lerna#3361]
Dependabot has just flagged this

```
lerna@5.6.2 requires axios@0.21.1 via a transitive dependency on nx@14.8.3
```

CVSS base metrics:
Attack vector.  Network
Attack complexity.  Low
Privileges required.  None
User interaction.  None
Scope.  Unchanged
Confidentiality.  None
Integrity.  None
Availability.  High

Just thought id let you know.

**Comment by JamesHenry** [comment]
Thanks folks! Nx 14.8.6 is the minimum version specified in the latest version of lerna so I'm going to go ahead close this
