### ISSUE TITLE
[Feature] Indicate private packages in "changed" section of publish output

### ISSUE THREAD

**Issue by gigabo** [lerna/lerna#337]
Similar to #329.  It's [confusing](https://github.com/lerna/lerna/issues/216#issuecomment-246069682) that private packages get listed there when they're not published.

Maybe just as simple as adding a `(private)` suffix, like in `lerna updated`?

```
Changes:
- public-package: 0.1.7 => 0.1.8
- private-package: 0.1.7 => 0.1.8 (private)
```

**Comment by hzoo** [comment]
Done in https://github.com/lerna/lerna/pull/329

**Comment by hzoo** [comment]
Oops that was only for lerna updated

**Comment by gigabo** [comment]
Merging in to https://github.com/lerna/lerna/issues/431, since that's more complete.
