### ISSUE TITLE
dotenv loaded unexpectedly when useNx: true

### ISSUE THREAD

**Issue by wyardley** [lerna/lerna#3371]
So with Lerna 5.6 with `useNX: true` or Lerna 6, we're seeing a few test cases fail. They all seem to be failing because running the test target with nx enabled seems to be automagically loading an existing `.env` file in the directory where the tests run

I'm starting to think this behavior is from `nx` itself, maybe because of this:

https://github.com/nrwl/nx/blob/a66a549e4bb2bca1c63add7ed40396228c3cbcbb/packages/nx/src/tasks-runner/forked-process-task-runner.ts#L278-L279

Is there a way to disable this behavior? It seems a little overly magical, and is arguably an undocumented breaking change.

**Comment by JamesHenry** [comment]
Thanks for reporting this @wyardley I have removed the discussion to keep things focused here.

We will update the release notes for v6 to highlight this change in default behaviour, and also give you a way to disable the automatic .env loading given that's desirable for your setup.

That flag will go out today and I will close this issue once it's ready.

**Comment by wyardley** [comment]
Awesome. Thanks!

**Comment by JamesHenry** [comment]
`6.0.1` is now available which allows you to set `--load-env-files=false` on lerna run

**Comment by wyardley** [comment]
thanks so much for the quick response + fix @JamesHenry! 💯 
Really appreciated

Is there any way to set options to `nx` in config, or is using the flag the only way to trigger this when using `nx` indirectly via lerna in this way?

**Comment by JamesHenry** [comment]
@wyardley in your `lerna.json` you can specify the flag for the run command:

**lerna.json**
```json
{
"command": {
    "run": {
      "loadEnvFiles": false
    }
  }
}
```

**Comment by wyardley** [comment]
Awesome. Thanks again; confirming that looks great
