### ISSUE TITLE
npm install lerna -g fail

### ISSUE THREAD

**Issue by pakholeung37** [lerna/lerna#3372]
## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration
➜  web npm i -g lerna
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @octokit/core@^4.1.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pakholeung/.npm/_logs/2022-10-14T04_52_38_456Z-debug-0.log

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```

</p></details>

**Comment by JamesHenry** [comment]
Hi @pakholeung37 I have not been able to reproduce this.

<img width="814" alt="image" src="https://user-images.githubusercontent.com/900523/195869466-05dca967-8b54-4cca-8465-990730009c59.png">

You may prefer to try running lerna using npx anyway:

E.g.

```sh
npx lerna init
```

Hope that helps!

If you continue to have issues with running lerna please feel free to reopen and provide much more information about your environment such as node installation, npm version, OS etc
