### ISSUE TITLE
Expose retry options of npm-registry-fetch to lerna publish command

### ISSUE THREAD

**Issue by vilaemail** [lerna/lerna#3373]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/lerna/lerna/blob/main/CONTRIBUTING.md))

## Description

Be able to recover from npm publish failures without [republishing all packages](https://lerna.js.org/docs/faq#how-do-i-retry-publishing-if-publish-fails) in (large - 500+ packages) monorepo. Network failures happen from time to time and we need a way to recover.

## Motivation

If publishing X packages (say 20) in monorepo of Y (say 500 - Y >> X) and the publish fails due to network error (see appendix), recovery action is [to publish all Y packages](https://lerna.js.org/docs/faq#how-do-i-retry-publishing-if-publish-fails). Publishing Y packages is much likely to fail, hence the recovery strategy is to keep republishing all packages until you get lucky and all publishes succeed. A better approach is to just retry those publish operations which failed.

## Suggested Implementation

`publish` command to accept all `fetchRetry*` parameters from [npm-registry-fetch](https://github.com/npm/npm-registry-fetch#-optsfetchretries) and pass them when calling [publish](https://github.com/lerna/lerna/blob/fd0befa470d962232addd95f44956f190f337e72/utils/npm-publish/npm-publish.js#L93). For completeness these will eventually get used [here](https://github.com/npm/make-fetch-happen/blob/main/lib/remote.js#L111).

## Alternate Implementations

* Use `lerna publish from-packages` to retry. Unsure if this would require Y (500) requests to check if package exists.

All of the below alternatives I find non-ideal as they essentially "use something which is not lerna" to recover from lerna command which failed.
- Publish all packages with `npm publish` ignoring errors [Reference](https://cri.dev/posts/2020-01-29-How-to-recover-from-failed-lerna-publish/). Not very good as it might fail again so improvement would be to parse what is the error, and if it is "feed already contains" treat that as success.
- Parse lerna output and then manually run `npm publish` command for packages which failed and weren't published (as publish command exits on first failure). 

## Appendix
Network failure:
```
lerna ERR! ERR_SOCKET_TIMEOUT request to REDACTED failed, reason: Socket timeout
lerna ERR! FetchError: request to REDACTED failed, reason: Socket timeout
lerna ERR!     at ClientRequest.<anonymous> (REDACTED\node_modules\minipass-fetch\lib\index.js:110:14)
lerna ERR!     at ClientRequest.emit (node:events:526:28)
lerna ERR!     at TLSSocket.socketErrorListener (node:_http_client:442:9)
lerna ERR!     at TLSSocket.emit (node:events:538:35)
lerna ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
lerna ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
lerna ERR! lerna request to REDACTED failed, reason: Socket timeout
```

**Comment by Beace** [comment]
I also encountered this problem in monorepo. I found that the `lerna` command did not pass the `retry` parameter of `npm-registry-fetch`. Is this feature still under development?

**Comment by JamesHenry** [comment]
Closing in favour of #455
