### ISSUE TITLE
[Docs] Mention RAM requirements in readme

### ISSUE THREAD

**Issue by Daniel15** [lerna/lerna#338]
I was trying to build Jest on a virtual machine with 512 MB RAM, which is fine for most other projects I work on but the Jest build was super slow and kept getting killed by the OOM killer. Bumping it to 2 GB helped - The build was much faster and didn't die.

It might be worth doing some benchmarking and determining the system requirements of Lerna. How much RAM is used by a "normal"-sized project using Lerna?

**Comment by gigabo** [comment]
Hi @Daniel15.  Did you try reducing concurrency with the `--concurrency` option?

The default is four child processes.  If reducing that helps, we could add a note about [using `--concurrency`](https://github.com/lerna/lerna#--concurrency) to limit memory usage to the README.

Could even look at reducing automatically in low-memory environments...

**Comment by doug-wade** [comment]
we never received a response; closing
