### ISSUE TITLE
Add option to use NTFS junctions on Windows

### ISSUE THREAD

**Issue by Daniel15** [lerna/lerna#339]
On Windows, creation of symlinks requires administrator rights, whereas creation of NTFS junctions does not. Junctions are similar to hardlinks on Linux.

Currently, if you use Lerna without admin rights on Windows, you can encounter permissions errors similar to:

> Errored while running BootstrapCommand.execute
> Error: EPERM: operation not permitted, symlink 'C:\src\jest\packages\jest-runtime\bin\jest-runtime.js' -> 'C:\src\jest\packages\jest-repl\node_modules\.bin\jest-runtime'
>     at Error (native)
> -> failed running: C:\src\jest\node_modules\.bin\lerna.cmd bootstrap

**Comment by motiz88** [comment]
[`npm link` does this](https://github.com/npm/npm/blob/master/lib/utils/link.js#L69). Would a PR fixing this be welcome?
