### ISSUE TITLE
[Feature] support method to /only/ link packages

### ISSUE THREAD

**Issue by seansfkelley** [lerna/lerna#341]
Use case: I add a dependency to an existing package on an existing package. All I want to do is create that one symlink between the two, but `lerna bootstrap` has to go through the whole rigamarole of checking and installing everything, which can be slow (especially if the repo is in some kind of intermediate state due to adding/removing a bunch of stuff, which it often is when I want to do this operation).

Possible solutions:
1. `bootstrap` respects `--scope` so I can pick the packages I want and reduce the time waiting for installation
2. `bootstrap` gets `--skip-externals` so it only does the symlink/prepublish
3. `bootstrap` gets `--link-only` (but this seems sort of annoyingly narrow when the other two are somewhat more generally applicable)
4. Lerna gets a new `link` command that only symlinks

While (1) should probably exist for general consistency, I think the ideal solution to solve this particular problem is actually (4). Given that #358 adds _more_ stuff to bootstrap that I don't care about running when I am in the above situation, having a stripped-down command instead of a bunch of flags to turn off useful bootstrap behaviors seems preferable.

**Comment by bradleyayers** [comment]
This is a major pain-point for the repo I'm working in, and a `link` command would solve the problem. It would also be useful if bootstrap respected `--scope`.

**Comment by seansfkelley** [comment]
Given that #358 adds a bunch more stuff to bootstrapping, and that I really do only need the linking behavior to cover my use-case, I'm thinking that a specific `link` command is the right way to go. Pre/post installation can be just as time-consuming and useless as prepublishing (if you, like me, use prepublish to transpile stuff).

**Comment by lukebatchelor** [comment]
If it helps, I'm looking at implementing option 1 tomorrow (#383).

As a work around before that I'm looking at writing a quick script that would essentially, get all the package names in the repo, find the ones **not** matched by the `--scope` glob, pass any that are left to

```
lerna bootstrap --ignore {package-a,package-b,package-c}
```

It would still run the prepublish in each package matched by `--scope` and any dependant packages they link, but still a lot better than running the whole repo.

**Comment by lukebatchelor** [comment]
Just an update, #383 adds `--scope` support for bootstrap, if that helps 👍

**Comment by timoxley** [comment]
@lukebatchelor IIUC I don't think that helps at all since `bootstrap` will still install dependencies & run scripts of the packages matching the `--scope`.

**Comment by seansfkelley** [comment]
FWIW, I ended up [doing option (4) in yerna](https://github.com/palantir/yerna/blob/master/bin/yerna#L196..L199) (my smaller, Yarn-based Lerna-like).
