### ISSUE TITLE
`lerna version` always bump a patch version

### ISSUE THREAD

**Issue by 1aron** [lerna/lerna#3425]
## Current Behavior

Lerna has done a very good job in all aspects, but the version bumping and difference analysis are a bit unsatisfactory.

Here is [our file structure](https://github.com/master-co/css/tree/beta):
```
css
└───packages
│   └─── css
│   └─── compiler
│   └─── vite
│   README.md
│   lerna.json    
│   ...
```
We set `changelogPreset: "conventionalcommits"` and deliberately tested the following commits:

- Change some files in the `packages/css` and commit with `chore: css`
- Change some files in the `packages/vite` and commit with `feat: vite`
- Change some files in the `packages/compiler` and commit with `fix: compiler`

Execute `lerna version` in `beta` branch:

```bash
lerna info getChangelogConfig Auto-prefixing conventional-changelog preset "conventionalcommits"
lerna info getChangelogConfig Successfully resolved preset "conventional-changelog-conventionalcommits"

Changes:
 - @master/css.compiler: 2.0.0-beta.19 => 2.0.0-beta.20
 - @master/css:          2.0.0-beta.41 => 2.0.0-beta.42
 - @master/css.vite:     2.0.0-beta.19 => 2.0.0-beta.20
```

### Related Issues & Problems:

1. #3362
2. #1569
3. Bump version without following conventional commits.
4. Always bump patch version even without adding any semantic prefix.

## Expected Behavior

Since the title of the `@master/css` commit is prefixed with `chore:`, it should not bump a patch version.

```diff
Changes:
+ @master/css.compiler: 2.0.0-beta.19 => 2.0.0-beta.20
- @master/css:          2.0.0-beta.41 => 2.0.0-beta.42
+ @master/css.vite:     2.0.0-beta.19 => 2.0.0-beta.20
```

Version bumpings should follow the conventions of [changesets](https://github.com/changesets/changesets) and [semantic-releases](https://www.npmjs.com/package/semantic-release).

If `lerna version --conventional-commits` doesn't depend on `releaseType` to tell if a release version or changelog is required, but always releases a patch version, then I'd say it's completely unavailable on CI.

Because you can't assume that any commit requires a release version, e.g. `chore`, `docs`, etc.

Using lerna instead of [changesets](https://github.com/changesets/changesets) and [semantic-releases](https://www.npmjs.com/package/semantic-release) is one step away!

## Steps to Reproduce

https://github.com/master-co/css/tree/beta

As above, try modifying some files and adding comments:
```bash
chore: css
feat: vite
fix: compiler
```
```bash
lerna version
```

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
    "$schema": "node_modules/lerna/schemas/lerna-schema.json",
    "useWorkspaces": true,
    "version": "independent",
    "changelogPreset": "conventionalcommits",
    "command": {
        "version": {
            "message": "chore(release): publish",
            "conventionalCommits": true,
            "conventionalBumpPrerelease": true
        }
    }
}
```

</p></details>

<details><summary>package.json</summary><p>

```json
{
    "name": "root",
    "version": "0.0.0",
    "scripts": {
        "bootstrap": "lerna bootstrap"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/master-co/css.git"
    },
    "workspaces": [
        "packages/*"
    ],
    "devDependencies": {
        "@commitlint/cli": "^17.2.0",
        "@commitlint/config-conventional": "^17.2.0",
        "@swc/core": "^1.3.9",
        "@swc/jest": "^0.2.23",
        "@types/jest": "^29.2.0",
        "@types/node": "^18.11.0",
        "@typescript-eslint/eslint-plugin": "^5.40.1",
        "@typescript-eslint/parser": "^5.40.1",
        "dedent": "^0.7.0",
        "esbuild": "^0.15.10",
        "eslint": "^8.25.0",
        "husky": "^8.0.2",
        "jest": "^29.2.2",
        "jest-environment-jsdom": "^29.3.1",
        "jest-puppeteer": "^6.1.1",
        "lerna": "^6.0.3",
        "puppeteer": "^19.2.2",
        "typescript": "^4.8.4"
    }
}
```

</p></details>

### Environment

```bash
 Environment info:

  System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M2
  Binaries:
    Node: 17.9.1 - ~/.nvm/versions/node/v17.9.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v17.9.1/bin/npm
  Utilities:
    Git: 2.37.3 - /opt/homebrew/bin/git
  npmPackages:
    lerna: ^6.0.3 => 6.0.3 
```

**Comment by amorscher** [comment]
I think https://github.com/lerna/lerna/pull/3362 is not released yet that is why the behavior is not inlcuded in 6.0.3. I tried it with a locally built version and I get following bumps:

```sh
Changes:
 - @master/css.compiler: 2.0.0-beta.19 => 2.0.1-beta.0
 - @master/css: 2.0.0-beta.41 => 2.0.1-beta.0
 - @master/css.vite: 2.0.0-beta.19 => 2.1.0-beta.0
```

**Comment by 1aron** [comment]
@amorscher `chore` shouldn't bump any version. So `@master/css` should be excluded from the change.
