### ISSUE TITLE
Lerna run parallel does not show the output for long running tasks like watch.

### ISSUE THREAD

**Issue by ghdoergeloh** [lerna/lerna#3429]
I was running tsc -w in each package to compile typescript on change.

therefore I used: `lerna run --parallel watch -- -- --preserveWatchOutput` in version 5.

## Current Behavior

Now we need to skip one "--" and it is running, but it does not show any output or error.
`lerna run --parallel watch -- --preserveWatchOutput` shows no output but the fact that it is running.

## Expected Behavior

output during the run of "tsc -w"

## Steps to Reproduce

- package.json
- packages
  - app
    - package.json (with script "watch": "tsc -w")
    - index.ts (valid or invalid code -> the output should show it)

```

</p></details>

### Environment

<!-- It's important for us to know the context in which you experience this behavior! -->
<!-- Please paste the result of running `npx lerna info` in your repo below! -->

**Comment by JamesHenry** [comment]
You want to add `--stream` to your command to use the streaming output for all your long-running scripts.

We have a heuristic for guessing when someone is running a long-running script and enable streaming automatically, but we did not yet account for `watch` (we had ends with `:watch` or `-watch` but not `watch` by itself). We will amend that in a future version, but in the meantime you can use `--stream`.

**Comment by ghdoergeloh** [comment]
Oh, okay, I thought `--stream` would start the jobs of depending packages when the jobs of dependent packages are finished what would never be the case with watch.
