### ISSUE TITLE
push tag after publish, plz

### ISSUE THREAD

**Issue by takegine** [lerna/lerna#3436]
My network is not stable. Therefore, `publish` often fails due to network problems, but `git push` workout. So when I use `lerna publish`, I often encounter that `git commit` and `tag` have been uploaded to the warehouse, but the release fails. I have to return `commit` and every `tag`, and then try to `publish` again.

**Comment by JamesHenry** [comment]
Hi @takegine we are working on recoverable publish, which is the solution to this issue, I will close this in favour of that tracking issue: #455
