### ISSUE TITLE
Not compatible with pnpm

### ISSUE THREAD

**Issue by runspired** [lerna/lerna#3449]
https://github.com/lerna/lerna/issues/3195#issuecomment-1304059284

Previous issue #3195 was closed despite lerna being incompatible with publishing pnpm based projects.

**Comment by runspired** [comment]
Note, users will either hit the above bug or this one: https://github.com/lerna/lerna/issues/2402

The solution was to remove lerna.

**Comment by JamesHenry** [comment]
@runspired Please help us to help you. In spite of your current status of "practicing empathy" a lot of your language so far is both aggressive and unhelpful, I'm not sure why that would be the case. Let's start from a clean slate and move things forward together giving each other the benefit of the doubt.

Clearly, the issue title of "Not compatible with pnpm" is not accurate enough. pnpm is being used successfully with lerna in many projects already, and is tested in lerna on every commit.

It seems you are reporting a specific issue related to specific pnpm command. You had previously added this feedback onto someone else's issue and you did not provide any information about the issue you are experiencing.

Please kindly update this issue with a more precise breakdown of the specific issue you experienced and how to reproduce it, then we will be very happy to take a look and figure out a path forward together.

Many thanks 🙏

**Comment by runspired** [comment]
I described the issues that prevent publishing pnpm workspace driven projects with lerna in the above linked issues, the first of which was unceremoniously closed despite the general lack of support. If it was not meant to be a kitchen-sync tracking issue for support, that wasn't clear.

I worked around lerna's issues with pack only to find myself still blocked with the bugs in the `version` command in #2402 and facing the prospect that lerna has recently moved to an overly complicated config for even the simplest projects I chose to just remove lerna.

> pnpm is being used successfully with lerna in many projects already, and is tested in lerna on every commit.

Sounds like lerna has some good unit tests and no integration tests.

**Comment by JamesHenry** [comment]
> "closed despite the general lack of support"

Again, please the simple ask here is to outline the steps required to reproduce issues you have seen. "General lack of support" simply isn't applicable language here, as evidenced below. You have seen something specific, and if you can provide more information, we can work on addressing.

> Sounds like lerna has some good unit tests and no integration tests.

It's a shame that you are doubling down on the snarky attitude, I'm at a loss as to why you feel I deserve it when all I am trying to do is help you.

For any others for posterity, here is one of a few different `pnpm` integration tests. It creates a real `pnpm` workspace + lerna repository, using the respective CLIs, and publishes a package to a local registry successfully: https://github.com/lerna/lerna/blob/af59f88e0846f143647da703082065ed36323ca4/e2e/tests/lerna-publish/lerna-publish-pnpm.spec.ts#L1
