### ISSUE TITLE
Parsing of nx args during build errors out

### ISSUE THREAD

**Issue by devenchawlayyc** [lerna/lerna#3468]
I just upgraded my mono repo from lerna 4.0 to lerna 6.1.0.

I'm not sure where this issue is but based on the stacktrace it appears like the issue is when args are being parsed and transformed into `NxArgs`. 

When I try to run a build I get the following error:

```
erna ERR! Error: No projects matching: e
lerna ERR!     at projectsToRun (C:\Projects\ePact\frontendMonoRepo\node_modules\nx\src\command-line\run-many.js:56:23)
lerna ERR!     at C:\Projects\ePact\frontendMonoRepo\node_modules\nx\src\command-line\run-many.js:24:26
lerna ERR!     at Generator.next (<anonymous>)
lerna ERR!     at fulfilled (C:\Projects\ePact\frontendMonoRepo\node_modules\tslib\tslib.js:114:62)
lerna ERR! lerna No projects matching: e
error Command failed with exit code 1.
```

And on further investigation, I updated the `projectsToRun` method in the `run-many.js` file, I found out when do a console.log of the `nxArgs`, it prints the following:
```
{
  projects: 'epact-dashboards-front-end,cico-portal-app,@epact/api,@epact/common,@epact/locales,@epact/theme,@epact/ui',
  outputStyle: 'dynamic',
  parallel: 12,
  nxBail: true,
  nxIgnoreCycles: true,
  skipNxCache: false,
  verbose: undefined,
  __overrides__: [],
  targets: [ 'build' ]
}
```

The above log indicates the projects are not being parsed into an array, which I think seems to be the issue here. When I hardcode the project names with the following, the build works:
`nxArgs.projects = ['epact-dashboards-front-end', 'cico-portal-app', '@epact/api', '@epact/common', '@epact/locales', '@epact/theme', '@epact/ui'];`

**Comment by devenchawlayyc** [comment]
If there are any workarounds, please let me know. We have named our packages in the `package.json` file as `@epact/common` etc.

**Comment by ykageyama-mondo** [comment]
Running into this problem as well with `useNx` enabled in lerna.json. Looks like there's a mismatch between the shape of `nxArgs.projects` between lerna and nx. Lerna is [converting project into a string of project](https://github.com/lerna/lerna/blob/798aae14656c9fbbde62bd941fe3a11450112f3b/commands/run/index.js#L221) while nx [expects an array](https://github.com/nrwl/nx/blob/4a43a04caf725cdb10dcc11fd0480c5f49430523/packages/nx/src/command-line/run-many.ts#L69).

**Comment by ykageyama-mondo** [comment]
A workaround that's working for me is to pin the version of nx to version 15.3.3

**Comment by jrmacks** [comment]
I was experiencing the same issue upon upgrading to lerna 6.2 today. I pinned the dependent version of `nx` to `15.3.3` and the issue went away.

**Comment by waitingsong** [comment]
with nx 15.4.0 will failed.
with nx 15.3.3 will ok.

**Comment by JamesHenry** [comment]
Hi Folks, really sorry about this one, I have a PR up to fix it.

We will make sure we come up with a cross project testing strategy in the new year to ensure that these kinds of issues do not occur in future

**Comment by JamesHenry** [comment]
Further update: we decided to fix this at the source in the nx task runner so that it can be flexible enough to handle a string or an array, so there is no lerna bump required. The problem will be resolved for you as long as your nx package in your `node_modules` is either before `15.4.0` or is equal to (or eventually greater than) `15.4.1`, which is the new latest version.

Sorry again for the confusion on this one, I will add some smoke testing to ensure that these kinds of issues don't occur again.

Happy holidays, everyone! 🎁

**Comment by devenchawlayyc** [comment]
Thanks it seems to work now with nx 15.4.1
