### ISSUE TITLE
not hardcoded packagesLocation

### ISSUE THREAD

**Issue by HatemJerbi** [lerna/lerna#347]
Make packagesLocation not hard coded. I think it can be specified in lerna.json (default value = 'packages').

This will be helpful for someone who want to use Lerna in an existing project that already contain "packages" directory (take the example of Meteor project).

Its not the same uses case as #332 try to solve. 
 
PS: thx for your great work.

best regards

**Comment by thejameskyle** [comment]
Why does #332 not solve this?

**Comment by thejameskyle** [comment]
Moving to #365
