### ISSUE TITLE
Cannot find module '@nrwl/workspace/tasks-runners/default'

### ISSUE THREAD

**Issue by crtdaniele** [lerna/lerna#3475]
Hi Devs,
I tried to implement the remot cache with Azure. I tried this library: nx-remotecache-azure but I have an error.

So, I have this library in devDep: nx-remotecache-azure (~3.0.0).
After, I changed the nx.json file:

```
"tasksRunnerOptions": {
    "default": {
      "runner": "nx-remotecache-azure",
      "options": {
        "accountName": "",
        "accountKey": "",
        "container": "nx",
        "cacheableOperations": [
          "transpile-state"
        ],
        "cacheDirectory": "./.build-cache-retail"
      }
    }
  },
```

But, when I tried to use lerna run transpile-state I have this error: Lerna (powered by Nx) Cannot find module '@nrwl/workspace/tasks-runners/default'.

Version of nx and lerna:

"nx": "~15.3.3"
"lerna": "~6.1.0"

How to configure a different default target runner?

Thanks,
Daniele

**Comment by fahslaj** [comment]
Hi @crtdaniele , thank you for opening this issue. It appears that the package "nx-remotecache-azure" and it's dependency, "nx-remotecache-custom", do not list @nrwl/workspace as an explicit dependency. Therefore, npm did not install it automatically, and "nx-remotecache-azure" can't find it.

To fix this yourself, you can install `@nrwl/workspace` manually as a devDependency, which should make `@nrwl/workspace/tasks-runners/default` available. I would also suggest opening an issue with "nx-remotecache-azure" that mentions the missing dependency declaration.
