### ISSUE TITLE
lerna format pnpm-lock.yaml with prettier 

### ISSUE THREAD

**Issue by chambo-e** [lerna/lerna#3476]
## Current Behavior

Hello :wave: 
There is an issue when using lerna with pnpm and prettier since https://github.com/lerna/lerna/pull/3284
It runs prettier when adding the pnpm-lock.yaml ([here](https://github.com/lerna/lerna/blob/main/commands/version/lib/git-add.js))

I assumed it would respect the prettierignore but that does not seems to work either

## Expected Behavior

Prettier should not be run on pnpm-lock.yaml as the indentation from pnpm is different

There might be a way to fetch the prettierignore and ignore specified files/paths :)

## Steps to Reproduce

You can see a reproduction from our repo here (commit result from lerna publish) https://github.com/scaleway/scaleway-lib/commit/8f789edef9bfb1e960f2e1fe1c0c8079c27f0b43#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb

I assume a pretty straightforward way of reproducing would be to have a repository with pnpm + lerna + prettier in devDeps and trigger a lerna version :)

### Failure Logs / Configuration

```json
{
  "packages": ["packages/*"],
  "useWorkspaces": true,
  "npmClient": "pnpm",
  "version": "independent",
  "command": {
    "publish": {
      "conventionalCommits": true,
      "changelogPreset": "conventionalcommits"
    },
    "version": {
      "message": "chore(release): publish"
    }
  }
}
```

### Environment

```sh
Environment info:

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Utilities:
    Git: 2.38.1 - /opt/homebrew/bin/git
  npmPackages:
    lerna: 6.1.0 => 6.1.0 
```

**Comment by chambo-e** [comment]
Works like a charm, thanks :)

**Comment by Leksat** [comment]
It would be nice if `pnpm-lock.yaml` is excluded by default.
