### ISSUE TITLE
Vulnerability in dependency glob-parent

### ISSUE THREAD

**Issue by thebpmgroup** [lerna/lerna#3509]
## Current Behavior

When running an npm audit I get

```
node_modules/watchpack-chokidar2/node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/watchpack-chokidar2/node_modules/chokidar
    watchpack-chokidar2  *
    Depends on vulnerable versions of chokidar
    node_modules/watchpack-chokidar2
      watchpack  1.7.2 - 1.7.5
      Depends on vulnerable versions of watchpack-chokidar2
      node_modules/watchpack
        webpack  4.44.0 - 4.46.0
        Depends on vulnerable versions of watchpack
        node_modules/webpack

5 high severity vulnerabilities
```
## Expected Behavior

No errors

## Steps to Reproduce

```
npm i lerna
npm audit
```

**Comment by JamesHenry** [comment]
Hi @thebpmgroup this does not appear to be related to `lerna`.

These dependencies you are showing, like `chokidar`, `watchpack-chokidar2` etc are not pulled in by `lerna` and are not related to the tool.

You can verify this by created a fresh lerna workspace and running `npm ls chokidar` etc and there will be no results. Additionally `npm audit` on a fresh lerna workspace does not yield any vulnerabilities, and you can see the snyk review of it here: https://snyk.io/advisor/npm-package/lerna

Hope that helps!
