### ISSUE TITLE
Lerna publish gets stuck after first package

### ISSUE THREAD

**Issue by VictorOnwukwe** [lerna/lerna#3526]
## Current Behavior

When I run `lerna publish`, it gets stuck after packaging the first package. This is where it gets stuck:

```
lerna WARN ENOLICENSE One way to fix this is to add a LICENSE.md file to the root of this repository.
lerna WARN ENOLICENSE See https://choosealicense.com for additional guidance.
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠏ publish: verb packed packages/react
```

This line particularly:
```
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠏ publish: verb packed packages/react
```

## Expected Behavior

It should publish to NPM successfully

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*",
    "docs"
  ],
  "version": "independent",
  "stream": true,
  "hoist": true,
  "command": {
    "bootstrap": {
      "npmClientArgs": ["--no-package-lock"]
    },
    "publish": {
      "ignoreChanges": ["**/stories/**", "**/tests/**"]
    }
  }
}
```

</p></details>

### Environment

System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    npm: 6.14.17 - ~/.nvm/versions/node/v14.21.2/bin/npm
  Utilities:
    Git: 2.32.1 - /usr/bin/git
  npmPackages:
    lerna: ^5.6.2 => 5.6.2

**Comment by fahslaj** [comment]
Hi @VictorOnwukwe, thank you for opening this issue. Unfortunately, I am not able to reproduce the behavior that you have described above using the lerna.json and environment settings provided.

Can you please create and share a minimal reproduction of the issue? You can use https://github.com/lerna/repro as a base.

**Comment by VictorOnwukwe** [comment]
Hi @fahslaj. Thanks for responding to this issue. I wish I could reproduce this issue, but I'm limited from sharing the codebase and in its entirety, special VPN access has to be granted for someone else to be able to reproduce this step. I was just hoping someone else has experienced this issue (which is actually the case here: [#3143](https://github.com/lerna/lerna/issues/3143). The proffered solution in that referenced issue (which is to update the Lerna version) didn't solve my issue.

**Comment by fahslaj** [comment]
@VictorOnwukwe , I understand. Unfortunately, there is not much we can do without an example codebase (even a small one in github) that showcases the problem. The only other suggestion I have is to try and update your versions of node and npm. That might fix the issue, and Node 14 reaches the end of its maintenance life mid this year anyway (https://github.com/nodejs/Release).
