### ISSUE TITLE
@nrwl/eslint-plugin-nx + lerna@6.5.0 ESLint errors - Error reading "tsconfig.base.json"

### ISSUE THREAD

**Issue by pachuka** [lerna/lerna#3538]
## Current Behavior

After upgrading to Lerna 6.5.0, ESLint with the `@nrwl/eslint-plugin-nx` fails with `Error reading "tsconfig.base.json"`.

There were no issues with this in Lerna 6.4.1 (this repo has never had a `tsconfig.base.json`). Seems like some lerna configuration is bleeding through to consumers

## Expected Behavior

Normal ESLint behavior, no errors

## Steps to Reproduce

Working on creating a standalone reproduction - will paste link shortly once ready.

### Failure Logs / Configuration

```
> eslint --cache packages/ --ext .ts,.tsx

Error reading "tsconfig.base.json": 
{"errno":-2,"syscall":"open","code":"ENOENT","path":"/home/bamboo/bamboo-agent-home/xml-data/build-dir/CERTAINLY-CC1030-JOBLINT/tsconfig.base.json"}
Error reading "tsconfig.base.json": 
{"errno":-2,"syscall":"open","code":"ENOENT","path":"/home/bamboo/bamboo-agent-home/xml-data/build-dir/CERTAINLY-CC1030-JOBLINT/tsconfig.base.json"}
Error reading "tsconfig.base.json": 
{"errno":-2,"syscall":"open","code":"ENOENT","path":"/home/bamboo/bamboo-agent-home/xml-data/build-dir/CERTAINLY-CC1030-JOBLINT/tsconfig.base.json"}
Error reading "tsconfig.base.json": 
{"errno":-2,"syscall":"open","code":"ENOENT","path":"/home/bamboo/bamboo-agent-home/xml-data/build-dir/CERTAINLY-CC1030-JOBLINT/tsconfig.base.json"}
Error reading "tsconfig.base.json": 
{"errno":-2,"syscall":"open","code":"ENOENT","path":"/home/bamboo/bamboo-agent-home/xml-data/build-dir/CERTAINLY-CC1030-JOBLINT/tsconfig.base.json"}
Error reading "tsconfig.base.json": 
{"errno":-2,"syscall":"open","code":"ENOENT","path":"/home/bamboo/bamboo-agent-home/xml-data/build-dir/CERTAINLY-CC1030-JOBLINT/tsconfig.base.json"}
Error reading "tsconfig.base.json": 
{"errno":-2,"syscall":"open","code":"ENOENT","path":"/home/bamboo/bamboo-agent-home/xml-data/build-dir/CERTAINLY-CC1030-JOBLINT/tsconfig.base.json"}
Error reading "tsconfig.base.json": 
{"errno":-2,"syscall":"open","code":"ENOENT","path":"/home/bamboo/bamboo-agent-home/xml-data/build-dir/CERTAINLY-CC1030-JOBLINT/tsconfig.base.json"}
Error reading "tsconfig.base.json": 
{"errno":-2,"syscall":"open","code":"ENOENT","path":"/home/bamboo/bamboo-agent-home/xml-data/build-dir/CERTAINLY-CC1030-JOBLINT/tsconfig.base.json"}
Error reading "tsconfig.base.json": 
{"errno":-2,"syscall":"open","code":"ENOENT","path":"/home/bamboo/bamboo-agent-home/xml-data/build-dir/CERTAINLY-CC1030-JOBLINT/tsconfig.base.json"}
Error reading "tsconfig.base.json": 
{"errno":-2,"syscall":"open","code":"ENOENT","path":"/home/bamboo/bamboo-agent-home/xml-data/build-dir/CERTAINLY-CC1030-JOBLINT/tsconfig.base.json"}
Error reading "tsconfig.base.json": 
```

After those errors in all files I also see these `@nrwl/nx/enforce-module-boundaries` errors:

example of 1:
```
1:1  error  Projects should use relative imports to import from other files within the same project. Use "./path/to/file" instead of import from "react"                                     @nrwl/nx/enforce-module-boundaries
3:1  error  Projects should use relative imports to import from other files within the same project. Use "./path/to/file" instead of import from "date-fns"                                  @nrwl/nx/enforce-module-boundaries
4:1  error  Projects should use relative imports to import from other files within the same project. Use "./path/to/file" instead of import from "react-intl"                                @nrwl/nx/enforce-module-boundaries
6:1  error  Projects should use relative imports to import from other files within the same project. Use "./path/to/file" instead of import from "@material-ui/core"                         @nrwl/nx/enforce-module-boundaries
7:1  error  Projects should use relative imports to import from other files within the same project. Use "./path/to/file" instead of import from "@solarialabs/certainly-client-common-web"  @nrwl/nx/enforce-module-boundaries
```

### Environment

```
 Environment info:

  System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    npm: 6.14.17 - ~/.nvm/versions/node/v14.21.2/bin/npm
  Utilities:
    Git: 2.39.1 - /opt/homebrew/bin/git
  npmPackages:
    lerna: 6.5.0 => 6.5.0 
    @nrwl/eslint-plugin-nx: 15.6.3
```

**Comment by pachuka** [comment]
Unfortunately having trouble creating a reproduction with the same failure in the `repro` repository. Unfortunately I can't share out the repo where I'm having this issue, but just removing my configuration for the `@nrwl/nx/enforce-module-boundaries` rule resolves it. I have to take a break from this tonight, but will try to reproduce and make a repo for that over next few days since it seems contingent on the 6.5 release (this repo has had no other changes on this branch).

**Comment by JamesHenry** [comment]
Thank you, @pachuka a reproduction would be gratefully appreciated. I would be surprised if this was down to lerna directly, because I have double checked and the is not a single occurrence of `tsconfig.base.json` in the distributed `lerna` package, or the two other `@lerna/` packages it requires at runtime as of version `6.5.0`.

If you are using the Nx `eslint-plugin` I am guessing you are using Nx to manage your workspace and using lerna for versioning and publishing? Perhaps when you upgraded Lerna it caused the Nx version in your node_modules to change somehow?

**Comment by JamesHenry** [comment]
It shouldn't have any impact on this (however given there isn't a clear identification of the problem yet it might be worth trying) but I just released `6.5.1` so you can give that a try.

**Comment by pachuka** [comment]
Yep, let me give that a shot! And yea I found it pretty odd, perused all the lerna changed between 6.4.1 -> 6.5 and didn't see anything that I'd expect to be problematic and can't create it in standalone yet.

We're actually mainly using Lerna in general but we've been getting ready to start leveraging more NX from a module federation perspective over the course of this year (so pretty excited about the new maintaintership model/love seeing all the updates so far). We had put in the eslint-plugin to enforce some code boundaries so folks weren't importing app code into library code. Granted maybe I need to double check that configuration as well.

Thanks for the quick look at this, but yeah let me keep digging on my end, maybe its something unique to our setup.

**Comment by pachuka** [comment]
I think I'm going to go ahead and close this for now. I have a feeling our eslint enforce project boundaries plugin likely wasn't running properly before this update. We purely had a lerna based repo with some of the NX project tagging configured but it wasn't truly structured like a NX generated project.

If I rename my base `tsconfig.json` -> `tsconfig.base.json` to match the standard NX pattern, the warnings go away, but I am also seeing `TypeError: Cannot read property 'react' of undefined` (and more for every dependency). So I'm guessing this is more a byproduct of us slowly migrating to a more NX centric structure. Until that's complete it may make more sense for me to disable this for now until structurally things are more aligned to the NX patterns.
