### ISSUE TITLE
`lerna run` cannot find project in v6, with nested lerna config

### ISSUE THREAD

**Issue by maribethb** [lerna/lerna#3548]
I recently updated to lerna v6. I'm using v6.4.1. `lerna run` is no longer working for me, unless I add the `useNx: false` to my `lerna.json` config. The release notes asked me to file an issue if I needed to do this, so here I am.

In my monorepo, I actually have two layers of lerna. At the top level we set up lerna to act on every directory inside the `plugins` directory. There is also a top-level `examples` directory, which has its own `lerna.json` config. I am not sure if this is explicitly supported, but it's been working for us so far. This problem only occurs for us in the `examples` directory, i.e. in the nested lerna directory.

```
- plugins/
    - package-a
    - package-b 
- examples/
    - package-c
    - package-d
    - lerna.json <-- only this one needs `useNx: false` 
- lerna.json <-- configured to look in the `plugins` directory only
```

## Current Behavior

This happens in the google/blockly-samples repo, but I've also made a minimal reproduction listed below.

```
npx lerna run build
lerna notice cli v6.4.1
lerna info versioning independent
 >  Lerna (powered by Nx)   Successfully ran target build for 0 projects (6ms)
 
$ npx lerna run predeploy
lerna notice cli v6.4.1
lerna info versioning independent

 >  Lerna (powered by Nx)   Cannot find project 'blockly-react-sample'
```

## Expected Behavior

`lerna run build` runs in multiple packages inside `examples/`
`lerna run predeploy` runs correctly - `predeploy` script is only in one package inside `examples/`, namely the directory `blockly-react` which contains the package.json with a project named `blockly-react-sample`

## Steps to Reproduce

Listed here: https://github.com/lerna/repro/pull/9

</p></details>

### Environment

Environment info:

  System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Utilities:
    Git: 2.39.1.581. - /usr/local/git/current/bin/git
  npmPackages:
    lerna: ^6.3.0 => 6.5.1 

(Note this also occurs on Node 16)

As a related note, if nested lerna configs are not supported, I'd be interested in hearing about alternatives. In this repo, `plugins` is our "main" monorepo which actually does have interconnected package dependencies. 90% of the time we use lerna it's only on the `plugins` directory. The `examples` packages are not interdependent, we just use lerna to run bulk commands in each package for times when we are updating our website, for example. When we want to run tests in CI though we don't run tests in the `examples` directory, which is why the configs are separate. Last I looked into it, the "scope" argument wasn't enough for us because it doesn't work on directory names, only the package names, and our packages do not have a consistent prefix we could use.

**Comment by maribethb** [comment]
Also related, I tried running the `lerna add-caching` command from within the `examples` subdirectory, and it added the config to the parent directory instead (despite the subdirectory having its own lerna config, as above)

**Comment by JamesHenry** [comment]
Hi @maribethb, thanks a lot for the clear write up and reproduction of the issue.

I will take a look now and provide a recommendation on your own repo's issue

**Comment by JamesHenry** [comment]
I spent a significant amount of time getting to know your repo and provided comprehensive recommendations here: https://github.com/google/blockly-samples/pull/1597

Best of luck!
