### ISSUE TITLE
Installing lerna shows two deprecated warnings for used module functionality

### ISSUE THREAD

**Issue by mleenaerts** [lerna/lerna#3550]
When installing lerna via npm install two warning are being showed about the usage of deprecated functionalities of used modules. This is present in both older version (5.5.2) and on the most recent version (6.5.1)

npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

## Expected Behavior

I would prefer the replacement of the deprecated code to avoid potential future issues as soon as possible.

## Steps to Reproduce

Create an empty folder and create a package.json file in that folder with the following content.

```
{
  "name": "test-app",
  "devDependencies": {
    "lerna": "6.5.1"
  }
}
```

Run `npm install` and notice the warning message regarding deprecated functionality.

### Failure Logs / Configuration

```
npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
```

**Comment by amorscher** [comment]
I think this not caused by lerna itself. npmcli/arborist package is using this deprecated functionality. By updating to the actual version one warning can be removed. See the attached pull request.

**Comment by mleenaerts** [comment]
Thanks for picking it up.
