### ISSUE TITLE
Improve git binary error

### ISSUE THREAD

**Issue by poteirard** [lerna/lerna#3557]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/lerna/lerna/blob/main/CONTRIBUTING.md))

## Description

The current error `The git binary was not found, or this is not a git repository` when there's a problem with `git` using `--since` seems a bit unclear.

In my end, what was happening in the CI was that the `git` binary didn't have the proper ownership permissions to run `git rev-parse`.

The Git ownership check is explained here: https://github.blog/2022-04-18-highlights-from-git-2-36/#stricter-repository-ownership-checks And here https://stackoverflow.com/a/73488472/1762002

## Motivation

It was hard to debug the problem, and I needed to read Lerna's code. So I want to help other people to have a better experience.

## Suggested Implementation

I would like change this error message:
https://github.com/lerna/lerna/blob/ce2ceca7defd06fc2c8abf0241cbb2c3dcfaf0f3/libs/core/src/lib/command/index.ts#L270
To something like:
```
The git binary was not found, this is not a git repository, or you git doesn't have the right ownership. Run `git rev-parse` to get more details.
```

## Alternate Implementations

We could have more granularity of the errors, like checking if git exists to show a different error.

**Comment by Nickman87** [comment]
Thank god I found this Issue, was having the same kind of error and runnign `git rev-parse` helped me fix it
