### ISSUE TITLE
Yarn install fails on example app due to missing version field

### ISSUE THREAD

**Issue by brownieboy** [lerna/lerna#3562]
## Current Behavior

Running `yarn install` on Getting Started Example (https://github.com/lerna/getting-started-example) does not install dependencies for the Remix app.  Gives following warning:

> warning Missing version in workspace at "lerna-getting-started/packages/remixapp", ignoring.

Despite the "warning" tag, it actually fails to install dependencies for the Remix app, so not much else works after that.

## Expected Behavior

Running `yarn install` should install the dependencies for all three sample apps.

I don't know if this has ever worked.  Perhaps it works with npm rather than yarn?  (I didn't try.)

Adding a `version` entry in packages/remixapp/package.json fixes the issue:

```json
{
  "name": "remixapp",
  "version": "0.0.0",
```

## Steps to Reproduce

Clone the sample app and run `yarn install`.   If you don't have yarn installed, you can install it with `npm i yarn -g`.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "useWorkspaces": true,
  "version": "0.0.0"
}

```

</p></details>

### Environment

WSL 2 under Windows 10.

**Comment by fahslaj** [comment]
Hi @brownieboy, thank you for reporting this issue. It appears that `yarn` requires a version, but `npm` doesn't. The getting started example does use npm and works correctly when running `npm install`. 

However, just for good measure, I've gone ahead and made the change in the example workspace in case anyone else tries to use Yarn. Thanks!
