### ISSUE TITLE
`lerna version` is stuck if there are peerdependencies within the monorepo (npm workspaces).

### ISSUE THREAD

**Issue by zimtsui** [lerna/lerna#3578]
## Current Behavior

There are 2 packages in the monorepo (npm workspaces): `a` and `b`

`packages.json` of `a`:

```json
{
    "name": "a",
    "version": "0.0.5"
}
```

`package.json` of `b`:

```json
{
  "name": "b",
  "version": "0.0.1",
  "peerDependencies": {
    "a": "^0.0.5"
  }
}
```

`lerna.json`:

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "useWorkspaces": true,
  "version": "0.0.0"
}
```

Now, run `lerna version 0.0.6`, it will be stuck at

```
lerna notice cli v6.5.1
lerna info current version 0.0.0
lerna notice FYI git repository validation has been skipped, please ensure your version bumps are correct
lerna info Looking for changed packages since v0.0.5
lerna WARN version Skipping working tree validation, proceed at your own risk

Changes:
 - a: 0.0.5 => 0.0.6
 - b: 0.0.1 => 0.0.6

? Are you sure you want to create these versions? Yes
lerna info execute Skipping git tag/commit
lerna info execute Skipping git push
lerna info execute Skipping releases
^C
```

This issue is related to #2402 and [emberjs/data#8295](https://github.com/emberjs/data/issues/8295) It may make sense not to update the version number, but it never makes sense to be stuck.

## Steps to Reproduce

As to Lerna 6.5.1, `lerna version` will stuck if there are any peerdependencies among local packages within the monorepo.

There is an simple [demo repo](https://github.com/zimtsui/lerna-bug), just follow the README and you can reproduce it.

## Environment

```
lerna notice cli v6.5.1

 Environment info:

  System:
    OS: Linux 6.0 Debian GNU/Linux bookworm/sid
    CPU: (4) x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
  Binaries:
    Node: 18.13.0 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
  Utilities:
    Git: 2.39.1 - /usr/bin/git
  npmPackages:
    lerna: ^6.5.1 => 6.5.1
```

**Comment by zimtsui** [comment]
The stuck point is `npm install --package-lock-only` during `lerna version patch`.

After `lerna version`, `a` becomes 0.0.6 but `b` still depends on `"a": "^0.0.5"`. `npm install --package-lock-only` cannot find a proper `a` and get stuck.

That's because [semver](https://semver.org/) says it's a breaking change from `0.0.5` to `0.0.6`.

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

**Comment by fahslaj** [comment]
Hi @zimtsui , thank you for reporting this issue. As you mentioned, this issue appears to be with the npm install hanging. This appears to be due to mismatched node and npm versions.

For node@18.13.0, the bundled version of npm is 8.19.3.
For node@18.15.0 (the current lts version), the bundled version of npm is 9.5.0.

If you use either of these combinations, then the install will no longer hang and will instead will rightfully fail due to peer dependency conflicts.

**Comment by zimtsui** [comment]
This should be a bug of [@npm/cli](https://github.com/npm/cli).
