### ISSUE TITLE
Missing add-caching command from npx lerna

### ISSUE THREAD

**Issue by stuft2** [lerna/lerna#3584]
## Current Behavior

Currently the command `add-caching` is missing when running lerna with npx.

## Expected Behavior

The command shouldn't be missing.

## Steps to Reproduce

Run `npx lerna add-caching` in the terminal

### Failure Logs / Configuration

```
ERR! lerna Unknown argument: add-caching
```

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "useWorkspaces": true,
  "version": "0.0.0",
  "changelogPreset": "angular"
}

```

</p></details>

### Environment

  System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
  Utilities:
    Git: 2.33.0 - /usr/local/bin/git

**Comment by JamesHenry** [comment]
@stuft2 what version of lerna are you using? I cannot reproduce this on the latest (`6.5.1`)

**Comment by stuft2** [comment]
I closed my terminal and opened a new one and tried again. It's working as expected.
