### ISSUE TITLE
Running `npm run build` always returns `Cannot read property 'name' of undefined`

### ISSUE THREAD

**Issue by darryltec** [lerna/lerna#3585]
Hi, just updated to v6.5.1 from v3.20.2 and everything seems to work great! Except for `lerna run`.

## Current Behavior

Running `npx lerna run [script]` always returns 

```
Lerna (powered by Nx)   Cannot read property 'name' of undefined
```

and nothing else. Nothing to go on when debugging it. Confirmed that all of my `package.json` have a name on them.

## Expected Behavior

Expected it to run normally like your [documentation](https://lerna.js.org/docs/features/run-tasks#run-everything) mentioned. For example

Running `npx lerna run build` should run the scripts

```
    ✔  header:build (501ms)
    ✔  footer:build (503ms)
    ✔  remixapp:build (670ms)

 —————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Successfully ran target build for 3 projects (1s)
```

or at the very least, returns more error logging

## Steps to Reproduce

- run `npx lerna run [your script]`
- That's it!

### Failure Logs / Configuration

Tried to run `lerna repair` and that returned 
![image](https://user-images.githubusercontent.com/15986172/225033998-9275fcb7-1995-42f7-85d1-db566c7fc395.png)

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "packages": [
    "packages/*"
  ],
  "command": {
    "version": {
      "conventionalCommits": true,
      "message": "chore(release): Publish",
      "allowBranch": [
        "master"
      ]
    },
  },
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "useWorkspaces": false
}
```

</p></details>

### Environment

```
  System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
  Utilities:
    Git: 2.39.1 - /usr/local/bin/git
  npmPackages:
    lerna: ^6.5.1 => 6.5.1
```

**Comment by fahslaj** [comment]
Hi @darryltec , thank you for opening this issue. Unfortunately, I am unable to reproduce this issue based on the information you have provided. Could you please create and share a minimal reproduction of the issue? You can use https://github.com/lerna/repro as a base, or provide your own repository.

**Comment by darryltec** [comment]
Hi @fahslaj, you can actually try it on [our repo](https://github.com/GetJobber/atlantis) in master.  Pull that down, `npm ci`, then `npx lerna run clean` would trigger that error as well

**Comment by darryltec** [comment]
@fahslaj ah, that's actually the reason why we're bumping to latest. We're going straight to node 18. That's good to know. I'll try it on my node 18 branch and see how it goes and report back here.

**Comment by darryltec** [comment]
Okay yeah, we are good! Thanks @fahslaj! This is gonna get logged onto, why did I not think of that 😆
