### ISSUE TITLE
Question: how to fix versions between dependencies?

### ISSUE THREAD

**Issue by SamyPesse** [lerna/lerna#359]
I don't know if Lerna has some automation to manage this, and I couldn't find any related issues to this:

Basically, I understand that the "Fixed/Locked mode" uses one version for all modules (this is what I want), but is there a way to fix dependencies between modules?

For example, if A depends on B, and the `version` in `lerna.json` is `4.1.0`, I want `packages/A/package.json` to be updated with:

``` js
{
  "dependencies": {
    "B": "4.1.0"
  }
}
```

instead of `"B": "^4.0.0"` (it seems to be what Babel is doing).

**Comment by SamyPesse** [comment]
Update: It doesn't look like something that can be done by lerna. I'll write a script in the repository to update all `package.json` files to fix versions according to the "master" version.

**Comment by SamyPesse** [comment]
Here is the script I'm using:

```js
#! /usr/bin/env node

const fs = require('fs');
const path = require('path');

const lernaConfig = require('../lerna.json');

// List all the packages
const PACKAGES_DIR = path.resolve(__dirname, '../packages');
const packages = fs.readdirSync(PACKAGES_DIR);

function updateDependencies(dependencies) {
    Object.keys(dependencies).map((key) => {
        if (!packages.includes(key)) {
            return;
        }

        dependencies[key] = lernaConfig.version;
    });
}

packages.forEach((name) => {
    // Avoid .DS_Store
    if (name[0] === '.') {
        return;
    }

    const pkgPath = path.resolve(PACKAGES_DIR, name, 'package.json');
    const pkg = require(pkgPath);

    pkg.version = lernaConfig.version;
    updateDependencies(pkg.dependencies);
    updateDependencies(pkg.devDependencies);

    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 3), 'utf-8');
});
```

**Comment by Gongreg** [comment]
Hey, when do you run this script? One person in our team accidentally made a change in multiple packages, which looked like it didn't create a breaking change, but because inner package dependencies are not locked, it broke other place which used older version. This thing would help us a lot.

**Comment by thejameskyle** [comment]
Merging into #259

**Comment by gigabo** [comment]
Looking at this again, I think it may actually be different from #259.  If I'm reading this right, this issue is about pinning to exact versions _within_ the repo, while #259 is about managing _external_ deps.

@Gongreg pointed out that https://github.com/lerna/lerna/pull/426 seems to address _this_ issue.

**Comment by develar** [comment]
My expectation was exactly the same — dependent package version should be fixed, not using `^` or `~` My main package is an aggregator of other packages and, so, I want to be sure that all are compatible and tested together, so, versions should be fixed.

**Comment by vitorbal** [comment]
I think this can be closed now that https://github.com/lerna/lerna/pull/426 was merged, which adds support for the `--exact` flag.
