### ISSUE TITLE
lerna.json schema: "contents" seems to have the wrong type

### ISSUE THREAD

**Issue by humodz** [lerna/lerna#3607]
## Current Behavior

In the JSONSchema for lerna.json, the `contents` option has type `booolean`:
```json
{
  "contents": {
    "type": "boolean",
     "description": "For `lerna bootstrap`, `lerna link`, and `lerna publish`, the subdirectory to use as the source of any links. Must apply to ALL packages."
  },
}
```

## Expected Behavior

The `version`, `bootstrap` and `publish` commands actually take a string as argument, like so:

```sh
npx lerna publish --contents dist
```

**Shoudn't the same parameter in lerna.json have type string as well?**

## Steps to Reproduce

Simply open the lerna.json below in VSCode

![lerna-contents](https://user-images.githubusercontent.com/8527969/227331974-8c4c3d87-05ea-4a86-8c2c-b11a06b6c091.png)

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
    "$schema": "node_modules/lerna/schemas/lerna-schema.json",
    "useNx": true,
    "useWorkspaces": true,
    "contents": "dist"
}
```

</p></details>

### Environment

```
$ npx lerna info
lerna notice cli v5.6.2
lerna info versioning independent

 Environment info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Utilities:
    Git: 2.25.1 - /usr/bin/git
  npmPackages:
    lerna: ^5.6.2 => 5.6.2 
```

**Comment by JamesHenry** [comment]
Thanks @humodz this will be fixed in the next release (going out shortly)
