### ISSUE TITLE
Support Deno

### ISSUE THREAD

**Issue by airtonix** [lerna/lerna#3608]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/lerna/lerna/blob/main/CONTRIBUTING.md))

## Description

- run lerna as an esm import: `deno run https://esm.sh/lerna@latest/bin/lerna.js`
- not require npm, yarn or pnpm
- use file other than `package.json` to describe the monorepo dependency graph (ie `project.json`)
- respect single `import_map.json` at root only

## Motivation

orange npm man bad.

## Suggested Implementation

magically. without complaint or dissent.

## Alternate Implementations

heresy, there is no alternative!

**Comment by fahslaj** [comment]
@airtonix , Thank you for opening this feature request! For now, you can also use nx + @nrwl/deno to create deno apps in a monorepo.

**Comment by airtonix** [comment]
`T_T`

**Comment by pfteter** [comment]
deno 2.0 is out, any plans ?
