### ISSUE TITLE
Can no longer install lerna on node 14 -   Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sginn** [lerna/lerna#3609]
## Current Behavior

```
npm install lerna@6.4.1
```
> npm ERR! Maximum call stack size exceeded

## Expected Behavior
The older, pinned version of lerna should still work

## Steps to Reproduce

This occurs in our CI environment, and locally on developer machines.
Last successful run I can see was ~16hrs ago, before the 6.6.0 release.

1) Open a terminal
2) run `npm install lerna@6.4.1`

### Failure Logs / Configuration

[2023-03-23T23_20_33_342Z-debug.log](https://github.com/lerna/lerna/files/11057155/2023-03-23T23_20_33_342Z-debug.log)

</p></details>

### Environment

On my local machine:
```
Last login: Thu Mar 23 16:20:00 on ttys008
➜  ~ npm --version
6.14.17
➜  ~ node --version
v14.20.1
➜  ~ 
```

**Comment by khross** [comment]
This appears to be due to version `15.8.8` in the `@nrwl/devkit` which no longer installs using node v14. Upgrading to v18 fixed the issue for us.

**Comment by sginn** [comment]
@khross that is perfect!  We're working on a node upgrade, but it's complicated for a number of reasons.

Just pinning devkit in our react/react-native monorepo wasn't quite enough.  went a little aggressive and pinned them all and things started working in node 14 hopefully for a few more days
```
npm install --exact @nrwl/cli@15.4.2 @nrwl/devkit@15.4.2 @nrwl/eslint-plugin-nx@15.4.2 @nrwl/jest@15.4.2 @nrwl/js@15.4.2 @nrwl/linter@15.4.2 lerna@6.4.1
```

**Comment by fahslaj** [comment]
There are a couple known issues with Lerna on node v14. I would suggest upgrading to at least Node 16, since Node 14 reaches the end of its maintenance life after next month.

**Comment by ceynri** [comment]
I tried several versions and finally found that 5.1.8 can be installed on node14, 5.2.0 is not.

**Comment by JamesHenry** [comment]
We're sorry about this folks, it was not intentional to drop support for node v14 in a minor version. We will be calling this out explicitly in the upcoming v7 release.

@ceynri whilst this is true, what @fahslaj says is important. Node v14 is fully _dead_ in literally 4 weeks from now. That means the Node organization themselves will never again submit any critical security fixes for it, no matter what vulnerabilities may be discovered.

I would encourage anybody reading this to upgrade to node 16 or node 18 and not wait until node 14 is completely EOL

**Comment by Marthym** [comment]
Same problem and can't upgarde node

**Comment by cheryly279** [comment]
We are seeing this issue on node16, can someone advise? Upgrading to 18 may not be feasible right now.

**Comment by JamesHenry** [comment]
Hi Folks,

I'm pleased to say that we have been able to release a patch to Nx which allows it to still work on node 14. It is `15.8.9`, so as long as that is the version you have installed it should work.

Lerna's dependency already includes all future 15.x releases so nothing needs to change on the lerna side. You might just need to do a fresh install and/or update your lockfile to ensure that `15.8.9` of nx is pulled in.

Again, just to reiterate, you should still consider upgrading your node version to 16 or ideally 18 (as 16 only has 5 months of support left from Node) as soon as possible.

Many thanks and sorry again for the unintentional breakage!

**Comment by Marthym** [comment]
It seem to work when installing lerna with yarn instead of npm
