### ISSUE TITLE
Unable to build on windows due to module not found @nrwl\nx-win32-x64-msvc\nx.win32-x64-msvc.node

### ISSUE THREAD

**Issue by lnmp4000** [lerna/lerna#3612]
This is an issue affecting Windows machines:

![image](https://user-images.githubusercontent.com/2903591/227495693-14871d9a-bd30-4370-a998-fd82fac207cb.png)

## Current Behavior
I can successfully build on Linux, but when my colleagues attempt the same build on windows, they encounter the above error.
Looking in the `node_modules` folder I can see the nx.win32-x64-msvc.node file in the expected path.

## Expected Behavior

Builds should work on Windows as well as Linux machines.

## Steps to Reproduce

Using a Windows machine and
Node v18.13.0
npm v8.19.3

Follow steps:
```
git clone https://github.com/lerna/getting-started-example.git
cd getting-started-example
git checkout prelerna
npm install
```
Within the above folder

```
npx lerna@latest init
npm install
npx lerna@latest run build
```

The following message is shown on Windows machines
![image](https://user-images.githubusercontent.com/2903591/227499962-4034a304-c62b-49f7-b3e2-94d6f2cb23aa.png)

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "useWorkspaces": true,
  "version": "0.0.0"
}
```

### Environment

lerna notice cli v6.6.0

 Environment info:

  System:
    OS: Windows 10 10.0.17763
    CPU: (2) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.39.0. - /mingw64/bin/git
  npmPackages:
    lerna: ^6.6.0 => 6.6.0

**Comment by lnmp4000** [comment]
I do have those entries in the `package-lock.json`

```
 "node_modules/@nrwl/nx-linux-x64-musl": {
            "version": "15.8.9",
            "resolved": "https://registry.olmeservices.co.uk/repository/npm-all/@nrwl/nx-linux-x64-musl/-/nx-linux-x64-musl-15.8.9.tgz",
            "integrity": "sha512-0RSEqFdwJmJZDhuj8yOKqxIr7olY4Xm+0hMNjz+20BVi2g37Oq138VC0iikzwaQVDP5Ude3cVaoRw4VBYlPfNw==",
            "cpu": [
                "x64"
            ],
            "dev": true,
            "optional": true,
            "os": [
                "linux"
            ],
            "engines": {
                "node": ">= 10"
            }
        },
        "node_modules/@nrwl/nx-win32-arm64-msvc": {
            "version": "15.8.9",
            "resolved": "https://registry.olmeservices.co.uk/repository/npm-all/@nrwl/nx-win32-arm64-msvc/-/nx-win32-arm64-msvc-15.8.9.tgz",
            "integrity": "sha512-GRs0cF3hyT7wdwlTwP4L5HG9LuHxt+I0/lTYzzUsUSs2WIvn6qycoKZv1qc/aSdZv+LgdKiPE5U7zHEVc6zpaA==",
            "cpu": [
                "arm64"
            ],
            "dev": true,
            "optional": true,
            "os": [
                "win32"
            ],
            "engines": {
                "node": ">= 10"
            }
        },
        "node_modules/@nrwl/nx-win32-x64-msvc": {
            "version": "15.8.9",
            "resolved": "https://registry.olmeservices.co.uk/repository/npm-all/@nrwl/nx-win32-x64-msvc/-/nx-win32-x64-msvc-15.8.9.tgz",
            "integrity": "sha512-u0L3T1ZMr4j1YM+6DdxnaJUl+VSkbSu+2vcLvLyo+c+Ekhr/JDirXPfyCdoM6c/DN+1NK1Km29soawX9Oyb2MA==",
            "cpu": [
                "x64"
            ],
            "dev": true,
            "optional": true,
            "os": [
                "win32"
            ],
            "engines": {
                "node": ">= 10"
            }
        }
```

I have also tried to re-generate the package-lock on the windows machine, but the error still exists.

**Comment by JamesHenry** [comment]
Hmm I wonder if your custom registry is playing a role here...

`https://registry.olmeservices.co.uk`

Please could you delete the lockfile again and try `npm install --registry=https://registry.npmjs.org` (or remove however you have configured the custom registry before running `npm install`

**Comment by jazzominy** [comment]
@lnmp4000 can you try installing Microsoft Visual C++ 2015 Redistributable (x64)

You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

Accessing native windows code (nx-win32-arm64-msvc package) requires above redistributable. Hope this helps. I face the similar error and found that i didnt have the redistributable installed. Installing it fixed the error

**Comment by codarose** [comment]
@jazzominy We are having a really similar issue with a windows user, except it says we are missing '@nrwc/nx-win32-ia32-msvc'. Any ideas how to fix that?

**Comment by lnmp4000** [comment]
The fix for this issue is to install the Microsoft Visual C++ 2015 Redistributable  package on any affected windows machine.

**Comment by jazzominy** [comment]
> @jazzominy We are having a really similar issue with a windows user, except it says we are missing '@nrwc/nx-win32-ia32-msvc'. Any ideas how to fix that? 

Check the node_modules/@nrwl/nx-win32-msvc folder. If it is there and you have your error. Then install the required ms visual redistributable as suggested in me earlier comment.

**Comment by kujtimprenkuSQA** [comment]
For anyone who has **Microsoft Visual C++ 2015 Redistributable** installed on Windows and still faces this issue these steps fixed the it for me:
- Remove`node_modules`
- Run `yarn cache clean`
- Run `yarn install`

**Comment by TrofimovMishka** [comment]
These steps help me:
 - Microsoft Visual C++ 2015 Redistributable;
 - Remove node_modules directory;
 - Remove package-lock.json file;
 - npm cache verify;
 - Restart the machine;
 - npm install;

**Comment by magdalsen** [comment]
> @lnmp4000 can you try installing Microsoft Visual C++ 2015 Redistributable (x64)
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe
> 
> Accessing native windows code (nx-win32-arm64-msvc package) requires above redistributable. Hope this helps. I faced the similar error and found that i didnt have the redistributable installed. Installing it fixed the error
> 
> I came across this [parcel-bundler/parcel#7104 (comment)](https://github.com/parcel-bundler/parcel/issues/7104#issuecomment-967260755) and it helped

For me also helped! I installed  Microsoft Visual C++ 2015 Redistributable (x64).
I had similar issue:

node:internal/modules/cjs/loader:1327
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\[user_folder]\Documents\epenses-app\node_modules\@rollup\rollup-win32-x64-msvc\rollup.win32-x64-msvc.node

**Comment by jamessv** [comment]
based on your architecture download and install package from here
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by theashutoshshukl** [comment]
Finally, npm run dev issue solved by downloading this on my pc - 
https://aka.ms/vs/17/release/vc_redist.x64.exe.

**Comment by abobakar-itbeam** [comment]
> Finally, **npm run dev issue solved** by downloading this on my pc - https://aka.ms/vs/17/release/vc_redist.x64.exe.

**Comment by fahslaj** [comment]
For additional users experiencing similar issues, see the [troubleshooting nx installation docs](https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues)

**Comment by alexxcamargo** [comment]
This error happens, when you install Node Windows 32-bits in a windows 64-bits.


![image](https://github.com/lerna/lerna/assets/7258051/9a79d8de-cdcd-460e-a5cb-ff795fb51683)

**Comment by JawedCIA** [comment]
npm ERR! Error: The specified module could not be found.
npm ERR! \\?\C:\azp\agent\_work\1\s\Frontend\node_modules\@nx\nx-win32-x64-msvc\nx.win32-x64-msvc.node

We had similar issue with Code compilation inside windows container. However after installing VC_redist.x64.exe in windows container solved the issue (as suggest above in few reply).

In DockerFile we added installation of  VC_redist.x64.exe
RUN start-process -Filepath .\VC_redist.x64.exe -ArgumentList @('/install', '/quiet', '/norestart') -Wait; `
Remove-Item -Force VC_redist.x64.exe;

and at the end all SET with green build :)

**Comment by khelkun** [comment]
This workaround the issue about the nx module installation on Windows might be mentioned on the [buildSystem.md](https://github.com/BabylonJS/Babylon.js/blob/master/buildSystem.md) in some "Windows isntallation" section?

> This error occurs when you install the 32-bit version of Node on a 64-bit Windows system.

I don't think so, I have node 18 64-bit.

**Comment by IsunGitHub** [comment]
> @lnmp4000您可以尝试安装 Microsoft Visual C++ 2015 Redistributable (x64)
> 
> 你可以从此处下载 -> https://aka.ms/vs/17/release/vc_redist.x64.exe
> 
> 访问本机 Windows 代码（nx-win32-arm64-msvc 包）需要上述可再发行组件。希望这能有所帮助。我遇到了类似的错误，发现我没有安装可再发行组件。安装它修复了错误
> 
> 我偶然发现了这个[parcel-bundler/parcel#7104 (评论)](https://github.com/parcel-bundler/parcel/issues/7104#issuecomment-967260755)，它很有帮助

有用，感谢大佬！

**Comment by kobL** [comment]
> This error occurs when you install the 32-bit version of Node on a 64-bit Windows system.
> 
> https://nodejs.org/en/download/current
> 
> ![image](https://private-user-images.githubusercontent.com/7258051/294523770-9a79d8de-cdcd-460e-a5cb-ff795fb51683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDc4NjMsIm5iZiI6MTcyMzgwNzU2MywicGF0aCI6Ii83MjU4MDUxLzI5NDUyMzc3MC05YTc5ZDhkZS1jZGNkLTQ2MGUtYTVjYi1mZjc5NWZiNTE2ODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTEyNjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTFhMWFhYzg4MGIwZjQ4OGIzN2U3OTQzNDFiMDNjMzEwZDBjYWE4NGVhMjZkYWU3ZmZjMjU2ZjI5N2FhNWNhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LcbHaxj4PZllT4qPCobr1A3k7sW_YrpjT0jGMUzxI7E)

We also had the problem with the missing '@nrwc/**nx-win32-ia32-msvc**

Turns out the 32-bit version of node was installed by accident, with the 64 bit version the error disappeared.

**Comment by ElectroBuddha** [comment]
This is what has worked for me:
```
npm i @nx/nx-win32-x64-msvc --force
npm cache clean --force
npm install --legacy-peer-deps
```

**Comment by DanielRuf** [comment]
A simple check for the relevant libraries could be also done, see for example https://github.com/httptoolkit/check-msvc-runtime

IMHO DX-wise this is could be better.

**Comment by DanielRuf** [comment]
A simple (preinstall) check for the relevant libraries could be also done, see for example https://github.com/httptoolkit/check-msvc-runtime

IMHO DX-wise this is could be better.

**Comment by nayarmanue** [comment]
> > [@lnmp4000](https://github.com/lnmp4000) can you try installing Microsoft Visual C++ 2015 Redistributable (x64)
> > You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe
> > Accessing native windows code (nx-win32-arm64-msvc package) requires above redistributable. Hope this helps. I faced the similar error and found that i didnt have the redistributable installed. Installing it fixed the error
> > I came across this [parcel-bundler/parcel#7104 (comment)](https://github.com/parcel-bundler/parcel/issues/7104#issuecomment-967260755) and it helped
> 
> Thank you so much for sharing—your solution really helped resolve my issue. Much appreciated!"

thank you ,your solution helped me to fix the problem

**Comment by nayarmanue** [comment]
> > Finally, **npm run dev issue solved** by downloading this on my pc - https://aka.ms/vs/17/release/vc_redist.x64.exe.

thank you

**Comment by jyotiska222** [comment]
### Rollup Version

4.37.0

### Operating System (or Browser)

10/11

### Node Version (if applicable)

Node.js Version: v22.14.0  |  npm Version: latest (npm 9.x)

### Link To Reproduction

https://github.com/jyotiska222/HealthCare.git

### Expected Behaviour

**Description:**
I'm encountering an error when trying to run the `npm run dev` command for the frontend of the project on a Windows machine. The error states that it cannot find the module `@rollup/rollup-win32-x64-msvc`.

**System Information:**
- OS: Windows 10/11
- Node.js Version: v22.14.0
- npm Version: latest (npm 9.x)
- Git: Latest

**Steps to Reproduce:** (Only Produced in my system)
1. Clone the repository: `git clone https://github.com/jyotiska222/HealthCare.git`
2. Navigate to the `frontend` 
3. Install the dependencies: `npm i`
4. Run the development server: `npm run dev`

**Expected Behavior:**
The development server should start without any issues.

### Actual Behaviour

**Actual Behavior:**
The following error occurs when running `npm run dev`:

```
Error: Cannot find module @rollup/rollup-win32-x64-msvc. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
```

**Error Details:**
```
Error: Cannot find module @rollup/rollup-win32-x64-msvc
    at requireWithFriendlyError (D:\test_project_health_care\Decentralized-Ticketing-System\frontend\node_modules\rollup\dist\native.js:64:9)
    at Object.<anonymous> (D:\test_project_health_care\Decentralized-Ticketing-System\frontend\node_modules\rollup\dist\native.js:73:76)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at cjsLoader (node:internal/modules/cjs/loader:262:5)
    at ModuleWrap.<anonymous> (node:internal/modules/cjs/loader:196:7) {
  [cause]: Error: Cannot find module '@rollup/rollup-win32-x64-msvc'
  Require stack:
    - D:\test_project_health_care\Decentralized-Ticketing-System\frontend\node_modules\rollup\dist\native.js
```

**System Information:**
- OS: Windows 10/11
- Node.js Version: v22.14.0
- npm Version: latest (npm 9.x)
- Git: Latest

**Troubleshooting Steps Already Taken:**
1. I ran `npm i` again after removing `package-lock.json` and the `node_modules` directory.
2. The issue persists despite multiple attempts.

### ***Other Information:***
**The same project works perfectly fine on another Windows system with the same setup, so the issue seems to be specific to my environment. I have verified that there are no additional dependencies missing.**

![Image](https://github.com/user-attachments/assets/0d224963-df2c-4122-87c3-2ce6834e49db)

##**MY SYSYEM INSTALLING THE LINUX VERSION OF @rollup MODULE IN MY WIN11**

**Comment by shinobako** [comment]
> [@lnmp4000](https://github.com/lnmp4000) can you try installing Microsoft Visual C++ 2015 Redistributable (x64)
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe
> 
> Accessing native windows code (nx-win32-arm64-msvc package) requires above redistributable. Hope this helps. I faced the similar error and found that i didnt have the redistributable installed. Installing it fixed the error
> 
> I came across this [parcel-bundler/parcel#7104 (comment)](https://github.com/parcel-bundler/parcel/issues/7104#issuecomment-967260755) and it helped

you are my savior，bro
