### ISSUE TITLE
[Feature] Validate package.json's have name and version

### ISSUE THREAD

**Issue by dimaip** [lerna/lerna#363]
Took me some time to figure out why a package was not symlinked by lerna, it appeared that it didn't have `version` specified in its `package.json`. Could be nice to mention it in the README.

**Comment by chrislloyd** [comment]
I'd like to add to this and ask that an error is thrown in Lerna in addition to it being documented in the README. Currently if no version is specified in a package, Lerna defaults to installing from NPM  and the cause of this is non-obvious.

**Comment by thejameskyle** [comment]
Which `package.json` the repo-level one or one inside a package?

**Comment by chrislloyd** [comment]
The `package.json` inside a package. I initially ran Lerna in fixed mode and assumed I only needed 1 `version` in the root `package.json`.

**Comment by thejameskyle** [comment]
Ah okay, yeah we should validate `package.json`. But btw, a `package.json` is considered "invalid" if it does not have a name and version according to npm.

**Comment by dimaip** [comment]
@thejameskyle true, but I only found out about it after hitting this issue, and accidentally seeing this notice in npm docs. I myself always added it, but I was integrating Lerna in community code, and one of the packages had no version...

**Comment by thejameskyle** [comment]
Yup, in general if there's an error from Lerna that is either not catching something early on or has a non-obvious message feel free to report that because we want to improve the experience

**Comment by mrfelton** [comment]
We use semantic-release for most of our packages and with it we use the recommended version string of "0.0.0-semantically-released.0". Lerna ignore packages with a version string like this (evn though it is a valid version string) and doesn't symlink those packages.
