### ISSUE TITLE
lerna version hangs in CI

### ISSUE THREAD

**Issue by tyler-boyd** [lerna/lerna#3635]
## Current Behavior

When running `npx lerna version` in my azure pipeline, the process hangs. It works fine locally, even with the same git sha checked out and node/npm versions.
<img width="739" alt="image" src="https://user-images.githubusercontent.com/4432772/230147515-24256822-c3c9-4c39-ac42-c9e2322d65cd.png">
-> no more output, even after 1h (takes only a second locally)

## Expected Behavior

`npx lerna version` should run successfully, or at least print a useful error message. Even with `--loglevel debug` there is nothing to go off of.

## Steps to Reproduce

Unfortunately I cannot even reproduce it myself locally. It only happens on my CI. Here is the failing step definition:

```yaml
node -v
npm -v
git checkout "$(Build.SourceBranchName)" --
echo "@kar-dmp:registry=https://npm.pkg.github.com/:_authToken=$(GITHUB_PAT)" > ~/.npmrc
# npm ci
npx lerna bootstrap
npx lerna version --allow-branch "$(Build.SourceBranchName)" --conventional-commits --tag-version-prefix "ts-v"
npx lerna publish from-git --conventional-commits --registry "https://npm.pkg.github.com"
```

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "useWorkspaces": true,
  "version": "0.0.5"
}
```

</p></details>

### Environment

* CI agent: ubuntu-20.04
* Node: 18.15.0
* Npm: 9.5.0
* lerna@6.6.1

**Comment by tyler-boyd** [comment]
Adding `--yes` appears to have fixed the issue. I still think this is a bug though -- the lerna output shows it detects it's running in a CI environment, so I don't think it should wait for input.

**Comment by fahslaj** [comment]
We want to keep Lerna's behavior in CI consistent with when it is run locally, so using `--yes` is the suggested fix for bypassing prompts in CI.

**Comment by tyler-boyd** [comment]
Fair enough, but I definitely disagree with that decision. Regardless of CI or not, I thought the standard for tools that ask for prompts is to at least throw an error if you're prompting but stdin isn't a TTY. Or perhaps have a reasonable timeout?
