### ISSUE TITLE
lerna bootstrap fails due to missing rimraf callback function 

### ISSUE THREAD

**Issue by raymondfeng** [lerna/lerna#3636]
## Current Behavior

```
lerna notice cli v6.6.1
lerna info versioning independent
lerna info Bootstrapping 90 packages
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna ERR! AssertionError [ERR_ASSERTION]: rimraf: callback function required
lerna ERR!     at rimraf (/Users/rfeng/Projects/collabland/collabland-monorepo/node_modules/rimraf/rimraf.js:56:10)
lerna ERR!     at rimrafDir (/Users/rfeng/Projects/collabland/collabland-monorepo/node_modules/@lerna/legacy-package-management/dist/index.js:3575:56)
lerna ERR!     at concurrency (/Users/rfeng/Projects/collabland/collabland-monorepo/node_modules/@lerna/legacy-package-management/dist/index.js:4371:42)
lerna ERR! lerna rimraf: callback function required
npm ERR! code 1
npm ERR! path /Users/rfeng/Projects/collabland/collabland-monorepo
npm ERR! command failed
npm ERR! command sh -c -- lerna bootstrap && npm run -s update-ts-project-refs
```

## Expected Behavior

`lerna bootstrap` should be successful.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```

</p></details>

**Comment by raymondfeng** [comment]
I think the root cause is that `@lerna/legacy-package-management` does not declare `rimraf` as a dependency even though it expects v4.0 which is not compatible with v3.0.x - which was picked up by ``@lerna/legacy-package-management`.

**Comment by endel** [comment]
`rimraf@5.0.0` was released a few days ago and seems to be causing this problem as well
using `rimraf@^4.4.1` as dev-dependency worked for me

**Comment by jtenner** [comment]
This issue plagues me too. Using the correct package version wasn't enough.

```ts
async function rimrafDir(dirPath) {
  import_npmlog32.default.silly("rimrafDir", dirPath);
  if (!(0, import_fs4.existsSync)(dirPath)) {
    return;
  }
  const rimraf = require("node:util").promisify((0, import_rimraf.default));
  try {
    await rimraf(dirPath);
  } catch (ex) {
    throw new Error(`Failed to fully remove ${dirPath}`);
  }

  import_npmlog32.default.verbose("rimrafDir", "removed", dirPath);
}
```

I had to modify the output js so that the rimrafDir function promisified the rimraf function. Please advise and I might help submit a pull request.

**Comment by fahslaj** [comment]
@raymondfeng Unfortunately, I am unable to reproduce the issue with the information provided.

To all experiencing this problem, I would suggest migrating to use npm/yarn/pnpm workspaces over `lerna bootstrap`. Lerna's package management commands are being deprecated in favor of closer integration with the workspace capabilities of package managers.

**Comment by matheo** [comment]
@fahslaj npm workspaces doesn't work for `dist` bundles, it seems that some deprecations are affecting the expected `lerna` behavior too much, instead solving this simple `rimraf` compatibility...

**Comment by JamesHenry** [comment]
@matheo Please could you provide a minimal reproduction of what you are saying does not work with `workspaces` and I will happily take a look.

`publishConfig.directory` is not going anywhere, and we are adding an optional, additional, more powerful/configurable option for controlling the directory contents that will be published in Lerna v7.

For this actual issue, I imagine this is the correct summary: https://github.com/lerna/lerna/issues/3636#issuecomment-1498453494

We can definitely add the missing `rimraf` dependency in there to resolve this issue

**Comment by pichlermarc** [comment]
We're having the same issue using `@lerna/legacy-package-management@6.6.2` over at https://github.com/open-telemetry/opentelemetry-js, but I was unsuccessful in creating a minimal repro until now. 

@JamesHenry is a repro still needed? :thinking:

**Comment by pichlermarc** [comment]
Ah, it looks like this is fixed already by https://github.com/lerna/lerna/commit/ab5ecd33ad19f46829ec871b1a24e9ed8874b8f6. I'm using `@lerna/legacy-package-management@7.0.2` now and that one now and it seems to work. 

Thank you :slightly_smiling_face:
