### ISSUE TITLE
Not resoved * in peerDependencies

### ISSUE THREAD

**Issue by a-zana** [lerna/lerna#3637]
I have a workspace created with nrwl wiht inside 2 angular libraries (a, b). The are some dependecies between them that i describe in every package.json as peerDependencies:

packages/b/pakage.json
``` json
"name": "b",
"version": "1.0.0",
"peerDependencies": {
  "a": "*"
},
"devDependencies": {
  "a": "1.0.0"
}
```

## Current Behavior

Do increase the version i run:

`npx lerna version 2.0.0 --no-git-tag-version --force-publish`

the version 1.0.0 inside the devDependencies is correctly advanded

if I do a build of all the libraries the * is not resolved and the peerDependencies will keep on having * inside

## Expected Behavior

That during the buidl process or before with a specific lerna command is possible to resolve the * with the current version

## Steps to Reproduce

create a workspace with two project inside, add a dependency between them using the * in the peerDependencies

**Comment by fahslaj** [comment]
Hi @a-zana , Lerna intentionally does not substitute or update peer dependencies. See #1018
