### ISSUE TITLE
Slack room invite limit has been reached

### ISSUE THREAD

**Issue by chrislloyd** [lerna/lerna#364]
I tried to join the Lerna Slack room, following the link on lernajs.io, but got this error.

<img width="491" alt="screen shot 2016-10-07 at 12 03 37 pm" src="https://cloud.githubusercontent.com/assets/718/19202239/3536cbdc-8c86-11e6-9279-d9a25a2979a3.png">

(Email address hidden for my privacy)

**Comment by thejameskyle** [comment]
Ugh.... What? There's only 89 people. I'll ask Slack

**Comment by thejameskyle** [comment]
Want to try again?

**Comment by beeman** [comment]
Seems to work now, I just joined successfully 👍
