### ISSUE TITLE
Error in gatsby cloud builds using gatsbyjs and lerna monorepo

### ISSUE THREAD

**Issue by ErwanEL** [lerna/lerna#3648]
![image](https://user-images.githubusercontent.com/31598913/232041427-a6801e27-3a78-41d2-8ea8-a3e6fba21bdd.png)

```
09:08:22 AM:
Using node version from environment variable NODE_VERSION: 14.18.0

09:08:22 AM:
Installing node version 14.18.0

09:08:23 AM:
Downloading and installing node v14.18.0...

09:08:26 AM:
Now using node v14.18.0 (npm v6.14.15)

09:08:29 AM:
LERNA bootstrap failure - Command failed with ENOENT: lerna bootstrap --registry=https://registry.yarnpkg.com
spawn lerna ENOENT

09:08:30 AM:
LERNA bootstrap --registry=https://registry.yarnpkg.com attempt 3 of 3...

09:08:31 AM:
LERNA bootstrap --registry=https://registry.yarnpkg.com failure - Command failed with ENOENT: lerna bootstrap --registry=https://registry.yarnpkg.com
spawn lerna ENOENT

09:08:31 AM:
ERROR Failed to compile: Error: Command failed with ENOENT: lerna bootstrap --registry=https://registry.yarnpkg.com
spawn lerna ENOENT
```

Hi,

We suddenly encountered an error while building a monorepo of Gatsby JS websites on Gatsby Cloud. Everything works fine locally.

Does anyone know where this error could be coming from?

**Comment by fahslaj** [comment]
Hi @ErwanEL , I am sorry that you are experiencing this issue. While I am not sure why it is happening, I do have some suggestions that might help your situation.

First, you may want to consider updating from Node 14 to Node 16+. [Node 14 maintenance support ended April 30th, 2023](https://endoflife.date/nodejs). 

Second, I would suggest migrating to [npm workspaces](https://docs.npmjs.com/cli/v9/using-npm/workspaces?v=true) and setting `useWorkspaces` to `true` in `lerna.json`. After this change, `lerna bootstrap` will no longer be necessary. Lerna is deprecating support for many package management commands, including `bootstrap`, in favor of closer integration with npm/yarn/pnpm workspaces. You can read more about this change in the [v7 roadmap](https://github.com/lerna/lerna/discussions/3410).
