### ISSUE TITLE
lerna.json displays warning on $schema property

### ISSUE THREAD

**Issue by olibooty** [lerna/lerna#3649]
## Current Behavior

In `lerna.json` file the `$schema` property has a highlighted warning. On hover it displays the following error:
```
Unable to load schema from '/Users/user/project/node_modules/lerna/schemas/lerna-schema.json': ENOENT: no such file or directory, open '/Users/user/project/node_modules/lerna/schemas/lerna-schema.json'
```
![Screenshot 2023-04-14 at 16 16 26](https://user-images.githubusercontent.com/27422045/232085871-2f97bed1-a61a-4441-9d6e-fe29b0ae2aec.png)

## Expected Behavior

No warning displayed

## Steps to Reproduce

```
$ mkdir lerna-test && cd lerna-test
$ npx lerna init
$ yarn
```

I have also added `"npmClient":"yarn"` to `lerna.json`

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "useWorkspaces": true,
  "npmClient":"yarn",
  "version": "0.0.0"
}
```

</p></details>

### Environment

```
 Environment info:

  System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
  Utilities:
    Git: 2.39.2 - /usr/bin/git
  npmPackages:
    lerna: ^6.6.1 => 6.6.1

```

**Comment by JamesHenry** [comment]
Hi @olibooty I'm sorry that you are encountering a problem. These steps do not reproduce the problem for me.

I would double check your `node_modules` folder is fully up to date, and check for the file actually being present at the specified path.

I would then look at maybe force reloading your VSCode window to make sure it has had chance to pick up the file.

P.S. It's not related but I would look to update your node and npm versions ASAP, node 14 is imminently EOL and will be completely unsupported by the node team, meaning no security fixes or anything

**Comment by olibooty** [comment]
Thanks James. It would appear to be a case of PEBCAK! A simple reload of the window worked!

**Comment by c4nzin** [comment]
> Hi @olibooty I'm sorry that you are encountering a problem. These steps do not reproduce the problem for me.
> 
> I would double check your `node_modules` folder is fully up to date, and check for the file actually being present at the specified path.
> 
> I would then look at maybe force reloading your VSCode window to make sure it has had chance to pick up the file.
> 
> P.S. It's not related but I would look to update your node and npm versions ASAP, node 14 is imminently EOL and will be completely unsupported by the node team, meaning no security fixes or anything

Thank you james!
