### ISSUE TITLE
Custom npm publish commands (provenance?)

### ISSUE THREAD

**Issue by broksonic21** [lerna/lerna#3657]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/lerna/lerna/blob/main/CONTRIBUTING.md))

## Description

Github announced provenance for publishing: https://github.blog/changelog/2023-04-19-npm-provenance-public-beta/

Is there a way to pass this through lerna publish to npm publish?

## Motivation

Security/Provenance support for publishing, and  the package has verifiable links back to its source code and build instructions.

## Suggested Implementation

Either add this as a direct parameter, or a pattern to pass through commands to npm publish

**Comment by ghiscoding** [comment]
I'm not entirely sure, maybe @JamesHenry  can confirm, but I think this is now supported as per [v6.6.2](https://github.com/lerna/lerna/releases/tag/6.6.2), it also look like it's going to be soon implemented into libnpmpublish as per this [libnpmpublish PR](https://github.com/npm/cli/pull/6375)

**Comment by JamesHenry** [comment]
Provenance is now fully supported when publishing with lerna as of v6.6.2

All of these methods (from https://docs.npmjs.com/generating-provenance-statements#using-third-party-package-publishing-tools) of letting lerna know about provenance are supported, so choose the one that works best for you:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/900523/236306370-fcd7efd0-0536-4b1e-96df-7b067e8747ff.png">

Here is a real example published with lerna:

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/900523/236306177-9dc003f3-058c-4420-89bb-c02ed4cb4649.png">

**NOTE: Provenance is currently only supported by npm for Github Actions**
