### ISSUE TITLE
Chalk colors unreadable

### ISSUE THREAD

**Issue by nhagen** [lerna/lerna#366]
I'm unable to read info input because i use a white terminal

```
  info(message, verbose = false) {
    this._log("info", verbose, chalk.white, message);
  }
```

Is there a recommended way to change the colors, or can we use a color that is a little bit safer for white terminals?

**Comment by gigabo** [comment]
@thejameskyle If you're going to take [my work](https://github.com/asini/asini/pull/33) please preserve authorship.

**Comment by thejameskyle** [comment]
I apologize for not preserving your authorship of 10 changed characters, it has since been updated to reflect your contribution to the project.

**Comment by gigabo** [comment]
And [this one](https://github.com/lerna/lerna/commit/83cac1b1488f0c1edc547c85dafefe337845bf96)?

Also worthwhile to preserve the original [commit messages](https://github.com/lerna/lerna/pull/328/commits/866d17348de4a6e0868d9a21655163e47e86219b).  They're often helpful down the road.
