### ISSUE TITLE
Bug: Yarn Audit Failing due to `cosmiconfig` > `yaml` published advisory

### ISSUE THREAD

**Issue by stegaBOB** [lerna/lerna#3662]
## Current Behavior

Lerna currently depends on v^7.0.0 of `cosmiconfig`, which depends on v1 of `yaml`. yaml recently released an advisory here:  https://github.com/advisories/GHSA-f9xv-q969-pqx4. The patched version is >=2.2.2.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/41593264/234130772-6d992f05-ff6a-4bfc-b209-3650792b3fc7.png">

## Potential Fixes

Bumping `cosmiconfig` to v8 would remove `yaml` as a subdependency, but would require a major version bump to `cosmiconfig`. There isn't currently a minor bump on `cosmiconfig` that resolves this issue. It seems like `cosmiconfig` isn't used too heavily, so it might be a pretty trivial change to lerna to resolve this. I'll dig a bit deeper to see if I can open a PR for this. 

Looking a bit deeper, v8 doesn't have any relevant breaking changes to `cosmiconfig`, so bumping the package.json might be enough.

**Comment by JamesHenry** [comment]
This is resolved as of the freshly released Lerna v7! We now use `cosmiconfig` v8.

https://github.com/lerna/lerna/releases/tag/7.0.0
