### ISSUE TITLE
Why limit the nx version of lerna dependency to>=15.5.2<16

### ISSUE THREAD

**Issue by projectcss** [lerna/lerna#3683]
## Current Behavior
I installed it in the project nx@16.1.1 Because nx@15.x.x There are some issues, but at node_ Two versions of nx were found in the module, which is not expected as it may lead to some abnormal behavior。
The final discovery was that the version dependent on lerna was limited to >=15.5.2<16

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```

</p></details>

**Comment by JamesHenry** [comment]
@projectcss It is very normal for a critical dependency to be limited to a single major version because APIs change across versions.

We will be releasing lerna v7 in the next couple of weeks which leverages Nx 16 behind the scenes so this will be addressed then

**Comment by JamesHenry** [comment]
If there are specific issues you can elaborate on in the meantime then please do

**Comment by JamesHenry** [comment]
This is resolved as of the freshly released Lerna v7!

https://github.com/lerna/lerna/releases/tag/7.0.0
