### ISSUE TITLE
lerna publish fails silently if no GH_TOKEN set

### ISSUE THREAD

**Issue by boneskull** [lerna/lerna#3692]
## Current Behavior

Without a `GH_TOKEN` in the environment, `lerna publish` fails silently.

## Expected Behavior

Lerna should warn the user that the token is not set.

I am unsure if this is a regression, but I imagine it is.  Even if there are other ways to authenticate, Lerna should still report that it cannot actually do anything.

## Steps to Reproduce

Configure Lerna as below.

1. Attempt a `lerna publish` in a repository which contains changesets that should trigger a publish.
2. Lerna will output:

```
lerna notice cli v6.6.2
lerna info versioning independent
```

...and exit with a nonzero code.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "https://json.schemastore.org/lerna",
  "changelogPreset": "conventional-changelog-conventionalcommits",
  "command": {
    "add": {
      "exact": true
    },
    "publish": {
      "message": "chore: publish"
    },
    "run": {
      "concurrency": 8
    },
    "version": {
      "conventionalCommits": true,
      "createRelease": "github",
      "version": {
        "allowBranch": "master"
      }
    }
  },
  "ignoreChanges": ["**/test/**", "**/*.md"],
  "useNx": false,
  "useWorkspaces": true,
  "version": "independent"
}
```
</p></details>

### Environment

```
 Environment info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Utilities:
    Git: 2.25.1 - /usr/bin/git
  npmPackages:
    lerna: 6.6.2 => 6.6.2
```

**Comment by JamesHenry** [comment]
This will be fixed in lerna v7 which should hopefully drop today

**Comment by JamesHenry** [comment]
This is resolved as of the freshly released Lerna v7!

https://github.com/lerna/lerna/releases/tag/7.0.0
