### ISSUE TITLE
inotify_add_watch on .../dist failed: No such file or directory

### ISSUE THREAD

**Issue by charlesritchea** [lerna/lerna#3696]
## Current Behavior

I'm trying `lerna add-caching` with a legacy bootstrap monorepo

After configuring for a task `build-dev` and outputs `dist`

the `build-dev` task fails with an error

` >  Lerna (powered by Nx)   inotify_add_watch on '/home/novaterata/Projects/wireframe-tool/packages/atc-tower-audit-dashboard/dist' failed: No such file or directory`

## Expected Behavior

Since that directory definitely exists I did not expect this error

## Steps to Reproduce

This is a Node 18, Angular 11, Webpack 4 monorepo that is not using workspaces (because webpack can't resolve dependencies when I use workspaces in npm or yarn for some reason)

### Failure Logs / Configuration

` >  Lerna (powered by Nx)   inotify_add_watch on '/home/novaterata/Projects/wireframe-tool/packages/atc-tower-audit-dashboard/dist' failed: No such file or directory`

<summary>lerna.json</summary>

```json
{
  "npmClient": "yarn",
  "packages": [
    "packages/*"
  ],
  "version": "0.0.1"
}
```

<summary>nx.json</summary>

```json
{
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": [
          "build-dev"
        ]
      }
    }
  },
  "targetDefaults": {
    "build-dev": {
      "outputs": [
        "{projectRoot}/dist"
      ]
    }
  }
}
```

### Environment
 Environment info:

  System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Utilities:
    Git: 2.34.1 - /usr/bin/git
  npmPackages:
    lerna: ^6.6.2 => 6.6.2

**Comment by fahslaj** [comment]
Hi @charlesritchea , unfortunately I am unable to reproduce this issue on a workspace matching the environment you described. Can you please provide a link to a minimal reproduction of the issue?

**Comment by charlesritchea** [comment]
@fahslaj our custom webpack setup is so odd let's just close the issue. There's a lot of stuff going on that I'd like to understand before circling back to this, thanks for looking into it though

**Comment by fahslaj** [comment]
Sounds good. Feel free to follow up if you have additional context and/or can make a reliable reproduction.
