### ISSUE TITLE
`lerna version --force-publish` does not update all packages in yarn workspace

### ISSUE THREAD

**Issue by ilhan007** [lerna/lerna#3727]
Hello there,
we have an yarn workspace with multiple packages:

- base
- main
- fiori
....
- tools

Link to the project repo: https://github.com/SAP/ui5-webcomponents/

and we rely on lerna for our project release. It works fine and it's very usefule, however we faced unexpected behaviour that I hope you can help us with. We want to synchronise our  packages' versions and we use the `--force-publish` parameter to do so.

## Current Behavior

Currently, we run
```sh
yarn lerna version 1.14.2 --conventional-graduate --force-publish --yes --exact --create-release github 
        
yarn lerna publish from-git --yes
```

but sometimes not all packages' version are updated - some of them are updated to the new patch/minor, some of them remain on the version before running the commands. In the latest case all the packages but one were updated to 1.14.2 - one of them remained on 1.14.1

## Expected Behavior

When running
```sh
yarn lerna version 1.14.2 --conventional-graduate --force-publish --yes --exact --create-release github 
        
yarn lerna publish from-git --yes
```

we expect all the packages to be bumped to 1.14.2 even without changes.

## Steps to Reproduce

Locally it seems to work properly, so it might be related to the environment. It happens on GitHub actions (provided the environment details below), so I don't have a minimal reproducible example, but I hope that you might have seen this in the past and connect it somehow to the environment that we have.

### Failure Logs / Configuration

Link to the log of the  GitHub action
https://github.com/SAP/ui5-webcomponents/actions/runs/5241010719/jobs/9462553912

I post a screenshot of the log just in case. The screenshot shows the commands being executed and the packages that are updated - just one is missing the `tools`, it is not updated to 1.14.2.

The command executed is
`yarn lerna version 1.14.2 --conventional-graduate --force-publish --yes --exact --create-release github`

<img width="1372" alt="Screenshot 2023-06-13 at 13 19 23" src="https://github.com/lerna/lerna/assets/15702139/8a26da68-a086-4a0c-a6e5-788b35d68204">

Link to the `lerna.json` https://github.com/SAP/ui5-webcomponents/blob/release-1.14.2/lerna.json

### Environment

- Operating System Ubuntu 22.0[4](https://github.com/SAP/ui5-webcomponents/actions/runs/5241010719/jobs/9462553912#step:1:4).2 LTS
 - git version 2.40.1
- yarn 1.22.19
- node 16.20.0
- lerna v6.6.1

**Comment by ilhan007** [comment]
@ghiscoding I understand that, but isn't the purpose of `--force-publish` to force the version bump even without changes in the package - https://lerna.js.org/docs/features/version-and-publish#synchronized-versions

"**Lerna will only version and publish packages that have changed since the previous release**, causing package versions to drift apart over time. **To prevent this, use the --force-publish option with lerna version. This will force Lerna to always version all packages, regardless of if they have changed since the previous release**. Then they will all be published to the registry by lerna publish from-git. As a result, all package versions will stay synchronized to the version in lerna.json."

**Comment by ghiscoding** [comment]
I could be wrong but I don't think so and I still think that `changelog-recommend-bump` is used in any case because you enabled `conventional-changelog` and so you'll get this behavior in any case... again I could be wrong but that's what I remember from looking at the code. I also use force publish and I also have the same behavior that you have once in a while, it's been like this for years

**Comment by ilhan007** [comment]
@ghiscoding thank you for the input, I believe you. If it's like this for years, it's unlikely to be changed I guess.. still let's see if someone @fahslaj @JamesHenry @amorscher can add some insights on the topic.

**Comment by fahslaj** [comment]
Hi @ilhan007 , I can confirm that the `--force-publish` option is ignored if both `--conventional-commits` and `--conventional-graduate` are used. It appears that this is the case in the command that you have linked (conventionalCommits is 'true' in lerna.json and --conventional-graduate was passed in the command). It is likely that this is the culprit.

I recognize that this is far from ideal when used in a publishing workflow that keeps all package versions in sync. This issue clearly demonstrates a gap in Lerna's ability to support this workflow. I'm going to convert this issue to a feature request so that a solution can be appropriately prioritized.

**Comment by ilhan007** [comment]
Hi @fahslaj  Sounds great! Thank you for looking into the issue.

**Comment by amorscher** [comment]
@fahslaj I could try to implement this if it is ok for the team. or are you already working on it?

**Comment by fahslaj** [comment]
@amorscher that would be fantastic. Could you please implement it in a way that is non-breaking and opt-in, such as via a new option or parameter?

**Comment by amorscher** [comment]
@fahslaj I think this could be closed.

**Comment by fahslaj** [comment]
This feature is available as of Lerna 7.4.1

**Comment by ilhan007** [comment]
I suppose we now have to replace   `--force-publish` and  `--conventional-graduate`  with `--force-conventional-graduate` right?

**Comment by ilhan007** [comment]
Got it:
"When run with this flag, `lerna version` will graduate all packages specified by `--conventional-graduate`. Non-prerelease packages will not be ignored as it would be the case without the flag. In combination with single version mode this can be used to force all specified packages to be updated to a single version despite having no change or being a non-prerelease version. It works similar to `--force-publish` but is not ignored when `--conventional-commits` and `--conventional-graduate` are enabled. This flag is only applicable when having `--conventional-graduate` set, otherwise the option is ignored."
