### ISSUE TITLE
Get wrong package.json after update t v7

### ISSUE THREAD

**Issue by rbirkgit** [lerna/lerna#3731]
## Current Behavior

I updated from 6.6.2 to 7.0.1 and my published package has wrong package.json

## Expected Behavior

I expect my new package to contain correct package.json (the one in the dist folder)

## Steps to Reproduce

I run `lerna publish --contents dist`

With 6.6.2 it published the dist folder "as-is"
With 7.0.1 is gets a copy of the root package.json overriding the one in the dist folder. This causing wrong file with wrong entries.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent",
  "conventionalCommits": true,
  "changelogPreset": "@xxx/gerrit",
  "registry": "https://xxx.com/artifactory/api/npm/npm/",
  "rejectCycles": true,
  "command": {
    "publish": {
      "registry": "https://xxxcom/artifactory/api/npm/npm/",
      "message": "chore(release): release new version\n\n"
    }
  }
}
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

</p></details>

### Environment

```
  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.6.3 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.40.0.
  npmPackages:
    lerna: ^7.0.1 => 7.0.1
```

**Comment by JamesHenry** [comment]
Sorry about this @rbirkgit, this has been fixed in `main` and I will release `7.0.2` later today

**Comment by JamesHenry** [comment]
`7.0.2` has now been released and you should no longer experience the issue

**Comment by rbirkgit** [comment]
Thanks!!
