### ISSUE TITLE
lerna exec doesn't work with npm prune command

### ISSUE THREAD

**Issue by guygadebois** [lerna/lerna#374]
Hi,
I need to prune the devDependencies of a whole lerna project (both root and children folders).
I've tried `lerna exec npm prune --production`
But for some reason, it won't do the job (my devDependencies are still present in the children folders), whereas going manually into each children folder an invoking `npm prune --production` does the job.
What confuses me is that, in the other hand, a simple command `lerna exec pwd` works fine: it indeed outputs the path of all children folders.

**Comment by guygadebois** [comment]
Forgot to add the specs:
- lerna version: 2.0.0-beta.29
- npm version: 2.15.9
- NodeJS version: 4.6.0

**Comment by guygadebois** [comment]
It seems to me that it's the optional arguments that are dropped.
Just tried `lerna exec ls -al` and it actually performs an `ls`, not an `ls -al`
Also tried to quote the command: `lerna exec 'ls -al'`, but then nothing is performed at all.

**Comment by seansfkelley** [comment]
CLI flag parsing is done with `meow`, which delegates to `minimist`, which understands `--` to mean "rest", so it works (though is undocumented) if you try

```
lerna exec -- ls -la
```

I just tried this on beta.29 and it works as expected. It should probably be mentioned in the docs, though.

**Comment by guygadebois** [comment]
Great, that syntax is working fine!
Do you want to keep that issue open to track the documentation update?
Otherwise this is good for me, and it can be closed.
Thanks!

**Comment by seansfkelley** [comment]
[Actually it is documented](https://github.com/lerna/lerna#exec), I just was too sleepy when I wrote this response to notice. So you can close it.

**Comment by guygadebois** [comment]
Great! closing this
