### ISSUE TITLE
Migrating from Lerna Bootstrap to Yarn or NPM Workspaces full of blockers

### ISSUE THREAD

**Issue by charlesritchea** [lerna/lerna#3755]
https://lerna.js.org/docs/legacy-package-management says to open an issue here if I have problems converting a Lerna Bootstrap monorepo to Yarn workspaces, and boy do I. I have so many issues I don't even know where to begin.

tsconfig relative paths change from being relative to the package to being root relative

because of this tsconfig "paths" don't work unless I have a separate alias for every single package

I had to change babel useBuiltIns from usage to entry and I don't know why or what the fallout of this will be

Ultimately after I get through the above issues, package imports aren't resolved, no idea why

Also, had to make lots of movements from dependencies to peerDependencies and root dependencies.

Complete nightmare and I always find some new blocker that nobody else in Google has found

**Comment by charlesritchea** [comment]
@JamesHenry thanks for the offer, truly, I've got to move from Webpack4 to 5 as well, and I'm hoping that process will resolve or ellucidate the issues with moving to workspaces. If I can't make any progress, I will come up with a reproducible package I can send you. It's not open-source, so you know how that goes. I'll close the issue for now, as I consider your response enough :)

**Comment by JamesHenry** [comment]
Ok sure thing, feel free to get back in touch if you can recreate any issues
