### ISSUE TITLE
Lerna repair and lerna build exceed maximum call stack

### ISSUE THREAD

**Issue by XavierGoncalves** [lerna/lerna#3763]
## Current Behavior

Running either `npx lerna run build` or `npx lerna repair` causes the script to hang and after a while display the message on the print-screen bellow.

## Expected Behavior

I expected the scripts to run sucessfully.

## Steps to Reproduce

This is a private repository, thus I cannot share it.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

<img width="634" alt="Screenshot 2023-07-05 at 13 00 50" src="https://github.com/lerna/lerna/assets/75749681/0ec523b6-bc3e-43ca-a226-7a76fa019a2e">

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "version": "independent"
}
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv {
0 silly argv   _: [ 'repair' ],
0 silly argv   lernaVersion: '7.1.1',
0 silly argv   '$0': '<REPO_PATH>/node_modules/.bin/lerna'
0 silly argv }
1 notice cli v7.1.1
2 verbose packageConfigs Resolving packages based on package.json "workspaces" configuration.
3 verbose rootPath <REPO_PATH>
4 error RangeError: Maximum call stack size exceeded
4 error     at buildAllWorkspaceFiles (<REPO_PATH>/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:68:14)
4 error     at <REPO_PATH>/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:43:32
4 error     at Generator.next (<anonymous>)
```

</p></details>

**Comment by JamesHenry** [comment]
@XavierGoncalves what does your workspaces config look like please?

**Comment by XavierGoncalves** [comment]
> @XavierGoncalves what does your workspaces config look like please?

It's vanilla
```
"workspaces": [
    "packages/*"
  ],
```

**Comment by JamesHenry** [comment]
Please could you share the result of:

```sh
npm ls nx
```

And try running `npx nx reset` and see if the problem persists?

**Comment by XavierGoncalves** [comment]
Sure, here it is
```
└─┬ lerna@7.1.1
  ├─┬ @nx/devkit@16.5.0
  │ └── nx@16.5.0 deduped
  └─┬ nx@16.5.0
    └─┬ @nrwl/tao@16.5.0
      └── nx@16.5.0 deduped
```

**Comment by JamesHenry** [comment]
Additionally, out of curiosity could you please try one of the commands with `NX_DAEMON=false`, e.g. `NX_DAEMON=false npx lerna repair`

**Comment by XavierGoncalves** [comment]
> npx nx reset

It did not, after experimenting with a colleague's PC, it seems that there's an issue with `nvm` on my machine, as the commands run perfectly on my colleague's PC

**Comment by Cammisuli** [comment]
Hi @XavierGoncalves, I'd like to see how many files are actually in your workspace that causes the Maximum call stack error. 

It might be a little involved because I'm going to ask you to modify your local node_modules files, and put some code in. 

If you're up for it, can you follow these steps:
1. open `./node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:66` (you should be able to copy and paste this path in vscode, and it should open to the correct line, and if not, go to the `buildAllWorkspaceFiles` function)
2. Add this code to the beginning of the `buildAllWorkspaceFiles` function:
```
    let projects = Object.keys(projectFileMap);
    let total = projects.keys(projectFileMap).reduce((acc, curr) => acc + projectFileMap[curr].length, 0);
    console.log('projects', projects.length);
    console.log('projectFileMap', total);
    console.log('globalFiles', globalFiles.length);

```
3. run `npx nx daemon --start` and then run your lerna command.
4. Open the `./node_modules/.cache/nx/d/daemon.log` file and find the numbers that should have been printed out. 

I want to try and create a workspace that has the same total amount of files you have so we can get to the bottom of this. Thank you!

**Comment by XavierGoncalves** [comment]
> Hi @XavierGoncalves, I'd like to see how many files are actually in your workspace that causes the Maximum call stack error.
> 
> It might be a little involved because I'm going to ask you to modify your local node_modules files, and put some code in.
> 
> If you're up for it, can you follow these steps:
> 
> 1. open `./node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:66` (you should be able to copy and paste this path in vscode, and it should open to the correct line, and if not, go to the `buildAllWorkspaceFiles` function)
> 2. Add this code to the beginning of the `buildAllWorkspaceFiles` function:
> 
> ```
>     let projects = Object.keys(projectFileMap);
>     let total = projects.reduce((acc, curr) => acc + projectFileMap[curr].length, 0);
>     console.log('projects', projects.length);
>     console.log('projectFileMap', total);
>     console.log('globalFiles', globalFiles.length);
> ```
> 
> 3. run `npx nx daemon --start` and then run your lerna command.
> 4. Open the `./node_modules/.cache/nx/d/daemon.log` file and find the numbers that should have been printed out. ie.
> 
> ```
> projects 110
> projectFileMap 5686
> globalFiles 0
> ```
> 
> I want to try and create a workspace that has the same total amount of files you have so we can get to the bottom of this. Thank you!

After uninstalling `nvm`, running lerna commands works as intended.
The issue did not stem from the amount of files in the repo because it is a demo monorepo, it has just what `vite`'s cli outputs, but from `nvm` not properly setting the `node` version, I think that internally it was using a lower version of node.
Thank you for the help @JamesHenry and @Cammisuli

**Comment by JamesHenry** [comment]
Great!
