### ISSUE TITLE
Lerna exception when using Prettier 3.0.0

### ISSUE THREAD

**Issue by rbirkgit** [lerna/lerna#3765]
## Current Behavior

I get an exception when using Prettier 3.0.0 together with lerna 7.1.1

I run `lerna publish` and get this exception:

```
[2023-07-06T01:42:02.912Z] lerna ERR! TypeError: resolvedPrettier.resolveConfig.sync is not a function
[2023-07-06T01:42:02.912Z] lerna ERR!     at maybeFormatFile (/jenkins/workspace/provisioning-tango-ui-sdk-publish/node_modules/lerna/dist/index.js:7464:49)
[2023-07-06T01:42:02.912Z] lerna ERR!     at gitAdd (/jenkins/workspace/provisioning-tango-ui-sdk-publish/node_modules/lerna/dist/index.js:7487:5)
[2023-07-06T01:42:02.912Z] lerna ERR!     at VersionCommand.updatePackageVersions (/jenkins/workspace/provisioning-tango-ui-sdk-publish/node_modules/lerna/dist/index.js:8318:17)
[2023-07-06T01:42:02.912Z] lerna ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-07-06T01:42:02.912Z] lerna ERR!     at async Promise.all (index 0)
```

## Expected Behavior

Expect publish to still work. I downgraded to Prettier 2.8.8 and all worked again.

## Steps to Reproduce

Upgrade to Prettier 3.0.0 and run `lerna publish`

### Failure Logs / Configuration

See above for error.

### Environment

```
  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.6.3 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.41.0.
  npmPackages:
    lerna: ^7.1.1 => 7.1.1
```

**Comment by nstuyvesant** [comment]
Also getting this issue. My log...
```
branch 'master' set up to track 'origin/master'.
Creating version, changelogs and publishing to Github...
lerna notice cli v7.1.1
lerna info ci enabled
lerna info current version 1.11.4
lerna WARN force-publish all packages
lerna info Assuming all packages changed
lerna info getChangelogConfig Successfully resolved preset "conventional-changelog-angular"

Changes:
 - @carbon/charts-angular: 1.11.4 => 1.11.5
 - @carbon/charts: 1.11.4 => 1.11.5
 - @carbon/charts-react: 1.11.4 => 1.11.5
 - @carbon/charts-svelte: 1.11.4 => 1.11.5
 - @carbon/charts-vue: 1.11.4 => 1.11.5

lerna info auto-confirmed 
lerna info execute Creating releases...
lerna ERR! TypeError: resolvedPrettier.resolveConfig.sync is not a function
lerna ERR!     at maybeFormatFile (/home/runner/work/carbon-charts/carbon-charts/node_modules/lerna/dist/index.js:7464:49)
lerna ERR!     at gitAdd (/home/runner/work/carbon-charts/carbon-charts/node_modules/lerna/dist/index.js:7487:5)
lerna ERR!     at VersionCommand.updatePackageVersions (/home/runner/work/carbon-charts/carbon-charts/node_modules/lerna/dist/index.js:8318:17)
lerna ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna ERR!     at async Promise.all (index 0)
lerna ERR! lerna resolvedPrettier.resolveConfig.sync is not a function
Error: Process completed with exit code 1.
```

**Comment by fahslaj** [comment]
I'm currently working a fix for this - #3766

I'll follow up once it is integrated into Lerna and a release has been cut that includes it. Thanks!

**Comment by nstuyvesant** [comment]
Thank you!

**Comment by mts** [comment]
Same [issue] (https://github.com/papillonbits/papillonbits/commit/dd02015602f4ae5297a9e33dde9f7fa21c0272bc#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R158) here.

```bash
lerna publish

? Are you sure you want to publish these packages? Yes
lerna info execute Skipping releases
lerna ERR! TypeError: resolvedPrettier.resolveConfig.sync is not a function
lerna ERR!     at maybeFormatFile (node_modules/lerna/dist/index.js:7464:49)
lerna ERR!     at gitAdd (node_modules/lerna/dist/index.js:7487:5)
lerna ERR!     at VersionCommand.updatePackageVersions (node_modules/lerna/dist/index.js:8318:17)
lerna ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna ERR!     at async Promise.all (index 0)
lerna ERR! TypeError: resolvedPrettier.resolveConfig.sync is not a function
lerna ERR!     at maybeFormatFile (node_modules/lerna/dist/index.js:7464:49)
lerna ERR!     at gitAdd (node_modules/lerna/dist/index.js:7487:5)
lerna ERR!     at VersionCommand.updatePackageVersions (node_modules/lerna/dist/index.js:8318:17)
lerna ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna ERR!     at async Promise.all (index 0)
lerna ERR! lerna resolvedPrettier.resolveConfig.sync is not a function
```

**Comment by TrejGun** [comment]
@fahslaj please backport your fix to lerna 6, npm can't handle my monorepo properly yet so I have to use old version

**Comment by pierceray** [comment]
Is there any way that a patch version can be published with this fix?

**Comment by JamesHenry** [comment]
This is fixed in lerna 7.1.3

**Comment by fahslaj** [comment]
@TrejGun We are not planning on backporting this to Lerna 6. If you have specific problems with Lerna 7, feel free to open a separate issue.

**Comment by mts** [comment]
v7.1.3 [resolves](https://github.com/papillonbits/papillonbits/blob/master/package.json#L150) this issue. Very much appreciated. Thanks a lot.

**Comment by TrejGun** [comment]
> @TrejGun We are not planning on backporting this to Lerna 6. If you have specific problems with Lerna 7, feel free to open a separate issue describing those problems.

This is so sad :(
My issue with npm is that npm does not calculate the dependency graph of my packages and does not build typescript packages in order, so we have to stick to lerna 6. If I'm wrong and you have a good example of how to implement this case please share a repo

**Comment by JamesHenry** [comment]
@TrejGun you can still use the `@lerna/legacy-package-management` features in v7, so you are not hard blocked from updating to v7:

https://lerna.js.org/docs/legacy-package-management#temporarily-polyfilling-legacy-package-management-commands

---

Specifically about wha you are saying here, Lerna builds a dependency graph of your packages as part of `lerna run` in order to know what order to run things in, npm is not involved in that, so I think you are referring to something else other than bootstrapping.

The way you can tell lerna about dependencies between your tasks such as build is covered here: https://lerna.js.org/docs/concepts/task-pipeline-configuration

**Comment by TrejGun** [comment]
Yeah, this is a little bit complicated

currently, I have mono-repo that only installs lerna in the root, then the `bootstrap` command installs and links dependencies of packages

with pure npm `install` command installs dependencies of packages while installing dependencies of the root. the problem here is that one package could be a dependency on another one and has been built in advance. and npm does not calculate this graph. so it is a kind of combination of `install` and `build`

anyways thanks for suggestion to use @lerna/legacy-package-management, I will take a look shortly
