### ISSUE TITLE
Lerna Deletes the Scripts in the Package.JSON

### ISSUE THREAD

**Issue by nickwelp** [lerna/lerna#3768]
## Current Behavior
`lerna boostrap --scope=@mystuff/small-project-in-mono-repo `
results in the Scripts content of the package.json being erased.

## Expected Behavior
I expect the package.json to not be so brutally ripped apart, and for the content I put in there to still be there.

## Steps to Reproduce
This is spotty behavior and I'm unsure how to reproduce it. Lerna doesn't do this every time. 

### Environment

Building Locally, after rm -rf the sub project's node_modules.

**Comment by JamesHenry** [comment]
Hi @nickwelp, we would strongly recommend you migrate away from using `lerna bootstrap` and instead use your package manager for installing and linking dependencies.

We have a dedicated guide for this in lerna v7 here:
https://lerna.js.org/docs/legacy-package-management

As per the notes there, we will not be looking to amend the behaviour of `lerna bootstrap` or other legacy package management commands, as those things should be handled by your package manager.

**Comment by nickwelp** [comment]
thank you for the follow up
