### ISSUE TITLE
Shrinkwrap support

### ISSUE THREAD

**Issue by christianacca** [lerna/lerna#377]
I shrinkwrap libraries. The problem is that lerna does not seem to support shrinkwrapped packages.

**Is shrinkwrap support on the roadmap to be added?**

Note: For best practice reasons, I shrinkwrap at _development time_ only ie the published package on npm does NOT include the `npm-shrinkwrap.json` file.
## Observations

When trying to use lerna with shrinkwrapped projects I've observed the following:
- `bootstrap` command ignores the `npm-shrinkwrap.json` when installing versions of external dependencies
- `publish` command does not update the `npm-shrinkwrap.json` file(s)

**Comment by thejameskyle** [comment]
We're going to switch to Yarn eventually, and we'll use `yarn.lock`'s as part of that.

**Comment by christianacca** [comment]
OK thanks for the heads up

**Comment by chrisui** [comment]
Are there any plans to revisit this with the recent npm progressions (ie. v5 with package-lock.json).

I'm currently looking for the canonical answer to how "how do I lock my dependencies with a lerna managed monorepo?"

Also regarding _"We're going to switch to Yarn eventually"_ what does the roadmap currently look like for lerna with yarn? Am I still going to be able to use lerna with npm in a few months?

**Comment by aaronmcadam** [comment]
@chrisui The original idea was that Yarn might take on Lerna's functionality, but I think that idea died when issues like caching differences were raised. I've always had problems using Yarn with Lerna, so yeah, it would be good to see where it fits into the roadmap.

**Comment by evocateur** [comment]
A roadmap is forthcoming

**Comment by chrisui** [comment]
Awesome @evocateur, if I can be of any use let me know. We really want to use lerna but require a first-class dependency locking story so happy to invest!
