### ISSUE TITLE
The "useWorkspaces" option has been removed.

### ISSUE THREAD

**Issue by ivetrivel** [lerna/lerna#3770]
I tried to setup lerna with a repo unfortunately I'm getting in to this error. Though the lerna.json is put as expected, still it throws incorrect error.

## Current Behavior

`lerna exec yarn link` command is throwing error `The "useWorkspaces" option has been removed. By default lerna will resolve your packages using your package manager's workspaces configuration. Alternatively, you can manually provide a list of package globs to be used instead via the "packages" option in lerna.json.`

## Expected Behavior

`lerna exec yyarn link` to work without isues

![image](https://github.com/lerna/lerna/assets/130036106/72b4fa43-ad27-433a-9bb3-6ea712c42021)

**Comment by JamesHenry** [comment]
Hi @ivetrivel, the `workspaces` are a package manager level thing, so they do not belong in your `lerna.json`. Given you are using yarn, they belong in your `package.json`.

(You can alternatively use a `packages` array of globs in your `lerna.json`).

In either case you need to remove the `useWorkspaces` option as per the error message.

You can check out an example of an npm workspaces configuration covered in the migration video here: https://lerna.js.org/docs/legacy-package-management

This is nearly identical to the case with yarn workspaces.

Hope that helps!
