### ISSUE TITLE
lerna init fails with no matching version found for @nrwl/devkit

### ISSUE THREAD

**Issue by cjr8020** [lerna/lerna#3774]
## Current Behavior

```
# Create an empty directory
mkdir ./new-lerna-workspace
# Change into the new directory
cd ./new-lerna-workspace
# Initialize lerna (using --dryRun to preview the changes)
npx lerna init --dryRun
Need to install the following packages:
  lerna@7.1.3
Ok to proceed? (y) y
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/devkit@16.5.2.
```

## Expected Behavior

Brand-new workspace initialized according to the [Starting from scratch](https://lerna.js.org/docs/getting-started#starting-from-scratch) section of the doc.

## Steps to Reproduce

Please see Current Behavior above

### Environment

ProductName:	macOS
ProductVersion:	13.4.1
BuildVersion:		22F82

node -v
v18.16.1

**Comment by JamesHenry** [comment]
Hi @cjr8020 I cannot reproduce this, it's possible you have a stale npm/npx cache.

Please try clearing the caches like so and trying again:

```sh
npm cache clear --force
rm -rf ~/.npm/_npx/
```

**Comment by cjr8020** [comment]
@JamesHenry 
deleting npx cache indeed fixed the issue:

```
npm cache clear --force
rm -rf ~/.npm/_npx/
``` 

Thank you!
