### ISSUE TITLE
[Feature] package is missing an "engines" section

### ISSUE THREAD

**Issue by Pomax** [lerna/lerna#378]
https://github.com/lerna/lerna/blob/master/package.json currently does not declare which version of node, and thus npm, it requires, which can cause problems when people use it with node4 (current LTS) vs. node 6 (current stable), as these use npm2 and npm3 respectively, which organize packages in _completely_ different ways. NPM2 organizes dependencies on an "each dep. has its own node_modules dir" basis, whereas npm3 creates a single flat "node_modules" dir in the root dir and puts _every_ dependency in that dir, regardless of how deep it was declared.

Adding an [engines](https://docs.npmjs.com/files/package.json#engines) section to the package.json will ensure that people don't try to use Lerna with a version of npm that is going to create problems due to files ending up in completely different location (particularly important when dealing with loading config files file module directories)

**Comment by wldcordeiro** [comment]
@Pomax reading through their CI stuff they support 0.10, 0.12, 4, 5, and 6 but it may still be nice to add this section.

**Comment by Pomax** [comment]
Quite, especially since 0.x through 4.x use a wildly different approach from 6.x to where, and how, modules are located.

**Comment by noherczeg** [comment]
@evocateur Is this still relevant? If yes a check should go to `Command.runValidations()` right?

**Comment by evocateur** [comment]
The `engines` field is only a warning, as npm3 removed the `engineStrict` flag. We've already got `node >= 4` in the `engines` field, that's good enough.
