### ISSUE TITLE
lerna success found 0 packages

### ISSUE THREAD

**Issue by AlexAtkinson** [lerna/lerna#3782]
## Current Behavior

`lerna list` can't find packages, reporting: `lerna success found 0 packages`...

## Expected Behavior

Lerna finds the packages.

## Steps to Reproduce

```
$ mkdir lerna-test && cd lerna-test
$ lerna init # if installed or `npx lerna init`
$ lerna create foo -y
$ lerna ls --all
lerna notice cli v7.1.3
lerna success found 0 packages
```

> NOTE: The `git@github.com:lerna/repro.git` repo is out of date.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "version": "0.0.0"
}
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv { _: [ 'create' ], lernaVersion: '7.1.3', '$0': 'lerna', name: 'foo' }
1 notice cli v7.1.3
2 verbose packageConfigs Resolving packages based on package.json "workspaces" configuration.
3 verbose rootPath /home/user/ugh2
4 error Error: canceled
4 error     at Interface.<anonymous> (/home/alex/.nvm/versions/node/v20.4.0/lib/node_modules/lerna/node_modules/read/lib/read.js:79:15)
4 error     at Interface.emit (node:events:512:28)
4 error     at [_ttyWrite] [as _ttyWrite] (node:internal/readline/interface:1124:18)
4 error     at ReadStream.onkeypress (node:internal/readline/interface:263:20)
4 error     at ReadStream.emit (node:events:512:28)
4 error     at emitKeys (node:internal/readline/utils:357:14)
4 error     at emitKeys.next (<anonymous>)
4 error     at ReadStream.onData (node:internal/readline/emitKeypressEvents:64:36)
4 error     at ReadStream.emit (node:events:512:28)
```

</p></details>

<details><summary>npx lerna info</summary><p>

```txt
### Environment

lerna notice cli v7.1.3

 Environment info:

  System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  Binaries:
    Node: 20.4.0 - ~/.nvm/versions/node/v20.4.0/bin/node
    npm: 9.7.2 - ~/.nvm/versions/node/v20.4.0/bin/npm
  Utilities:
    Git: 2.34.1 - /usr/bin/git
```

</p></details>

**Comment by juanvargas-pax** [comment]
same issue here, CI it's complaining about the packages 404
https://registry.yarnpkg.com/@lerna/pulse-till-done/-/pulse-till-done-6.4.1.tgz

**Comment by juanvargas-pax** [comment]
it's already solved.
this is an internal package
https://registry.yarnpkg.com/@lerna/pulse-till-done/-/pulse-till-done-6.4.1.tgz

**Comment by JamesHenry** [comment]
I wonder if you were hitting the npm issues yesterday, this isn't reproducible with lerna as of now. If you can reproduce again please let me know

**Comment by AlexAtkinson** [comment]
Today everything works.

I started the day by trying out `6.0.1`, and it worked great.
After seeing your comment here, testing `7.1.4` worked great.
Running with `npx lerna@7.1.3` succeeds also.

Thanks, folks.
