### ISSUE TITLE
Error during `yarn add lerna` and `yarn install` for existing repo with lerna - @lerna/run-parallel-batches - 404 Not Found

### ISSUE THREAD

**Issue by ttomaszewski** [lerna/lerna#3784]
## Current Behavior

Downloading @lerna/run-parallel-batches via Yarn returns a 404
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@lerna/run-parallel-batches/-/run-parallel-batches-3.0.0.tgz: Request failed \"404 Not Found\"".
```

I tried to just install a new version of `lerna` but get the following error, so upgrading doesnt seem to even work
```
➜  project git:(master) ✗ yarn add lerna
yarn add v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error Couldn't find package "@nx/devkit@>=16.1.3 < 17" required by "lerna" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
## Expected Behavior

Downloading @lerna/run-parallel-batches from yarn is successful. This was working earlier today (7/14/2023)

## Steps to Reproduce
- `yarn add lerna`
- `yarn install` with `"lerna": "^3.4.3"` in old project package.json

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```

</p></details>

### Environment

yarn

**Comment by rudemex** [comment]
hi @ttomaszewski I think it's already solved... try reinstalling, in my case it worked... it might have been a problem with npm/yarn registry

**Comment by JamesHenry** [comment]
Yes npm was having issues and it seems this was likely to blame here
