### ISSUE TITLE
[Feature] npm preinstall script

### ISSUE THREAD

**Issue by jasonLaster** [lerna/lerna#379]
We have preinstall script that installs lerna if it is not installed already and then calls lerna bootstrap. This works in npm 2, but fails in npm 3. 

In npm 3, tree resolution is called before preinstall, so any packages that are not published will cause an error. 

Do others have a solution for this?

**Comment by wldcordeiro** [comment]
In researching this issue I got lead to this npm issue - https://github.com/npm/npm/issues/10379 which may be of relevance to others here.

**Comment by danielo515** [comment]
Why don't you use lerna bootstrap as a post install script? Works for me

**Comment by doug-wade** [comment]
This is fixed in npm 5; closing
