### ISSUE TITLE
lerna ls started failing randomly

### ISSUE THREAD

**Issue by cipriancaba** [lerna/lerna#3792]
## Current Behavior

lerna ERR! TypeError [ERR_INVALID_ARG_TYPE]: Failed to process the project graph with "nx-js-graph-plugin".
lerna ERR! The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
lerna ERR!     at writeFileSync (node:fs:2211:5)
lerna ERR!     at writeLastProcessedLockfileHash (/Users/cipri/dev/7879/src/7879/node_modules/nx/src/plugins/js/index.js:49:28)
lerna ERR!     at /Users/cipri/dev/7879/src/7879/node_modules/nx/src/plugins/js/index.js:25:17
lerna ERR!     at Generator.next (<anonymous>)
lerna ERR!     at /Users/cipri/dev/7879/src/7879/node_modules/tslib/tslib.js:118:75
lerna ERR!     at new Promise (<anonymous>)
lerna ERR!     at Object.__awaiter (/Users/cipri/dev/7879/src/7879/node_modules/tslib/tslib.js:114:16)
lerna ERR!     at Object.processProjectGraph (/Users/cipri/dev/7879/src/7879/node_modules/nx/src/plugins/js/index.js:15:57)
lerna ERR!     at /Users/cipri/dev/7879/src/7879/node_modules/nx/src/project-graph/build-project-graph.js:121:38
lerna ERR! lerna Failed to process the project graph with "nx-js-graph-plugin".
lerna ERR! lerna The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

## Expected Behavior

This started failing in github actions randomly

## Steps to Reproduce

It doesn't always happen

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

lerna notice cli v7.1.4
lerna ERR! TypeError [ERR_INVALID_ARG_TYPE]: Failed to process the project graph with "nx-js-graph-plugin".
lerna ERR! The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
lerna ERR!     at writeFileSync (node:fs:2314:5)
lerna ERR!     at writeLastProcessedLockfileHash (/usr/local/lib/node_modules/lerna/node_modules/nx/src/plugins/js/index.js:49:[28](https://github.com/7879-investment/7879/actions/runs/5659152849/job/15332154542#step:4:29))
lerna ERR!     at /usr/local/lib/node_modules/lerna/node_modules/nx/src/plugins/js/index.js:25:17
lerna ERR!     at Generator.next (<anonymous>)
lerna ERR!     at /usr/local/lib/node_modules/lerna/node_modules/tslib/tslib.js:169:75
lerna ERR!     at new Promise (<anonymous>)
lerna ERR!     at Object.__awaiter (/usr/local/lib/node_modules/lerna/node_modules/tslib/tslib.js:165:16)
lerna ERR!     at Object.processProjectGraph (/usr/local/lib/node_modules/lerna/node_modules/nx/src/plugins/js/index.js:15:57)
lerna ERR!     at /usr/local/lib/node_modules/lerna/node_modules/nx/src/project-graph/build-project-graph.js:121:38
lerna ERR! lerna Failed to process the project graph with "nx-js-graph-plugin".
lerna ERR! lerna The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

<details><summary>lerna.json</summary><p>

{
  "packages": [
    "packages/*",
    "apps/*",
    "services/*",
    "lambdas/*",
    "microservices/*"
  ],
  "version": "0.0.0"
}

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```

</p></details>

**Comment by fahslaj** [comment]
Hi @cipriancaba , can you please provide which version of Nx is installed via `npx nx --version`? Also, are you running `npm install` before `lerna ls` in your github action?

**Comment by cipriancaba** [comment]
Hey @fahslaj really sorry for the lack of info, we are using lerna in a rather peculiar way, just to see changed packages

`"changedSince": "lerna ls -a --since $1",`

This is the package.json script we use to check diff between head and a tagged commit. We don't use nx to manage to monorepo

Lerna version is 7.1.4 and we indeed do yarn install before. 

I really don't know why these actions randomly fail and cannot pinpoint exactly what happened yesterday that triggered this flaky errors

![Screenshot 2023-07-26 at 07 07 34](https://github.com/lerna/lerna/assets/695515/e0854c89-f248-4ca7-bd41-750e92025a68)
![Screenshot 2023-07-26 at 07 08 36](https://github.com/lerna/lerna/assets/695515/9dd11e59-0f4b-428c-84d6-3a7733d1d58f)

**Comment by fahslaj** [comment]
Got it, thanks for the info. I haven't been able to repro it on my side yet but I've got a few ideas. What version of yarn are you using? And are you using plug'n'play? Also, do you cache node_modules in CI between runs or reinstall fresh every time?

**Comment by cipriancaba** [comment]
Caching node_modules with setup_actions@3
Yarn 1.22.19 no pnp
`runs-on: ubuntu-latest`
I was under the impression that lerna is resolved from my package.json devDeps but apparently I am running the changed command before doing `yarn install` and therefore lerna is the version installed on ga (which is in this case the latest 7.1.4)
However, I have since pinned it via npx and the problem went away. Here is my change from package.json:
`"changedSince": "npx lerna@5.6.2 ls -a --since $1",`

**Comment by fahslaj** [comment]
Closing this issue as a workaround has been found. However, I will note that Lerna v6 and later require dependencies to be installed locally before invoking commands. This is likely why pinning to 5.6.2 avoids the issue.
