### ISSUE TITLE
different package discover logic in CI and local

### ISSUE THREAD

**Issue by Dante-dan** [lerna/lerna#3794]
## Current Behavior
I set `packages` in `lerna.json`, to aviod build `apps` directory, because they are application which has a lot of config :

```json
// lerna.json
{
  "packages": [
    "packages/*",
    "!apps/*"
  ],
}
```

I set `packages` in `pnpm-workspace.yaml` to make all application or packages have the same dependencies: 

```yaml
# pnpm-workspace.yaml
packages:
  - "apps/*"
  - "packages/*"
  - '!**/test/**'
```

when I do lerna run build, in local, it means my override packages config is efficient in local:
```bash

> lerna run build

lerna notice cli v7.1.4
lerna info versioning independent

> my-package:build  [existing outputs match the cache, left as is]


```

but, when I run `lerna run build` in CI,my override packages config is useless in gitlab CICD: 

```bash

lerna notice cli v7.1.4
lerna info versioning independent
lerna info ci enabled
 >  Lerna (powered by Nx)   Running target build for 47 projects:
    - my-app-1
    - my-app-2

```

## Expected Behavior

lerna should have the same behavior in CI and local enviroment, the `lerna.json` `packages` should overwrite the `packages` from  `workspace`

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "npmClient": "pnpm",
  "version": "independent",
  "packages": [
    "packages/*",
    "!apps/*",
  ],
  "command": {
    "version": {
      "message": "Gitbot: Update package versions [skip ci]",
      "conventionalCommits": true,
      "allowBranch": "master"
    },
  },
  "changelogPreset": "angular",
  "ignoreChanges": [
    "**/*.md",
    "**/*.yml",
    "**.(cy|test|spec|unit).(js|jsx|ts|tsx|vue)",
    "**/example/**",
    "**/__tests__/**",
    "**/tests/**",
    "**/cypress/**",
    "**/.eslintrc.js",
    "**/tsconfig.json",
    "**/tsconfig.*.json"
  ]
}

```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```

</p></details>

### Environment

node@16.17.0
pnpm@7.12.0
lerna@7.1.4

**Comment by fahslaj** [comment]
Hi @Dante-dan , can you please add `"loglevel": "verbose"` to your `lerna.json` and post the output (both local and in CI)?

This line should appear: 
`Explicit "packages" configuration found in lerna.json. Resolving packages using the configured glob(s): ...`
