### ISSUE TITLE
[Feature] lerna owners

### ISSUE THREAD

**Issue by jamiebuilds** [lerna/lerna#38]
It's rather tedious to have to add npm owners to every project. It would be nice to have commands that could do the following operations in every package.

```
$ lerna owners add username
$ lerna owners rm username
```

Which would do the following actions.

```
$ npm add owner username package
$ npm rm owner username package
```

It'd be even nicer if it tracked the owners so that when you added a new package it would add them all.

Would work well with #42

**Comment by hzoo** [comment]
a great idea. do we want to do the whole "OWNERS" file to track. How to we how to configure/store data (this would go with the changelog - github project name, token, etc, issue labels, etc)

**Comment by Marak** [comment]
Is possible to include `npm` as dependency and run commands.

You can also spawn `npm` as child process.

**Comment by thejameskyle** [comment]
I was wondering if we wanted to create a `lerna.json` file that could track information like "version", "owners", "independent" and anything else that might come up

**Comment by hzoo** [comment]
yay more configs `.lernarc`

**Comment by thejameskyle** [comment]
Could just be `package.json` too

**Comment by thejameskyle** [comment]
Could just be `package.json` too. Better than having eight files to track different things.

**Comment by thejameskyle** [comment]
If anyone wants to use scripts for this for now, you can use these: https://gist.github.com/thejameskyle/eba3a918a3db80ddc656

Just dump those in a `scripts/` directory and `chmod +x` them all. Then create an `NPM_OWNERS` file and add the current owners' npm usernames on individual lines and run `./scripts/npm-owner-update.sh`. The other two scripts are there if you ever want to grant or revoke ownership to users.

**Comment by hzoo** [comment]
We can add this to `lerna.json` now

**Comment by thejameskyle** [comment]
Yeah, I was working on a PR this weekend for it

**Comment by MoOx** [comment]
Any plan to grad something like https://github.com/babel/babel/blob/master/scripts/grant-npm-owner.sh into the core?

**Comment by hzoo** [comment]
Yeah, just not implemented https://github.com/lerna/lerna/pull/294, and if you want to make a pr feel free

**Comment by Sawtaytoes** [comment]
Is the config file name `lerna.json` and optionally `.lernarc` or just `lerna.json`?

**Comment by evocateur** [comment]
Currently just `lerna.json`. Probably will expand in the 3.0 alpha when `cosmiconfig` is used, dunno yet.
