### ISSUE TITLE
Migrating from lerna bootstrap -> package.json not found

### ISSUE THREAD

**Issue by pvieira91** [lerna/lerna#3801]
## Current Behavior

We tried to upgrade lerna to v7. Lerna bootstrap was removed and therefore we were replacing it with npm workspaces. I've followed the migration steps, which are pretty straightforward, but I ended up having this error. Whenever i try to run a lerna command this is the output.

`lerna ERR! ENOPKG `package.json` does not exist, have you run `lerna init`?`

The package.json files does exist. Here is the structure of the file

```package.json
{
  "name": "root",
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "devDependencies": {},
  "scripts": {},
  "description": "monorepo",
  "lint-staged": {},
  "msw": {},
  "husky": {},
  "dependencies": {}
}
```

The lerna.json file is

```lerna.json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "packages": ["apps/*", "packages/*"],
  "version": "7.3.0",
  "exact": true,
  "npmClient": "npm",
  "command": {
    "publish": {
      "registry": "https://npm.pkg.github.com/@beckersdp",
      "message": "AUTO-COMMIT %v"
    }
  },
  "maxBuffer": 10240000,
  "ignoreChanges": [
    "**/__fixtures__/**",
    "**/__tests__/**",
    "**/*.md",
    "scripts/**",
    "**/README.md",
    "docs/**",
    "**/test-report.json",
    "**/test-report.xml"
  ],
  "useNx": true
}
```

Any idea of what is happening? Is there a way to get more detailed logs?

**Comment by pvieira91** [comment]
Turns out it was due to node version. Installed v18 and it's now working like a charm

**Comment by JamesHenry** [comment]
Great thanks for confirming @pvieira91 

I’d recommend running the lerna repair command to tidy up your lerna.json a bit
