### ISSUE TITLE
Adding `--scope` to `ls` or some way to determine which packages are depended upon for a single package

### ISSUE THREAD

**Issue by Steven-Evans** [lerna/lerna#381]
Supposing a monorepo has multiple common dependent packages for services which are also in the same repository, it would be useful to know the complete list of packages that a particular service depends on. For example:

Service-1 depends on Auth
Auth depends on Common
Service-2 depends on Auth and Profile
Profile depends on Common

Then `lerna ls --scope Service-1` outputs something like:
Service-1
Auth
Common

**Comment by Steven-Evans** [comment]
https://github.com/lerna/lerna/pull/382

**Comment by lukebatchelor** [comment]
Just linking this here for completeness re: the quiet flag #133

**Comment by ccrowhurstram** [comment]
Feature sounds very interesting... can you make sure it works with https://github.com/lerna/lerna/pull/365 when it lands (not sure if you need to anything, just a "heads up")

**Comment by Steven-Evans** [comment]
I gave it a quick glance and it seems like it shouldn't be a problem. packages and packageGraph are still defined during runPreparations. 

As per my comment on the PR, I'm going to create a new PR to remove the --quiet flag since @thejameskyle suggested the intent to remove the lerna version line of output altogether, which is somewhat unrelated to this.

**Comment by thejameskyle** [comment]
Moving to #384
