### ISSUE TITLE
Version --sync-dist-version not work

### ISSUE THREAD

**Issue by trevisanweb** [lerna/lerna#3829]
When trying to use the --sync-dist-version option does not work, the following error appears as if the option does not exist.

npx lerna version --sync-dist-version
ERR! lerna Unknown arguments: sync-dist-version, syncDistVersion

**Comment by fahslaj** [comment]
Hi @trevisanweb , that feature has not been released yet. I'll follow up here after the next feature release of Lerna.

**Comment by fahslaj** [comment]
@trevisanweb this was just released with Lerna 7.3.0.
