### ISSUE TITLE
Independent versioning mode

### ISSUE THREAD

**Issue by its-me-dhina** [lerna/lerna#3840]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://lerna.js.org/docs/features/version-and-publish#independent-mode

### Additional context or description

In independent versioning mode, 

- How can I version only a particular package with the help of a scope tag If that is supported?
- Some code examples would be great.

**Comment by mcanelo** [comment]
I have the same problem. 

i can't version only one package.

**Comment by fahslaj** [comment]
Duplicate of #3853
