### ISSUE TITLE
This repo's `package-lock.json` is broken

### ISSUE THREAD

**Issue by dotlambda** [lerna/lerna#3843]
## Current Behavior
Many entries in [`package-lock.json`](https://github.com/lerna/lerna/blob/main/packages/lerna/package.json) don't have `"resolved"` and `"integrity"` values.
The first such dependency I could find is `"node_modules/@babel/plugin-syntax-async-generators"`,

## Expected Behavior
Every dependency should have `"resolved"` and `"integrity"` values so that Lerna can be built reproducably.

### Failure Logs / Configuration
Trying to do an offline install fails withh something like
```
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/yocto-queue failed: cache mode is 'only-if-cached' but no cached response is available.
```

### Environment
NixOS

**Comment by felschr** [comment]
Issues that track the problem of missing `integrity` & `resolved` fields in npm:
https://github.com/npm/cli/issues/4263, https://github.com/npm/cli/issues/4460 https://github.com/npm/cli/issues/6301
