### ISSUE TITLE
lerna 6 support

### ISSUE THREAD

**Issue by arpit1503khanna** [lerna/lerna#3868]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

Please provide the date until which you are going to support lerna 6.

**Comment by JamesHenry** [comment]
@arpit1503khanna Lerna v7 is the currently supported major version of Lerna.

Please can you explain why you want to continue to use Lerna v6?

**Comment by arpit1503khanna** [comment]
Because some of my projects depend on lerna 6, and I don't want to upgrade them to lerna 7 as of now, so can u tell how long will you give support for lerna 6.

**Comment by JamesHenry** [comment]
@arpit1503khanna Lerna has never had a multi major version support model, so when version 7 was released, which was many month ago, it became the supported version of lerna, and lerna 6 was no longer directly supported (although obviously it is not going to suddenly disappear from npm or anything).

If could elaborate on why you don't want to upgrade the projects to the latest lerna maybe we can help? If it is related to the bootstrap etc commands being removed by default, then hopefully you've seen you can resolve that by installing an extra package? Overall we are not aware of any blockers from 6 to 7, so if you are experience some please share them with us.
