### ISSUE TITLE
[Question] win10:  lerna: command not found

### ISSUE THREAD

**Issue by suhaotian** [lerna/lerna#387]
windows 10:

``` shell
$ npm install --global lerna@^2.0.0-beta
C:\Users\DELL\AppData\Roaming\npm\lerna -> C:\Users\DELL\AppData\Roaming\npm\node_modules\lerna\bin\lerna.js
C:\Users\DELL\AppData\Roaming\npm
`-- lerna@2.0.0-beta.30

DELL@DELL-PC MINGW32 /g/repo/coms (master) $ lerna init 
bash: lerna: command not found
```

**Comment by thejameskyle** [comment]
Has anyone else had this problem? I haven't heard any reports of people having issues installing Yarn globally on windows

**Comment by suhaotian** [comment]
Now it's work.

**Comment by besrabasant** [comment]
I faced this issue when I installed `lerna` using `yarn`. Reinstalling using `npm` solved the issue.

**Comment by hewentaowx** [comment]
@suhaotian When I used yarn I also encountered this problem but replaced npm to solve the problem

**Comment by Nandanchaturvedi** [comment]
@suhaotian how did you solve this issue ?

**Comment by rajeshkumarsampath** [comment]
I had this issue even with npm. By explicitly adding C:\Users\yourusername\AppData\Roaming\npm to the PATH variable under System Variables in environment variable solves the issue for me.

**Comment by jaquesgrobler** [comment]
npm instead of yarn fixed it for me in this case
