### ISSUE TITLE
Lerna says it is targeting 8 projects, but it is only logging for two

### ISSUE THREAD

**Issue by DaveStein** [lerna/lerna#3872]
## Current Behavior

I am running `lerna run dev --stream` which kicks off 8 `dev` commands for each package, where they all run watchers.

It prints `Lerna (powered by Nx)   Running target dev for 8 projects`

I only see logs for two watchers, and editing any of the other packages does nothing.

## Expected Behavior

It should stream all 8 or at least print errors as to why it is not acting upon the other 6.

## Steps to Reproduce

My `dev` steps are all either:

`"dev": "rm -rf dist && vite build --watch --mode=development",` or `cross-env MODE=development yarn watch`

`watch` maps to `"watch": "webpack --watch --config webpack.config.js",`

## Extra Note
I used to run `--parallel` before I was able to move a few packages to Vite. It seems fatal errors in Webpack don't break its watcher. So when things compiled out of order, it would eventually get it right. Errors break Vites compiler so I figured `--stream` would solve the issue as it can have concurrency. I see it watching two things at once... even if I do `--concurrency 8`, it still only watches two.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.22.1",
  "version": "0.40.3",
  "npmClient": "yarn",
  "packages": ["packages/*"],
  "command": {
    "publish": {
      "registry": "secret.com"
    }
  }
}

```

</p></details>

</p></details>

### Environment

```
lerna notice cli v7.4.1

 Environment info:

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.0.0/bin/yarn
    npm: 8.6.0 - ~/.nvm/versions/node/v18.0.0/bin/npm
  Utilities:
    Git: 2.39.2 - /usr/bin/git
  npmPackages:
    lerna: ^7.4.1 => 7.4.1 
```

**Comment by fahslaj** [comment]
Hi @DaveStein , I'm sorry you are experiencing this issue. Unfortunately, I was not able to reproduce it running `lerna run dev --stream` in a repo with 8 vite packages using the exact `vite build --watch --mode=development` command provided above. The behavior you are describing is consistent with `--concurrency=2` being passed as an argument to Lerna. 


Could you please provide a minimal reproduction of this issue?  This can be a link to the repo in which you are experiencing the issue or a link to a new repo that consistently produces the issue.

**Comment by DaveStein** [comment]
When I reported this, I switched to independently watching each package as needed to get unblocked. I will close this for now to not clog your issues. If I can get to making a small repro I will re-open (if I can). Thanks for commenting.
