### ISSUE TITLE
[Feature] Add a `--with-deps` flag to bootstrap --scope

### ISSUE THREAD

**Issue by lukebatchelor** [lerna/lerna#388]
After playing with the results on #386 locally for a bit I've realised what would be most useful is if a scoped bootstrap command bootstrapped all the dependencies of packages first. 
- If used without `--scope` it would ignore this.
- Would need some logic to sort out the order of installation if more than one package is matched by `--scope`

The use case for us is lots of packages now taking a long to time prepublish and link. `--scope` helps a lot but not in the case where you've done a clean and just want to start working on one package. You would try to scope to the package you want but your dependencies wont be built.

I can see #384 being super useful for this. If we have a direction on #384 and #386 then I can start working on this next week if you like.

(`--with-deps` is a terrible name, any suggestion would be appreciated. `--recursive` maybe? `--bootstrap-deps`?)

**Comment by lukebatchelor** [comment]
I was leaning towards that too, but I think keeping it like this would give more flexibility. If you want to prepublish deps, you can, but if you just want to clean and rebuild/link one package as fast as possible, you can too. 

Also makes sense from the semantics of --scope, "perform acertain command in a specific package". The only edge case is if your bootstrapping requires a package that you are building at the same time

**Comment by lukebatchelor** [comment]
Maybe it should warn if you are bootstrapping a package that relies on a package you are bootstrapping?

**Comment by seansfkelley** [comment]
Yeah, that also seems reasonable.

**Comment by lukebatchelor** [comment]
Opinion: Should `--with-deps`/`--recursive`/whatever throw an error if `--scope` matches more than one package? The logic for the order to bootstrap them will get pretty complicated and it seems like more of an edge case than the case where you are simply bootstrapping one package. The other way of looking at it is that it would make `--scope`'s sematic meaning be a little less consistent  (`--scope` scopes a command to a set of packages matching a glob **unless** the `--with-deps` flag is set, the `--with-deps` flag is ignored if you don't pass the `--scope` flag, etc, etc). Just seems like it's making more exceptions to the rule.

Anyone have any opinions? I'm leaning towards Throwing if it matches more than one, just because I feel like this covers the majority of use-cases.

**Comment by seansfkelley** [comment]
I would definitely not throw. The semantics of including the transient dependencies are well-defined, and throwing should be reserved for exceptional circumstances where you really cannot proceed (indeed, I think that Lerna throwing when nothing matches scope is bad UX).

That said, while we're talking about UX, the include-exclude-include (`scope`-`ignore`-`with-deps`) behavior itself is a bit weird to begin with.

**Comment by lukebatchelor** [comment]
Fair call on the Throwing, that was more to keep it consistent with the throwing from not matching anything. I think I agree there actually, there are probably cases where you want to generate your bootstrap command on the fly and you may well want to run bootstrap (or any command) and have it act on no packages.

Not sure I agree on the UX in include-exclude-withdeps though. They seem pretty consistent in their meanings across all commands

`--scope` - whitelist a command to packages that match this glob
`--ignore` - blacklist a command against packges that match this glob
`--with-deps` - (in bootstrap, only when used with scope and/or ignore) bootstrap dependencies even if they are not matched by the previous globs

Seems pretty consistent, open to suggestions though.

**Comment by lukebatchelor** [comment]
Also, leaning towards `--include-deps` as the flag. I'm going with that for now but definitely open to suggestions.

Question: does a flag with `--` at the beginning imply it takes parameters? This one wouldnt.

```sh
lerna bootstrap --scope "package-a" --include-deps
```

**Comment by seansfkelley** [comment]
http://serverfault.com/a/387938

**Comment by noherczeg** [comment]
@lukebatchelor Since `yargs` is used internally in Lerna `--scope "package-a"` should be the same as if you would provide `--scope=package-a`, etc.

**Comment by lukebatchelor** [comment]
@noherczeg, not sure what you mean by that. This issue wasnt about how to pass args? It was a separate flag i wanted to add?

This issue should actually be closed too. I implemented it in #390.

**Comment by noherczeg** [comment]
@lukebatchelor I was referring to this: "Question: does a flag with -- at the beginning imply it takes parameters?"

And tried to point out that checking out yargs docs is the way to go. That's all. Oh and I didn't see the PR, so I thought that it's still an ongoing issue.
