### ISSUE TITLE
Add support for `package.yaml`

### ISSUE THREAD

**Issue by rlidwka** [lerna/lerna#3918]
- [x] I'd be willing to implement this feature

## Description

Lerna should look for `package.json5` or `package.yaml` before `package.json` for local packages (root and all packages in workspace).

## Motivation

It is very important for me to be able to comment out project dependencies (as well as scripts and occasionally other metadata). Why? Because if some package has a bug in it, and I have to lock its version as specifically as "=1.2.3", I need to document *somewhere* why that version is locked.

For this reason, I've maintained a custom npm fork 10 years ago, then I was documenting this stuff to separate `.md` file for 6 years, and then I've switched to `pnpm` after it added `package.json5` support 4 years ago.

Turns out, I cannot use this setup with `lerna`, because it complains about lack of `package.json` in root:

```
$ ls -l
total 152
-rw-r--r-- 1 user user    109 Dec 13 06:06 lerna.json
drwxr-xr-x 4 user user   4096 Dec 13 06:06 node_modules
-rw-r--r-- 1 user user    280 Dec 13 06:05 package.yaml
-rw-r--r-- 1 user user 135662 Dec 13 06:05 pnpm-lock.yaml
-rw-r--r-- 1 user user     27 Dec 13 06:06 pnpm-workspace.yaml

$ ./node_modules/.bin/lerna run test
lerna notice cli v8.0.0
lerna ERR! ENOPKG `package.json` does not exist, have you run `lerna init`?

$ ./node_modules/.bin/lerna init
lerna notice cli v8.0.0
lerna ERR! Lerna has already been initialized for this repo.
lerna ERR! If you are looking to ensure that your config is up to date with
the latest and greatest, run `lerna repair` instead
```

`pnpm` supports both `json5` and `yaml`. Either one will work for me (I just need comments), but supporting both would be better for compatibility reasons.

Normally, adding new formats is controversial because new dependency increases installation size for everyone.

But `lerna` already has yaml parser as a dependency (because of things like pnpm-workspace), adding this feature would have no downsides except for some `.stat()` calls. Same goes for json5 because it's already pulled as a transitive dependency (via nx->tsconfig-paths).

**Comment by JamesHenry** [comment]
@rlidwka Lerna is built on top of npm CLI internals and even when using pnpm as the package manager, it is still npm interals logic that is used for versioning and publishing. We wouldn't look to deviate from npm's way of doing things (i.e. no support for custom manifest files) as that would introduce unnecessary complexity.

I understand your reason for wanting this, but I'm afraid it's not something we will proceed with
