### ISSUE TITLE
Support For Custom Tagging Formats

### ISSUE THREAD

**Issue by briananstett** [lerna/lerna#3940]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/lerna/lerna/blob/main/CONTRIBUTING.md))

## Description
It would be nice if you could customize the tagging format used when generating a git tag. Right now it appears to follow the format `<package name>@<version>`.

## Motivation
I was hoping to use Lerna to manage a monorepo of GitHub actions where each "package" is a differnet action. The issue I ran into is that GitHub uses the "@" symbol in it's `use` directive to denote the tag in the repo.
```
uses: actions/checkout@v4
```

Since all my action's tags were folloing the format `<action name>@<version>`, GitHub was throwing some errors when trying to use them in this format.
```
uses: myorg/repo/actions/actionName@actionName@v1.2.3
```

## Suggested Implementation
I was invisioning something like a delimiter setting in the `lerna.json` file?

**Comment by JamesHenry** [comment]
This is available in the latest lerna (landed in https://github.com/lerna/lerna/pull/3951)

**Comment by briananstett** [comment]
Hey @JamesHenry I think there was a bug introduced with the `--tag-version-separator` change. 

When trying to create a new version of a package with the `--tag-version-separator` flag, it appears creating a GitHub release is failing or rather just not happening.

For example:
```bash
git commit -m'fix(action2): testing fix patch3'
npx lerna version --conventional-commits --tag-version-separator="v" --create-release github --yes
lerna notice cli v8.1.2
lerna info versioning independent
lerna info Looking for changed packages since action2@1.1.5
lerna info getChangelogConfig Successfully resolved preset "conventional-changelog-angular"

Changes:
 - action2: 1.1.5 => 1.1.6

lerna info auto-confirmed 
lerna info execute Creating releases...
lerna info git Pushing tags...
lerna success version finished
```

But I go to the GitHub release page, there is not a release for the `1.1.6` version. 

I can see the tag created but not the GitHub release.
```bash
$ git tag
action2v1.1.6
```
![image](https://github.com/lerna/lerna/assets/18585217/cf7a9e53-9d40-4be4-8980-8f195c935678)
![image](https://github.com/lerna/lerna/assets/18585217/0adc6f23-2e86-4e8f-992b-f5610820ba0c)


Also, I believe the the `--tag-version-separator` option is missing from the [version command](https://github.com/lerna/lerna/tree/main/libs/commands/version#readme) documentation.
