### ISSUE TITLE
[Feature] Add custom commit message option to publishConfig

### ISSUE THREAD

**Issue by traviskaufman** [lerna/lerna#395]
Currently it looks like the commit messages for publishing are [hard](https://github.com/lerna/lerna/blob/cc9b48725f89ad94a2fa2b5cd7f984da199cd5a1/src/commands/PublishCommand.js#L311)-[coded](https://github.com/lerna/lerna/blob/cc9b48725f89ad94a2fa2b5cd7f984da199cd5a1/src/commands/PublishCommand.js#L325). This presents problems for us since we enforce a pre-defined commit message style in a git hook via [validate-commit-message](https://www.npmjs.com/package/validate-commit-message). 

Currently, we plan on getting around this by patching lerna's commit messages within the `prepare-commit-message` hook. However, it would be nice if lerna exposed some functionality to customize the `publish` commit messages so that repo maintainers with commit guidelines wouldn't have use workarounds like those described above. I'm happy to help contribute this feature if the team is open to adding it.

**Comment by traviskaufman** [comment]
I was thinking as a `publishConfig` option. Something like `publishConfig.customCommitMessage` . 

Do you think the custom message should overwrite the entire commit message, or just the subject? It looks like for independently-versioned repos lerna adds all of the tags it will create to the commit message body. It seems like this would be okay to overwrite but I'm not sure if there are other mechanics that rely on this being present.

**Comment by thejameskyle** [comment]
I would prefer this implemented as a flag `--message` or `-m`. Otherwise people will immediately want some kind of template syntax for adding versions and what packages changed, that's just gonna get messy

**Comment by thejameskyle** [comment]
Note that this should not change the git tag that is created, I would like to be able to use that with confidence.

**Comment by traviskaufman** [comment]
^ sorry this took me so long to get around to. Lmk if there's any docs I've missed and/or if there's any part of the feature impl I've overlooked.
