### ISSUE TITLE
NPM Private registry

### ISSUE THREAD

**Issue by troianoandres** [lerna/lerna#396]
Hi, I have a question that not sure if defined into the docs. 

I'm supposing that `lerna publish` will take in count `publishConfig` definition, more exactly the `registry` value, but I need a confirmation about that. 

I must be sure that the package will be published into my private registry instead of the global npm registry. If this is as I described I'll go forward.

Thanks.

**Comment by evocateur** [comment]
Yes, a `publishConfig` that specifies an alternate `registry` will be honored. It has to be located in every package, however (`./packages/*/package.json`), not the "root" package.json.
