### ISSUE TITLE
`lerna list` output is truncated at 8192 bytes when `exec`ed

### ISSUE THREAD

**Issue by jonscheiding** [lerna/lerna#3970]
## Current Behavior

When executing `lerna list` from within a Node process via `exec` or `spawn`, the stdout is truncated at 8192 bytes.

## Expected Behavior

All stdout output should be captured.

This appears to have been introduced with bafe090, because the `process.exit` terminates the process handle before the output buffers are finished flushing.

Reference: https://stackoverflow.com/a/59322701/27578

## Steps to Reproduce

Run this code in a monorepo which has a large enough number of packages to push the output of `list` past 8192 bytes.

```
const { exec } = require("child_process");

exec("npx lerna@8.1.2 list --all --json", (error, stdout, stderr) => {
  console.log(`stdout: ${stdout}`);
});
```

Other variantions tried:

```
const { exec } = require("child_process");

const process = exec("npx lerna@8.1.2 list --all --json");

let stdout = "";
process.stdout.on("data", (chunk) => (stdout += chunk));

process.on("close", () => {
  console.log(stdout);
});
```

```
const { spawn } = require("child_process");

const process = spawn("npx", ["lerna@8.1.2", "list", "--all", "--json"]);

let stdout = "";
process.stdout.on("data", (chunk) => (stdout += chunk));

process.on("close", () => {
  console.log(stdout);
});
```

These snippets work as expected with `lerna@8.1.0`.

**Comment by smerrill** [comment]
![image](https://github.com/lerna/lerna/assets/156815/537f3806-d8f6-40cb-8feb-41a02a1f6196)
Here is a simple reproduction and fix using our actual `lerna list --all --json` output. Without the `process.stdout.end()` callback, `test2.js` would only receive 8k and not our full 20k of output.

**Comment by RoXuS** [comment]
+1 same issue during our release, hard to debug, all works as expected on 8.1.0.

This commit seems to be the culprit: https://github.com/lerna/lerna/commit/bafe090e837675c0febb938bab3e8c71b27dbe70
