### ISSUE TITLE
Package.json workspaces field is being ignored

### ISSUE THREAD

**Issue by igoldny** [lerna/lerna#3973]
## Current Behavior

Currently, Package.json workspaces field is being ignored and `@lerna/project ` gets the default packages folder only.
`getPackagesSync` from `@lerna/project` returns only packages from packages folder.
`lerna.json` packages field has to be provided instead on `"lerna": "^8.1.2"`.

## Expected Behavior

Package.json workspaces field should be applied when `lerna.json` packages field isn't provided.

## Steps to Reproduce

1. Install `"lerna": "^6.6.2"`
2. Provide Package.json workspaces field
3. Get all packages using `getPackagesSync` from `@lerna/project` 
4. Update to `"lerna": "^8.1.2"`
5. Package.json workspaces has been ignored and `getPackagesSync` returns only packages folder

You can reproduce it here: https://codesandbox.io/p/devbox/lerna-workspace-packages-bug-yp796f?file=%2Frun-lerna.js%3A1%2C38-1%2C52

**Comment by fahslaj** [comment]
Hi @igoldny , @lerna/project has been deprecated and does not work with modern versions of Lerna. Instead, you should use the `detectProjects()` utility exported directly from `lerna/utils` - https://lerna.js.org/docs/api-reference/utilities#detectprojects
