### ISSUE TITLE
lerna success found 0 packages

### ISSUE THREAD

**Issue by Fuarm** [lerna/lerna#3985]
version: 8.1.2
lerna list 

lerna notice cli v8.1.2
lerna info versioning independent
lerna success found 0 packages

version: 7.4.2
lerna list  
       
lerna notice cli v7.4.2
lerna info versioning independent
core
demo
lerna success found 2 packages

**Comment by Fuarm** [comment]
[#3964 ](https://github.com/lerna/lerna/issues/3964)

**Comment by JamesHenry** [comment]
@Fuarm Please follow the steps on the comment I put on that issue you linked to and see if you can reproduce the issue, I will close this one so that we can keep everything together.
