### ISSUE TITLE
`exec` can hit "stdout maxBuffer exceeded" errors

### ISSUE THREAD

**Issue by seansfkelley** [lerna/lerna#399]
Lerna uses `exec` in some places, rather than `spawn`. If your task has a lot of output, this can cause erroneous failures due to implementation details of `exec` (http://www.hacksparrow.com/difference-between-spawn-and-exec-of-node-js-child_process.html). In particular, I hit this because I had Webpack/Uglify misconfigured and it was spewing thousands of useless log lines and failing my builds. I've fixed my direct cause (I never wanted these log lines), but I thought I would raise the broader issue here.

**Comment by thejameskyle** [comment]
Merging into #278
