### ISSUE TITLE
[Feature] When installed in other dependencies field, use that for init instead

### ISSUE THREAD

**Issue by timoxley** [lerna/lerna#401]
### Problem

When updating an existing lerna project from 1.x to 2.x, users will end up with lerna 2.x in their `devDependencies` and lerna 1.x in `dependencies`.

### Suggestion

`lerna init` should remove any version of `lerna` in `dependencies` before adding itself to `devDependencies`, ideally only when updating from 1.x to 2.x.

### Details

The `lerna bootstrap` command from lerna 1.1.3 adds `lerna` to `devDependencies`.
The `lerna init` command from lerna 2.0.0-beta.30 adds `lerna` to `dependencies`.

#### Repro Script

```sh
yarn global add lerna@1.1.3 # current release version
mkdir $TMPDIR/lerna-test && cd $TMPDIR/lerna-test
lerna bootstrap # will create package.json with lerna in dependencies
yarn global add lerna@2.0.0-beta.30 # current prerelease version
lerna init # will add lerna to package.json devDependencies
cat package.json
```

```json
{
  "private": true,
  "dependencies": {
    "lerna": "^1.1.3"
  },
  "devDependencies": {
    "lerna": "2.0.0-beta.30"
  }
}
```

This was mainly surprising because `lerna init` appears to know what it's doing when performing the "upgrade":

```
`lerna.json` does not exist, have you run `lerna init`?
> lerna init
Lerna v2.0.0-beta.30
Updating package.json.
Creating lerna.json.
Removing old VERSION file.
Successfully created Lerna files
```

----

IIUC this problem will be somewhat resolved if https://github.com/lerna/lerna/pull/370 lands for 2.x, as I believe the existing version of `lerna` in `dependencies` will be updated rather than a new one added to `devDependencies`. The problem is that when 2.x is released most existing users will end up with `lerna` in their `dependencies` rather than `devDependencies`, where it probably belongs.

I'd suggest that @joscha's usecase should be considered an edgecase, "advanced" usage. I think any "damage" for such users would be mitigated if the init script informs the user "moving lerna to devDependencies" like it does with "Removing old VERSION file.". Most users end up with lerna in the right location, a small subset of users has to move the dependency back to `dependencies`.

Also possible to be "smart" and only invoke this forced move from `dependencies` to `devDependencies` if it's detected the user is upgrading from lerna 1.x to 2.x e.g. user has a VERSION file or current version of `lerna` in `dependencies` is 1.x.

**Comment by thejameskyle** [comment]
It might be better to just use whatever field it is already installed into. So if Lerna was installed in `dependencies` we'll just continue to use `dependencies`
