### ISSUE TITLE
Dependency on braces 3.0.2

### ISSUE THREAD

**Issue by izaaz** [lerna/lerna#4027]
## Current Behavior

Lerna has a dependency on the library braces which has a security vulnerability in version 3.0.2. This was fixed in version 3.0.3

https://github.com/micromatch/braces/issues/36

## Expected Behavior

No dependency on libraries with known security vulnerabilities

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```

</p></details>

**Comment by JamesHenry** [comment]
This is resolved in the latest lerna `8.1.5`
