### ISSUE TITLE
conventionalcommits don't worky anymore with lerna publish

### ISSUE THREAD

**Issue by bennycode** [lerna/lerna#4030]
## Current Behavior

Error when releasing packages:

> lerna ERR! EPRESET Unable to load conventional-changelog preset 'conventionalcommits' (conventional-changelog-conventionalcommits)

## Expected Behavior

Successful release with changelogs.

## Steps to Reproduce

Set `changelogPreset:name` in your `lerna.json` file to `conventionalcommits` and run `lerna publish`. The issue exists because `conventional-changelog-conventionalcommits` in Version 8 switched fully to ECMAScript moduels: https://github.com/conventional-changelog/conventional-changelog/releases/tag/conventional-changelog-writer-v8.0.0

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "changelogPreset": {
    "issueUrlFormat": "{{host}}/{{owner}}/{{repository}}/issues/{{id}}",
    "name": "conventionalcommits"
  },
  "command": {
    "publish": {
      "allowBranch": "main",
      "conventionalCommits": true,
      "message": "[skip ci] chore: Publish"
    }
  },
  "exact": true,
  "loglevel": "verbose",
  "npmClient": "yarn",
  "npmClientArgs": ["--exact"],
  "registry": "https://registry.npmjs.org/",
  "version": "independent",
  "yes": true
}
```

</p></details>

### Environment

- "lerna": "8.1.3"
- "conventional-changelog-conventionalcommits": "8.0.0"

**Comment by ghiscoding** [comment]
duplicate of #4021 simply downgrade to v7.x of conventional commits since they had major breaking changes

**Comment by bennycode** [comment]
Thanks for the info! 👍
