### ISSUE TITLE
Lerna 8.1.5 is not including yarn.lock to lerna publish package.tgz

### ISSUE THREAD

**Issue by prathick** [lerna/lerna#4037]
## Current Behavior
yarn.lock is not getting added to npm pack or yarn pack thats done during lerna publish. yarn.lock is required to install offline and we do that in our pipeline

## Expected Behavior
to include yarn.lock to the package tarball so that it can be used for yarn install —offline

**Comment by JamesHenry** [comment]
Please provide a minimal reproduction of how lerna is behaving differently to `npm pack` or `yarn pack` in this regard.

In my testing, they intentionally omit the lock file, even if explicitly included via files:

<img width="807" alt="image" src="https://github.com/lerna/lerna/assets/900523/41c13b22-034e-4001-a33c-28555aac38dd">

<img width="901" alt="image" src="https://github.com/lerna/lerna/assets/900523/2a4713ec-1618-4749-94b5-b8ff54e8e82c">

**Comment by prathick** [comment]
here is my example:

node version: 18.17.0
yarn version: 1.22.19

I created a sample app and added yarn.lock to files in package json. Now if do yarn pack i can see the yarn.lock inside the tgz created. Please the images 
Yarn pack:
![Screen Shot 2024-07-05 at 11 03 28 AM](https://github.com/lerna/lerna/assets/17000631/5837be88-db2b-4e8d-9dea-fc1a6922b39e)

package folder with yarn.lock
![Screen Shot 2024-07-05 at 11 04 06 AM](https://github.com/lerna/lerna/assets/17000631/b3832005-cd04-4533-8864-445becb97386)

I tried the same with npm but it did not add the yarn.lock or package-lock to the package. My question is did lerna move from yack pack to npm pack command? because I down graded to lerna 8.0.1 and U see our published package have the yarn.lock. But with 8.1.5 i dont see yarn.lock in the published package

**Comment by JamesHenry** [comment]
Lerna simply builtds on top of npm utilities, and it looks like npm formally updated the behaviour at some point, you can see `npm pack` will always ignore yarn.lock based on the docs here on v10 https://docs.npmjs.com/cli/v10/configuring-npm/package-json/#files but not here on v9 https://docs.npmjs.com/cli/v9/configuring-npm/package-json

Push back on a case from npm similar to yours:

https://github.com/npm/cli/issues/6738

We won't be attempting to deviate from npm's behaviour here I'm afraid, lerna is built on top of npm utilities and there would have to be a very strong reason to be misaligned with them.
