### ISSUE TITLE
Bootstrap ignore flag misses package

### ISSUE THREAD

**Issue by swashcap** [lerna/lerna#405]
The `bootstrap` command fails to ignore a package when using the `--ignore` flag. Here’s some details:

```shell
$ ls -1 packages
coinstac-client-core/
coinstac-common/
coinstac-decentralized-algorithm-integration/
coinstac-server-core/
coinstac-simulator/
coinstac-storage-proxy/
coinstac-ui/
$ node_modules/.bin/lerna bootstrap --ignore 'coinstac-{client-core,decentralized-algorithm-integration,simulator,storage-proxy,ui}'
Lerna v2.0.0-beta.30
Ignoring packages that match 'coinstac-{client-core,decentralized-algorithm-integration,simulator,storage-proxy,ui}'
Bootstrapping 3 packages
Installing external dependencies
Successfully bootstrapped 3 packages.
$ find packages -type d -name node_modules -maxdepth 2
packages/coinstac-common/node_modules
packages/coinstac-decentralized-algorithm-integration/node_modules
packages/coinstac-server-core/node_modules
```

Lerna seems to miss the `decentralized-algorithm-integration` in the ignore glob. Any thoughts?

* Repo: [MRN-Code/coinstac](https://github.com/MRN-Code/coinstac)
* Node: 6.9.1
* npm: 3.10.9
* lerna: 2.0.0-beta.30

**Comment by thejameskyle** [comment]
You're trying to ignore the folder name but your package name is different: https://github.com/MRN-Code/coinstac/blob/master/packages/coinstac-decentralized-algorithm-integration/package.json#L2

**Comment by swashcap** [comment]
❗️😱 _Nice catch!_
