### ISSUE TITLE
[Bug] Lerna swallows exit code when NODE_ENV is test

### ISSUE THREAD

**Issue by taion** [lerna/lerna#406]
Due to this code: https://github.com/lerna/lerna/blob/v2.0.0-beta.30/src/Command.js#L156-L158

Lerna commands won't pass through their exit codes when `NODE_ENV` is `test`.

CircleCI automatically sets `NODE_ENV` to `test` for builds that use Node, so if you do something like `lerna run test`, your build won't fail when your tests fail.

**Comment by thejameskyle** [comment]
We should change that to `NODE_ENV=lerna-test` since that's for our own test suite

**Comment by taion** [comment]
I'm not sure they're mutually exclusive. Presumably you still want to hide progress bars – unless you want to modify the other checks for `NODE_ENV` as well.

**Comment by thejameskyle** [comment]
Ah good point, we can just move it to a method and mock it in the tests

**Comment by timdp** [comment]
After looking at the code, I wrongfully assumed that `NODE_ENV=test` would just hide the progress bars, and then I ended up not noticing broken tests. So I'd like to second what @taion said.

**Comment by ryb73** [comment]
Looks like `NODE_ENV=test` will also cause Lerna to suppress logging to stdout and ignore Lerna version mismatches (the former I discovered the hard way, the latter I found by CTRL+F-ing for "NODE_ENV").

In response to @taion's comment:
> I'm not sure they're mutually exclusive. Presumably you still want to hide progress bars – unless you want to modify the other checks for NODE_ENV as well.

If the checks you're referring to are the ones I mentioned above, it seems reasonable (and preferable) to modify them – would you agree? If so I'd be happy to put in a PR implementing @thejameskyle's first suggestion of changing it to `lerna-test`.

**Comment by gigabo** [comment]
@ryb73 Yeah, that sounds worthwhile.  Thanks!
