### ISSUE TITLE
[Feature] Pattern match git tags

### ISSUE THREAD

**Issue by ianwremmel** [lerna/lerna#407]
I'm using jenkins for CI and automated release. Jenkins adds tags to every build, so git diff HEAD..$(LAST_TAG) detects zero changes. Have you run into this before? Any recommendations?

**Comment by thejameskyle** [comment]
Lerna always looks for the last tagged commit. Why does your Jenkins need to tag every build?

**Comment by ianwremmel** [comment]
that's a fantastic question, but so far i haven't been able to figure out how to turn it off.  could lerna's diff command be enhanced to look for a particular pattern? right now it's just grabbing the most recent tag, but I can imagine where some workflows would create tags reasons other than npm release.

**Comment by thejameskyle** [comment]
Sure we could add that

**Comment by hzoo** [comment]
> lerna's diff command be enhanced to look for a particular pattern?

very useful - lerna diff/updated both do the same

**Comment by thejameskyle** [comment]
Oh do we want a flag for this?

I was planning on just enforcing the `^/v[0-9]+\.[0-9]+.[0-9]+$/` (`vX.X.X`) pattern when looking for git tags.

**Comment by ianwremmel** [comment]
I think matching that pattern is fine. There's currently no means of altering the pattern that lerna uses for tags, right?

**Comment by thejameskyle** [comment]
There is not

**Comment by thejameskyle** [comment]
Oh, note that in independent mode the tags are different

```
locked      : v[version]
independent : [package]@[version]
```
