### ISSUE TITLE
[Discussion] Lerna Maintenance

### ISSUE THREAD

**Issue by seansfkelley** [lerna/lerna#408]
Tagging @hzoo and @thejameskyle directly.

When I first discovered Lerna about 2 months ago, it was in the midst of a big overhaul and it seemed like a pretty vibrant project. In the last 2 months, several important PRs have been sitting idle with zero participation from the maintainers. Looking [at the list of PRs that have been merged recently](https://github.com/lerna/lerna/pulls?q=is%3Apr+is%3Aclosed), they are almost exclusively documentation updates, save for #372 which was a dealbreaking bug (and which has not been released in a new version of Lerna, regardless).

This is a project that I, and clearly others, depend on for production code. Perhaps I jumped the gun when I first discovered Lerna (I was really excited to find something that seemed to address my _exact_ problem!), but I'm committed now. So I ask: is Lerna going to be seriously maintained/administered, either by the current maintainers or by others? Several contributors have already been driven away to start another project, and I am seriously considering maintaining an internal fork of Lerna and to stop contributing back, which seems like a lose-lose (unless my contributions are really that bad :O).

**Comment by thejameskyle** [comment]
Lerna has not been abandoned. We just maintain many projects.

There's a good chance Lerna is going to be merged into Yarn after awhile.

**Comment by thejameskyle** [comment]
I'll leave this open and let people ask questions if they want to

**Comment by dfabulich** [comment]
Is there an issue/PR/doc about this merge on Yarn's side?

**Comment by thejameskyle** [comment]
There is not, and I currently oppose doing it. I want to wait until Yarn is able to support other languages and see if we can solve all the problems we need to in Lerna before we consider making them into the same tool and what that would look like.

**Comment by thejameskyle** [comment]
Note that the majority of issues in this repo are feature requests. I just went through every single issue in the repo and marked them with tags in their titles.

There's very few [bug reports](https://github.com/lerna/lerna/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%22%5BBug%5D%22%20in%3Atitle) and they are mostly small things. More than half of them are just a handful of cross-cutting issues related to stuff like stdout/stderr, globs in commands, error handling, etc.

In terms of the features people request, most of them are workflow things, almost all of them can be worked around for now, and only a handful are actually causing serious pain to (some) users.

I'll go through the PRs next, but as of right now I see no reason for people to be concerned with the state of Lerna.

**Comment by seansfkelley** [comment]
What is the expectation going forward for feature requests? There are workarounds, but workarounds still suck and I have some helpful features in mind I want to tackle, but can't/won't until earlier prerequisite features exist.

**Comment by thejameskyle** [comment]
Such as?

**Comment by seansfkelley** [comment]
The one I'm eyeing in particular is https://github.com/lerna/lerna/issues/341, but I didn't want to start on it until https://github.com/lerna/lerna/issues/386 and https://github.com/lerna/lerna/pull/412 were accepted, since the path I was going to take to implement it was to rename bootstrap to link and strip the script-running, then reimplement bootstrap by delegating to a combination of link + run.

**Comment by mAAdhaTTah** [comment]
I have a question related to this: What are the ticket(s)/issue(s) that are keeping this from coming out of beta? We've been using WebPack@beta2 for a bit, and using beta software burned me a few times, so while I'm considering lerna as a solution for some pain points we're experiencing with separate repos, but I'm hesitant given the beta tag.

**Comment by hzoo** [comment]
Sorry, yeah haha it's long past time really. Just didn't pull the plug is all

**Comment by mAAdhaTTah** [comment]
Pull the plug?! I'm assuming you mean pull the trigger :)

**Comment by hzoo** [comment]
LOL sigh I need to go home. 🎱
