### ISSUE TITLE
Emoji in project description leads to confusing SEO title "Dragon"

### ISSUE THREAD

**Issue by friday** [lerna/lerna#4084]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

The GitHub repo description: https://github.com/lerna/lerna

I searched for Lerna and initially got confused, thinking you renamed to "Dragon".

![image](https://github.com/user-attachments/assets/4a68042f-c2b3-489d-a753-4315caca192f)

On mobile it looks like this:

![Screenshot_20240925-174425.png](https://github.com/user-attachments/assets/bf96bbf1-6f56-42b5-8420-2e48e938a9e1)

This is of course really a GitHub-issue, but it seems they are now translating emojis to their english names and using for the SEO titles now.

![image](https://github.com/user-attachments/assets/1711306a-44b1-4e6f-b7b3-411354ac0e10)

(maybe you can put it last in the description instead)

**Comment by JamesHenry** [comment]
Thanks, I've removed it for simplicity
