### ISSUE TITLE
End support for Node 0.10 and 0.12

### ISSUE THREAD

**Issue by thejameskyle** [lerna/lerna#418]
Official support for Node 0.10 has already been dropped, 0.12 will be dropped at the end of December, we should remove support for these– especially since 0.10 keeps failing in CI

**Comment by hzoo** [comment]
We kept in 0.10 since we were supporting it in Babel but if you want we can drop and babel will just use the older version until we drop it there as well.

**Comment by gigabo** [comment]
@hzoo Is there a babel issue we can link to that tracks when support will be dropped there?

**Comment by hzoo** [comment]
Yep, and just encountered this today via preset-env 😛  https://github.com/babel/babel/issues/4315

**Comment by hzoo** [comment]
We're going to drop in Babel soon so we can do this in a beta version as well.

**Comment by hzoo** [comment]
https://github.com/lerna/lerna/issues/484
