### ISSUE TITLE
[Feature] Ability to disable "resetting git state" on canary publications

### ISSUE THREAD

**Issue by L8D** [lerna/lerna#419]
I'll probably start on a quick PR for this in the next week or so, but it'd be convenient to have a flag/convention to disable the "Resetting git state" on canary publications. I use the leftover states so I can build one of my packages in docker with the new canary version. Currently I can get around this by running `lerna publish --skip-git --skip-npm --canary --yes` after the first publish to re-create the versions.

**Comment by gigabo** [comment]
@L8D Interesting.

So this would be a flag that would leave the repo with uncommitted changes to package.json?

I'm not sure I understand your current workflow.  Does `--skip-git` in the _initial_ publish not give you what you need?

**Comment by L8D** [comment]
@gigabo It does not because of [this line](https://github.com/lerna/lerna/blob/83cac1b1488f0c1edc547c85dafefe337845bf96/src/commands/PublishCommand.js#L117) which doesn't happen if I use `--skip-npm` on the second publish for some reason.

**Comment by gigabo** [comment]
Oh!  Okay, that makes sense.

So... yeah that workflow is kind of awkward.

Want to add a flag (and some documentation and tests 😁 )?

**Comment by rastasheep** [comment]
Thanks @L8D for the work around. I have same situation as you.

Is this something that can be addressed, or should be solved by adding some clarification in the docs? Personally i hoped that `--skip-git` will skip reseting git state as well.

**Comment by L8D** [comment]
@rastasheep Lerna has had many structural changes since I last looked into the code. I'm not sure if the behavior is still the same. I know Lerna will now annotate package.json with the "gitHead" attribute so there's more complexity to handle there.

I think the need for this feature would go away if Lerna allows us to run each publishing step standalone. We would have a different command for each step of the process and we could run our own build scripts between steps or omit entire steps.

**Comment by evocateur** [comment]
`--skip-git` is a poorly-named option, it has _never_ meant "skip all git operations ever", it would be more accurate to name it `--skip-git-commit-and-push`. I took a stab at splitting `lerna publish` into `lerna version && lerna publish` a couple months ago, but I haven't landed it yet.

**Comment by karliky** [comment]
I'm facing this situation too and would be great if an argument like this exists.
