### ISSUE TITLE
Lerna-wizard in readme

### ISSUE THREAD

**Issue by szarouski** [lerna/lerna#422]
Hi, would you be interested in mentioning https://github.com/szarouski/lerna-wizard in readme? If answer is positive, I can make a PR. Thank you.

**Comment by gigabo** [comment]
Whoa, that looks cool @szarouski!

Not sure where that would fit into the README. :thinking: 

Maybe see if you can find a natural place and make a PR?

**Comment by szarouski** [comment]
@gigabo updated readme. Please let me know what you think. Thank you.
