### ISSUE TITLE
Use symlinks with relative paths instead of absolute on non-windows environments

### ISSUE THREAD

**Issue by JaapRood** [lerna/lerna#423]
It seems that with [the great effort to make symlinks work on win32](https://github.com/lerna/lerna/pull/348) portability of a lerna repo has been reduced, as the use of "junction" to create a symlink requires [the use an absolute destination path](https://nodejs.org/api/fs.html#fs_fs_symlink_target_path_type_callback). What this means is that after running `lerna bootstrap` and then moving the project folder, all symlinks are invalid and no longer point to an existing directory.

Why care? When deploying a repo that uses Lerna to Heroku the app gets built in a temporary folder, to then be copied over to it's runtime destination. You *can* run `lerna bootstrap` before booting your server, however, this also means any other `prepublish` hooks will be triggered, causing much of the app to build again (as that's the main means of building node apps before they are deployed on Heroku).

**Comment by gigabo** [comment]
Hmm... thanks for reporting this @JaapRood.

So, it sounds like:

1. Windows _requires_ an absolute destination (for junctions)
1. Lerna is therefore _always_ using an absolute destination
1. This breaks heroku, which builds and then moves into place

Is that right?  Would a solution here be to only convert to absolute destinations on windows?  That would leave build/move broken on Windows, but it would at least allow build to work on windows and also allow build/move to work in other environments.

**Comment by gigabo** [comment]
Oh, I see that's exactly what you've suggested in the issue title. 😆 

That sounds great.  @JaapRood Are you interested in taking this on?

**Comment by JaapRood** [comment]
@gigabo that's exactly right. I don't have access to a windows machine with development environment, so I'll need help on that front, but I'll give it a go and see how far I get.
