### ISSUE TITLE
Unknown command "init"

### ISSUE THREAD

**Issue by yaycmyk** [lerna/lerna#428]
There a command `lerna init` in your documentation. However, it does not seem to be available in the most recent version on npm.

```
npm i -g lerna
lerna init           # Unknown command "init"
```

**Comment by hzoo** [comment]
This is since 2.x isn't on the `latest` dist tag so you are getting lerna 1.x, (we should probably get rid of beta)

```
npm install --global lerna@prerelease
```

**Comment by StarpTech** [comment]
I installed lerna 1.1.3 and get the same warning.

**Comment by hzoo** [comment]
@StarpTech right I didn't explain it well. Installing 1.x will give you the error b/c `lerna init` is only in 2.x so you'll need to install that https://github.com/lerna/lerna#getting-started
