### ISSUE TITLE
Added support for non-interactive shell

### ISSUE THREAD

**Issue by tiagojsalmeida** [lerna/lerna#429]
Hey guys!
Loving lerna so far but we are having problems using it in our CI.
`lerna publish` is a interactive script and we wonder if it was possible to just add a flag with the version instead of prompting it?

Thanks!

**Comment by gigabo** [comment]
Hi @tiagojsalmeida I think the [`--repo-version`](https://github.com/lerna/lerna#--repo-version) option may provide what you're looking for.

**Comment by tiagojsalmeida** [comment]
Perfect @gigabo ! Thanks!
