### ISSUE TITLE
[Feature] Lerna Import should tag when importing packages

### ISSUE THREAD

**Issue by mAAdhaTTah** [lerna/lerna#430]
I'm creating a new lerna repo, importing repositories w/ their packages. I'm now in the process of adding new packages, and the currently existing packages haven't changed since their last publish. However, `lerna publish` shows these as "changed" since the last publish, since there hasn't been a publish yet. Is there a way to tell lerna that these packages have already been published as they currently exist?

**Comment by mAAdhaTTah** [comment]
I'll also add that I have the packages versioned independently.

**Comment by gigabo** [comment]
Oh, good issue @mAAdhaTTah.

I think this should just be a matter of adding a `package@version` _tag_ to the git repo.

Maybe `import` could do that automatically? :thinking:

**Comment by mAAdhaTTah** [comment]
Yeah, that appears to resolve the issue. Updated the name to match the fix.

**Comment by gigabo** [comment]
Thanks for verifying.  Interested in adding automatic tagging to `import`? 😁

**Comment by mAAdhaTTah** [comment]
I am. I'll take a look at implementing if I get some time.

**Comment by joewoodhouse** [comment]
@gigabo @mAAdhaTTah still interested in this fix as I've hit the same issue. I'm a learner newbie - @gigabo could you describe exactly what the process of manually fixing this is? I'm (trying to) run an independently versioned set of packages.
