### ISSUE TITLE
Highlight private packages in updated/publish output

### ISSUE THREAD

**Issue by gigabo** [lerna/lerna#431]
@chrishelgert Added private package annotation to `ls` output in https://github.com/lerna/lerna/pull/427.

The `updated` command includes the `(private)` annotation, but without the red highlighting.

The `publish` command also includes private packages in its list of "changes", but it doesn't annotate them at all.

It would be nice to have consistent output across these three commands, with private packages highlighted in the same way in each.

**Comment by gigabo** [comment]
Oh, whoops, the `publish` portion of this was already covered in https://github.com/lerna/lerna/issues/337.

I'll close that since this is more complete.

**Comment by chrishelgert** [comment]
i can give it a try :simple_smile:

**Comment by gigabo** [comment]
This landed in [`lerna@2.0.0-beta.31`](https://github.com/lerna/lerna/releases/tag/v2.0.0-beta.31)! 🎉
