### ISSUE TITLE
lerna field in package.json is currently not used

### ISSUE THREAD

**Issue by tofuness** [lerna/lerna#433]
The `lerna` field in `package.json`, created by `lerna init`, is currently not used (I think).
I'd be happy to submit a PR if needed 😄

**Comment by gigabo** [comment]
Based on [previous discussion](https://github.com/lerna/lerna/issues/42#issuecomment-195545968) it looks like this was originally planned but may have just fallen through the cracks.

Thanks for resurrecting this @tofuness!
