### ISSUE TITLE
Lerna beta 31 seems to be broken

### ISSUE THREAD

**Issue by lukebatchelor** [lerna/lerna#445]
I'm still digging into the issue but after updating to beta.31 (from beta.29) I'm getting errors.

![](http://i.imgur.com/cN33Ik9.png)

At a guess I'm assuming it is to do with the configurable package locations change? I tried adding 

```
packages: ["packages/*"]
```

to our lerna.json to no avail.

I'll update this as I learn more

**Comment by gigabo** [comment]
Uh oh.  Thanks for reporting @lukebatchelor.

A few details that might help:

- What  command were you running when you hit this?
- Is the repo open on GitHub by any chance, so we could try to repro?

**Comment by lukebatchelor** [comment]
I'm actually not sure which command was running. I was running `git cz` so it's likely one of our validation scripts. Likely `lerna exec -- npm ls >/dev/null`.

Repo is on Bitbucket and recently made private temporarily unfortunately. :/

**Comment by gigabo** [comment]
Hmm... looks like it's originating from `lerna-cz-changelog`?

I wonder if that's using the `PackageManager` directly...

**Comment by lukebatchelor** [comment]
Oh, let me check

**Comment by lukebatchelor** [comment]
https://github.com/atlassian/cz-lerna-changelog/blob/master/src/index.js#L12

```
function getAllPackages () {
  const packagesLocation = new Repository().packagesLocation;
  return PackageUtilities.getPackages(packagesLocation);
}
```

**Comment by lukebatchelor** [comment]
Ah, so the problem is the signature of getPackages changed.

```
static getPackages(repository) {
```

from

```
static getPackages(packagesPath) {
```

So, false alarm the problem is in cz-lerna-chagelog, I'll get on that soon.

Thanks!

**Comment by gigabo** [comment]
Oh, yep.  Nice find.  That's not part of the public interface for Lerna.

The change is pretty straightforward, though:

```javascript
function getAllPackages () {
  return PackageUtilities.getPackages(new Repository);
}
```

Need to get https://github.com/lerna/lerna/issues/167 done!

Meanwhile... I think the fix here is in `cz-lerna-changelog`. 😬

**Comment by lukebatchelor** [comment]
Yep, we cant be mad when we are relying on things that aren't API ¯\_(ツ)_/¯
