### ISSUE TITLE
Show immediate log output of npm scripts

### ISSUE THREAD

**Issue by tofuness** [lerna/lerna#446]
Logs are currently *only* displayed after a successful command (like `lerna run test`). This means scripts like `test:watch` or `build:watch` won't work well.

@gigabo mentioned:
> The reason it all comes out at once at the end is to avoid having output from different packages interleaved.
> Might be nice to have an option to turn on immediate output, maybe with a prefix of package name so the interleaving isn’t so inscrutable?

Is this something worth exploring? I'd be happy to help.

**Comment by gigabo** [comment]
@tofuness Yeah, this seems like a useful option.  Want to take this on?

**Comment by seansfkelley** [comment]
This will also help prevent OOMing issues, if the tasks being run generate a large amount of output.

**Comment by tofuness** [comment]
Yes, I could try to implement this when I get back from vacation 👌

**Comment by Robinfr** [comment]
100% needed to be able to watch tests in all packages.

**Comment by Robinfr** [comment]
I checked out the code, and this should be easily implemented with a flag that makes it use `spawn` instead of `exec`.

**Comment by seansfkelley** [comment]
Unconditionally using spawn over exec can also fix https://github.com/lerna/lerna/issues/278 more permanently while simplifying the code. I'm not sure what benefit using exec has when you're already using spawn, so seems worth a shot?

How does this + watching interact with lerna-debug.log? Do you have to hold onto a copy of all the output in memory so you only dump to disk on failure? Seems like a great way to OOM the node process (which I already ran into in https://github.com/lerna/lerna/pull/372, where I worked around it by somewhat hackily truncating lengthy log lines).

**Comment by gigabo** [comment]
Good point about just using spawn and good question about `lerna-debug.log` @seansfkelley.

Could have `lerna-debug.log` keep a rolling tail of output, or could just disable collection for immediate output.  Seems easier and less side-effect-y to just disable for immediate output?  FWIW we worked around the issue you ran into in #372 in Asini by just [disabling collection during tests](https://github.com/asini/asini/pull/7).

**Comment by seansfkelley** [comment]
I OOMed the node process during #372 by turning up the logging -- some of those log lines are huuuuge. I opted for truncation as a consistent, albeit subpar solution. Turning it off during testing is probably just a good idea regardless, and undoing the truncating behavior would be a good call. 

Possible solution for lerna-debug.log: tail logs to a file in /tmp, then move the file into cwd on failure (and delete on success). 

FWIW, in the [tool I alluded to in this comment](https://github.com/lerna/lerna/issues/371#issuecomment-267680583) (which I have not yet extracted for others to see...), I just hold onto stderr/stdout for each child process and dump it once that child exits to prevent confusing interleaving. This should address the objective of this ticket without resulting in confusing output, though obviously does not work with watching.

**Comment by scottmas** [comment]
It seems to me that an easy solution would be to just repurpose a package like [concurrently](https://www.npmjs.com/package/concurrently)

**Comment by gigabo** [comment]
Opened https://github.com/lerna/lerna/pull/608 for this. 🍻

**Comment by Robinfr** [comment]
@gigabo so why in the end decide for an option over just always using spawn?

**Comment by evocateur** [comment]
@scottmas The biggest problem I can see with `concurrently` is that is has effectively no programmatic API whatsoever, which makes it a non-starter in my opinion. We can no doubt learn some lessons from the code, however.
