### ISSUE TITLE
Disable progress bar when not running interactively

### ISSUE THREAD

**Issue by gigabo** [lerna/lerna#447]
It looks weird in logs, CI output, etc.

It's currently disabled for _Lerna's_ tests, but not for tests that _use_ Lerna (e.g. `lerna run test` in a Lerna repo).

A simple check for `process.stdout.isTTY` might be enough?  Might want to encapsulate that somewhere in case it turns out not to be exactly right.

Born from https://github.com/lerna/lerna/pull/440#discussion_r92538279.

**Comment by taion** [comment]
This is the check in npm: https://github.com/npm/npm/blob/v4.0.5/lib/npm.js#L282

**Comment by taion** [comment]
char-spinner only checks `isTTY` though: https://github.com/isaacs/char-spinner/blob/v1.0.1/spin.js#L5-L10

**Comment by camwest** [comment]
Here is an example from my CI: https://circleci.com/gh/Autodesk/orion-ui/1027

<img width="803" alt="screenshot 2017-04-28 15 53 44" src="https://cloud.githubusercontent.com/assets/22905/25550052/e382512c-2c2a-11e7-9643-c84032a10657.png">

**Comment by evocateur** [comment]
hmm, guess we have to explicitly `disableProgress()` instead of assuming it will read it correctly...

**Comment by camwest** [comment]
@evocateur want me to submit a patch?

**Comment by evocateur** [comment]
That would be great!

**Comment by camwest** [comment]
@evocateur sorry I didn't get to this! I got too distracted, thanks for submitting it.
