### ISSUE TITLE
feature request: update dependencies

### ISSUE THREAD

**Issue by jeffwhelpley** [lerna/lerna#448]
There is a node command line tool called `npm-check` that does a really good job of finding where you need dependency updates and then interacts with the user to pick and choose which deps should be updated. It would be amazing to have this functionality with lerna. Since the tool requires interaction with the user, I am thinking that it would behave slightly different than `lerna run`. Instead of running the command in all packages at once, lerna would have to go to each package in sequence (i.e. once npm-check done with first package then move to the next).

**Comment by gigabo** [comment]
Yeah, this would be awesome!

**Comment by jeffwhelpley** [comment]
Not sure if this would be the same change or different, but I also have an issue with sequencing when doing things like `tsc`. In some cases, when you use `lerna run` to execute `tsc` on every package at the same time, it fails because they are all npm linked and one lib needs to have the other one finish its `tsc` before starting.

So, perhaps the feature would be twofold from a generic sense:

1. Sequencing commands to packages (based on order of dependency graph)
2. For each command allowing for a long running command like `npm-check -u`

**Comment by gigabo** [comment]
Good point @jeffwhelpley.

There's actually a PR in-flight for `lerna run` in dependency graph order: https://github.com/lerna/lerna/pull/412

That wouldn't help for _watching_, though, where all commands would be running at once.

That might be an argument in favor of a dedicated [watch command](https://github.com/lerna/lerna/pull/255) as suggested by @rygine.
