### ISSUE TITLE
Lerna 2.0.0-beta.31 tagged as latest

### ISSUE THREAD

**Issue by SimenB** [lerna/lerna#450]
This might be supposed to happen for all I know, but it seems weird `prerelease` is 30 while `latest` is 31.

```sh-session
$ npm dist-tag ls lerna
latest: 2.0.0-beta.31
prerelease: 2.0.0-beta.30
```

**Comment by hzoo** [comment]
Yeah I figured it was more confusing when people are looking at the 2.x readme when they install so I just made it latest

**Comment by SimenB** [comment]
Ah, ok! Make prerelease match?
Far away from it just being stable?

**Comment by hzoo** [comment]
I removed it from the readme so can just use latest now?

**Comment by SimenB** [comment]
Yeah, I do use latest. It just confused me for a second 😄
