### ISSUE TITLE
In independent versioning mode, --force-publish not work.

### ISSUE THREAD

**Issue by Alex-fun** [lerna/lerna#453]
Hi! 

I found, when in independent versioning mode,  run ``lerna publish --force-publish lerna-1``, it will still let me select a new version for other repos.

```bash
lerna git:(master) ✗ lerna publish --force-publish lerna-1            
Lerna v2.0.0-beta.30
Independent Versioning Mode
Checking for updated packages...
? Select a new version for lerna-1 (currently 1.0.2) Patch (1.0.3)
? Select a new version for lerna-2 (currently 0.0.4) (Use arrow keys)
❯ Patch (0.0.5) 
  Minor (0.1.0) 
  Major (1.0.0) 
  Custom 

```
Does Lerna not support ``--force-publish`` in independent versioning mode?

**Comment by gigabo** [comment]
Hi @Alex-fun the `--force-publish` flag is actually meant to cause a package to be published when it otherwise wouldn't (because it didn't have any changes).  It doesn't prevent _other_ packages from being published.

You may be able to use the `--scope` flag to get the behavior you're looking for:

```
lerna publish --scope lerna-1
```

**Comment by Alex-fun** [comment]
😢 Soga! It seems that I misunderstood, thank you for your reply!
