### ISSUE TITLE
Bootstrap fails when `console.error()` used in package

### ISSUE THREAD

**Issue by F1LT3R** [lerna/lerna#456]
I'm having great pains getting lerna to boostrap an existing project. It will not run `npm prepublish`, which runs `npm test`.

Here I my steps:

- `lerna init`
- `mkdir packages`
- `cp ~/repos/markserv-cli/ packages`
- `lerna bootstrap`

I'm getting the following error:

```
~/ms/markserv-lerna > lerna bootstrap
Lerna v2.0.0-beta.31
Bootstrapping 1 packages
Preinstalling packages
Installing external dependencies
Symlinking packages and binaries
Postinstalling packages
Prepublishing packages
NpmUtilities.execInDir        ("run prepublish", [], "./packages/markserv-cli")
Error: Command failed: npm run prepublish
Unhandled rejection AssertionError: expected 'No plugins loaded!: /Users/al/ms/markserv-lerna/packages/markserv-cli/test/specs/conf/empty-conf/Markconf.js.' to equal '\u001b[33mNo plugins loaded!\u001b[39m: \u001b[34m\u001b[4m/Users/al/ms/markserv-lerna/packages/markserv-cli/test/specs/conf/empty-conf/Markconf.js\u001b[24m\u001b[39m.'
    at require.catch.err (/Users/al/ms/markserv-lerna/packages/markserv-cli/test/specs/conf/empty-conf/empty-conf.spec.js:21:19)
    at tryCatcher (/Users/al/ms/markserv-lerna/packages/markserv-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/al/ms/markserv-lerna/packages/markserv-cli/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/al/ms/markserv-lerna/packages/markserv-cli/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/al/ms/markserv-lerna/packages/markserv-cli/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/al/ms/markserv-lerna/packages/markserv-cli/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Users/al/ms/markserv-lerna/packages/markserv-cli/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/al/ms/markserv-lerna/packages/markserv-cli/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/al/ms/markserv-lerna/packages/markserv-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
npm ERR! Test failed.  See above for more details.
```

So it is failing on a test that throws (and then catches) and exception.

- Tests run Ok on Travis.
-  Tests run Ok  in my lerna project (`cd packages/markserv-cli` and run `npm test`)

Is it possible that lerna automatically fails to bootstrap on ALL/EVERY exception(s)? 

If so, what should we do if are specifically testing for an exception?

**Comment by F1LT3R** [comment]
I can confirm when I remove the exception-test, lerna is able to bootstrap the project Ok.

**Comment by F1LT3R** [comment]
So I think lerna's process that is running `npm test` is listening for _all_ exceptions and failing out when encountering _any_. However, Travis is able to pass the build with this test, so perhaps lerna is missing a trick, or I have configured things incorrectly?

Here is the test if it helps to add context:

```javascript
const path = require('path');
const chai = require('chai');

const expect = chai.expect;

const argv = [null, null,
	// Use the Markconf file from this spec directory
	'-c', __dirname,
	// Turn off the logger
	'-l', 'OFF'
];

describe('empty Markconf', () => {
	it('should fail to initialize', done => {
		require('app/markserv')(argv)
		.catch(err => {
			// console.log(err);
			expect(err).to.be.a('string');
			const markconfPath = path.resolve(path.join(__dirname, 'Markconf.js'));
			const errorMsg = `\u001b[33mNo plugins loaded!\u001b[39m: \u001b[34m\u001b[4m${markconfPath}\u001b[24m\u001b[39m.`;
			expect(err).to.equal(errorMsg);
			done();
		});
	});
});
```

In the process of running this code, my logging output uses `console.error()` so users can trace the stack when things fail.

I specifically *want* to capture an error here, if possible.

Am I crazy here, it seems like Travis able to understand that a `console.error` is not a test failure, but lerna does not?

**Comment by gigabo** [comment]
Hi @F1LT3R, sorry you're running into confusing behavior here.

My guess is it's not actually the use of `console.error`, but rather that the process with the failed assertion exits with a non-zero exit code.  Since the tests are run as part of your `prepublish` script an exit code signaling failure indicates that the _prepublish_ failed.  A failed prepublish for any package means a failed bootstrap for Lerna!

If you want to run the tests but _ignore failures_ during bootstrap you might be able to set up your `package.json` with something like this:

```javascript
{
  "scripts": {
    "prepublish": "do-my-build && (npm test || true)",
    ...
  }
}
```

But, then again, if you're ignoring the results of your tests then why run them?

Your bootstrap would be faster without. 👹

**Comment by F1LT3R** [comment]
Good thoughts, I will try this.

**Comment by F1LT3R** [comment]
I guess my thoughts on "why run them?" .. are .. I want to run tests before every publish to NPM.

Does this change using lerna, or is there just a better way to check tests before publishing to npm?

**Comment by F1LT3R** [comment]
You were 100% correct btw @gigabo. :)  Wrapping npm test || true worked: `(npm test || true)`. I suppose Travis was never testing with `prepublish` anyway, so I think my questions were irrelevant. Closing. Thanks for the help.
