### ISSUE TITLE
FATAL "is in submodule" with lerna publish

### ISSUE THREAD

**Issue by F1LT3R** [lerna/lerna#457]
I bootstrapped packages, Ok.

Here is the structure:

```
packages
├── markserv-cli
├── markserv-contrib-app.github
├── markserv-contrib-inc.html
├── markserv-contrib-inc.less
├── markserv-contrib-inc.markdown
├── markserv-contrib-mod.dir
├── markserv-contrib-mod.file
├── markserv-contrib-mod.html
├── markserv-contrib-mod.http-404
├── markserv-contrib-mod.markdown
└── markserv-pages
```

Then I updated `markserv-cli/package.json`.

After this, I ran `lerna publish`.

I incremented all the versions by 1.

After selecting `yes`, lerna throws a _fatal_ like so:

```
GitUtilities.addFile          ("./packages/markserv-cli/package.json", 0, ["./packages/markserv-cli/package.json","/Users/myself/ms/mar...)
fatal: Pathspec '/Users/myself/ms/markserv-lerna/packages/markserv-cli/package.json' is in submodule 'packages/markserv-cli'
GitUtilities.addFile          ("./packages/markserv-cli/package.json", 0, ["./packages/markserv-cli/package.json","/Users/myself/ms/mar...)
Error: Command failed: git add /Users/myself/ms/markserv-lerna/packages/markserv-cli/package.json
fatal: Pathspec '/Users/myself/ms/markserv-lerna/packages/markserv-cli/package.json' is in submodule 'packages/markserv-cli'

    at checkExecSyncError (child_process.js:483:13)
    at Object.execSync (child_process.js:523:13)
    at Function.execSync (/usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js:76:40)
    at addFile (/usr/local/lib/node_modules/lerna/lib/GitUtilities.js:75:39)
    at descriptor.value (/usr/local/lib/node_modules/lerna/lib/logger.js:143:33)
    at Array.forEach (native)
    at PublishCommand.updateUpdatedPackages (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:353:22)
    at PublishCommand.execute (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:146:14)
    at PublishCommand._attempt (/usr/local/lib/node_modules/lerna/lib/Command.js:166:21)
    at /usr/local/lib/node_modules/lerna/lib/Command.js:151:15
Errored while running PublishCommand.execute
Error: Command failed: git add /Users/myself/ms/markserv-lerna/packages/markserv-cli/package.json
fatal: Pathspec '/Users/myself/ms/markserv-lerna/packages/markserv-cli/package.json' is in submodule 'packages/markserv-cli'

    at checkExecSyncError (child_process.js:483:13)
    at Object.execSync (child_process.js:523:13)
    at Function.execSync (/usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js:76:40)
    at addFile (/usr/local/lib/node_modules/lerna/lib/GitUtilities.js:75:39)
    at descriptor.value (/usr/local/lib/node_modules/lerna/lib/logger.js:143:33)
    at Array.forEach (native)
    at PublishCommand.updateUpdatedPackages (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:353:22)
    at PublishCommand.execute (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:146:14)
    at PublishCommand._attempt (/usr/local/lib/node_modules/lerna/lib/Command.js:166:21)
    at /usr/local/lib/node_modules/lerna/lib/Command.js:151:15
```

I'm confused as to what is going on here, and what I am meant to be doing. Any ideas?

**Comment by gigabo** [comment]
Hi @F1LT3R, looks like you may have `packages/markserv-cli` set up as a [git submodule](https://git-scm.com/docs/git-submodule)?

Lerna's `publish` command makes a git commit with the changes to the repo (version and dep updates) during publish.  You could try publishing with the `--skip-git` option.  That will leave the file changes as un-staged local modifications.

**Comment by F1LT3R** [comment]
When I copied the code from my other repo, to packages, the `.git` dir came with. I guess that makes it a submodule.

How will Lerna update and push the `markserv-cli` repo for me if it's not a submodule?

**Comment by F1LT3R** [comment]
All of them are submodules. That's the structure I'm using. I want each submodule to have it's own suite of tests and build on CI (Travis).

**Comment by gigabo** [comment]
That's a cool structure, but unfortunately it's not well supported by Lerna.

Lerna expects all of the packages to live in a single repository (a "monorepo").  It provides an "import" command for pulling packages in, preserving their git history.  It doesn't know how to deal with multiple repos aside from that.

**Comment by F1LT3R** [comment]
Got it. Thanks.

**Comment by netpoetica** [comment]
@gigabo Do you think Lerna will ever move toward supporting Git submodules? This would be a huge win for the monorepo argument, especially for people who are using Git. One of the first concerns I have is the merged git history for all of these packages (I am not alone on this). Git submodules would solve this problem and allow for faster clones, cleaner Git history.

**Comment by paralin** [comment]
I'm running into the same thing - I use submodules for the parts of my project.

The change should be minimal enough. Instead of making a commit and log for just the root repo, detect any submodules in the packages directory and do the bump/commit process on each of them separately, then finally do it on the root repo, using the package repo as the working dir for git.

**Comment by light24bulbs** [comment]
I sense a pull request coming. 

 It might be against the lerna "philosophy" to allow submodules, but when used without monorepo, lerna is still an extremely powerful package linking and versioning tool.

**Comment by askz** [comment]
We run into the same issue.
We have a monorepo, but 1 or 2 packages are in submodules for external gig developement purposes (we do not want to give them access to rest)

**Comment by yi-ge** [comment]
We also have the same problem, we want to use lerna with submodule. ☺

**Comment by bluelovers** [comment]
i know why my publish is fail now, lol

hope can support it

**Comment by MM263** [comment]
Also ran into this issue. We wanted to develop in one monorepo, but for gitlab-ci deployment purposes we wanted to store package code in submodule
