### ISSUE TITLE
lerna publish does update package.json but does not update npm-shrinkwrap

### ISSUE THREAD

**Issue by thomasfr** [lerna/lerna#463]
Hi,

lerna publish does update dependency versions in the corresponding package.json, but it does not update the versions in a npm-shrinkwrap file, which is very annoying because after publishing and pushing to git, one has to pull from origin and manually recreate the shrinkwraps and push again.

Is it possible that you also update all corresponding npm-shrinkwrap files if available? I think this would also be necessary for yarns Lockfile.

**Comment by gigabo** [comment]
Oh, interesting.  Should be possible.  Want to give it a shot? 😁

**Comment by thomasfr** [comment]
I took a quick look into the source - you do not use the official npm module programmatically, is there a reason for this (I never used it myself before, i just know that one could use it programmatically). 
Have you an idea how we can workaround that for the moment? One (half) solution would be to use fixed versions in `package.json` and remove the `npm-shrinkwrap.json` file.
Just fyi: `npm update -s` checks for new published versions and update the installed module in node_modules and also updates the npm-shrinkwrap file - so maybe there is a programmatically appropriate method.
