### ISSUE TITLE
logger.warning is not a function

### ISSUE THREAD

**Issue by doug-wade** [lerna/lerna#468]
Adding a new package to [clefs](https://github.com/doug-wade/clefs) with deps already installed by yarn and I get the following error:

```
/Users/dwade/foss/clefs/node_modules/lerna/lib/commands/BootstrapCommand.js:301
                  _this6.logger.warning(dependency + " is already installed for " + filteredPackage.name + ". " + "Replacing with symlink...");
                                ^

TypeError: _this6.logger.warning is not a function
    at /Users/dwade/foss/clefs/node_modules/lerna/lib/commands/BootstrapCommand.js:301:33
    at /Users/dwade/foss/clefs/node_modules/lerna/lib/commands/BootstrapCommand.js:325:15
    at Array.forEach (native)
    at /Users/dwade/foss/clefs/node_modules/lerna/lib/commands/BootstrapCommand.js:279:12
    at Array.forEach (native)
    at BootstrapCommand.symlinkPackages (/Users/dwade/foss/clefs/node_modules/lerna/lib/commands/BootstrapCommand.js:271:29)
    at /Users/dwade/foss/clefs/node_modules/lerna/lib/commands/BootstrapCommand.js:101:23
    at /Users/dwade/foss/clefs/node_modules/async/lib/async.js:718:13
    at Immediate.iterate (/Users/dwade/foss/clefs/node_modules/async/lib/async.js:262:13)
    at runCallback (timers.js:651:20)
```

Deleting node_modules fixes the problem

**Comment by gigabo** [comment]
Hi @doug-wade sorry you ran into trouble.  There's [a fix for this issue](https://github.com/lerna/lerna/pull/444) in master, but it hasn't been published yet. https://github.com/lerna/lerna/issues/451 has some suggestions for workarounds that should get you unblocked in the mean time.

**Comment by danielo515** [comment]
Deleting the node_modules folder is not an acceptable workaround.
This should be a hotfix and be released as soon as possible. I can't afford reinstalling all the dependencies each time that I generate a new module.

Regards

**Comment by doug-wade** [comment]
The fix _has_ been sitting on master for three weeks :thinking:

**Comment by doug-wade** [comment]
@danielo515 sorry for any confusion, I was agreeing with you.  I meant "there is a fix, and there has been for a long time, but its still not available.  Maybe its time to cut a release?

**Comment by danielo515** [comment]
> @danielo515 sorry for any confusion, I was agreeing with you. I meant "there is a fix, and there has been for a long time, but its still not available to end users. 

No problem! Thanks for clarifying. 

> Maybe its time to cut a release?

Agree. What's preventing that?

**Comment by hzoo** [comment]
Sorry, took a break from coding/OSS so haven't really been following anything here. Got informed of this by James and will make a release later when I get back from the airport or James has already. No reason in particular other than people were not available

**Comment by hzoo** [comment]
@thejameskyle published https://github.com/lerna/lerna/commit/d3be749e3e0a84bc002e8bc4b51419c97f9b9b81 a beta.32 so should be good

**Comment by doug-wade** [comment]
Thank you so much @thejameskyle @hzoo!  I really appreciate your quick response!  I see there was some madness with Travis; I really appreciate your pushing through.
