### ISSUE TITLE
Bootstrap fails if there are external dependencies at github

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#473]
Hello,

I have a couple of dependencies (just two) that are actually hosted at private github repos. The format is

```
"case-logger": "git+https://authstring@github.com/user/reponame.git#"
```

If I run lerna bootstrap it fails. It this a known reported bug?

**Comment by swashcap** [comment]
I’m seeing the same thing for [MRN-Code/coinstac](https://github.com/MRN-Code/coinstac), where [we depend on non-private repos](https://github.com/MRN-Code/coinstac/blob/1075b985d164a6023f6315902c3f5e36ab84fcba/packages/coinstac-common/package.json#L25-L35). Here’s the output:

```shell
$ node_modules/.bin/lerna bootstrap

Lerna v2.0.0-beta.32
Bootstrapping 8 packages
Preinstalling packages
Encountered a cycle in the dependency graph. This may cause instability!
Installing external dependencies
NpmUtilities.installInDir     ("./packages/coinstac-common", ["decentralized-single-shot-ridge-regression@github:mrn-code/decentral...)
Command failed: npm install decentralized-single-shot-ridge-regression@github:mrn-code/decentralized-single-shot-ridge-regression laplacian-noise-ridge-regression@github:mrn-code/decentralized-laplacian-ridge-regression#v3.1.0
Errored while running BootstrapCommand.execute
Command failed: npm install decentralized-single-shot-ridge-regression@github:mrn-code/decentralized-single-shot-ridge-regression laplacian-noise-ridge-regression@github:mrn-code/decentralized-laplacian-ridge-regression#v3.1.0
Waiting for 1 child process to exit. CTRL-C to exit immediately.
#...
```

**Comment by nruhe** [comment]
I believe this is also happening with dependencies of dependencies.

**Comment by casesandberg** [comment]
I took a quick look and it looks like the error might be here: https://github.com/lerna/lerna/blob/master/src/NpmUtilities.js#L41-L42

It looks like it tries to find a package version number via `splitVersion` and if it doesn't match the regex it returns `undefined` and falls back to '*' instead of the Github path.

**Comment by doug-wade** [comment]
@casesandberg hit the nail on the nose -- take a look at https://github.com/lerna/lerna/blob/master/src/NpmUtilities.js#L70

**Comment by doug-wade** [comment]
This was fixed in https://github.com/lerna/lerna/commit/e93970458d1bc75c4b14de5ec45b73a1fd985406; closing
