### ISSUE TITLE
How to prevent certain packages from being published

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#474]
Hello,

Sorry for this question, but I can't figure it out reading the documentation.
How can I skip certain set of packages from being published ? I can not use a glob pattern for all because they don't have anything in common in the name.

I tried using publishConfig:

```js
"publishConfig":{
      "ignore": [
          "module-directory/*"
      ]
  }
```

But it is not working. What I'm doing wrong?

**Comment by danielo515** [comment]
Well, what I have posted works for excluding the module at all. I only want to exclude it from the publish procedure, but I want to be able to detect changes, bump versions and all that stuff

**Comment by doug-wade** [comment]
I set packages I don't want published with ["private": true in package.json](https://github.com/doug-wade/clefs/blob/master/packages/integration-tests/package.json#L3) to exclude it from the publishing procedure.

**Comment by danielo515** [comment]
I have some packages as private too, and it is detected by lerna. Are they also excluded from version bumping and git tagging? Because I don't want to exclude them from that, just publishing. 

Regards

**Comment by danielo515** [comment]
Duplicated with #953
