### ISSUE TITLE
First publish: "No updated packages to publish."

### ISSUE THREAD

**Issue by garthk** [lerna/lerna#476]
The out-of-box-experience need more work, more documentation, or both.

Repro steps:

* Start with a poorly organised monorepo with six packages, none published, and no tags
* `git branch lerna-reorg`
* `git checkout lerna-reorg`
* `lerna init`
* Set `packages` in `lerna.json` to `["pkg/*"]`
* Set `version` in `lerna.json` to `"independent"`
* `git mv` each package into `pkg`
* Fix things up until `learna bootstrap` and `learna run build` succeed
* Prematurely gloat about the firepower of your fully armed and operational battle station
* `lerna updated`
* `lerna publish`

What I expected to happen:

* `lerna updated` warning me it had no idea whether anything had changed or not, and telling me how to `git tag` etc so it could figure it out
* `lerna publish` asking me what had changed, asking for new version numbers for those, and publishing them

What actually happened:

* `lerna updated` output `Checking for updated packages...` and three blank lines
* `lerna publish` crashed with `Errored while running PublishCommand.initialize` and `Error: No updated packages to publish.`

Wading through the [published list of open source users]() looking for one with independent versioning e.g. [`brittanica/brittanica`], it strikes me `lerna` might rely on previously set git tags of the form `${package}-${version}`. That said, `lerna updated` picked up I'd changed a different package after `lerna import`, so maybe there's something else going on. Please advise.

**Comment by noherczeg** [comment]
I'm trying to run publish as well, and got the same error.

I'm using the locked mode. I made a tag, pushed commits afterwards, yet I still get this error.

It might be that I'm dumb, the docs are somewhat Chinese to  me as they are phrased now. Could you please give us (or update the readme) examples how to do the very first publish?

**Comment by arekkas** [comment]
Same issue here on my end

**Comment by arekkas** [comment]
Apparently you need to publish all packages manually at first

**Comment by noherczeg** [comment]
@arekkas I'll try it out tonight, thanks!

**Comment by arekkas** [comment]
Hm, it worked locally but it doesn't on travis-ci: https://travis-ci.org/ory-am/editor/jobs/194554082#L1185-L1205

**Comment by rdamborsky** [comment]
Are your packages marked as private in their package.json files? That's been an issue for me. Took me long, but https://github.com/lerna/lerna/issues/570 finally helped me to move on.

**Comment by mojavelinux** [comment]
I agree, there's a chicken-egg problem here. Before you have your first tag, lerna is confused. And I have no idea what to set the version to before there's a version.

What I did figure out was to set the versions to 1.0.0-alpha.0, then pass the `--cd-version` flag:

```
--cd-version=1.0.0-alpha.1
```

This forced lerna to change the versions of all packages and publish. I have no idea what "cd" stands for, but it should be called `--first-version`.

**Comment by HorizonCoding** [comment]
> Apparently you need to publish all packages manually at first

I'm wondering that

**Comment by mojavelinux** [comment]
This is still a problem, though I suppose it could be solved with docs.

**Comment by kirill-konshin** [comment]
Got the same issue today.
