### ISSUE TITLE
Feature: use first packages entry for lerna import, not "packages/

### ISSUE THREAD

**Issue by garthk** [lerna/lerna#477]
Good beginner issue: if `lerna.json` contains `"packages": ["pkg/*"]`, `lerna import /path/to/pkgname` should offer to import to `pkg/pkgname`, not `packages/pkgname`.

In more detail:

* Look at the first entry in `packages` (default `[]`) for which `path.basename` returns `"*"`
* If there is no such entry, use `packages` as the prefix to `targetDir`
* Otherwise, use `path.dirname` of the entry as the prefix

While you're in there, fix #478 if it hasn't been fixed already.

**Comment by ericnkatz** [comment]
I love that you made this issue as a lay up for beginners and then made a PR with the fix later that day lol.

**Comment by garthk** [comment]
True, @ericnkatz, and I even stuffed up the lay-up: look how the PR went.

**Comment by ericnkatz** [comment]
You got this. ❤️
