### ISSUE TITLE
Use `path.join`, not string concatenation

### ISSUE THREAD

**Issue by garthk** [lerna/lerna#478]
Never do [this](https://github.com/lerna/lerna/blob/3a5cb2419fdaf8469c85aa2d0e5e4b73fe41f07d/src/commands/ImportCommand.js#L37):

```js
    this.targetDir = "packages/" + externalRepoBase;
```

**Comment by doug-wade** [comment]
Fixed in https://github.com/lerna/lerna/pull/480; closing
