### ISSUE TITLE
Rewrite README

### ISSUE THREAD

**Issue by thejameskyle** [lerna/lerna#48]
- `lerna-temp` tag
- support for `@org/packages`
- https://github.com/kittens/lerna/pull/44
- https://github.com/kittens/lerna/pull/36
- https://github.com/kittens/lerna/pull/45

- removed `stable` tag
- exposed api https://github.com/kittens/lerna/pull/75
- dev/canary release https://github.com/kittens/lerna/pull/65

**Comment by hzoo** [comment]
Doing in https://github.com/lerna/lerna/pull/132
