### ISSUE TITLE
Consider prefixing the commit messages for imports?

### ISSUE THREAD

**Issue by emirotin** [lerna/lerna#490]
The import functionality is a huge deal for me as I often combine several existing modules into a new monorepo.
The only problem I have is that it ends up intermixing the commit messages that no longer have proper meaning, like "update changelog" or "v4.0.0". Prefixing the messages with the package name would make it way cleaner.
Sometimes that may introduce conflicts with other tools relying on the commit message format so additionally it could be possible to allow a simple format string to be passed, like "[%p] %m"

**Comment by gigabo** [comment]
Good idea @emirotin!  Want to take it on? 😁

**Comment by emirotin** [comment]
Would love to if I find some time soon.

**Comment by emirotin** [comment]
BTW do you think this should be opt-in or opt-out?

**Comment by gigabo** [comment]
Preserving the original commit messages still seems like a good default to me, so I'd prefer opt-in personally.

**Comment by Ephem** [comment]
I just found myself missing this exact feature. I ended up using `git filter-branch` to rewrite all commit-messages before importing (only locally of course):

```
git filter-branch --msg-filter 'printf "[PREFIX_HERE] " && cat' -- --all
```

This is definitely a hassle though so it would be an awesome opt-in feature!
