### ISSUE TITLE
[Bug] `lerna run test` does not execute pretest/posttest if test script does not exist

### ISSUE THREAD

**Issue by julien-f** [lerna/lerna#491]
https://github.com/julien-f/issue-lerna-posttest

**Comment by simon360** [comment]
It looks like [this](https://github.com/lerna/lerna/blob/d1ec2e176507c7c088c4382fc5381623f04e8755/src/commands/RunCommand.js#L15-L16) is the cause.

Basically, lerna will only run scripts if they are defined in `package.json`; however, npm defines defaults for some scripts. `test` is one of those scripts - by default, it will `echo 'Error: no test specified'`, even if `test` isn't defined in `package.json` at all.

My first instinct is that lerna would need a whitelist of scripts that have default values - [this](https://docs.npmjs.com/misc/scripts) may be a place to start, although I'm not sure how complete it is. This also feels like a bit of a kludgy solution to me.

**Comment by evocateur** [comment]
It might even be as simple as testing for all three variants of the script (`pre{script}`, `{script}`, and `post{script}`), instead of just the script itself. No need for whitelisting, necessarily, since it's unlikely someone would expect a lifecycle that doesn't support pre/post to work.

```js
this.packagesWithScript = this.filteredPackages
  .filter((pkg) => pkg.scripts && (
    pkg.scripts[this.script] ||
    pkg.scripts[`pre${this.script}`] ||
    pkg.scripts[`post${this.script}`]
  ));
```

**Comment by simon360** [comment]
That would work, but would result in an error if a package defined a script named `prehelloworld`, left `helloworld` undefined, and then ran `lerna run helloworld`.

I'm not sure how important that case is, though. There's tooling out there that expects `pre{x}` scripts, like husky with `prepush` and `precommit`, but in those cases, you'd probably never define a `commit` script, or try to use `lerna run commit`.

**Comment by simon360** [comment]
Actually, based on [this](https://github.com/npm/npm/blob/5933720b71a7df45be9c46e1f7919d7c1aae3448/lib/run-script.js#L137-L148) from the npm source, only `test` and `env` would need to be covered (`env` is a bit of a weird one to have `pre` and `push` for, but who knows what people are into).

So maybe something like...
```js
if (this.script === "test" || this.script === "env") {
  this.packagesWithScript = this.filteredPackages;
} else {
  this.packagesWithScript = this.filteredPackages
    .filter((pkg) => pkg.scripts && pkg.scripts[this.script]);
}
```
would do the trick?

**Comment by julien-f** [comment]
Thanks! :)
