### ISSUE TITLE
[Bug] lerna publish: topologically sort packages

### ISSUE THREAD

**Issue by mxdubois** [lerna/lerna#492]
(As noted in a comment, this might relate to #342)

It seems like lerna does not publish interdependent packages in topological order (the order of dependencies in the dependency graph). I found this kind of surprising, so let me know if it's unexpected behavior that might be related to my setup.

In lerna.json, I have:
```
{
  "lerna": "2.0.0-beta.32",
  "version": "independent",
  "packages": [
    "packages/*"
  ]
}
```

In my directories, I have a package A (`packages/style`) and a package B (`packages/components-react`). Package A generates some files as part of its build step and package B imports some of those files. 

It seems, lerna attempts to publish all the packages in parallel? Or maybe in alphabetical order 
(though, hard-coding the the packages in-order in `lerna.json` also doesn't seem to afffect the ordering)? Whatever the order, the build for package B fails initially because it can't import a file from package A and then lerna recovers by retrying the failed publishes.

It seems like lerna should probably publish in topological order, by default. If that's difficult, I'd settle for a way to control ordering in `lerna.json`. What do you all think?

**Comment by seansfkelley** [comment]
This can probably be rolled into #412.

**Comment by frederickfogerty** [comment]
This can be closed
