### ISSUE TITLE
Is it any useful that Lerna version is hardcoded in lerna.json?

### ISSUE THREAD

**Issue by Reinmar** [lerna/lerna#506]
For me it only means more work when I'm updating Lerna. I have it harcoded now in a couple of places (e.g. in CI scripts which need to create `lerna.json` on the fly) and I don't see any profits from that.

I'd propose removing this validation or at least allowing to not define it or define it to a semver range.

**Comment by gigabo** [comment]
Yeah, @evocateur [relaxed the check in Asini](https://github.com/asini/asini/pull/58) and it was really nice.  Want to port that over here?

**Comment by Reinmar** [comment]
It's nothing critical for us, but we'll try to make PR in some spare time.
