### ISSUE TITLE
Add support for `exact` flag in lerna.json

### ISSUE THREAD

**Issue by gigabo** [lerna/lerna#511]
https://github.com/lerna/lerna/pull/426 added an `--exact` flag, but only on the command line.

It would be nice to allow durable configuration via `lerna.json`.  Should be a one-liner after https://github.com/lerna/lerna/pull/507 lands since that PR standardizes configuration and exposes a `.getOptions()` method on command objects.

Will need to update docs, though.  And tests would be nice. 😁

**Comment by dortzur** [comment]
I can try and take this on.

**Comment by gigabo** [comment]
Thanks @dortzur!

**Comment by gigabo** [comment]
@dortzur #507 has landed in master, so `this.getOptions()` is available in command objects! 🚀

**Comment by YasserKaddour** [comment]
@dortzur I hope you don't mind me doing it, Thanks
