### ISSUE TITLE
Is it supossed to Push git ?

### ISSUE THREAD

**Issue by MatthD** [lerna/lerna#512]
I do not understand if lerna is suposed to publish to git repo when "Lerna publish is used".

I know it publish module to npm, but it should be cool to auto-push to git repo at the same time.

**Comment by hzoo** [comment]
Yeah it does.

https://github.com/lerna/lerna#publish

> Create a new git commit and tag for the new version.

There's also the opposite option https://github.com/lerna/lerna#--skip-git

**Comment by MatthD** [comment]
I read that but it appears that it does not push anything to my github monorepo when I tried it.

It clearly increment packages versions & create a commit of it but it does not push anything to my github repository (I added it in package.json too ... ) 

I tried on this repo https://github.com/MatthD/sisyphe 

Command use & result (Id does not say anythign after "Yes"): 

![lerna](https://cloud.githubusercontent.com/assets/7901366/22200446/60a41dfa-e15f-11e6-9de7-c2ab9763bfdf.png)

**Comment by gigabo** [comment]
Discussion moved to https://github.com/lerna/lerna/issues/521.
