### ISSUE TITLE
publish using private registry argument

### ISSUE THREAD

**Issue by jogelin** [lerna/lerna#515]
I read many discussions about the possibility to publish to a private registry but is there a way to specify a private registry as an argument in the publish command ?

Using npm we can do `npm publish --registry http://my-private-registry`

I can use the publishConfig configuration in each package.json but it's a duplication which is something that I want to avoid by using lerna ;-)

Do you think it's a good idea to have : `lerna publish --registry=http://my-private-registry` ?

**Comment by rtsao** [comment]
You can do `npm_config_registry=https://my.npm.registry.org lerna <command>` for all commands.

**Comment by hzoo** [comment]
* [#599](https://github.com/lerna/lerna/pull/599) Explicit registry flag feature. ([@noherczeg](https://github.com/noherczeg))

```sh
$ lerna publish --registry https://my-private-registry
```
