### ISSUE TITLE
What does --canary do?

### ISSUE THREAD

**Issue by ForbesLindesay** [lerna/lerna#518]
The documentation says that it creates a canary release, but it never says what a canary release **is** in the context of lerna?

**Comment by ForbesLindesay** [comment]
Ah, there's lots of info in https://github.com/lerna/lerna that's not on the website.

**Comment by doug-wade** [comment]
It seems like your question was answer @ForbesLindesay, so I'm closing this in favor of https://github.com/lerna/website/issues/13, which would make this more discoverable.  Lemme know if I've misunderstood.
