### ISSUE TITLE
Lerna push to github repo

### ISSUE THREAD

**Issue by MatthD** [lerna/lerna#521]
I am sorry but I can't reopen my previous ticket on this ...

I read docs but it appears that it does not push anything to my github monorepo when I tried it.

It clearly increment packages versions & create a commit of it but it DOES NOT push anything to my github repository (I added it in package.json too ... ) 

I tried on this repo https://github.com/MatthD/sisyphe 

Command use & result (Id does not say anything after "Yes"): 

![lerna](https://cloud.githubusercontent.com/assets/7901366/22200446/60a41dfa-e15f-11e6-9de7-c2ab9763bfdf.png)

May i forgot something ?

**Comment by MatthD** [comment]
Ok, I understand what append,

https://github.com/lerna/lerna/blob/aeb775d1fec9988f9165cbfad82db2d4fb796c7b/src/commands/PublishCommand.js#L130

i was using --skip-npm (because I did not wanted to publish on npm & with this option it does not git push in fact)

**Comment by gigabo** [comment]
Thanks for reporting @MatthD.

Hmm... is this a bug?  Should `--skip-npm` push the commit and release tags?

**Comment by noherczeg** [comment]
I think that the `npm version` way should be used. [link](https://docs.npmjs.com/cli/version)

So if you want a release like you said you could do something like this:
```
"scripts": {
  "mypublish": "npm run lerna publish --yes --skip-npm",
  "postmypublish": "git push && git push --tags"
}
```

This way you could run `npm run mypublish`, and I assume you'd get what you wanted. If this is sufficient then the docs should be updated letting the users know about git as well.
