### ISSUE TITLE
Lerna publish: Is it possible to provide custom git commit message?

### ISSUE THREAD

**Issue by malonecj** [lerna/lerna#522]
Currently when we run ```lerna publish```, a new commit is pushed to Github with the message ```$(echo v2.0.0)```

like this
https://github.com/adazzle/react-data-grid/commit/8ea5916c7a0e76ebfba449e2961cdc7547ca4b4b

It would be nice if we could provide a custom git comment instead, so we can prevent our CI server from building for these type of commits via a [ci skip] command in git comment. Is this possible?

**Comment by gigabo** [comment]
Thanks for the suggestion @malonecj.  I think https://github.com/lerna/lerna/issues/395 should provide what you're looking for when it lands.  Please reopen if not.
