### ISSUE TITLE
Document that `lerna clean` supports the `--yes` flag

### ISSUE THREAD

**Issue by arekkas** [lerna/lerna#523]
`lerna clean` always asks for confirmation. Instead, it should support a `--yes` or `--force` flag

**Comment by arekkas** [comment]
workaround for sh/bash: `echo 'y' | lerna clean`

doesn't work on windows obviously

**Comment by gigabo** [comment]
Good idea @arekkas!  Fortunately `lerna clean` actually _does_ support a `--yes` flag.

I guess [the docs](https://github.com/lerna/lerna#clean) just need to be updated to reflect that.

**Comment by arekkas** [comment]
Awesome! :)
