### ISSUE TITLE
Fails on npm publish leaves the repository on a inconsistent state

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#524]
Hello,

When you do lerna publish, several good things happens: 

- Version is bumped on modified packages
- Github tags are added and committed
- Packages are published to npm

If this last step fails, then you are not able to republish the packages you were trying to publish. If you run lerna publish again, it raises an error about `no packages has changed`. You have to go to each package manually and run npm publish.

Is there any better approach?
Regards

**Comment by noherczeg** [comment]
https://github.com/lerna/lerna#--force-publish-packages ?

**Comment by danielo515** [comment]
Never noticed there is such option. How should I deduct that I have to add a dash `-` before the packages? I though the `[packages]` was part of the command?

I'll check it out

**Comment by danielo515** [comment]
Dear @noherczeg , because your short answer was so short and misleading I understood it the wrong way. Now I see that what you posted is just the url. 

To answer your question (is it a question?) No, the force publish does not fixes the situation. I don't want to type manually all the packages that have changed, and if I just use `*` I am forced to bump all packages, which is not good.

This same situation happens if the git publish fails. It is not easy to recover from those errors

**Comment by blahah** [comment]
I've faced the same issue several times. The problems are that after a failed `npm publish`:

1. lerna doesn't handle the errors properly, they all just get logged in a very verbose way and lerna exits
2. you're left with a publish commit and a set of tags that haven't been pushed to git, but which prevent lerna from progressing with a publish

Ideally, lerna would delete the publish commit and all the tags, allowing the publish step to be run again.

However, in the meantime you can use this:

```bash
# delete the latest commit
git reset --hard HEAD~1
# delete the latest batch of tags
git tag -d $(git log --date-order --tags --simplify-by-decoration --pretty=format:'%d' | head -1 | tr -d '()' | sed 's/,* tag://g')
```

**Comment by danielo515** [comment]
Many thanks @blahah
I'll agree with all you said.
I'll try your suggestion on the next problem I will presumably get

**Comment by tomccabe** [comment]
Also having this issue. Most annoying is that my packages are blown away into `.backup` files and left as such on an error, so I'll have to go through every package and copy the backup into a `package.json` and delete the backup.

There really needs to be more graceful handling of errors and rolling back of changes as this is really (one of) the major feature of Lerna.

**Comment by noherczeg** [comment]
@danielo515 I didn't wanted to be misleading, just wanted to help. Sorry that my suggestion didn't help :disappointed:

**Comment by danielo515** [comment]
@noherczeg I have re-read my answer and it was not very polite. I take for granted that every answer has good intention. It was my fault to answer you so impolitely, and I'm sorry about it. Please accept my apologies.

**Comment by evocateur** [comment]
We definitely have room for improvement when it comes to recovering from failed publishing.

**Comment by noherczeg** [comment]
I might tackle this in the weekend. I'm expecting that the recovery of the original `package.json` file should be easiest part.  Not sure about the reverting. We'll see.

**Comment by danielo515** [comment]
For those who are facing this situation where publish or git fails and the dependencies gets out of sync, I have created a small set of scripts to check that every package is using the correct version within the monorepo. Then a small report is shown:

 - case-notify-db-saver@0.4.0
 - case-notify-push@0.2.1
lerna success publish finished

~/GIT/case-alert
➞  npm run check-local-deps                                                                                                                                                                                                                                    [git:feature/notification] ✔ [ruby-2.3.0]

> case-alert@1.0.0 check-local-deps /Users/danielo/GIT/case-alert
> node bin/check_local_deps.js

```
{
    "case-alerts-notifications-service": {
        "deps": [
            {
                "found": "0.2.6",
                "expected": "0.2.9",
                "name": "case-alerts-db-connect"
            },
            {
                "found": "0.3.1",
                "expected": "0.3.4",
                "name": "case-alerts-notifications-fetcher"
            },
            {
                "found": "0.3.0",
                "expected": "0.6.0",
                "name": "case-alerts-notifications-formatter"
            },
            {
                "found": "0.1.3",
                "expected": "0.4.0",
                "name": "case-notify-db-saver"
            }
        ],
        "devDeps": []
    },
    "case-alerts-input-service": {
        "deps": [],
        "devDeps": [
            {
                "found": "^0.7.2",
                "expected": "0.10.0",
                "name": "case-alerts-test-utils"
            }
        ]
    }
}
```


Here are the scripts

> get_packages.js

```
'use strict';

const Fs = require('fs');
const ReadDir = Fs.readdirSync;
const Stat = Fs.statSync;

const getAllPackageNames = (basePath = __dirname) => {

    return ReadDir(basePath)
        .map((d) => `${basePath}/${d}`)
        .filter((d) => Stat(d).isDirectory())
        .map((d) => ReadDir(d).filter((i) => (/package\.json/i).test(i)).map((x) => `${d}/${x}`))
        .reduce((all, p) => p.concat(all), []);

};

module.exports.getAllPackages = (dir) => getAllPackageNames(dir).map(require);
module.exports.getVersions = (dir) => getAllPackageNames(dir).map((p) => ({ [require(p).name]: require(p).version }));
```

> check_local_deps.js

```
#!/usr/bin/env node

'use strict';
const Packages = require('./get_packages');
const Path = require('path');

const pkgDir = Path.join(__dirname, '../', 'src');
const packages = Packages.getAllPackages(pkgDir);

const actualVersions = Packages
    .getVersions(pkgDir)
    .reduce((final, ver) => {

        const key = Object.keys(ver)[0];
        final[key] = ver[key];
        return final;
    }, {});

const findMismatch = (toCheck, truth) => {

    const keys = Object.keys(toCheck);
    return keys.map((k) => {

        if (!truth.hasOwnProperty(k) || (toCheck[k].replace(/[\^~]/, '') === truth[k])) {
            return null;
        }

        return { found: toCheck[k], expected: truth[k], name: k };
    })
        .filter((i) => i);
};

const checkDeps = (report, pkg) => {

    const deps = pkg.dependencies ? findMismatch(pkg.dependencies, actualVersions) : [];
    const devDeps = pkg.devDependencies ? findMismatch(pkg.devDependencies, actualVersions) : [];

    if (deps.length > 0 || devDeps.length > 0) {
        report[pkg.name] = {
            deps,
            devDeps
        };
    }

    return report;
};

const missMatchReport = packages.reduce(checkDeps, {});
console.log(JSON.stringify(missMatchReport, null, 4));
```

Hope this helps, and hope some kind of functionality like this is included in lerna

**Comment by kevinbarabash** [comment]
What's a good way to recover if `lerna` has pushed tags already to GitHub?

**Comment by evocateur** [comment]
`lerna publish from-git` will restart the publish if the previous execution pushed upstream successfully but then failed during the upload to the registry. YMMV.

**Comment by danielo515** [comment]
Sorry, it may be myself but I don't get exactly what does that mean evocateur
