### ISSUE TITLE
Lerna should publish in dependency order

### ISSUE THREAD

**Issue by gigabo** [lerna/lerna#526]
Publishing dependents before their dependencies can lead to npm errors that get cached.

https://github.com/babel/babel/issues/5170#issuecomment-274638873

I think the groundwork laid down by @seansfkelley here should make this easy: https://github.com/lerna/lerna/pull/412

**Comment by doug-wade** [comment]
I took a crack at this last night for a couple of hours.  While the work done by @seansfkelley does get us pretty far, the changes to the tests are pretty extensive, so be forewarned.

**Comment by doug-wade** [comment]
Also, I'm p sure this is a dupe of https://github.com/lerna/lerna/issues/492

**Comment by gigabo** [comment]
Yep, nice catch.  Merging into #492.
