### ISSUE TITLE
Lerna and React (Singleton module) - Is that anyway to sort this out?

### ISSUE THREAD

**Issue by danilosterrapid7** [lerna/lerna#529]
I have 2 packages that are consuming each other, both has your own react lib in its own node_modules folder. The problem is that resolving modules is going to the closest parent within package.json file and try to find for node_modules. If package.json and node_modules exists, then, the module loaded is related to this path.

e.g.

PROJECT_LERNA
- packages
-- A
--- package.json
--- node_modules
---- react
---- B
----- package.json
----- node_modules
------ react
-- B
--- package.json
--- node_modules
---- react

B is being consumed by A and during the compilation both react libs are imported.

Rather than create a symlink within node_modules, could it not create a normal folder creating nested symlinks to the files/directories in my package apart from the node_modules?

**Comment by sgwilym** [comment]
Was bitten by this for a while too. If you're using webpack to build your bundle, the resolution is to alias the packages you don't want more than one copy of.  In your webpack config:


```js
resolve: {
  alias: {
    'react': path.resolve('./node_modules/react'),
    'react-dom': path.resolve('./node_modules/react-dom'),
    'react-relay': path.resolve('./node_modules/react-relay'),
  },
},
```

**Comment by gigabo** [comment]
For React Server we use automatic hoisting (as provided by https://github.com/lerna/lerna/pull/507) to pull React to the root of the repo.

**Comment by danilosterrapid7** [comment]
Thanks guys! @gigabo , @sgwilym 
Just to let you guys know. We are getting from root... 
Our prepublish script triggers build;
Our prebuild delete all the nested react instances from the sub node_modules folder and, then,
at the webpack config we set the modulesDirectories to point to the current project node_modules folder and the parent node_modules folder;

Anyway, I will check out your alternatives! Thanks again!

**Comment by evocateur** [comment]
I would consider this fixed by the `--hoist` option. @danilosterrapid7 do you agree?

**Comment by danilosterrapid7** [comment]
@evocateur I will try it...

**Comment by veeramarni** [comment]
We have encountered this issue with webpack when one of the peerDependency is also a `package` under `packages` folder. I don't think `--hoist` work in this case as we don't find the working package in main `node_modules`.  

in the package.json file
```
  "devDependencies": {
  .....
     "@pkg/core": "*"
   }
    "peerDependencies": {
    "@pkg/core": "*"
  },
```
In our webpack configuration, we set libraryTarget to `umd`

```
.....
    target: 'node',
    output: {
        filename: libPath("[name].js"),
        library: "@pkg/jsonschemas",
        libraryTarget: "umd"
    },
....
    externals: [nodeExternals(), {
        '@pkg/core': {
            commonjs: "@pkg/core",
            commonjs2: "@pkg/core",
            amd: "@pkg/core",
            root: "@pkg/core"
        }
    }]
```
In `@pkg/core` we have this class which suppose to work as singleton
```
export namespace MySingleton {
  interface IMySingleton {
      doSomething(): void;
  }
  class MySingleton implements IMySingleton {
      private usePrivate() { }
      doSomething() {
          this.usePrivate();
      }
  }
  export var Instance: IMySingleton = new MySingleton();
}
```
In Typescript tsconfig, we set module to `commonjs` [to avoid module_not_found issue.](http://stackoverflow.com/questions/38392697/webpack-umd-critical-dependency-cannot-be-statically-extracted) 
```
  "compilerOptions": {
    "module": "commonjs",
    "rootDir": "./src",
    "outDir": "./lib",
    "baseUrl": ".",
    "paths": {
       "@pkg/core": ["../core"]
    }
```

When we run a test in `@pkg/config` which depends on `@pkg/jsonschemas` and `@pkg/core`, there are two instances of singleton class from two location of `@pkg/config` which causing errors in our tests.

**Comment by danielo515** [comment]
I want to know if this issue was also about peerDependencies. I found that peer dependencies are not being properly handled, resulting in weird errors (like instanceof not working properly)

**Comment by veeramarni** [comment]
it is been a while, wondering if anyone has an workaround for this issue other than deleted nested `node_modules`

**Comment by rumax** [comment]
Only `--hoist` and `--nohoist`, but it doesn't help too much

**Comment by veeramarni** [comment]
I was able to find a workaround for it. I use `--hoist` and use `webpack` for build which resolve modules to `node_modules` and for testing, I use jest which I need to place `moduleResolver` to `node_modules`. That way they don't look for nested `node_modules` for module resolution.

**Comment by evocateur** [comment]
I consider the original issue solved. If the peerDependencies problem still exists, please open a separate issue with a repro.
