### ISSUE TITLE
Packages bootstrapped with lerna are not being copied using electron-packager

### ISSUE THREAD

**Issue by samb90** [lerna/lerna#539]
I am using lerna to package modules inside an electron app.

I use electron-packager https://github.com/electron-userland/electron-packager to build a .app file on Mac OSx.

The packages bootstrapped with lerna do not appear inside my .app because they are symlinked.

**Comment by walleXD** [comment]
@samb90 Did you figure out how to fix this?

**Comment by evocateur** [comment]
Lerna is not a module bundler (like webpack or rollup), it just coordinates npm package development between related modules.
