### ISSUE TITLE
Remove usage of object-assign package

### ISSUE THREAD

**Issue by hzoo** [lerna/lerna#544]
Since we have dropped node 0.10/0.12 we can just use the native Object.assign now.

- [ ] remove from package.json
- [ ] remove import statements and use `Object.assign` instead.

**Comment by wtgtybhertgeghgtwtg** [comment]
I'll take it if nobody else wants it.
For the record, `object-assign` will still be in the dependency tree, at least until `meow` updates.

**Comment by thejameskyle** [comment]
object-assigned-sorted was bumped
