### ISSUE TITLE
lerna publish - fatal: ref HEAD is not a symbolic ref

### ISSUE THREAD

**Issue by palmerabollo** [lerna/lerna#545]
I get this error (`fatal: ref HEAD is not a symbolic ref`) when I try to run `lerna publish` and I don't know why. I'm using lerna v2.0.0-beta.34 in fixed mode.

```
> lerna publish --force-publish='*' --repo-version "1.3.0" --yes -m "chore: publish"

Lerna v2.0.0-beta.34
Current version: 1.306.0
Checking for updated packages...

... this detects all the packages ok

Publishing packages to npm...
Pushing tags to git...

fatal: ref HEAD is not a symbolic ref
GitUtilities.getCurrentBranch ()
Error: Command failed: git symbolic-ref --short HEAD
fatal: ref HEAD is not a symbolic ref

    at checkExecSyncError (child_process.js:483:13)
    at Object.execSync (child_process.js:523:13)
    at Function.execSync (.../node_modules/lerna/lib/ChildProcessUtilities.js:76:40)
    at getCurrentBranch (.../node_modules/lerna/lib/GitUtilities.js:142:46)
    at Function.descriptor.value (.../node_modules/lerna/lib/logger.js:143:33)
    at pushWithTags (.../node_modules/lerna/lib/GitUtilities.js:111:90)
    at Function.descriptor.value (.../node_modules/lerna/lib/logger.js:143:33)
    at .../node_modules/lerna/lib/commands/PublishCommand.js:192:36
    at .../node_modules/lerna/lib/commands/PublishCommand.js:514:9
    at .../node_modules/async/lib/async.js:726:13
```

When I run `git symbolic-ref --short HEAD` in the command line, it returns `master`.

**Comment by evocateur** [comment]
Can you post the contents of (or link to a gist of) the `lerna-debug.log` file, please?

(it should have been written in the repo root when the error happened)

**Comment by palmerabollo** [comment]
Thanks, I think I found the issue. I had the master branch protected against force-pushes in github. Sorry.

**Comment by theinterned** [comment]
I am curious @palmerabollo - what did you do as a work around? I have github branch protection setup on `master` and my current release flow is to 

1. Go into the github settings and uncheck the **"Include administrators"** checkbox. 
2. run learn publish on the master branch. 
3. Re-uncheck the **"Include administrators"** checkbox. 

This works and keeps the master branch safe but it is not very graceful. I wonder if there is another workflow that people are using?

**Comment by palmerabollo** [comment]
@theinterned That's what I did. I didn't find a better solution and I'm not using lerna in my current project so I don't know if there is a better workaround currently.
