### ISSUE TITLE
[Feature] Check npm login and registry before publishing

### ISSUE THREAD

**Issue by jamiebuilds** [lerna/lerna#55]
If you aren't logged in to npm, lerna should stop and ask you to login. It would be good if it logged you back out afterwards.

**Comment by kittens** [comment]
If you're doing this for security then it's pointless.

**Comment by thejameskyle** [comment]
I have to switch between npm profiles for different (public and private) registries

**Comment by thejameskyle** [comment]
I'm going to just do a check at the beginning to make sure that you're logged in to the right registry.

```
$ npm whoami
$ npm config get registry
```

Logging in is overkill, but I think the more checks we can do at the beginning is good.
