### ISSUE TITLE
npm install --global lerna@^2.0.0-beta is not working

### ISSUE THREAD

**Issue by bboysathish** [lerna/lerna#550]
The Command provided on the website is not working

`npm install --global lerna@^2.0.0-beta`

Reference:
![image](https://cloud.githubusercontent.com/assets/8023447/22425686/54ac20b0-e722-11e6-8577-ebaedfb9ff16.png)

**Comment by spudly** [comment]
I think what you want is this:

`npm install --global lerna@^2.0.0-beta.34`

**Comment by bboysathish** [comment]
@spudly i tried it works. The issue is in the website `npm install --global lerna@^2.0.0-beta`, people tend to copy paste it :)

**Comment by spudly** [comment]
@bboysathish,

You're right. I've submitted a pull request to fix the website: lerna/website#11

**Comment by bboysathish** [comment]
Great @spudly
