### ISSUE TITLE
Making Lerna work with Sinopia

### ISSUE THREAD

**Issue by bboysathish** [lerna/lerna#556]
I presume there is no official support for lerna to work with tools like sinopia. But as per @doug-wade [comment](https://github.com/lerna/lerna/issues/536#issuecomment-275984463). Some of the team are using lerna with sinopia. Can someone help me troubleshoot this issue?

Steps:

1. I have installed lerna version `lerna@^2.0.0-beta.34`.
2. I have installed sinopia and it is running in `http://localhost:4873/`.
3. I have changed the npm registry to point sinopia
![1_lerna](https://cloud.githubusercontent.com/assets/8023447/22454399/934b995c-e7ab-11e6-9ea6-e1c05822f2cc.png)
4. After `lerna init`
![2_lerna](https://cloud.githubusercontent.com/assets/8023447/22454419/b97802dc-e7ab-11e6-997a-6c11b914d4c5.png)
5. After `lerna publish --skip-git`
![4_lerna](https://cloud.githubusercontent.com/assets/8023447/22454436/d2f36986-e7ab-11e6-9d06-e4dad543a9e5.png)
6. Sinopia Server log
![3_lerna_sinopia_log](https://cloud.githubusercontent.com/assets/8023447/22454442/de5a2774-e7ab-11e6-9929-676ec513d8ec.png)
7. lerna says it has published the packages, But when hit the registry url in browser it not shown there
![5_lerna](https://cloud.githubusercontent.com/assets/8023447/22454466/03108be4-e7ac-11e6-9f78-4d4f5f99fa29.png)
8. Sinopia server log while fetching packages
![6_lerna](https://cloud.githubusercontent.com/assets/8023447/22454472/1165daaa-e7ac-11e6-8eb6-e06b966eeee1.png)

But without using lerna, if I publish a package manually by using `npm publish` it works. Moreover, after the first manually publishing, `lerna publish --skip-git` works by updating the existing packages.

Note: I don't know this is lerna issue or any configuration issue or sinopia issue. 

Have I done it correctly?

**Comment by doug-wade** [comment]
@bboysathish yeah, my ui doesn't seem to update locally either 

<img width="1169" alt="screen shot 2017-01-31 at 1 21 55 am" src="https://cloud.githubusercontent.com/assets/3477707/22459023/ce5ebd1a-e753-11e6-99eb-efd57d28afc1.png">

but they install just fine, which is the important part

<img width="1097" alt="screen shot 2017-01-31 at 1 24 31 am" src="https://cloud.githubusercontent.com/assets/3477707/22459091/13db7400-e754-11e6-9022-a9138adf7e97.png">

My [verdaccio](https://github.com/verdaccio/verdaccio) instance, on the other hand, updates the ui immediately:

<img width="1157" alt="screen shot 2017-01-31 at 1 31 51 am" src="https://cloud.githubusercontent.com/assets/3477707/22459374/2f77fe44-e755-11e6-8704-93713a5c7670.png">

If running verdaccio in place of sinopia works for your use case, it seems to be more actively maintained and more stable.

**Comment by bboysathish** [comment]
@doug-wade Then it should be sinopia issue. Right ? May I know about the warning that sinopia throws `package **sk-util-http** does not have **"latest"** tag ?`

**Comment by doug-wade** [comment]
@bboysathish you'll have to file that against sinopia.
