### ISSUE TITLE
Need a more explanative error message for scoped `run` command

### ISSUE THREAD

**Issue by emirotin** [lerna/lerna#564]
I had a run command scoped to a specific package X return `No packages found that match X`.
The actual issue was that I forgot to define the corresponding script for the package X.
The better error would be `No packages found that match X and have the script S`.
I know that the error comes from the low-level generic util and it may be a bit tricky to override, but I've spent maybe 15 minutes before I noticed the actual problem.

**Comment by noherczeg** [comment]
Strange since the code actually seems to have the proper message:

https://github.com/lerna/lerna/blob/master/src/commands/RunCommand.js#L19

Which version are you using?

**Comment by emirotin** [comment]
It looks like the filtering message happens to hit earlier. First the generic `Command` constructor filters the packages which already throws an error. So the child RunCommand check never runs.

I'm using beta.30 and I think the result will be the same with beta.36
