### ISSUE TITLE
force publish for prereleased packages

### ISSUE THREAD

**Issue by spudly** [lerna/lerna#567]
My packages have to go through a QA process before published versions are deployed to production, so I create prerelease versions which are used during the QA process (for example, 1.1.0-rc.0, 1.1.0-rc.1. 1.1.0-rc.2, etc.). When I am satisfied that version is bug-free, I want to publish it with a non-prerelease version before deployment to production. When lerna publishes the packages, I want each prereleased package to be updated to the same non-prerelease version. Unfortunately, lerna only looks at the changes between tags, so lerna thinks there is nothing to update and doesn't update the package versions.

It'd be nice if there was a `--force-publish-prereleased` flag so that I could force all prerelease versions to be bumped to non-prereleased versions.

For example, assuming I had this setup and there were no changes since the last release:
```
lerna.json: 1.0.0-rc.1
├── pkg-a@1.0.0
├── pkg-b@1.0.1-rc.1
├── pkg-c@1.0.1-rc.0
├── pkg-d@1.0.0
```

I would expect it to bump the versions as follows:
```
lerna.json: 1.0.1 <-- updated
├── pkg-a@1.0.0 <-- not updated
├── pkg-b@1.0.1 <-- updated
├── pkg-c@1.0.1 <-- updated
├── pkg-d@1.0.0 <-- not updated
```

Right now I can workaround by using `--force-publish` but that republishes lots of packages unnecessarily, so it's not ideal.

I should also note that I'm publishing from a CI server (jenkins) so my TTY is not interactive; I can't selectively choose versions for each package. I'm publishing using `lerna publish --repo-version $VERSION --yes`

I'm willing to work on a pull request if you can give me some assurance that a feature like this would be accepted. Also, I'm not married to `--force-publish-prereleased` so feel free to bikeshed all you want.

**Comment by evocateur** [comment]
I too will soon enter the brave new world of auto-publishing from Jenkins, so I am sympathetic to this request. #607 is close to ready, but it doesn't completely cover your case here (since you don't want to increment _all_ versions by a given semver keyword).

It sounds like we need a flag similar to `--scope` (although ugh the name) that is also complementary to `--cd-version`....

**Comment by cif** [comment]
I'd suggest simply supporting more --cd-version values a la https://github.com/sindresorhus/np#usage

e.g. `lerna publish --yes --cd-version=prerelease`

**Comment by spudly** [comment]
Perhaps named scope groups?

For example,
```bash
lerna publish --scope-groups=updated,prereleased,my-custom-group
```

Some of these scope groups would have to be pre-defined (like updated and prereleased). The default value would be 'updated' (current behavior). Maybe users could also define custom groups using globs in their lerna.json file:

```json
{
  "scope-groups": {
    "react-components": "@my-scope/react-component-*"
  }
}
```

We'd probably also have to add a corresponding `--force-publish-groups` option or, better yet, change `--force-publish` to respect `--scope` and `--scope-groups`).

Either of the following would solve my use case:
```bash
// if we add --force-publish-groups
lerna publish --repo-version $VERSION --yes --force-publish-groups=prereleased

// if we update --force-publish to respect --scope and --scope-groups
lerna publish --repo-version $VERSION --yes --force-publish --scope-groups=prereleased
```

**Comment by spudly** [comment]
@cif, I agree. Your PR is more about what the resulting version numbers are, whereas mine is more about which packages are updated.
