### ISSUE TITLE
[Question] Lerna is trying to install a local package from NPM, what am i doing wrong?

### ISSUE THREAD

**Issue by Bnaya** [lerna/lerna#572]
I'm converting an existing project to use lerna

My lerna ls looks line that:
```
Lerna v2.0.0-beta.36
- extension (private)
- companyname-parser (private)
- companyname-log (private)
```
But when i run `lerna bootstrap` i get:
```
...
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/companyname-parser
npm ERR! 404 
npm ERR! 404  'companyname-parser' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```
Means lerna is trying to install it from npm instead of linking it

**Comment by doug-wade** [comment]
This can happen if the current version of the dependee in your repository doesn't fulfill the version range listed in the dependent. (e.g. if `a` has a dependency on `b ^1.0.0`, but `b` lists its version as `2.0.1`, then lerna will install it from npm).  Can you include the version of `companyname-parser` and the version name of whatever package is emitting the error?  The other thing that I can think of is that npm checks the registry for a lot of commands that you might not think it would check the registry for (e.g. `npm link`).  Can you post the full npm-debug.log?

**Comment by Bnaya** [comment]
Thank you!
I've changed my version requirement to "*" (from "") and it works
I also had other issue with the order of the prepublish of packages being called,
but it was because seems that lerna doesn't look on `peerDependencies`, so i've added it also under `dependencies` (or should it be under 'devDependencies')?

**Comment by doug-wade** [comment]
I think you might be confused about what peerDependencies are -- peerDependencies are no longer installed (since npm 3); they simply indicate packages that a dependent must _also_ install.  As such, no, Lerna does not, and will not, install peerDependencies.

**Comment by Bnaya** [comment]
I needed lerna to look on the `peerDependencies` so it will calculate the order of running the prepublish, not for installing.
My case is as follows:
```
package A
- deps: ['B', 'C']
package B
- peerDeps: ['C']
package C
``

And lerna run the pre-publish of `C` and `B` in parallel, even that `B` is dependent on  `C` (yes, peer dep, but for correctness it should have first prepublish `C` then `B` then `A`)


Adding `C` as peerDep and dep of `B` solved it, i need to keep the peerDep to hint that i want `A` and `B` will have access to the same actual library

**Comment by evocateur** [comment]
In my understanding, a peer dependency is only ever relevant to the runtime `dependencies` of a package, not build-time. When expressing a peer dependency, you generally also add it as a dev dependency so you can run tests and whatnot, since otherwise `npm` does not install it.

For the case you demonstrated, I would _strongly_ recommend that you either remove the ordering dependency (and the peer), or make `C` a direct dependency of `B`. Abusing `peerDependencies` like this is a recipe for pain, trust me.

(If `B` is often used standalone and for some reason you don't want consumers to also download `C`, then a dev dependency is appropriate)

**Comment by Bnaya** [comment]
Its relevant for build time because it contains d.ts files

**Comment by evocateur** [comment]
Definitely a dev dependency, then.

**Comment by Bnaya** [comment]
So as i see it, its a devDependency *and* peerDependency
Becouse i need my package to share the exact  same module instance (even when bundled when webpack, which requires additional setup)

**Comment by evocateur** [comment]
That makes sense. Peer + dev dep is a very common pattern for this use case.

**Comment by rtm** [comment]
This occurred to me when the version field for the dependency was of the form `v1.5.0-alpha1` or `v1.5.0-alpha.1`. When I changed the version to `1.5.0` all was well.

**Comment by evocateur** [comment]
Ooh, then that means our method of identifying "matching" local versions is having difficulty with prerelease semver tags (it looks for the same name with a semver.satisfies() version range). So that's quite likely a big part of this bug.

**Comment by rtm** [comment]
@evocateur FYI this happened when the dependency was given as `"*"`. In other words, `"*"` does not seem to match `v1.5.0-alpha1`.

**Comment by evocateur** [comment]
Interesting. I imagine that would need to be a special case in our comparison method.

**Comment by pascal1990** [comment]
@evocateur  Please I have this issue 

> web3@1.0.0-beta.27 postinstall C:\node\wiz\submodules\oracles-web3-1.0
> lerna bootstrap

lerna info version 2.8.0
lerna info Bootstrapping 20 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm install
lerna ERR! npm ERR! Error while executing:
lerna ERR! npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
lerna ERR! npm ERR!
lerna ERR! npm ERR! fatal: unable to connect to github.com:
lerna ERR! npm ERR! github.com[0: 192.30.255.112]: errno=No such file or directory
lerna ERR! npm ERR! github.com[1: 192.30.255.113]: errno=No such file or directory
lerna ERR! npm ERR!
lerna ERR! npm ERR!
lerna ERR! npm ERR! exited with error code: 128
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     C:\Users\c-fossoup\AppData\Roaming\npm-cache\_logs\2018-01-22T13_08_22_019Z-debug.log
lerna ERR!
lerna ERR!     at Promise.all.then.arr (C:\node\wiz\submodules\oracles-web3-1.0\node_modules\execa\index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: npm install
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR!
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.255.112]: errno=No such file or directory
npm ERR! github.com[1: 192.30.255.113]: errno=No such file or directory
npm ERR!
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\c-fossoup\AppData\Roaming\npm-cache\_logs\2018-01-22T13_08_22_019Z-debug.log

    at Promise.all.then.arr (C:\node\wiz\submodules\oracles-web3-1.0\node_modules\execa\index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'npm ERR! Error while executing:\nnpm ERR! C:\\Program Files\\Git\\mingw64\\bin\\git.EXE ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git\nnpm ERR! \nnpm ERR! fatal: unable to connect to github.com:\nnpm ERR! github.com[0: 192.30.255.112]: errno=No such file or directory\nnpm ERR! github.com[1: 192.30.255.113]: errno=No such file or directory\nnpm ERR! \nnpm ERR! \nnpm ERR! exited with error code: 128\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     C:\\Users\\c-fossoup\\AppData\\Roaming\\npm-cache\\_logs\\2018-01-22T13_08_22_019Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm install',
  timedOut: false,
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web3@1.0.0-beta.27 postinstall: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web3@1.0.0-beta.27 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\c-fossoup\AppData\Roaming\npm-cache\_logs\2018-01-22T13_08_22_175Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ico_wizard@0.2.0 installWeb3: `cd submodules/oracles-web3-1.0 && npm install && cd ../../ && npm install submodules/oracles-web3-1.0/packages/web3`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ico_wizard@0.2.0 installWeb3 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\c-fossoup\AppData\Roaming\npm-cache\_logs\2018-01-22T13_08_22_223Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ico_wizard@0.2.0 startWin: `npm run installWeb3 && npm run generateFlatSoliditySafeMathLibContractWin && npm run generateFlatSolidityCrowdsaleNullFinalizeAgentContractWin && npm run generateFlatSolidityCrowdsaleFinalizeAgentContractWin && npm run generateFlatSolidityCrowdsaleContractWin && npm run generateFlatSolidityCrowdsaleTokenContractWin && npm run generateFlatSolidityCrowdsalePricingStrategyContractWin && npm run compileSafeMathLibExtContractWin && npm run compileCrowdsaleNullFinalizeAgentContractWin && npm run compileCrowdsaleFinalizeAgentContractWin && npm run compileCrowdsaleContractWin && npm run compileCrowdsaleTokenContractWin && npm run compileCrowdsalePricingStrategyContractWin && node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ico_wizard@0.2.0 startWin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\c-fossoup\AppData\Roaming\npm-cache\_logs\2018-01-22T13_08_22_238Z-debug.log


could you help me

**Comment by evocateur** [comment]
@pascal1990: Don’t use git dependencies. (Yours is not a lerna error, it’s an npm problem)

**Comment by curran** [comment]
FWIW I resolved this issue by deleting `package-lock.json` in the offending package. No idea why that worked.
