### ISSUE TITLE
_this6.logger.warning is not a function on bootstrap

### ISSUE THREAD

**Issue by cif** [lerna/lerna#573]
I can work around this by finding the installed module that should be symlinked and removing manually, but thought it was worth noting that `lerna bootstrap` command throws the following error if you have a module installed from npm:
```
/usr/local/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:301
                  _this6.logger.warning(dependency + " is already installed for " + filteredPackage.name + ". " + "Replacing with symlink...");
                                ^

TypeError: _this6.logger.warning is not a function
    at /usr/local/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:301:33
    at /usr/local/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:325:15
    at Array.forEach (native)
    at /usr/local/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:279:12
    at Array.forEach (native)
    at BootstrapCommand.symlinkPackages (/usr/local/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:271:29)
    at /usr/local/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:101:23
    at /usr/local/lib/node_modules/lerna/node_modules/async/lib/async.js:718:13
    at iterate (/usr/local/lib/node_modules/lerna/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/lerna/node_modules/async/lib/async.js:274:29
```

Running Lerna v2.0.0-beta.31, Independent Versioning Mode

**Comment by doug-wade** [comment]
While your particular error has [already been fixed](https://github.com/lerna/lerna/blob/6e9bf137ce439ee0fdf72e0264e073b724f49b67/src/Package.js#L101), we do actually have a rogue [logger.warning running](https://github.com/lerna/lerna/blob/6e9bf137ce439ee0fdf72e0264e073b724f49b67/src/Package.js#L101) around.

**Comment by evocateur** [comment]
D'oh, I missed that because it wasn't using an instance property (`this.logger.warning()`)

**Comment by evocateur** [comment]
Or, rather, it was added in a recent PR.
