### ISSUE TITLE
When creating a new package, support npm "@scope" prefix in package name

### ISSUE THREAD

**Issue by evocateur** [lerna/lerna#577]
This is related to #485, addressing an issue for folks (like myself) who use an npm [scope](https://docs.npmjs.com/misc/scope) to point packages at an internal registry (and letting unscoped packages default to the public registry).

In a nut, I would like the ability to create a new package _without_ the `@my-scope` prefix in the dirname, and certainly not nested (as a name of `@my-scope/foo` would seem to imply). In the initial implementation of `lerna create`, there is no such support for this.

Greenfield example:
```bash
lerna create new-package --scope my-scope
# ./packages/new-package/package.json created
# package name === "@my-scope/new-package"
```

Conveniently, `npm init` has a [`--scope`](https://docs.npmjs.com/cli/init#scope) flag available for just this purpose. However, we've already yoinked `--scope` for passing a whitelist glob for packages to affect with a given command. 😿

So, would it be too confusing to use `--scope` for the create command in the manner of `npm init`?

(Could `lerna create` simply use `npm init` internally? 💥)

**Comment by vyorkin** [comment]
hi, maybe I've missed smth, but I can't see any `lerna create` in `2.1.2` (latest version of lerna)

**Comment by evocateur** [comment]
Yeah, the create sub command doesn't exist yet. Probably will need to be reimplemented, given code drift since the original PR.
