### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by gruberjl** [lerna/lerna#580]
Is `lerna publish` suppose to run the following:

* `git add .`
* `git commit -m ''`
* `git push origin master`

It seems to be running `git push origin master` but not the other two for me. Is that correct?

Assuming I'm making a `patch` change with only one `git commit`.

Should I use the following workflow:

```
git add .
git commit -m 'updated ...'
lerna publish
```

**Comment by hzoo** [comment]
Yea I don't think we would want lerna to do a `git add .` or commit for you? You would make all your changes and then run publish

**Comment by gruberjl** [comment]
Perfect thanks. Lerna's simplicity + power is quite impressive. I appreciate all your hard work. Thank you so much for your help. Have a good one.

**Comment by hzoo** [comment]
Thanks 😄 , we also have a slack if you want to join: https://slack.lernajs.io/
