### ISSUE TITLE
v2.0.0 milestone

### ISSUE THREAD

**Issue by bjankord** [lerna/lerna#583]
I noticed this project has a fair amount of beta releases. Is there a milestone to track progress to v2.0.0 release? Is the v2.0.0 release close-ish?

**Comment by doug-wade** [comment]
I've created the milestone; let's keep this issue until we feel relatively confident that the milestone has all the issues attached to it that need to be in the v2 release.

**Comment by evocateur** [comment]
I forgot to close this when I actually published v2.0.0 🍔
