### ISSUE TITLE
`lerna diff` throws an exception on success

### ISSUE THREAD

**Issue by fistachos** [lerna/lerna#585]
When spawned process succeeds, ChildProcessUtilities will call callback with _null_ as first arg (https://github.com/lerna/lerna/blob/master/src/ChildProcessUtilities.js#L63), which causes DiffCommand to fail: https://github.com/lerna/lerna/blob/master/src/commands/DiffCommand.js#L39 (as `null !== 0`).

Probably `if(code)` will be enough.

**Comment by evocateur** [comment]
That is a rather disturbing oversight in our test cases, thanks!

`if (code)` looks like the ticket, as that is pattern used elsewhere (including some callbacks that _depend_ on the "success" being `null`, as they are conventional Node "errbacks" (`callback(null, result)` to indicate succcess).
