### ISSUE TITLE
Possibility to pass additional flags to `npm publish`

### ISSUE THREAD

**Issue by sullenor** [lerna/lerna#590]
I faced with this issue when I wanted to make an initial publish of the scoped package.

According to the [npm](https://docs.npmjs.com/cli/access#details) docs I have to use `npm publish --access=public` command in that case. So I wonder if there is any possibility to pass additional flags to npm with `lerna publish` command?

**Comment by doug-wade** [comment]
I thought you could pass extra arguments to `npm` after a `--` switch, e.g. `lerna publish -- --access=publish`, but looking through the code, it doesn't seem like that's the case.  It does seem like something we should support (using a scope seems like a great way to group lerna packages).  It does look like as a workaround, you can use `npm access public` after the fact, so I'm labeling this an enhancement.

**Comment by sullenor** [comment]
@doug-wade I think a `--` switch is a good and well known solution. As far as I know [minimist](https://github.com/substack/minimist#var-argv--parseargsargs-opts) supports it and [meow](https://github.com/sindresorhus/meow), which is used in lerna, uses minimist to parse the arguments.

If you require any help, let me know. Thanks.

**Comment by ef4** [comment]
> It does look like as a workaround, you can use npm access public after the fact, so I'm labeling this an enhancement.

This workaround only works if you're on a paid npm account. If you're not, attempting to publish the new private package fails, and leaves your `lerna publish` in a half-finished state.

**Comment by evocateur** [comment]
Add a `publishConfig` block to the package.json of the scoped package you wish publish publicly:
```json
{
  "publishConfig": {
    "access": "public"
  }
}
```

**Comment by Bamieh** [comment]
this would also solve #1137
