### ISSUE TITLE
lerna bootstrap prune hoisting takes a very, very long time from scratch

### ISSUE THREAD

**Issue by garthk** [lerna/lerna#602]
`lerna bootstrap` with `hoist: true` on `2.2.0-beta.37` waits for feels like an unusually long time while displaying `Prune hoisted`. There's no network activity. I haven't yet checked for CPU burn or I/O.

This is not #582, because it's not a *hang*, strictly — it does eventually finish — and because that was "fixed" in 37.

**Comment by gigabo** [comment]
Hi @garthk sorry you're running into trouble.  Does this delay happen every time you run `lerna bootstrap`, or just the first time?  Are you able to link to the repo where you're seeing this behavior?

**Comment by garthk** [comment]
It's every time I run `lerna bootstrap` after nuking all of the `node_modules` folders, both at the monorepo's top level and under the `packages` directory. No, I'm afraid I can't link to the repository.

**Comment by garthk** [comment]
I see @spudly thumbed up; same symptoms? Can link to repo?

**Comment by spudly** [comment]
Nah, actually my issue went away. It went slow once or twice but that's all. Just enabled hosting yesterday and it is awesome btw. Good job!

**Comment by kylecordes** [comment]
What really happens, behind the scenes? Are all of the dependencies installed for every package, then later deleted in this prune process? That would suggest `--hoist` doesn't deliver the install time improvement hoped for?

**Comment by evocateur** [comment]
A big complicated (well-commented) algorithm that collects all the dependencies for the entire tree and does a best-effort identification of the "most common version" for each dep and installs those _first_ in the root, then loops through the rest of the dependencies and installs anything remaining (if anything, usually conflicting versions of hoisted dependencies) and then does the binary re-linking (if any).

The interesting parts start [here](https://github.com/lerna/lerna/blob/master/src/commands/BootstrapCommand.js#L261)

**Comment by kylecordes** [comment]
@evocateur Thank you, yes, that code is nicely commented and structured!

I'm trying to understand the following scenario:

* Freshly cleaned - all node_modules at all levels deleted.
* Using NPM
* bootstrap --hoist
* Comment says "// Remove any hoisted dependencies that may have previously been installed in package directories"
* During the installation there is a **long** time with "Prune hoisted" displayed.

This seems contradictory - as a fresh install, there should be no previously installed packages to prune. This is what makes me suspect that during `bootstrap --hoist` they are being installed then pruned.

If you'd like to see it this firsthand, here is my example project, "hoist" branch:

https://github.com/OasisDigital/many-to-many-angular/tree/hoist

```./build.sh```

**Comment by evocateur** [comment]
Indeed, you would expect a clean bootstrap with `--hoist` to be especially speedy.

**Comment by aga5tya** [comment]
Pruning all modules before hoist prevents me from trying to cache node_modules,, usually to skip npm spending time to re-install from scratch when my dependencies are not changed very frequently. Any other ways to get around to cache when intended to ?

**Comment by evocateur** [comment]
I would clean first, install in root, and then bootstrap.

`lerna clean --yes && npm i && lerna bootstrap --hoist`

**Comment by aga5tya** [comment]
@evocateur: Not sure if i am clear, but the suggested commands do a clean install. 

My need is to not re-install from scratch again as clean. Since my dependencies are intact, need to  ideally to avoid pruning and instead reuse already installed ones. 

This opens up possibilities to where i can use a separate docker image containing only node_modules alone and reuse it whenever needed (more like an offline/cached bootstrap).

**Comment by evocateur** [comment]
You're trying to cache `./packages/*/node_modules` (the target of hoisting) _in addition_ to `./node_modules` (the source of hoisting)? I'm afraid I don't understand the issue you're having, as the root `./node_modules` should stay stable throughout the hoisting process, and that _should_ be all you need with fully-hoisted `./packages/*/node_modules` (in which the pruning phase is basically a no-op).

**Comment by aga5tya** [comment]
@evocateur , Now i understand the pruning logic, my bad. 

I feel there should be an option to extract the temporary package.json created that has all the hoisted(computed) dependencies. Right now afaik the following happen:
1. Backs up original package.json
2. Create a new package.json(temporarily) that has new computed dependencies. npm install this.
3. Replace the backed up package.json.

Shouldn't there be an option where if a flag/config is passed, this temporary file can be extracted out before step 3 happens.

**Comment by evocateur** [comment]
For now, I manually hoist everything, and shrinkwrap the root as well. It's clearly not optimal for large numbers of package dependencies, however.

I need to experiment with npm5's new monorepo-oriented capabilities; between it and yarn workspaces, we might be able to delegate all of this brittle logic to the package manager proper.
