### ISSUE TITLE
Bootstrap: "Command exited with status 228: npm install"

### ISSUE THREAD

**Issue by k3n** [lerna/lerna#606]
Greetings,

Everything works as expected locally, but in CI, I am getting these errors and am having a hard time deducing the actual source. Interestingly, it has worked a few times, but more often than not, it fails with the following:

```
Lerna v2.0.0-beta.37
Bootstrapping 6 packages
Preinstalling packages
Installing external dependencies
NpmUtilities.installInDir     ("./packages/ken-package-1", ["lodash@^3.10.1","babel-preset-es2015@^6.1.18","chai@^3.4.1","mocha@^2....)
Command exited with status 228: npm install
Errored while running BootstrapCommand.execute
Command exited with status 228: npm install
Waiting for 3 child processes to exit. CTRL-C to exit immediately.
NpmUtilities.installInDir     ("./packages/ken-package-2", ["joi@^6.10.0","lodash@^3.10.1","babel-preset-es2015@^6.1.18","brocc...)
Command exited with status 228: npm install

npm ERR! Linux 3.18.25-18.el7.x86_64
npm ERR! argv "/usr/local/node-v4.4.7-linux-x64/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! ken-monorepo@2.3.4 postinstall: `./node_modules/lerna/bin/lerna.js bootstrap`
npm ERR! Exit status 1
```

Any ideas? I've been searching through issues here and can't find any references to it.

Failing machine is CentOS 7.2.1511, Node 4.4.7.

**Comment by k3n** [comment]
Follow-up: is there any way to increase the log level?

**Comment by gigabo** [comment]
@k3n Yep, you can use the `--loglevel` option.

Lerna also write _all_ logs to a file on failure, so depending on your CI setup you may be able to `cat` that on failure.  For example in Travis you could do something like:

```yaml
after_failure:
  - cat lerna-debug.log
```

**Comment by k3n** [comment]
@gigabo Thanks! Unfortunately, it's Jenkins, but hopefully I can do something similar there.

At current, I believe this is a resource (memory) issue, but that may change as I keep looking into it. I'll update once I learn more.

**Comment by k3n** [comment]
Does appear that this was a memory issue on the Docker host. Closing.
