### ISSUE TITLE
add `list` command for testing flag combinations/piping to other scripts

### ISSUE THREAD

**Issue by seansfkelley** [lerna/lerna#610]
In large monorepos with many packages and their many names, it can be useful to test what your `--scope`, `--ignore` and `--include-filtered-dependencies` are about to do without having to run-oops-ctrl-c to get that feedback. You can also use it to feed to other scripts (with dependencies and in topologically-sorted order, both of which are quite handy)!

(This was a feature I added in [Yerna](https://github.com/palantir/yerna) that I found quite useful; I'm filing this issue for discussion purposes. Feel free to close if it's not a behavior you want in Lerna.)

**Comment by hzoo** [comment]
anything that gives more info like a dryrun type command sounds good to me

**Comment by hzoo** [comment]
offtopic: I know you mentioned you were frustrated at how things were going with Lerna earlier but I believe things are picking up again so would love to have your contributions (I'd like to work less on Lerna myself), thanks for the issue too!

**Comment by seansfkelley** [comment]
Yeah, "dry run" is also a good way to think about it.

I just finished filing a couple tickets with the features I found most valuable in Yerna that Lerna was lacking (it doubled as an experimenting ground for some features I really wanted). I have noticed the pace of development picking up! I'm happy to see that, but unfortunately I don't have the bandwidth to contribute more than these discussion tickets/reference implementations, which I do sincerely hope are useful!

**Comment by evocateur** [comment]
@seansfkelley [This](https://github.com/palantir/yerna/blob/master/bin/yerna#L100) is the command in `yerna` you're talking about, correct?

**Comment by seansfkelley** [comment]
Yeah, exactly.

**Comment by mnasyrov** [comment]
It would be great to add an option to list absolute (or relative) paths of packages for using with external scripts/pipes.

**Comment by evocateur** [comment]
`lerna ls` gained a whole bunch of [new options](https://github.com/lerna/lerna/blob/master/commands/list/README.md#options) in v3, mimicking most of was `npm ls` provides. It also respects all the filtering options, including `--since`. Would that be sufficient to consider this issue closed?

**Comment by seansfkelley** [comment]
Looks like!
