### ISSUE TITLE
add `--include-filtered-dependents`

### ISSUE THREAD

**Issue by seansfkelley** [lerna/lerna#611]
As a counterpart to `--include-filtered-dependencies`, the proposed `--include-filtered-dependents` flag would include dependents of the selected packages. My use-case for this option is for build/test systems: when I change a package, I need to rebuild its dependencies (so the package itself can be built) but also its dependents (so I know if the package broke anything downstream). (This is of particular import in Typescript repos, where many of these types of issues can be caught at build time.)

The application order of package-selection flags, with each step taking the set of packages output from the previous step, should be:

1. `scope` (all packages, if absent)
2. `ignore` (nop, if absent)
3. `include-filtered-dependents` (nop, if absent)
4. `include-filtered-dependencies` (nop, if absent)

Like the current behavior, this may include explicitly-excluded packages from `ignore`. Note, in particular, that dependents are added before dependencies; this has to be done to adhere to the contract of `--include-filtered-dependencies`, namely, "all selected packages' dependencies are also selected" (which would not hold if the order were reversed).\* [Here's a reference implementation of this behavior](https://github.com/palantir/yerna/blob/master/lib/filtering.js#L42).

\* Strictly speaking, you should have to continue adding dependents and dependencies until you reach a stable state, but the way that `--dependents` is used is generally such that you only want dependents of your "first generation" packages, i.e., not any inferred additions. Hence the simplification and therefore the ordering constraint. You could even get away without doing dependencies-of-dependents, but as I originally wrote this feature in the context of Typescript, that was prone to erroneous breakage if those dependencies were out of date.

(This was a feature I added in [Yerna](https://github.com/palantir/yerna) that I found quite useful; I'm filing this issue for discussion purposes. Feel free to close if it's not a behavior you want in Lerna.)

**Comment by evocateur** [comment]
I like this idea. How difficult would it be to implement in `lerna`?

**Comment by chrisui** [comment]
I've came across this as a real need for our use case. This would really help optimise tests/builds (any ci really) and is probably more useful than the inverse `--include-filtered-dependencies` a lot of the time.

If someone could advise on where to start in the lerna codebase I could take a crack at this?

**Comment by seansfkelley** [comment]
`--include-filtered-dependencies` does it in [`Command.js`](https://github.com/lerna/lerna/blob/36a6501fcd5856e8b6291b71fa251c53aa939a33/src/Command.js#L274..L276), which you should be able to as well.

**Comment by stramel** [comment]
I believe this can be closed? @evocateur
