### ISSUE TITLE
run / exec scripts in parallel

### ISSUE THREAD

**Issue by cyberthom** [lerna/lerna#619]
Are there plans to add the ability to run npm or shell scripts in parallel to `lerna run` and `lerna exec` commands?

I am thinking something along the lines of a `--parallel` flag:

```
lerna run --parallel watch
lerna exec --parallel babel src --out-dir lib --watch
```

I appreciate there's a `--concurrency` option but that doesn't seem to enforce parallel script execution. 

The main use case for this is having the ability to add watch steps, which don't exit without being killed, and be able to run them for all packages simultaneously:

* packages/module1/package.json:
  ```
  {
    scripts: {
      "watch": "babel src --out-dir lib --watch"
    }
  }
  ```

* packages/module2/package.json:
  ```
  {
    scripts: {
      "watch": "babel src --out-dir lib --watch"
    }
  }
  ```

* package.json:
  ```
  {
    scripts: {
      "watch": "lerna run --parallel watch"
    }
  }
  ```

An alternative would be to allow using the `--concurrency` option as a flag which, if used without a number, triggers parallel execution of all scripts.

**Comment by gigabo** [comment]
Hi @cyberthom scripts are actually run in parallel in separate child processes (with concurrency governed by the `--concurrency` option), but their output is captured and emitted only when child processes complete.

I think https://github.com/lerna/lerna/pull/608 may provide what you're looking for, which is immediate _output_ from child processes.

**Comment by douglasduteil** [comment]
Can be closed now that `--stream` is merged ?

**Comment by cyberthom** [comment]
Yes, `--stream` in combination with `--concurrency` will do the job!

**Comment by noherczeg** [comment]
@evocateur This could be added to the FAQ docs right?

**Comment by evocateur** [comment]
Yes, seems reasonable.

**Comment by loopmode** [comment]
Is `--stream` and `--concurrency` the way to go when the number of packages increases?
I have 14 packages currently, and I'm using "watch": "lerna run watch --concurrency 20 --stream"``.

I wonder if the mechanism will scale well. Otherwise, I'd need to think about a custom solution (for example a script using nodemon to watch all packages at once)

**Comment by evocateur** [comment]
--parallel is generally more appropriate for watch tasks, though I would recommend running the watcher from the root in most cases.

**Comment by loopmode** [comment]
@evocateur I would appreciate if you could elaborate on running the watcher from the root. 

I was under the impression I'd need something like nodemon, and in case of a change/update, I'd have to figure out which package contains the file that was changed, then run the build script of that package in probably a new process. And I supposed I'd have to code this manually - it's not much, but still..

Maybe lerna already has everything it takes, and I just don't see it? (I'm fairly new to lerna)

**Comment by evocateur** [comment]
Tools like jest already run very well from the root over any number of packages scattered across a monorepo. Tools like [`pectin`](https://github.com/evocateur/pectin) are designed to run Babel-based Rollup builds with conventional configuration across an entire tree, with watching support built-in.

Lerna is not designed to watch your code for you. That is the job of other tools.
