### ISSUE TITLE
lerna on subdirectory

### ISSUE THREAD

**Issue by FezVrasta** [lerna/lerna#622]
I'm trying to initialize a lerna project inside a subdirectory of a repository, in my case I have a big monorepo, and inside it, I have a folder where I want to use lerna (without affecting the rest of the repository).

When I run `lerna init` it initializes itself on the root directory, if I move the files to the subdirectory, it says that it can't find the package.json when I run `lerna bootstrap`

**Comment by evocateur** [comment]
We support a custom location for the packages directory (which defaults to `./packages`), does that not work?

**Comment by FezVrasta** [comment]
Nope, I need to keep the package.json and the lerna config in that folder as well 😞

**Comment by joscha** [comment]
refs #555

**Comment by evocateur** [comment]
@joscha Indeed! Thanks for finding this. Closing in favor of #555
