### ISSUE TITLE
[bootstrap]: React Native crashes when attempting to process symlinked `.babelrc`

### ISSUE THREAD

**Issue by jacobp100** [lerna/lerna#623]
I have Package A, which has its own `.babelrc`, but this is added to `.npmignore`.

I also have Package B, which is a React Native project. B depends on A.

Because `lerna bootstrap` symlinks A into B, the `.babelrc` is copied over, even though it's in `.npmignore`.

In React Native, it picks up A's `.babelrc`, which causes a crash upon load.

**Comment by evocateur** [comment]
A `.npmignore` is only used to configure what is included in a package tarball, it does not change what gets linked (via `npm link` or lerna's symlink strategy).

React Native shouldn't be picking up `.babelrc` files from `node_modules`, but that's not lerna's bug. To workaround it, move the babel config into the `babel` property of `package.json`.

**Comment by jacobp100** [comment]
> To workaround it, move the babel config into the babel property of package.json

The resolution for `.babelrc` is the same as `package.json`, so this causes the same issue (although you can't overcome this with `.npmignore`.

> React Native shouldn't be picking up .babelrc

Actually, this is the behaviour of Babel, meaning that this affects all projects with babel configs between projects. While you could blame Babel for this, `.npmignore`d artefacts always have the potential to interfere with projects, and there will always be cases where you need them excluded.

I think a solution would be to to provide a non-default option to `npm install /path/to/package` instead of the default behaviour in each project, and document this option.

If you're happy with this solution, I'd be happy to work on this.

**Comment by evocateur** [comment]
Is this a Webpack process that is triggering this `node_modules` consumption, or a direct `babel-cli` call?

**Comment by jacobp100** [comment]
My use case is React Native—I'm not too sure about how that packages things.

For now I've moved the RN project out of `projects` and then `npm install ../packages/*` to manually update. It works, but it would be nice to have this fixed!

**Comment by evocateur** [comment]
I must admit total noobery when it comes to RN, I did not realize it was common practice to publish _non_-transpiled code and recurse through `node_modules` during the packaging phase. https://github.com/facebook/react-native/issues/10966 is a well-written overview of this state of affairs. 😨 

As for `lerna`'s stance, I'm inclined to stick closer to the idioms and patterns of the larger npm community, which as the linked issue lays out is

> * package.json's "main" only points to ES5 commonJS
> * `npm explore foo && npm install && npm test` should work

I understand the desire to co-locate application and library code, but I'm still leery of it, especially in light of RN's "generally accepted pattern" of transpiling `node_modules` by default.

**Comment by evocateur** [comment]
I've re-titled and re-opened this issue so we can discuss this more deeply, and perhaps get feedback from other RN+lerna users.

**Comment by konrad-garus** [comment]
Same issue with Angular and AoT compilation.

**Comment by kylecordes** [comment]
Up above a few messages it is mentioned that "npm link" has the same behavior, symlinking without regard to the .npmignore. It seems to me that the typical user of npm link sort of expects various brokenness and workarounds to be needed. Developing two packages concurrently is seen as a special case. But with Lerna in the mix, developing N packages concurrently is a standard case that eventually "everyone" will do all the time.

I see three main categories of solution:

* Lerna could do much more fine-grained symlinking, respecting the .npmignore, in theory this should allow other tools to work on modified.
* Lerna could declare that this is just how it works, it works like `npm link` - therefore other tools that consume packages (Babel in the react native case, ngc in the Angular case) would need to be enhanced with a way of configuring them to either respect the .npmignore and pretend they don't see files they aren't supposed to see, or to have a more project specific ad hoc way of tolerating extraneous files that appear in a symlinked package.

**Comment by evocateur** [comment]
My first inclination is toward treating `lerna`'s bootstrap behaviour like `npm link`, warts and all.
