### ISSUE TITLE
skip git during publishing does not skip GitUtilities

### ISSUE THREAD

**Issue by jogelin** [lerna/lerna#627]
On CI environment that uses docker to build and publish the monorepo, there is an issue because my docker container doesn't contain git: 

```
12:10:48.795 /bin/sh: 1: git: not found
12:10:48.798 Initializing Git repository.
12:10:48.808 /bin/sh: 1: git: not found
12:10:48.808 /home/app/node_modules/lerna/lib/logger.js:151
12:10:48.808             throw error;
12:10:48.808             ^
12:10:48.808 
12:10:48.808 Error: Command failed: git init
12:10:48.809 /bin/sh: 1: git: not found
12:10:48.809 
12:10:48.809     at checkExecSyncError (child_process.js:490:13)
12:10:48.809     at Object.execSync (child_process.js:530:13)
12:10:48.809     at Function.execSync (/home/app/node_modules/lerna/lib/ChildProcessUtilities.js:67:38)
12:10:48.809     at init (/home/app/node_modules/lerna/lib/GitUtilities.js:163:46)
12:10:48.809     at Function.descriptor.value (/home/app/node_modules/lerna/lib/logger.js:146:33)
12:10:48.809     at new Repository (/home/app/node_modules/lerna/lib/Repository.js:50:30)
12:10:48.809     at CleanCommand.Command (/home/app/node_modules/lerna/lib/Command.js:58:23)
12:10:48.811 GitUtilities.init             ()
```

I can create a docker file with git or map the git command to the container but I don't think it's a good solution.

During publish --skip-git could be use to skip git steps but why it cannot be use to skip all git command when it isn't available ?

I would be good to not force people using lerna to use git by adding a dummyGit or something.

**Comment by evocateur** [comment]
While I agree that it is a bit presumptuous to `git init` for someone unconditionally, `--skip-git` was never designed to support working _without_ `git`. Even skipping the init check won't make your build work, since there are other `git` commands used during `lerna publish` to decide what to publish in the first place.
