### ISSUE TITLE
--hoist enables illegal access to external packages

### ISSUE THREAD

**Issue by akosyakov** [lerna/lerna#629]
Consider 2 sub-packages A and B, where only A depends on an external package C. With `--hoist` C is put into the root `node_modules` enabling access to C from B, which is bogus. Is there a way to prevent it?

**Comment by spudly** [comment]
There is no way to prevent it that I know of, but you can use eslint to catch these errors.

Use the [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) eslint plugin and the [import/no-extraneous-dependencies](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md) rule that it provides.

**Comment by akosyakov** [comment]
@spudly thanks for the pointer! i use typescript, let's see maybe tslint has a similar rule

**Comment by evocateur** [comment]
@akosyakov This really is more of an external validation issue, since nothing (except good sense) really stops you from installing a bunch of modules in a parent directory (or globally, for example) and using them in your module. It'll obviously fail, but that's not in the purview of `lerna`.
