### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE when using lerna publish in docker container

### ISSUE THREAD

**Issue by jogelin** [lerna/lerna#633]
Hello,

I would like to use lerna to publish my packages on my CI environment but I have an issue: `UNABLE_TO_VERIFY_LEAF_SIGNATURE`, more details in the logs below.

The first reaction is to think about strict-ssl but my .npmrc is in place, used and correctly configured.

In our CI environment, we are using docker images to run command on our apps (build, test, publish, etc...). We can directly run a command by using a `docker-compose.yml` description. By example, to publish we use:

```
version: '2'
services:
  js-publish:
    container_name: npm-publish
    image: kkarczmarczyk/node-yarn:7.6-slim
    command: /bin/sh -c "yarn run _docker:publish -- 0.1.0"
    working_dir: /home/app
    volumes:
      - .:/home/app
      - .npmrc:/root/.npmrc
```
_(The version number is replaced by the CI tool before we run the command.)_

Below, the scripts that I am using:
```
{
        "bootstrap": "lerna bootstrap",
        "transpile": "ngc -p ./packages/tsconfig.json",
        "package": "lerna exec -- ../../node_modules/.bin/rollup -c rollup.config.js",
        "extends": "lerna exec -- ../../node_modules/.bin/babel-node ../../scripts/extends-package.js  --presets es2015",
        "build": "npm-run-all clean bootstrap extends transpile package",
        "publish": "lerna publish --yes --skip-npm --skip-git --skip-temp-tag --repo-version",
        "LERNA:HACK": "cp ./scripts/GitUtilities.js ./node_modules/lerna/lib/GitUtilities.js",
        "//DOCKER": "****************************************************************************",
        "_docker:install": "yarn install --no-progress && npm run LERNA:HACK",
        "_docker:build": "npm run _docker:install && yarn run build",
        "_docker:test": "npm run _docker:install && echo \"NOT IMPLEMENTED : npm run all -- yarn run test\"",
        "_docker:publish": "npm run _docker:install && lerna publish --yes --skip-git --skip-temp-tag --force-publish --repo-version"
}
```

Then we run the command:
```
$ docker-compose run --rm js-publish
```

Then we have the errors below:
- [console.log](https://raw.githubusercontent.com/jogelin/host-files/master/console.log)
- [lerna-debug.log](https://raw.githubusercontent.com/jogelin/host-files/master/lerna-debug.log.log)

If I connect to my docker container and I publish manually a package by using `npm publish --tag latest`
OR
If I run directly a command by using the `docker exec 2eb80d97f39e npm publish --tag latest packages/localization`
IT WORKS AND PUBLISH MY PACKAGE !!

I tried many solutions like `lerna exec -- npm publish --tag latest`....same error....each time I am using lerna, I have this certificate error....

Someone can help ?

**Comment by evocateur** [comment]
Are you able to recover the `npm-debug.log` or `lerna-debug.log` files generated after that error?

Where is your `.npmrc` located in this case?

**Comment by jogelin** [comment]
my `.npmrc` is located at `/root/.npmrc` which is the home of the docker node image.

I will provide the logs later. But I don't understand why it publish when I execute the command manually. Maybe because I am using docker-compose to run my command but I am not an expert...
I'll keep you inform

**Comment by evocateur** [comment]
I suspect there is a difference in shell variables or resolved configuration between the CI process and your user account. I've never encountered this particular error before, and since I've not used npm 4 that much, I'm not sure if that's a contributing factor as well.

**Comment by jogelin** [comment]
I updated my description by adding logs and put more details on my CI process.

Indeed, there is a difference...but not easy to find ;)

**Comment by jogelin** [comment]
After some investigations, test, etc... If I replace yarn by npm in my `docker-compose`:
 `yarn run _docker:publish -- 0.1.0` by `npm run _docker:publish -- 0.1.0`...it works.

I read many issue about strict-ssl not evaluated correctly by yarn. But even with a `.yarnrc` or a `yarn config set strict-ssl false` before, it failed.

I don't understand why a `yarn run ...` command which execute a script doing an `npm publish` has an impact on the way that the publish is done ?!?

**Comment by jogelin** [comment]
I solved my issue with the best solution: configure the certificates into the docker container...
