### ISSUE TITLE
Add flags for improved `lerna run` workflow

### ISSUE THREAD

**Issue by spudly** [lerna/lerna#637]
I'm currently running `lerna run lint` over and over and fixing issues as they come up in a repo with over 100 packages. This is really tedious because it re-runs the lint task for every package each time.

It'd be nice if you could get more control over what happens when a task exits with a non-zero exit code.

`--bail`: Gives control over whether to stop when a task fails (Default: true). Set `--bail=false` to continue running regardless of whether the task fails for one package.
`--continue`: Rerun the task for any packages that either failed, or didn't run the last time you ran `lerna run <task>`.

Either of these flags would make it a lot easier for my current use case. If you like the idea, I'll work on a PR.

**Comment by evocateur** [comment]
May I ask why you don't lint globally from the root?

I understand there is a subset of lerna users that want to keep a given package's script executions and devDependencies "package-local", enabling focused development on a single package. I personally find "repo-global" linting and test running (with coverage reporting configured in one place) to be extremely beneficial.

`eslint`, for example, has a [`--cache`](http://eslint.org/docs/user-guide/command-line-interface#caching) option that makes repeated runs on a codebase that is largely unchanged much more efficient.

That being said, I am open to the idea of supporting the `--` pattern for passing additional args to the script that `npm run` [already supports](https://docs.npmjs.com/cli/run-script):

> [You] can use custom arguments when executing scripts. The special option `--` is used by `getopt` to delimit the end of the options. npm will pass all the arguments after the `--` directly to your script:
>
> `npm run test -- --grep="pattern"`
>
> The arguments will only be passed to the script specified after npm run and not to any pre or post script.

If package.json's `scripts.test = "mocha"`, the above example would execute `mocha --grep="pattern"`. Does that sound reasonable?

**Comment by spudly** [comment]
> May I ask why you don't lint globally from the root?

Unfortunately I haven't finished porting all our coffeescript packages to es6 yet :sad:. So some of my packages use eslint and others use coffeelint.

> eslint, for example, has a --cache option

Woah! Didn't know about that. Will definitely be using `--cache` in the future.

> I am open to the idea of supporting the -- pattern for passing additional args to the script that npm run already supports:

That already works today I think. I haven't used it with `lerna run` but I use it with `lerna exec` all the time.

Unfortunately, that doesn't solve my problem. I want it to skip packages, not pass a parameter to each package, especially considering that the arguments it accepts might be different for each package.

**Comment by noherczeg** [comment]
Define a script entry in the root with the lerna task and the scopes?

**Comment by spudly** [comment]
> Define a script entry in the root with the lerna task and the --scopes?

I'm afraid that doesn't help me at all with this use case.

I think at this point I'm more interested in a `--bail=false` command-line argument. I think this would help with multiple use cases (not just this one). All it does is allow `lerna run` to continue when scripts fail.

Right now my workflow for this is:
1. run `lerna run lint` (takes forever with > 100 packages)
2. if lint passed for all packages, stop
3. fix errors
4. go back to step 1

Adding `--bail=false` would show me a list of all errors the first time, so I could fix them all at once, changing my workflow to this:
1. run `lerna run lint`
2. fix errors
3. stop

I think `--bail=false` would help in other use cases too. I know I've seen other issues in this repo where users were unable to do certain things because `lerna run` stops when it encounters an error.
