### ISSUE TITLE
lerna bootstrap fails on version keyword "latest"

### ISSUE THREAD

**Issue by dominikwilkowski** [lerna/lerna#640]
Given the blow packages (folder names equal package names) and making `pancake-js` depend on `pancake` on `latest` will break bootstrap. Lerna bootstrap will try to install the dependency from the registry as opposed to linking the lerna pakages.

```shell
.
├── lerna.json
├── package.json
├── packages
│   ├── pancake
│   ├── pancake-js
│   ├── pancake-sass
│   └── pancake-svg
└── yarn.lock
```

pancake-js `package.json`
```json
"dependencies": {
	"@gov.au/pancake": "latest"
},
```

**Comment by evocateur** [comment]
Yeah, the way we associate "packages that are in the same monorepo and should be linked" is a simple `semver.satisfy(pkg.version, needVersion)`, not an actual poll of the registry to resolve any tag (such as `latest`). So if you use a matching major, like `^1.0.0`, it should work again.

**Comment by dominikwilkowski** [comment]
I can't change the version match just because lerna doesn't understand it :)
But I get it, no worries.

I expected to not check version and only see if the dependent module is inside our repo. I don't understand when you would ever want to depend on an older version of the same thing you are developing especially inside a monorepo. (Where things are built together)

Anyway I might be an edgecase then :)

**Comment by dominikwilkowski** [comment]
A nice solution for this is to use:

```json
"dependencies": {
	"@gov.au/pancake": ">0.1.0"
},
```

That way I stay within semver validation. Hope this helps someone else.

**Comment by evocateur** [comment]
Using the `latest` tag as a local dependency specifier is not supported by `lerna`.

**Comment by lleaff** [comment]
I think this should be added to the FAQ or some kind of gotchas/caveats collection.
