### ISSUE TITLE
`lerna init` on an empty folder don't generate any file

### ISSUE THREAD

**Issue by gre** [lerna/lerna#645]
the prerequisite is to have a git repo but the command says it generated files successfully but didn't.

```
$ mkdir foo
$ cd foo
$ lerna init
Lerna v2.0.0-beta.38
Updating package.json.
Updating lerna.json.
Successfully created Lerna files
$ ls
# // nothing
```

**Comment by evocateur** [comment]
I get something subtly different:
```bash
[~/github]$ mkdir foo
[~/github]$ cd foo/
[~/github/foo]$ lerna init
fatal: Not a git repository (or any of the parent directories): .git
Initializing Git repository.
Lerna v2.0.0-beta.38
Creating package.json.
Updating lerna.json.
Successfully created Lerna files
[~/github/foo] (master)$ ls -l
total 16
drwxr-xr-x  9    306B Mar  7 13:24 .git/
-rw-r--r--  1     91B Mar  7 13:24 lerna.json
-rw-r--r--  1     60B Mar  7 13:24 package.json
```

That fact that your logging said "Updating <file>" instead of "Creating <file>" is suspicious.

What are the versions of node, npm, and git in your shell?
```
node --version
npm --version
git --version
```

**Comment by khaled** [comment]
same issue here.

node version:  v6.9.1
npm version: 3.10.8
git version: 2.2.1

**Comment by khaled** [comment]
Looks like `lerna init` was creating initialization files in the parent directory, which happened to be a git repo.  After running `git init` in the child directory, `lerna init` did the right thing.

**Comment by evocateur** [comment]
I think you've correctly identified the issue, @khaled. More and more, I think our "assume the git root is _always_ the place we want" is a bit naïve. Certainly in the case of `lerna init`, we should be using `process.cwd()` instead of `git rev-parse --show-toplevel`.
