### ISSUE TITLE
b38: "Comparing with:" message misleading, scary

### ISSUE THREAD

**Issue by garthk** [lerna/lerna#648]
```
Lerna v2.0.0-beta.38
Independent Versioning Mode
Ignoring packages that match '*.md,test/**'
Checking for updated packages...
Comparing with: bbb@1.1.1
```

Wait, what? I changed ccc, not bbb. Why is it only comparing with bbb? *PANIC*

The "Comparing with:" message suggests Lerna has forgotten about all my other packages. My guess is most packages' tags share one hash, and Lerna is taking the first after sorting by name.

**Comment by evocateur** [comment]
Indeed, that is weird!

I did some digging in this area recently (for much the same reason, though indirectly), and the TL;DR is we should probably start using the `--match` arg of [`git describe`](https://www.kernel.org/pub/software/scm/git/docs/git-describe.html) when calling [`GitUtilities.getLastTag()`](https://github.com/lerna/lerna/blob/master/src/GitUtilities.js#L65) in [`UpdatedPackagesCollector.collectUpdatedPackages()`](https://github.com/lerna/lerna/blob/master/src/UpdatedPackagesCollector.js#L34) (it's weird that we never use the `tag` var anywhere else...).

I think for the purposes of that initial `hasTags` check, we can just log "Comparing with most recent tag" and be done with it.

I was noodling about `git describe --match <glob>` to address a slightly different issue when using `--independent` mode, but it's beyond the scope of this issue (and I kinda forgot what I was _actually_ looking at it for 😞 ) .
