### ISSUE TITLE
Possibility to not add @scope to the git tags.

### ISSUE THREAD

**Issue by pleunv** [lerna/lerna#649]
The current format for the git tags is `<pkgName>@<pkgVersion>`, however with private (scoped) packages combined with independent versioning this tends to get very noisy, as you get a bunch of `@organisation/my-component@x.x.x` tags on each commit. Would it be feasible to either strip the `@organisation/` part by default, or at least make it a `--flag`?

**Comment by mrfelton** [comment]
Agree that the abundance of so many tags is an issue, though I don't see how the @scope portion of the tag message is the cause of this.
