### ISSUE TITLE
No such file error when running bootstrap with yarn as npmClient

### ISSUE THREAD

**Issue by seb0zz** [lerna/lerna#650]
I've got the following lerna.json:

```json
{
  "lerna": "2.0.0-beta.38",
  "version": "0.0.0",
  "npmClient": "yarn"
}
```

When I run `lerna bootstrap` yarn is crashing in random packages with the following trace:

```
Trace:
  Error: https://registry.yarnpkg.com/core-js/-/core-js-1.2.7.tgz: ENOENT: no such file or directory, lstat '/Users/my-user/Library/Caches/Yarn/npm-core-js-1.2.7-652294c14651db28fa93bd2d5ff2983a4f08c636/client/core.js'
```

Seems to be related to [concurrent yarn processes](https://github.com/yarnpkg/yarn/issues/1418). Also tried to run bootstrap with the parameter `--concurrency 1` but that doesn't seem to fix it.

**Comment by evocateur** [comment]
We could probably try using the [`--mutex`](https://yarnpkg.com/en/docs/cli/#toc-concurrency-and-mutex) flag as described in [this issue](https://github.com/yarnpkg/yarn/issues/683). I'm not sure how that would mess with lerna's `--concurrency` arg, though.

@gigabo ?

**Comment by gigabo** [comment]
Yeah, could alternatively try with `--concurrency=1`.

May need to add support for passing options to npm clients.  Or have per-client presets internally?

**Comment by evocateur** [comment]
Given the existing problems with `yarn` in multiple concurrent processes, I would think per-client presets would be the way to go.
