### ISSUE TITLE
lerna publish with --registry flag errors with "env: node: No such file or directory"

### ISSUE THREAD

**Issue by YellowKirby** [lerna/lerna#652]
When using lerna publish with the `--registry` CLI flag, I'm getting the following error:

```sh
> lerna publish --registry=https://some-custom-registry.com

...

? Are you sure you want to publish the above changes? Yes

Publishing packages to npm...
NpmUtilities.publishTaggedInDir("lerna-temp", "./packages/base-types", "https://some-custom-registry.com")
Error: Command failed: cd /Users/username/dev/project/packages/base-types && npm publish --tag lerna-temp
env: node: No such file or directory

    at ChildProcess.exithandler (child_process.js:210:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:504:12)
```

The problem seems to be that [`NpmUtilities.getTagOpts()`](https://github.com/lerna/lerna/blob/master/src/NpmUtilities.js#L137) sets up an `env` property that gets passed to `child_process` which _only_ contains the `npm_config_registry` value. When playing around with `child_process` interactively, it seems that passing `null` (or an empty object) for the 2nd parameter will pass through any environment variables, but this is not the case when an explicit `env` property is set:

When no `env` option is provided to `child_process`:
```sh
> child.exec('env', { }, (err, stdout, stderr) => console.log(stdout)) && false
false
> TERM=xterm-256color
SHELL=/usr/local/bin/fish
USER=username
PATH=/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin:/Users/username/.yarn/bin:/Users/username/.fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/Users/username/dev/project
_=/usr/bin/env
...
```

But if an `{ env: { npm_config_registry: "foo" } }` is provided:
```sh
> child.exec('env', { env: { npm_config_registry: 'foo' } }, (err, stdout, stderr) => console.log(stdout)) && false
false
> npm_config_registry=foo
PWD=/Users/username/dev/project
SHLVL=1
_=/usr/bin/env
```

In the latter case, since `PATH` isn't set, the `node` executable cannot be found.

**Comment by noherczeg** [comment]
@YellowKirby I will look into it in the evening, sorry for the inconvenience!

**Comment by evocateur** [comment]
Wondering if we could also employ [`npm-run-path`](https://github.com/sindresorhus/npm-run-path#readme) here, in addition to properly merging `process.env`...

**Comment by noherczeg** [comment]
@evocateur I'll do the PR without it, and you can decide if you want it to be added to it or not, if it's okay.
