### ISSUE TITLE
Can't run bootstrap as postinstall when consuming a lerna monorepo as a package

### ISSUE THREAD

**Issue by probablyup** [lerna/lerna#658]
The culprit is here: https://github.com/lerna/lerna/blob/d246667b9b8513d2c3ac14a796d9dc04126a1294/src/GitUtilities.js#L85

The idea is that if I `npm install` a package that is a lerna monorepo and has a postinstall step to run bootstrapping, that utility will go up the whole tree to the consuming NPM project which won't have the `lerna.json` and bootstrapping fails.

**Comment by evocateur** [comment]
What does the `lerna.json` for the monorepo package look like? What is the directory structure of the repository it is contained in?

With the default `packages` location (`$GIT_ROOT/packages`), a lerna monorepo only uses the root `package.json` for hosting shared `devDependencies` and lifecycle commands. That is to say, the root package.json (which contains the `"postinstall": "lerna bootstrap"` script) is never actually consumed as an npm dependency externally.

If, as I suspect, you are using multiple `packages` locations, one of them being the root, that _does_ make the root package published for external consumption. In that case, you have two straightforward options:
1. rename the postinstall script "bootstrap", thus avoiding the external lifecycle hook
2. move the external package in the root back into the shared `packages` location

There are more complicated solutions, but in this case, the solution is not a change in `lerna`. The line you highlighted may very well be naïve, but it does represent one of the fundamental design goals of `lerna`, and thus supporting the pattern you described here is extremely unlikely.

**Comment by probablyup** [comment]
Here's the structure:

```
consuming-package/
    package.json
    node_modules/
        lerna-monorepo/
            package.json
            lerna.json
            packages/
```

I intentionally want `lerna-monorepo` to run bootstrap on `postinstall`, but because of how that utility works, lerna looks all the way to the top for lerna.json instead of where the command itself is actually invoked.

**Comment by evocateur** [comment]
A published npm module shouldn't require a postinstall phase unless it is compiling native extensions. Lerna is not intended to be a runtime dependency.

**Comment by probablyup** [comment]
OK... I guess.

**Comment by NunoFl** [comment]
ory editor is giving me this problem when doing "npm i" command

**Comment by NunoFl** [comment]
npm ERR! undefined postinstall: `npm-run-all clean clean:lerna bootstrap build:lib`
