### ISSUE TITLE
Is there a way to automatically select patch on all lerna publish version selection prompts?

### ISSUE THREAD

**Issue by omerxx** [lerna/lerna#659]
Hey,
Trying to run lerna in a CI process:
Using `--yes` doesn't affect version selection prompts from `lerna publish`
I cannot use `npm --repo-version` since it would hard set a single version to all modules.

**Is there a flag / workaround to select the first option (Patch) and let lerna do its version magic automatically?**

**Comment by nutgaard** [comment]
PR #607 solves this if I'm not mistaken

9. mar. 2017 16.46 skrev "Omer Hamerman" <notifications@github.com>:

**Comment by omerxx** [comment]
Thanks for the quick reply!
The feature is great and would solve my problem perfectly, however it's still not merged and there seem to be code conflicts..
Any other suggestion for quick workaround or should I wait for the guys to complete it?

**Comment by nutgaard** [comment]
I could wait due to a limited amount of time at a current project; so I released cif-branch with some added debugging here: https://www.npmjs.com/package/lerna-waiting-on-pull-607

Hopefully the PR will get merged soon so I can deprecate and forget about this shady solution.

**Comment by omerxx** [comment]
Nice :)
Thank you for that!

**Comment by nutgaard** [comment]
Yeah, I've not had any issues with it. I just added `--cd-version patch` to the lerna-command and it bumps the packages that has been changed.

**Comment by danielo515** [comment]
The PR has been merged. May close the issue?

**Comment by nutgaard** [comment]
I've deprecated my package on npmjs.org and switched to the original package without any issues. So as far as I'm concerned it can be closed.

**Comment by evocateur** [comment]
Thanks all!
