### ISSUE TITLE
add support for conventional-changelog format commit messages

### ISSUE THREAD

**Issue by bcoe** [lerna/lerna#662]
I've become a convert to _this whole monorepo thing_. I see it as a great tool for simplifying the development, and perhaps more importantly, the management of two of the ecosystems I maintain ([conventional-changelog was recently ported over to lerna](https://github.com/conventional-changelog/conventional-changelog), and we're in the process of [moving over Istanbul](https://github.com/istanbuljs/istanbuljs)).

_.... my problem._

## Problem Statement

I've become fairly dependent on [conventional-commit-messages](https://github.com/bcoe/conventional-changelog-standard/blob/master/convention.md), I adhere to a few simple rules when squashing commits:

* prefix with `fix:` for patches.
* prefix with `feat:` for new features.
* add `BREAKING CHANGE:` on a newline to describe a breaking API change.

By doing this I'm able to:

* automatically generate a CHANGELOG for repos; this is [really valuable for providing users with contextual information](https://github.com/yargs/yargs/pull/740#issuecomment-270508120).
* I also use this CHANGELOG format to recommend the next version # (if a release is taking a month to land, it's sometimes easy to forget if it's a `patch`, `minor`, or `major`).

When running `lerna` in independent mode, I lose this valued functionality.

## Proposal

I've been hard at work adding support to conventional-changelog for a lerna-style-git-history:

https://github.com/conventional-changelog/conventional-changelog/issues/168

I would like to add an additional flag for publishing in `independent` mode (`--conventional-commits`?) when running in this mode, two things would happen:

1. we would not prompt the user for version increments, we'd detect this based on the commit history (instead having a confirm step).
2. we would auto-generate the CHANGELOG in each `./pacakge/:name`.

I think adding this functionality would be pretty straightforward, and could be facilitated by pulling in a couple of the `conventional-changelog` core libraries, and augmenting the functionality of `PublishCommand.js`.

-----

thoughts, comments, concerns (CC: @hzoo, @evocateur).

**Comment by evocateur** [comment]
I am generally in favor of this (also p excited that you're getting excited about `lerna` :D). As I mentioned in #643, this feels like a plugin system, but I am not opposed to a more focused solution to avoid larger, more complicated refactoring.

`--conventional-commits` seems like a reasonable flag. It would also be configurable in `lerna.json` as `"conventionalCommits": true`, either at the root or `command.publish` namespace.

**Comment by bcoe** [comment]
@evocateur lifecycle scripts and/or a plugin system does feel like it would be a pretty awesome eventual feature. 

It felt to me that using conventional commit messages is a common enough practice, and that it improves the `independent` workflow enough, that it would be worth implementing the approach outlined in #665 -- it also turns out that it doesn't take too much code to wire things together 😄

**Comment by hzoo** [comment]
Curious how this will interop/relate to https://github.com/lerna/lerna-changelog, I guess unrelated then since this assumes the commit message format?

**Comment by evocateur** [comment]
We could certainly open up more customization to the `--conventional-commits` args (not everyone uses the angular style?), but I don't see it necessarily conflicting with `lerna-changelog`.

In fact, I'm kind of interested in seeing how this could be "dogfooded" on an eventual lerna-as-lerna-monorepo ( #174, aka "yo dawg, i heard you liked lerna...").

For one thing, it's nice (for unfortunate folks like me who will forever yearn for their company's code to be rescued from Bitbucketian horrors) that `conventional-changelog` doesn't depend explicitly on GitHub metadata to operate.

**Comment by bcoe** [comment]
@hzoo I think they probably pair nicely, and could eventually be combined? It seems to me that:

* if you're running in `independent` mode, it's pretty nice to have a per-module CHANGELOG.md (makes it easier to pull in legacy projects for starters); Also, it can be tedious bumping each version manually so using a convention is nice.
* it seems like an approach like lerna-changelog works better for fixed/locked mode -- where I think it potentially makes more sense to report changes in a single top level document?

It seems like the angular conventional-commit format (which is used by [semantic-release](https://github.com/semantic-release/semantic-release#default-commit-message-format) by default, and [standard-version](https://github.com/conventional-changelog/standard-version)) is getting pretty healthy adoption, is probably worth parsing for both use-cases?

**Comment by evocateur** [comment]
@bcoe oh hey, forgot to mention:

```sh
$ npm dist-tag ls lerna
canary: 2.0.0-beta.38-18-g5043ad2
latest: 2.0.0-beta.38
```

**Comment by traviskaufman** [comment]
Been waiting for something like this to land 🙌 I'm hoping it can replace a lot of the infra we built manually to do this ourselves. Thanks @bcoe and @evocateur!

**Comment by bcoe** [comment]
@traviskaufman awesome, please don't hesitate to flag me in issues on lerna as you test stuff out; I'm excited to make this feature kick butt.

**Comment by myfairsyer** [comment]
How is [atlassian/cz-lerna-changelog](https://github.com/atlassian/cz-lerna-changelog) (not) related and/or relevant to this?
