### ISSUE TITLE
Add option to turn hoist warnings into errors

### ISSUE THREAD

**Issue by sstone1** [lerna/lerna#667]
Just trying out --hoist, and it's awesome! 
However, just a suggestion on this:

> Note: If packages depend on different versions of an external dependency, the most commonly used version will be hoisted, and a warning will be emitted.

It would be better if this warning could be turned into an error via lerna.json option or CLI switch, at which point the warnings can be stopped at build/PR time and force the developers to fix the problems.

**Comment by evocateur** [comment]
#655 is surfacing the mismatched dependency warning, which is currently never enabled. It would be straightforward to convert `hasMatchingDependency()`'s second argument into an options object that consumes the value of a `--strict` flag, if present.
