### ISSUE TITLE
Arrow keys don't work on Windows cmd when using --force-publish

### ISSUE THREAD

**Issue by sccolbert** [lerna/lerna#675]
As it says on the tin. The --force-publish flag is not usable on Windows 10 cmd.exe because the arrow keys don't work, making it impossible to specify the version.

Lerna Version: 2.0.0-beta.38

**Comment by evocateur** [comment]
@sccolbert What version of node + npm are you using?

I suspect this might be an upstream issue with inquirer (and actually node.js): https://github.com/SBoudrias/Inquirer.js/issues/266

**Comment by sccolbert** [comment]
Node v5.10.0
Npm v3.8.3

**Comment by sccolbert** [comment]
I should note that arrow keys *do* work when doing a regular publish. It only seems to not work when using --force-publish.

**Comment by evocateur** [comment]
Curiouser and curiouser. What does your `lerna.json` look like, and what is the command that causes it to fail?

**Comment by sccolbert** [comment]
Following that issue chain led to this comment:
https://github.com/nodejs/node/issues/5384#issuecomment-219984590

I'll try updating node in a bit and see if that fixes the problem.

Lerna.json:
https://github.com/phosphorjs/phosphor/blob/master/lerna.json

Command in question:
`lerna publish --force-publish @phosphor/application`

**Comment by evocateur** [comment]
I wonder if `--independent` mode is combining with the single-target `--force-publish` in some weird way? I would have expected the arrow keys to fail in _all_ cases, not just the case with `--force-publish` included...

**Comment by sccolbert** [comment]
This problem is not present in Node v6.10.0. Sorry for the noise!

**Comment by evocateur** [comment]
No worries, glad it was resolved!
