### ISSUE TITLE
transitive dependencies of non-hoisted dependencies replace hoisted versions

### ISSUE THREAD

**Issue by jppurcell9** [lerna/lerna#677]
Say I have a package that depends on `lodash@4` and another module `uses-old-lodash` with a transitive dependency on `lodash@3`.  If I do a regular `lerna bootstrap`, I end up with the following in my `node_modules` folder:

```
.
└── my-package
    └── node-modules
        ├── lodash@4
        └── uses-old-lodash
            └── node-modules
                └── lodash@3
```

Normally, using `lerna bootstrap --hoist` will pull the dependencies up to the top level without a problem.  But, if for some reason we can't hoist `uses-old-lodash` (either because of a version conflict or `--nohoist=uses-old-lodash`), then we end up with the following structure:

```
.
├── node_modules
│   └── lodash@4
└── my-package
    └── node-modules
        ├── lodash@3
        └── uses-old-lodash
```

Because of the way npm is flattening dependencies (npm@3 and above), `lodash@3` comes up to the root of `my-package/node-modules` when `lodash@4` gets hoisted.  So if I `require('lodash')` in a script in `my-package`, I'm going to get the wrong version of `lodash`.

It would be nice if the transitive dependencies did not get flattened in the case where a different version of the same dependency has been hoisted.

**Comment by evocateur** [comment]
Yikes, that's a pretty terrible experience.

One potential workaround, at least for `npm`, would be to specify the [`--global-style`](https://docs.npmjs.com/misc/config#global-style) option when installing the non-hoisted dependencies. It does incur the cost of less deduping, but in our case, that's probably a distinction without a difference (this _should_ be a rare occurrence).

If we used `--global-style`, this is what the tree would look like in your second case:

```
.
├── node_modules
│   └── lodash@4
└── my-package
    └── node-modules
        └── uses-old-lodash
            └── lodash@3
```

I'm not sure what the `yarn` solution for this is. :/

**Comment by spudly** [comment]
I'm having a similar problem in my builds where it is installing the wrong version of 'uuid' intermittently (about 50% of the time) on the build server.

I haven't nailed down the exact problem, but I think it may be related to the same de-duping behavior of npm.

**Comment by jppurcell9** [comment]
Thanks for the quick response.  I noticed https://github.com/yarnpkg/yarn/issues/877 over in the yarn repo with some ideas on implementing `--global-style`, but it looks like it would not be a quick fix.

**Comment by jppurcell9** [comment]
I started implementing an approach that might work for both npm and yarn clients in the PR referenced above.  Still a work in progress and feedback would be appreciated.  Here's the basic idea - install leaf deps into a "shadow" directory:

```
.
├── node_modules
│   └── lodash@4
└── my-package
    └── node_modules
        └── _node_modules
            └── node_modules
                ├── lodash@3
                └── uses-old-lodash
```

Then move any named deps back into the `node_modules` dir:

```
.
├── node_modules
│   └── lodash@4
└── my-package
    └── node_modules
        ├── _node_modules
        │   └── node_modules
        │       └── lodash@3
        └── uses-old-lodash
```

And finally symlink the shadow `node_modules` back into the dep:

```
.
├── node_modules
│   └── lodash@4
└── my-package
    └── node_modules
        ├── _node_modules
        │   └── node_modules
        │       └── lodash@3
        └── uses-old-lodash
            └── node_modules -> ../_node_modules/node_modules
```

**Comment by evocateur** [comment]
Like I mentioned in the PR,  I'd be much happier with a solution that simply used `npm install --global-style` (regardless of `--npm-client` option) to deal with non-hoisted package dependencies. It should be a rare enough occurrence, in practice.

**Comment by bcoe** [comment]
@evocateur I seem to be seeing this same problem on beta.38:

The directory structure looks like this:

```
./packages/transform-file-follower/node_modules/@npm/knork/package.json:    "numbat-emitter": "^2.3.2",
```

and the old `2.3.2` version gets hoisted to the top-level `transform-file-follower`; I'm upgrading the internal dependency to fix -- but thought I'd give the update.
