### ISSUE TITLE
lerna publish --skip-npm only creates a git commit, but doesn't push

### ISSUE THREAD

**Issue by omerxx** [lerna/lerna#680]
When trying to debug the git pushing (I'm working with drone CI server) I try `lerna publish --yes --cd-version=path --skip-npm` but it only creates the git commit and doesn't push it. any idea why?
Is this a bug, or intentional? Can I force this push?

And another question, if this is a problem on my environment, can I deliberately force only git commit (no pushing)?

**Comment by evocateur** [comment]
Right now, there is no way to split the enabled git operations (commit + tag + push).

What version of `lerna` are you using?

**Comment by omerxx** [comment]
Using latest release.
The fact is that only `--skip-npm` creates the commit but doesn't push.
I actually do need this behaviour since I need to refactor the commit to prevent my CI server from being triggered.
I couldn't find any supporting documentation for what I'm experiencing and your comment confuses me too...

**Comment by evocateur** [comment]
The code that calls `git push` is currently located inside a method that is not called when you pass `--skip-npm`. This looks intentional, to me.

If you're doing this locally, why not just push manually after amending the commit?

**Comment by omerxx** [comment]
I'm not doing this locally. Using a CI server
I can take a fork and change it to never publish if there's no option to set it up

**Comment by evocateur** [comment]
Your CI doesn't let you `lerna publish <args> && git push --tags origin`?

**Comment by omerxx** [comment]
Of course it does, but I'd like to publish npm packages on one hand, create git commit and tags but prevent it from being pushed on the other.
So I need something like `lerna publish <args> && git push --tags origin` according to my situation would push twice to git. I can't allow that.

**Comment by omerxx** [comment]
Anyway, @evocateur you've helped a lot by pointing me to the face that `--skip-npm` will not push to git. I'll use that.
Thanks!
