### ISSUE TITLE
lerna run only appears to use 2 concurrent threads

### ISSUE THREAD

**Issue by ryancole** [lerna/lerna#683]
I've got a repo with several packages that have `watch` scripts. When I use `lerna run watch --stream`, it appears that only 2 ever run at the same time. Only two of the packages will have their `watch` script execute. I've tinkered with the `--concurrency` setting, which is 4 by the default, but it doesn't appear to change anything.

```
npm: 4.1.2
node: 7.7.1
lerna: 2.0.0-beta.38
```

On Windows 10 64-bit, using Hyper 1.3.1.

**Comment by evocateur** [comment]
Verrrry interesting. What does `node -e 'console.log(os.cpus().length)'` output?

**Comment by ryancole** [comment]
@evocateur it outputs `12`

**Comment by evocateur** [comment]
zoiks, that does seem like it would be able to deal with it just fine.

Random shot in the dark: have you tried adding `--no-sort`? It often makes `--stream` kinda useless, since topologically sorting creates bottlenecks _on purpose_ (to make sure dependencies run before dependents).

`lerna run watch --stream --no-sort`

**Comment by ryancole** [comment]
@evocateur that seems to work. with `no-sore`, all of my watch scripts now run.

**Comment by ryancole** [comment]
I wanted to swing back around and mention that I don't actually think the `--no-sort` has resolved the issue. Even with `--no-sort` I have experienced some scripts just simply not running. Without `--no-sort`, at all, it only ever runs 2 concurrent scripts. With `--no-sort`, it will sometimes run all of my scripts (4) and other times it might only run 3. Although, I've never seen it run less than 3 with `--no-sort`.

For the time being, I've just chosen to get rid of several of these watch scripts, because they're not absolutely necessary. But, I do think that if the intention is for this to be capable of running several blocking scripts at once, such as watch script, then this might still be a bug somewhere.

**Comment by gigabo** [comment]
@ryancole Lerna has a default concurrency of 4.  You can increase that with the `--concurrency` option.

This came up recently in https://github.com/lerna/lerna/issues/449#issuecomment-287184448, also.  A `--watch` option was suggested.  Seems to make sense.
