### ISSUE TITLE
Cannot find peer dependency of symlinked module

### ISSUE THREAD

**Issue by szdavid92** [lerna/lerna#691]
Version: 2.0.0-beta.38

I face the problem by using lerna reported already for browserify:
https://github.com/substack/node-browserify/issues/1325

Lerna symlinks my package that has a peer dependency, and so that throws an error when trying to load the dependency. 

I guess there's no clean way to solve this. The only thing on my mind is installing the affected dependencies normally, but that is far from ideal.

**Comment by ryancole** [comment]
I think this just seems to be the case for dependency hierarchies within your (my) lerna repo, in general. I was about to make my own issue, but I saw this at the top and it seems to be the same issue, or at least related.

In my case, I've got several packages within my lerna repo. I've got a package that is sort of a common package and is a dependency to some of my other packages. Finally, I've got a single package that depends on a package that depends on that common base package. So, it looks something like this ...

- Package A
- Package B
  - Depends on Package A
- Package C
  - Depends on Package B

In the `node_modules` for Package C, you will find Package B sym linked, but not Package A or its dependencies.

**Comment by noherczeg** [comment]
@szdavid92 Are you using the [--hoist option](https://github.com/lerna/lerna#--hoist-glob)? If not you could try it out, since it hoists all dependencies to the top therefore processes may be able to find deps. easier.

**Comment by szdavid92** [comment]
@noherczeg No that didn't work. The problem I face is with the symlinking of internal dependencies, and this seems to hoist external ones.

@ryancole similar situation for me:

Package A depends on B and C
Package B peerDepends on C

Result:

B symlinked into A's modules
C copied into A's modules

However my problem is no matter C is symlinked or not, it cannot be resolved when B tries to load it. As for now I use a workaround (for browserify) that actually works if C is copied instead of symlinked, but neither will work in node.

I have another problem, I don't know if it is related or I should create a separate issue for this.
I have actually multiple version of Cs:

Package A1 depends on B and C@1
Package B peerDepends on C@*

Package A2 depends on B and C@2
Package B peerDepends on C@*

Lerna can resolve only one version. C@1 simply won't be copied/symlinked into A1.

[Here's](https://github.com/szdavid92/mixxx-launchpad) the repo. In this state, it works (using mentioned workaround) with browserify. 

However after changing these lines [1](https://github.com/szdavid92/mixxx-launchpad/blob/master/packages/mk1/package.json#L8), [2](https://github.com/szdavid92/mixxx-launchpad/blob/master/packages/mk2/package.json#L8) to properly reference the corresponding dependencies by versions instead of filepaths `"1.0.0"`, `"2.0.0"`, only one of them will be installed (for me "2.0.0"). The package that depends on the other version, won't have it installed.
I guess lerna can't manage to resolve multiple versions of the same package simultaneously in the same project.

**Comment by evocateur** [comment]
A peer dependency alone is not sufficient to install it during local development, just as it is not sufficient when installing it in another package. This is no different in `lerna` as it is in `npm`, which is on-purpose (as we are simply calling `npm install` in a given directory).

Generally speaking, when you express `peerDependencies` in a package, you must also add them to the `devDependencies` to ensure the tests pass etc. Consumers that install such a package will get the benefit of `peerDependencies`, which is merely to assert that they have _also_ installed another package at such and such semver range, while avoiding the (occasionally messy) complications of a direct dependency.

**Comment by LukasBombach** [comment]
Hmm, not sure if this is a bug in lerna or if _I am doing it wrong_. I also have a case where I have a symlinked monorepo-package that has a peerDependency that it is supposed to find in the "consuming" monorepo package:

```
packages
 | - @red/app
 | - @red/gql
```

* `@red/app` has a `dependency` to `@red/gql` and to `graphql`
* `@red/gql` has a `peerDependency` to `graphql`

`@red/gql` also has a bin that makes use of `graphql` and when I execute it from `@red/app` it cannot find `graphql`.

It seems to me I am not doing anything wrong here and that this is supposed to work. It did work before we used a monorepo so I am not quite sure of @evocateur 's answer here. 

If I do `bootstrap` with the `hoist` option it does work so it appears to me that it cannot find the `graphql` package from `@red/gql` because it is symlinked and it it searching for `graphql` in the wrong folder.

**Comment by evocateur** [comment]
If hoist works, why not just do that?

A proper entry in devDependencies for the peering module will also work.

**Comment by LukasBombach** [comment]
My question is _should_ this work without `hoist`? Because _if so_, this is a bug report. And it appears to me that having a `peerDependecy` in a symlinked lerna dependency should be resolved properly

**Comment by LukasBombach** [comment]
This appears to be related: https://github.com/npm/npm/issues/5875

**Comment by evocateur** [comment]
If you have a proper dev dependency on the specified peer, it will work (exactly like a “normal” npm package). Anything else is relying on an implicit resolution, which in my opinion _should_ fail.

**Comment by LukasBombach** [comment]
I see, thank you.
