### ISSUE TITLE
Dependency of dependency not being sym linked (all are packages within repo)

### ISSUE THREAD

**Issue by ryancole** [lerna/lerna#696]
I've got several packages within my lerna repo. I've got a package that is sort of a common package and is a dependency to some of my other packages. Finally, I've got a single package that depends on a package that depends on that common base package. So, it looks something like this ...

- Package A
- Package B
  - Depends on Package A
- Package C
  - Depends on Package B

In the `node_modules` for Package C, you will find Package B sym linked, but not Package A or its dependencies.

## Expected Behavior

I expected to see Package A, and it's dependencies, installed into `node_modules` for Package C.

## Current Behavior

I see Package B is sym linked, within Package C's `node_modules`, but I see no Package A or its dependencies.

## Possible Solution

Right now, I guess I can just specify both Package A and Package B as a dependency of Package C.

## Context

I'mt not publishing public modules. I'm just using lerna as sort of a helper tool to allow me to structure my project directories as if they're separate modules. This helps me logically keep layers of things separated. Specifically, lerna simplifies the task of installing dependencies and running scripts across my packages, which helps me avoid larger tools such as Grunt, etc.

I had first mentioned this in an existing issue (#691), but that issue was specific to peer dependencies. I wanted to make this so that I don't hijack the other issue.

## Your Environment

I'm on Windows 10 64-bit, using ...

- node 7.7.1
- npm 4.1.2
- lerna 2.0.0-beta.38

**Comment by austinh** [comment]
+1 same here

**Comment by hzoo** [comment]
Please don't +1

**Comment by evocateur** [comment]
@ryancole Package C in your example never requires/imports Package A in its source code, is that correct?

When a package is required, `node` resolves all symlinks (using `realpath` or something like it) before loading the main file and starting the whole parse+execution dance. The transitive dependency (Package A) in your example _should_ work as Package B requires it, unless I am missing something?

**Comment by ryancole** [comment]
@evocateur Correct, Package C never directly required/imports Package A.

Hmm, alright. If it's supposed to be working, let me see if I can definitely rule out an issue made by myself. If I can't do so within my current project's code, I'll probably need to see if I can reproduce the issue in a sample repo.

Perhaps @austinh can provide input on his configuration so that we can cross compare and see if it sounds similar to mine.

**Comment by jacarma** [comment]
I have the same problem. If you cd to C and do:

```
yarn link B
yarn install
```

You get this in C/node_modules 
```
A
B -> ../.config/yarn/link/B
```

Note that also A is there. So I think that Lerna should be linking also A inside node_modules

**Comment by jacarma** [comment]
It's happening to me too. While I was using yarn links it worked because `yarn install` on C installed A inside the node_modules of C.

I think there could be a problem in my webpack configuration that prevents the module A to be available in C when A is not in node_modules of C (it is in B/node_modules which is linked in C/node_modules)

**Comment by jspears** [comment]
I hacked a thing to fix this problem.
[lerna-relinker](https://github.com/jspears/lerna-relinker)
Wasn't sure if it was "correct" or not, but definitely annoying.

**Comment by evocateur** [comment]
Lerna can't support myriad build tools and their violations of the node [module resolution algorithm](https://nodejs.org/dist/latest-v6.x/docs/api/modules.html#modules_all_together). The current symlinking approach is working as intended, as evidenced by the fact that any of these transitive associations work just fine when required in a node process, or indeed when the package is installed by a consumer.

**Comment by danderson00** [comment]
This is still broken. @evocateur - what are you talking about when you mention "myriad build tools"? No other build tools were mentioned in this issue.
