### ISSUE TITLE
[beta.38] Broken canary publish from CI (Travis)

### ISSUE THREAD

**Issue by Guria** [lerna/lerna#699]
Follow up from #475 

## Expected Behavior
Being able to publish from Travis CI

## Current Behavior
Publish attempt fails with error:
https://travis-ci.org/cerebral/cerebral/builds/210713536#L1979-L2002

## Possible Solution
https://github.com/lerna/lerna/pull/475#issuecomment-287948809

>`GitUtilities.getCurrentBranchDescription()` should be using `git rev-parse --abbrev-ref HEAD`, and should not be blocking a --canary publish.

**Comment by evocateur** [comment]
Current progress here: https://github.com/lerna/lerna/compare/master...evocateur:relax-git-during-canary

There's still a few weird test issues :P

**Comment by Guria** [comment]
any ETA on new release?
