### ISSUE TITLE
Diffing against last commit (push) instead of initial commit

### ISSUE THREAD

**Issue by vanesyan** [lerna/lerna#700]
## Expected Behavior

Git diff against last commit, rather than initial commit.

## Current Behavior

Lerna diffing packages against initial commit if no git tags found, it cause all packages in repository to be constantly appeared as updated, and forced me to scoping packages each time I want to publish 'em.

## Possible Solution

Git diff against last commit.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-beta.38",
  "version": "independent",
  "npmClient": "npm",

  "commands": {
    "publish": {
      "ignore": [
        "webpack.config.js",
        "*.md"
      ]
    }
  },
  "packages": [
    "packages/*"
  ]
}
```
</p></details>

## Your Environment

```
uname -a

Linux laptop 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
git version

git version 2.11.0`
```
```
npm version

{ npm: '4.4.4',
  ares: '1.10.1-DEV',
  cldr: '30.0.3',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '51',
  node: '7.7.3',
  openssl: '1.0.2k',
  tz: '2016j',
  unicode: '9.0',
  uv: '1.11.0',
  v8: '5.5.372.41',
  zlib: '1.2.11' }
```
```
yarn --version

0.21.0
```

**Comment by evocateur** [comment]
Are you passing `--skip-git` when calling `lerna publish`, perhaps? That's the first thing that springs to mind to explain why lerna isn't adding git tags during publish.

Normally, when versioning independently, lerna adds a git tag for each published package in the format `<packageName>@<version>`. Skipping git operations would be the only non-error way to avoid this behaviour.

If you've recently converted to a lerna monorepo, you may have to do an initial "kickstart" publish to get the tags to cooperate. Alternatively, you could identify the commits where the individual packages were last published and manually add tags (`git tag <packageName>@<version> <commit>`)  for those packages.

**Comment by vanesyan** [comment]
Yeah, I passing `--skip-git` as I don't want to publish tags for each package. Okay, as I understand now I need to publish tags to make lerna works as correctly?

**Comment by evocateur** [comment]
Yes, that's way lerna is designed to work. It looks less noisy when you use the default "fixed" versioning (the tag names are fairly "standard" semver `vX.x.x`), but the requirement is the same in both versioning modes.

**Comment by vanesyan** [comment]
Okay, thanks. But maybe, we can make lerna a bit more flexible, to trying diff against last pushed commits?

**Comment by evocateur** [comment]
Release tags are an integral part of responsible git-based development. For the most part, lerna is intended as a coordinator of existing programs (git, npm, yarn) and their existing idioms/patterns to accomplish its goals.

Git tags are the best solution for the question of "how many commits since the last release?". There are often many commits and pushes between releases of a given package, and we're trying to avoid rewriting `git`. "Last pushed commits" is far too ambiguous to be useful.

**Comment by vanesyan** [comment]
Okay, understand the idea :) Thanks, feel free to close the issue.
