### ISSUE TITLE
How to use the canary release?

### ISSUE THREAD

**Issue by nicojs** [lerna/lerna#702]
## Expected Behavior

I'm trying the new canary release in order to use the new conventional-changelog option (via https://github.com/conventional-changelog/conventional-changelog/issues/168)

```bash
npm i -D lerna@canary
./node_modules/.bin/lerna init
./node_modules/.bin/lerna publish  --skip-npm --skip-git --conventional-commits
```

I expect the changelog to be updated

## Current Behavior

I get this error:

```
Lerna major version mismatch: The current version of lerna is 2.0.0-beta.38-38-g8c7deb7, but the Lerna version in `lerna.json` is 2.0.0-beta.38-38-g8c7deb7. You can either run `lerna init` again or install `lerna@2.0.0-beta.38-38-g8c7deb7`.
```

## Versions:

```
$ ./node_modules/.bin/lerna --version
2.0.0-beta.38-38-g8c7deb7

$ npm --version
3.8.2

$ node --version
v7.5.0
```

**Comment by wizardzloy** [comment]
@nicojs just set the "lerna" field in your `lerna.json` to `2.0.0-beta.38-38-g8c7deb7` and it should work

**Comment by evocateur** [comment]
Huh, theoretically `lerna init` should have updated `lerna.json` appropriately. Investigating...

**Comment by evocateur** [comment]
Definitely a bug, didn't test against the `git describe` format I've been using for the canary releases. 😬

**Comment by evocateur** [comment]
@nicojs The latest canary (`lerna@2.0.0-beta.38-40-g203f7eb`) should work now.

**Comment by nicojs** [comment]
Thanks! I'll give it a spin right now
