### ISSUE TITLE
--only-explicit-updates should be renamed to discourage use

### ISSUE THREAD

**Issue by thejameskyle** [lerna/lerna#706]
Most people should not be using `--only-explicit-updates`. It causes the silent updating of local packages in git that are not published to npm until later on.

This has caused bad releases for some people using it without fully understanding what it does.

I think these names are better:

- `--dangerously-only-publish-explicit-updates`
- `--update-dependencies-without-publish`

**Comment by jwineman** [comment]
We ran into this exact issue at Cloudflare with CF-UI.  Im in favor of renaming it.

**Comment by evocateur** [comment]
I've used it when independently versioning to reduce the tag noise for changes that I _know_ are compatible (using caret versions). I can appreciate that I'm an edge case, and I was blatantly abusing the flag just so my git tag list was a little less bloated.

I see even less reason for a fixed versioning monorepo to use this, considering the drawbacks. I lean toward `--update-dependencies-without-publish` for renaming.

**Comment by hzoo** [comment]
Yeah it was only intended for backwards-compat in Babel

**Comment by thejameskyle** [comment]
lol, we could rename it `--custom-magical-flag-for-babel-and-no-one-else-do-not-use-or-ill-bite-you`

**Comment by tajo** [comment]
Can you please come up with some specific examples? 

Two libs A and B where B is a dep of A: 
1. What happens for minor bumps of B with the flag?
2. What happens for minor bumps of B without the flag?
3. What happens for major bumps of B with the flag? 
4. What happens for minor bumps of B without the flag? 

More I read about this, more confused I am.

**Comment by hzoo** [comment]
Like mentioned it wasn't meant for anyone to use, just for Babel since we had 100 pkgs and lots of dependencies where all of them were already using `^` so there was no reason to update all packages.

**Comment by thejameskyle** [comment]
The only reason that's okay for Babel to do is because they have a good understanding of Lerna and almost never make major version bumps.

**Comment by thejameskyle** [comment]
Moving to #707
