### ISSUE TITLE
--conventional-commits tries to run cli with default script runner on windows

### ISSUE THREAD

**Issue by nicojs** [lerna/lerna#708]
When running publish with `--conventional-commits` it tries to run the `conventional-recommended-bump\cli.js` with the default script runner, which is the "Windows script host" by default on windows, which results in an error. 

![issue-lerna-conventional-recommended-bump-cli](https://cloud.githubusercontent.com/assets/1828233/24185735/1852fd34-0ed5-11e7-984f-69033b6d12b7.PNG)

## Expected Behavior
I think this should be explicitly set to `node` for windows.

## Current Behavior
Error:
```
$ ./node_modules/.bin/lerna publish  --skip-npm --skip-git --conventional-commits
Lerna v2.0.0-beta.38-40-g203f7eb
Independent Versioning Mode
Checking for updated packages...
Comparing with: v0.5.9
ConventionalCommitUtilities.recommendVersion({"name":"stryker-api","version":"0.5.0-rc0","location":"C:\\z\\github\\stryker-mutator\\stryker\\pac...)
Error: Command failed: C:\z\github\stryker-mutator\stryker\node_modules\conventional-recommended-bump\cli.js -l stryker-api --commit-path=C:\z\github\stryker-mutator\stryker\packages\stryker-api -p angular
```

## Steps to Reproduce (for bugs)

1. Buy a windows machine
1. Run
```
./node_modules/.bin/lerna init
./node_modules/.bin/lerna publish  --skip-npm --skip-git --conventional-commits
```
```json
{
  "lerna": "2.0.0-beta.38-38-g8c7deb7",
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```
## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-beta.38-40-g203f7eb |
| `npm --version`  | 3.8.2 |
| `yarn --version` |  - |
| `node --version` | v7.5.0 |

| OS | Version |
| --- | --- |
| Windows 10 | |

**Comment by evocateur** [comment]
I think this is related to how npm installs binary executable files in Windows (using [`cmd-shim`](https://github.com/ForbesLindesay/cmd-shim)) and what we're actually doing, which is calling the link _target_ directly.

We should probably be calling the script with proper "local" `.bin` paths prepended, using [`execa`](https://github.com/sindresorhus/execa) instead of rolling our own.

**Comment by nicojs** [comment]
Is this something i can fix? I see you added the `execa` dependency 3 hours ago, has that anything to do with fixing this issue?

**Comment by evocateur** [comment]
Possibly, yes; execa does have a "preferLocal" config that automatically adds locally installed CLI to the PATH var. However, that doesn't really work when calling it from a globally-installed lerna. We might need to figure out a different angle of attack.

**Comment by nicojs** [comment]
IMHO installing lerna globally is a bad practice. We just install it locally and put `lerna bootstrap` in postinstall. Is this issue fixed for local lerna installations?

**Comment by evocateur** [comment]
I'm working on converting our internal child_process calls to use execa, which automatically adds npm bins to the PATH.

I don't believe this issue would be avoided in local dependencies via npm script either, as it is not creating the cmd-shim that npm does.
