### ISSUE TITLE
Use standard-changelog instead of conventional-changelog-cli

### ISSUE THREAD

**Issue by wzrdzl** [lerna/lerna#709]
`conventional-changelog-cli` through its transitive dependencies (`conventional-changelog`) brings all these guys:

```
"dependencies": {
    "conventional-changelog-angular": "^1.3.3",
    "conventional-changelog-atom": "^0.1.0",
    "conventional-changelog-codemirror": "^0.1.0",
    "conventional-changelog-core": "^1.8.0",
    "conventional-changelog-ember": "^0.2.5",
    "conventional-changelog-eslint": "^0.1.0",
    "conventional-changelog-express": "^0.1.0",
    "conventional-changelog-jquery": "^0.1.0",
    "conventional-changelog-jscs": "^0.1.0",
    "conventional-changelog-jshint": "^0.1.0"
  },
```

Since we are opinionated about the "angular" commit message format anyways we could use [standard-changelog](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/standard-changelog) which requires only `conventional-changelog-angular`.

lerna version : `2.0.0-beta.38-40-g203f7eb`

@evocateur @bcoe

**Comment by bcoe** [comment]
@wizardzloy 👍 seems reasonable; I'd like to add support to both for performing the merging logic, so that we can remove that from lerna.

**Comment by evocateur** [comment]
I wonder if `conventional-changelog` could be configured as an optional dependency, with appropriate documentation and error messages when one attempts to use the flag without the dep installed?

**Comment by bcoe** [comment]
@evocateur I'm open to this idea; I'm about to flag you on an issue in the conventional-changelog org, that I think might help clarify the direction I'd like to go in; around standardizing on the angular commit format.

**Comment by wtgtybhertgeghgtwtg** [comment]
> I wonder if conventional-changelog could be configured as an optional dependency, with appropriate documentation and error messages when one attempts to use the flag without the dep installed?

What if there was a plug-in system for `lerna`, instead?
