### ISSUE TITLE
`npm: not found` in a docker image which doesn't have node and npm in default PATH

### ISSUE THREAD

**Issue by onigoetz** [lerna/lerna#710]
I have a docker image that runs lerna, through `maven-frontend-plugin` which downloads node and npm locally and runs my scripts from there. When running `lerna publish` it breaks when trying to spawn the npm process (`npm: not found`) But npm/node was obviously found as it is running Lerna

## Expected Behavior
Publish successfully by using the current user's PATH and find the right node/npm version.

## Current Behavior
It fails because it can't find npm in the PATH

```
[INFO] Running 'node/node node_modules/.bin/lerna publish --yes --skip-temp-tag --skip-git --force-publish=* --repo-version 1.0.0-20170322173358 --canary'
[ERROR] /bin/sh: 1: git: not found
[INFO] Found HG Repository
[INFO] Lerna v2.0.0-beta.38.1
[INFO] Independent Versioning Mode
[INFO] Publishing canary build
[INFO] Checking for updated packages...
[INFO] Comparing with: sq-i18n-js@1.0.0-20170322151329:sq-i18n-react@1.0.0-20170322151329
[INFO] 
[INFO] Changes:
[INFO] - sq-i18n-js: 1.0.0-20170322151329 => 1.0.0-20170322173358
[INFO] - sq-i18n-react: 1.0.0-20170322151329 => 1.0.0-20170322173358
[INFO] 
[INFO] Assuming confirmation.
[INFO] 
[INFO] Publishing packages to npm...
[INFO] NpmUtilities.publishTaggedInDir("canary", "./packages/sq-i18n-js", "https://nexus.bank.swissquote.ch/repository/sq-npm/")
[INFO] Error: Command failed: cd /home/jenkins/workspace/sq-i18n/javascript/src/main/frontend/packages/sq-i18n-js && npm publish --tag canary
[INFO] /bin/sh: 1: npm: not found
[INFO] 
[INFO]     at ChildProcess.exithandler (child_process.js:206:12)
[INFO]     at emitTwo (events.js:106:13)
[INFO]     at ChildProcess.emit (events.js:191:7)
[INFO]     at maybeClose (internal/child_process.js:877:16)
[INFO]     at Socket.<anonymous> (internal/child_process.js:334:11)
[INFO]     at emitOne (events.js:96:13)
[INFO]     at Socket.emit (events.js:188:7)
[INFO]     at Pipe._handle.close [as _onclose] (net.js:498:12)
```

## Possible Solution
Modify the ChildProcessUtilities to add the following to each (exec, execSync, spawn and spawnStreaming) methods :

```
if (process.env.PATH) {
mergedOpts.env.PATH = process.env.PATH;
}
```
(I tried and it seems to work fine)

## Steps to Reproduce (for bugs)

I'm sorry I don't have anything public I can give you.
The steps to reproduce would be

- A docker image with java/maven
- A pom.xml with 
  - maven-frontend-plugin
  - an execution to install node + npm
  - npm install
  - npm run deploy (deploy.js is below)
- `mvn deploy`

I will try to reproduce in a more minimal environment

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-beta.38",
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}

```
</p></details>

<details><summary>deploy.js</summary><p>

```javascript
"use strict";

const childProcess = require("child_process");
const path = require("path");
const fs = require("fs");

let version = process.env.PROJECT_VERSION;

if (!version) {
  throw new Error("Could not determine the current version");
}

function getFullDate() {
  const date = new Date();

  const mm = date.getMonth() + 1; // getMonth() is zero-based
  const dd = date.getDate();
  const day = date.getFullYear() + (mm > 9 ? "" : "0") + mm + (dd > 9 ? "" : "0") + dd;

  const hh = date.getHours();
  const min = date.getMinutes();
  const sec = date.getSeconds();
  const time = (hh > 9 ? "" : "0") + hh + (min > 9 ? "" : "0") + min + (sec > 9 ? "" : "0") + sec;

  return day + time;
}

let release = true;
if (version.indexOf("SNAPSHOT") > -1) {
  release = false;
  version = version.replace("SNAPSHOT", getFullDate());
}

const lernaCommand = "node/node node_modules/.bin/lerna ";

const publishCommand = lernaCommand + "publish --yes --skip-temp-tag --skip-git --force-publish=* --repo-version " + version + (release ? "" : " --canary");
console.log("Running '" + publishCommand + "'");
childProcess.execSync(publishCommand, {stdio:[0, 1, 2], cwd: process.cwd()});
```
</p></details>

Can be run separately like this:
```
export PROJECT_VERSION =1.0.0-20170322154532 && node deploy.js
```

## Context
I can't publish my packages from my build environment. Which I would love to do to improve my release process.

## Your Environment
Fasten your seatbelt.

This command is executed by maven, running in a docker container that is a Jenkins slave, initialized by Kubernetes from jenkins running in Kubernetes as well :)

If I run the same process locally, because I have a npm version installed with nvm (4.1.2) and one installed with `apt install` (3.5.2) my own path `npm --version` returns 4.1.2 but inside lerna's `ChildProcess.exec("npm --version")` returns 3.5.2.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-beta.38 |
| `npm --version`  | 3.8.6 |
| `yarn --version` | - |
| `node --version` | v6.10.0  |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Ubuntu | 16.04 |

**Comment by onigoetz** [comment]
I made a small script to test/reproduce this : 

the result is : (ordered for clarity)

```
[INFO] noEnv: ChildProcessUtilities.exec:  FAILED Command failed: which npm && npm --version
[INFO] noEnv: ChildProcessUtilities.execSync: FAILED  Command failed: which npm && npm --version
[INFO] noEnv: ChildProcessUtilities.spawn:  FAILED Command exited with status -2: npm --version

[INFO] env: ChildProcessUtilities.exec:  /home/jenkins/workspace/sq-i18n/javascript/src/main/frontend/node/npm   3.8.6   
[INFO] env: ChildProcessUtilities.execSync: /home/jenkins/workspace/sq-i18n/javascript/src/main/frontend/node/npm   3.8.6
[INFO] env: ChildProcessUtilities.spawn:  3.8.6   
[INFO] env: ChildProcessUtilities.spawnStreaming: 3.8.6
```

```javascript
const ChildProcessUtilities = require("lerna/lib/ChildProcessUtilities");

const variants = {noEnv: {}, env: {PATH: process.env.PATH}};
for (let variant in variants) {
  const env = variants[variant];

  ChildProcessUtilities.exec("which npm && npm --version", {env: env}, (stderr, stdout) => {
    console.log(variant + ": ChildProcessUtilities.exec: ", (stderr ? "FAILED " + stderr.message : stdout.replace(/\r?\n|\r/g, "   ")));
  })

  try {
    const output = ChildProcessUtilities.execSync("which npm && npm --version", {env: env})
    console.log(variant + ": ChildProcessUtilities.execSync:", output.replace(/\r?\n|\r/g, "   "));
  } catch (e) {
    console.log(variant + ": ChildProcessUtilities.execSync: FAILED ", e.message);
  }

  ChildProcessUtilities.spawn("npm", ["--version"], {stdio: "pipe", env: env}, (stderr, stdout) => {
    console.log(variant + ": ChildProcessUtilities.spawn: ", (stderr ? "FAILED " + stderr : stdout.replace(/\r?\n|\r/g, "   ")));
  })

  ChildProcessUtilities.spawnStreaming("npm", ["--version"], {
    stdio: "pipe",
    env: env
  }, variant + ": ChildProcessUtilities.spawnStreaming: ", () => {})
}
```

**Comment by evocateur** [comment]
@onigoetz I appreciate the detailed bug report and reproductions!

Believe it or not, I have a lot of experience/scars from running `path/to/node path/to/npm/npm-cli.js <args>` from a Maven execution in almost _exactly_ the way you've described. I feel your pain.

In `master`, the npm commands with `registry` config were [fixed to mixin `process.env` correctly](https://github.com/lerna/lerna/blob/master/src/NpmUtilities.js#L125). We definitely have other opportunities to move this `process.env` (and `cwd`) config munging (so `git` commands work more consistently, etc).

Does installing the current `lerna@canary` help alleviate your problem? (we hope to have a "real" release soon)

**Comment by evocateur** [comment]
Oh, also, specific to the Maven pattern here, I think the env vars `npm_execpath` and `npm_node_execpath` might be an interesting way to solve this, by ensuring that they're always present in the (cross-platform) `opts.env` object that we pass to all `exec` and `execSync` calls.

`npm run env | grep execpath` demonstrates their value. `yarn` provides them, but it doesn't support `yarn run env` unless you add a script `"env": "env | grep execpath"` to your `package.json`.

**Comment by ChristianUlbrich** [comment]
I'd also like to chime in, I am having similar issues and a similar build chain as well (maven in docker container running npm with `maven-frontend-plugin`) and a _bind-mounted_ volume. On macOS everything of course works, however we get errors on Windows 10 with Docker _Native_. First set of problems was, rather trivial; Git was setup (as is the default), that LineEndings were _normalized_ i.e. turned into CRLF on Windows, which caused npm not being found (because I guess feeding a dockerized _Linux_ shell scripts with CRLF is no good). Second problem was, that we versioned the whole node_modules hierarchy in the repo... and we forgot about symlinks! By default symlinks are not enabled for Git on Windows (but they can, if you are admin have Windows 7+).

So if your problems are occuring on _windows_ make sure, you have proper line endings and symlinks enabled... :)

**Comment by onigoetz** [comment]
Thanks it seems it works with the latest code.
