### ISSUE TITLE
--cd-version (patch | minor) still prompting to pick version

### ISSUE THREAD

**Issue by Maxtream** [lerna/lerna#713]
Everything is explained in the title. With --cd-version attribute I still getting asked if it's a patch, minor or major update.
Using current latest version 2.0.0-beta.38. independent version, with yarn client.

**Comment by noherczeg** [comment]
@Maxtream `beta.38` did not have that feature yet. It's only present on master.

At least if I'm not mistaken, [docs](https://github.com/lerna/lerna/tree/v2.0.0-beta.38).

**Comment by evocateur** [comment]
`lerna@canary` has support for `--cd-version`. We hope to cut an official release (tentatively `2.0.0-rc.0`) soon.
