### ISSUE TITLE
ignore flag failed with publish command

### ISSUE THREAD

**Issue by Guria** [lerna/lerna#715]
## Expected Behavior
lerna publish should respect ignore flag

## Current Behavior
Seems lerna recognizes option, but it still tryies to publish package that should be ignored
https://travis-ci.org/cerebral/cerebral/builds/214933301#L1067

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-beta.37 |
| `npm --version`  | 3.10.10 |
| `node --version` | v6.10.1 |

**Comment by evocateur** [comment]
That's very odd. We don't currently have any tests of `lerna publish` that attempt to use `--ignore`, though we do have coverage of the underlying filter method. We should probably fix that.

**Comment by noherczeg** [comment]
This is somewhat related to my current investigation regarding flag support exposure so I'll look into this while am at it.

**Comment by noherczeg** [comment]
I think I have a failing test for this. Seems like it really is something going on here.

**Comment by noherczeg** [comment]
@evocateur I think this could be closed given the PR is merged.
