### ISSUE TITLE
--stream only works for single package

### ISSUE THREAD

**Issue by Robinfr** [lerna/lerna#717]
I'm running `lerna run test:watch --stream` on about 5 packages. But I only see the output of a single package. All of the packages have a `test:watch` script defined..

**Comment by evocateur** [comment]
You should use the [`--no-sort`](https://github.com/lerna/lerna#--no-sort) flag whenever streaming results from a watch command. Apologies it's not well-documented.

**Comment by Robinfr** [comment]
@evocateur thanks!
