### ISSUE TITLE
lerna run stderr

### ISSUE THREAD

**Issue by tmcw** [lerna/lerna#72]
`lerna run test` is great for running tests against collections of packages, but it's hard to determine from the error message (in my case, `Run script failed Errored while running npm script 'test' in packages.`) which package failed and how. Could it output the package that failed, or its stderr?

**Comment by thejameskyle** [comment]
Makes sense, it already should be dumping it into `lerna-debug.log`, but we can modify the logger to output the errors as well: https://github.com/kittens/lerna/blob/cdfd26ec17a4c672ee5f7f415bb0eacb22ea9723/lib/utils/logger.js#L13-L29

**Comment by tmcw** [comment]
👍 looks like this is fixed in master https://github.com/lerna/lerna/blob/master/src/logger.js
