### ISSUE TITLE
Using lerna to bootstrap inner packages with themeselves

### ISSUE THREAD

**Issue by roytz** [lerna/lerna#720]
Hi,
Sorry for not sticking to the guidelines but I have a question regarding lerna functionality.
I have this project structure:
```
-MyProject
--Package1
--Package2
--Package3
```
All 3 packages are private and what I want is for packages 1 and 2 to be able to import from package 3 (not with relative path obviously, using lerna).
How can I do that?
Will writing lerna.json under `MyProject` folder like this:
```
{
  "lerna": "2.0.0-beta.38",
  "packages": [
    "Package1",
    "Package2",
    "Package3"
  ],
  "version": "0.1.0"
}
```
will work? or it will only allow me to use those packages in `MyProject` only?

**Comment by evocateur** [comment]
Generally speaking, lerna-based monorepos have a single `packages` directory, sibling to `lerna.json`, that holds the managed packages (where "package" is defined as a directory that contains (at least) a `package.json` file):

```json
{
  "lerna": "2.0.0-beta.38",
  "version": "1.0.0"
}
```
```txt
default-monorepo/
├── lerna.json
├── package.json
└── packages
    ├── package-1
    │   └── package.json
    ├── package-2
    │   └── package.json
    └── package-3
        └── package.json
```

There is nothing stopping you, should you choose, to configure the packages elsewhere, such as all in the root. (In my experience, however, that gets messy very quickly):

```json
{
  "lerna": "2.0.0-beta.38",
  "packages": [
    "package-*"
  ],
  "version": "1.0.0"
}
```
```txt
extra/
├── lerna.json
├── package-1
│   └── package.json
├── package-2
│   └── package.json
├── package-3
│   └── package.json
└── package.json
```

The strings in the `packages` config of `lerna.json` are [globs](https://github.com/isaacs/node-glob#glob-primer) that match package directories (relative to the location of `lerna.json`). They can also be an explicit whitelist (`"packages": ["package-1", "package-2", "package-3"]` in this example), though I would imagine that gets rather unwieldy rather quickly.

Many projects will configure multiple "base" directories for different uses, such as `["packages/*", "examples/*"]`, which enables example projects (for documentation) to use relative symlinks.

I have to wonder, though: if _all_ of your packages are private, why bother with `lerna` at all?

**Comment by roytz** [comment]
@evocateur thanks for the detailed answer!
I decided to put my packages on the root (for now). They are all private (packge.json -> `private:true`). I ran `lerna bootstrap` and it indicated that the 3 packages were added but then when I try to do `require('Package2')` from a file inside Package1 I get an error saying it doesn't recognize Package2. My lerna.json file and project structure are the same as I posted on my example above. What am I doing wrong?

**Comment by evocateur** [comment]
I would definitely avoid using TitleCase to name your modules. Idiomatic npm is lowercased, with dashes between words. What you require must also match the `name` property of the module's `package.json`, not necessarily the directory name.

I'm trying to build a repro locally right now, and so far I've noticed that it indeed does not seem to work...

**Comment by evocateur** [comment]
Okay, I had a typo in my packages config, `"packages": ["package-*"]` should work. Trying the explicit whitelist now...

**Comment by evocateur** [comment]
I've validated it works with both globs and explicit whitelists. Here's my config:

```json
{
  "lerna": "2.0.0-beta.38",
  "packages": [
    "package-*"
  ],
  "version": "1.0.0"
}
```
```json
{
  "name": "root-glob-monorepo",
  "private": true,
  "scripts": {
    "postinstall": "lerna bootstrap",
    "test": "lerna run test"
  },
  "devDependencies": {
    "lerna": "2.0.0-beta.38"
  }
}
```

`package-1/package.json`:
```json
{
  "name": "@example/package-1",
  "private": true,
  "version": "1.0.0"
}
```
`package-2/package.json`:
```json
{
  "name": "package-2",
  "private": true,
  "version": "1.0.0",
  "dependencies": {
    "@example/package-1": "^1.0.0"
  }
}
```
`package-3/package.json`:
```json
{
  "name": "package-3",
  "private": true,
  "version": "1.0.0",
  "dependencies": {
    "@example/package-1": "^1.0.0",
    "package-2": "^1.0.0"
  }
}
```

The `@example/` scope isn't necessary, just demonstrating that the package name and directory are not _necessarily_ the same.

**Comment by roytz** [comment]
Thank you @evocateur !! I'll be home soon and try your solution.
By the way, what did you mean about "why using lerna if all of my packages are private"?
The thing is, I wrote some packages which in some cases use one another but I want the ability to upload them independently (maybe even to different servers).
I want something that will help me to "connect" between those packages on my development environment (but not using relative path, if possible) and on production (maybe by using git url).

**Comment by evocateur** [comment]
If you're never publishing these packages to any registry (public or private), then referencing via a relative path is the same difference, and much more robust cross-platform.

Lerna is designed to facilitate publishing multiple related packages from a single repository, enabling virtually the same workflow as the single-package-per-repository pattern. It just happens to support your usage, but there's no guarantee it will continue to do so. We certainly don't support importing lerna-bootstrapped modules from an external source directory.

If they _are_ intended to be used as npm packages, you should publish and install them as such, not use shaky workarounds like git URLs in production. You should _never_ `npm install` in production, but instead build a tarball from the result of `npm install` on a build machine and unpack the tarball into the production location.

My apologies if this sounds a bit preachy, but I'd rather you didn't contort yourself into a lerna-like shape just for the sake of using tools to avoid relative paths.

**Comment by shai32** [comment]
@evocateur 
can we we use lerna with [private modules](https://docs.npmjs.com/private-modules/intro)?

**Comment by evocateur** [comment]
@shai32 Yes, lerna supports private modules. We're just calling npm, after all.

No, lerna will not support linking git dependencies in local directories. They'll be installed by npm the same way as always. I really don't recommend git dependencies, in general, they are a leaky abstraction.

**Comment by roytz** [comment]
@evocateur thank for all the detailed answers!

**Comment by shai32** [comment]
@evocateur Do you know of an alternative to lerna that solve the the linking issues without publishing to npm?

**Comment by noherczeg** [comment]
@shai32 If you utilze a "parent package" with lerna, you could try [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) if you really want to go down this path.

**Comment by roytz** [comment]
@evocateur do you have any idea what can I do/use?

**Comment by evocateur** [comment]
If you're unable/unwilling to actually publish the packages, I would just use relative paths with a single package.json in the root. You don't appear to need any of the automatic versioning and other package management that lerna provides, and the sibling dependency symlinking is not needed when using relative paths.

**Comment by wvbe** [comment]
I've tried to go the same route with lerna (not publishing any packages yet), because:
- I would like to avoid tedious '../my-package', '../../my-package' and '../../../my-package' imports in code
- I would like to track dependencies of each individual package, rather than one monolithic package.json with everything
- I have no private registry set up yet, but intend to publish in the distant future

From reading this issue/question I'm not quite sure if my attempt is quite the same as the OP's. My packages all have the dependencies that are from the same lerna repo defined in package.json as such (packages/some-other-package/package.json):

```
"dependencies": {
    "my-package": "../my-package"
}
```

Granted I need lerna's symlinking the most, but keeping the versions in sync is also quite nice because I would ideally allow any of the modules to report its own version number in error logs etc.

Installing any of the modules through npm (without lerna) works fine. Installing all of them through `lerna bootstrap` yields the following error (where "fsds" is my project name):

```
lerna info version 2.0.0-rc.4
lerna info Bootstrapping 11 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute Error: Command failed: npm install
lerna ERR! execute npm ERR! addLocal Could not install /git/fsds/packages/fsds-util
```

Some external dependencies are now installed, but nothing from my lerna project.

**Comment by evocateur** [comment]
Currently, lerna recognizes "sibling" dependencies (from the same monorepo) by their name and matching major version. So instead of the relative paths in package.json, just use a matching caret version range (e.g., "^1.0.0"). What you describe sounds otherwise perfectly reasonable.

**Comment by wvbe** [comment]
`lerna bootstrap` actually started working for me after bumping all versions from 0.0.0 to 0.0.1.

**Comment by doug-wade** [comment]
I think we've answered all the questions here.  If I'm wrong, feel free to reopen.
