### ISSUE TITLE
`NODE_ENV=production` is not honored when installing packages

### ISSUE THREAD

**Issue by kevinpumpup** [lerna/lerna#721]
Background: I want to use `lerna bootstrap` in a production setting, but there seems no way to add a `--production` flag to the underlying npm or yarn. Therefore I am trying the `NODE_ENV` env which are used by `npm` and `yarn`. See
- https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-production
- https://docs.npmjs.com/cli/install

However, `lerna bootstrap` does not seem to honor `NODE_ENV` either.

## Expected Behavior
`lerna bootstarp` should honor `NODE_ENV` by exposing it to underlying `npm install` or `yarn install` command

## Current Behavior
`NODE_ENV` is not honored.

## Possible Solution
TBD

## Steps to Reproduce (for bugs)
https://github.com/kevinpumpup/lerna-example

- `export NODE_ENV=production`
- `yarn` or `npm install` under `packages/foo` will not install dev dependencies
- `lerna bootstrap` will install dev depedencies

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-beta.38",
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

## Context
Want to use `lerna bootstrap` in a production context.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-beta.38 |
| `npm --version`  | 3.10.3 |
| `yarn --version` | 0.21.3 |
| `node --version` | v6.5.0 |

| OS | Version |
| --- | --- |
| macOS | 10.11.6 |

**Comment by evocateur** [comment]
Thanks for the great description!

Indeed, when we are [installing dependencies](https://github.com/lerna/lerna/blob/master/src/NpmUtilities.js#L11) in a given directory, we are not [explicitly propagating `process.env`](https://github.com/lerna/lerna/blob/master/src/NpmUtilities.js#L125) to the spawned subprocess (unless you've passed `--registry` config, which is then mixed in). I _thought_ that meant it defaulted to `process.env` anyway, but this clearly indicates the wrongness of that assumption.

Does this repro if you try this with `lerna@canary`?

**Comment by kevinpumpup** [comment]
@evocateur Yes it is reproduced with `lerna@canary`.

**Comment by evocateur** [comment]
Thanks for checking. We would love a PR, if you're interested.

**Comment by arcticShadow** [comment]
Just spent all morning trying to get a CI build to run - this was the issue. I'll see if i can PR.

**Comment by arcticShadow** [comment]
This is super strange. I am unable to reproduce the issue. Because, as @evocateur suggested, child_process.spawn defaults `env` to process.env if nothing is provided. 

All I can determine is that something somewhere is introducing an object to `env` that is causing the defaults to not be used. although i've traced all the code on master and have not found anything introducing new vars. ill try on the lastest tagged (which is where my problem originated.

**Comment by arcticShadow** [comment]
I went round and round in circles for a while on this. My resolution is that Lerna does pass all environment variables through to the resulting npm process. 

My specific case was that i was trying to update the PATH, but I was calling lerna via a script, which included `nvm run` -  which mutates the path to ensure you use the correct version of node. - so my PATH mutation was happening, but was never the priority. Other env vars were being passed just fine. 

@kevinpumpup Is it possibly your environment (as it was mine) that is stopping things working?

**Comment by kevinpumpup** [comment]
@arcticShadow I just tried again with https://github.com/kevinpumpup/lerna-example and could reproduce the problem.  Basically this is what I did.
```
git pull
git clean -fdx
yarn
export NODE_ENV=production
lerna bootstrap
ls packages/foo/node_modules/
# lots of packages..
```

Are you getting different results?

**Comment by arcticShadow** [comment]
... no - im getting the same results as you Now i'm really confused. 

but heres the super weird part. 

If I add a PATH modifier to the script as well, making a directory continaing an executable 'npm' script the priority - lerna uses my script. The sole responsibility is to dump out the var's of my script. And, NODE_ENV is there, and set to production.

**Comment by arcticShadow** [comment]
i.e run lerna like `PATH=<full_path_to_your_npm_script_dir>:$PATH NODE_ENV=production lerna bootstrap`

and have a directory contiang a file called `npm` (make sure to `chmod +x` that your npm file)

NPM script:
```bash
#!/bin/bash

date > testfile.txt
env >> testfile.txt

echo "Done installing, (NOT :-) )"
exit 1
```

**Comment by arcticShadow** [comment]
There is something super strange here. And I have no more patience to figure it out. 

I have identified that, 
* running lerna master, hacking `--produciton` into the npm install command _still_ installs dev deps. 
* As far as I can tell, there is no extra info being passed to the spawned npm command that runs the install. 

I would love if someone figured this out.

**Comment by evocateur** [comment]
I do know that we [explicitly don't pass any arguments](https://github.com/lerna/lerna/blob/master/src/NpmUtilities.js#L18) to the client install command, largely to facilitate `npm` vs `yarn` differences. I'm not very sanguine about this, tbh.

**Comment by noherczeg** [comment]
I really wanted to help, but I can not think of anything else besides my previous useless PR. Event tests seem to prove that it should really work :(

**Comment by arcticShadow** [comment]
I made the same mistake :-D i.e. jumped in with a P.R. then found out it was already working.

**Comment by noherczeg** [comment]
@arcticShadow Oh, I only saw your commit. Didn't see a PR, that's why I jumped in as well.

**Comment by arcticShadow** [comment]
@noherczeg I never filled the PR, because while trying to figure out how to test it, i figured out it wasn't broken.

**Comment by erikmueller** [comment]
So I guess that only bootstrapping prod dependencies is still not working and nobody knows why? (At least I didn't really get the problem because the environment seems to be passed correclty)

**Comment by evocateur** [comment]
It’s because we mangle the package.json during installation, removing any distinction between prod and dev dependencies.

**Comment by nikku** [comment]
I've filed #1113 that should fix the issue and reliably pass `process.env` down to sub commands.

**Comment by else** [comment]
So, what is the expected way to bootstrap a monorepo for a production release which should not carry dev dependencies? Do I understand it correctly that currently there's no way to do this?

**Comment by nikku** [comment]
`NODE_ENV=foobar lerna ...` should work now. At least as of [my comment](https://github.com/lerna/lerna/pull/1113#issuecomment-344874688) mid November.

**Comment by evocateur** [comment]
Lerna manages development and publishing of several packages. It makes no difference when publishing a package if the devDependencies are present. It is not a deployment platform.

**Comment by else** [comment]
Thanks for the heads-up; it helped understanding the scope of lerna.

**Comment by Bamieh** [comment]
@evocateur True, however with things AWS microservices, the node_modules must be uploaded with the source files to the lambda.

We are using lerna as a monorepo manager for our microservices and being unable to `npm install` production only is an issue.

**Comment by evocateur** [comment]
Lerna is not a deployment tool.

**Comment by doug-wade** [comment]
@Bamieh I think you still have a couple of things you can do to make this work for you.  The first thing you might consider is hoisting all of your dev dependencies to the monorepo root -- we symlink the binaries into the appropriate .bin directories, so you can keep using them as usual.  This will mean that only production dependencies are ever installed in the modules that are uploaded to lambda.  The other thing you might consider is adding an extra step to your deploy script that runs a `lerna exec -- npm prune --production`, which would have the same effect.

**Comment by Bamieh** [comment]
@doug-wade thanks buddy, you're awesome

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
