### ISSUE TITLE
Doc request: hoist vs non-hoist

### ISSUE THREAD

**Issue by kylecordes** [lerna/lerna#724]
Lerna cross-sibling-project symlinking is fantastic! And well explained.

This is a request to enhance the docs to more full explain the hoist vs non-hoist behavior of `lerna bootstrap`. If anyone in-the-know can write some comments here, I would be happy to help with the README or any other docs.

As I understand, Lerna has these main goals:

* Assist with projects which consist of many related packages with cross dependencies.
* Assist with testing of such projects.
* Assist with publishing of such projects.
* Assist with the explosion of `npm install` time and space that ensues, as developers embrace tooling (Lerna) that makes it very easy to decompose a semantic single project in to many NPM packages.

Is this correct, particularly the last bit (which seems to be implied by `--hoist` but isn't actually stated)? (If so, it would be great for the docs to say it.)

What is the purpose of hoist and non-hoist options while running `lerna bootstrap`?

What are the use cases for which a mega-project using lerna, would prefer hoist vs not?

Is `--hoist` intended to be somewhat transparent, a runtime optimization? Or are projects expected to make many edit throughout, to accomodate `--hoist`?

Which behavior is intended as a future "best" way for lerna to behave? Hoist or not?

With `--hoist`, "... Any binaries from these dependencies will be linked into dependent package...". This makes any binaries from hoisted packages available to each package that declared a dependency, but does *not* make the hoisted packages themselves available. This is surprising - a main feature of Lerna is to symlink packages, but it does not symlink hoisted packages. What are the reasons for this?

When using `--hoist` to reduce bootstrap time, projects may be affected (greatly) by the above. Many packages may find some or all of their needed `dependencies` disappear, as they were hoisted. Is the correct use of Lerna, to craft a set `--nohoist [glob]` flags, to exclude all the `dependencies` and `devDependencies` which are needed for their contents, so that only those used only as .bin scripts are really hoisted?

Is there some other related dev tooling, which could be used with Lerna, to reduce bootstrapping time by doing something like a hoist, but symlinking things up so that dependcies are available to each package?

**Comment by evocateur** [comment]
Hoisting actually takes advantage of node's module resolution algorithm: recursing up the tree looking for `node_modules/<package>` (when the argument to require/import isn't a local path, that is). Binaries are symlinked to afford the same convenience in npm script execution, as they need to be added to the shell PATH (which npm does automagically), not resolved as a node module.

I do agree we could use better documentation in this area. I just spent a long thread earlier today explaining it to a colleague.

There are a couple lingering bugs with hoisting at the moment (sometimes transitive deps of un-hoisted deps override a hoisted version), but nothing intractable.

**Comment by kylecordes** [comment]
@evocateur To confirm I understand this right:

* The behavior I observed, where binaries get linked downward, but where the remaining contents of node_modules exist only at the "root" level, is correct.
* The node module resolution algorithm (I can probably find a documentation link) requires compatible tools looking for package A, to look in `./node_modules/A`, `../node_modules/A`, `../../node_modules/A`, `../../../node_modules/A`, etc.
* Some tooling might not do this - it might only look in the "first" `node_modules` it finds, then fail with an error if the package is missing.
* Such tooling is broken - it incorrectly implements node module resolution, and I should look there for a fix.

Is this correct?

I'm concerned this might be an obstacle to adoption - I suspect quite a lot of tooling in the node ecosystem implements looking and only a single node_modules directory unfortunately.

**Comment by evocateur** [comment]
Indeed, you are correct on those points. I appreciate the clarity of your writing :)

eslint, for example, when attempting to resolve plugins specified in a package-local .eslintrc, probably fails loudly. One advantage of lerna is that you can do all the linting from the root, maintaining consistency and reducing duplication across packages. In fact, I recommend exactly this pattern for linting and running tests. (We can definitely do better at documenting common patterns)

With the new integration test pattern I merged last night, I hope to write more tests to automatically validate these sorts of behaviors with "live" code.

**Comment by kylecordes** [comment]
@evocateur I will work on:

* PR to doc this stuff
* Issue to ask for extra symlinks, to work around tools out there that don't follow the NPM module resolution correctly.  (Unfortunate example: Angular CLI :-(   https://github.com/angular/angular-cli/issues/3864 )

**Comment by evocateur** [comment]
@kylecordes That would be great, thanks!

**Comment by Guria** [comment]
I also invented own way to hoist dependency before it became available as option in lerna:

* add "." to lerna.json in pacakages array
* add dev dependency on monorepo where it needed
* put shared deps into monorepo's package.json
* add [bin section into monorepo's package.json](https://github.com/cerebral/cerebral/blob/dea77785228a1e33df488ca4a0651d409c82ce0b/package.json#L20) to re expose binaries

Advantage here is that there is only one place to update dependencies.
But I see some drawbacks here as well:
* package dev deps become implicit
* packages node-modules polluted with extra binaries and packages symlinks that they don't need

**Comment by kylecordes** [comment]
@evocateur PR ready for a look, #751
