### ISSUE TITLE
Is the intention of lerna to ever pull dependencies based on git tags rather then npm tags?

### ISSUE THREAD

**Issue by fc** [lerna/lerna#725]
I was hoping something like this would work...
By setting a different version number in a package, it would then pull that tag version of that package out of the git repository and install that in my node_modules instead of trying to find it on the npm server.  Sure, this could be resolved using a local private npm server (verdaccio) which works but in a decentralized team environment, the added dependency of a local private npm registry seems a little overkill.
Would you be able to clarify why this is currently not the case or thoughts you may have on this?

**Comment by evocateur** [comment]
We don't plan on supporting git dependencies in the way you describe. We do support scoped packages, which are private by default (on the public registry).

Nothing about lerna stops you from using git dependencies; they are supported by npm itself after all. I don't, however, see them becoming an alternate method of "linking" monorepo siblings.

**Comment by fc** [comment]
Thanks for your response!

Are you open to the possibility of this kind of behavior? I haven't looked in-depth yet into the complexity that may be involved to achieve it but in my testing it seems like it is close to possible.
While using git dependencies would certainly work, it's less deal.   Would you open to the possibility of a PR for it?  Rather then hacking it into the existing code, I'd see it more as a plugin or module for resolving dependencies.
Also, am I the only one who has sought this desired behavior? haha

Thoughts?

**Comment by evocateur** [comment]
Resolving git tags as symlinked dependencies is not within the scope of lerna, and won't be accepted as a PR, sorry.
