### ISSUE TITLE
lerna bootstrap for a single (new package)

### ISSUE THREAD

**Issue by hzoo** [lerna/lerna#73]
We probably don't want to `lerna bootstrap` each each we create a new package so it should just `npm install` and link up that new package?

**Comment by thejameskyle** [comment]
Well `lerna bootstrap` is actually really fast if you're only updating one package. However, we should have a larger discussion about instantiating new packages, adding/removing dependencies to them, and destroying them.

**Comment by hzoo** [comment]
since `lerna bootstrap` can be run multiple times, I think we can move this to https://github.com/lerna/lerna/issues/53
