### ISSUE TITLE
lerna publish inserts _package into package.json

### ISSUE THREAD

**Issue by timdp** [lerna/lerna#741]
After upgrading from 2.0.0-beta.38 to 2.0.0-rc.0, `lerna publish` failed with:

```
Error: Command failed: npm publish --tag lerna-temp
npm ERR! No name provided
```

After that error, I was left with a repo where lerna had created a new commit for the version, which didn't just bump the version number for every package, but also moved the entire package.json structure into a subkey called `_package`. E.g., `{"name": "foo"}` became `{"_package":{"name": "foo"}}`. That obviously caused npm not to find the `name` property anymore and bail.

I'm guessing some private property is being included in the serialized JSON?

This is with Node 7.7.2 and npm 4.4.4 on Ubuntu 16.04.

**Comment by evocateur** [comment]
Oh geez, sorry! Will fix ASAP
