### ISSUE TITLE
Remove `--skip-temp-tag` (or make it the default)

### ISSUE THREAD

**Issue by hzoo** [lerna/lerna#742]
> --skip-temp-tag

> When activated, this flag will alter the default publish process by not creating a temporary tag and handling the process accordingly. Instead it will immediately publish with the proper dist-tag as npm it self would. 

This isn't really necessary anymore since packages are published in topological order now. As a separate issue we do need to handle publish issues, and for others that still want it, we should make the opposite flag to turn it back on. Since you may publish 1 package but the others fail so you are safe from it being on `latest`.

**Comment by noherczeg** [comment]
This might overlap a bit with [my work-in-progress flag handling PR](https://github.com/lerna/lerna/pull/719) in a way that if we follow [yargs's arg patterns](https://github.com/yargs/yargs#negate-fields), flags and their negated versions come without any public breaking changes.

Back when I introduced it I didn't follow this patterns so the "skip-" part won't fit in, but it eventually gets merged in we might only want to consider the "renaming" of the current version to `--no-temp-tag` and flip `temp-tag`'s default to true.

**Comment by noherczeg** [comment]
I'll check tomorrow if I create a "temp-tag" flag with a default value of `false` what will happen. In that case yargs should handle it as such and if someone would like to create the temp tag for some reason they can still add in the `--temp-tag` flag.

**Comment by noherczeg** [comment]
The change requires the testing toolkit to be modified/upped a bit so it'll take some time. Sorry for that.
