### ISSUE TITLE
Lerna should do unpublish when failing in publishing

### ISSUE THREAD

**Issue by mocheng** [lerna/lerna#754]
## Expected Behavior
During the execution of `lerna publish`, if there is new commit to remote branch, it falls into a inconsistent state. Since `lerna` makes local commit and then publishing modules to npm registry and then push to remote, it would successfully published to npm registry and fails to push to remote branch. 

When in this situation, we have to manually unpublish packages that are just published and try it over.

## Possible Solution

It would be preferable to make `lerna publish` act like transaction. If anything wrong while publishing, it just unpublishses packages.

**Comment by evocateur** [comment]
If your package published successfully to the registry but your repo didn't successfully push to origin, why not just `git pull --rebase && git push origin --tags`? Lerna is mostly just calling repetitive and boring commands for you, it isn't doing any special dark magic.

**Comment by logotype** [comment]
Perhaps error message could be improved at least? It's not immediately clear what's happening and why (when I tried to publish, I suddenly saw a bunch of `error: failed to push some refs` stack traces in the console, repeatedly). Those messages can be in the debug log sure, but perhaps common errors can be be more user friendly?

**Comment by evocateur** [comment]
I agree, the logging can be improved (here, and in general).

**Comment by mocheng** [comment]
@evocateur Thanks for your info.
In this case, `git pull --rebase` might not be a good idea, Since it makes remote commit parent of local bump-version-commit as below.

```
* local commit that bumps version (with tags)
* remote commit
* common base
```

This makes tagged commit includes content of remote commit which is not actually published to registry.

`git pull` looks better even though it adds a merge commit.
```
*   merge commit
|\
| *  local commit that bumps version (with tags)
* |  remote commit
|/
* common base
```

**Comment by evocateur** [comment]
hmm, yeah. I wonder if it would make sense to re-order the git push to _before_ the npm publish?

**Comment by jvivs** [comment]
@evocateur that seems to make sense to me too in general.

Seems like a good idea to only publish after making a best effort to verify publishing preconditions. 

Would it be worth running all the preflight scripting (pull latest tags, check mergable status w/ origin, test, build, perversion, etc) to verify the publish would be successful, then tag and push latest tag to origin as the last step before actually publishing to a registry?

**Comment by noahpeters** [comment]
@evocateur I have a similar situation. We execute `lerna publish` from CI systems and it is difficult to build in problem resolution strategies for failures. If lerna publish failures would leave git/npm in a consistent state that didn't require manual intervention and didn't effect future publish actions, that would be great. Right now, if a subsequent push to master occurs after the CI build begins, it will fail to do the git push and someone will have to go manually unpublish the packages.

**Comment by mocheng** [comment]
@noahpeters Doing "lerna publish" in CI might leave hard-to-clean situation on failure. That's the reason why we have to do publish locally.

**Comment by roastlechon** [comment]
Has anyone figured a better solution than `git pull` in a CI situation?

**Comment by madbonez** [comment]
in case with unexpected commit before lerna push we use this approach (with gitlab api)
you can protect your branch, build and finally do unprotect
curl --request PUT --header "PRIVATE-TOKEN: Dt4U34pz3pS111vx54Nx" https://buildserver.host.ru/api/v4/projects/23/repository/branches/test/protect (unprotect)
