### ISSUE TITLE
lerna publish report npm ERR! you do not have permission to publish "aa". 

### ISSUE THREAD

**Issue by Vincent2015** [lerna/lerna#755]
I didn't find how to login "npm repo " when publish.

and after i logined  "npm repo",execute "lerna publish", the error was same

**Comment by noherczeg** [comment]
Please provide a full error log with npm, node and lerna versions.

**Comment by aaronmcadam** [comment]
@Vincent2015 Try using [this issue template](https://github.com/lerna/lerna/blob/master/.github/ISSUE_TEMPLATE.md) to give everyone a bit more detail about your use case

**Comment by Vincent2015** [comment]
@aaronmcadam @noherczeg 


Publishing packages to npm...
NpmUtilities.publishTaggedInDir("lerna-temp", "./packages/aa", )
Error: Command failed: npm publish --tag lerna-temp
npm ERR! publish Failed PUT 403
npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/node" "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/npm" "publish" "--tag" "lerna-temp"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E403

npm ERR! you do not have permission to publish "aa". Are you logged in as the correct user? : aa
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qiupengchao/work/saas/lerandemo/packages/aa/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Attempting to retry publishing aa...
Error: Command failed: npm publish --tag lerna-temp
npm ERR! publish Failed PUT 403
npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/node" "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/npm" "publish" "--tag" "lerna-temp"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E403

npm ERR! you do not have permission to publish "aa". Are you logged in as the correct user? : aa
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qiupengchao/work/saas/lerandemo/packages/aa/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
NpmUtilities.publishTaggedInDir("lerna-temp", "./packages/aa", )
Error: Command failed: npm publish --tag lerna-temp
npm ERR! publish Failed PUT 403
npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/node" "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/npm" "publish" "--tag" "lerna-temp"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E403

npm ERR! you do not have permission to publish "aa". Are you logged in as the correct user? : aa
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qiupengchao/work/saas/lerandemo/packages/aa/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Attempting to retry publishing aa...
Error: Command failed: npm publish --tag lerna-temp
npm ERR! publish Failed PUT 403
npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/node" "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/npm" "publish" "--tag" "lerna-temp"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E403

npm ERR! you do not have permission to publish "aa". Are you logged in as the correct user? : aa
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qiupengchao/work/saas/lerandemo/packages/aa/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
NpmUtilities.publishTaggedInDir("lerna-temp", "./packages/aa", )
Error: Command failed: npm publish --tag lerna-temp
npm ERR! publish Failed PUT 403
npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/node" "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/npm" "publish" "--tag" "lerna-temp"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E403

npm ERR! you do not have permission to publish "aa". Are you logged in as the correct user? : aa
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qiupengchao/work/saas/lerandemo/packages/aa/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Attempting to retry publishing aa...
Error: Command failed: npm publish --tag lerna-temp
npm ERR! publish Failed PUT 403
npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/node" "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/npm" "publish" "--tag" "lerna-temp"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E403

npm ERR! you do not have permission to publish "aa". Are you logged in as the correct user? : aa
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qiupengchao/work/saas/lerandemo/packages/aa/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
NpmUtilities.publishTaggedInDir("lerna-temp", "./packages/aa", )
Error: Command failed: npm publish --tag lerna-temp
npm ERR! publish Failed PUT 403
npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/node" "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/npm" "publish" "--tag" "lerna-temp"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E403

npm ERR! you do not have permission to publish "aa". Are you logged in as the correct user? : aa
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qiupengchao/work/saas/lerandemo/packages/aa/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
Attempting to retry publishing aa...
Error: Command failed: npm publish --tag lerna-temp
npm ERR! publish Failed PUT 403
npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/node" "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/npm" "publish" "--tag" "lerna-temp"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E403

npm ERR! you do not have permission to publish "aa". Are you logged in as the correct user? : aa
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qiupengchao/work/saas/lerandemo/packages/aa/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
NpmUtilities.publishTaggedInDir("lerna-temp", "./packages/aa", )
Error: Command failed: npm publish --tag lerna-temp
npm ERR! publish Failed PUT 403
npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/node" "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/npm" "publish" "--tag" "lerna-temp"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E403

npm ERR! you do not have permission to publish "aa". Are you logged in as the correct user? : aa
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qiupengchao/work/saas/lerandemo/packages/aa/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Ran out of retries while publishing aa
Error: Command failed: npm publish --tag lerna-temp
npm ERR! publish Failed PUT 403
npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/node" "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/npm" "publish" "--tag" "lerna-temp"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E403

npm ERR! you do not have permission to publish "aa". Are you logged in as the correct user? : aa
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qiupengchao/work/saas/lerandemo/packages/aa/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Errored while running PublishCommand.execute
Error: Command failed: npm publish --tag lerna-temp
npm ERR! publish Failed PUT 403
npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/node" "/Users/qiupengchao/.nvm/versions/node/v6.9.5/bin/npm" "publish" "--tag" "lerna-temp"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E403

npm ERR! you do not have permission to publish "aa". Are you logged in as the correct user? : aa
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qiupengchao/work/saas/lerandemo/packages/aa/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by evocateur** [comment]
@Vincent2015 [`npm adduser`](https://docs.npmjs.com/cli/adduser) is the command you're looking for. This error isn't `lerna`'s fault.

**Comment by MatteoGabriele** [comment]
This error is caused also when managing more than one npm user and accidentally you try to publish a package with the wrong one.

I will suggest at least that tags and commit are applied after a positive publish on npm, otherwise every time this error happen, we need to manually remove the version tag and hard reset to the previous commit.

Thanks anyway :)

**Comment by evocateur** [comment]
Publishing to npm has absolutely no requirement on the git commit being present in a public repo, and the opposite is true as well. When a publish fails, you can simply go into the directory where it failed and type `npm publish` again. It's basically the same difference, as that's all lerna is doing anyway with respect to publishing packages to npm.

I do agree that lerna's error handling and retry mechanisms need some improvement. Being able to publish the existing version without bumping would be a good start, for example.

**Comment by MatteoGabriele** [comment]
true, but the error is not super user friendly and also when you have a lot of packages can be quite annoying:  but i get your point.

i was just wondering this: if an error occurs,  lerna could put the previous version back or discard all changes,  so that's possible to try again without too much pain. 

but thanks for the response. this tool is really handy and this can be a small price to pay :)

**Comment by thomasfr** [comment]
In my case the problem was that i was logged in with npm but was using `yarn run lerna publish`. Solution was to either login with yarn (`yarn login`) or use npm (`npm run lerna publish`) and make sure you are loggedin

**Comment by lostintangent** [comment]
Like @thomasfr, I was hitting this error, and it turned out to be because I was running `lerna publish` via a `yarn` command (`yarn release`), even though I was logged in with `yarn`. As soon as I run `npm run release`, everything worked perfectly.

Is there a workaround for this that allows you to continue to use `yarn` instead of `npm`? I'm guessing I'm doing something wrong, but I'm definitely logged in to both `yarn` and `npm`, but I can only successfully run `lerna publish` via an `npm` script, not a `yarn` script.
