### ISSUE TITLE
Custom version prompt does not work.

### ISSUE THREAD

**Issue by timdorr** [lerna/lerna#757]
## Expected Behavior
Entering a custom version should submit when hitting Enter

## Current Behavior
The same version string is printed on the screen. The prompt is cleared, remains on screen, and nothing happens. Here's what it looks like:

<img width="619" alt="screen shot 2017-04-12 at 3 55 21 pm" src="https://cloud.githubusercontent.com/assets/17882/24976819/ed5003c8-1f98-11e7-848c-cf59569e9970.png">
Up top is the result if I enter a valid version. If I hit Enter below, it submits a blank value which is not semver valid.

## Steps to Reproduce (for bugs)
1. In independent version mode, run `lerna publish`
2. Choose a custom version for a package
3. Enter any semver valid version
4. Collect underpants
5. ...
6. Profit?

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.1 |
| `npm --version`  | 4.2.0 |
| `yarn --version` | 0.22.0 |
| `node --version` | v7.8.0 |

**Comment by evocateur** [comment]
Not surprising, given that it's completely uncovered by tests (which we should fix)!

**Comment by timdorr** [comment]
BTW, I'm only doing this as a hack to avoid publishing a particular package (maybe there should be a skip option?). I was able to get around it by commenting out [the `validate` check](https://github.com/lerna/lerna/blob/master/src/commands/PublishCommand.js#L339). I guess the return type isn't what Inquirer wants?

**Comment by evocateur** [comment]
#728 fixed the `--ignore` flag behaviour with `lerna publish`, perhaps you could try `lerna publish --ignore react-router-native` ?

**Comment by evocateur** [comment]
and yeah, that `validate` method looks fishy

**Comment by noherczeg** [comment]
I'll grab this one soon™

**Comment by timdorr** [comment]
> #728 fixed the --ignore flag behaviour with lerna publish, perhaps you could try lerna publish --ignore react-router-native?

Yeah, that's the one I was looking for. Thanks!
