### ISSUE TITLE
Don't use semver ranges

### ISSUE THREAD

**Issue by amasad** [lerna/lerna#76]
Currently, if a library relies on a Babel package and they try to lockdown the dependency version they will invariably get updates since Babel packages uses "^" all over. That means that if we do a release with a regression we would break people's packages and CI's even though they tried to lock down the version.

A core feature of monorepos is explicit dependency management. Since we update everything atomically we have the opportunity to lockdown dependencies. That may mean more minor version releases but that also means more safety.

**Comment by amasad** [comment]
@kittens was using `^` a conscious decisions or did you just go with the default? Any thoughts on this?

**Comment by thejameskyle** [comment]
That makes sense to me, it would simplify things I think.

However, this will make https://github.com/kittens/lerna/issues/27 an issue not just for major versions but for minor and patch versions, so they'll have to be done at the same time.

**Comment by kittens** [comment]
@amasad It was. Deduping is very ineffective unless you use ranges. I'm pretty strongly against this, it isn't the right tool for the job. If you want locked transitive dependencies then use a shrinkwrap.

**Comment by thejameskyle** [comment]
Gonna close this since people should just use Yarn and have lockfiles 😛
