### ISSUE TITLE
lerna publish:Error: Command failed: git rev-parse --abbrev-ref HEAD fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by Vincent2015** [lerna/lerna#763]
bogon:lerandemo qiupengchao$ lerna  publish
Lerna v2.0.0-rc.1
Current version: 1.1.1
Checking for updated packages...
No tags found! Comparing with initial commit.
? Select a new version (currently 1.1.1) Minor (1.2.0)

Changes:
- aa: 1.1.1 => 1.2.0

? Are you sure you want to publish the above changes? Yes
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
GitUtilities.getCurrentBranch ({"cwd":"."})
Error: Command failed: git rev-parse --abbrev-ref HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at checkExecSyncError (child_process.js:483:13)
    at Object.execSync (child_process.js:523:13)
    at Function.execSync (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/ChildProcessUtilities.js:68:44)
    at getCurrentBranch (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/GitUtilities.js:148:46)
    at Function.descriptor.value (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/logger.js:146:33)
    at isDetachedHead (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/GitUtilities.js:65:37)
    at Function.descriptor.value (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/logger.js:146:33)
    at PublishCommand.execute (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/commands/PublishCommand.js:167:55)
    at PublishCommand._attempt (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/Command.js:219:21)
    at /Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/Command.js:204:15
GitUtilities.isDetachedHead   ({"cwd":"."})
Error: Command failed: git rev-parse --abbrev-ref HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at checkExecSyncError (child_process.js:483:13)
    at Object.execSync (child_process.js:523:13)
    at Function.execSync (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/ChildProcessUtilities.js:68:44)
    at getCurrentBranch (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/GitUtilities.js:148:46)
    at Function.descriptor.value (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/logger.js:146:33)
    at isDetachedHead (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/GitUtilities.js:65:37)
    at Function.descriptor.value (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/logger.js:146:33)
    at PublishCommand.execute (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/commands/PublishCommand.js:167:55)
    at PublishCommand._attempt (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/Command.js:219:21)
    at /Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/Command.js:204:15
Errored while running PublishCommand.execute
Error: Command failed: git rev-parse --abbrev-ref HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at checkExecSyncError (child_process.js:483:13)
    at Object.execSync (child_process.js:523:13)
    at Function.execSync (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/ChildProcessUtilities.js:68:44)
    at getCurrentBranch (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/GitUtilities.js:148:46)
    at Function.descriptor.value (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/logger.js:146:33)
    at isDetachedHead (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/GitUtilities.js:65:37)
    at Function.descriptor.value (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/logger.js:146:33)
    at PublishCommand.execute (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/commands/PublishCommand.js:167:55)
    at PublishCommand._attempt (/Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/Command.js:219:21)
    at /Users/qiupengchao/.nvm/versions/node/v6.9.5/lib/node_modules/lerna/lib/Command.js:204:15

**Comment by evocateur** [comment]
Please use the issue template: https://raw.githubusercontent.com/lerna/lerna/master/.github/ISSUE_TEMPLATE.md

In this case, `git --version` would also be appropriate.

**Comment by Vincent2015** [comment]
bogon:lerandemo qiupengchao$ git --version
git version 2.10.1 (Apple Git-78)
bogon:lerandemo qiupengchao$

**Comment by otbe** [comment]
Same issue here. Fails with:
```
lerna info version 2.0.0-rc.4
lerna ERR! initialize Error: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
lerna ERR! initialize Use '--' to separate paths from revisions, like this:
lerna ERR! initialize 'git <command> [<revision>...] -- [<file>...]'
lerna ERR! initialize
lerna ERR! initialize     at Function.module.exports.sync (/Users/boo/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/node_modules/execa/index.js:277:26)
lerna ERR! initialize     at Function.execSync (/Users/boo/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/ChildProcessUtilities.js:51:30)
lerna ERR! initialize     at Function.getCurrentSHA (/Users/boo/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/GitUtilities.js:193:49)
lerna ERR! initialize     at ImportCommand.initialize (/Users/boo/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/commands/ImportCommand.js:136:51)
lerna ERR! initialize     at ImportCommand._attempt (/Users/boo/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/Command.js:265:21)
lerna ERR! initialize     at ImportCommand.runCommand (/Users/boo/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/Command.js:251:12)
lerna ERR! initialize     at ImportCommand.run (/Users/boo/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/Command.js:148:12)
lerna ERR! initialize     at Object.handler (/Users/boo/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/commands/ImportCommand.js:53:53)
lerna ERR! initialize     at Object.self.runCommand (/Users/boo/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/node_modules/yargs/lib/command.js:231:22)
```

```$ git --version
git version 2.11.0 (Apple Git-81)
```

Im using ```2.0.0-rc.4``` right now on a new created (lerna init) test repo.

**Comment by devmao** [comment]
OS: Ubunut
Git: 2.7.4
Lerna: 2.0.0-rc.4

```
lerna info version 2.0.0-rc.4                                                                                                                                                  
lerna info versioning independent                                                                                                                                              
lerna ERR! initialize Error: No repository found at "https://devmao@bitbucket.org/pricefx/pricefx-sfdc-canvas.git"                                                             
lerna ERR! initialize     at ImportCommand.initialize (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/lib/commands/ImportCommand.js:109:27)                       
lerna ERR! initialize     at ImportCommand._attempt (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/lib/Command.js:265:21)                                        
lerna ERR! initialize     at ImportCommand.runCommand (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/lib/Command.js:251:12)                                      
lerna ERR! initialize     at ImportCommand.run (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/lib/Command.js:148:12)                                             
lerna ERR! initialize     at Object.handler (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/lib/commands/ImportCommand.js:53:53)                                  
lerna ERR! initialize     at Object.self.runCommand (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/node_modules/yargs/lib/command.js:231:22)                     
lerna ERR! initialize     at Object.Yargs.self._parseArgs (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/node_modules/yargs/yargs.js:990:30)                     
lerna ERR! initialize     at Object.Yargs.self.parse (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/node_modules/yargs/yargs.js:533:23)                          
lerna ERR! initialize     at Object.<anonymous> (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/bin/lerna.js:4:25)                                                
lerna ERR! initialize     at Module._compile (module.js:570:32)                                                                                                                
lerna ERR! initialize  callback with error                                                                                                                                     
lerna ERR! initialize  Error: No repository found at "https://devmao@bitbucket.org/pricefx/pricefx-sfdc-canvas.git"                                                            
lerna ERR! initialize     at ImportCommand.initialize (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/lib/commands/ImportCommand.js:109:27)                       
lerna ERR! initialize     at ImportCommand._attempt (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/lib/Command.js:265:21)                                        
lerna ERR! initialize     at ImportCommand.runCommand (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/lib/Command.js:251:12)                                      
lerna ERR! initialize     at ImportCommand.run (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/lib/Command.js:148:12)                                             
lerna ERR! initialize     at Object.handler (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/lib/commands/ImportCommand.js:53:53)                                  
lerna ERR! initialize     at Object.self.runCommand (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/node_modules/yargs/lib/command.js:231:22)                     
lerna ERR! initialize     at Object.Yargs.self._parseArgs (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/node_modules/yargs/yargs.js:990:30)                     
lerna ERR! initialize     at Object.Yargs.self.parse (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/node_modules/yargs/yargs.js:533:23)                          
lerna ERR! initialize     at Object.<anonymous> (/home/mao/.nvm/versions/node/v6.10.1/lib/node_modules/lerna/bin/lerna.js:4:25)                                                
lerna ERR! initialize     at Module._compile (module.js:570:32)
```

**Comment by devmao** [comment]
same also issue with git 2.11.0

**Comment by otbe** [comment]
@devmao 
I guess you have to pass a file system path not a remote URL. So try to clone the repo and use this path :)

**Comment by devmao** [comment]
@otbe same issue with a path, relative or absolute.

**Comment by iyobo** [comment]
Same issue here

**Comment by iyobo** [comment]
Okay looks like I found a fix for this.
This issue only comes up when I try to lerna import into a lerna repo with uncommited changes.

Commit all changes in your monorepo and have a clean tree before attempting to import another package and it's git history. I suppose it makes sense :)

**Comment by evocateur** [comment]
I could have sworn we already throw an error when the local tree had uncommitted changes. In any case, thank you for investigating!

**Comment by devmao** [comment]
@iyobo yes, it's the solution for me too.
lerna really need to provide some sort of checking for these trivial mistakes to report useful error messages.
