### ISSUE TITLE
Workflow for supporting private & public packages

### ISSUE THREAD

**Issue by khoomeister** [lerna/lerna#766]
If I have a privately hosted monorepo that has some components I want to share on public Github, is there a way to do so seamlessly?  I know I can publish them to npm already, but it'd be great to have npm packages that could link directly to public github repos.

I did try an unconventional setup - see below directory structure:

```
root directory with lerna.json (no git repo)
  |-- public directory with public packages (github repo)
  |--private directory with private packages (private repo) (all package.json files have private: "true")
```

In this case, lerna.json would specify `packages: ["public/*", "private/*"]`.

I tried running `lerna publish --skip-git`, however lerna has a direct coupling between lerna.json and the root directory being the git repo.  lerna complains when the directory with lerna.json is not a git repo.

I also tried an alternative where a private monorepo references public packages outside that directory, however lerna complains that the public files are outside the repository.

These approaches I mentioned kinda break how lerna is supposed to work (i.e. the concept of a monorepo - lerna.json to one repo relationship), so I'm not necessarily asking anyone to implement them.  I'm mainly interested in a seamless approach to private and public packages, so if something like that already exists or if anyone has thoughts, I'd be interested to know.

I'm sure there's plenty of locked down code behind walls interspersed with open sourceable code that could benefit from whatever the solution to this problem is.

**Comment by khoomeister** [comment]
Thinking about this more, you just need a way of automating `npm link` a bit more.

Let's say you have a private monorepo.  Once you have a package you want to make public, you break it out to its own repo/directory, and there's a new setting in `lerna.json` that npm links all dependencies of the same name to that directory when you call bootstrap.

e.g.

```json
{
  "local": {
    "my-package": "~/namespace/my-package"
  }
}
```

That'd be the extent of lerna's responsibilities.  You handle publish, etc. of this package yourself since it's technically not part of the monorepo.

**Comment by evocateur** [comment]
If you've gone to the trouble of open-sourcing something, extracting it into a separate repo and everything, then it should just become another external dependency in your monorepo. It's beyond the scope of `lerna` to automate `npm link` (which is notably never called, internally). You can still use `npm link` for local development, just like any npm package.
