### ISSUE TITLE
Hoisting broken in lerna@2.0.0-rc.2 ???

### ISSUE THREAD

**Issue by brentertz** [lerna/lerna#768]
Greetings.

I am updating a project from `lerna@2.0.0-beta.38` to `lerna@2.0.0-rc.2` and have noticed that `lerna bootstrap --hoist` is taking much longer.  

The following commands were run immediately following an `npm install` at the repo root;

Using `lerna@2.0.0-beta.38` - very fast
![master](https://cloud.githubusercontent.com/assets/202773/25067027/a1d2d944-21f4-11e7-90c3-9bbd97a34216.png)

Using `lerna@2.0.0-rc.2` - very slow
![update-lerna](https://cloud.githubusercontent.com/assets/202773/25067024/9c49ba42-21f4-11e7-8159-763fd66fb6dc.png)

Using `lerna@2.0.0-rc.2`, shared dependencies for the individual packages do not appear to be getting hoisted at all, but rather each package's node_modules is full of shared dependencies.  

This is contrast to using `lerna@2.0.0-beta.38`, in which case the node_modules folder for the individual packages just contains symlinks.

## Expected Behavior

I would expect shared dependencies from individual packages to be hoisted to the main package root.

## Current Behavior

Shared dependencies from individual packages are not getting hoisted, but instead are duplicated in each package's node_modules.

## Steps to Reproduce (for bugs)

1.  Clone my repo. `git clone https://github.com/mineral-ui/mineral-ui.git`
2.  Switch to the "update-lerna" branch. `git checkout update-lerna`
3.  Install dependencies. `npm install`
4.  Run bootstrap script. `npm run bootstrap`
5.  Note how long it takes.  Also, note the contents of the `node_modules` folders for any of the packages.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.2",
  "packages": [
    "packages/*",
    "packages/components/*"
  ],
  "version": "independent"
}

```
</p></details>

## Context

Attempting to update lerna in order to take advantage of new features, such as `--conventional-commits` flag and automated changelog generation.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.2 |
| `npm --version`  | 3.10.10 |
| `node --version` | v6.10.2 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS El Capitan | 10.11.6 |

**Comment by evocateur** [comment]
@brentertz Thanks for the great bug report! The repo repro will definitely help figure out the root cause.

**Comment by justinwilaby** [comment]
This is a problem for us as well. Blocked a team of 6 devs for 8 hours :(

**Comment by evocateur** [comment]
I was up until 2am working on a resolution for this. Release will commence as soon as I get to my desk.

**Comment by evocateur** [comment]
Well, poop, `v2.0.0-rc.3` didn't really solve this. Still taking about a minute to `lerna bootstrap --hoist` on the repo provided, and the logging is absolute shite so I have no idea why it's bogging down.

**Comment by hzoo** [comment]
I'm sorry if it's broken, but I would just revert back, it's easy to revert back to a previous version with lerna since it's just 1 package. Maybe don't use `^` if you are as well.

**Comment by nicojs** [comment]
In the mean time, people might be able to use https://www.npmjs.com/package/link-parent-bin

**Comment by brentertz** [comment]
Thanks @nicojs. I was able to use `link-parent-bin` to skirt the hoisting issue.  It had the added benefit of enabling me to clean up individual package devDependencies which were being included solely to enable use in npm scripts.
