### ISSUE TITLE
Lerna bootstrap failing

### ISSUE THREAD

**Issue by dptoot** [lerna/lerna#785]
## Expected Behavior
Lerna should bootstrap supplied packages.

## Current Behavior
Lerna appears to be removing a good portion of  the package.json files for each package and then failing to bootstrap as "No name provided in package.json"

## Steps to Reproduce (for bugs)

This seems to happen after several successful lerna bootstrap and lerna clean commands have been processed
1. lerna clean
2. lerna bootstrap

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "lerna": "2.0.0-rc.3",
  "packages": [
    "packages/*",
    "packages/axl-storybook/demo"

  ],
  "version": "0.0.0"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
lerna(info)    Lerna v2.0.0-rc.3
lerna(verbose) GitUtilities.isInitialized    ("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook")
lerna(verbose) GitUtilities.isInitialized    ("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook") => true
lerna(verbose) FileSystemUtilities.existsSync("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook\\VERSION")
lerna(verbose) FileSystemUtilities.existsSync("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook\\VERSION") => false
lerna(verbose) Attempting running BootstrapCommand.initialize
lerna(verbose) Successfully ran BootstrapCommand.initialize
lerna(verbose) Attempting running BootstrapCommand.execute
lerna(info)    Bootstrapping 3 packages
lerna(info)    Preinstalling packages
lerna(info)    Installing external dependencies
lerna(verbose) NpmUtilities.installInDir     ("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook\\packages\\axl-storybook", ["babel-config-atc@^1....)
lerna(verbose) FileSystemUtilities.rename    ("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook\\packages\\axl-storybook\\package.json", "C:\\Use...)
lerna(verbose) NpmUtilities.installInDir     ("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook\\packages\\smart-knobs", ["babel-config-atc@^1.0....)
lerna(verbose) FileSystemUtilities.rename    ("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook\\packages\\smart-knobs\\package.json", "C:\\Users...)
lerna(verbose) NpmUtilities.installInDir     ("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook\\packages\\axl-storybook\\demo", ["babel-config-a...)
lerna(verbose) FileSystemUtilities.rename    ("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook\\packages\\axl-storybook\\demo\\package.json", "C...)
lerna(verbose) FileSystemUtilities.rename    ("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook\\packages\\axl-storybook\\package.json", "C:\\Use...) => 
lerna(verbose) FileSystemUtilities.rename    ("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook\\packages\\smart-knobs\\package.json", "C:\\Users...) => 
lerna(verbose) FileSystemUtilities.rename    ("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook\\packages\\axl-storybook\\demo\\package.json", "C...) => 
lerna(verbose) FileSystemUtilities.renameSync("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook\\packages\\axl-storybook\\demo\\package.json.lern...)
lerna(verbose) FileSystemUtilities.renameSync("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook\\packages\\axl-storybook\\demo\\package.json.lern...) => 
lerna(error)   NpmUtilities.installInDir     ("C:\\Users\\jelewis1\\Desktop\\work\\axl-storybook\\packages\\axl-storybook\\demo", ["babel-config-a...)
    Error: Command failed: npm install
    npm ERR! addLocal Could not install C:\Users\jelewis1\Desktop\work\axl-storybook\packages\smart-knobs
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
    npm ERR! node v6.9.4
    npm ERR! npm  v3.10.10
    
    npm ERR! No name provided in package.json
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\jelewis1\Desktop\work\axl-storybook\packages\axl-storybook\demo\npm-debug.log
    
        at Promise.all.then.arr (C:\Users\jelewis1\AppData\Roaming\npm\node_modules\lerna\node_modules\execa\index.js:210:11)
        at process._tickCallback (internal/process/next_tick.js:103:7)
lerna(error)   Errored while running BootstrapCommand.execute
```
</p></details>

## Context

Full disclosure: first usage of Lerna :)

Everything seemed to be working smoothly .  Then, as before,  any call to lerna bootstrap will cause this issue to occur.   At that point the repo is rendered unusable until I delete lerna.json and re-init.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.3 |
| `npm --version`  | 3.10.10 |
| `node --version` | v6.9.4|

| OS | Version |
| --- | --- |
| Windows 7 | - |

**Comment by spudly** [comment]
This line from `lerna-debug.json` seems like the problem:

```
    npm ERR! No name provided in package.json
```

One of your packages has a package.json file without a "name" key/value pair.

**Comment by dptoot** [comment]
Oh I agree that is the issue :) 

Unfortunatley it appears that Lerna is causing this by improperly re-writing the package.json files during bootstrapping.  The lerna package cache files are fine but for some reason the real package json files are being altered and only re-written with a dependecies seciton.  Somehow all other aspects of the original package json files have been removed.  It is doing this for each package json file in each package within my packages dir.

**Comment by evocateur** [comment]
What happens if you remove these lines from `lerna.json`?
```diff
{
  "lerna": "2.0.0-rc.3",
-  "packages": [
-    "packages/*",
-    "packages/axl-storybook/demo"
-  ],
  "version": "0.0.0"
}
```
(or move `"packages/axl-storybook/demo"` to `"demo"`?)

**Comment by dptoot** [comment]
I will have to wait until the next explosion happens :)  
I hope it doesn't!   I will close this issue if so.

**Comment by dptoot** [comment]
Closing this for now as I haven't been able to reproduce.  Let's all just assume I have no idea what I am doing.  thanks for the help guys :+1:

**Comment by ubershmekel** [comment]
I found this issue because I also just got 

> lerna ERR! execute npm ERR! No name provided in package.json

2 package.json files were modified by lerna, they only had their `dependencies` or `deveDependencies` section left. After reverting these changes, lerna succeeded. Strange stuff.

**Comment by ubershmekel** [comment]
After reading `lerna-debug.log` I think I understand what's going on. The mangling of package.json is just how `lerna` works. Lerna npm installs what it thinks should be installed by modifying package.json and replacing it back when it's done. So if interrupted or failing unexpectedly you get that intermediate state.

My specific issue was having a `file:` dependency for a package that was in packages. I guess that caused lerna to crash after it succeeded linking in `node_modules` which caused the next run to succeed.

**Comment by JacekJagiello** [comment]
@ubershmekel I have the same problem, I also have linked dependency using `file:`. +1 for issue
