### ISSUE TITLE
Feature request: use custom preset for conventional-changelog-cli

### ISSUE THREAD

**Issue by futagoza** [lerna/lerna#786]
When using [conventional-changelog-cli](https://www.npmjs.com/package/conventional-changelog-cli) we can use a custom preset with the `-p [preset]` flag. For example, I usually follow a committing style that is very similar to eslint, so I usually use `-p eslint` and get the expected result.

Can you add a option/flag that allows us to change the currently used preset for `--conventional-commits`. Currently it seems to be hard coded to use the `angular` preset (`src/ConventionalCommitUtilities.js`, lines [#30](https://github.com/lerna/lerna/blob/master/src/ConventionalCommitUtilities.js#L30) and [#59](https://github.com/lerna/lerna/blob/master/src/ConventionalCommitUtilities.js#L59)).

Example option/flag, usable only with `lerna publish`:

```terminal
-p, --conventional-preset   Change the preset for conventional-changelog
```

Example `lerna.json` option, either at the root or `command.publish` namespace:
```json
"conventionalCommits": true,
"conventionalPreset": "eslint" // defaults to null
```

If no preset option is passed (or is `null` or `false` in the config file), the `-p` flag  should be omitted from the call to conventional-changelog-cli, allowing for default behaviour.

**Comment by evocateur** [comment]
@bcoe ?

I'd rather it just be an extension of the existing `--conventional-commits` flag, basically turning the boolean into an implicit `--conventional-commits angular`.

**Comment by futagoza** [comment]
I thought about that as well, but then wouldn't that conflict with existing build setups?

If you use a different flag like `-p, --conventional-preset` then there is no conflict, as well as no need to add a check to see if the flag has a value or not, reducing the chance to break existing build setups that use the `--conventional-commits` boolean flag.

If it is deceded to just extend the boolean flag `--conventional-commits`, then I suggest you add the check, and if it finds no value, give the developer a warning rather then an error.

**Comment by bcoe** [comment]
@evocateur @futagoza my temptation would be defaulting eventually to this preset:

https://conventionalcommits.org/

Which is the compromise commit format that I've been advocating; It seems like a reasonable extension to allow another format to be passed as a second argument to `--conventional-commit`, and I don't think we need to warn if we default to the `conventional-commit` format ... I always lean towards making a developer do minimal work.

I like the idea for this extension though @futagoza!

**Comment by evocateur** [comment]
@bcoe If one doesn't pass a preset to `conventional-changelog`, does it behave as specified at https://conventionalcommits.org/ ? I'm all for simplifying configuration in favor of strong defaults (dare I say, "conventions"? 🤣)

**Comment by bcoe** [comment]
@evocateur we currently default to `-p angular`:

https://github.com/lerna/lerna/blob/master/src/ConventionalCommitUtilities.js#L30

which is what the spec on https://conventionalcommits.org/ is based on; currently the angular preset is a superset of the specification discussed on conventionalcommits.org -- I imagine they'll eventually diverge somewhat, and we could switch to `-p conventional`.

The goal with https://conventionalcommits.org/ is to encourage folks to standardize on commit messages, which in turn helps automated tools parse the git history -- the angular convention seems to hit a sweet spot, and is getting pretty wide adoption -- I think before we entertained additional presets, we'd actually need to do some work [here](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-recommended-bump#conventionalrecommendedbumpoptions-parseropts-callback) to appropriately recommend version bumps based on other commit formats.

**Comment by alan-agius4** [comment]
This has been done https://github.com/lerna/lerna/pull/1111
