### ISSUE TITLE
--npm-client=yarn breaks in rc.4

### ISSUE THREAD

**Issue by brianveltman** [lerna/lerna#793]
## Expected Behavior
When running lerna bootstrap --npm-client=yarn it uses yarn to install dependencies.
When adding `"npmClient": "yarn"` to lerna.json it should use yarn to install dependencies.

## Current Behavior
Currently in rc.4 lerna bootstrap --npm-client=yarn falls back to npm.

## Steps to Reproduce (for bugs)

1. Update to lerna 2.0.0-rc.4
2. Run lerna clean && lerna bootstrap

<details><summary>lerna.json</summary><p>

```json
{
    "lerna": "2.0.0-rc.4",
    "npmClient": "yarn",
    "packages": ["packages/*"],
    "version": "independent"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.4 |
| `npm --version`  | 4.2.0 |
| `yarn --version` | 0.23.2 |
| `node --version` | 6.10.0 |

| OS | Version |
| --- | --- |
| macOS Sierra  | 10.12.4 |

**Comment by evocateur** [comment]
Can you run `lerna bootstrap --loglevel silly 2&>lerna-bootstrap.log` and stick `lerna-bootstrap.log` in a gist?

**Comment by evocateur** [comment]
Cool, thanks. The log posted doesn't look like it's necessarily `--npm-client=yarn`'s fault. Is the repo you're running this in public, by chance?

**Comment by brianveltman** [comment]
Unfortunately not.

**Comment by jvivs** [comment]
@brianveltman to provide another data point, I upgraded to rc4 from beta.38 on Friday specifically for yarn support and it worked well.

I'm on yarn@0.23.3 and here's a version of my `lerna.json` edited for privacy: 
```javascript
{
  "lerna": "2.0.0-rc.4",
  "packages": [
    "./",
    "packages/*"
  ],
  "registry": "<location-of-private-registry>",
  "npmClient": "yarn",
  "version": "0.0.0"
}

```

**Comment by brianveltman** [comment]
Maybe I'm just a bit confused. RC.4 has the NPM look as output. I tried it with NPM and then yarn, yarn was faster, but the output looks like NPM. Is this intended with #779?

**Comment by evocateur** [comment]
The log you posted was inconclusive, and seemed to indicate a different error. The logging was indeed switched to the same lib that npm itself uses. We don't pipe the installation logs, however, so there's no explicit notice that yarn is being used. It _is_ definitely being used when properly configured, however.

**Comment by evocateur** [comment]
Closing this as it appears to largely be a misinterpretation of the new logging. We've never emitted client logging during bootstrap, as it is intended to run concurrently and most of the time that's a very noisy prospect.
