### ISSUE TITLE
windows bootstrap unable to symlink missing bin tool

### ISSUE THREAD

**Issue by tyler-johnson** [lerna/lerna#794]
I have a CLI tool in the `bin` property of the `package.json` that is built on the `prepublish` step, but since that comes after the symlink step, I get an error in Windows that the file doesn't exist.

I know there are some larger issues here around the order in which packages are bootstrapped, however I am going to avoid that and focus on this issue specifically.

## Expected Behavior
I would expect the CLI tools to be symlinked after the prepublish step since those files might not exist yet. This is not to be confused with symlinking the package folder, which probably needs to happen before prepublishing can take place.

## Current Behavior
Lerna attempts to symlink the CLI at the same time as symlinking the package folder and since the file does not exist a `ENOENT` error is thrown.

## Possible Solution
My thinking was to separate the symlinking steps, so package folder symlinking took place before the prepublish and CLI symlinking takes place after.

## Steps to Reproduce (for bugs)

On a windows machine:

1. Create a lerna repo with two packages: A and B
2. Add B as a dependency of A
3. In B `package.json`, add a prepublish script and a bin reference:
```
"bin": "cli.js",
"script": {
  "prepublish": "echo \"#!/usr/bin/env node\" > cli.js"`
}
```
4. run `lerna bootstrap`

## Context

This has made it very difficult to build our repo in Windows and most solutions have an adverse effect on the Linux side. The best we could do so far is to place a proxy file, essentially a dummy CLI file that requires the real CLI file when ran. This satisfies lerna, but is dirty and adds unnecessary overhead.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.4 |
| `npm --version`  | 4.5.0 |
| `yarn --version` | N/A |
| `node --version` | 7.7.2 |

| OS | Version |
| --- | --- |
| Windows 10 | 1607 |

**Comment by evocateur** [comment]
Hrm, yeah, this is a tricky case. It doesn't strike me as unique to Windows, though perhaps there are more readily apparent reasons for dynamically generating a CLI file on that platform? Perhaps a more useful demonstration would be `"bin": "lib/cli.js"`, with `lib/cli.js` transpiled from `src/cli.js` during `prepublish` (or `prepare`, eventually).

The problem with splitting the bin symlinking from the directory symlinking is that you would break dependent modules that use a CLI command during `prepublish` that is provided by a sibling module.

I'm actually a fan of your "dirty" solution, as it provides a few other benefits:
* the CLI options management (filtering/defaulting/validating) is now unit-testable without heinous mocking
* the actual bin file always has the correct executable permissions (echoing content with a shebang into a file is not sufficient to make it actually work)
* the actual bin file is _always_ CommonJS and never ignored by git, which lets npm operate on it consistently

Honestly, I don't see the extra complexity of splitting the dependency symlinking phases as a maintainable solution.

**Comment by tyler-johnson** [comment]
Hmm yes, after more thought I realize that fixing it one way would lead to the inverse issue, so I think we will stick with our current solution until Lerna can build the dep tree in order.

Thanks!

**Comment by benmccann** [comment]
@tyler-johnson can you share some more details on your workaround? Is there a public repo where you use this solution that you can point to? Or can you share the contents of your proxy file here?
