### ISSUE TITLE
Lerna throws a error when there is nothing to publish

### ISSUE THREAD

**Issue by koddsson** [lerna/lerna#802]
## Expected Behavior
Lerna should not throw an error but just log out that there's nothing to publish and carry on.

## Current Behavior
```sh
> @ publish /home/ubuntu/apis
> lerna publish --cd-version=patch --yes

lerna info version 2.0.0-rc.4
lerna info current version 1.0.5
lerna info Checking for updated packages...
lerna info Comparing with tag v1.0.5
lerna ERR! initialize Error: No updated packages to publish.
lerna ERR! initialize     at PublishCommand.initialize (/home/ubuntu/apis/node_modules/lerna/lib/commands/PublishCommand.js:204:18)
lerna ERR! initialize     at PublishCommand._attempt (/home/ubuntu/apis/node_modules/lerna/lib/Command.js:265:21)
lerna ERR! initialize     at PublishCommand.runCommand (/home/ubuntu/apis/node_modules/lerna/lib/Command.js:251:12)
lerna ERR! initialize     at PublishCommand.run (/home/ubuntu/apis/node_modules/lerna/lib/Command.js:148:12)
lerna ERR! initialize     at Object.handler (/home/ubuntu/apis/node_modules/lerna/lib/commands/PublishCommand.js:83:43)
lerna ERR! initialize     at Object.self.runCommand (/home/ubuntu/apis/node_modules/lerna/node_modules/yargs/lib/command.js:231:22)
lerna ERR! initialize     at Object.Yargs.self._parseArgs (/home/ubuntu/apis/node_modules/lerna/node_modules/yargs/yargs.js:990:30)
lerna ERR! initialize     at Object.Yargs.self.parse (/home/ubuntu/apis/node_modules/lerna/node_modules/yargs/yargs.js:533:23)
lerna ERR! initialize     at Object.<anonymous> (/home/ubuntu/apis/node_modules/lerna/bin/lerna.js:4:25)
lerna ERR! initialize     at Module._compile (module.js:410:26)
lerna ERR! initialize  callback with error
lerna ERR! initialize  [Error: No updated packages to publish.]
```

## Possible Solution
I'm not sure why this is throwing an error but I think a warning would be enough here. 

## Steps to Reproduce (for bugs)

1. Publish all your unpublished changes.
2. Make sure there are no changes when running `lerna updated`.
3. Run `lerna publish`.
4. Notice error.

## Context

I'm trying to run in a monorepo and don't wan't to fail a step because of this.

If there's a way to check if there's something to publish or not I could also just do that but couldn't find anything in the docs. Something like:

`lerna there-are-updates && lerna publish`

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-beta.38n |
| `npm --version`  | 4.2.0 |
| `yarn --version` | 0.23.4 |
| `node --version` | v7.9.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.4 |

**Comment by evocateur** [comment]
https://github.com/lerna/lerna#updated

**Comment by koddsson** [comment]
So can I use that to check for updates programmicly? Only thing I can think of is doing something like: `! ./node_modules/.bin/lerna updated && ./node_modules/.bin/lerna publish` but it seems that `lerna updated` returns a 0 exit code if something has updated or not.

```
☁  apis [new-infra] ⚡ ./node_modules/.bin/lerna updated
lerna info version 2.0.0-rc.4
lerna info Checking for updated packages...
lerna info Comparing with tag v1.0.5
lerna info result
- @apis/car
☁  apis [new-infra] ⚡ echo $?
0
☁  apis [new-infra] ⚡
```

```
☁  apis [new-infra] ./node_modules/.bin/lerna updated
lerna info version 2.0.0-rc.4
lerna info Checking for updated packages...
lerna info Comparing with tag v1.0.5
lerna info result

☁  apis [new-infra] echo $?
0
☁  apis [new-infra]
```

(Sorry if this is something blatantly obvious)

**Comment by evocateur** [comment]
I do believe you've highlighted a real issue: `lerna updated` should exit non-zero (but not necessarily throw an error) when there are no updated packages. I would indeed expect it to act like a cheap filter for the more expensive `lerna publish`.

I would _also_ expect `lerna publish` to just shrug and `exit 0` when there is nothing to do, perhaps logging a message to that effect. Pull requests welcome! :)

**Comment by koddsson** [comment]
Cool! I'll try to take a stab at this :)

**Comment by koddsson** [comment]
@evocateur Mind if I throw some questions at you to help me move forward with this? I've got a couple of things I want to achieve.

1. Right now I have a branch where I simply check if there are any packages to update in the updated command and call the callback with a error if there are no packages. I kind of want to not throw an error but just exit non-zero like you mentioned but am not sure how I'd go about it. Is there any way to do it right now or do I have to add some more options to the callback to achieve it?

2. I'm trying to write a test for the `publish` command when there are no packages that need updating but all the fixtures I've checked out so far seem to have some changes already. Any good way for me to create a new fixture that have no changes so I can write a test for the `publish` command?

Thanks in advance! (I can also create a PR and discuss all this there if that's better).

**Comment by koddsson** [comment]
Actually in a true person asking a question fashion, I figured out how I can change the exit code without throwing an error, I'll add that to my branch but am still trying to figure out the second thing 😄

**Comment by evocateur** [comment]
@koddsson Opening a PR, even incomplete, would be a great help. I find discussing code easier when I can look at the code. :)

As for item 2, in `lerna publish`'s [integration test](https://github.com/lerna/lerna/blob/master/test/integration/lerna-publish.test.js), you can run any number of git commands before you actually run the lerna command. It might be as simple as:
```js
const cwd = await initFixture("PublishCommand/normal");
await execa("git", ["tag", "-a", "v1.0.0", "-m", "v1.0.0"], { cwd });
// then call lerna
```

**Comment by koddsson** [comment]
Cool! I'll open up the PR soon™ and will ping you there if I run into any problems :)

**Comment by enriquecaballero** [comment]
This seems to be happening again
