### ISSUE TITLE
Lerna unpublish all packages I accidentally published 

### ISSUE THREAD

**Issue by smmJasoff** [lerna/lerna#805]
As title said, does lerna have this sort of command to do unpublish all after you actually already lerna published all..?

**Comment by evocateur** [comment]
No. Unpublishing packages is generally [frowned upon](https://docs.npmjs.com/cli/unpublish).

**Comment by steezeburger** [comment]
I accidentally published private packages and am now getting 400s when trying to manually unpublish in a specific `package/private-package` directory. I know unpublishing is frowned upon, but now my private packages are on npm publically. Any ideas what could be causing this?

**Comment by evocateur** [comment]
@steezeburger You need to unpublish in reverse-topological order; that is, if any of your packages depend on other lerna-based packages, you need to unpublish those first, then the dependencies.

https://docs.npmjs.com/cli/unpublish

**Comment by steezeburger** [comment]
Sorry to spam this closed issue. I realize it was due to npm changing how unpublishing works. I had to email their support and they removed them for me. Thanks for the quick reply!
