### ISSUE TITLE
Lerna should error when provided an invalid command

### ISSUE THREAD

**Issue by azz** [lerna/lerna#809]
```
$ lerna boostrap
```

## Expected Behavior

```
lerna: invalid command "boostrap"
```
Exit code non-zero.

## Current Behavior

No output. Exit code zero.

## Context
We had a build script with a lerna command misspelled that took us way too long to diagnose due to lerna quietly exiting.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.2 |
| `npm --version`  | 4.4.4 |
| `yarn --version` | 0.23.4 |
| `node --version` | v6.2.2 |

| OS | Version |
| --- | --- |
| Windows 10 Enterprise | 14393 |

**Comment by hiskind** [comment]
One way to fix this is by enabling yargs [strict mode](https://github.com/yargs/yargs#strictenabledtrue):

> Any command-line argument given that is not demanded, or does not have a corresponding description, will be reported as an error.
> Unrecognized commands will also be reported as errors.

This way sounds right, but I've just started using lerna and can't say if this solution is fine or there are some special CLI use cases which might not work in strict mode. 

And the other option is to create default command handler `.command('*', fn)` and throw this error manually.

Please let me know what you think, and I'll make PR.

**Comment by evocateur** [comment]
@hiskind I think enabling yargs `strict` is a good idea. Pull request welcome!
