### ISSUE TITLE
Dependency 'fs-promise' is deprecated

### ISSUE THREAD

**Issue by emilyrohrbough** [lerna/lerna#818]
Running npm install results in the following warning:

> fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support

## Suggested Solution
The author of `fs-promise` suggests to use `mz` or `fs-extra^3.0` [here](https://github.com/kevinbeaty/fs-promise)

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.4 |

**Comment by evocateur** [comment]
Thanks for reporting! I have a branch [in-progress](https://github.com/evocateur/lerna/compare/814d557...dda863a) I just haven't had time to merge. It will definitely happen before the official v2.0.0 release.

**Comment by evocateur** [comment]
This is fixed by #828
