### ISSUE TITLE
lerna updated command shows incorrect packages

### ISSUE THREAD

**Issue by bjankord** [lerna/lerna#819]
Our repo uses independent mode and we recently updated to use v2.0.0-rc.4 release. We've been working in the repo for some time. However, we have not used `lerna publish` or created any tags in the repo until recently. We just ran `lerna publish` for the first time in the repo and it created releases / tags and successfully pushed those to the git repo without issue. 

We added 1 new commit to master branch with changes in only one of the recently published packages. Running `lerna updated` lists all of the packages in the monorepo, where we expect it would only list the 1 package with changes since the previous publish.

## Expected Behavior
Running `lerna updated` lists only packages that include changes since last time `lerna publish` was run.

## Current Behavior
Running `lerna updated` lists that all packages in monorepo have been updated.

<details><summary>console output when running lerna updated</summary><p>

```bash
Console output:

terra-core|master ⇒ lerna updated
lerna info version 2.0.0-rc.4
lerna info versioning independent
lerna info ignore [ 'terra-content-container',
lerna info ignore   'terra-content',
lerna info ignore   'terra-modal',
lerna info ignore   'terra-site',
lerna info ignore   'terra-standout',
lerna info ignore   'terra-title' ]
lerna info Checking for updated packages...
lerna info Comparing with tag terra-slide-panel@0.2.0
lerna info result
- terra-arrange
- terra-badge
- terra-base
- terra-button-group
- terra-button
- terra-date-picker
- terra-demographics-banner
- terra-grid
- terra-i18n-plugin
- terra-i18n
- terra-icon
- terra-image
- terra-list
- terra-markdown
- terra-progress-bar
- terra-props-table
- terra-responsive-element
- terra-slide-panel
- terra-status
- terra-table
- terra-toolkit
```
</p></details>

## Steps to Reproduce (for bugs)
Repo url https://github.com/cerner/terra-core
1. Clone repo
2. Run npm install
3. Run `lerna updated`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.4",
  "packages": [
    "packages/*"
  ],
  "command": {
    "publish": {
      "ignore": [
        "terra-content-container",
        "terra-content",
        "terra-modal",
        "terra-site",
        "terra-standout",
        "terra-title"
      ]
    }
  },
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context
We're trying to run `lerna publish` again to release changes in the single package that changed since the previous publish, but `lerna updated` seems to be having issues with diffs since the last tags. 

I've tried running `lerna diff package-name` on some of our packages and it seems to time out without error. Not sure if there is a verbose flag I can use to get more info.

Running `git describe --abbrev=0 --tags` I see `terra-slide-panel@0.2.0`. On [the repo, under releases](https://github.com/cerner/terra-core/releases), terra-toolkit@0.3.0 looks like the latest released package / tag.

When I run `git diff --name-only terra-slide-panel@0.2.0` I see the files change I would expect `lerna updated` to find, it shows only the changes in the 1 package we've modified since last release.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | v2.0.0-rc.4 |
| `npm --version`  | v4.5.0 |
| `yarn --version` | N/A |
| `node --version` | v6.9.4 |

| OS | Version |
| --- | --- |
| mac OS X El Capitan | 10.11.6 |

**Comment by evocateur** [comment]
Awesome repro, thank you!

(Using `d99de93` as the base, not the current head, which does have a lot of package.json changes)
```
git clone git@github.com:cerner/terra-core.git
cd terra-core
git checkout -b lerna-updated-problem d99de93
npm i
./node_modules/.bin/lerna updated
```

**Comment by bjankord** [comment]
Thanks for the quick reply @evocateur. Yeah, this was user error on my part, looks like a commit snuck in master that _did_ change all the packages when I was doing a release. Threw me off as I thought we just had 1 package change in master. This can be closed.

**Comment by evocateur** [comment]
Ah, ok! Thanks again for taking the time to file an issue. :)
