### ISSUE TITLE
Integrate with Library from Angular 2 Yeoman Generator

### ISSUE THREAD

**Issue by rkusuma** [lerna/lerna#820]
I'm using [generator-angular2-library](https://github.com/jvandemo/generator-angular2-library) to create the library and manage it with lernajs.

The problem is i need to run `gulp build` in each packages and publish it from `dist` folder.
Can i do that with `lerna publish`? i read the documentation and not found the solution.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-beta.38 |
| `npm --version`  | 4.1.2 |
| `yarn --version` | 0.21.3 |
| `node --version` | 7.7.4 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.4 |

**Comment by evocateur** [comment]
There's absolutely no reason to have two `package.json` files in this case. Just put the `module` and `main` (pointing to files under `dist`) and `dependencies` in the right place (the package's "root" `package.json`) and call `gulp build` from the `prepublish` script.
