### ISSUE TITLE
Bootstrap not working with scoped package

### ISSUE THREAD

**Issue by jcreamer898** [lerna/lerna#825]
## Expected Behavior
Symlinks should apply to scoped packages.

## Current Behavior
I have a project setup with independent versions.

```
packages/foo
packages/bar
```

They are scoped in their package.json names.

```
"name": "@org/foo",
"dependencies": {
  "@org/bar": "latest"
}
```

When I run `lerna bootstrap` it's not symlinking to my local `@org/bar` in the foo project.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.2",
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.4 |
| `npm --version`  | 4.5.0 |
| `yarn --version` | 0.22 |
| `node --version` | 6.9.1 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.4 |

**Comment by evocateur** [comment]
You need to use a matching semver range (e.g., `^1.0.0`), not "latest", for lerna's algorithm to identify "sibling" packages that should be symlinked. This mismatch between recognized name and version range could probably be better surfaced as a warning. (The presence or absence of a scope is irrelevant in this case)

**Comment by jcreamer898** [comment]
Got it. Thanks!
