### ISSUE TITLE
Lerna exec with rollup watch does not launch enough processes

### ISSUE THREAD

**Issue by rayrutjes** [lerna/lerna#826]
When running lerna exec with long running processes it only opens a random amount of child processes.

```bash
lerna exec --parallel -- rollup -c ../../build/rollup.cjs.config.js -w
```

## Expected Behavior
I expect to have 1 process running per package so that I can watch all of them at the same time.

## Current Behavior
Currently it launches processes for a random amount of packages which changes depending on the --ignore and --scope arguments, but never all are run (unless there is only few).

When I remove the rollup -w parameter to simply run the build synchronously, all expected packages are properly ran.

It looks like lerna doesn't manage to parallelize because of some reason.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.4",
  "packages": [
    "packages/*",
    "packages/examples/*"
  ],
  "npmClient": "yarn",
  "version": "0.0.0"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.4 |
| `npm --version`  | VERSION |
| `yarn --version` | 0.23.3 |
| `node --version` | v7.7.2 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.4 |

**Comment by evocateur** [comment]
The `--parallel` flag for `lerna run` and `lerna exec` hasn't been released yet, so you'll have to do `--stream --concurrency=9999` for the time-being. I hope to cut a release soon.

**Comment by rayrutjes** [comment]
Thanks a lot for the quick answer @evocateur .

FYI I also had to use the `--no-sort` parameter in combination  of the 2 others.

It works now ;)
