### ISSUE TITLE
Feature request: commands to add/remove dependencies from managed packages

### ISSUE THREAD

**Issue by pospi** [lerna/lerna#833]
Without some way of doing this built in to Lerna itself, usage of module hoisting alongside Yarn becomes impractical when adding or removing dependencies to packages.

- Yarn wants to download all the dependencies it's missing, and is ignorant of hoisted ones. So you suffer the wait of re-downloading your packages whenever running `yarn add` directly within a module. Cleaning up this duplication also eats time.
- Adding the dependency manually is also an option, but this requires re-running `lerna` and that takes far longer than a normal module install.

`lerna add [--dev]` and `lerna remove` commands which accept the target package as well as dependency would provide a smooth means of dealing with these problems.

Great package and desperately needed in the node ecosystem, keep up the great work!

**Comment by evocateur** [comment]
I'm increasingly desiring this myself, dealing with synchronization of hoisted modules with npm (so it's not just a yarn issue). While you _could_ achieve most of this with a artisanally-crafted `lerna exec --scope <glob> --
 yarn add <pkg> && lerna bootstrap --hoist`, it has the awkward side-effects you've noted.

I'm only concerned about the namespacing of the commands you suggest. `add` and `remove` are a bit ...broad? I'd feel better if the operation (add, remove, etc) was an argument of a single entry point, like `lerna dependency` (aliased to `lerna dep` for fewer keystrokes).

How does this API sound to you?
```bash
lerna dep add [--dev] <dependency>[@version] [..glob]
lerna dep remove <dependency> [..glob]
lerna dep upgrade <dependency> [..glob]
lerna dep sync [..glob]
```

I figure allowing one or more package globs make sense, defaulting to `**` like the `--hoist` option. We'd definitely want to support the `yarn upgrade`/`npm install <pkg>@<latest>` use case.

The `sync` subcommand would only be necessary for `--hoist`-configured repos, to facilitate manual root upgrades. Not sure if it's really necessary, but I definitely feel _this_ specific pain (which would largely go away with the availability of the other proposed commands).

**Comment by pospi** [comment]
Makes sense to me. I'm fine with whichever API fits the lerna paradigm
best, so long as I can squeeze the time savings out of it!

**Comment by loklaan** [comment]
This would be a great addition to lerna - in the mean time I've used a script in the `preinstall` lifecycle of managed packages, to override `yarn add` behaviour. [It's a total hack.](https://gist.github.com/loklaan/bc996796216f749a6699a00cdfd779ba)

**Comment by jasonkarns** [comment]
I've attempted the hand-crafted command listed above (`lerna exec --scope <glob> -- yarn upgrade <pkg> && lerna bootstrap --hoist`) but that errors out since the managed package does not contain a yarn.lock.

_should_ there be yarn.lock files in managed packages? I was assuming no but...

**Comment by marionebl** [comment]
* `lerna add` was implemented in the meantime via https://github.com/lerna/lerna/pull/1069

**Comment by sachnk** [comment]
Hi --

Thanks for the great work. I'm currently using `lerna add` with no problems. Any recommended ways to  achieve the corresponding `lerna remove` functionality?

**Comment by shrugs** [comment]
Workaround for now:

```
lerna exec -- yarn remove my-package
```

**Comment by fyodorvi** [comment]
```
lerna exec -- yarn remove my-package
```
errors and doesn't update the lock file

**Comment by naddison36** [comment]
The workaround if you want to remove all devDependencies from your manged packages using lerna and npm
```bash
lerna exec -- npm prune --production
lerna bootstrap -- --production
```

This is useful if you are building a docker image for production use. In a Dockerfile, this would be
```bash
RUN lerna exec -- npm prune --production && \
    lerna bootstrap -- --production
```

**Comment by brian-moore** [comment]
@naddison36 why do you have to run lerna bootstrap -- --production again?

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
