### ISSUE TITLE
A way to prevent any error after lerna publish.

### ISSUE THREAD

**Issue by smmJasoff** [lerna/lerna#838]
To prevent any error after lerna publish. 
Is there any script I can do, sort of like 'lerna prepublish/ testPublish' for testing if it will be 100% successfully published to npm?

**Comment by cttttt** [comment]
+1

Would be nice to have a way to run everything (including `prepublish` scripts) but without actually affecting:

- The local repo.
- Git remotes.
- The `npm` repository.
- The working directory.

The current best option, `lerna publish --skip-git --skip-npm` does a little too little and a little too much:  It only bumps the package dependencies in `package.json` files in the Lerna tree, so it can't really be treated as a "dry run".

**Comment by tomccabe** [comment]
`lerna exec -- npm pack`?

**Comment by evocateur** [comment]
@smmJasoff other than the script @tomccabe suggested, there's really no way lerna can anticipate the behaviour of your network and npm config and current authorization (if any) and registry and strong nuclear force and and and...

We totally should have a `--dry-run`, too, but that won't really give you any more confidence that a given `npm publish` will work, other than what it _intends_ to do.

**Comment by cttttt** [comment]
Understood.  Our problems were actually during the pre-publish steps, so @tomccabe 's suggestion is a legit one:  Just run that step on each package in CI in order to vet pull requests.
