### ISSUE TITLE
package.json.lerna_backup can get left behind after builds

### ISSUE THREAD

**Issue by egid** [lerna/lerna#843]
We recently ran into an issue where a Lerna build left `package.json.lerna_backup` behind and it didn't clean up after itself.

## Expected Behavior
All builds should clean up build artifacts after they finish, successful or otherwise.

## Current Behavior

`package.json.lerna_backup` can remain in the filesystem after a build completes.

## Steps to Reproduce (for bugs)

1. Run Lerna, apparently.
2. We don't have clear repro steps; there wasn't a build failure when this occurred.

@gigabo is familiar with our setup so I'm going to refrain from pasting configs unless requested.

**Comment by evocateur** [comment]
Is your config any more complex than the default (spit out by `lerna init`)? If so, it's really important for ruling out various classes of errors. Even anonymized it can still be valuable.

That said, how did you discover this? An errant `git commit -am "stuff"`?

**Comment by vyorkin** [comment]
I'm really suffering from the same problem. *Almost* every when time I got some `postinstall` error from one of subpackages (or any error at all) during install, my `package.json` is messed up and its content is replaced with lerna build artifacts. I guess its possible to reproduce this by just pressing `ctrl+c` before installation finish, not sure about this though.

**Comment by evocateur** [comment]
If I had to guess, multiple onExit handlers might not be the best approach to cleaning up after install errors. Some minor bookkeeping and a single loop to restore currently-modified files might work better.
