### ISSUE TITLE
`lerna bootstrap` should support --only-updated flag

### ISSUE THREAD

**Issue by kanzelm3** [lerna/lerna#847]
## Expected Behavior
`lerna bootstrap` should respect the new `--only-updated` flag for CI purposes. `lerna bootstrap --only-updated` should only symlink packages that have updates, and install the others as external dependencies.

## Current Behavior
`lerna bootstrap` does not respect the new `--only-updated` flag

## Possible Solution
Like I mentioned above, update `lerna bootstrap` to respect the `--only-updated` flag and only symlink modules if they've been updated. Otherwise, install them as external dependencies.

## Context
We would love to run our build/test/lint on only updated packages as this would speed up our CI builds significantly. Since as of today `lerna bootstrap` does not respect the new `--only-updated` flag, when we run `lerna exec --only-updated -- yarn build` it only builds out updated packages (yay). However; when we run `lerna exec --only-updated -- yarn test` now, tests that depend on modules that did not change fail because they were not built (boo). So currently, we can only get away with building _all_ packages and running lint/test on only updated packages.

**Comment by treshugart** [comment]
Hey @kanzelm3, in #822 I'm working on moving `--only-updated` to be called `--since` and also accept an optional `ref` argument (like `master` or `[commit]`) that works for all commands where `--scope` does (like `bootstrap`).

**Comment by evocateur** [comment]
I'm not sure I'm comfortable with making the staggeringly complex bootstrap command _even more_ complex just to save a few cycles on CI. _If_ such a solution were compact, easy to reason about, and well-tested, I'd be open to a PR.

**Comment by treshugart** [comment]
@evocateur not sure if you're responding to me, or @kanzelm3, but I'd like to clarify a couple things.

> I'm not sure I'm comfortable with making the staggeringly complex bootstrap command even more complex just to save a few cycles on CI. If such a solution were compact, easy to reason about, and well-tested, I'd be open to a PR.

Our use case is similar. In our case, bootstrapping 11+ mins and is growing. #822 would allow smaller changes take less than a minute in CI. In terms of complexity, the implementation of `--since` is more lightweight than `--only-updated` and works for everything that `--scope` works for.

**Comment by evocateur** [comment]
@treshugart Sorry, yes, I meant to respond to @kanzelm3. I'm clearing my queue before I review #822, I appreciate your patience.

**Comment by treshugart** [comment]
No worries at all, just wasn't sure :)

**Comment by kanzelm3** [comment]
Sounds like @treshugart is on the right track. I wasn't sure what the best way to implement it was, I just know the use case we have, and it's the same as his.
