### ISSUE TITLE
Package without name

### ISSUE THREAD

**Issue by borela** [lerna/lerna#848]
Currently, Lerna requires all packages to have a name but anonymous packages(no name or version, just dependencies and scripts) are useful for functional testing.

## Expected Behavior
Lerna should allow packages without names and bootstrap their dependencies. The `lerna ls` could either ignore the anonymous packages or show their directory relative to the `lerna.json`.

## Current Behavior
You have to name all packages.

Lerna: 2.0.0-beta.38
Windows 10 x64

**Comment by treshugart** [comment]
Why not add a `name` and `"private": true`?

**Comment by borela** [comment]
I am doing that right now but there might be too many combinations for the webpack settings/environment and these packages don't need to be listed on `lerna ls` at all, only bootstraped.

**Comment by borela** [comment]
After investigating a bit, the lines [112](https://github.com/lerna/lerna/blob/master/src/commands/BootstrapCommand.js#L112) and [605](https://github.com/lerna/lerna/blob/master/src/commands/BootstrapCommand.js#L605) are causing the issue because the tracker is calling slice on undefined if the package's name doesn't exist. Just adding `|| ''` so that there's always string as the argument solves the issue and lerna works with anonymous packages.
