### ISSUE TITLE
Bootstrapping conflates dependencies and devDependencies

### ISSUE THREAD

**Issue by tivac** [lerna/lerna#851]
## Expected Behavior
When running `lerna bootstrap --hoist` the `package.json` it generates puts all of the hoisted dependencies into the `dependencies` key, instead of splitting them into `dependencies`/`devDependencies`.

## Current Behavior
`lerna` would put dependencies in its temporary `package.json` under the correct key based on where they came from in the source `package.json`.

## Steps to Reproduce
1. `npm i -g npm@next` to install npm5
2. `lerna init`
3. Create a package that includes `devDependencies`
4. `lerna bootstrap --hoist`
5. Check the generated `package-lock.json` file and note that the `devDependencies` from step 3 are in the `dependencies` section.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.5",
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "command": {
    "publish": {
      "message": "chore: Publish"
    },
    "bootstrap": {
      "hoist": true
    }
  }
}
```
</p></details>

## Context
Been trying out `npm@5` and everything seems to work fine, I only noticed this when looking at my `package-lock.json` file. It's probably not actually an issue but does seem not as clean as it could be.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.5 |
| `npm --version`  | 5.0.0 |
| `node --version` | 7.9.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Windows 10 | 14393 |
| Ubuntu | 16.10 |

**Comment by evocateur** [comment]
Yeah, this behaviour also prevents us from supporting the "only bootstrap production dependencies" case (like `npm install --only=production`), as well.

**Comment by garthk** [comment]
Otherwise put: when preparing deployment images, `lerna bootstrap --scope $(PACKAGE) --include-filtered-dependencies` should not pull in all the `devDependencies` if `NODE_ENV=production`.
