### ISSUE TITLE
Lerna creates commit vundefined when no update is needed

### ISSUE THREAD

**Issue by borela** [lerna/lerna#853]
If you run the publish command when no package need to be updated, lerna will create a commit and tag `vundefined` as you can see [an example here](https://github.com/storybooks/storybook/commit/ec597d590d63dea7ef0aaa4c930efe5fd44ab3b4).

## Expected Behavior
Lerna already detects that no update is needed, all it needs to do is to not create the commit and tag.

## Current Behavior
Lerna creates a commit with the message `vundefined` and a tag with the same name.

## Steps to Reproduce (for bugs)
1. Run the command when all packages are already updated.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.5|
| `npm --version`  |4.1.2|
| `node --version` | 7.6.0|

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Windows 10  x64| 1703 |

**Comment by dtothefp** [comment]
Also, it seems that for a `vundefined` tag lerna will remove the `version` line from `lerna.json`. For, `vnull` it may replace the version value with `null` if I'm remembering correctly but I'm unable to reproduce recently. 

This same issue is also reported here I believe:

https://github.com/lerna/lerna/issues/912

**Comment by darkobits** [comment]
This behavior is pretty obnoxious, especially considering that it also pushes the created commit and tag. I've had to temporarily disable protection on remote branches numerous times to fix the mess this creates.

```
$ lerna publish

lerna info version 2.0.0
lerna info current version <version here>
lerna info Checking for updated packages...
lerna info Comparing with <version here>.
lerna info No updated packages to publish. <== SWEET JESUS, WE CAN STOP HERE!!
lerna info publish Publishing packages to npm...
lerna info git Pushing tags...
Successfully published:

lerna success publish finished
```
