### ISSUE TITLE
TypeError: Cannot set property stack of JSONError which has only a getter

### ISSUE THREAD

**Issue by richburdon** [lerna/lerna#854]
## Expected Behavior
`lerna clean` should run without errors

## Current Behavior
The following error happens with any lerna command (it's been working before today; trying to figure out what has changed.)
`TypeError: Cannot set property stack of JSONError which has only a getter`

## Steps to Reproduce (for bugs)
No idea.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.4",
  "packages": [
    "sub/*"
  ],
  "npmClient": "yarn",
  "version": "0.0.0"
}
```
</p></details>

No `lerna-debug.log`

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.5 |
| `npm --version`  | 4.6.1 |
| `yarn --version` | 0.24.5 |
| `node --version` | v7.10.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.5 |

**Comment by richburdon** [comment]
Happens if any of the sub package.json files are corrupt (e.g., hanging `,`).

**Comment by iyobo** [comment]
Verified. Not a very helpful error message

**Comment by evocateur** [comment]
I've been bitten by this myself. We definitely need better error handling for this sort of error.

**Comment by anfedorov** [comment]
@evocateur would allowing for trailing commas in the `project.json` be a valid solution, as well? even though technically a deviation from the formal JSON spec, I would much prefer that to error-ing at all and would be willing to fix it.

**Comment by evocateur** [comment]
package.json is always going to be JSON. We should do better about catching errors and messaging appropriately.

**Comment by anfedorov** [comment]
sounds good. unfortunately now that I know what the error means, I get nothing out of making it more clear ;)

**Comment by Siilwyn** [comment]
This issue has been solved by the looks of it. Wanted to pick it up but the error message is pretty clear though a bit verbose now:
```
lerna info version 2.0.0
lerna info versioning independent
lerna ERR! EPACKAGES JSONError: Trailing comma in object at 10:3 in modules/my-project-package/package.json
lerna ERR! EPACKAGES   },
lerna ERR! EPACKAGES   ^
lerna ERR! EPACKAGES     at module.exports (/home/selwyn/codeground/my-project/node_modules/parse-json/index.js:27:17)
lerna ERR! EPACKAGES     at parse (/home/selwyn/codeground/my-project/node_modules/load-json-file/index.js:8:29)
lerna ERR! EPACKAGES     at Function.module.exports.sync.fp [as sync] (/home/selwyn/codeground/my-project/node_modules/load-json-file/index.js:11:29)
lerna ERR! EPACKAGES     at Function.module.exports.sync (/home/selwyn/codeground/my-project/node_modules/read-pkg/index.js:40:25)
lerna ERR! EPACKAGES     at /home/selwyn/codeground/my-project/node_modules/lerna/lib/PackageUtilities.js:125:47
lerna ERR! EPACKAGES     at Array.forEach (native)
lerna ERR! EPACKAGES     at /home/selwyn/codeground/my-project/node_modules/lerna/lib/PackageUtilities.js:119:86
lerna ERR! EPACKAGES     at Array.forEach (native)
lerna ERR! EPACKAGES     at Function.getPackages (/home/selwyn/codeground/my-project/node_modules/lerna/lib/PackageUtilities.js:118:22)
lerna ERR! EPACKAGES     at Repository.buildPackageGraph (/home/selwyn/codeground/my-project/node_modules/lerna/lib/Repository.js:82:51)
lerna ERR! EPACKAGES  Errored while collecting packages and package graph { JSONError: Trailing comma in object at 10:3 in modules/my-project-package/package.json
lerna ERR! EPACKAGES   },
lerna ERR! EPACKAGES   ^
lerna ERR! EPACKAGES     at module.exports (/home/selwyn/codeground/my-project/node_modules/parse-json/index.js:27:17)
lerna ERR! EPACKAGES     at parse (/home/selwyn/codeground/my-project/node_modules/load-json-file/index.js:8:29)
lerna ERR! EPACKAGES     at Function.module.exports.sync.fp [as sync] (/home/selwyn/codeground/my-project/node_modules/load-json-file/index.js:11:29)
lerna ERR! EPACKAGES     at Function.module.exports.sync (/home/selwyn/codeground/my-project/node_modules/read-pkg/index.js:40:25)
lerna ERR! EPACKAGES     at /home/selwyn/codeground/my-project/node_modules/lerna/lib/PackageUtilities.js:125:47
lerna ERR! EPACKAGES     at Array.forEach (native)
lerna ERR! EPACKAGES     at /home/selwyn/codeground/my-project/node_modules/lerna/lib/PackageUtilities.js:119:86
lerna ERR! EPACKAGES     at Array.forEach (native)
lerna ERR! EPACKAGES     at Function.getPackages (/home/selwyn/codeground/my-project/node_modules/lerna/lib/PackageUtilities.js:118:22)
lerna ERR! EPACKAGES     at Repository.buildPackageGraph (/home/selwyn/codeground/my-project/node_modules/lerna/lib/Repository.js:82:51)
lerna ERR! EPACKAGES   stack: 'JSONError: Trailing comma in object at 10:3 in modules/my-project-package/package.json\n  },\n  ^\n    at module.exports (/home/selwyn/codeground/my-project/node_modules/parse-json/index.js:27:17)\n    at parse (/home/selwyn/codeground/my-project/node_modules/load-json-file/index.js:8:29)\n    at Function.module.exports.sync.fp [as sync] (/home/selwyn/codeground/my-project/node_modules/load-json-file/index.js:11:29)\n    at Function.module.exports.sync (/home/selwyn/codeground/my-project/node_modules/read-pkg/index.js:40:25)\n    at /home/selwyn/codeground/my-project/node_modules/lerna/lib/PackageUtilities.js:125:47\n    at Array.forEach (native)\n    at /home/selwyn/codeground/my-project/node_modules/lerna/lib/PackageUtilities.js:119:86\n    at Array.forEach (native)\n    at Function.getPackages (/home/selwyn/codeground/my-project/node_modules/lerna/lib/PackageUtilities.js:118:22)\n    at Repository.buildPackageGraph (/home/selwyn/codeground/my-project/node_modules/lerna/lib/Repository.js:82:51)',
lerna ERR! EPACKAGES   name: 'JSONError',
lerna ERR! EPACKAGES   fileName: 'modules/my-project-package/package.json' }
```

Thoughts?

**Comment by evocateur** [comment]
We really should figure out how to make the error logging less repetitive. In this instance, I'm not sure how useful the stack trace is anyway (except the origin), we don't care about the underlying library lines...

**Comment by Siilwyn** [comment]
Yes probably though I'd rather have a verbose error than miss information. That said isn't this outside the scope of this issue?

**Comment by evocateur** [comment]
I think the error reporting improvements are part of the solution. I don't believe it is lerna's responsibility to fix invalid JSON. Normal npm commands will also fail with invalid package.json content, so we should aspire to useful error messages that help the developer fix the typo quickly and get on with their day.

**Comment by anfedorov** [comment]
> Normal npm commands will also fail with invalid package.json content, so we should aspire to useful error messages that help the developer fix the typo quickly and get on with their day

good point. fwiw, in iTerm2, iirc, a file path like `/User/andrey/code/foo/project.json:23:34` can be opened with a single command-click in a way that editors recognize as pointing to that spot, so including that seems idea.

**Comment by Siilwyn** [comment]
@evocateur fully agree. What I meant is that this issue is about missing information when invalid JSON is used, which is fixed. While to me the suggestions you bring up are applicable to errors from Lerna in general.

**Comment by anfedorov** [comment]
@Siilwyn fixed it in parse-json and load-json-file. could you update the version to 3.0.0 or comment on #976 if you see any issues?
