### ISSUE TITLE
`lerna diff` against arbitrary gitref

### ISSUE THREAD

**Issue by paolobueno** [lerna/lerna#855]
## Expected Behavior

`lerna diff` could accept an extra param pointing to an arbitrary gitref instead of targetting its own created semver tags.
I understand this might modify the original semantics of the command, which state that it diffs "since the last release", however the additional flag could have documentation around this change of meaning.

## Current Behavior

`lerna diff` currently targets conventionally-named semver tags it creates as part of a `publish` operation, either a single one when using unified versioning or multiple tags when using independent versioning mode, when determining which packages have been changed.

## Context

My specific use case is `--scope`-ing the running of tests and some costly operations in a CI server to the set of packages modified in a PR.
With this extra parameter it would be way easier to use lerna to determine which packages have actually been changed just for that set of changes that rarely go back all the way to the previous release.

**Comment by treshugart** [comment]
I've implemented a `--since` option in #822 that defaults to the latest tag, if no `ref` is specified. This should sate your needs if specifying `--since [ref]`. It will apply to all commands `--scope` does.

Someone else also requires the same functionality for `bootstrap`in #847.

**Comment by paolobueno** [comment]
Thanks a lot @treshugart, I'll keep an eye out for your PR and we might use your fork if we need that feature in the meantime.

In our use case we have a strict schedule for publishing new versions but have a stable `master` that we'll often branch out of for feature development, so we really need the ability to point to a specific gitref instead of only having the option to go all the way back to the latest release tag.

**Comment by evocateur** [comment]
Aside from the potential for `--since`, why not just a normal `git diff HEAD..<tree-ish> -- ./packages` ? There's nothing really special going on with `lerna diff` other than the "since last release" evaluation.
