### ISSUE TITLE
yarn should be called with --non-interactive flag

### ISSUE THREAD

**Issue by ruifortes** [lerna/lerna#863]
Hi.
Yarn asks to choose version when installing from git. (to be confirmed [here](https://github.com/yarnpkg/yarn/issues/3572))
Since it's not possible interact with prompts when bootstraping shouldn't yarn be called with --non-interactive flag?

**Comment by evocateur** [comment]
That seems fair. PRs welcome.

**Comment by mmcgahan** [comment]
Looks like this can be closed https://github.com/lerna/lerna/pull/897

**Comment by hzoo** [comment]
Thanks!
