### ISSUE TITLE
Can reuse deps?

### ISSUE THREAD

**Issue by sospedra** [lerna/lerna#864]
Getting a simple lerna packages with 2 products:

```
- packages/
-   packA/
-   packB/ 
```

And both them have:

```json
"dependencies": {
  "lodash": "^4.17.4",
},
```

and/or a good `npm@5` `package-lock.json`.

Should they reuse the same `node_modules/lodash`? If Lerna cannot do this, why? And, is there any possiblity to achieve this feature?

Many many thanks!
Hope I explain myself clearly ;)

**Comment by sospedra** [comment]
Is by using `lerna bootstrap --hoist`? This is moving all the deps to the top-level, not only the shared ones.

**Comment by evocateur** [comment]
Yes, `--hoist` is what you're looking for. I can't promise any npm5-specific support, however it should still work?

**Comment by sospedra** [comment]
The answer fixes de question
