### ISSUE TITLE
lerna scripts doesn't return exit codes

### ISSUE THREAD

**Issue by mlunoe** [lerna/lerna#869]
When I run lerna scripts in bash I expect to receive the exit code as a result of the script.

One use case is when I run scripts with `set -e` to exit if one of the scripts fail or running multiple scripts and returning the error if one of them exits with an error:
```sh
EXIT_STATUS=0

npm install || EXIT_STATUS=$?
lerna bootstrap || EXIT_STATUS=$?
lerna exec npm test || EXIT_STATUS=$?

exit $EXIT_STATUS
```

## Expected Behavior
I expect to recieve the exit code as a result of running the script

## Current Behavior
Any lerna script I run always exits with status `0`

## Steps to Reproduce (for bugs)

1. Create a lerna project with a failing test
2. Save the above script to a file
3. Run the above script
4. Observe the exit code being `+ exit 0`, expected result `+ exit 1`
5. When the `npm test` command is run directly by the same bash script it exits correctly with `+exit 1`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-beta.30",
  "version": "1.11.0"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
lerna(info)    Lerna v2.0.0-beta.30
lerna(debug)   Attempting running ExecCommand.initialize
lerna(debug)   Successfully ran ExecCommand.initialize
lerna(debug)   Attempting running ExecCommand.execute
lerna(error)   Errored while running command 'npm' with arguments 'test' in 'xxx'
lerna(error)   Errored while running ExecCommand.execute
    Command failed: npm test

```
</p></details>

## Context

I am trying to run this in CI and let the build fail when the script runs, if one of the subtasks fail

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-beta.30 |
| `npm --version`  | 3.10.10 |
| `yarn --version` | - |
| `node --version` | v6.10.2 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.5 |

**Comment by epiloque** [comment]
Publish failures do no return >0 exit codes either

`npm ERR! "You cannot publish over the previously published version 6.0.6." : @epiloque/weaver-test`

**Comment by dizlexik** [comment]
Yeah `lerna run test` is not very useful if I can't get a >0 exit code back when tests fail.

This issue is currently preventing me from using this in CI.

**Comment by dizlexik** [comment]
This seems to have been fixed at some point. I'm getting error code 1 on failing tests now.

**Comment by mlunoe** [comment]
Tested it and it works now! Great 👏
