### ISSUE TITLE
[feature request] link packages for root package.json

### ISSUE THREAD

**Issue by Andarist** [lerna/lerna#870]
So basically my use case for now is that I have set up the monorepo structure, but I have both packages and the app in my git repo.

From what I understand (and see during bootstrap process) lerna is not linking packages when they are referenced in the root `package.json`. Aint sure if what I have said is clear so the best it will be if I explain with a simple config

**lerna.json**
```js
{
  "lerna": "2.0.0-rc.5",
  "npmClient": "yarn",
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0",
  "hoist": true
}
```
**root package.json**
```js
"private": true,
"dependencies": {
  "my-package": "^0.0.0",
}
```
**directory structure** - my app lives in the src ofc and I would like to use linked `my-package` from there
```
my-lerna-repo/
  package.json
  packages/
    my-package/
      package.json
  src/
```

Behaviour:
`error An unexpected error occurred: "https://registry.npmjs.org/my-package: Not found".`

**Comment by evocateur** [comment]
Just add the root to your `packages` list in `lerna.json`:
```diff
  "packages": [
+    ".",
    "packages/*"
  ],
```
