### ISSUE TITLE
Is it possible to override the 'npm publish' command?

### ISSUE THREAD

**Issue by magicmark** [lerna/lerna#871]
Let's say we have a custom a npm package publishing workflow which replaces `npm publish`.

If we still want to use lerna on top of this workflow, is this possible currently to replace `npm publish` with a different command? If not, would you be open to a PR for this?

Thanks!

**Comment by evocateur** [comment]
The existing lifecycle hooks (`prepublish`, `publish`, & `postpublish`) aren't enough?

I don't see something this fundamental to the purpose of `lerna` being overridable in any context.

**Comment by magicmark** [comment]
Our npm registry only serves files and does not understand 'npm publish', so we would need a custom command to upload the tarballs to our registry.

It would be nice to still be able to use lerna to manage multiple packages in one repo though :)

**Comment by evocateur** [comment]
You could conceivably chain some `lerna exec` calls, I suppose.

```sh
# bump versions in changed packages, create tag(s) and push to remote
lerna publish --skip-npm
# create ${packageName}-v${version}.tgz file in each package
lerna exec -- npm pack
# run a command to upload that tgz to tarball repository
lerna exec -- rsync *.tgz <destination>
```

`npm pack` is run during the `npm publish` process.
