### ISSUE TITLE
Not working with Node 8.1

### ISSUE THREAD

**Issue by borela** [lerna/lerna#874]
Publishing is broken on Node 8.1.

## Current Behavior
When asked:
`Are you sure you want to publish the above changes? (ynH)`
The keys `y` or `n` doesn't work and even Ctrl+C doesn't stop the process.

## Steps to Reproduce (for bugs)
Try to publish the packages.

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.5|
| `npm --version`  | 5.0.3 |
| `node --version` | 8.1.0|

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Windows 10 | 1703 |

**Comment by Havunen** [comment]
Facing exactly same issue. Lerna does not seem to read any keyboard input. Ubuntu 16.0.4.LTS2 tried with different terminal applications, that didn't work either.  Node 8.1 + npm 5.0.3

**Comment by davej** [comment]
Probably related: https://github.com/nodejs/node/pull/13560

**Comment by evocateur** [comment]
This is an upstream regression in readline, and will be fixed accordingly.
