### ISSUE TITLE
GitUtilities tries to checkout package.json on wrong path on canary release

### ISSUE THREAD

**Issue by exah** [lerna/lerna#875]
`GitUtilities` tries to checkout `package.json` after change on wrong path, when publishing canary release. This results in `UnhandledPromiseRejectionWarning`:

```
lerna info publish Publishing packages to npm...
lerna info published framez-core
lerna info published framez-easings
lerna info published framez
lerna info canary Resetting git state
(node:79159) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: error: pathspec 'packages/*/package.json' did not match any file(s) known to git.
```

Related line: https://github.com/lerna/lerna/blob/ab3c7855bc9549cbc61f728fb8b74b153a96a907/src/commands/PublishCommand.js#L242

## Expected Behavior

`GitUtilities.checkoutChanges()` should contain paths to packages from `lerna.json`.

## Current Behavior

`GitUtilities.checkoutChanges()` tries to checkout in hard coded `packages/*/package.json` path.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.5",
  "npmClient": "yarn",
  "packages": [
    "dist",
    "dist/core",
    "dist/easings"
  ],
  "version": "independent"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.5 |
| `npm --version`  | 5.0.3 |
| `yarn --version` | 0.24.6 |
| `node --version` | 6.9.5 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.5 |

**Comment by evocateur** [comment]
Oh hey, yeah, that's definitely a bug.

[This line](https://github.com/lerna/lerna/blob/4d64a2813ff0c35fd46ed745bbca1833e5cb86f0/src/commands/PublishCommand.js#L242) should be looping through the new [`this.repository.packageParentDirs`](https://github.com/lerna/lerna/blob/4d64a2813ff0c35fd46ed745bbca1833e5cb86f0/src/Repository.js#L65) collection (like DiffCommand does [here](https://github.com/lerna/lerna/blob/661b4f4292a285f47dc4a0219244fd6397371d6c/src/commands/DiffCommand.js#L56)) to construct the arguments to [`GitUtilities.checkoutChanges`](https://github.com/lerna/lerna/blob/56568d367bf8ff91fe2507b506a126097637a7ce/src/GitUtilities.js#L158) (which would need to accept an array as the first argument, not a string, and be spread into the args of the `execSync` call).

**Comment by exah** [comment]
Yes, sorry I have copied link to line with branch name not direct commit.
