### ISSUE TITLE
lerna [updated|diff] <commit>

### ISSUE THREAD

**Issue by chrisui** [lerna/lerna#876]
Given a use case where you want to optimise CI for a large monorepo based on _"what has changed?"_ it would be useful to be able to target git commits rather than always using the "last release" as is the current behaviour of `lerna updated` and `lerna diff`.

See https://github.com/lerna/lerna/issues/611 for more examples of this use case.

## Expected Behavior

- `lerna updated af943bg3` gives packages updated between git commit `af943bg3` and git `HEAD`
- `lerna updated af943bg3 fch034f4` gives packages updated between git commit `af943bg3` and git commit `fch034f4`
- `lerna diff af943bg3` gives files updated between git commit `af943bg3` and git `HEAD`
- `lerna diff af943bg3 fch034f4` gives files updated between git commit `af943bg3` and git commit `fch034f4`

#### Alternative syntax since `lerna diff` already has an argument (package name)

- `lerna updated --git-from af943bg3` gives packages updated between git commit `af943bg3` and git `HEAD`
- `lerna updated --git-from af943bg3 --git-to fch034f4` gives packages updated between git commit `af943bg3` and git commit `fch034f4`
- `lerna diff --git-from af943bg3` gives files updated between git commit `af943bg3` and git `HEAD`
- `lerna diff --git-from af943bg3 --git-to fch034f4` gives files updated between git commit `af943bg3` and git commit `fch034f4`

## Current Behavior

Currently `lerna updated` and `lerna diff` only give you the changed packages or files between `HEAD` and the "last release".

## Possible Solution

I believe it would be pretty simple to use the specified git <commit> instead of searching for the last release tag.

## Context

Trying to optimise CI with a large monorepo. Ie. On a small feature branch only run what is affected. This ties in with my desire to see https://github.com/lerna/lerna/issues/611 worked on.

## Your Environment

N/A

**Comment by chrisui** [comment]
Note I'm more than happy to implement this if we think it's a good idea! Would be great to get some pointers in the codebase to get going with. :)

**Comment by ricky** [comment]
I think #822 is is heading down that road. (Although, it lacks a `--git-to`/`--until` equivalent.)

**Comment by chrisui** [comment]
Awesome thanks @ricky

**Comment by chrisui** [comment]
Closing since https://github.com/lerna/lerna/pull/822 is merged!
