### ISSUE TITLE
Auto-updating dependencies breaks release

### ISSUE THREAD

**Issue by helfer** [lerna/lerna#879]
When running `lerna publish`, Lerna updates the npm dependencies of all packages and adds a git commit, apparently ignoring semver ranges defined in package.json.

## Expected Behavior
I don't expect `lerna publish` to automatically updating packages. I run CI tests on multiple versions of node, but I can only publish from one of them. The workflow that I use is to first make sure all CI tests pass, then release the packages with `lerna publish`. Having lerna auto-update the dependencies during that can break the released packages _after_ I've run the CI tests, which is really not convenient. See this PR here: https://github.com/apollographql/graphql-server/pull/425

## Current Behavior
I don't want `lerna publish` to update any packages, but I might be able to live with it if I could turn it off for specific dependencies. But `lerna publish` even updates packages that have an exact version defined, which makes it impossible to work around and isn't consistent with the docs (README.md). See this commit [here](https://github.com/apollographql/graphql-server/pull/425/commits/90a9ec78dadd27bc1eb419026eb219e99c87d6f5#diff-1d7cf40401abb403335e93ffb404f349R29).

## Possible Solution
Don't make `lerna publish` auto update dependencies just before releasing, or at the very least let people override it or turn it off somehow. There are other tools out there that help people keep dependencies updated.

## Steps to Reproduce (for bugs)
Run `lerna publish` on a package that has a non-current dependency in package.json. It will get updated to the most current version, even if that version isn't in the semver range.

## Your Environment
Lerna version 2.0.0-rc.4, node version 4.4.7

**Comment by evocateur** [comment]
`lerna publish` should never be modifying dependencies that it doesn't explicitly manage (the other siblings under `./packages`). To be clear, you are seeing `lerna publish` modify _non_-managed dependency versions?

**Comment by helfer** [comment]
@evocateur My apologies, this doesn't seem to have anything to do with Lerna. Thanks to your reply I noticed that the project I was working on is running a rather curious script that updates dependencies on every release.
