### ISSUE TITLE
Opt-out of bootstrap lifecycles

### ISSUE THREAD

**Issue by loklaan** [lerna/lerna#881]
## Expected Behavior

When `lerna bootstrap` is given a `--noscripts` flag, it should skip the following steps in the BootstrapCommand:
* `preinstallPackages`
* `postinstallPackages`
* `prepublishPackages`

## Current Behavior

There is no way to opt out of the above lifecycle events.

## Possible Solution

Add a `--noscripts` flags, that when present, caused the BootstrapCommand to skip the above listed lifecycle functions.

## Context

When bootstraping a project, I want all the lifecycle events to occur to do building/testing.

However, imagine for a moment that I am in a project that need's its dependencies hoisted. After already running bootstrap, I decide to add a dependency to `package-x` - I then need to use lerna to install this dependency with `bootstrap --hoist`. In this case, I don't care about running lifecycle events to do builds/test... I just want to download and install dependencies from npm, and continue development.

P.S. `npm` & `yarn` both have flags for opting out of lifecycle functions for the above stated reasons.

---

There may be a better approach to achieving this particular case of updating hoisted dependencies from edited package.json's, or even clearer wording in the suggested flag.

**Comment by evocateur** [comment]
You should use `--scope` to limit the bootstrap actions to the affected package.

```sh
lerna bootstrap --scope affected-package-name
```

Disabling scripts during bootstrap is potentially dangerous, given that we're already breaking up the normal flow of the install lifecycle to begin with. I'd rather not introduce that footgun when other solutions exist.

**Comment by loklaan** [comment]
Hey, thanks for jump on the issue!

Also for the advice on `--scope`.

Goodluck closing off issues - it looks like you're getting through a lot lately!

---

### Notes for posterity

The real issue here is decreasing the time your project spends in `lerna bootstrap`, since you realistically need to be running it often when doing heavy development.

_In case someone stumbles on this, looking to improve that bootstrap time._

While I think my suggestion (`--no-scripts`) still holds merit for the public release, we privately found that removing all but the most necessary lifecycle scripts (eg `prepublishOnly`) permanently helped the bootstrap time of our growing packages repo.

Initially we would require transitive dependencies (internal packages depending on other internal packages) to be built so that including them with `import`/`require` in another internal package would use the same files that would end up on the npm registry.

This was slow, not only because `bootstrap` time was long, but because developing across several inter-dependent packages ment that a developer would have to situationally run `npm run build` in a package; this added to things a dev needed to know about and was confusing.

Moving forward we made sure that all of our tooling (webpack / jest) would pull in the uncompiled source files of transitive dependencies and do the necessary building of those files on the fly. Only at publish time would the built files need to be output and packed.
