### ISSUE TITLE
installing npm package

### ISSUE THREAD

**Issue by gpltaylor** [lerna/lerna#882]
I have a Lerna solution up and running. 

I want to install a third party lib, however, when I run "npm install" or "yarn add" it fails. The reason is that the npm is trying to resolve the packages, and one is a lerna package, not an offical npm package.

```
$ yarn add --dev react-router
yarn add v0.21.3
[1/4] Resolving packages...
error Couldn't find package "fl-server" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

note that 'fl-server' is a private package within my packages folder and included in 

```
  "devDependencies": {
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
...
    "fl-server": "^1.0.0",
    "fl-components": "^1.0.0"
  }
```

How do I install third party packages?

**Comment by gpltaylor** [comment]
NOTE: I am solving this issue by manually adding the package to **packages.json**, then running 
``$ lerna bootstrap``

This works really well, but I want to confirm if this is the correct way?

**Comment by danoc** [comment]
@gpltaylor I believe you're doing this the right way.

**Comment by gpltaylor** [comment]
Thank you @danoc

**Comment by evocateur** [comment]
For adding a dependency to a lerna-managed `package.json`, editing the file directly and then running `lerna bootstrap` is the correct method.

**Comment by altayaydemir** [comment]
@evocateur doesnt it affect the usage of npm-shrinkwrap in a bad way?

**Comment by evocateur** [comment]
It's not recommended to shrinkwrap lerna-managed modules.

**Comment by danoc** [comment]
@evocateur – Does that mean the packages should also not have a `yarn.lock`? (Feel free to point me to documentation! 😄 )

**Comment by evocateur** [comment]
Yarn is a different beast. There really isn't any lerna-specific documentation either way, sorry.
