### ISSUE TITLE
How to add packages when using yarn.

### ISSUE THREAD

**Issue by richburdon** [lerna/lerna#884]
Am I missing something? I have lerna's npmClient option set to yarn. And bootstrap works, but how do you actually add new packages (since yarn breaks in each sub package)? 

## Expected Behavior
In a sub-module: `yarn add xxx`

## Current Behavior
``error Couldn't find package "my-sub-package" on the "npm" registry.``

## Possible Solution
a) Provide top-level mechanism to add packages to a sub package
b) Fix yarn to not complain about local packages

**Comment by altayaydemir** [comment]
does it work as expected for npm?

**Comment by richburdon** [comment]
Yes, everything is fine with npm4 (not 5). I'd recommend removing the yarn option (it cost me weeks trying to get it to work and working around it until getting the feedback that npm4 is really the only viable option).

**Comment by richburdon** [comment]
Sorry, didn't mean to close it -- yarn is still unresolved.

**Comment by MiguelMadero** [comment]
Looks like https://github.com/lerna/lerna/pull/425 could help with this.

**Comment by evocateur** [comment]
[`lerna add`](https://github.com/lerna/lerna#add) was added in [v2.5.0](https://github.com/lerna/lerna/releases/tag/v2.5.0), which should address this use case.
