### ISSUE TITLE
Lerna hangs with invalid package versions and yarn

### ISSUE THREAD

**Issue by rcchen** [lerna/lerna#885]
When using `yarn` as `npmClient`, if one of the packages has a dependency with an invalid version, `lerna bootstrap` will hang at the `Installing external dependencies` step.

## Expected Behavior

Should error out like when using `npm` as the `npmClient`, indicating that versions cannot be found and whatnot.

## Current Behavior

Hangs on `Installing external dependencies`

## Possible Solution

If the reason is because installing packages when `npmClient: yarn` involves running `yarn add` in the target package instead of just listing it in `package.json` then running `yarn bootstrap` at the top level, then feel free to close this issue, if there's documentation somewhere I was not able to find it. Maybe a clarification on `yarn` usage in the `README`?

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.4 |
| `npm --version`  | 4.2.0 |
| `yarn --version` | 0.24.5 |
| `node --version` | 7.10.0 |

| OS | Version |
| ---: | :--- |
| macOS Sierra | 10.12.5 |

**Comment by tricoder42** [comment]
I think it's caused by input dialog, which `
yarn` shows when it cannot find the version. `npm` just throws an error.


<img width="493" alt="snimek obrazovky 2017-06-26 v 13 09 29" src="https://user-images.githubusercontent.com/827862/27536713-a8162112-5a70-11e7-8c47-99d30f3d6bbf.png">

**Comment by jadengore** [comment]
@tricoder42 That would make sense, when I try to run `lerna bootstrap` it endlessly hangs, which would suggest an interactive mode issue
