### ISSUE TITLE
Not clear from docs how to use shared modules that are not packages

### ISSUE THREAD

**Issue by vitalets** [lerna/lerna#888]
Hey,

I have lerna-project with several packages and in all packages I want to use one shared module. Although I don't want shared module itself to be a package. It's just some common logic. E.g.
```
my-lerna-repo/
  package.json
  shared-module.js <-- used in several packages
  packages/
  ...
```

Is it possible with lerna?

**Comment by evocateur** [comment]
That's a textbook case for a package, consumed as a dependency by the dependent modules. If it's required in _any_ code that is included in published packages, it needs to be a package itself. Otherwise your packages are broken.

**Comment by vitalets** [comment]
>  If it's required in any code that is included in published packages, it needs to be a package itself. 

Thanks for the reply! Could you explain a bit more?
For example I have `utils`module that I use in any published package. 
So I'm required to publish `utils` to npm?

**Comment by evocateur** [comment]
If you `require()` or `import` a module at runtime, it needs to either be a part of the package tarball (when published), or a dependency. So if this `utils` module is needed when consumers of your package require your module, then yes, it needs to be its own package published to npm.

**Comment by vitalets** [comment]
Ok, thanks a lot for explaining!
