### ISSUE TITLE
Bootstrap removes node_modules from root (during hoist).

### ISSUE THREAD

**Issue by richburdon** [lerna/lerna#889]
## Expected Behavior
`lerna bootstrap --hoist` should install root and sub package dependencies.

## Current Behavior
The root `node_modules` are deleted (except for hoisted packages).

## Possible Solution
Honor the root `package.json` file.

## Steps to Reproduce (for bugs)
1. Add a package to the root package (e.g., eslint in devDependencies).
2. Run lerna bootstrap --hoist xxx

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.5 |
| `npm --version`  | 5.0.3 |
| `yarn --version` | 0.24.6 |
| `node --version` | v8.1.2 |

**Comment by evocateur** [comment]
@richburdon Can you provide an example repo? I'm a bit mystified by the context of this error.

**Comment by doug-wade** [comment]
Closing due to the lack of a repro or response
