### ISSUE TITLE
[Feature] Option instead of lastTag/lastRelease for updated packages

### ISSUE THREAD

**Issue by hzoo** [lerna/lerna#89]
Right now we figure out what packages to publish based on a git diff of the lastTag.

However in the case of a backport (you might publish v5.x.x after a v.6.x.x) and now the lastTag is actually v5.x.x, so maybe you should be able to pass in a tag, otherwise default to the latest (we should log out the last tag if we aren't already or prompt it).

**Comment by thejameskyle** [comment]
If you are in a separate branch for the older version I assume we can just change:

```diff
- git rev-list --tags --max-count=1           # get commit of last tag across branches
+ git rev-list -n 1 $(git describe --tags)    # get commit of last tag in current branch
```

[[ref](https://github.com/kittens/lerna/blob/master/lib/utils/gitUtils.js#L26)]

**Comment by hzoo** [comment]
Would you ever want to do anything else such that you might want to specify the version manually? Probably not right?

What do you think about logging that info in the lerna updated/publish command as well? Basically something like `Checking updated files since v6.8.1`

And based on your suggestion, we just check the current branch - if it's `master` do the regular command, and if it's not do the 2nd one?

**Comment by Gongreg** [comment]
Dumb, We got into this issue, that if we do changes on different branches for different versions, we need to use newest tag in that branch, not in whole project. Could we try to do a pull request for this feature? Maybe add passing some kind of parameter for turning this option on?
