### ISSUE TITLE
Support for --conventional-commits in Fixed/Locked mode

### ISSUE THREAD

**Issue by nicojs** [lerna/lerna#890]
As of now, the `--conventional-commits` flag only works for independent mode.

## Expected Behavior
Given this lerna.json:

```json
{
  "lerna": "2.0.0-rc.5",
  "packages": [
    "packages/*"
  ],
  "command": {
     "publish": {
       "conventionalCommits": true
     }
  }
  "version": "0.1.0"
}
```

When running `lerna publish`.

Then i would expect the locked version to be determined based on the highest bump of one of the packages.

For example: i have 3 packages:

```
packages
  /one
  /two
  /three
  /four
```

Package "one" has a breaking change, package "two" has a new feature, package "three" has a bug fix and package "four" has no changes.

I would expect the determined version to be a major release (v0.2.0 in this case). 

## Current Behavior

Currently, --conventional-commits are only supported in "independent" mode, as discussed in #850

**Comment by rsouthgate** [comment]
In addition to a +1, I was wondering if lerna publish could be invoked with a version number in the fixed mode.

In my use case while waiting for --conventional-commits to be supported in fixed mode I could use semantic-release to work out the global version number based on all commits to all packages across the monorepo and then pass this to lerna publish to use in our CI environment.

Looked at the source and couldn't see a way of bypassing the version prompt without using canary or cdVersion (but I don't want to rely on lerna bumping the major/minor/patch based on cdVersion, I'd rather pass the actual computed semantic version from semantic release).
