### ISSUE TITLE
How to apply flow type checking in lerna managed project?

### ISSUE THREAD

**Issue by mocheng** [lerna/lerna#891]
Since Lerna hoists common npm packages into root `node_modules` folder, running `flow` in each package cannot find these common npm packages in its own `node_modules` folder. It would fail with error message as below. 

```
  5: import {createStore, applyMiddleware, combineReducers, compose} from 'redux';
                                                                          ^^^^^^^ redux. Required module not found
```

In above case, `redux` is hoisted to `node_modules` in root `node_modules`.

Is there any practice to workaround for flow type-checking?

**Comment by slightlytyler** [comment]
Would love to use hoist but this feature is holding me back. Seems like this might be an issue we need to raise on the flow repo? It should follow the node module resolution pattern talked in hoist (or at least thats my understanding)

**Comment by wtgtybhertgeghgtwtg** [comment]
I have [a `lerna` repo](https://github.com/wtgtybhertgeghgtwtg/redux-modules) that heavily uses flow and I have never run into this issue.
What I am running into is `conventional-changelog-core` breaking Flow due to a malformed test that [they do not intend to fix](https://github.com/conventional-changelog/conventional-changelog/issues/197).  It might help if `lerna` used something else.

**Comment by evocateur** [comment]
@mocheng Can you provide an example repo? It would be interesting to see what differences with @wtgtybhertgeghgtwtg's setup are contributing to this problem.

**Comment by mocheng** [comment]
@evocateur I checked @wtgtybhertgeghgtwtg 's repo and found the difference. In that repo, flow is run[ at root](https://github.com/wtgtybhertgeghgtwtg/redux-modules/blob/master/package.json#L42) instead of each package. And, there is a `flow-typed` sub folder holding dependency package libdef.

Surely, we can leverage same strategy to make flow work in lerna. But, it is preferred to enable each sub-package could run flow independently without much setup.

**Comment by Inkdpixels** [comment]
@mocheng @evocateur @wtgtybhertgeghgtwtg @slightlytyler FYI there is a CLI called [flow-mono-cli](https://immoweltgroup.gitbooks.io/flow-mono-cli/) which solves most of the issues when working with flow in a mono-repo. Check it out, if you have any additional feature requests or feedback I am more than happy to hear from you guys! :)

**Comment by sibelius** [comment]
@Inkdpixels flow-mono-cli solves the problem

we can close this

**Comment by steelbrain** [comment]
@sibelius Relying on third party solutions is not ideal. While I agree this particular issue is out of scope for Lerna itself, I still think it should be taken care of in flow instead of some third party wrapper or fork

**Comment by steelbrain** [comment]
A PR to fix this has been opened at https://github.com/facebook/flow/pull/6504
