### ISSUE TITLE
Common Dependencies

### ISSUE THREAD

**Issue by jacobp100** [lerna/lerna#892]
We've building a monorepo of React components, and each of these components is using ant Design as its fundamental building blocks. To ensure consistency, I put `antd` in the top-level `package.json`.

```json
{
  "dependencies": {
    "antd": "^2.9.3"
  },
  "devDependencies": {
    "lerna": "^2.0.0-rc.5"
  }
}
```

However, when running `lerna bootstrap`, these are not installed anywhere.

My workaround has been to run `npm install`  in the top level.

Is it intended behaviour to not support this? If so, what is the recommended approach for doing something like this?

**Comment by lukebatchelor** [comment]
That sounds like the intended behaviour to me, you wouldn't expect it to be placed in the node_modules of a package that doesn't have an implicit dependency on it right?

It will still be resolvable from within the packages though as normal resolution will keep walking up directories looking for a `node_modules`.

**Comment by evocateur** [comment]
@jacobp100 You should [`lerna bootstrap --hoist`](https://github.com/lerna/lerna/blob/master/doc/hoist.md) so your packages themselves can express the proper dependency and not be broken when others install them.
