### ISSUE TITLE
Durable options in lerna.json

### ISSUE THREAD

**Issue by treshugart** [lerna/lerna#893]
In https://github.com/lerna/lerna/pull/822#issuecomment-303191481 you mentioned wanting to start using `options` more. I'm wondering if this is something you'd like to do across the board because I'm interested in doing this.

## Possible Solution

Currently, my naive approach to this would be to rename references of `flags` to `options`, but obviously this is without digging in.

## Context

Our use case is being able to specify sane defaults for our workflows. For example, being able to specify `stream: true` by default for most of our workflow commands makes sense and this currently doesn't seem to work.

## Your Environment

A [fork](https://github.com/treshugart/lerna) of 2.0.0-rc.5.

**Comment by ricky** [comment]
AFAIK, exactly what you're suggesting was done in https://github.com/lerna/lerna/pull/844. Not sure if there's more to it than that.

**Comment by treshugart** [comment]
Oh, awesome. Thank you! I'm running a fork so I can have #847 so I probably just need to update. I'll reopen if there's any issues and update the description.

**Comment by treshugart** [comment]
This doesn't seem to be working for options like `stream` and `parallel`.

**Comment by treshugart** [comment]
Ok, I found the core issue. I'll raise a separate issue outlining the problem and will fix it.
