### ISSUE TITLE
Commands Publish on lerna.json are ignored

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#902]
Commands configs on lerna.json are being ignored

## Expected Behavior
I wanted every lerna publish to take in account both the conventionalCommits and message configs that exists on the lerna.json file

## Current Behavior
It is ignoring all the configs under the publish command

```json
{
  "lerna": "2.0.0-rc.5",
  "packages": [
    "src/*"
  ],
  "registry": "https://tools-int.caseonit.net/npm",
  "commands": {
    "publish": {
      "conventionalCommits": true,
      "message": "chore: Publish"
    }
  },
  "version": "independent"
}

```

As you can see, both message and conventional commits are included as part of lerna.json. However they are not being applied.

I'm running lerna this way:

`lerna publish --conventional-commits`

That is the only way to make conventional commits argument to work.

I was trying this without any luck

`lerna publish`

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` |  2.0.0-rc.5 |
| `npm --version`  | 4.1.2 |
| `node --version` | 7 |

**Comment by evocateur** [comment]
I believe this was fixed by @treshugart in #898. I hope to publish it soon.

**Comment by M3kH** [comment]
@evocateur I guess is related to this line https://github.com/lerna/lerna/blob/d0e8d9c5af654f52634119d2c2bd2a888b9488f0/src/commands/PublishCommand.js#L683
That has a different behaviour than this:
https://github.com/lerna/lerna/blob/d0e8d9c5af654f52634119d2c2bd2a888b9488f0/src/commands/PublishCommand.js#L695

**Comment by evocateur** [comment]
As far as I can tell, customizing the commit message during an `--independent` publish is already validated here: https://github.com/lerna/lerna/blob/1d7eb9eeff65d5a7de64dea73613b1bf6bfa8d57/test/PublishCommand.js#L680-L688

**Comment by danielo515** [comment]
So it'd the new version which includes this fixed published?

**Comment by evocateur** [comment]
In the sense that you can override the heading of the independent publish message, yes, for several releases now. Still can’t interpolate the placeholder, as there is no unitary version that makes any sense in independent mode.

**Comment by danielo515** [comment]
> In the sense that you can override the heading of the independent publish message, yes, for several releases now

Are we talking about doing it through lerna.json right ?

**Comment by evocateur** [comment]
Yes.
