### ISSUE TITLE
Lerna@2.0.0-rc5 incompatable with npm@5

### ISSUE THREAD

**Issue by BurtHarris** [lerna/lerna#906]
This may have the same root cause as #903: an incompatibility with npm version 5, but my repro case is quite different.   However I've tried it with npm@4.6.1 and I'm getting pretty much the same results.

My repro has one package which implements a command-line tool which is used in building the other three packages in the repro.   When I run `lerna bootstrap`, it seems to be attempting to hoist that tool to the root, when I need it, it's not there.

I'm wondering why lerna isn't simply setting up the links with `npm link packge/tool` command(s), instead of custom-building the symbolic links and command-line stub files.   

## Expected Behavior
Build steps depending on custom tool should work

## Current Behavior
With NPM 5 installed, when I execute a build step dependent on my tool, build I get :
```
[15:09:00] Error: Command failed: npm run antlr4ts
module.js:487
    throw err;
    ^
Error: Cannot find module 'antlr4ts-cli'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)                                                                                                          at Object.<anonymous> (C:\code\antlr4ts\packages\tool\antlr4ts:3:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

## Possible Solution
Why not setup the inter-package dependencies with `npm link` or `npm add` commands, so that npm isn't confused by what lerna is doing?

## lerna.json
```json
{
  "lerna": "2.0.0-rc.5",
  "packages": [
    "packages/*"
  ]
}
```
## Context
Timing here has been really bad, I started to try to use Lerna just about the same time as NPM@5 was released.   Its seriously complicated matters, just documenting there are known incompatibilities with NPM@5 should be a high priority.

At this point I've got to bail-out on Lerna and finish without it.   But I sure hope these growing pains can get worked out soon.

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.5|
| `npm --version`  | 5.0.4 |
| `yarn --version` | 0.24.5|
| `node --version` |8.1.3 |

| OS | Version |
| --- | --- |
| Windows| 10.0.15063|
-->

**Comment by DavideDaniel** [comment]
Had to revert to the following to get it to work:

**Comment by evocateur** [comment]
If you're calling a CLI provided by a devDependency in a leaf package.json, it needs to be specified in that package.json. `--hoist` is a bootstrap optimization and does not remove the necessity for expressing proper package dev/dependencies.

As I've mentioned several times in the last week alone, `npm link` is not appropriate for the needs of a monorepo for a variety of reasons.

**Comment by mlunoe** [comment]
Could you direct me to where you have mentioned that before and/or maybe elaborate a bit on why `npm link` is not appropriate for the needs of a monorepo?
I did find a bit of info here is that the right place to look?
https://github.com/lerna/lerna/issues/11#issuecomment-234738279

**Comment by evocateur** [comment]
That's a decent summary. There are other issues with npm link at present, one of them being that it is soon to be rewritten according to a thread I saw somewhere...
