### ISSUE TITLE
When using with workspaces, yarn ignores nohoist settings 

### ISSUE THREAD

**Issue by Bnaya** [lerna/lerna#909]
When delegating the workspace bootstrap handling to yarn ( #899 ) 
the nohoist setting in lerna.json/cli param not taken into account.

I can understand why, most of the bootstrapping happens on the yarn install ,even before the lerna bootstrap.

**Comment by Bnaya** [comment]
My settings was wrong, gonna recheck it

**Comment by Bnaya** [comment]
Ok, yes its still true

**Comment by thomasfr** [comment]
I created an issue at yarn for supporting `--no-hoist` like lerna: https://github.com/yarnpkg/yarn/issues/3882

**Comment by bestander** [comment]
This is an issue with Yarn, this issue can be closed
