### ISSUE TITLE
`package-lock.json` files on the packages, is that the right behavior?

### ISSUE THREAD

**Issue by moshest** [lerna/lerna#913]
Every time when I edit the `package.json` file of one of my packages and add a new dependency, I got a new `package-lock.json` file on that package after the new dependency installed.

I wondering if that's the right behavior.
Should sub-packages also have `package-lock.json` files?

**Comment by rgbkrk** [comment]
Thanks for asking this, I really wish I knew what the right thing to do with lerna and npm 5 was.

**Comment by moshest** [comment]
I think that one `package-lock.json` at the root of the project should be enough.

_Lerna_ should install all the dependencies on the root `node_modules` folder and then link them to the required sub-packages. If there is a collision, lerna should install the specific version only for the  specific sub-package and handle internal `package-lock.json` by it self.

This behavior will save time and be more clear for the new user (like me).
In addition, [it's pointless](https://docs.npmjs.com/files/package-lock.json) to add `package-lock.json` to sub-modules:

`One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package.` 
 

My solution for now is to use lena with `--no-package-lock` command:
```bash
$ ./node_modules/.bin/lerna bootstrap -- --no-package-lock
```

**Comment by unional** [comment]
> Lerna should install all the dependencies on the root node_modules folder and then link them to the required sub-packages.

This is the hoist scenario.
If I understand correctly, hoist doesn't work if I want to be able to open each package directly (for IDE support).
i.e., instead of opening `mylernaproject`, I want to open `mylernaproject/packages/x` and `mylernaproject/packages/y`

**Comment by moshest** [comment]
> If I understand correctly, hoist doesn't work if I want to be able to open each package directly (for IDE support).

The linking process should be for all the packages on the root `node_modules` to the sub-packages `node_modules` folders. This will enable IDE support and more important an ESLint validation.

**Comment by evocateur** [comment]
There's a lot of stuff todo re: npm5 and package-locks. I didn't even know package-lock.json was supposed to be ignored if not at the "top-level". Seems ambiguous, to me.

**Comment by alex-pex** [comment]
You should definitely find a way to use lerna **WITH** package locks. The default behavior wanted with npm@5 is to lock the versions. I'm not using yarn but I think it's using lock files too (yarn.lock). I develop apps with shared packages and I don't want to ship my apps with unknown package versions.

I'll get rid of my lock files for the moment but I'm looking for a better solution.

**Comment by mikestead** [comment]
Just a note on one scenario. I've been using `Lerna` to manage a bunch of node (micro-)services. 
Each package is released as a Docker image. When I build that image I want to npm install the exact prod dependencies to ensure correctness. For this setup a lock file per package is required. 

Perhaps not what `Lerna` was envisioned for but thought worth a mention.

**Comment by kirill-konshin** [comment]
I bet this has to be reopened...
