### ISSUE TITLE
No docs on how to publish public scoped packages

### ISSUE THREAD

**Issue by cdaringe** [lerna/lerna#914]
## Expected Behavior

- able to `lerna publish` public scoped packages

## Current Behavior

```
lerna ERR! execute  Error: Command failed: npm publish --tag latest
lerna ERR! execute npm ERR! publish Failed PUT 402
lerna ERR! execute npm ERR! Darwin 15.6.0
lerna ERR! execute npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish" "--tag" "latest"
lerna ERR! execute npm ERR! node v7.10.0
lerna ERR! execute npm ERR! npm  v4.2.0
lerna ERR! execute npm ERR! code E402
lerna ERR! execute
lerna ERR! execute npm ERR! You need a paid account to perform this action.
```

## Possible Solution

- get some docs on how to do so.  the readme suggests that this is supported.  i'll submit the patch if i can find the info!

## Steps to Reproduce (for bugs)

- `lerna publish` in a project compose of scoped packages

**Comment by zxqfox** [comment]
In npm: `npm publish --access public`

Please try: `lerna publish -- --access public`
Does it work?

p.s I have scoped packages too and want to use `lerna` to publish them all.

**Comment by cdaringe** [comment]
@zxqfox, same error as above

**Comment by robdonn** [comment]
I'm running into the same problem. A temporary solution may be a custom script.

In the root package.json:
`"publish": "lerna publish --skip-npm && lerna run publish-npm"`

Then in each package json you could have:
`"publish-npm": "npm publish --access public"`

**Comment by akosyakov** [comment]
Does anybody try: https://github.com/lerna/lerna/issues/178#issuecomment-261736824?

**Comment by hshoff** [comment]
Yes the solution in https://github.com/lerna/lerna/issues/178#issuecomment-261736824 works for publishing scoped packages. Check out https://github.com/hshoff/vx for an example repo. It's been working for me since March when I started the project.

Solution is to add the following to each packages `package.json`:

```json
  "publishConfig": {
    "access": "public"
  }
```

**Comment by evocateur** [comment]
PRs welcome to add this solution to the documentation
