### ISSUE TITLE
issues with publish commend for dependencies version

### ISSUE THREAD

**Issue by streamgao** [lerna/lerna#916]
- we have some different services for centralized build / publish than npm. 
and the real publish step would be triggered into the last step. 

## issues
- so when running publish command.  Both version / dependency version would be bumped to the newest one.  it would cause us problem like dependency 's newest version doesn't exist.
For example. 
If both package A and B got upgraded, and B requires A as dependency.
Say A upgrades from `VersionA0` to `VersionA1` and B from `VersionB0` to `VersionB1`. 
In B's package.json, the A's version would be automatically bumped to A's VersionA1. 

However, since we have different deploy service that we does not publish to npm.   A would not finish build/publish yet.   Only when both A and B builds get passed, then publish.  
So the latest dependency version would hurt for services that doesn't publish like npm. 

## current behaviour
- before:
A's package.json:
```
"version": "a.1.0.0"
```

in B package.json:
```
"dependencies": {
    "A": "^a.1.0.0"
     ...
}
"version": "b.1.0.0"
```
- after
A's package.json:
```
"version": "a.1.0.5"
```

in B package.json:
```
"dependencies": {
    "A": "^a.1.0.5"
     ...
}
"version": "b.1.0.2"
```

## Expected Behavior
separate version bump in version / dependencies version during publish command. 
1. automatically publish the dependency version to be one lower than the newest. 

2. offer option to keep the old dependency versions
i.e.   `$ lerna publish --dep-version=old | next | latest | beforelatest`
- for example after
A's package.json:
```
"version": "a.1.0.5"
```

in B package.json:
```
"dependencies": {
    "A": "^a.1.0.4"
     ...
}
"version": "b.1.0.2"
```

**Comment by evocateur** [comment]
Lerna always publishes packages in topological order; that is, dependencies before dependents.

We've already had the discussion about "only bump changed dependencies" several times. The answer is the same: we will _always_ bump dependent versions when a dependency version changes.

Lerna only supports `npm publish`, as it is designed to aid publish npm packages.

If you need to inject a "staging" step in the publish process, you can pass `--temp-tag` to `lerna publish` and it will publish the changed modules under the `lerna-temp` dist-tag before switching them all to the `latest` dist-tag.
