### ISSUE TITLE
question

### ISSUE THREAD

**Issue by yxuecheng** [lerna/lerna#917]
i want to build a component library like [ElemeFE/mint-ui](https://github.com/ElemeFE/mint-ui)，so i want use lerna ，but i don't publish it to npm just push it to my github rep，can i use lerna publish？

**Comment by FabienDeshayes** [comment]
You can use `lerna publish --skip-npm`. See [doc](https://github.com/lerna/lerna#--skip-npm).

**Comment by yxuecheng** [comment]
thank you ，if i use webpack ，the packages folder of component ，each component has a webpack.config file for bundle？？
