### ISSUE TITLE
How to publish all packages if root was modified

### ISSUE THREAD

**Issue by oreporan** [lerna/lerna#920]
## Expected Behavior
When I modify my root package.json with things that modify all the submodules (such as babel transpile configurations in .babelrc) I expect that all the packages will be "affected" causing `lerna publish --conventional-commits --yes` to publish all packages.

## Current Behavior
I modify .babelrc file and the prepublish script, but none of my submodules get published so they can never take the new publish script.

## Workaround
Make all my packages depend on the root package.json
This is also a problem because my root project is not released to `npm`

## Possible Solution
maybe a list of files that cause all packages to be published, or a flag of `--root=true` which publishes all packages if anything in the root of the project is changed.

## Steps to Reproduce (for bugs)
1. Create package.json with `"prepublish": "lerna exec --parallel -- babel *.js src/*.js --out-dir dist/"` and another package under the root
2. change the prepublish script from `src/*js` to something else like `source/*js`
3. run `lerna publish`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0",
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "commands": {
    "publish": {
      "ignore": [
        "*.md",
        "test/**"
      ]
    }
  }
}

```
</p></details>

**Comment by jezzay** [comment]
As a workaround, you could manually force publish all packages with   `--force-publish=*`  https://github.com/lerna/lerna#--force-publish-packages 

`lerna publish --force-publish=* --conventional-commits --yes`

**Comment by oreporan** [comment]
That workaround assumes I know only the root has changed. Im trying to avoid calculating the diff

**Comment by evocateur** [comment]
Conventionally speaking, the root package.json should never be depended on by the "leaf nodes" (the lerna-managed `./packages/*`). I think the `--force-publish` solution is more than sufficient for this (hopfully) rare case.

**Comment by oreporan** [comment]
Would a Pull Request that creates this feature be merged? Such as a list of files that turn a publish into a force publish?

**Comment by evocateur** [comment]
No, because this isn’t something that happens frequently enough to merit automation. No change to the Babel configuration “just happens.” You’re always capable of identifying if anything changed since the last release and cutting a release to “clear the decks” before a force-published Babel (or other root) change.
