### ISSUE TITLE
Question: How to publish git github instead of npm in independant mode

### ISSUE THREAD

**Issue by pierr** [lerna/lerna#923]
I would like to publish a tree of components in independent mode using git tags instead of npm.
The main problem is that after doing an `npm install`of a `git tag` i don't have the same structure as an `npm` published repo.
> Is there something to do in order to be able to have this working?

**Comment by evocateur** [comment]
If you're trying to install a lerna-managed package from a github version specifier (e.g., `"yargs": "myfork/yargs"`), I'm afraid that won't work. If you need to provide prerelease versions, I would suggest `lerna publish --canary`.
