### ISSUE TITLE
Config option for hoist.

### ISSUE THREAD

**Issue by richburdon** [lerna/lerna#924]
It's unclear (to me) how to spec multiple packages to hoist.

## Expected Behavior
Possibly Bug: The documentation isn't clear. I read "glob" to mean regex, but:
`lerna bootstrap --hoist="(aws-sdk)|(graphql)"`
Doesn't work.

Feature: Add field to learn.json to specify hoisted packages.

## Current Behavior
Endless errors that doesn't seem to relate to hoisting.
`lerna ERR! execute Error: Command failed: npm install --global-style`

## Possible Solution
`lerna.json`
~~~~
{
  "hoist": ["aws-sdk", "graphql"]
}
~~~~

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.5 |
| `npm --version`  | 5.0.3 |
| `node --version` | v8.1.4 |

**Comment by noherczeg** [comment]
I believe it expects a globbing pattern. If you look at the sources you can see a reference to the format:

https://github.com/lerna/lerna/blob/master/src/commands/BootstrapCommand.js#L26

**Comment by noherczeg** [comment]
I'd try the `or` pattern with the carrets like it's described here: https://github.com/sindresorhus/globby#globbing-patterns

**Comment by Robinfr** [comment]
@noherczeg That works for me.

**Comment by evocateur** [comment]
`"hoist": "{aws-sdk,graphql}"` should work.
