### ISSUE TITLE
How to run custom command right after lerna bumps package version number

### ISSUE THREAD

**Issue by vass-david** [lerna/lerna#925]
## Problem
We are using npm@5 with lock files. Every package release updates version of package (obviously), but lock files are not updated. This causes update of lock files after release while developer works on different things (not even in same package), which triggers release of that package again even if nothing has changed simply because "some" file in that package has changed from last release.

## Question
Is there any possibility to run npm install after package version is bumped but before creating "releasing components" commit? This could solve that issue. Adding "npm install --ignore-scripts && git commit -an --amend --no-edit" to "prepublish" script seems a bit hacky to me.

**Comment by evocateur** [comment]
We essentially want something like `npm version <newVersion> --no-git-tag-version`, which automatically updates the `package-lock.json` version key.

**Comment by gauntface** [comment]
+1 this request.

Normally I would run `npm version` perform any build steps that needed this new package version (i.e. build a new version of the lib / tool with this new version inlined) and then publish that to NPM.

Lerna requires --skip-git, --skip-npm, build then build with --repo-version.

**Comment by evocateur** [comment]
We added calling the `version` lifecycle scripts in #1029 (and made properly synchronous in #1030), if that helps any. We still have a few issues related to npm5 compatibility, one of them being calling npm to update the version as I described so the lockfile gets updated, too.

**Comment by gauntface** [comment]
oohh thanks @evocateur this seems to solve my use case :)
