### ISSUE TITLE
How to exclude several dependencies from hoisting?

### ISSUE THREAD

**Issue by akosyakov** [lerna/lerna#926]
Could I do something like `--nohoist=node-pty|electron-rebuild`?

**Comment by gre** [comment]
according to [this code](https://github.com/lerna/lerna/blob/1084189c3e4dda1929754047ab499131de2cf8b5/src/PackageUtilities.js#L19) what you suggested should work, it uses library `minimatch` , see syntax: https://www.npmjs.com/package/minimatch

**Comment by dwaligora** [comment]
Hi Guys,

Unfortunately, that does not work for me.
I tried with

`--nohoist=+\(react\|intl\)*`

but does not seem to work (even it is working fine with the https://github.com/isaacs/node-glob).

My goal is to nohoist several different packages: `react`, `react-native`, `intl`, etc

Any idea folks?

**Comment by akosyakov** [comment]
It did not work for me either, so I've found a solution with all dependencies hoisted for my issue.

**Comment by dwaligora** [comment]
@akosyakov unfortunately I am using lerna for react and react-native apps and there is bunch of problems with dependencies. Probably I wont use `hoist` which is a bit pitty

**Comment by natew** [comment]
anyone figure this out? I tried using negative glob: `!(react)` and no dice.

**Comment by evocateur** [comment]
`--nohoist` is effectively an implicit negation. You can pass as many `--nohoist=<glob>` arguments as you want, they'll be iterated in order to filter the list. The glob itself should match the package name, not directory or any other value.
```sh
lerna bootstrap --nohoist node-pty --nohoist electron-rebuild
```

Alternatively, you can provide an array under `command.bootstrap.nohoist` in `lerna.json`:
```json
{
  "lerna": "2.0.0",
  "command": {
    "bootstrap": {
      "nohoist": [
        "node-pty",
        "electron-rebuild"
      ]
    }
  },
  "version": "1.0.1"
}
```

**Comment by natew** [comment]
Thank you Daniel, was exactly what I was looking for.
