### ISSUE TITLE
Publish --exact & removing symlinks

### ISSUE THREAD

**Issue by cloudratha** [lerna/lerna#927]
I'm currently evaluating the use of Lerna for an upcoming project.

Adding the exact flag during publish sets the dependency modules to the exact version you are publishing.

After Publishing I would expect that the symlinks in the packages be replaced with the current state of the package. This behaviour is honoured when bootstraping a version which is lower than the current package version, pulling the lower version from npm. 

Is it reasonable to say that versions that match the current version, preceded with a caret, should be symlinked during bootstrap. And that exact matches should copy the package across (or npm install). I'm sure this could be, yet another flag, or configurable lerna.json option.

So if I would like to re-add the symlink to a previously exact match version dependency I could just add the caret in the package.json in the package and re-boostrap.

I've tried to find similar issues, so I'm sure I'm either missing something or this is an unique usecase.

Thoughts?

**Comment by evocateur** [comment]
What you describe isn't really how lerna was intended to work. Whether or not you use `--exact` doesn't change the fact that lerna will always symlink local packages with a matching version. After publishing, the "current state of the package" is exactly what's on disk.

Yes, you can install non-matching versions of monorepo siblings, but that's not really meant to be a common part of the workflow. It's more of an escape hatch for packages that you don't have time to update to a new breaking API or somesuch.
