### ISSUE TITLE
lerna publish removes node_modules folders

### ISSUE THREAD

**Issue by Aurelsicoko** [lerna/lerna#929]
When I'm running this command `lerna publish --npm-tag=whateveryouwant`, the `node_modules` folders are deleted. It's pretty bad because some of my packages need them to be able to build an app for example before being published.

Moreover,[ the `node_modules` folder is ignored by npm](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) so I don't understand why this behavior has been implemented.

## Expected Behavior
Don't delete the `node_modules` folders when running `lerna publish`.

## Current Behavior
The `node_modules` folders are deleted during `lerna publish`.

## Your Environment

| Executable | Version |
| --- | --- |
| `lerna --version` | 2.0.0 |
| `npm --version`  | 5.3.0 |
| `node --version` | 8.2.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.5 |

**Comment by evocateur** [comment]
It would help if you could provide a sample repo to reproduce this, or a log of some kind. Definitely the `lerna.json`.

**Comment by Aurelsicoko** [comment]
@evocateur Here [the link of the repository](https://github.com/strapi/strapi). The version in the  `lerna.json` is not up to date because we are not using it anymore due to this issue. We developed many scripts to replace Lerna but this situation isn't optimal for us. FYI, when I tested to publish with `lerna`, the script that you can see in the repository to remove the `node_modules` folder in each package wasn't here so this issue cannot be caused by it.

**Comment by evocateur** [comment]
We can't fix something we can't reproduce. I personally have never experienced node_modules being deleted during hundreds of `lerna publish` executions, that makes literally no sense.
