### ISSUE TITLE
npm 5 not supported

### ISSUE THREAD

**Issue by bryzaguy** [lerna/lerna#938]
## Expected Behavior
Would be awesome if lerna worked with npm 5.

## Current Behavior
It *kind of* works today.  The problem is that each time I run bootstrap something is modifying the package-lock.json files in inconsistent ways.  Sometimes it removes the root level name and version from the package lock file.  Sometimes it breaks and leaves the package.json in a state where it only has a list of the dependencies and a package.json.lerna_backup file exists.

## Possible Solution
Something is clearly going on where potentially npm is watching modifications to the package.json and messing stuff up as lerna is modifying them.  Not totally sure.

## Steps to Reproduce (for bugs)
Honestly, each time I ran bootstrap I would get a different result.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0",
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```
</p></details>

## Context

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0 |
| `npm --version`  | 5.3.0 |
| `yarn --version` | 0.25.7 |
| `node --version` | 8.1.4 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.1.2 |

**Comment by nicojs** [comment]
For what its worth, the work around for us is to put package-lock.json files in .gitignore. That way you have the npm4 behavior ... kind of. Too bad npm@5 forces package-lock.json files down your throat with each `npm install`.

**Comment by brentertz** [comment]
You can alternatively add `package-lock=false` to an `.npmrc` file.

**Comment by tivac** [comment]
@brentertz You can, but you need a `.npmrc` for the root and each package.

https://github.com/lerna/lerna/issues/856#issuecomment-317462625

😓

**Comment by bryzaguy** [comment]
Thanks for the suggestions on making the package-lock files less of an issue. However, I want to have and use the package-lock files.

**Comment by evocateur** [comment]
While I agree that npm5 support in lerna could be improved, I use npm5 + lerna successfully every day.

**Comment by anfedorov** [comment]
@evocateur can you comment on how? I haven't looked into the issues yet, but some of our team has held off on updating (I switched to yarn, which is faster + has no issues). can try to look into what the issue was with npm if that helps.

**Comment by evocateur** [comment]
I use `--hoist` when bootstrapping and ensure all dependencies under `packages/*` are expressed identically in the root `package.json`. This effectively turns `lerna bootstrap --hoist` into a symlink-only operation, completely avoiding `npm install` under `packages/*`.

It's a bit more painful to update dependency versions (`npm up <pkg>` in the root and then manually copy the version specifier to any consumers), but at least it's easy to know when things are drifting out of date (`npm outdated` in the root) and completely avoids the nested lockfile issues.

I've been meaning to write some scripts to streamline this, possibly as a lerna subcommand (or plugin command), although I might just switch to yarn workspaces once they're more mature.

**Comment by evocateur** [comment]
(Also, as much as possible, I do all the build/test/etc stuff from the root, not many of my lerna-managed packages have `devDependencies` or lifecycle scripts of their own)

**Comment by redonkulus** [comment]
@evocateur This should definitely put on the website or somewhere as a best practice or common management approach. A subcommand to help keep versions consistent is something we had to hack together as well. Both would be much appreciated if lerna provided out of the box.

**Comment by jquense** [comment]
@evocateur just to be clear on your approach. You manually have your root package.json reflect the sum total of all the sub-packages package.jsons? So changing a dep requires changing it in at least two places?

**Comment by evocateur** [comment]
@jquense Yep, that's the current burden. It's worth it, for me, considering the advantages.

I've been noodling a `lerna hoist` subcommand that facilitates updating / removing / adding deps to variously filtered packages. I like the DX of [yarn workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/), but I also like staying in the root directory when developing...

**Comment by nealoke** [comment]
When I install a new package with `npm 5` it removes my symblinks created by `lerna bootstrap`, super annoying

**Comment by esprehn** [comment]
@evocateur This is a problem for us too, lerna doesn't seem to work with npm5. Not everyone can use --hoist, and currently lerna both changes the package-lock.json each time you bootstrap (adding or removing the dev flags or the package name) and the symlinks also don't seem to always work. Everything worked fine with npm3 though, It'd be really excellent if lerna could support the same workflow in npm5. :)

**Comment by evocateur** [comment]
3.0-alpha.0 works perfectly in npm5

**Comment by doug-wade** [comment]
Closing per https://github.com/lerna/lerna/issues/938#issuecomment-367554173
