### ISSUE TITLE
[Suggestion] npm-esque "scripts" e.g. prebootstrap, postbootstrap

### ISSUE THREAD

**Issue by AshCoolman** [lerna/lerna#941]
It would be nice to have something like [npm scripts](https://docs.npmjs.com/misc/scripts)

I can't see anything in the docs/issues for this explicitly

### Why not use npm scripts?

Sometimes the npm toolchain isn't enough for local development (e.g. [symlinks in react-native](https://github.com/facebook/metro-bundler/issues/1#issuecomment-317806397))

### Advantages

* More flexibility (local dev, ci envs)
* A _Right place_™ for lifecycle logic

### Disadvantages

* Beyond remit of mono repo orchestration & publishing?
* Assuming things play nice with npm simplifies the future

**Comment by evocateur** [comment]
There's nothing stopping folks from writing in their root `package.json`:
```json
  "scripts": {
    "prebootstrap": "do thing",
    "bootstrap": "lerna bootstrap",
    "postbootstrap": "do other thing"
  }
```
That will work with `npm run bootstrap` out of the box.

I'd rather focus on a cogent plugin API than rewrite npm scripts, if that makes sense?
