### ISSUE TITLE
Hoist does not understand 1.x syntax

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#944]
Hoist is treating dependencies like 4.x.x as they were different form 4.0.0 . This breaks in some way how npm works, which will consider both requirements as equivalent.

## Expected Behavior
I expect all packages with a version 4.x.x to be hoisted if the hoisted dependency is compatible. 

## Current Behavior
I'm getting messages like this:

```
lerna WARN EHOIST_PKG_VERSION "agent-integration" package depends on lab@^10.9.0, which differs from the hoisted lab@10.x.x
lerna WARN EHOIST_PKG_VERSION "case-base-dao" package depends on code@^4.x.x, which differs from the hoisted code@^4.0.0.
```

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0",
  "packages": [
    "src/*"
  ],
  "hoist": true,
  "changelog": {
    "repo": "****",
    "labels": {
      "bug": "Bug fix",
      "cleanup": "Housekeeping",
      "enhancement": "Enhancement",
      "Docu": "Documentation",
      "pkg#case-auth": "Case-auth"
    },
    "cacheDir": ".changelog"
  },
  "version": "independent"
}
```
</p></details>

**Comment by evocateur** [comment]
If you specify the dependency range identically everywhere, does it work?

**Comment by danielo515** [comment]
Yes, in that case it works

**Comment by evocateur** [comment]
Ok, that's good. The hoist algorithm emphasizes an identical range specifier to ensure the accuracy of what is hoisted.

In the `^4.x.x` vs `^4.0.0` case, it wouldn't be harmful (although using carets with `.x` wildcards is a bit strange). However, `^10.9.0` cannot satisfy `10.x.x` in all cases, and is thus warned about (`10.x.x` could resolve to `10.8.0`, for example, and that doesn't satisfy `^10.9.0`).

The situation right now managing the _upgrade_ of hoisted dependency versions is very painful (manual, error-prone copy+paste in all affected `package.json` files). I hope to ease this pain in the near future with some sort of subcommand API.

**Comment by danielo515** [comment]
Hello @evocateur ,

You're right about the syntax `^10.x.x` is not very common. It is from an old time and I want to change it to just 10.x.x or just 10.x .
About the resolution, I think it should always resolve to the higher version on the repo. For example, if you have 3 packages (like one of my cases) that requires a version 10.x and a package that requires 10.9 then you should resolve to that package. Of course this will require some analysis and logic, but would be much more comfortable for the end user than managing the versions manually.

Regards

**Comment by danielo515** [comment]
Hello,

This report may deserve it's own issue, but I'm reporting it here to avoid issues pollution. Today I just realized that lerna does not understand neither when you use the caret `^` for versioning, even when they resolve to the same version.

Here is a log extract:

```
lerna WARN EHOIST_PKG_VERSION "case-alerts-inactivity-service" package depends on lab@14.1.1, which differs from the hoisted lab@^14.1.1.
lerna WARN EHOIST_PKG_VERSION "case-alerts-evaluator" package depends on case-kpi@^0.7.0, which differs from the hoisted case-kpi@0.7.0.
lerna WARN EHOIST_PKG_VERSION "case-alerts-notification-info" package depends on case-kpi@^0.7.0, which differs from the hoisted case-kpi@0.7.0.
```

**Comment by evocateur** [comment]
In that particular instance, it seems to be the disjoint between exact and caret ranges. The warnings are meant to highlight disparities between hoisted range specifiers, though the wording is a bit confusing. The hoist resolution still works.
