### ISSUE TITLE
Can't use packages in the parent folder

### ISSUE THREAD

**Issue by xareelee** [lerna/lerna#945]
## Expected Behavior

I move the `packages/` folder to the parent folder, and change the lerna.json

from 

```js
// lerna.json
{
  "packages": [
    "packages/*"
  ],  
}

// file system
app/
 |- packages/
 |    |- xxx/
 |- lerna.json
 |- package.json
 |- node_modules/
```

to

```js
// lerna.json
{
  "packages": [
    "../packages/*"
  ],  
}

// file system
repo/
 |- packages/
 |    |- xxx/
 |- app/
     |- lerna.json
     |- package.json
     |- node_modules/
```

but this doesn't work.

When I try to build inside the `app/` project which imports the module from lerna, it shows an error:

```
// where xxx is the module from lerna in the `packages/` folder
Unable to resolve module 'xxx' from '<path_to_source>': Module does not exist in the module map
```

## Context

I'm developing React Native apps, and I want to use monorepo to share modules for multiple React Native apps.

I simply move the `packages/` to the parent folder, and change the corresponding `lerna.json`, but it doesn't work.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0 |
| `npm --version`  | 5.3.0 |
| `yarn --version` | 0.27.5 |
| `node --version` | 8.1.4 |

| OS | Version |
| --- | --- |
| macOS | 10.12.5 |

**Comment by evocateur** [comment]
`lerna.json` must always be an ancestor of any configured `packages` directory. It doesn't _have_ to be at the root of the repository, but that's by far the most common pattern, and avoids a lot of confusion.

You can certainly have other directories beneath `lerna.json`'s location. You can even configure multiple `packages` locations, if you want, and they'll all be able to consume other local packages via `lerna bootstrap` symlinks.
