### ISSUE TITLE
Lerna seems to not understand when to publish

### ISSUE THREAD

**Issue by krainboltgreene** [lerna/lerna#947]
I'm trying to publish and it thinks all of my packages have been updated!

## Expected Behavior
Just publish those that have changed

## Current Behavior
Everything.

```
| npx lerna publish
lerna info version 2.0.0
lerna info versioning independent
lerna info Checking for updated packages...
lerna info Comparing with @unction/allobjectp@1.0.7.
? Select a new version for @unction/allobjectp (currently 1.0.7) Patch (1.0.8)
? Select a new version for @unction/allp (currently 1.0.4) Patch (1.0.5)
? Select a new version for @unction/always (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/append (currently 1.0.3) Patch (1.0.4)
? Select a new version for @unction/appendm (currently 1.0.4) Patch (1.0.5)
❯ Patch (1.0.5)
krainboltgreene on laurelandwolf-macbookpro.local in unction.js working on core
| npx lerna diff @unction/appendm
lerna info version 2.0.0
lerna info versioning independent
modified: package/appendM/package.json
@ package.json:3 @
{
  "name": "@unction/appendm",
  +"version": "1.0.5",
  -"version": "1.0.4",
  "description": "Takes an item and an array, appends (MUTATION) the original array with the item",
  "keywords": [
    "unction",
```

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "lerna": "2.0.0",
  "packages": [
    "package/*"
  ]
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0 |
| `npm --version`  | 5.3.0 |
| `node --version` | 7.7.2 |

**Comment by willyboy** [comment]
Seeing the same with npm version 3.10.10

**Comment by evocateur** [comment]
So that patch version selection for the `appendM` package was the last output from `lerna publish`? And no `lerna-debug.log` output?

**Comment by krainboltgreene** [comment]
I'm just showing you that lerna wants to update everything and why lerna
wants update everything. Since I can't skip updates right now this also
means I'm stuck.

**Comment by evocateur** [comment]
Okay, that means one of two things:
1. There are no git tags that lerna can see, so it seems to be assuming this is the "first publish". (very odd, since you've clearly published before)
2. There are non-ignored changes in every package since the most recent tag.

Could this possibly be due to a side-effect of `npx`?

**Comment by jbidston** [comment]
I was having a similar issue, and was running Lerna with npx.

As you suggested, it appears to be when running with npx. 

I installed Lerna globally, published (all packaged) but then subsequent changes were picked up correctly.
