### ISSUE TITLE
[Feature] Skip certain package from publish but include it in the rest of the flow

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#953]
This is a feature request.
It will be very cool if you can mark certain package to be excluded from publish to npm, but it is still getting included in the rest of the flow. This means version bump, git tag, inter-dependency management etc.
This is useful if some of your packages does not need to be published, (ej, they contain a service) but you are able to keep them in sync with the rest of packages as they evolve. 

Many thanks and regards

**Comment by evocateur** [comment]
Yep, just add `"private": true` to the package's `package.json` file, and it will do exactly that.

**Comment by danielo515** [comment]
Simple solution. thanks I'll check it out

**Comment by milesj** [comment]
The `private: true` approach seems to have broken with v3.

**Comment by evocateur** [comment]
That’s news to me, as someone who uses lerna 3 and `”private”: true` daily.

**Comment by milesj** [comment]
This was from 5 minutes ago:

```
lerna info version 3.0.0-beta.21
lerna info versioning independent
lerna info Checking for updated packages...
lerna info Comparing with emojibase-data@2.2.0.
? Select a new version for emojibase (currently 1.5.0) Minor (1.6.0)
? Select a new version for emojibase-data (currently 2.2.0) Minor (2.3.0)
? Select a new version for emojibase-generator (currently 0.0.0) (Use arrow keys)
❯ Patch (0.0.1) 
  Minor (0.1.0) 
  Major (1.0.0) 
  Prepatch (0.0.1-0) 
  Preminor (0.1.0-0) 
  Premajor (1.0.0-0) 
  Prerelease 
  Custom 
```

And the package: https://github.com/milesj/emojibase/blob/master/packages/generator/package.json#L2

**Comment by milesj** [comment]
I downgraded to 2.11 and the problem still persists. Maybe something else is going on.

```
lerna info version 2.11.0
lerna info versioning independent
lerna info ignore [ '*.md' ]
lerna info Checking for updated packages...
lerna info Comparing with emojibase-data@2.2.0.
lerna info Checking for prereleased packages...
? Select a new version for emojibase (currently 1.5.0) Minor (1.6.0)
? Select a new version for emojibase-data (currently 2.2.0) Minor (2.3.0)
? Select a new version for emojibase-generator (currently 0.0.0) 
  Patch (0.0.1) 
  Minor (0.1.0) 
  Major (1.0.0) 
  Prepatch (0.0.1-0) 
❯ Preminor (0.1.0-0) 
  Premajor (1.0.0-0) 
  Prerelease 
  Custom 
```

I have to use `--ignore=emojibase-generator` to get this working at the moment.

**Comment by evocateur** [comment]
https://www.npmjs.com/package/emojibase-generator is a 404, so it’s working as intended. Private packages are still versioned in git, they’re just not published to a registry. Literally how it has always worked with lerna.

**Comment by milesj** [comment]
Ah, gotcha. Thought it would just skip the version part (as it's completely unnecessary IMO).

**Comment by evocateur** [comment]
It’s necessary because of how lerna associates local packages by name _and_ version.
