### ISSUE TITLE
provide some kind of Lerna-aware Yarn wrapper to prevent accidentally installing packages over symlinks

### ISSUE THREAD

**Issue by seansfkelley** [lerna/lerna#957]
If you try to `yarn add` in a Lerna monorepo when you have symlinks created by `lerna bootstrap`, Yarn will either

1. Delete your symlinks and replace them with published packages that fit the version requested if such exist, or
2. Die.

Lerna already deals with this problem during bootstrap by rewriting `package.json` and stashing `package.json.lerna_backup`. Yerna, my Lerna-like from a while ago before Lerna had Yarn support, also [includes a binary called `yarnhack`](https://github.com/palantir/yerna#yarnhack) that wraps Yarn to do just this kind of `package.json` munging on demand.

I still use `yarnhack` with Lerna, since (on every package add/remove!) I would otherwise have to either (1) manually add the version to `package.json` then `lerna bootstrap` or (2) `yarn add` the thing, then `lerna bootstrap` afterwards to undo what it did (which is considerably worse -- it cna fail depending on the published-ness and versions of the packages and will add local dependencies to `yarn.lock` where you probably don't want them if it does succeed).

It would be nice if Lerna came with a companion, Lerna-aware Yarn wrapper so I could tell my teammates "just use this thing instead of Yarn in all cases" rather than "do (1) above but under no circumstances do (2) and if you mess it up weird things might happen, here are some docs if that happens".

**Comment by QuentinFchx** [comment]
Not sure if 100% related to #448, but if the whole "update each package's dependencies" flow could be fixed(^yarn symlinks)/improved/documented that would be awesome.

**Comment by evocateur** [comment]
I think [Workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/) are the new jam for bootstrapping Lerna monorepos (if you're using yarn)?

**Comment by evocateur** [comment]
[`lerna add`](https://github.com/lerna/lerna#add) (new in v2.5.0) addresses this, as well as `yarn <workspace> add <dependencyName>` (the docs are not very helpful, had to dig into source code to figure it out).
