### ISSUE TITLE
I have too many packages

### ISSUE THREAD

**Issue by krainboltgreene** [lerna/lerna#959]
https://travis-ci.org/krainboltgreene/unction.js?utm_source=email&utm_medium=notification

What are good options?

**Comment by evocateur** [comment]
I would move `lerna bootstrap` out of the `postinstall` lifecycle and into `prebuild`. In my experience, `postinstall` is a very error-prone lifecycle for things such as `lerna bootstrap` that might call `npm install` in places you don't expect (such as the root, which causes an endless loop right now).

**Comment by krainboltgreene** [comment]
While I've done that I've also moved to repo-per-package (which also means travis-per-package) and into my own tooling.
