### ISSUE TITLE
lerna run with --loglevel=silent is a little too silent

### ISSUE THREAD

**Issue by achingbrain** [lerna/lerna#974]
I'm trying to set up a CI build using lerna.  Our project has several modules that may or may not have a `test` script.  The ones that do have a `test` script use `ava`, and we want them to output `tap` which we then pipe to `tap-merge` and finally `tap-xunit`.

If I have a test that fails, running this from the package directory works as expected:

```sh
$ npm run test --silent -- --tap
TAP version 13
# unit › handlers › kittens › it should send a kitten
not ok 1 - unit › handlers › kittens › it should send a kitten
  ---
    name: AssertionError
    assertion: is
    operator: ===
    values:
      'Actual:': 'true'
      'Must be strictly equal to:': 'false'
    at: 'Test.fn (test/unit/handlers/kittens.js:16:10)'
  ...
# integration › kittens › GET /kittens should return a kitten
ok 2 - integration › kittens › GET /kittens should return a kitten

1..2
# tests 2
# pass 1
# fail 1
```

If I run this via lerna from the root directory I get all sorts of npm noise:

```
$ lerna run test -- -- --tap
lerna info version 2.0.0
lerna info versioning independent
lerna ERR! test Errored while running script in 'package-with-failing-test'
lerna ERR! execute Error: Command failed: npm run test -- --tap
lerna ERR! execute 
lerna ERR! execute npm ERR! Darwin 16.6.0
... snip ...
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'npm run test -- --tap',
lerna ERR! execute   timedOut: false }
```

So I pass the silent flag:

```
$ lerna run test -- --silent -- --tap
lerna info version 2.0.0
lerna info versioning independent
lerna ERR! test Errored while running script in 'package-with-failing-test'
lerna ERR! execute Error: Command failed: npm run test --silent -- --tap
lerna ERR! execute TAP version 13
lerna ERR! execute # unit › handlers › kittens › it should send a kitten
lerna ERR! execute not ok 1 - unit › handlers › kittens › it should send a kitten
lerna ERR! execute   ---
lerna ERR! execute     name: AssertionError
lerna ERR! execute     assertion: is
lerna ERR! execute     operator: ===
lerna ERR! execute     values:
lerna ERR! execute       'Actual:': 'true'
lerna ERR! execute       'Must be strictly equal to:': 'false'
lerna ERR! execute     at: 'Test.fn (test/unit/handlers/kittens.js:16:10)'
lerna ERR! execute   ...
lerna ERR! execute # integration › kittens › GET /kittens should return a kitten
lerna ERR! execute ok 2 - integration › kittens › GET /kittens should return a kitten
lerna ERR! execute 
lerna ERR! execute 1..2
lerna ERR! execute # tests 2
lerna ERR! execute # pass 1
lerna ERR! execute # fail 1
lerna ERR! execute 
lerna ERR! execute 
... snip, stack trace ...
lerna ERR! execute   cmd: 'npm run test --silent -- --tap',
lerna ERR! execute   timedOut: false }
```

Almost there, just need to get rid of the `lerna ERR! execute...` bits.  `--silent` made npm suppress it's own output, only showing the output of the script itself and lerna has a `--loglevel` option that mirrors npm's so let's use that:

```javascript
$ lerna run test --loglevel=silent -- --silent -- --tap
```

Now I have no output at all!

## Expected Behavior

I expect the `loglevel` flags passed to lerna to make it behave in the same way that `npm` would with the same flags.  That is, `silent` would show the output of the scripts being run but not add any extra output to stdout or stderr.

## Current Behavior

`--loglevel=silent` causes all output for a package to be suppressed when a script in a package returns an exit code that isn't 0.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0 |
| `npm --version`  | 3.10.10 |
| `yarn --version` | n/a |
| `node --version` | v6.9.1 |

| OS | Version |
| --- | --- |
| Mac OS X Sierra | 10.12.5 |

**Comment by evocateur** [comment]
I am definitely in favor of matching npm's behaviour here. Our error logging currently leaves something to be desired, as you've seen.

One potential wrinkle here is _where_ `--silent` is passed in the args. In any case, I agree the logging needs some tweaking.

**Comment by jasoncarmona** [comment]
This would definitely help the process of running scripts at the root level when they are chaining calls with `lerna run script-name` inside the packages.
