### ISSUE TITLE
When symlink in toolkit that used lerna, is that allow consumer project to use npm link @scope/component?

### ISSUE THREAD

**Issue by minmingsheng** [lerna/lerna#975]
I am assuming when lerna do symlink, it already run `npm link` in each package, so technically I run `npm link @scope/component` in consumer project should work, but it seems not?
I checked the source code, can't see anything on `npm link`, seems it is using another strategy instead of `npm link` or hiding somewhere?

So if it doesn't exist, any alternative way to achieve that I can npm link @cope/component in another project locally except manually running `npm link` in each package that might conflict with lerna symlink?

**Comment by evocateur** [comment]
Lerna does not use `npm link` internally, as you've noted. After you've run `lerna bootstrap`, there's nothing stopping you from going into a package directory and running `npm link`.

**Comment by veeramarni** [comment]
one problem, I noticed after running `npm link` on the specific package it loads all the dependencies under packages `node_modules` directory. I use `--hoist` to avoid downloading dependencies under the individual package. Is there a way we can run `link` without all dependencies under node_modules.

**Comment by evocateur** [comment]
Yeah, I've hit this too when hoisting. `yarn link` seems to avoid that build step, but that doesn't help when using npm.

A workaround I've used is to just `rm -rf node_modules` in the directory you just linked, then run `lerna bootstrap --scope <linkedPackage>` from the root to restore the sibling symlinks and such. It's not ideal, but it works very well after that.
