### ISSUE TITLE
Lerna version mismatch

### ISSUE THREAD

**Issue by Havunen** [lerna/lerna#984]
Lerna is published to npm as version 2.1.0, but internally its reporting version: `2.0.0-rc.5`

steps to reproduce:
1 - `npm init`
2 - `npm i -g lerna`
3 - `npm i --save-dev lerna`

`lerna --version` = 2.0.0-rc.5 (wrong?)
`lerna init` = 
```
lerna info version 2.0.0-rc.5
lerna info Initializing Git repository
lerna info Updating package.json
lerna info Creating lerna.json
lerna success Initialized Lerna files
```

Shouldn't the version be 2.1.0 ?

**Comment by evocateur** [comment]
Your `$PATH` seems to have an old version of `lerna` installed.

```sh
$ npm view lerna dist-tags
{ latest: '2.1.0' }
$ npm -g i lerna
+ lerna@2.1.0
added 276 packages in 6.547s
$ lerna -v
2.1.0
$ lerna init
lerna info version 2.1.0
lerna info Updating package.json
lerna info Creating lerna.json
lerna success Initialized Lerna files
```

What version of node/npm/OS are you using?

**Comment by Havunen** [comment]
Its node 8.4.0 npm 5.3.0 and Ubuntu 16.0.4LTS. I fixed it by reinstalling node and all packages. Sorry for the noise.
