### ISSUE TITLE
Push to git before publishing on npm

### ISSUE THREAD

**Issue by simondel** [lerna/lerna#986]
Because Lerna publishes on npm before it pushes to the remote git repo, you can end up in a situation where you have releases in npm but not in your remote git repo. An example of this would be an automated release using Travis that uses an invalid GitHub token and thus can't push to github. This would also be helpful if only some of the npm packages were pushed. 

## Expected Behavior
Publish the changes/tags to the remote git repository before publishing the npm packages.

## Current Behavior
npm packages are pushed before the git changes are pushed. If any npm package publish goes wrong or if the git push goes wrong, no commits/tags will be available on the remote git repository.

## Possible Solution
Push to git first.

**Comment by smrq** [comment]
I've ended up in situations where packages got pushed to npm but then failed to end up in git altogether, which was a fun rollback to deal with.  Git first would be a lot less scary.

**Comment by erquhart** [comment]
Just wanted to chime in on what a big deal this is. Here's what just happened on the Netlify CMS repo:

1. Ran our publish script.
2. Ours takes a while, so I reviewed and merged a PR while waiting.
3. Releases were published to npm.
4. Push failed (obviously).

My tags are now in stone, so the only way to fix this was to remove protections from master, cherry pick the merged work, and _force push to master_.

So I won't merge PR's during publishing anymore, but we have other maintainers that could merge a PR at any time, making publishing sort of an unsafe operation.

Just wanted to add some additional perspective, hope it helps outline the problem a little better.

**Comment by tkissing-work** [comment]
We just had the same happen in our repo. About a dozen packages published (by Jenkins) and the commit/tag are lost because someone merged to master in the meantime. 
We use Jenkins to do the release (developers can't even push to master) on other, single-package repositories and there the order is `npm version`, `git push`, `npm publish`. If `git push` fails, nothing has happened yet. If `npm publish` fails, it's easy to recover: check out the tag, publish again.

**Comment by evocateur** [comment]
As soon as I get around to publishing what's currently on `master` (split `lerna publish` into `lerna version` + `lerna publish`), this will effectively be fixed.

**Comment by evocateur** [comment]
https://github.com/lerna/lerna/releases/tag/v3.0.0
