### ISSUE TITLE
[Feature] add logger, log-levels etc

### ISSUE THREAD

**Issue by cdaringe** [lerna/lerna#99]
how would folks feel about adding a logger package in and integrating it into the current command set?

**Comment by thejameskyle** [comment]
What do you mean by this

**Comment by cdaringe** [comment]
`lerna some-action --low-level=verbose/warn/error`  .  I wanted verbose output to see what's going on behind the scenes

**Comment by joscha** [comment]
we could use https://www.npmjs.com/package/debug - that way you can control what is logged with a glob and also redirect it if need be.

**Comment by thejameskyle** [comment]
Added in #367 waiting on publish, but gonna close this
