### ISSUE TITLE
Installing a new dependencies in projects with private dependencies that are not in NPM

### ISSUE THREAD

**Issue by MiguelCrespo** [lerna/lerna#998]
Hi! Thank you for making this tool, I have a lerna project that uses some private repositories (Also lerna packages, that are not in NPM),  and when I try to add a new npm dependency to some of them, by running 

``npm/yarn install someDependency``

I get an error telling me 
``Couldn't find package "someLocalPackage" on the "npm" registry.```

I get along it removing the local dependency that is not in NPM from package.json, then install the new dependency and then adding back the local lerna package, but It is really annoying

## Expected Behavior
It should just install the new dependency from NPM and ignore the local lerna dependency

## Current Behavior
It throw an error saying 

``Couldn't find package "someLocalPackage" on the "npm" registry.``

## Possible Solution
Maybe find a way to tell npm or yarn to ignore the installation of x dependencies because we're using symlinks for them?

## Steps to Reproduce (for bugs)
1. Create at least two packages inside your lerna project
2. Add package1 to the package.json of the other one
3. Try running yarn add react

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.1.0 |
| `npm --version`  | 5.3.0 |
| `yarn --version` | 0.27.5 |
| `node --version` | v8.3.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.6 |

**Comment by evocateur** [comment]
This is one of the drawbacks of lerna: You can't use `npm install` in one of the managed package directories (`packages/*`). Generally speaking, you stay in the root of the repository when developing in a lerna monorepo, not the package subdirectory.

For now, it's best to just modify the package.json directly and run `lerna bootstrap` from the root. It will do all the install stuff for you, avoiding the problems you've encountered. If you want to avoid running bootstrap for all the other (non-affected) packages, you can pass a scope: `lerna bootstrap --scope my-target-package-name`

**Comment by Inkdpixels** [comment]
@evocateur This is actually something that I thought about as well when working with lerna and I think it hinders developers the most from bring really productive.

What I thought about to solve this, is to add a new CLI command, e.g.

```sh
lerna add <args-to-npm-client>

# or written out
lerna add --scope=my-package -- foo@2.0.1 --dev
```

which will basically just propagate everything to npm/yarn and once finished re-links all cross-deps of the mono-repo packages.

Of course this Commando needs to support the `--scope` Option to only installiert something in one/multiple packages. 

What do you think, is this something that one can contribute to lerna?

**Comment by evocateur** [comment]
@Inkdpixels I've been noodling about something similar, recently. We'd also want to support `upgrade` and `remove`/`rm`. All these commands would support the package filtering flags (`--scope`, `--ignore`, `--since`, etc).

```
lerna add <packageName>[@<version>] [--dev]
lerna upgrade <packageName>[@<version>]
lerna remove <packageName>
```

I don't think want to force passing direct npm args after `--`, as we won't necessarily be doing that exactly (probably just direct edits of the scoped `package.json` files). Instead, you'd automatically run a similarly-scoped `lerna bootstrap` after any of these commands to ensure the resulting package state was correct.

**Comment by MiguelCrespo** [comment]
I totally agree that we need a way to add/upgrade/remove npm packages for packages in the lerna way and I find the approach @evocateur suggested simple and it will work

And as @Inkdpixels said is this something that one can contribute to lerna?

Because I can work on this

**Comment by evocateur** [comment]
By all means, please do!

**Comment by marionebl** [comment]
I opened a PR that implements `lerna add`, which works by direct manipulation of `package.json` and executes `BootstrapCommand` on changed packages. 

I added lots of usage examples that should illustrate some of the design choices, e.g.:
* Fail for package not in local packages
* Fail for version ranges not satisfiable locally
* Warn about packages not installing themselves
* Do not bootstrap when no packages were changed

**Comment by iansu** [comment]
🎉 Any idea when this will be released?

**Comment by evocateur** [comment]
Tomorrow morning (PDT), at the earliest. I nuked my brain today getting the integration tests to stop flaking on Windows.

**Comment by kachkaev** [comment]
Temporary workaround until `remove` is implemented:

```
lerna exec --concurrency=1 yarn remove something
```

Helps when installing something with `lerna add` by accident. The command crashes for me without `--concurrency=1`.

**Comment by doug-wade** [comment]
@kachkaev Do you have the lerna-debug.log and npm-debug.log or the error or anything?  I'm curious to know why its crashing; iiuc it shouldn't be.

**Comment by kachkaev** [comment]
@doug-wade sure

```
yarn lerna add left-pad
yarn lerna exec --concurrency=1 yarn remove left-pad
```
👌 

---

```
yarn lerna add left-pad
yarn lerna exec yarn remove left-pad
```
<details>
<summary>error log</summary>
<pre>
0 silly input [ 'yarn', 'remove', 'left-pad' ]
1 silly flags { _: [ 'exec' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   command: 'yarn',
1 silly flags   args: [ 'remove', 'left-pad' ] }
2 verbose rootPath /path/to/root
3 info version 2.10.2
4 silly existsSync /path/to/root/VERSION
5 info versioning independent
6 silly initialize attempt
7 silly initialize success
8 silly execute attempt
9 error exec Errored while executing 'yarn remove left-pad' in 'block-attributes'
10 error execute callback with error
11 error Error: Command failed: yarn remove left-pad
11 error     at Promise.all.then.arr (/path/to/root/node_modules/lerna/node_modules/execa/index.js:236:11)
11 error     at <anonymous>
</pre>
</details>

The command executes well for 4 out of 7 packages (the ones that have no own internal dependencies) and then lerna crashes.
